### ISSUE TITLE
Allow commands to define their own bash completions

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#1006]
In #212 we introduced generic support for `<file>` positional args and for associative args.

The next step would be to allow individual commands to define their own completions.

For example, `wp plugin activate ` could suggest the slugs for the installed plugins.

The only drawback would be that completions wouldn't be as snappy, since we'd have to load WordPress.

**Comment by danielbachhuber** [comment]
Punting on this as I don't think the cost of loading WordPress is worth the benefit.
