### ISSUE TITLE
Let users know when there's a new version available

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1011]
From https://github.com/wp-cli/wp-cli/pull/1008#issuecomment-34879316

We'd need some phone home mechanism, and could display this information on `wp help`.

**Comment by danielbachhuber** [comment]
@nyordanov do you still feel the need to make this automatic, and obtrusive, or are you happy with `wp cli check-update`?

**Comment by danielbachhuber** [comment]
Actually, I really like how Oh My ZSH does this. Even better: we show some indicator of release notes on update.

**Comment by nyordanov** [comment]
Isn't Oh My ZSH obtrusive? It prevents you from doing anything until you state whether you want to update.

This won't be a problem if we can reliably detect if WP-CLI is used in a script or in an interactive shell, but can we do this from a Phar?

**Comment by danielbachhuber** [comment]
> Isn't Oh My ZSH obtrusive? It prevents you from doing anything until you state whether you want to update.

Yes. We can limit the impact by only executing on the informational commands like `wp`, `wp help` or `wp <command> help`. I think this is the best way to assume that a human is behind the operation, not a script.

**Comment by danielbachhuber** [comment]
@nyordanov Would you like to pick this up? I think it could be a cool addition to v0.20.0, and will permit faster release cycles.

**Comment by nyordanov** [comment]
@danielbachhuber I would, but after May 20. When is v0.20.0 scheduled to be released?

**Comment by danielbachhuber** [comment]
> I would, but after May 20. When is v0.20.0 scheduled to be released?

That'll be fine. Probably looking at mid-July or so for v0.20.0

**Comment by nyordanov** [comment]
I'm sorry I'm terribly late with this - other things took priority. Please check #2223.

**Comment by danielbachhuber** [comment]
> I'm sorry I'm terribly late with this - other things took priority.

No worries!
