### ISSUE TITLE
WP-CLI with a wordpress in subdirectory (and wp-content in root)

### ISSUE THREAD

**Issue by gizburdt** [wp-cli/wp-cli#1024]
Hi,

My environment looks like this:
- wordpress/
- wp-content/
- index.php
- wp-config.php
- wp-cli.phar

How can I let wp-cli install plugins in wp-content/plugins and not in wordpress/wp-content/plugins. And maybe also to install wp-config.php in root and not in wordpress/

Thanks! :)

**Comment by jorgeorpinel** [comment]
Not exactly the best solution in my mind. Anyone finding this issue may want to take a look at https://github.com/wp-cli/wp-cli/issues/137 instead.
