### ISSUE TITLE
Set up docs for framework code

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#1045]
We have docs for commands and for config flags, but nothing for the framework code.

Tasks:

* [ ] Add inline docs for all classes and methods, particularly for stuff in the `WP_CLI\Dispatcher` namespace.
* [ ] Display them on wp-cli.org, using phpDocumentor or some other tool

**Comment by danielbachhuber** [comment]
First pass at an internal docs page: http://wp-cli.org/docs/api/

Good, but not great.

**Comment by danielbachhuber** [comment]
This is in pretty good shape now. Closing, and we can open subsequent issues as needed.
