### ISSUE TITLE
core config --extra-php

### ISSUE THREAD

**Issue by gizburdt** [wp-cli/wp-cli#1046]
Hi,

Not sure how this works. I would like to set the content_dir:

```
php wp-cli.phar core config --dbname=conductor --dbuser=root --dbpass=root --dbhost=localhost --dbprefix=wp_ --extra-php <<PHP define('WP_CONTENT_DIR', 'path/to/dir'); PHP
```

But when I run this command, my terminal goes in PHP mode (I think). So how does this work exactly?

Thanks! :)

**Comment by oviliz** [comment]
In the command line as sudo, where I should put the --allow-root?
```
wp core config --extra-php <<PHP
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
PHP --allow-root
```

**Comment by scribu** [comment]
Anywhere before `<<PHP`.

**Comment by oviliz** [comment]
Thank you!

**Comment by mattyhead** [comment]
This is a bit late to chime in, but you can also do:
echo "define( 'WP_DEBUG', true);" | wp core config --extra-php [other stuff]

**Comment by planetahuevo** [comment]
The solution is this one: 
https://github.com/wp-cli/wp-cli/issues/1268

Add "=" at the end and problem solved for me. 
--extra-php="STRING"

`wp core config --dbname=test --dbuser=root --dbpass=root --dbhost=localhost --extra-php="define('WP_DEBUG',true);\n"
`

**Comment by onetrev** [comment]
Thanks @planetahuevo that worked nicely for me! I had to use this solution for using WP CLI in Windows Powershell because `<<PHP` causes an error.

Only thing for me is the new line tag `\n` showed up as plain text so I had to remove it. Would be cool if you could get the new line in there still, but at least it works!
