### ISSUE TITLE
wp scaffold plugins-test should allow for mu-plugins

### ISSUE THREAD

**Issue by wpsmith** [wp-cli/wp-cli#1083]
Currently `wp scaffold plugin-tests pluginname` assumes plugins directory as it should. However, shouldn't it also contain a parameter to redirect to mu-plugins?

**Comment by lgellert** [comment]
Just ran into this as well...  many customized sites use mu-plugins, . I guess I'll make the directory it wants in /plugins/ then move everything it generates into /mu-plugins/.   Rather than a flag, it would be delightful if it would auto-detect this scenario.

**Comment by danielbachhuber** [comment]
> Rather than a flag, it would be delightful if it would auto-detect this scenario.

@lgellert Can you answer this question?

> Could you give an example of a plugin that belongs (not merely can exist) in the mu-plugins directory, which would also benefit from unit tests?

**Comment by lgellert** [comment]
Case in point, the custom plugin I'm currently writing for a high end Wordpress development shop.

It is required to live in mu-plugins so it does not appear in the plugins list and is automatically loaded. It has classes containing business logic that will benefit from unit tests.

**Comment by danielbachhuber** [comment]
In #1764, you'll be able to specify `--dir=<dirname>` to scaffold plugins (or just plugin tests) to arbitrary directories.

**Comment by lgellert** [comment]
Thank you sir!
