### ISSUE TITLE
wp-cli, php errors [using cgi-fcgi binary]

### ISSUE THREAD

**Issue by gthb1** [wp-cli/wp-cli#1085]
Hi,

WP-CLI seems awesome, just need to get it to work!

There are php errors coming up:

```
PHP Warning:  proc_open(): Descriptor item must be either an array or
a File-Handle in phar:///usr/bin/wp/php/commands/help.php on line 96
X-Powered-By: PHP/5.4.25
Content-type: text/html

<br />
<b>Warning</b>:  proc_open(): Descriptor item must be either an array
or a File-Handle in <b>phar:///usr/bin/wp/php/commands/help.php</b> on
line <b>96</b><br />
PHP Warning:  proc_close() expects parameter 1 to be resource, boolean
given in phar:///usr/bin/wp/php/commands/help.php on line 96
<br />
<b>Warning</b>:  proc_close() expects parameter 1 to be resource,
boolean given in <b>phar:///usr/bin/wp/php/commands/help.php</b> on
line <b>96</b><br />
```

and I have no idea why.

What must be done to fix this?

Many thanks in advance and kind regards.

**Comment by anibalardid** [comment]
> Well, one way would be to create an alias in your `~/.bash_profile`:
> 
> ```shell
> alias wp='/usr/bin/php-cli /FULL/PATH/TO/wp-cli.phar'
> ```
> 
> After you've added it and ran `source ~/.bash_profile`, when you run `wp --info`, it should show the path to php-cli.

something similar works for me:
alias wp='/usr/local/lsws/lsphp72/bin/php /root/wp-cli.phar --allow-root'

lsphp72, 73 or what you want
and /root/wp-cli.phar or directory that you want
