### ISSUE TITLE
Retain ascii table formatting

### ISSUE THREAD

**Issue by dsawardekar** [wp-cli/wp-cli#1102]
I'm working on a Vim plugin for WordPress that integrates with WP-CLI. Certain `wp-cli` commands like `wp plugin list` return Ascii table formatted output. When I run these commands through Vim, with the `system()` call, the Ascii formatting gets lost. This happens even when I explicitly specify the `--format=table` option.

In other tests I noticed that the formatting also gets lost when piping to `less` or redirecting to a file. It seems there are conditionals that alter output based on the type of output stream wp-cli is writing to.

Is there a way to preserve the table formatting?

Thanks.

**Comment by lkraav** [comment]
To clarify for people googline, the solution is `SHELL_PIPE=0 wp post list`

**Comment by toddr** [comment]
I'm glad I found `SHELL_PIPE`. I REALLY wish `--json` was an option for `options list`

**Comment by danielbachhuber** [comment]
> I REALLY wish `--json` was an option for `options list`

@toddr Do you mean `wp option list --format=json` ?

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
