### ISSUE TITLE
wp core download --locale=nl seems not to work.

### ISSUE THREAD

**Issue by byordereurope** [wp-cli/wp-cli#1117]
wp core download --locale=nl
OR
wp core download --locale=nl_NL

Seems to just install the english version.
I had to download the package from nl.wordpress.org to get the dutch version

Also the next errors popped up...

PHP Warning:  copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/commands/core.php on line 142

Warning: copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/commands/core.php on line 142
Downloading WordPress 3.8.2 (nl_NL)...

**Comment by jason404** [comment]
I've never tried installing WordPress using wp-cli before,  but have updated it many times.

This is not working:
`$ wp core download --locale=en-GB`
`Error: The requested locale (en-GB) was not found.`

This usually works fine:
`wp core update --locale=en-GB`

**Comment by danielbachhuber** [comment]
@jason404 The correct command is:

```
salty-wordpress ➜  en-gb  wp core download --locale=en_GB
Downloading WordPress 4.2.4 (en_GB)...
Success: WordPress downloaded.
```

Note: `en_GB` with an underscore, instead of a dash.

**Comment by jason404** [comment]
@danielbachhuber  Ah thanks.  

My `.bash_history` seems say that I have been using `wp core update --locale=en-GB` successfully, so that's quite odd.  Maybe I have not been updating with the intended language?

**Comment by danielbachhuber** [comment]
> Maybe I have not been updating with the intended language?

Quite possibly.

**Comment by jason404** [comment]
Just FYI, it does seem to work with `wp core update --locale=en-GB`.

    $ wp core update --locale=en-gb
    Updating to version 4.3 (en_GB)...
    Success: WordPress updated successfully.
    Downloading update from https://downloads.wordpress.org/release/en_GB/wordpress-4.3.zip...
    Unpacking the update...

**Comment by shakaran** [comment]
The tmp writting problem is not really fixed well, see my comment at https://github.com/wp-cli/wp-cli/issues/1118#issuecomment-332073056
