### ISSUE TITLE
Import subcommand - way to suppress messages?

### ISSUE THREAD

**Issue by WebEndevSnippets** [wp-cli/wp-cli#1159]
Hello,

When using the import subcommand, there can be a large amount of screen output if the file is large.

I'm redirecting STDOUT and STDERR to a file, and haveing just a simple success/fail message instead of all of the detailed output would be nice.

Is there a way to suppress the 'Processing' detailed messages, and only get the final success message?

Thank you.

**Comment by danielbachhuber** [comment]
I'm going to close this as wontfix, because I couldn't ever get my output buffering hack to work on PHP 5.3

We should put our verbosity improvement efforts towards https://github.com/humanmade/wordpress-importer
