### ISSUE TITLE
php suhosin

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1181]
I've just upgraded to php 5.4 and managed to [compile suhosin](https://gist.github.com/szepeviktor/31881af34f5ac2dd99fa) for php.
It needs this line to run a phar:

```
suhosin.executor.include.whitelist = phar
```

Without this it does nothing and exits with 0.
### How to detect this?

``` bash
php -r 'exit((extension_loaded("suhosin") && strpos(ini_get("suhosin.executor.include.whitelist"), "phar") !== false )?0:1);' || die 99 "suhosin whitelist"
```

``` bash
die() {
    local RET="$1"
    shift
    echo -e "$@" >&2
    exit "$RET"
}
```

**Comment by aokolovskis** [comment]
Thanks, for the solution.
