### ISSUE TITLE
Add global option (--config-path) to specify location of WordPress config file

### ISSUE THREAD

**Issue by samstoller** [wp-cli/wp-cli#1218]
My wp-config.php file is located in a non-standard directory levels above wp-content. WordPress is able to locate this file as the standard wp-config.php has been changed to "require()" the actual conf file.

wp-cli is unable to parse my config file as it's just reading the source looking for the constants and wp-setting. So rather than try to parse the PHP code and read the file from the correct location, it would be easier and more flexible to specify a path to the conf file instead.

I'd be happy to work on this and submit a pull request. Thoughts?

**Comment by kevin-coyle** [comment]
Yeah I'm having the same issue as this. I really would like to keep the wp-config outside of a directory that apache can read to.

**Comment by credwards27** [comment]
@orev @kevin-coyle

As @danielbachhuber said, the stub `wp-config.php` file needs to have the following line in it for WP-CLI to parse it correctly:

```php
require_once( ABSPATH . 'wp-settings.php' );
```

Remove that line from your custom `wp-config.php` (outside web root), and place it after the `require_once` statement in your `wp-config.php` stub. As long as the stub is in the same directory as the rest of Wordpress core, WP-CLI shouldn't have any issues.

**Comment by samstoller** [comment]
Exactly right. I made a gist for this for anyone still having trouble. HTH.

https://gist.github.com/samstoller/efc38eb309e62df392ea

**Comment by gilzow** [comment]
I know this closed but add another +1 to the request to allow us to define the location of wp-config.php via parameter.

**Comment by kupietools** [comment]
Another +1. That gist is not helpful at all. I'm not using any sort of a "stub" but if it can't find my wp-config file for some reason, despite being in the same folder I'm running it from, right there alongside my other WP folders, it would be helpful if I could just tell it where it is with a parameter.

**Comment by anthonyeden** [comment]
I know this is an old issue, but I wanted to comment here in case anyone find this via Google. The workaround is to set an environmental variable in your shell. e.g.

```
export WP_CONFIG_PATH="/sites/example.com/public/wp-config.php"
```

Doing so overrides the default wp-config.php file in WP-CLI.
