### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by carbontwelve** [wp-cli/wp-cli#122]
Just issuing the wp command in the root of my wordpress install returns the following error:

PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 30720 bytes) in /root/git/wp-cli/src/php/wp-cli/commands/internals/plugin.php on line 84

I have 128MB limit set in php.ini and wordpress alone uses 40.87 of that per instance.

I am using:
PHP 5.3.3-7+squeeze8 with Suhosin-Patch (cli) (built: Feb 10 2012 13:05:56)

**Comment by 2hands10fingers** [comment]
I'm having this issue. I get it without running wordpress installation at all. I open Command Prompt -> enter "wp" into the command line, and then I get "Not enough memory". What's going?

**Comment by Rarst** [comment]
@2hands10fingers I have exactly same error, seems to be specific to PHP 7.1+ on Windows in my case, please see #4593 and comment if your setup is same/similar.

**Comment by patbell101** [comment]
Finding the right php.ini and setting memory-limit = 512M solved this for me.

# Find your php.ini for PHP-CLI
$ php -i | grep php.ini
Configuration File (php.ini) Path => /usr/local/etc/php/7.0
Loaded Configuration File => /usr/local/etc/php/7.0/php.ini
# Increase memory_limit to 512M or greater
$ vim /usr/local/etc/php/7.0/php.ini
memory_limit = 512M

**Comment by 2hands10fingers** [comment]
@Rarst Glad I came back to your comment. The updates to wp-cli via your comment helped to fix my issue and it's now working. Glad to finally have this working. Thanks everyone!

All I needed to do was `$wp cli update`

**Comment by ramonfincken** [comment]
neatly explained https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes
