### ISSUE TITLE
Adding a RSS widget does not set the feed URL

### ISSUE THREAD

**Issue by avaly** [wp-cli/wp-cli#1222]
Adding a RSS widget to a sidebar will not populate the feed URL for that widget.

```
$ wp widget add rss sidebar-1 1 --url="http://www.smashingmagazine.com/feed/" --items=3
Success: Added widget to sidebar.
```
Actual result: widget is added with the number of items set to 3, but with empty feed URL.

Expected result: widget has the feed URL set.

wp-cli version 0.15.1.

**Comment by JonathanReeve** [comment]
I was directed here from [this StackOverflow question](http://wordpress.stackexchange.com/questions/194707/how-can-i-add-an-rss-widget-using-wp-cli?noredirect=1#comment284363_194707) where I'm trying to add an RSS widget using the `--url` flag, unsuccessfully. Is there a workaround for this?

**Comment by danielbachhuber** [comment]
> Is there a workaround for this?

No workarounds, unfortunately.
