### ISSUE TITLE
sh: mysql: command not found on wp core config

### ISSUE THREAD

**Issue by alessandrotesoro** [wp-cli/wp-cli#1223]
I've installed wp cli following the guidelines here http://wp-cli.org/ since i'm running MAMP on my mac, i've created a .bash_profile file into my user directory like explained here http://stackoverflow.com/questions/4145667/how-to-override-the-path-of-php-to-use-the-mamp-path/10653443#10653443

My .bash_profile file looks like this

```
export MAMP_PHP=/Applications/MAMP/bin/php/php5.5.10/bin
export PATH="$MAMP_PHP:$PATH"
```

If i run wp --info 

i get this 

```
PHP binary: /Applications/MAMP/bin/php/php5.5.10/bin/php
PHP version:    5.5.10
php.ini used:   /Applications/MAMP/bin/php/php5.5.10/conf/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 0.15.1
```

I have then ran the following into the folder i created for my wp installation

```
wp core download
```

I have then ran the following to setup the wp-config file

```
wp core config --dbname=db --dbuser=root
```

And there's the error 

sh: mysql: command not found

What am i doing wrong? I've checked existing topics here on github but i can't find a proper solution to my situation.

**Comment by voltronik** [comment]
This also worked for me after I updated to Max OS X El Capitan.

**Comment by dendeffe** [comment]
Thanks for posting the solution. Worked for me.

**Comment by jepser** [comment]
So much thanks man!

**Comment by erfanv** [comment]
I'm an amateur here - bash profile? Does someone mind explaining how this is done? Thanks in advance!

**Comment by krajinovicm** [comment]
Thank you!

**Comment by rob-gordon** [comment]
For anyone else having trouble here - it **has to be ~/.bash_profile** – even if you running the command from zsh or some other shell. That threw me off for a minute. Thanks @alessandrotesoro!

**Comment by RaphaAmericano** [comment]
> Fixed by adding to the bash profile
> 
> ```
> export PATH=$PATH:/Applications/MAMP/Library/bin/
> ```

Work for me. Mojave
