### ISSUE TITLE
Limit db export to tables matching prefix

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1225]
Please consider adding a `--prefix` option to DB export that would export only the prefixed tables.

**Comment by szepeviktor** [comment]
Could it go like https://github.com/wp-cli/wp-cli/pull/1629 ?

**Comment by danielbachhuber** [comment]
> What is your decision on prefixed export?

We could have `--all-tables-with-prefix` flag, but it would be nice to also have some wildcard matching syntax.

**Comment by szepeviktor** [comment]
Could you review my plans?
https://github.com/szepeviktor/wp-cli/commit/e1b9f737758afabdcfdb5c41caf688491347753e

**Comment by szepeviktor** [comment]
Without wilcard support and tests.

**Comment by szepeviktor** [comment]
As in `wp option list`:
```php
	if ( isset( $assoc_args['search'] ) ) {
	$pattern = self::esc_like( esc_sql( $assoc_args['search'] ) );
	// substitute wildcards
	$pattern = str_replace( '*', '%', $pattern );
	$pattern = str_replace( '?', '_', $pattern );
	}
```
OK?

**Comment by danielbachhuber** [comment]
Looks pretty good.

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/wp-cli/pull/1663

**Comment by danielbachhuber** [comment]
Because WordPress isn't fully loaded for `wp db export`, and we don't have access to `$wpdb`, I've decided to just make composability easier:

```
wp db export --tables=$(wp db tables --all-tables-with-prefix --format=csv)
```

You can also search based on wildcard:

```
wp db export --tables=$(wp db tables 'wp_user*' --format=csv)
```

**Comment by szepeviktor** [comment]
Your idea is very welcome.

**Comment by lkraav** [comment]
Thanks. `--scope=blog --all-tables-with-prefix` is what I needed to get. Looks like I had to switch from 0.21.1 to `master` to get this goodness. Bit of a puzzling moment when `wp db tables --help` only showed one available parameter.
