### ISSUE TITLE
Collision with composer in theme

### ISSUE THREAD

**Issue by doctordesh** [wp-cli/wp-cli#1235]
Hello!

We use `wp` to manage our Wordpress sites. We also use `composer` for dependency management in our themes/plugins. 

With the latest update (0.15.1) I get this message when I'm in my current theme (that has a `composer.json` and a `vendor` folder).

    Call to undefined method Composer\Autoload\ClassLoader::setPsr4() in /.....vendor/composer/autoload_real.php on line 36

It seems to be a some kind of conflict with my theme using the `composer` inside the `wp cli`.

**Comment by mAAdhaTTah** [comment]
I'm getting this issue reported here: https://github.com/mAAdhaTTah/WP-Gistpen/issues/25 - I can't reproduce yet though.
