### ISSUE TITLE
Using WP-CLI with cron(tab)

### ISSUE THREAD

**Issue by msundquist** [wp-cli/wp-cli#1279]
I have a PHP script which I would like to execute using WP-CLI via a crontab entry. Due to the nature of the script, I'm trying to avoid using WP-Cron.

I can see that the crontab entry is properly executed (reviewing the cron log), however the actual PHP script does not seem to execute (reviewing the custom script log as well as the expected results of the script's operation.) I've also tried wrapping the command in a shell script to no avail.

If I execute the PHP script manually using WP-CLI from the command-line, I see normal operation as expected. Same with the shell script. This is essentially the command I'm using:
**/usr/local/bin/wp --allow-root eval-file /path/to/script.php**

Tested crontab entry:
*** \* \* \* \* cd /path/to/site/ ; /usr/local/bin/wp --allow-root eval-file /path/to/site/script.php**

I'm wondering if there is any known barrier to using WP-CLI together with cron. Any assistance is appreciated.

**Comment by bendoh** [comment]
+1 can confirm this behavior and that using --path fixes it. 

Even when my shell script cd'd into the WordPress root before running the wp command...

**Comment by ronshe** [comment]
Regarding STDOUT/STDERR, I created a script to solve this:
```
#!/bin/bash

# Suppress errors by including this generated file
echo "<?php if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'r')); if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w')); if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w')); error_reporting(0); @ini_set('display_errors', 0);" > /tmp/__pre.php

owner=`stat -c %U .`
sudo -u $owner /usr/local/bin/wp --path=$PWD --color --require=/tmp/__pre.php $*

rm -f /tmp/__pre.php
exit
```

**Comment by itsravenous** [comment]
@ronshe that worked for me - thanks so much!

**Comment by ronshe** [comment]
I'm glad that I could help :)

**Comment by ibertrix** [comment]
Not sure if it is related but trying to run:

`* * * * 1-5 /usr/local/bin/wp --path=/home/myuser/public_html/wordpress core version >> /root/test.log 2>&1`

and I´m getting in test.log:

`Content-type: text/html; charset=UTF-8`

It´s what I´m getting from any bash script with wp-cli commands. Those scripts run fine from command line:


```
#!/bin/bash

WP=/usr/local/bin/wp
array=($(find /home -maxdepth 6 -type d -name '*wp-content*' -exec dirname {} \;))

for x in ${array[@]} ;do
 echo "Checking:" $x
 $WP --allow-root --path=$x core version 
done
```

**Comment by TheLastCicada** [comment]
Just ran into this same thing on a project.  Documenting the procedure to fix it here in case anyone else comes across this weird setup.  This was on a LiquidWeb dedicated VM with cPanel.  Symptoms of this problem were the same as everyone else - I'm getting PHP headers output as the result of running `wp`:

```
X-Powered-By: PHP/7.0.33
Content-type: text/html; charset=UTF-8
```

To determine that it was the same problem described in this ticket, I first did `which php` at the command line to see what version was running when my script worked:

```
$ which php
/usr/local/bin/php
```

Then I used this PHP binary to get the version info:

```
$ /usr/local/bin/php --version
PHP 7.0.33 (cli) (built: Sep 22 2020 20:12:22) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.1.0 (), Copyright (c) 2002-2017, by ionCube Ltd.
```

Note the `(cli)` in the first line.  Then I created a cron job that did `which php` using `crontab -e` and sent it to a log file:

```
42 10 * * * which php > /home/example-user/logs/wp-cli-test.log
```

The output was: `/usr/bin/php` .  Note this is different than the binary used on the command line. 

Doing `--version` on this php binary.....

```
$ /usr/bin/php --version
PHP 7.0.33 (cgi-fcgi) (built: Sep 22 2020 20:12:57)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.1.0 (), Copyright (c) 2002-2017, by ionCube Ltd.
```

Note the `(cgi-fcgi)` on the first line.  This is the PHP-CGI binary, which is going to cause all sorts of problems running wp-cli in your cron.  

What I did to fix this is to force the PHP binary from the CLI to run wp-cli in my script.  So anywhere I call wp-cli in my script, I'm doing the following:

```
/usr/local/bin/php /usr/local/bin/wp
```

This uses the PHP binary at `/usr/local/bin/php` to run `/usr/local/bin/wp` and now everything in crontab works the same as if I did it on the command line.

**Comment by codaamok** [comment]
@TheLastCicada you are a shining example of all the great things about the Internet. Thank you so much for sharing that. This was exactly my issue, too, when trying to interface with a plugin that had WP CLI support - I was also receiving web server header responses via cron jobs whereas running the same commands at the command line was producing the real expected results.

Thanks again.

**Comment by rashidkalwar786** [comment]
Thank you for sharing that..

**Comment by Dwarfjazzer** [comment]
@TheLastCicada thank you for your great work. 

I am leaving here the error that returns when the php used in the cron is the incorrect one to help someone else as well:
```shell
PHP Fatal error:  Uncaught Error: Undefined constant "WP_CLI\Utils\STDOUT" in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1194
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(891): WP_CLI\Utils\isPiped()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/InitializeColorization.php(23): WP_CLI\Runner->init_colorization()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\InitializeColorization->process(Object(WP_CLI\Bootstrap\BootstrapState))
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#4 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#5 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#6 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1194
```
