### ISSUE TITLE
subdir install

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1284]
Are you planning to support subdir installs?

webroot=`/var/www/`
ABSPATH=`/var/www/secret/` (wp files except `wp-content`)
wp-content=`/var/www/static/`

Now it is possible by
```bash
cp secret/index.php index.php
sed -i "s|'/wp-blog-header.php'|'/secret/wp-blog-header.php'|" index.php
wp core config ... --extra-php
wp core install ... --url=http://subdir.wp/secret
wp option set home http://subdir.wp
```
```php
// --extra-php
define( 'WP_CONTENT_DIR', '/var/www/static' );
define( 'WP_CONTENT_URL', 'http://subdir.wp/static' );
```

**Comment by danielbachhuber** [comment]
At this point, I'm not planning to support installation schemes outside those WordPress core supports.

**Comment by szepeviktor** [comment]
Excuse me.
- moving `wp-content` is supported through `WP_CONTENT_DIR`
- installing to a subdirectory is detailed here: https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory#Moving_a_Root_install_to_its_own_directory

**Comment by danielbachhuber** [comment]
> installing to a subdirectory is detailed here:

Documentation in the Codex doesn't mean official support by core. Those directions include modifying `index.php`, which isn't a part of any officially-supported installation process.

**Comment by szepeviktor** [comment]
That *is* correct.

`index.php` in the root has to be copied and modified at one line.

**Comment by szepeviktor** [comment]
:scream: (almost) all of my install are unofficial.
