### ISSUE TITLE
Prompt for passwords

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#129]
There are a couple of commands that require passing a password as a parameter:

```
wp core config
wp core install
```

If the parameter is not passed, we should prompt for the password instead of just throwing an error.

This seems to be a common pattern. For an example, see the `mysql` command.

**Comment by yuvilio** [comment]
I look at not putting the password in the command from the security perspective. My workaround is putting the password in a temp file and just extracting it from there.  That way  it doesn't leave a trace in the command history (slightly more secure) and doesn't prevent automation.


```bash
$ cat dbpass.txt 
secret
$ wp core install --admin_password=$(cat dbpass.txt) ...
Success: WordPress installed successfully.
$ 
```

 For extra neurotic security, maybe the password file could be placed in a USB key drive separately.

**Comment by matpen** [comment]
@yuvilio your solution prevents indeed the sensitive inputs to be stored in the history, however the password can be seen by every user on the system with ps.

**Comment by matpen** [comment]
I suggest I small modification to the global "--prompt" option, which currently simply prompts for input of ALL options of the specific command. If we could enter a list of options to be prompted for, those values could be piped through stdin. As an example: `wp user create bob bob@example.com --role=author --prompt=user_pass` would prompt only for the user password. When scripting, this can be used securely like `cat passwd.txt | wp user create bob bob@example.com --role=author --prompt=user_pass`. For secure use at the terminal we could introduce `--prompt-secure=user_pass` to hide the user input.

**Comment by danielbachhuber** [comment]
I like the idea of something like `--prompt-secure` or similar, and I also like the idea of being able to specify which arguments to prompt for. However, for the latter, I'm not sure what the syntax would be to prompt for positional arguments or flags (which `--prompt` supports currently).

We could also magically use a secure prompt for arguments with `*pass*`, but I'm sure that would cause bugs we'd regret. And it doesn't handle positional arguments which need to be secure.

**Comment by pkarjala** [comment]
Ideally it would function the same as the `wp user create` command at http://wp-cli.org/commands/user/ where the password is output on the command line and as such does not appear in the history.  This is the same as the GUI interface when spinning up a new Wordpress site; a randomly generated password is presented to the user for the admin login, so you could tap into that functionality to generate the password for the user and display it if the user does something like `--admin_random_password` as an option on `wp core install`.

The entire argument regarding worrying about a screen-sharing session is IMHO moot, because as soon as you're screen sharing, you're not in a secure context anyway.

**Comment by danielbachhuber** [comment]
> Ideally it would function the same as the `wp user create` command at http://wp-cli.org/commands/user/ where the password is output on the command line and as such does not appear in the history.

The scenario you're describing is _output_. We're discussing _input_.

**Comment by danielbachhuber** [comment]
> I suggest I small modification to the global "--prompt" option, which currently simply prompts for input of ALL options of the specific command.

@matpen I like this suggestion, and think it's sufficient for our needs.

Sorry it's taken so long to address this issue :( It's literally the oldest open issue we have.

**Comment by pkarjala** [comment]
Apologies; I'll write it into a separate issue.
