### ISSUE TITLE
How to uninstall wp-cli that was installed with installer.sh

### ISSUE THREAD

**Issue by jacklenox** [wp-cli/wp-cli#1292]
Is there a way of removing a version of wp-cli that has been installed with the old `installer.sh`?

I'm finding it difficult to work out what the installer script did.

**Comment by drew3000** [comment]
So what is the way to uninstall it before doing a fresh install?

**Comment by danielbachhuber** [comment]
> So what is the way to uninstall it before doing a fresh install?

Delete the file. You can find it with `which wp`:

```
$ which wp
~/bin/wp
$ rm ~/bin/wp
```
