### ISSUE TITLE
Can't make it work with XAMPP

### ISSUE THREAD

**Issue by dashaluna** [wp-cli/wp-cli#1307]
Hello,

I've followed this tutorial on how to get WP CLI working with XAMPP http://trepmal.com/2014/02/22/getting-started-with-wp-cli without any luck. The original issue is the following:

```
Error: 
<h1>Error establishing a database connection</h1>
<p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect 
or we can't contact the database server at <code>localhost</code>. This could mean your host's database server is down.</p>...

wp --info
PHP binary: /usr/bin/php
PHP version:    5.4.24
php.ini used:   
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 0.16.0
```

I'd hugely appreciate any help.

Many thanks,
Dasha

**Comment by aubreypwd** [comment]
For anyone else hitting this, edit your `~/.bash_profile` on OSX and add:

```
export PATH="/Applications/XAMPP/xamppfiles/bin":$PATH;
```

Make sure this is at the very top of your file or before any other `$PATH` modifications. This should preference the PHP binary in `xamppfiles/bin` above system PHP.
