### ISSUE TITLE
undefined function add_filter() and apply_filters()

### ISSUE THREAD

**Issue by javiertury** [wp-cli/wp-cli#1310]
After configuring automatic updates following http://codex.wordpress.org/Configuring_Automatic_Background_Updates using wp-cli gives the following error:
<code>PHP Fatal error:  Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/wp-cli.php(23) : eval()'d code on line 50</code> The same happens for apply_filters() function

My configuration is working properly with respect to wordpress itself, and yes, I've put the configuration after this line:
<code>require_once( ABSPATH . 'wp-settings.php' );</code>

Has wp-cli problems with the previous line? Have I misconfigured anything?

This is my custom config of wp-config.php

<pre>/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

define( 'FORCE_SSL_LOGIN', true );
define( 'FORCE_SSL_ADMIN', true );
define( 'WP_AUTO_UPDATE_CORE', true );
add_filter( 'allow_major_auto_core_updates', '__return_true' );
add_filter( 'automatic_updates_is_vcs_checkout', '__return_false', 1 );
add_filter( 'auto_update_plugin', '__return_true' );
add_filter( 'auto_update_theme', '__return_true' );
apply_filters( 'auto_core_update_send_email', false, success, $core_update, $result );</pre>

Edit: the error occurs with most commands such as <code>wp plugin list</code> but not with others e.g. <code>wp --version</code>. The version I'm using is WP-CLI 0.16.0

**Comment by danielbachhuber** [comment]
Created a new canonical issue for the `wp-config.php` problem #1631

**Comment by jamesmehorter** [comment]
Sorted this out in vipqs by running `sudo wp cli update --nightly --allow-root`

**Comment by lsmith77** [comment]
same issue .. using the nightly solved the issue .. but raises the question when we can expect the next release?

**Comment by lsmith77** [comment]
nevermind .. seems like the release was done but the phar at https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar doesn't seem to point to the latest version

**Comment by danielbachhuber** [comment]
> the phar at https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar doesn't seem to point to the latest version

It does, you're mistaken:

```
local ➜  Desktop  wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
--2016-08-17 06:05:42--  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
Resolving raw.githubusercontent.com... 151.101.40.133
Connecting to raw.githubusercontent.com|151.101.40.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4967063 (4.7M) [application/octet-stream]
Saving to: ‘wp-cli.phar’

wp-cli.phar                     100%[======================================================>]   4.74M  3.34MB/s    in 1.4s

2016-08-17 06:05:45 (3.34 MB/s) - ‘wp-cli.phar’ saved [4967063/4967063]
local ➜  Desktop  php wp-cli.phar --info
PHP binary:	/usr/local/Cellar/php70/7.0.9/bin/php
PHP version:	7.0.9
php.ini used:	/usr/local/etc/php/7.0/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/Users/danielbachhuber/salty-wordpress/wp-cli/packages/
WP-CLI global config:	/Users/danielbachhuber/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	0.24.1
```

**Comment by enoch85** [comment]
@jamesmehorter Thanks!

**Comment by evertramos** [comment]
Hi @danielbachhuber

I am not complaining or anything... just to confirm, but I having the same issue, solved with an update, the new version 0.24.1 became very slow, am I the only one?

Not sure if should be posted here... though might be any filtering problems, although I do not have any filtering configuration in my wp-config.php file, but still got this error with the older version of wp-cli.

Thanks!

**Comment by danielbachhuber** [comment]
Hi @evertramos,

Github issues are no longer an appropriate venue for support. Please see http://wp-cli.org/#support

**Comment by dannyb195** [comment]
For VVV users, going to www/wp-cli and pulling master (in my case I needed a `git reset --hard HEAD` then a `git pull origin master` to resolve this. Didnt dig any deeper though.

**Comment by toleabivol** [comment]
@dannyb195 what have VW drivers with this ?!
