### ISSUE TITLE
PHP Notice:  Constant ABSPATH already defined

### ISSUE THREAD

**Issue by tillkruss** [wp-cli/wp-cli#1315]
When I run `wp db export`, I get the following error:

```
PHP Notice:  Constant ABSPATH already defined in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(615) : eval()'d code on line 38
```

Is there an easy way to turn of PHP notices, or can you use `defined()`?

**Comment by mqudsi** [comment]
This can also happen if you have a _really_ old WordPress installation that you've been updating all these years, as WP didn't always ship with the `if (!defined...` guard.
