### ISSUE TITLE
--tax_input

### ISSUE THREAD

**Issue by xlightwaverx** [wp-cli/wp-cli#1323]
The wp post create command's --tax_input is not working correctly when assigning custom taxonomies to the newly created posts.

No documentation is added in regards to adding custom taxonomies to newly created posts via Wp-cli.

**Comment by danielbachhuber** [comment]
We'll eventually handled nested arguments as a part of #1784

**Comment by drzraf** [comment]
This is still a bug to be reopened.
`$ wp post update --tax_input='{"footype":["news"]}' --post_type=post 1129`
```
web/wp/wp-includes/post.php:3508:
PHP Warning:  Invalid argument supplied for foreach() in /web/wp/wp-includes/post.php on line 3509
```
`$postarr['tax_input'] == string(24) "{\"footype\":[\"news\"]}"`

**Comment by MikeiLL** [comment]
I'm finding that this still doesn't work with `WP-CLI 2.7.1`, and guessing it's still a bug in Wordpress itself.

```
wp post update 24713 --tax_input='{"class_category": "Dance]}'
Warning: Invalid argument supplied for foreach() in /peth_to/wp-includes/post.php on line 4478
Success: Updated post 24713.
```

**Comment by shogathu** [comment]
I also have this bug with `WP-CLI 2.7.1` and `PHP 7.4 - PHP 8.1.2`

`wp post update 238 --tax_input='{"up_j2m_tax_steps":["ttg-v4-t1-a1"]}' `
or 
`wp post update 238 --tax_input='{"up_j2m_tax_steps":"ttg-v4-t1-a1"}'`
and other combination, gives

`Warning: Invalid argument supplied for foreach() in /path/public_html/wp-includes/post.php on line 4520`

**Comment by swissspidy** [comment]
This issue was closed 8 years ago. Please consider opening a [new issue](https://github.com/wp-cli/wp-cli/issues/new/choose) instead of leaving a comment here.

**Comment by szepeviktor** [comment]
Or try using https://github.com/wp-cli/restful

**Comment by EarthlingDavey** [comment]
10 years later. wow.

I hope this snippet will save some headaches. 

Both formats `--tax_input='{"taxonomy":"aTag"}'` & `--tax_input='{"taxonomy":["aTag","bTag"]}'` should work.

```php
add_filter('pre_tax_input', 'parse_tax_input_json');
add_filter('pre_post_tax_input', 'parse_tax_input_json');

function parse_tax_input_json($value)
{
    if (gettype($value) !== 'string') {
        return $value;
    }

    // Remove slashes
    $value = stripslashes($value);

    // Convert json to array
    $value = json_decode($value);

    return $value;
}
```
