### ISSUE TITLE
Remove the dependency on `mysql`

### ISSUE THREAD

**Issue by borekb** [wp-cli/wp-cli#1324]
Would it be possible to remove the dependency on `mysql` cmdline binary? Most of WP-CLI runs perfectly fine in pure PHP and WordPress can also install itself without this dependency so maybe it could be removed. Or is there a reason why it needs to be there?

**Comment by karellm** [comment]
I second @clakeb bog time on that one. 

Imagine a Docker setup, one container runs `mysql`, one runs `apache/php`. I simply want to install wordpress and the plugins in the `apache/php` one. I'll activate them and do all the rest when I boot the stack. Without this, I'm actually forced to install plugins at every start of the server.

**Comment by karellm** [comment]
@clakeb if that helps, in the meantime:

```
pluginsList=(
      wordpress-seo
      wordpress-importer
    )

    # Install plugins
    for plugin in "${pluginsList[@]}"
    do
      echo ""
      echo "Install $plugin"
      curl -LOk http://wordpress.org/extend/plugins/download/${plugin}.zip
      unzip -q ${plugin}.zip
      rm ${plugin}.zip
    done
```

**Comment by danielbachhuber** [comment]
Closing this as wontfix — WP-CLI is sufficiently dependent on the `mysql` binary that I don't think we can refactor to replace it.

**Comment by eni23** [comment]
I have the same issue and do not understand why you rely on a binary when wordpress fully works without it. This makes the tool complete unuseable for Deployments inside Docker Containers or a PaaS environment like Kubernetes where you not have mysql inside your web container and you do not want that deps installed in it just for the Setup.

**Comment by gitowiec** [comment]
I can't use wp-cli inside wordpress Docker container, could You reopen this issue and fix it? 
People saying same thing here in this thread, how to do `wp export db` on a dockerized Wordpress?

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/ideas/issues/52

**Comment by BrianHenryIE** [comment]
To resolve/install it: `sudo apt-get install mysql-client`

**Comment by jonathannz** [comment]
I've had the same issue using wp-cli in an openlitespeed server. OLS has its own mysql package (`lsphp74-mysql`), that wp-cli does not detect. I've also been told the package is called `mysqlnd` on OLS.

This means I can't use wp-cli to install WP in such an environment, because wp-cli will give me an error that PHP needs mysql. And the installation aborts.

I would like to suggest at least adding a flag one you use to force the install, without checking for PHP related dependencies. At least that way the user who wants to over-ride those checks can.

**Comment by iohnatan** [comment]
> I've had the same issue using wp-cli in an openlitespeed server. OLS has its own mysql package (`lsphp74-mysql`), that wp-cli does not detect. I've also been told the package is called `mysqlnd` on OLS.
> 
> This means I can't use wp-cli to install WP in such an environment, because wp-cli will give me an error that PHP needs mysql. And the installation aborts.
> 
> I would like to suggest at least adding a flag one you use to force the install, without checking for PHP related dependencies. At least that way the user who wants to over-ride those checks can.

Install the mysql client without the server, on centos with openlitespeed execute this:
yum -y install mysql

**Comment by lusareal** [comment]
> To resolve/install it: `sudo apt-get install mysql-client`

you can't... because in alpine docker there os no apt or apt-get

**Comment by wojsmol** [comment]
@lusareal `apk add mysql-client` is a equivalent for alpine.
