### ISSUE TITLE
WP-CLI should respect values set in open_basedir

### ISSUE THREAD

**Issue by 0dp** [wp-cli/wp-cli#1332]
I don't understand where this warning is coming from?
`Warning: is_readable(): open_basedir restriction in effect. File(/srv) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/:/etc/webapps/:/usr/local/bin) in phar:///usr/local/bin/wp/php/utils.php on line 112`

**Comment by HLFH** [comment]
Same issue.

**Comment by danielbachhuber** [comment]
In #2211, I'm going to suppress the error. `is_readable()` returns `false` if it can't read the directory, so we don't need the complexity of trying to interpret the values in `open_basedir`

**Comment by ElleshaHackett** [comment]
I still have this issue today.

**Comment by ddarbyson** [comment]
This is still an issue for me.

I found that adding a `wp-cli.yml` config file to the root of your project will stop the warnings. I suppose with `open_basedir` in effect, somewhere the search for the yml file is traversing all the way up to the root / ?!?

no idea...

**Comment by tmuka** [comment]
> This is still an issue for me.
> 
> I found that adding a `wp-cli.yml` config file to the root of your project will stop the warnings. I suppose with `open_basedir` in effect, somewhere the search for the yml file is traversing all the way up to the root / ?!?
> 
> no idea...

Thanks, @ddarbyson that workaround was helpful.  The empty wp-cli.yml file was enough to stop that open_basedir warning on my plesk site.
