### ISSUE TITLE
Not picking up WordPress in a subfolder

### ISSUE THREAD

**Issue by jghazally** [wp-cli/wp-cli#137]
Hi my site directory structure is:

wp/
wp-config.php
wp-content/

doing a `wp core version`
returns the error:
_Error: This does not seem to be a WordPress install. Pass --path=`path/to/wordpress` or run `wp core download`._

which seems to work correctly if I do pass the `--path` however trying to do `wp --path=wp plugin status` shows no installed plugins ( I suspect it is still looking for wp-content within the wp directory though I have not dug into it much)

**Comment by jorgeorpinel** [comment]
This still doesn't work for me using DOCUMENT_ROOT and I'm on version 0.22.0 :T

**Comment by baldursson** [comment]
I have this in my `wp-config`:
```
define("WP_SITEURL", "http://" . $_SERVER["HTTP_HOST"] . "/wp/");
define("WP_HOME", "http://" . $_SERVER["HTTP_HOST"]);
```

Site works fine, wp-cli does not. When I change the path to:
```
define("WP_SITEURL", "http://" . $_SERVER["HTTP_HOST"] . "/../wp/");
define("WP_HOME", "http://" . $_SERVER["HTTP_HOST"]);
```
Site breaks, but wp-cli seams to work fine. How do I get both to work?

**Comment by javorszky** [comment]
note that when using `wp-cli`, the `$_SERVER` superglobal has a lot of missing information

**Comment by baldursson** [comment]
Ah ha! Replaced it with `dirname(__FILE__)` and now the both seem to work. Thank you @javorszky for a super fast response.
