### ISSUE TITLE
Error on SampleTest::testSample - UnexpectedValueException: RecursiveDirectoryIterator::__construct(/tmp/wordpress/wp-content/uploads): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by hellofromtonya** [wp-cli/wp-cli#1425]
With no other tests than just SampleTest, after running phpunit I get the following error:

UnexpectedValueException: RecursiveDirectoryIterator::__construct(/tmp/wordpress/wp-content/uploads): failed to open dir: No such file or directory

/private/tmp/wordpress-tests-lib/includes/testcase.php:407
/private/tmp/wordpress-tests-lib/includes/testcase.php:425
/private/tmp/wordpress-tests-lib/includes/testcase.php:26

Greatly appreciate a nudge in the right direction. Cheers

UPDATE: 
The issue I believe is on my end as I'm getting a permissions error when running bash bin/install-wp-tests.sh wordpress_test root '' localhost latest.   Got around it by installing the svn wordpress_develop and then modifying the bootstrap accordingly.

**Comment by paddelboot** [comment]
I had the same error after running the `install-wp-tests.sh` with sudo, and permission issues when running it as non-sudo user.

I had to manually update the permissions of `/tmp/wordpress`:

    $ sudo chown -R myuser /tmp/wordpress
    $ sudo chmod -R 755 /tmp/wordpress

After that, the sample test in `/tests` ran successfully.
