### ISSUE TITLE
Append bash auto-complete via Composer post install Script

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wp-cli/wp-cli#1448]
First off, I've already written a [composer package](https://github.com/wecodemore/wp-cli-composer) that already a possibility to add bash auto complete to the install (see the repo). Of course there are some settings for the end user to add to the `composer.json`, but the package already helps getting around most of it. The script could be easily added to WP-CLI core. In short: Would be nice if there would be _no need_ for that and this could be incorporated into WP-CLI itself.

What also would be nice if there would be another post install script that symlinks the bin folder to `/usr/share/bin` so there's no need to do more than simply add WP-CLI and everything will be taken care off.

**Comment by danielbachhuber** [comment]
Passing on this issue — the install instructions on the homepage seem sufficient.
