### ISSUE TITLE
Export Command: post__in not compatible when using together with post_type ?

### ISSUE THREAD

**Issue by ajf-** [wp-cli/wp-cli#1451]
I'm using the following command:
```
wp --require=__pre.php export --max_file_size=0.1 --skip_comments --post_status=publish --dir=export/post --post_type=post --post__in=148082,148056,148050,147994,147976,147950,147862,147908
```
**Note**: __pre.php just silences some PHP warnings. 

But wp-cli still generates A LOT of (more than 2000) files (this is a blog with about 60,000 posts). I would expect no more than 3 files if I'm exporting just 8 posts.

I know the example states that the usage is:

```
wp export --dir=/tmp/ --post__in=123,124,125
```

But in my case, I need the --post_type argument, because if I don't use it, I get ```Error: Term is missing a parent.```. In any case, I wouldn't expect that these two parameters can't be used together. Seems like a bug. 

Any feedback on this?
Thanks

### For reference, the full code of the bash script I'm using is this:
The goal is to be able to export a limited number (50) of posts throughout all post types.

```bash 
#!/bin/bash
NUMBER_OF_POSTS=50;
POST_TYPES=$(wp --require=__pre.php eval "$(cat <<EOF
    \$ptypes = get_post_types(array(
        'public' => true,
        'can_export' => true
    ));
    foreach (\$ptypes as \$ptype) {
        echo \$ptype . PHP_EOL;
    }
EOF
)");

function getIds {
POST_IDS=$(wp --require=__pre.php eval "$(cat <<EOF
    \$query = new WP_Query();
    \$posts = \$query->query(array(
        'post_type' => '$POST_TYPE',
        'posts_per_page' => $NUMBER_OF_POSTS,
    ));

    \$ids = array();
    foreach (\$posts as \$post) {
        array_push(\$ids,\$post->ID);
    }

    echo implode(',', \$ids);
EOF
)");
}

for POST_TYPE in $POST_TYPES 
do 
    mkdir -p export/$POST_TYPE; 
    getIds;
    echo "Executing wp --require=__pre.php export --post_type=$POST_TYPE --skip_comments --max_file_size=0.1 --post_status=publish --dir=export/$POST_TYPE --post__in=$POST_IDS;";
    wp --require=__pre.php export --post_type=$POST_TYPE --skip_comments --max_file_size=0.1 --post_status=publish --dir=export/$POST_TYPE --post__in=$POST_IDS; 
    
done
```

**Comment by VickG** [comment]
I am having the same problem. I am usinglatest version 0.18 and I am getting same error:
Error: Term is missing a parent.

when doing an export. Any resolution? 
Can I somehow with a SQL query find what term is orphan? I might just be able to delete it.

**Comment by danielbachhuber** [comment]
After #1685 is merged, the error message will include the term slug and term taxonomy ID. You can install nightlies following these instructions: https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods#installing-nightly-via-phar

**Comment by VickG** [comment]
@danielbachhuber thank you for your quick reply! and thanks for WP CLI! :)
