### ISSUE TITLE
Support authentication in URL for plugin location

### ISSUE THREAD

**Issue by bdruth** [wp-cli/wp-cli#1452]
Given:
A user needs to install a plugin from a URL which requires authentication.

When:
The authentication credentials are embedded in the URL (e.g. https://username:password@host/plugin/location)

Then:
``wp client install <url>`` should send authentication headers, as indicated in the URL.

When we try to install plugins that are archived as part of a CI build, where the CI server (e.g. Jenkins) requires authentication, plugin installation fails.

**Comment by danielbachhuber** [comment]
Closing this as wontfix. I don't think there's sufficient need to have this as a part of WP-CLI.

**Comment by grappler** [comment]
I tried to do this today and it did not work. We have our purchased premium plugins on a server behind a http auth.

**Comment by kyodev** [comment]
I also tried :(
I cannot serve plugins from my server with http authentication without adding lines of code in my scripts, it's a bit annoying

**Comment by danielbachhuber** [comment]
@grappler @kyodev If one of you want to DM me in WordPress.org Slack with an example I can test with, I'd be happy to put together a filter for this.

**Comment by EloB** [comment]
Is this still not doable? I'm also trying to automate the installation of a plugin from a premium plugin provider. Would be good if it was possible todo:
```bash
wp plugin install http://some.domain/plugin.zip \
--header "Authorization: Bearer mytoken" \
--activate \
--force
```

**Comment by EloB** [comment]
@szepeviktor I don't know how to extend that. I haven't use `--require` before.

**Comment by szepeviktor** [comment]
You could ask Gemini/ChatGPT/Copilot.
```php
<?php
add_filter('http_request_args', function ($args) {
    $args['headers']['Authorization'] = 'Bearer SSdtIG5vdCBkdW1iIGZha2UgQVBJIGtleQ==';
    return $args;
});
```
https://developer.wordpress.org/reference/hooks/http_request_args/
You could also check the current URL.

**Comment by EloB** [comment]
@szepeviktor Haven't tried yet but thanks for your reply :)
