### ISSUE TITLE
Not working with custom wp-config-local.php (Pantheon)

### ISSUE THREAD

**Issue by camb416** [wp-cli/wp-cli#1453]
When running WP-CLI on a clone of the Pantheon wordpress, this error is displayed:

<pre>[05-Aug-2014 14:30:45 UTC] PHP Fatal error: Cannot redeclare wp_unregister_GLOBALS() (previously declared in /Applications/MAMP/htdocs/lookey/wp-includes/load.php:17) in /Applications/MAMP/htdocs/lookey/wp-includes/load.php on line 32</pre>

I proposed this workaround in the wp-config.php to trick WP-CLI into including the code in CLI mode... 
https://github.com/pantheon-systems/WordPress/pull/5

However, it was suggested that the root of the problem is perhaps upstream, either in here, or in WP Core.

I'm not familiar with the wp-cli code, so any suggestions would be very helpful!

Thanks

problem description:
http://5cameron.com/content/wp-cli-cloned-local-pantheon-wordpress

**Comment by danielbachhuber** [comment]
Created a new canonical issue for the `wp-config.php` problem #1631
