### ISSUE TITLE
Renaming wp-config-sample.php causes checksum verification to fail

### ISSUE THREAD

**Issue by aheckler** [wp-cli/wp-cli#1465]
When installing WP, lots of people simply rename `wp-config-sample.php` to `wp-config.php` and overwrite the placeholder values. However, doing so causes `wp core verify-checksums` to fail with:

```
Warning: File doesn't exist: wp-config-sample.php
Error: WordPress install doesn't verify against checksums.
```

I would think that if this were the only missing file, `verify-checksums` should still pass?

**Comment by LatinSuD** [comment]
So what you are saying is that now we need another tool on top of wp-cli to actually decide if an installation is valid.
