### ISSUE TITLE
List taxonomies associated with posts (and users)

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/wp-cli#1474]
There should a command that lists the taxonomies linked to an object type. I believe the syntax should look like this. 

For users
```wp user terms taxonomies```

For posts

```wp post terms taxonomies --post_type=page```

I believe this can be done by overriding the taxonomies method in posts, so it takes post_type arg (and should be required). From there we can call the parent class / method. This should keep it generic for other object types. 

related https://github.com/wp-cli/wp-cli/issues/1379

**Comment by rodrigoprimo** [comment]
I'm planning to create a PR for this in the next days.

I'm thinking the syntax should be:

`wp taxonomies list [--post_type=page]`

@danielbachhuber any preference?

**Comment by rodrigoprimo** [comment]
Actually `wp taxonomy` instead of `wp taxonomies `

**Comment by danielbachhuber** [comment]
It would make sense to me to have `wp taxonomy list` default to listing all taxonomies, and then `--post_type=<post-type>` would filter to those assigned to a given post type.

**Comment by rodrigoprimo** [comment]
On #2145 I created `wp taxonomy list` with the following fields:

```
name
label
description
public
hierarchical
```

Do any of you think that other fields returned by `get_taxonomies()` are useful and should be included as well?

I would like to be able to see the list of capabilities associated with a taxonomy but I'm inclined to add this as another command. Maybe `wp taxonomy cap <taxonomy>`. Thoughts?

**Comment by danielbachhuber** [comment]
> Do any of you think that other fields returned by get_taxonomies() are useful and should be included as well?

Nah. We can always add them later.

**Comment by danielbachhuber** [comment]
`wp taxonomy get` was introduced in #2173
