### ISSUE TITLE
Is it possible to list all the posts associated to a specific term?

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/wp-cli#1491]
Although it is possible to use `wp post list --<field>=<value>` to pass arguments to WP_Query I don't this includes 'tax_query' since this argument expects an array.

Related #1474

**Comment by tedsecretsource** [comment]
I know this is kind of old but I'm not finding answers elsewhere. Does the above mean that if you have a taxonomy called "people" you can do `wp post list --people=fred` or would it be more like `--tax_query=people=fred`?

Thanks in advance.

**Comment by cbirdsong** [comment]
If anyone ends up here looking or a solution, this was [added in 2025](https://make.wordpress.org/cli/2025/05/07/wp-cli-v2-12-0-release-notes/):

```
wp post list --tax_query='[{"taxonomy":"genre","field":"slug","terms":"horror"}]'
```
