### ISSUE TITLE
wp user import-csv should avoid destructively altering users by default

### ISSUE THREAD

**Issue by ryanmarkel** [wp-cli/wp-cli#1500]
`user import-csv` has an option marked `--skip-update` that forces it to avoid making destructive changes to user accounts that already exist based on the CSV fed to it.

For example, without the option selected, if you have "new" data in a row that also has existing user data, the script will overwrite user bits as it sees fit to get the old data to match. (It's overwritten usernames before.)

That amount of destructive power should not be the default behavior of anything you run on a WordPress site. I'd propose altering `user import-csv` so the update-skipping is the default behavior and require the option `--force-update` to grant it the ability to make destructive changes.

**Comment by Lewiscowles1986** [comment]
I just came to see any issues and it looks like there is a commit from @joshbetz in 2014 on this; looks like it's from the wp-cli repo so is `--force` now a flag, is `--skip-update` now dead, or are both in existence?

**Comment by danielbachhuber** [comment]
> looks like it's from the wp-cli repo so is --force now a flag, is --skip-update now dead, or are both in existence?

I think it looks like it's from the WP-CLI repo because @joshbetz must've deleted the original repo with the commit.

We just have the `--skip-update` flag: http://wp-cli.org/commands/user/import-csv/ At this point, I don't think it makes sense to change the behavior.
