### ISSUE TITLE
Add commands for site transients

### ISSUE THREAD

**Issue by mboynes** [wp-cli/wp-cli#1503]
Current transient command doesn't support [`get_site_transient()`](http://codex.wordpress.org/Function_Reference/get_site_transient), [`set_site_transient()`](http://codex.wordpress.org/Function_Reference/set_site_transient), and [`delete_site_transient()`](http://codex.wordpress.org/Function_Reference/delete_site_transient).

**Comment by szepeviktor** [comment]
@danielbachhuber Should they be `wp transient get name --site` or `wp transient get-site name`?

**Comment by szepeviktor** [comment]
Beacuse we use a WP core class, should I get update URL-s from `update_plugins` and `update_themes`?

**Comment by sebastiaandegeus** [comment]
@danielbachhuber am I still needed on this or is @szepeviktor picking this up?

**Comment by danielbachhuber** [comment]
Whomever submits the best pull request. We don't really have issue assignments

**Comment by szepeviktor** [comment]
@sebastiaandegeus Go for it and get the update URLs!

**Comment by szepeviktor** [comment]
...but first get an answer from @danielbachhuber on https://github.com/wp-cli/wp-cli/issues/1503#issuecomment-74387195

**Comment by danielbachhuber** [comment]
> Should they be wp transient get name --site or wp transient get-site name?

We should have `wp site transient <command>`, I think

**Comment by szepeviktor** [comment]
@sebastiaandegeus I seems like a copy&paste job.

**Comment by danielbachhuber** [comment]
> It seems like a copy&paste job.

Nope — won't merge a copy and paste job :wink:. I will merge a sensible abstraction, though.
