### ISSUE TITLE
Crash when attempting to download a beta version using a non-existant locale

### ISSUE THREAD

**Issue by Fab1en** [wp-cli/wp-cli#1509]
When I tried to download the latest beta with the french locale, I had the following crash :

    $>wp core download --locale=fr_FR --version=4.1-beta1
    Downloading WordPress 4.1-beta1 (fr_FR)...
    PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'internal corruption of phar "/tmp/wp_546fbd8325bab.tar.gz" (__HALT_COMPILER(); not found)' in phar:///usr/bin/wp/php/commands/core.php:181
    Stack trace:
    #0 phar:///usr/bin/wp/php/commands/core.php(181): PharData->__construct('/tmp/wp_546fbd8...')
    #1 phar:///usr/bin/wp/php/commands/core.php(167): Core_Command::_extract('/tmp/wp_546fbd8...', '/server/wordpre...')
    #2 [internal function]: Core_Command->download(Array, Array)
    #3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func(Array, Array, Array)
    #4 [internal function]: WP_CLI\Dispatcher\{closure}(Array, Array)
    #5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(293): call_user_func(Object(Closure), Array, Array)
    #6 phar:///usr/bin/wp/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
    #7 phar:///usr/bin/wp/php/WP_CLI/Runner.php(311): WP_CLI\Runner->run_command(Array, Array)
    #8 phar:///usr/bin/wp/php/WP_CLI/Runner.php(52): WP_CLI\Runn in phar:///usr/bin/wp/php/commands/core.php on line 181

Download without without specifying the locale DOES work :

    $> wp core download --version=4.1-beta1
    Downloading WordPress 4.1-beta1 (en_US)...
    Success: WordPress downloaded.

I update to the 0.17.1 WPCLI version, but the issue is still present. It would be great to have an error message.

**Comment by nyordanov** [comment]
@danielbachhuber I don't think that this is fixed. For example, try this:

```
> wp core download --version=4.1.0 --force
Downloading WordPress 4.1.0 (en_US)...
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'internal corruption of phar "/tmp/wp_5521145e1831a.tar.gz" (__HALT_COMPILER(); not found)' in phar:///usr/local/bin/wp/php/commands/core.php:190
Stack trace:
#0 phar:///usr/local/bin/wp/php/commands/core.php(190): PharData->__construct('/tmp/wp_5521145...')
#1 phar:///usr/local/bin/wp/php/commands/core.php(176): Core_Command::_extract('/tmp/wp_5521145...', '/home/vamtam/pu...')
#2 [internal function]: Core_Command->download(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(295): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(311): WP_CLI\Runner->run_comman in phar:///usr/local/bin/wp/php/commands/core.php on line 190

> cat /tmp/wp_55211685646a0.tar.gz 
Release not found.
```

The problem is that the supposedly .tar.gz file is just a plain text file containing "Release not found." Perhaps you need to catch the exception, and then check the contents of the downloaded file?

The problem here is that the error message (`UnexpectedValueException`) is not descriptive enough. Exiting with "Error: Release 4.1.0 (en_US) not found." would be better.

**Comment by danielbachhuber** [comment]
Good suggestion.
