### ISSUE TITLE
Precharge plugin cache

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1511]
On `wp plugin update-all` is it possible to minimize maintenance time by putting all to-be-updated plugins in the file cache?

**Comment by tmuka** [comment]
I came here to ask about this too. It would be nice if there was a way. Thanks!

**Comment by szepeviktor** [comment]
We only need to get someone who writes the PR.

**Comment by danielbachhuber** [comment]
This can be done with https://github.com/runcommand/precache
