### ISSUE TITLE
Modify wp-config parsing code to fix "String wp-config.php file" error

### ISSUE THREAD

**Issue by ben-rosio** [wp-cli/wp-cli#1514]
The standard procedure for new sites our company creates requires a wp-config.php file and a wp-config-global.php file.  The former has database credentials and isn't put in git, the latter has site wide configurations (like whether or not it's a multisite, the language, etc.).  wp-config.php requires wp-config-global.php, which then requires wp-settings.php.

The issue stems from the check on line [339 in Runner.php](https://github.com/wp-cli/wp-cli/blob/1a4266cebd3ca369291612b1550fd9a7d368e26c/php/WP_CLI/Runner.php#L339).

I have two potential solutions to this issue.  The first would be to just remove all require statements from wp-config.php.  It'd be the easiest method, but it'd also be a bit of a hack/brittle for people who want to subdivide their configurations even further than we do.

The second option would be to prepend the eval statement with: 

```php
define('WP_USE_THEMES', false);
define('WP_ALLOW_MULTISITE', false);
define('SHORTINIT', true);
```

This would cut down on what WordPress loads, and instead of having to regex php code wp-cli can instead just run through the init code and load the constants needed.

**Comment by danielbachhuber** [comment]
Related #1631

**Comment by danielbachhuber** [comment]
At a glance, `SHORTINIT` still seems too late because it's after:

```
if ( WP_CACHE )
	WP_DEBUG ? include( WP_CONTENT_DIR . '/advanced-cache.php' ) : @include( WP_CONTENT_DIR . '/advanced-cache.php' );
```

and:

```
// Initialize multisite if enabled.
if ( is_multisite() ) {
	require( ABSPATH . WPINC . '/ms-blogs.php' );
	require( ABSPATH . WPINC . '/ms-settings.php' );
} elseif ( ! defined( 'MULTISITE' ) ) {
	define( 'MULTISITE', false );
}
```

**Comment by danielbachhuber** [comment]
Closing in favor of #1631. `SHORTINIT` isn't early enough.
