### ISSUE TITLE
Add ability to NOT pass output through less

### ISSUE THREAD

**Issue by JPry** [wp-cli/wp-cli#1519]
Currently in non-Windows environments, when the `--help` flag is passed (or the help command is used), the output is always passed through `less`. When calling WP CLI from another script, it would be nice to have the ability to simply retrieve the help text as plain text, instead of passing it through `less`. Perhaps this could be something like a `--raw` flag.

**Comment by lsl** [comment]
For those who show up here from google.

Respecting `PAGER` was eventually added in https://github.com/wp-cli/wp-cli/pull/2264

```
PAGER=cat wp help
```
