### ISSUE TITLE
silently fails; exit code 0

### ISSUE THREAD

**Issue by mozai** [wp-cli/wp-cli#1534]
I've seen this happen on six different machines now.

Steps to reproduce:
moses@vps [/tmp]$ php --version
PHP 5.3.13 (cli) (built: Jun 26 2012 16:25:39) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with eAccelerator v0.9.6.1, Copyright (c) 2004-2010 eAccelerator, by eAccelerator
    with Suhosin v0.9.33, Copyright (c) 2007-2012, by SektionEins GmbH
moses@vps [/tmp]$ curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
moses@vps [/tmp]$ php wp-cli.phar --info
moses@vps [/tmp]$ echo $?
0

No output, no matter what parameter.  Exit status 0 ("success").
PHP version is sufficient (>5.3.2), Wordpress version is irrelevant because I don't even get that far.
How would I diagnose this?  Is there a debug-mode switch?

**Comment by vodou** [comment]
I had this issue today (after upgrading wp-cli to the latest version), and the solution for me was to add `suhosin.simulation = On` to the end of my CLI `php.ini`. Anyone know if there are security implications to this? (This is on a local test server, but I'd hate to do this on a production server and find out I shouldn't have.)

**Comment by szepeviktor** [comment]
Yes. It **turns OFF suhosin**. Add:
```ini
suhosin.executor.include.whitelist=phar
```

**Comment by mozai** [comment]
No don't do either of those.  You don't want suhosin turned off every time you run php or you run code in any PHarchive (*.phar)

Turn off suhosin ONLY when you're running wpcli from a terminal. This is what I use in bash:

    WPCLI() { sudo -u $(whoownshere) -- /usr/local/bin/php -d suhosin.simulation=On /usr/local/bin/wp-cli $* ; }

so then I can run "WPCLI plugin list" and it works properly.

**Comment by szepeviktor** [comment]
This is almost my uwp script
```bash
#!/bin/bash
#
# Execute wp-cli as the current directory's owner.
#
# VERSION       :0.1
# DATE          :2014-12-19
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/sbin/uwp

THIS_OWNER="$(stat . -c %U)"

sudo -u "$THIS_OWNER" --  wp --path="$(pwd)" "$@"
```
It works only in ABSPATH.

**Comment by szepeviktor** [comment]
On Debian based systems you have separate php.ini for CLI and other SAPI-s.

**Comment by vodou** [comment]
This is on an Ubuntu VM, and there are indeed separate `php.ini` files for CLI and my Apache server.
