### ISSUE TITLE
Wrong success message when unable to regenerate thumbnails because the file is missing

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/wp-cli#1540]
If an attachment exists in the database but is missing in the file system, `wp media regenerate` is unable to regenerate the thumbails but report success.

```
$ wp media regenerate 75
Found 1 image to regenerate.
Warning: Can't find "albatroz" (ID 75).
Success: Finished regenerating the image.
```

**Comment by danielbachhuber** [comment]
@rodrigoprimo if you had one warning and one success, what would you expect the end message to be?

Related #1430

**Comment by michalkleiner** [comment]
I think it could be just an "Info" prefix of the message like so:

Info: Finished regenerating the image.

Or empty:

Finished regenerating the image.
