### ISSUE TITLE
Can't delete hello dolly with wp-cli

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#1545]
wp plugin list
+-------+----------+--------+---------+
| name  | status   | update | version |
+-------+----------+--------+---------+
| hello | inactive | none   | 1.6     |
+-------+----------+--------+---------+

wp plugin delete hello
wp plugin uninstall hello

Nothing shows up. Is it maybe that the plugin doesn't use own folder?

P.S. Awesome work with wp-cli !

**Comment by voltronik** [comment]
I'm also getting this on Mac OS X 10.11.3 using WP-CLI 0.22.0.
Whilst in a WordPress installation root directory, using the command wp plugin delete hello from the terminal don'ts result in the hello.php file being deleted. wp plugin uninstall hello also has the same issue. 
No errors or messages are outputted and --debug doesn't reveal anything. 

If you use the  --deactivate flag on the uninstall command, it does say: 
`Warning: Plugin 'hello' isn't active.` but that's it.

**Comment by danielbachhuber** [comment]
> I'm also getting this on Mac OS X 10.11.3 using WP-CLI 0.22.0.

Given this originally was a Windows issue and you're on a Mac, it's probably not the same issue.

Deleting `hello` appears to work for me:

```
salty-wordpress ➜  wordpress-test.dev  wp plugin list --name=hello
+-------+----------+--------+---------+
| name  | status   | update | version |
+-------+----------+--------+---------+
| hello | inactive | none   | 1.6     |
+-------+----------+--------+---------+
salty-wordpress ➜  wordpress-test.dev  wp plugin delete hello
Success: Deleted 'hello' plugin.
salty-wordpress ➜  wordpress-test.dev  wp plugin list --name=hello
+------+--------+--------+---------+
| name | status | update | version |
+------+--------+--------+---------+
+------+--------+--------+---------+
```

If you can still reproduce, can you open a new issue with more details and steps to reproduce? We can also use it as an exercise to improve our [reporting a bug](http://wp-cli.org/docs/bug-reports/) doc.

**Comment by Frique** [comment]
I've got the same issue on OSX 10.10.5, WP CLI 0.23.0.
I can install plugins but not delete/uninstall any. It does print out a success message in the terminal, but the files are still there. It does work fine with themes.
