### ISSUE TITLE
Getting to MVP of the package command - browse, install, and update community commands

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1564]
Last year, I spent a lot of time trying to ship `wp package`, which would make community packages browsable and installable. After two consuming attempts, I burned out. #936 is a great read if you'd like all of the gory details.

However, the need is still there — WP-CLI users are creating interesting, useful commands that deserve the same level of visibility as core commands. Bundling a command with core only makes sense when it will be useful to 80-90% of users. But, when a command is only useful to 10% of users, or is early stage and needs to undergo a more regular release cycle, (e.g. #1557 and #1559), it should be really easy to find and install that command.

To make this happen, I'd love for one person step up and help out in a substantial way, and for a few others to volunteer to be early, thorough beta testers.

cc @mattes @boonebgorges @santagada @pixline @rodrigoprimo

**Comment by corradomatt** [comment]
Any update on this? I'm interested in installing some community packages....works with composer but just a few extra hoops to jump through at the moment since the package index is currently down.

**Comment by danielbachhuber** [comment]
No updates at this time.

**Comment by danielbachhuber** [comment]
Prototype landed in #2442

While I had a long debate previously with @scribu about this, where he was against it, I've decided to use a separate Composer project to manage community packages for two reasons:

1. Most WP-CLI installations are Phar-based these days, which makes @scribu's original points moot.
2. It avoids the potential for catastrophic breakage which blocked #936 from landing.

Community packages are installed to `~/.wp-cli/packages`, unless you specify a separate `WP_CLI_PACKAGES_DIR`. Composer generates a `vendor/autoload.php` for the project, and WP-CLI loads it in its bootstrap process.

We'll see how well this command works out :) Consider it a very early prototype, and liable to change (or be removed) I'd encourage all interested parties to run `wp cli update --nightly`, and try to break it as many ways as they can.

Couple things I'm already aware of:

* [ ] There's no clear way to `wp package update` yet.
* [ ] If your package autoload file is referencing a package that doesn't exist, it breaks WP-CLI. I don't know how we can validate the autoload file.

**Comment by danielbachhuber** [comment]
I'm going for it. This will land in v0.23.0, but be flagged as a beta feature as there are a few to several moderate usability issues to work out.
