### ISSUE TITLE
Exporting posts by term

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/wp-cli#1569]
For a client work, I replaced `--category=<name>` parameter of `wp export` with `--<taxonomy>=<term>` to make it possible to filter posts to be exported by a given term of any taxonomy and not just categories.

Let me know if you think this should be in WP-CLI core and I will create a pull request.

**Comment by rodrigoprimo** [comment]
I had to change the new exporter.

I'm using it only in the command line and I'm not sure if I will have time to add a user interface to it to create a patch to the new exporter on Trac. I'm also not sure if that ticket is the best place to discuss improvements to the new exporter since it is not even clear if WP will ever use it.

If it helps someone else the code to export posts by term can be found in the link below:

https://github.com/rodrigoprimo/wp-cli/commit/eca8cf9e0baea37d65aa54d20a1cb0fc22e75bac

**Comment by danielbachhuber** [comment]
At this point, I don't think we're going to make any large modifications to the exporter until there's clear direction from WordPress core on how the importer / exporter are intended to evolve. I'm not keen to maintain a fork.

For now, you could achieve similar results by using `wp export --post__in=$(wp post list --<taxonomy>=<term>)`
