### ISSUE TITLE
Fatal error: Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/wp-cli.php(23) : eval()'d code on line 91

### ISSUE THREAD

**Issue by simplenotezy** [wp-cli/wp-cli#1586]
I am trying to follow this guide: https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests

But when running:

```
wp scaffold plugin-tests my-plugin
```

It fails, and outputs:

```
Fatal error: Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/wp-cli.php(23) : eval()'d code on line 91
```

Running latest version of both WordPress and wp-cli (as I just installed it).

**Comment by danielbachhuber** [comment]
Created a new canonical issue for the `wp-config.php` problem #1631
