### ISSUE TITLE
Search Replace not working for domain name change

### ISSUE THREAD

**Issue by gpspake** [wp-cli/wp-cli#1592]
Cloning a site from production and moving to development environment so I'm going from site.company.com to sitedev.company.com

Once the database has been moved to the development domain, every instance of site.company.com must be changed to sitedev.company.com

I'm currently using [this tool](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) which works great but I'd like to be able to use wp-cli to add this functionality to a script.

After moving a site, though, the following returns an 'unable to connect to database' error ```wp search-replace 'site.company.com' 'sitedev.company.com'```

The tool mentioned above uses the contents of the wp-config file to connect to the database. If I drop it on the dev server and walk through the steps manually, it works with no problems. but based on the error, it seems like wp-cli does it differently. So is there something else I should be doing so it can connect to the database?

**Comment by rodrigoprimo** [comment]
`wp search-replace --url=site.company.com site.company.com sitedev.company.com` works.

It is not intuitive. After discussion on #1232, @danielbachhuber added this to the command examples but I think we could make it more explicit.

@danielbachhuber, what if we create a new command called `wp migrate-url old-domain new-domain` as an alias to `wp search-replace --url=old-domain old-domain new-domain`? Or maybe we could add a new flag to `wp search-replace` called `--migrate-url` or something like that?

**Comment by gpspake** [comment]
Ok, that seems to do something at least but after knocking out a few errors I'm down to this:
```PHP Fatal error:  Call to undefined function cli\mb_detect_encoding() in phar:///home/username/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/cli.php on line 164```
which looks like the same issue in #1537. Not sure what's going on there.
If it helps, I'm using PHP 5.3.3 on CentOS

**Comment by gpspake** [comment]
Update: I installed the mb_detect_encoding module which solved my previous issue. Now search replace completes but makes 0 replacements. I tried the following:

`wp search-replace --url=old-domain old-domain new-domain`
`wp search-replace --url=old-domain old-domain new-domain --precise`

Both complete successfully but make no changes. Just to ensure that I'm not confused and I'm using the correct strings, I tried the interconnectit search replace again and it worked.

**Comment by gpspake** [comment]
@danielbachhuber and @rodrigoprimo I really like the idea of aliasing this specifically to replace the domain, since that's probably the most common use case. One note there: It might be a good idea to include an option to replace it in wp-config.php as well in case it's hard-coded for multi-site installs.

**Comment by danielbachhuber** [comment]
> I really like the idea of aliasing this specifically to replace the domain, since that's probably the most common use case.

Eh, I don't really want to add an alias. You're welcome to create your own command though.

Were you able to track down why it wasn't performing any replacements?

**Comment by gpspake** [comment]
No; I'm still trying and it's still not working for me. Here are some more details...   
I'm moving a site from `site.company.com` to `sitedevl.company.com`
Once I've moved the database and the files from `site.company.com` to `sitedevl.company.com` I need to replace every instance of `site.company.com` in the database with `sitedevl.company.com`

Note: This is a multisite install so, at this point, the wpconfig file still defines the current domain as `site.company.com`:
```define( 'DOMAIN_CURRENT_SITE', 'site.company.com' );```
so if I try to go to `sitedevl.company.com` in a browser, I'm just redirected to the old site.

So if I run any of the following commands, nothing happens. I don't get any output at all:
```wp search-replace site.company.com sitedevl.company.com```
```wp search-replace --url=site.company.com site.company.com sitedevl.company.com```
```wp search-replace --url=site.company.com site.company.com sitedevl.company.com --precise```

If I change the entry in wpconfig to define the domain as `sitedevl.company.com`: 
```define( 'DOMAIN_CURRENT_SITE', 'sitedevl.company.com' );```
and got to `sitedevl.company.com` in a browser I'm no longer redirected but I get a database connection error (Since the database still contains `site.company.com`)

So let's see what happens now...  
Once I've changed the config file, all of the commands listed above return ```<h1>Error establishing a database connection</h1>``` which is the same output I get in a browser. This seems odd.

Finally, just to make sure I'm trying to do the right thing, I drop the [Interconnectit search replace tool](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) in my wp directory, navigate to it in my browser and do a search replace for `site.company.com` to `sitedevl.company.com` and it works and I can access the site from `sitedevl.company.com`

So, with all that being said, what could I be missing? Since `wp search-replace` command isn't giving me any output, is there anyway to see logs or find out what might be wrong?

**Comment by gpspake** [comment]
Update: I made some changes to my wp-cli config file and tried again and got the following: 
```
$ wp search-replace --url=site.company.com site.company.com sitedevl.company.com --precise

+------------------+-----------------------+--------------+------+
| Table            | Column                | Replacements | Type |
+------------------+-----------------------+--------------+------+
| wp_commentmeta   | meta_key              | 0            | PHP  |
| wp_commentmeta   | meta_value            | 0            | PHP  |
| wp_comments      | comment_author        | 0            | PHP  |
| wp_comments      | comment_author_email  | 0            | PHP  |
| wp_comments      | comment_author_url    | 0            | PHP  |
| wp_comments      | comment_author_IP     | 0            | PHP  |
| wp_comments      | comment_content       | 0            | PHP  |
| wp_comments      | comment_approved      | 0            | PHP  |
| wp_comments      | comment_agent         | 0            | PHP  |
| wp_comments      | comment_type          | 0            | PHP  |
| wp_links         | link_url              | 0            | PHP  |
| wp_links         | link_name             | 0            | PHP  |
| wp_links         | link_image            | 0            | PHP  |
| wp_links         | link_target           | 0            | PHP  |
| wp_links         | link_description      | 0            | PHP  |
| wp_links         | link_visible          | 0            | PHP  |
| wp_links         | link_rel              | 0            | PHP  |
| wp_links         | link_notes            | 0            | PHP  |
| wp_links         | link_rss              | 0            | PHP  |
| wp_options       | option_name           | 0            | PHP  |
| wp_options       | option_value          | 6            | PHP  |
| wp_options       | autoload              | 0            | PHP  |
| wp_postmeta      | meta_key              | 0            | PHP  |
| wp_postmeta      | meta_value            | 8            | PHP  |
| wp_posts         | post_content          | 1324         | PHP  |
| wp_posts         | post_title            | 0            | PHP  |
| wp_posts         | post_excerpt          | 0            | PHP  |
| wp_posts         | post_status           | 0            | PHP  |
| wp_posts         | comment_status        | 0            | PHP  |
| wp_posts         | ping_status           | 0            | PHP  |
| wp_posts         | post_password         | 0            | PHP  |
| wp_posts         | post_name             | 0            | PHP  |
| wp_posts         | to_ping               | 0            | PHP  |
| wp_posts         | pinged                | 0            | PHP  |
| wp_posts         | post_content_filtered | 0            | PHP  |
| wp_posts         | guid                  | 5266         | PHP  |
| wp_posts         | post_type             | 0            | PHP  |
| wp_posts         | post_mime_type        | 0            | PHP  |
| wp_term_taxonomy | taxonomy              | 0            | PHP  |
| wp_term_taxonomy | description           | 0            | PHP  |
| wp_terms         | name                  | 0            | PHP  |
| wp_terms         | slug                  | 0            | PHP  |
| wp_usermeta      | meta_key              | 0            | PHP  |
| wp_usermeta      | meta_value            | 7            | PHP  |
| wp_users         | user_login            | 0            | PHP  |
| wp_users         | user_nicename         | 0            | PHP  |
| wp_users         | user_email            | 0            | PHP  |
| wp_users         | user_url              | 0            | PHP  |
| wp_users         | user_activation_key   | 0            | PHP  |
| wp_users         | display_name          | 0            | PHP  |
+------------------+-----------------------+--------------+------+
Success: Made 6611 replacements.
```
The problem is... it still doesn't seem to work. After that, I still get a database connection error when I go to the site. So if I run interconnectit search replace in the browser again, it makes an additional 66005 replacements and the site works.

For reference here's my wp-cli config.yml file
```
path: /var/www/wordpress
debug: true
disabled_commands:
  - db drop
  - plugin install
core config:
        dbname: dbname
        dbuser: dbusername
        dbpass: dbpassword
```

**Comment by rodrigoprimo** [comment]
Since you are dealing with a multisite install you have to use the `--network` flag as well to perform changes in every table and not just in the tables of the main site.

**Comment by gpspake** [comment]
Aw snap. that did it @rodrigoprimo  
This is what ended up working:
```
wp search-replace --network --url=site.company.com site.company.com sitedevl.company.com --precise
```
Thanks for all the help guys.

**Comment by rodrigoprimo** [comment]
:+1:

**Comment by danielbachhuber** [comment]
@gpspake Is there something we could make more clear in the docs? http://wp-cli.org/commands/search-replace/

**Comment by gpspake** [comment]
@danielbachhuber Now that I understand everything, I think the docs cover it all pretty clearly. I probably could have done a better job of reading them :)

The only thing I could think of is maybe including an example with --url on the search-replace page since it might not work if you have one hardcoded in your config file. It makes sense to me now but I was missing that originally.

Once I got it working, I ended up setting up my own script to use search-replace and used sed to search and replace the same inputs in wp-config. I don't know if it would be dangerous to include that but if you're replacing  the domain on a network db, it's necessary. It might be nice to work that in as a --domain option or something.

**Comment by DrDamnit** [comment]
Had the same problem with a single-site. It should be noted here that you must create a config file (http://wp-cli.org/config/) in order for this to work.

**Comment by Bubelbub** [comment]
Its not working on windows.

    C:\xampp\htdocs\wordpress>wp search-replace example.org localhost
    +-------+--------+--------------+------+
    | Table | Column | Replacements | Type |
    +-------+--------+--------------+------+
    +-------+--------+--------------+------+
    Success: Made 0 replacements.

But this works.

    C:\xampp\htdocs\wordpress>wp user list
    +----+-------------+-------------+-------------+-------------+----------------+
    | ID | user_login  | display_nam | user_email  | user_regist | roles          |
    +----+-------------+-------------+-------------+-------------+----------------+
    | 1  | johndoe      | John Doe | john@doe.com | 2015-12-12  | administrator  |
    +----+-------------+-------------+-------------+-------------+----------------+

And on Linux it's working, too.
I installed wp-cli through the composer.phar in C:\xampp\wp-cli and added C:\xampp\wp-cli\bin in the PATH settings.

**Comment by displaynone** [comment]
I now it is closed. 

I had the same issue, the problem was that you have to remove quotes:

> wp search-replace 'site.company.com' 'sitedev.company.com'

Change it for

`wp search-replace site.company.com sitedev.company.com`

**Comment by Dibbyo456** [comment]
@displaynone great catch. 👍

**Comment by despecial** [comment]
This doesn't seem to work with custom Gutenberg blocks

**Comment by DrLightman** [comment]
> I had the same issue, the problem was that you have to remove quotes:
> > wp search-replace 'site.company.com' 'sitedev.company.com'
> Change it for
> `wp search-replace site.company.com sitedev.company.com`

Not working for me with or without quotes.
[Docs](https://developer.wordpress.org/cli/commands/search-replace/) explicitly use quotes though.

**Comment by NicoHood** [comment]
Hi,
I am currently facing that not all of my urls are replaced by the search & replace command. The urls of the RankMath Seo plugin are still kept with the old domain. I found this github post and now I am a bit confused.

That's what I am using:
```
wp search-replace https://example.com https://test.example.com
```

But what is the difference to the following? Is anything of it better?
```
wp search-replace https://example.com/ https://test.example.com/
wp search-replace example.com test.example.com
wp search-replace --url=example.com test.example.com
```

**Comment by DrLightman** [comment]
NicoHood, did you try with --precise switch?
I had always run it with single quotes with no issues by the way.

test:
`wp search-replace 'OLD' 'NEW' --dry-run --precise`

real:
`wp search-replace 'OLD' 'NEW' --precise`

**Comment by NicoHood** [comment]
That does not seem to make any difference.

**Comment by chesio** [comment]
@NicoHood URLs stored in JSON are problematic to replace, see: https://github.com/wp-cli/wp-cli/issues/3753 Perhaps that's your case too?

**Comment by NicoHood** [comment]
How can I find out how the plugin stores the data?

**Comment by DrLightman** [comment]
By analyzing the plugin source code

**Comment by NicoHood** [comment]
So I just finally checked the database with the help of the rankmath support.

To better understand, here is a real-world example of a rankmath redirection:
![grafik](https://user-images.githubusercontent.com/6888294/198013535-55b1fe0d-7b96-46ab-a265-f5ca5906cc45.png)

And this is the database entry:
![grafik](https://user-images.githubusercontent.com/6888294/198013585-4bb08a89-b687-4f7d-9c8b-6134021ccf07.png)
![grafik](https://user-images.githubusercontent.com/6888294/198013622-ef105015-b8e2-4431-b3be-abe17addcfae.png)

To me this looks like it should be able to work with search&replace, but it does NOT. Why?

Any ideas?

**Comment by NicoHood** [comment]
What I noticed is, that the search & replace does not look up this table at all. The table name is `9aISZzD3Nr_rank_math_redirections ` in this case.

```
$ wp search-replace 'https://partyborn.de' 'https://test.partyborn.de' --dry-run --precise
+--------------------------+-----------------------------+--------------+------+
| Table                    | Column                      | Replacements | Type |
+--------------------------+-----------------------------+--------------+------+
| 9aISZzD3Nr_actionschedul | hook                        | 0            | PHP  |
| er_actions               |                             |              |      |
| 9aISZzD3Nr_actionschedul | status                      | 0            | PHP  |
| er_actions               |                             |              |      |
| 9aISZzD3Nr_actionschedul | args                        | 0            | PHP  |
| er_actions               |                             |              |      |
| 9aISZzD3Nr_actionschedul | schedule                    | 0            | PHP  |
| er_actions               |                             |              |      |
| 9aISZzD3Nr_actionschedul | extended_args               | 0            | PHP  |
| er_actions               |                             |              |      |
| 9aISZzD3Nr_actionschedul | slug                        | 0            | PHP  |
| er_groups                |                             |              |      |
| 9aISZzD3Nr_actionschedul | message                     | 0            | PHP  |
| er_logs                  |                             |              |      |
| 9aISZzD3Nr_commentmeta   | meta_key                    | 0            | PHP  |
| 9aISZzD3Nr_commentmeta   | meta_value                  | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_author              | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_author_email        | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_author_url          | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_author_IP           | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_content             | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_approved            | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_agent               | 0            | PHP  |
| 9aISZzD3Nr_comments      | comment_type                | 0            | PHP  |
| 9aISZzD3Nr_links         | link_url                    | 0            | PHP  |
| 9aISZzD3Nr_links         | link_name                   | 0            | PHP  |
| 9aISZzD3Nr_links         | link_image                  | 0            | PHP  |
| 9aISZzD3Nr_links         | link_target                 | 0            | PHP  |
| 9aISZzD3Nr_links         | link_description            | 0            | PHP  |
| 9aISZzD3Nr_links         | link_visible                | 0            | PHP  |
| 9aISZzD3Nr_links         | link_rel                    | 0            | PHP  |
| 9aISZzD3Nr_links         | link_notes                  | 0            | PHP  |
| 9aISZzD3Nr_links         | link_rss                    | 0            | PHP  |
| 9aISZzD3Nr_options       | option_name                 | 0            | PHP  |
| 9aISZzD3Nr_options       | option_value                | 0            | PHP  |
| 9aISZzD3Nr_options       | autoload                    | 0            | PHP  |
| 9aISZzD3Nr_postmeta      | meta_key                    | 0            | PHP  |
| 9aISZzD3Nr_postmeta      | meta_value                  | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_content                | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_title                  | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_excerpt                | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_status                 | 0            | PHP  |
| 9aISZzD3Nr_posts         | comment_status              | 0            | PHP  |
| 9aISZzD3Nr_posts         | ping_status                 | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_password               | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_name                   | 0            | PHP  |
| 9aISZzD3Nr_posts         | to_ping                     | 0            | PHP  |
| 9aISZzD3Nr_posts         | pinged                      | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_content_filtered       | 0            | PHP  |
| 9aISZzD3Nr_posts         | guid                        | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_type                   | 0            | PHP  |
| 9aISZzD3Nr_posts         | post_mime_type              | 0            | PHP  |
| 9aISZzD3Nr_snippets      | name                        | 0            | PHP  |
| 9aISZzD3Nr_snippets      | description                 | 0            | PHP  |
| 9aISZzD3Nr_snippets      | code                        | 0            | PHP  |
| 9aISZzD3Nr_snippets      | tags                        | 0            | PHP  |
| 9aISZzD3Nr_snippets      | scope                       | 0            | PHP  |
| 9aISZzD3Nr_term_taxonomy | taxonomy                    | 0            | PHP  |
| 9aISZzD3Nr_term_taxonomy | description                 | 0            | PHP  |
| 9aISZzD3Nr_termmeta      | meta_key                    | 0            | PHP  |
| 9aISZzD3Nr_termmeta      | meta_value                  | 0            | PHP  |
| 9aISZzD3Nr_terms         | name                        | 0            | PHP  |
| 9aISZzD3Nr_terms         | slug                        | 0            | PHP  |
| 9aISZzD3Nr_usermeta      | meta_key                    | 0            | PHP  |
| 9aISZzD3Nr_usermeta      | meta_value                  | 0            | PHP  |
| 9aISZzD3Nr_users         | user_login                  | 0            | PHP  |
| 9aISZzD3Nr_users         | user_nicename               | 0            | PHP  |
| 9aISZzD3Nr_users         | user_email                  | 0            | PHP  |
| 9aISZzD3Nr_users         | user_url                    | 0            | PHP  |
| 9aISZzD3Nr_users         | user_activation_key         | 0            | PHP  |
| 9aISZzD3Nr_users         | display_name                | 0            | PHP  |
+--------------------------+-----------------------------+--------------+------+
```

**Comment by wojsmol** [comment]
Then add`--all-tables-with-prefix` or `--all-tables` flags - see [documentation](https://developer.wordpress.org/cli/commands/search-replace/)

**Comment by NicoHood** [comment]
Thank you so much!
