### ISSUE TITLE
Error establishing a database connection, even though `wp db query` works

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#1593]
This happened in the process of setting up WP from scratch, using only WP-CLI.

```
$ wp cli version
WP-CLI 0.17.1
$ wp core version
4.1
$ wp db query 'SHOW TABLES';
+-----------------------+
| Tables_in_wp-server-8 |
+-----------------------+
| test                  |
+-----------------------+
$ wp core install
Error:
<h1>Error establishing a database connection</h1>
<p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code>localhost</code>. This could mean your host's database server is down.</p>
<ul>
	<li>Are you sure you have the correct username and password?</li>
	<li>Are you sure that you have typed the correct hostname?</li>
	<li>Are you sure that the database server is running?</li>
</ul>
<p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>
```

**Comment by danielbachhuber** [comment]
What's the source of the problem connecting to the database?

**Comment by scribu** [comment]
It looks like it's some sort of misconfiguration on my machine. WP tries to connect to MySQL through a Unix socket and can't find it.

The quick fix was to change `wp-config.php`, from `define('DB_HOST', 'localhost');` to `define('DB_HOST', '127.0.0.1');`

More details here: http://stackoverflow.com/a/13771199/97998

**Comment by cfxd** [comment]
Just want to thank you for posting this. I experienced the same issue while trying to perform a `wp media regenerate`. Almost all other commands worked and changing my `DB_HOST` to `127.0.0.1` from `localhost` did the trick. Thank you 🙏🏻

**Comment by SuperstrongBE** [comment]
Encounter the same issue ! Solved. @cfxd Say thank for the trick !

**Comment by betweenbrain** [comment]
Just adding that I also ran into this issue, and changing the wp-config.php, from `define('DB_HOST', 'localhost');` to `define('DB_HOST', '127.0.0.1')`; solved the issue. Since `localhost` is the WordPress default, is this some WP-CLI could handle?

**Comment by schlessera** [comment]
@betweenbrain This is problem with your environment configuration. WP-CLI should not arbitrarily replace host strings and make wild guesses in such a way.

What I might consider though is to have WP-CLI detect this case on non-UNIX systems and produces a hint about what the likely problem might be.

**Comment by azizultex** [comment]
Hi @scribu, I'm on docker where `wp-config.php` has 

`/** MySQL hostname */
define('DB_HOST', 'db:3306');
`
How do I solve that?

**Comment by khandelwaly** [comment]
Hi @azizultex 
I also have the same issue, how did you solve this

**Comment by azizultex** [comment]
@khandelwaly 
I can't remember if I was able to solve it. I was using Linux now moved to MacOS.

**Comment by AdsonCicilioti** [comment]
@azizultex i'm on MacOs and the problem is the same. WP cli with wordpress+mysql docker wirks for you on MacOS? You can share your docker-compose.yml or setup containers options?

**Comment by nydame** [comment]
I have the same problem. WP CLI works inside the docker container, but can't connect to the database.

**Comment by Kipjr** [comment]
Got the same issue, trying to find a workaround for this:
#5513

**Comment by MatzeKitt** [comment]
You can try to add `db` as host in Docker:

```
docker run --add-host db:127.0.0.1 -ti [Source_Container_Image] /bin/bash
```
