### ISSUE TITLE
Need skip themes option

### ISSUE THREAD

**Issue by oneumyvakin** [wp-cli/wp-cli#1594]
There "skip-plugins" option in config, but there is no option to skip themes loading.

Is there a chance for implementation of this option in future releases?

**Comment by danielbachhuber** [comment]
Could you provide a bit more detail as to why it would be useful?

**Comment by oneumyvakin** [comment]
It's same issue as i've described here https://github.com/wp-cli/wp-cli/issues/1483
I have a lot of WordPress instances with a non-public or commercial themes and plugins which code quality is low. I'm not a owner of this WordPress instances so I can't just fix it, or report bugs to a vendors(because it's actually a lot of different vendors), or disable theme. 

Right now I'm using my own patches on wp-cli, but they are not production ready.

**Comment by danielbachhuber** [comment]
Fair enough. I'm open to a pull request for this feature then.

**Comment by QWp6t** [comment]
Wouldn't it be as simple as setting the constant `WP_USE_THEMES` to false?

**Comment by oneumyvakin** [comment]
I've create PR #1595, may be it can help you.
