### ISSUE TITLE
Trying to modify blog_public on network install has no effect

### ISSUE THREAD

**Issue by shurik** [wp-cli/wp-cli#1597]
1. Be using a network WordPress install
2. Try to use wp option update with blog_public

```
$ wp option get blog_public
0
$ wp option update blog_public 1
Success
$ wp option get blog_public
0
```

**Comment by danielbachhuber** [comment]
Is this a fresh install of WordPress, or an existing install with plugins, custom theme, etc?

If the latter, can you try against a fresh install of WordPress? It may be some code specific to your instance.

If the former, can you share your environment details, including any persistent object cache you may be running?
