### ISSUE TITLE
Can't install packages.

### ISSUE THREAD

**Issue by tillkruss** [wp-cli/wp-cli#1598]
When I run the suggested command from [Community-Packages](https://github.com/wp-cli/wp-cli/wiki/Community-Packages).

    composer require danielbachhuber/wp-cli-stat-command=dev-master

or

    php composer.phar require danielbachhuber/wp-cli-stat-command=dev-master

I receive the following error:

    [Composer\Downloader\TransportException]                                                                                       
      The "http://wp-cli.org/package-index/include/all$cc60c5b828017a7c5627c4edfd8afe1a341d368c.json" file could not be downloaded   
      (HTTP/1.1 404 Not Found)

**Comment by danielbachhuber** [comment]
I've taken down the package index while we figure out its future: #1564
