### ISSUE TITLE
search replace regular expressions

### ISSUE THREAD

**Issue by yivi** [wp-cli/wp-cli#1600]
Is it possible somehow to use regular expressions on 'wp search-replace', as you can in https://github.com/interconnectit/Search-Replace-DB?

If not, maybe that project could be a good place to look to "borrow" that feature in the future. :)

**Comment by danielbachhuber** [comment]
Just does `str_replace()` right now, but I suppose we could consider regex. I suspect the performance impact would be significant.

**Comment by sebastiaandegeus** [comment]
Maybe make it optional to use a regex but not by default so normal replace can remain fast.

**Comment by yivi** [comment]
Yup, I think that optional regex would be the way to go. But having the option would be a lifesaver ocasionally. Again, in the project I mentioned early that's the way it works: regular search unless you specify regex.
