### ISSUE TITLE
`wp core config` incompatible with core subfolder

### ISSUE THREAD

**Issue by lukerollans** [wp-cli/wp-cli#1601]
If WordPress core is in a subfolder such as `wp` for example, `wp core config` will generate `wp-config.php` and place it in that directory. `wp-config-php` would ideally be created within the current directory so subfolder installs do not break

**Comment by jmslbam** [comment]
You could pass `--path=wp` or add it to your `wp-cli.yml` in your projects webroot:
```
path: wp
```

**Comment by danielbachhuber** [comment]
@lukerollans Did you already have `index.php` created in your root directory? How should WP-CLI programmatically determine where your `wp-config.php` should be?

**Comment by lukerollans** [comment]
@danielbachhuber index.php is indeed in the root directory. I'm confused as to the need for logic as `wp-config.php` should always be in the root?

**Comment by danielbachhuber** [comment]
> I'm confused as to the need for logic as wp-config.php should always be in the root?

Sure — but WP-CLI doesn't understand this currently.

WP-CLI knows how to *find* the `wp-config.php` file when it's a part of a subdirectory install, but it doesn't know that sometimes it should *put* the `wp-config.php` file in a different directory.

In fact, I don't know that we could support this, unless we did some fancy sniffing of the `index.php` for a non-standard `ABSPATH`. There aren't any other indicators that it's a subdirectory install.

**Comment by lukerollans** [comment]
Is it possible to add an option to write the resultant wp-config.php file to the current directory `wp` is running from?

**Comment by danielbachhuber** [comment]
`wp core config` is already a [mess of options](http://wp-cli.org/commands/core/config/). I'm not keen on adding yet another option for a use case of limited utility.

**Comment by lukerollans** [comment]
I wouldn't agree that WordPress core in a subfolder is of limited utility, but thanks for your time
