### ISSUE TITLE
wp rewrite flush

### ISSUE THREAD

**Issue by yivi** [wp-cli/wp-cli#1602]
When I flush my rewrite rules by going to the dashboard->settings->permalinks my rewrite rules are saved properly to the DB, and I get this:
![_mysql_5_5_38__localhost_yosilose_ysls_options](https://cloud.githubusercontent.com/assets/1815039/5691647/d9ca03d4-98d2-11e4-811f-8e3db6aff72f.png)
Notice there are 118 rules in the array.

But after running wp rewrite flush I get only this:
![_mysql_5_5_38__localhost_yosilose_ysls_options](https://cloud.githubusercontent.com/assets/1815039/5691655/086c9378-98d3-11e4-902a-fc87e8fe12fd.png)
Now there are only 68 rules in the array, and obviously many of my custom routes, defined in CPTs, plugins or taxonomies are not working...

Am I doing something wrong? Is this the expected behavior?

Thanks and regards

**Comment by danielbachhuber** [comment]
> Is this the expected behavior?

> Am I doing something wrong?

It sounds like your CPTs and custom taxonomies are registered incorrectly, and not loading when WP-CLI is setting your rewrite rules. Hard to say specifically without having access to your codebase.
