### ISSUE TITLE
"wp core config" doesn't check connection on its database

### ISSUE THREAD

**Issue by athoune** [wp-cli/wp-cli#1603]
The wordpress user doesn't have to connect the whole mysql server, only on its database. If you creat a restricted user, the check feature fails.

core.php#338

**Comment by danielbachhuber** [comment]
What if the database isn't yet created?

What would you expect the behavior to be instead?

**Comment by athoune** [comment]
I work with old school sysadmins. Table and user creations are admin jobs, not a developer task.
But devops exist, and they can create their own db. I don't know what can be the "right behavior". Something like --restricted-user, --mutualized-db ?

**Comment by danielbachhuber** [comment]
Oh. You should use `--skip-check`, which is why the flag was added #1068
