### ISSUE TITLE
List all registered taxonomies

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1604]
Is there a plan to list all registered taxonomies?
Maybe filtered by post type.

**Comment by danielbachhuber** [comment]
Yes #1474

**Comment by szepeviktor** [comment]
Thank you! i've searched and not found.

**Comment by szepeviktor** [comment]
Oh no! I mean list taxonomies only:
`wp taxonomy list`

**Comment by szepeviktor** [comment]
Sorry. I got it now.

**Comment by szepeviktor** [comment]
Is there anyone taking care of it?
