### ISSUE TITLE
Fix rate-limited requests to Github API

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1612]
In #1535, we added `wp cli update` and the corresponding test coverage. However, Github's API is rate-limited to 60 requests/hour, so it's failing the build quite often:

![image](https://cloud.githubusercontent.com/assets/36432/5758738/ce130f7e-9c7c-11e4-9ad1-ac553c61be8c.png)

Previously #1605

**Comment by danielbachhuber** [comment]
@szepeviktor Want to research this a bit? I think what we'll need to do is mock the Github API response when the build is running in Travis. It would be nice if we could do this without too much refactoring though.

**Comment by danielbachhuber** [comment]
Isn't working for some reason :(

**Comment by szepeviktor** [comment]
Try `error_log()`-ging here: https://github.com/wp-cli/wp-cli/blob/f4dac3bef26c57285ba898f8424ceb36ae80cf14/php/utils.php#L438

**Comment by danielbachhuber** [comment]
When I set `export WP_CLI_REQUESTS_CACHE_DIR=/tmp/wp-cli-requests-cache-dir` locally and ran cli tests with `error_log()`, it hits the cache. Not sure why Travis would be different, unless the cache directory isn't being copied into location for some reason.

**Comment by szepeviktor** [comment]
Isn't `mkdir WP_CLI_REQUESTS_CACHE_DIR` missing?

**Comment by danielbachhuber** [comment]
> Isn't mkdir WP_CLI_REQUESTS_CACHE_DIR missing?

`cp` takes care of it, no? https://github.com/wp-cli/wp-cli/blob/master/ci/prepare.sh#L21

**Comment by szepeviktor** [comment]
Yes.
Sorry.

**Comment by szepeviktor** [comment]
You could also `error_log()` into Travis log?

**Comment by danielbachhuber** [comment]
Well, I think it's clear that it's not hitting the cache. The question is: why?

**Comment by danielbachhuber** [comment]
The cache key changed somehow so it was expecting a file that didn't exist #1625

**Comment by szepeviktor** [comment]
I am happy that you've found it out.

**Comment by szepeviktor** [comment]
I was putting this in `http_request()`:

```php
error_log('HTTP/'.serialize($request->status_code));
error_log('Response:'.serialize($request->headers));
```

**Comment by szepeviktor** [comment]
WARNING!
https://github.com/wp-cli/wp-cli/blob/f4dac3bef26c57285ba898f8424ceb36ae80cf14/php/utils.php#L435
Headers contain ever-changing dates.

**Comment by szepeviktor** [comment]
What could have changed?

```php
hash_hmac( 'sha256', 'requests_' . $url . serialize( $headers ) . serialize( $data ) . serialize( $options ), '' )
```

**Comment by danielbachhuber** [comment]
> What could have changed?

I must've changed the key after I generated the cache file. The headers are the request headers, and don't include dates.
