### ISSUE TITLE
Properly escape quotes with search-replace

### ISSUE THREAD

**Issue by kovshenin** [wp-cli/wp-cli#1613]
When I run a search-replace and use a double-quote `"` as part of the search string, it's placed as is in the SQL query, causing a `"%"foo` search which obviously fails. I've tried escaping it with a backslash, but unfortunately my backslash is escaped by a backslash, so `\"` becomes `\\"` in the query.

**Comment by danielbachhuber** [comment]
Interesting... I'll take a look further. Thanks for the report!

**Comment by tmuka** [comment]
i ran into this issue today too. eg.
wp search-replace 'src="http://some.dev' ' src="http://some.livedomain.com'

**Comment by tobyhage** [comment]
i ran into this issue today too. is there already a fix?

**Comment by danielbachhuber** [comment]
> is there already a fix?

Not yet. Pull requests welcome.

**Comment by kossmann** [comment]
Any workaround until there is no fix?

**Comment by here** [comment]
@kossmann @tobyhage -- Use regex support? :)

https://github.com/wp-cli/wp-cli/issues/1600
https://github.com/wp-cli/wp-cli/pull/1861

**Comment by janmazanek** [comment]
The same problem on my installation. Double quotes are not escaped:
 
Error: Database error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%" LIMIT 1000 OFFSET 0' at line 1

<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;%&quot;&#039; at line 1]<br /><code>SELECT COUNT(*) FROM wp_options  WHERE `option_value` LIKE &quot;%www.vyrobnihaly.cz/ll&quot;%&quot;</code></p></div><div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;%&quot; LIMIT 1000 OFFSET 0&#039; at line 1]<br /><code>SELECT `option_id`, `option_value` FROM wp_options  WHERE `option_value` LIKE &quot;%www.vyrobnihaly.cz/ll&quot;%&quot; LIMIT 1000 OFFSET 0</code></p></div>
