### ISSUE TITLE
Cannot successfully export and import database

### ISSUE THREAD

**Issue by jason404** [wp-cli/wp-cli#1617]
I tried exporting the database from one WordPress instance, within its directory:

    $ wp db export /srv/www/collx/dcduo_collx.sql

Then within the site directory to import it I get this error:

    $ wp import dcduo_collx.sql --authors=create
    Starting the import process...
    Warning: This does not appear to be a WXR file, missing/invalid WXR version number

What am I doing wrong?

**Comment by danielbachhuber** [comment]
`wp import` expects a WXR file: http://wp-cli.org/commands/import/

You want to use `wp db import`: http://wp-cli.org/commands/db/import/
