### ISSUE TITLE
Empty install-wp-tests.sh file

### ISSUE THREAD

**Issue by jawittdesigns** [wp-cli/wp-cli#1620]
I followed @pippinsplugins [tutorial](https://pippinsplugins.com/unit-tests-wordpress-plugins-setting-up-testing-suite/) for setting up unit tests for plugins, but I've been having all types of issues.

Maybe I don't get something, but do I need to go through the install every time I reboot my PC? The library in the tmp directory gets erased ( I guess that makes sense ), and all the code in the install-wp-tests.sh gets erased when I run tests. 

So I have to re-setup everything every time I reboot. Is this normal?

Also the install doesn't create the uploads folder in the tmp library, so I have to add it by hand.

**Comment by danielbachhuber** [comment]
> all the code in the install-wp-tests.sh gets erased when I run tests.

You mean, all of the code that `install-wp-tests.sh` add gets erased, or the actual file itself? In either case, neither of these should be helping.

> So I have to re-setup everything every time I reboot. Is this normal?

Yes, the script downloads all of the files to the `/tmp` directory, which means the files get deleted on reboot. You can instead download the files to persistent directories, and set the `WP_TESTS_DIR` and `WP_CORE_DIR` environment variables to have the tests run against your alternate downloads: https://github.com/wp-cli/wp-cli/blob/master/templates/install-wp-tests.sh#L14

> Also the install doesn't create the uploads folder in the tmp library, so I have to add it by hand.

This should happen when WordPress is installed. Did you wait that long?

**Comment by jawittdesigns** [comment]
> You mean, all of the code that install-wp-tests.sh add gets erased, or the actual file itself? In either case, neither of these should be helping.

All the code in the file gets erased as soon as I run a test

> This should happen when WordPress is installed. Did you wait that long?

Well, I waited until it was done. It wasn't unusually long.

**Comment by danielbachhuber** [comment]
Hm. I don't have any good ideas as to how this might be happening without seeing it myself. Any chance you can share a screencast of the bug in action?

**Comment by jawittdesigns** [comment]
Yeah, I'm not too sure about it either. 

I was using MAMP, so I uninstalled that and just set up a basic Apache, mySQL, PHP stack. That seemed to work, because now everything is working fine. I'm not even sure if I can reproduce the issue now.

**Comment by danielbachhuber** [comment]
Ok. We can revisit again in the future if it's reproducible.
