### ISSUE TITLE
Is there a way to copy all meta data from one post to another?

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1621]
`wp post meta list 503 --format=json --fields=meta_key,meta_value` returns a JSON.
(For polylang translation of a site with Pods.)

Not a solution:

```bash
#!/bin/bash

FROM_POST=$1
TO_POST=$2

for META in $(wp post meta list $FROM_POST --fields=meta_key|tail -n +2); do

    echo "copy $META from $FROM_POST -> $TO_POST"
    eval wp post meta update $TO_POST $META \'$(wp post meta get $FROM_POST $META --format=json)\' --format=json

done
```

**Comment by danielbachhuber** [comment]
> Is there a way to copy all meta data from one post to another?

I can't think of an easy way, off the top of my head. This is a problem I tried to solve with [Dictator](https://github.com/danielbachhuber/dictator), and may come back around to again. Do you have any suggestions?

**Comment by szepeviktor** [comment]
A community command, and then - myabe - a merge.

**Comment by danielbachhuber** [comment]
Sounds good.
