### ISSUE TITLE
why doesn't wp shell reflect new changes?

### ISSUE THREAD

**Issue by montchr** [wp-cli/wp-cli#1623]
If I run `wp shell`, then change a method and save the file, the output remains the same as before the change. Why is this?

**Comment by danielbachhuber** [comment]
You're changing the method on the class, and re-executing that method?

`wp shell` is one PHP process where all of the code is loaded into memory.

**Comment by montchr** [comment]
Correct. I was expecting behavior similar to the old Debug Bar Console which reflects changes on the fly, but this behavior makes sense in the case of `wp shell`. Thanks.
