### ISSUE TITLE
Running search command causes Undefined index: SERVER_NAME PHP error

### ISSUE THREAD

**Issue by codecowboy** [wp-cli/wp-cli#1630]
If I try:

```wp search-replace '#dd9933' '#FFFFFF' --dry-run```

I get:

```PHP Notice:  Undefined index: SERVER_NAME in /usr/share/wp-cli/php/wp-cli.php(23) : eval()'d code on line 92```

Wordpress version 4.1 running on Ubuntu 14.04 under vagrant. wp-cli version : 

```PHP binary:	/usr/bin/php5
PHP version:	5.6.4-1+deb.sury.org~trusty+1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	/usr/share/wp-cli
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.18.0```

**Comment by codecowboy** [comment]
Looks like I need a config file containing:

```url: http://local.mydevsite
user: myser
color: false
core config:
	dbuser: dbuser
	dbpass: dbpass
	extra-php: |
		define( 'WP_DEBUG', true );```

**Comment by danielbachhuber** [comment]
`SERVER_NAME` isn't set by default, but is set when you supply `--url`.

Can you share the contents of your `wp-config.php`, minus any secrets?

**Comment by szepeviktor** [comment]
I think @codecowboy hase some cli-unaware logic in `wp-config.php`.
