### ISSUE TITLE
Sanitychecking environmentvariables regarding locales

### ISSUE THREAD

**Issue by MikeMikjaer** [wp-cli/wp-cli#1632]
I get the following error when running the version available on the webpage:

www-data@www:~$ php wp-cli.phar plugin status
PHP Notice:  Use of undefined constant ‘WPLANG’ - assumed '‘WPLANG’' in phar:///var/www/wp-cli.phar/php/wp-cli.php(23) : eval()'d code on line 71
PHP Notice:  Use of undefined constant ‘da_DK’ - assumed '‘da_DK’' in phar:///var/www/wp-cli.phar/php/wp-cli.php(23) : eval()'d code on line 71
[snip]

www-data@www:~$ php wp-cli.phar --info       
PHP binary:	/usr/bin/php5
PHP version:	5.4.35-0+deb7u2
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.18.0

Im going to download from git to se wether the error persists and if i find it does im going to investegate further ... however if anybody seen this before please provide insight if posible.

**Comment by danielbachhuber** [comment]
Seems like your `wp-config.php` references constants that aren't defined. Can you share its contents here (minus any secrets) ?

**Comment by MikeMikjaer** [comment]
I suspect this is the culprit: (from wp-config.php)

define(?~@~XWPLANG?~@~Y, ?~@~Xda_DK?~@~Y);

**Comment by MikeMikjaer** [comment]
I changed it to:

define("WPLANG", "da_DK");

Now the warning's gone.

Should we implement some way of validating the php-code before we invoke it?

**Comment by danielbachhuber** [comment]
It's ultimately a problem of #1631, which we need to solve more holistically.

**Comment by MikeMikjaer** [comment]
Fair .. i wont submit a patch then :-)
