### ISSUE TITLE
search-replace outside quotes if no space

### ISSUE THREAD

**Issue by esaheiskanen** [wp-cli/wp-cli#1633]
wp search-replace "http://olddomain.xx" "http://newdomain.yy"--skip-columns=guid (no space)

replaces first parameter "http://olddomain.xx" with "http://newdomain.yy%3d--skip-columns=guid" 

This is propably never wanted result.

**Comment by danielbachhuber** [comment]
I don't think this is something we can support within WP-CLI, as the argument splitting happens at the PHP level.
