### ISSUE TITLE
Fatal error after activating plugin "backupwordpress"

### ISSUE THREAD

**Issue by mjot** [wp-cli/wp-cli#1635]
After installing and activating the "backupwordpress" plugin, I get the following error. It's not possible to use one of the wp cli commands. Hope someone has an idea.

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class BackUpCommand does not exist' in phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:20
Stack trace:
#0 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(20): ReflectionClass->__construct('BackUpCommand')
#1 phar:///usr/local/bin/wp/php/class-wp-cli.php(194): WP_CLI\Dispatcher\CommandFactory::create('backupwordpress', 'BackUpCommand', Object(WP_CLI\Dispatcher\RootCommand))
#2 /srv/wp/html/wp-content/plugins/backupwordpress/classes/class-backupwordpress-wp-cli-command.php(115): WP_CLI::add_command('backupwordpress', 'BackUpCommand')
#3 /srv/wp/html/wp-content/plugins/backupwordpress/backupwordpress.php(185): include('/srv/localserve...')
#4 /srv/wp/html/wp-content/plugins/backupwordpress/backupwordpress.php(83): HM\BackUpWordPress\Plugin->includes()
#5 [internal function]: HM\BackUpWordPress\Plugin->plugins_loaded('')
#6 /srv/wp/html/wp-includes/plugin.php(496): call_us in phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php on line 20
Fatal error: Uncaught exception 'ReflectionException' with message 'Class BackUpCommand does not exist' in phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:20
Stack trace:
#0 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(20): ReflectionClass->__construct('BackUpCommand')
#1 phar:///usr/local/bin/wp/php/class-wp-cli.php(194): WP_CLI\Dispatcher\CommandFactory::create('backupwordpress', 'BackUpCommand', Object(WP_CLI\Dispatcher\RootCommand))
#2 /srv/wp/html/wp-content/plugins/backupwordpress/classes/class-backupwordpress-wp-cli-command.php(115): WP_CLI::add_command('backupwordpress', 'BackUpCommand')
#3 /srv/wp/html/wp-content/plugins/backupwordpress/backupwordpress.php(185): include('/srv/localserve...')
#4 /srv/wp/html/wp-content/plugins/backupwordpress/backupwordpress.php(83): HM\BackUpWordPress\Plugin->includes()
#5 [internal function]: HM\BackUpWordPress\Plugin->plugins_loaded('')
#6 /srv/wp/html/wp-includes/plugin.php(496): call_us in phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php on line 20
```

**Comment by danielbachhuber** [comment]
It looks like the file was named incorrectly: https://github.com/humanmade/backupwordpress/commit/54327e0feb0254f740b8ff2c9635858881a745a1

**Comment by danielbachhuber** [comment]
... and the class name was incorrect. https://github.com/humanmade/backupwordpress/pull/727

WP-CLI shouldn't fail hard though. We'll fix that part.

**Comment by mjot** [comment]
Thanks Daniel. :)

**Comment by willmot** [comment]
Fix for this will be in next release of BackUpWordPress

**Comment by mjot** [comment]
Thanks Tom, great work!

**Comment by szepeviktor** [comment]
A `class_exists()` in [CommandFactory.php:20](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Dispatcher/CommandFactory.php#L20)

**Comment by danielbachhuber** [comment]
> A class_exists() in

Sure, and throw an error if it doesn't. Can you prepare a PR with a test?

**Comment by szepeviktor** [comment]
@danielbachhuber Could you help where `<type>` comes from in `upgradables.feature`?

**Comment by szepeviktor** [comment]
It is OK earlier?
https://github.com/szepeviktor/wp-cli/compare/wp-cli:master...missing_cmd?diff=unified&name=missing_cmd

**Comment by danielbachhuber** [comment]
> It is OK earlier?

That's fine. You want to use `WP_CLI::error()` though, instead of throwing an exception.

> Could you help where <type> comes from in

It's built from this `Examples:` declaration: https://github.com/wp-cli/wp-cli/blob/master/features/upgradables.feature#L177

However, don't worry about fixing the current build. It's on my list to take care of as soon as I can.

**Comment by szepeviktor** [comment]
How come that Travis has a theme called `Mercury`?
https://travis-ci.org/wp-cli/wp-cli/jobs/50095863#L237

**Comment by danielbachhuber** [comment]
> How come that Travis has a theme called

WordPress.org is returning weird API search responses again.

**Comment by szepeviktor** [comment]
I thought it is binary. `p2 !== mercury`

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/wp-cli/pull/1645
