### ISSUE TITLE
It would be neat to have the "_sassify!" option for `scaffold _s`

### ISSUE THREAD

**Issue by FStop** [wp-cli/wp-cli#1638]
_s includes Sass files, and there is a "_sassify!" option for the generator on the underscores.me website. I think would be a nice addition to the `scaffold _s` command as well.

If I had any idea how to make that happen I'd take a crack at it but alas, I do not, so the best I can do is open this issue and hope that it's not too complicated.

**Comment by danielbachhuber** [comment]
Good suggestion!

**Comment by acusti** [comment]
This is beautiful! In fact, this whole project, combined with `_s`, is beautiful, but this is the final piece that enables my ideal WP development workflow. Can’t wait until the next release!

**Comment by danielbachhuber** [comment]
> Can’t wait until the next release!

You can use the equivalent of `master` by following these instructions: https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods#installing-nightly-via-phar

**Comment by acusti** [comment]
:+1: :godmode:

**Comment by FStop** [comment]
Awesome! :beers:
