### ISSUE TITLE
Help me love the search-replace function...

### ISSUE THREAD

**Issue by MarceloPedra** [wp-cli/wp-cli#1639]
Hi! I'm managing to migrate a very big website from dev to production. So, all the db references to the localhost must be turned into the domain.com form.

WP-CLI has made a very good job... on those tables belonging to WP, AND using the $table_prefix. But it happens that a great amount of plugins, like ecommerce related, affiliate related, and the like, use their very own "$table_prefix".tables or even their own prefixes. Hence, they are ignored by WP-CLI. 

Those ignored tables contain hundred of references to the domain, image paths and URLs that make it almost an impossible task if done by hand. And of course 95% of the data is serialized! :)

So... is it any way to make WP-CLI include ALL the tables present in the DB when you need to process it with the search-replace command?

Thanks!

**Comment by szepeviktor** [comment]
1) You can write a community command for table inclusion.
2) wp-cli's s&r is from [Search Replace DB](https://github.com/interconnectit/Search-Replace-DB)

+1 It is very easy to write a [new db command](https://github.com/szepeviktor/wp-cli-database-prefix-command/blob/master/wp-cli-database-prefix-command.php) all you need is copy&paste.

*please close the issue*

**Comment by danielbachhuber** [comment]
Will be addressed by #1629
