### ISSUE TITLE
search and replace on serialized values gets only the first instance of 'search' on serialized values

### ISSUE THREAD

**Issue by yivi** [wp-cli/wp-cli#1640]
Give this option_value, where there are several instances of "yosilose.ojiva.es"

`a:10:{i:13;a:5:{s:5:"title";s:14:"Weight Watcher";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150331";s:3:"src";s:4:"4784";s:4:"href";s:63:"http://clk.tradedoubler.com/click?p=227643&a=1346626&g=22072978";}i:17;a:5:{s:5:"title";s:14:"Weight Watcher";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150331";s:3:"src";s:4:"4784";s:4:"href";s:63:"http://clk.tradedoubler.com/click?p=227643&a=1346626&g=22072978";}i:18;a:5:{s:5:"title";s:14:"Weight Watcher";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150331";s:3:"src";s:4:"4784";s:4:"href";s:63:"http://clk.tradedoubler.com/click?p=227643&a=1346626&g=22072978";}i:20;a:0:{}i:22;a:0:{}i:23;a:5:{s:5:"title";s:19:"Especial Yosílosé";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150601";s:3:"src";s:4:"5312";s:4:"href";s:43:"http://yosilose.ojiva.es/especial-comunion/";}i:24;a:5:{s:5:"title";s:19:"Especial Yosílosé";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150601";s:3:"src";s:4:"5312";s:4:"href";s:43:"http://yosilose.ojiva.es/especial-comunion/";}i:25;a:5:{s:5:"title";s:19:"Especial Yosílosé";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150601";s:3:"src";s:4:"5312";s:4:"href";s:43:"http://yosilose.ojiva.es/especial-comunion/";}i:26;a:5:{s:5:"title";s:19:"Especial Yosílosé";s:10:"start-date";s:8:"20150201";s:11:"expiry-date";s:8:"20150601";s:3:"src";s:4:"5312";s:4:"href";s:43:"http://yosilose.ojiva.es/especial-comunion/";}s:12:"_multiwidget";i:1;}`

Every time I run `wp search-replace yosilose.ojiva.es yosilose.local` will replace only one instance, leaving the rest as "yosilose.ojiva.es".

Is this the expected behaviour?

Thanks and regards.

**Comment by szepeviktor** [comment]
I've imported your JSON value: `wp option set xx < /tmp/json` There are four of `yosilose.ojiva.es` and after your wp-cli command four `yosilose.local`-s.
Don't be misled by the cloumn name `Replacements`.
```
| wp_options       | option_value          | 1            | PHP  |
```
That `1` means: one variable.
*please use the latest wp-cli and close the issue*

**Comment by szepeviktor** [comment]
I like your website.
