### ISSUE TITLE
Is there a command to alter a template used by a page?

### ISSUE THREAD

**Issue by codecowboy** [wp-cli/wp-cli#1641]
If I want to change a large list of pages to use template x, is there a WP-CLI command to do this? If not, would it be possible with a plugin?

**Comment by jmslbam** [comment]
Like Tom says here, it's a meta field of the post type Page: https://tommcfarlin.com/programmatically-set-a-wordpress-template/
So you can set it by running the Post Meta command 

 `wp post meta update _wp_page_template  'template-name.php'`

**Comment by mikelyons** [comment]
The field value info here: http://wp-cli.org/commands/post/create/

references the array of post attributes here: https://codex.wordpress.org/Function_Reference/wp_insert_post

as I embarassingly discovered here: http://wordpress.stackexchange.com/questions/190540/how-do-i-set-and-list-page-template-with-wpcli/190542#190542
