### ISSUE TITLE
Creating Phar

### ISSUE THREAD

**Issue by ractoon** [wp-cli/wp-cli#1644]
Hi There,

After modifying the source how do you create the new phar file?

**Comment by szepeviktor** [comment]
First set
```php
[Phar]
;phar.readonly = On
phar.readonly = Off
```
in `/etc/php5/cli/php.ini`.
After `composer install` run [utils/make-phar.php ./wp.phar](https://github.com/wp-cli/wp-cli/blob/master/utils/make-phar.php).
*please close the issue*

**Comment by ractoon** [comment]
Perfect, thanks!

**Comment by szepeviktor** [comment]
Glad to help.
