### ISSUE TITLE
wp user create: The FROM email is not set when --send-email param is passed

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#1654]
Related file:
https://github.com/wp-cli/wp-cli/blob/master/php/commands/user.php Line: #250.
It uses a standard WordPress function: wp_new_user_notification

![screenshot 2015-02-14 16 48 32](https://cloud.githubusercontent.com/assets/137558/6199960/c7ea0db4-b469-11e4-94b2-f406851cec59.png)

Is it possible to start defining filters and actions within WP-CLI that can potentially be called in the before executing a WP function?

**Comment by danielbachhuber** [comment]
> Is it possible to start defining filters and actions within WP-CLI that can potentially be called in the before executing a WP function?

You can just create a MU plugin and use something like this:

```
add_filter( 'wp_mail_from', function( $email ){
	if ( defined( 'WP_CLI' ) && WP_CLI ) {
		return 'wp-cli@example.com';
	} else {
		return $email;
	}
});
```

**Comment by lordspace** [comment]
Thanks that could work. Thanks!
