### ISSUE TITLE
extend wp export command by --file option

### ISSUE THREAD

**Issue by qm78** [wp-cli/wp-cli#1657]
To automate my wp install script I'd like to run amongst others 'wp import --url=myurl mylatest.wxr' Therefore I miss --file option on wp export to set export filename to eg. mylatest.wxr

Perhaps a even more generic approach could be to enhance 'wp export' to export to stdout, then it's open for pipe (eg. additional compress export file)

**Comment by danielbachhuber** [comment]
> Therefore I miss --file option on wp export to set export filename to eg. mylatest.wxr

The filename is based on the supplied arguments. Based on the size of the export, you might end up with more than one file. You'd be better off exporting all of your files to a specific directory, and importing from that directory with `wp import --url=domain.com directory`

> (eg. additional compress export file)

Similarly, you can do this with some small amount of shell scripting.
