### ISSUE TITLE
issue related to wordpress-mu-domain-mapping -> Use of undefined constant -> 'SUNRISE'

### ISSUE THREAD

**Issue by qm78** [wp-cli/wp-cli#1658]
After installing wordpress-mu-domain-mapping plugin and manually adding 
const 'define( 'SUNRISE', on );' in my wp-config.php I'm having nasty PHP Notice on all wp-cli commands.

PHP Notice:  Use of undefined constant on - assumed 'on' in phar:///usr/local/bin/wp/php/wp-cli.php(23) : eval()'d code on line 42

-- excerpt of my wp-config-php --
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
$base = '/';
define('DOMAIN_CURRENT_SITE', 'blog.mydomain.tld');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
define( 'SUNRISE', on );
-- excerpt of my wp-config-php --

Is there any workaround available?

**Comment by danielbachhuber** [comment]
It's likely caused by #1631.

Can you share the contents of your `wp-config.php`, minus any secrets?

**Comment by qm78** [comment]
Hi Daniel,

please see: http://pastebin.com/XHVPFBxr for my wp-config.php no secrets.

**Comment by szepeviktor** [comment]
What is `$base` for? Seems like it is lost without `global $base;`.

**Comment by szepeviktor** [comment]
@qm78 Try `define( 'SUNRISE', 'on' );`.

**Comment by szepeviktor** [comment]
`SUNRISE` could have any value. I suggest use `true`.

**Comment by danielbachhuber** [comment]
> could have any value.

Good catch. `on` isn't a valid value because PHP is interpreting it as an (undefined) constant.

**Comment by szepeviktor** [comment]
`on` seems very much like a real value!

**Comment by qm78** [comment]
Indeed **on** was the problem. Thanks!

**Comment by szepeviktor** [comment]
We are happy to help.
