### ISSUE TITLE
Properly format global parameters on website

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1659]
![image](https://cloud.githubusercontent.com/assets/36432/6204204/1b483ba6-b4f7-11e4-87bc-015171b4de7b.png)

**Comment by szepeviktor** [comment]
You mean `--` -> `–`?

**Comment by danielbachhuber** [comment]
No, that they should be formatted like this:

![image](https://cloud.githubusercontent.com/assets/36432/6282117/fe4b0ad4-b883-11e4-8841-cdd8ca20f5cc.png)

**Comment by danielbachhuber** [comment]
https://github.com/wp-cli/wp-cli.github.com/pull/52

![image](https://cloud.githubusercontent.com/assets/36432/6949711/e2b7ac44-d86a-11e4-94e9-99d75bce5a97.png)

**Comment by szepeviktor** [comment]
Hw to make it like in [the above comment](https://github.com/wp-cli/wp-cli/issues/1659#issuecomment-75194236)?

**Comment by danielbachhuber** [comment]
> How to make it like

Not sure — probably need fancier formatting regex, because global params aren't formatted this way in the code. I don't think it's worth the effort.
