### ISSUE TITLE
wp-cli code base growth

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1660]
Is someone willing to put together a script to generate a graph for the Wiki?
https://mathiasbynens.be/demo/jquery-size

- repo source code size
- `php` folder size
- phar file size

**Comment by sebastiaandegeus** [comment]
Is it really important for a tool to measure the size of the codebase? It's not downloaded on a page request like jquery.

**Comment by szepeviktor** [comment]
I wasn't thiniking about bandwidth but PHP parsing.

**Comment by szepeviktor** [comment]
...as there is no opcache on CLI.

**Comment by szepeviktor** [comment]
0.3.0 was 72 kB, now 1.28 MB

**Comment by danielbachhuber** [comment]
@szepeviktor Anything else you want to do here?

**Comment by szepeviktor** [comment]
No.
![growth](http://i.snag.gy/eZXub.jpg)

**Comment by danielbachhuber** [comment]
Odd. What cause the jump for v0.18.0?

**Comment by szepeviktor** [comment]
:) That was wp-cli-0.15.1.phar but I sorted them by value. Sorry.

**Comment by danielbachhuber** [comment]
Oh. I think that's because I built the Phar locally. False alarm

**Comment by szepeviktor** [comment]
@danielbachhuber 
https://www.openhub.net/p/wp-cli/analyses/latest/languages_summary
