### ISSUE TITLE
This does not seem to be a WordPress Install

### ISSUE THREAD

**Issue by Melindrea** [wp-cli/wp-cli#1661]
I'm trying to use WP-CLI on a production server, but when I try to install plugins (or anything except --info), it gives me that error message.

I am in the right folder, and the site works when I go to it via the browser. Any ideas on where to start looking for a solution? Are there any ports that need to be open for wp-cli to work? (Default has all except the most common blocked)

**Comment by Melindrea** [comment]
Exploring it further, it works if I give the exact path to the particular install. This is a fairly old installation (as in, it's been around a long time, not that it's outdated), is there something in the wp-config that could be missing from it?

**Comment by szepeviktor** [comment]
You have to start wp-cli in the WordPress root folder or give it the path option: `wp --path=<path>`.
wp-cli expects `wp-config.php` end [like this](https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php#L73-L80). See in [php/WP_CLI/Runner.php](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L339).

**Comment by szepeviktor** [comment]
Try using `--debug` also.

**Comment by Melindrea** [comment]
It is in the WP root folder when I run it. The two `wp-config.php` files end as follows:

```
/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

define('WP_CACHE', true);
	
/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
```

```
/* Det var allt, sluta redigera här! Blogga på. */

/** WordPress absoluta sökväg till Wordpress katalogen. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Anger WordPress värden och inkluderade filer. */
require_once(ABSPATH . 'wp-settings.php');
?>
```

Running `wp --debug plugin path` doesn't give me more info than `wp plugin path` does

**Comment by szepeviktor** [comment]
Do you run wp-cli in the directory where `wp-config.php` and `wp-settings.php` resides?
Do you use `sudo -i`?

**Comment by Melindrea** [comment]
Yes to both (using www-data for a user)

**Comment by szepeviktor** [comment]
Maybe `sudo -i` changes the current directory.

**Comment by szepeviktor** [comment]
I always us wp-cli.yml above the WP root. BTW I use `public_html/server`, and `server` is the DocumentRoot.

**Comment by Melindrea** [comment]
eugh, yeah, that probably explains it. I'll have to learn to live with it, then. Thanks for the help!

**Comment by szepeviktor** [comment]
This is my tool for this problem:

```bash
#!/bin/bash
#
# Execute wp-cli as the current directory's owner.
#
# VERSION       :0.1
# DATE          :2014-12-19
# AUTHOR        :Viktor Szépe <viktor@szepe.net>
# LICENSE       :The MIT License (MIT)
# URL           :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION  :4.2+
# LOCATION      :/usr/local/sbin/suwp

THIS_OWNER="$(stat . -c %U)"

sudo -u "$THIS_OWNER" --  wp --path="$PWD" "$@"
```
https://github.com/szepeviktor/debian-server-tools/tree/master/tools

**Comment by brilik** [comment]
U need paste the wordpress data in volumes. For example: 
```
# In wp-cli service
volumes:
      - wpdata:/var/www/html

``````
volumes:
  wpdata: {}
```

**Comment by micabal** [comment]
> You have to start wp-cli in the WordPress root folder or give it the path option: `wp --path=<path>`. wp-cli expects `wp-config.php` end [like this](https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php#L73-L80). See in [php/WP_CLI/Runner.php](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L339).

For exemple, it will not work:
`wp media image-size`

But **this** will work:
`wp --path='/srv/www/mywebsiteexample/public_html' media image-size`

This will also work: 
`cd /srv/www/mywebsiteexample/public_html`
`wp media image-size`

_/srv/www/mywebsiteexample/public_html_ is the folder where WordPress has been installed. You will see the folder `wp-content` among others,  and the file `wp-config.php`

**Comment by Konamiman** [comment]
Inspired by [@szepeviktor 's comment](https://github.com/wp-cli/wp-cli/issues/1661#issuecomment-75040197) I have added this to my `.bashrc`:

```bash
alias wp='sudo -u "$(stat . -c %U)" --  \wp --path="$HOME/wordpress" "$@"'
```

Adjust the value passed to `--path` accordingly for your system, and bam, you can run `wp` from anywhere.

**Comment by maltfield** [comment]
fwiw, this was a linux os permissions issue for me.
