### ISSUE TITLE
wp-cli support for premium plugin updates

### ISSUE THREAD

**Issue by Vinsanity** [wp-cli/wp-cli#1662]
Love WP-CLI! Thanks.

I noticed that when I attempt to update premium plugins like "Advanced Custom Fields Pro" (wp plugin update advanced-custom-fields-pro) for instance, that it will not update the plugin but still prints a success message of: 
Success: Updated 0/0 plugins.

Is there anyway to update premium plugins via wp-cli and if not, is this planned for a future release?

**Comment by danielbachhuber** [comment]
> Is there anyway to update premium plugins via wp-cli and if not, is this planned for a future release?

Not unless the plugin implements an update mechanism that's compatible with WordPress core. If the plugin does, then it will work as expected.

**Comment by acobster** [comment]
@danielbachhuber , could you elaborate or a provide a link describing what you mean by "compatible with WordPress core"? Thanks for this awesome tool.

**Comment by danielbachhuber** [comment]
> could you elaborate or a provide a link describing what you mean by "compatible with WordPress core"

WP-CLI checks the `update_plugins` transient to see if there is an update available for a plugin:

* https://github.com/wp-cli/wp-cli/blob/8702c14a199f11180accb2b22e68593e160a9af5/php/WP_CLI/CommandWithUpgrade.php#L341
* https://github.com/wp-cli/wp-cli/blob/8702c14a199f11180accb2b22e68593e160a9af5/php/commands/plugin.php#L14

For a non-WordPress.org plugin to introduce an update, it needs to filter the `update_plugins` transient to return what's called a "download offer" for the plugin.

WP Remote has a relevant piece of support documentation: https://wpremote.com/support-center/integrating-wp-remote/adding-wp-remote-support-premium-theme-plugin/
