### ISSUE TITLE
Gravity Forms plugin not noticed by WP-CLI

### ISSUE THREAD

**Issue by gerardjp** [wp-cli/wp-cli#1665]
Hi all,

I have websites running the plugin Gravity Forms. In the dash (on the update status page) Wordpress tells me there's an update available.

![screen shot 2015-02-19 at 07 43 45](https://cloud.githubusercontent.com/assets/317344/6262843/1a012eac-b80c-11e4-87dc-721a6b3a0512.png)

However on the CLI the available update is not mentioned.

![screen shot 2015-02-19 at 07 43 59](https://cloud.githubusercontent.com/assets/317344/6262848/328b269e-b80c-11e4-9b46-3db794a80a85.png)

![screen shot 2015-02-19 at 07 44 31](https://cloud.githubusercontent.com/assets/317344/6262849/36b0d516-b80c-11e4-8c81-b1a6bec16370.png)

Just pulled the lastest from http://wp-cli.org/ and does this also. Platform is latest ubuntu 14.04.

Any suggestions?

Thanx a lot and good day.

Kind regards,

Gerard.

**Comment by szepeviktor** [comment]
It is not on WP-org. See: http://www.gravityforms.com/
I should hook WP update and insert its data into the update list.
wp-cli uses its own update method. I think it was not hooked by gravityforms.
@danielbachhuber Could wp-cli plugin update be hooked?

**Comment by danielbachhuber** [comment]
> wp-cli uses its own update method. I think it was not hooked by gravityforms.

WP-CLI simply wraps core's update method, so not sure why it works in the admin and not at the command line.

@gerardjp Can you open a support ticket with Gravity Forms and point them here so we can discuss their implementation with greater technical depth?

**Comment by szepeviktor** [comment]
I suspect GF implements it in a way that is far away from WP.

**Comment by gerardjp** [comment]
Hi All,

I posted a request with GF just now (closed support forum), see with what they respond. I understand how for premium plugins, some form of authentication is advisable, so only buyers can download.

A party that does this rather well and fairly transparant IMHO is Elegant themes. With a acquireable API key from their member area you can authenticate the download request from within wordpress.

The API key is stored in the database of the Wordpress installation and appended in the url when downloading an update. The available 'updater plugin' is found and described here:
 
http://www.elegantthemes.com/gallery/divi/tutorial-update.html

Very neat and workeable implementation IMHO.

Hope it helps .. I'll keep you guys posted on any GF feedback.

Regards,

Gerard.

**Comment by gerardjp** [comment]
PS: GF just responded that the issue at hand will be looked at by their developers

**Comment by gerardjp** [comment]
Hi All,

The GF developers said, this issue is resolved since version 1.9.2. I can confirm.

I updated to the latest GF. Manually down-ed the version number in the source code to 1.9.1 and afterwards it also showed up on the commandline. Closing ...

**Comment by lukecav** [comment]
Also Gravity Forms now has https://github.com/gravityforms/gravityformscli
