### ISSUE TITLE
WP-CLI tries to be too smart when guessing URL

### ISSUE THREAD

**Issue by rmccue** [wp-cli/wp-cli#1667]
Let's say I have this in my `wp-config.php`:

```php
defined( 'DOMAIN_CURRENT_SITE' ) or define( 'DOMAIN_CURRENT_SITE', 'some.example.org' );
```

`DOMAIN_CURRENT_SITE` instead gets overridden by another file included in (`wp-config-local.php`). Right now, WP-CLI tries too hard to guess this, and will pick `some.example.org` because it can't guess correctly. Even better, if the value is actually a variable, you'll end up with `example.com` instead.

When running `wp core multisite-install`, this causes the first site's domain in `wp_blogs` to be wrong, **even when specifying `--url`**.

**Comment by rmccue** [comment]
Probably duplicate of #1631.

**Comment by danielbachhuber** [comment]
I'm ready to put a bounty on someone spending tens of hours figuring this out :) Or, I suppose I could put some time towards it.

We can keep this open for now.

**Comment by rmccue** [comment]
One solution I was thinking might work: for those with more complicated config files, they could check for a constant, and avoid loading WP if it's set. People that run into this sort of problem are likely to have highly custom config files, so it shouldn't be an issue to change to:

```php
if ( ! defined( 'WP_CLI_SKIP_WP' ) )
    require_once( ABSPATH . 'wp-settings.php' );
```

**Comment by mboynes** [comment]
I started on this problem in #1362 but ended up getting distracted with something else. I'll try to revisit it again real soon. It's done and works, just needs tests.

**Comment by Axisar** [comment]
Confirm. Same problem here. i`ve set --url="www." and all became good. but before, when i tried http://www.domain.com/, result was "www.domain.comdomain.com" after installation
