### ISSUE TITLE
WP-CLI and HHVM -- no output

### ISSUE THREAD

**Issue by sepehr125** [wp-cli/wp-cli#1671]
My setup:
Ubuntu 14.04, Nginx, HHVM, the nightly Phar of wp-cli. 
Other setups I have tried included Apache, php5, and stable release of wp-cli. The problem, described below, persists under both setups.

Symptoms:
1) running `wp --info` from any location, provides output that is seemingly correct: 
PHP binary:	/usr/bin/hhvm
PHP version:	5.6.99-hhvm
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	/var/www/html/wp-cli.local.yml
WP-CLI version:	0.18.0
 
2) Within a wordpress directory, no other `wp` commands provide any output. There is a slight delay before the prompt is available again, during which time it seems to be doing *something*, but I am not sure what. 

3) If I run `wp` by itself from a NON-wordpress directory, I do get all the available commands and flags: the usual instructions. And it provides the error "This is not a wordpress install" if I pass any commands to wp-cli. 

Here are some other possibly useful files:

My /etc/hhvm/php.ini:
; php options
session.save_handler = files
session.save_path = /var/lib/php5
session.gc_maxlifetime = 1440

; hhvm specific 
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false

(My install directory is /var/www/html/)
My wp-cli YAML file: /var/www/html/wp-cli.local.yml:
`path: /var/www/html/`

My /var/log/hvvm/error.log:
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record
FastCGI protocol: received an invalid record

That's it! Any ideas what could be going on?  

Thanks so much!

**Comment by danielbachhuber** [comment]
Apologies for the late reply. Were you able to sort this out?

**Comment by sepehr125** [comment]
Thank

Nope. Still in the dark about what could be causing this. Would be awesome
to diagnose it. I imagine it's something in the hhvm config files.

Any ideas on what to look for?

Thanks,
Sepehr



On Tuesday, March 3, 2015, Daniel Bachhuber <notifications@github.com>
wrote:

> Apologies for the late reply. Were you able to sort this out?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wp-cli/wp-cli/issues/1671#issuecomment-77093204>.
>


-- 
Sent from Mobile

**Comment by danielbachhuber** [comment]
Couple of debugging steps:

* Can you look in your PHP error log for any fatals that might be occurring and not getting reported for whatever reason?
* Can you try against a fresh install of WordPress with all plugins deactivated?
* Is this a WordPress multisite instance by chance?
