### ISSUE TITLE
Retrieve posts - post__not_in

### ISSUE THREAD

**Issue by danielst-vccp** [wp-cli/wp-cli#1672]
Hi, I'm trying to exclude a post from a post list, but I'm having trouble getting the post__not_in filter to work.

The documentation suggests that this filter is only available to a logged in user with the correct permissions? I've tried the following syntax without much success, both logged in and not. `filter[post__not_in]=1234` and `filter[post__not_in][]=1234` have no effect.

**Comment by danielbachhuber** [comment]
Did you mean to file this in WP-API?

**Comment by danielst-vccp** [comment]
Yessir... nothing to see here.
