### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?' in phar:///usr/local/bin/wp/php/wp-cli.php(23) : eval()'d code on line 1

### ISSUE THREAD

**Issue by zzzerotime** [wp-cli/wp-cli#1674]
Hi, 

I have a debian 7 wp install. I installed latest version of wp-cli. I have 2 wordpress instance in this server. wp-cli only works in one instance. 

- www/site1files -> does not work
- www/site2/site2files > it works

I have edited my wp-config file, to no avail, I copy and paste it. Can you help me?

Thank you very much.

```php
<?php 
/** 
 * Configuración básica de WordPress.
 *
 * Este archivo contiene las siguientes configuraciones: ajustes de MySQL, prefijo de tablas,
 * claves secretas, idioma de WordPress y ABSPATH. Para obtener más información,
 * visita la página del Codex{@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} . Los ajustes de MySQL te los proporcionará tu proveedor de alojamiento web.
 *
 * This file is used by the wp-config.php creation script during the
 * installation. You don't have to use the web site, you can just copy this file
 * to "wp-config.php" and fill in the values.
 *
 * @package WordPress
 */
define('WP_CACHE', true); // Added by W3 Total Cache
// ** Ajustes de MySQL. Solicita estos datos a tu proveedor de alojamiento web. ** //
/** El nombre de tu base de datos de WordPress */
define('DB_NAME', 'nivelocultov4');

/** Tu nombre de usuario de MySQL */
define('DB_USER', 'xxxxx');

/** Tu contraseña de MySQL */
define('DB_PASSWORD', 'xxxxxxx');

/** Host de MySQL (es muy probable que no necesites cambiarlo) */
define('DB_HOST', 'localhost');

/** Codificación de caracteres para la base de datos. */
define('DB_CHARSET', 'utf8');

/** Cotejamiento de la base de datos. No lo modifiques si tienes dudas. */
define('DB_COLLATE', '');

define('DISABLE_WP_CRON', 'true');
/**#@+
 * Claves únicas de autentificación.
 *
 * Define cada clave secreta con una frase aleatoria distinta.
 * Puedes generarlas usando el {@link https://api.wordpress.org/secret-key/1.1/salt/ servicio de claves secretas de WordPress}
 * Puedes cambiar las claves en cualquier momento para invalidar todas las cookies existentes. Esto forzará a todos los usuarios a volver a hacer login.
 *
 * @since 2.6.0
 */

/**#@-*/

/**
 * Prefijo de la base de datos de WordPress.
 *
 * Cambia el prefijo si deseas instalar multiples blogs en una sola base de datos.
 * Emplea solo números, letras y guión bajo.
 */
$table_prefix  = 'wp_';

/**
 * Idioma de WordPress.
 *
 * Cambia lo siguiente para tener WordPress en tu idioma. El correspondiente archivo MO
 * del lenguaje elegido debe encontrarse en wp-content/languages.
 * Por ejemplo, instala ca_ES.mo copiándolo a wp-content/languages y define WPLANG como 'ca_ES'
 * para traducir WordPress al catalán.
 */
define('WPLANG', 'es_ES');

/**
 * Para desarrolladores: modo debug de WordPress.
 *
 * Cambia esto a true para activar la muestra de avisos durante el desarrollo.
 * Se recomienda encarecidamente a los desarrolladores de temas y plugins que usen WP_DEBUG
 * en sus entornos de desarrollo.
 */
define('WP_DEBUG', false);

/* ¡Eso es todo, deja de editar! Feliz blogging */

/** WordPress absolute path to the Wordpress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');
/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

```

**Comment by danielbachhuber** [comment]
Can you share this in a gist or pastebin? The formatting is important, and I think copy and pasting has changed it some.

Probably related #1631

**Comment by szepeviktor** [comment]
This config file seems to be OK.

**Comment by szepeviktor** [comment]
@zzzerotime Please consider removing comment for your own sake.

**Comment by scribu** [comment]
Also consider changing all your secret keys, now that you've made them public.

**Comment by zzzerotime** [comment]
Thanks, but howcan i fix this, is there any way to make it work¿

**Comment by szepeviktor** [comment]
It is in the comments: https://api.wordpress.org/secret-key/1.1/salt/

**Comment by zzzerotime** [comment]
I have to remove the secret keys from config to make  wp-cli work? Thanks!

**Comment by szepeviktor** [comment]
No. Secret keys should be removed beacuse you've just made them public (above).

**Comment by scribu** [comment]
Secret keys should be _replaced_, not removed. That's what I said.

**Comment by zzzerotime** [comment]
OK, so in order to make wp-cli work, is there something I can do?, thanks

**Comment by szepeviktor** [comment]
Please share more details like `wp --info`.

**Comment by zzzerotime** [comment]
PHP binary:     /usr/bin/php5
PHP version:    5.4.36-0+deb7u3
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.18.0

**Comment by szepeviktor** [comment]
Do you have PHP-suhosin https://github.com/wp-cli/wp-cli/issues/1181 ?

**Comment by zzzerotime** [comment]
No, not at the moment. I have 2 wordpress installations, wp-cli works only in one of them.

**Comment by zzzerotime** [comment]
Both installations are on the same server

**Comment by szepeviktor** [comment]
Try disabling plugins.
What output do you get?

```
wp core version
exit $?
```

**Comment by zzzerotime** [comment]
wp core version
4.1

**Comment by szepeviktor** [comment]
Then it works!!

**Comment by zzzerotime** [comment]
why if I only type wp I get this error?

**Comment by szepeviktor** [comment]
Try running wp-cli from source and modify line 23 from `eval` to `echo`.

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods#installing-via-composer

**Comment by zzzerotime** [comment]
I get same error, but before it, i get an echo of the wp-config.php file.

**Comment by szepeviktor** [comment]
I suspect this echod `wp-config` is different from [above](https://github.com/wp-cli/wp-cli/issues/1674#issue-58976474).

**Comment by zzzerotime** [comment]
Sorry, I don't understand. I just want to make wp-cli work on my installation. Echod wp-config.php and wp-config.php are the same.

**Comment by szepeviktor** [comment]
I mean the echod one must be different from the one above in your comment.
Because that code above in your comment parses OK and executes.

I hope your removed the secret keys only from the comment above not from your wp-config.

**Comment by szepeviktor** [comment]
```php
<?php 
/** 
 * Configuración básica de WordPress.
 *
 * Este archivo contiene las siguientes configuraciones: ajustes de MySQL, prefijo de tablas,
 * claves secretas, idioma de WordPress y ABSPATH. Para obtener más información,
 * visita la página del Codex{@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} . Los ajustes de MySQL te los proporcionará tu proveedor de alojamiento web.
 *
 * This file is used by the wp-config.php creation script during the
 * installation. You don't have to use the web site, you can just copy this file
 * to "wp-config.php" and fill in the values.
 *
 * @package WordPress
 */
define('WP_CACHE', true); // Added by W3 Total Cache
// ** Ajustes de MySQL. Solicita estos datos a tu proveedor de alojamiento web. ** //
/** El nombre de tu base de datos de WordPress */
define('DB_NAME', 'nivelocultov4');

/** Tu nombre de usuario de MySQL */
define('DB_USER', 'xxxxx');

/** Tu contraseña de MySQL */
define('DB_PASSWORD', 'xxxxxxx');

/** Host de MySQL (es muy probable que no necesites cambiarlo) */
define('DB_HOST', 'localhost');

/** Codificación de caracteres para la base de datos. */
define('DB_CHARSET', 'utf8');

/** Cotejamiento de la base de datos. No lo modifiques si tienes dudas. */
define('DB_COLLATE', '');

define('DISABLE_WP_CRON', 'true');
/**#@+
 * Claves únicas de autentificación.
 *
 * Define cada clave secreta con una frase aleatoria distinta.
 * Puedes generarlas usando el {@link https://api.wordpress.org/secret-key/1.1/salt/ servicio de claves secretas de WordPress}
 * Puedes cambiar las claves en cualquier momento para invalidar todas las cookies existentes. Esto forzará a todos los usuarios a volver a hacer login.
 *
 * @since 2.6.0
 */

/**#@-*/

/**
 * Prefijo de la base de datos de WordPress.
 *
 * Cambia el prefijo si deseas instalar multiples blogs en una sola base de datos.
 * Emplea solo números, letras y guión bajo.
 */
$table_prefix  = 'wp_';

/**
 * Idioma de WordPress.
 *
 * Cambia lo siguiente para tener WordPress en tu idioma. El correspondiente archivo MO
 * del lenguaje elegido debe encontrarse en wp-content/languages.
 * Por ejemplo, instala ca_ES.mo copiándolo a wp-content/languages y define WPLANG como 'ca_ES'
 * para traducir WordPress al catalán.
 */
define('WPLANG', 'es_ES');

/**
 * Para desarrolladores: modo debug de WordPress.
 *
 * Cambia esto a true para activar la muestra de avisos durante el desarrollo.
 * Se recomienda encarecidamente a los desarrolladores de temas y plugins que usen WP_DEBUG
 * en sus entornos de desarrollo.
 */
define('WP_DEBUG', false);

/* ¡Eso es todo, deja de editar! Feliz blogging */

/** WordPress absolute path to the Wordpress directory. */
if ( !defined('ABSPATH') )
    define('ABSPATH', dirname(__FILE__) . '/');
/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
```

**Comment by zzzerotime** [comment]
Thanks for clarify. Ok I understand now. 

- My wp-config.php file and the echod wp-config.php file are the same.
- keys remain in my wp-config.php, and also in the echod wp-config.php.

So, it still does not work. I still get same error.

**Comment by szepeviktor** [comment]
> PHP Parse error: syntax error, unexpected '?'

Could you copy here the output of `head -n3 wp-config.php | hexdump -C`?

**Comment by zzzerotime** [comment]
<code>00000000  ef bb bf 3c 3f 70 68 70  20 0a 2f 2a 2a 20 0a 20  |...<?php ./** . |
00000010  2a 20 43 6f 6e 66 69 67  75 72 61 63 69 c3 b3 6e  |* Configuraci..n|
00000020  20 62 c3 a1 73 69 63 61  20 64 65 20 57 6f 72 64  | b..sica de Word|
00000030  50 72 65 73 73 2e 0a                              |Press..|
00000037</code>

**Comment by szepeviktor** [comment]
Oh BOM!

**Comment by zzzerotime** [comment]
I am sorry, what do you mean by oh BOM!?

**Comment by szepeviktor** [comment]
Please set your Windows editor to use Linux lineends.
For every project....

Remove [BOM](http://es.wikipedia.org/wiki/Marca_de_orden_de_bytes_%28BOM%29) by changing encoding in your editor. Try: http://xhmikosr.github.io/notepad2-mod/

**Comment by zzzerotime** [comment]
Thank you so much!, I will try this asap.

**Comment by szepeviktor** [comment]
And please close this issue.

**Comment by zzzerotime** [comment]
it works now. I hope this helps others. This wp-config.php was old, so maybe someone edited it in windows with notepad.

I close the issue, thanks for all your patience.

**Comment by nextgenthemes** [comment]
@zzzerotime I would not post my database name publicly. Not sure how risky it is since there is of course no user+pw but still.

**Comment by rask** [comment]
This one happened here too. Stripping BOMs fixed it as in OPs situation. All commands that loaded `wp-config.php` returned that `unexpected '?'` error while other worked fine. I already started looking for syntax errors which contain question marks but a quick Google landed me here.

In PhpStorm you can just use `File -> Remove BOM` to achieve this. Other editors may have similar tools or saving modes.

**Comment by 7c** [comment]
For the records:

it is 2021 and I have seen same issue on latest ubuntu too. After long research the solution was at https://danielbachhuber.com/tip/fix-php-parse-error-unexpected/
![image](https://user-images.githubusercontent.com/22910022/141641276-563ac25f-cb48-4d20-b13b-66d18305673d.png)


Hope to have helped few people
