### ISSUE TITLE
Broke MySQL on Core Update

### ISSUE THREAD

**Issue by joshlsullivan** [wp-cli/wp-cli#1678]
I installed the latest version on DO Server running Ubuntu and LAMP. I had one droplet running four different sites. I issued "wp core update" on one of the sites, and after a few minutes, it threw an error. I hate that I can't remember it, but basically, it broke MySQL completely. It shutdown and erased mysqld.sock.

**Comment by danielbachhuber** [comment]
> I hate that I can't remember it, but basically, it broke MySQL completely. It shutdown and erased mysqld.sock.

I've never heard of this happening before. It could be something specific to your environment. If you can produce more reliable reproduction steps, I'd be happy to look into it further.

**Comment by joshlsullivan** [comment]
I wish I knew. I love WP-CLI and have been using it for a long time. :/
