### ISSUE TITLE
Possible issue: Undefined index: SERVER_PORT

### ISSUE THREAD

**Issue by ankitpokhrel** [wp-cli/wp-cli#1679]
Not sure if its an issue or I am missing something. I am using wp_cli to write tests for a plugin. I am just running sample test that wp_cli generate automatically. The test runs successfully but It shows `Undefined index: SERVER_PORT` notice for [this line in my plugin](https://github.com/ankitpokhrel/Dynamic-Featured-Image/blob/dev/dynamic-featured-image.php#L84):

```
$protocol = ( (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') ||
						$_SERVER['SERVER_PORT'] == 443 ) ? "https://" : "http://";
```
Looks like wp_cli can't find SERVER_PORT inside constructor. Any idea?

PS: I am using Ubuntu 14.04 LTS and WP-CLI v0.18.0

**Comment by danielbachhuber** [comment]
> Looks like wp_cli can't find SERVER_PORT inside constructor. Any idea?

There is no `SERVER_PORT` set when using WP-CLI. You'll need an `isset()` or `! empty()` check before inspecting `$_SERVER['SERVER_PORT']`
