### ISSUE TITLE
System Tepmporary Directory of Unit Tests on a Windows Environment

### ISSUE THREAD

**Issue by onet4** [wp-cli/wp-cli#1689]
Hi there,

I've set up unit tests using wp-cli on a Windows environment and would like to report an issue I had encountered.

The system temporary directory path `/tmp/` could be recognized in bash scripts (.sh files) but not in PHP scripts. I had to modify the following part in the "...\Temp\wordpress-tests-lib\wp-tests-config.php" file,

```php
define( 'ABSPATH', '/tmp/wordpress/' );
```

to

```php
define( 'ABSPATH', getenv( 'TEMP' ) . '/wordpress/' );
```

And in [`bootstrap.php`](https://github.com/wp-cli/wp-cli/blob/v0.18.0/templates/bootstrap.mustache)

```php
if ( !$_tests_dir ) $_tests_dir = '/tmp/wordpress-tests-lib';
```

to 

```php
if ( !$_tests_dir ) $_tests_dir = getenv( 'TEMP' ) . '/wordpress-tests-lib';
```

**Comment by danielbachhuber** [comment]
Because we're simply checking out the WP testing suite, I think this would be better resolved upstream.

**Comment by onet4** [comment]
That would be ideal.

What about adding a workaround for the time being? It requires two lines of change.

This line https://github.com/wp-cli/wp-cli/blob/v0.18.0/templates/install-wp-tests.sh#L48

```
sed $ioption "s:dirname( __FILE__ ) . '/src/':'$WP_CORE_DIR':" wp-tests-config.php
```

to 

```
sed $ioption "s:dirname( __FILE__ ) . '/src/':getenv( 'TEMP' ) . '/wordpress/':" wp-tests-config.php
```

And https://github.com/wp-cli/wp-cli/blob/v0.18.0/templates/bootstrap.mustache#L4

```
if ( !$_tests_dir ) $_tests_dir = '/tmp/wordpress-tests-lib';
```

to

```
if ( !$_tests_dir ) $_tests_dir = getenv( 'TEMP' ) . '/wordpress-tests-lib';
```

**Comment by danielbachhuber** [comment]
> What about adding a workaround for the time being?

I don't want to maintain a workaround.

**Comment by danielbachhuber** [comment]
@onet4 Can you create a core ticket for this please?
