### ISSUE TITLE
Error on CenOS 

### ISSUE THREAD

**Issue by Yachtsman** [wp-cli/wp-cli#1692]
Fresh install on Plesk managed CentOS server.
```
sh: /less: No such file or directory
```

**Comment by danielbachhuber** [comment]
Can you install [less](http://en.wikipedia.org/wiki/Less_%28Unix%29) ?

**Comment by Yachtsman** [comment]
Package less-436-13.el6.x86_64 already installed and latest version

**Comment by danielbachhuber** [comment]
What's the source of the error?

**Comment by ryanduff** [comment]
Sounds like a path issue. What does `echo $PATH` get you? Also, `which less` will show you the path to the less binary. 

If it's a stock install less should be in a common location. More than likely the user account doesn't have that directory in the $PATH

**Comment by Yachtsman** [comment]
```
echo $PATH
/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```
```
which less
/usr/bin/less
```

**Comment by danielbachhuber** [comment]
Odd. Can you share more context around the original error?

**Comment by szepeviktor** [comment]
That `/less` seems strange beacuse of the root dir: `/`.
Could you share what your `less` is really is? `ls -la /usr/bin/less`
