### ISSUE TITLE
Import to multisite ignores -url parameter

### ISSUE THREAD

**Issue by codecowboy** [wp-cli/wp-cli#1705]
I tried importing site content from a single site to a multisite install as follows:

```wp import sitename.wordpress.2015-03-10.xml -url=www.[sitename].com --authors=create```

Rather than import the content into the correct multisite tables (in my case wp_3_...), the content was added to the master site in the multisite install.

Can someone let me know if the above should work? In case it is relevant, DNS has not yet been changed for www.[sitename].com so that domain is actually pointing to the old server.

**Comment by Clorith** [comment]
Hi,

I'm seeing two things, the command needs a double dash and quotes around the URL for the parameter to be read, so `--url="sitename.com"`, also did you ensure the URL is the correct one as seen by WordPress, you can check this with `wp site list`.

**Comment by warrenseine** [comment]
I think wp-cli should exit with an error code if no site is matched for a `--url`. Currently, it returns 0 and displays nothing in the standard or error output.

**Comment by codecowboy** [comment]
thanks, is it me or are the docs not consistent on the '-' and '--' ? The note on multisite at http://wp-cli.org/ says '--' but the command page - http://wp-cli.org/ - has a single '-'

**Comment by szepeviktor** [comment]
@codecowboy See: https://github.com/wp-cli/wp-cli/issues/1659

**Comment by danielbachhuber** [comment]
> I think wp-cli should exit with an error code if no site is matched for a --url. Currently, it returns 0 and displays nothing in the standard or error output.

The problem is that WP-CLI doesn't know it's an invalid URL. It's more of an issue with WP core.

**Comment by warrenseine** [comment]
I don't think that's totally true. For instance with `search-replace`, there are 3 cases (put aside missing arguments):
* stdout says "Made 0 replacements"
* stdout says "Made n replacements" (n > 0)
* stdout is empty

Exit code is always 0, but the last case seems to happen only if the site root is invalid.

**Comment by danielbachhuber** [comment]
Fix the escaping issue https://github.com/wp-cli/wp-cli.github.com/pull/52
