### ISSUE TITLE
Add --enable-network option to scaffold’s child-theme + _s subcommands

### ISSUE THREAD

**Issue by acusti** [wp-cli/wp-cli#1711]
Same type of change as #1709, as mentioned in #1710

**Comment by acusti** [comment]
@danielbachhuber I think I made this close from a commit that I rolled back in my previous PR, but the final PR doesn’t actually implement this functionality. If adding these options to `scaffold _s` is something you agree would be worthwhile to add, I will make a new branch with the change and submit a PR, and I suppose this issue should be reopened until that makes it in.

**Comment by danielbachhuber** [comment]
> I think I made this close from a commit that I rolled back in my previous PR

Yep, sorry about this.

> If adding these options to scaffold _s is something you agree would be worthwhile to add, I will make a new branch with the change and submit a PR

Please do!
