### ISSUE TITLE
Adding Tabular and JSON output to stable API

### ISSUE THREAD

**Issue by joshkoenig** [wp-cli/wp-cli#1713]
I'm working on writing some WP-CLI extensions which handle structured data, and I'd like to offer default output in table format, and also give users the option to use JSON as an option if they are scripting.

These are options in the `Formatter` class, but not listed as part of the stable API:

https://github.com/wp-cli/wp-cli/wiki/API

Any chance we'll see the formatter made a part of the public API? It'd be super-useful for people looking to extend their own CLI versions.

**Comment by joshkoenig** [comment]
Hm... paying a little more attention, there are all these too:

https://github.com/wp-cli/php-cli-tools

So I suppose using the table API there is the right path?

**Comment by danielbachhuber** [comment]
That wiki page is way out of date. When I get around to scripting some documentation (#1045), I'll likely deprecate that page.

The formatter class is fine to use.

**Comment by danielbachhuber** [comment]
Shiny new page landed for `WP_CLI\Utils\format_items()` http://wp-cli.org/docs/internal-api/wp-cli-utils-format-items/
