### ISSUE TITLE
Add [--<field>=<value>] to wp site list

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/wp-cli#1716]
I'm thinking about creating a PR to add `[--<field>=<value>]` to `wp site list`. I would like to be able to filter the results of `wp site list`. Also I would like to add theme to the list of available fields so that I can filter sites by theme. Thoughts?

**Comment by danielbachhuber** [comment]
> I would like to be able to filter the results of wp site list

Seems fine to me.

> Also I would like to add theme to the list of available fields so that I can filter sites by theme.

I can't see the performance of this being great. `wp_get_sites()` supports filtering based on columns in `wp_blogs`, which is a far simpler query. This use case is better suited with a custom command / one-off script.
