### ISSUE TITLE
PHP Fatal error:  Cannot redeclare cli\render()

### ISSUE THREAD

**Issue by FortuneAlex** [wp-cli/wp-cli#1717]
Tying to push as database to a server and I keep getting this, I'm at a loss what to do

I found a similar issue posted here, I removed the line from composer.json, but I still get this error

Anything I could do to fix this? Thanks

PHP Fatal error:  Cannot redeclare cli\render() (previously declared in phar:///usr/local/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/cli.php:26) in /home/forge/starterb/releases/20150317205810/vendor/wp-cli/php-cli-tools/lib/cli/cli.php on line 46
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->before_wp_load() phar:///usr/local/bin/wp/php/wp-cli.php:20
PHP   5. eval() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:624
PHP   6. require_once() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(624) : eval()'d code:6
PHP   7. ComposerAutoloaderInit94d6f8d23a2a34c9c00b9edd2fe0d59f::getLoader() /home/forge/starterb/releases/20150317205810/vendor/autoload.php:7
PHP   8. composerRequire94d6f8d23a2a34c9c00b9edd2fe0d59f() /home/forge/starterb/releases/20150317205810/vendor/composer/autoload_real.php:45

**Comment by danielbachhuber** [comment]
Seems like your composer instance might be borked. Can you try Phar installation mechanism instead? http://wp-cli.org/#install

**Comment by FortuneAlex** [comment]
That's how I actually installed it. Trying it again doesn't fix it either

**Comment by danielbachhuber** [comment]
It looks like it's colliding with your existing use of Composer:

```
/home/forge/starterb/releases/20150317205810/vendor/composer/autoload_real.php:45
```

Are you already using php-cli-tools? Can you remove from the project, by chance?

**Comment by FortuneAlex** [comment]
Tried removing it, but it's absolutely necessary for " bundle exec cap development wpcli:db:push" to run it seems, or else at the 8th step in the trace it tells me it's not found.

If it can helps, I'm trying to deploy the database with capistrano. Pushing the files works nicely enough with "bundle exec cap development deploy", it just refuses to push the database.

If it can help I'm following this:
http://efeqdev.com/tutorial/using-bedrock-for-wordpress-for-the-first-time/
Except that I changed the net-ssh to the newer version since their version doesn't exist anymore

Here's the full trace:
http://pastebin.com/BxiAq859

**Comment by FortuneAlex** [comment]
Well I got it, I'm a dummy.

Actually had to remove wp-clip from composer.json ... However, you have do to composer update after (duh?...). Then of course push the changes to git. Then use the deploy command, then the database command and it should work. Hopefully it will fix your problem if you come across this

Anyways, problem solved, I got it, it was my own fault. Thanks for helping!

**Comment by danielbachhuber** [comment]
> Anyways, problem solved, I got it, it was my own fault. Thanks for helping!

Glad you were able to sort it out!
