### ISSUE TITLE
Export option to specific file and not over-write existing file

### ISSUE THREAD

**Issue by jb510** [wp-cli/wp-cli#1718]
I'm trying to export a WXR by year.

```
wp export --start_date=2000-01-01 --end_date=2001-01-01
wp export --start_date=2001-01-01 --end_date=2002-01-01
wp export --start_date=2002-01-01 --end_date=2003-01-01
etc...
```

However each time it over writes the xml file (named site_name.wordpress.2015-03-17.000.xml )

We need two options.
1) to specify a file name (--dir currently doesn't work for this)
2) to specify that the existing XML file name should be indexed instead of being over written

For reference when exporting my max file site, it does index the file names .000, .001, .002, etc...

**Comment by danielbachhuber** [comment]
We used to include the supplied arguments in the filename, which would solve your problem: https://github.com/wp-cli/wp-cli/pull/525/files#diff-92725afe093bc972e436493f9aae8204L307

I think we should restore that behavior.

**Comment by danielbachhuber** [comment]
Ah, this exchange is relevant https://github.com/wp-cli/wp-cli/pull/525#issuecomment-20010928

**Comment by dangtrinhnt** [comment]
Is there any update on this issue? Seem like I have to hack into the source of WP-CLI.
