### ISSUE TITLE
Search replace for theme mods doesn't work

### ISSUE THREAD

**Issue by markoheijnen** [wp-cli/wp-cli#1719]
When running wp search-replace http://oldurl.dev http://newurl.dev results in the output below. This happened with Twenty Fifteen with option: theme_mods_twentyfifteen. I only started debugging and I do see that the values are still found and being parsed by SearchReplacer but nothing happens.

```
array(3) {
  'header_image' =>
  string(67) "http://newurl.dev/wp-content/uploads/2015/03/bg.jpg"
  'header_image_data' =>
  class stdClass#345 (5) {
    public $attachment_id =>
    int(5)
    public $url =>
    string(66) "http://oldurl.dev/wp-content/uploads/2015/03/bg.jpg"
    public $thumbnail_url =>
    string(66) "http://oldurl.dev/wp-content/uploads/2015/03/bg.jpg"
    public $height =>
    int(121)
    public $width =>
    int(182)
  }
  'background_image' =>
  string(68) "http://newurl.dev/wp-content/uploads/2015/03/bg2.jpg"
}
```

**Comment by markoheijnen** [comment]
Ah, found why it was failing. recurse_objects is by default false but the unit tests is default true. Unsure what the right value of recurse_objects is.

**Comment by markoheijnen** [comment]
See #951

**Comment by szepeviktor** [comment]
Yes. There is no `recurse-objects = false` test.

**Comment by danielbachhuber** [comment]
Thanks for the report. We'll get this fixed.
