### ISSUE TITLE
Cannot redeclare wp_is_mobile()

### ISSUE THREAD

**Issue by milesblackwood** [wp-cli/wp-cli#1721]
A fresh download of wp-cli performs fine on doing a `wp core download` but breaks as soon as I try to do anything else within an active site root.

Could this be related to https://github.com/wp-cli/wp-cli/pull/1546 ?

Output of error:

    Fatal error: Cannot redeclare wp_is_mobile() (previously declared in /Users/***/Sites/***/wp-includes/vars.php:124) in phar:///usr/local/bin/wp/php/wp-settings-cli.php on line 218

**Comment by szepeviktor** [comment]
`wp-includes/vars.php` should not be included. Read the comment in #1546.
Try searching for the inclusion of `vars.php` in your themes, plugins.

**Comment by milesblackwood** [comment]
Thanks for the heads up--I'm checking the plugins and themes directory, to no avail, but I'll try to find the source of that include.

**Comment by szepeviktor** [comment]
@milesblackwood  It's not fair to advertise my plugins but [What's running](https://wordpress.org/plugins/whats-running/) may come handy when you are searching for such an inclusion.
Try cleaning up the HTML of use `html2text`.

**Comment by lukejanicke** [comment]
Check your **wp-config.php** file and make sure any files that are included/required in it do not also require **wp-settings.php**. The last statement in **wp-config.php** is usually `require_once( ABSPATH . 'wp-settings.php' );`. If any other included/required file also has that line, it will be executed twice. Two calls to require **wp-settings.php** means two calls to require **wp-includes/vars.php**, which means `wp_is_mobile()` is declared twice.
