### ISSUE TITLE
wp media import c:\path\filename.ext thinks c is the PHP_URL_SCHEME on Windows

### ISSUE THREAD

**Issue by bobbingwide** [wp-cli/wp-cli#1722]
In a Windows environment a fully qualified file name often includes the drive letter followed by a colon.

In the import() function in media.php there is a check to see if the file is remote.
For the filename c:\path\filename.ext  or c:/path/filename.ext the call to parse_url() returns a value of 'c', which is not empty, so the code attempts to load the file using download_url().

This fails, producing 
`Warning: filesize() expects parameter 1 to be a valid path, object given in ...`
and
`Warning: Unable to import file c:\path\filename.ext. Reason: File is empty. ...`

The second Warning message is very misleading.

Workaround:
Remove the drive letter and colon

Proposed Fix: Improve the testing for a local file before performing the remote get.

**Comment by szepeviktor** [comment]
Do yo mean to check `file_exists( $is_file_remote . DIRECTORY_SEPARATOR )`?
https://github.com/wp-cli/wp-cli/blob/master/php/commands/media.php#L125

**Comment by bobbingwide** [comment]
I didn't propose a solution. Would is_dir() make more sense?

**Comment by szepeviktor** [comment]
:smile: Yes.

**Comment by danielbachhuber** [comment]
`is_dir()` or some form of local file check seems reasonable to me.
