### ISSUE TITLE
Switch the package source for array_column

### ISSUE THREAD

**Issue by morganestes** [wp-cli/wp-cli#1724]
Running provision in VVV and noticed this line jump out at me:

```
Package rhumsaa/array_column is abandoned, you should avoid using it. Use ramsey/array_column instead.
```
There's no specifics as to *why* you should switch, but it's worth investigating if (or when) we should for wp-cli.

**Comment by rossedman** [comment]
This has been causing errors for me all day. I can't even update or use wp-cli at this point because of this.

**Comment by morganestes** [comment]
Didn't realize there was an open PR on this when I submitted my issue + patch. See #1723 for comparison.
