### ISSUE TITLE
I installed wp-cli, but not returning text in bash

### ISSUE THREAD

**Issue by BenjaminBarnett** [wp-cli/wp-cli#1725]
I made executable, moved into my path, but am getting no command-response. Guidance?

root@cp1 [~]# chmod +x wp-cli.phar
root@cp1 [~]# sudo mv wp-cli.phar /usr/local/bin/wp
root@cp1 [~]# wp --info
root@cp1 [~]# wp oauth1 add
root@cp1 [~]# wp
root@cp1 [~]# cd /home/videotst/public_html
root@cp1 [/home/videotst/public_html]# wp oauth1 add
root@cp1 [/home/videotst/public_html]# wp cli update
root@cp1 [/home/videotst/public_html]# php wp-cli.phar
Could not open input file: wp-cli.phar
root@cp1 [/home/videotst/public_html]# wp --info
root@cp1 [/home/videotst/public_html]#

**Comment by BenjaminBarnett** [comment]
I have a little more info now. 

- First off, Red Hat linux server. 
- Package does indeed install into /var/cache/yum/rhel-x86_64-server-5/packages/wp-cli-phar
- BUT, error_log entry in same directory: " [24-Mar-2015 16:05:27 America/New_York] PHP Fatal error:  Class 'Phar' not found in /var/cache/yum/rhel-x86_64-server-5/packages/wp-cli.phar on line 3 "
- first few lines of phar file:

#!/usr/bin/env php
<?php
Phar::mapPhar();
include 'phar://wp-cli.phar/php/boot-phar.php';
__HALT_COMPILER(); ?>

¯Qwp-cli.phar   ...etc.


Does this help troubleshoot at all?

**Comment by szepeviktor** [comment]
Do you use suhosin PHP extension?

**Comment by szepeviktor** [comment]
> Could not open input file: wp-cli.phar

...seems strange. Are you sure `php` is php CLI and not CGI?
Try `where php` in Windows.

**Comment by BenjaminBarnett** [comment]
Sorry for the lack of follow-up communication... abandoned wp-cli for now and found another workaround. Thanks for the attempted help though.
