### ISSUE TITLE
"cron event schedule" doesnt respect the <next-run> argument

### ISSUE THREAD

**Issue by tkmoney** [wp-cli/wp-cli#1728]
It seem that no matter what value I give it. It will always run the hook immediately. So "wp cron event schedule my_hook '+6 hours' " will execute the hook as if I said "now". Ive tried all kinds of different times and it doesnt seem to even observe them. Im running on Windows in case that matters.

**Comment by szepeviktor** [comment]
```
[<next-run>]
    A Unix timestamp or an English textual datetime description compatible with strtotime(). Defaults to now.
```

Windows may not like single quoted `'`. Try `wp cron event schedule my_hook "+6 hours"`.

**Comment by tkmoney** [comment]
Just tried that but got the same result

**Comment by szepeviktor** [comment]
Have you listed them? `wp cron event list` What is your output?

**Comment by tkmoney** [comment]
Yes. It returns the list of crons with the one I just added. The one I just added says "now" for the "next_run_relative" column.

**Comment by szepeviktor** [comment]
It is sure now that Windows does not pass the datetime description.

**Comment by szepeviktor** [comment]
I was wrong, it does:

```
C:\a\wamp\bin\php\php5.5.12>php a.php 'apple'
array(2) {
  [0] =>
  string(5) "a.php"
  [1] =>
  string(7) "'apple'"
}

C:\a\wamp\bin\php\php5.5.12>php a.php "apple"
array(2) {
  [0] =>
  string(5) "a.php"
  [1] =>
  string(5) "apple"
}
```

**Comment by tkmoney** [comment]
are you able to reproduce the bug?

**Comment by szepeviktor** [comment]
```php
<?php
print strtotime('now') . "\n";
print strtotime($argv[1]) . "\n";
```

prints

```
1427416575
1427438175
```

I do not use Windows for WP.

**Comment by szepeviktor** [comment]
Oh no! It is a bug:
https://github.com/wp-cli/wp-cli/blob/master/php/commands/cron.php#L100
That `!`.

**Comment by szepeviktor** [comment]
"Blame" shows @danielbachhuber 
https://github.com/wp-cli/wp-cli/commit/537c60a96e03b6c47489cc330f772955064aad09

**Comment by danielbachhuber** [comment]
> There is no test for this.

Let's make sure there is one when we fix it.
