### ISSUE TITLE
Fix the code to follow the WordPress Coding Standards

### ISSUE THREAD

**Issue by wrnx** [wp-cli/wp-cli#1733]
Some pieces of code don't follow, mainly, these rules:
* [Indentation](https://make.wordpress.org/core/handbook/coding-standards/php/#indentation)
* [Brace Style](https://make.wordpress.org/core/handbook/coding-standards/php/#brace-style)
* [Remove Trailing Spaces](https://make.wordpress.org/core/handbook/coding-standards/php/#remove-trailing-spaces)
* [Space Usage](https://make.wordpress.org/core/handbook/coding-standards/php/#space-usage)
* [Single and Double Quotes](https://make.wordpress.org/core/handbook/coding-standards/php/#single-and-double-quotes)

**But neither do some WordPress core code.**
And the following uses are mixed in the code:

```php
$var = "PHP $text";
$var = 'PHP ' . $text;
$var = "PHP ".$arr['text'];
$var = "PHP {$text}"; // Should be preferred?
```

Could be open a pull request to correct some of these?

**Comment by danielbachhuber** [comment]
> Could be open a pull request to correct some of these?

I appreciate the consideration, but I'm not interested in pull requests for code formatting.
