### ISSUE TITLE
Percent character (%) in output breaks table layout

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#1736]
Given output which contains a percent character, the layout will break when using the table format.

For example, with a post with a title "10%":

```
+------+--------------+-------------+---------------------+-------------+
| ID   | post_title   | post_name   | post_date           | post_status |
+------+--------------+-------------+---------------------+-------------+
| 1073 | 10%         | 10          | 2015-04-01 00:16:33 | publish     |
+------+--------------+-------------+---------------------+-------------+
```

This affects at least `\WP_CLI\Formatter::display_item()` and `\WP_CLI\Formatter::display_items()`.

**Comment by danielbachhuber** [comment]
This is most likely a bug in https://github.com/wp-cli/php-cli-tools, specifically `cli\Table`

**Comment by szepeviktor** [comment]
:smile: php-cli-tools is not upstream.

**Comment by szepeviktor** [comment]
SQl `%%` -> `%` could be after `strlen()`.

**Comment by danielbachhuber** [comment]
@szepeviktor Create a pull request with test coverage?

**Comment by szepeviktor** [comment]
We have a bigger problem. `post_title = '%10'` fools php-cli-tools.

**Comment by szepeviktor** [comment]
@danielbachhuber In Wp-cli's Formatter I've added a protection:
```php
array_walk_recursive( $data , function ( &$item, $key ) {
  $item = str_replace( '%', '%%%%', $item );
} );
```
and modified Stream\render
```php
$args[0] = preg_replace('/[^%](%([^%\w]|$))/', "%$1", $args[0]);
```
and cli\safe_str_pad
```php
// Protected % signs
$cleaned_string = str_replace( '%%%%', '%', $cleaned_string );
```
Is it too complicated? Now It prints one percent sigen per `%`, and pads accordingly.

**Comment by szepeviktor** [comment]
Background: colorize **and** sprintf converts `%%` to `%`.

**Comment by danielbachhuber** [comment]
> Is it too complicated? Now It prints one percent sign per %, and pads accordingly.

Can you submit a PR for it?

My initial reaction is that we need to escape all values before we pass them to Formatter, because `cli\Table` shouldn't need to know the difference between colorized strings and uncolorized strings.

**Comment by szepeviktor** [comment]
> we need to escape all values before we pass them to Formatter

Formatter is called from almost all commands. Do you mean to add an escaping function to these calls?

**Comment by danielbachhuber** [comment]
> Do you mean to add an escaping function to these calls?

I guess but I still don't fully understand the extent of the problem. I'd think `cli\Table` shouldn't be colorizing strings. If it is though, I don't want to change that behavior — we'll just need to escape our non-colorized values before we send them in.

**Comment by szepeviktor** [comment]
But in php-cli-tools [colorize and sprintf converts `%%` to `%`](https://github.com/wp-cli/wp-cli/issues/1736#issuecomment-94378968), so `%%%%` wil get shortened to just `%`.

**Comment by szepeviktor** [comment]
Do you mean `%` → `%%%%` by escaping?
