### ISSUE TITLE
Custom content directory

### ISSUE THREAD

**Issue by joehandsome** [wp-cli/wp-cli#1737]
Hi,
i use in my wp-config 'WP_CONTENT_DIR' but this seems to have no effect on for example 'wp plugin list'. Is this a bug or are there any known workarounds ?

**Comment by danielbachhuber** [comment]
> i use in my wp-config 'WP_CONTENT_DIR' but this seems to have no effect on for example 'wp plugin list'.

Can you share how the code is defined?

**Comment by joehandsome** [comment]
my wp-config.php looks like that:
...
define('WP_HOME','http://test.de');
define('WP_SITEURL','http://test.de/wordpress');
define('WP_CONTENT_URL', 'http://test.de/content');
define('WP_CONTENT_DIR', realpath($_SERVER['DOCUMENT_ROOT'] . '/content'));
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');
require_once(ABSPATH . 'wp-settings.php');

and my Document_Root looks like that:
wordpress/
content/
index.php
wp-config.php
..

**Comment by jmslbam** [comment]
It looks like your WordPress also lives in an other directory, right?

Can you set your `wp-cli.yml` config like this / or create one on the same level as your `wp-config.php`
```
path: wordpress
```
See for more info: http://wp-cli.org/config/

https://github.com/roots/bedrock does it like that

**Comment by jmslbam** [comment]
and shouldn't the ABSPATH be have `wordpress` behind it? 

Like https://github.com/roots/bedrock/blob/master/config/applications php?

**Comment by joehandsome** [comment]
bedrock has a different directory structure, all wordpress stuff is in the directory wp.
I have my core in the directory wordpress and all the other content, like uploads,theme,plugins,... in directory content.

So i still guess, that "WP_CONTENT_DIR" is maybe not used correctly by wp-cli ?

**Comment by joehandsome** [comment]
i also tried to define WP_PLUGIN_DIR and WP_PLUGIN_URL in wp-config.php and 'wp plugin path' is still empty :(

**Comment by szepeviktor** [comment]
Try using absolute path instead `realpath($_SERVER['DOCUMENT_ROOT']`.

**Comment by joehandsome** [comment]
thanks, i use dirname(__FILE__) now instead of $_SERVER['DOCUMENT_ROOT'] and it works.

**Comment by szepeviktor** [comment]
Please close the issue.

**Comment by danielbachhuber** [comment]
Previously: https://github.com/wp-cli/wp-cli/issues/785#issuecomment-24915224

**Comment by jorgeorpinel** [comment]
Note: this had been solved back in the day in https://github.com/wp-cli/wp-cli/issues/137 but issue seems to be back. It seems using `dirname(__FILE__)` is the only option for now.
