### ISSUE TITLE
Different wp-cli.yml values for different environments

### ISSUE THREAD

**Issue by asanger** [wp-cli/wp-cli#1742]
I've found a few things that are close to what I need, but nothing that works or fully answers my question.

What I want to be able to do is use wp-cli to pull down a database from production (`wp db export`), then import that dump into a local database (`wp db import`), and finally run a search/replace on the new local db (`wp search-replace`). It's an extremely simple sequence of events, but I can't figure out a way to update the config parameters between the export and the import.

Ideally, I would have something like `wp-cli.development.yml` and `wp-cli.production.yml` and could call `wp production db export` then `wp development db import` and so on, though I know that's not possible without a plugin. 

A close second would be the ability to override the configured db values as parameters when calling the command, like `wp db export --dbname="prod-db" --dbhost="www.somehost.com" etc`

Does anybody have advice on how I might achieve something like this?

Here are some related links
#1061 Discussion about something very similar
https://github.com/viewone/wp-cli-environment Plugin by the author of the above issue, but non-functional.

**Comment by scribu** [comment]
Less pretty, but more explicit and no extra plugin required:

```
WP_CLI_CONFIG_PATH=wp-cli.development.yml wp db export
```

**Comment by scribu** [comment]
You could even implement the desired syntax in a bash script:

```bash
environment=$1
shift
WP_CLI_CONFIG_PATH=wp-cli.{$1}.yml wp $@
```

(not tested)

**Comment by asanger** [comment]
ah, nice! I'll give this a shot shortly, and if it works I'll go ahead and close this. Thanks!

**Comment by asanger** [comment]
Alright - so the issue now is that wp-cli uses the wp-config.php values for `db` commands, so while setting the `WP_CLI_CONFIG_PATH` does load the specified yml file, it will still just pull the values from whatever wp-config.php has.

Is there a way to override wp-config.php values when running a command? Or maybe specify the path of the wp-config.php so I can have a wp-config.production.php? Or will I have to run `wp core config` any time I need to switch environments?

**Comment by scribu** [comment]
I don't get it - aren't there two separate WP installs - one for production (on a remote server) and one for development (local) - each with its own `wp-config.php` file?

**Comment by asanger** [comment]
Correct - there's a production install (remote), and then theoretically an infinite number of other installs that will be based on that remote production.

My workflow is as follows:
Assume that a production environment exists. I need to do some development work locally, so I clone the repository to my desktop, run a script to fetch the production (remote) database, dump it to a local file, import the file to my local db, and search/replace the URLs with localhost.

This exact same process would need to be performed if I wanted to push everything to a staging server to be tested. Staging server would fetch the production db, load it locally, and replace the prod url with the staging url.

Get where I'm going with this?

**Comment by scribu** [comment]
One potential solution is to include some conditional logic inside `wp-config.php`:

```php
if (is_readable('wp-config.local.php')) {
  require('wp-config.local.php');
} else {
  // define production values
}
```

instead of `is_readable()`, you could check an environment variable etc.

**Comment by asanger** [comment]
Appreciate the ideas. I'm going to play around with mixing wp-cli and straight mysqldump within a bash script to see if I can get the desired results. Thanks again!
