### ISSUE TITLE
Customize Download of WP Core

### ISSUE THREAD

**Issue by joshsmith01** [wp-cli/wp-cli#1744]
I'd like to install wp core with only one theme, twentyfifteen. If I can't download only one can I delete all but twentyfifteen?

I've tried `wp theme delete all --skip-themestwentyfifteen`

Skip loading all or some themes
The docs state all or some but I can't figure out how to delete all of them. Skip loading all or some themes

**Comment by danielbachhuber** [comment]
```
wp theme delete $(wp theme list --field=name); wp theme install twentyfifteen
```

**Comment by captin411** [comment]
wp theme list --status=inactive --field=name | while read THEME; do wp theme delete $THEME; done;

**Comment by captin411** [comment]
I should have explained that last command a bit better. I'm sorry.

First this runs the command theme list and puts each inactive theme name on one line.

Then I pipe (|) each line through the shell 'while read X; do ....; done;' portion.

This takes each line and assigns it to a variable named 'THEME'.  Then it runs the wp theme delete command with that shell variable.

**Comment by joshsmith01** [comment]
Perfect!
