### ISSUE TITLE
Quoted options that start with -- are interpreted as WP options

### ISSUE THREAD

**Issue by theMikeD** [wp-cli/wp-cli#1745]
```
$ wp post meta set 1060 story_author_bio '- hi'
Success: Updated custom field.

$ wp post meta set 1060 story_author_bio "hi -- hi"
Success: Updated custom field.

$ wp post meta set 1060 story_author_bio '-- hi'
Error: Parameter errors:
 unknown -- hi parameter

$ wp post meta set 1060 story_author_bio "-- hi"
Error: Parameter errors:
 unknown -- hi parameter
```

**Comment by danielbachhuber** [comment]
Ew, this bug is rough. By the time the arguments get to `Configurator::parse_args()`, the quoting has been stripped:

```
salty-wordpress ➜  wordpress-test.dev  wp option update foo '--bar'
array (
  0 => 'option',
  1 => 'update',
  2 => 'foo',
  3 => '--bar',
)
Error: Parameter errors:
 unknown --bar parameter
salty-wordpress ➜  wordpress-test.dev  wp option update foo --bar
array (
  0 => 'option',
  1 => 'update',
  2 => 'foo',
  3 => '--bar',
)
Error: Parameter errors:
 unknown --bar parameter
```

I'll have to give some thought as to how to address this.

**Comment by theMikeD** [comment]
I'm doing a huge conversion of a custom CMS to WP (huge meaning 27,000 posts) which is why I'm getting all these corner cases. I'll help however I can.

**Comment by danielbachhuber** [comment]
> I'm doing a huge conversion of a custom CMS to WP (huge meaning 27,000 posts) which is why I'm getting all these corner cases.

Always happens :)

> I'll help however I can.

Pull requests welcome!

**Comment by szepeviktor** [comment]
In shell it is usually `wp option update foo -- --bar`.

**Comment by szepeviktor** [comment]
But wp-cli does not have this data protection (`--`) feature.
The `grep` command behaves the similar way:

```bash
$ grep '--only-matching apply' o.php
grep: unrecognized option '--only-matching apply'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

$ grep --only-matching apply o.php
apply

$ grep 'only-matching apply' o.php ; echo $?
1
```

**Comment by theMikeD** [comment]
Using bash this also fails
```
touch /tmp/t
wp post create /tmp/t --post_title="This will fail !?" 
```
because !? is being interpreted by the shell as the previous command. The exact error will vary depending on what the previous command was.

This does too
```
touch /tmp/t
wp post create /tmp/t --post_title="This will fail $Â" 
```
because $Â is being interpreted as a variable with an invalid name.

FYI

```
/bin/bash --version
GNU bash, version 3.2.51(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by szepeviktor** [comment]
Use single quotes.

**Comment by theMikeD** [comment]
```
wp post create /tmp/t --post_title='This will fail \' !?'
```
also fails

**Comment by szepeviktor** [comment]
You're a moving target. That is:
```
'String '"'"' !?'
```

**Comment by theMikeD** [comment]
Yes, that is the quagmire to which I was referring. Thanks for the help :)

**Comment by szepeviktor** [comment]
If you use shell you should be familiar with quoting Unless you like bad surprises.
Pls close the issue.

**Comment by theMikeD** [comment]
The issues I added today were added to this bug because I thought they were related. As it turns out, they are not. That does not imply the original bug is invalid.

As for what I should or shouldn't be familiar with if I'm using the command line, there are many levels of experience. I suggest you keep that in mind, as statements such as yours come off as condescending when I'm sure they are not intended to be.

**Comment by szepeviktor** [comment]
Oh!! I am very sorry about that.

**Comment by szepeviktor** [comment]
Please excuse me.

**Comment by szepeviktor** [comment]
A unixy solution would be `--` as in https://github.com/wp-cli/wp-cli/issues/1745#issuecomment-89670774.

**Comment by theMikeD** [comment]
No problems Viktor, really! :) I have the same problems too. In fact, my reply could be interpreted that way too. It's all good, we all want the same thing: wp-cli to be the best it can be.

**Comment by b-long** [comment]
:+1: Nice find @theMikeD

**Comment by scribu** [comment]
+1 for `--`. I use it all the time with git.

**Comment by danielbachhuber** [comment]
> Quoted options that start with `--` are interpreted as WP options

As it turns out, we can't use `--` in this case because `$argv` is too lossy. Instead, `--format=json` is a better approach:

```
wp post meta set 1060 story_author_bio '"-- hi"' --format=json
```
