### ISSUE TITLE
Plugin scaffold: Add gruntfile with readme to markdown enabled

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1748]
https://github.com/stephenharris/wp-readme-to-markdown

**Comment by danielbachhuber** [comment]
https://github.com/fusioneng/Unified-Post-Types/commit/9b280f07e8ba79977f54103f938e0422ee63a1f2 has code to steal

**Comment by szepeviktor** [comment]
Nice finding.
