### ISSUE TITLE
wp theme delete won't accept variables

### ISSUE THREAD

**Issue by joshsmith01** [wp-cli/wp-cli#1749]
Related to: https://github.com/wp-cli/wp-cli/issues/1744

I keep recieving this error: `Warning: The 'twentyfourteen
twentythirteen' theme could not be found.`, when I try to remove multiple themes at once. If I type each theme name in in by hand then all the themes will be deleted. Such as: wp theme delete twentyfourteen twentythirteen` 

I think that the script would be more robust if I could install WP, then identify which themes are inactive and then delete those. 

So is there a way to use a variable in this command or do I have to type each theme name out explicitly?

**Comment by danielbachhuber** [comment]
> I keep recieving this error: Warning: The 'twentyfourteen twentythirteen' theme could not be found., when I try to remove multiple themes at once.

Can you share the command you're using to delete the themes?

**Comment by joshsmith01** [comment]
The command was: `wp theme delete $(wp theme list --field=name); wp theme install twentyfifteen`

I have since resolved the issue using this command: `wp theme list --status=inactive --field=name | while read THEME; do wp theme delete $THEME; done;`

and [this](https://github.com/wp-cli/wp-cli/issues/1744#issuecomment-90953924)
