### ISSUE TITLE
Change composer for array_column

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/wp-cli#1750]
It seems that rhumsaa/array_column has been abandoned. It has been replace with [ramsey/array_column](https://github.com/ramsey/array_column). I am currently getting an notification when I build with WP CLI about it being abandoned. 

For reference - https://packagist.org/packages/rhumsaa/array_column

**Comment by danielbachhuber** [comment]
Fixed already in 3dc3421c98ce3380fc4d6628dfa0d0fca349e9fe

**Comment by spacedmonkey** [comment]
Do you know when this will be put into stable build 0.18.1 or 0.19.0? The message bugs me :smile:

**Comment by danielbachhuber** [comment]
> Do you know when this will be put into stable build 0.18.1 or 0.19.0?

Hopefully shipping v0.19.0 in the next week and a half or so. If not, I can release v0.18.1
