### ISSUE TITLE
Make `search-replace` a subcommand of `db`

### ISSUE THREAD

**Issue by 8ig8** [wp-cli/wp-cli#1752]
A relatively minor issue, but it seems `search-replace` is better suited as a subcommand under the `db` command instead of being a top-level command as it is now.

(Thank you for all the work on wp-cli.)

**Comment by nyordanov** [comment]
I agree, but the top-level command should be kept as a (deprecated) alias.

**Comment by danielbachhuber** [comment]
> but it seems search-replace is better suited as a subcommand under the db command instead of being a top-level command as it is now.

I see what you're saying. I don't think there's much value in changing it now though.
