### ISSUE TITLE
Core Download Permissions

### ISSUE THREAD

**Issue by robertjw1** [wp-cli/wp-cli#1753]
I really love wp-cli, but I have noticed that every time I do a core download the permissions are wrong and the new installation won't run - Apache gives errors

I typically run this to fix the permissions
find . -type d -exec chmod 755 {} \;  # Change directory permissions rwxr-xr-x
find . -type f -exec chmod 644 {} \;  # Change file permissions rw-r--r--

Not sure if this is a bug or if I'm missing something, but thought I would share.  Thanks!

**Comment by voldemortensen** [comment]
I've never had this issue. Maybe its a server configuration issue?
Besides that, I'm hesitant to run those commands because it will ruin any scripts that need the executable permission. i.e. all my shell/perl scripts.

**Comment by robertjw1** [comment]
Wasn't necessarily suggesting you add the commands, just passing along what I did. I only run that in the directory where I've done a new download.

wp core download

I wouldn't think you would want any executable scripts in the WP directory structure.  

I think I'm running a pretty standard configuration.  Running ubuntu with a standard Apache server. 

If I get a few minutes I'll try to break it down further.  I haven't had this problem when pulling a latest.tar.gz down and extracting it.

**Comment by danielbachhuber** [comment]
> I really love wp-cli, but I have noticed that every time I do a core download the permissions are wrong and the new installation won't run - Apache gives errors

What do the permissions get set to? This is what I get:

```
salty-wordpress ➜  www  wp core download --path=wp-cli-test
Creating directory /srv/www/wp-cli-test/
Downloading WordPress 4.1.1 (en_US)...
Success: WordPress downloaded.
salty-wordpress ➜  www  ls -al wp-cli-test
total 164
drwxr-xr-x 1 vagrant vagrant   714 Apr  9 21:33 .
drwxr-xr-x 1 vagrant vagrant   850 Apr  9 21:32 ..
-rw-r--r-- 1 vagrant vagrant   418 Apr  9 21:33 index.php
-rw-r--r-- 1 vagrant vagrant 19930 Apr  9 21:33 license.txt
-rw-r--r-- 1 vagrant vagrant  7195 Apr  9 21:33 readme.html
-rw-r--r-- 1 vagrant vagrant  4951 Apr  9 21:33 wp-activate.php
drwxr-xr-x 1 vagrant vagrant  2992 Apr  9 21:33 wp-admin
-rw-r--r-- 1 vagrant vagrant   271 Apr  9 21:33 wp-blog-header.php
-rw-r--r-- 1 vagrant vagrant  5008 Apr  9 21:33 wp-comments-post.php
-rw-r--r-- 1 vagrant vagrant  2726 Apr  9 21:33 wp-config-sample.php
drwxr-xr-x 1 vagrant vagrant   170 Apr  9 21:33 wp-content
-rw-r--r-- 1 vagrant vagrant  2956 Apr  9 21:33 wp-cron.php
drwxr-xr-x 1 vagrant vagrant  4250 Apr  9 21:33 wp-includes
-rw-r--r-- 1 vagrant vagrant  2380 Apr  9 21:33 wp-links-opml.php
-rw-r--r-- 1 vagrant vagrant  2714 Apr  9 21:33 wp-load.php
-rw-r--r-- 1 vagrant vagrant 33435 Apr  9 21:33 wp-login.php
-rw-r--r-- 1 vagrant vagrant  8252 Apr  9 21:33 wp-mail.php
-rw-r--r-- 1 vagrant vagrant 11115 Apr  9 21:33 wp-settings.php
-rw-r--r-- 1 vagrant vagrant 25152 Apr  9 21:33 wp-signup.php
-rw-r--r-- 1 vagrant vagrant  4035 Apr  9 21:33 wp-trackback.php
-rw-r--r-- 1 vagrant vagrant  3032 Apr  9 21:33 xmlrpc.php
```

**Comment by robertjw1** [comment]
Hmm... that's different than mine

[bob@aramis temp]$ wp core download
Downloading WordPress 4.1.1 (en_US)...
Using cached file '/home/bob/.wp-cli/cache/core/en_US-4.1.1.tar.gz'...
Success: WordPress downloaded.
[bob@aramis temp]$ ls -alh
total 724K
drwxrwxr-x  5 bob bob 4.0K Apr  9 15:38 ./
drwxr-xr-x 61 bob bob 4.0K Apr  9 15:24 ../
-rw-------  1 bob bob 539K Dec 15  2011 .bashrc
-rw-rw-r--  1 bob bob  418 Apr  9 15:38 index.php
-rw-rw-r--  1 bob bob  20K Apr  9 15:38 license.txt
-rw-rw-r--  1 bob bob 7.1K Apr  9 15:38 readme.html
-rw-rw-r--  1 bob bob 4.9K Apr  9 15:38 wp-activate.php
drwxrwxr-x  9 bob bob 4.0K Apr  9 15:38 wp-admin/
-rw-rw-r--  1 bob bob  271 Apr  9 15:38 wp-blog-header.php
-rw-rw-r--  1 bob bob 4.9K Apr  9 15:38 wp-comments-post.php
-rw-rw-r--  1 bob bob 2.7K Apr  9 15:38 wp-config-sample.php
drwxrwxr-x  4 bob bob 4.0K Apr  9 15:38 wp-content/
-rw-rw-r--  1 bob bob 2.9K Apr  9 15:38 wp-cron.php
drwxrwxr-x 12 bob bob 4.0K Apr  9 15:38 wp-includes/
-rw-rw-r--  1 bob bob 2.4K Apr  9 15:38 wp-links-opml.php
-rw-rw-r--  1 bob bob 2.7K Apr  9 15:38 wp-load.php
-rw-rw-r--  1 bob bob  33K Apr  9 15:38 wp-login.php
-rw-rw-r--  1 bob bob 8.1K Apr  9 15:38 wp-mail.php
-rw-rw-r--  1 bob bob  11K Apr  9 15:38 wp-settings.php
-rw-rw-r--  1 bob bob  25K Apr  9 15:38 wp-signup.php
-rw-rw-r--  1 bob bob 4.0K Apr  9 15:38 wp-trackback.php
-rw-rw-r--  1 bob bob 3.0K Apr  9 15:38 xmlrpc.php

**Comment by danielbachhuber** [comment]
Oh. Apache is probably running as `www-data` or similar. Your files are owned by `bob`. You need to run commands as `www-data`, or change ownership after you've downloaded.

**Comment by robertjw1** [comment]
Right, I assign ownership, and that's not your problem, but the permissions are different.  Notice how mine are rw on the group, while yours aren't?  Why are they different?

**Comment by robertjw1** [comment]
Probably a umask setting on my local system.  Makes sense now.  Thanks!

**Comment by captin411** [comment]
I wonder, should wp-cli warn if a umask looks suspect?

**Comment by danielbachhuber** [comment]
Could. Seems like a nice minor enhancement to throw a warning

**Comment by robertjw1** [comment]
My umask is the default Ubuntu setting of 002, something about USERGROUPS_ENAB defaulting to yes and giving group permissions to everything.
