### ISSUE TITLE
PHP Parse error on WP-CLI, not on web server

### ISSUE THREAD

**Issue by jorgeorpinel** [wp-cli/wp-cli#1754]
I have a network of over a hundred sites and I try to use wp-cli to make bulk changes to many of these. Particularly to their wp_x_options table via wp --url=site.url option update <key> <value>

However, wp commands fail with several of my files, severely limiting the usefulness of the tool, particularly when trying to run with a list of urls | xargs wp --url={} ... because after the first failure, the rest are skipped.

The error I get is always the same:

    PHP Parse error: syntax error, unexpected end of file in ... /functions.php

This error does not happen when loading the pages normally via the browser. My functions.php files are perfectly OK. Some of them don't have a closing ?> tag but that can't be the problem since many of these (lacking closing ?>) run OK with wp-cli.

Any thoughts?

WP-CLI 0.18.0
Wordpress 4.0.1
PHP 5.5.9-1ubuntu4.4 (cli)
php.ini has 
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off

**Comment by jorgeorpinel** [comment]
Also posted at https://wordpress.stackexchange.com/questions/183781/php-parse-error-on-wp-cli-not-on-web-server

**Comment by danielbachhuber** [comment]
What happens when you run `php -l /path/to/functions.php` ?
Can you share the contents of your functions.php, minus any secrets?

**Comment by jorgeorpinel** [comment]
Same error indeed with php -l . Confused. The website runs normally. I'm running nginx with PHP FPM though, wonder if that makes a difference.

WAIT it may be a lazy <? without "php" in my functions.php , I think I set fpm's php.ini to short_open_tag=On but not on cli ! Let me try that...

**Comment by jorgeorpinel** [comment]
YUP that was that >:| sorry about the false alarm. Perhaps someone else will find this "issue" useful though.

Just enabled

    short_open_tag=On

in /etc/php5/cli/php.ini

p.s. this is an aws ubuntu box

**Comment by danielbachhuber** [comment]
> short_open_tag=On

You should fix your code and [disable short tags](http://stackoverflow.com/questions/200640/are-php-short-tags-acceptable-to-use) :)

**Comment by jorgeorpinel** [comment]
I will eventually. I have many, many legacy themes developed by 3rd parties. When I find a good way to replace only <? (and not '<?' in "<?php" in thousands of files reliably, I'll go for it :) .

**Comment by captin411** [comment]
You may try a regular expression similar to this:

`s/<?([^p])/<?php\1/g`

and

`s/([^p])?>/\1php?>/g`

Test these before blindly copying and pasting - consider these 'pseudo regular expressions' as I have not run them myself.

Syntax and escaping of the parenthesis and backspace will vary depending on the language or quoting you are using.  The '\1' may also be done differently again dependent on the regular expression engine in your language of choice.

However, the spirit of this expression is:
- match '<?'
- if it is followed "by anything but a 'p'"
-- save "that thing that is not a 'p'"
-- replace <?[thing] with <?php[thing] -- this is good for example if it is a space and you want "<?php " properly

The caveat is that if you have an actual string in php that has a <? in it this will be naïve.  Probably not likely but you'll want to at least use some process to look at your changes after you make them... perhaps using git diff for a before and after.

**Comment by jorgeorpinel** [comment]
Awesome thanks for the suggested regex.

There's also the cavet of <?= :D

I'll get to this at some point. Not really a problem for anyone right now. Cheers
