### ISSUE TITLE
Bitnami Issues

### ISSUE THREAD

**Issue by zrosenbauer** [wp-cli/wp-cli#1755]
Has anyone got this to work with local Bitnami installs. We use Bitnami at production level but would love to be able to use this but it is causing a host of issues from: 

Access denied for user 'bn_wordpress'@'localhost'

to Not a Wordpress Install error

I have tried many types of structures, local.yml changes etc. Let me know if you have any pointers and I can also add more information as needed.

**Comment by danielbachhuber** [comment]
Can you share more environmental details for when you get each error?

It seems like the environment is reasonably well-supported. Have you asked them to package and support WP-CLI?

**Comment by lukecav** [comment]
WP-CLI should be packaged in the WordPress application.

https://bitnami.com/stack/wordpress
