### ISSUE TITLE
first time installing wp-cli, need guidance

### ISSUE THREAD

**Issue by spwebtest** [wp-cli/wp-cli#1756]
This is where I hope experience can help where I am not sure, not a very long time mac user but getting
myself familiar with the command line.

I have included a couple of screen shots that hope can explain better than what I type.

![screen shot 2015-04-10 at 09 46 39](https://cloud.githubusercontent.com/assets/8846625/7084588/b9e4cf6a-df66-11e4-9ac7-442dda37a1a0.png)

I seem fine downloading wp-cli and the version checks out fine when downloaded, but when it comes to moving it and checking wp --info it doesn't seem to find it

![screen shot 2015-04-10 at 09 47 59](https://cloud.githubusercontent.com/assets/8846625/7084597/d1f787b4-df66-11e4-9c21-a07bbcdc2510.png)

**Comment by danielbachhuber** [comment]
You'll need to add `/usr/local/bin` to your `PATH`, or instead move WP-CLI to `/usr/bin` after download:

`sudo mv wp-cli.phar /usr/bin/wp`

**Comment by spwebtest** [comment]
Hey thanks Daniel I did a re-install and as you suggested and all it good :)
