### ISSUE TITLE
install-wp-tests.sh should use git

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/wp-cli#1757]
The install-wp-tests.sh script should not use svn. It makes it harder to run the tests if you have to make sure that SVN is installed as well. Other plugins seem to using git. Take yoast for example. 

https://github.com/Yoast/wordpress-seo/blob/trunk/.travis.yml#L40-L52

**Comment by michaelbeil** [comment]
The `install-wp-tests.sh` script pulls from SVN for the PHPUnit tests available in trunk, whereas Yoast is using the Git repo of WordPress for testing builds of his plugin against the latest version of WP and several versions of PHP on https://travis-ci.org. Hence, `svn co --quiet https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/` (see: https://github.com/wp-cli/wp-cli/blob/master/templates/install-wp-tests.sh#L53) for local development testing. 

Does that make sense?

**Comment by spacedmonkey** [comment]
It doesn't. If you look at jetpack it is using git as well. Look [here]( https://github.com/Automattic/jetpack/blob/master/.travis.yml#L38-L50). It checkouts of from the develop branch of wordpress that contains the WP tests. It is using [WP_UnitTestCase](https://github.com/Automattic/jetpack/blob/master/tests/test_class.functions.compat.php#L3).

**Comment by danielbachhuber** [comment]
> It makes it harder to run the tests if you have to make sure that SVN is installed as well.

Can you explain your logic? What if I don't have git installed?

**Comment by spacedmonkey** [comment]
It means that I have to have SVN installed on any machine I want to run the tests on. It is a pain, as I (and most developers I know) use git full time now. I had a look around at everyone else was doing for their unit tests and saw many are just using git. It is about making it easier to run the test, but your point is valid if you don't have git installed. 

Look, personally I am going to write this for my tests, change the install script to use git. I just wondering if you guys want to make the change / push this upstream with a pull request.

**Comment by danielbachhuber** [comment]
Given the WordPress project officially uses SVN, I think SVN needs to remain the prerequisite. You can easily install SVN alongside git. And yes, I use git full-time too.
