### ISSUE TITLE
wp --info ???    p? garbled character

### ISSUE THREAD

**Issue by centminmod** [wp-cli/wp-cli#1758]
Been using wp-cli tool on centos for ages now without problem

but this is first time I came across this error on whm/cpanel server.

After installing wp-cpi, all I see when i run wp command line is these characters ?

    wp --info
    ???
       p?

any ideas ?

**Comment by szepeviktor** [comment]
Please share `wp --info 2>&1|hexdump -C`.

**Comment by centminmod** [comment]
here's output
    
    wp --info 2>&1|hexdump -C
    00000000  3f 3f 3f 0c 70 3f                                 |???.p?|
    00000006

**Comment by szepeviktor** [comment]
So these are real question marks.
Try cloning the repository, [install composer](https://getcomposer.org/download/) and run `composer install` in the repo. Then start wp-cli as `/path/to/repo/bin/wp --info`.

**Comment by frenkel** [comment]
Same problem on OpenBSD with php-5.3.29. Unfortunately I'll not be able to try the steps you suggested.

**Comment by szepeviktor** [comment]
@frenkel This is a complete wp-cli v0.21.0-alpha for you.
http://ovh.to/Yc9q1ZG

**Comment by frenkel** [comment]
@szepeviktor Thanks. That package does not give me any problems, so I guess the bug was fixed already.

**Comment by szepeviktor** [comment]
...or it is phar-related.

**Comment by frenkel** [comment]
Yes, of course, that might be possible as well. It is possible for you to build a simple "hello world" phar that I can use to test?

**Comment by szepeviktor** [comment]
Here you are http://ovh.to/XAyeV3

**Comment by frenkel** [comment]
```
$ php-5.3 hello.phar                                                           
??????$    
$ php-5.6 hello.phar                                                           
Tot straks, Frank!
```
Found the cause! Somewhere between php 5.3 and 5.6 the phar functionality was fixed.

**Comment by szepeviktor** [comment]
> You may optionally wish to enable the zlib and bzip2 extensions to take advantage of compressed phar support.

**Comment by szepeviktor** [comment]
and:
> PHP 5.3 configured with --enable-zend-multibyte makes phar dependant on the ini option detect_unicode.

**Comment by szepeviktor** [comment]
Do you have phar extension on 5.3?

**Comment by frenkel** [comment]
It is compiled with `--enable-zend-multibyte` and I do have the Phar extension on 5.3. I don't see `detect_unicode` anywhere on the php.net site. Where did you find that quote?

**Comment by szepeviktor** [comment]
Here http://php.net/manual/en/phar.requirements.php

**Comment by frenkel** [comment]
None produce the result we want:
```
$ php-5.3 -d detect_unicode=Off hello.phar  
$ php-5.3 -d detect_unicode=On hello.phar   
??????
```

**Comment by szepeviktor** [comment]
Sorry, I am out of new ideas.

**Comment by szepeviktor** [comment]
http://stackoverflow.com/questions/15216292/not-able-to-run-composer-phar

**Comment by szepeviktor** [comment]
Just fired up PHP 5.3 on [Digital Ocean](https://www.digitalocean.com/?refcode=1f29354cd6ab)
and sad :cry: news, no ouotput...

**Comment by szepeviktor** [comment]
BUT!
`$ php -d suhosin.executor.include.whitelist=phar ./wp-cli-0.20.1.phar -- --info` works.

**Comment by szepeviktor** [comment]
Could you try to execute test.php:
```
<?php
echo "OK\n";
__halt_compiler();
```

**Comment by frenkel** [comment]
That prints:
`OK`

**Comment by szepeviktor** [comment]
And how about `suhosin.executor.include.whitelist`?

**Comment by frenkel** [comment]
Same problem unfortunately.

**Comment by szepeviktor** [comment]
The phar extension must have a problem.


-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!
