### ISSUE TITLE
Loosen nixes as requirement

### ISSUE THREAD

**Issue by Rarst** [wp-cli/wp-cli#1759]
The requirements prominently ask for nixes first thing:

> UNIX-like environment (OS X, Linux, FreeBSD, Cygwin)

> http://wp-cli.org/

While wp-cli is far from perfect on Win platform, these days it runs reasonably well, even in simple `cmd` shell. Not _everything_ might work, but _many_ things do.

In my opinion it might be time to (cautiously) loosen the requirement on this. Having more people on Win use it will speed up discovery of lingering issues too, it's self sustaining process pretty much.

**Comment by danielbachhuber** [comment]
> In my opinion it might be time to (cautiously) loosen the requirement on this.

Travis doesn't currently support running builds against Windows. Are you offering to do all of the necessary maintenance? I don't have any desire to support Windows personally.

**Comment by Rarst** [comment]
I am not urging to declare Windows as fully supported, I am urging to mention technical possibility to run on it at all. Current wording implies otherwise.

**Comment by danielbachhuber** [comment]
> I am urging to mention technical possibility to run on it at all. Current wording implies otherwise.

Ok, that's fine. Submit a PR with suggested change? https://github.com/wp-cli/wp-cli.github.com
