### ISSUE TITLE
`wp term list category --name="Name of Category"` does not work

### ISSUE THREAD

**Issue by markjaquith** [wp-cli/wp-cli#1760]
`wp term list` says you can pass `--field=<value>` to filter its results.

Indeed, this works:

`wp term list category --slug="category-slug"`

But this returns all categories:

` wp term list category --name="Name of Category"`

**Comment by markjaquith** [comment]
My workaround, for anyone stumbling upon this:

`wp eval "echo get_term_by( 'name', 'Name of Category', 'category' )->term_id;"`

**Comment by danielbachhuber** [comment]
Thanks for the report. This enhancement is coming in WP 4.2 https://core.trac.wordpress.org/ticket/30611
