### ISSUE TITLE
On completed command load file (Feature request)

### ISSUE THREAD

**Issue by timnashcouk** [wp-cli/wp-cli#1761]
WP-CLI currently supports require: either within YAML or via --require which loads a PHP file. Which in effect provides a pre command script launch facility though I suspect that wasn't the intention. This is really useful for example for setting up tests etc. It would be useful to have a similar at the end of the process.

While you can daisy chain commands through the command line, and pipe results etc, it would be nice to be able to simply execute any cleanup scripts either set in YAML or through --postcommand or similar.

My current separate use case for a postcommand is using Liquibase to do database versioning, when interacting via the WP-CLI I want to call Liquibase post command to generate the database diffs for versioning control of the database. So after each command, run by WP-CLI fire off a check for Liquibase because multiple users the ideal world this would be seamless, hence the suggestion of a post command file load, which would then exec Liquibase.

**Comment by theMikeD** [comment]
Sounds like a shell script would be ideal for this...?

**Comment by timnashcouk** [comment]
Well it would be ideal to execute something post the command, but given the existing limitations it makes more sense for it to be a another PHP file.

However I suspect you actually meant, why not wrap the two actions inside a shell script? 
Pretty much for the reasons outlined above, a shell script is only useful if everyone has it within the team and executes it. Much easier for it to be set as part of the wp-cli config if its going to be executed each time. The second big benefit in my DB versioning example, is with no knowledge of which commands are being executed, you would need to either write a wrapper for WP-CLI and execute that or have an awful lot of shellscripts.

The third reason for not using shell scripts is that it helps reduce down the number of moving parts and mirrors existing use cases inside WP-CLI codebase.

**Comment by theMikeD** [comment]
I'm a bit confused by the use case as written in the OP, sorry if I'm missing something. Is there a reason why the shell script can't be versioned and put into PATH for your team? And does the DB versioning command change every time you use it? Or only when you use it on different installs?

**Comment by szepeviktor** [comment]
Try using `--require` and hook into WP's shutsown action.
```php
add_action( 'shutdown', 'liquibase_database_versioning' );
```

**Comment by timnashcouk** [comment]
I think I have confused the issue with demoing two use cases at the same time and we have latched on to the interesting one and ignoring the boring one. 

So to simplify, currently WP-CLI offers the ability to load a PHP file either globally via config or manually prior to executing command. 

To have the same behaviour post command opens up an equal number of opportunities as the require does to pre command.

----
Using shell scripts for both require and post command are feasible though as detailed above not ideal and while require means you can load additional classes which commands may rely on, all the additional benefits of require basically exist for a post command equivalent.

@szepeviktor Require runs prior to wp-cli bootstrapping Wordpress, which is both a benefit and a curse so you can't use actions and hooks in it.

**Comment by danielbachhuber** [comment]
We have a simple hook system. `before_invoke` fires before a command is run: https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Dispatcher/Subcommand.php#L293

However, commands can run `exit;` In fact, `WP_CLI::error()` does. While we can add `after_invoke` hook, I'm hesitant to do so because we'd be making a promise (the hook will fire) we can't keep (the command may exit).

Are there other use cases you can share?

**Comment by timnashcouk** [comment]
Realistically I really see 2 primary use cases for this,

1) notifying something the command has completed
2) modifying / cleaning up after a command has run

I suspect most usecases sit in number 1, be it calling 3rd party logging, simply notifying slack that a command was run through to my slightly convoluted use case of doing db revisions. 

While number 1 could be done by bundling commands into a shell script, it's adding an extra layer of complication, and in some cases could be adding considerable work. The downside is as you say if we added a hook, no guarantee it fires, especially if the command fails or simply never exists. The other alternative is within the commands, which is fine for plugins and community packages that you are building but not an option with core commands.

However I think that's ok, if a function fails or doesn't exit then my action doesn't fire thats sort of assumed behaviour, infact in most circumstances for 1 you wouldn't want it to fire on non competition.

For number 2 style uses, the no guarantee of running is perhaps more of an issue, but again these would be isolated.

**Comment by danielbachhuber** [comment]
Can you check out #1770 to see how well that suits you?

**Comment by timnashcouk** [comment]
That works well :)

**Comment by danielbachhuber** [comment]
:ship:
