### ISSUE TITLE
Document empty trash

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1763]
Should be doable with `wp post delete $(wp post list --post_status=trash --format=ids)`. Let's make this explicitly documented.

Request from @tarendai

**Comment by Tarendai** [comment]
Wooo!!

**Comment by Onyx808** [comment]
@danielbachhuber I just tried and got the following result

``wp post delete $(wp post list --post_status=trash --format=ids)``
``usage: wp post delete <id>... [--force] [--defer-term-counting]``

What am I doing wrong?

**Comment by swissspidy** [comment]
@Onyx808 That sounds like you have no trashed posts. Just run `wp post list --post_status=trash --format=ids` to see if it returns any IDs.

However, **please** don't ccomment on 3-year-old closed issues on GitHub if you have questions about WP-CLI. Open a new one or ask on Slack.
