### ISSUE TITLE
You can activate child themes sans parents

### ISSUE THREAD

**Issue by Ipstenu** [wp-cli/wp-cli#1765]
Install a child theme (biker, child of jolene)

```wp theme install biker --activate```

Theme is installed and active and *broken* becuase jolene isn't there, which means I have to delete biker in order to get and run any wp-cli commands.

If I install without activating, it properly doesn't list them theme:

```
wp_d56vyn@wp398941:~/plugins.breakwpdh.com/wp-content/themes$ wp theme status
3 installed themes:
 A twentyfifteen  1.0
 I twentyfourteen 1.3
 I twentythirteen 1.4

Legend: A = Active, I = Inactive

wp_d56vyn@wp398941:~/plugins.breakwpdh.com/wp-content/themes$ ls -lah
total 20K
drwxr-xr-x 6 wp_d56vyn pg6084468  120 Apr 16 13:33 .
drwxr-xr-x 6 wp_d56vyn pg6084468  101 Apr 16 13:33 ..
drwxr-xr-x 6 wp_d56vyn pg6084468 4.0K Apr 16 13:33 biker
-rw-r--r-- 1 wp_d56vyn pg6084468   28 Jun  5  2014 index.php
drwxr-xr-x 7 wp_d56vyn pg6084468 4.0K Feb 18 14:10 twentyfifteen
drwxr-xr-x 9 wp_d56vyn pg6084468 4.0K Feb 18 14:10 twentyfourteen
drwxr-xr-x 8 wp_d56vyn pg6084468 4.0K Feb 18 14:10 twentythirteen
```

However you can still activate it:

```
wp_d56vyn@wp398941:~/plugins.breakwpdh.com/wp-content/themes$ wp theme activate biker
Success: Switched to 'Biker' theme.
wp_d56vyn@wp398941:~/plugins.breakwpdh.com/wp-content/themes$ wp theme install jolene
Fatal error: Call to undefined function jolene_get_defaults() in /home/wp_d56vyn/plugins.breakwpdh.com/wp-content/themes/biker/functions.php on line 32
```

Child themes should fail on activate if the parent isn't there, or just not be activatable.

**Comment by danielbachhuber** [comment]
> Child themes should fail on activate if the parent isn't there, or just not be activatable.

This behavior makes sense to me.

**Comment by Ipstenu** [comment]
I should not be able to activate a child theme if the parent theme isn't installed.

What's not sensible about that? That's how it works in wp-admin right now. You cannot activate a child theme unless the parent's installed.

**Comment by szepeviktor** [comment]
Maybe checking `get_template_directory() === get_stylesheet_directory()`?
