### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by joshlsullivan** [wp-cli/wp-cli#1773]
When I issue the following command, I get an error: wp plugin update --all.
I get this error:
WordPress database error Table 'misllc.wp_woocommerce_termmeta' doesn't exist for query SELECT t.*, tt.*, tm.*  FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id LEFT JOIN wp_woocommerce_termmeta AS tm ON (t.term_id = tm.woocommerce_term_id AND tm.meta_key = 'order')  WHERE tt.taxonomy IN ('product_cat') ORDER BY tm.meta_value+0 ASC, t.name ASC  made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), require('phar:///usr/local/bin/wp/php/wp-settings-cli.php'), do_action('init'), call_user_func_array, add_nectar_to_vc, require_once('/themes/salient/nectar/nectar-vc-addons/nectar-addons.php'), get_categories, get_terms

**Comment by danielbachhuber** [comment]
> 'misllc.wp_woocommerce_termmeta'

It looks like this table wasn't created properly, so you'll need to re-run Woo Commerce's installation script. I suspect the error occurs frequently, but is only exposed when you use WP-CLI.
