### ISSUE TITLE
Sometimes search-replace not working

### ISSUE THREAD

**Issue by yudaprama** [wp-cli/wp-cli#1774]
Hi thanks for the great software. I like it

I use search-replace to translate my wordpress into another language. However, sometimes it's not working. I use another options, still don't work. 

I compare to Better Search and Replace plugin, the cells were found, but the changes were not made

I think, it is my issue, but I don't know why. And why the issue only appear on several strings

Thanks

**Comment by danielbachhuber** [comment]
> I use search-replace to translate my wordpress into another language.

`wp search-replace` is used to replace strings stored in the database. How or why are your translation strings in the database?

> However, sometimes it's not working. I use another options, still don't work.

Can you describe in greater detail how it doesn't work, with specific reproduction steps?

**Comment by szepeviktor** [comment]
@yudaprama Adding `--recurse-objects` is the [solution](https://github.com/wp-cli/wp-cli/blob/master/php/commands/search-replace.php#L43-L44).
As of now [Polylang](https://wordpress.org/plugins/polylang/) is the best plugin for you. Please consider learning how to use it.
