### ISSUE TITLE
media regenerate fails for files without metadata

### ISSUE THREAD

**Issue by michalkleiner** [wp-cli/wp-cli#1782]
When there is a file without valid metadata, for whatever reason, remove_old_images should fail safely without throwing PHP warnings.

**Comment by danielbachhuber** [comment]
Which version of WP-CLI are you using? Could this be #1459 ?

**Comment by michalkleiner** [comment]
Thanks for a prompt reaction. It's not the same, I have a file that even doesn't have any metadata, don't know how it's possible but it's there. So I just moved the condition few lines above.

**Comment by michalkleiner** [comment]
I tested with both phar file and clone of master too.

**Comment by danielbachhuber** [comment]
Makes sense. I'll fix with #1783

**Comment by michalkleiner** [comment]
I think the condition should test for array as I suggested otherwise you can receive a PHP notice on trying to access a property of non array. For the file causing my issue `wp_get_attachment_metadata` returns empty string.

Also it's a good practise to test for existence of array keys prior to using them but that part can be omitted with less pain :)

**Comment by danielbachhuber** [comment]
> I think the condition should test for array as I suggested otherwise you can receive a PHP notice on trying to access a property of non array.

Er, not by using `empty()`:

```
salty-wordpress ➜  wordpress-test.dev  wp shell
wp> $var = '';
string(0) ""
wp> $var['apple']
PHP Warning:  Illegal string offset 'apple' in /home/vagrant/.wp-cli/php/WP_CLI/REPL.php(31) : eval()'d code on line 1
Warning: Illegal string offset 'apple' in /home/vagrant/.wp-cli/php/WP_CLI/REPL.php(31) : eval()'d code on line 1
string(0) ""
wp> empty( $var['apple'] );
bool(true)
```

**Comment by michalkleiner** [comment]
Fair point, thanks for clarifying.
