### ISSUE TITLE
Advice for using wp-cli server-wide not per 'user'

### ISSUE THREAD

**Issue by meredevelopment** [wp-cli/wp-cli#1785]
Firstly: I have a rather odd server setup, and accept that this is why I'm having loads of problems getting WP-CLI working, but would please like some help. If there is a better area to ask for support, please let me know. 

I manage my server with a privileged user, not root. I'm using WHM/cPanel and as such each web service 'account' has it's own user account. These accounts do not have SSH access.

What would you suggest is a good place to put WP-CLI and which user should it run as so that I can use things like 'core verify-checksums' and 'core update' when logged in with my privileged user?

I realise this is a very broad question and I've explained little about my setup, I just need to start somewhere. Knowing what setups others use for WP-CLI might help me. 

Thanks!

**Comment by danielbachhuber** [comment]
> What would you suggest is a good place to put WP-CLI

`/usr/bin` is a fine place typically, although I'm not 100% familiar if WHM has an equivalent.

> which user should it run as so that I can use things like 'core verify-checksums' and 'core update' when logged in with my privileged user?

**Comment by danielbachhuber** [comment]
> I realise this is a very broad question and I've explained little about my setup, I just need to start somewhere.

Sorry, I hit enter on the first message prematurely. Let me know how these answers help.

**Comment by szepeviktor** [comment]
You can use [`uwp`](https://github.com/szepeviktor/debian-server-tools/blob/master/tools/uwp) (like `sudo` without "S(uper)") if your user is in the sudo group.

**Comment by szepeviktor** [comment]
AFAIK putting w-cli into `/usr/bin` will pollute that directory, it is only for binaries from packages.
Maybe `/usr/local/bin`.
