### ISSUE TITLE
The "wp post list" command and "--nopaging=true" paramter should be added to documentation

### ISSUE THREAD

**Issue by gerhardsletten** [wp-cli/wp-cli#1790]
In order to get all post with the "wp post list" command you have to use the "--nopaging=true" paramter, maybe it should be motioned in the documentation http://wp-cli.org/commands/post/list/

```bash
wp post list --post_type=attachment --post_parent=3957428 --format=ids --nopaging=true
```

**Comment by danielbachhuber** [comment]
> In order to get all post with the "wp post list" command you have to use the "--nopaging=true" paramter

You shouldn't have to — `posts_per_page` defaults to `-1`: https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L287

Are you sure there aren't any plugins, etc. affecting your results?

**Comment by gerhardsletten** [comment]
No, I am not sure, but I got it from this thread:
http://wordpress.stackexchange.com/questions/70424/posts-per-page-doesnt-work 

The plugins on the installation where I was working was these:

```bash
+-------------------------+----------+--------+---------+
| name                    | status   | update | version |
+-------------------------+----------+--------+---------+
| codepress-admin-columns | active   | none   | 2.4.1   |
| adrotate                | active   | none   | 3.11.3  |
| advanced-custom-fields  | active   | none   | 4.4.1   |
| lightbox-gallery        | active   | none   | 0.8.2   |
| liveblog                | active   | none   | 1.4     |
| p3-profiler             | active   | none   | 1.5.3.9 |
| regenerate-thumbnails   | inactive | none   | 2.2.4   |
| scripts-n-styles        | active   | none   | 3.3     |
| varnish-http-purge      | active   | none   | 3.4     |
| w3-total-cache          | active   | none   | 0.9.4.1 |
| wordpress-importer      | inactive | none   | 0.6.1   |
| wp-all-import-pro       | inactive | none   | 4.1.3   |
+-------------------------+----------+--------+---------+
```

**Comment by danielbachhuber** [comment]
> No, I am not sure, but I got it from this thread:

Ok. There's probably something else going on we can't easily account for.
