### ISSUE TITLE
Maximum execution time of 60 seconds exceeded - is this supposed to happen in a cli script?

### ISSUE THREAD

**Issue by DrLightman** [wp-cli/wp-cli#1792]
Hello, I'm using wp-cli to import an xml consisting of posts and relative attachments.

wp import guides.xml --allow-root --user=1 --authors=create

After partially bypassing a memory exhaustion problem, I though things went smooth but instead I faced this other strange error:

> Processing post #129252 ("How to train your dragon") (post_type: post)
> -- 3,709 of 5,818
> -- Wed, 22 Apr 2015 09:13:11 +0000
> PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/html/--cut--/wp-includes/cache.php on line 672
> Fatal error: Maximum execution time of 60 seconds exceeded in /var/www/html/--cut--/wp-includes/cache.php on line 672

I knew max execution time was infinite for cli scripts, do you have any idea why is this happening while running wp-cli?

The installation where I'm doing this import is a fresh wp installation with no plugins except the "wordpress importer" in a linux dedicated server.

Thank you in advance for any help and suggestion.

edit: forgot to mention, also max_execution_time is 30 in /etc/php.ini, not 60

**Comment by DrLightman** [comment]
After digging disperately, I found this in /wp-includes/functions.php:

> function wp_get_http( $url, $file_path = false, $red = 1 ) {
>	@set_time_limit( 60 );

To fetch attachments I presume that this function is called many times each for every attachment obviously minimum. It does indeed at row 909 of /plugins/wordpress-importer/wordpress-importer.php

> // fetch the remote url and write it to the placeholder file
> $headers = wp_get_http( $url, $upload['file'] );

And I don't want to belive that this function forces max execution time to 60. Neither I want to belive that it doesn't even restore it to the previous value if the function succeedes.

Any idea on how to solve this matter?

**Comment by szepeviktor** [comment]
PHP CLI should have a separate config file.

**Comment by szepeviktor** [comment]
What is your `which php` output?

**Comment by DrLightman** [comment]
/usr/bin/php

**Comment by szepeviktor** [comment]
That is OK, that is PHP-CLI.

**Comment by danielbachhuber** [comment]
> And I don't want to belive that this function forces max execution time to 60. Neither I want to belive that it doesn't even restore it to the previous value if the function succeedes.

Looks like this is the relevant core ticket: https://core.trac.wordpress.org/ticket/21521

I'm surprised no one has hit this before. I'm curious why `set_time_limit()` has an effect in your context.

**Comment by DrLightman** [comment]
Yes, it shouldn't affect cli scripts, first time I face that issue with PHP in general.

**Comment by danielbachhuber** [comment]
This needs to be fixed upstream: https://core.trac.wordpress.org/ticket/34679

**Comment by cooperdk** [comment]
I agree, and this STILL needs to be fixed. After five years.
