### ISSUE TITLE
`wp media regenerate` - Illegal string offset 'file' in phar:///usr/local/bin/wp/php/commands/media.php on line 237 and 238

### ISSUE THREAD

**Issue by DrLightman** [wp-cli/wp-cli#1803]
PHP Warning:  Illegal string offset 'file' in phar:///usr/local/bin/wp/php/commands/media.php on line 237
Warning: Illegal string offset 'file' in phar:///usr/local/bin/wp/php/commands/media.php on line 237
PHP Warning:  Illegal string offset 'file' in phar:///usr/local/bin/wp/php/commands/media.php on line 238
Warning: Illegal string offset 'file' in phar:///usr/local/bin/wp/php/commands/media.php on line 238
Warning: Couldn't regenerate thumbnails for "Icone schermo" (ID 445080)..

**Comment by danielbachhuber** [comment]
This was fixed in #1783
