### ISSUE TITLE
Specifying remote zip location for plugin update/core download/update

### ISSUE THREAD

**Issue by timnashcouk** [wp-cli/wp-cli#1806]
Currently wp plugin install urltozip exists allowing installing a plugin from a non w.org location.

However there is no option for explicitly updating a plugin by manually specifying a remote location, likewise core download and update are hardcoded to w.org. 

Use Cases:
Plugins which are not on w.org that need updating, currently the only way to do this is by: wp plugin install urltozip --force 

For core there is currently no override options so the machine has to be able to talk to w.org to receive an update. For any internal network sites say an intranet they might not have the ability to connect to w.org. Likewise dev machines or simply if working with a large number of sites, or a bespoke repository (for example some weird IIS/SQL server nastiness). 

Implementation
While the simple solution to be able to provide a parameter to wp plugin update, wp core download and wp core update (and themes I guess) which grabs the zip from that URL.

Longer term would be interesting to explore the concept of repository and the ability to specify a server as an alternate location to w.org similar manner to .deb

**Comment by danielbachhuber** [comment]
> However there is no option for explicitly updating a plugin by manually specifying a remote location

Why does it need to be _update_? Isn't force installing a plugin from ZIP essentially the same thing?

> Plugins which are not on w.org that need updating, currently the only way to do this is by: wp plugin install urltozip --force
> Longer term would be interesting to explore the concept of repository and the ability to specify a server as an alternate location to w.org similar manner to .deb

If it's a custom plugin you want to provide an upgrade mechanism for, you can do this by filtering the update check. I'm not really sure what problem this is a solution for.

Related #1762

**Comment by timnashcouk** [comment]
This is mainly an attempt to standardise behaviour across commands, while also allowing a bit more flexibility.

So the use case is identical to that for allowing core download and update to point to non w.org url:

The plugin might not exist on the repository or you might not have access to the repository but do have access to local copy.

Let's take a pretty standard example we have a set of plugins we install and a run a script to update plugins regularly.

to install:
wp plugin install akimet, bbpress, http://myplugin.zip, hello-dolly
to update:
wp plugin update akismet, bbpress, hello-dolly
wp plugin install http://myplugin.zip --force

Fine for just one or two plugins but quickly get's messy at a few hundred, so even if under the hood all it's doing is wp plugin --force it makes sense for:

wp plugin update akimet, bbpress, http://myplugin.zip, hello-dolly

Which at leasts puts the two commands in sync.

Extending that, point to a known location for core at download and update means wp-cli features can still be used in a standardised (i.e won't break scripts way) in closed networks.

**Comment by danielbachhuber** [comment]
> wp plugin update akimet, bbpress, http://myplugin.zip, hello-dolly

How should `wp plugin update` know which plugin to replace for `http://myplugin.zip` ?
