### ISSUE TITLE
Secure password change

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1809]
Could you help me how to chage user password without entering it in the command?

**Comment by szepeviktor** [comment]
[scope:documentation]

**Comment by rmccue** [comment]
The following should be secure, and won't appear in `history` logs:

```bash
$ read -s pass
$ wp user update 42 --user_pass="$pass"
$ unset pass
```

**Comment by szepeviktor** [comment]
Thank you.
`ps auxx` will display that for a moment.

**Comment by rmccue** [comment]
Good point. Likely not possible right now then, since you can't make `user update` read from stdin ala `--prompt` due to the variable args.

**Comment by danielbachhuber** [comment]
> Likely not possible right now then, since you can't make user update read from stdin ala --prompt due to the variable args.

Related #129. I've also created #1810
