### ISSUE TITLE
Incorrectly detecting installations in subdirectories

### ISSUE THREAD

**Issue by compilingEntropy** [wp-cli/wp-cli#1811]
The tool seems to detect installations that are up one level. 
````
[~/public_html/wordpress_test/test]# wp core verify-checksums
Success: WordPress install verifies against checksums.
[~/public_html/wordpress_test/test]# wp core is-installed; echo $?
0
[~/public_html/wordpress_test/test]# ls
./  ../
[~/public_html/wordpress_test/test]#
````
A basic scenario in which this is problematic is when trying to decide whether to do 'update' or 'download'.
````
if (( $(wp core is-installed &> /dev/null; echo $?) == 0 )); then
   wp core update
else
   wp core download
fi
````
I'm using 0.17.0, so I apologize if this has already been resolved, but I was unable to find any closed bug reports concerning this (other than possibly #1729). I am not able to test on a later version at this time.

**Comment by szepeviktor** [comment]
From the docs:
> Determine if the WordPress **tables** are installed.
Please be aware that this is database related.

**Comment by szepeviktor** [comment]
You can detect - for example - `wp-blog-header.php`

```bash
if [ -f "./wp-blog-header.php" ]; then
```

**Comment by szepeviktor** [comment]
Or `[ "$(wp eval "echo defined('ABSPATH');")" == 1 ]`.

**Comment by compilingEntropy** [comment]
Okay, so it sounds like what you're saying is that it's intentionally looking up one level for a wp-config.php file to use. That's fine, just not the behavior I was expecting, but what about verify-checksums? That also seems to be looking up one level, and not just for the database credentials. This is also intended?

**Comment by szepeviktor** [comment]
Yes. You don't have to care about `cd ABSPATH` when using/developing WordPress.

**Comment by szepeviktor** [comment]
wp-cli can even dive into a subdir if it finds the subdir in `index.php`.
```php
require( dirname( __FILE__ ) . '/subdir/wp-blog-header.php' );

```

**Comment by szepeviktor** [comment]
I always use url, user, debug and skip-plugins in the config YAML.

**Comment by danielbachhuber** [comment]
> Okay, so it sounds like what you're saying is that it's intentionally looking up one level for a wp-config.php file to use.

Correct, for the reasons @szepeviktor explains.

**Comment by compilingEntropy** [comment]
Thanks for taking a look guys. =)
