### ISSUE TITLE
core install creates wrong URL in wp_options

### ISSUE THREAD

**Issue by eduardoarandah** [wp-cli/wp-cli#1814]
core install creates a wrong URL (check image)

![image](https://cloud.githubusercontent.com/assets/36432/7438833/0f97b3a4-f020-11e4-9154-e0385a80da7b.png)

In wp_options saves it as: http://hotelsanjosecoatepec.locloc 

My computer: 
windows 8 
wampserver 2.5

    php wp-cli.phar --path="C:\wamp\www\hotelsanjosecoatepec.loc" core download --locale=es_ES
    
    php wp-cli.phar --path="C:\wamp\www\hotelsanjosecoatepec.loc" core config --dbname=hotelsanjosecoatepec --dbuser=root
    
    php wp-cli.phar --path="C:\wamp\www\hotelsanjosecoatepec.loc" db create hotelsanjosecoatepec
    
    php wp-cli.phar  --path="C:\wamp\www\hotelsanjosecoatepec.loc" --title="Hotel San Jose Plaza Coatepec" --admin_user="admin" --admin_password="passwordhere" --admin_email="emailhere@gmail.com" --url="http://hotelsanjosecoatepec.loc" core install

**Comment by danielbachhuber** [comment]
Hm, I don't have any good ideas for this, unfortunately. Can you do a bit more debugging by installing via `git clone; composer install` and adding debug checkpoints?

**Comment by szepeviktor** [comment]
Do you have YAML files?
`wp --info`

**Comment by eduardoarandah** [comment]
(0_o ') never done that but I'll try.
Some ideas on where the problem could be?

I have feelings that it should be some replace regex.

I always develop using .loc domain and then replace it manually to .com for
production as they are same length and dont mess with serialized strings.

I'll do some tests myself

El viernes, 1 de mayo de 2015, Daniel Bachhuber <notifications@github.com>
escribió:

> Hm, I don't have any good ideas for this, unfortunately. Can you do a bit
> more debugging by installing via git clone; composer install and adding
> debug checkpoints?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wp-cli/wp-cli/issues/1814#issuecomment-98261690>.
>


-- 
Enviado desde mi móvil

**Comment by szepeviktor** [comment]
This is a *very* easy way to clone a site:
`wp search-replace --precise --recurse-objects --all-tables-with-prefix <OLD> <NEW>`
These items should be replaced:

1. http://domain.tld (no trailing slash)
1. /var/www/path/to/site (no trailing slash)
1. email@address.es
1. domain.tld (yes, once again without protocol)

**Comment by szepeviktor** [comment]
And a solution that has a UI: https://github.com/interconnectit/Search-Replace-DB
