### ISSUE TITLE
Pass extra `db query` arguments to MySQL

### ISSUE THREAD

**Issue by rmccue** [wp-cli/wp-cli#1817]
I'd like to be able to pass `--skip-column-names` to MySQL to just get the raw data output, but right now that's not possible. It'd be super sweet if I could pass these along, perhaps only after a `--` to indicate the end of WP-CLI args. e.g:
```bash
$ echo 'SELECT domain FROM wp_site' | wp db query -- --skip-column-names
```

**Comment by danielbachhuber** [comment]
`wp core config` has an existing paradigm of `--extra-php=<php>`, which it makes more sense to follow. This argument could be `--extra-mysql-args` or similar.

**Comment by rmccue** [comment]
In general, the Unix-y pattern is `--` to "end" the assoc args and force extras to be treated as positional, so that'd be better for both, but there's likely problems with just doing that straight up (since the query itself is also positional). One thing with `--extra...` as an assoc arg rather than positional is that you need to double up escaping, which can be hairy with complex stuff involving variables.

**Comment by danielbachhuber** [comment]
Related #1222

**Comment by scribu** [comment]
Just wanted to note that there was a `wp db str` subcommand at some point (#946), that was meant to be used when one needed to pass extra parameters to `mysql` (or to `mysqldump`).

**Comment by scribu** [comment]
Actually, an even older subcommand was `wp db connect-str` (#235).

Also note that `wp db export` already allows passing all arguments to `mysqldump`.

**Comment by rmccue** [comment]
Yeah, that'd also be nice for other reasons, so happy to have that as well.

**Comment by roXet** [comment]
+1 on this issue, I'm working on some bash scripts today that I would love to be able to use wp-cli for to pull info out of the db, but I don't want the column names or the grid. I'd love to be able to use `wp db query` for this, rather than resorting to direct use of the mysql client

**Comment by danielbachhuber** [comment]
> In general, the Unix-y pattern is `--` to "end" the assoc args and force extras to be treated as positional, so that'd be better for both, but there's likely problems with just doing that straight up (since the query itself is also positional).

Unfortunately, PHP's implementation of `$argv` is too lossy to replicate this. `--` is ignored by PHP, which means quoted arguments lose their quotes, etc.

Passing extra arguments through directly will do the trick.
