### ISSUE TITLE
wp term list post_tag --term_id=_ID_ not working

### ISSUE THREAD

**Issue by spacetrack** [wp-cli/wp-cli#1818]
Asking for the complete list of tags ...

	$ wp term list post_tag
	+---------+-------------------------+
	| term_id | slug                    |
	+---------+-------------------------+
	(...)
	| 295     | windows                 |
	| 4636    | windows-10              |
	| 296     | windows-7               |
	| 297     | windows-8               |
	| 3955    | windows-8-1             |
	| 300     | windows-nt              |
	| 302     | windows-vista           |
	| 303     | windows-xp              |
	(...)
	+---------+-------------------------+

... works fine as well as filtering for a slug ...

	$ wp term list post_tag --slug=windows
	+---------+---------+
	| term_id | slug    |
	+---------+---------+
	| 295     | windows |
	+---------+---------+

... but filtering for term_id ...

	wp term list post_tag --fields=term_id,slug --term_id=295
	+---------+-------------------------+
	| term_id | slug                    |
	+---------+-------------------------+
	(...)
	| 295     | windows                 |
	| 4636    | windows-10              |
	| 296     | windows-7               |
	| 297     | windows-8               |
	| 3955    | windows-8-1             |
	| 300     | windows-nt              |
	| 302     | windows-vista           |
	| 303     | windows-xp              |
	(...)
	+---------+-------------------------+

... again returns the complete list of post_terms. Did I miss something?

**Comment by danielbachhuber** [comment]
Filtering is based on `get_terms()`, which doesn't support `term_id`.

I'll need to think about whether the fix will be to clarify the documentation, hack some fix into WP-CLI, or wait until https://github.com/wp-cli/wp-cli/issues/1784 lands for proper support.

**Comment by danielbachhuber** [comment]
This was landed.
