### ISSUE TITLE
Unable to retrieve post information by post_name

### ISSUE THREAD

**Issue by jthayne** [wp-cli/wp-cli#1822]
When I run the following command `wp post list --post_name=about-us`, nothing is returned.

When I run `wp post list --post_type=page`, I get two results including a page with the post_name value of about-us

If I combine the two commands, the `--post_name=about-us` flag is ignored.

I need to get the ID of only the about-us page.  From the instructions, there should be, but I haven't found the right combination of flags to even reduce it down to just the about-us page.

I could loop through the results to find the right page, but I was hoping for a one line instruction similar to what have for deactivating a specific widget.

Any assistance?

**Comment by jthayne** [comment]
I have tried several variations from the WP_Query documentation [here](https://codex.wordpress.org/Class_Reference/WP_Query) but the result is the same every time.  The only filter that does anything is `--post-type=page` and then all other filters are ignored.

**Comment by danielbachhuber** [comment]
```
salty-wordpress ➜  wp-api  wp post list --post_type=page --name=post-99
+-----+------------+-----------+---------------------+-------------+
| ID  | post_title | post_name | post_date           | post_status |
+-----+------------+-----------+---------------------+-------------+
| 707 | Page 99    | post-99   | 2015-05-06 17:47:10 | publish     |
+-----+------------+-----------+---------------------+-------------+
```

**Comment by lordspace** [comment]
I just ran into this. 
Why other fields are --post_title, --post_content etc and the slug is just --name?

**Comment by danielbachhuber** [comment]
> Why other fields are --post_title, --post_content etc and the slug is just --name?

This is a WordPress implementation detail, not specific to WP-CLI.

> Can we have an alias for --post_name ?

I'm not keen to introduce an alias. `wp post list` will be deprecated at some point in the future anyway, in favor of [RESTful WP-CLI](https://github.com/danielbachhuber/wp-rest-cli)

**Comment by szepeviktor** [comment]
@danielbachhuber Could we reopen it as `needs-documentation`?
https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L328

**Comment by danielbachhuber** [comment]
It's already documented:

> [--<field>=<value>]
> : One or more args to pass to WP_Query.

We're not going to include an example for every argument that WP_Query supports.

**Comment by szepeviktor** [comment]
> We're not going to include an example for every argument that WP_Query supports.

OK. I would add only one example that show the `--post_name` <--> `--name` difference.
