### ISSUE TITLE
@ECHO: command not found

### ISSUE THREAD

**Issue by ethanclevenger91** [wp-cli/wp-cli#1825]
I'm trying to install wp-cli on a Windows machine. I created the composer project (`composer create-project wp-cli/wp-cli --no-dev`) in my user folder, but when I try to run any commands, such as `wp-cli/bin/wp.bat --info`, I get:
```
wp-cli/bin/wp.bat: line 1: @ECHO: command not found
Could not open input file: %~dp0../php/boot-fs.php
```
This could be PHP issue I suppose, but that seems to work find off the command line. Something like `php -v` gets me:

```
PHP 5.5.12 (cli) ...
```

Any help would be greatly appreciated.

**Comment by danielbachhuber** [comment]
Can you try the Phar installation approach?

**Comment by ethanclevenger91** [comment]
Huh, I had usually had trouble doing it that way on Windows but everything works great. Aliased to `wp` and all is well. Thanks for the (obvious) suggestion - should have tried it first.

**Comment by ethanclevenger91** [comment]
Ah, now that I get going, I remember the issue - that alias is in my `.bashrc` and if I try to run a shell script with the `wp` command in it, it fails because the alias doesn't persist outside of Bash, which is why I've used the alternative install method in the past, giving me a `.bat` file.

**Comment by ethanclevenger91** [comment]
But installing via composer this morning is panning out, so whatever. Sorry about all that.

**Comment by pkosenko** [comment]
I do not understand.  No explanation is being offered here for why the @ECHO line gives the error.  It is happening to me in GIT Bash regardless of trying to run wp-cli.phar.  If the first line of my .bat file has @ECHO OFF, I get the error.  Is there a way to fix THAT?

**Comment by pkosenko** [comment]
But I now see that the workaround is to alias the wp-cli.phar executable in .bashrc if I want to run in GIT Bash rather than DOS (which would require the  .bat file).
