### ISSUE TITLE
tab completions do not work as root

### ISSUE THREAD

**Issue by renatofrota** [wp-cli/wp-cli#1829]
As title says, the tab completion do not work as root (output an error as if we had sent the command without --allow-root, then hang).

I don't know if a permanent solution is doable. Maybe always simulating "--allow-root" is present when querying the completions?

**Comment by danielbachhuber** [comment]
> I don't know if a permanent solution is doable. Maybe always simulating "--allow-root" is present when querying the completions?

You should run WP-CLI as a different user: https://github.com/wp-cli/wp-cli/blob/8c5d6287b8d292a82bb12c4b8db8719e2627aecc/php/WP_CLI/Runner.php#L536

**Comment by szepeviktor** [comment]
I also add --allow-root to the completion file. It is dangerous!
https://github.com/wp-cli/wp-cli/blob/master/utils/wp-completion.bash

Always run wp-cli as a normal user. http://github.com/szepeviktor/debian-server-tools/blob/master/tools/uwp
