### ISSUE TITLE
List posts by metadata

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1831]
I'd like to tag (server-side) optimized attachments with a metadata `optimized`.
How is it possible to query post by metadata?

**Comment by szepeviktor** [comment]
I know I may `WP_query()` by `eval-file`.

**Comment by szepeviktor** [comment]
The answer to the question is
```bash
wp post list --format=ids --post_type=attachment --post_status=inherit --meta_key=optimized '--meta_compare=NOT EXISTS'
```

**Comment by fiftin** [comment]
Is something changes? It isn't works for me in 2021 )

**Comment by szepeviktor** [comment]
@fiftin Here you go.

![kép](https://user-images.githubusercontent.com/952007/110202064-c01fb700-7e66-11eb-88fc-1fac5538f71c.png)

https://developer.wordpress.org/cli/commands/post/list/

**Comment by fiftin** [comment]
Thank you, pair `meta_key` / `meta_value` are working.
