### ISSUE TITLE
Document wp post list array

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1832]
Please append an example in the docblock.
https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L292-L294

**Comment by danielbachhuber** [comment]
Sorry, what specifically do you want documented?

**Comment by szepeviktor** [comment]
When you use `__` in an option which should be an array: `=elem1,elem2,elem3`

**Comment by danielbachhuber** [comment]
It's not a magical argument, per se. It's just an abstraction to handle `post__in` and the like:

```
wp post list --post__in=1,3
```

**Comment by szepeviktor** [comment]
Thank you.
