### ISSUE TITLE
Cannot run phpunit from scaffold plugin

### ISSUE THREAD

**Issue by lassebunk** [wp-cli/wp-cli#1833]
Maybe this is a noob question.

I'm following the instructions in the [Plugin Unit Tests](https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests) wiki.

Afterwards, when running `phpunit` I get the following error:

```
Warning: require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream: No such file or directory in /Users/lassebunk/dev/wordpress/cleaner/tests/bootstrap.php on line 8

Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:') in /Users/lassebunk/dev/wordpress/cleaner/tests/bootstrap.php on line 8
```

If I look in `/tmp/wordpress-tests-lib/` there is no `includes` folder which is what it looks for.

Any ideas?

**Comment by miya0001** [comment]
Please try.
https://github.com/wp-cli/wp-cli/pull/1827/files

**Comment by danielbachhuber** [comment]
This is fixed in v0.19.1

**Comment by jaworskimatt** [comment]
I'm having a similar issue with 0.19.11 (using Vagrantpress)

require_once(/tmp/wordpress//wp-includes/class-phpmailer.php): failed to open stream

@danielbachhuber  @miya0001  @lassebunk 

![screenshot 2015-05-28 13 37 24](https://cloud.githubusercontent.com/assets/2210443/7853281/bccb00c0-053e-11e5-9935-62651195de5b.png)

**Comment by LjupcheVasilev** [comment]
If you're on Windows, open wp-tests-config.php and change the ABSPATH with absolute path to your TEMP folder. For example:
define( 'ABSPATH', 'C:\Users\{User}\AppData\Local\Temp/wordpress/' );

I changed this and phpunit worked! This code is on line 7 in %TEMP%/wordpress-tests-lib/wp-tests-config.php
