### ISSUE TITLE
Shorter command line on deep S&R

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1837]
Now you have to issue
```
wp search-replace --precise --recurse-objects --all-tables-with-prefix --verbose
```
to get a decent s&r.
Is it possible to have *one* option that turns on all these three?
```
wp search-replace --deep
```

**Comment by danielbachhuber** [comment]
> Is it possible to have one option that turns on all these three?

No. You should just create a bash alias if you intend to use it frequently.
