### ISSUE TITLE
Allow `allow-root` to be set in wp-cli.yml

### ISSUE THREAD

**Issue by joshbetz** [wp-cli/wp-cli#1838]
I'm personally not a big fan of the `allow-root` flag. If you have root access, you can do just as much damage with other tools. This is a problem that should probably be solved at the OS level. That said, I would be happy if we could at least set `allow-root` everywhere with wp-cli.yml.

**Comment by danielbachhuber** [comment]
There are some reasons documented in #973 why you shouldn't run WP-CLI as root, and why it's deliberately difficult to do so.

**Comment by joshbetz** [comment]
That's fine. Can I explicitly set `allow-root` in the wp-cli config though?

**Comment by danielbachhuber** [comment]
> Can I explicitly set allow-root in the wp-cli config though?

Did you see https://github.com/wp-cli/wp-cli/pull/973#issuecomment-35841761 ?

**Comment by rahul286** [comment]
@joshbetz you can add an `alias wp="wp --allow-root"` inside your `.bashrc`

In one-line:
```
echo 'alias wp="wp --allow-root"' >>  ~/.bashrc
```

However, this using root is generally not recommended. So avoid this on a production server.

**Comment by ixkaito** [comment]
@rahul286
 
Found a problem of using `alias wp="wp --allow-root"`. We won't be able to use WP-CLI aliases. Adding the following code to the `.bashrc` will solve this problem.

```
wp() {
  /usr/local/bin/wp "$@" --allow-root
}
```

**Comment by rahul286** [comment]
@ixkaito Thanks for the improvement. :-)

**Comment by themenow** [comment]
@ixkaito 

I cannot get this to work, giving error:

```
-bash: .bashrc: line 16: syntax error near unexpected token `('
-bash: .bashrc: line 16: `wp() {'
```

Am I missing something simple?

**Comment by joehoyle** [comment]
When running `wp-cli` under Docker this is quite a pain, as typically you'll just have a very slim container with only a root user.

**Comment by danielbachhuber** [comment]
A rare @joehoyle spotting!

**Comment by joehoyle** [comment]
🏃

**Comment by alexstandiford** [comment]
For those running `docker-compose` I was able to get by the `--allow-root` nag by changing my `entrypoint` to include the `--allow-root` flag

```
  cli:
    build: .
    volumes:
      - ~/.ssh:/root/.ssh/
    volumes_from:
      - wp
    links:
      - 'db:mysql'
    entrypoint: wp --allow-root
```

**Comment by iandunn** [comment]
I think this should be reconsidered.

It's great to make users aware of the dangers of something, but at the end of the day, they know their specific circumstances better than WP-CLI devs, and are in the best position to determines what risks are acceptable to them in that context.

Local environments built with Docker are a perfect example. In that situation, there is no real problem with running WP-CLI as `root`; it's the simplest and most convenient thing. The `allow-root` nag is extremely annoying and unnecessary, and having to setup unsupported workarounds is a pain in the butt.

**Comment by codebard** [comment]
Im using wp cli in installing WP into docker images used in kubernetes after deployment and i would appreciate this feature.

**Comment by deletosh** [comment]
After trying all solutions proposed across thread, [this SO solution](https://stackoverflow.com/a/58929460) was the only one that worked consistent.

**Comment by giggio** [comment]
It looks like you can set `WP_CLI_ALLOW_ROOT` now, but I was not able to get it working. See #5448, already merged.

**Comment by mrmkrs** [comment]
@giggio It does work in the wp cli nightly build (wp cli update --nightly --allow-root)

**Comment by pavrda** [comment]
Simple wrapper can help you. Part of Dockerfile:

```
# wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wpp

RUN echo "#!/bin/sh\n/usr/local/bin/wpp --allow-root \"\$@\"" > /usr/local/bin/wp && \
    chmod +x /usr/local/bin/wp

```

First it downloads wp-cli as wpp and later creates wrapper that enables root. Enjoy!

**Comment by randolf** [comment]
Setting the following environment variable is the solution, and it works well for automation...

> `WP_CLI_ALLOW_ROOT=1`
