### ISSUE TITLE
Check whether coreutils are present?

### ISSUE THREAD

**Issue by ingomueller-net** [wp-cli/wp-cli#1841]
I am working in a weird chroot'ed environment of a shared hoster where `dirname` and `which` are not present. This prevents `wp` from running. Is it necessary to check for the presence of these programs in order to provide better error messages?

**Comment by danielbachhuber** [comment]
> This prevents wp from running.

How?

> Is it necessary to check for the presence of these programs in order to provide better error messages?

I could be convinced, but I suspect it's a slippery slope.

**Comment by ingomueller-net** [comment]
This is what happens when I run wp:

    $ ./vendor/wp-cli/wp-cli/bin/wp
    ./vendor/wp-cli/wp-cli/bin/wp: line 11: dirname: command not found
    ./vendor/wp-cli/wp-cli/bin/wp: line 11: cd: : No such file or directory
    ./vendor/wp-cli/wp-cli/bin/wp: line 26: dirname: command not found
    ./vendor/wp-cli/wp-cli/bin/wp: line 39: which: command not found
    ./vendor/wp-cli/wp-cli/bin/wp: line 46: exec: : not found`

[This answer](http://stackoverflow.com/a/677212/651937) on Stackoverflow describes a way how to check for the existence of commands with only bash built-ins. Maybe doing this kind of check for all non-built-in commands is a solution?

**Comment by szepeviktor** [comment]
Try to install wp-cli as a PHAR archive.
http://wp-cli.org/#install

**Comment by ingomueller-net** [comment]
Using the PHAR archive works, but I loose the ability to install it with composer.

**Comment by danielbachhuber** [comment]
I think Phar is an acceptable alternative method. I don't think it's worthwhile to try to rewrite the bash loader to accommodate this edge case. You could write your own alternative bash loader for your project.

**Comment by szepeviktor** [comment]
:smile: Rewrite those commands in PHP.
`cd` looks like this:
```php
#!/usr/bin/env php
<?php chdir( $argv[1] );
```
then `chmod +x cd`

**Comment by ingomueller-net** [comment]
It *is* an edge case and I will find a solution. Thanks for the two ideas!
