### ISSUE TITLE
WP-CLI doesn't work in PHP 7

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1842]
```bash
# wp --allow-root --info
PHP binary:     /usr/local/bin/php
PHP version:    7.0.0-dev
php.ini used:   /usr/local/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.19.1

# wp --allow-root core download
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

**Comment by digitalchild** [comment]
Clear out your .wp-cli cache/core directory and try again. I had this issue just yesterday.

**Comment by szepeviktor** [comment]
It is a brand new server with PHP 7.

**Comment by szepeviktor** [comment]
I think DocParser does not work in PHP 7. `wp --allow-root help core download`

```
NAME

  wp core download

DESCRIPTION



SYNOPSIS

  wp core download



GLOBAL PARAMETERS

  --path=<path>
      Path to the WordPress files

  --url=<url>
      Pretend request came from given URL. In multisite, this argument is how the target
  site is specified.
```

**Comment by szepeviktor** [comment]
But
```
# php -r 'var_Export(class_exists("Reflection"));'
true
```

**Comment by danielbachhuber** [comment]
Hm, I can't replicate in PHP 5.5.9-1ubuntu4.7

#1844 is running Travis against PHP7 nightly. Let's see what explodes.

**Comment by danielbachhuber** [comment]
Low and behold, [lots of failures](https://travis-ci.org/wp-cli/wp-cli/jobs/63413153) :)

**Comment by szepeviktor** [comment]
state:confirmed

**Comment by danielbachhuber** [comment]
I'm not sure we'll be able to support PHP 7 fully until WP supports PHP 7

**Comment by szepeviktor** [comment]
WP runs on PHP 7, here it is: http2.olm.hu/wp2/ though not fully tested.

**Comment by szepeviktor** [comment]
@danielbachhuber Please remove the URL after reading.

**Comment by danielbachhuber** [comment]
If you look at the test failures though, there are some error notices coming from WP.

**Comment by szepeviktor** [comment]
I think the number of them is close to 1.

**Comment by centminmod** [comment]
FYI, PHP 7.0.0 Alpha1 is released and WP-CPI throws up a bunch of errors on installing some WP Plugins https://community.centminmod.com/posts/14892/

**Comment by szepeviktor** [comment]
@danielbachhuber 

### Results

- `php -r 'var_dump(substr( "--flag", strlen( "--flag" ) ));'` 5.6: bool(false), 7.0: string(0) ""

**Comment by szepeviktor** [comment]
`Scenario: Ability to set a custom version when building` fails on PHP 5.6 too. Is it a bug?
`PHP Fatal error:  require(): Failed opening required './vendor/autoload.php' in utils/make-phar.php on line 3`

**Comment by szepeviktor** [comment]
All other thing are *green* providing E_DEPRECATED is muted in WP core.

**Comment by danielbachhuber** [comment]
> STDOUT/STDERR cause silent failure

Have you come across any relevant bug reports upstream?

> Scenario: Ability to set a custom version when building fails on PHP 5.6 too. Is it a bug?
> PHP Fatal error: require(): Failed opening required './vendor/autoload.php' in utils/make-phar.php on line 3

I suspect this means that Composer failed in some way.

**Comment by szepeviktor** [comment]
Also on PHP 5.6?

**Comment by tw2113** [comment]
Just some hopefully helpful notes. I'm using https://atlas.hashicorp.com/rasmus/boxes/php7dev for my PHP7 source and am not running into much for issues, other than the ones below and similar.

```
Warning: The `wp plugin install` command has an invalid synopsis part: [--force]
Warning: The `wp plugin install` command has an invalid synopsis part: [--activate]
Warning: The `wp plugin install` command has an invalid synopsis part: [--activate-network]
```
However, I am also using the .phar file locally in the folder instead of having it in a place like /usr/local/bin.

Not sure how related it is, but food for thought.

**Comment by centminmod** [comment]
yeah ran into similar as @tw2113 with PHP 7.0.0RC1

    wp cli update --allow-root
    Warning: The `wp cli update` command has an invalid synopsis part: [--patch]
    Warning: The `wp cli update` command has an invalid synopsis part: [--minor]
    Warning: The `wp cli update` command has an invalid synopsis part: [--yes]
    Success: WP-CLI is at the latest version.
