### ISSUE TITLE
Using YAML config file from cron job

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1845]
Is it possible to use the YAML file of a project from a cron job without `cd /project/path`?

**Comment by szepeviktor** [comment]
`--path` does not do that, and there is no `--config`.

**Comment by danielbachhuber** [comment]
Why don't you set `WP_CLI_CONFIG_PATH` environment variable?

**Comment by szepeviktor** [comment]
Because I haven't read the end of the [fourth list item](http://wp-cli.org/config/).
