### ISSUE TITLE
WP_CLI::run_command core install fails

### ISSUE THREAD

**Issue by philcook** [wp-cli/wp-cli#1846]
Hi,

I was making a simple quick WP CLI extension to suit our need for a one click install of wordpress and plugins. I have had an initial stab here:
https://github.com/philcook/squick

However when my code gets to this point
```
WP_CLI::run_command(array('core', 'install'));
```

I am getting this error which I have been unable to debug
```
PHP Fatal error:  Call to undefined function is_blog_installed() in /usr/local/Cellar/wp-cli/0.19.1/php/commands/core.php on line 556

Fatal error: Call to undefined function is_blog_installed() in /usr/local/Cellar/wp-cli/0.19.1/php/commands/core.php on line 556
```

I am unsure if there is a bug here or I am doing something wrong, any advice would be appreciated.

**Comment by danielbachhuber** [comment]
Try spawning another process with `WP_CLI::launch_self()`: https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L392
