### ISSUE TITLE
Use shared cache directory for multiple installs

### ISSUE THREAD

**Issue by andyexeter** [wp-cli/wp-cli#1848]
I'm aware this isn't an "issue" as such, but I wasn't sure where else to post it:

Is it possible to use the same cache directory for multiple installs at paths owned by different users?

for example, site 1 is owned by Alice at /var/www/vhosts/site1 and site 2 is owned by Bob at /var/www/vhosts/site2

I've written a script which will update both core and/or plugins of multiple sites using `find`, getting the owner of the files using `stat` and then using `sudo -U` to run the `wp` command but the only problem is it has to download the update for every site because the CLI caches it in the user's home directory under `.wp-cli/cache`

I know I could just run the script as root, but that would mean root owns any new files it creates

**Comment by danielbachhuber** [comment]
You can specify `WP_CLI_CACHE_DIR` environment variable to use an alternate cache directory: https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L76

**Comment by andyexeter** [comment]
I tried to set the environment variable in a couple places in the command but it doesn't seem to have an effect. First I tried:

`WP_CLI_CACHE_DIR=/var/www/vhosts/site1/.wp-cli/cache sudo -u $USER  /usr/local/bin/wp "$@" --path=/var/www/vhosts/site2`

Then I tried placing the variable after `sudo`:

`sudo -u $USER WP_CLI_CACHE_DIR=/var/www/vhosts/site1/.wp-cli/cache  /usr/local/bin/wp "$@" --path=/var/www/vhosts/site2`

But the CLI still downloaded and cached the plugin I was updating for every install. Am I doing something wrong?

**Comment by danielbachhuber** [comment]
You'd set an environment variable like this:

```
export WP_CLI_CACHE_DIR=/var/www/vhosts/site1/.wp-cli/cache
```

Then you can run:

```
sudo -u $USER /usr/local/bin/wp "$@" --path=/var/www/vhosts/site2
```

**Comment by andyexeter** [comment]
Thanks. To anyone else looking to do the same thing, I had to specify the `-E` flag to sudo to preserve environment variables:

    export WP_CLI_CACHE_DIR=/var/www/vhosts/site1/.wp-cli/cache
    sudo -u $USER -E /usr/local/bin/wp "$@" --path=/var/www/vhosts/site2

**Comment by tmuka** [comment]
The other thing that worked for me in combination with sudo without `-E`, was to define WP_CLI_CACHE_DIR in /root/.bashrc

**Comment by merlinsilk** [comment]
I have this working so far, but run into a permission issue and don't know how to fix that:
Starting with an empty directory I run the update for the first user ('cnr') which creates my cache directory and all folders under that owned by cnr:
drwxr-xr-x 3 cnr  cnr    4096 Feb  9 19:50 cache
this is only writable by user cnr, that means that other wp users later, e.g. alex can not put cached files into that directory. Is there a way to create all those files in the cache as read/write for all?

**Comment by schlessera** [comment]
@merlinsilk This is unrelated to WP-CLI and is caused by the way you set up your filesystem. You will have to set up group write permissions on the folder and add relevant users to that group. WP-CLI will only have the permissions of the user that is running it, so it cannot create files with access outside of that boundary.

**Comment by merlinsilk** [comment]
thank you @schlessera!
I might a bit of hand-holding on accomplishing the group/other write permission when wp-cli creates its cache files. If I set umask to all 0 when I su to a user, then all files created will be writable for all, not only the cache files. Any idea how to do this?
Thanks, Merlin
