### ISSUE TITLE
Don't use `wp_clean_update_cache()` in WP 4.0 context

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1849]
It was introduced in WP 4.1

From #1847

**Comment by szepeviktor** [comment]
Should it go into `utils-wp.php`?

**Comment by danielbachhuber** [comment]
I think maybe just a private method on that class, so we can easily remove later.

**Comment by szepeviktor** [comment]
Is `wp_version_410()` OK?

**Comment by danielbachhuber** [comment]
> Is wp_version_min_410() OK?

Yeah, I think that should be fine.
