### ISSUE TITLE
Request: use options --major and --minor with core update

### ISSUE THREAD

**Issue by vovodroid** [wp-cli/wp-cli#1850]
Hi!

It would be very nice to have those options working also with **core update** command, i.e. to choose whether to update only to latest minor version or to latest major. I think --minor will be good for auto updates.

Thanks.

**Comment by danielbachhuber** [comment]
Seems like a reasonable request — thanks for submitting the issue.

**Comment by vovodroid** [comment]
Actually the same can be applied to plugins and themes (though their versioning may be less strict).

**Comment by szepeviktor** [comment]
Even core does not seem to have semver:
https://github.com/WordPress/WordPress/blob/ca542b5d18778f273d18b590fe9fc2cd97ccb28d/wp-includes/version.php#L7

**Comment by vovodroid** [comment]
My WP copy has version "4.2.2"

**Comment by dfisek** [comment]
This would be a great feature.

A general security practice is "not allowing the application server user to write to the application source code". This also means breaking the auto update functionality of Wordpress itself.

If wp-cli had this feature, we could emulate the automatic update functionality of Wordpress by running `wp core update --minor` periodically from cron.

**Comment by nicomollet** [comment]
Interested in this feature too.
