### ISSUE TITLE
list comment with siteurl and status fails

### ISSUE THREAD

**Issue by chrismccoy** [wp-cli/wp-cli#1851]
wp comment list --format=ids --url=http://domain.com

will list the comments, but once adding a status to the params nothing is listed

    wp comment list --format=ids --status=spam --url=http://domain.com

checking the status shows the correct status of spam for the url in question.

    wp comment status {id} --url=http://domain.com

shows the status that is being passed

**Comment by danielbachhuber** [comment]
Seems to work just fine for me:

```
salty-wordpress ➜  wordpress-test.dev  wp comment list
+------------+-----------------+--------------+------------------+----------------+----------------------+
| comment_ID | comment_post_ID | comment_date | comment_approved | comment_author | comment_author_email |
+------------+-----------------+--------------+------------------+----------------+----------------------+
+------------+-----------------+--------------+------------------+----------------+----------------------+
salty-wordpress ➜  wordpress-test.dev  wp comment list --status=spam
+------------+-----------------+---------------------+------------------+----------------+----------------------+
| comment_ID | comment_post_ID | comment_date        | comment_approved | comment_author | comment_author_email |
+------------+-----------------+---------------------+------------------+----------------+----------------------+
| 1          | 1               | 2015-05-28 04:30:35 | spam             | Mr WordPress   |                      |
+------------+-----------------+---------------------+------------------+----------------+----------------------+
salty-wordpress ➜  wordpress-test.dev  wp comment list --status=spam --format=ids
1%
```

Can you try against a fresh and so clean install of WP? Any plugins that could be changing the behavior?

**Comment by chrismccoy** [comment]
ya that works fine for me too, its when I pass the url param it doesnt. this is for multisite.

**Comment by chrismccoy** [comment]
chris@golf:~/sites/domain.com$ wp comment status 8779
    unapproved
    chris@golf:~/sites/domain.com$ wp comment list --status=unapproved
    +------------+-----------------+--------------+------------------+----------------+----------------------+
    | comment_ID | comment_post_ID | comment_date | comment_approved | comment_author |     comment_author_email |
    +------------+-----------------+--------------+------------------+----------------+----------------------+
    +------------+-----------------+--------------+------------------+----------------+----------------------+

see above (this is a non multisite) its for comments that are pending, ones that are spam will show up.

**Comment by danielbachhuber** [comment]
Hm. I don't have any good suggestions at this point. To confirm, you've disabled all plugins?

**Comment by chrismccoy** [comment]
tried it on another fresh install, when setting status to unapproved nothing shows same as other install, running latest wp cli and latest wordpress

**Comment by chrismccoy** [comment]
solved the problem, the --status=unapproved was incorrect,

--status=hold is what i needed.

**Comment by danielbachhuber** [comment]
:+1:
