### ISSUE TITLE
more in-depth examples needed in the documentation

### ISSUE THREAD

**Issue by goodpixels** [wp-cli/wp-cli#1853]
hi guys,

first things first - this is an amazing project. thanks for maintaining it!

i am having difficulties generating posts - the documentations does not fully explain how it works.

i am not that familiar with PHP, and i don't know whats STDIN - and without a sample code i can't really understand on how to generate a bunch of posts that would have random titles and body content. in addition to this, i cant understand how would i create a post from a `.txt` file. it would be amazing if you could provide such examples in the docs, as many people who work with WordPress are not familiar with PHP.

cheers,
John

**Comment by szepeviktor** [comment]
wp-cli is much like a command line tool. I think user experience does not show that it is actually written in PHP. Please try to google for `shell piping` and `stdin stdout` to get familiar with the shell.

**Comment by szepeviktor** [comment]
Please close this issue.

**Comment by szepeviktor** [comment]
Tip: execute `wp help post generate` to get an example.

**Comment by goodpixels** [comment]
aaah, sorry, i should have been more thorough. thanks!
