### ISSUE TITLE
wp user list --role=administrator returns 0

### ISSUE THREAD

**Issue by goodpixels** [wp-cli/wp-cli#1854]
is this intentional?

**Comment by szepeviktor** [comment]
Do you mean wp-cli's return code is 0 or it does not list administrators?
`uwp user list --role=administrator`
```
+----+------------+--------------+------------------+---------------------+---------------+
| ID | user_login | display_name | user_email       | user_registered     | roles         |
+----+------------+--------------+------------------+---------------------+---------------+
| 1  | viktor     | v            | viktor@szepe.net | 2014-07-21 18:59:33 | administrator |
+----+------------+--------------+------------------+---------------------+---------------+
```

**Comment by goodpixels** [comment]
sorry, I should've been more clear- it doesnt return any users, and it doesn't return 0. results table is always empty.

**Comment by szepeviktor** [comment]
Try `wp user list` and see the `roles` column!

**Comment by szepeviktor** [comment]
You may have a setup failure. Please share the output (STDOUT) of `wp cli info`.

**Comment by goodpixels** [comment]
when  i run `wp user list --role=administrator`, i get nothing:

```
+----+------------+--------------+------------+-----------------+-------+
| ID | user_login | display_name | user_email | user_registered | roles |
+----+------------+--------------+------------+-----------------+-------+
+----+------------+--------------+------------+-----------------+-------+
```

i've double-checked in `wp-admin` and i definitely have two admins:

```
All (5,766) | Administrator (2) | Editor (5) | Subscriber (2) | Partner (5,706) | Pending (50) | User Admin (6)
```

in addition to the original issue, it seems that running `wp user list --format=count` returns **an incorrect** number of users!

`wp user list --format=count`, gives me this:

```
5759
```

here's the output of `wp cli info`:

```
PHP binary:	/Applications/MAMP/bin/php/php5.6.7/bin/php
PHP version:	5.6.7
php.ini used:	/Applications/MAMP/bin/php/php5.6.7/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.19.1
```

please note, that all other commonly used functions seem to work properly. i can add, edit and delete users, activate and deactivate plugins, etc.

**Comment by szepeviktor** [comment]
Maybe the plugin/code that manages non-core roles.
Try https://wordpress.org/plugins/user-role-editor/

**Comment by goodpixels** [comment]
hm. we're using `wpfront-user-role-editor`. yeah, i guess it might be the plugin, as running `get_users( array('role'=>'administrator') )` in the shell mode didn't return any users either.

**Comment by szepeviktor** [comment]
wp-cli provides many ways to migrate to `user-role-editor`.
Please test it before you move on.

**Comment by szepeviktor** [comment]
Please close this issue.
