### ISSUE TITLE
Remove end-of-line comments

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1857]
There are few ( `grep -r "\S\+\s\+//.*" php/* | wc -l` returns 39 ) end-of-line comments.
Like in https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/CommandWithTranslation.php#L61-L64

I suggest to convert them and add a Codesniffer test to refuse further ones.

**Comment by szepeviktor** [comment]
BTW We have `$ wpcs/vendor/bin/phpcs --standard=WordPress-Core php | wc -l`
7272

**Comment by szepeviktor** [comment]
Basically most of them could be corrected in 20 seconds:
https://github.com/szepeviktor/wp-cli/commit/2b14d14b8a900307fac12c94a2cd707db27d1346

**Comment by danielbachhuber** [comment]
> I suggest to convert them and add a Codesniffer test.

Sounds fine.

> PHPCBF CAN FIX 3356 OF THESE SNIFF VIOLATIONS AUTOMATICALLY

I haven't actually found PHPCBF to be terribly accurate.

**Comment by szepeviktor** [comment]
Yes: `continue; }`.

**Comment by danielbachhuber** [comment]
Eh, not worth it to do this globally.

**Comment by szepeviktor** [comment]
Solved!
