### ISSUE TITLE
Allow trunk/nightlies as an option in install-wp-tests.sh

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#1860]
Specifying `latest` as the `[wp-version]` argument in `bin/install-wp-tests.sh` means the latest stable version of WordPress (it directly maps to wordpress.org/latest.tar.gz). For some reason I had assumed that it meant the latest version from trunk.

It would be nice to introduce `trunk` or `nightly` as a possible version here. Unfortunately there's no .tar.gz available for nightlies (see [meta ticket #578](https://meta.trac.wordpress.org/ticket/578)). Can we use a .zip file instead?

**Comment by danielbachhuber** [comment]
> Can we use a .zip file instead?

Could. Although, why do you think it's necessary to package this in the script?

Couple of considerations I can think of:

1. If you really care about running your tests against trunk, you can specify `WP_CORE_DIR`.
1. Because, if you run your tests against trunk, there's the very real chance your tests could explode for some unrelated reason, as mine have done before.

**Comment by johnbillion** [comment]
> If you really care about running your tests against trunk, you can specify WP_CORE_DIR.

This would add unnecessary complexity to a `.travis.yml` file, for example.

I guess my argument is for making it easier to test against trunk/nightlies, without the need to write a command to separately manage an installation of trunk and its configuration, and without the need to add more logic to a CI implementation.

Whether the tests subsequently explode isn't relevant (failures can be ignored).

**Comment by danielbachhuber** [comment]
Ok, I'm on board.

Related #1800 #425

**Comment by danielbachhuber** [comment]
One challenge I ran into looking into this: Nightly is a zip, when most of our downloads right now are tar.gz

**Comment by Ramoonus** [comment]
you could make an if and replace tar xf with unzip
