### ISSUE TITLE
Switch back to a stable release of php-cli-tools

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1866]
Right before release

From #1865

**Comment by szepeviktor** [comment]
Could any of my stuff get into the next release?

**Comment by danielbachhuber** [comment]
> Could any of my stuff get into the next release?

What stuff?

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/wp-cli/issues/1842
https://github.com/wp-cli/wp-cli/issues/1286
https://github.com/wp-cli/wp-cli/pull/1856

**Comment by danielbachhuber** [comment]
Sure — if we merge pull requests that fix them.
