### ISSUE TITLE
import command should support URLs

### ISSUE THREAD

**Issue by shawnhooper** [wp-cli/wp-cli#1867]
You can install plugins and themes from URLs, but it looks like the import command only supports a file path.  Would be useful to be able to specify a WXR from a URL.

**Comment by danielbachhuber** [comment]
> Would be useful to be able to specify a WXR from a URL.

You should just download the WXR with `curl` or `wget`

**Comment by shawnhooper** [comment]
Why not provide the shortcut of being able to specify the URL directly? 

I would think the same logic that applies to the other commands (being able to use URLs) should be here for consistency, no?

The use case I was thinking of was being able, in one command, to install the theme unit testing data.

**Comment by danielbachhuber** [comment]
> Why not provide the shortcut of being able to specify the URL directly?

See [Philosophy](https://github.com/wp-cli/wp-cli/wiki/Philosophy):

> ### Composability is always a good idea.
> [...]
> A corollary of this is that commands should be orthogonal, which means that there should be no overlapping functionality between commands. (wp plugin install --activate is an exception).

> I would think the same logic that applies to the other commands (being able to use URLs) should be here for consistency, no?

We have some exceptions, yes.

**Comment by shawnhooper** [comment]
Fair enough. Thanks for the reply.
