### ISSUE TITLE
Testing community commands

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1868]
It would be helpful to include a `.feature` file from a community command.

**Comment by danielbachhuber** [comment]
Not sure I follow. Can you clarify?

**Comment by szepeviktor** [comment]
```feature
Feature: Testing community commands

  Scenario: I write a community command
    Given there is an error in it
    And I do not notice it

    When I try `vendor/behat/behat/bin/behat`
    Then my command should be required and it's .feature file should also be tested
    And STDERR should be empty
```

**Comment by danielbachhuber** [comment]
Where would this go?

**Comment by szepeviktor** [comment]
No! This just a funny way of writing my answer.
I'd like to `--require` my community command during behat testing and include a `.feature` file in behat testing.

**Comment by danielbachhuber** [comment]
> I'd like to --require my community command during behat testing and include my .feature file in behat testing.

Are you aware of our existing [package functional tests](https://github.com/wp-cli/wp-cli/wiki/Package-Functional-Tests)? This is what `wp scaffold package-tests` does.

**Comment by szepeviktor** [comment]
No. Sorry.
