### ISSUE TITLE
Proper way of using multiple wp-configs

### ISSUE THREAD

**Issue by r34ch** [wp-cli/wp-cli#1869]
I have read the FAQ. What is the proper / standard way to have multiple wp-config.php files (for deploying to multiple environments) and to use them via wp-cli, if any?

I am considering writing a script which generates a wp-config.php depending on the detected environment, which would be run after a site was deployed using git.

I'm just checking beforehand that there isn't some obscure command I've missed or some standard of doing this has appeared that I am not aware of.

**Comment by r34ch** [comment]
Found this;

http://torquemag.io/using-wp-cli-to-set-up-a-test-version-of-your-site/

I will use a script and wp-cli commands to perform what I need.

**Comment by szepeviktor** [comment]
Consider not putting `wp-config.php` under VCS control.
