### ISSUE TITLE
core multisite-install: Unneeded parameters admin_user, admin_password, admin_email?

### ISSUE THREAD

**Issue by plutus78** [wp-cli/wp-cli#1870]
Hi,

why are the parameters admin_user, admin_password, admin_email needed?

I've installed multisite with the following command line:

wp-cli core multisite-install --title="bla bla" --admin_user="ga ga" --admin_password="fla fla" --admin_email="gna gna"

That worked!

BUT when I make a mysqldump I don't see anywhere "ga ga", "fla fla" or "gna gna". Are these parameters completely ignored?

Thanks,
Marcel

**Comment by danielbachhuber** [comment]
> why are the parameters admin_user, admin_password, admin_email needed?

To create the default admin user.

> I've installed multisite with the following command line:

Can you share the full output?

**Comment by plutus78** [comment]
sorry, my fault!

I've used on an installed wp. Therefore it automatically _converts_ my wp to multisite. Instead I should use multisite-convert.

Thanks!
