### ISSUE TITLE
wp core download fails

### ISSUE THREAD

**Issue by jklepatch** [wp-cli/wp-cli#1872]
I am running wp-cli on ubuntu 14.04, on a standard LAMP installation (not XAMPP, MAMP, and the likes)

WP CLI version and config:
```
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.9
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.19.1
```

PHP Version:
```
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

After running `wp core download` in `/var/www/clients/projectname`, I got lots of errors, ending by:
```
PHP Warning:  copy(/var/www/clients/projectname//wp-content/themes/twentyfifteen/content-link.php): failed to open stream: No such file or directory in phar:///usr/local/bin/wp/php/commands/core.php on line 221
PHP Warning:  copy(/var/www/clients/projectname//readme.html): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/commands/core.php on line 221
```

For the first error what I pasted is actually repeated for each file of WordPress, and for the second errors it appears just once at the end.

Did I miss a configuration or something ?

**Comment by szepeviktor** [comment]
Does your user have permission to write to `/var/www/clients/projectname`?

**Comment by jklepatch** [comment]
I am new to linux, so not very knowledgable yet.
All I know is that I need to do sudo + command to execute a command in this directory. I guess it means my user does not have enough permission for this directory ?

I tried the same wp cli command in my ~/ directory, and it worked perfectly

**Comment by szepeviktor** [comment]
If your WP directory's permissions are OK (check with `ls -ld /path/to/WPROOT`) then install my script:
https://github.com/szepeviktor/debian-server-tools/blob/master/tools/uwp
by `cp uwp /usr/local/sbin/uwp`. It will launch wp-cli ad the current directory's owner.

**Comment by szepeviktor** [comment]
If you have the correct user and group: do `chown -c -R USER:GROUP /path/to/WPROOT` to reset the owner.

**Comment by danielbachhuber** [comment]
Thanks for your help on this, @szepeviktor

**Comment by psyche699** [comment]
Hello,

I have the same problem , but I can not seem to solve it.
Please Help me !
