### ISSUE TITLE
Some special characters prevent a story from being injected

### ISSUE THREAD

**Issue by theMikeD** [wp-cli/wp-cli#1873]
if ’ or “ or ” exist in a a file that is being added via wp post create, the post creation will fail.

**Comment by danielbachhuber** [comment]
Can you share the exact command you're using?

**Comment by theMikeD** [comment]
Sure
```
wp post create /tmp/_tmp_post_content_ --post_title="Knowing the Secret without knowing."
```

The problem is not with the command. The problem is that wp-cli barfs on the post body that contains special characters.

**Comment by theMikeD** [comment]
I can provide an example file if you tell me where to upload it

**Comment by theMikeD** [comment]
Maybe this is an issue with 0.19.1. How do I get a previous build, specifically 0.19.0?

**Comment by danielbachhuber** [comment]
> I can provide an example file if you tell me where to upload it

Gist or Pastebin is fine.



> How do I get a previous build, specifically 0.19.0?

https://github.com/wp-cli/wp-cli/releases

**Comment by theMikeD** [comment]
Both of those services may convert the encoding. Is there a way to get a zip file to you?

**Comment by theMikeD** [comment]
Sample zip file is in slack

**Comment by theMikeD** [comment]
This has been discovered by taking the contents of one DB field and using it as the contents of a new story being injected into WP. The collation of the source field is latin1_swedish_ci and wp_posts is utf8_general_ci. Is this the likely issue?

**Comment by theMikeD** [comment]
Is there perhaps a way to get wp-cli to be a bit more specific with the error message? All I get is "Could not insert post into the database"

**Comment by theMikeD** [comment]
When I manually change the encoding from "Western (ISO Latin 1)" to "Unicode(UTF-8)" using BBEdit, the insertion works fine.

**Comment by theMikeD** [comment]
I can confirm that this is an encoding conflict.

**Comment by danielbachhuber** [comment]
> I can confirm that this is an encoding conflict.

The error is one that comes back from `wp_insert_post()`, so I don't think there's much WP-CLI can do.
