### ISSUE TITLE
`wp core config` not using `--dbuser` mysql login name, defaulting to account name

### ISSUE THREAD

**Issue by andybp85** [wp-cli/wp-cli#1874]
When I run this command I'm getting this behavior:

    ACCOUNTUSER@HOST$ wp core config --dbname='DBNAME' --dbuser='DBUSER' --dbpass='DBPASS'
    ERROR 1045 (28000): Access denied for user 'ACCOUNTUSER'@'localhost' (using password: YES)

For the record this works:

    $ mysql --user=DBUSER --pass=DBPASS
    Warning: Using unique option prefix pass instead of password is deprecated and will be removed in a future release. Please use the full name instead.
    Warning: Using a password on the command line interface can be insecure.
    Welcome to the MySQL monitor.  Commands end with ; or \g.
    [truncated]
    mysql>

Wish I had more time and experience to play with the code but as best I can tell the issue is occurring somewhere in `run_mysql_command` or `assoc_args_to_str`.  I'd want to see the vars at runtime on line 360 in php/utils.php: `$final_cmd = $cmd . assoc_args_to_str( $assoc_args );`

Here's the relevant funcs:

    // php/commands/core.php:344
    
    if ( ! \WP_CLI\Utils\get_flag_value( $assoc_args, 'skip-check' ) ) {
      Utils\run_mysql_command( 'mysql --no-defaults', array(
        'execute' => ';',
        'host' => $assoc_args['dbhost'],
        'user' => $assoc_args['dbuser'],
        'pass' => $assoc_args['dbpass'],
      ) );
    }
    
    // php/utils.php: 181
    
    function assoc_args_to_str( $assoc_args ) {
    	$str = '';
    	foreach ( $assoc_args as $key => $value ) {
    		if ( true === $value )
    			$str .= " --$key";
    		else
    			$str .= " --$key=" . escapeshellarg( $value );
    	}
    	return $str;
    }
    
    
    // php/utils.php:346
    
    function run_mysql_command( $cmd, $assoc_args, $descriptors = null ) {
    	if ( !$descriptors )
    		$descriptors = array( STDIN, STDOUT, STDERR );
    	if ( isset( $assoc_args['host'] ) ) {
    		$assoc_args = array_merge( $assoc_args, mysql_host_to_cli_args( $assoc_args['host'] ) );
    	}
    	$pass = $assoc_args['pass'];
    	unset( $assoc_args['pass'] );
    	$old_pass = getenv( 'MYSQL_PWD' );
    	putenv( 'MYSQL_PWD=' . $pass );
    	$final_cmd = $cmd . assoc_args_to_str( $assoc_args );
    	$proc = proc_open( $final_cmd, $descriptors, $pipes );
    	if ( !$proc )
    		exit(1);
    	$r = proc_close( $proc );
    	putenv( 'MYSQL_PWD=' . $old_pass );
    	if ( $r ) exit( $r );
    }

Here's my `wp --info`
    PHP binary:	/usr/local/bin/php
    PHP version:	5.5.24
    php.ini used:
    WP-CLI root dir:	phar://wp-cli.phar
    WP-CLI global config:
    WP-CLI project config:
    WP-CLI version:	0.19.1

**Comment by danielbachhuber** [comment]
When I `error_log( var_export( $final_cmd, true ) )`, here's what I get:

```
salty-wordpress ➜  wordpress-test.dev  wp core config --dbname="localhost" --dbuser="root"
'mysql --no-defaults --execute=\';\' --host=\'localhost\' --user=\'root\''
Success: Generated wp-config.php file.
```

And:

```
salty-wordpress ➜  wordpress-test.dev  wp core config --dbname="localhost" --dbuser="test"
'mysql --no-defaults --execute=\';\' --host=\'localhost\' --user=\'test\''
ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: NO)
```

Can you try against a different machine? Maybe there's some MySQL config trickery applying?
