### ISSUE TITLE
filesystem error messages should be more detailed

### ISSUE THREAD

**Issue by lkraav** [wp-cli/wp-cli#1880]
```
$ [-] wp plugin install ukuupeople-the-simple-crm
Installing UkuuPeople - The Simple CRM (1.0.2)
Downloading install package from downloads.wordpress.org/…...
Using cached file '/home/leho/.wp-cli/cache/plugin/ukuupeople-the-simple-crm-1.0.2.zip'...
Unpacking the package...
Warning: Could not create directory.
```

...WHICH directory? What's my next step?

Solution: output the failed directory name

Related #1587

**Comment by lkraav** [comment]
Mad `strace` skills revealed the culprit: `wp-content/upgrade`

**Comment by stephenharris** [comment]
As I understand it wp-cli simply uses a plain-text skin for WordPress' `WP_Upgrader` - so I think the problem is upstream: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-upgrader.php#L133

**Comment by danielbachhuber** [comment]
> so I think the problem is upstream

Yes, this is correct. "Could not create directory" is the error reported to us.

> Mad strace skills revealed the culprit: wp-content/upgrade.

Can you clarify what specifically the problem was?

**Comment by szepeviktor** [comment]
Try `mkdir -v -p wp-content/upgrade` and see mkdir's message.

**Comment by lkraav** [comment]
@danielbachhuber it is of course "not enough permissions" and that's fine. this is a ux perspective issue, just needed to quickly know which directory owner/group to adjust... without going hardcore on it with `strace` type stuff.
