### ISSUE TITLE
Possible issue: Activating our updated plugin causes WP-CLI to fail silently on most commands

### ISSUE THREAD

**Issue by jschank** [wp-cli/wp-cli#1881]
When I run most wp-cli commands I get silent failure. If I echo the return code, I can see that it is 255.

Some background. Our team is working on a plugin. Previous version of plugin works fine with wp-cli. If I update the plugin ($ wp plugin update our-plugin) the plugin updates, and the site seems to work fine, BUT, any further commands with wp-cli silently fail with return code 255.

I am talking about simple commands like ($ wp plugin list) or ($ wp plugin status) The 255 error codes even extend to theme subcommands as well.

The question is: How do I debug this? Is there a way to get more details failure information from wp-cli?

**Comment by danielbachhuber** [comment]
> If I echo the return code, I can see that it is 255.

This is most likely a PHP fatal with error notices suppressed: http://serverfault.com/questions/153634/php-exit-status-255-what-does-it-mean

Your plugin is likely fataling in WP-CLI context (or even generally). Does this give you enough information to debug further?

**Comment by szepeviktor** [comment]
Try `wp --debug ...`.

**Comment by jschank** [comment]
It gives me some clues, which is what I was looking for at this point.
Thank you.

John

**Comment by jschank** [comment]
Confirmed that this is not a problem with WP-CLI.

My situation is that xdebug was overriding php.ini settings, and hiding error messages. When I realized that and was able to see stack traces, the problem was entirely that our plugin was relying on getallheaders() which is implemented in the apache context, but not in the CLI context.

See this link for details.
http://stackoverflow.com/questions/30769256/wordpress-wp-cli-generates-error-call-to-undefined-function-getallheaders)

Sorry for the false alarm.

**Comment by szepeviktor** [comment]
Try adding a condition: `if ( defined( 'WP_CLI_ROOT' ) )`.

**Comment by szepeviktor** [comment]
There is another false *alarm* in th SE question:

> In this case wp-cli uses the PHP-FPM (FastCGI Process Manager) as the SAPI.

All cli applications run on the CLI SAPI.

**Comment by jschank** [comment]
Yep that is what I did.
I just wanted to comment on the issue that this really was not a problem with WP-CLI,
and I furnished a link to one possible solution, in case others have this problem.

But, thank you for the reply. I do appreciate it.
You guys were very responsive.

John
