### ISSUE TITLE
wp plugin list gives incorrect output on multisites

### ISSUE THREAD

**Issue by harry-m** [wp-cli/wp-cli#1882]
I just used wp plugin list to generate plugin status data for a bunch of sites that we host. (I'm trying to encourage clients to remove inactive plugins).

However, this doesn't work as I would expect on multisite installations. On a couple of sites, plugins were listed as inactive even though they were in use on individual blogs. 

Is it possible that wp-cli is only checking the network site and looking for network-level activations? And reporting a plugin as inactive if not found in one of those places?

**Comment by szepeviktor** [comment]
Does this problem exist in the output of `wp plugin status`?

**Comment by harry-m** [comment]
Yes - I have worked around this by supplying --url to specify a given blog and then merging all of the results into one json object, where any active status overrides an inactive one. But it's pretty hacky.

I can see the logic in having a command to retrieve a list of plugins for a specific site, which is what it's doing now. But from a site management perspective, I only really care if a plugin is in use on any site - the specific site it's on is less relevant.

**Comment by szepeviktor** [comment]
Ah! So in a network environment `inactive` means it is not activated network-wide.
Ad you would like to have a command like `wp plugin list --anywhere`.

**Comment by szepeviktor** [comment]
@danielbachhuber What would be the logic of such a command?

**Comment by harry-m** [comment]
Exactly that.

I couldn't see a way to do it other than looping through all sites, as the list is in each site's wp_options table.

I think "Inactive" does just mean it's not active on the site you're querying - I don't think there's any special logic there. The confusing thing is that when you run this on a multisite install it defaults to the network site without telling you.

**Comment by szepeviktor** [comment]
[documentation]

**Comment by danielbachhuber** [comment]
> What would be the logic of such a command?
> Loop through all sites??

Easier to just do:

```
wp site list --field=url | xargs -n 1 -I % wp plugin list --url=%
```

See "Composability": https://github.com/wp-cli/wp-cli/wiki/Philosophy#composability-is-always-a-good-idea

> The confusing thing is that when you run this on a multisite install it defaults to the network site without telling you.

This is expected behavior.
