### ISSUE TITLE
can't find cacert.pem when part of a larger project

### ISSUE THREAD

**Issue by kcivey** [wp-cli/wp-cli#1883]
If wp-cli is part of a larger project (so the `vendor` folder is three levels up), it's looking for cacert.pem in the wrong place (a nonexistent `vendor` folder inside the `wp-cli` folder), so we get

    Warning: cURL error 77: error setting certificate verify locations:
    CAfile: [project folder]/vendor/wp-cli/wp-cli/vendor/rmccue/requests/library/Requests/Transport/cacert.pem
    CApath: /etc/ssl/certs

Probably the `$options['verify']` in `http_request()` in `php/utils.php` should be using `get_vendor_paths()` or something similar.

**Comment by rmccue** [comment]
Looks like wp-cli is assuming it's the top-level, and needs to check if it's running out of the vendor dir?

**Comment by danielbachhuber** [comment]
> Looks like wp-cli is assuming it's the top-level, and needs to check if it's running out of the vendor dir?

This is correct — it's a bug. We'll get it fixed. Thanks for the report, @kcivey

**Comment by danielbachhuber** [comment]
@kcivey Can you verify #1891 please?
