### ISSUE TITLE
wp rewrite flush --hard not generating .htaccess file

### ISSUE THREAD

**Issue by StephanMeijer** [wp-cli/wp-cli#1884]
I was trying the command:
```wp rewrite flush --hard```
to generate the .htaccess. 

It keeps coming with the message `Warning: Regenerating a .htaccess file requires special configuration. See usage docs.`.

Content of `/srv/http/test/wp-cli.yaml`:
```
url: http://localhost/test
user: test
color: false
disabled_commands:
  - db drop

core config:
        dbuser: root
        dbpass: dbpass
        extra-php: |
                define( 'WP_DEBUG', true );
                define( 'WP_POST_REVISIONS', 50 );
apache_modules: 
        - mod_rewrite
```

Content of `~/.wp-cli/config.yaml`:
```
apache_modules:
        - mod_rewrite
```

**Comment by szepeviktor** [comment]
I think `get_config()` does not return an array.
Until then try
```yaml
apache_modules: mod_rewrite
```

**Comment by szepeviktor** [comment]
Once I've got
```php
array(1) {
  [0]=>
  string(13) "- mod_rewrite"
}
```
for the argument.

**Comment by szepeviktor** [comment]
That was
```yaml
apache_modules:- mod_rewrite
```
Could you install wp-cli from source and insert `var_dump( WP_CLI::get_config( 'apache_modules' ) );` in `public function flush()` and share the output?

**Comment by StephanMeijer** [comment]
I will do that :).

**Comment by szepeviktor** [comment]
And `wp --info` also please.

**Comment by danielbachhuber** [comment]
Er, formatting is supposed to be:

```
apache_modules:
  - mod_rewrite
```

The docs are off, which I've fixed in https://github.com/wp-cli/wp-cli.github.com/commit/2b46ed5c8266bf8914335ffab3ea0469af92ffb3
