### ISSUE TITLE
After an interrupted "wp export" as root, Wordpress installation crashed

### ISSUE THREAD

**Issue by vyctoroliveira** [wp-cli/wp-cli#1887]
Hi. Recently, I tried to use the wp export to get an xml for testing, but my server has crashed and the Wordpress isn't working anymore. I don't know what I should do next.

**Comment by danielbachhuber** [comment]
> but my server has crashed and the Wordpress isn't working anymore

To get your server running again, you'll likely need to reboot or as your hosting support for assistance.

Generally, running WP-CLI causes your server to crash, you should either:

1. Switch servers, to one that can support WP-CLI without crashing.
2. Avoid using WP-CLI, which causes your server to crash.
