### ISSUE TITLE
Core download is failing when using locale fr_FR

### ISSUE THREAD

**Issue by aeyoll** [wp-cli/wp-cli#1892]
Hello,
The core download command doesn't seem to work when using --locale=fr_FR. It works just fine without the locale option, or with an other one (es_ES, or it_IT for example)

You can see the error below:

```
$ ~/code/wp-cli/bin/wp core download --locale=fr_FR
Downloading WordPress 4.2.2 (fr_FR)...
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'phar error: "/tmp/jeanphilippe/wp_5587b0c006fb5.tar.gz" is a corrupted tar file (truncated)' in /home/jeanphilippe/code/wp-cli/php/commands/core.php:195
Stack trace:
#0 /home/jeanphilippe/code/wp-cli/php/commands/core.php(195): PharData->__construct('/tmp/jeanphilip...')
#1 /home/jeanphilippe/code/wp-cli/php/commands/core.php(181): Core_Command::_extract('/tmp/jeanphilip...', '/tmp/')
#2 [internal function]: Core_Command->download(Array, Array)
#3 /home/jeanphilippe/code/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 /home/jeanphilippe/code/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(295): call_user_func(Object(Closure), Array, Array)
#6 /home/jeanphilippe/code/wp-cli/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 /home/jeanphilippe/code/wp-cli/php/WP_CLI/Runner.php( in /home/jeanphilippe/code/wp-cli/php/commands/core.php on line 195
```

Thanks!

**Comment by aeyoll** [comment]
Ok, it seems that the tar.gz file is corrupted in http://fr.wordpress.org/, but not the zip file, so it's not a wp-cli issue, sorry for that! However, maybe it's possible to add an error message when the md5sum of the tar.gz file is not valid?

**Comment by danielbachhuber** [comment]
> However, maybe it's possible to add an error message when the md5sum of the tar.gz file is not valid?

How would we get the valid md5? And, what if the md5 represents the corrupted file?

**Comment by aeyoll** [comment]
You can get the md5 by appending .md5 to any wordpress.org tar.gz link (eg. https://wordpress.org/wordpress-4.2.2.tar.gz.md5 or http://fr.wordpress.org/wordpress-4.2.2-fr_FR.tar.gz.md5).

> And, what if the md5 represents the corrupted file?

Well, that's the problem, sadly it happens to be the case for the 4.2.2.fr_FR release, making the sum unusable… Anyway, md5sum could be a good idea in a larger scale, to check if the file has been correctly transfered.

Also, maybe the UnexpectedValueException could be catched to display an error message.

**Comment by szepeviktor** [comment]
> You can get the md5 by appending .md5 to any wordpress.org tar.gz link

What a secret!

**Comment by szepeviktor** [comment]
MD5 checking is useful feature request.

**Comment by danielbachhuber** [comment]
> MD5 checking is useful feature request.

#1899
