### ISSUE TITLE
Associative arguments with null values are interpreted as positional arguments

### ISSUE THREAD

**Issue by JRGould** [wp-cli/wp-cli#1894]
Running a command like:
```bash
$ wp db export db.sql --path=''
``` 
results in the error: `Error: Too many positional arguments: --path=`

Likewise, running 
```bash
$ wp db export --path=
```
Will successfully export your database to `./--path=` 

Expected outcome would be for `--path=''` and `--path=` to be interpreted as associative arguments with null values and let (sub)commands determine if this should throw an error.

**Comment by szepeviktor** [comment]
Please try `wp --path='' db export db.sql`

**Comment by szepeviktor** [comment]
BTW `''` is an invalid path. The current directory is `--path=.`.

**Comment by szepeviktor** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/1745

**Comment by JRGould** [comment]
```bash
$ wp --path='' db export db.sql
Error: '--path=' is not a registered wp command. See 'wp help'.

$ wp --path='.' db export db.sql
Success: Exported to db.sql
```
Just using `wp db` as an example, this is an issue with how arguments are parsed.

If this is confirmed as a bug I'm happy to submit a PR with a fix.

**Comment by danielbachhuber** [comment]
> If this is confirmed as a bug I'm happy to submit a PR with a fix.

It's a bug... but, per #1745, I don't think there's an easy fix. I'd be happy to look at a PR though.

```
salty-wordpress ➜  fusion-2015  wp post get 100426 --field=post_content
[fusion-pullquote source="\"Test"]
salty-wordpress ➜  fusion-2015  wp post update 100426 --post_content=""
Error: Unable to read content from --post_content=.
```
