### ISSUE TITLE
wp: command not found

### ISSUE THREAD

**Issue by warb2n** [wp-cli/wp-cli#1895]
I try install  it 30 times =@ idk what i do wrong.
wp: command not found

php wp-cli.phar --info
>PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.9
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.19.2

I use Ubuntu 14.04.2 LTS
nginx+php-fm 5.5.9

**Comment by danielbachhuber** [comment]
> wp: command not found

Did you run `sudo mv wp-cli.phar /usr/local/bin/wp` too?

If so, can you confirm `/usr/local/bin/wp` is in your `PATH` ?

```
echo $PATH
```

**Comment by warb2n** [comment]
sry for my noobish i am new in this theme…

###### What i do
* curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
* chmod +x wp-cli.phar
* then i do mkdir /usr/local/bin/wp , cuz i don't have wp folder
* sudo mv wp-cli.phar /usr/local/bin/wp
* wp --info and i get wp: command not found

**Comment by szepeviktor** [comment]
`wp` is a *file*. Try `mkdir /usr/local/bin` if you do NOT have that directory.

**Comment by szepeviktor** [comment]
Please close this issue.

**Comment by danielbachhuber** [comment]
@warb2n Almost there! Can you verify `/usr/local/bin` is actually a directory?

> Please close this issue.

Please be nice. I don't need to be reminded to close issues.

**Comment by szepeviktor** [comment]
Excuse me.
It was for @warb2n.

**Comment by warb2n** [comment]
@szepeviktor Why close?
still not working =@

@danielbachhuber   Yes is a directory.
![s](https://cloud.githubusercontent.com/assets/6230166/8329346/5f5ce806-1a81-11e5-8f8c-d83ccd73df62.png)

echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by danielbachhuber** [comment]
@warb2n From `/usr/local`, can you run `mv bin/wp-cli.phar bin/wp` and try again?

Because you want to call WP-CLI as `wp`, not `wp-cli.phar`, it needs to exist as `wp` in a directory on your `PATH`.

**Comment by warb2n** [comment]
@danielbachhuber Thx for U help man, all work now.

**Comment by danielbachhuber** [comment]
> Thx for U help man, all work now.

Glad you got it sorted out :)
