### ISSUE TITLE
wp core update broke install due to application incremental update (possibly because of cached file)

### ISSUE THREAD

**Issue by novazembla** [wp-cli/wp-cli#1898]
Hello, 

Yesterday I've used `wp core update` to update a site from 4.1.1 to 4.2.2. The update went through and after a `wp core update-db` the system also stated that it is now running 4.2.2. However the site and admin tool was partially broken as the update pulled just incremental changes between 4.2.1 and 4.2.2 and did not pull the changes from 4.2 and all the other versions between 4.1.1 and 4.2.2. 

After I manually copied all core files from a blank new install the site worked bug free. 

I'm not sure if this is the intended mechanism? How would I ensure to apply all incremental changes between two versions? How could I force to download the full install? 

I remember to have seen a notification that wp-cli was using a cached file in `~/.wp-cli/cache/core`
Unfortunately I can't remember which file has been used. As you can see the following files are in this folder. All would have been pulled by wp-cli (probably sometimes used in a `sudo` command).

```
-rw-r--r--  1 novazembla  staff  6183711 28 Jan 13:51 en_US-4.1.tar.gz
-rw-r--r--  1 novazembla  staff  6321767  5 May 22:18 en_US-4.2.1.tar.gz
-rw-r--r--  1 root        staff  6307937  8 Jun 17:40 en_US-4.2.2.tar.gz
-rw-r--r--  1 novazembla  staff   519434 15 Jun 13:29 en_US-4.2.2.zip
```
Looking at the file sizes I assume that it has been using the .zip file. 

Is there a way to ensure that `wp core update` always updates all changes between two versions. 

Thanks!

**Comment by szepeviktor** [comment]
Yes. It is `wp core verify-checksums`.

**Comment by szepeviktor** [comment]
> ... the update pulled just incremental changes between 4.2.1 and 4.2.2 and did not pull the changes from 4.2 and all the other versions between 4.1.1 and 4.2.2.

AFAIK wp-cli uses WP core's upgrader: https://github.com/wp-cli/wp-cli/blob/master/php/utils-wp.php#L65-L70

**Comment by novazembla** [comment]
Thanks! But as I ended up from a working 4.1.1. version to a half-complete 4.2.2 something must tripped the upgrade progress. Could it be that the cached version applied was for whichever reason the wrong one. I wonder why there is a .zip and a .tar.gz file in my cache? Both of which have been downloaded by `wp-cli` Comparing the file sizes I would wager that my `wp core udpate` used the .zip.

**Comment by szepeviktor** [comment]
You can run `wp core update; echo $?` to see the exit status.

**Comment by szepeviktor** [comment]
It could be a partial download.
```bash
wget -q -O- https://wordpress.org/wordpress-4.2.2.zip | wc -c
6860180
```

**Comment by danielbachhuber** [comment]
> Yesterday I've used wp core update to update a site from 4.1.1 to 4.2.2.

Can you provide the exact command you ran? It should be available in your bash history.

**Comment by szepeviktor** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/1892

**Comment by novazembla** [comment]
Hi, 

I've cloned the folder and reverted my commits to the repository. So I started with the same codebase version 4.1.1 then I did the same as yesterday however used `wp core verify-checksums`

Here is the log:

```
Novazembla:xxx novazembla$ wp core version
4.1.1
Novazembla:xxx novazembla$ wp core verify-checksums
Success: WordPress install verifies against checksums.
Novazembla:xxx novazembla$ wp core update 
Updating to version 4.2.2 (en_US)...
Using cached file '/Users/novazembla/.wp-cli/cache/core/en_US-4.2.2.zip'...
Unpacking the update...
Success: WordPress updated successfully.
Novazembla:xxx novazembla$ wp core verify-checksums
Warning: File doesn't verify against checksum: wp-settings.php
Warning: File doesn't verify against checksum: wp-cron.php
Warning: File doesn't verify against checksum: wp-comments-post.php
Warning: File doesn't verify against checksum: wp-admin/link-parse-opml.php
Warning: File doesn't verify against checksum: wp-admin/js/editor.js
Warning: File doesn't verify against checksum: wp-admin/js/user-profile.min.js
Warning: File doesn't exist: wp-admin/js/tags-box.js
...
```
As you can see it used the .zip file. Leading to an incomplete upgrade. 

Many thanks guys!

**Comment by szepeviktor** [comment]
The zip in your cache is *broken*. Please purge your file cache and repeat the above.
I hope it will turn out to be OK.

**Comment by danielbachhuber** [comment]
> The zip in your cache is broken.

WP-CLI might be saving partials to the cache directory. I'm testing now.

**Comment by danielbachhuber** [comment]
Bug verified in #1901. Thanks for all of the details, @novazembla.

I'll need to give some thought as to how we should fix this. It's nice to have the downloads cached, but we have partials masquerading as full archives.

**Comment by szepeviktor** [comment]
Oh! So partials and fulls have the same file name?

**Comment by danielbachhuber** [comment]
Options I can think of off the top of my head:

1. Include the from version in the cached partial filename.
1. Don't cache partial upgrades.
1. Verify md5 from WordPress.org before performing the operation.

**Comment by szepeviktor** [comment]
2. Sounds good and 1. sound better.

**Comment by szepeviktor** [comment]
I think MD5 verification should take place when we *put* something into the cache.

**Comment by davidfavor** [comment]
#3 sounds like a winner, as this likely resolves the partial updates masquerading a full updates.

Daniel, Kudos to you for getting to the bottom of this gnarly situation.

**Comment by danielbachhuber** [comment]
@novazembla I can't reproduce this now :( 

```
salty-wordpress ➜  .wp-cli  ./vendor/bin/behat features/core.feature --tags="@daniel"
Feature: Manage WordPress installation

  @daniel
  Scenario: Ensure cached partial upgrades aren't used in full upgrade # features/core.feature:659
    Given a WP install                                                 # features/steps/given.php:47
    And an empty cache                                                 # features/steps/given.php:14
    When I run `wp core download --version=4.2.1 --force`              # features/steps/when.php:24
    And I run `wp core update`                                         # features/steps/when.php:24
    Then STDOUT should not be empty                                    # features/steps/then.php:128
    When I run `wp core download --version=4.1.1 --force`              # features/steps/when.php:24
    And I run `wp core update`                                         # features/steps/when.php:24
    And I run `wp core verify-checksums`                               # features/steps/when.php:24
    Then STDOUT should be:                                             # features/steps/then.php:15
      """
      Success: WordPress install verifies against checksums.
      """

1 scenario (1 passed)
9 steps (9 passed)
0m17.68s
```

I'm asking `#meta` on WordPress Slack whether anything has changed about the API.

**Comment by danielbachhuber** [comment]
> I'm asking #meta on WordPress Slack whether anything has changed about the API.

[From](https://wordpress.slack.com/archives/meta/p1440315671000099) @dd32:

> The behaviour for partials hasn’t changed in months, partials have their own unique filenames, but one wouldn’t be offered for 4.1.x -> 4.2.x.  Most likely an interupted download, you can unzip partially downloaded ZIP files in some cases.

**Comment by danielbachhuber** [comment]
Found it 392aba67ebb58d6a6568f4065a808807d0992903

This bug sucked :(

**Comment by danielbachhuber** [comment]
:ship:'d for 0.17.2, 0.18.1 and 0.19.3, and I'll be getting to 0.20.0 this week.
