### ISSUE TITLE
wp comment recount command

### ISSUE THREAD

**Issue by nickcernis** [wp-cli/wp-cli#1902]
The `wp comment count` command returns the number of comments, but doesn't appear to update the `comment_count` column in the `wp_posts` table.

Updating comment counts can be useful if counts are inaccurate for any reason, such as following an import of posts from another WP blog.

Would `wp comment recount` be a welcome addition, or is there a way to achieve this already?

The `recount` command could run `wp_update_comment_count()` against all posts or a single given post ID.

**Comment by danielbachhuber** [comment]
> The wp comment count command returns the number of comments, but doesn't appear to update the comment_count column in the wp_posts table.

Correct.

> Would wp comment recount be a welcome addition, or is there a way to achieve this already?

I'd be open to a pull request. There is a way to achieve this, but it would involve writing a little script for yourself. I can see a dedicated command being helpful.

#1784 is related, because we'll need to think about how this command falls within the scope of CRUD operations.

**Comment by nickcernis** [comment]
Thanks for your work on this, @danielbachhuber – appreciate it. :-)
