### ISSUE TITLE
Check also extraneous files when verifying?

### ISSUE THREAD

**Issue by Ciantic** [wp-cli/wp-cli#1905]
I think at least in past the wp verify did not check if WP core directories contained extraneous files. Would it be possible to do also this check? It would give a sense of peace knowing that virus has not left extraneous files in some WP core directory.

**Comment by danielbachhuber** [comment]
> It would give a sense of peace knowing that virus has not left extraneous files in some WP core directory.

I'm not sure this is a problem we can solve with `wp core verify-checksums`. Isn't leaving extraneous files in `wp-content/themes`, `wp-content/uploads` or `wp-content/plugins` a similar issue? You can always use version control to detect added files.

**Comment by Ciantic** [comment]
No you can't solve wp-content/* directories with it, but I can at least skip versioning the WP core files and directories.

**Comment by danielbachhuber** [comment]
I think this problem is outside the scope of WP-CLI to solve.
