### ISSUE TITLE
media regenerate fails in vagrant using "wp-stack" setup

### ISSUE THREAD

**Issue by Vinsanity** [wp-cli/wp-cli#1906]
I have vagrant running with VVV and WP-CLI installed (0.19.2). My WordPress setup has WP as a git submodule and the content directory is outside the wp folder. 

When running any WP-CLI commands i need to add the --path flag but the issue I'm having is that no images will regenerate with wp media regenerate. I always get "Can't Find "imageName" (ID #)" 

I've checked into the $fullsizepath which throws the error and it's seeing the file and path correctly. An example is "/srv/www/domain/htdocs/content/uploads/2015/06/filename.jpg" and I can navigate to that image in terminal but somehow WP-CLI is not finding the images.

Any ideas what would cause this?

Thanks

**Comment by danielbachhuber** [comment]
> and I can navigate to that image in terminal but somehow WP-CLI is not finding the images.

Can you add some debugging on [this line](https://github.com/wp-cli/wp-cli/blob/master/php/commands/media.php#L213) and see what those values are?

In order to debug, you'll need to [install WP-CLI via Composer](https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods#installing-via-composer) so you have access to editing the files.

**Comment by szepeviktor** [comment]
Nowadays I put path in wp-cli.yml (which sits above docroot)
```yaml
path: /srv/www/domain/htdocs
```

**Comment by Vinsanity** [comment]
Thanks Daniel. Here is what I got on var_dump for the $fullsizepath. It appears that it is not prefixing the full path to the file. Should be "/srv/www/sitename/htdocs/content/uploads/" and then what you see below.

`Found 7 images to regenerate.
string(21) "2015/06/TopImage3.jpg"
Warning: Can't find "TopImage3" (ID 68).
string(21) "2015/06/TopImage4.jpg"
Warning: Can't find "TopImage4" (ID 69).
string(22) "2015/06/TopImage_1.jpg"
Warning: Can't find "TopImage_1" (ID 66).
string(21) "2015/06/TopImage2.jpg"
Warning: Can't find "TopImage2" (ID 67).
string(24) "2015/06/test-product.jpg"
Warning: Can't find "test-product" (ID 65).
Success: Finished regenerating all images.`

I'll try some additional debugging on my end and let you know what i find.

**Comment by Vinsanity** [comment]
@szepeviktor Thanks for the help.
I did try this and it does fix the issue of having to specify the --path flag but I still get the "Can't Find" message. The full file path string is not being appended/concatenated.

**Comment by szepeviktor** [comment]
What is the output of `wp eval 'var_export(wp_upload_dir());'`?

**Comment by Vinsanity** [comment]
Funny you should mention that. I was just testing that and noticed that It was reporting the directory without the full path. I tried changing the WP constant I have defined for WP_CONTENT_DIR form ` `$_SERVER['DOCUMENT ROOT']` to `dirname(_FILE_)` and it works now. 

It appears that vagrant returns the $_SERVER['DOCUMENT ROOT'] differently. 

Thanks for the help guys. Sorry for the false lead.

**Comment by szepeviktor** [comment]
> $_SERVER['DOCUMENT ROOT']
It is possible that the `_` is missing?

**Comment by Vinsanity** [comment]
No, the underscore is there. Markdown cutout my _ in my response (I had the wrong markdown syntax in there). Thanks again though. :)
