### ISSUE TITLE
installing wp doesn't create .htaccess file

### ISSUE THREAD

**Issue by Amin-z** [wp-cli/wp-cli#1907]
Hello, so when I install WordPress normally using the browser it creates the .htaccess file, which I typically need, but installing with WP-CLI doesn't create that .htaccess, so I have to copy/paste it manually ? shouldn't it also create the file for me.

**Comment by danielbachhuber** [comment]
> which I typically need, but installing with WP-CLI doesn't create that .htaccess, so I have to copy/paste it manually ?

You can also run `wp rewrite flush`: http://wp-cli.org/commands/rewrite/

> shouldn't it also create the file for me.

Oh! I totally forgot core added `wp_install_maybe_enable_pretty_permalinks()`. We'll look into doing the same behavior. Thanks for the report.

**Comment by Amin-z** [comment]
Thanks a lot mate for the update, I did try `wp rewrite flush` nothing happened, but no problem I do write the content of .htaccess manually.

Thanks again, feel free to close this issue.

**Comment by szepeviktor** [comment]
This option may help:
https://github.com/wp-cli/wp-cli/blob/master/php/commands/rewrite.php#L25-L26

**Comment by danielbachhuber** [comment]
> Oh! I totally forgot core added wp_install_maybe_enable_pretty_permalinks(). We'll look into doing the same behavior. Thanks for the report.

Not sure what I was thinking of before. `wp_install_maybe_enable_pretty_permalinks()` is [called within](https://core.trac.wordpress.org/browser/tags/4.2.2/src/wp-admin/includes/upgrade.php#L91) `wp_install()`, which we use.

**Comment by szepeviktor** [comment]
Adding `--hard` simply solves this.

**Comment by FarrOut** [comment]
yea i usually need to ```flush --hard``` after steak night
