### ISSUE TITLE
WP-CLI silently dies when --url parameter is used with an inexistent site url

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/wp-cli#1908]
In a multisite install, if you call WP-CLI using the --url parameter with an inexistent site url it will die silently. I think we should show a error message to the user. Something like:

```
$ wp post list --url=inexistent.example.com
Error: Site inexistent.example.com not found.
```

Thoughts?

**Comment by danielbachhuber** [comment]
I _believe_ this is actually a problem of WordPress, as all WP-CLI does is set the `HTTP_HOST`. I did a [search](https://github.com/wp-cli/wp-cli/issues?page=3&q=is%3Aissue+multisite+is%3Aclosed&utf8=%E2%9C%93) of [past](https://github.com/wp-cli/wp-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+url+is%3Aclosed+) issues though, and couldn't find any threads on the subject.

WP-CLI might be able to detect when WP doesn't do anything, and throw an error. I'll look into this more when I have a moment.

**Comment by rodrigoprimo** [comment]
The only easy way I found to fix this is using ms_site_not_found hook (https://github.com/rodrigoprimo/wp-cli/commit/0b8a45d78e0f24c9bf12fb1ebd7943860027c716). Should I open a PR or you prefer to first investigate if there is another solution?

**Comment by danielbachhuber** [comment]
> Should I open a PR or you prefer to first investigate if there is another solution?

PR would be great, thanks :)

**Comment by rodrigoprimo** [comment]
PR created. See #1909
