### ISSUE TITLE
Manage unconfirmed users on multisite

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#1911]
On multisite, a super admin can send an invite to a user to create an account. Until the invitation is accepted, the account lives in an odd, unconfirmed limbo state.

[Unconfirmed](https://wordpress.org/plugins/unconfirmed/) is a nifty plugin for managing unconfirmed users. While core [figures out whether this is a problem they want to solve](https://core.trac.wordpress.org/ticket/16001), it would be nice to have CLI for performing these operations.

**Comment by trepmal** [comment]
For what it's worth, I have https://github.com/trepmal/wp-cli-unconfirmed-users

**Comment by danielbachhuber** [comment]
Closing this at wontfix — best implemented as a community package first.

**Comment by tyrann0us** [comment]
Hi @danielbachhuber, after seven years, do you have a different opinion about supporting unconfirmed user handling in WP-CLI? @trepmal's package is nice, but it's cumbersome to install a package on many projects (and the `unconfirmed` command should be a `user` subcommand, IMO).

I think a tool like WP-CLI aimed at WordPress power users should include these advanced features (as in: not supported by WordPress UI) by default. Just like it includes existential commands like `search-replace`.

BTW, an alternative to the "[Unconfirmed](https://wordpress.org/plugins/unconfirmed/)" plugin is the great "[WP User Signups](https://wordpress.org/plugins/wp-user-signups/)" plugin by @jjj.

Thanks a lot!

**Comment by danielbachhuber** [comment]
@tyrann0us I'm not strongly opposed, no. We can reopen this.

**Comment by tyrann0us** [comment]
@danielbachhuber, that's great to hear, thanks!

@trepmal, would you agree on and have the resources to do a PR against https://github.com/wp-cli/entity-command to bring the code you wrote in https://github.com/trepmal/wp-cli-unconfirmed-users to core WP-CLI?
From the looks of it, it shouldn't be too much work. 🙂

Thanks!

**Comment by ernilambar** [comment]
I have created separate `signup` command here. https://github.com/ernilambar/signup-command If acceptable, I can prepare PR against `entity-command` repo.

**Comment by ernilambar** [comment]
PR create here https://github.com/wp-cli/entity-command/pull/489

**Comment by tyrann0us** [comment]
With https://github.com/wp-cli/entity-command/pull/489 released as part of WP-CLI 2.11.0, the [`wp user signup`](https://developer.wordpress.org/cli/commands/user/signup/) command is now available and this issue can be closed. Almost 9 years after it was created. 💪🏽 🙂

**Comment by danielbachhuber** [comment]
🚢
