### ISSUE TITLE
How to use classes with PHP?

### ISSUE THREAD

**Issue by eduardoarandah** [wp-cli/wp-cli#1912]
I don't know if this is the right place to ask this question:

How can I use wp-cli classes in PHP without going through command line?

Example:

Instead of using php to execute command line to execute wp-cli:

    <?php
    exec('php wp-cli.phar cli version', $out, $ret);

I want to use classes directly. something like this:

    <?php 
    include 'wp-cli.phar';
    echo new CLI_Command().version();

**Comment by danielbachhuber** [comment]
> How can I use wp-cli classes in PHP without going through command line?

WP-CLI is a "command line interface" for WordPress. It's not intended to be used outside of the CLI context.
