### ISSUE TITLE
Systemwide wp-cli update

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1914]
```
$ wp --allow-root cli update
You have version 0.19.1. Would you like to update to 0.19.2? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v0.19.2/wp-cli-0.19.2.phar...
Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.

If you'd like to continue as root, please run this again, adding this flag:  --allow-root

If you'd like to run it as the user that this site is under, you can run the following to become the respective user:

    sudo -u USER -i -- wp <command>


PHP Warning:  max(): Array must contain at least one element in phar:///usr/local/bin/wp/php/WP_CLI/Loggers/Regular.php on line 87




Error: The downloaded PHAR is broken, try running wp cli self-update again.
```

**Comment by szepeviktor** [comment]
Does it fail by design?

**Comment by danielbachhuber** [comment]
> Does it fail by design?

Nope, probably just an oversight.

**Comment by szepeviktor** [comment]
The could be a `get_flag_value( 'allow-admin' )`.

**Comment by danielbachhuber** [comment]
:ship:

**Comment by szepeviktor** [comment]
Are you sure #1935 will solve this issue?

**Comment by szepeviktor** [comment]
I think running wpcli update without `--allow-root` causes this error. https://github.com/wp-cli/wp-cli/blob/master/php/commands/cli.php#L175

**Comment by szepeviktor** [comment]
Oh! #1932 solves this.

**Comment by jonathan-dejong** [comment]
So I know this is a closed issue but I'm on v 0.18 and attempts to update with no luck. 

Running `sudo wp cli update --allow-root` results in:
`
PHP Warning:  max(): Array must contain at least one element in phar:///usr/local/bin/wp/php/WP_CLI/Loggers/Regular.php on line 87
Error: The downloaded PHAR is broken, try running wp cli self-update again.
`
How should I go about updating so this issue is rid off? The owner is www-data which I don't have access to :/

**Comment by danielbachhuber** [comment]
Try using the manual installation instructions instead http://wp-cli.org/#install

**Comment by jonathan-dejong** [comment]
Thanks @danielbachhuber  

It worked. I saw the docs before but failed to notice the little note "Upgrade using the same procedure." at the end.
