### ISSUE TITLE
Call to undefined function wp_cache_post_change()

### ISSUE THREAD

**Issue by mondalaci** [wp-cli/wp-cli#1915]
$:~/.wp-cli/commands/wp-super-cache-cli# wp --path=/var/www/mysite super-cache flush --post_id=1502
PHP Fatal error:  Call to undefined function wp_cache_post_change() in /root/.wp-cli/commands/wp-super-cache-cli/cli.php on line 16
Fatal error: Call to undefined function wp_cache_post_change() in /root/.wp-cli/commands/wp-super-cache-cli/cli.php on line 16

Originally, I wanted to report this issue under https://github.com/wp-cli/wp-super-cache-cli but there's no issue section there. Maybe it should be created.

**Comment by szepeviktor** [comment]
`wp_cache_post_change()` is defined in [wp-super-cache/wp-cache-phase2.php](https://github.com/Automattic/wp-super-cache/blob/456cfd3a47e43e274a476ed3f3dedf68b6ed3c8b/wp-cache-phase2.php#L1061).
Is wp-super-cache plugin active?

**Comment by mondalaci** [comment]
I could already see that `wp_cache_post_change()` is defined in `wp-super-cache/wp-cache-phase2.php`.

Yes, the super cache plugin is active.

**Comment by szepeviktor** [comment]
It is a bug.

**Comment by mondalaci** [comment]
Could you please elaborate on that? I need to use the super cache cli plugin quite badly.

**Comment by szepeviktor** [comment]
wp-cli lauches WP core by its [php/wp-settings-cli.php](https://github.com/wp-cli/wp-cli/blob/master/php/wp-settings-cli.php) so `wp-settings.php` does not get executed thus `advanced-cache.php` does not get included thus no wp_cache_postload thus `wp_cache_phase2()` does not get called. And your undefined function is in `wp-cache-phase2.php`.
I think wp-super-cache-cli is not maintained.

**Comment by danielbachhuber** [comment]
> wp-cli lauches WP core by its php/wp-settings-cli.php so wp-settings.php does not get executed thus advanced-cache.php does not get included thus no wp_cache_postload() thus wp_cache_phase2() does not get called. 

I've merged https://github.com/wp-cli/wp-super-cache-cli/pull/5 to fix this.

> I think wp-super-cache-cli is not maintained.

Sorry, I wasn't getting notifications on the repo.

**Comment by mondalaci** [comment]
Thanks a ton for being so helpful and quick, guys! In the meantime, I've fixed the fix at https://github.com/wp-cli/wp-super-cache-cli/pull/6 :)
