### ISSUE TITLE
Can't install plugins via composer

### ISSUE THREAD

**Issue by mondalaci** [wp-cli/wp-cli#1916]
I did everything as written in https://github.com/wp-cli/wp-cli/wiki/Community-Packages#setting-up-the-package-index and yet, I get:

$:~/.wp-cli# composer.phar require danielbachhuber/wp-cli-stat-command=dev-master
./composer.json has been updated
Loading composer repositories with package information
                                                                                                                                                         
  [Composer\Downloader\TransportException]                                                                                                               
  The "http://wp-cli.org/package-index/include/all$cc60c5b828017a7c5627c4edfd8afe1a341d368c.json" file could not be downloaded (HTTP/1.1 404 Not Found)  
 
require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

**Comment by danielbachhuber** [comment]
> Note: The WP-CLI Package Index is unavailable while we [determine a new direction](https://github.com/wp-cli/wp-cli/issues/1564) for community packages.
