### ISSUE TITLE
Bash. apt-get tab completion works incorrectly after use wp tab completion

### ISSUE THREAD

**Issue by StarWix** [wp-cli/wp-cli#1919]
When I login in system apt-get tab completion work correctly:
<pre>
apt-get [tab] 
autoclean        check            dselect-upgrade  source
autoremove       clean            install          update
build-dep        dist-upgrade     purge            upgrade
changelog        download         remove
</pre>
After I use wp tab completion:
<pre>
wp [tab]
cache            eval-file        plugin           site 
cap              export           post             super-admin 
cli              help             rewrite          term 
comment          import           role             theme 
core             media            scaffold         transient 
cron             menu             search-replace   user 
db               network          shell            widget 
eval             option           sidebar    
</pre>
And apt-get completion work incorrectly:
<pre>
apt-get [tab]
            changelog check clean autoclean autoremove
            dist-upgrade install remove purge source build-dep download
update upgrade dselect-upgrade
</pre>
or
<pre>
apt-get u[tab]pdate upgrade dselect-upgrade
</pre>
OS: Ubuntu 14.04

**Comment by szepeviktor** [comment]
You're right. I've never knew what happened to apt-get completion.

**Comment by szepeviktor** [comment]
The temporary solution is to restore `$IFS`

```bash
_wp_complete() {
    local OLD_IFS="$IFS"

    # The current function content.

    IFS="$OLD_IFS"
    return 0
```

**Comment by szepeviktor** [comment]
@danielbachhuber Do you know someone who can help us?
Our completion function does not look like this:
http://anonscm.debian.org/cgit/bash-completion/bash-completion.git/tree/completions/apt-get

**Comment by danielbachhuber** [comment]
> Do you know someone who can help us?

Help us in what way? Would your proposed temporary solution be sufficient?

**Comment by szepeviktor** [comment]
That is called a *hack*.
wpcli's completion script should look like
http://anonscm.debian.org/cgit/bash-completion/bash-completion.git/tree/completions/apt-get

**Comment by szepeviktor** [comment]
If you are willing I prepare a PR with the above.

**Comment by danielbachhuber** [comment]
I'm fine with the hack fix for now. Eventually rewriting the bash completion to make it proper shouldn't get in the way of the fix

**Comment by szepeviktor** [comment]
PR: https://github.com/wp-cli/wp-cli/pull/1926
