### ISSUE TITLE
Running WPCLI in php script

### ISSUE THREAD

**Issue by Thirty8Digital** [wp-cli/wp-cli#1924]
Hi

Forgive me if this is a silly question (it may well be) - but I've had success running WPCLI from the [cough] CLI. But now I'd like to call it from a PHP script. Is this possible / stupid / misguided? I have tried some shell_exec attempts but to no avail...

Thanks 

Mike

**Comment by danielbachhuber** [comment]
> Is this possible / stupid / misguided?

Nope, totally doable.

> I have tried some shell_exec attempts but to no avail...

Can you share what you've tried, and how those attempts failed?

**Comment by Thirty8Digital** [comment]
Well, I only got as far as this:

$output = shell_exec('wp core download 2>&1');
echo "<pre>$output</pre>";

Forgive any obvious noob errors - I'm more a hacker than a proper dev :-)

I get this error:

/usr/bin/wp: line 1: /Applications/MAMP/bin/php/php5.3.14/bin/php: No such file or directory

If I run my shell script in the same location, it works fine..

**Comment by szepeviktor** [comment]
Try something like
```php
define( 'WP_CLI_ROOT', '/path/to/wp-cli' );
include WP_CLI_ROOT . '/php/wp-cli.php';
```
as in https://github.com/wp-cli/wp-cli/blob/master/php/boot-phar.php

**Comment by szepeviktor** [comment]
Then you may have to fiddle with `$GLOBALS['argv']`.

**Comment by szepeviktor** [comment]
I was also thinking about running wp-cli on shared hosting where there's no shell access.

**Comment by szepeviktor** [comment]
@danielbachhuber Maybe there could be a `boot-web.php`.

**Comment by danielbachhuber** [comment]
I don't think running WP-CLI from web requests is a good idea.

**Comment by danielbachhuber** [comment]
> /usr/bin/wp: line 1: /Applications/MAMP/bin/php/php5.3.14/bin/php: No such file or directory

Does `/Applications/MAMP/bin/php/php5.3.14/bin/php` exist?

**Comment by Thirty8Digital** [comment]
Um, no. But there are more recent versions of PHP in there. Unclear how/where the php version is specified....

![screen shot 2015-07-16 at 12 42 11](https://cloud.githubusercontent.com/assets/10513960/8722011/20aee418-2bb8-11e5-93b5-cef55b4303f5.png)

**Comment by danielbachhuber** [comment]
> Unclear how/where the php version is specified....

Old symlink maybe? Can you call `which php` from `shell_exec()` to see how your system is resolving it?

**Comment by Thirty8Digital** [comment]
So this:


$output = shell_exec('which php');
echo "<pre>$output</pre>";

outputs just 

/usr/bin/php

**Comment by danielbachhuber** [comment]
And try `ls -al /usr/bin/php` ? Is it a symlink to the MAMP binary?

**Comment by Thirty8Digital** [comment]
That gives

-rwxr-xr-x  1 root  wheel  9970848 May 19 18:12 /usr/bin/php

**Comment by danielbachhuber** [comment]
Hm. Hard to debug without access to your machine :(

**Comment by szepeviktor** [comment]
> $output = shell_exec('wp core download 2>&1');

Try my snippet:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/shared-hosting-aid/wp-unzip-install.php

**Comment by Thirty8Digital** [comment]
Thanks @danielbachhuber - I'll keep fiddling. It's good to know it's basically possible.

@szepeviktor - thanks for help, but want to use WPCLI rather than other methods :-)

**Comment by mlutfy** [comment]
I have done similar testing for the Aegir project (aegirproject.org, a Free Software farm hosting for Drupal, but I want to add WordPress support). Aegir itself is a Drupal instance that installs other Drupal instances (using drush sub-modules). It probably sounds a bit wacky, but it's basically a set of PHP scripts that happen to run within Drupal (for user/access management, admin dashboard, etc).

So far, I have been using this:
https://github.com/mlutfy/hosting_wordpress/blob/7.x-3.x/hosting_wpplatform/drush/install.wordpress.provision.inc#L83

```
  $GLOBALS['argv'] = array(
    'wp',
    '--path=' . d()->root . '/',
    'core',
    'install',
    '--url=' . d()->uri,
    '--title=' . d()->uri,
    '--admin_user=admin',
    '--admin_email=' . $admin_email,
    '--admin_password=FIXME',
  );
  define('WP_CLI_ROOT', '/var/aegir/.composer/vendor/wp-cli/wp-cli');
  require_once WP_CLI_ROOT . '/php/wp-cli.php';
```

The main motivations for using wp-cli this way:

* we could generate a password and not pass it on the command line (where it could be seen by other users in the process list)
* to have more clear logging of warnings/errors (ideally using a custom logging class).

I would much prefer to use WP_CLI::run_command(), but I could not figure the details on how to pass the parameters.

On the other hand, maybe it's not worth it. I heard that WP 4.3 will have support to automatically create a strong password. There would then be the logging issue, but between the output and the error code, it could be sufficient for my needs.

**Comment by szepeviktor** [comment]
I was supposing this in https://github.com/wp-cli/wp-cli/issues/1924#issuecomment-121929530

@danielbachhuber using wp-cli programmatically should be more user-friendly (and hack-free)-

**Comment by danielbachhuber** [comment]
WP-CLI stands for WordPress Command Line Interface. Currently, it presents a clear, consistent interface to WordPress because WordPress' interfaces themselves are the result of dozens of developers over 10+ years. WP-CLI will eventually shed much of its internals to wrap WP-API, a project to make WordPress‘ interfaces more consistent. WP-CLI will only ever be a command line interface to WordPress. Use cases outside of the command line are outside the scope of the project.

**Comment by szepeviktor** [comment]
Please consider that there's a composer package of wp-cli that indicates programmatically usage.
Would it be hard work to provide one function to start up wp-cli?

**Comment by danielbachhuber** [comment]
> Would it be hard work to provide one function to start up wp-cli?

Difficulty isn't the point. My point is that it's outside the scope of WP-CLI to interoperate with web applications. CLI tools can call WP-CLI as a binary just fine.

**Comment by szepeviktor** [comment]
> to interoperate with web applications

Maybe with other CLI application? I think Aegir project is a CLI one.

**Comment by szepeviktor** [comment]
Would there be a downside to provide a bootstrap function instead of fiddling with `$GLOBALS['argv']`?

**Comment by danielbachhuber** [comment]
> Would there be a downside to provide a bootstrap function

This isn't a use case I'd like to support. `shell_exec()` is sufficient for launching WP-CLI in CLI context.

**Comment by COLABORATI** [comment]
Hey, Daniel, please reconsider this. It is really a great idea to have wp-cli and all the tools, commands and libraries at hand when writing your own scripts for any wordpress environment, and of course writing these scripts in php and not in ruby, bash or anything else makes sense, so it would be really great to have you support the usage of wp-cli not only as a command line tool to exec but also as an ecosystem for wordpress that anybody can just `include` in their own php shell scripts. 

I am defnitely not writing about using wp-cli from a web request - this would be material for some funny absurd recursive anti-hack :) However, for a shell script with php having wp-cli at hand would be great. 

I do not think the use like mlufty described [above](https://github.com/wp-cli/wp-cli/issues/1924#issuecomment-122075194) is too complicated or hacky. I just wanted to confirm that the use of wp-cli & friends as a library is a great way to make use of it in php shell scripts and should be supported and not break in future. 

Of course this might be an indicator that writing your own wp-cli commands for three lines of shell script is still too involved... have to check that again.

**Comment by sun** [comment]
FWIW, I don't think that this should be "officially supported" by WP-CLI, but people may already be happy to come here and find a working solution.

I've summarized the different suggestions into a quick script.  To use:

1. Download/upload `wp-cli.phar` to your web space.

1. Create `cli.php` (the script below) and upload it into the same folder of `wp-cli.phar`.

1. Test that it works by accessing it; e.g., http://example.com/cli.php

1. Replace the last arguments (`cli info`) within the script with your desired arguments and options in the same way you'd specify them normally on the command line.

1. Access it again; e.g., by reloading.

    Note that some commands (such as `search-replace`) assume `STDOUT` to be a writable stream resource, which doesn't exist in this execution context, so you will see errors like the following instead of the actual output:

    > Warning:  fwrite() expects parameter 1 to be resource, string given in phar:///path/to/htdocs/wp-cli.phar/vendor/wp-cli/php-cli-tools/lib/cli/Streams.php on line 66

    I'm relatively sure there's a trick around that, but I didn't need that for my purposes.

1. Delete both files `cli.php` and `wp-cli.phar`.

---
`cli.php`:
```php
<?php

ini_set('display_errors', 'on');
//error_reporting(E_ALL);
echo "<pre>\n";

# @see https://github.com/wp-cli/wp-cli/issues/1924#issuecomment-122075194
$GLOBALS['argv'] = explode(' ', 'wp --path=' . __DIR__ . ' cli info');

# @see https://github.com/wp-cli/wp-cli/blob/master/php/boot-phar.php
const WP_CLI_ROOT = 'phar://wp-cli.phar';
include WP_CLI_ROOT . '/php/wp-cli.php';

?>
```

**Comment by mwithheld** [comment]
Here's  a variant for the cli.php code that works for me, in case it helps someone else:

`<?php
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', '1');
echo "<PRE>\n";

if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'r'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));
if(!defined('STDERR')) define('STDERR', fopen('php://stdout', 'w'));

echo "Started\n\n";
$return_status = false;
$output = array();
$executable = '/path/to/php-executable -c /path/to/php.ini -d error_reporting="E_ALL & ~E_NOTICE" -d memory_limit="2048M" -d max_execution_time=43200 wp-cli.phar ';
//Redirect stdERR so we see warnings/errors
$suffix = ' 2>&1';
//echo 'Built executable='.$executable."\n";

$command = 'user delete johnsmithfake --network --yes';
$full_command = $executable.$command.$suffix;
echo "About to execute command=\n{$full_command}\n";
exec($full_command, $output, $return_var);

echo "---------------\n";
echo implode("\n", $output)."\n";
echo "---------------\n";
echo "Return status (false/0 is success)=".($return_status?1:0)."\n";

echo "\nDone</PRE>\n";
`

**Comment by truongluu** [comment]
thanks mwithheld. works for me

**Comment by pixelprogrammer** [comment]
@mwithheld you ingenious son of a gun. That worked! How did you come up with that solution and could you explain it a little as to why it would work?

**Comment by mwithheld** [comment]
PHP has the ability to run shell commands built-in (which may be disabled by server admins).  All the script does is build the command and run it, using built-in PHP to capture the output.

**Comment by pixelprogrammer** [comment]
interesting, because what was failing for me wasn't using 

`exec('wp --info')`
 
but doing something like 

`exec('wp core install --url="example.com" --path="/path/to/wordpress"....)`

Whenever I used core install it would work on the command line but would fail when run through the exec() function in php. Adding the $output and $return parameters to the exec() function returned no output but returned 1 (which means error). So something was failing anytime I ran commands that needed to interact with Wordpress but not anything simple like `wp --info`.

Anyways, your solution worked so thank you.

**Comment by lordspace** [comment]
@pixelprogrammer  have you redirected STDERR to see what's the actual error?
`exec('wp --info 2>&1');`

**Comment by pixelprogrammer** [comment]
@lordspace No I hadn't tried that one.

**Comment by benfavre** [comment]
Nice to see people are open to ideas and discussion on what is one of the biggest open source projects powering the web.
