### ISSUE TITLE
'plugin list' option changes format when written to a file in CentOS 7

### ISSUE THREAD

**Issue by rklrkl** [wp-cli/wp-cli#1925]
On CentOS 7 with PHP 5.4.16 and WP-CLI 0.19.2, if you just run "wp plugin list" on a terminal, you get a bordered text table. However, if you run "wp plugin list >/tmp/plugin.list" and then look at the /tmp/plugin.list file, it removes all the table formatting (i.e. no minus, plus or  vertical bar chars), which is somewhat inconsistent.

Note that on CentOS 6 with PHP 5.3.3 and WP-CLI 0.19.2, this doesn't happen - the terminal output from the first command and the contents of /tmp/plugin.list after running the second command are the same.

Ideally, I'd like something like a --table-format option to enforce keeping the bordered text table format regardless as to whether it's going to a terminal or a file.

**Comment by danielbachhuber** [comment]
> On CentOS 7 with PHP 5.4.16 and WP-CLI 0.19.2, if you just run "wp plugin list" on a terminal, you get a bordered text table. However, if you run "wp plugin list >/tmp/plugin.list" and then look at the /tmp/plugin.list file, it removes all the table formatting (i.e. no minus, plus or vertical bar chars)

This is intended: https://github.com/wp-cli/php-cli-tools/blob/228e8c1300675313e519b4195783aaa1a1a020bf/lib/cli/Table.php#L69

> Ideally, I'd like something like a --table-format option to enforce keeping the bordered text table format regardless as to whether it's going to a terminal or a file.

You can set a `SHELL_PIPE=0` environment variable to achieve this behavior: https://github.com/wp-cli/php-cli-tools/blob/228e8c1300675313e519b4195783aaa1a1a020bf/lib/cli/Shell.php#L52
