### ISSUE TITLE
Is there a way to specify DB creds on the command line?

### ISSUE THREAD

**Issue by theMikeD** [wp-cli/wp-cli#1927]
I use a system by which `wp-config.php` is in git, but the db creds are not; they are loaded via an include as Mark suggests here

https://github.com/markjaquith/WordPress-Skeleton

`wp-cli` fails with such a setup because it's reading in the `wp-config.php` file directly (as opposed to after having been washed through php first) and it's looking for something that's not *in* the file. 

This page

http://wp-cli.org/config/

seems to imply that the DB creds can be put into a `wp-cli.local.yml` file using dbuser and dbpass. I've tried it though and it doesn't work.

Is there a trick to it, or is this something that will not work at all? I'm def. not looking for a debate on the merits of doing things this way; take that up with Mark if you like.

**Comment by theMikeD** [comment]
Closing, because I think the issue is elsewhere. Sorry for the noise.

**Comment by danielbachhuber** [comment]
> wp-cli fails with such a setup because it's reading in the wp-config.php file directly (as opposed to after having been washed through php first) and it's looking for something that's not in the file.

See also #1631
