### ISSUE TITLE
Enhancement Request: Add Changelog

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#1937]
Be great if there was a Changelog on github front page.

**Comment by szepeviktor** [comment]
wp-cli is moving fast. You can take a look at the commit messages.

**Comment by szepeviktor** [comment]
And here are the solved issues for the next milestone:
https://github.com/wp-cli/wp-cli/issues?q=milestone%3Anext+is%3Aclosed

**Comment by danielbachhuber** [comment]
As @szepeviktor mentioned, there are already a few different ways to review changes going into WP-CLI. The [release notes](http://wp-cli.org/blog/) are the canonical source of documentation for each release.
