### ISSUE TITLE
wordpress-tests-lib files not being created

### ISSUE THREAD

**Issue by ZWS2014** [wp-cli/wp-cli#1938]
I'm using WP-CLI 0.19.2 and have been attempting to run phpunit after using wp scaffold, exactly as per instructions here: https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests

I've tried this on both Ubuntu 14.04 and Arch Linux systems, following the above instructions to the letter. PHPunit and WP-CLI are correctly installed, and I've tested using both global and project specific installs of phpunit and wp-cli.

The issue is always the same; upon running phpunit I get:

`Warning:  require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/my_plugin_name/tests/bootstrap.php on line 8`

`Fatal error:  require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/wp-content/plugins/my_plugin_name/tests/bootstrap.php on line 8`

There are no files being created in /tmp/wordpress-tests-lib other than wp-tests-config.php

**Comment by danielbachhuber** [comment]
Can you share the output of:

```
bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
```

from your plugin directory?

**Comment by ZWS2014** [comment]
Sure, output is: 

` + install_wp
+ '[' -d /tmp/wordpress/ ']'
+ return
+ install_test_suite
++ uname -s
+ [[ Linux == \D\a\r\w\i\n ]]
+ local ioption=-i
+ '[' '!' -d /tmp/wordpress-tests-lib ']'
+ cd /tmp/wordpress-tests-lib
+ '[' '!' -f wp-tests-config.php ']'
+ install_db
+ PARTS=(${DB_HOST//\:/ })
+ local PARTS
+ local DB_HOSTNAME=localhost
+ local DB_SOCK_OR_PORT=
+ local EXTRA=
+ '[' -z localhost ']'
++ echo
++ grep -e '^[0-9]\{1,\}$'
+ '[' ']'
+ '[' -z ']'
+ '[' -z localhost ']'
+ EXTRA=' --host=localhost --protocol=tcp'
+ mysqladmin create wordpress_test --user=root '--password=my_password' --host=localhost --protocol=tcp`

**Comment by danielbachhuber** [comment]
Can you try running `rm -rf /tmp/wordpress-tests-lib; bash bin/install-wp-tests.sh wordpress_test root '' localhost latest` and then `phpunit` again? It seems like you may have a bad download

**Comment by ZWS2014** [comment]
After another retry, it's now working fine. 
I have absolutely no idea why this occurred; I've gone back and attempted to replicate the error by changing various installation conditions but now can't seem to get it to fail!
I did refactor my plugin code between initial failures and the successful install, changing a few plugin filenames and so forth, so I'm thinking perhaps some problem traversing my plugin may have caused some kind of error cascade when installing the test, that led to the download command for the wordpress-tests-lib not to be triggered...
In any case, it's working well now, that's the main thing. If I can replicate the issue in future I'll report back - maybe submit a pull request if I can figure out exactly what was causing the problem.
Thanks for the suggestions and for all your work on this plugin - very much appreciated.

**Comment by abdulwahab610** [comment]
Hi Deniel
I'm try PHPUnit test on Windows. 
Installed PHPUnit and WP-CLI successfully. The issue is same as above mention for Ubuntu, Linux system.

`PHP Warning:  require_once(/tmp/wordpress-tests-lib/includes/functions.php): fai
led to open stream: No such file or directory in C:\xampp\htdocs\myplugin\wp-content\plugins\wp-analytify\tests\bootstrap.php on line 14` 

No files being created in /tmp/wordpress-tests-lib other than wp-tests-config.php

**Comment by sjalgeo** [comment]
@danielbachhuber I have to repeat the fix 
`rm -rf /tmp/wordpress-tests-lib; bash bin/install-wp-tests.sh wordpress_test root '' localhost latest` 
everytime I reboot.

Is it something to do with it being a temp file? Any input appreciated

**Comment by danielbachhuber** [comment]
Hi @sjalgeo,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by rochapablo** [comment]
I'm getting the same error and at [#support](http://wp-cli.org/#support) there is nothing about it.

The database it's been created, but none tmp folder.
 

Here's the output:

```
$ rm -rf /tmp/wordpress-tests-lib; bash bin/install-wp-tests.sh wordpress-server-tests root '' localhost latest
+ install_wp
+ '[' -d /tmp/wordpress/ ']'
+ return
+ install_test_suite
++ uname -s
+ [[ MINGW32_NT-10.0-WOW == \D\a\r\w\i\n ]]
+ local ioption=-i
+ '[' '!' -d /tmp/wordpress-tests-lib ']'
+ mkdir -p /tmp/wordpress-tests-lib
+ svn co --quiet https://develop.svn.wordpress.org/tags/4.7.2/tests/phpunit/includes/ /tmp/wordpress-tests-lib/includes
+ svn co --quiet https://develop.svn.wordpress.org/tags/4.7.2/tests/phpunit/data/ /tmp/wordpress-tests-lib/data
+ '[' '!' -f wp-tests-config.php ']'
+ download https://develop.svn.wordpress.org/tags/4.7.2/wp-tests-config-sample.php /tmp/wordpress-tests-lib/wp-tests-config.php
++ which curl
+ '[' /mingw32/bin/curl ']'
+ curl -s https://develop.svn.wordpress.org/tags/4.7.2/wp-tests-config-sample.php
++ echo /tmp/wordpress/
++ sed 's:/\+$::'
+ WP_CORE_DIR=/tmp/wordpress
+ sed -i 's:dirname( __FILE__ ) . '\''/src/'\'':'\''/tmp/wordpress/'\'':' /tmp/wordpress-tests-lib/wp-tests-config.php
+ sed -i s/youremptytestdbnamehere/wordpress-server-tests/ /tmp/wordpress-tests-lib/wp-tests-config.php
+ sed -i s/yourusernamehere/root/ /tmp/wordpress-tests-lib/wp-tests-config.php
+ sed -i s/yourpasswordhere// /tmp/wordpress-tests-lib/wp-tests-config.php
+ sed -i 's|localhost|localhost|' /tmp/wordpress-tests-lib/wp-tests-config.php
+ install_db
+ '[' false = true ']'
+ PARTS=(${DB_HOST//\:/ })
+ local PARTS
+ local DB_HOSTNAME=localhost
+ local DB_SOCK_OR_PORT=
+ local EXTRA=
+ '[' -z localhost ']'
++ echo
++ grep -e '^[0-9]\{1,\}$'
+ '[' ']'
+ '[' -z ']'
+ '[' -z localhost ']'
+ EXTRA=' --host=localhost --protocol=tcp'
+ mysqladmin create wordpress-server-tests --user=root --password= --host=localhost --protocol=tcp
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
```

Another question is

```
+ sed -i s/youremptytestdbnamehere/wordpress-server-tests/ /tmp/wordpress-tests-lib/wp-tests-config.php
+ sed -i s/yourusernamehere/root/ /tmp/wordpress-tests-lib/wp-tests-config.php
+ sed -i s/yourpasswordhere// /tmp/wordpress-tests-lib/wp-tests-config.php
```

Should I change those values (youremptytestdbnamehere, yourusernamehere, yourpasswordhere)?

If YES, what should I put in the password since it's empty, which take me to others errors.

**Comment by kadimi** [comment]
Before re-running the shell script, I would recomment deleting all WordPress file in `/tmp`, not only `/tmp/wordpress-tests-lib/includes`, so:

```shell
rm -fr /tmp/wordpress* &&  bash bin/install-wp-tests.sh "wp.dev" root root localhost latest

**Comment by mylonasg88** [comment]
Removing everything from `/tmp/` folder regarding wordpress did the job! Thanks @kadimi 
After that I had error regarding `svn` command not being installed.
`sudo apt-get install subversion` to install it. 

Now I'm getting `PHPUnit_Util_Test` errors but that's an other story 😄

**Comment by kibblewhite** [comment]
Still having the same issue here. Resolved it by using the following:
rm -Rf /tmp/wordpress* &&  bin/install-wp-tests.sh wordpress_test root 'password-here' localhost latest
