### ISSUE TITLE
when running wp core config --dbpass I get an error

### ISSUE THREAD

**Issue by adampatterson** [wp-cli/wp-cli#1941]
I get an error when my password contains !! even when closing --dbpass="xxxx!!"

I tried this a few times without any luck. Im obviously not going to change my DB password but thought you should know.

**Comment by szepeviktor** [comment]
I see you might have `!` in your password.
Bash need single quotes around `'!'`.

**Comment by szepeviktor** [comment]
`!` is the history expansion character:
http://www.gnu.org/software/bash/manual/bash.html#Quoting
