### ISSUE TITLE
post_category bug

### ISSUE THREAD

**Issue by johnnywinter** [wp-cli/wp-cli#1944]
I cannot change my post category. I try this but it's not working:
wp post update 10294 --post_category=2 --path=/usr/share/nginx/html

**Comment by danielbachhuber** [comment]
Can you share the output you get?

**Comment by johnnywinter** [comment]
Output:
Success: Updated post 10294.

But nothing happened the post category not change.

**Comment by johnnywinter** [comment]
wp_insert parameters:
'post_category'  => [ array(<category id>, ...) ] // Default empty.

I think that I must add an array. How can I do this?

**Comment by danielbachhuber** [comment]
> I think that I must add an array. How can I do this?

You don't need to format as an array. WP-CLI already intelligently parses CSV: https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L67

But, that's just for `wp post insert`. The same needs to be handled for `wp post update`
