### ISSUE TITLE
Check for existing value by field

### ISSUE THREAD

**Issue by poorgeek** [wp-cli/wp-cli#1949]
As part of a multi-env setup, we're starting to script out more and more of our content changes so that as we deploy changes succesive environements we can make sure that the same posts/pages/capabilities/etc... get created. One thing that would make this a little easier to do would be an 'exists' sub-command for each of the commands that creates/adds something. Then using the existing `--<field>=` params to find what it is you're looking for.

I'm thinking it would work something like
```sh
$ wp post exists --post_title="Example"
0
$ wp post create --post_type=post --post_title="Example" --porcelain
52
$ wp post create --post_type=page --post_title="Example" --porcelain
53
$ wp post exists --post_title="Example"
52,53
$ wp post exists --post_type=page --post_title="Example"
53
```

As 0.19.2, the only way to do this, that I know of, is to grep the result of `wp post list` for the value I'm looking for.

**Comment by danielbachhuber** [comment]
> As 0.19.2, the only way to do this, that I know of, is to grep the result of wp post list for the value I'm looking for.

Doesn't this do what you're asking?

```
salty-wordpress ➜  wordpress-develop.dev  wp post list --post_name=hello-world
+----+--------------+-------------+---------------------+-------------+
| ID | post_title   | post_name   | post_date           | post_status |
+----+--------------+-------------+---------------------+-------------+
| 1  | Hello world! | hello-world | 2015-07-27 03:29:02 | publish     |
+----+--------------+-------------+---------------------+-------------+
salty-wordpress ➜  wordpress-develop.dev  wp post list --post_name=hello-world --field=ID
1
```

**Comment by poorgeek** [comment]
Why yes, yes it does. I had totally overlooked the ID option to `--format`. :(

Maybe it makes sense to have an `exists` subcommand as an alias to `wp * list --field=ID`. If not, maybe this issue will help someone else trying to do the same thing we are.

**Comment by poorgeek** [comment]
@danielbachhuber Sorry, but I spoke too soon. I went to try this out and no matter what field/value combination I enter, the list subcommand always returns the full list. 

Given the above example, `--post_name=sock` returns the same result as `--post_name=hello-world`.

**Comment by danielbachhuber** [comment]
Sorry, the argument is `--name`:

```
salty-wordpress ➜  wordpress-develop.dev  wp post list --name=foo --field=ID
salty-wordpress ➜  wordpress-develop.dev  wp post list --name=hello-world --field=ID
1
```

You can use any arguments you'd pass to WP_Query

**Comment by poorgeek** [comment]
Ah that got it. Little confusing with the switch to WP_Query syntax there, but it works so I'm good.

**Comment by chrisbloom7** [comment]
I was having the same issue. According to the `post list` docs:

    [--<field>=<value>]
        One or more args to pass to WP_Query.
    ...
    AVAILABLE FIELDS
    ...
    >> post_name

That would seem to indicate that I could search on `post_name`, especially since the examples on that page follow the same format. Updating the docs with this would be helpful.
