### ISSUE TITLE
wp plugin update deletes old version of plugin before checking if new version exists (if --version is set)

### ISSUE THREAD

**Issue by pczupil** [wp-cli/wp-cli#1950]
Found a bug when trying to update a plugin that didn't exist on the wordpress.org/plugins site (In retrospect, I probably shouldn't have tried to install a plugin that was not available). Here is the snippet of code causing the problem:		

```
function update( $args, $assoc_args ) {
    if ( isset( $assoc_args['version'] ) ) {
        foreach ( $this->fetcher->get_many( $args ) as $plugin ) {
            $this->_delete( $plugin );
            $assoc_args['force'] = 1;
            $this->install( array( $plugin->name ), $assoc_args );
        }
    }
    ...
}
```
I think the existence of the plugin should be checked in the case that it doesn't exist.

**Comment by szepeviktor** [comment]
What is your actual command and error message?

**Comment by szepeviktor** [comment]
Could you tell us whether wp-cli shows that an update is available?

**Comment by pczupil** [comment]
actual command: wp plugin update wp-checkout --version=1.8.9
wp does show that that plugin update is not available

**Comment by szepeviktor** [comment]
Does `wp-checkout` have a build-in update mechanism?

**Comment by danielbachhuber** [comment]
> I think the existence of the plugin should be checked in the case that it doesn't exist.

This assumption seems reasonable to me.
