### ISSUE TITLE
Generation of .htaccess fails silently if .yml file not set correctly

### ISSUE THREAD

**Issue by elimc** [wp-cli/wp-cli#1952]
Users have to use the following code to generate an .htaccess file:

```bash
apache_modules:
	- mod_rewrite
```

However, if a dev doesn't know this, they will be confused when trying to set permalinks and then failing. Is there a way to generate an error in the console when this failure happens?

**Comment by danielbachhuber** [comment]
> Is there a way to generate an error in the console when this failure happens?

This is the error I get:

```
salty-wordpress ➜  fusion-2015  wp rewrite flush --hard
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
```

Do you not get similar?

**Comment by szepeviktor** [comment]
Duplicate: https://github.com/wp-cli/wp-cli/issues/1884

**Comment by elimc** [comment]
@danielbachhuber I just tried my script with an incorrect config.yml and was somehow able to generate a functional site with an .htaccess file. I don't know how this was able to occur.

I have quite a script setup. You can check it out here if you want to mess with it: https://github.com/elimc/jumpstart-install-script
