### ISSUE TITLE
WP-CLI Truck Factor

### ISSUE THREAD

**Issue by gavelino** [wp-cli/wp-cli#1953]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **WP-CLI** and obtained a value of **1**.

The developer responsible for this TF is:

Cristi Burcă (scribu) - author of 78% of the files 

To validate our results, we would like to ask **WP-CLI** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **WP-CLI**?

(b) Do you agree that **WP-CLI** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(b) Does **WP-CLI** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by danielbachhuber** [comment]
> (a) Do you agree that the listed developer is the main developer of WP-CLI?

Conceptually, yes. However, Cristi passed along maintainership [a year ago](http://wp-cli.org/blog/new-maintainer-daniel-bachhuber.html).

> (b) Do you agree that WP-CLI will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

Nope. Project seems to be fine from my perspective.

> (b) Does WP-CLI have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

N/A. The project is pretty well-documented.

**Comment by gavelino** [comment]
Hi Daniel,

Thank you for your answer.
