### ISSUE TITLE
Include script to deploy plugin to WordPress.org

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1955]
Is it a good idea to add `wp scaffold plugin-deploy`? Maybe it could be a shell script.

http://scribu.net/blog/deploying-from-git-to-svn.html

**Comment by danielbachhuber** [comment]
Could be a good idea. @rmccue added something similar to WP-API recently: https://github.com/WP-API/WP-API/blob/develop/bin/release.sh

**Comment by szepeviktor** [comment]
OK. I make up a criteria list and write a failure-tolerant bash script that does it.
BTW. `if [[ $VERSION == "v*" ]]; then` doesn't do its job.

**Comment by danielbachhuber** [comment]
Here's another script: https://github.com/mikejolley/github-to-wordpress-deploy-script

**Comment by danielbachhuber** [comment]
At this point, this isn't something that makes sense to include in WP-CLI core. I'd [love to see](https://runcommand.io/for/release-plugin-wordpress-org/) a community command that implements this functionality though, with comprehensive tests.

**Comment by szepeviktor** [comment]
It could have hooks: `$hook_name_$plugin_slug`.
