### ISSUE TITLE
WP core under git control

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#1957]
I happen to keep core under git control, from GitHub.
While I'm doing `git checkout 4.2.3 && wp core update-db` how could I put WP into maintenance mode?

**Comment by danielbachhuber** [comment]
Hm, doesn't seem like it's easily possible:

```
salty-wordpress ➜  wordpress-develop.dev  wp eval "require_once( ABSPATH . 'wp-admin/includes/upgrade.php' ); WP_CLI\Utils\get_upgrader( 'WP_CLI\NonDestructiveCoreUpgrader' )->maintenance_mode( true );"
PHP Fatal error:  Call to a member function abspath() on a non-object in /srv/www/wordpress-develop.dev/src/wp-admin/includes/class-wp-upgrader.php on line 717
```

Even with that hacky statement, it looks like `$wp_filesystem` isn't instantiated.

**Comment by szepeviktor** [comment]
Thank you for your effort.

**Comment by szepeviktor** [comment]
Maybe I hack the maintenance PHP file in the root dir.
