### ISSUE TITLE
How to write tests for wp-cfm?

### ISSUE THREAD

**Issue by mortona42** [wp-cli/wp-cli#1958]
Hey, I'm working on wp-cfm, over at https://github.com/forumone/wp-cfm.  I'd like to write up some test cases for the plugin - for example creating/saving/loading config with different arguments and validating the db storage or file changes.

I'm looking at the documentation for contributing to wp-cli, and I'm not understanding how to set up my test environment.  I think I want to start with behat functional tests - the .feature files in wp-cli looks like what I'm trying to achieve.  However, I'm stuck on step 1 of https://github.com/wp-cli/wp-cli/wiki/Package-Functional-Tests.  Running wp scaffold package-tests . from within my plugin directory says I'm missing a composer.json file.

According to https://github.com/wp-cli/wp-cli/wiki/Commands-Cookbook, this plugin should either have a composer.json file, or I'd have to specify --require=/path/to/wp-cfm in order to run the functions, however the commands are working for me just by having the plugin installed.

What am I missing here?  Do I need to convert the plugin to a community package, and create a composer.json file in order to run tests?  Am I going about this the right way?

**Comment by danielbachhuber** [comment]
> Running wp scaffold package-tests . from within my plugin directory says I'm missing a composer.json file.

Can you share the exact output of your command execution?

**Comment by mortona42** [comment]
Thanks for a fast response!  Here's what I'm seeing:

[vagrant@localhost wp-cfm]$ wp scaffold package-tests .
Error: Invalid package directory. composer.json file must be present.
[vagrant@localhost wp-cfm]$ wp scaffold package-tests /vagrant/public/wp-content/plugins/wp-cfm/
Error: Invalid package directory. composer.json file must be present.
[vagrant@localhost wp-cfm]$ pwd
/vagrant/public/wp-content/plugins/wp-cfm
[vagrant@localhost wp-cfm]$

**Comment by mortona42** [comment]
I created a composer.json file containing:

    "autoload": {
        "files": [ "includes/class-wp-cli.php" ]
    }

Now the scaffold command works.  Then I installed behat using composer (added it the composer.json file).  Now the default test is working.


Here's where I'm stuck now:

    [vagrant@localhost wp-cfm]$ ./vendor/behat/behat/bin/behat
    PHP Fatal error:  Class 'WP_CLI_Command' not found in /vagrant/public/wp-content/plugins/wp-cfm/includes/class-wp-cli.php on line 7

**Comment by danielbachhuber** [comment]
@mortona42 Sorry for the late reply. Did you get this sorted out?

**Comment by jarednova** [comment]
@danielbachhuber I'm having the same issue as @mortona42. I tried adding the file to my autoload as he suggested with...

```json
  "autoload": {
    "files": [ "vendor/wp-cli/wp-cli/php/class-wp-cli.php" ]
  },
```
But when running tests I get:

```sh
PHP Fatal error:  Call to a member function error() on a non-object in /srv/www/timber/vendor/wp-cli/wp-cli/php/class-wp-cli.php on line 256

Fatal error: Call to a member function error() on a non-object in /srv/www/timber/vendor/wp-cli/wp-cli/php/class-wp-cli.php on line 256
```

I've tried autoloading `/vendor/wp-cli/wp-cli/php/wp-cli.php` but got this error:

```sh
Fatal error: Call to undefined function WP_CLI\Utils\load_dependencies() in /srv/www/timber/vendor/wp-cli/wp-cli/php/wp-cli.php on line 18
```

**Comment by danielbachhuber** [comment]
@mortona42 @jarednova Could one of you share a branch I can check out to reproduce locally?

Just so it's stated, I only ever tested `wp scaffold package-tests` against a standalone WP-CLI command (e.g. [Dictator](https://github.com/danielbachhuber/dictator))

```
[vagrant@localhost wp-cfm]$ ./vendor/behat/behat/bin/behat
PHP Fatal error:  Class 'WP_CLI_Command' not found in /vagrant/public/wp-content/plugins/wp-cfm/includes/class-wp-cli.php on line 7
```

This means `includes/class-wp-cli.php` is loading before WP-CLI is actually loaded.

`install-package-tests.sh`, which is run by Travis, calls `set_package_context()` ([ref](https://github.com/danielbachhuber/dictator/blob/master/bin/install-package-tests.sh#L17)). This sets up a `config.yml` file to load your custom command for the Behat tests, which means WP-CLI will be loading the command far _after_ Composer has done its thing.
