### ISSUE TITLE
Allow subclassing/overriding the WP_Import class

### ISSUE THREAD

**Issue by rmccue** [wp-cli/wp-cli#1959]
Right now, wp-cli manually creates a new instance of the `WP_Import` class. This doesn't obey whatever's registered via `register_importer`, which is super annoying if you need to subclass the importer.

In addition, the methods are all declared `private`, so if you want to make your own custom import command, you can't simply subclass and override. `protected` would be mucho better here.

**Comment by danielbachhuber** [comment]
What are you trying to do?

**Comment by szepeviktor** [comment]
He must have a

> custom import command

**Comment by rmccue** [comment]
Trying to subclass `WP_Import` :)

We need to subclass to handle some edge cases on import that can't be handled via filters (aka bugs in WP Importer), so I'm subclassing and replacing the globally registered importer with our own instance (both in `$GLOBALS['wp_import']` and `register_importer`). Works fine in the UI, but not in wp-cli.

**Comment by danielbachhuber** [comment]
> This doesn't obey whatever's registered via register_importer, which is super annoying if you need to subclass the importer.

It seems like we should fix this.

> In addition, the methods are all declared private, so if you want to make your own custom import command, you can't simply subclass and override. protected would be mucho better here.

Which methods do you need to subclass?

**Comment by rmccue** [comment]
> Which methods do you need to subclass?

Specifically to work around this, I'd have liked to subclass `Import_Command` to override just the bit that instantiates the class. The `private`s littered around make it hard to subclass.

(In general, I think it's good practice to avoid `private` in favour of `protected` anyway.)

**Comment by danielbachhuber** [comment]
wontfix for this issue, actually. `register_importer()` registers a dispatch callback, which isn't compatible with WP-CLI's implementation of the importer.

And, given WP-CLI has a very custom implementation of the importer, I'm not keen to support one-off extensions of it. WordPress import / export generally needs to be rewritten from the ground up
