### ISSUE TITLE
Implement wp_defer_term_counting()

### ISSUE THREAD

**Issue by dougaxe1** [wp-cli/wp-cli#1960]
Batch post and term operations could be sped up significantly by enabling [wp_defer_term_counting()](http://codex.wordpress.org/Function_Reference/wp_defer_term_counting). A new `--defer_term_counting` flag could enable this performance increase.

````
wp post delete $(wp post list --post_type='page' --format=ids) --force --defer_term_counting
````

````php
	/**
	 * Delete a post by ID.
	 *
	 * ## OPTIONS
	 *
	 * <id>...
	 * : One or more IDs of posts to delete.
	 *
	 * [--force]
	 * : Skip the trash bin.
	 *
	 * [--defer-term-counting]
	 * : Defers term counting until all posts are deleted
	 *
	 * ## EXAMPLES
	 *
	 *     wp post delete 123 --force
	 *
	 *     wp post delete $(wp post list --post_type='page' --format=ids)
	 *
	 *     # delete all posts in the trash
	 *     wp post delete $(wp post list --post_status=trash --format=ids)
	 *
	 *     wp post delete $(wp post list --post_type='page' --format=ids) --force --defer_term_counting
	 */
	public function delete( $args, $assoc_args ) {
		$defaults = array(
			'force' => false,
			'defer_term_counting' => false
		);
		$assoc_args = array_merge( $defaults, $assoc_args );

		if ( $assoc_args['defer_term_counting'] ) { wp_defer_term_counting(true); }
		
		parent::_delete( $args, $assoc_args, function ( $post_id, $assoc_args ) {
			$status = get_post_status( $post_id );
			$r = wp_delete_post( $post_id, $assoc_args['force'] );

			if ( $r ) {
				$action = $assoc_args['force'] || 'trash' === $status ? 'Deleted' : 'Trashed';

				return array( 'success', "$action post $post_id." );
			} else {
				return array( 'error', "Failed deleting post $post_id." );
			}
		} );

		if ( $assoc_args['defer_term_counting'] ) { wp_defer_term_counting(false); }
	}
````

Thanks to @davideve for pointing out this performance bottleneck.

I can create a pull request for this at some point in the future, but I just wanted to put this out there to see if someone else was interested in implementing. Or in case this is a bad idea.

**Comment by danielbachhuber** [comment]
> Batch post and term operations could be sped up significantly

Do you have any numbers to share?

And, just to be clear, this means term counts will be incorrect after the operation?

**Comment by dougaxe1** [comment]
The term counts would be up to date at the end of the run. `wp_defer_term_counting(false)` will trigger the recount, but in batch (deduped) as opposed to each run. 

The term count _would be incorrect if the command was aborted_, hence the flag requiring opt-in.

I don't know if I would get to it this soon, but working on a PR I could run some benchmarks.

**Comment by danielbachhuber** [comment]
> `wp_defer_term_counting(false)` will trigger the recount, but in batch (deduped) as opposed to each item.

Great.

> I don't know if I would get to it this soon, but working on a PR I could run some benchmarks.

:+1:
