### ISSUE TITLE
Import command accidentally uses double the memory it needs

### ISSUE THREAD

**Issue by rmccue** [wp-cli/wp-cli#1963]
In `commands/import.php`, the file you pass in is [parsed into an array](https://github.com/wp-cli/wp-cli/blob/47ca6f9e15b0eb078aad9a8485d663f5de4bf4a7/php/commands/import.php#L72), and this data is used [to work out the users](https://github.com/wp-cli/wp-cli/blob/47ca6f9e15b0eb078aad9a8485d663f5de4bf4a7/php/commands/import.php#L77). After this, `$import_data` is not used again. For large imports, this can be hundreds of MB in the data array.

In `$wp_import->import( $file )`, `parse` is internally called again, which generates this array again. This means that for a file that might be ~100MB once parsed, you're actually using double this with 200MB, since the same array is loaded twice. (The two are generated separately, so copy-on-write doesn't apply.)

**Comment by blobaugh** [comment]
Thank you Ryan!!!! This has bitten me several times :)
