### ISSUE TITLE
Error: The requested locale (sv_SE) was not found.

### ISSUE THREAD

**Issue by vietzon** [wp-cli/wp-cli#1965]
Hi,

I just ran this cmd from my server and it's not working anymore

wp core download --locale=sv_SE
Error: The requested locale (sv_SE) was not found.

**Comment by danielbachhuber** [comment]
WordPress 4.2.4 was just released, so you may have hit the edge case where the locale build hadn't been created yet. I just ran the command, and it works for me:

```
salty-wordpress ➜  wp-se.dev  wp core download --locale=sv_SE
Downloading WordPress 4.2.4 (sv_SE)...
Success: WordPress downloaded.
```

Can you try again?

**Comment by vietzon** [comment]
Yeah, it does work now :+1: 

Cheers
