### ISSUE TITLE
Specifying multiple IDs in `wp post meta`

### ISSUE THREAD

**Issue by montchr** [wp-cli/wp-cli#1967]
I would like to bulk add a meta field to a group of posts. Is there a way to accomplish this without running the command for each individual ID?

Specifically, I'd like to take the output of `wp post list --format=ids` and feed into `wp post meta add` like so:

`wp post meta add $(wp post list --format=ids) meta_key meta_value`

I understand this might cause some issues with positional arguments, but even so, the command doesn't accept a list of comma-separated IDs either, instead only affecting the first post in the list.

**Comment by danielbachhuber** [comment]
> I understand this might cause some issues with positional arguments

Unfortunately, because `[<value>]` is already optional, we couldn't make this change without breaking backwards compatibility.

Consider this command:

```
wp post meta add 1 2 foo`
```

If we supported `<id>...`, WP-CLI could interpret this as "add 2=>foo to post 1" _or_ "add STDIN to meta key foo for posts 1 and 2". This ambiguity would be a bug.

> the command doesn't accept a list of comma-separated IDs either, instead only affecting the first post in the list.

I'm not a huge fan of the CSV approach, because it'd be inconsistent with our other command arguments.

**Comment by montchr** [comment]
> If we supported <id>..., WP-CLI could interpret this as "add 2=>foo to post 1" or "add STDIN to meta key foo for posts 1 and 2". This ambiguity would be a bug.

This makes sense.

> I'm not a huge fan of the CSV approach, because it'd be inconsistent with our other command arguments.

Inconsistent in the sense that no other command would support it? Or in some other way? If the former, why not add CSV support to other commands too?

**Comment by danielbachhuber** [comment]
> Inconsistent in the sense that no other command would support it? Or in some other way? If the former, why not add CSV support to other commands too?

Inconsistent in that other commands support multiple post IDs with `<id>...`

**Comment by danielbachhuber** [comment]
Closing in favor of #1784

REST API is the one true path forward for managing WP data.
