### ISSUE TITLE
wp-cli support for older versions of WordPress

### ISSUE THREAD

**Issue by a7127cff69cab32e5c4723e8446e21c4b7325dc** [wp-cli/wp-cli#1970]
wp-cli currently supports only WordPress versions 3.5.2 and above.  While I agree that helps to create new functionality and extends features beyond what would be possible with full backward compatibility, it would be helpful to have some functionality extend to earlier versions in order to facilitate upgrades to newer versions.

Are there some features that are required for any wp-cli operation at all, or can older versions enjoy some reduced functionality?

I would be happy to commit some development resources to this initiative, but would really like some insight into the challenges that may need to be solved, as well as some direction in order to contribute meaningfully to wp-cli.

**Comment by danielbachhuber** [comment]
> wp-cli currently supports only WordPress versions 3.5.2 and above. While I agree that helps to create new functionality and extends features beyond what would be possible with full backward compatibility, it would be helpful to have some functionality extend to earlier versions in order to facilitate upgrades to newer versions.

Ultimately, it's about maintenance burden, and the resources we have available to shoulder the maintenance burden (e.g. me). I've actually been considering increasing the minimum supported version to WP 4.0 or so.

> Are there some features that are required for any wp-cli operation at all, or can older versions enjoy some reduced functionality?

Here's when minimum supported version was bumped to 3.5.2 #1004

For the purposes of upgrading, you can use `wp core download --force`:

```
salty-wordpress ➜  test-dir  wp core download --force --version=2.8
Downloading WordPress 2.8 (en_US)...
Success: WordPress downloaded.
```

For other subcommands, you could also try WP-CLI < v0.11.0 (when the version check was introduced #567). However, it appears there were some problems with the loader process when this was last attempted #593
