### ISSUE TITLE
Fatal PHP Error: cannot redeclare CLI\Render()

### ISSUE THREAD

**Issue by Soben** [wp-cli/wp-cli#1971]
Similar to https://github.com/wp-cli/wp-cli/issues/1717

However, the issue was that I had a composer-based plugin using Twig in my mu-plugins folder... which conflicts with this... Might be a good idea to figure out how to prevent this moving forward in the future...

I'm not sure if it's something that needs to be fixed on your end of things, or just better programming practices as a whole, but I figured I would send this your way.

```
$ wp core install
Fatal error: Cannot redeclare cli\render() (previously declared in phar:///usr/local/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/cli.php:26) in /Users/chris/Sites/wordpress/wp-content/mu-plugins/timber/vendor/wp-cli/php-cli-tools/lib/cli/cli.php on line 28
```

In the meantime I just deleted the Timber plugin as I hadn't actually started development with it yet.

**Comment by szepeviktor** [comment]
Are you using wp-cli from your mu-plugin?

**Comment by Soben** [comment]
No, Twig/Timber is using it, that's where the issue lied. This post was more of an "informative" thing.

Thankfully, in my case, it was a non issue as Timber was entirely set up as a experiment, so I didn't need it, and I wasn't concerned with it conflicting. I just removed Timber/Twig.

Twig/Timber were using Composer and CLI... and tried declaring cli\render() too, which causes this conflict.

**Comment by danielbachhuber** [comment]
Oh, Timber has WP-CLI as a dependency: https://github.com/jarednova/timber/blob/c27c1f8e35a4765219e056ad157bdf3da655ee13/composer.json#L36

We can't solve this problem with WP-CLI, so we'll need to solve it with Timber https://github.com/jarednova/timber/issues/687
