### ISSUE TITLE
Homebrew undefined method `desc' for WpCli:Class

### ISSUE THREAD

**Issue by tvahey** [wp-cli/wp-cli#1973]
Tried to install on Mac OSX 10.9.5.

Got this error:

brew install homebrew/php/wp-cli
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 10336, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 10336 (delta 25), reused 0 (delta 0), pack-reused 10291
Receiving objects: 100% (10336/10336), 2.12 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (7011/7011), done.
Checking connectivity... done.
Tapped 502 formulae
Error: undefined method `desc' for WpCli:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/wp-cli.rb:2:in `<class:WpCli>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/wp-cli.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:185:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:131:in `<main>'

**Comment by szepeviktor** [comment]
@danielbachhuber Maybe missing this line
```ruby
require File.expand_path("../../Requirements/php-meta-requirement", __FILE__)
```
Compare:
https://github.com/homebrew/homebrew-php/blob/master/Formula/wp-cli.rb
https://github.com/Homebrew/homebrew-php/blob/master/Formula/drush.rb

**Comment by szepeviktor** [comment]
@tvahey When googling for the error message: `Homebrew undefined method `desc'`
You''l find that the first result is https://github.com/Homebrew/homebrew/issues/41882

Please try `brew update`.

**Comment by szepeviktor** [comment]
To escape the backtick:

```md
``Homebrew undefined method `desc'``
```

**Comment by tvahey** [comment]
brew update seems to have fixed this issue.

But, I updated brew and got a different error message.
==> Installing wp-cli from homebrew/homebrew-php
composer: Missing PHP53, PHP54, PHP55, PHP56, PHP70 from homebrew-php. Please install one of them before continuing

FYI - I'm running MAMP 3.0.7.3. I'll update to MAMP 3.4. 

Consider this issue closed. I'll open a new issue if there are further problems.
