### ISSUE TITLE
WP-CLI - Core WP directory accessed via symlink 

### ISSUE THREAD

**Issue by gegere** [wp-cli/wp-cli#1974]
Is it possible to use WP-CLI with a Skeleton WordPress install?

I am following [this guide](http://www.htmlgraphic.com/symlinking-wordpress-core-files-wordpress-skeleton/).

**Comment by danielbachhuber** [comment]
> Is it possible to use WP-CLI with a Skeleton WordPress install?

Should be. What error do you get when you try to run WP-CLI?

**Comment by gegere** [comment]
This is the error message by having a symlinked `wp` directory.

```
$ wp plugin list --allow-root
Error: Strange wp-config.php file: wp-settings.php is not loaded directly.
```

**Comment by gegere** [comment]
Here is a simple way to produce this issue and move it along quicker.

```
https://github.com/wp-cli/wp-cli/issues/1974#
mkdir ~/temp && cd temp
git clone https://github.com/markjaquith/WordPress-Skeleton.git wordpress && cd wordpress
git submodule update --init --recursive
wp plugins list --allow-root
```
**This works, let's say I edit the database credentials, everything will work correctly.**

**Move WordPress Core back a directory**
`mv wp ../`

**Symlink the directory**
`ln -s ~/temp/wp wp`

**wp-config.php needs to point to the correct one**
`echo '<?php include_once("${_SERVER['DOCUMENT_ROOT']}/wp-config.php");' >> wp/wp-config.php`

`wp plugins list --allow-root`

**This does NOT work**
$ "**Error:** Strange wp-config.php file: wp-settings.php is not loaded directly."

**Comment by danielbachhuber** [comment]
`$_SERVER['DOCUMENT_ROOT']` isn't set at the command line. See: https://github.com/wp-cli/wp-cli/issues/785#issuecomment-138040347
