### ISSUE TITLE
Corresponding number in plugin/theme list for commands.

### ISSUE THREAD

**Issue by tw2113** [wp-cli/wp-cli#1975]
If this is possible, it'd be an awesome enhancement.

Take for example the theme list here:

```
+----------------+----------+--------+---------+
| name           | status   | update | version |
+----------------+----------+--------+---------+
| twentyeleven   | inactive | none   | 2.2     |
| twentyfifteen  | active   | none   | 1.3     |
| twentyfourteen | inactive | none   | 1.5     |
| twentyten      | inactive | none   | 2.0     |
| twentythirteen | inactive | none   | 1.6     |
| twentytwelve   | inactive | none   | 1.8     |
+----------------+----------+--------+---------+
```
If I wanted to act on one/many of them, I have to provide the name for each. While not horrible, it'd be awesome if a corresponding number was provided as an alias. The number would start from 1 for the first one, and increment until no more to list. Our example above would be 1 through 6. If I wanted to delete twentyeleven and twentyten, normally I have to do `wp theme delete twentyeleven twentyten` or so on. With the aliased numbers, I'd be able to switch that to `wp theme delete 1 4` based on the list above.

**Comment by danielbachhuber** [comment]
> While not horrible, it'd be awesome if a corresponding number was provided as an alias.

Why would this be useful? How should this work if you could have a theme called `1`?

**Comment by szepeviktor** [comment]
> How should this work if you could have a theme called 1

:laughing:

**Comment by szepeviktor** [comment]
@tw2113 
```
wp theme list --field=name | sed -n '1p;4p' | xargs wp theme delete
```

**Comment by tw2113** [comment]
@danielbachhuber it wouldn't be named "1", the number would just correspond to the same position in the list so that someone could type "1" instead of "longer-theme-name"

**Comment by danielbachhuber** [comment]
I don't think this is a good idea, sorry.
