### ISSUE TITLE
Unable to run install 

### ISSUE THREAD

**Issue by emersonthis** [wp-cli/wp-cli#1977]
I'm following the setup/install instructions. I got `wp scaffold plugin-tests my-plugin` to run. But then at the next step when I try to run `bash bin/install-wp-tests.sh wordpress_test root '' localhost latest` I get the following error:

```
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to MySQL server on 'localhost' (61)'
Check that mysqld is running on localhost and that the port is 3306.
You can check this by doing 'telnet localhost 3306'
```

My local Wordpress site is running with MAMP (which is working). I'm not sure if that's relevant for the install script since I think it's creating a temporary DB to run the tests... Does it matter if it uses the built-in OSX mysql or MAMP's MySQL?

Here's the output from `wp --info`

```
$ ./vendor/wp-cli/wp-cli/bin/wp --info
PHP binary:	/Applications/MAMP/bin/php/php5.6.10/bin/php
PHP version:	5.6.10
php.ini used:	/Applications/MAMP/bin/php/php5.6.10/conf/php.ini
WP-CLI root dir:	/Applications/MAMP/htdocs/pipeline/wp-content/plugins/wp-github-pipeline/vendor/wp-cli/wp-cli
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.19.2
```

**Comment by emersonthis** [comment]
Interestingly, this works just fine:
```
$ ./wp-content/plugins/wp-github-pipeline/vendor/wp-cli/wp-cli/bin/wp plugin list
+--------------------+--------+--------+---------+
| name               | status | update | version |
+--------------------+--------+--------+---------+
| wp-github-pipeline | active | none   | 0.1.0   |
+--------------------+--------+--------+---------+
```

**Comment by emersonthis** [comment]
After a lot of trial and error, the install script works, but then when I run `phpunit` I get...

```
$ phpunit
PHP Warning:  mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: NO) in /private/tmp/wordpress/wp-includes/wp-db.php on line 1452
PHP Stack trace:
PHP   1. {main}() /private/tmp/wordpress-tests-lib/includes/install.php:0
PHP   2. require_once() /private/tmp/wordpress-tests-lib/includes/install.php:21
PHP   3. require_wp_db() /private/tmp/wordpress/wp-settings.php:79
PHP   4. wpdb->__construct() /private/tmp/wordpress/wp-includes/load.php:350
PHP   5. wpdb->db_connect() /private/tmp/wordpress/wp-includes/wp-db.php:649
PHP   6. mysqli_real_connect() /private/tmp/wordpress/wp-includes/wp-db.php:1452

Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: NO) in /private/tmp/wordpress/wp-includes/wp-db.php on line 1452
```

I'm attempting to follow the exact instructions [here](https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests).

**Comment by danielbachhuber** [comment]
Sorry for the late reply here.

> My local Wordpress site is running with MAMP (which is working). I'm not sure if that's relevant for the install script since I think it's creating a temporary DB to run the tests... Does it matter if it uses the built-in OSX mysql or MAMP's MySQL?

It's only relevant in as so far as the `root` user actually has access to create and delete tables for the MySQL instance running on `localhost`. In this case, your root user has a non-blank password, which means it can't create and delete tables using the default setup instructions.

You can track down the password for `root` user at local host or, probably better, use the credentials you use for your MySQL instance running in MAMP.

**Comment by emersonthis** [comment]
@danielbachhuber Thanks for the clarification. I had actually switched it so everything was running on the MAMP (mysql, php, etc). But the gotcha was that I had already run the install script with the OSX mysql credentials. I re-ran it again, but it took me a long time realize that the install script won't overwrite existing files. Right? So I **thought** I was starting over but I wasn't. After I manually edited the `wp-config.php` to use the right DB credentials, it worked perfectly.

Is this the expected behavior of the installation script? Do you want a PR mentioning this in the docs?

**Comment by danielbachhuber** [comment]
> Is this the expected behavior of the installation script?

Yep.

> Do you want a PR mentioning this in the docs?

Sure, seems reasonable.
