### ISSUE TITLE
Support "no-content" and "new-bundled" options

### ISSUE THREAD

**Issue by roikles** [wp-cli/wp-cli#1978]
Feature request: I think it would be very beneficial if there was an option for `core install` and `core update` to install the no_content_download that WordPress offer via the API.

**Comment by danielbachhuber** [comment]
Seems reasonable.

**Comment by szepeviktor** [comment]
:+1:

**Comment by danielbachhuber** [comment]
Going to pass on this. It doesn't appear there are `no-content` packages for all versions, locales, and archive file types. Our logic within `Core_Command->download()` is already quite complex, so I don't think it's worth the effort to write tests around all of the additional complexity.
