### ISSUE TITLE
wp-cli-0.19.2 throws an odd exception

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#1979]
net4-dev# sudo -u $(which wp-cli.phar) core update
Updating to version 4.2.4 (en_US)...
PHP Warning:  mkdir(): Permission denied in phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php on line 265
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->after_wp_load() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:34
PHP   5. WP_CLI\Runner->_run_command() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:705
PHP   6. WP_CLI\Runner->run_command() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:311
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:304
PHP   8. call_user_func:{phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295
PHP  10. call_user_func:{phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  11. Core_Command->update() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  12. Core_Upgrader->upgrade() phar:///david-favor/tools/wp-cli.phar/php/commands/core.php:940
PHP  13. WP_CLI\CoreUpgrader->download_package() /sites/kb/howtoreducemydebtnow.com/wordpress/wp-admin/includes/class-wp-upgrader.php:2014
PHP  14. WP_CLI::get_cache() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/CoreUpgrader.php:39
PHP  15. WP_CLI\FileCache->__construct() phar:///david-favor/tools/wp-cli.phar/php/class-wp-cli.php:79
PHP  16. WP_CLI\FileCache->ensure_dir_exists() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php:56
PHP  17. mkdir() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php:265
Success: WordPress updated successfully.

This looks like some artifact from when wp-cli was packaged as many files.

If wp-cli.phar is installed, per http://wp-cli.org instructions, there is only a single file.

Hence, there is no - /david-favor/tools/wp-cli.phar/php/... files - which is why exception is being thrown.

Let me know the best way to work around this.

Maybe just run from a "git clone" till this is fixed...

**Comment by szepeviktor** [comment]
PHP sees a `phar` file as a mounted filesystem.
I think your cache directory cannot be written. Try setting WP_CLI_CACHE_DIR
```bash
export 
```
As for `sudo -u $(which wp-cli.phar) core update`
`-u` needs a user name and it is useful to provide `--` also.
I suggest you to install wp-cli in you local `bin` directory under the name `wp`.
```
wget -O/usr/local/bin/wp https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x /usr/local/bin/wp
```
For switching user see my [script](https://github.com/szepeviktor/debian-server-tools/blob/master/tools/uwp):
```bash
THIS_OWNER="$(stat . -c %U)"

sudo -u "$THIS_OWNER" --  wp --path="$(pwd)" "$@"
```

**Comment by danielbachhuber** [comment]
Thanks for your help with this, @szepeviktor
