### ISSUE TITLE
Make update work with NGINX

### ISSUE THREAD

**Issue by mikeschinkel** [wp-cli/wp-cli#1980]
A comment on my blog said this:

http://mikeschinkel.com/blog/17-reasons-wordpress-is-a-better-cms-than-drupal/#comment-567725

> _I recently tried to update WP via command line, since I am using Nginx the core update doesn’t work from my WP backend.  Unfortunately, the WP-CLI tool doesn’t work that simple. In fact, it doesn’t work at all._

I do not have NGINX admin skill so do not use it, but if this is true it would be great if it could be fixed.

**Comment by TheLastCicada** [comment]
I use Nginx on many many sites and have never had a problem updating WordPress with wp-cli.  'wp core update' works fine.  Have never had any issue with any wp-cli command and Nginx compatibility.

**Comment by mikeschinkel** [comment]
@TheLastCicada Thanks for the follow up.

**Comment by TheLastCicada** [comment]
If you have any further details I can provide a more focused answer.  Seems like a specific configuration issue to me.
