### ISSUE TITLE
wp rewrite structure 'structure' --hard does not update .htaccess on fresh install

### ISSUE THREAD

**Issue by Yanchek99** [wp-cli/wp-cli#1981]
Repro Steps:

1. Use wp-cli to download and install wordpress.
2. Create touch an .htaccess file in the install path for wordpress (gave it 777 permissions just for simplicity)
3. Run `wp rewrite structure 'structure' --hard`
4. less the .htaccess file and note that there is no rewrite rules. 

The .htaccess file is only populated after logging in to the wp-admin and viewing the permalink settings.  PS. You will notice that a custom permalink structure is set as defined. So the command is updating the db just not the .htaccess file

**Comment by danielbachhuber** [comment]
Did you follow the [configuration instructions](http://wp-cli.org/commands/rewrite/flush/)?

**Comment by Yanchek99** [comment]
@danielbachhuber Yes 
```
apache_modules:
  - mod_rewrite
```
Is declared in` ~/.wp-cli/config.yml`

**Comment by danielbachhuber** [comment]
Can you share the full output of command execution?

**Comment by Yanchek99** [comment]
Sure thing, the weird part is the output looks successful. 

```
user@ubuntu:~$ more /var/www/html/wordpress/.htaccess 
user@ubuntu:~$ wp rewrite structure '/%category%/%postname%/' --hard
Success: Rewrite structure set.
user@ubuntu:~$ more /var/www/html/wordpress/.htaccess
```

**Comment by danielbachhuber** [comment]
Hm. I just tested on my Webfaction instance, and it worked fine:

```
web129.webfaction.com ➜  dbcom  wp option get permalink_structure
/%year%/%monthnum%/%day%/%postname%/
web129.webfaction.com ➜  dbcom  rm .htaccess
web129.webfaction.com ➜  dbcom  wp rewrite structure '/%year%/%monthnum%/%day%/%postname%/' --hard
Success: Rewrite structure set.
web129.webfaction.com ➜  dbcom  cat .htaccess

# BEGIN WordPress
<IfModule mod_rewrite.c>

RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

WP-CLI calls `flush_rewrite_rules()`, which calls `WP_Rewrite::flush_rules()`: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/rewrite.php#L2178

It appears there are a couple cases in which rewrites wouldn't actually get created:

1. You have a filter on `flush_rewrite_rules_hard` somewhere in your codebase.
2. `save_mod_rewrite_rules()` is missing from your server (disabled or otherwise)

But, neither of these cases explain why it works in the admin.

Just to be clear, the `.htaccess` file gets created, but is empty?

**Comment by Yanchek99** [comment]
@danielbachhuber Initially there was a blank .htaccess file that was created by me using touch.  This was to ensure the file had the proper file owner/group permissions.  Then the wp-cli command was run to overwrite that file.  I just tried removing it and running wp-cli to see if it would create the file but had no luck.  Note: When .htaccess does not exist I can not update it through the UI.  There needs to be a blank file with the correct permissions in order for me to update with UI.

```
user@ubuntu:~$ more /var/www/html/wordpress/.htaccess
/var/www/html/wordpress/.htaccess: No such file or directory
user@ubuntu:~$ wp rewrite structure '/%year%/%monthnum%/%day%/%postname%/' --hard
Success: Rewrite structure set.
user@ubuntu:~$ more /var/www/html/wordpress/.htaccess
/var/www/html/wordpress/.htaccess: No such file or directory
```

**Comment by rodrigoprimo** [comment]
Are you testing this on a multisite install? If so, see #2017.

**Comment by Yanchek99** [comment]
@rodrigoprimo No this is just on a single site install.

**Comment by chrisbloom7** [comment]
Same issue on a single site install. The rewrite command does not generate a .htaccess file. I also tried using `touch` to create an empty one first, but rewrite still doesn't update it. Using `--debug` on the command doesn't show anything irregular.

    $ wp cli info
    PHP binary:	/usr/bin/php5
    PHP version:	5.5.29-1+deb.sury.org~precise+3
    php.ini used:	/etc/php5/cli/php.ini
    WP-CLI root dir:	phar://wp-cli.phar
    WP-CLI global config:	/home/vagrant/.wp-cli/config.yml
    WP-CLI project config:	
    WP-CLI version:	0.20.1
    $ cat /home/vagrant/.wp-cli/config.yml
    color: true
    path: /var/www/html
    apache_modules:
      - mod_rewrite
    $ cat /var/www/html/.htaccess 
    $ ls -l /var/www/html/.htaccess 
    -rwxr-xr-x 1 vagrant vagrant 0 Sep 24 14:36 /var/www/html/.htaccess
    $ wp rewrite structure "/%year%/%monthnum%/%postname%" --hard --tag-base=tags --category-base=topics --debug
    Success: Rewrite structure set.
    $ cat /var/www/html/.htaccess 
    $ ls -l /var/www/html/.htaccess 
    -rwxr-xr-x 1 vagrant vagrant 0 Sep 24 14:36 /var/www/html/.htaccess

This is on a fresh install of WP using

**Comment by chrisbloom7** [comment]
Just noticed that this seems to work:

    wp rewrite structure "/%year%/%monthnum%/%postname%" --hard --tag-base=tags --category-base=topics
    wp rewrite flush --hard

So the extra `flush --hard` is necessary. Shouldn't `structure --hard` do that on its own though?

**Comment by danielbachhuber** [comment]
> Shouldn't structure --hard do that on its own though?

It does for me locally:

```
salty-wordpress ➜  wordpress-test.dev  rm .htaccess
salty-wordpress ➜  wordpress-test.dev  wp rewrite structure "/%year%/%monthnum%/%postname%" --hard --tag-base=tags --category-base=topics
Success: Rewrite structure set.
salty-wordpress ➜  wordpress-test.dev  cat .htaccess

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

But, I'm actually testing on a VM without Apache. 

>  Using --debug on the command doesn't show anything irregular.

Yeah, `--debug` isn't very helpful right now. #1022

**Comment by danielbachhuber** [comment]
I'm not sure what this issue is, but it seems to be specific to your environment. Sorry I can't help further.

**Comment by davidfavor** [comment]
Same behavior occurs for me using wp-cli-0.22 where steps are...

wp core download
wp core config ...
wp core install ...
Verify site is working...
wp-cli.phar --allow-root rewrite structure '/%postname%' --hard

Resulting .htaccess file is empty.

Navigating to Settings + Save creates .htaccess correctly.

**Comment by danielbachhuber** [comment]
> Resulting .htaccess file is empty.

@davidfavor Per the [documentation](http://wp-cli.org/commands/rewrite/structure/), you need to add the following to a `wp-cli.yml` [config file](http://wp-cli.org/config/):

```
apache_modules:
  - mod_rewrite
```

**Comment by davidfavor** [comment]
Still not working for me. Steps taken...

lxc-rmt-lightweight-vivid# export WP_CLI_CONFIG_PATH=/david-favor/etc/wp-cli/wp-cli.yml

lxc-rmt-lightweight-vivid# cat $WP_CLI_CONFIG_PATH
apache_modules:
  - mod_rewritelxc-rmt-lightweight-vivid# cat $WP_CLI_CONFIG_PATH
apache_modules:
  - mod_rewrite

lxc-rmt-lightweight-vivid# wp-cli.phar --allow-root rewrite structure '/%postname%' --hard
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
Success: Rewrite structure set.

lxc-rmt-lightweight-vivid# cat .htaccess
cat: .htaccess: No such file or directory

**Comment by danielbachhuber** [comment]
If you get this error:

> Warning: Regenerating a .htaccess file requires special configuration. See usage docs.

It means your config.yml isn't being read properly.

Can you try including `wp-cli.yml` in the root directory of your WordPress install?

**Comment by davidfavor** [comment]
So export WP_CLI_CONFIG_PATH=... doesn't work as docs say... Guess I can symlink a common .yml file into every WordPress directory. I provide High Speed WordPress Hosting in LXC containers, so symlinking is complex.

Tested...

1) WP_CLI_CONFIG_PATH=... fails to work as stated in docs

2) wp-cli.yml in WordPress root directory works

Thanks.

**Comment by danielbachhuber** [comment]
> So export WP_CLI_CONFIG_PATH=... doesn't work as docs say...

Well, it does work generally. It just doesn't work in your environment, likely for an environment-specific reason.

Can you run `wp-cli.phar --allow-root rewrite structure '/%postname%' --hard --debug` and share the full result?

**Comment by davidfavor** [comment]
I've tried export WP_CLI_CONFIG_PATH + setting WP_CLI_CONFIG_PATH=... prior to command.

Neither of these work.

Environment variables are environment variables.

And bash is bash.

Difficult to imagine this is an environment problem.

Let me know if there's a way to debug what's occurring + I'll report my findings.

**Comment by danielbachhuber** [comment]
> Let me know if there's a way to debug what's occurring + I'll report my findings.

As I mentioned, please run `wp-cli.phar --allow-root rewrite structure '/%postname%' --hard --debug` and share the full result.

**Comment by davidfavor** [comment]
Oops. Missed the trailing --debug...

net4-dev# WP_CLI_CONFIG_PATH=/david-favor/etc/wp-cl wp-cli.phar --allow-root rewrite structure '/%postname%' --hard --debug
wp-cli/
net4-dev# WP_CLI_CONFIG_PATH=/david-favor/etc/wp-cli/wp-cli.yml wp-cli.phar --allow-root rewrite structure '/%postname%' --hard --debug
Debug: Using global config from WP_CLI_CONFIG_PATH env var: /david-favor/etc/wp-cli/wp-cli.yml (0.013s)
Debug: No project config found (0.015s)
Debug: ABSPATH defined: /sites/drf/fastseohosting.com/wordpress/ (0.027s)
Debug: Begin WordPress load (0.028s)
Debug: wp-config.php path: /sites/drf/fastseohosting.com/wordpress/wp-config.php (0.028s)
Debug: Loaded WordPress (0.319s)
Debug: Running command: rewrite structure (0.32s)
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.

Success: Rewrite structure set.
net4-dev# ln -s /david-favor/etc/wp-cli/wp-cli.yml
net4-dev# wp-cli.phar --allow-root rewrite structure '/%postname%' --hard --debug
Debug: No readable global config found (0.019s)
Debug: Using project config: /sites/drf/fastseohosting.com/wordpress/wp-cli.yml (0.02s)
Debug: ABSPATH defined: /sites/drf/fastseohosting.com/wordpress/ (0.038s)
Debug: Begin WordPress load (0.039s)
Debug: wp-config.php path: /sites/drf/fastseohosting.com/wordpress/wp-config.php (0.039s)
Debug: Loaded WordPress (0.292s)
Debug: Running command: rewrite structure (0.292s)
Success: Rewrite structure set.

**Comment by Stephen-Cronin** [comment]
I'll just chip in and say I get the same behaviour as @chrisbloom7 reported above: 
```
wp rewrite structure '%category%/%postname%' --hard
```
does not work on it own. The .htaccess file is not generated. However, when I follow that with:
```
wp rewrite flush --hard
```
it does generate successfully.

Setup info:
- I have the config.yml set up with mod_rewrite entry. 
- WP-CLI version: 0.23.0
- PHP version: 5.6.15
- Apache version: Apache/2.4.17 (Win32) OpenSSL/1.0.2d 
- Using XAMPP locally on Windows 8.1

**Comment by danielbachhuber** [comment]
I realized what the problem is.

When we use `WP_CLI::launch_self()` to spawn a new process, the environment variables (including `$HOME`) aren't persisted. This means `~/.wp-cli/config.yml` isn't loaded, and your `apache_mods` declaration is missed.

An immediate workaround is to create `wp-cli.yml` within your project with the `apache_mods` declaration.

We might also consider passing `WP_CLI_CONFIG_PATH` to the executed command, which I think is a reasonable assumption.

**Comment by Stephen-Cronin** [comment]
Hi @danielbachhuber ,

Unfortunately that doesn't fix the problem (for me at least).

With 0.23.0 `launch_self`passes this `$command` onto `launch`:
```
C:\xampp56\php\php.exe C:/SJCHD/Dev/!Sites/wp-cli/bin/../php/boot-fs.php rewrite flush   --hard
```
Var_dumping `$results` in `launch` shows it's failing because of a database connection error:
```
object(WP_CLI\ProcessRun)#441 (6) {
  ["stdout"]=>
  string(1) "
"
  ["stderr"]=>
  string(892) "Warning: mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\SJCHD\Dev\!Sites\wpa\wp-includes\wp-db.php on line 1489
Warning: mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: No such host is known.
 in C:\SJCHD\Dev\!Sites\wpa\wp-includes\wp-db.php on line 1489
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\SJCHD\Dev\!Sites\wpa\wp-includes\wp-db.php on line 1515
Warning: mysql_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\SJCHD\Dev\!Sites\wpa\wp-includes\wp-db.php on line 1515
Warning: mysql_connect(): php_network_getaddresses: getaddrinfo failed: No such host is known.  in C:\SJCHD\Dev\!Sites\wpa\wp-includes\wp-db.php on line 1515
Error: Error establishing a database connection
"
  ["return_code"]=>
  int(1)
  ["command"]=>
  string(95) "C:\xampp56\php\php.exe C:/SJCHD/Dev/!Sites/wp-cli/bin/../php/boot-fs.php rewrite flush   --hard"
  ["cwd"]=>
  NULL
  ["env"]=>
  array(0) {
  }
}
```

With 0.24.0-alpha, the passed $ command becomes:
```
WP_CLI_CONFIG_PATH="C:\Users\Stephen Cronin/.wp-cli/config.yml" C:\xampp56\php\php.exe C:/SJCHD/Dev/!Sites/wp-cli/bin/../php/boot-fs.php rewrite flush --hard
```
and `$results` shows it's now failing because `WP_CLI_CONFIG_PATH` is not recognized as a command:
```
object(WP_CLI\ProcessRun)#1214 (6) {
  ["stdout"]=>
  string(0) ""
  ["stderr"]=>
  string(109) "'WP_CLI_CONFIG_PATH' is not recognized as an internal or external command,
operable program or batch file.
"
  ["return_code"]=>
  int(1)
  ["command"]=>
  string(159) "WP_CLI_CONFIG_PATH="C:\Users\Stephen Cronin/.wp-cli/config.yml" C:\xampp56\php\php.exe C:/SJCHD/Dev/!Sites/wp-cli/bin/../php/boot-fs.php rewrite flush --hard"
  ["cwd"]=>
  NULL
  ["env"]=>
  array(0) {
  }
}
```
I can enter `WP_CLI_CONFIG_PATH="C:\Users\Stephen Cronin/.wp-cli/config.yml"` as a command in Bash (using ConsoleZ and Git for Windows), but in cmd.exe I get the same error as above, so I guess this a Windows ... thing.

Hope that info helps. And thanks for maintaining such a great project! 

As an aside, I added `wp-cli.yml` with the `mod_rewrite` entry to the project folder and verified it's being picked up using `wp --info` and that didn't help with either 0.23.0 or 0.24.0-alpha.
