### ISSUE TITLE
Make search-replace skip GUID column by default

### ISSUE THREAD

**Issue by aheckler** [wp-cli/wp-cli#1982]
Would be nice to help prevent accidental altering of GUIDs. Could add a flag like:

`--include-guids`

... that would run the search-replace on that column as well.

**Comment by danielbachhuber** [comment]
We already have `--skip-columns=guid`.

If you're running search and replace against an entire production database, it behooves you to:

1. Back up your production database before you run the command, and ensure you can successfully restore.
2. Run the command locally or against staging before running against production.
3. Verify expected results locally or on staging before running against production.

If you don't follow these steps, there are many things you can accidentally break by running search / replace.

**Comment by lkraav** [comment]
It'd actually be nice to have additional documentation about the GUID thing. Not everybody is likely to be aware of why you should skip that column. Is https://codex.wordpress.org/Changing_The_Site_URL#Important_GUID_Note the only consideration?

**Comment by danielbachhuber** [comment]
> It'd actually be nice to have additional documentation about the GUID thing.

What should be documented?

**Comment by jalefkowit** [comment]
I know this is old and closed, but I just wanted to add my $0.02: a tool's default behavior should be to operate the way it's intended to be used. If changing GUIDs is a Very Bad Thing that people should generally not be doing, WP-CLI should require you to do something affirmative (like passing an option flag) before it changes them. Requiring people to pass an option flag each time in order for WP-CLI to _not_ do the Very Bad Thing just means that some percentage of people are going to forget (or not know) to pass it, thereby shooting themselves in the foot.

**Comment by gitlost** [comment]
The problem is backward compatibility. Although that should be the behaviour, we're stuck with what we have...
