### ISSUE TITLE
Please change direct use Spyc.php to package mustangostang/spyc

### ISSUE THREAD

**Issue by Balancer** [wp-cli/wp-cli#1985]
Spyc have composer package mustangostang/spyc with many dependents: https://libraries.io/packagist/mustangostang%2Fspyc

All this packages can not use with wp-cli with conflict "**Cannot redeclare class Spyc**".

Or move Spyc from global namespace.

Thank you.

**Comment by danielbachhuber** [comment]
> Or move Spyc from global namespace.

This would be my preference, although it would be a breaking change we'd need to accommodate in a major release.

**Comment by danielbachhuber** [comment]
I'm not sure why removing Spyc from global namespace was my initial inclination. Using `mustangostang/spyc` does the trick just fine.
