### ISSUE TITLE
Not able to create the directory when I try to update the core

### ISSUE THREAD

**Issue by GCorbel** [wp-cli/wp-cli#1987]
I did `wp core update` and I have this result : 

    Updating to version 4.3 (fr_FR)...
    Téléchargement de la mise à jour depuis https://downloads.wordpress.org/release/fr_FR/wordpress-4.3.zip...
    Décompression de la mise à jour...
    Error: Impossible de créer le dossier.

It's in french but the last line means "Not able to create the directory". What is the problem ?

Thanks for your help!

**Comment by danielbachhuber** [comment]
> It's in french but the last line means "Not able to create the directory". What is the problem ?

WP-CLI likely can't create `wp-content/upgrades`. You may need to create it manually, and give WordPress read/write access to it.

**Comment by GCorbel** [comment]
That was it. Thanks for your help. It could be nice to create the directory if it doesn't exist.

**Comment by danielbachhuber** [comment]
> It could be nice to create the directory if it doesn't exist.

It tried to, but didn't have the appropriate permissions.

**Comment by helgatheviking** [comment]
following this [answer](http://stackoverflow.com/a/23755604/383847) I

```
chown <username>:<username>  -R * # Let your useraccount be owner
chown www-data:www-data wp-content # Let apache be owner of wp-content
```

and *finally* `wp-cli` was able to get beyond the same error. I also had already added myself to the `www-data` group. not sure if that helped, but mentioning it for reference.
