### ISSUE TITLE
Does Wp-cli fetches data from cache when running some commands .

### ISSUE THREAD

**Issue by rjdp** [wp-cli/wp-cli#1989]
I ran `wp user list` on my 3 wordpress installs and faced inconsitency issues.

* Note: For simplicity I consider output of concerned wp command as variables X,Y,Z.

cd path/to/site1/htdocs/ 
 wp user list
 optput = X

cd path/to/site2/htdocs/
 wp user list
 optput = X

cd path/to/site3/htdocs/
 wp user list
 optput = Y

then again i revisited site2

cd path/to/site2/htdocs/
 wp user list
 optput = Y

but after few moments when I run `wp user list` inside `path/to/site2/htdocs/` , I get output = Z which was correct output.

**Comment by danielbachhuber** [comment]
> Does Wp-cli fetches data from cache when running some commands

Do you have a caching system in place on your sites? Does the problem persist with cache disabled?

WP-CLI doesn't natively cache any data.

**Comment by tersmitten** [comment]
We have to same problem. This occurs when we set `options`:

```
wp-cli --allow-root --no-color --path='/var/www/example.com/www/public_html' option update 'comments_notify' '0'
```

The output is always:
```
Success: Value passed for '####' option is unchanged
```

I must say we use `W3 Total Cache` and the problem is gone when we disable that. Is there any way to fix this problem on the `wp-cli` side?

**Comment by danielbachhuber** [comment]
> I must say we use W3 Total Cache and the problem is gone when we disable that

Which caching strategy are you using with W3 Total Cache?

**Comment by tersmitten** [comment]
Both object and database cache

**Comment by tersmitten** [comment]
I thought I fixed the problem [doing this](https://github.com/Oefenweb/ansible-wordpress/commit/0295d629d96b958a32a84a08525adf7411ce66bb), but options still are not set :-(
