### ISSUE TITLE
revslider - tables not being created on activation

### ISSUE THREAD

**Issue by nick255** [wp-cli/wp-cli#1997]
I'm having an issue with activating the revslider plugin using wp-cli, it reports that it is activated on the command line but I noticed that the tables required by the plugin are not being created:
 
If I install the plugin on the command line but then activate through wp-admin page, the tables get created or if I install and activate though wp-admin.
This is on a Linux container, on my windows desktop it activates fine so might be something that is wp-cli and Linux specific but I've run out of ideas as to what maybe causing the problem.

command im running
wp plugin install /var/somepath/revslider.zip --path=/var/www/html --activate

PHP binary:     /usr/local/bin/php
PHP version:    5.6.10
php.ini used:
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.19.2

**Comment by szepeviktor** [comment]
`register_activation_hook()` is buried in a class.

```php

class UniteBaseAdminClassRev extends UniteBaseClassRev{

/**
 *
 * register the "onActivate" event
 */
protected function addEvent_onActivate($eventFunc = "onActivate"){
        register_activation_hook( self::$mainFile, array(self::$t, $eventFunc) );
}
```

There are :cry: poor quality plugins out there.

**Comment by MatthewEppelsheimer** [comment]
Same problem with Query Monitor, which also calls `register_activation_hook()` from inside of a class. (Related [WP.org support ticket](https://wordpress.org/support/topic/wp-cli-activation-doesnt-seem-to-attach-the-admin-menu))

Is putting `register_activation_hook()` inside of a class really a bad practice? It seems common. Is the `__construct()` method's `protected` keyword the problem?

**Comment by danielbachhuber** [comment]
> Is putting register_activation_hook() inside of a class really a bad practice? It seems common.

I don't know that it's necessarily a bad practice, but you do need to make sure your code is executing as you expect it to. 

> Is the __construct() method's protected keyword the problem?

I don't see `__construct()` in the example. However, if you were to register a protected method as your registration callback, it wouldn't be executed because the callback is executed by `call_user_func_array()` which doesn't have access to private scope.
