### ISSUE TITLE
Script Integration Strategy

### ISSUE THREAD

**Issue by danlasota** [wp-cli/wp-cli#2004]
[BACKGROUND]
In a multisite WordPress instance I have added bash scripts to regularly import enrollment data from the Institution's student management system, as well as another table to track WordPress sites that serve as academic course shells:

    wp_basepath_bf_enrolls
    +-------+-------------+------+-----+---------+-------+
    | Field | Type        | Null | Key | Default | Extra |
    +-------+-------------+------+-----+---------+-------+
    | term  | varchar(8)  | YES  |     | NULL    |       |
    | crn   | varchar(6)  | YES  |     | NULL    |       |
    | lg_id | varchar(40) | YES  |     | NULL    |       |
    +-------+-------------+------+-----+---------+-------+

    wp_basepath_bf_shells
    +-------+-------------+------+-----+---------+-------+
    | Field | Type        | Null | Key | Default | Extra |
    +-------+-------------+------+-----+---------+-------+
    | term  | varchar(8)  | YES  |     | NULL    |       |
    | crn   | varchar(6)  | YES  |     | NULL    |       |
    | site  | varchar(40) | YES  |     | NULL    |       |
    +-------+-------------+------+-----+---------+-------+

I have also installed wp-cli and was thinking about using some of the user commands like:

    wp --url=[rt_sitename].[rt_machine].uaf.edu user list --field=user_login
to list the students in a given site and

    wp --url=[rt_sitename].[rt_machine].uaf.edu user create [rt_UA_accountName] [rt_UA_accountName]@alaska.edu --role=author --quiet
to add the students if they are not already listed

[OBJECTIVE]
In high level quasi code:
Loop through the course shells and pull up the class roster of students in the enrolls table by matching the term and crn fields.

For each of these rosters I would make sure all the student registrants is enrolled in each course.
I will not check to see if they are no longer registered in the class. The students are only auto-registered, not auto-removed.

[QUESTION]
What's the best way to script these actions?
I can write procedures in MySQL, create bash scripts, and cron jobs on the server and script PHP. I am unsure of how to return output from wp-cli into array objects, however, and act on error text returned.

Could someone please point me in a direction that makes sense?

**Comment by danielbachhuber** [comment]
> I am unsure of how to return output from wp-cli into array objects

Have you considered the `--format` param for `wp user list`? You can use `wp user list --format=json` or `wp user list --format=csv`, and then mangle the data as you'd like in your bash script.

> act on error text returned.

If you get an error, you should get an error code.

**Comment by szepeviktor** [comment]
As I do a lot of Bash:
I suggest you to write a [community command](https://github.com/wp-cli/wp-cli/wiki/Commands-Cookbook)
Bash [is not for databases](https://github.com/szepeviktor/debian-server-tools/blob/cb9a3fd73fce6140dceb1d52d44a601030246b73/monitoring/cse/can-send-email.sh#L39-L41).
