### ISSUE TITLE
filter wp post list by post_date

### ISSUE THREAD

**Issue by angrycyborg** [wp-cli/wp-cli#2005]
hello,

Should I be able to filter by date? 

`wp post list --post_date=2011-01-01`
or
`wp post list --post_date=2011%`

returns all posts

thanks!

**Comment by danielbachhuber** [comment]
`wp post list` [supports](http://wp-cli.org/commands/post/list/) any arguments that WP_Query supports. WP_Query doesn't support `post_date` as an argument.

WP_Query _does_ support `year`, `monthnum` and `day`:

```
wp post list --year=2011 --monthnum=1 --day=1

wp post list --year=2011
```
