### ISSUE TITLE
Website design cleanup

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2006]
Placeholder issue for some website cleanup.

**Comment by danielbachhuber** [comment]
These global params should be styled:

![image](https://cloud.githubusercontent.com/assets/36432/9480915/f29544d0-4b3a-11e5-9798-9d785d647dda.png)

Or we should just remove them from all pages that aren't the global params page, and link the global params page instead.

**Comment by saltcod** [comment]
Hey Daniel!   I'd definitely like to help with this. I've seen some decent examples around on some other docs sites that I can probably dig up. 

How s/could we get started?

**Comment by danielbachhuber** [comment]
> Hey Daniel! I'd definitely like to help with this.

I appreciate it :)

> How s/could we get started?

If you just want to contribute design ideas, feel free to drop them in this thread.

If you feel like contributing some CSS, the [website is open source too](https://github.com/wp-cli/wp-cli.github.com). Getting it configured locally is a good start. I'm happy to provide input on how you might go about submitting some pull requests.

**Comment by saltcod** [comment]
Maybe I'll just post in some ideas for now, and see how that goes. 

https://dl.dropboxusercontent.com/s/s5brcg2n3p2wahk/2015-08-26%20at%2012.14%20PM.png

I'm thinking a few things here: 

— separate the main command a little more from the rest of that page's content.  So just give the top-most command a little more breathing room. 

— Maybe wrap those global parameters in the code tag as well — code.parameter maybe — and change the style of them.  That gives the "hey this is code!" feeling, but separates it from the main command. 

None of those are wrapped in any markup at the moment (code or span or anything) so that might be a bit of a chore(?).

**Comment by danielbachhuber** [comment]
We could make both of those changes! How do you feel about dropping global parameters from those pages entirely?

**Comment by saltcod** [comment]
Aaah now I see what you mean.  Yeah that could be moved below sub commands, be moved to a different page, or maybe made a sidebar widget: 

https://dl.dropboxusercontent.com/s/l4sbd514fwpiwl6/2015-08-26%20at%2010.20%20PM.png

**Comment by danielbachhuber** [comment]
I added the horizontal rule: http://wp-cli.org/commands/cache/

![image](https://cloud.githubusercontent.com/assets/36432/9547626/5cab7346-4d50-11e5-9ae7-dda9ecba1bec.png)

How should Global Parameters work as a sidebar widget on mobile?

**Comment by saltcod** [comment]
Sweet! Yeah that looks better to my eye at least! 

I'd say on mobile it would just fall above/below the subcommands area and shrink up as it does now.  The sidebar widget might just be a compromise anyway. You'd know better than me how important/relevant that info is on that page, but putting it in a sidebar and giving it a this-is-secondary-information style treatment is a decent compromise on removing it all together. 

If you're talking in real, practical terms:   I'd say sub-commands = 60%, global parameters = 40% and both become 100% on mobile.   You can change the float left/right on mobile widths to change the order of them to be what you'd like (ie: to put one on top of the other).

**Comment by danielbachhuber** [comment]
> If you're talking in real, practical terms: I'd say sub-commands = 60%, global parameters = 40% and both become 100% on mobile. You can change the float left/right on mobile widths to change the order of them to be what you'd like (ie: to put one on top of the other).

Cool. I'll take care of this when I have a moment.

**Comment by saltcod** [comment]
maybe I should just get setup locally. That'd save you a bunch of time.
If I get a chance later today I'll give it a go.

**Comment by saltcod** [comment]
Hey Daniel — I looks I might have some availability coming up to be able to dedicate a bit more time to this. Want to shoot me an email and we can discuss?   I'm saltcod at the big gmail-ator.

**Comment by danielbachhuber** [comment]
> Want to shoot me an email and we can discuss?

Let's chat in `#cli` in WordPress Slack.

**Comment by danielbachhuber** [comment]
Global params are nice and shiny now:

![image](https://cloud.githubusercontent.com/assets/36432/13355380/e6b79f4a-dc54-11e5-9cf3-b5f55ff6f534.png)

**Comment by saltcod** [comment]
Sweet!
