### ISSUE TITLE
wp theme update --all returns status error at all time

### ISSUE THREAD

**Issue by a1exus** [wp-cli/wp-cli#2015]
any time I ran `wp theme update --all`, I'm getting `status` `Error`, even though theme gets updated.

```
+-----------+-------------+-------------+--------+
| name      | old_version | new_version | status |
+-----------+-------------+-------------+--------+
| customizr | 3.4.6       | 3.4.8       | Error  |
+-----------+-------------+-------------+--------+
```

I tried deleting theme and installing it, no problem, just update returns error for unknown reason..

**Comment by danielbachhuber** [comment]
Thanks for the report, @a1exus. The theme is being updated, however there's a bug in the reporting.

If you want to use `--format=summary`, you'll get the correct message. I'll get the bug fix into `master` shortly, and will likely release a v0.20.1 in the next couple of weeks to address this issue (as it was introduced in v0.20.0)
