### ISSUE TITLE
install-wp-tests.sh should also drop test database if exists (or drop tables in test database)

### ISSUE THREAD

**Issue by kminh** [wp-cli/wp-cli#2018]
When testing the core WordPress (i.e. https://make.wordpress.org/core/handbook/testing/automated-testing/), all tables are dropped after the tests are completed, so I think it makes sense to do the same thing when we test plugins.

The way I'm using `install-wp-tests.sh` might be different, because I run it every time I run my functional tests, not just after running `wp scaffold plugin`.

**Comment by danielbachhuber** [comment]
> so I think it makes sense to do the same thing when we test plugins.

But plugin tests use the same test suite as core? I'm not sure I follow what your suggestion is.

**Comment by kminh** [comment]
Not sure if it's a bug, but after I run my tests all tables in test database are still there.

**Comment by kminh** [comment]
My bad should have extended the WP_UnitTestCase class.
