### ISSUE TITLE
adding users when they already exist in multisite

### ISSUE THREAD

**Issue by danlasota** [wp-cli/wp-cli#2024]
I am trying this:
`'wp --path=/var/www/public_html/ --skip-plugins --skip-themes --quiet --url=[rt_site].machine.domain user create [rt_userID] [rt_userID]@domain --role=author'`
where [rt_site] and [rt_userID] are being swapped out for appropriate values

It's often the case that one user already has an account in the multisite network on other blog(s). Apparently the above command to wp-cli will not work. I get this as a message:

Error: The 'username' username is already registered.

My intention is to just try and add users from a list generated by an authoritative source of registrations. (This is for academic class registration, some of the blogs on our multisite are populated with students).

The above command does work if the user exists in the system, when the user is new to our multisite, however, it does work.

Is there an appropriate workaround to add an existing user to another blog when they exist in multisite?
What's the best way to test if they exist on multisite, but not on a particular blog?

**Comment by szepeviktor** [comment]
> The above command does work if the user exists in the system, when the user is new to our multisite, however, it does work.

Itn't a *not* missing?

**Comment by szepeviktor** [comment]
`wp --url=http://a.particular.blog user list --user_login=username` tells you whether the user exists.

**Comment by danielbachhuber** [comment]
> What's the best way to test if they exist on multisite, but not on a particular blog?

Actually, you'll want to use the `--network` flag with `wp user list` to get all users on the network.

```
salty-wordpress ➜  wordpress-develop.dev  wp core multisite-convert
Set up multisite database tables.
Added multisite constants to wp-config.php.
Success: Network installed. Don't forget to set up rewrite rules.
salty-wordpress ➜  wordpress-develop.dev  wp user list --network
+----+------------+--------------+-----------------------+---------------------+
| ID | user_login | display_name | user_email            | user_registered     |
+----+------------+--------------+-----------------------+---------------------+
| 1  | daniel     | daniel       | d@danielbachhuber.com | 2015-07-27 03:29:02 |
+----+------------+--------------+-----------------------+---------------------+
salty-wordpress ➜  wordpress-develop.dev  wp user delete daniel
--reassign parameter not passed. All associated posts will be deleted. Proceed? [y/n] y
Success: Removed user 1 from http://wordpress-develop.dev
salty-wordpress ➜  wordpress-develop.dev  wp user list
+----+------------+--------------+------------+-----------------+-------+
| ID | user_login | display_name | user_email | user_registered | roles |
+----+------------+--------------+------------+-----------------+-------+
+----+------------+--------------+------------+-----------------+-------+
salty-wordpress ➜  wordpress-develop.dev  wp user list --network
+----+------------+--------------+-----------------------+---------------------+
| ID | user_login | display_name | user_email            | user_registered     |
+----+------------+--------------+-----------------------+---------------------+
| 1  | daniel     | daniel       | d@danielbachhuber.com | 2015-07-27 03:29:02 |
+----+------------+--------------+-----------------------+---------------------+
```

**Comment by szepeviktor** [comment]
I am sorry for missing `--network`.

**Comment by danlasota** [comment]
OK. So, if a user exists in multisite, then how do you go about adding them to a particular blog then? (or another way of thinking about it is, assigning another role on an additional blog.

**Comment by danielbachhuber** [comment]
> So, if a user exists in multisite, then how do you go about adding them to a particular blog then?

`wp --url=subsite.example.com user set-role <user-login> <role>`

Generally, the docs are your friend: http://wp-cli.org/commands/

**Comment by danlasota** [comment]
Thanks Dan. I have been pouring through the docs, I must have filtered out the set-role subsection for the user commands. I didn't think to even look in there.

**Comment by danielbachhuber** [comment]
@danlasota no worries. Any other questions on this thread?

**Comment by danlasota** [comment]
That's it. Thanks very much!

**Comment by photocurio** [comment]
Back to this thread.. I see that you can _add_ a user from the multisite network to a blog.  Can you _remove_ a user from the blog, but not delete the user from the network?  It looks like the value for role can only be default, or a different role.
