### ISSUE TITLE
Is wp the right approach for adding users?

### ISSUE THREAD

**Issue by danlasota** [wp-cli/wp-cli#2025]
First, thanks for the quick responses on some of my earlier questions. 

I really like the functionality of wp, especially in the user command block. It allows me not to worry about WordPress database internals.

The downside to wp though, is that it seems resource intensive. I did some tests for adding approximately 400 users, and wp processes about two account creations per second.

I know I could manipulate the WordPress database much faster, if I knew which tables to manipulate. The last time I looked into it, WordPress puts what blogs a user is a member of (with roles), into an encoded string. Would anyone have any info about deciphering and manipulating this string? How often does WordPress change this string? (I don't want to write brittle code that breaks between WordPress updates).

Thanks.

**Comment by szepeviktor** [comment]
wp-cli runs on the CLI SAPI that - by default - has no opcache and the phar file has to be unpacked. I think these are the main reasons of starting up in half a second.

**Comment by szepeviktor** [comment]
For example in my [mini WP-based WAF](https://github.com/szepeviktor/wordpress-fail2ban/blob/master/miniban/miniban-wordpress.php#L114-L127) I do `SHORTINIT` and then require one more file to be able to use `get_option()`.

**Comment by danielbachhuber** [comment]
> I did some tests for adding approximately 400 users, and wp processes about two account creations per second.

You may also have some hooks firing on user creation that are slowing things down. This seems pretty slow. How many users do you have to import in total?

> I know I could manipulate the WordPress database much faster, if I knew which tables to manipulate. The last time I looked into it, WordPress puts what blogs a user is a member of (with roles), into an encoded string. Would anyone have any info about deciphering and manipulating this string? How often does WordPress change this string? (I don't want to write brittle code that breaks between WordPress updates).

I think using WordPress APIs is your safest bet. Unless it's a very controlled environment, direct database manipulation is generally fraught with land mines, as its hard to know how plugins and themes are changing things / expecting things to be changed.

Have you considered `wp user import-csv` to get around WordPress load time?

**Comment by danlasota** [comment]
>You may also have some hooks firing on user creation that are slowing things down. This seems pretty slow. How many users do you have to import in total?

This is an academic environment. New student registrations. About 400-500 new class registrations per semester. A big portion of the students already have usernames in multisite though.

I am retrieving account names and blog memberships (class registrations) from the institutional registration system. It gets updates every hour as people get enrolled through self actions via the web, through instructor adds, and through the old fashioned way of people walking up to a counter and having a clerk manually add them. I'd like to run my import script about every hour.

I realize that its inefficient to have a script that keeps trying to add users who already exists in terms of cpu, but its efficient in scripting time...

>Have you considered wp user import-csv to get around WordPress load time?
I would consider it, but again, I'm looking at it handling a mix of users who already have accounts/usernames.

It might be nice if there is a way to have wp-cli just take usernames and 'try' to add them. If the user already exists in the network, fine. Just add them to the particular blog. If they already exist at the particular blog, fine, do nothing.

**Comment by danielbachhuber** [comment]
> I realize that its inefficient to have a script that keeps trying to add users who already exists in terms of cpu, but its efficient in scripting time...

You could also cache usernames for those users who already exist to a local file, and grep that before trying to add them again. You can even create the local file on each script execution to ensure its fresh — it would still have the performance boost of not hitting WordPress.

> It might be nice if there is a way to have wp-cli just take usernames and 'try' to add them. If the user already exists in the network, fine. Just add them to the particular blog. If they already exist at the particular blog, fine, do nothing.

While this is a bit of an edge case to accommodate in the main project, it should be quite simple to do with a custom WP-CLI command. See https://github.com/wp-cli/wp-cli/wiki/Commands-Cookbook#anatomy

**Comment by danlasota** [comment]
I will check that out.
Over lunch I thought of a strategy to check for the existence of a user on the SQL side in the wp_users tables. If they are in there, I change the role. If zero rows are returned, I need to add them.

Thanks.
