### ISSUE TITLE
Installing community packages when WP installed with homebrew

### ISSUE THREAD

**Issue by veganista** [wp-cli/wp-cli#2027]
What would the suggested location for community packages be if wp-cli was installed via homebrew.

Is it preferred to install as a standalone command rather than doing it through homebrew if a user is planning to extend wp-cli?

Cheers

**Comment by danielbachhuber** [comment]
Community command installation and management isn't supported at the moment. #1564 has the history.

**Comment by veganista** [comment]
Sorry i should have been a bit clearer. 

I'm trying to install my plugin system wide, but was unsure where to put the files as i have installed via homebrew.

Just looking for a "this is what i would do" kind of answer

**Comment by danielbachhuber** [comment]
> I'm trying to install my plugin system wide, but was unsure where to put the files as i have installed via homebrew.

Where you put the files shouldn't matter. You can `require` them in a `config.yml` file, and then load the `config.yml` file with a `WP_CLI_CONFIG_PATH` environment variable.

Learn more about runtime configuration here: http://wp-cli.org/config/
