### ISSUE TITLE
Content check from WP-CLI

### ISSUE THREAD

**Issue by mattclegg** [wp-cli/wp-cli#2029]
I'd like to implement the functionality from [wp-cli_check-content](https://github.com/mattclegg/wp-cli_check-content) as a part of the core. Is this something that will be useful?

**Comment by danielbachhuber** [comment]
Hm. Probably seems best as a community command for the time being.

**Comment by mattclegg** [comment]
Ok, no problem. I was just having a problem installing community commands for all users until I found that you can specify WP_CLI_CONFIG_PATH manually. I'll add this to the docs.
