### ISSUE TITLE
Generate a wp-yml file from existing wordpress site

### ISSUE THREAD

**Issue by philcook** [wp-cli/wp-cli#2032]
Hi,

I was wondering if generating a wp-yml file could be built as a new feature.

What I am looking for is a way to speed up development for my team by one developer generating this file, submitting to our repo and then all other devs can just pull and run wp cli.

Thanks for considering.

**Comment by danielbachhuber** [comment]
> I was wondering if generating a wp-yml file could be built as a new feature.

What would the file contain?

**Comment by philcook** [comment]
Basic details of

```
path: public_html/
url: http://wizzi.dev
user: admin
theme-name: wizzi
core download:
  locale: en_GB
core config:
	dbname: wizzi
	dbuser: root
	dbpass:
core install:
    title: Wizzi
    admin_user: admin
    admin_password: password
    admin_email: admin@admin.dev
```

Would also be nice if it did the plugin names and then was able to loop on this to install when another developer comes to work on the project

```
plugin install:
  - breadcrumb-navxt
  - contact-form-7
  - scripts-to-footerphp
  - wp-scss
  - https://github.com/wp-sync-db/wp-sync-db/archive/master.zip
  - https://github.com/wp-sync-db/wp-sync-db-media-files/archive/master.zip
```

**Comment by danielbachhuber** [comment]
I'm sorry. I don't understand why this would need to be a feature of WP-CLI. Why can't you just commit a file with these details to your version control?

**Comment by philcook** [comment]
Hi @danielbachhuber 

Firstly, sorry if I am not explaining it correctly. We could create these YML files manually however we have hundreds of wordpress sites created before using WP CLI.

Therefore as and when we come to work on these projects again it would be good to have a command to run on the production server that would generate this YML file from the existing site. Commit that to the repo and then the developers pulls this down to a local repo on their machine.

Then to setup their local environment they then run a few WP CLI commands based off that YML file.

This is just a time saving feature request so save the manual creation of the YML file from a pre-existing wordpress site.

**Comment by danielbachhuber** [comment]
I see.

For the logic you want, I think it would make most sense as a [community command](https://github.com/wp-cli/wp-cli/wiki/List-of-community-commands). In fact, I started something related in the past: https://github.com/danielbachhuber/dictator

Also, I don't know that `wp-cli.yml` is the best place to store this data, as it defines the default arguments every time you run a given command. Instead, you might consider a WP-CLI command to populate a bash `setup.sh` file, intended to be run once (or safely run multiple times).
