### ISSUE TITLE
Clarify status of parent theme to active theme

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2033]
In `wp theme list`, the parent theme of the currently active theme should be listed with `status=parent`, not `status=inactive`

From https://github.com/wp-cli/wp-cli/issues/1954#issuecomment-137566711

**Comment by tmuka** [comment]
You probably already know how this works, but get_template_directory will return the active parent, might be useful inside is_active_theme() in place of get_stylesheet_directory(),  or perhaps in a different fn that gets called with that in theme->get_status().

thanks for the awesome work here!
