### ISSUE TITLE
WooCommerce notice not displayed on theme switch

### ISSUE THREAD

**Issue by shivapoudel** [wp-cli/wp-cli#2038]
If we activate theme that doesn't support `add_theme_support( 'woocommerce' )` then woocommerce theme check notice is affected as it uses `switch_theme`.

Ref: https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-notices.php#L36

**Comment by danielbachhuber** [comment]
Sorry, I don't follow. Can you clarify what you expect WP-CLI to be doing in this scenario?

**Comment by shivapoudel** [comment]
If we hook any functionality on `switch_theme` action hook then that should definitely execute while switching theme only. It work while we surf admin themes page and switch theme. But my point is if we activate the theme via `wp theme activate next-theme`, none of the functionality from `switch_theme` action hook is triggered =/

IMO WP-CLI should trigger `switch_theme` hook when theme is switched or activated :)

**Comment by danielbachhuber** [comment]
> IMO WP-CLI should trigger switch_theme hook changes when theme is switched or activated :)

WP-CLI calls `switch_theme()` https://github.com/wp-cli/wp-cli/blob/master/php/commands/theme.php#L141 which calls the `switch_theme` hook in turn https://core.trac.wordpress.org/browser/trunk/src/wp-includes/theme.php#L750

> It work while we surf admin themes page and switch theme.

When the theme is being switched from the admin, is the `woocommerce_installed` action called? https://github.com/woothemes/woocommerce/blob/master/includes/admin/class-wc-admin-notices.php#L37

**Comment by mikejolley** [comment]
@shivapoudel The code which handles `switch_theme` and admin notices is loaded only in when `is_admin()` is true, and after `init` hook is fired. I assume CLI doesn't load admin?

**Comment by danielbachhuber** [comment]
> I assume CLI doesn't load admin?

It loads all of the admin APIs, but doesn't set the `WP_ADMIN` constant:

```
wp> constant( 'WP_ADMIN' );
PHP Warning:  constant(): Couldn't find constant WP_ADMIN in /home/vagrant/.wp-cli/php/WP_CLI/REPL.php(31) : eval()'d code on line 1
Warning: constant(): Couldn't find constant WP_ADMIN in /home/vagrant/.wp-cli/php/WP_CLI/REPL.php(31) : eval()'d code on line 1
NULL
```

See http://wp-cli.org/blog/how-wp-cli-loads-wordpress.html for more details.
