### ISSUE TITLE
Site Aliases

### ISSUE THREAD

**Issue by davidbarratt** [wp-cli/wp-cli#2039]
It would be really helpful if `wp-cli` supported site-aliases like drush:
https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php

This would allow you to do something like this:
```
wp @dev core update
```
without having to ssh into the server, cd into the directory and execute the command.

Drush also supports the magic `@all` which allows you to perform the command on all of your aliases. This way, you could have an alias file of hundreds of wordpress sites and update all of them in a single command. :)

**Comment by danielbachhuber** [comment]
In what ways is this different than the alias system we already have?

For instance, in your `wp-cli.yml` file, you can have:

```
core config:
	dbuser: root
	dbpass: 
	extra-php: |
		define( 'WP_DEBUG', true );
		define( 'WP_POST_REVISIONS', 50 );
```

These arguments become the default whenever you run `wp core config`

**Comment by davidbarratt** [comment]
@danielbachhuber,

Can you define a remote host like this?
https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php#L336-L337
or even a local root?
https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php#L334

Maybe I just don't undertand the current alias system.

**Comment by danielbachhuber** [comment]
> Can you define a remote host like this?

WP-CLI doesn't currently support connecting to a remote host. You may want to consider https://github.com/xwp/wp-cli-ssh

> or even a local root?

This example you're pointing to seems to refer to a remote staging site. WP-CLI _can_ connect to any local WordPress install with the `--path=/path/to/wp/directory` argument.

> Maybe I just don't undertand the current alias system.

Have you tried using it? [Here's a blog post documenting the feature](http://wp-cli.org/blog/version-0.13.html) when it was introduced.

**Comment by danielbachhuber** [comment]
Picking this up in conjunction with #2754 for v0.24.0

**Comment by danielbachhuber** [comment]
The initial version of this feature works like this...

One or more aliases can be defined in `config.yml` or `wp-cli.yml`:

```
@wpdev:
  path: /srv/www/wordpress-develop.dev/src
```

An alias is called as the first argument to the `wp` executable:

```
salty-wordpress ➜  .wp-cli  wp @wpdev option get home
http://wordpress-develop.dev
```

The matching alias will overload the global parameters it defines. When an alias is used, any passed arguments will be treated as local parameters:

```
salty-wordpress ➜  .wp-cli  wp @wpdev option get home --path=/srv/www/wordpress-develop.dev/src
Error: Parameter errors:
 unknown --path parameter
```

**Comment by danielbachhuber** [comment]
Feeling pretty good about this now.

You can define a group of aliases to run a command against all WordPress instances in the group:

```
$ cat cat wp-cli.local.yml
user: daniel
@both:
  - @prod
  - @dev
@prod:
  ssh: rc~/webapps/production
@dev:
  ssh: v/srv/www/runcommand.dev
$ wp @both rewrite flush
Success: Rewrite rules flushed.
Success: Rewrite rules flushed.
```

`wp cli alias` will give you a list of all aliases:

```
$ wp cli alias
---
@both:
  - @prod
  - @dev
@prod:
  ssh: rc~/webapps/production
@dev:
  ssh: v/srv/www/runcommand.dev
@all:
  - @both
  - @prod
  - @dev
```
