### ISSUE TITLE
multisite-convert fails when wp-config file is not writeable

### ISSUE THREAD

**Issue by Fab1en** [wp-cli/wp-cli#2040]
If the `multisite-convert` command is run and the `wp-config.php` file is not writeable, the command is still executed but leaves the installation is an indefinite state. Network is not installed, but trying to re-run the `multisite-convert` after having changed wp-config.php rights does not work : "Network already exists".

The command should first check that `wp-config.php` file is writeable before actually creating the network.

**Comment by danielbachhuber** [comment]
> The command should first check that wp-config.php file is writeable before actually creating the network.

I'm not sure of this conclusion. I think converting a single site to multisite when `wp-config.php` isn't writable is a valid use case. However, we could do better about warning the user their constants are missing.
