### ISSUE TITLE
Must-Use plugins

### ISSUE THREAD

**Issue by oviliz** [wp-cli/wp-cli#2041]
I have tried to see the website commands and Wiki but can't understand if there is a way to install Must-Use plugins inside the mu-plugins folder. Could you please advise?

**Comment by ryanduff** [comment]
I'll be out of the office Monday September 7th and will respond to your email Tuesday September 8th.

**Comment by danielbachhuber** [comment]
There is not a way to install plugins to the mu-plugins folder with WP-CLI.

An alternative would be to install the plugin with `wp plugin install <my-slug>`, and then move it to the mu-plugins directory.

**Comment by nightelf** [comment]
"Must-use plugins (a.k.a. mu-plugins) are plugins installed in a special directory inside the content folder and which are automatically enabled on all sites in the installation." No need to "install" must-use plugins. They are installed just by putting them in the directory
