### ISSUE TITLE
wp help doesn't validate parameters

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#2043]
The following command triggers an error due to the unknown parameter (note the typo in the `--url` parameter):

`wp option get home --url-example.com`

But the `wp help` command doesn't trigger such an error:

`wp help --url-example.com`

If, like me, you have fat fingers, this might cause some head scratching. Is there a reason `wp help` doesn't validate its parameters if any are provided?

**Comment by danielbachhuber** [comment]
> Is there a reason wp help doesn't validate its parameters if any are provided?

We could do that. We could also (possibly) fill in the provided parameters to the help docs, to visually communicate what you've already provided.

**Comment by scribu** [comment]
Previously: #1411

**Comment by danielbachhuber** [comment]
Punting on this, as it's not easily viable https://github.com/wp-cli/wp-cli/pull/2294#issuecomment-164040826
