### ISSUE TITLE
search-replace --precise to json_decode

### ISSUE THREAD

**Issue by joehoyle** [wp-cli/wp-cli#2044]
If you have values in JSON, search-replace will often fail, due to json_encoding adding slashes. If the `--precise` flag is passed, how about it handles the data like similar to serialsed data?

**Comment by danielbachhuber** [comment]
Related (I think) #1613

How would you feel about the quotes being automatically escaped? Or switch to `--precise` mode if quotes are detected?

**Comment by danielbachhuber** [comment]
@joehoyle Can you provide an example test case to work from?

**Comment by joehoyle** [comment]
If I were to do:

```PHP
add_post_meta( $post_id, 'urls', json_encode( array( 'https://hmn.imgix.net/humanmade-production/uploads/2015/05/airbnb-header4.png?w=940&h=400&fit=crop' ) ) );
```

And then try do `wp search-replace https://hmn.imgix.net https://hmn-v2.imgix.net --precise` it would't pick up the above image, as the JSON encoded array will be slashed as `"https:\/\/hmn.imgix.net\/humanmade-production\/uploads\/2015\/05\/airbnb-header4.png?w=940&h=400&fit=crop"`

**Comment by danielbachhuber** [comment]
Hm. I can't reproduce the behavior of `json_encode()` adding slashes.

Using this script:

```
<?php
add_post_meta( $GLOBALS['argv'][3], 'urls', json_encode( array( 'https://hmn.imgix.net/humanmade-production/uploads/2015/05/airbnb-header4.png?w=940&h=400&fit=crop' ) ) );
```

When I call `wp eval-file wp-set-post-meta.php 100`, I see this stored in the database:

![image](https://cloud.githubusercontent.com/assets/36432/11341431/4a9d56e6-91b7-11e5-847c-059b78a788e4.png)

**Comment by danielbachhuber** [comment]
Huh. I can't even forcefully add slashed data:

```
<?php
      global $wpdb;
      $wpdb->query( "INSERT INTO $wpdb->postmeta (post_id,meta_key,meta_value) VALUES ({$GLOBALS['argv'][3]},'urls','[\"https:\\/\\/hmn.imgix.net\\/humanmade-production\\/uploads\\/2015\\/05\\/airbnb-header4.png?w=940&h=400&fit=crop\"]')");
```

**Comment by danielbachhuber** [comment]
I'm going to punt on this. Your particular need can be solved by dropping the `https://` from your `search-replace`:

```
wp search-replace hmn.imgix.net hmn-v2.imgix.net
```

Fortunately, WP-CLI isn't mangling data with its normal operation. If you know your dataset includes slashed JSON blobs, you can search-replace for that as well.
