### ISSUE TITLE
`wp help`: don't show GLOBAL PARAMETERS section by default, add `--global-help` switch

### ISSUE THREAD

**Issue by borekb** [wp-cli/wp-cli#2051]
When using `wp help`, the actual command help usually scrolls out of view because there is a relatively long GLOBAL PARAMETERS section at the end (which is generally not very useful).

Maybe this long section could be replaced with a message like:

    Use --global-help to show global parameters

and that switch could be added to the `wp help` command.

**Comment by borekb** [comment]
For reference: [discussion on Slack](https://wordpress.slack.com/archives/cli/p1442342899000118).

**Comment by rodrigoprimo** [comment]
Previously: #1032

I find global parameters on every help page useful for new users (see @scribu comment on the issue above).

**Comment by scribu** [comment]
> When using wp help, the actual command help usually scrolls out of view

That shouldn't happen, because we're using `less` to paginate the output.

**Comment by borekb** [comment]
Aha, didn't notice that because WP-CLI [disables pagination on Windows](https://github.com/wp-cli/wp-cli/blob/6d0062e7edf8ac95a2d892dc9179adb8df9bf1b7/php/commands/help.php#L93).

As someone on Windows, I think WP-CLI should behave this way:

 1. try `less` first (many power users will have this available e.g. through Git for Windows)
 2. if it isn't available use `more` ([docs](http://ss64.com/nt/more.html))

Most of the pain caused by GLOBAL PARAMETERS would go away, that's true, although I would still prefer to get command help output only as I generally think the GLOBAL PARAMS are not very useful (in 99% cases, and for the remaining 1% there would still be an info how to get them).

**Comment by danielbachhuber** [comment]
I've been on the fence about this issue, so I think we're going to punt and keep the existing behavior.

While the global parameters section is slightly annoying to me as a power user, I totally appreciate how it can be useful for new users. `--path` and `--url` are very important parameters, so we should do whatever we can to ensure users are aware of them.

The Windows issue was addressed in #2100, and now we're even doing one better by respecting the `$PAGER` variable.
