### ISSUE TITLE
fatal error allowed memory size of bytes exhausted (tried to allocate bytes) in php 

### ISSUE THREAD

**Issue by a1exus** [wp-cli/wp-cli#2054]
I encounter following error while running ```wp```, but then when I ran it again it ran fine:

```
$ wp
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 72 bytes) in /usr/home/X/wordpress/wp-includes/wp-db.php on line 2255
$ wp cli version
WP-CLI 0.20.0
$ php -i | grep memory_limit
memory_limit => 512M => 512M
$ 
```

Is 512M not enough?

**Comment by danielbachhuber** [comment]
It should be. Can you try disabling plugins and switching to the standard theme to see if there's some nefarious code?

**Comment by a1exus** [comment]
@danielbachhuber it's intermediate issue. I am using standard theme (twentyfifteen 1.3).

**Comment by danielbachhuber** [comment]
> it's intermediate issue.

I don't follow. What do you mean by "intermediate issue"?

**Comment by a1exus** [comment]
sorry, i meant to say intermittent issue, which means it doesn't always happens and it's hard to replicate...
