### ISSUE TITLE
#1909 broke methods that don't require --url

### ISSUE THREAD

**Issue by markoheijnen** [wp-cli/wp-cli#2056]
With #1909 merged methods now break like getting the site based on id with ```wp site url 1``` and I would also expect that you can still ask for updates for themes and plugins through ```wp theme list```.

**Comment by danielbachhuber** [comment]
I don't follow how #1909 would've broken what you're describing. Can you share more detail?

**Comment by markoheijnen** [comment]
Using ```wp site url 1``` return ```Error: Site  not found.```. So I assume that WP-CLI is requesting the site on every request and because of that action ```ms_site_not_found``` is always fired.

**Comment by danielbachhuber** [comment]
I can't really reproduce the test case you're describing. These are all expected results:

```
salty-wordpress ➜  wordpress-test.dev  wp site url 1
http://wordpress-test.dev
salty-wordpress ➜  wordpress-test.dev  wp site url 2
http://wordpress-test.dev/foo
salty-wordpress ➜  wordpress-test.dev  wp site url 3
http://wordpress-test.dev/bar
salty-wordpress ➜  wordpress-test.dev  wp site url 4
Error: Could not find the site with ID 4.
salty-wordpress ➜  wordpress-test.dev  wp site list
+---------+-------------------------+---------------------+---------------------+
| blog_id | url                     | last_updated        | registered          |
+---------+-------------------------+---------------------+---------------------+
| 1       | wordpress-test.dev/     | 2015-09-13 13:45:48 | 2015-09-07 15:17:11 |
| 2       | wordpress-test.dev/foo/ | 2015-09-13 14:45:24 | 2015-09-13 15:45:24 |
| 3       | wordpress-test.dev/bar/ | 2015-09-13 14:45:29 | 2015-09-13 15:45:28 |
+---------+-------------------------+---------------------+---------------------+
```

> Using wp site url 1 return Error: Site not found. So I assume that WP-CLI is requesting the site on every request and because of that action ms_site_not_found is always fired.

Maybe WP-CLI isn't able to determine the primary site on the network? What happens when you try `wp site url 1` with a `--url=<url>` to a known URL on the site?

**Comment by markoheijnen** [comment]
Then I do get the output. Will check if it's WordPress trunk, my project or PHP 7.

**Comment by markoheijnen** [comment]
My bad, Seems that I never tested WP-CLI correctly after I changed wp-config.php to load the settings from the parent folder (outside www). So it doesn't guess the main url.

This would mean that things could break when people set things up with local-config.php which has the settings. But for now a no issue.
