### ISSUE TITLE
Wp cli works very good using Putty but not using shell_exec

### ISSUE THREAD

**Issue by moreplease** [wp-cli/wp-cli#2057]
Hello, I have a little problem. Like in the title - I'm logged in Putty on the same user that is used in php (I've checked whoami) and everything works good - user is created.

The problem is when I'm trying to use it in my AJAX handler in WP: https://gyazo.com/ba0c6876338b4e16470ad77a03b295f7. When I run these lines, nothing happens, ssh works for sure, because when I tried to run "pwd", "whoami" and other standard commands, they returns output well. There is only problem with WP CLI, should I install something more on the server? Or maybe something in PHP is blocked?

I've just seen that also "which wp" doesn't return any output.

Thanks for your help!

**Comment by danielbachhuber** [comment]
Where is `wp` installed to? Does the web PHP user have access to that path?

**Comment by szepeviktor** [comment]
Could you share its output?
```php
$output = shell_eexec($cmd);
```

**Comment by jasonhai** [comment]
I've a same problems on it. Please help to to resolve it :(. Thanks...
