### ISSUE TITLE
wp core update-db

### ISSUE THREAD

**Issue by danlasota** [wp-cli/wp-cli#2060]
I am trying to run this command in a multisite instance.
I notice that the --url option is allowed with this command, I'm wondering if there is a way to flag the entire system of all blogs in the multisite instance for database update?

**Comment by danielbachhuber** [comment]
Yes `--network` will be available in v0.21.0 #2048

If you're using v0.20.0, you can use `wp cli update --nightly` to upgrade to the latest on master.
