### ISSUE TITLE
Merge global and local config

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#2069]
When you have:

```
WP-CLI global config:	/srv/www/.wp-cli/config.yml
WP-CLI project config:	/srv/www/ci/builds/project-17/wp-cli.yml
WP-CLI version:	0.19.3
```

And the global config contains the password:

```
core config:
  dbuser: JohnDoe
  dbpass: Foo
  dbhost: localhost
```

But the local doesn't:

```
core config:
  dbuser: SomeoneElse
```

Then please treat the global config as default but do not kill the password or host.

**Comment by danielbachhuber** [comment]
I _think_ I agree with this behavior. I'll need to give some thought as to whether or not it's a breaking change (e.g. produce unexpected results for someone who is already dependent on the existing behavior).

**Comment by danielbachhuber** [comment]
Related #1063

**Comment by danielbachhuber** [comment]
In v0.23.0, you'll be able to deep merge by including the following at the top of your `wp-cli.yml`:

```
_:
  merge: true
```
