### ISSUE TITLE
Is there a reason that wp option update does not support --autoload=

### ISSUE THREAD

**Issue by tersmitten** [wp-cli/wp-cli#2081]
While `update_option` does [support it](https://codex.wordpress.org/Function_Reference/update_option)

**Comment by danielbachhuber** [comment]
No reason it shouldn't. Adding support in #2082

**Comment by danielbachhuber** [comment]
Actually, `$autoload` support was added to `update_option()` in WP 4.2. It will be a version-contingent feature.
