### ISSUE TITLE
wp cli update

### ISSUE THREAD

**Issue by a1exus** [wp-cli/wp-cli#2084]
```
[alexus@j ~]$ sudo wp cli update
You have version 0.20.0. Would you like to update to 0.20.1? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v0.20.1/wp-cli-0.20.1.phar...

	                
	 php: not found 
	                
	                

Error: The downloaded PHAR is broken, try running wp cli update again.
[alexus@j ~]$ head -1 /usr/local/bin/wp
#!/usr/bin/env php
[alexus@j ~]$ which php
/usr/local/bin/php
[alexus@j ~]$ 
```

**Comment by danielbachhuber** [comment]
Can you try specifying the PHP binary with [one of these approaches](https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L431)?

**Comment by a1exus** [comment]
```
[alexus@j ~]$ for i in PHP_BINARY WP_CLI_PHP_USED WP_CLI_PHP ; do export $i=`which php` ; done
[alexus@j ~]$ sudo wp cli update
Password:
You have version 0.20.0. Would you like to update to 0.20.1? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v0.20.1/wp-cli-0.20.1.phar...

	                
	 php: not found 
	                
	                

Error: The downloaded PHAR is broken, try running wp cli update again.
[alexus@j ~]$ 
```

**Comment by danielbachhuber** [comment]
Bummer. It looks like we aren't actually paying attention to any of these: https://github.com/wp-cli/wp-cli/blob/bd5ecd48d116e341730927e9c6460b79e5024c47/php/commands/cli.php#L189

**Comment by szepeviktor** [comment]
A hardcoded string! :cry:

**Comment by danielbachhuber** [comment]
@a1exus Can you [install the nightly](https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods#installing-nightly-via-phar) and try `wp cli update --nightly` to verify #2085 did the trick?

**Comment by a1exus** [comment]
I would assume that also wouldn't work, since ```wp cli update``` didn't work at the first place...

**Comment by danielbachhuber** [comment]
> I would assume that also wouldn't work

How do you mean?

Use the install instructions here: http://wp-cli.org/#install

But replace the URL with that of the nightly Phar

**Comment by a1exus** [comment]
```
[alexus@j ~]$ wp cli version
WP-CLI 0.21.0-alpha-a2f40ae
[alexus@j ~]$ sudo wp cli update
Success: WP-CLI is at the latest version.
[alexus@j ~]$ 
```

**Comment by danielbachhuber** [comment]
@a1exus Run `wp cli update --nightly`, not `wp cli update`

**Comment by a1exus** [comment]
```
[alexus@j ~]$ sudo wp cli update --nightly
You have version 0.21.0-alpha-a2f40ae. Would you like to update to the latest nightly? [y/n] y
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release
[alexus@j ~]$ 
```

**Comment by danielbachhuber** [comment]
> wp cli update didn't work so using (or not) --nighly wouldn't make any difference,

Huh? `wp cli update --nightly` will always pull the latest nightly, regardless of which version you're currently running.

**Comment by a1exus** [comment]
right, the problem was that ```wp cli update``` wasn't working (that's the idea behind this issue), so after you guys fixed it and i pulled that nightly manually, now it will work for me)
