### ISSUE TITLE
wp 0.20.1 export does not terminate, using 100% cpu

### ISSUE THREAD

**Issue by hakan42** [wp-cli/wp-cli#2087]
Running wp-cli on my linux box exports my site, but then just sits there, consuming 100% CPU.
 
```
/usr/bin/php wp-cli-0.20.1.phar --debug --path=/var/www/my-blog --dir=/my-backup-dir/wp export
Starting export process...
Writing to file /my-backup-dir/my-blog.wordpress.2015-09-23.000.xml
Success: All done with export.
```

Is there any way I can further debug this?

**Comment by danielbachhuber** [comment]
Can you try with an [earlier release](https://github.com/wp-cli/wp-cli/releases) and see if you get the same results?
