### ISSUE TITLE
Introduce `WP_CLI::load_wordpress()` for commands running independent of WordPress

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2089]
A command running before WordPress loads should be able to call `WP_CLI::load_wordpress()` to load the entirety of WordPress.

Related https://github.com/wp-cli/wp-cli/issues/2086#issuecomment-142621625
Previously attempted in #524

**Comment by szepeviktor** [comment]
What is the problem with #524?

**Comment by danielbachhuber** [comment]
Nothing other than it's very old and likely needs to be revisited.

**Comment by danielbachhuber** [comment]
Reopening this because the `load_wordpress()` method needs to more sensibly check `$this->check_wp_version()` and:

```
if ( !Utils\locate_wp_config() ) {
			WP_CLI::error(
				"wp-config.php not found.\n" .
				"Either create one manually or use `wp core config`." );
		}
```

Even once these are in, I'm going to leave this open for a while for any unexpected explosions that occur.

**Comment by goldenapples** [comment]
One bug here: after ef2f66ecc12c5c4a87a7fd741c67c63ae20eefc4, custom urls and paths provided by command line flags or wp-cli.yml file configuration are no longer applied.

**Comment by danielbachhuber** [comment]
@goldenapples can you write a test case to reproduce?

**Comment by goldenapples** [comment]
> can you write a test case to reproduce?

Will do. Its been so long since I've mucked around in wp-cli, I'll have to refamilarize myself with its internals a bit.

**Comment by danielbachhuber** [comment]
After https://core.trac.wordpress.org/ticket/34217 lands, we'll want to replicate whichever approach core has taken.

**Comment by danielbachhuber** [comment]
Haven't heard of any more issues — :ship: :ship: :ship:
