### ISSUE TITLE
wp core config dbpass errors when using $ in a password.

### ISSUE THREAD

**Issue by jsilva7765** [wp-cli/wp-cli#2091]
This took a while for me to figure out. If your MYSQL user has a $ in the password the command errors and states there access denied. I know the password was correct, I decided to use the --skip-check flag and noticed that in the wp-config.php file it is changing the $ in the password to "bash". If you wrap the password with '' it works fine. You may want to add that to your website command instructions for linux beginners.

**Comment by danielbachhuber** [comment]
Hm. I'll give some thought as to where might be the best place for this.

**Comment by jsilva7765** [comment]
Thanks! It's a simple thing and I can't believe it took me a few hours to figure out what was going on. I am sure others may struggle with the same issue depending on the passwords they use. Cheers! Amazing project keep up the good work.

**Comment by danielbachhuber** [comment]
I don't think it makes sense to add documentation for this specific to `wp core config`, as `$` is one of many special characters in bash that can get you into trouble in a number of contexts.
