### ISSUE TITLE
Speed up testing

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#2093]
`eatmydata` disables fsync etc.
It would be very useful for running the tests.
https://packages.debian.org/jessie/eatmydata

**Comment by danielbachhuber** [comment]
Sorry, not sure I follow. How would this work?

**Comment by szepeviktor** [comment]
You add `eatmydata /usr/sbin/mysqld ....` in the init script, or to the test script `eatmydata wp-cli/bin/wp ...` and Linux kernel won't commit changes to the disk!

**Comment by danielbachhuber** [comment]
What would the performance gain be?

**Comment by szepeviktor** [comment]
I've deployed a new [Vultr VPS](http://www.vultr.com/?ref=6815796) with Debian jessie and behat ran for **15m5.034s**.
And now inserting `eatmydata` into `mysqld` and `bin/wp` and before the behat start command...

**Comment by szepeviktor** [comment]
Mounting /tmp in RAM would also help.

**Comment by szepeviktor** [comment]
A small negative gain **15m47.232s** :cry:

**Comment by szepeviktor** [comment]
Maybe industrial SSD-s are so fast and starting `eatmydata` takes a little bit of time.

**Comment by szepeviktor** [comment]
## FAILED
