### ISSUE TITLE
proc_open(): Descriptor item must ... etc, WP_CLI_PHP not being used?

### ISSUE THREAD

**Issue by Justin-Maxwell** [wp-cli/wp-cli#2095]
Hi.

I have a problem that I'm fairly sure is related to the wrong PHP binary being invoked. I can work around the problem.  

I've no idea how "/usr/newage/bin/php-5.4" is getting in there, but that path does seem to exist on our host.

Thanks.

```
bash-3.2$ pwd
/var/sites/s/staging.tibdit.com/subdomains/sep15/wordpress
```

```
bash-3.2$ wp export
Warning:  fwrite() expects parameter 1 to be resource, string given in phar:///var/sites/s/staging.tibdit.com/usr/bin/wp/php/WP_CLI/Loggers/Regular.php on line 24>
```

```
bash-3.2$ env | grep PHP
WP_CLI_PHP=/usr/bin/php-5.4-cli
```

```
bash-3.2$ which php-5.4-cli
/usr/bin/php-5.4-cli
```

```
bash-3.2$ which wp
/var/sites/s/staging.tibdit.com/usr/bin/wp
```

```
bash-3.2$ wp --info
Content-type: text/html

PHP binary:	/usr/newage/bin/php-5.4
PHP version:	5.4.42
php.ini used:	/usr/local/php54/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.20.1
```

```
bash-3.2$ /usr/bin/php-5.4-cli /var/sites/s/staging.tibdit.com/usr/bin/wp export
Starting export process...
Writing to file /var/sites/s/sep15.staging.tibdit.com/public_html/wordpress/tibitthemetrials.wordpress.2015-09-28.000.xml
^C
```

```
bash-3.2$ /usr/bin/php-5.4-cli /var/sites/s/staging.tibdit.com/usr/bin/wp --info
PHP binary:	/usr/bin/php-5.4-cli
PHP version:	5.4.42
php.ini used:	/usr/local/php54/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.20.1
```

**Comment by danielbachhuber** [comment]
Can you share `echo $PATH` ?

**Comment by danielbachhuber** [comment]
`WP_CLI_PHP` will only work when using Composer- or Git-based installation. The bash file is smart enough to look up the PHP binary based on the environment variable: https://github.com/wp-cli/wp-cli/blob/master/bin/wp#L33

However, because you're using the Phar archive, your user is using the first accessible PHP binary on your `$PATH`.

`which php` should point you to `/usr/newage/bin/php-5.4`

**Comment by Justin-Maxwell** [comment]
Hi, thanks.

I've cloned down the git, but I'm at a bit of a loss how to now install it on the hosting site.

For now, I've created a script, that seems to do the job.  Through some form of black magic, tab-completion half works...  I'm well outside my comfort zone, so any tips appreciated.  

```
#!/bin/bash
/usr/bin/php-5.4-cli ~/usr/bin/wp-cli "$@"

bash-3.2$ wp ex[tab][tab]
cli completions --line=wp ex --point=5  export 
bash-3.2$ wp ex
```

```
bash-3.2$ echo $PATH
/usr/local/bin:/bin:/usr/bin:/var/sites/s/staging.tibdit.com/usr/bin

bash-3.2$ which php
/usr/local/bin/php
```

**Comment by danielbachhuber** [comment]
You could also set an alias for `wp` to include the path to the PHP binary you want to use.

It doesn't seem like this is a bug in WP-CLI though.

**Comment by Justin-Maxwell** [comment]
Agree - I'd suggest some short additional instructions though, especially
around the use of the WP_CLI_PHP var, and other ways to 'hardcode' which
php executable to run (i.e. basically just explaining what you've set out
above)

Cheers.



[image: tibdit icon] <http://www.tibdit.com/> tibdit
<http://www.tibdit.com/>

@tibdit on twitter <http://www.twitter.com/tibdit>

Facebook page <https://www.facebook.com/pages/tibdit/470144859751000>

Google+ page <https://plus.google.com/+tibditMicropayments/posts>
justin maxwell ceo & founder

@Justin_Maxwell_ <http://twitter.com/Justin_Maxwell_>

linkedin.com/in/tibditJustin

**Comment by wojsmol** [comment]
@Justin-Maxwell see https://github.com/wp-cli/wp-cli/issues/956
