### ISSUE TITLE
Paginate output on Windows

### ISSUE THREAD

**Issue by borekb** [wp-cli/wp-cli#2099]
WP-CLI [disables pagination on Windows](https://github.com/wp-cli/wp-cli/blob/6d0062e7edf8ac95a2d892dc9179adb8df9bf1b7/php/commands/help.php#L93) which I am not sure why.

I think WP-CLI should behave this way:

 1. Try `less` first (Windows power users will have this available e.g. through *Git for Windows*)
 2. If it isn't available, use `more` ([docs](http://ss64.com/nt/more.html))

**Comment by borekb** [comment]
(Creating this issue separately from #2051 where it was first discovered; will try to prepare pull request for it.)

**Comment by danielbachhuber** [comment]
> WP-CLI disables pagination on Windows which I am not sure why.

e3d50372fb740c7a6cab8780aaf13f0a23a3aed2

Do you have a Windows environment to test with?

**Comment by borekb** [comment]
Yes I am on Windows and really keen to get this working :)

**Comment by borekb** [comment]
@danielbachhuber BTW do I think correctly that (on Linux / Mac OS X systems) the help output doesn't stay in the console? The `less` pages seems to discard the output as soon as you quit it, right? In some cases, I would like to keep the help output in the history but I guess that would be for another ticket.

**Comment by borekb** [comment]
It is a bit tricky. This is the code I've tried:

```php
$pagers = array( 'less -r', 'more' );

foreach	($pagers as $pager) {
	$exitCode = proc_close( proc_open( $pager, $descriptorspec, $pipes ) );
	if ($exitCode == 0) {
		return;
	}
}
```

It will mostly work but will leave the ugly "'less' is not recognized as an internal or external command,
operable program or batch file." message in the console. I don't think there is an easy way to get rid of that, only a couple of workarounds like executing less separately just to find out if it is available, which seems wasteful.

My feeling is that the pages should be user-configurable, with some default values like `less` on Linux and `more` on Windows. Personally, even if I were on Linux, I'd probably prefer `less -X` rather than `less -r` so it would be nice if I could influence this through config.yaml or configuration in general.

Just putting my thoughts down, I'll probably start by hardcoding `more` for Windows.

**Comment by danielbachhuber** [comment]
> Personally, even if I were on Linux, I'd probably prefer less -X rather than less -r so it would be nice if I could influence this through config.yaml or configuration in general.

What if we allowed for an override via environment variable? This could potentially let you disable paging entirely.

**Comment by borekb** [comment]
Are environment variables part of standard configuration mechanism? If not, putting it into `config.yml` feels more in line with the rest of WP-CLI.

**Comment by danielbachhuber** [comment]
> Are environment variables part of standard configuration mechanism?

They're typically used for system configuration.

For instance, `WP_CLI_PHP` can be used to define the path to your preferred PHP binary: https://github.com/wp-cli/wp-cli/blob/master/bin/wp#L33

Similarly, `WP_CLI_CONFIG_PATH` lets you specify the path to your global config: https://github.com/wp-cli/wp-cli/blob/b6c08973a432aa0fb7273f625748637426384b43/php/WP_CLI/Runner.php#L64

> If not, putting it into config.yml feels more in line with the rest of WP-CLI.

I'm not really keen on making `config.yml` a dumping ground for every option we can come up with. For really low-level customizations, I think environment variables make more sense.

**Comment by borekb** [comment]
What pager to use feels similar to me to whether to colorize the output or not, i.e., it is a UI configuration, not a system configuration. But whatever the way I would be happy to be able to customize this.

**Comment by danielbachhuber** [comment]
Let's go with an environment variable.

**Comment by borekb** [comment]
I've created a separate issue for that as I believe just enabling `more` on Windows (PR #2100) is enough for this issue to be closed.

**Comment by danielbachhuber** [comment]
:ship: Thanks for creating the second issue.
