### ISSUE TITLE
Setting blog_public option does not work

### ISSUE THREAD

**Issue by grantnorwood** [wp-cli/wp-cli#2101]
When calling `wp option update blog_public 1` or `wp option update blog_public 0`, neither command actually updates the option in the db.

There have been some similar issues (https://github.com/wp-cli/wp-cli/issues/1597, https://github.com/wp-cli/wp-cli/pull/634), and a fix from @scribu for one of those (f98a6f1) back in 2013, but I'm seeing some weird behavior.

*Here's my test:*
```shell
# Check the current value.
wp option get blog_public
# returns 0

# Try to make the site public.
wp option update blog_public 1
# returns "Error: Could not update option 'blog_public'."

# Check the value again.
wp option get blog_public
# returns 0 (Should be 1)

# Try to discourage search engines.
wp option update blog_public 0
# returns "Success: Value passed for 'blog_public' option is unchanged."

# Check the value again.
wp option get blog_public
# returns 0

# Try to make the site public using "wp db query".
wp db query "UPDATE wp_options SET option_value = 1 WHERE option_name = 'blog_public';"

# Check the value again.
wp option get blog_public
# returns 0 (Should be 1)

# Check the value using "wp db query".
wp db query "SELECT option_value FROM wp_options WHERE option_name = 'blog_public';"
# returns "1" (correct!)

# Set the option back to 0.
wp option update blog_public 0
# returns "Success: Value passed for 'blog_public' option is unchanged." (It was set to 1, this should've changed)

# Try to set to 0 using "wp db query".
wp db query "UPDATE wp_options SET option_value = 0 WHERE option_name = 'blog_public';"

# Check the value again.
wp option get blog_public
# returns 0 (correct!)

# Check the value using "wp db query".
wp db query "SELECT option_value FROM wp_options WHERE option_name = 'blog_public';"
# returns "0" (correct!)

# Ok, now try to use "wp option set" command (undocumented?)
wp option set blog_public 1
# returns "Success: Updated 'blog_public' option."

# Check the value again.
wp option get blog_public
# returns 0 (wait ... i thought we just set this to 1)

# Check the value using "wp db query".
wp db query "SELECT option_value FROM wp_options WHERE option_name = 'blog_public';"
# returns "1" (correct!)
```

I am using the latest v0.20.1 of wp-cli.  It was very weird to see that the "wp option set" command worked, as I don't see any documentation on that.

Thanks for the help!
gkn

**Comment by danielbachhuber** [comment]
Can you share your environment details, including any persistent object cache you may be running?

**Comment by grantnorwood** [comment]
Using the [Roots.io Trellis stack](https://roots.io/trellis/) (Ubuntu 14.04 Trusty LTS, Nginx, MariaDB, PHP 5.6 + Composer, WP-CLI, sSMTP, Memcached, Fail2ban, ferm)

Here's my `wp --info`:
```shell
PHP binary:	/usr/bin/php5
PHP version:	5.6.13-1+deb.sury.org~trusty+3
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	/srv/www/example.com/current/wp-cli.yml
WP-CLI version:	0.20.1
```

No caching plugins installed, but here's my plugin list:
```shell
$ wp plugin list --status=active
+----------------------------+--------+--------+----------+
| name                       | status | update | version  |
+----------------------------+--------+--------+----------+
| advanced-custom-fields-pro | active | none   | 5.3.0    |
| taxonomy-terms-order       | active | none   | 1.4.6.1  |
| geoip-detect               | active | none   | 2.5.2    |
| gravityforms               | active | none   | 1.9.13.7 |
| members                    | active | none   | 1.0.2    |
| multiple-post-thumbnails   | active | none   | 1.6.6    |
| pods                       | active | none   | 2.5.5    |
| taxonomy-images            | active | none   | 0.8.0    |
| wordpress-seo              | active | none   | 2.3.5    |
+----------------------------+--------+--------+----------+
```

Let me know if you need anything else!

**Comment by danielbachhuber** [comment]
@grantnorwood did you get this sorted out?can you share the contents of `/srv/www/example.com/current/wp-cli.yml`?

**Comment by grantnorwood** [comment]
I honestly haven't come back to this, but I can take another look in a couple days.

My `wp-cli.yml` file simply contains:
```yaml
path: web/wp
```

Thank you for following up, Daniel!

**Comment by here** [comment]
Confirming that this now works to toggle the "Search Engine Visibility" setting under Settings -> Reading Settings

wp option update blog_public 0

**Comment by nonameolsson** [comment]
This isn't solved for me :-/ I can't do this on my development machine, nor on the staging and production server. I get the same error messages as above.

Does this work for you?

**Comment by johnfitz00** [comment]
I was also getting the `Error: Could not update option 'blog_public'.` error and unable to get `wp option update blog_public 1` to work.

For anyone coming across this problem, I found a solution that worked for me:
`wp db query "UPDATE $(wp db prefix)options SET option_value = 1 WHERE option_name = 'blog_public';"`

**Comment by michaelw85** [comment]
For anyone stumbling on this old thread, and using roots.io bedrock setup, keep in mind if you are using a non production environment the `disallow-indexing` mu plugin will always return 0.
