### ISSUE TITLE
`wp core check-update` does not return empty value as documented when no update is available

### ISSUE THREAD

**Issue by chrisbloom7** [wp-cli/wp-cli#2102]
The [docs](http://wp-cli.org/commands/core/check-update/) for this method specify "Returns latest version if there’s an update, or empty if no update available", however when no update is available it actually reports "Success: WordPress is at the latest version.". You have to pass the `--quiet` tag to suppress that message, though I'm not sure what affect that would have on the output if an update was legitimately available. The docs should be updated to reflect the actual return value, or the command should assume `--quiet` (and possibly have a way to force it to be noisy).

**Comment by danielbachhuber** [comment]
I'll fix the docs.
