### ISSUE TITLE
Use space separated --post__in in export command

### ISSUE THREAD

**Issue by joshlevinson** [wp-cli/wp-cli#2103]
The `wp export` command accepts a `post__in` argument. However, the argument only accepts a comma separated list. This doesn't fit in well with the ability to chain wp cli commands. If I want to export posts with a query whose filters fall outside the normal export filters (i.e. chaining in the results of `wp post list --format=ids`), I'm unable to do so because `wp post list` yields a space separated list.
I propose that `wp export`'s `post__in` parameter accept a space separated list instead of the current comma separated list.

**Comment by danielbachhuber** [comment]
What are you trying to do?

**Comment by joshlevinson** [comment]
Example: `wp export --post__in="$(wp post list --channel=opinion --posts_per_page=5 --format=ids)"`
where `opinion` is a term in the custom `channel` taxonomy
