### ISSUE TITLE
core download command not working on HHVM

### ISSUE THREAD

**Issue by steelbrain** [wp-cli/wp-cli#2107]
```sh
/v/w/h/wp ❯❯❯ hhvm wp.phar  core download
Downloading WordPress 4.3.1 (en_US)...
Error: Couldn't extract WordPress archive. DirectoryIterator::__construct(/tmp/steel/wp_560f87fdd697e/): failed to open dir
```
```sh
/v/w/h/wp ❯❯❯ php wp.phar core download                                                                                                             ⏎
Downloading WordPress 4.3.1 (en_US)...
Success: WordPress downloaded.
```
```sh
/v/w/h/wp ❯❯❯ rm -rf *
zsh: sure you want to delete all the files in /var/www/html/wp [yn]? y
/v/w/h/wp ❯❯❯ hhvm wp.phar core download
Downloading WordPress 4.3.1 (en_US)...
Using cached file '/home/steel/.wp-cli/cache/core/wordpress-4.3.1-en_US.tar.gz'...
Warning: Extraction failed, downloading a new copy...
```
The extraction seems to be failing
Digging the repo source pointed me at https://github.com/wp-cli/wp-cli/blob/213e43ff7346fe5eafe2c91d3b5efd5057094aa2/php/commands/core.php#L199
so I checked if the class `PharData` exists, and it does. It spawns a process there, the codebase of wp-cli looks like it was written in a hurry so I gave up on that point.
Any help would be appreciated.

**Comment by danielbachhuber** [comment]
WP-CLI doesn't support HHVM, see past conversations: https://github.com/wp-cli/wp-cli/search?q=hhvm&type=Issues&utf8=%E2%9C%93

**Comment by steelbrain** [comment]
Is it going to stay that way or are we going to add support for it?

**Comment by danielbachhuber** [comment]
No plans to add support at this time.
