### ISSUE TITLE
documentation: --post_type="x" works for post list

### ISSUE THREAD

**Issue by Justin-Maxwell** [wp-cli/wp-cli#2108]
... which is very handy, but doesn't seem to be in the docs or the tab-completions.

**Comment by danielbachhuber** [comment]
The docs [state](http://wp-cli.org/commands/post/list/):

```
[--<field>=<value>]
One or more args to pass to WP_Query.
```

This means `wp post list` accepts arbitrary key=>value pairs supported by `WP_Query`.
