### ISSUE TITLE
Allow `help` pager customization

### ISSUE THREAD

**Issue by borekb** [wp-cli/wp-cli#2110]
As discussed in #2099, it would be useful to be able to customize what pager the `help` command uses. For example, the default `less -r` doesn't leave any output in the console history, or some users on Windows might prefer `less` instead of `more` if they have that installed, or someone might prefer to have the paging disabled entirely.

Some relevant quotes from the aforementioned issue:

@borekb:

> My feeling is that the pages should be user-configurable, with some default values like less on Linux and more on Windows. Personally, even if I were on Linux, I'd probably prefer less -X rather than less -r so it would be nice if I could influence this through config.yaml or configuration in general.

@danielbachhuber:

> What if we allowed for an override via environment variable? This could potentially let you disable paging entirely.

> I'm not really keen on making config.yml a dumping ground for every option we can come up with. For really low-level customizations, I think environment variables make more sense.

@borekb:

> What pager to use feels similar to me to whether to colorize the output or not, i.e., it is a UI configuration, not a system configuration. But whatever the way I would be happy to be able to customize this.

@danielbachhuber:

> Let's go with an environment variable.

**Comment by bretweinraub** [comment]
use $PAGER ! ;)

**Comment by rodrigoprimo** [comment]
Related: #1519
