### ISSUE TITLE
Unable to run wp server with recent upgrade (0.20.1)

### ISSUE THREAD

**Issue by mvattuone** [wp-cli/wp-cli#2114]
Hey folks, love this package so much.  

I recently upgraded via wp-cli.org to see if that would help with wp server running extremely slow, but now I am encountering a strange error whenever I run the command to init a new local server (i.e. wp server):

```
Cannot redeclare class Server_Command in /Users/vattuonet/.wp-cli/commands/server/command.php on line 51
```

Not really sure how to debug that, aside from reinstalling (which I tried to no avail).  It does look like Github has a newer alpha version, but not sure if I should try that or not...

Here's the output of wp --info:

```
PHP binary:	/usr/bin/php
PHP version:	5.5.27
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	/Users/vattuonet/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	0.20.1
```

Let me know if you can help.  Thanks!

**Comment by danielbachhuber** [comment]
> I recently upgraded via wp-cli.org to see if that would help with wp server running extremely slow, but now I am encountering a strange error whenever I run the command to init a new local server (i.e. wp server):

`wp server` was [added to WP-CLI in v0.20.0](http://wp-cli.org/blog/version-0.20.0.html), which is why you're getting the fatal. Sorry about that :(

You'll want to remove it from wherever you're requiring it from now, and use the version packaged with WP-CLI.

**Comment by mvattuone** [comment]
I'm confused.  I've never required this anywhere directly, AFAIK.  I don't seem to recall having to do anything special to have wp server work before.  

Going to dig into older issues but... yeah, not really sure what to do.

**Comment by danielbachhuber** [comment]
> I don't seem to recall having to do anything special to have wp server work before.

It looks like it's installed to `/Users/vattuonet/.wp-cli/commands/server/command.php` You can remove that copy.

**Comment by mvattuone** [comment]
Oh jeez, I see what you mean.  Forgive my denseness there.

We're good!  Thanks Daniel.
