### ISSUE TITLE
wp core download does not download .htaccess file

### ISSUE THREAD

**Issue by robojamison** [wp-cli/wp-cli#2115]
Running the following command:

`wp core download --path=.`

does not download/obtain the .htaccess file that is distributed with WordPress that enables mod_rewrite to work. The file must be manually downloaded and added to the installation.

Using WP-CLI 0.20.1
Output of `wp --info` is as follows:

```
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.13
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.20.
```

**Comment by borekb** [comment]
`.htaccess` is no longer distributed with WordPress (despite [Codex suggesting otherwise](https://codex.wordpress.org/htaccess)), it is generated on-the-fly as the permalink settings are updated.
