### ISSUE TITLE
Malloc error

### ISSUE THREAD

**Issue by Fab1en** [wp-cli/wp-cli#2128]
I get a strange error with the wp-cli version 0.20.1 :
```
$>wp plugin install contact-form-7
Installing Contact Form 7 (4.3)
Téléchargement de l&rsquo;archive d&rsquo;installation depuis https://downloads.wordpress.org/plugin/contact-form-7.4.3.zip...
php: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Abandon
```
I tried the same command a few time after, and it worked as expected. I just wanted to log this issue for information.

**Comment by danielbachhuber** [comment]
Thanks for reporting. I haven't ever seen this before, and it seems unrelated to WP-CLI internals.
