### ISSUE TITLE
Allow wildcard in plugin/theme names (Feature Request)

### ISSUE THREAD

**Issue by indietravel** [wp-cli/wp-cli#2132]
Would love to be able to use wildcards in commands, e.g. 
`wp theme delete twenty*`

**Comment by danielbachhuber** [comment]
Hm. Can you think of any other themes or plugins you'd use this for, other than `twenty*` ?

**Comment by indietravel** [comment]
Good question: internally, we have some development plugins that also have the same prefix, so we'd also use it to kill them/toggle them if this was available.

**Comment by danielbachhuber** [comment]
I can't say I'm convinced this is a 80% use case, or that it wouldn't cause some unexpected bugs. I'd say probably not for now, but we can reconsider it later if someone else brings it up.

**Comment by dwainm** [comment]
Hi @danielbachhuber, thank you for the awesome work you gusy are putting into WP-Cli.

Do you think it would it be possible to reconsider this? 

We deal with many plugins in our workflow. Enabling and disabling them all the time. It would be really helpful if we could call:
`wp plugin activate *long-plug* `

This compared to having to write out 'extremely-long-wordpress-plugin-slug-text'

**Comment by danielbachhuber** [comment]
@dwainm I'm not going to include this in WP-CLI, but you're welcome to write your own command for it, and publish it in the package index.

I've spent a bit of time retooling the [Commands Cookbook](http://wp-cli.org/docs/commands-cookbook/) to give you a heads start. Let me know what you think of it.
