### ISSUE TITLE
Possible to install theme from private repo?

### ISSUE THREAD

**Issue by jonathan-dejong** [wp-cli/wp-cli#2135]
Hi!

Just looking to see wether it would be possible to install a theme and/or plugin from a private github repo?

Can't find any documentation about it.. 

The background story is that we use Varying vagrant vagrants https://github.com/Varying-Vagrant-Vagrants/VVV for local development and I'm customizing the bash script that uses WP CLI for installing WP etc. 
I would like to be able to install our core theme and some plugins from private repos here on Github to further automise the setup of a new site :) 

Very grateful for any leads!

**Comment by danielbachhuber** [comment]
> I'm customizing the bash script that uses WP CLI for installing WP etc. 
> I would like to be able to install our core theme and some plugins from private repos here on Github to further automise the setup of a new site :)

You should just use `git clone ...` in your bash script, instead of calling WP-CLI.

WP-CLI doesn't support managing git repos, see #1557, nor does it handle the authentication process needed to connect to private repos.

**Comment by jonathan-dejong** [comment]
Thanks for the info Daniel!

I've actually looked into Composer now and it seems a good way to go.. now to get it working with my private repos instead! ;)

**Comment by XedinUnknown** [comment]
Sorry to resurrect this, but this is the thread I found related to my problem.

Using Composer to install from private repo is not a good idea when you need to install _built_ plugins, because even the `dist` automatically created by Github does not contain the built version. It only contains compressed minimal version of the codebase.
