### ISSUE TITLE
Wordpress core latest minor update problem

### ISSUE THREAD

**Issue by dfisek** [wp-cli/wp-cli#2137]
I was looking for a command to update to the latest minor update of Wordpress.

I can get the latest minor version with this:
```wp core check-update```

Then manually update to it:
```wp core update --version=whatever_version_i_got_from_the_previous command```

When I tried to list only the latest minor version update with this:
```wp core check-update --minor```

It only said:
```Success: WordPress is at the latest version.```

I got what I wanted :). The site was updated to the latest minor version.

However I believe this is a bug, since the command was to actually "check" the update, not to make it.

So I think we need a new parameter for the update module like this:
```wp core update --minor```

We also need to fix the functionality of check-update modules --minor parameter.

**Comment by danielbachhuber** [comment]
> However I believe this is a bug, since the command was to actually "check" the update, not to make it.

Didn't you run `wp core update --version=whatever_version_i_got_from_the_previous command` ?

**Comment by dfisek** [comment]
Sorry I must have missed the previous comment.

No, I hadn't. But I can't reproduce the behavior now. Sorry for a non-reproducable bug report :(.

What do you think about a parameter to update to the latest minor version functionality? (e.g.: `wp core update --minor`)

**Comment by danielbachhuber** [comment]
> What do you think about a parameter to update to the latest minor version functionality? (e.g.: wp core update --minor)

It's a good idea, and already tracked with #1850

**Comment by dfisek** [comment]
Thank you, I had had looked at older issues but I must have missed this one too :(.

**Comment by hdGuild** [comment]
Hello all.

I just have the same pbm that dfisek above.
`wp core version --path=/var/www/html/`
`4.7.1`
`wp core check-update --path=/var/www/html/`
`Success: WordPress is at the latest version.`
`wp core version --path=/var/www/html`
`4.7.2`

That's a bit a pitty as I just began to use this beautifull tool ^^
