### ISSUE TITLE
search-replace on multisite with --network switch throws error

### ISSUE THREAD

**Issue by nbyloff** [wp-cli/wp-cli#2146]
I pulled a multisite DB from another environment and tried to do a search-replace after running the ```wp db import``` locally. Using the nightly build, ran the command below, with the results.

```javascript
vagrant@mydomain:/srv/www/mydomain.dev/current$ wp search-replace 'http://stg.mydomain.com' 'http://mydomain.dev' --network --debug
Debug: No readable global config found (0.032s)
Debug: Using project config: /srv/www/mydomain.dev/current/wp-cli.yml (0.036s)
Debug: ABSPATH defined: /srv/www/mydomain.dev/current/web/wp/ (0.039s)
Debug: Begin WordPress load (0.047s)
Debug: wp-config.php path: /srv/www/mydomain.dev/current/web/wp-config.php (0.049s)
PHP Warning:  Unterminated comment starting line 22 in phar:///usr/bin/wp/php/WP_CLI/Runner.php(731) : eval()'d code on line 22
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///usr/bin/wp/php/WP_CLI/Runner.php:697
Debug: Set URL: mydomain.dev/ (0.11s)
Error: Site mydomain.dev/ not found.
vagrant@mydomain:/srv/www/mydomain.dev/current$
```

If I update the tables ```wp_site``` and ```wp_blogs``` manually with my local domain, ```search-replace``` works just fine.

**Comment by danielbachhuber** [comment]
> Using the nightly build, ran the command below, with the results.

Do you get the same error with v0.20.0?

Just to be clear, what do you see the bug as?

**Comment by nbyloff** [comment]
@danielbachhuber It is still unsuccessful, but the error is different with v0.20.0. In that version, it doesn't find my domain name, which I believe was fixed in a previous ticket. (See below for output)

As far as this bug, my expected use case was to be able to ```wp db import``` from a different environment, then do a ```wp search-replace old new``` like you can with a standard Wordpress install. However it appears, the ```search-replace``` function does a check to make sure the ```wp_site``` and ```wp_blogs``` represent the local domain in my config file before it can even update the domains.

I don't know much about the inner workings, but I would think 1) ```search-replace``` should skip this domain check when ```--network``` is present so it doesn't fail replacing the old domain because it's already expecting the new domain at that point or 2) add a ```--force``` option that allows the user to ignore the failure of finding the correct domain name and continue on updating all tables within the DB.

```javascript
vagrant@mydomain:/srv/www/mydomain.dev/current$ wp search-replace 'http://stg.mydomain.com' 'http://mydomain.dev' --network --debug
PHP Warning:  Unterminated comment starting line 22 in phar:///usr/bin/wp/php/wp-cli.php(23) : eval()'d code on line 22
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
PHP Notice:  Undefined index: HTTP_HOST in /srv/www/mydomain.dev/current/web/wp/wp-includes/ms-settings.php on line 30
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
PHP   4. require() phar:///usr/bin/wp/php/wp-cli.php:26
PHP   5. require() phar:///usr/bin/wp/php/wp-settings-cli.php:114
Error: Site  not found.
vagrant@mydomain:/srv/www/mydomain.dev/current$
```

**Comment by danielbachhuber** [comment]
If `stg.mydomain.com` is stored in the database, you'll need to run:

```
wp search-replace 'http://stg.mydomain.com' 'http://mydomain.dev' --network --debug --url=stg.mydomain.com
```

`--url=stg.mydomain.com` lets WP-CLI know which host context in which to load WordPress. See the example in the documentation:

```
# Turn your production database into a local database
wp search-replace --url=example.com example.com example.dev
```
