### ISSUE TITLE
Get cron array wrongly fetched from Cache

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wp-cli/wp-cli#2149]
The command `wp cron event list` will **always** list the wrong data when cache is present. It uses `_get_cron_array()`, which relies on [`get_option('cron');`](https://github.com/wp-cli/wp-cli/blob/master/php/commands/cron.php#L277). Problem is that Cron is cached and the option with `option_name` of `cron` should be fetched directly from the DB with a raw query.

**Comment by danielbachhuber** [comment]
How does core do it differently?

**Comment by franz-josef-kaiser** [comment]
It does not. That's the problem. Just had that with Memcached. Alloptions array is [cached](https://github.com/WordPress/WordPress/blob/537ac4c2ec0410bd44858ac93e6432d8671b6db4/wp-includes/option.php#L175).

**Comment by danielbachhuber** [comment]
Isn't this a bug with core then? Why isn't the cache being cleared?

**Comment by franz-josef-kaiser** [comment]
I'd say, it should get fixed where it's needed. When I look at how long some of my tickets are rotting in trac…

**Comment by danielbachhuber** [comment]
Why isn't the cache being cleared when cron is updated?

**Comment by danielbachhuber** [comment]
@franz-josef-kaiser Were you able to track down why the cache isn't being cleared when cron is updated?

**Comment by r-a-y** [comment]
I'm experiencing the same problem with memcached.

If I use `wp cron event list` and compare it to the cron event list generated by the WP-Crontrol plugin, the list is different.  WP-Crontrol appears to have a more, updated event list even though both wp-cli and WP-Crontrol are using `_get_cron_array()`.
