### ISSUE TITLE
relative "path" in config file taken relative to that file

### ISSUE THREAD

**Issue by rolfkleef** [wp-cli/wp-cli#2154]
I'm attempting to work with configuration files.

When I start a new project, I'd like Wordpress to be loaded in the directory www, so I tried adding `path: www` to my global `~/.wp-cli/config.yml`.

When I do a `wp core download`, it does so in `~/.wp-cli/www/`.

If I create a `wp-cli.yml` in my project directory, with the setting `path: www`, it does create the subdirectory www in there.

I had expected the relative path in both cases to be relative to where I run the wp command, not to where the config file is?

**Comment by danielbachhuber** [comment]
> I had expected the relative path in both cases to be relative to where I run the wp command, not to where the config file is?

Ok. It sounds like the actual behavior is different than your expectation then. If you use a relative path in your config file, WP-CLI will interpret it as relative to the config file.
