### ISSUE TITLE
`wp term get` should support term slug

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/wp-cli#2156]
I would like to be able to get a term by the slug. Currently this command support only term id. Should I open a PR?

**Comment by danielbachhuber** [comment]
Because term slugs can be numeric, we can't easily support getting a term by slug _or_ id.

In the interim, you could use `wp term list <taxonomy> --slug=<slug>`

Related https://github.com/wp-cli/wp-cli/issues/894#issuecomment-57939790

**Comment by danielbachhuber** [comment]
I don't think we'll ever make this breaking change, given `wp term list` will eventually be a wrapper for a REST request. #1784

For the history on why WP-API doesn't support getting an individual Resource by slug, see https://github.com/WP-API/WP-API/issues/642
