### ISSUE TITLE
wp-cli not working for Debian WordPress installations?

### ISSUE THREAD

**Issue by borissamardzija** [wp-cli/wp-cli#2157]
Hello,

I have WordPress installation that's installed from [Debian's oldstable (Wheezy) repository](https://packages.debian.org/wheezy/wordpress) that uses Debian customized  [wp-config.php](https://sources.debian.net/src/wordpress/3.6.1%2Bdfsg-1~deb7u6/debian/wp-config.php/).

```
bsamardz@srv:/usr/share/wordpress$ wp --info
PHP binary:     /usr/bin/php5
PHP version:    5.4.45-0+deb7u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.21.0-alpha-9a90e8b
```

When I try to run wp-cli, I get this

```
bsamardz@srv:/usr/share/wordpress$ wp theme list --debug
Debug: No readable global config found (0.011s)
Debug: No project config found (0.012s)
Debug: ABSPATH defined: /usr/share/wordpress/ (0.029s)
Debug: Begin WordPress load (0.03s)
Debug: wp-config.php path: /usr/share/wordpress/wp-config.php (0.03s)
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(731) : eval()'d code on line 10
Neither <b>/etc/wordpress/config-.php</b> nor <b>/etc/wordpress/config-.php</b> could be found. <br/> Ensure one of them exists, is readable by the webserver and contains the right password/username.
```

Any ideas how to get it working?

**Comment by danielbachhuber** [comment]
`$_SERVER['HTTP_HOST']` isn't set, so your file lookup isn't working: https://sources.debian.net/src/wordpress/3.6.1%2Bdfsg-1~deb7u6/debian/wp-config.php/#L11

You can specify `--url` when you run `wp theme list`, or you define it in a project or global config.

Alternatively, you can edit `wp-config.php` to load the right file, instead of doing a fancy lookup based on `$_SERVER['HTTP_HOST']`

**Comment by borissamardzija** [comment]
Hmm, good idea, tried that also (editing wp-config.file to remove fancy lookup), but then it clashes with [domain mapping plugin](https://wordpress.org/plugins/wordpress-mu-domain-mapping/)

```
bsamardz@srv:/usr/share/wordpress$ wp themes list --debug
Debug: No readable global config found (0.01s)
Debug: No project config found (0.011s)
Debug: ABSPATH defined: /usr/share/wordpress/ (0.012s)
Debug: Begin WordPress load (0.012s)
Debug: wp-config.php path: /usr/share/wordpress/wp-config.php (0.012s)
PHP Warning:  Creating default object from empty value in /usr/share/wordpress/wp-content/sunrise.php on line 10
PHP Fatal error:  Call to undefined method stdClass::escape() in /usr/share/wordpress/wp-content/sunrise.php on line 11
```

**Comment by imran-uk** [comment]
Same issue, I bypassed this by simplifying the filename selection like this:

```
/* Look up a host-specific config file in
  * /etc/wordpress/config-<host>.php or /etc/wordpress/config-<domain>.php
  */
 //$debian_server = preg_replace('/:.*/', "", $_SERVER['HTTP_HOST']);
 //$debian_server = preg_replace("/[^a-zA-Z0-9.\-]/", "", $debian_server);
 //$debian_file = '/etc/wordpress/config-'.strtolower($debian_server).'.php';
 /* Main site in case of multisite with subdomains */
 //$debian_main_server = preg_replace("/^[^.]*\./", "", $debian_server);
 //$debian_main_file = '/etc/wordpress/config-'.strtolower($debian_main_server).'.php';

 $debian_file = '/etc/wordpress/config-<actual name of file>.php';
```

**Comment by hugovolzoliveira** [comment]
Hi @imran-uk, can you explain where should I put your filename selection solution?

**Comment by imran-uk** [comment]
Sorry for late reply. Glad you got it working.

I now run several WordPress installations on one Debian server directly
from wordpress.org, I found that some essential plugins did not work with
the older version in Debian Stable. It's pretty easy to keep them updated
via the built in update mechanism. Just one click.

Now that Debian is using more up-to-date WordPress though this isn't so
much an issue.
