### ISSUE TITLE
HTML corrupted 

### ISSUE THREAD

**Issue by e-webstyle** [wp-cli/wp-cli#2167]
when I run most any wp-cli command I get `<!-- html is corrupted -->` appended to the output.
For instance

`wp core update`
`Success: WordPress is up to date.`
`<!-- html is corrupted -->`

or

`wp eval 'echo home_url();'`
`http://example.com<!-- html is corrupted -->`

Why is this?

**Comment by rmccue** [comment]
This seems like you have a misbehaving cache plugin; neither wp-cli nor WordPress itself have anything like this message.

**Comment by danielbachhuber** [comment]
You can use `wp plugin list` to see your installed plugins, and then `wp eval 'echo home_url();' --skip-plugins=<plugin-slug>` to debug which plugin is causing the issue.

**Comment by e-webstyle** [comment]
Thanks guys. That was a cache plugin indeed.
