### ISSUE TITLE
wp core install --url is broken

### ISSUE THREAD

**Issue by elnicknamio** [wp-cli/wp-cli#2168]
wp core always takes localfile path plus the url param value in version 0.20.2:

wp core install --url="localhost/wp_test" --title="$sitename" --admin_user="$wpuser" --admin_password="$wppassword" --admin_email="$wpemail"

result:

the site_url param in the table "wp_options" is set to: "localhost/wp_testApplications/MAMP/htdocs/wp_test"

On Mac 10.11, MAMP Pro 3.4, WP-CLI 0.20.2

**Comment by danielbachhuber** [comment]
This may be a problem with core's `wp_guess_url()`. `wp core install` is mostly a wrapper for `wp_install()`, which uses `wp_guess_url()`.

WP-CLI parses `--url` correctly to set `HTTP_HOST` and `REQUEST_URI`:

```
wp> WP_CLI\Utils\parse_url( 'localhost/wp_test' );
array(3) {
  ["scheme"]=>
  string(4) "http"
  ["host"]=>
  string(9) "localhost"
  ["path"]=>
  string(8) "/wp_test"
}
```

What does the `home` option get set to? And, if you set `WP_SITEURL` to the correct value in `wp-config.php`, does `wp core install` work properly?

**Comment by elnicknamio** [comment]
Thanks,
WP_SITEURL works for me.

the solution for me:
$url => http://localhost/wp_test

wp core config --dbname="$dbname" --dbuser="$dbuser" --dbpass="$dbpass" --dbhost="$dbhost" --extra-php <<PHP
define( 'WP_SITEURL', '$url' );
PHP

===

(@daniel: the home option had the same value as site_url)

**Comment by gbcxjoe** [comment]
this worked

wp core config --dbname="$dbname" --dbuser="$dbuser" --dbpass="$dbpass" --dbhost="$dbhost" --extra-php <<PHP
define( 'WP_SITEURL', '$siteurl' );
PHP

thanks

**Comment by lukapaunovic** [comment]
This is an issue, how do I fix that without this creepy workaround?
because in database site url stays wrong.
Why is it adding path if I define site URL via `--url`
