### ISSUE TITLE
Install multiple plugins of specific version

### ISSUE THREAD

**Issue by dtolj** [wp-cli/wp-cli#2169]
This command fails where it complains about the last plugin's version number. Installing addthis 5.0.8 on its own works fine.

wp plugin install active-directory-integration --version=1.1.7 addthis --version=5.0.8 --allow-root
Error: Can't find the requested plugin's version 5.0.8 in the WordPress.org plugin repository (HTTP code 404).

PHP binary:     /opt/rh/php54/root/usr/bin/php
PHP version:    5.4.40
php.ini used:   /opt/rh/php54/root/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.20.2

**Comment by danielbachhuber** [comment]
WP-CLI only supports supplying `--version` once. If you want to use separate versions of separate plugins, you can just call `wp plugin install` twice.

**Comment by dtolj** [comment]
I have dozens of plugins and I want the beauty of a one-liner :(

**Comment by danielbachhuber** [comment]
Then you can do:

```
wp plugin install active-directory-integration --version=1.1.7 && wp plugin install addthis --version=5.0.8
```

**Comment by scribu** [comment]
You could add a Python-style requirements file:

```
wp plugin install --requirements plugins.txt
```

where `plugins.txt` looks like this:

```
active-directory-integration==1.1.7
addthis==5.0.8
```

**Comment by scribu** [comment]
I say "you could", but I don't know if it's actually possible to install multiple plugins within a single process.   I'm gusessing "yes", since I do remember seeing a plugin that did bulk installs like this.
