### ISSUE TITLE
Add command update-db-status (or other means to check for DB updates)

### ISSUE THREAD

**Issue by ingomueller-net** [wp-cli/wp-cli#2171]
In some situations it is useful to know whether there are pending DB updates without immediately executing them. One example are automatic deployment tools like [ansible](https://ansible.com). This is currently not possible.

In drush (the command line tool for drupal), this is done with the command [`updatedb-status`](http://drushcommands.com/drush-7x/core/updatedb-status). It either prints `No database updates required` or lists the pending updates. It would be great to have something similar in `wp-cli`.

**Comment by danielbachhuber** [comment]
We could add a `--dry-run` flag to `wp core upgrade-db` so you can see what would happen without any database modification.

> In some situations it is useful to know whether there are pending DB updates without immediately executing them.

To provide further context around this request, can you share these situations?

**Comment by ingomueller-net** [comment]
I am automating deployment with ansible. This and other similar tools bring a remote system into a desired state and report whether or not changes were needed to do so. In our case, I want the remote system "to have an up-do-date wordpress database". If I want to correctly report whether a change was made, I need to implement a [`changed_when`](http://docs.ansible.com/ansible/playbooks_error_handling.html#overriding-the-changed-result) command. Maybe #2172 could be enough to achieve that by parsing the output of `update-db`.

Still with ansible, I might want to backup the database before running the upgrade. I would then implement a `changed_when` command using `update-db-status` or `update-db --dry run` and parse the output. I would then trigger a backup + update of the database using ansible's [`notify`](http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change).
