### ISSUE TITLE
Cannot run phpunit

### ISSUE THREAD

**Issue by AndrewCloss** [wp-cli/wp-cli#2177]
I'm following the Plugin Unit Tests guide.
When running `phpunit` I get the following error:
```
Warning: require_once(/tmp/wordpress//wp-includes/class-phpmailer.php): failed to open stream: No such file or directory in /tmp/wordpress-tests-lib/includes/mock-mailer.php on line 2

Fatal error: require_once(): Failed opening required '/tmp/wordpress//wp-includes/class-phpmailer.php' (include_path='.:/opt/lampp/lib/php') in /tmp/wordpress-tests-lib/includes/mock-mailer.php on line 2
```
My `/tmp/wordpress` directory is empty.

**Comment by danielbachhuber** [comment]
Can you share `wp --info` ? And can you try deleting `/tmp/wordpress` and running `bash bin/install-wp-tests.sh` again?

**Comment by AndrewCloss** [comment]
It looks like the deleting the empty `/tmp/wordpress` folder fixed it. Thanks for the help!

**Comment by LjupcheVasilev** [comment]
If you're on Windows, open wp-tests-config.php and change the ABSPATH with absolute path to your TEMP folder. For example:
define( 'ABSPATH', 'C:\Users\{User}\AppData\Local\Temp/wordpress/' );

I changed this and phpunit worked! This code is on line 7

**Comment by davidgalvez** [comment]
> It looks like the deleting the empty `/tmp/wordpress` folder fixed it. Thanks for the help!

Yes, I had the same issue, and solved in **Windows** following this steps : 
Delete 'C:\Users\{user}\AppData\Local\Temp\wordpress'  and 'C:\Users\{user}\AppData\Local\Temp\wordpress-tests-lib' folders, 

then I executed the command:
`bin/install-wp-tests.sh wp_plugins_test root '' localhost latest`

Finally I changed the APBSPATH in file 'C:\Users\{user}\AppData\Local\Temp\wordpress-tests-lib\wp-tests-config.php' line 4 from:
`define( 'ABSPATH', '/tmp/wordpress/' );`
to 
`define( 'ABSPATH', 'C:\Users\{user}\AppData\Local\Temp/wordpress/' );`

Note that you have to replace {user} for your windows user name.

**Comment by tonnysantana2004** [comment]
"C:\Users\tonny\AppData\Local\Temp\wordpress-tests-lib\wp-tests-config.php"

<?php

define( 'ABSPATH', 'C:/Users/tonny/AppData/Local/Temp/wordpress/' );  // change here 

...

define( 'DB_HOST', 'localhost' ); //change here

here work 100%
