### ISSUE TITLE
wp rewrite structure prepends index.php to the rules

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#2184]
Hi,

I am working on a quick installer for WP multisite.
When I execute this command it puts index.php in front of the rules. Why?
wp rewrite structure '/%postname%' --path={$setup_params_esc['doc_root']}";

and the links become
http://slavi9.weeuu-staging.bolt.devel.ca/index.php/hello-world#comment-1

```
wp --info
PHP binary:     /usr/bin/php5
PHP version:    5.5.9-1ubuntu4.7
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.20.1

```

WP multisite rules for folder setup.
```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]
```

This would be a workaround for those waiting for a fix.
```
wp option get permalink_structure '/%postname%'
wp option update permalink_structure '/%postname%'
````

**Comment by danielbachhuber** [comment]
When WP-CLI doesn't detect `mod_rewrite`, it prefixes the rewrite rules with `index.php`: https://github.com/wp-cli/wp-cli/blob/master/php/commands/rewrite.php#L88-L89

This is because it can't safely assume you have a correctly-configured `.htaccess` file. 

You can tell WP-CLI you have `mod_rewrite` available by adding the following to your `config.yml` or `wp-cli.yml` file:

```
apache_modules:
  - mod_rewrite
```

**Comment by danielbachhuber** [comment]
Huh. I actually get the same result when I add the declaration in `wp-cli.yml`. On top of that, I don't fully grok the logic in `wp rewrite structure`. I'll take a deeper look when I have a moment.

**Comment by lordspace** [comment]
Sounds good Daniel
