### ISSUE TITLE
GET Plugins without a wp-config.php

### ISSUE THREAD

**Issue by jbkc85** [wp-cli/wp-cli#2189]
In setting up WordPress, I really wish I could grab plugins without any need to touch the database.  For example, if I am prepping a file system that does not yet have Database access I would love to grab all the plugins that I am wanting to install without having to rely on the config.php.  Is there anyway to add a simple argument to skip the wp-config.php validation?

**Comment by danielbachhuber** [comment]
> I really wish I could grab plugins without any need to touch the database.

What do you mean by "grab plugins"? Can you provide a bit more background on your situation?

>  Is there anyway to add a simple argument to skip the wp-config.php validation?

When you use `wp plugin list`, WP-CLI uses the `active_plugins` option in the database to get a list of active plugins.

**Comment by jbkc85** [comment]
Certainly, I apologize about how vague it is.

I will use Drush as an example.  In Drush I am able to supply a 'make' file that will go out and download each plugin specified.  With a very simple set of instructions I now have a basic file setup of a Drupal site without any need for the database to be initialized (which is the obvious second step).

Much like you do a wp core download, I would love to do a 'wp plugin download <name>' to simply download the plugin in the appropriate directory.  I don't want to have to have wp-config.php or the ```active_plugins``` to fire off due to the fact i may not have a wp-config.php in place.

To be completely forth coming, I am using this in a Dockerfile.  I am trying to make a completely immutable WordPress instance and if i am able to download plugins on each Docker build, I can automate the upgrading/updating of a WordPress container without the end-user needing to know anything about how to install the plugins (obviously this restricts some features of WP, but I personally don't like the idea of WP installing things on my behalf unless I initiate it via the CLI)

Let me know if i blabbered on too much :-)

**Comment by danielbachhuber** [comment]
> Much like you do a wp core download, I would love to do a 'wp plugin download ' to simply download the plugin in the appropriate directory. I don't want to have to have wp-config.php or the active_plugins to fire off due to the fact i may not have a wp-config.php in place.

WP-CLI is dependent on WordPress for installation-related code, and the `WP_PLUGIN_DIR` constant defined in `wp-config.php` to know where to put installed plugins.

> To be completely forth coming, I am using this in a Dockerfile. I am trying to make a completely immutable WordPress instance and if i am able to download plugins on each Docker build, I can automate the upgrading/updating of a WordPress container without the end-user needing to know anything about how to install the plugins

You can use some simple bash to achieve the same effect:

```
wget -o user-switching.zip https://downloads.wordpress.org/plugin/user-switching.1.0.8.zip
unzip user-switching.zip
mv user-switching path/to/plugins/dir
```

Or, you can write a custom WP-CLI command that does essentially the same but runs before WordPress loads.

**Comment by jbkc85** [comment]
Thank you for your response.  I will certainly look into creating a WP-CLI command.  I was hoping to avoid having to specify a version number for the plugin, as once again anytime I want to 'build' WordPress I want it to pull down everything brand-spanking-new.

**Comment by danielbachhuber** [comment]
> I was hoping to avoid having to specify a version number for the plugin, as once again anytime I want to 'build' WordPress I want it to pull down everything brand-spanking-new.

You could grep the WordPress.org plugin page for the latest version.

**Comment by cbravo** [comment]
@danielbachhuber I am in the same boat here... the only problem with using wget is that not EVERY plugin has the version in the url. Some urls only have the plugin slug in the zip name for the current version so one cannot reliably know what version you are downloading. Is there any kind of recommendation you can make with regards to creating a custom wp-cli command that simply downloads the plugin zip?

**Comment by BloomPhilippe** [comment]
Possible solution : 

`
mkdir $1
cd $1
wp core download --locale=fr_FR --force
for PLUGIN in gotmls disable-comments better-wp-security jetpack imsanity advanced-custom-fields wp-optimize p3-profiler
do
	printf "installation plugin $VARIABLE"
    curl -O https://downloads.wordpress.org/plugin/$PLUGIN.zip
    unzip $PLUGIN.zip -d wp-content/plugins/
    rm $PLUGIN.zip
done
`

**Comment by drzraf** [comment]
for reference: https://github.com/wp-cli/extension-command/issues/26
