### ISSUE TITLE
Use PHPUnit 4.8 in `wp scaffold plugin`

### ISSUE THREAD

**Issue by connerbw** [wp-cli/wp-cli#2198]
Hi,  Thanks for your awesome work on wp-cli. 

I have tweaked the results of `wp scaffold plugin` to:

+ Explicitly use phpunit 4.8 
+ Generate a clover.xml that can be using with coveralls.io

Code here:

+ https://github.com/pressbooks/pressbooks/blob/dev/.travis.yml
+ https://github.com/pressbooks/pressbooks/blob/dev/.coveralls.yml

Should I submit a pull request?

Thanks.

**Comment by danielbachhuber** [comment]
> Explicitly use phpunit 4.8

Why?

> Generate a clover.xml that can be using with coveralls.io

I don't think Coveralls is mainstream enough that it merits including the config in `wp scaffold plugin`

**Comment by connerbw** [comment]
> Why?

Two reasons:

 + I encountered a bug (https://github.com/sebastianbergmann/phpunit/issues/1898) which is fixed in 4.8
 + [Your wiki](https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests) explicitly says: "Note: phpunit 4.8.x is required (5.x won't work)" but travis-ci.org, with the current yaml config generated by WP-CLI, runs PHPUnit 4.5.0.

**Comment by danielbachhuber** [comment]
Ok. Changing to the Composer-based PHPUnit seems reasonable.
