### ISSUE TITLE
Gitlab CI configuration in wp scaffold plugin-tests?

### ISSUE THREAD

**Issue by Nikschavan** [wp-cli/wp-cli#2199]
Follow up on #2198 

Should we add support to Gitlab CI config? setting up continues integration is a challenging job for the new developers, the `wp scaffold plugin-tests` command helps a lot of developers to get the ideal development procedures.

Coveralls might not be mainstream, but gitlab.com is bit popular with their unlimited private repos and inbuilt CI.

Maybe we can pass in an optional flag for the CI config like `--gitlab` and default to Travis CI?

**Comment by danielbachhuber** [comment]
> Maybe we can pass in a optional flag to be for the CI config like --gitlab and default to Travis CI?

I'll flag this as an enhancement we can consider in the future. I don't have a good sense of the proper implementation right now.

**Comment by danielbachhuber** [comment]
@Nikschavan is there a default config you can share for Gitlab?

**Comment by Nikschavan** [comment]
Yes, [this](https://gitlab.com/Nikchavan/test-wp-plugin/blob/master/.gitlab-ci.yml) is how the `.gitlab-ci.yml` looks like, I had to modify the `install-wp-tests.sh` a bit into a new file `install_gitlab_tests.sh`. The main difference is Travis requires creating a new database while Gitlab requires installing some basic packages to start testing like [here](https://gitlab.com/Nikchavan/test-wp-plugin/blob/master/bin/install_gitlab_tests.sh#L100)

**Comment by danielbachhuber** [comment]
Cool. I'd be amenable to adding a `--ci=<provider>` argument to `wp scaffold plugin-tests` that accepted `travis`, `gitlab` or `circle` (or some combination of the three, I suppose)

**Comment by danielbachhuber** [comment]
@Nikschavan Want to put together a PR for this? I added Circle support, so it would be cool to have Gitlab in there too.

Rather than modifying `install-wp-tests.sh`, you should put any Gitlab-specific configuration steps in to `.gitlab-ci.yml`.

**Comment by Nikschavan** [comment]
>Want to put together a PR for this?

I would be happy to!

**Comment by Nikschavan** [comment]
@danielbachhuber I have submitted a pull request for Gitlab tests.

I have added Gitlab specific configurations to its .yml, but as this needs to skip creating a databse, I have added a new option in `install-wp-tests.sh` to bail early in `install_db()`

**Comment by danielbachhuber** [comment]
🚢
