### ISSUE TITLE
"Global" variables not accessible

### ISSUE THREAD

**Issue by phh** [wp-cli/wp-cli#2200]
See https://wordpress.org/support/topic/a2a_share_save_plugin_dir-not-set-and-breaks-wp-cli?replies=6

I'm getting some errors from wp-cli, due to the add-to-any plugin is defining their variables in the global scope.

See answer from micropat:
https://wordpress.org/support/topic/a2a_share_save_plugin_dir-not-set-and-breaks-wp-cli?replies=6#post-7650210

*This is a WP-CLI issue, not an AddToAny issue.*

*Using a reduced test case, WP-CLI 0.21.0 fails, but WP-CLI 0.20.2 worked.*
```
// Already global scope, so the global keyword isn't used.
//global $a_global_var;

$a_global_var = 'Of course.';

function foo() {
	global $a_global_var;

	if ( empty( $a_global_var ) ) {
		$a_global_var = 'Nope!';
	}

	die( 'Is global scope behaving? ' . $a_global_var . " \n" );
}

foo();
```

**Comment by danielbachhuber** [comment]
WP-CLI now loads WordPress inside of a function: https://github.com/wp-cli/wp-cli/issues/2089

Global variables need to be explicitly globalized in order to function as expected in WP-CLI.

**Comment by danielbachhuber** [comment]
@jeremysimmons That should work fine.

"Explicitly globalized" means you need to use the `global` keyword before using the variable:

```
global $foo
$foo = 'bar';
```

However, `$GLOBALS` is a superglobal, so you don't need to do anything in order to use that.

**Comment by jeremysimmons** [comment]
@danielbachhuber thank you for the comment.

I'm using `wp eval-file foo.php --use-include`. (I understand --use-include is different than the normal eval-file for context). This already bit me with $args being null, but that's tangental)

The `$bar` variable I thought was global

```php
<?php
$bar = [];
$bar[] = ...;
function my_fun() {
global $bar;
// $bar is null here
}
my_fun();
```
I didn't understand why $bar was null. 
This is working, but feels hacky.
```php
$bar = [];
$bar[] = ...;
$GLOBALS['bar'] = $bar; 
function my_fun() {
$bar = $GLOBALS['bar'];
// $bar is my array. success, but feeling wrong.
}
my_fun();
```

**Comment by jeremysimmons** [comment]
@danielbachhuber does it run in global scope when you specify `--use-include` ?
I would have thought that `global $bar` was only to reference an existing `$bar` from the wordpress core / plugins, not my own `$bar` variable. 

Thanks. I appreciate your wisdom!

**Comment by danielbachhuber** [comment]
> does it run in global scope when you specify `--use-include` ?

@jeremysimmons Hm, not quite. `--use-include` is still running inside of a function, so any variables are in local scope.

> I would have thought that `global $bar` was only to reference an existing `$bar` from the wordpress core / plugins, not my own `$bar` variable.

`global $bar` is one way you can access a `global $bar` in your plugin, certainly. But `global $bar` also will access a `global $bar` defined by _any other code_.

This is a pretty good article and HN thread about global variables:
* https://web.archive.org/web/20141129064316/http://www.safetyresearch.net/blog/articles/toyota-unintended-acceleration-and-big-bowl-%E2%80%9Cspaghetti%E2%80%9D-code
* https://news.ycombinator.com/item?id=9643204

I'm not saying you _shouldn't_ use global variables, but it's worth being aware of the potential side effects.

**Comment by jeremysimmons** [comment]
>Hm, not quite. --use-include is still running inside of a function, so any variables are in local scope.

Thanks for confirming. Sorry, I should have just read [the code](https://github.com/wp-cli/eval-command/blob/058ab776e6044a990b44bd21ad5802c90b9fe540/src/EvalFile_Command.php#L73). 

I'm still coming from 20 years of working in dotnet, where includes are not a part of the language (compiled vs interpreted). It stretches my brain to remember that the execution of the included file is dependent on the context of where the `include` is called. 

> I'm not saying you shouldn't use global variables, but it's worth being aware of the potential side effects.

Point taken. I have never liked global variables. They've gotten me in trouble more than they've helped. 

I further do not like how the php foreach iteration variable is in scope after the foreach loop completes.

I'm good for now. Very much appreciate your help and discussion on this. Thank you!

**Comment by danielbachhuber** [comment]
@jeremysimmons You're welcome!

**Comment by jeremysimmons** [comment]
P.S. This scenario is commented on at https://www.php.net/manual/en/language.variables.scope.php.

https://www.php.net/manual/en/language.variables.scope.php#63500
