### ISSUE TITLE
Register an arbitrary function, closure, or method as a command

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2204]
For simpler definition of WP-CLI commands, it would be cool if you could specify an arbitrary callback as a command.

As an example:

```
WP_CLI::add_command( 'cool command', function( $args, $assoc_args ) {
    // do something
});
```

Documentation could be specified in the third `$args` parameter for `WP_CLI::add_command()`. However, we'd likely want to specify a schema for the documentation based on some formalization of our PHPdoc parsing.

**Comment by borekb** [comment]
Very good idea!

**Comment by danielbachhuber** [comment]
> Documentation could be specified in the third $args parameter for WP_CLI::add_command()

As it turns out, PHP's Reflection properly parses docs for closures and functions, so we can handle this as a second issue.
