### ISSUE TITLE
Allow multiple of the same command option to be stored as array

### ISSUE THREAD

**Issue by JPry** [wp-cli/wp-cli#2212]
I don't believe this is currently possible, but please correct me if I'm mistaken.

It would be nice to be able to define custom commands with option flags that can be used multiple times with the values stored as an array. For example:

```
wp foo --bar=something --bar=something_else
```

Ideally this would give you an array for the `bar` key of the `$assoc_args` array:

```php
print_r( $assoc_args['bar'] );
```
```
Array
(
    [0] => something
    [1] => something_else
)
```

**Comment by danielbachhuber** [comment]
> It would be nice to be able to define custom commands with option flags that can be used multiple times with the values stored as an array.

Can you share your use case?

**Comment by JPry** [comment]
My use case was that I was building a command that could optionally accept multiple taxonomy slugs as arguments. I found a way to do what I wanted with an array of arguments. However, I thought of other command-line libraries (specifically Symfony Console) where you can specify that options can be reused and will generate an array. While I found another solution this time around, I'm sure there would still be a benefit to either myself or others if an option could be specified as an array.

This is the code I ended up with:

```php
class JPry_CLI_Command extends WP_CLI_Command {
	/**
	 * Perform an initial sync of all taxonomies from the main site in the network to each subsite in the network.
	 *
	 * ## OPTIONS
	 *
	 * [<taxonomy>...]
	 * : One or more taxonomy slugs to sync. If omitted, then all taxonomies will be synced.
	 *
	 * @subcommand initial-tax-sync
	 * @alias initial-taxonomy-sync-to-language-sites
	 */
	public function initial_taxonomy_sync_to_language_sites( $args, $assoc_args ) {
		try {
			$taxonomy_sync = new JPry_CLI_Initial_Taxonomy_Sync( $args );
			$taxonomy_sync->do_sync();
		} catch ( \Exception $e ) {
			WP_CLI::error( $e->getMessage() );
		}
	}
}

if ( defined( 'WP_CLI' ) && WP_CLI ) {
	WP_CLI::add_command( 'jpry', 'JPry_CLI_Command' );
}
```
```php
class JPry_CLI_Initial_Taxonomy_Sync {
	/**
	 * @param array $taxonomies Array of taxonomy names to sync.
	 */
	function __construct( $taxonomies = array() ) {
		if ( empty( $taxonomies ) ) {
			$taxonomies = get_taxonomies();
		} else {
			$this->ensure_taxonomies_exist( $taxonomies );
		}

		$this->taxonomies = $taxonomies;
	}

	/**
	 * Ensure that the given taxonomies exist.
	 *
	 * @param array $taxonomies The taxonomies to check.
	 *
	 * @throws \Exception When any one of the taxonomies doesn't exist.
	 */
	private function ensure_taxonomies_exist( $taxonomies ) {
		foreach ( $taxonomies as $taxonomy ) {
			if ( ! taxonomy_exists( $taxonomy ) ) {
				throw new \Exception( sprintf( 'The taxonomy %s does not exist.', $taxonomy ) );
			}
		}
	}

	public function do_sync() {
		// code here...
	}
}

**Comment by danielbachhuber** [comment]
Cool. I've flagged it as an enhancement for future consideration.

**Comment by danielbachhuber** [comment]
Closing this as wontfix. I don't think we can change the behavior here without introducing backwards compatibility issues.

The current prior art is to accept one or more arguments with positional arguments:

```
/**
 * Render each positional argument on a new line
 *
 * ## OPTIONS
 *
 * <arg>...
 * : One or more positional arguments.
 */
function print_args( $args ) {
	foreach( $args as $arg ) {
		WP_CLI::log( $arg );
	}
}
```
