### ISSUE TITLE
wp-cli.phar  installation issue - won't verify

### ISSUE THREAD

**Issue by roscom** [wp-cli/wp-cli#2216]
Hi
Downloaded wp-cli with curl
Running `php wp-cli.phar --info` to verify it works following the download produces the following output:
```
???
   p?
```
Would appreciate it if you could point me in the right direction to solve.

php version info:
```
PHP 5.3.29 (cli) (built: Nov 22 2014 12:28:53)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with the ionCube PHP Loader v4.6.1, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
```
Thank you.

**Comment by wojsmol** [comment]
@roscom see https://github.com/wp-cli/wp-cli/issues/1758

CC: @szepeviktor

**Comment by szepeviktor** [comment]
@wojsmol Have you gone through all my commments in #1758?
Any success?

**Comment by szepeviktor** [comment]
@roscom Have you gone through all my commments in #1758?
Any success?

**Comment by roscom** [comment]
Yes. Upgraded php from 5.3.29 to 5.5.30. Problem solved
