### ISSUE TITLE
Does WP-CLI works in PHP 5.5? Aka. enviroment variables not working

### ISSUE THREAD

**Issue by samuelnasta** [wp-cli/wp-cli#2221]
Scenario
Wp-cli downloads the core, creates the wp-config.php, creates database but any mysql function returns an error (as it was deprecated in PHP 5.5)
I'm running MAMP Pro

Tried to change the enviroment variables:
[.profile]
export WP_CLI_PHP=/Applications/MAMP/bin/php/php5.4.4/bin/php
[.bash_profile]
export WP_CLI_PHP=/Applications/MAMP/bin/php/php5.4.4/bin/php
[.bashrc]
export PATH=$PATH:/Applications/MAMP/Library/bin
alias wpinstall="bash ~/.wp-cli/wpinstall.sh"
alias php="/Applications/MAMP/bin/php/php5.4.4/bin/php"
export WP_CLI_PHP=/Applications/MAMP/bin/php/php5.4.4/bin/php

[wp --info]
PHP binary:	/usr/bin/php
PHP version:	5.5.29
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	/Users/samuel/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	0.21.0
[echo $WP_CLI_PHP]
/Applications/MAMP/bin/php/php5.4.4/bin/php

Still I cannot change the PHP binary and create the tables (as I cannot any wp plugin or wp theme and so on).

Any solutions or ideas?

**Comment by danielbachhuber** [comment]
> Does WP-CLI works in PHP 5.5?

Yes.

> any mysql function returns an error (as it was deprecated in PHP 5.5)

Can you share an example of the error?

**Comment by samuelnasta** [comment]
Success: WordPress downloaded.
Success: Generated wp-config.php file.
Success: Database created.


PHP Warning:  mysqli_real_connect(): (HY000/2002): No such file or directory in /Applications/MAMP/htdocs/neu/wp-includes/wp-db.php on line 1452
Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /Applications/MAMP/htdocs/neu/wp-includes/wp-db.php on line 1452
PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /Applications/MAMP/htdocs/neu/wp-includes/wp-db.php on line 1482
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /Applications/MAMP/htdocs/neu/wp-includes/wp-db.php on line 1482
PHP Warning:  mysql_connect(): No such file or directory in /Applications/MAMP/htdocs/neu/wp-includes/wp-db.php on line 1482
Warning: mysql_connect(): No such file or directory in /Applications/MAMP/htdocs/neu/wp-includes/wp-db.php on line 1482

Error: 
<h1>Erro ao estabelecer conexão com o banco de dados</h1>
<p>Isto tanto pode significar que as informações de nome de usuário e senha em seu arquivo <code>wp-config.php</code> estão incorretas, ou que não pudemos contactar o servidor do banco de dados em <code>localhost</code>. Pode ser também que o servidor de hospedagem do seu banco de dados esteja fora do ar.</p>
<ul>
	<li>Você tem certeza que possui o nome de usuário e senha corretos?</li>
	<li>Você tem certeza que digitou corretamente o nome do servidor de hospedagem?</li>
	<li>Você tem certeza que o servidor do banco de dados está funcionando?</li>
</ul>
<p>Procure o seu servidor de hospedagem se você não tem certeza do que estes termos significam. Se ainda assim você precisar de ajuda, visite o <a href='http://br.forums.wordpress.org/'>Fórum de Suporte do WordPress</a>.</p>

This last part is the "Can't connect to database" WordPress error in portuguese

**Comment by danielbachhuber** [comment]
It looks like WordPress can't connect to your database server. Are you sure the credentials are correct, MAMP is running, etc. ?

**Comment by samuelnasta** [comment]
Yes and yes.
Indeed there's a notice saying
Success: Database created.
Database was created but with no tables.

**Comment by samuelnasta** [comment]
I think it's because of 
PHP Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead

http://php.net/manual/en/migration55.deprecated.php

**Comment by danielbachhuber** [comment]
> I think it's because of 
> PHP Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead

If the function didn't work, your code would fatal. The error notice just indicates the function is deprecated.

**Comment by samuelnasta** [comment]
I've tried reseting my mac but didn't make any difference.
You're saying that wp-cli was tested in PHP 5.5 and worked alright and these are just notices, with the functions working okay.

So, what could be the errors, since the credentials are just root/root and the MAMP is running?
127.0.0.1 instead of localhost?
I have another wp-config that's just the same root/root. Don't get it why it doesn't work.

**Comment by danielbachhuber** [comment]
> You're saying that wp-cli was tested in PHP 5.5 and worked alright and these are just notices, with the functions working okay.

Correct.

> So, what could be the errors, since the credentials are just root/root and the MAMP is running? 127.0.0.1 instead of localhost?

Hard to say, because I don't have access to your local environment.

You might check out past threads on WordPress StackExchange for tips: http://wordpress.stackexchange.com/search?q=wp-cli+mamp
