### ISSUE TITLE
run post generate and post meta add together

### ISSUE THREAD

**Issue by marcelo2605** [wp-cli/wp-cli#2224]
I would like to generate a number of posts and attach the same featured image to all posts.

```
wp post generate --count=20
wp post meta add <id> _thumbnail_id 215
```
But how can I run this two commands together? How can I retrieve the id of created post?

**Comment by danielbachhuber** [comment]
It's not easily possible to run these two commands together at the moment. It could be a nice future enhancement, however.

**Comment by marcelo2605** [comment]
Thanks Daniel, I agree.

**Comment by danielbachhuber** [comment]
After #2622 lands, you'll be able to:

```
wp post generate --format=ids | xargs -0 -d ' ' -I % wp post meta add % foo bar
```

**Comment by dylannirvana** [comment]
Thinking of the other parameters of creating multiple pages at once; for example,
wp post generate --count=3 --post_cat=something , adding a parameter to the command, or
wp post generate --count=3 | wp post term set --category=something  , rather as a pipe. In other words, I would like to generate multiple posts, pages and assigning their categories.
