### ISSUE TITLE
RHEL / CentOS RPM package and repository for WP-CLI

### ISSUE THREAD

**Issue by dfisek** [wp-cli/wp-cli#2229]
Setting up a RHEL / CentOS RPM repository for wp-cli will integrate wp-cli with the Linux distribution and ease its management via system updates.

I am willing to create the package, maintain updates and a repository if no one objects.

**Comment by danielbachhuber** [comment]
Sounds good :+1: 

Can you document the work involved on https://github.com/wp-cli/wp-cli/wiki/Release-Checklist ?

**Comment by dfisek** [comment]
Will do. Can you assign the issue to me?

**Comment by danielbachhuber** [comment]
It's not possible to assign issues to GH users outside the WP-CLI organization.

**Comment by danielbachhuber** [comment]
Closing this until someone is actually committed to picking it up.
