### ISSUE TITLE
google-calendar-events >=3.0 error with wp-cli: Class 'WP_Requirements' not found

### ISSUE THREAD

**Issue by gsf** [wp-cli/wp-cli#2241]
There's already a related issue at google-calendar-events (moonstonemedia/Simple-Calendar#40) but since we're only seeing it in wp-cli I thought I better mention it here. Is this due to the way wp-requirements is brought in as a dependency?

> $ wp rewrite flush
> PHP Fatal error:  Class 'WP_Requirements' not found in /home/ubuntu/phila.gov/wp-content/plugins/google-calendar-events/google-calendar-events.php on line 46

**Comment by danielbachhuber** [comment]
How did you install the plugin?

**Comment by gsf** [comment]
Installed with composer. See the deploy script at https://github.com/CityOfPhiladelphia/phila.gov/blob/master/scripts/deploy.sh and deploy output at https://travis-ci.org/CityOfPhiladelphia/phila.gov/builds/92986082.

**Comment by danielbachhuber** [comment]
> Is this due to the way wp-requirements is brought in as a dependency?

Here are the dependencies installed:

```
Installing dependencies (including require-dev)
  - Installing composer/installers (v1.0.22)
    Loading from cache
  - Installing johnpbloch/wordpress-core-installer (0.2.1)
    Loading from cache
  - Installing cityofphiladelphia/phila.gov-customization (0.20.0)
    Loading from cache
  - Installing cityofphiladelphia/phila.gov-theme (0.21.3)
    Loading from cache
  - Installing johnpbloch/wordpress (4.3.1)
    Loading from cache
  - Installing private/meta-box-group (1.0.1)
    Loading from cache
  - Installing private/wpfront-user-role-editor-personal-pro (2.12.1)
    Loading from cache
  - Installing wpackagist-plugin/amazon-s3-and-cloudfront (0.9.6)
    Loading from cache
  - Installing wpackagist-plugin/amazon-web-services (0.3.4)
    Loading from cache
  - Installing wpackagist-plugin/easy-wp-smtp (1.2.1)
    Loading from cache
  - Installing wpackagist-plugin/google-calendar-events (3.0.5)
    Loading from cache
  - Installing wpackagist-plugin/media-library-assistant (2.15)
    Loading from cache
  - Installing wpackagist-plugin/meta-box (4.5.7)
    Loading from cache
  - Installing wpackagist-plugin/nginx-helper (1.9.6)
    Loading from cache
  - Installing wpackagist-plugin/restrict-categories (2.6.3)
    Loading from cache
  - Installing wpackagist-plugin/simple-301-redirects (1.06)
    Loading from cache
  - Installing wpackagist-plugin/simple-page-ordering (2.2.4)
    Loading from cache
  - Installing wpackagist-plugin/wordfence (6.0.20)
    Loading from cache
  - Installing wpackagist-plugin/wordpress-importer (0.6.1)
    Loading from cache
```

The fatal error occurs because `WP_Requirements`, which [is a dependency](https://github.com/moonstonemedia/Simple-Calendar/blob/ed32f6154b669b631ed3d358ccd08daf86fd1357/composer.json#L28) of `google-calendar-events`, isn't installed.

Can you reproduce by running the deploy script locally?

**Comment by gsf** [comment]
Looks like this is related to https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md. Thanks for pointing me in that direction!
