### ISSUE TITLE
Improve search-replace performance on large datasets

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2244]
On large datasets, the performance of `wp search-replace` is degraded by our inconsiderate use of `LIKE ` and `REGEXP`. Specifically:

```
$serialRow = $wpdb->get_row( "SELECT * FROM `$table` WHERE `$col` REGEXP '^[aiO]:[1-9]' LIMIT 1" );
```

```
$args = array(
	'table' => $table,
	'fields' => $fields,
	'where' => $regex ? '' : "`$col`" . $wpdb->prepare( ' LIKE %s', '%' . self::esc_like( $old ) . '%' ),
	'chunk_size' => $chunk_size
);
```

We're running `REGEXP` on columns that don't need it, and `LIKE` repeatedly on tables with millions of rows. We should have smarter behavior when we're considering using these costly queries.

**Comment by danielbachhuber** [comment]
Couple of ideas:

* Only attempt to detect serialized data in specific columns on specific tables (e.g. `wp_options.option_value`). This would still permit `--precise` to be supplied.
* Don't use the `LIKE` in the `WHERE` when we have greater than, say, 50k rows.

@lkwdwrd @kevindoole @JPry @phh @tddewey would love your thoughts when you have a moment.

**Comment by joshkoenig** [comment]
One note from the peanut gallery: it looked to me as though there were cases where two `LIKE` queries were being run: one to count rows (looking for a match) and then a very similar query to get the row IDs. 

If so, that's an easy candidate for optimization by dispensing with the explicit `COUNT` query by just counting the number of IDs returned in the second query. In the event that there are 0, the load on the DB is the same, as running a `COUNT` query forces the DB to do just as much work as actually fetching back the IDs.

**Comment by danielbachhuber** [comment]
Another idea: if the `REGEXP` query returns matching serialized data, use PHP replacement mode on just those specific rows, and then run SQL replacement on all rows but those. On large datasets, this should reduce the slowness of having to iterate through all rows, potentially unnecessarily.

**Comment by danielbachhuber** [comment]
Surprisingly enough, on a postmeta table with ~3.5 million rows, the REGEXP query is really fast:

```
Checking: wp_postmeta.meta_value
Debug: ["SELECT * FROM `wp_postmeta` WHERE `meta_value` REGEXP '^[aiO]:[1-9]' LIMIT 1",0.00029778480529785
```

`SELECT COUNT(*)` is a consistent time suck though:

```
Debug: ["SELECT COUNT(*) FROM wp_postmeta  WHERE `meta_value` LIKE '%domain.com%' ",5.6773121356964
Debug: ["SELECT `meta_id`, `meta_value` FROM wp_postmeta  WHERE `meta_value` LIKE '%domain.com%'  LIMIT 1000 OFFSET 0",0.47706890106201
```

**Comment by danielbachhuber** [comment]
Sadly, changing to `SQL_CALC_FOUND_ROWS` doesn't produce any performance gains.

**Comment by danielbachhuber** [comment]
For the next time someone is working on search-replace performance.

Before #2304, of 734.926s:

```
$ ack "SELECT COUNT\(\*\) FROM wp_postmeta[^,]+,([0-9\.]+)" replace.log --output "\$1" | awk '{ sum+=$1} END {print sum}'
444.025
$ ack "SELECT \`meta_id\`, \`meta_value\` FROM wp_postmeta[^,]+,([0-9\.]+)" replace.log --output "\$1" | awk '{ sum+=$1} END {print sum}'
148.626
$ ack "UPDATE \`wp_postmeta\` SET \`meta_value\`[^,]+\",([0-9\.]+),\"include\(" replace.log --output "\$1" | awk '{ sum+=$1} END {print sum}'
102.864
```

After #2304, of 225.509s:

```
$ ack "SELECT meta_value FROM wp_postmeta[^,]+,([0-9\.]+)" replace-new.log --output "\$1" | awk '{ sum+=$1} END {print sum}'
43.2791
$ ack "UPDATE \`wp_postmeta\` SET \`meta_value\`[^,]+\",([0-9\.]+),\"include\(" replace-new.log --output "\$1" | awk '{ sum+=$1} END {print sum}'
111.279
```
