### ISSUE TITLE
Deleting menu item with sub-items does not update sub-items' parent

### ISSUE THREAD

**Issue by JanVoracek** [wp-cli/wp-cli#2246]
If I create menu with following structure:
 - Parent
   - Child 1
     - Child 2

and I delete _Child 1_, it should look like this:
 - Parent
   - Child 2

The problem is that WP-CLI does not update the _Child 2_'s parent (postmeta `_menu_item_menu_item_parent`).

It's the same bug as in WP – see [Trac](https://core.trac.wordpress.org/ticket/34803).

**Comment by danielbachhuber** [comment]
Huh. Thanks for flagging.
