### ISSUE TITLE
updating community packages without composer ?

### ISSUE THREAD

**Issue by centminmod** [wp-cli/wp-cli#2251]
With regards to https://github.com/wp-cli/wp-cli/wiki/Community-Packages and install instructions without composer, is the update of the community packages as simple as just a git pull ? Or anything else to it ?

Looking at installing wp-super-cache-cli plugin https://github.com/wp-cli/wp-super-cache-cli

https://github.com/wp-cli/wp-super-cache-cli.git

so install

    mkdir -p $HOME/.wp-cli/commands
    git clone https://github.com/wp-cli/wp-super-cache-cli.git $HOME/.wp-cli/commands/super-cache
    echo "require:" > $HOME/.wp-cli/config.yml
    echo "  - commands/super-cache/cli.php" >> $HOME/.wp-cli/config.yml

contents of $HOME/.wp-cli/config.yml

    require:
      - commands/super-cache/cli.php

test

    wp super-cache --allow-root
    usage: wp super-cache disable 
       or: wp super-cache enable 
       or: wp super-cache flush [--post_id=<post-id>] [--permalink=<permalink>]
       or: wp super-cache preload [--status] [--cancel]
       or: wp super-cache status 
    
    See 'wp help super-cache <command>' for more information on a specific command.

but updating is the community package is just ?

    cd $HOME/.wp-cli/commands/super-cache
    git pull

cheers

**Comment by danielbachhuber** [comment]
>  install instructions without composer, is the update of the community packages as simple as just a git pull ?

Yep
