### ISSUE TITLE
Won't run on CentOS 6. With CPanel, Get garbage on stdout

### ISSUE THREAD

**Issue by upshutusquare** [wp-cli/wp-cli#2257]
Hi, Im a bit stuck at the moment trying to get wp-cli to run I have:

    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

then I run:

    php wp-cli.phar --info

and it get:

    root@server1 [~]# php wp-cli.phar --info
    X-Powered-By: PHP/5.3.29
    Content-type: text/html

    ???p????Q??root@server1 [~]#

    root@server1 [~]# /usr/bin/php5-cli wp-cli.phar --info
    ???p????Q??root@server1 [~]# 

    root@server1 [~]# /usr/bin/php5 wp-cli.phar --info
    ???p????Q??root@server1 [~]#

My PHP version:

    PHP 5.3.29 (cli) (built: Feb 13 2015 16:06:16) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
        with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
        with the ionCube PHP Loader v4.6.1, Copyright (c) 2002-2014, by ionCube Ltd., and
        with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies
        with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with Suhosin v0.9.33, Copyright (c) 2007-2012, by SektionEins GmbH

How can I start to figure out whats going on here? 

I have a CentOS 6.7 VM with the php from the stock repo and it all works fine.

Thanks.

**Comment by danielbachhuber** [comment]
Upgrade to PHP 5.3.30 https://github.com/wp-cli/wp-cli/issues/2216#issuecomment-160778113
