### ISSUE TITLE
Add simple Windows installation method to Wiki

### ISSUE THREAD

**Issue by 13pixlar** [wp-cli/wp-cli#2258]
Werther we like it or not, many developers are Windows users. Installing WP-CLI on windows is fairly simple without the need for composer. I suggest adding the following to the [Alternative Install Methods](https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods) page

## Simple installation on Windows

Make sure you have php installed and [in your path](http://php.net/manual/en/faq.installation.php#faq.installation.addtopath) so you can execute it globally.

Download [wp-cli.phar](https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar) manually and save it to a folder, for example `c:\wp-cli`

Create a file named `wp.bat` in `c:\wp-cli` with the following contents:

```
@ECHO OFF
php "c:/wp-cli/wp-cli.phar" %*
```

Add `c:\wp-cli` to your path:

```bash
setx path "%path%;c:\wp-cli"
```

You can now use wp-cli from anywhere in Windows command line.

**Comment by danielbachhuber** [comment]
> . I suggest adding the following to the Alternative Install Methods page

You're more than welcome to edit the page!

**Comment by QWp6t** [comment]
`composer global require wp-cli/wp-cli` also works fine on Windows. I'm surprised that method isn't on there already since it's cross-platform and it can be updated with `composer global update`.

**Comment by 13pixlar** [comment]
@danielbachhuber Sure. I have edited the page and added a Windows section.
@QWp6t Please expand the Windows section i added with `composer global require wp-cli/wp-cli` if you like.

**Comment by danielbachhuber** [comment]
:+1:
