### ISSUE TITLE
create user fails with WP_Error failure

### ISSUE THREAD

**Issue by dancrumb** [wp-cli/wp-cli#2263]
Running the command:
```
wp user create new-id new.email --role=city_boss --display_name="New Name"
```

I get 
```
Fatal error: Cannot use object of type WP_Error as array in phar:///usr/local/bin/wp/php/commands/user.php on line 286
```

**Comment by dancrumb** [comment]
```
$ wp --info
PHP binary:	/usr/bin/php5
PHP version:	5.6.11-1ubuntu3.1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.21.1
```

**Comment by danielbachhuber** [comment]
Which version of WordPress are you using?

**Comment by szepeviktor** [comment]
Seems like a WP 4.0 problem.

**Comment by dancrumb** [comment]
Using WP version 4.3.1

**Comment by danielbachhuber** [comment]
Do you have any code filtering `wpmu_validate_user_signup` ? Can you try:

```
wp user create new-id new.email --role=city_boss --display_name="New Name" --skip-plugins --skip-theme
```

**Comment by danielbachhuber** [comment]
@dancrumb any luck tracking this down?

**Comment by dancrumb** [comment]
@danielbachhuber I'll have a chance to try this today.

**Comment by dancrumb** [comment]
Looks like I have a ReCAPTCHA plugin that attaches to that hook. It always used to work. Did the wp-cli plugin change to use this?

**Comment by dancrumb** [comment]
To confirm: using `--skip-plugins` worked

**Comment by danielbachhuber** [comment]
> Looks like I have a ReCAPTCHA plugin that attaches to that hook.

This would make sense. 

> It always used to work. Did the wp-cli plugin change to use this?

WP-CLI isn't a plugin, and the code for `wp user create` [hasn't been changed in a while](https://github.com/wp-cli/wp-cli/commits/master/php/commands/user.php)

Maybe the ReCAPTCHA plugin changed its implementation mechanism?
