### ISSUE TITLE
Accept passwords in hash form

### ISSUE THREAD

**Issue by marcusatbang** [wp-cli/wp-cli#2270]
We're attempting to automate the installation of WordPress sites, including the default set of users to be installed. That means setting passwords for these users - from a script that's in source control for everybody to see.

I like my colleagues, but I'm not willing to give them my password, and nor should they. I'm happy to give them a password hash though. Like this one: 

```
$2a$16$K02F3Df8D17lnP0Vq89wxOGnKtEaPPnR5usxzBzHB3xf0SdaTpovy
```

It would be helpful if WP-CLI was able to accept a password hash in place of a password. All hashes are guaranteed to start with a `$` prefix signifying the hash algorithm used (SHA-256, bcrypt, etc).

**Comment by danielbachhuber** [comment]
> It would be helpful if WP-CLI was able to accept a password hash in place of a password.

Probably not going to happen. Realistically, users should be setting passwords on their own, and using different passwords between WordPress installs. If you want to have some form of single sign-on, you should properly implement SSO.

You're also welcome to write a custom command specifically for setting the password from hash, or make a direct database query.

**Comment by theDanielJLewis** [comment]
4 years later, is there more interest for this? I think this is mandatory for migrations where WP owners might need to migrate users (and only users) from one site to another. That's what I'm trying to do.

**Comment by antoine-morvan** [comment]
@theDanielJLewis if you are still looking for way try this (you probably don't need the first line, but might be usefull in other cases):

```
HASHED_PASS=$(wp eval "echo wp_hash_password('$CLEAR_PASSWORD');")
USER_ID=$(wp user list --login="$USR_LOGIN" --format=ids)
wp db query "UPDATE wp_users SET user_pass='$HASHED_PASS' WHERE ID = $USER_ID;"
```
