### ISSUE TITLE
Uninstall package

### ISSUE THREAD

**Issue by arelidev** [wp-cli/wp-cli#2271]
Is there a way to uninstall the package? I used it for a quick fix and it worked great but I need to remove it until I read more. I'll definitely be using it in the future!

**Comment by danielbachhuber** [comment]
How did you install it?

**Comment by arelidev** [comment]
Through the ssh terminal

-----Original Message-----

**Comment by danielbachhuber** [comment]
You'll need to be more clear than that. Can you provide the exact commands you used to install WP-CLI? There are multiple installation methods.

**Comment by arelidev** [comment]
curl -O
https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

I'm just looking to uninstall this.

On Tue, Dec 8, 2015 at 7:52 PM, Daniel Bachhuber <notifications@github.com>
wrote:

> You'll need to be more clear than that. Can you provide the exact commands
> you used to install WP-CLI? There are multiple installation methods.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wp-cli/wp-cli/issues/2271#issuecomment-163071956>.
>



-- 
*Keith Petrillo*
*Sr. Developer / Project Manager*
*The Areli Group <http://www.theareligroup.com/> - Branding, Design,
Development, and Digital Marketing.*
p: (855) 902-7354 ext 702
t: @KeithPetrillo <http://www.twitter.com/keithpetrillo>
in: Keith Petrillo <http://www.linkedin.com/keithpetrillo>
Skype: Keith.Petrillo

**Comment by danielbachhuber** [comment]
Just remove the file with `rm path/to/file.phar`

**Comment by arelidev** [comment]
Simple enough. Thank you!
