### ISSUE TITLE
trouble upgrading wp-cli

### ISSUE THREAD

**Issue by billc108** [wp-cli/wp-cli#2275]
I'm having trouble upgrading wp-cli itself.  I've got one at version 0.18 (OS 10.9.5) and two at 0.17 (OS 10.9.5 and OS 10.10.5).

It downloads fine, and running
php wp-cli.phar --info 

shows it as running 0.21.1, but when I run

chmod +x wp-cli.phar
sudo mv wp-cli.phar /usr/local/bin/wp
wp --info

it still shows as running the old version.  

I tried quitting and restarting both Terminal (just in case) and the server, but I'm still seeing the same behavior.  

Any ideas?  I recall that there was a similar problem when I first installed at a WordCamp several years ago.   Unfortunately, I don't recall the solution. 

Thanks

**Comment by danielbachhuber** [comment]
Can you share the results of `which wp` ?

**Comment by szepeviktor** [comment]
Could we have a bot asking these questions randomly?

**Comment by szepeviktor** [comment]
@billc108 `which -a wp`

**Comment by szepeviktor** [comment]
See: https://github.com/wp-cli/wp-cli/wiki/How-to-solve-an-issue

**Comment by billc108** [comment]
> which -a wp
/usr/bin/wp
/usr/local/bin/wp
/usr/bin/wp

**Comment by billc108** [comment]
> which -a wp
/usr/bin/wp
/usr/local/bin/wp
/usr/bin/wp

**Comment by szepeviktor** [comment]
Please delete all but one version.

**Comment by danielbachhuber** [comment]
`rm /usr/bin/wp`

**Comment by billc108** [comment]
Worked.

Thanks

On 12/9/15 5:31 PM, Daniel Bachhuber wrote:
>
> |rm /usr/bin/wp|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wp-cli/wp-cli/issues/2275#issuecomment-163436455>.
>


-- 
Bill Christensen
http://SustainableSources.com
http://LinkedIn.com/in/billc108
