### ISSUE TITLE
Offer to install the importer plugin if not available

### ISSUE THREAD

**Issue by morganestes** [wp-cli/wp-cli#2281]
When I run the `wp import` command for the first time (and after jumping through the `--users` hoop when I forget to specify that flag/value), I then am greeted with a frustrating "run this command to install the importer plugin" message.

To ease a bit of the frustration, can we present a "Would you like to install it now? Y/n" prompt after that so they can easily install without having to re-type or copy/paste the command to install the plugin?

**Comment by danielbachhuber** [comment]
> can we present a "Would you like to install it now? Y/n" prompt after that so they can easily install without having to re-type or copy/paste the command to install the plugin?

I don't think it's a great idea to introduce this prompt for a couple of reasons:

1. I don't want to establish a pattern of "oh, do you want to do this other thing?" throughout the codebase. The informational message solves the users problem, albeit with a second step, and is an existing pattern we have.
2. Prompts block script execution. Introducing a prompt would mean any scripts calling `wp import` could hang indefinitely. There are ways to get around this, but I don't think it's worth the effort + risk of breakage.
