### ISSUE TITLE
script bash with install

### ISSUE THREAD

**Issue by xavierartot** [wp-cli/wp-cli#2285]
Hi,
I'm using MAMP
I don't understand why the script below script doesn't install WP:
https://gist.github.com/xavierartot/61f7e6d7ab1e6318a1d0

In the terminal I start the script:

wp-local-complete-install.sh
please, create your repertoire website
test5
mkdir: created directory 'test5'
downloading WordPress
Downloading WordPress 4.4 (en_US)...
Using cached file '/Users/xavi/.wp-cli/cache/core/wordpress-4.4-en_US.tar.gz'...
Success: WordPress downloaded.
create the database
create the file wp-config.php
Success: Generated wp-config.php file.
TITLE
TITLE
You want som post by default (100 maximum): 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Error: The site you have requested is not installed.
Run `wp core install`.
100  2170  100  2170    0     0   3924      0 --:--:-- --:--:-- --:--:--  3931
(23) Failed writing body
Error: The site you have requested is not installed.
Run `wp core install`.
Error: The site you have requested is not installed.
Run `wp core install`.

That mean he doesn't understood this?

wp core install --url=http://localhost:8888/$rep --title=$TITLE --admin_user=$ADMIN_USER --admin_password=$ADMIN_PASSWORD --admin_email=$EMAIL

**Comment by shawnhooper** [comment]
Hi @xavierartot - What version of WP-CLI are you running?  
To install WordPress 4.4, you'll need to make sure you're running at least WP-CLI 0.21.1.  
The "wp core install" command doesn't with WP 4.4 and older versions of the CLI.

**Comment by shawnhooper** [comment]
Also, just a tip, you could replace:

```mysql -u root -p"root" -e "CREATE DATABASE \`$rep\`;"```

with

```wp db create```

and run it right after you've created your config file.

**Comment by xavierartot** [comment]
I have the WP-CLI 0.20.2, 
Can I do? 
wp db create $rep
