### ISSUE TITLE
Composer update not working?

### ISSUE THREAD

**Issue by ethanclevenger91** [wp-cli/wp-cli#2288]
Echoing [what this guy](http://wordpress.stackexchange.com/questions/211393/how-to-update-wp-cli-on-windows-via-composer) said but putting it here for visibility, running `composer update` in my WP-CLI project to get to at least 20.4 for WP 4.4 isn't working. Looks like it may have updated some dependencies, but `wp --version` still gets me `0.20.0`. A coworker is stuck at `0.20.3`.

**Comment by webspecnick** [comment]
Co-worker here to confirm. The workaround is to manually replace the files in the wp-cli folder or deleting the folder and running a new `composer create-project wp-cli/wp-cli --no-dev`

**Comment by danielbachhuber** [comment]
> running composer update in my WP-CLI project to get to at least 20.4 for WP 4.4 isn't working.

Can you share the output you get when you run `composer update`? Do you have a `composer.lock` file in place?

**Comment by ethanclevenger91** [comment]
GitHub doesn't support `.lock` files, so I changed it to .txt.

Output the first time I gave it a go this morning: 
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/finder (v2.7.5)
  - Installing symfony/finder (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 30%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 80%m
    Downlo    Downloading: 100%

  - Removing symfony/yaml (v2.7.5)
  - Installing symfony/yaml (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 40%m
    Downlo    Downlo    Downlo    Downlo    Downloading: 100%

  - Removing symfony/filesystem (v2.7.5)
  - Installing symfony/filesystem (v3.0.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 100%9
m

  - Removing symfony/config (v2.7.5)
  - Installing symfony/config (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 25%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 65%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 100%9
m

  - Installing symfony/polyfill-mbstring (v1.0.0)
    Downlo    Downlo    Downlo    Downlo    Downloading: 100%

  - Removing symfony/console (v2.7.5)
  - Installing symfony/console (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 20%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 50%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 80%m
    Downlo    Downlo    Downlo    Downlo    Downloading: 100%

  - Removing symfony/dependency-injection (v2.7.5)
  - Installing symfony/dependency-injection (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 20%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 50%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 80%m
    Downlo    Downlo    Downlo    Downlo    Downloading: 100%

  - Removing symfony/event-dispatcher (v2.7.5)
  - Installing symfony/event-dispatcher (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downloading: 100%

  - Removing symfony/translation (v2.7.5)
  - Installing symfony/translation (v2.8.0)
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 20%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 50%m
    Downlo    Downlo    Downlo    Downlo    Downlo    Downloading: 80%m
    Downlo    Downlo    Downlo    Downloading: 100%
```

And now:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

FWIW, Windows 10. Composer itself is also up-to-date.

[composer.txt](https://github.com/wp-cli/wp-cli/files/58216/composer.txt)

**Comment by danielbachhuber** [comment]
Right. `composer.lock` locks your project to the hash present in the lock file. You'll need to `rm composer.lock` before running `composer update`

**Comment by ethanclevenger91** [comment]
Shouldn't `composer update` update the `composer.lock` file?

**Comment by ethanclevenger91** [comment]
Also - removing `composer.lock` and then running `composer update` regenerates the lock file and still doesn't update.

**Comment by danielbachhuber** [comment]
What is the contents of your `composer.json`?

**Comment by danielbachhuber** [comment]
Huh. `composer create-project wp-cli/wp-cli --no-dev` doesn't produce an installation that can be updated. You need to remove `wp-cli/cli` and re-run the command.

You can also reinstall with `composer create-project wp-cli/wp-cli --prefer-source`. Once you've done so, you can update as you would with Git:

```
cd wp-cli
git pull origin master
composer install
```

**Comment by ethanclevenger91** [comment]
Will it be updatable if I leave off the `--no-dev`?

**Comment by danielbachhuber** [comment]
Nope.

Btw, I'd recommend [Phar installation](http://wp-cli.org/#install) unless there's some specific reason you're using Composer.

**Comment by ethanclevenger91** [comment]
Fair enough. I've never figured out `.phar` and Windows, but may give it another stab. Thanks!
