### ISSUE TITLE
Cannot upgrade wp-cli

### ISSUE THREAD

**Issue by jschank** [wp-cli/wp-cli#2290]
Try as I might, I cannot seem to get wp-cli to a more recent version.
Currently, I am on
```
# wp --info
PHP binary:	/usr/bin/php
PHP version:	5.5.24
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.19.1
```
And since I am using wordpress 4.4, I need something more recent.

I have even tried downloading using the nightly build url.
(I am using phar to do the install)

Any suggestions on how to update would be appreciated. (or suggestions on how to diagnose the problem)

Thanks,
John

**Comment by danielbachhuber** [comment]
Can you provide the results of `which -a wp` ?

You've likely installed WP-CLI twice, and the older version is taking precedent over the newer.

**Comment by jschank** [comment]
```
# which -a wp
/usr/local/bin/wp
/usr/bin/wp
```

So I deduce from this that I have two versions deployed?

**Comment by jschank** [comment]
Yep, and I see that the `/usr/bin/wp` version is the latest. But my path is pulling `/usr/local/bin` in preference.

Not even sure how the /local one got there. but I'll kill em both and reinstall.

**Comment by jschank** [comment]
Interesting note: I tried `which` before, but I wasn't aware of the -a flag. TIL
