### ISSUE TITLE
Wordpress 4.4 "Class 'WP_Widget' not found" errors

### ISSUE THREAD

**Issue by moses-moore-spafax** [wp-cli/wp-cli#2291]
After upgrading Wordpress core to 4.4 (2015 Dec 08), wp-cli crashes with PHP fatal error.  I've seen this on three different sites on three different machines so far.

Steps to reproduce:
- cd public_html
- wp-cli core update
- wp-cli

Expect to see:  man page of how to use wp-cli

Seen instead:
"Fatal error: Class 'WP_Widget' not found in /.../public_html/wp-includes/widgets/class-wp-widget-pages.php on line 17"
It may also report this problem in a plugin's code, like Akismet, but this is the error message I get after disabling all plugins on the site, so I feel this is a problem with wp-cli and WordPress core, not a plugin.

**Comment by danielbachhuber** [comment]
Please [update WP-CLI](http://wp-cli.org/blog/versions-0.21.1-and-0.20.4.html) and, next time, search past issues before you open a new issue.

**Comment by moses-moore-spafax** [comment]
Understood.  Duplicate of #2284

**Comment by penghuajun** [comment]
Please update WP-CLI WP-CLI version:	0.22.0

**Comment by thinkhuman** [comment]
I get the error too. I've got the latest wp-cli installed, because I blew it away and installed anew.

`wp-cli update` still doesn't work for me. Result message: `Error: 'cli update' is not a registered wp command.`

**Comment by danielbachhuber** [comment]
@thinkhuman Can you open a new issue please, with the [debugging steps](http://wp-cli.org/docs/bug-reports/) completed? Thanks
