### ISSUE TITLE
No .gitignore is included in scaffolded plugins

### ISSUE THREAD

**Issue by duncanjbrown** [wp-cli/wp-cli#2296]
Noting that my plugin scaffold came with a `Gruntfile` that does useful things, I ran `npm install`. I then found a whole `node_modules` folder ready to go into my git index. 

Usually when working on a project with `npm` I would add `node_modules` to `.gitignore`. Why not include a `.gitignore` with the scaffold?

If wp-cli policy is that `node_modules` should be added to system-wide git config, that's fine. If not, I can send a PR.

**Comment by danielbachhuber** [comment]
Default `.gitignore` would be helpful. We might also want to ignore `.DS_Store` and `vendor` directories.

**Comment by duncanjbrown** [comment]
Great! PR to follow. Given that the `composer init` process offers the option to `.gitignore` `vendor`, and there's no `composer.json` by default (though maybe there should be) I'll start with just `node_modules` and `.DS_Store`.

**Comment by danielbachhuber** [comment]
:ship:
