### ISSUE TITLE
getConfigs() error with WP4.4 & 0.21.1

### ISSUE THREAD

**Issue by lanfun** [wp-cli/wp-cli#2298]
WP-CLI version 0.21.1 and WP 4.4 generate the following error:

Fatal error: Call to a member function getConfigs() on null in ....

Example plug-ins which trigger this error are:

/plugins/addthis/addthis_addjs_new.php
/plugins/instagramy/instagramy-admin.php

Can you solve this? Thanks!

**Comment by danielbachhuber** [comment]
Although you haven't provided enough detail for me to communicate the exact source of the problem, I suspect the code is calling global variables which aren't explicitly globalized.

See also https://github.com/wp-cli/wp-cli/issues/2289#issuecomment-163959059
