### ISSUE TITLE
wp core download to use local file or custom external url

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#2299]
Hi,

It would be nice to be able to specify a local install package so it doesn't pull it from the live server all the time because it seems on Windows at least the package is not saved in the cache folder. I've defined the cache dir in the ENV.

https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php

Slavi

**Comment by danielbachhuber** [comment]
Why would you need to use `wp core download` if you already have a copy of core locally? Couldn't you just use `unzip /path/to/file.zip`?

**Comment by lordspace** [comment]
Hmm, I see what you're saying.
I just wanted things to be standard so I can switch to local or live wp copy

**Comment by lordspace** [comment]
The other semi-annoying thing is that the wp package contains the wordpress folder. Will have to do some moving/renaming after the unzip
