### ISSUE TITLE
Install plugin from WP plugin's page url

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#2303]
It would be nice to be able to install a plugin from WP.org plugin's page url and by default pull the latest version or if the user enters --verison to pull that specific version
e.g. 
wp plugin install https://wordpress.org/plugins/orbisius-child-theme-creator/

This would translate to: https://downloads.wordpress.org/plugin/orbisius-child-theme-creator.1.2.9.zip

**Comment by danielbachhuber** [comment]
You should just use `wp plugin install orbisius-child-theme-creator`

The slug in the URL is the plugin slug.

**Comment by lordspace** [comment]
I was thinking of having that in addition to the other approaches
