### ISSUE TITLE
Renaming media files

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#2307]
Would it be possible to rename a media file then `wp search-replace OLDURL NEWURL` for each size?

**Comment by danielbachhuber** [comment]
I don't see why not. Worth testing on a local install, though.

**Comment by szepeviktor** [comment]
Excuse me, I do not know how to modify a media file's name in WP.
I've seen two plugins doing this but I have no clue whether that is the way to do it.

**Comment by danielbachhuber** [comment]
> Excuse me, I do not know how to modify a media file's name in WP.

Sorry — that's outside the scope of this issue tracker.

**Comment by szepeviktor** [comment]
Would it be possible to implement it in `wp media rename ...`?

**Comment by danielbachhuber** [comment]
> Would it be possible to implement it in wp media rename ...?

If someone opens a pull request for it, I'd consider it. However, this is the first time I've come across the need to rename media files, so I don't think it's a terribly common problem to be solved.

**Comment by szepeviktor** [comment]
Thanks.
Could you give me a hint where to look for a way to rename media in WP?

**Comment by danielbachhuber** [comment]
> Could you give me a hint where to look for a way to rename media in WP?

Please be respectful of the purposes of this issue tracker.
