### ISSUE TITLE
Command for listing all types of updates available

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2310]
Is there command for listing all update available? Eg, view updates or core, themes and plugins in a single command? I searched the commands in the doc but could not find so? If it already does not exists, then this would be very useful command. Just my two cent.

**Comment by danielbachhuber** [comment]
> Is there command for listing all update available?

Nope.

> Eg, view updates or core, themes and plugins in a single command?

You could run `wp core check-update && wp plugin list --update=available && wp plugin theme --update=available` to get all updates.

**Comment by heymo** [comment]
I know this is an old issue, but just for reference I think the command needs to read like this:

`wp core check-update && wp plugin list --update=available && wp theme list --update=available`
