### ISSUE TITLE
Error when trying to install plugins

### ISSUE THREAD

**Issue by garybrowne** [wp-cli/wp-cli#2313]
I'm using wp-cli to manage my plugins and themes, but I cannot get it to install plugins. For example:

```wp plugin install add-this```

results in:

```Warning: add-this: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>.```

I get the same error for other plugins I try to install. My setup is:

O/S: Ubuntu 15.10
Web server: Apache 2.4.10
PHP: 5.6.4
Wordpress: 4.4

I have no idea what "server configuration" I need to change or why this stopped working in the first place. If anyone could help it would be very much appreciated!

**Comment by johnbillion** [comment]
Do you get the same error if you attempt to install a plugin or theme through the corresponding 'Add New' screen in the WordPress admin area?

**Comment by garybrowne** [comment]
No, but it seems to be working again, although I am still presented with the same PHP notice. Not sure what happened there. Thanks for your response anyway.
