### ISSUE TITLE
wp-cli-0.21.1 slight plugin install diagnostic bug related to permission checking

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#2315]
Summary - wp install --activate - reports both failure + success + actually does succeed. Diagnostic message is incorrect.

Details...

net4-dev# wp-cli.phar --allow-root --info
PHP binary:	/usr/bin/php5
PHP version:	5.6.11-1ubuntu3.1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.21.1

To reproduce...

cd .../wordpress

net4-dev# wp core version
4.4

net4-dev# ls wp-content/plugins
index.php

### Install --activate plugin reports as both failure + success.

net4-dev# /bin/ls -hFqld --group-directories-first --color .
drwxr-x--- 5 www-data www-data 4.0K Dec 20 17:16 ./

net4-dev# sudo -u www-data $(which wp-cli.phar) plugin install wp-fail2ban --activate
Installing WP fail2ban (2.3.1)
PHP Warning:  mkdir(): Permission denied in phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php on line 265
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:699
PHP   6. WP_CLI\Runner->run_command() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:318
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:311
PHP   8. call_user_func:{phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295
PHP  10. call_user_func:{phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  11. Plugin_Command->install() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  12. WP_CLI\CommandWithUpgrade->install() phar:///david-favor/tools/wp-cli.phar/php/commands/plugin.php:447
PHP  13. Plugin_Command->install_from_repo() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/CommandWithUpgrade.php:145
PHP  14. WP_CLI::get_http_cache_manager() phar:///david-favor/tools/wp-cli.phar/php/commands/plugin.php:316
PHP  15. WP_CLI::get_cache() phar:///david-favor/tools/wp-cli.phar/php/class-wp-cli.php:131
PHP  16. WP_CLI\FileCache->__construct() phar:///david-favor/tools/wp-cli.phar/php/class-wp-cli.php:79
PHP  17. WP_CLI\FileCache->ensure_dir_exists() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php:56
PHP  18. mkdir() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php:265
Downloading install package from https://downloads.wordpress.org/plugin/wp-fail2ban.2.3.2.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Translations updates are not needed for the 'English (US)' locale.
Activating 'wp-fail2ban'...
Warning: Plugin 'wp-fail2ban' is already active.

### Plugin is in fact installed

net4-dev# ll wp-content/plugins
total 8.0K
drwxr-xr-x 2 www-data www-data 4.0K Dec 21 07:39 wp-fail2ban/
-rw-r--r-- 1 www-data www-data   28 Dec 20 17:16 index.php

### Plugin delete works fine

net4-dev# sudo -u www-data $(which wp-cli.phar) plugin delete wp-fail2ban
Success: Deleted 'wp-fail2ban' plugin.

### Opening all permissions still produces same output

net4-dev# chmod 777 .
net4-dev# sudo -u www-data $(which wp-cli.phar) plugin install wp-fail2ban --activate
Installing WP fail2ban (2.3.1)
PHP Warning:  mkdir(): Permission denied in phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php on line 265
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:699
PHP   6. WP_CLI\Runner->run_command() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:318
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:311
PHP   8. call_user_func:{phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/Subcommand.php:295
PHP  10. call_user_func:{phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52}() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  11. Plugin_Command->install() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  12. WP_CLI\CommandWithUpgrade->install() phar:///david-favor/tools/wp-cli.phar/php/commands/plugin.php:447
PHP  13. Plugin_Command->install_from_repo() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/CommandWithUpgrade.php:145
PHP  14. WP_CLI::get_http_cache_manager() phar:///david-favor/tools/wp-cli.phar/php/commands/plugin.php:316
PHP  15. WP_CLI::get_cache() phar:///david-favor/tools/wp-cli.phar/php/class-wp-cli.php:131
PHP  16. WP_CLI\FileCache->__construct() phar:///david-favor/tools/wp-cli.phar/php/class-wp-cli.php:79
PHP  17. WP_CLI\FileCache->ensure_dir_exists() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php:56
PHP  18. mkdir() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/FileCache.php:265
Downloading install package from https://downloads.wordpress.org/plugin/wp-fail2ban.2.3.2.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Translations updates are not needed for the 'English (US)' locale.
Activating 'wp-fail2ban'...
Warning: Plugin 'wp-fail2ban' is already active.

### root user works, apache user fails, likely a WP-4.4 issue

net4-dev# chmod 750 .
net4-dev# sudo -u www-data $(which wp-cli.phar) plugin delete wp-fail2ban 
Success: Deleted 'wp-fail2ban' plugin.
net4-dev# wp plugin install wp-fail2ban --activate
Installing WP fail2ban (2.3.1)
Downloading install package from https://downloads.wordpress.org/plugin/wp-fail2ban.2.3.2.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Translations updates are not needed for the 'English (US)' locale.
Activating 'wp-fail2ban'...
Warning: Plugin 'wp-fail2ban' is already active.
net4-dev# chown -hR www-data:www-data wp-content/plugins

**Comment by danielbachhuber** [comment]
If you use `wp plugin delete`, WP-CLI deletes the plugin files without removing the plugin from the `active_plugins` option + triggering the uninstall hook.

You can use `wp plugin uninstall --deactivate` to remove the plugins files, and remove it from `active_plugins`.

**Comment by davidfavor** [comment]
This bug is about - plugin install.

Please read the bug again. Plugin uninstall works fine.

Plugin install is what's broken... either in wp-cli or WP core.

**Comment by davidfavor** [comment]
This behavior occurs first time a plugin is installed, so appears to have no relation to left over plugin residue from an uninstall.

**Comment by danielbachhuber** [comment]
I can't reproduce:

```
salty-wordpress ➜  wordpress-test.dev  wp plugin install wp-fail2ban --activate
Installing WP fail2ban (2.3.1)
Downloading install package from https://downloads.wordpress.org/plugin/wp-fail2ban.2.3.2.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Translations updates are not needed for the 'English (US)' locale.
Activating 'wp-fail2ban'...
Success: Plugin 'wp-fail2ban' activated.
```

Regarding:

> This behavior occurs first time a plugin is installed, so appears to have no relation to left over plugin residue from an uninstall.

This is with a brand new WordPress install? Can you reproduce with a second brand new WordPress install in a separate environment?
