### ISSUE TITLE
PHP Notice:  Constant WP_CACHE already defined in /opt/wp-cli/php/WP_CLI/Runner.php(732) : eval()'d code on line 77

### ISSUE THREAD

**Issue by connerbw** [wp-cli/wp-cli#2332]
Every time i do `wp` I get:

PHP Notice:  Constant WP_CACHE already defined in /opt/wp-cli/php/WP_CLI/Runner.php(732) : eval()'d code on line 77

WP_CACHE is defined in my wp-config.php file.

More info:

```
$ wp --version
WP-CLI 0.22.0-alpha
```

**Comment by danielbachhuber** [comment]
> WP_CACHE is defined in my wp-config.php file.

Can you share the full contents of your wp-config.php file, with any secrets removed?

**Comment by connerbw** [comment]
Woops, sorry. Nobug. 

WP_CACHE was defined twice in the config. 

Thanks.
