### ISSUE TITLE
Error delete _transient option when update-db in WP Multisite

### ISSUE THREAD

**Issue by sugengsuprayogi** [wp-cli/wp-cli#2356]
Error delete _transient option when update-db in WP Multisite
I'm using WP Multisite with hyperdb

WordPress database error Table 'wpmu_global.wp_8855_options' doesn't exist for query DELETE a, b FROM wp_8855_options a, wp_8855_options b
                WHERE a.option_name LIKE '\\_transient\\_%'
                AND a.option_name NOT LIKE '\\_transient\\_timeout\\_%'
                AND b.option_name = CONCAT( '_transient_timeout_', SUBSTRING( a.option_name, 12 ) )
                AND b.option_value < 1452069321 made by populate_options

**Comment by danielbachhuber** [comment]
Can you try using the latest nightly build of WP-CLI? `wp cli update --nightly`

I believe your issue may have been fixed with #2318

**Comment by sugengsuprayogi** [comment]
My script

php wp-cli.phar --url=$url core update-db --nightly

Error: Parameter errors:
 unknown --nightly parameter

**Comment by danielbachhuber** [comment]
It would be:

```
php wp-cli.phar cli update --nightly
```

However, since 0.22.0 is released, you could just use:

```
php wp-cli.phar cli update
```
