### ISSUE TITLE
Between no-debug and debug

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#2364]
I do like debug output but it would be nice to hide these initial lines, up to and including `Running command:`
```
$ wp --allow-root cache type
Debug: Using default global config: /root/.wp-cli/config.yml (0.008s)
Debug: Using project config: /var/www/subtwo/wp-cli.yml (0.008s)
Debug: Required file from config: /root/.wp-cli/commands/wp-cli-database-prefix-command/wp-cli-database-prefix-command.php (0.019s)
Debug: Required file from config: /root/.wp-cli/commands/wp-cli-extra-config-command/wp-cli-extra-config-command.php (0.02s)
Debug: ABSPATH defined: /var/www/subtwo/2/ (0.02s)
Debug: Set URL: http://subtwo.wp (0.02s)
Debug: Begin WordPress load (0.02s)
Debug: wp-config.php path: /var/www/subtwo/2/wp-config.php (0.02s)
Debug: Loaded WordPress (0.289s)
Debug: Running command: cache type (0.29s)
Redis
```
How about introducing an option for that?

**Comment by danielbachhuber** [comment]
> but it would be nice to hide these initial lines, up to and including Running command:

I'm not sure I follow. What would `--debug` include, if not those lines?

> How about introducing an option for that?

I'm not confined it should be an option. The point of `--debug` is to give you as much information as possible, for the purposes of debugging whatever problem is at hand.

**Comment by szepeviktor** [comment]
Whatever I do with WP-CLI I see the same lines (I am talking only the above 10lines), It would be nice to hide *only* these 10 lines with a new option and display all other debug lines.

**Comment by danielbachhuber** [comment]
> Whatever I do with WP-CLI I see the same lines (I am talking only the above 10lines),

But they'll be different if you're running WP-CLI in a different context. If they're always the same, and it's something that's bothering you, you should probably disable `--debug` and only use it when you need it.

**Comment by szepeviktor** [comment]
OK-OK.
It there a way to write a command that mutes these lines?
