### ISSUE TITLE
Reading wp-config.php env vars in database settings

### ISSUE THREAD

**Issue by NathanKleekamp** [wp-cli/wp-cli#2365]
In order to commit our wp-config.php file to a public git repo, we use environmental variables instead of strings for our db settings, like this:

```
define('DB_NAME', getenv('DB_NAME'));
```

It appears wp-cli only works with strings, however. Is there any chance of getting support for this feature?

**Comment by danielbachhuber** [comment]
> It appears wp-cli only works with strings, however.

How are you supplying your environment variables? Are they defined in the CLI context?

**Comment by mselner** [comment]
HI I also have this issue. I could provide the variables as part of the CLI context or pass them on the command line like used for "wp core config".
thanks

**Comment by danielbachhuber** [comment]
> HI I also have this issue. I could provide the variables as part of the CLI context or pass them on the command line like used for "wp core config".

Sorry, is there a question in this? Here are some ways you can define environment variables in CLI context: http://stackoverflow.com/questions/18098006/setting-php-enviromental-variable-while-running-command-line-script

**Comment by mselner** [comment]
Hello. I didn't think it was that simple!

I ran it like this (all one line):

WP_DB_NAME ="example" WP_DB_USER ="example" WP_DB_PASSWORD ="secret" WP_DB_HOST ="localhost"  /path/to/wp-cli  --path=/path/to/example/site  core check-update

and it worked:
Success: WordPress is at the latest version.

To clarify, I set the variables in the apache config file inside my <Virtualhost> section like this:

SetEnv WP_DB_NAME "example"
SetEnv WP_DB_USER "example"
SetEnv WP_DB_PASSWORD "secret"
SetEnv WP_DB_HOST "localhost"

and reference them in wp-config.php like this:

define('DB_NAME', $_SERVER['WP_DB_NAME']);
define('DB_USER', $_SERVER['WP_DB_USER']);
define('DB_PASSWORD', $_SERVER['WP_DB_PASSWORD']);
define('DB_HOST', $_SERVER['WP_DB_HOST']);

And this works fine for normal WP access (Apache passes environment vars within $_SERVER).
