### ISSUE TITLE
Fails to recognise Wordpress apt package as being a valid install

### ISSUE THREAD

**Issue by austinjp** [wp-cli/wp-cli#2367]
Hi there.

I'm installing wp-cli inside an LXC container which has Wordpress installed using apt-get install wordpress. I've done this many times, the config files are all in place and Wordpress is working fine i.e. is accessible using a browser.

However, unfortunately wp-cli doesn't recognise the installation:

```bash
$ wp --debug --allow-root option get home --path=/usr/share/wordpress/
Debug: No readable global config found (0.01s)
Debug: No project config found (0.011s)
Debug: ABSPATH defined: /usr/share/wordpress/ (0.022s)
Debug: Begin WordPress load (0.023s)
Debug: wp-config.php path: /usr/share/wordpress/wp-config.php (0.023s)
Error: The site you have requested is not installed.
Run `wp core install`.
```

I am running this as root (bad habit I know).

The apt package manager installs Wordpress in `/usr/share/wordpress` with config files in `/etc/wordpress/config-*.php` and `/usr/share/wordpress/wp-config.php` etc.

It seems that [wp-cli/utils-wp.php](https://github.com/wp-cli/wp-cli/blob/master/php/utils-wp.php) calls a Wordpress function `is_blog_installed()` which appears to fail.

However the installation is perfectly valid and functioning. Any ideas? :smiley:

**Comment by austinjp** [comment]
Okay I worked out why -- I hadn't run the web-based Wordpress installation process. Doh!

You can safely ignore this -- although perhaps the error message could prompt the user "Have you installed Wordpress, or completed the installation process?" or similar.

**Comment by schrapel** [comment]
You could've just ran the command 'wp core install' as suggested

**Comment by austinjp** [comment]
Hi @schrapel 

I didn't want to run `wp core install` because apt had already installed Wordpress. Pointing my web browser at the server and completing the basic setup there fixed things, and wp-cli happily completed the upgrade after.

The apt package installs 3.8 by default, and I wanted to use wp-cli to perform an upgrade, which it did.
