### ISSUE TITLE
Waiting for `user list`

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#2369]
```
$ time wp --allow-root user list --format=count
62408
real    0m46.424s
user    0m43.460s
sys     0m1.760s
```
It is a Xeon E3-1240 server with zero load.
What could be the reason?

**Comment by danielbachhuber** [comment]
@szepeviktor Can you try the `2369-list-user-perf` branch to see if that improves performance for you? I suspect you're running into a couple bad SQL queries.

**Comment by szepeviktor** [comment]
```
$ time ../wpcli/wp-cli-2369-list-user-perf/bin/wp --allow-root user list --format=count
62410
real    0m0.452s
user    0m0.412s
sys     0m0.032s
```
0,97% of the original.

**Comment by danielbachhuber** [comment]
:+1: Thanks for running that.
