### ISSUE TITLE
PHP Fatal Error Running wp-cli core install

### ISSUE THREAD

**Issue by gjgreen** [wp-cli/wp-cli#2372]
I'm trying to run wp-cli core install for the firs time and get the following error:
PHP Fatal error:  Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(756) : eval()'d code on line 108
I have the following filter defined in my wp-config.php

```
// Disable update emails
add_filter( 'auto_core_update_send_email', '__return_false' );
```
Commenting the filter allows the install to proceed. That filter is part of our standard wp-config.php it would be nice to be able to run the install with needing to disable this setting.

PHP version 5.5.3
WP version 4.4.1
WP-CLI version: 0.22.0

**Comment by danielbachhuber** [comment]
You should move the filter to a `mu-plugin`.

See thread in #1631
