### ISSUE TITLE
Customising the Settings Options in WordPress Admin

### ISSUE THREAD

**Issue by JakeHenshall** [wp-cli/wp-cli#2380]
Hi,

Is there a way to customise the settings options in the WordPress like the below:

Untick Search Engine Visibility
Untick Trackbacks / Pingbacks
Untick Show Avatars

Thanks Jake.

**Comment by danielbachhuber** [comment]
You can use `wp option update` ([docs](http://wp-cli.org/commands/option/update/)) to set these options.
