### ISSUE TITLE
Removing the Dashboard Cards / Screen Options

### ISSUE THREAD

**Issue by JakeHenshall** [wp-cli/wp-cli#2381]
Hi,

I've attached an image to show what I mean. I would automatically like to remove the cards / disabled from view in the screen options.

This may help:

https://codex.wordpress.org/Class_Reference/WP_Screen

![remove dashboard cards](https://cloud.githubusercontent.com/assets/4720782/12352370/5d385b94-bb7d-11e5-8a0a-205dc60ace1e.png)

**Comment by danielbachhuber** [comment]
You can use:

```
wp user meta update 1 show_welcome_panel 0
```
