### ISSUE TITLE
wp-cli backward compatibility range for WordPress core

### ISSUE THREAD

**Issue by here** [wp-cli/wp-cli#2385]
I'm updating wp-cli to v21.1+ for WordPress core v4.4+ , and we also use this wp-cli executable as a shared resource for managing WordPress installations still running v4.1.x , v4.2.x , etc.

Is there any testing or documentation around how far back wp-cli releases support older WordPress core branches?  For example if wp-cli v22.0 is relying on features new to WordPress core in v4.4, we will need to wait in upgrading wp-cli for managing those sites until we get WordPress core up to date.

WordPress core releases security updates for at least a few major releases back ( ~1 year? ).  If wp-cli isn't able to support that range (for good reasons), it would be ideal if we can find out when wp-cli releases include breaking changes for older WordPress branches.

Possible https://github.com/wp-cli/wp-cli/wiki/FAQ ?

Thank you!

**Comment by here** [comment]
Related release notes regarding v21.1 and WordPress v4.4+ at http://wp-cli.org/blog/versions-0.21.1-and-0.20.4.html

**Comment by here** [comment]
..and someone helpfully points out that the wp-cli.org homepage clearly shows "WordPress 3.5.2 or later".

Unless there is further detail or comment, this can be closed.

**Comment by danielbachhuber** [comment]
I need to update the homepage. WP-CLI now supports WP 3.7 and higher.

**Comment by danielbachhuber** [comment]
Updated the homepage.
