### ISSUE TITLE
WP_CLI::error() should support custom exit codes

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#2386]
`public static function error( $message, $exit = true )`

It would be handy if `$exit` could also support integer values which then will be used for the exit code, which is currently `1` per default.

Use case: You have a command which can return more than one failures depending on the input. The command is called by another script. In this case different exit codes would make error handling in the other script easier.
Thoughts?

```php
/**
 * Display an error in the CLI and end with a newline
 *
 * @param string|WP_Error $message
 * @param bool|int        $exit    If true, the script will exit(1), if status
 *                                 is an integer, that value will be used as the
 *                                 exit status.
 */
public static function error( $message, $exit = true ) {
	if ( ! isset( self::get_runner()->assoc_args[ 'completions' ] ) ) {
		self::$logger->error( self::error_to_string( $message ) );
	}

	if ( true === $exit ) {
		exit( 1 );
	} elseif ( is_int( $exit ) ) {
		exit( $exit );
	}
}
```

**Comment by danielbachhuber** [comment]
> It would be handy if $exit could also support integer values which then will be used for the exit code, which is currently 1 per default.

:+1: 

Related #1430

**Comment by ocean90** [comment]
@danielbachhuber Does the code look proper to you? Happy to provide a PR with one or two tests then.

Another idea would be `public static function error( $message, $exit = true, $exit_code = 1 ) {}`.

**Comment by danielbachhuber** [comment]
> Does the code look proper to you?

Yes, I prefer:

```
if ( true === $exit ) {
	exit( 1 );
} elseif ( is_int( $exit ) && $exit >= 1 ) {
	exit( $exit );
}
```
> Happy to provide a PR with one or two tests then.

Great!
