### ISSUE TITLE
No output at all on a Debian server

### ISSUE THREAD

**Issue by lucasbracher** [wp-cli/wp-cli#2390]
Running wp returns nothing and does nothing on a Debian box.
On my other servers is running ok.
wp --debug returns nothing as well.

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 6.0.5 (squeeze)
Release:	6.0.5
Codename:	squeeze

uname -a
Linux Endor 2.6.32-5-amd64 #1 SMP Sun May 6 04:00:17 UTC 2012 x86_64 GNU/Linux

which -a php
/usr/bin/php

php -v
PHP 5.3.3-7+squeeze28 with Suhosin-Patch (cli) (built: Nov  8 2015 18:16:13) 
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Suhosin v0.9.32.1, Copyright (c) 2007-2010, by SektionEins GmbH

php -m | grep -i suhosin
suhosin
Suhosin

grep '^\$wp_version\s' wp-includes/version.php
grep: wp-includes/version.php: No such file or directory

which -a wp
/usr/local/bin/wp

stat $(which wp)
  File: `/usr/local/bin/wp'
  Size: 1469311   	Blocks: 2880       IO Block: 4096   regular file
Device: 803h/2051d	Inode: 481904      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (   50/   staff)
Access: 2016-01-18 18:36:01.000000000 -0200
Modify: 2016-01-18 18:35:13.000000000 -0200
Change: 2016-01-18 18:35:52.000000000 -0200

wp --allow-root --info
(nothing)

**Comment by danielbachhuber** [comment]
Can you review #1758 to see if any of the discussion on that thread may help you debug?

**Comment by davidfavor** [comment]
Might be useful to mention how you installed wp.

For example...

curl -s -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

Or by other means. Using the http://wp-cli.org instructions (above curl invocation) resolved many challenges I was having.

**Comment by lucasbracher** [comment]
Downloading compose and source solved the issue for me.

Thank you! :)

Lucas Bracher
+55 32 8458-7377
+55 21 98669-8461 (Whatsapp)
