### ISSUE TITLE
Enhancement request: Add -c wp-cli.yml option to specify a configuration file

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#2391]
Current work around now appears to be symlinking many install directories to .yml file in wordpress root.

Be great if this file could be passed directly to wp-cli at invocation time.

**Comment by danielbachhuber** [comment]
You can already use `--config=<path>`, which isn't documented because it's deprecated.

Here's the history on why it's deprecated: https://github.com/wp-cli/wp-cli/pull/698#issuecomment-26939247

**Comment by davidfavor** [comment]
Thanks. Be great if --config can be retained through future, as this is highly useful in situations where many 100s-1000s of WordPress installs are managed on a physical machine... and...

Different config files are passed for different operations.

Thanks for your consideration of this retention request.

**Comment by davidfavor** [comment]
Hum... Appears --config no longer works... Refers users to use WP_CLI_CONFIG_PATH which seems to fail in some cases.

net4-dev# wp-cli.phar --allow-root --config=/david-favor/etc/wp-cli/wp-cli.yml rewrite structure '/%postname%' --hard --debug
WP-CLI: The --config global parameter is deprecated. Use the WP_CLI_CONFIG_PATH environment variable instead.
Debug: No readable global config found (0.019s)
Debug: No project config found (0.02s)
Debug: ABSPATH defined: /sites/ms1/liveallheart.com/wordpress/ (0.038s)
Debug: Begin WordPress load (0.038s)
Debug: wp-config.php path: /sites/ms1/liveallheart.com/wordpress/wp-config.php (0.038s)
Debug: Loaded WordPress (0.273s)
Debug: Running command: rewrite structure (0.273s)
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.

Success: Rewrite structure set.
net4-dev# cat .htaccess
cat: .htaccess: No such file or directory

**Comment by danielbachhuber** [comment]
> Appears --config no longer works

Given it appears in your debug log, `--config` does in fact work. The debug also says:

```
Debug: No readable global config found (0.019s)
```

This means that your global config file isn't readable by WP-CLI, which means any settings defined in it aren't applied.
