### ISSUE TITLE
How to remove WP from the root in Mac

### ISSUE THREAD

**Issue by ahmadawais** [wp-cli/wp-cli#2392]
Something messed up for sure. Since whenever I start the terminal it tells me to
![](https://i.imgur.com/jGXxNlw.png)
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.

```

How to remove this error?

BTW there is nothing in the root to suggest that it's WP but there are symlinks which were never an issue 

![](https://i.imgur.com/aUAOWdY.png)

**Comment by danielbachhuber** [comment]
> How to remove this error?

WP-CLI appears to be executing every time you open a new session. 

I might recommend checking your `.zshrc` (or `.bashrc`) to see if you have a poorly formed alias that's calling WP-CLI instead of defining `wp` when the profile is loaded.

Alternatively, you may have located your copy of WP-CLI in an "auto-run" directory.

**Comment by ahmadawais** [comment]
Thanks for the quick response @danielbachhuber !

Here's my `.zshrc` file and the exact lines where I have a few aliases and a function for WP CLI https://github.com/ahmadawais/dotFiles/blob/master/.zshrc#L409-L454

This is really annoying, most of the time a new tab just gets stuck. Any advice would be appreciated. Pointers about where to look in. What is the auto-run directory?

**Comment by danielbachhuber** [comment]
I don't have any good ideas, unfortunately :(

Where is WP-CLI installed? Can you share `which -a wp` ?

**Comment by ahmadawais** [comment]
@danielbachhuber  :(

It's installed in the local bin `/usr/local/bin/wp`. See if you could suggest something.

**Comment by ahmadawais** [comment]
@danielbachhuber Found the issue. 

It was a buggy alias 
```
alias wpdb="wp post delete $(wp post list --post_type='vr_booking' --format=ids)"

```

I deleted WPCLI and ZSH told me the error

```
/Users/ahmadawais/.zshrc:457: command not found: wp

```

Then I removed this alias and reinstalled WPCLI. 

Everything is fine now. 

Just in case anyone gets the same error.
