### ISSUE TITLE
wrong extention type with wp media import

### ISSUE THREAD

**Issue by jasonhai** [wp-cli/wp-cli#2393]
Hello Friends,

Im processing on the function "wp media import" to import my images into system. But i really that it was wrong...

I run by this way: wp media import /var/www/project_name/1450405551.jpg 

When it run and completed. I received images with extension type is: *.png

I dont know why is that? Could you please checked and lets me know?

I would be appreciate for your supports.

Thanks and regards!
Jason

**Comment by danielbachhuber** [comment]
Deep under the hood, WordPress calls `_wp_handle_upload()`, which calls `wp_check_filetype_and_ext()`. This second function will set the extension of the uploaded file based on the file's mime type. While you think you had a JPEG, WordPress discovered your imported file was actually PNG and renamed it accordingly.
