### ISSUE TITLE
Update plugin from zip file

### ISSUE THREAD

**Issue by vercotux** [wp-cli/wp-cli#2394]
### Problem

Commercial 3rd party plugins are distributed through zip files and are not available in the standard WordPress plugin directory. Attempting to upgrade such a plugin will fail and produce the following warning message:

    Warning: Update package not available.

### Proposal

Add *zip* (and ideally *url*) parameter support to the [```wp plugin update```](http://wp-cli.org/commands/plugin/update/) command the same way it is possible with [```wp plugin install```](http://wp-cli.org/commands/plugin/install/):

> \<plugin|zip|url\>…
> A plugin slug, the path to a local zip file, or URL to a remote zip file.

**Comment by danielbachhuber** [comment]
No need for `wp plugin update`. You can run `wp plugin install --force <plugin|zip|url>` to achieve the same effect.

**Comment by vercotux** [comment]
I tried that, but it failed. Then I removed the plugin and ran a regular install and it worked. So clearly something is different. Should I open a new bug report for that?

**Comment by danielbachhuber** [comment]
> I tried that, but it failed. Then I removed the plugin and ran a regular install and it worked. So clearly something is different. Should I open a new bug report for that?

Can you share the full output from the procedure here?
