### ISSUE TITLE
Remote database

### ISSUE THREAD

**Issue by theuruguayan** [wp-cli/wp-cli#2399]
Guys, can i use wp-cli with a remote mysql database?

mysql works fine since i adjusted the /root/.my.cnf to the remote host, but the wp-cli still trying to find the mysql.sock.

Any information will be appreciated.

carlos

**Comment by danielbachhuber** [comment]
> mysql works fine since i adjusted the /root/.my.cnf to the remote host

To clarify, you're talking about the constants you've edited in your `wp-config.php` (e.g. `DB_HOST`)?

> but the wp-cli still trying to find the mysql.sock.

Can you share the error you see?

**Comment by theuruguayan** [comment]
I actually figure out why is doing that, you need to first create the configuration file before installing wordpress you need to pass the --dbhost=remoteip, then wp-cli will take that data per default then it will work. If not it will not because it seems to fail when there is no mysql.sock on the server ( is not reading the /root/.my.cnf either)

could be nice to be able to do wp-cli --host=remoteip so it will create the wordpress config file / etc automatically.

**Comment by kevinquinnyo** [comment]
Can we reopen this?  I don't know how I'm supposed to run commands when the server is either remote, or configured to use local TCP/IP (not a UNIX socket).

I think it's possible, incidentally with `wp core config` since there is a `dbhost=` option that both configures and uses that host for it's connection.  No such option seems to exist for other commands, such as `wp-cli --allow-root core install` which will result in an error like this:
```
wp-cli --allow-root core install --url="some-site.com" --title="Some Title" --admin_user="some_user" --admin_password="p4ssw0rd" --admin_email="email@example.com"
PHP Warning:  mysqli_real_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in /var/www/...

[..snip..]

Error: Error establishing a database connection
```

Note that I can access mysql just fine, manually:
```
# netstat -tnlp | grep mysql
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      28921/mysqld    

root@staging:/var/www/man-break.com/public# mysql -u root -h 127.0.0.1 -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.

[..snip..]
```

**Comment by danielbachhuber** [comment]
> No such option seems to exist for other commands, such as wp-cli --allow-root core install which will result in an error like this:

`wp core install` uses the DB configuration details stored in `wp-config.php`. If it can't connect to MySQL, then WordPress won't be able to connect to MySQL.

Are you sure the DB configuration details you've entered are correct?

**Comment by kevinquinnyo** [comment]
@danielbachhuber  Oh, I see it now.  DB_HOST in wp-config.php needs to be '127.0.0.1' -- for some reason it was 'localhost' in this wp-config.php which was making mysql try the unix socket.  If I switch localhost to 127.0.0.1 in wp-config.php it works. 

This must have been a wp-config.php that was not installed by wp-cli.  Thanks for helping me get to the bottom of this!  We can close now.
