### ISSUE TITLE
How do I add fields to wp post list and wp post get output?

### ISSUE THREAD

**Issue by mautematico** [wp-cli/wp-cli#2407]
I'm trying to find a way to get posts info, including extra fields (thar are not listed on the docs), something like:

```
wp post get 123 --fileds=ID,url,post_content,post_categories 
wp post list --post-status=publish --fileds=ID,url,post_content,post_categories 
```

But no success yet.
Right now I'm trying to write a plugin (or a wp eval-file's php file) to get this, but may be there is already some way to do it?

Thank you!

**Comment by danielbachhuber** [comment]
At this point, you'd need to write your own command for it. `wp post get` currently only exposes the `WP_Post` object, which doesn't include meta fields, taxonomy terms, etc.

Keep an eye on the [wp-rest-cli](https://github.com/danielbachhuber/wp-rest-cli) project though, as it will expose all of the fields [present on the Post Resource](http://v2.wp-api.org/reference/posts/)

**Comment by mautematico** [comment]
Thank you very much!
I'll keep an eye on https://github.com/danielbachhuber/wp-rest-cli

For those who may be interested, I managed to get what I need in a **dirty** way, using cgi:
https://gist.github.com/mautematico/eb2351dc5362da54dc29

I'm using cgi here just because I don't need (nor want) to load ALL the wordpress things to display a single post. I know this solution is not optimal, but it's enough for me. :D
