### ISSUE TITLE
Option to iterate over wp post list output?

### ISSUE THREAD

**Issue by mautematico** [wp-cli/wp-cli#2408]
Let's say I want to get a bouch of files, one for each of my wordpress posts:

```
#!/bin/bash

for post_id in $(wp --skip-themes post list --post_status=publish --field=ID)
do
               wp --skip-themes --skip-plugins post get $post_id  --format=json > /tmp/post/$post_id.json
done
echo "done"
```

There were A LOT of connections to DB.
Is it possible to get "iterate" over wp post list, and may be get something similar to this?

I know I can get a json array of post objects, but that's not the same as one file for each post. :)

Thank you for the hard (and good) work! :+1:

**Comment by danielbachhuber** [comment]
I did some googling around and wasn't able to find a one-liner for you.

I'd recommend exporting in one operation:

```
wp post list --format=json > posts.json
```

This will give you `posts.json` with a JSON array you can parse in some alternative way, without having to hit WordPress (and the DB) as you try your export procedure.

You might also find some luck using [jq](https://stedolan.github.io/jq/), although I wasn't able to find any built-in flags for this use case.

**Comment by mautematico** [comment]
Thank you very much!
jq seems exactly what I need on this case, I'll give it a try!

**Comment by mautematico** [comment]
Yep, I think this will do the trick.
For those who may be interested, have a look at this:

https://realguess.net/2014/05/18/split-a-large-json-file-into-smaller-pieces/

**Comment by mautematico** [comment]
And... Here you have!

https://gist.github.com/mautematico/5567fb3f1cad166dbc82

Again, Thank you, @danielbachhuber

**Comment by danielbachhuber** [comment]
Glad you've figured it out :)
