### ISSUE TITLE
Unkown --export parameter on Amazon EC2

### ISSUE THREAD

**Issue by MattiasMediaempire** [wp-cli/wp-cli#2410]
Trying to do a 

    wp search-replace "foo" "bar" --export=database.sql 

on my EC2 but for some reason I'm getting the following:

    Error: Parameter errors:
     unknown --export parameter

--debug gives the following: 

    Debug: No readable global config found (0.007s)
    Debug: No project config found (0.008s)
    Debug: ABSPATH defined: /usr/share/nginx/html/mediaempire/site/ (0.015s)
    Debug: Begin WordPress load (0.015s)
    Debug: wp-config.php path: /usr/share/nginx/html/mediaempire/site/wp-config.php (0.015s)
    Debug: Loaded WordPress (0.14s)
    Debug: Running command: search-replace (0.14s)
    Error: Parameter errors:
     unknown --export parameter

Some data:

    WP-CLI 0.21.1
    PHP 5.5.9-1ubuntu4.14

This works on Vagrant VVV with the exact same version numbers. Thankful for any response on what might be causing this!

**Comment by danielbachhuber** [comment]
You'll need to update to WP-CLI v0.22.0 to use the `--export` param, as the feature was only introduced in this most recent version.

**Comment by MattiasMediaempire** [comment]
Now that you mention it that makes sence. I compared the version number with my local installation which also runs 0.21, but I forgot to SSH into vagrant where the actual export was performed.

Thanks!
