### ISSUE TITLE
Do you really need to use exit() in commands?

### ISSUE THREAD

**Issue by johnReeve** [wp-cli/wp-cli#2411]
I really like this wp-cli work-- it's quite nice.

I'm using it inside an import script that I've written... I'd really like to be able to use it like:

            WP_CLI::run_command(['site', 'create'], ['slug' => $atts['slug'], 'title'=>$atts['title'] ]);
            $url = "http://{$atts['slug']}.apsprod.dev/";
            WP_CLI::set_url( $url );
            WP_CLI::run_command(['theme', 'activate', 'apsmain'], []);
            WP_CLI::run_command(['rewrite', 'structure', '/%postname%']);
            WP_CLI::run_command(['option', 'set', 'timezone_string', 'America/New_York']);
            WP_CLI::run_command(['option', 'set', 'default_comment_status', 'closed']);
            WP_CLI::run_command(['option', 'set', 'blogname', $atts['title']]);
            WP_CLI::run_command(['option', 'set', 'blogdescription', $atts['tagline']]);
....

But the theme command issues an exit() :(  Which means that my script halts after the             WP_CLI::run_command(['theme', 'activate', 'apsmain'], []);

Am I just being a bad programmer in using the software this way?  Is there a reason why Theme_Command::activate() needs to exit instead of returning?

**Comment by johnReeve** [comment]
I suppose I should add that I can just 

switch_theme();

But it would be nice to stick with the very convenient API you've written.

**Comment by danielbachhuber** [comment]
> But the theme command issues an exit() :( Which means that my script halts after the WP_CLI::run_command(['theme', 'activate', 'apsmain'], []);

Oh. It should only exit on error, but it appears to exit on success too. We can change that.

You can also use `WP_CLI::launch_self()`, which will launch a new process and let you inspect the return value.
