### ISSUE TITLE
The "theme update" command does not output JSON

### ISSUE THREAD

**Issue by Falc** [wp-cli/wp-cli#2415]
I am using the command `theme update` to preview the themes that will be updated, but it does not output a JSON result:
```
wp-cli theme update --all --path=/var/www/vhosts/mywordpress --json --dry-run
```

Then I tried the `--format` option with `table` and `summary` values. Both of them displays the same output, so it looks like there are some problems with the output part.

**Comment by danielbachhuber** [comment]
> but it does not output a JSON result:

The docs state:

```
Output summary as table or summary
```

JSON isn't supported.

>  Both of them displays the same output, so it looks like there are some problems with the output part.

Can you share the full result of both?

**Comment by sakrow** [comment]
I have the same problem, the code is (one example):

`wp-cli theme update --dry-run --all --format=summary --path=/var/www/vhosts/domain.com/httpdocs 
--allow-root`

And

`wp-cli theme update --dry-run --all --format=table --path=/var/www/vhosts/domain.com/httpdocs 
--allow-root`

The output:
![output](https://cloud.githubusercontent.com/assets/5989947/12584852/bfd4e4dc-c449-11e5-9f00-1b6d4f0a7914.jpg)

**Comment by Falc** [comment]
@danielbachhuber I see that it only supports table and summary, and both of them display the same output (@sakrow posted a good example).

Is `theme update` going to support JSON as format? How could I help with it?

**Comment by danielbachhuber** [comment]
> I see that it only supports table and summary, and both of them display the same output

Yes, I see that too. I need to debug when I have a moment.

> Is theme update going to support JSON as format?

It could, but I'm not sure what it would look like or how it would be useful. Can you share a use case?

**Comment by Falc** [comment]
@danielbachhuber we are using WP-CLI for WP management. Suppose we have 3 servers: `wpmanager`, `wp1` and `wp2`. `wpmanager` has a web UI that allows to manage WP instances installed on `wp1` and `wp2` through SSH (or a REST API), so we need commands to output JSON for interoperability purposes.

The web UI runs daily checks to show outdated core, plugins and themes, and stores info about the available updates for displaying some alerts and keeping the action history/log. In some cases the core, plugins and themes are updated automatically, and we need to know which ones where updated and the version.

So we would run something like...
```
wp-cli theme update --all --format=json --path=/wordpress/wptest.com
```
...and expect JSON output to know the new version and/or wether the update finished successfully:
```json
[
    {
        "name": "twentyfourteen",
        "status": "inactive",
        "version": "1.5",
        "update_version": "1.6"
    },
    {
        "name": "twentyfifteen",
        "status": "active",
        "version": "1.3",
        "update_version": "1.4"
    }
]
```

Since theme update does not output JSON, we decided to parse the output when format is summary or table, but we realized that both of them are identical. This is not a blocking issue for us, since we can workaround all of this by running `wp-cli theme list --format=json` before and after updating the themes and comparing the result. But it is strange to have JSON format support only for some commands.

**Comment by danielbachhuber** [comment]
> Since theme update does not output JSON, we decided to parse the output when format is summary or table, but we realized that both of them are identical.

They're actually slightly different. `--format=table` produces this at the end:

```
Success: Updated 1/1 themes.
+------+-------------+-------------+---------+
| name | old_version | new_version | status  |
+------+-------------+-------------+---------+
| p2   | 1.5         | 1.5.5       | Updated |
+------+-------------+-------------+---------+
```

`--format=summary` produces this:

```
Success: Updated 1/1 themes.
P2 updated successfully from version 1.5 to version 1.5.5
```

Nothing to fix there. But we could add `--format=json` and `--format=csv` to the mix.

**Comment by gilbitron** [comment]
Just to clarify @sakrow's comment, `--format=table` and `--format=summary` work as expected if you are not using `--dry-run`. However when using `--dry-run` the output is always a table.

**Comment by danielbachhuber** [comment]
> However when using --dry-run the output is always a table.

Oh. Thar be the bug. It'd be good to expand our tests to cover that case.

**Comment by gilbitron** [comment]
:+1:
