### ISSUE TITLE
wp media import default title

### ISSUE THREAD

**Issue by tannerm** [wp-cli/wp-cli#2416]
When using wp media import, can we update WP CLI to use use the filename of an image as the default title when none are provided just like WordPress does when uploading a file?

**Comment by danielbachhuber** [comment]
Seems reasonable to me

**Comment by tannerm** [comment]
Sweet! I just imported a bunch of images and their attachment pages are all broken presumably since they were side-loaded without a title. Not 100% on that, but that's my running theory.

I'm pretty slammed this week but happy to submit a patch next week.
