### ISSUE TITLE
After running "php wp-cli.phar --info" I get "PHP Fatal Error"

### ISSUE THREAD

**Issue by colmrs** [wp-cli/wp-cli#2417]
After running "php wp-cli.phar --info" I get:

PHP Fatal error:  Allowed memory size of 262144 bytes exhausted (tried to allocate 109 bytes) in Unknown on line 0

I have tried upping the PHP Memory size up to no avail.

**Comment by danielbachhuber** [comment]
> I have tried upping the PHP Memory size up to no avail.

Ok. This is ultimately the problem though, so you'll need to make more memory available to WP-CLI.

**Comment by colmrs** [comment]
Thank You!
You were correct, I simply didn't up it high enough, sorry about that. 

Have a great day!
