### ISSUE TITLE
Remote mysql executable

### ISSUE THREAD

**Issue by IAmJulianAcosta** [wp-cli/wp-cli#2418]
Hi, I'm trying to use wp-cli in a docker container with mysql in another container, but when I try to use `core config`, I get the error `mysql: not found`.

How can I run `core config` without using a local mysql installation?

**Comment by wojsmol** [comment]
@IAmJulianAcosta see http://wp-cli.org/commands/core/config/
> [--skip-check]
    If set, the database connection is not checked.

**Comment by danielbachhuber** [comment]
See also #1324
