### ISSUE TITLE
Removing Dashboard Cards

### ISSUE THREAD

**Issue by JakeHenshall** [wp-cli/wp-cli#2419]
Hi,

Is there anyway to disable this on the dashboard, as i always untick them.

Ive tried adjusting values in the database and have also used wp option update {values} to try and disable / untick them and nothing has seemed to have worked.

<img width="1244" alt="screen shot 2016-01-29 at 01 09 07" src="https://cloud.githubusercontent.com/assets/4720782/12664103/0d95f68e-c625-11e5-8a40-b51b5a8c9e0a.png">
<img width="535" alt="screen shot 2016-01-29 at 01 09 14" src="https://cloud.githubusercontent.com/assets/4720782/12664102/0d957fb0-c625-11e5-813f-22fa8f977077.png">

Thanks Jake.

**Comment by danielbachhuber** [comment]
> Ive tried adjusting values in the database and have also used wp option update {values} to try and disable / untick them and nothing has seemed to have worked.

They are user-specific options, so you'll need to figure out the correct values in user meta and update them for each user.

Alternatively, I might recommend looking at existing plugins, or writing your own, to handle the behavior you'd like. This isn't necessarily a use-case WP-CLI is meant to handle.
