### ISSUE TITLE
Adding Database Fields

### ISSUE THREAD

**Issue by JakeHenshall** [wp-cli/wp-cli#2420]
Hi,

I'm trying to pre activate a plugin called optimus.

When the plugin is activated it creates 2 fields in wp_options database. (Image).

![screen shot 2016-01-29 at 01 16 50](https://cloud.githubusercontent.com/assets/4720782/12664321/870adace-c626-11e5-97c0-86471e8ce784.jpg)

Is there a way in WP-CLI that i can already add these fields in with the populated data that i need to pre-active the plugin?

Thanks Jake.

**Comment by morbeo** [comment]
You should be able to do that with a MySQL query. I do not see how wp-cli will assist you here.

**Comment by danielbachhuber** [comment]
> Is there a way in WP-CLI that i can already add these fields in with the populated data that i need to pre-active the plugin?

You could make secondary calls like:

```
wp option update optimus_key <key>
wp option update optimus_purchase_time <time>
```
