### ISSUE TITLE
Seems that wp-cli doesn't parse activated theme code

### ISSUE THREAD

**Issue by lordgiotto** [wp-cli/wp-cli#2421]
Hello,
i'm trying to implement into my custom theme a wp-cli command:  i can define a custom command class extending WP_CLI_Command inside my theme code and wp-cli finds the new command and execute it.
But, unfortunaty, it seems like it runs it a complete new istance of WP where my theme is not loaded. For istance:
- No globals shared with my theme code
-  ~~No Class or Functions defined in my theme code can be called~~
- ~~Mine hooks seems to not be parsed (for exemple i've extended woocommerce WC_Order class, but wc-cli use normal WC_Order class instead of mine)~~

Is it the wanted behaviour? Is there something i'm missing?

Thank you!

**Comment by danielbachhuber** [comment]
How are the classes and functions for your theme being loaded? Can you share an example?

**Comment by lordgiotto** [comment]
My code is organized in this way:
functions.php in theme root folder require_once different php file from inc/ directory. Everyone of this file contains a single istance of a class that handle specific funcitonality (like a lot of plugins that use hooks in __construct, public methods for that hooks and private methods for class internal use) and maybe some global function for site wide functionalities.

I've just noticed that defined class and functions are working, sorry for that: the problem is that i usually use globals for conveniente inside the site wide functions ( gobal $istance; $istance->method() )... I'll rewire classes like singletons to avoid it.

I'm really sorry!! Howevet the issue is still real only for globals.
