### ISSUE TITLE
Can't have custom associative argument that starts with --no-

### ISSUE THREAD

**Issue by dkotter** [wp-cli/wp-cli#2423]
Title really says it all but was having an issue where a custom command kept giving me a Parameter Error, even though I was passing in the right param. After some debugging, found out that on associative arguments, if they start with `--no-`, that part is stripped out.

This happens in the Configurator.php file, line 88, which was added in here: https://github.com/wp-cli/wp-cli/commit/034f1e634cbf47f3d458bd5346fb260e4ef562af#diff-445ef2877063cddd8d2d17a2f58e44f7.

I guess I'm just trying to figure out the reasoning behind this, as the commit referenced above doesn't really help and there's no documentation I could find with any information on this. Thanks!

**Comment by danielbachhuber** [comment]
`--no-<flag>` intentionally negates the flag. This lets you override flags that may be set in `wp-cli.yml` or similar.

For instance, if `--debug` was set in `wp-cli.yml`, I could disable it with `--no-debug`.

Hope this helps clarify.
