### ISSUE TITLE
wp media import to consider hook/active plugins

### ISSUE THREAD

**Issue by gesen** [wp-cli/wp-cli#2425]
I have developed a plugin called [Clean Image Filenames](https://wordpress.org/plugins/clean-image-filenames/) that basically uses `sanitize_title()` to make the filenames of uploaded media files nicer. As an example, it changes _Världens bästa räksmörgås.JPG_ to _varldens-basta-raksmorgas.jpg_. 

The plugin runs on the `wp_handle_upload_prefilter` hook. However, when trying out the wp media import command, it seems that the command does not consider wp_handle_upload_prefilter or active plugins. 

(I'm fairly new to WP-CLI, so please excuse me if I've got anything wrong.)

**Comment by danielbachhuber** [comment]
WP-CLI calls `media_handle_sideload()` ([ref](https://github.com/wp-cli/wp-cli/blob/4d56828a1eec620af0b5e2dc143ae3555df29a72/php/commands/media.php#L169)), which in turn calls `wp_handle_sideload()`, which calls `_wp_handle_upload()` with the `wp_handle_sideload` action. 

If you register your plugin to also run on the `wp_handle_sideload_prefilter` filter, you'll be able to modify sideloaded images, including those WP-CLI imports.
