### ISSUE TITLE
Users with Empty (None) user roles

### ISSUE THREAD

**Issue by sacredwebsite** [wp-cli/wp-cli#2428]
When migrating user tables from multisite out into a single install, I want to be able to use wp-cli to list users with an empty role. currently omitting an entry in the field option lists all users, and the command does not accept none as listed in the dashboard, as there is no registered empty role called none, its simply not assigned to the user.

example:
 wp user list --role=''
returns all users, i wish to filter for empty roles to remove the users:
| 01 | user1         | user1       | example@domain.com         | 2015-04-04 02:37:33 | administrator |
| 02 | user2            | user2           | example@domain.com        | 2016-01-28 08:50:41 |               |

any ideas?

**Comment by danielbachhuber** [comment]
If users on the network aren't assigned to the site, then they won't have an empty role for the site.

You can list all users on the network with `wp user list --network`

**Comment by sacredwebsite** [comment]
@danielbachhuber this is after exporting the user tables and importing into a single install. the users that do not belong to the sub site are listed as none role in the dash, empty string in the role field in cli.

**Comment by danielbachhuber** [comment]
> the users that do not belong to the sub site are listed as none role in the dash, empty string in the role field in cli.

Oh, I see.

WP-CLI simply passes the args through to `WP_User_Query`, which doesn't support querying by `role=''`.

You could use `wp user list --format=csv` and then filter the list in Google Docs or similar.

**Comment by sacredwebsite** [comment]
Thank you for your suggestion. I guess I will output the list to a file and then remove any users with roles before feeding this list back to wp-cli for removal.
