### ISSUE TITLE
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(756)

### ISSUE THREAD

**Issue by jgraup** [wp-cli/wp-cli#2431]
I followed the instructions of downloading the file, allowing execution, then placing in .../bin/wp. `wp --info` works fine until I run the command in my WP directory. When I do, I get this error:

```
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(756) : eval()'d code on line 39
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(756) : eval()'d code on line 60
```

Any thoughts on why this might be happening? I'm running on an AWS EC2 instance.

```
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.22.0
```

**Comment by danielbachhuber** [comment]
You likely have `$_SERVER['HTTP_HOST']` in your wp-config.php, which isn't set in WP-CLI context. You'll want to make sure you have a conditional around it.

Related #730
Partially related #1631

**Comment by jgraup** [comment]
That was the problem exactly. I never had a way to check that error until now so thank-you for the quick response.

After adding some `empty` checks I don't have any errors, but I also don't have any output. Is there something else that can cause this to go silent? `--info` shows but nothing beyond that.

**Comment by danielbachhuber** [comment]
> After adding some empty checks I don't have any errors, but I also don't have any output.

Can you try with `--debug` and share the output? `--info` intentionally doesn't load WordPress.

**Comment by jgraup** [comment]
Thanks for the `--debug` tip! I'm trying to teach myself this as I go and I appreciate the fast response.

Looks like more assumptions of the server that are failing. I'll clean those up but looking at the output, do I need a global config or project config for the future? 

```bash
Debug: No readable global config found (0.057s)
Debug: No project config found (0.059s)
Debug: ABSPATH defined: /var/xyz/www/ (0.077s)
Debug: Begin WordPress load (0.077s)
Debug: wp-config.php path: /var/xyz/www/wp-config.php (0.077s)

PHP Notice:  Undefined index: SERVER_PORT in /var/xyz/www/mu-plugins/lame.php on line 143
```

**Comment by danielbachhuber** [comment]
> do I need a global config or project config for the future?

You shouldn't need either.

Script execution is being halted when WordPress is loaded. You might try `--skip-plugins --skip-themes` to see if it's a plugin or your theme that's prematurely calling `exit;`

**Comment by jgraup** [comment]
I removed the last error but silence again. I may have added too many direct access checks which could be causing it to `die`. I'll double check everything.

Is there a debug section on the wiki? Seems like this is basic stuff that could go into a section like that.

**Comment by jgraup** [comment]
Looks like I had created an mu-plugins/GeoIP Blocker which also blocked anyone without a `$_SERVER['HTTP_USER_AGENT']` defined. The random errors before might have been fine but the `die` was definitely causing the no show of data.

Now I can see a whole slew of new notices. Would this be considered a `wp-social-login` issue or more bad server setup?

Backtrace from warning 'session_start(): open(/my/php/session/sess_xyz123, O_RDWR) failed: Permission denied (13)' at /var/xyz/www/wp-content/plugins/wordpress-social-login/wp-social-login.php 63:
  /var/xyz/www/wp-content/plugins/wordpress-social-login/wp-social-login.php 63 calling session_start()
  phar:///usr/local/bin/wp/php/wp-settings-cli.php 286 calling include_once()
  phar:///usr/local/bin/wp/php/WP_CLI/Runner.php 770 calling require()
  phar:///usr/local/bin/wp/php/WP_CLI/Runner.php 721 calling load_wordpress()
  phar:///usr/local/bin/wp/php/wp-cli.php 21 calling start()
  phar:///usr/local/bin/wp/php/boot-phar.php 5 calling include()
  /usr/local/bin/wp 4 calling include()

Thank-you for your help. I've been using WP-CLI locally recently and I hope to make it part of the everyday workflow.

**Comment by danielbachhuber** [comment]
> Is there a debug section on the wiki? Seems like this is basic stuff that could go into a section like that.

https://github.com/wp-cli/wp-cli/wiki/FAQ

Feel free to edit :)

> Looks like I had created an mu-plugins/GeoIP Blocker which also blocked anyone without a `$_SERVER['HTTP_USER_AGENT']` defined.

That definitely makes sense as a culprit.

> Now I can see a whole slew of new notices. Would this be considered a wp-social-login issue or more bad server setup?

Probably mostly application layer (e.g. plugins and whatever else you have running in your WordPress install).

**Comment by jgraup** [comment]
Turns out, like many AWS EC2 issues, this is a permissions problem; `root`, `apache` and `ec2-user` walk into a bar... but only one can drink at a time.

The solution:
`sudo chown -R apache:group /my/php/session`

Ok. No more errors. WP-CLI is working perfectly. My life is complete.

**Comment by enoch85** [comment]
@danielbachhuber Sorry for bumping an old issue but I have this in my config:
```
define('FORCE_SSL_ADMIN', true);
// in some setups HTTP_X_FORWARDED_PROTO might contain 
// a comma-separated list e.g. http,https
// so check for https existence
if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false)
       $_SERVER['HTTPS']='on';
``` 

How should it look like instead?

**Comment by danielbachhuber** [comment]
@enoch85 Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by stefanpl** [comment]
Just found this, in case anyone still wonders what the solution is: you basically have to sourround any mentions of `$_SERVER` variables in your wp-config.php with an `isset(…)` check. Simplified:
```php
if (isset($_SERVER['HTTP_HOST'])) {
  $whatever = $_SERVER['HTTP_HOST'];
} else {
  $whatever = false;
}
```

**Comment by jasonkiptoo** [comment]
Undefined index: SERVER_PORT in C:\Users\kipto\Documents\GitHub\fm\SchoolErp\application\config\config.php on line 3 
/////having the same problem
