### ISSUE TITLE
Properly support plurality in output messages

### ISSUE THREAD

**Issue by fjarrett** [wp-cli/wp-cli#2433]
When the number of objects affected by a command is known, it seems that the message output should be made singular/plural automatically.

```sh
Success: Executed a total of 1 cron event.
Success: Executed a total of 2 cron events.
```

Instead of:

```sh
Success: Executed a total of 1 cron event(s).
Success: Executed a total of 2 cron event(s).
```

Is it easier to write tests using the latter?

**Comment by danielbachhuber** [comment]
> it seems that the message output should be made singular/plural automatically.

English doesn't make this easy to do "automatically". Instead, you have to provide singular and plural versions of each message.

> Is it easier to write tests using the latter?

It's less code to maintain.

**Comment by fjarrett** [comment]
OK yeah by automatically I meant to the end user :smile:
