### ISSUE TITLE
Print execution time when running multiple cron event hooks in debug mode

### ISSUE THREAD

**Issue by fjarrett** [wp-cli/wp-cli#2434]
When running multiple cron event hooks in the same command (#2323) it can be important to know how long each event took to execute, not just the entire operation via `time`.

It would be great if the internal timer was part of the output for each event when in debug mode, then the execution time for each event could be deciphered.

**EXAMPLE**

```sh
$ wp cron event run --all --debug
Debug: No readable global config found (0.042s)
Debug: No project config found (0.045s)
Debug: ABSPATH defined: /srv/www/wordpress-trunk/ (0.11s)
Debug: Begin WordPress load (0.112s)
Debug: wp-config.php path: /srv/www/wordpress-trunk/wp-config.php (0.113s)
Debug: Loaded WordPress (0.838s)
Debug: Running command: cron event run (0.839s)
Executed the cron event 'foo'. (1.525s)
Executed the cron event 'bar'. (3.78s)
Executed the cron event 'baz'. (4.374s)
Success: Executed a total of 3 cron event(s).
```

**Comment by danielbachhuber** [comment]
> It would be great if the internal timer was part of the output for each event when in debug mode, then the execution time for each event could be deciphered.

I don't know that hooking into debug mode is the best approach. We could instead just include the total execution time, though.

**Comment by fjarrett** [comment]
> I don't know that hooking into debug mode is the best approach.

:+1: 

> We could instead just include the total execution time, though.

Do you mean the total execution of all events ran, or for each event?

**Comment by danielbachhuber** [comment]
> Do you mean the total execution of all events ran, or for each event?

Each event
