### ISSUE TITLE
core download --locale=ru_RU

### ISSUE THREAD

**Issue by sopov** [wp-cli/wp-cli#2435]
If language not found for current core we have error
Error: The requested locale (ru_RU) was not found.

reason current en core 4.4.2, for ru: 4.4.1

**Comment by danielbachhuber** [comment]
Right, it fails the build too:

![image](https://cloud.githubusercontent.com/assets/36432/12763799/475d5400-c9ab-11e5-8964-92aa397d5b65.png)

You'll need to wait a bit longer for WordPress.org to create a ru_RU release.

**Comment by wojsmol** [comment]
To avoid such errors in my script I use
```
wp core download
wp core install (...)
wp core language install pl_PL --activate
```
