### ISSUE TITLE
Generate password reset emails

### ISSUE THREAD

**Issue by shankiesan** [wp-cli/wp-cli#2436]
Hi @danielbachhuber – nice to see you at A Day of Rest. Great talk!

We're working on a WP CLI-based script and the ability to generate password reset emails would be fabulous. I know that we can use the `wp_update_user` wrapper to set a password, but in our use-case, the ability to send a password reset email would be more useful.

What do you think?

**Comment by danielbachhuber** [comment]
Thanks :)

I think what you describe could be useful too. Today, I landed `wp package` (https://github.com/wp-cli/wp-cli/issues/1564#issuecomment-179426634), a command to browse and install [community commands](https://github.com/wp-cli/wp-cli/wiki/List-of-community-commands). Want to publish your command and add it to our [growing directory](http://wp-cli.org/package-index/)?

**Comment by shankiesan** [comment]
Ah, I wasn't aware of community commands!

Sure, @bones5 and I could work on this. It would be really useful for us.

**Comment by danielbachhuber** [comment]
> Sure, @bones5 and I could work on this. It would be really useful for us.

Cool :+1: 

As you run into questions, please do identify them so I can take it as an opportunity to improve the documentation.
