### ISSUE TITLE
`wp core update` to latest patch version?

### ISSUE THREAD

**Issue by tommarshall** [wp-cli/wp-cli#2441]
_Not sure if this is the right place for this sort of question? Happy to move to stackexchange (or elsewhere) if directed._

---

Is it possible to instruct `wp core update` to install the latest patch version for a given `major`.`minor`? i.e. Can I tell `wp core update` to install the latest `4.4` version?

I've tried:

```
wp core update --version=4.4.x --locale=en_GB
```

and:

```
wp core update --version=4.4 --locale=en_GB
```

on a `4.4.1` site, and both report `Success: WordPress is up to date.`, when really I want them to upgrade to WordPress to the latest patch version (currently `4.4.2`) version that is available.

[The docs](http://wp-cli.org/commands/core/update/) list `--minor` switch, which I've also tried, but that is giving an error:

```
Error: Parameter errors:
 unknown --minor parameter
```

Is this something that is already possible with the right combination of arguments, or is it a feature request?

**Use case:**

I have an Ansible playbook that uses WP CLI to install and update multiple sites across a cluster of servers. The version of WordPress to install is defined in the inventory config for each site. Currently I'm having to specify down to the patch version, e.g. `4.4.1`, which means the ansible config is fighting with WordPress automated security updates.

Specifying `4.4` would stop the Ansible regressing sites that have been upgraded by WordPress security updates, but it won't upgrade sites on `4.4.1` to `4.4.2` if the security updates are disabled or unavailable.

I should add the `--version=latest` isn't desirable in this case as I don't want to jump a minor or major version, e.g. `4.4` to `4.5`, or `4` to `5` without specifying so.

```
$ wp --info
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.14
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.21.1
```

**Comment by danielbachhuber** [comment]
`--minor` was introduced in v0.22.0 (#2256). You'll need to update WP-CLI to make use of it.

**Comment by danielbachhuber** [comment]
Oh, and you can use `wp cli update` to update.

**Comment by tommarshall** [comment]
Thanks @danielbachhuber.

To clarify, what exactly should the command be to pin the major and minor version but install the latest patch version?

```
wp core update --minor --version=4.4
```
?

**Comment by danielbachhuber** [comment]
Because WordPress doesn't have patch versions, only major and minor, `wp core update --minor` will update you to the latest minor version of your current major version.

For instance, if you're on version 4.4, `wp core update --minor` will update you to 4.4.2. If you're on version 4.3,  `wp core update --minor` will update you to 4.3.3

**Comment by tommarshall** [comment]
Aah. I was describing the versions assuming semver's MAJOR.MINOR.PATCH, but I see that's not how they're describing things. That clarifies the issue. Thanks for the prompt response, and for adding `--minor` :+1:.
