### ISSUE TITLE
Verify whether cron events successfully executed

### ISSUE THREAD

**Issue by fjarrett** [wp-cli/wp-cli#2445]
It appears that the [run_event() method](https://github.com/wp-cli/wp-cli/blob/29b3aa05fd079e14c4894c8e4a20b8a553d64aa5/php/commands/cron.php#L214) in the `Cron_Event_Command` class always returns `true`, which makes the [warning line](https://github.com/wp-cli/wp-cli/blob/29b3aa05fd079e14c4894c8e4a20b8a553d64aa5/php/commands/cron.php#L184) in the `run()` method obsolete.

One idea for improving this could be to catch any Exceptions that might be thrown during an event hook and return the error message, or at the very least use `did_action()` to verify that the hook ran.

**EXAMPLE**

```php
try {
	do_action_ref_array( $event->hook, $event->args );
}  catch ( Exception $e ) {
	return $e->getMessage(); // or return false
}

return ( did_action( $event->hook ) > 0 );
```

**Comment by danielbachhuber** [comment]
> which makes the warning line in the run() method obsolete.

Good call, I'll clean that up.

> One idea for improving this could be to catch any Exceptions that might be thrown during an event hook and return the error message,

If you start throwing Exceptions in your cron callbacks, you'll break your WordPress :)

Given there isn't an existing paradigm of reporting errors with WP Cron, I think your best bet is to include some WP-CLI-specific reporting in your callbacks:

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
   WP_CLI::log( 'The callback has made it this far without breaking' );
}
```

**Comment by fjarrett** [comment]
> Good call, I'll clean that up.

Thanks.

> If you start throwing Exceptions in your cron callbacks, you'll break your WordPress :)

Well that makes a ton of sense... :)
