### ISSUE TITLE
Bad theme breaks wp-cli ?

### ISSUE THREAD

**Issue by dirad** [wp-cli/wp-cli#2448]
Hi there,

While moving a site between servers I'm in the process of learning a lot about the infrastructure.
I encountered a bug [?] while changing from apache to nginx .
For some reason this theme's functions.php file throws a syntax error `` unexpected '}' in /.../functions.php on line 590 ``

Now while this is strange in itself [apache doesnt report this but ngnix break absolutely], i am trying to change theme with ``wp theme activate TS`` i get the same error in the shell .. actually twice, first prepended with "PHP"

I can't login or bring up *any* page. 
My only solution is:
* Rename the theme folder > now i can access wp-admin , but the site gives me a blank page
* wp theme activate _different_theme_ > alles good.

should wp break this much just because of a poor functions.php file ?

thanks thank ~!!

**Comment by danielbachhuber** [comment]
> should wp break this much just because of a poor functions.php file ?

I'm not sure how this is a question, unfortunately. With PHP, if you have a syntax error, you'll get a fatal. There's not much avoiding that.

With WP-CLI, you can use `wp --skip-themes` to be able to execute commands without loading the theme, which should be helpful for recovering from the fataled state.

**Comment by dirad** [comment]
@danielbachhuber i did mean the wp-cli tool, and not the entity of wordpress.. 
Your switch help me plenty though. thanks again.
