### ISSUE TITLE
Do not exit from wp shell if there is some command typed while pressing ctrl + c

### ISSUE THREAD

**Issue by adisos** [wp-cli/wp-cli#2451]
Now:
1) wp shell
2) type something and press `ctrl`+ `c`
It exits, but instead it should clear what you typed before.

**Comment by danielbachhuber** [comment]
> It exits, but instead it should clear what you typed before.

Hm. I'm not so sure about this.

PHP's interactive shell also exits with `ctrl` + `c`. However, Python's will clear input.

Do you have other examples we can refer to?

**Comment by adisos** [comment]
Ruby's `irb` or `pry` :) But if PHP's shell also exits, so I think it's ok.
