### ISSUE TITLE
Table format distorting displayed values containing special characters 

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#2455]
Items as JSON:
```
[{"key":"AUTH_KEY","value":"$5)onc8eh`)v\/*;zG<9l`~oQ xB{mn;#Q| {CC^%6*KgKI|mD`&uZP(N|N.,ZA4#"},{"key":"SECURE_AUTH_KEY","value":"Nn&tSno-($G(cw_$R_*rYZDysUu \/aklE_nE~e>C-zn}nPnOz=>F03m-@w^;P~Bq"},{"key":"LOGGED_IN_KEY","value":"@CUu5D)^.cMVPdIiA|BzMpbWqF|FzgG1f~<[|EqQT]X9p7,p7rLaN^0}2?Y,91&o"},{"key":"NONCE_KEY","value":"jGw,h>E+RV<*5D|8NCj>J:< 59:+%ZtiB8)6hvW]d`Rj2Bd5H<0lNZ7L>d`X({+="},{"key":"AUTH_SALT","value":"K)YDim@{^n;<^bh{QCe<h8b7b@]>c_SqN?Y6<f4&:mqNb|RuvQ*{OE\/dY1+k-:1u"},{"key":"SECURE_AUTH_SALT","value":",1HEiZK96;m4}LLnh7j1b1%In#-$((5fN_:2P@Z+NR[nTC%E.*xSl aruyZ-8Fw("},{"key":"LOGGED_IN_SALT","value":"L02Iy0*XLxiipWG-{.}w)yl?+$},uxFKsaXoe&N+:4\/yK%,}fwf 6{\/V+4FYmQ:$"},{"key":"NONCE_SALT","value":"V~<I7a|^O!QFd}-F,yFTWU Ue@CfQLG]Z~T1,|Zj5@:YMlN+dLmZ:4e9<(B`*V=|"}]
```

As table:
![screenshot](http://d.pr/i/1eX7n+)

As you can see, the first value in the table contains some special characters which are colorizing the output.  It's not only color which is an issue though, the value for `NONCE_KEY` is also distorted as can be seen with the length of the value not matching, where the "wall" of the table on the right side is out of place. 

However, if I output only the single value (`AUTH_KEY`), it prints correctly.
```
$5)onc8eh`)v/*;zG<9l`~oQ xB{mn;#Q| {CC^%6*KgKI|mD`&uZP(N|N.,ZA4#
```
In this case, the `%6` is being interpreted as a color code.  Using the `--no-color` flag also has no effect.

Is it possible to escape these special characters in a table format?  And if so, does it belong in WP-CLI or  in my command?

**Comment by danielbachhuber** [comment]
> Is it possible to escape these special characters in a table format? And if so, does it belong in WP-CLI or in my command?

I'm going to disable colorization for `format=table`, as I see this bug happening more often than someone wanting table output to be colorized. For those who want table output colorized, they can run their strings through `::colorize()` before passing them to `\WP_CLI\Formatter()`

**Comment by aaemnnosttv** [comment]
That sounds like a good change to me.  :+1:
