### ISSUE TITLE
Enhance the Output API with a progress bar

### ISSUE THREAD

**Issue by gnotaras** [wp-cli/wp-cli#2456]
Hello, any chance of enhancing the [Output API](https://github.com/wp-cli/wp-cli/wiki/API#output) with the addition of a progress bar? It doesn't have to be sophisticated. A simple implementation ([example](http://stackoverflow.com/a/5265440)) would be nice.

**Comment by danielbachhuber** [comment]
> Hello, any chance of enhancing the Output API with the addition of a progress bar?

Sure! I'm working on documentation right now (https://github.com/wp-cli/wp-cli/issues/1045#issuecomment-180618311), so I'll get to it when I have a moment.

**Comment by gnotaras** [comment]
That's so great, Daniel!

**Comment by danielbachhuber** [comment]
@gnotaras here you go http://wp-cli.org/docs/internal-api/wp-cli-utils-make-progress-bar/

**Comment by gnotaras** [comment]
@danielbachhuber Marvelous work, Daniel! Thank you very much!
