### ISSUE TITLE
wp rewrite structure and archives 

### ISSUE THREAD

**Issue by kevinr0** [wp-cli/wp-cli#2462]
Hello, i've noticed some strange issue.
When i am changing post url structure with **wp rewrite structure "/sometext/%postname%** or **wp rewrite structure "/sometext%postname%"** i have archives and author url structure also changed.
It would be something like /sometext/2015/02/09/ or /sometext20150209 same with author url.
Perhaps this is not a bug but i didn't find any info about this in docs.

Thank you.

**Comment by danielbachhuber** [comment]
Given WP-CLI is a wrapper around core functionality, this is most likely this bug in WordPress core https://core.trac.wordpress.org/ticket/29669
