### ISSUE TITLE
Presets plugin

### ISSUE THREAD

**Issue by thomh25** [wp-cli/wp-cli#2463]
Hi,

I would like to know if it's possible to import serialized datas into wp_options (or another table) to import saved settings from another site to a new one ? For example : let's say I would like to make a new site with User Role Editor in it, would it be possible for me to get saved settings from an old site to my new one ? 

I already tried to use a saved json like this : 
`wp option update option_name --format=json < saved_options.json`
But it doesn't work.

**Comment by danielbachhuber** [comment]
> But it doesn't work.

Can you be more descriptive, please?

**Comment by thomh25** [comment]
Thank you for trying to help me !

Nothing happens. I have a "success" line telling me that the option has been updated but my options in back end are still "empty" (without my settings).

**Comment by szepeviktor** [comment]
Try validating your JSON http://jsonlint.com/
then issue `wp option get option_name --format=json` and check the output.

**Comment by danielbachhuber** [comment]
> I have a "success" line telling me that the option has been updated but my options in back end are still "empty" (without my settings).

Can you inspect the database to see if the option is set, and what value it's set to?

Similarly, can you change your settings through the plugin UI, and inspect what value the option is set to in the database?

Lastly, when you perform both of these steps, can you share your findings here? Screenshots, snippets of output, etc. are very helpful.
