### ISSUE TITLE
Document branch naming convention and review process in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mbovel** [wp-cli/wp-cli#2465]
I would find useful to add two things in CONTRIBUTING.md:

- how to name branche,
- what to do once the pull request is accepted.

Maybe something like this:

> 0. [Search existing issues](https://github.com/wp-cli/wp-cli/issues); if you can't find anything related to what you want to work on, [open a new issue](https://github.com/wp-cli/wp-cli/wiki/Creating-Helpful-Bug-Reports) so that you can get some initial feedback.
> 1. [Fork](https://github.com/wp-cli/wp-cli/fork) the repository.
> 2. Create a branch for each issue you'd like to address. Choose a simple name describing your changes in the form `my-update`, optionally precessed with an issue number (example: `1234-my-update`).
> 3. Commit your change.
> 4. Push the code changes from your local clone to your fork.
> 5. Open a pull request.
> 6. Your code is going to be reviewed by a wp-cli team member.
> 7. If your changes are accepted, your branch will be merged with the main repository. You can then [remove your fork from your github account](http://programmers.stackexchange.com/a/209551).

Would that make the guide too long?

**Comment by danielbachhuber** [comment]
> Would that make the guide too long?

Nah — pull requests welcome :)

While we don't _require_ specific branch names, I typically follow `<number>-<feature-slug>`, and find it a helpful pattern when working with tons of branches.
