### ISSUE TITLE
Error on download link from WP version 4.0.1

### ISSUE THREAD

**Issue by sakrow** [wp-cli/wp-cli#2468]
Hi, when i try to upgrade core from 4.0 to 4.0.1 with:

`wp-cli core update --minor --path=/var/www/vhosts/domain.com/httpdocs --allow-root --debug`

The wp-cli is trying to download a wordpres version from:

`https://es.wordpress.org/wordpress-4.0.10-es_ES.zip`

When the link is:

`https://es.wordpress.org/wordpress-4.0.1-es_ES.zip`

This create a error in the update, because the "zip" is "corrupted":

```
Debug: No readable global config found (0.007s)
Debug: No project config found (0.008s)
Debug: ABSPATH defined: /var/www/vhosts/domain.com/httpdocs/ (0.022s)
Debug: Begin WordPress load (0.022s)
Debug: wp-config.php path: /var/www/vhosts/domain.com/httpdocs/wp-config.php (0.022s)
PHP Notice:  Undefined index: enable_css in /var/www/vhosts/domain.com/httpdocs/content/plugins/widgets-on-pages/widgets_on_pages.php on line 289
Notice: Undefined index: enable_css in /var/www/vhosts/domain.com/httpdocs/content/plugins/widgets-on-pages/widgets_on_pages.php on line 289
PHP Notice:  Undefined variable: text_domain in /var/www/vhosts/domain.com/httpdocs/content/plugins/wp-category-posts-list/wp-category-post-list.php on line 56
Notice: Undefined variable: text_domain in /var/www/vhosts/domain.com/httpdocs/content/plugins/wp-category-posts-list/wp-category-post-list.php on line 56
Debug: Loaded WordPress (1.299s)
Debug: Running command: core update (1.299s)
Updating to version 4.0.10 (es_ES)...
Error: No se ha podido descomprimir el paquete. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
Descargando paquete de instalación desde https://es.wordpress.org/wordpress-4.0.10-es_ES.zip...
Descomprimiendo actualización...
```
What is generating that URL?
Is a exception(only in this case), or can be repeat in other version of wordpress?

EDIT: This only occurs in this version, because in other updates the download link is correct and the "zip" can be extracted correctly

**Comment by danielbachhuber** [comment]
> This create a error in the update, because the "zip" is "corrupted":

I can reproduce:

```
salty-wordpress ➜  es-download  wp core download --version=4.0 --locale=es_ES
Downloading WordPress 4.0 (es_ES)...
Success: WordPress downloaded.
salty-wordpress ➜  es-download  wp core update --minor
Updating to version 4.0.10 (es_ES)...
Descargando paquete de instalación desde https://es.wordpress.org/wordpress-4.0.10-es_ES.zip...
Error: Descarga fallida.
salty-wordpress ➜  es-download  http HEAD https://es.wordpress.org/wordpress-4.0.10-es_ES.zip
HTTP/1.1 404 Not Found
```

> What do generating that URL? 

WordPress.org provides us the download offer. The ZIP _should_ exist, so it's something WordPress.org will need to fix. I've [filed an issue for it](https://meta.trac.wordpress.org/ticket/1567)

**Comment by danielbachhuber** [comment]
Actually, it's our bug. We're producing the download link, so we need to verify it's correct.

**Comment by danielbachhuber** [comment]
After #2469 lands, `wp core update --minor` for WP 4.0.9 es_ES will use https://downloads.wordpress.org/release/wordpress-4.0.10-partial-0.zip to perform the update, given there's no 4.0.10 es_ES build.
