### ISSUE TITLE
cd $(wp plugin path) not working

### ISSUE THREAD

**Issue by jschank** [wp-cli/wp-cli#2473]
The documentation for plugin path command uses this example as a way to change to the plugin path directory.
When I try this in centos6, I get an error...
`
-bash: cd:/var/www/html/apps/cc-dev/wordpress/wp-content/plugins: No such file or directory
`
Even though this directory does, in fact, exist. 
I tried googling, but my google fu isn't up to the task.

Can someone offer some advice?

**Comment by danielbachhuber** [comment]
`cd $(wp plugin path)` seems to work for me on Ubuntu:

```
salty-wordpress ➜  wordpress-develop.dev  cd $(wp plugin path)
salty-wordpress ➜  plugins  wp plugin path
/srv/www/wordpress-develop.dev/src/wp-content/plugins
```

I'm not sure why you're ending up with `cd:/var/` when it should be `cd /var/`. How are you calling the command in centos6? Do other WP-CLI commands work?

**Comment by jschank** [comment]
I really appreciate your reply. It is pretty frustrating.

I am issuing the command, via cut and paste, in my project directory. Which is where my wp-cli.yml is.

Ive tried both $() syntax, and backticks, which i think will do the same thing, and i get the same results.

Ive tried just $ wp plugin path, and it does report the entire, correct, existing path.

It seems like cd is the problem, like it strips the space, or adds the colon.

**Comment by danielbachhuber** [comment]
Can you try quoting the command? `cd "$(wp plugin path)"`

**Comment by jschank** [comment]
Same results

[vagrant@localhost cc-dev]$ cd "$(wp plugin path)"
-bash: cd:/var/www/html/apps/cc-dev/wordpress/wp-content/plugins: No such file or directory

If it helps

[vagrant@localhost cc-dev]$ wp --info
PHP binary:	/usr/bin/php
PHP version:	5.5.32
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:	/var/www/html/apps/cc-dev/wp-cli.yml
WP-CLI version:	0.22.0

**Comment by jschank** [comment]
also, other wp-cli commands do work fine.
In fact the entire site was set up by using wp-cli

**Comment by jschank** [comment]
Hmm,

This works: cd $(echo /var/www)

but these do not:

[vagrant@localhost ~]$ cd /var/www/html/apps/cc-dev/
[vagrant@localhost cc-dev]$ cd $(echo $(wp plugin path))
-bash: cd:/var/www/html/apps/cc-dev/wordpress/wp-content/plugins: No such file or directory
[vagrant@localhost cc-dev]$ cd $(echo "$(wp plugin path)")
-bash: cd:/var/www/html/apps/cc-dev/wordpress/wp-content/plugins: No such file or directory

Could the wp-cli, plugin path command’s output be confusing cd?

**Comment by jschank** [comment]
Daniel now this is interesting…

[vagrant@localhost cc-dev]$ echo $foo
/var/www/html/apps/cc-dev/wordpress/wp-content/plugins

[vagrant@localhost cc-dev]$ echo "+$foo+"
/var/www/html/apps/cc-dev/wordpress/wp-content/plugins+

[vagrant@localhost cc-dev]$ echo "$foo"
/var/www/html/apps/cc-dev/wordpress/wp-content/plugins

[vagrant@localhost cc-dev]$ bar="fred"
[vagrant@localhost cc-dev]$ echo "+$bar+"
+fred+

notice that there is no leading + when I echo $foo bracketed by + signs
unless that coincidentally has something to do with the leading / ??

**Comment by danielbachhuber** [comment]
> Could the wp-cli, plugin path command’s output be confusing cd?

It's more likely a bash configuration issue.

**Comment by jschank** [comment]
OK
I suspect the problem is the trailing \n on the emitted line
in 
	/**
	 * Display a message in the CLI and end with a newline.
	 * Ignores --quiet flag. To respect, use WP_CLI::log()
	 *
	 * @access public
	 *
	 * @param string $message
	 */
	public static function line( $message = '' ) {
		echo $message . "\n";
	}

It may well be a bash config issue, but I don’t know which setting.
Digging further :)


[vagrant@localhost cc-dev]$ foo="/var/www/html/\n"
[vagrant@localhost cc-dev]$ echo foo
foo
[vagrant@localhost cc-dev]$ cd $foo
-bash: cd: /var/www/html/\n: No such file or directory
[vagrant@localhost cc-dev]$ foo="/var/www/html"
[vagrant@localhost cc-dev]$ cd $foo
[vagrant@localhost html]$

**Comment by jschank** [comment]
no, I think trailing newlines are stripped, and they definitely are if I use echo.

**Comment by wojsmol** [comment]
@jschank Show results of
`echo $IFS`

**Comment by jschank** [comment]
[vagrant@localhost ~]$ echo $IFS


Looks like it is a blank line

**Comment by jschank** [comment]
[vagrant@localhost ~]$ echo "+$IFS+"
+
+

**Comment by szepeviktor** [comment]
> -bash: cd:/var/www/html/apps/cc-dev/wordpress/wp-content/plugins: No such file or directory

My bash output one more space after `cd:`:
`-bash: cd: /wppluginpath: No such file or directory`

I hope this help debugging.

**Comment by szepeviktor** [comment]
And maybe `wp plugin path|hexdump -C`

**Comment by jschank** [comment]
I will follow up on these suggestions. I appreciate them. But I wanted to mention...
I'm using vagrant, so centos is running in a vm. I don't expect this to make much difference. BUT I can say that I had a vagrant vm from a couple weeks ago and $ cd $(wp plugin path --dir) 
worked fine in the older vm, but after I destroyed it and recreated it, I got the results I mention here.

So... Something changed in the last week or two, to break this. I don't know if it is wp-cli, wordpress, or the vagrant guest tools.
I can say that my vagrant set up uses the latest available wordpress and wp-cli. 

that is:
wordpress 4.4.2
and
[vagrant@localhost cc-dev]$ wp --info
PHP binary:	/usr/bin/php
PHP version:	5.5.32
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:	/var/www/html/apps/cc-dev/wp-cli.yml
WP-CLI version:	0.22.0

**Comment by szepeviktor** [comment]
I suspect some invisible control characters.

**Comment by danielbachhuber** [comment]
> So... Something changed in the last week or two, to break this. I don't know if it is wp-cli, wordpress, or the vagrant guest tools.

Given the problem doesn't reproduce in other environments, it's most likely specific to your environment.

**Comment by szepeviktor** [comment]
`cd "$(wp plugin path)" | hexdump -C`

**Comment by jschank** [comment]
@szepeviktor
[vagrant@localhost cc-dev]$ wp plugin path|hexdump -C
00000000  08 2f 76 61 72 2f 77 77  77 2f 68 74 6d 6c 2f 61  |./var/www/html/a|
00000010  70 70 73 2f 63 63 2d 64  65 76 2f 77 6f 72 64 70  |pps/cc-dev/wordp|
00000020  72 65 73 73 2f 77 70 2d  63 6f 6e 74 65 6e 74 2f  |ress/wp-content/|
00000030  70 6c 75 67 69 6e 73 0a                           |plugins.|
00000038

**Comment by jschank** [comment]
@danielbachuber - agreed. I'm trying to figure out what it might be.

**Comment by jschank** [comment]
OK, so I deactivated all of my plugins and now the cd command works. So this is an incompatibility with one of the plugins (likely the one my company develops)

I can narrow it down from here.

I do appreciate the suggestions from the community here.
Especially the one from @szepeviktor, because I was looking for a way to do what was suggested.

Thank you all.
I'll close the thread

**Comment by jschank** [comment]
FYI, when the command works the hexdump looks like this...
[vagrant@localhost plugins]$ wp plugin path|hexdump -C
00000000  2f 76 61 72 2f 77 77 77  2f 68 74 6d 6c 2f 61 70  |/var/www/html/ap|
00000010  70 73 2f 63 63 2d 64 65  76 2f 77 6f 72 64 70 72  |ps/cc-dev/wordpr|
00000020  65 73 73 2f 77 70 2d 63  6f 6e 74 65 6e 74 2f 70  |ess/wp-content/p|
00000030  6c 75 67 69 6e 73 0a                              |lugins.|
00000037

The difference is the leading 0x08, when my plugins are active.

**Comment by szepeviktor** [comment]
>  00000000 08 2f 76 61 72 2f 77 77 77 2f 68 74 6d 6c 2f 61 |./var/www/html/a|

@jschank ONe of your plugins emits a DEL (ASCII 0x08) char

**Comment by jschank** [comment]
@szepviktor, yep, I agree. Now I have to figure out how to grep/ack/search for that. But that's why the internet was invented... So I can Google stuff.

:)

**Comment by jschank** [comment]
Totally found it and fixed the problem.
Used ack to find the culprit
[vagrant@localhost ~]$ ack '[\b]'
