### ISSUE TITLE
Suppress errors if using `wp db drop` and db doesn't exist

### ISSUE THREAD

**Issue by gilbitron** [wp-cli/wp-cli#2475]
It would be helpful to be able to do something like:

```
wp db drop --if-exists
```

so that no errors are shown if you attempt to drop a DB that doesn't exist.

**Comment by danielbachhuber** [comment]
> Suppress errors if using `wp db drop` and db doesn't exist

Can you share your use case in greater detail? Why should we offer an option to disable errors in this context, and not in others?

**Comment by gilbitron** [comment]
So often I do something like:

```
wp db drop
wp db create
```

in a script to make sure there is a fresh database before running the install. However the first time the script is run `wp db drop` spits out an error because the database hasn't been created yet.

**Comment by danielbachhuber** [comment]
Why not just skip the error in the script?

**Comment by gilbitron** [comment]
Yeh not a big deal. Was just thinking this would be neater.

**Comment by danielbachhuber** [comment]
Decisions, not options :) If there's a reasonable existing way of doing something, we should do that instead.

**Comment by gilbitron** [comment]
:+1:
