### ISSUE TITLE
Update core failing silently, even with `--debug`

### ISSUE THREAD

**Issue by tommarshall** [wp-cli/wp-cli#2476]
I'm having trouble with `wp core update`. It appears to be failing silently, although it is exiting with a `255` code.

```sh
$ sudo -u www-data -H wp core version
4.3.3

$ sudo -u www-data -H wp --debug core update --version=4.4.2 --locale=en_GB
Debug: No readable global config found (0.015s)
Debug: No project config found (0.017s)
Debug: ABSPATH defined: /var/www/htdocs/ (0.058s)
Debug: Begin WordPress load (0.058s)
Debug: wp-config.php path: /var/www/htdocs/wp-config.php (0.058s)

$ echo $?
255

$ sudo -u www-data -H wp core version
4.3.3
```

```sh
$ sudo -u www-data -H wp cli info
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.14
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.22.0

$ sudo -u www-data -H which wp
/usr/local/bin/wp

$ ls -l /usr/local/bin/wp
-rwxr-xr-x 1 root root 1469311 Feb  3 15:53 /usr/local/bin/wp
```

WP CLI isn't newly installed on this host, and did work in the past, however it has been recently updated.

I've had a quick crawl through the open issues and can't see this raised anywhere, so figure it's likely to be something environmental, but I can't work out where the issue is.

Any assistance would be greatly appreciated. Let me know if there's any other information you need.

Thanks,
Tom

**Comment by danielbachhuber** [comment]
> I've had a quick crawl through the open issues and can't see this raised anywhere, so figure it's likely to be something environmental, but I can't work out where the issue is.

Can you try running `wp core update` with the `--skip-plugins` and `--skip-themes` flags?

Also, do other WP-CLI commands that make use of WordPress work as expected? Can you try `wp option get home` and share the output?

**Comment by tommarshall** [comment]
Thanks for the prompt response.

> Can you try running wp core update with the --skip-plugins and --skip-themes flags?

That worked.

```sh
$ sudo -u www-data -H wp --debug core update --version=4.4.2 --locale=en_GB --skip-plugins --skip-themes
Debug: No readable global config found (0.016s)
Debug: No project config found (0.017s)
Debug: ABSPATH defined: /var/www/htdocs/ (0.062s)
Debug: Begin WordPress load (0.062s)
Debug: wp-config.php path: /var/www/htdocs/wp-config.php (0.062s)
Debug: Loaded WordPress (0.358s)
Debug: Running command: core update (0.358s)
Updating to version 4.4.2 (en_GB)...
Downloading update from https://en.wordpress.org/wordpress-4.4.2-en_GB.zip...
Unpacking the update...
Success: WordPress updated successfully.
```

> Also, do other WP-CLI commands that make use of WordPress work as expected? Can you try wp option get home and share the output?

Gives a similar looking failure.

```sh
$ sudo -u www-data -H wp --debug option get home
Debug: No readable global config found (0.015s)
Debug: No project config found (0.017s)
Debug: ABSPATH defined: /var/www/htdocs/ (0.037s)
Debug: Begin WordPress load (0.037s)
Debug: wp-config.php path: /var/www/htdocs/wp-config.php (0.037s)

$ echo $?
255
```

**Comment by danielbachhuber** [comment]
Ok. One of your plugins, or your active theme, is halting WP-CLI execution in some way. I'd recommend doing a search for `WP_CLI` within your codebase to see what code is conditionally included / executed.

**Comment by tommarshall** [comment]
Ok thanks.

The only reference to `WP_CLI` that I could find was in `w3-total-cache`. I've deactivated the plugin and deleted the files in `wp-content/plugins`, however I'm still seeing the same issue.

I can't find any remaining reference to `WP_CLI` in the whole of the `htdocs`. Is there anything else that I should be looking for?

```sh
$ sudo grep -ri 'WP_CLI' *

$ echo $?
1

$ sudo -u www-data -H wp --debug option get home
Debug: No readable global config found (0.016s)
Debug: No project config found (0.017s)
Debug: ABSPATH defined: /var/www/htdocs/ (0.037s)
Debug: Begin WordPress load (0.037s)
Debug: wp-config.php path: /var/www/htdocs/wp-config.php (0.049s)

$ echo $?
255
```

**Comment by danielbachhuber** [comment]
> Is there anything else that I should be looking for?

Not sure. It's hard to say what the problem might be now without access to your codebase.

You'll need to do a bit of debugging to track it down. Try using `--skip-plugins=<plugin-slug>` with each active plugin to conditionally run WP-CLI without that particular plugin. If it loads when you're skipping a particular plugin, then that plugin is the one causing the problem.

**Comment by tommarshall** [comment]
Thanks. Didn't realise I could pass a slug to `--skip-plugins`. I should have checked the docs.

Looks to be an issue with [`addthis`](https://wordpress.org/plugins/addthis/):

```sh
for slug in `ls wp-content/plugins`; do sudo -u www-data -H wp --skip-plugins="$slug" option get home && echo $slug; done
http://example.com
addthis
```

We're on a slightly older version of that plugin, so I'll upgrade to the latest and see if that helps. 

Thanks again for your help with this.

**Comment by tommarshall** [comment]
FYI upgrading the `addthis` plugin from version 5.1.2 to 5.2.3 resolved the issue. Thanks again for your help with this.

**Comment by danielbachhuber** [comment]
You're welcome — glad you've figured it out!
