### ISSUE TITLE
Using this with git

### ISSUE THREAD

**Issue by TrollWarlord** [wp-cli/wp-cli#2477]
How would I manage various wordpress sites using wp-cli and do migrations with the database? I make a change locally, approve it, push it to git -> deploy it on the server, but your missing the db change to "enable/install" said plugin.

**Comment by danielbachhuber** [comment]
WP-CLI only supports simple database operations. You can use `wp db export` to export a copy of your database, and then `wp db import` to import the file you produced in the first operation. [Here are the docs](http://wp-cli.org/commands/db/) on the `wp db *` class of commands.

However, keep in mind there may be other values you need to transform as a part of the migration process, including updating the URLs in the database.
