### ISSUE TITLE
mu plugins are run even with --skip-plugins

### ISSUE THREAD

**Issue by BjornW** [wp-cli/wp-cli#2478]
When I used wp core --network is-installed I noticed that it was running a mu-plugin as well. I added the --skip-plugins parameter but it was still running the mu plugin which seems weird to me.

**Comment by danielbachhuber** [comment]
"mu plugins" stands for "must-use plugins", so I think the expected behavior is that they're always used. They should be considered equivalent to using a drop-in, adding code to your wp-config.php, etc.

I'll add a note to `--skip-plugins` mentioning that mu plugins are always used.

**Comment by BjornW** [comment]
Thanks
