### ISSUE TITLE
PHAR verification during update not robust enough

### ISSUE THREAD

**Issue by Viper007Bond** [wp-cli/wp-cli#2483]
WP-CLI was out of date so I updated it using itself:

```
C:\Users\Alex>wp cli update
You have version 0.21.1. Would you like to update to 0.22.0? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v0.22.0/wp-cli-0.22.0.phar...
New version works. Proceeding to replace.
Success: Updated WP-CLI to 0.22.0
```

Unfortunately what downloaded was actually an error response in XML format from Amazon/AWS:

[wp-cli.phar-broken.txt](https://github.com/wp-cli/wp-cli/files/135647/wp-cli.phar-broken.txt)

```
C:\Users\Alex>wp cli version
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>[...]
```

Regardless of why that happened (behind the scenes stuff on GitHub presumably), this means that the error checking isn't good enough. Presumably it would detect a broken PHAR download but when the contents of the file are something that PHP can read (text?) it looks like it doesn't detect that it's a bad download.

**Comment by danielbachhuber** [comment]
Sorry about that :(

> Presumably it would detect a broken PHAR download but when the contents of the file are something that PHP can read (text?) it looks like it doesn't detect that it's a bad download.

Yeah, that's exactly it:

```
$process = WP_CLI\Process::create( "{$php_binary} $temp --version {$allow_root}" );
$result = $process->run();
if ( 0 !== $result->return_code ) {
	$multi_line = explode( PHP_EOL, $result->stderr );
	WP_CLI::error_multi_line( $multi_line );
	WP_CLI::error( 'The downloaded PHAR is broken, try running wp cli update again.' );
}
```

We should run `--info` instead of `--version`, and check for a string from `--info` in the response.

**Comment by Viper007Bond** [comment]
Yeah, I read through the source of the command to make sure it wasn't a bug that had since been fixed and found that but I guess since it was returning non-empty (the XML) it assumed it worked.
