### ISSUE TITLE
Setup multiple multisite installations using the same database is not possible?

### ISSUE THREAD

**Issue by BjornW** [wp-cli/wp-cli#2484]
Not sure if this is an issue or more of a discussion on my usage of wpcli: 

I'm using wpcli to setup multiple WordPress Network installations automatically via an Ansible playbook. My objective is to have 2 or more load-balanced WordPress network installations sharing a database. Due to sharing the database I cannot use wpcli's command for multisite installation: it will setup one multisite installation without issue, but the second one is not setup as a Multisite installation. I presume this due to a database check which indicates (wrongfully, in this case) that a multisite has already been set up. I wonder if my usecase can be enabled without negative side effects for other users of wpcli.

**Comment by danielbachhuber** [comment]
> Due to sharing the database I cannot use wpcli's command for multisite installation: it will setup one multisite installation without issue, but the second one is not setup as a Multisite installation.

Just to verify, you're using two different table prefixes for these installations? Can you share more specific details on the commands you're running, and the output you see?

**Comment by BjornW** [comment]
Sure, I'm not using different table prefixes, because both installs should use the same database. It looks similar to this: 

<pre>
   loadbalancer
      |   |              
  wpmu1  wpmu2
        |
     database   
      storage
</pre>

So wpmu1 and wpmu2 are both Nginx webservers running a WordPress Network installation which is using 1 database and a shared nfs storage. This makes it easy have some downtime on wpmu1 while wpmu2 continues for instance.

The command which is run from within Ansible is: 
wp core multisite-install --url={{wordpress_url}} --title="{{wordpress_title}}" --admin_user={{wordpress_admin_user_name}} --admin_password={{wordpress_admin_password}} --admin_email={{wordpress_admin_email}} chdir={{wordpress_install_path}} --allow-root

**Comment by danielbachhuber** [comment]
> Sure, I'm not using different table prefixes, because both installs should use the same database.

Why do you need to run the installation command twice then? The command is intended primarily for the database alteration that needs to happen, and secondarily for altering the wp-config

**Comment by BjornW** [comment]
I need to run it per server so that the wp-config.php is changed. I've created a workaround in Ansible, where I check if the sitemeta table already exists and if it does I just add the required multisite constants to the wp-config.php file myself. It would be nice if running the wpcli multiple times would change the wp-config.php if it has not been changed yet, but the database indicates it should be a multisite installation. If that makes sense?

**Comment by danielbachhuber** [comment]
> I've created a workaround in Ansible, where I check if the sitemeta table already exists and if it does I just add the required multisite constants to the wp-config.php file myself.

You could also just include the `wp-config.php` file as a template in Ansible, and avoid having to use WP-CLI entirely.

> It would be nice if running the wpcli multiple times would change the wp-config.php if it has not been changed yet, but the database indicates it should be a multisite installation.

While I understand your use case, I don't think this is expected behavior for 80% of users, and a change that should be made to WP-CLI. Thanks for checking, though.

**Comment by BjornW** [comment]
Ok, I presumed my usecase was a bit far-fetched for the general usage of wpcli. Nonetheless thanks for considering.
