### ISSUE TITLE
Error on wp-cli export when text have accents and apostrophes (fr)

### ISSUE THREAD

**Issue by sakrow** [wp-cli/wp-cli#2490]
I have a FR wordpress. When i have exported the wordpress

`wp-cli.phar export --skip_comments --post_type=listing --debug --path=/var/www/vhosts/domain.fr/httpdocs --allow-root`

The `xml` looks like this:
```
<item>
  <title></title>
  <link>http://domain.fr/city/rennes/listing/creperie-la-saint-georges-rennes/</link>
  <pubDate>Tue, 17 Feb 2015 13:03:27 +0000</pubDate>
  <dc:creator>jean</dc:creator>
  <guid isPermaLink="false">http://domain.fr/?post_type=listing&amp;p=418</guid>
  <description></description>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>418</wp:post_id>
  <wp:post_date>2015-02-17 13:03:27</wp:post_date>
  <wp:post_date_gmt>2015-02-17 13:03:27</wp:post_date_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>open</wp:ping_status>
  <wp:post_name>creperie-la-saint-georges-rennes</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>listing</wp:post_type>
  <wp:post_password></wp:post_password>
  <wp:is_sticky>0</wp:is_sticky>
  <category domain="listingtags" nicename="35000"><![CDATA[35000]]></category>
  <category domain="listingtags" nicename="bretagne"><![CDATA[Bretagne]]></category>
  <category domain="listingcategory" nicename="creperies"><![CDATA[CrÃªperies]]></category>
  <category domain="listingtags" nicename="ille-et-vilaine"><![CDATA[Ille-et-Vilaine]]></category>
  <category domain="listingtags" nicename="rennes"><![CDATA[Rennes]]></category>
  <wp:postmeta>
    <wp:meta_key>_aioseop_keywords</wp:meta_key>
    <wp:meta_value><![CDATA[creperie, crÃªperie, rennes]]></wp:meta_value>
  </wp:postmeta>
</item>
```
The `<title>` has no value.
Others like `listingcategory` and `wp:meta_value` have codification error

**Comment by danielbachhuber** [comment]
Can you perform an export through the WordPress admin to verify that the admin exporter exports data as you'd expect?

**Comment by sakrow** [comment]
The export from the Wordpress admin interface works fine.

<item>
		<title>Crêperie La Saint-Georges</title>
		<link>http://ti-domain.fr/city/rennes/listing/creperie-la-saint-georges-rennes/</link>
		<pubDate>Tue, 17 Feb 2015 13:03:27 +0000</pubDate>
		<dc:creator><![CDATA[jean-albert]]></dc:creator>
		<guid isPermaLink="false">http://domain.fr/?post_type=listing&#038;p=418</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>418</wp:post_id>
		<wp:post_date><![CDATA[2015-02-17 13:03:27]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2015-02-17 13:03:27]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[open]]></wp:ping_status>
		<wp:post_name><![CDATA[creperie-la-saint-georges-rennes]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[listing]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="listingtags" nicename="35000"><![CDATA[35000]]></category>
		<category domain="listingtags" nicename="bretagne"><![CDATA[Bretagne]]></category>
		<category domain="listingcategory" nicename="creperies"><![CDATA[Crêperies]]></category>
		<category domain="listingtags" nicename="ille-et-vilaine"><![CDATA[Ille-et-Vilaine]]></category>
		<category domain="listingtags" nicename="rennes"><![CDATA[Rennes]]></category>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_aioseop_keywords]]></wp:meta_key>
			<wp:meta_value><![CDATA[creperie, crêperie, rennes]]></wp:meta_value>
		</wp:postmeta>
	</item>

**Comment by danielbachhuber** [comment]
Ok. I'm unable to reproduce, unfortunately:

```
salty-wordpress ➜  wordpress-develop.dev  wp post list
+----+---------------------------+-----------------------+---------------------+-------------+
| ID | post_title                | post_name             | post_date           | post_status |
+----+---------------------------+-----------------------+---------------------+-------------+
| 7  | This content is paged     | this-content-is-paged | 2016-02-08 15:20:14 | publish     |
| 1  | Crêperie La Saint-Georges | post-0                | 2016-01-30 18:17:21 | publish     |
| 2  | Post 1                    | post-1                | 2016-01-30 18:17:21 | publish     |
+----+---------------------------+-----------------------+---------------------+-------------+
salty-wordpress ➜  wordpress-develop.dev  wp export --post__in=1 --skip_comments
Starting export process...
Writing to file /srv/www/wordpress-develop.dev/wordpressdevelop.wordpress.2016-02-19.000.xml
Success: All done with export.
salty-wordpress ➜  wordpress-develop.dev  cat wordpressdevelop.wordpress.2016-02-19.000.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- generator="WordPress/4.5-alpha-35776-src" created="2016-02-19 13:26" -->
<rss version="2.0" xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:wp="http://wordpress.org/export/1.2/">
  <channel>
<title>WordPress Develop</title>
<link>http://wordpress-develop.dev</link>
<description>Just another Fake Site site</description>
<pubDate>Fri, 19 Feb 2016 13:26:19 +0000</pubDate>
<language>en-US</language>
<wp:wxr_version>1.2</wp:wxr_version>
<wp:base_site_url>http://wordpress-develop.dev/</wp:base_site_url>
<wp:base_blog_url>http://wordpress-develop.dev</wp:base_blog_url>
<generator>https://wordpress.org/?v=4.5-alpha-35776-src</generator>
<item>
  <title>Crêperie La Saint-Georges</title>
  <link>http://wordpress-develop.dev/2016/01/30/post-0/</link>
  <pubDate>Sat, 30 Jan 2016 18:17:21 +0000</pubDate>
  <dc:creator>daniel</dc:creator>
  <guid isPermaLink="false">http://wordpress-develop.dev/index.php/%post_name%/</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>1</wp:post_id>
  <wp:post_date>2016-01-30 18:17:21</wp:post_date>
  <wp:post_date_gmt>2016-01-30 18:17:21</wp:post_date_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>open</wp:ping_status>
  <wp:post_name>post-0</wp:post_name>
  <wp:status>publish</wp:status>
  <wp:post_parent>0</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>post</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>1</wp:is_sticky>
  <category domain="category" nicename="uncategorized"><![CDATA[Uncategorized]]></category>
  <wp:postmeta>
    <wp:meta_key>_edit_last</wp:meta_key>
    <wp:meta_value><![CDATA[1]]></wp:meta_value>
  </wp:postmeta>
</item>
  </channel>
</rss>
```

Are there other details you can share about your environment that might help me debug? Or, can you give me specific instructions to reproduce?

**Comment by sakrow** [comment]
I'm using the wp-cli 0.22 version, the WP have a WPML plugin but the WP not have any post in other languages, only in french 

The admin panel is in english.

you need other data type?

**Comment by danielbachhuber** [comment]
Oh. It probably relates to WPML. Can you deactivate the plugin and see if the issue reproduces?
