### ISSUE TITLE
wp package: Don't install WP-CLI when identified as a dependency

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2493]
Some packages define `wp-cli/wp-cli` as a dependency:

```
{
    "name": "c10b10/wp-cli-deploy",
    "description": "Deploys the local WordPress database or the uploads directory to a remote 
    "require": {
        "php": ">=5.4",
        "wp-cli/wp-cli": ">=0.14"
    },
}
```

This is permissible because we do support installing WP-CLI as a dependency on a Composer project.

However, `wp package install` shouldn't ever install WP-CLI as a dependency:

```
alty-wordpress ➜  wordpress-develop.dev  wp package install c10b10/wp-cli-deploy
Installing c10b10/wp-cli-deploy (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
 - Installing package
 - Error: wp-cli/wp-cli dev-master requires nb/oxymel 0.1.0 -> satisfiable by nb/oxymel[v0.1.0].
 - Installing package
 - Error: wp-cli/wp-cli dev-master requires symfony/translation 2.7.* -> satisfiable by symfony/translation[2.7.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
 - Installing package
 - Error: wp-cli/wp-cli dev-master requires symfony/event-dispatcher 2.7.* -> satisfiable by symfony/event-dispatcher[2.7.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
 - Installing package
 - Error: wp-cli/wp-cli dev-master requires symfony/dependency-injection 2.7.* -> satisfiable by symfony/dependency-injection[2.7.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
 - Installing package
 - Error: wp-cli/wp-cli dev-master requires symfony/console 2.7.* -> satisfiable by symfony/console[2.7.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
```

Not sure how difficult it is to overload Composer's dependency resolution process.

Related #1564

**Comment by danielbachhuber** [comment]
I spent an hour on this today without a lot of luck :(

I looked into two approaches:

1. Attempt to overload the dependency resolution process in `Composer\Installer->run()`. If only it was so easy as subclassing — `->run()` is several hundred lines long.
2. Attempt to inject WP-CLI as a platform dependency. This is currently restricted to PHP versions, HHVM, and PHP extensions.

Conceptually, what we need to be able to do is inform Composer that WP-CLI vX.X.X is already installed, and avoid trying to resolve it as a dependency.

**Comment by schlessera** [comment]
As mentioned on Twitter, I'd suggest looking into adding "Composer plugin" functionality to WP-CLI ( see [Setting up and using plugins](https://getcomposer.org/doc/articles/plugins.md) ).

The basic mechanism would work like this:

1. You tell Composer through your `composer.json` that WP-CLI is of `"type": "composer-plugin"`.
2. You `"require": { "composer-plugin-api": "^1.0" }`.
3. You tell Composer what class represents the plugin entry point: `"extra": { "class": "WP_CLI\\Composer_Plugin" }`
4. Your class `WP_CLI\Composer_Plugin implements Composer\Plugin\PluginInterface`.
5. In `WP_CLI\Composer_Plugin::activate()` you can get access to all the internal Composer configuration.
6. In `WP_CLI\Composer_Plugin::getSubscribedEvents` you can attach your own methods to Composer events.

The difference between this and the script hooks that Composer provides is:
- This is not only executed for the root process, but also for all dependencies at all levels.
- This is more tightly integrated into the Composer flow and lets you manipulate pretty much anything.

I would estimate that you should be able to hook into the pre-install event and prevent the dependency from being processed.

I'm pressed for time atm, but I would probably be able to look into this in more detail on Friday, if you think it might be worth a try.

**Comment by schlessera** [comment]
As a simple example of how to use this, you can look at one of my recent repos here: https://github.com/brightnucleus/geolite2-country/blob/master/src/DatabaseUpdater.php

I wanted to have a way of automatically keeping a geolocation database up-to-date on each `composer update`. This was not possible using the script hooks, as these are only executed for the root package.

At [DatabaseUpdater.php L40-L41](https://github.com/brightnucleus/geolite2-country/blob/master/src/DatabaseUpdater.php#L40-L41) you can see that you can attach arbitrary hooks to the Composer events in this way.

**Comment by danielbachhuber** [comment]
Very interesting. This does seem like a reasonable approach.

> I'm pressed for time atm, but I would probably be able to look into this in more detail on Friday, if you think it might be worth a try.

Oh, please do. I spent more time than I'd like yesterday, with little results, so I think I'm burnt out on this for the week. This bug is probably a blocker for WP-CLI v0.23.0 though, due out in a couple of weeks.
