### ISSUE TITLE
Dont regenerate big images thumbnails

### ISSUE THREAD

**Issue by s7e7v7e7n7** [wp-cli/wp-cli#2500]
Hello,

I have a wallpaper site and have 70k wallpapers.

I can try regenerate thumbnails, but program doing 500-550 image after stop process. I think problem is just big images like this (http://i.imgur.com/1i9qP51.jpg stop this image) ... Cant regenerate big images.

i use this code 

wp --path=/var/www/vhosts/domain.net/httpdocs/ media regenerate --yes

after 500-550 post stop process and giving no error.

Stop like this;

> Regenerated thumbnails for "290965-face, women, Chloe_Bennet, actress, closeup" (ID 179041).
Regenerated thumbnails for "290912-women, face" (ID 179039).
[root@server ~]#

and i try this code

seq 1 999999 | xargs wp --path=/var/www/vhosts/domain.net/httpdocs/ media regenerate --yes

stop same image regenerate and stop process ...

But this giving this error;
.....

> Regenerated thumbnails for "290965-face, women, Chloe_Bennet, actress, closeup" (ID 179041).
Regenerated thumbnails for "290912-women, face" (ID 179039).
xargs: sh: exited with status 255; aborting
[root@server ~]#

How can i skip and continue regenerate? 70k image wait regenerate  :(

Thank for help...

(So sorry my english not good...)

Edit: I think problem is just big files like this... Cant regenerate big images.
http://i.imgur.com/1i9qP51.jpg

how can i fix this?

**Comment by danielbachhuber** [comment]
To address your original question, you can use `--skip-delete` to skip deletion of original thumbnails, or `--only-missing` to only generate missing thumbnails. [Please see the docs](http://wp-cli.org/commands/media/regenerate/).

> Edit: I think problem is just big files like this... Cant regenerate big images. how can i fix this?

I'm not sure without being able to debug. It's likely a configuration issue specific to your server — or the problem is present with that specific image file.

**Comment by s7e7v7e7n7** [comment]
--only-missing not for me. I need to create all the pictures again. 

--skip-delete not skip big files

but problem have just big images. maybe problem is my php.ini file... i dont know...

is it possible? How do I make an adjustment in php.ini (or another config) process large images ?

Is there a limit to regenerate process?

**Comment by danielbachhuber** [comment]
Sorry, I'm not sure what your problem is and can't help further without debugging. You might consider regenerating your image files on another server, and then sync them over after completion.
