### ISSUE TITLE
Please use semver to tag wp-cli releases, and make the next release 1.0.

### ISSUE THREAD

**Issue by greg-1-anderson** [wp-cli/wp-cli#2502]
Using [Semantic Versioning](http://semver.org/) is a good way to communicate the level of change in each release to clients who use your software.

Using "0.x" versions makes no promise about backwards compatibility.  If the release after v0.22.0 is tagged v0.23.0, then new features and/or breaking changes might be included, but there is no way to communicate that explicitly, as nothing is promised.  If v0.22.1 is used, that implies that only bugfixs were made, but even here, nothing is promised.

Tagging the release after v0.22.0 as v1.0.0 does **not** mean that said version has necessarily made any breaking changes or added any new features.  The v1.0.0 release defines the public API, which simply means that semver will be used to tag all of the releases that follow.

Use:

v1.0.1 if the next release after v1.0.0 contains only bugfixes.
v1.1.0 if the next release after v1.0.0 contains new features (bug fixes optional).
v2.0.0 when any breaking change is introduced.

Semver does not say anything about how frequently or infrequently you should add features or make breaking changes; it only stipulates how the software should be described when features are added, or breaking changes are made.

Mature, in-production software like wp-cli should be using semver versioning, as it is very useful to be able to see which versions are compatible when this mechanism is used. Managing multiple "0.x" releases on a platform becomes harder to maintain, because it is not clear which versions made breaking changes.

**Comment by danielbachhuber** [comment]
Thanks for continuing this discussion, @greg-1-anderson.

At this time, I don't have plans to tag the next release as v1.0.0. WP-CLI loosely follows semantic versioning — not religiously. There are long, philosophical conversations to be had about versioning, and I don't wish to rehash them in this issue. v1.0.0 will come at some point. Between now and the, and afterwards, I strongly encourage you to read the thorough changelog I put together with each release.
