### ISSUE TITLE
PHP Fatal Error. Call to a member function add_shortcode()

### ISSUE THREAD

**Issue by plutocrat** [wp-cli/wp-cli#2503]
Hi,
Not sure if this is an issue with wp-cli or with the theme. I've just been trying to run wp-cli on a website. It runs fine on other wp installs on the same server. However when it comes to this one site, it fails to run when in the wp root directory. Any command I try to run fails with 
Fatal error: Call to a member function add_shortcode() on a non-object in /p/a/t/h/wp-content/themes/gadgetry-parent/framework/extensions/shortcodes/helpers/SHORTCODES.php on line 5

The file in question says
```
<?php

function tf_add_shortcode($type, $function, $atts) {
    global $TFUSE;
    $TFUSE->ext->shortcodes->add_shortcode($type, $function, $atts);
}

function tf_shortcode_alias($alias, $alias_to, $values = array()) {
    global $TFUSE;
    $TFUSE->ext->shortcodes->add_alias($alias, $alias_to, $values);
}
```
wp cli sub-commands work though ... I guess they don't try to load the wp install files. 
$ wp cli info
PHP binary:	/usr/bin/php5
PHP version:	5.4.45-1~dotdeb+7.1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.22.0
 
So is this a bug? Is there a workaround? The site and theme seem to work fine. Let me know if you need any more info.

**Comment by voldemortensen** [comment]
Sounds like the theme is doing something wrong. A workaround would be to add the `--skip-themes` flag to prevent the theme files from loading.

**Comment by plutocrat** [comment]
Thanks. That did indeed help, and I can confirm that wp-cli does actually start up now, so I can use some non-theme related commands. I'll see what the theme developer has to say on the matter.

**Comment by plutocrat** [comment]
So yeah, tried to contact the developer but they won't let you submit any support requests without purchasing a theme. 
Tried a bit of debugging. Commented out the first function, and then got another PHP Fatal error from another file in the theme framework which referenced tf_add_shortcode. There were too many references for me to deal with, so had to abandon ship. Will stick with the --skip-themes workaround.

**Comment by mrksdiehl** [comment]
If anybody is facing the same problem, there are three files where you have to edit the theme if you want to use wp-cli with TFUSE themes.

1. In framework/extensions/shortcodes/helpers/SHORTCODES.php in function tf_add_shortcode and tf_shortcode_alias check if the global $TFUSE is actually there before executing like this:
    ```
    function tf_add_shortcode($type, $function, $atts) {
      global $TFUSE;
      if($TFUSE){
        $TFUSE->ext->shortcodes->add_shortcode($type, $function, $atts);
      }
    }

    function tf_shortcode_alias($alias, $alias_to, $values = array()) {
        global $TFUSE;
        if($TFUSE){
          $TFUSE->ext->shortcodes->add_alias($alias, $alias_to, $values);
        }
    }
    ```
2. In theme_config/options/admin_options.php I added this at the top:

    ```
    global $TFUSE;
    if($TFUSE->ext->slider === null){
        return;
    }
    ```
3. In framework/helpers/GENERAL.php at line 591 I changed the code to:

    ```
    if(defined(WP_CLI)){
      user_error('$TFUSE is not loaded', E_USER_ERROR);
    }
    ```
After that I could run wp without errors.
