### ISSUE TITLE
search and replace not working on serialized data

### ISSUE THREAD

**Issue by mariodabek** [wp-cli/wp-cli#2505]
data testing

a:1:{s:51:"/nas/content/live/sobeys/wp-content/uploads/sites/5";a:1:{s:4:"size";i:0;}}

using command

 wp search-replace "/uploads/sites/5" "/uploads" --skip-columns=guid --precise --recurse-objects

**Comment by danielbachhuber** [comment]
Where is the data stored in your database? Can you share the full command execution (input and output)?

**Comment by raptor235** [comment]
@danielbachhuber this was stored in the options table I belive, we also tried putting it in excerpt in wp_posts just to run as a test and the serialized object wasn't replaced but a plain string was. 

When you guys loop over tables and columns do you look for serialized data in every column and row or is it on specific columns?

**Comment by raptor235** [comment]
Sorry Mario, I'm hijacking your thread, here is some info

**Before Upgrade**

https://www.dropbox.com/s/ld6lybjexbo8yfb/Screenshot%202016-02-25%2008.50.10.png?dl=0

1 update

https://www.dropbox.com/s/rhte7rbh22cb28y/Screenshot%202016-02-25%2008.50.36.png?dl=0

**Result**

https://www.dropbox.com/s/stx8ed5p0twwvn4/Screenshot%202016-02-25%2008.50.48.png?dl=0

**Comment by raptor235** [comment]
Test #2 on options table

https://www.dropbox.com/s/drgfxxykbs049zj/Screenshot%202016-02-25%2008.52.07.png?dl=0

1 Update 

https://www.dropbox.com/s/bmz2cvspe67zxv9/Screenshot%202016-02-25%2008.52.23.png?dl=0

https://www.dropbox.com/s/ngksh6sti9y53qu/Screenshot%202016-02-25%2008.52.37.png?dl=0

vagrant@hgv:/hgv_data/sites/sob_tabletal$ wp search-replace '/uploads/sites/5' '/uploads' --skip-columns=guid --recurse-objects --precise --verbose
Checking: wp_commentmeta.meta_key
0 rows affected using PHP (in 0.003s)
Checking: wp_commentmeta.meta_value
0 rows affected using PHP (in 0.006s)
Checking: wp_comments.comment_author
0 rows affected using PHP (in 0.005s)
Checking: wp_comments.comment_author_email
0 rows affected using PHP (in 0.004s)
Checking: wp_comments.comment_author_url
0 rows affected using PHP (in 0.007s)
Checking: wp_comments.comment_author_IP
0 rows affected using PHP (in 0.003s)
Checking: wp_comments.comment_content
0 rows affected using PHP (in 0.026s)
Checking: wp_comments.comment_approved
0 rows affected using PHP (in 0.002s)
Checking: wp_comments.comment_agent
0 rows affected using PHP (in 0.007s)
Checking: wp_comments.comment_type
0 rows affected using PHP (in 0.003s)
Checking: wp_links.link_url
0 rows affected using PHP (in 0.001s)
Checking: wp_links.link_name
0 rows affected using PHP (in 0s)
Checking: wp_links.link_image
0 rows affected using PHP (in 0s)
Checking: wp_links.link_target
0 rows affected using PHP (in 0s)
Checking: wp_links.link_description
0 rows affected using PHP (in 0s)
Checking: wp_links.link_visible
0 rows affected using PHP (in 0s)
Checking: wp_links.link_rel
0 rows affected using PHP (in 0s)
Checking: wp_links.link_notes
0 rows affected using PHP (in 0.001s)
Checking: wp_links.link_rss
0 rows affected using PHP (in 0.001s)
Checking: wp_options.option_name
0 rows affected using PHP (in 0.001s)
Checking: wp_options.option_value
1 rows affected using PHP (in 0.009s)
Checking: wp_options.autoload
0 rows affected using PHP (in 0s)
Checking: wp_postmeta.meta_key
0 rows affected using PHP (in 0.005s)
Checking: wp_postmeta.meta_value
0 rows affected using PHP (in 0.018s)
Checking: wp_posts.post_content
0 rows affected using PHP (in 0.007s)
Checking: wp_posts.post_title
0 rows affected using PHP (in 0.002s)
Checking: wp_posts.post_excerpt
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.post_status
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.comment_status
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.ping_status
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.post_password
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.post_name
0 rows affected using PHP (in 0.002s)
Checking: wp_posts.to_ping
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.pinged
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.post_content_filtered
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.post_type
0 rows affected using PHP (in 0.001s)
Checking: wp_posts.post_mime_type
0 rows affected using PHP (in 0.001s)
Checking: wp_term_taxonomy.taxonomy
0 rows affected using PHP (in 0.001s)
Checking: wp_term_taxonomy.description
0 rows affected using PHP (in 0.001s)
Checking: wp_terms.name
0 rows affected using PHP (in 0.001s)
Checking: wp_terms.slug
0 rows affected using PHP (in 0.001s)
Checking: wp_usermeta.meta_key
0 rows affected using PHP (in 0s)
Checking: wp_usermeta.meta_value
0 rows affected using PHP (in 0.001s)
Checking: wp_users.user_login
0 rows affected using PHP (in 0s)
Checking: wp_users.user_nicename
0 rows affected using PHP (in 0s)
Checking: wp_users.user_email
0 rows affected using PHP (in 0s)
Checking: wp_users.user_url
0 rows affected using PHP (in 0s)
Checking: wp_users.user_activation_key
0 rows affected using PHP (in 0s)
Checking: wp_users.display_name
0 rows affected using PHP (in 0s)
+------------------+-----------------------+--------------+------+
| Table            | Column                | Replacements | Type |
+------------------+-----------------------+--------------+------+
| wp_commentmeta   | meta_key              | 0            | PHP  |
| wp_commentmeta   | meta_value            | 0            | PHP  |
| wp_comments      | comment_author        | 0            | PHP  |
| wp_comments      | comment_author_email  | 0            | PHP  |
| wp_comments      | comment_author_url    | 0            | PHP  |
| wp_comments      | comment_author_IP     | 0            | PHP  |
| wp_comments      | comment_content       | 0            | PHP  |
| wp_comments      | comment_approved      | 0            | PHP  |
| wp_comments      | comment_agent         | 0            | PHP  |
| wp_comments      | comment_type          | 0            | PHP  |
| wp_links         | link_url              | 0            | PHP  |
| wp_links         | link_name             | 0            | PHP  |
| wp_links         | link_image            | 0            | PHP  |
| wp_links         | link_target           | 0            | PHP  |
| wp_links         | link_description      | 0            | PHP  |
| wp_links         | link_visible          | 0            | PHP  |
| wp_links         | link_rel              | 0            | PHP  |
| wp_links         | link_notes            | 0            | PHP  |
| wp_links         | link_rss              | 0            | PHP  |
| wp_options       | option_name           | 0            | PHP  |
| wp_options       | option_value          | 1            | PHP  |
| wp_options       | autoload              | 0            | PHP  |
| wp_postmeta      | meta_key              | 0            | PHP  |
| wp_postmeta      | meta_value            | 0            | PHP  |
| wp_posts         | post_content          | 0            | PHP  |
| wp_posts         | post_title            | 0            | PHP  |
| wp_posts         | post_excerpt          | 0            | PHP  |
| wp_posts         | post_status           | 0            | PHP  |
| wp_posts         | comment_status        | 0            | PHP  |
| wp_posts         | ping_status           | 0            | PHP  |
| wp_posts         | post_password         | 0            | PHP  |
| wp_posts         | post_name             | 0            | PHP  |
| wp_posts         | to_ping               | 0            | PHP  |
| wp_posts         | pinged                | 0            | PHP  |
| wp_posts         | post_content_filtered | 0            | PHP  |
| wp_posts         | post_type             | 0            | PHP  |
| wp_posts         | post_mime_type        | 0            | PHP  |
| wp_term_taxonomy | taxonomy              | 0            | PHP  |
| wp_term_taxonomy | description           | 0            | PHP  |
| wp_terms         | name                  | 0            | PHP  |
| wp_terms         | slug                  | 0            | PHP  |
| wp_usermeta      | meta_key              | 0            | PHP  |
| wp_usermeta      | meta_value            | 0            | PHP  |
| wp_users         | user_login            | 0            | PHP  |
| wp_users         | user_nicename         | 0            | PHP  |
| wp_users         | user_email            | 0            | PHP  |
| wp_users         | user_url              | 0            | PHP  |
| wp_users         | user_activation_key   | 0            | PHP  |
| wp_users         | display_name          | 0            | PHP  |
+------------------+-----------------------+--------------+------+
Success: Made 1 replacements.

**Comment by danielbachhuber** [comment]
> When you guys loop over tables and columns do you look for serialized data in every column and row or is it on specific columns?

Yes, `wp search-replace` inspects each column to see if it potentially has serialized data in it.

> this was stored in the options table I belive, we also tried putting it in excerpt in wp_posts just to run as a test and the serialized object wasn't replaced but a plain string was.

Are you sure it's serialized properly? If it's not, then WP-CLI won't be able to deserialize it and deep inspect it.

**Comment by JRGould** [comment]
It looks like the issue here is that the string `/nas/content/live/sobeys/wp-content/uploads/sites/5` is a key in an associative array and the `SearchReplacer` only operates on the values of unserialized data - it makes no attempts to run search/replace operations on array keys.

**Comment by danielbachhuber** [comment]
Good find, @JRGould.

Ignoring keys is expected behavior for `wp search-replace`.

**Comment by nylen** [comment]
> Ignoring keys is expected behavior for `wp search-replace`.

Hi @danielbachhuber - out of curiosity, why does `wp search-replace` not replace inside serialized array keys too?  Is this intentional, or would a patch be accepted to change this?

**Comment by danielbachhuber** [comment]
> out of curiosity, why does `wp search-replace` not replace inside serialized array keys too? Is this intentional, or would a patch be accepted to change this?

Yes, it's intentional. I think it's largely an anachronism of the original implementation though.

I'd be amenable to a patch that modifies this behavior with an environment variable.

**Comment by nylen** [comment]
Cool - we should make sure we don't modify array key order.  Any other potential gotchas you can think of?

Any reason to go with an environment variable rather than a documented CLI option?

**Comment by danielbachhuber** [comment]
> Any other potential gotchas you can think of?

Not at this point.

> Any reason to go with an environment variable rather than a documented CLI option?

`wp search-replace` is quite overloaded with options right now. Given the infrequency that this would be used, a less-prominent environment variable seems more appropriate.

**Comment by nylen** [comment]
>Is this environment variable already implemented ?

Not yet. I've been meaning to look at this for a while but haven't had time yet.

>It really appeared to me as an undesired effect, when you do a search replace you expect every occurence of the string to be replaced not just the values of the serialized data..

**Comment by mkdizajn** [comment]
Hey guys why did this thread stopped,, feel like this is needed much? (WooCommerce anyone?)

Can we add some custom flag for ex: `--keys=true` `default=false`

**Comment by nylen** [comment]
Another option would be to make replacing keys the default behavior.  This is what most people would expect, I think.

Still need to look out for edge cases:

- don't modify array key order
- make sure the replacement array key does not already exist

**Comment by Tofandel** [comment]
What about converting the serialized data to array then to json and doing the replace on the string? And then reserialize it ? It's much slower but the simpler and safer way to do it

**Comment by nylen** [comment]
That is not simpler or safer.

**Comment by martingoldie** [comment]
Can this issue be moved to https://github.com/wp-cli/search-replace-command/issues
