### ISSUE TITLE
Migrate wiki docs to the website

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2508]
Now that our internal API docs are present on the website (#1045), moving the rest of the wiki docs to the website means they'll be exposed in search and will benefit from a review workflow.

We need to migrate:

* [x] Alternative Install methods
* [x] Helpful Bug Reports
* [x] Commands Cookbook
* [x] List of community commands
* [x] Frequently Asked Questions
* [x] Plugin Unit Tests
* [x] Package Functional Tests
* [x] External Resources
* [x] Example Usage
* [x] Shell Tips
* [x] Tools that use WP-CLI
* [x] Philosophy
* [x] Governance
* [x] Release Checklist
* [x] Implementation Details
* [x] <del>Github Issue Labels</del>
* [x] <del>Similar Projects</del>
* [x] List of Hosting Companies

**Comment by borekb** [comment]
Wiki is technically a Git repo, couldn't the website pull it periodically and just render the Markdown files there? (Not sure how the website is done, if it's static HTML only, the HTML would be generated by some script / CI server that would watch the wiki repo.)

**Comment by danielbachhuber** [comment]
> Wiki is technically a Git repo, couldn't the website pull it periodically and just render the Markdown files there

Technically we could, but I'd like to follow a PR workflow going forward for docs.

**Comment by borekb** [comment]
So what is this task technically about? Move the Markdown files to this repo? To some other repo?

**Comment by danielbachhuber** [comment]
Oh, sorry. The website is tracked in this repo: https://github.com/wp-cli/wp-cli.github.com

We want to port each wiki page over, and ensure it looks good within the website.

**Comment by gilbitron** [comment]
I'm going to have a crack at porting some of these today. Will submit PRs over on https://github.com/wp-cli/wp-cli.github.com.

**Comment by gilbitron** [comment]
@danielbachhuber Should these docs go under a `/wiki` subdirectory or be top level pages?

**Comment by danielbachhuber** [comment]
@gilbitron Just to follow up your question, I'm putting these in `/docs/` and giving them some extra header details so they get special treatment:

```
---
layout: doc
title: Installing
category: Guides
description: Recommended and alternative installation mechanisms.
---
```

Notably:

* "Category" is either "Guides, "Resources", "Contributing" or "Misc".
* "Description" is the description that lands on `/docs/`, and is also used in the SEO title.
* The list in `/docs/` is generated by `./vendor/bin/phake`.

**Comment by danielbachhuber** [comment]
Wow, that was a ton of work.
