### ISSUE TITLE
Multi-site install (wp-config.php edits) doesn't work for older versions

### ISSUE THREAD

**Issue by tevert** [wp-cli/wp-cli#2517]
The problem is that older versions of wp-config.php don't contain the magic string: "that's all, stop editing!" I'm specifically using 3.8.5, since that's the most up-to-date version obtainable from apt-get (which is another problem, but not one under our control). 

Proposal - allow passing a custom search term. This was already implemented in https://github.com/wp-cli/wp-cli/pull/1746, but was rejected for some reason.

This would allow flexibility going backwards _and_ forward in versions. It also solves the language problem brought up in #1703. 

As an alternate solution: are there potential problems with just inserting the wp-config lines at the top of the file? I'm not a wordpress expert so I'm not sure what the potential ramifications there are. Of course - this then does not solve the language problem, just the issue with having a somewhat brittle approach for determining where to insert.

**Comment by danielbachhuber** [comment]
> The problem is that older versions of wp-config.php don't contain the magic string: "that's all, stop editing!" I'm specifically using 3.8.5, since that's the most up-to-date version obtainable from apt-get (which is another problem, but not one under our control).

I think apt-get is actually your problem. WordPress 3.8.5 [downloaded from the release archives](https://wordpress.org/download/release-archive/) includes the magic string.

> Proposal - allow passing a custom search term. This was already implemented in #1746, but was rejected for some reason.

I think adding a custom search term fails the tenet of decisions, not options. Using a custom search term is a minority use case, and a small one at that. The alternative, modifying wp-config yourself, is perfectly reasonable.

> As an alternate solution: are there potential problems with just inserting the wp-config lines at the top of the file?

I don't know, actually. The location assumption is from very early bc6a036f662c166a36e8eca83aebb52c8ba391f2, so there might be something else we could key from

**Comment by tevert** [comment]
Yeah, on further inspection, the aptitude package actually includes a custom wp-config.php. That's definitely part of the problem here. 

> I think adding a custom search term fails the tenet of decisions, not options. Using a custom search term is a minority use case, and a small one at that. The alternative, modifying wp-config yourself, is perfectly reasonable.

I'll agree that it's likely a small use case, but I disagree that manual edits are perfectly reasonable. Wordpress's huge failing point is its lack of automation, and since this tool is designed to help compensate for that deficiency, I would expect that it would strive to more fully solve that problem. It's entirely possible that I've misunderstood the vision of the project though.

**Comment by danielbachhuber** [comment]
Try as we might, WP-CLI can't solve for every edge case. Installing WP 3.8.5 via apt-get, which packages a custom wp-config, is an edge case.

If we can inject based on a different token though, we might be able to globally solve the problem.

**Comment by danielbachhuber** [comment]
> If we can inject based on a different token though, we might be able to globally solve the problem.

I've spent some time thinking about this, and haven't identified a better token to use that's guaranteed to be more reliable. Because the process of modifying the wp-config.php is quite ugly, I'm concerned about making a change which could cause a regression.

For now, I'm going to address this issue by warning the end user when the token can't be found, instead of erroneously inserting the constants into the end of the file.
