### ISSUE TITLE
Error running wp core config: Too many positional arguments, dbpass

### ISSUE THREAD

**Issue by bhagerty** [wp-cli/wp-cli#2518]
Using WP-CLI 0.22.0, I run this command:

`wp core config --dbname=demo --dbuser=demouser dbpass=dempassword --dbhost='localhost' --dbcollate='utf8_unicode_ci'`

I get this result:

`Error: Too many positional arguments: dbpass=dempassword`

I got the identical error with various different passwords.

Am I doing something wrong? If not, do you need any more info from me to fix this issue?

**Comment by trepmal** [comment]
Don't forget the double hyphen before dbpass,  `--dbpass`

**Comment by bhagerty** [comment]
DUH!
