### ISSUE TITLE
wp user meta add appears broken when accompanied by a --format option

### ISSUE THREAD

**Issue by maraymer** [wp-cli/wp-cli#2519]
I've tried this on two different installations of wordpress and two different versions of wp-cli:

wp user meta add userid keyname keyvalue --format=json

I always get Error: Invalid JSON: <keyvalue>

Has anyone else seen this happen?

**Comment by danielbachhuber** [comment]
The error indicates you're supplying invalid JSON. `--format=json`, when used with write operations like `add`, denotes the format of the supplied input.

Can you share the full command you're running?

**Comment by maraymer** [comment]
Hi,

I'm using the following:

wp user meta add 3 test fun --format=json --path=_location of my wordpress_

Matthew

**Comment by danielbachhuber** [comment]
`fun` isn't JSON, so you don't need to use `--format=json`

**Comment by maraymer** [comment]
Daniel,

Thanks.  I think I understand my confusion now.  I was thinking in terms of output -- but in this case there isn't anything more than a confirmation of output.  So, it does make sense that the format would refer to the input!

Matthew

**Comment by danielbachhuber** [comment]
> I was thinking in terms of output -- but in this case there isn't anything more than a confirmation of output. So, it does make sense that the format would refer to the input!

Yep, exactly. Sorry for the confusion.
