### ISSUE TITLE
Unexpected error when installing plugins

### ISSUE THREAD

**Issue by AbdealiJK** [wp-cli/wp-cli#2520]
I was installing civicrm and got an error while trying to install some wp plugin.
When trying to do it manually, I got the same error. It's been reported by others that this should work.
It happens for all plugins that I'm trying to install

I'm unable to figure out what could be wrong. I tried upgrading `openssl` and `php5-curl` as I read that online in some forum. Restarting apache didn't help either.

```
ajk@ajk-ThinkPad-R60:~/buildkit/build/wpmaster/wp-content/plugins$ wp plugin install civicrm-admin-utilities --debug
Debug: No readable global config found (0.029s)
Debug: Using project config: /home/ajk/Documents/civi/civicrm-buildkit/build/wpmaster/wp-cli.yml (0.034s)
Debug: ABSPATH defined: /home/ajk/Documents/civi/civicrm-buildkit/build/wpmaster/ (0.121s)
Debug: Begin WordPress load (0.121s)
Debug: wp-config.php path: /home/ajk/Documents/civi/civicrm-buildkit/build/wpmaster/wp-config.php (0.122s)
Debug: Loaded WordPress (0.724s)
Debug: Running command: plugin install (0.725s)
PHP Notice:  An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /home/ajk/Documents/civi/civicrm-buildkit/build/wpmaster/wp-admin/includes/plugin-install.php on line 158
PHP Stack trace:
PHP   1. {main}() /home/ajk/Documents/civi/civicrm-buildkit/bin/wp:0
PHP   2. include() /home/ajk/Documents/civi/civicrm-buildkit/bin/wp:4
PHP   3. include() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Runner.php:723
PHP   6. WP_CLI\Runner->run_command() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Runner.php:320
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Runner.php:313
PHP   8. call_user_func() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:294
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:294
PHP  10. call_user_func() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  11. Plugin_Command->install() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:52
PHP  12. WP_CLI\CommandWithUpgrade->install() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/commands/plugin.php:445
PHP  13. Plugin_Command->install_from_repo() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/WP_CLI/CommandWithUpgrade.php:141
PHP  14. plugins_api() phar:///home/ajk/Documents/civi/civicrm-buildkit/bin/wp/php/commands/plugin.php:297
PHP  15. trigger_error() /home/ajk/Documents/civi/civicrm-buildkit/build/wpmaster/wp-admin/includes/plugin-install.php:158
Warning: civicrm-admin-utilities: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>.
```

**Comment by danielbachhuber** [comment]
Can you try `wp plugin install civicrm-admin-utilities --debug --skip-plugins` to see if one of the plugins is modifying the installation procedure?

**Comment by AbdealiJK** [comment]
@danielbachhuber Thanks for the quick reply.
But that didnt work, still giving the same error

**Comment by danielbachhuber** [comment]
Are you able to install the plugin through the WordPress admin?

**Comment by AbdealiJK** [comment]
Ah, I never tried opening the wordpress installation as civicrm hadnt completed doing it's stuff (failed in between).
Let me try that out.

**Comment by AbdealiJK** [comment]
Well, that's interesting. When I go to the "Add plugins" page, and try to browse, I get the same error.
So, I guess this is not a wp-cli issue
Although, could you give me some pointers on what the issue could be ? Or even which log I can look at ?
(The server error logs say the same error as I got with wp-cli.)

PS: Closing this issue as it's not a wp-cli issue.

**Comment by danielbachhuber** [comment]
I suspect it's an issue with SSL verification against WordPress.org. Unfortunately, I can't think of any logs you can look at, as `trigger_error()` is the most WordPress does to log the error.

You can use `wp shell` to call `plugins_api()` directly and see what its raw response is:

```
$ wp shell
wp> require_once ABSPATH.'wp-admin/includes/plugin.php';
wp> require_once ABSPATH.'wp-admin/includes/plugin-install.php';
wp> plugins_api( 'plugin_information', array( 'slug' => 'bbpress' ) );
```

**Comment by AbdealiJK** [comment]
Thanks for that bit of info :) I'll figure it out

**Comment by AbdealiJK** [comment]
Just an FYI for people who get the same issue:
https://wordpress.org/support/topic/cannot-install-plugins-unexpected-http-error solves the issue
They recommend changing the timeout in `wp-admin/includes/plugin-install.php` for the function `wp_remote_post()` from 15 to 60.
For some weird reason if this is done, the page loads within 2-3 seconds ... (Not sure why it timed out in the first place)

**Comment by danielbachhuber** [comment]
FWIW, you shouldn't modify core files. If you're experiencing timeout issues, which probably isn't a WordPress issue by the way, you can change the timeout using a filter.
