### ISSUE TITLE
No way of checking if database exists other than mysql

### ISSUE THREAD

**Issue by garrett-eclipse** [wp-cli/wp-cli#2524]
Hello,

I have a bash script for installing Wordpress which used the 'wp db create' command.
However while developing I'd get part way and have to rerun, which failed on the db create command as the table already existed.
So I put in the drop command 'wp db drop --yes' which works if the table already exists.
But on a clean install will fail;
ERROR 1008 (HY000) at line 1: Can't drop database '...'; database doesn't exist

So I was trying to find a way using wp-cli to either conditionally check if the table exists so I can run the drop command or a flag on the drop command to avoid the error message if no table exists, or I guess a flag on the create command which would force replace the table. Not sure what would be most appropriate.

Anyway for now I've resorted to mysql to do the conditional check;
```
if mysql --user=root --password=root -e "use $dbname"; then
    wp db drop --yes
fi
```

Is there a better way using all wp-cli commands? 

Appreciated,
Cheers

**Comment by danielbachhuber** [comment]
> I have a bash script for installing Wordpress which used the 'wp db create' command.
>
> However while developing I'd get part way and have to rerun, which failed on the db create command as the table already existed.

In your bash script, instead of:

```
wp db create
```

use:

```
wp db create || true
```

to continue execution if the command fails.

**Comment by garrett-eclipse** [comment]
Thanks @danielbachhuber, if the db already exists from a failed install will not dropping it cause any issues with the 'wp core install' that follows the 'wp db create' command? Will it's contents simply be replaced?
Or would it make more sense to tie the continue execution command to the wp db drop command like
wp db drop --yes || true
Appreciate your input. Thanks

**Comment by danielbachhuber** [comment]
> if the db already exists from a failed install will not dropping it cause any issues with the 'wp core install' that follows the 'wp db create' command? Will it's contents simply be replaced?

`wp core install` will error if core is already installed.

> Or would it make more sense to tie the continue execution command to the wp db drop command like
wp db drop --yes || true

It depends on what your goals are with the script. If you want to fully reset the installation, then you can call `wp db reset` to always reset the database, and avoid the `wp db drop` and `wp db create` dance.

**Comment by garrett-eclipse** [comment]
Thanks @danielbachhuber 

I would like the script to function regardless if it's a new install or replacing an existing install (be it corrupt or not). To me it seems wp db reset only works on existing so would have to either reset or create depending on there existing a db already.

I opted for the drop command with the '|| true' conditional so if there's a database existing it will be removed, otherwise nothing will occur and we'll move along to creating the database.

I appreciate you hashing that out with me, your input has been very helpful.

Cheers

**Comment by danielbachhuber** [comment]
You're welcome! Glad you've gotten it figured out.

**Comment by artursopelnik** [comment]
@garrett-eclipse Could you show me how your bash script work? Maybe it could help me …

**Comment by garrett-eclipse** [comment]
Hi @artursopelnik here's the original article my bash script concept and initial version came from;
https://indigotree.co.uk/automated-wordpress-installation-with-bash-wp-cli/

Mine just does a few more custom plugin/theme installs but the core script hasn't changed much.

One core change I did make that is mentioned in this thread is the dropping of existing database which is done like so;
```
# create database, and install WordPress
if mysql --user=$dbuser --password=$dbpass -e "use $dbname"; then
    wp db drop --yes
fi
wp db create
```

Let me know if you get stuck or need some guidance, happy to help.

Cheers

**Comment by artursopelnik** [comment]
@garrett-eclipse if the database not exists your condition gives me an error
`
ERROR 1049 (42000) at line 1: Unknown database 'ars_wordpress'
`
