### ISSUE TITLE
WXR import: Multi-file option can skip non-custom menu items

### ISSUE THREAD

**Issue by jacobischwartz** [wp-cli/wp-cli#2527]
Hello,

There seems to be a bug that sometimes causes the import command to skip importing menu items, unless they are custom menu items. It seems like it might only happen when the menu item post is located in a different WXR file from the content post. It doesn't matter that the WXR with the content post was imported before the WXR with the menu item post.

Here are the mechanics as I have been able to identify them:

wp-cli/php/commands/import.php (wp-cli)
The __invoke method in this file discovers the wxr files and imports them one by one, by calling the import_wxr method each time. That method creates a new instance of WP_Import and imports the file.

wordpress-importer/wordpress-importer.php (Wordpress Importer plugin)
On line 802, the WP_Import->process_menu_item method checks that the content referred to by the post_type menu item exists - and it does this by checking whether it was imported within the same file. It determines that by checking $this->processed_posts.

The plugin doesn't seem to be built to accommodate multi-WXR imports - the wp-cli command adds that functionality. So it's something that the plugin COULD solve, by also checking whether the post exists in the database, but does not. I'll cross-post in the plugin's support forum.

**Comment by danielbachhuber** [comment]
I imagine you learned this the hard way :(

> The plugin doesn't seem to be built to accommodate multi-WXR imports - the wp-cli command adds that functionality.

Yeah. There's not much happening with the existing plugin right now either, as @rmccue is in the process of rewriting it: https://github.com/humanmade/WordPress-Importer

We could potentially solve this in WP-CLI, I think. Doing so would require a bit of technical discovery and test coverage.

**Comment by jacobischwartz** [comment]
Yessss the hard way :P

It would be a good thing to note on the command's reference page, if it's a known issue. Wordpress VIP support also spent a fair amount of time trying to help me with it.

I can see a few ways to potentially solve it in WP-CLI, but if the plugin is being rewritten then maybe it's a waste of time. Do you happen to know what kind of a timeline that has?

**Comment by danielbachhuber** [comment]
I think it would be worthwhile to fix in WP-CLI, as I don't see the problem being fixed in the importer anytime soon, or the new importer getting to a release point.

**Comment by rmccue** [comment]
> Do you happen to know what kind of a timeline that has?

Right now, it's just a side-project, so it takes a bit of a backseat to the other open source stuff (i.e. the REST API) unfortunately. Can't really offer a timeframe, sorry.

**Comment by jacobischwartz** [comment]
Ok, well it looks like the plugin might not have an issue with parsing multiple XML structures in one file. So the simplest solution might be to just concatenate all the files before passing them to the plugin. I'll test later this week and let you know if that solves it. If it works, I'm happy to write the change in the wp-cli command. Sound good?

**Comment by danielbachhuber** [comment]
> So the simplest solution might be to just concatenate all the files before passing them to the plugin.

This would defeat the purpose of parsing the files separately — memory consumption. Concatenating the files isn't the right approach.

**Comment by jacobischwartz** [comment]
Ok. Really, the only thing that needs to persist between WXR files is the processed_posts property on WP_Import. It's a pretty simple array of keyed IDs. I doubt it'd be a huge memory risk if that array were grabbed at the end of the import, stored in an Import_Command property, and merged it into subsequent importers shortly after the importer is initialized.

**Comment by danielbachhuber** [comment]
> I doubt it'd be a huge memory risk if that array were grabbed at the end of the import, stored in an Import_Command property, and merged it into subsequent importers shortly after the importer is initialized.

Oh, this is an interesting idea. If it works, this seems like a reasonable approach to me.

**Comment by jacobischwartz** [comment]
Possible implementation: https://github.com/wp-cli/wp-cli/pull/2545
