### ISSUE TITLE
wp core config puts wp-config at the wrong place

### ISSUE THREAD

**Issue by martijngastkemper** [wp-cli/wp-cli#2528]
To keep my Git repo clean and WordPress easy to update I include WordPress as a submodule. The root directy looks like this:

```
index.php
vendor
wordpress
  wp-admin
  wp-content
  wp-includes
  wp-*.php
wp-content
  plugins
  themes
```

When I run ``wp core config`` the wp-config.php file will be put inside the folder ``wordpress``. That's the wrong place, using the --path path doesn't solve the problem.

**Comment by danielbachhuber** [comment]
WP-CLI only supports generating `wp-config.php` files for standard WordPress installations because it can reliably determine where `wp-config.php` is expected to be based on `ABSPATH`.

When `wp-config.php` is expected to be outside of `ABSPATH`, WP-CLI can't know where it's expected to be placed.
