### ISSUE TITLE
wp option list returns a mangled value for permalink_structure

### ISSUE THREAD

**Issue by benoitchantre** [wp-cli/wp-cli#2529]
The returned value is `/ostname%/ ` instead of `/%postname%/ ` for the permalink_structure.

Tested with WP-CLI 0.22.0

**Comment by danielbachhuber** [comment]
This was fixed in #2458 and will be released in v0.23.0

If you need to use the fix before the release, you can update to the nightly with `wp cli update --nightly`

**Comment by benoitchantre** [comment]
Thanks!
