### ISSUE TITLE
community command not defined while calling from php

### ISSUE THREAD

**Issue by mingfyp** [wp-cli/wp-cli#2548]
I tried to run `wp super-cache flush` with php exec() and I got

`Error: 'super-cache' is not a registered wp command. See 'wp help'.`

while running the same command with the same user over ssh is fine.

**Comment by danielbachhuber** [comment]
> community command not defined while calling from php

How are you loading the community command?

If you're not yet using `wp package` ([ref](http://wp-cli.org/commands/package/)), can you try installing `wp super-cache` with it and seeing if your error continues?

You'll need to `wp cli update --nightly`, then run `wp package install wp-cli/wp-super-cache-cli`

**Comment by mingfyp** [comment]
I tried `wp package` ,  conifg, global config, all result in the same error.
here is my `wp --info` output 

> PHP binary:	/usr/local/bin/php
> PHP version:	5.5.30
> php.ini used:	/usr/local/lib/php.ini
> WP-CLI root dir:	phar://wp-cli.phar
> WP-CLI packages dir:	/home/{user}/.wp-cli/packages/
> WP-CLI global config:	/etc/wp-cli/config.yml
> WP-CLI project config:	
> WP-CLI version:	0.23.0-alpha-1116515

here is my `wp --info` output by calling from php

> PHP binary:	/usr/local/bin/php
> PHP version:	5.5.30
> php.ini used:	/usr/local/lib/php.ini
> WP-CLI root dir:	phar://wp-cli.phar
> WP-CLI packages dir:	/.wp-cli/packages/
> WP-CLI global config:
> WP-CLI project config:
> WP-CLI version:	0.23.0-alpha-1116515

**Comment by mingfyp** [comment]
and I get this when trying to uninstall the package

> Fatal error: Call to undefined function add_action() in /home/{user}/.wp-cli/packages/vendor/wp-cli/wp-super-cache-cli/wp-super-cache-cli.php on line 20

**Comment by danielbachhuber** [comment]
> here is my wp --info output by calling from php

Oh. The obvious problem is that the path to the packages directory isn't correct, and the path to your global config is missing.

For the first, WP_CLI uses the `HOME` environment variable to build the base path. I'm not sure whether that's present when using `exec()`. Can you explore?

For the second, I see your global config is a non-standard path. How are you setting that?

> and I get this when trying to uninstall the package

Sorry about that :( I've fixed the immediate problem with https://github.com/wp-cli/wp-super-cache-cli/commit/2fdbf1607a451c56cfbfb332b355d715701dd5d4

I'm also improving the load process so bad packages don't break the uninstall procedure: #2555

To fix your problem right now, though, you'll need to delete `/home/{user}/.wp-cli/packages/`
