### ISSUE TITLE
require_once() in wp-config.php not respecting --path flag

### ISSUE THREAD

**Issue by adriantoll** [wp-cli/wp-cli#2549]
I use a hosting company where the default setup has two config files:

`wp-config-hosting.php`
`wp-config.php`

`wp-config.php` uses `require_once('wp-config-hosting.php');` to get the MySQL details.

When I use `wp --path=/path/to/wordpress db export dbname.sql` I get a fatal error as the `require_once()` command ignores the `--path` flag and uses a wp-cli `$PATH` variable when searching for the required file instead.

Would it be possible for wp-cli to search the contents of the `--path` flag first when `require_once()` is called?

I currently having it working using `--require=/path/to/wordpress/wp-config-hosting.php` and by changing `require_once()` to `include()` which doesn't generate a fatal error and completes the export, but the hosting service I'm using defaults to using `require_once()`, so I'd rather it took its cue from the `--path` flag, which seems more intuitive to me too.

**Comment by danielbachhuber** [comment]
Can you try `require_once( dirname( __FILE__ ) . '/wp-config-hosting.php');` in your wp-config?

**Comment by adriantoll** [comment]
Yep, that works - I can feed that back to the hosting team to see if they'd consider changing their setup.  However, would it make sense to you (in both technical and cost / benefit terms) if any require / include functions in wp-config.php respected the `--path` flag if the strings were were relative?

**Comment by danielbachhuber** [comment]
> However, would it make sense to you (in both technical and cost / benefit terms) if any require / include functions in wp-config.php respected the --path flag if the strings were were relative?

No. You should always use absolute paths when referring to files.

For instance, unless they've done some hacking to their web server config, a request to `/wp-admin/` won't load `wp-config-hosting.php` with `require_once('wp-config-hosting.php');` because `wp-config-hosting.php` doesn't exist in the `/wp-admin/` directory.

**Comment by adriantoll** [comment]
Yep, they (Pagely) have a reasonably complex setup, and `/wp-admin/` definitely works!  I take your point about absolute paths though - I'll suggest they use that to require that file.  Thanks for the pointer.
