### ISSUE TITLE
Cannot delete hello or akismet

### ISSUE THREAD

**Issue by voltronik** [wp-cli/wp-cli#2552]
I'm using WP-CLI 0.22.0 on Mac OS X 10.11.3 in the Terminal.

Whilst in a WordPress installation root directory, using the command `wp plugin delete hello` from the terminal doesn't result in the hello.php file being deleted. `wp plugin uninstall hello` also has the same issue and no errors or messages are outputted. `--debug` doesn't reveal anything either.

If you use the `--deactivate` flag on the uninstall command, it does say `Warning: Plugin 'hello' isn't active.`, but that's all's the output I get from any of these commands. 

This is all done immediately after a fresh WordPress install using WP-CLI. 

Basic commands used to re-produce: 
wp core config
wp db create
wp core install
wp plugin uninstall hello

The only other thing I do after the `wp core install` is 'harden' the files and folders using these commands: 
```
find Build -type d -exec chmod 755 {} \;
find Build -type f -exec chmod 644 {} \;
```

But even after this, I can install and uninstall plugins without issue so it seems to be something specific to the plugins that come bundled with WordPress.

**Comment by danielbachhuber** [comment]
> wp plugin uninstall hello also has the same issue and no errors or messages are outputted.

If the plugin doesn't exist, you should see a warning:

```
salty-wordpress ➜  wordpress-test.dev  wp plugin uninstall foo
Warning: The 'foo' plugin could not be found.
```

If you aren't seeing any output, there may be a fatal occurring somewhere in the process. Are you suppressing errors at the command line?

**Comment by voltronik** [comment]
I can confirm that the plugin exists because I haven't deleted it out of a standard installation yet. 
Not suppressing errors, no. Using --debug shows some info prior to this command but nothing after.

Does either of these commands require that the plugin has been previously installed and/or activated in order to uninstall or delete? I imagine the WordPress installation process just dumps the plugin files/folders there which will allow them to display in the Plugins screen when in the WP Admin.

**Comment by sourcerer-mike** [comment]
wp 0.22.0 on Ubuntu 15.10:

    wp plugin delete hello

Works fine - the plugin exists and is gone afterwards. No problems here. This commands runs almost every day for some weeks now on our server.

**Comment by danielbachhuber** [comment]
> Does either of these commands require that the plugin has been previously installed and/or activated in order to uninstall or delete?

No.

>  I imagine the WordPress installation process just dumps the plugin files/folders there which will allow them to display in the Plugins screen when in the WP Admin.

This is correct. Can you run `wp plugin uninstall hello` and share the full output though? I'd like to verify you're seeing some output after the command is executed.

> Shows a 255 error without any messages.

This is intentional. `wp plugin delete` doesn't display an error message (which is inconsistent with `wp plugin uninstall`, I know).

**Comment by voltronik** [comment]
As the same thing is happening with Akismet, I tried using `wp plugin uninstall akismet` but I get no output at all.

**Comment by danielbachhuber** [comment]
Ok. I'm not sure what this problem is, but it seems to be specific to your system.

> The only other thing I do after the wp core install is 'harden' the files and folders using these commands:

Few more debugging questions:

* Can you share which user and group own the files and directories?
* Does uninstalling a plugin work through the WordPress admin?
* Can you try creating a new WordPress install without performing the hardening step, and see if the issue persists?

**Comment by voltronik** [comment]
In further testing, it does seem to be my 'hardening' that is causing the problem. Not sure why but it works before I do it and not after.
Interestingly, I also noticed that hello.php is distributed with WordPress but if deleted and then re-installed from the plugin repo, it's a different version - it's a folder with files in called 'hello-dolly' as opposed to a single file called 'hello.php'. This caused some confusion for a while. 

I have also noticed that if you don't deactivate a plugin before uninstalling, it seems to think it's still activated so when you try and re-install it, it thinks it's already installed. Not sure if this is an issue with WordPress or WP-CLI. Can you clarify?

**Comment by danielbachhuber** [comment]
> I have also noticed that if you don't deactivate a plugin before uninstalling, it seems to think it's still activated so when you try and re-install it, it thinks it's already installed. Not sure if this is an issue with WordPress or WP-CLI. Can you clarify?

`wp plugin delete` deletes the files in place. If you use it when a plugin is already active, then the `plugins_active` option won't be updated to remove the plugin. See http://wp-cli.org/commands/plugin/delete/

`wp plugin uninstall` won't uninstall the plugin unless the plugin has first been deactivated.

**Comment by lordspace** [comment]
I've just experienced the same problem. 
It seems the directory didn't have the right permissions.

it would have been really convenient to have some sort of an error in addition to the exit code.
