### ISSUE TITLE
Set less strict version for composer/semver

### ISSUE THREAD

**Issue by FlyingDR** [wp-cli/wp-cli#2553]
Currently this project have [very strict](https://github.com/wp-cli/wp-cli/blob/master/composer.json#L15) version restriction `1.0.0` for `composer/semver`. It prevents other projects that depends both on your project and `composer/semver` to install more recent version (current release is [1.3.0](https://github.com/composer/semver/releases)).

**Comment by danielbachhuber** [comment]
Sounds good. I'll get this fixed up shortly.
