### ISSUE TITLE
wp user list --<field>=<value> doesn't filter

### ISSUE THREAD

**Issue by cjhaas** [wp-cli/wp-cli#2557]
No matter what I pass into `--<field>` I can't get it to filter the results and looking at my query log I'm not seeing that filter hit the server either.

In my database, this should return one user but instead returns the entire user list
`wp user list --display_name=Chris`

And this I'd assume would return zero users since this email doesn't exist but it also returns the entire user list:
`wp user list --user_email=xyz@example.net`

I've tested on a couple of servers, all with WP-CLI version 0.22 and WP version 4.4:

```
PHP binary:     /usr/bin/php5
PHP version:    5.6.18-1+deb.sury.org~trusty+1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.22.0

PHP binary:     /usr/bin/php7.0
PHP version:    7.0.4-1+deb.sury.org~trusty+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.22.0

```

**Comment by danielbachhuber** [comment]
`get_users()` doesn't support `display_name` or `user_email`, see https://codex.wordpress.org/Function_Reference/get_users

[From the docs](http://wp-cli.org/commands/user/list/):

```
[--<field>=<value>]
  Control output by one or more arguments of get_users().
```

**Comment by cjhaas** [comment]
Sorry, I missed that part, I thought it was related to the returned fields. Thanks!
