### ISSUE TITLE
Possible Bug with Simple Download Monitor

### ISSUE THREAD

**Issue by rems75** [wp-cli/wp-cli#2558]
I installed wp-cli yesterday, and used it to install simple-download-monitor. 
It seemed to work (the plugin in particular also appeared in my browser). However, when I tried running it to monitor downloads on a file, I get the following error (when trying to download the file):

> WordPress database error: [Table 'bitnami_wordpress.wp_sdm_downloads' doesn't exist]
> SHOW FULL COLUMNS FROM `wp_sdm_downloads`
> 
> Error! Failed to log the download request in the database table

It seems like during the install of the plugin, wp did not create the appropriate table in the sql DB. The owner of the DB is root. I tried installing the plugin both as the usual user (wp-ironfist)  and as root. I did not solve the issue. 

My system runs PHP 5.5.9-1ubuntu4.14 (cli). I updated WordPress using wp, I'm running the 4.4.2 version. And "which wp" gives
> Access: (0744/-rwxr--r--)  Uid: ( 1000/wp-ironfist)   Gid: (   33/www-data)

**Comment by danielbachhuber** [comment]
> It seems like during the install of the plugin, wp did not create the appropriate table in the sql DB.

Huh. I tried this locally, and it appears to work for me.

Can you roll back your database, try installing and activating from the WordPress admin, and see if the tables get created?

**Comment by rems75** [comment]
Thanks for your answer!

It helped me find the problem: during a server migration, the wordpress user lost its privileges over the sql db, hence could not create any table.
