### ISSUE TITLE
Undefined index HTTP_X_FORWARDED

### ISSUE THREAD

**Issue by blindpet** [wp-cli/wp-cli#2562]
I require the lines in wp-config.php for SSL termination, wp cli complains about them

```
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
        $_SERVER['HTTPS']='on';
```

This is the error thrown by wp cli when I run it in the root of the WP installation

    Undefined index: HTTP_X_FORWARDED_PROTO in phar:///usr/bin/wp/php/WP_CLI/Runner.php(756) : eval()'d code on line 57

I still seem to be able to install plugins but that's all I've tried so far

**Comment by danielbachhuber** [comment]
> I require the lines in wp-config.php for SSL termination, wp cli complains about them

`$_SERVER` isn't populated in the CLI context. You'll need to check if the index is set:

```
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
        $_SERVER['HTTPS']='on';
```

**Comment by JDmnT** [comment]
why after almost 4 years it still an issue without any proper solution ?
why we still need to tweak wp-config.php and it didn't became a standard parameter into it ?

and even with the solution mentioned by @danielbachhuber it still not working for me
...

**Comment by wgroenewold** [comment]
I'm using this snippet @JDmnT , did you do the define as well?

https://gist.github.com/wgroenewold/68fcaaabfbf939282b1a5cddd6f636e8
