### ISSUE TITLE
Errors when using international characters in arguments

### ISSUE THREAD

**Issue by eduardoarandah** [wp-cli/wp-cli#2564]
When an argument has an international character it behaves strangely

Example:
`wp term create category 'España'`

Creates a category with empty name

**Comment by danielbachhuber** [comment]
The example you've provided seems to work fine for me:

```
salty-wordpress ➜  wordpress-develop.dev  wp term create category 'España'
Success: Created category 2.
salty-wordpress ➜  wordpress-develop.dev  wp term list category
+---------+------------------+---------------+---------------+-------------+--------+-------+
| term_id | term_taxonomy_id | name          | slug          | description | parent | count |
+---------+------------------+---------------+---------------+-------------+--------+-------+
| 2       | 2                | España        | espana        |             | 0      | 0     |
| 1       | 1                | Uncategorized | uncategorized |             | 0      | 1     |
+---------+------------------+---------------+---------------+-------------+--------+-------+
```

To verify, this is a stock install of WordPress with all plugins disabled, a default theme in use, etc.?

**Comment by eduardoarandah** [comment]
Its running on Windows 10 / cygwin

I haven't had problems with international characters with any other script.

I'll do some tests on Ubuntu



El lunes, 14 de marzo de 2016, Daniel Bachhuber <notifications@github.com>
escribió:

> The example you've provided seems to work fine for me:
>
> salty-wordpress ➜  wordpress-develop.dev  wp term create category 'España'
> Success: Created category 2.
> salty-wordpress ➜  wordpress-develop.dev  wp term list category
> +---------+------------------+---------------+---------------+-------------+--------+-------+
> | term_id | term_taxonomy_id | name          | slug          | description | parent | count |
> +---------+------------------+---------------+---------------+-------------+--------+-------+
> | 2       | 2                | España        | espana        |             | 0      | 0     |
> | 1       | 1                | Uncategorized | uncategorized |             | 0      | 1     |
> +---------+------------------+---------------+---------------+-------------+--------+-------+
>
> To verify, this is a stock install of WordPress with all plugins disabled,
> a default theme in use, etc.?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/wp-cli/wp-cli/issues/2564#issuecomment-196627036
>


-- 
Enviado desde mi móvil

**Comment by eduardoarandah** [comment]
## Result in Linux 


	stk2@h2.sinetiks.com [~/public_html/sinetiks.com]# php wp-cli.phar term create category 'España'
	Success: Created category 62.
	stk2@h2.sinetiks.com [~/public_html/sinetiks.com]# php wp-cli.phar term list category
	+---------+-----------+-----------+-----------+-------------+--------+-------+
	| term_id | term_taxo | name      | slug      | description | parent | count |
	|         | nomy_id   |           |           |             |        |       |
	+---------+-----------+-----------+-----------+-------------+--------+-------+
	| 62      | 63        | España    | espana    |             | 0      | 0     |
	+---------+-----------+-----------+-----------+-------------+--------+-------+



## Result in windows 10 / Cygwin

		eduardo@DESKTOP-BPCK5J7 /cygdrive/c/wamp/www/demo.sinetiks.com
		$ php wp-cli.phar term create category 'España'
		Success: Created category 5.

		eduardo@DESKTOP-BPCK5J7 /cygdrive/c/wamp/www/demo.sinetiks.com
		$ php wp-cli.phar term list category
		+---------+-----------+-----------+-----------+-------------+--------+-------+
		| term_id | term_taxo | name      | slug      | description | parent | count |
		|         | nomy_id   |           |           |             |        |       |
		+---------+-----------+-----------+-----------+-------------+--------+-------+
		| 5       | 5         |           | espana    |             | 0      | 0     |
		+---------+-----------+-----------+-----------+-------------+--------+-------+


## Result in windows 10 / Powershell


	PS C:\wamp\www\demo.sinetiks.com> php wp-cli.phar term create category 'España'
	Success: Created category 3.
	PS C:\wamp\www\demo.sinetiks.com> php wp-cli.phar term list category
	+---------+-----------+-----------+-----------+-------------+--------+-------+
	| term_id | term_taxo | name      | slug      | description | parent | count |
	|         | nomy_id   |           |           |             |        |       |
	+---------+-----------+-----------+-----------+-------------+--------+-------+
	| 3       | 3         |           | espana    |             | 0      | 0     |
	+---------+-----------+-----------+-----------+-------------+--------+-------+

## Result in windows 10 / Command line


	C:\wamp\www\demo.sinetiks.com>php wp-cli.phar term create category 'España'
	Success: Created category 4.

	C:\wamp\www\demo.sinetiks.com>php wp-cli.phar term list category
	+---------+-----------+-----------+-----------+-------------+--------+-------+
	| term_id | term_taxo | name      | slug      | description | parent | count |
	|         | nomy_id   |           |           |             |        |       |
	+---------+-----------+-----------+-----------+-------------+--------+-------+
	| 4       | 4         |           | espana    |             | 0      | 0     |
	+---------+-----------+-----------+-----------+-------------+--------+-------+

**Comment by danielbachhuber** [comment]
Ok, this issue seems to be specific to Windows.

WP-CLI doesn't fully support Windows. If you can track down the problem and provide a pull request, I'd be happy to consider it. Otherwise, this isn't something I'm going to spend time fixing.
