### ISSUE TITLE
Have a specific `type` for WP-CLI packages

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#2567]
I recommend having the WP-CLI packages be regrouped under a common Composer [`type`](https://getcomposer.org/doc/04-schema.md#type), like `wp-cli-package`.

In this way, you can provide a Composer plugin to define a custom installer for this type, which allows you to exert more control over the installation process (see [Setting up and using custom installers](https://getcomposer.org/doc/articles/custom-installers.md) ).

**Comment by danielbachhuber** [comment]
> I recommend having the WP-CLI packages be regrouped under a common Composer type

Does this have to be something package authors remember to do, or is it something we can enforce?

**Comment by schlessera** [comment]
This is done by the package authors, by adding the `type` key to their `composer.json`.

As an example, this is used for WordPress plugins, by setting `"type" => "wordpress-plugin"` in the plugin's `composer.json`. Together with https://github.com/composer/installers, this makes sure that plugins get installed into the `wp-content/plugins` folder instead of the `vendor` folder.

**Comment by danielbachhuber** [comment]
Cool. I think we need to do three things:

* [ ] Update the docs.
* [ ] Ensure `wp scaffold package` includes the type.
* [ ] Submit a bunch of PRs against packages in the package index.

**Comment by danielbachhuber** [comment]
🚢 🚢
