### ISSUE TITLE
Request for additional fields in plugin search --fields=

### ISSUE THREAD

**Issue by hinoue-work** [wp-cli/wp-cli#2568]
I would like to display fields that aren't available in the plugin search API.  This page,
https://developer.wordpress.org/reference/functions/plugins_api/, has a list of fields that are available.  Specifically, I'd like to get at the downloaded or active_installs fields.

Can someone explain why these fields are not available or give some guidance on how I might add support for them?

**Comment by danielbachhuber** [comment]
> Can someone explain why these fields are not available or give some guidance on how I might add support for them?

I'm not sure the `fields` param actually works in API requests. Might be a bug introduced in the WordPress.org API.

**Comment by danielbachhuber** [comment]
HTTP POST with the default request args returns all fields for me.

```
array (
  'timeout' => 15,
  'body' =>
  array (
    'action' => 'query_plugins',
    'request' => 'O:8:"stdClass":4:{s:8:"per_page";i:10;s:6:"search";s:3:"foo";s:6:"fields";a:3:{i:0;s:4:"name";i:1;s:4:"slug";i:2;s:6:"rating";}s:6:"locale";s:5:"en_US";}',
  ),
)
```

**Comment by danielbachhuber** [comment]
I've created a Meta Trac ticket: https://meta.trac.wordpress.org/ticket/1637

**Comment by hinoue-work** [comment]
Wow!  This is great.  Thanks.
