### ISSUE TITLE
wp core download fails

### ISSUE THREAD

**Issue by enoch85** [wp-cli/wp-cli#2572]
Hey!

Trying to automate my Wordpress VM and are currently coding the bash part. Problem is when it comes to wp-cli - I'm not familiar with the command, and have been trying for 2 days now to get it to work. This is the closest to install I've come: http://pastebin.com/mHGz72GG

The script can be found here:  https://github.com/enoch85/wordpress-vm/blob/master/wordpress_install.sh#L135-L191 

Running `echo $PWD` tells me that I'm in $WPATH before the wp command. 

This is the debug "script" is use now:

```
cd $WPATH
echo $PWD
sleep 5

sudo -u wordpress -i -- wp core download --force --debug --path=$WPATH

ls -l $HTML
ls -l $WPATH
sleep 5
```

I know this is an issue tracker, but either this is a bug, or I'm doing something wrong. Please help.

Thank you!

### Expected result
Wordpress should download (and install)

### Actual result
http://pastebin.com/mHGz72GG

### Server
Ubuntu 14.04.4
PHP 7
Apache 2.4
MySQL 5.6

cc @danielbachhuber

**Comment by danielbachhuber** [comment]
Did you read the warnings?

> PHP Warning:  copy(/var/www/html/wordpress//wp-mail.php): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/commands/core.php on line 188

WP-CLI doesn't have write permissions to the directory you're trying to install WordPress to.

**Comment by enoch85** [comment]
@danielbachhuber Feel like a noob now, but how do I fix that issue? --allow-root would be one afaik (not tested). But if I want to run as the 'wordpress' user, would I need to set some config then? like .xml file or similar...?

**Comment by danielbachhuber** [comment]
> Feel like a noob now, but how do I fix that issue?

You'll need to spend a bit of time learning about system file permissions.

**Comment by enoch85** [comment]
@danielbachhuber Thanks for the... help. :)

**Comment by enoch85** [comment]
www-data works :)
