### ISSUE TITLE
Stop skipping WPMS tables for site changes

### ISSUE THREAD

**Issue by DanielJLewis** [wp-cli/wp-cli#2575]
`wp search-replace` is skipping important tables for domain changes with WordPress Multisite.

For example, changing the main domain skips `wp_site`, `wp_sitemeta`, and `wp_blogs`. These tables have to be targeted manually because you can't use a wildcard to select all non-`wp_#_…` tables, or else you have to use `--network` and process every table. 

Changing a subsite's domain skips `wp_blogs` and `wp_domain_mapping`. These could be manually targeted by not using WP-CLI's site-targeting features and instead target `wp_#_* wp_blogs wp_domain_mapping`.

**Comment by danielbachhuber** [comment]
> WP-CLI is skipping important tables for domain changes with WordPress Multisite.

Sorry, just to clarify, do you mean with `wp search-replace`?

If so, `wp search-replace` gives you a few different ways to control which tables your search-replace operation is performed on ([doc](http://wp-cli.org/commands/search-replace/)). I'm not quite sure of what you're actually proposing.

**Comment by DanielJLewis** [comment]
Oops, yes. I'm talking about `wp search-replace`.

But I'm pointing out that there are these holes, despite what controls we have. Especially if you target a site with `url=`, it misses the important network-level tables (`wp_blogs` and `wp_domain_mapping`) for the search-and-replace operation.

**Comment by danielbachhuber** [comment]
> Especially if you target a site with url=, it misses the important network-level tables (wp_blogs and wp_domain_mapping) for the search-and-replace operation.

Well, right. `wp search-replace`'s default behavior is to just operate against the current site's tables. Given this, you have two options:

1. Use the `--network` flag to perform the operation across the entire network.
2. Explicitly specify the tables you'd like to search-replace against as arguments.

**Comment by DanielJLewis** [comment]
In that case, I suggest removing or editing this example from the documentation:

```
# Turn your production database into a local database
wp search-replace --url=example.com example.com example.dev wp_\*_options
```

Because this is not thorough enough to change the domain.
