### ISSUE TITLE
wp-cli v0.23.0 requires composer/composer 1.0.0-alpha11

### ISSUE THREAD

**Issue by manu09** [wp-cli/wp-cli#2582]
I set `wp-cli` as dev dependency and manage plugins with composer. I'm running the latest version `1.0-dev` a8e9df55dc62d8806360be2f79ad112b8678d397, but wp-cli isnt using [next significant release operators](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators), thus I can not install/require packages with composer. Please use the tilde operator or any other non-exact version. I don't see any reason why wp-cli requires this exact version.

```
html [master] ⚡ composer require wpackagist-plugin/custom-post-type-ui 
Using version ^1.2 for wpackagist-plugin/custom-post-type-ui
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wp-cli/wp-cli ^0.23.0 -> satisfiable by wp-cli/wp-cli[v0.23.0].
    - wp-cli/wp-cli v0.23.0 requires composer/composer 1.0.0-alpha11 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by danielbachhuber** [comment]
>  Please use the tilde operator or any other non-exact version.

Sorry about that. Changing in #2583

> I don't see any reason why wp-cli requires this exact version.

No particular reason.
