### ISSUE TITLE
@package tag is formatted incorrectly by `wp scaffold plugin`

### ISSUE THREAD

**Issue by wesm87** [wp-cli/wp-cli#2584]
For example, if I run `wp scaffold plugin test-plugin`, the following file header is generated in the main plugin file:

```
/**
 * Plugin Name: Test-plugin
 * Version: 0.1-alpha
 * Description: PLUGIN DESCRIPTION HERE
 * Author: YOUR NAME HERE
 * Author URI: YOUR SITE HERE
 * Plugin URI: PLUGIN SITE HERE
 * Text Domain: test-plugin
 * Domain Path: /languages
 * @package Test-plugin
 */
```

According to [the documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#other-tags), the `@package` tag should be capitalized and separated by underscores (e.g. `Test_Plugin`). I would also expect the Plugin Name to be `Test Plugin` rather than `Test-plugin`.

I've already made these modifications to my local install of wp-cli so I'd be happy to provide a PR.

**Comment by danielbachhuber** [comment]
> I've already made these modifications to my local install of wp-cli so I'd be happy to provide a PR.

Sure — pull requests welcome!

**Comment by wesm87** [comment]
:+1:  PR submitted ( #2588 )
