### ISSUE TITLE
Serve Package Index over https

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2585]
Composer now defaults to not permitting packages to be installed from http sources.

While this is a configurable setting we can change for the interim (8b1eff834b660e66c9047f94a7b341f7d99ec71e), we really should be serving the entire site over https.

From #2583

**Comment by gilbitron** [comment]
Have you considered using something like [CloudFlare](https://www.cloudflare.com)? It has a free plan and works with GitHub pages.

**Comment by danielbachhuber** [comment]
Oh, I totally forgot about CloudFlare. I think that'd do the trick.
