### ISSUE TITLE
wp core config - permission denied but user valid

### ISSUE THREAD

**Issue by GuerrillaCoder** [wp-cli/wp-cli#2589]
Hi,

I have already downloaded and I am running this command on ububtu (LEMP):

```
wp core config --dbname="mydbname" --dbuser="mydbuser" --dbpass="mydbpass"
```

It gives me: 

```
ERROR 1045 (28000): Access denied for user 'mydbuser'@'localhost' (using password: YES)
```

I cannot figure out why.  If I do "mysql -u mydbuser -p mydbpass" I can see the database there and I have privileges on it.

What reason would there be for access denied?

I created the wp-config.php file manually with same details and then used "wp core install ..." successfully.  It is just "wp core config" that isn't working.

**Comment by danielbachhuber** [comment]
> I have privileges on it.

Can you share all of the privileges you have?

> What reason would there be for access denied?

WP-CLI runs a null command (`;`) so, for some reason, your user doesn't have permission to execute it.

> I created the wp-config.php file manually with same details and then used "wp core install ..." successfully.

FYI - you can also use the `--skip-check` flag to skip the database check.

**Comment by lemats** [comment]
Make sure your password does **not** contain `#`.

**Comment by nathanell** [comment]
Oh my...

**Comment by toddbarnett** [comment]
The mysql password may **not** contain a `$` either. Using --skip-check as @danielbachhuber mentioned will remove the `$` and any characters after the `$` in your password.
