### ISSUE TITLE
Scaffold plugin with includes path

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#2596]
Hello, I have a little "concept" for you. Would be great to see that in your work.

`wp scaffold plugin` adds the folder "includes" and some logic to the plugin:

```
// Fetch all files
foreach ( glob( __DIR__ . '/includes/*' ) as $file_node ) {
	if ( is_dir( $file_node ) ) {
		continue;
	}

	require_once $file_node;
}
```

This follows WP Coding Standards (even the folder "includes"). Any file placed in the includes folder will be loaded automatically. This leads to a very readable structure, like:

- includes/
  - admin-no-heartbeat.php
  - cpt-bar.php
  - fix-chrome.php
  - tax-foo.php
  - ... etc ...

Please let me know if this is okay for wp-cli.

**Comment by danielbachhuber** [comment]
I think this is probably out of scope, but thanks for the suggestion
