### ISSUE TITLE
wp-cli doesn't create post only shows page source

### ISSUE THREAD

**Issue by bebablub** [wp-cli/wp-cli#2597]
Hello,

i have big trouble while running Wordpress 4.4.2 and php-cli 0.23.0

here are my specs:
sudo -u www-data -i -- /var/www/wordpress/wp-cli.phar --path='/var/www/wordpress' --info
PHP binary:	php
PHP version:	5.3.29
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/var/www/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.23.0

problem: when i'm running (posttemplate is filled):
sudo -u www-data -i -- /var/www/wordpress/wp-cli.phar --path='/var/www/wordpress' post create /var/www/runtastic_stats/gpx/posttemplate --post_category=2 --post_title='test' --post_status=publish --post_date='2016-03-27 18:00:00' --post_author=1 --post_excerpt='test' --porcelain --debug

i theres no post created, wlp-cli only returns the main page source. Theres no additional info (like a postid) returned. Debug delivers:
Debug: No readable global config found (0.011s)
Debug: No project config found (0.012s)
Debug: No package autoload found to load. (0.024s)
Debug: ABSPATH defined: /var/www/wordpress/ (0.025s)
Debug: Begin WordPress load (0.025s)
Debug: wp-config.php path: /home/www-data/wordpress/wp-config.php (0.025s)

In previous releases (sorry i don't have more specific information, around christmas time and before) this command worked like expected. Because of missing error messages i don't have any idea on whats going on...

Would be nice if anyone could help. Thank you!

**Comment by bebablub** [comment]
I'm now using PHP5 because i think it's more decent:
sudo -u www-data -i -- 'php5' '/var/www/wordpress/wp-cli.phar' --path='/var/www/wordpress' --infoPHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.14
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/var/www/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.23.0

I think i found an error message now (but with all that output it's hard to find). After typing:
sudo -u www-data -i -- php5 /var/www/wordpress/wp-cli.phar --path='/var/www/wordpress' post create /var/www/runtastic_stats/gpx/posttemplate --post_category=2 --post_title='test' --post_status=publish --post_date='2016-03-27 18:00:00' --post_author=1 --post_excerpt='test' --porcelain > test.html 

i got:
PHP Notice:  Undefined index: SERVER_PORT in phar:///home/www-data/wordpress/wp-cli.phar/php/WP_CLI/Runner.php(792) : eval()'d code on line 19

**Comment by bebablub** [comment]
The output doesn't depend on command, also:
sudo -u www-data -i -- php5 /var/www/wordpress/wp-cli.phar --path='/home/www-data/wordpress/' wp core version
fails with page source.
It's like: https://wordpress.org/support/topic/using-wp-cli-running-any-command-other-than-info-returns-html-of-site-page
But i'm running recent version of wp-cli

**Comment by danielbachhuber** [comment]
Can you try running the command with the `--skip-plugins` flag?

**Comment by bebablub** [comment]
Wow thank you! That solved my issue. My scripts are running again. So seems that theres a problem with one of the plugins in combination with wp-cli.
