### ISSUE TITLE
wp shell prompt should include newline character

### ISSUE THREAD

**Issue by JRGould** [wp-cli/wp-cli#2600]
When running `wp shell`, the output from the last command appears on the same line as the prompt

```bash
wp> echo "foo";
foowp>
```

**Comment by danielbachhuber** [comment]
Thanks for the report. 

Just for reference, here's what Python does:

```
>>> print 'foo';
foo
>>>
```

And here's what PHP does:

```
php > echo 'foo';
foo
php >
```

As such, I'd be open to changing our behavior.
