### ISSUE TITLE
Can't update WPLANG option unless core language pack is installed

### ISSUE THREAD

**Issue by fjarrett** [wp-cli/wp-cli#2602]
When updating the `WPLANG` option I received a message that wasn't exactly helpful. It took me a bit to troubleshoot and understand what was actually happening:

```
$ wp option get WPLANG
es_ES
$ wp option update WPLANG fr_FR
Success: Value passed for 'WPLANG' option is unchanged.
```

Uhhh, what? Well it turns out that this particular option will not update unless the core language pack is installed first. Once you do that, it works as you would expect:

```
$ wp option get WPLANG
es_ES
$ wp core language install fr_FR
Success: Language installed.
$ wp option update WPLANG fr_FR
Success: Updated 'WPLANG' option.
```

Either:

A. The success message needs to be changed to something more descriptive when attempting to update this option without the proper core language pack. And a `--force` flag should be made available to be able to update the option anyway w/o the language pack.

-or-

B.  The user should be allowed to update this option to be whatever the hell they want it to be without prerequisites :smile: 

I prefer B because it's the behavior you expect when manipulating option values directly from the command line.

In my use-case I was testing a plugin that _did_ have a `fr_FR` language pack - so having the core pack was irrelevant to me. IMO the option should just update and not try to get fancy.

**Comment by borekb** [comment]
I think we encountered similar issue with VersionPress and came to the conclusion that this is how WordPress behaves. @JanVoracek might remember some more details..

**Comment by danielbachhuber** [comment]
Thanks for the detailed report, Frankie.

WP-CLI's underlying implementation is to simply call `update_option()`. It doesn't have a higher-level understanding of the option being saved (expected format, what constitutes success vs failure, etc).

When WP-CLI eventually wraps a Site REST endpoint, the latter can return a more helpful error code / message for WP-CLI to display. It doesn't make sense for WP-CLI to special case this option in the interim, though.
