### ISSUE TITLE
Bash autocomplete adds trailing slash to plugin & theme names

### ISSUE THREAD

**Issue by shawnhooper** [wp-cli/wp-cli#2603]
If you're in the wp-content/themes/ or wp-content/plugins/ folder and press the TAB key to autocomplete the name of a theme or plugin folder, bash includes the slash after the end of the folder name. 

Suggest updating WP-CLI to remove trailing slashes so that this shortcut works.

**Comment by danielbachhuber** [comment]
Wontfix, see https://github.com/wp-cli/wp-cli/pull/2604#issuecomment-203071408
