### ISSUE TITLE
Target a separate database with search-replace

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#2610]
Often, part of the workflow when moving a site from one environment to another is to perform a search-replace on the database to alter the URLs scattered throughout it.

`wp search-replace` does this but affects the target database, meaning if you were, for example, moving a database from staging to live and replaced `staging.example.com` with `live.example.com` it would render the staging site inaccessible after the change.

There's an `--export` flag available on `wp search-replace` but I'm not confident that this will scale well.

It would be great if `wp search-replace` allowed you to specify a target database which would be populated with the result of the search-replace action.

That said, maybe the `--export` flag _does_ scale, and its output should just be piped into another database.

Suggestions welcome.

**Comment by danielbachhuber** [comment]
> That said, maybe the --export flag does scale, and its output should just be piped into another database.

I _think_ it scales — and if it doesn't, we should solve whatever performance problem arises. `--export` is meant just for this situation. Also, it won't cause a performance problem on the production site, as it's only performing read operations on the database.

**Comment by danielbachhuber** [comment]
@johnbillion How'd this turn out for you?
