### ISSUE TITLE
core verify-checksums shall ignore obsolete files

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#2612]
Some files are removed for good reasons but shown as problem:

```
Warning: File doesn't exist: license.txt
Warning: File doesn't exist: wp-config-sample.php
Warning: File doesn't exist: readme.html
Warning: File doesn't exist: liesmich.html
```

Those are gone to obscure information about the WP installation. How about adding an option to handle such scenario?

1. Ignore all non-existing files (meh, that makes verify checksum incomplete)
2. Ignore obsolete files (wow, hard to enlist them as it is up to different flavours)
3. comma-separated ignore list (best idea so far)

**Comment by danielbachhuber** [comment]
Why can't you just ignore the warning?

**Comment by danielbachhuber** [comment]
The point of `wp core verify-checksums` is to warn you when checksums differ than core's published manifest. I think it's expected behavior that the command does warn you when the files are missing.

**Comment by sourcerer-mike** [comment]
I really like to use this command for testing (CI) if the core has been changed by accident or other stupid reasons. By hand I can ignore them but for automation it's a bit harder.  
Unfortunately the return code is "1" no matter what the error or warning is about.

In this case some files are okay for being deleted while all other shall still be checked against the checksum.

**Comment by danielbachhuber** [comment]
Why can't you keep those files in place? There's no harm in doing so.

**Comment by sourcerer-mike** [comment]
It's to obscure information for security reasons. WPScan for example complain about those files as well as iThemes Security does. So having a bit of flexibility or multiple exit codes would be great.

**Comment by runningman84** [comment]
There is also a problem with different languages. If you install the German language pack and update the wordpress installation using the gui later, the checksum check will complain about a German sample file while other files are English. It would be really cool to have an option to exclude specific files.

**Comment by ScreamingDev** [comment]
Or a general option like `--ignore-missing-files` at all.

**Comment by LatinSuD** [comment]
> Why can't you just ignore the warning?

Because they end up in ERROR, not just a warning.

```
Warning: File doesn't verify against checksum: wp-config-sample.php
Error: WordPress installation doesn't verify against checksums.
```
