### ISSUE TITLE
Composer unable to update to ^0.23

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#2613]
Some package requires Composer 1.0.0-alpha11.

For production the stability won't be set to "dev" and kept at "stable".
So this dependency can not be resolved.

    wp-cli/wp-cli v0.23.0 requires composer/composer 1.0.0-alpha11 -> no matching package found.

Please remove the dependency to composer (1.0.0-alpha11) so that everyone can upgrade to the latest WP-CLI.

**Comment by danielbachhuber** [comment]
Composer powers the `wp package` commands, so we can't remove it as a dependency.

Can you see if #2583 resolves the stability issue?

**Comment by sourcerer-mike** [comment]
Your commit for ~1.0.0-beta still blocks an update from 0.22 to 0.23 unless the
minimum-stability is set to beta.
One step forward but still unusable for production which only wants stable releases unless composer itself is stable.

Sad for me because I really like to see my fix for the vendor-dir ;) So I need to wait for the release of composer 1.0.0

**Comment by danielbachhuber** [comment]
Keep in mind you'll need WP-CLI v0.23.0 for WordPress 4.5 compatibility, as v0.22.0 is incompatible with 4.5.

**Comment by wesm87** [comment]
@sourcerer-mike As a temporary fix you can add the following line to your `composer.json`:

`"composer/composer": "~1.0.0@dev"`

Basically what that does is set the minimum stability to "dev" for Composer, while still using "stable" for all your other packages.

**Comment by sourcerer-mike** [comment]
Thanks @wesm87 . Or "composer/composer:1.0.0-alpha11" as wp-cli is using this particular release.
That's what I did yesterday. It doesn't feel good but solves it until composer has some final release.

**Comment by borekb** [comment]
Same problem here, if you're looking for a confirmation of the issue. It's already fixed in `master`.

**Comment by danielbachhuber** [comment]
@borekb do you suggest any action at this point?

**Comment by borekb** [comment]
0.23.1 release? I'm not sure how these things are supposed to be handled.

**Comment by danielbachhuber** [comment]
Oh, but tagging a v0.23.1 release won't actually fix the following problem until Composer tags a 1.0.0 release, right?

> Your commit for ~1.0.0-beta still blocks an update from 0.22 to 0.23 unless the
minimum-stability is set to beta.

**Comment by wesm87** [comment]
@danielbachhuber Yeah I don't think there's anything you can do on your end until a stable version of Composer is released. Composer uses the `minimum-stability` setting for any packages that you install, as well as any dependencies those packages try to install. [This article](https://igor.io/2013/02/07/composer-stability-flags.html) outlines the problem pretty well. The default value is `stable` so anyone who doesn't specify a minimum stability of `beta` or lower will run into this issue trying to install WP-CLI.

For anyone who's having this issue, there are two different ways you can get around it:

1 - Manually specify the minimum stability for Composer as I mentioned in my previous comment. You can use `@dev`, `@alpha`, or `@beta` (`dev` includes both `alpha` and `beta`).

2 - Change your minimum stability to `beta` and then add `"prefer-stable": true` in the root of your `composer.json`, like so:
```json
"minimum-stability": "beta",
"prefer-stable": true
```

**Comment by danielbachhuber** [comment]
Thanks @wesm87 - I appreciate you taking the time to communicate all of the details.

**Comment by borekb** [comment]
`master` worked for me because I already had `"minimum-stability": "beta"` in composer.json, sorry.
