### ISSUE TITLE
Add `--config_path` parameter to `wp core install`

### ISSUE THREAD

**Issue by davetgreen** [wp-cli/wp-cli#2615]
It would be useful to have a parameter for explicitly declaring the path to the `wp-config.php` you'd like to use during the installation. 

In our development boilerplate we have `wp-content` outside of WP, using composer to add WP core to the project. This structure is not uncommon in WP development agencies. Our structure looks like this:

```
build/
   wordpress
   wp-content
   .htaccess
   index.php
   local-config.php
   robots.txt
   wp-config.php
```
In this case, `wp core install` -- which we're running in Vagrant's `vvv-init.sh` script will fail because the `wp-config.php` resides outside of this directory. 

If we could tell wp-cli to actually use the DB details in an alternative config file that would be fantastic.

**Comment by danielbachhuber** [comment]
Can you share the full output of the installation script failure? WP-CLI is compatible with storing wp-config.php outside of the WordPress directory, so there might be some other issue at play

**Comment by davetgreen** [comment]
hey @danielbachhuber 

I'll be honest, up until now when I've seen the failure in the Vagrant log, I've always just assumed it was because of our set-up. It dawned on me this morning that we weren't supplying the --path parameter to point it to `build/wordpress` in the above structure.

So, having tried that, I'm getting the following error:

`Fatal error: Class 'WP_Widget' not found in /Users/davetgreen/Vagrant/www/bloom-design/build/wordpress/wp-includes/widgets/class-wp-widget-pages.php`

A quick Google turned up a suggestion to upgrade WP-CLI itself, which I've done. Everything now works perfectly.

Hopefully this will be of use to anyone reading this issue. Apologies for wasting your time. :)

**Comment by danielbachhuber** [comment]
No worries, glad you've figured it out!
