### ISSUE TITLE
Document WP-CLI bootstrap process

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2617]
For those who are new to the internals of WP-CLI, it would be helpful to have documentation of `wp-settings-cli.php` and the bootstrap process generally.

We have http://wp-cli.org/docs/implementation-details/#wpadmin, but it's not very detailed.

**Comment by holsta** [comment]
As part of building a Wordpress setup more resistant to attack, I am investigating wp-cli and came across this situation where the command runs fine, exits with 0:

```
$ php-5.6 wp-cli.phar --info
$ echo $?
0
```

Looking at the process trace, I get this alert before the program exits:

```
 5959 php-5.6  GIO   fd 3 wrote 187 bytes
       "<9>suhosin[5959]: ALERT - Include filename ('phar://wp-cli.phar/php/boot-phar.php') is a U\
        RL that is not allowed (attacker 'REMOTE_ADDR not set', file '/home/holsta/wp-cli.phar', l\
        ine 4)
       "
  5959 php-5.6  RET   sendto 187/0xbb
```

Is there anything in the coming documentation that would help my situation?
