### ISSUE TITLE
During large imports, 1000 post batches, wp-cli import hangs for minutes

### ISSUE THREAD

**Issue by Jaace** [wp-cli/wp-cli#2619]
I'm not sure if this is an environmental issue or an issue with wp-cli import itself, or if this is expected behavior, but I'm experiencing very large amounts of time between 1000 post batches when importing WXR files.

I've checked top and mysql seems to be the issue there. The batches process at a speed I would expect but once it hits the last post in batch, it hangs for many minutes before finally reporting "Success: Finished importing from..."

When I run a top, I see that mysql during this hanging time is taking up 99% of CPU. I can provide more info if necessary, just let me know what's needed.

**Comment by danielbachhuber** [comment]
It's expected behavior. After all posts have been imported, the importer [runs three backfill processes](https://plugins.trac.wordpress.org/browser/wordpress-importer/trunk/wordpress-importer.php#L117) which can be time consuming and computationally expensive.

**Comment by cristianuibar** [comment]
This issue is so counterintuitive. WP should display some progress or debugging info. We were left wondering what is going on and why it needs 8 hours for an import to complete.

**Comment by swissspidy** [comment]
If you need a modern importer, try something like https://github.com/humanmade/WordPress-Importer

**Comment by cristianuibar** [comment]
Thanks @swissspidy . I'll try that.

I have added some logs to see where the bottleneck is and I can see that the problem is in the `backfill_attachment_urls` function.

The 2 queries that are running there are running very slowly.

In my case for each pass through that foreach loop, it takes about 1 minute for that 2 queries to run.

```php
			// remap urls in post_content
			$wpdb->query( $wpdb->prepare( "UPDATE {$wpdb->posts} SET post_content = REPLACE(post_content, %s, %s)", $from_url, $to_url ) );
			// remap enclosure urls
			$result = $wpdb->query( $wpdb->prepare( "UPDATE {$wpdb->postmeta} SET meta_value = REPLACE(meta_value, %s, %s) WHERE meta_key='enclosure'", $from_url, $to_url ) );
```

What do you think, is it safe for me to disable this function and simply run a `wp search-replace` after all import is complete?

**Comment by swissspidy** [comment]
You can certainly give it a try, but I am personally not familiar with the whole backfilling logic there to make an informed recommendation.

**Comment by iamkingsleyf** [comment]
> If you need a modern importer, try something like https://github.com/humanmade/WordPress-Importer

This has not been updated for years I doubt it still works in 2023/2024.

**Comment by iamkingsleyf** [comment]
> Thanks @swissspidy . I'll try that.
> 
> I have added some logs to see where the bottleneck is and I can see that the problem is in the `backfill_attachment_urls` function.
> 
> The 2 queries that are running there are running very slowly.
> 
> In my case for each pass through that foreach loop, it takes about 1 minute for that 2 queries to run.
> 
> ```
> 			// remap urls in post_content
> 			$wpdb->query( $wpdb->prepare( "UPDATE {$wpdb->posts} SET post_content = REPLACE(post_content, %s, %s)", $from_url, $to_url ) );
> 			// remap enclosure urls
> 			$result = $wpdb->query( $wpdb->prepare( "UPDATE {$wpdb->postmeta} SET meta_value = REPLACE(meta_value, %s, %s) WHERE meta_key='enclosure'", $from_url, $to_url ) );
> ```
> 
> What do you think, is it safe for me to disable this function and simply run a `wp search-replace` after all import is complete?

Please, are you able to solve this? keep having this problem, it hangs after importing and then timeouts... I have increased timeout on SSH + Putty yet no solution.

Once the importing items are above 2000 it won't be show a SUCCESS message.

**Comment by iamkingsleyf** [comment]
> It‘s really a flaw in WordPress / the importer plugin, not WP-CLI. Use one of the workarounds above.

Importing via XML by AUTHORS less post per author than category method.
