### ISSUE TITLE
Plugin installation should not trigger translation update

### ISSUE THREAD

**Issue by 2ndkauboy** [wp-cli/wp-cli#2626]
I installed a plugin through the CLI today and after the successful installation the CLI also updated the translations for some plugins. Although I am very pro auto-update, I think that many developers would not expect this to happen. So you might want to block the auto-update. Or at least add a attribut to skip it.

**Comment by danielbachhuber** [comment]
Can you share `wp --info` ? I thought I had disabled this behavior in #2439

**Comment by 2ndkauboy** [comment]
It's version 0.22.0, so if you fixed it in the newest release, it might be OK.

**Comment by 2ndkauboy** [comment]
OK, it seems that with 0.23.0 everything is fine. Sorry for reporting the same issue again, but I haven't found it.

**Comment by danielbachhuber** [comment]
:+1:
