### ISSUE TITLE
Installing plugin raises PHP Notice (error_reporting E_ALL)

### ISSUE THREAD

**Issue by bronylexx** [wp-cli/wp-cli#2627]
> What were you doing

wp --allow-root plugin install ahn-feedsyndicate-news-content-plugin

> What you expect to see

Installation of aforementioned plugin

> What you actually saw

Plugin was installed however, the following notice was raised (error_reporting E_ALL):

```
wordpress_1 | PHP Notice:  Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124
wordpress_1 | PHP Stack trace:
wordpress_1 | PHP   1. {main}() /usr/local/bin/wp:0
wordpress_1 | PHP   2. include() /usr/local/bin/wp:4
wordpress_1 | PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:5
wordpress_1 | PHP   4. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/wp-cli.php:21
wordpress_1 | PHP   5. WP_CLI\Runner->_run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:757
wordpress_1 | PHP   6. WP_CLI\Runner->run_command() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:334
wordpress_1 | PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:327
wordpress_1 | PHP   8. WP_CLI\Dispatcher\Subcommand->validate_args() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:342
wordpress_1 | PHP   9. WP_CLI\DocParser->get_arg_args() phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:261
wordpress_1 | Installing FeedSyndicate Full Text News Article Importer (3.6.9.1)
wordpress_1 | Downloading install package from https://downloads.wordpress.org/plugin/ahn-feedsyndicate-news-content-plugin.zip...
wordpress_1 | Unpacking the package...
wordpress_1 | Installing the plugin...
wordpress_1 | Plugin installed successfully.
```

> What is your system?

Linux 1e6d3716709f 4.1.19-boot2docker #1 SMP Mon Mar 7 17:44:33 UTC 2016 x86_64 GNU/Linux

> Which version of PHP are you using?

PHP 7.0.4 (cli) (built: Mar 19 2016 00:29:51) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Retinas

> Are you running suhosin?

No

> Which version of WordPress are you using?

4.4.2

> Can you share the results of which wp ?

/usr/local/bin/wp

**Comment by danielbachhuber** [comment]
Thanks for the awesome report :) I have a pretty good sense of the issue, but not 100% sure of the source.

Do you have any packages installed?

**Comment by dsifford** [comment]
Thanks for the fix @danielbachhuber 

Any idea on when this newer version will make it to the install url listed on [this page](http://wp-cli.org/#install).

The url => `https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar`

Still seem to be getting the last version.

Thanks! 👍

**Comment by danielbachhuber** [comment]
> Any idea on when this newer version will make it to the install url listed on this page.

I don't have a date identified for the next release (v0.24.0), in which this fix will be included.

You can use `wp cli update --nightly` to use the latest nightly build in your development environment, though.

**Comment by karellm** [comment]
@danielbachhuber If it was fixed can you please release it? We use wp-cli in a docker image and it feels counter productive to modify the image to address that issue when it was already fixed. Thanks a lot!

**Comment by danielbachhuber** [comment]
> If it was fixed can you please release it?

v0.24.0 was [released today](http://wp-cli.org/blog/version-0.24.0.html)
