### ISSUE TITLE
path/to/file appended to URL

### ISSUE THREAD

**Issue by gbcxjoe** [wp-cli/wp-cli#2632]
when creating a new WordPress site the /path/to/directory/ to the user's public_html directory is appended to the sites url in the WordPress options db.

for example the url of the site is http://www.mysite.com . the path to user's public_html directory is /home/mysite/public_html

when wp-cli wrote to the database the URL comes out like this: 

http://www.mysite.comhome/mysite/public_html

have you ever seen this happen? do you know what the issue is and how to fix?

Using 
version 0.23.0
ubuntu 14.04

**Comment by x2764tech** [comment]
Can you say what commands you ran?

**Comment by gbcxjoe** [comment]
variables are entered on the command line and passed to the following. i tried it with and without --path=$SITEPATH



# download Wordpress core
sudo -u $username /wp core download

# create wp-config.php file
sudo -u $username /wp core config --dbuser=$SQLUSER --dbname=$SQLDBNAME --dbpass=$SQLPASS --dbhost=$SQLHOST --dbprefix=$SQLPREFIX

# Wordpress install
sudo -u $username /wp core install --url=$SITEURL --title="$SITETITLE" --admin_user=$ADMINUSER --admin_password=$ADMINPASS --admin_email=$ADMINEMAIL --path=$SITEPATH


Thanks

**Comment by x2764tech** [comment]
Thanks - what are the values of the variables?

**Comment by danielbachhuber** [comment]
Potentially related

* https://github.com/wp-cli/wp-cli/issues/2168#issuecomment-150260737
* https://github.com/wp-cli/wp-cli/issues/858#issuecomment-36811681

**Comment by gbcxjoe** [comment]
I moved the $sitepath to the bottom of the script and got the same results

-----------------------------------------

SQLHOST="localhost"
SQLUSER="$username"
SQLPASS="$dbpw"
SQLDBNAME="$username"
SQLPREFIX=`</dev/urandom tr -dc '12345abcdefghijaklanopqrstuvwxyz' | head -c4; echo "_"`
echo Enter Site URL i.e. http://dev.yoursite.com
read SITEURL
echo the title of the WordPress site i.e. My Big Blog
read SITETITLE
echo Enter WordPress admin user account login name
read ADMINUSER
ADMINPASS=`</dev/urandom tr -dc '12345qwertQWERTasdfgASDFGzxcvbZXCVB' | head -c8; echo ""`
echo enter WordPress admin user account email
read ADMINEMAIL

SITEPATH="/home/$username/public_html"
cd $SITEPATH

**Comment by lukapaunovic** [comment]
This isn't fixed

**Comment by schlessera** [comment]
@lukapaunovic Can you be more specific? What exactly are you doing and what is the result?
And more importantly, are you setting the `WPSITEURL` setting in your `wp-config.php` file?

**Comment by lukapaunovic** [comment]
This is the script I wrote

https://gist.githubusercontent.com/lukapaunovic/3a8f59f80c8f0ecb15e572a2781b23ae/raw/6ae0643aa570d15adf38c47514d1ac820435347d/create_wp.sh

`sudo -H -u$user /home/$user/wp core install --url="$domain" --title="Moj Wordpress" --admin_user="admin" --admin_password="$password" --admin_email="webmaster@$domain" --path=$WORKINGDIR`

Even though example.com is specified.
The wordpress for some reasons sets url like

`www.example.com/web/public_html
`
And then I need to

`mysql -u$DBUSER -p$PASSWDDB -e "USE $DBUSER; update wp_options set option_value = 'http://www.$domain' where option_name = 'siteurl';update wp_options set option_value = 'http://www.$domain' where option_name = 'home';"`
