### ISSUE TITLE
modify wp-config.php is causing errors

### ISSUE THREAD

**Issue by gbcxjoe** [wp-cli/wp-cli#2633]
HI

i have tried to modify wp-config.php, want to add some security to WP and set up a varnish server

when i add this line anywhere to wp-config.php

define(VHP_VARNISH_IP,124.140.78.130);

when running the user create command
/wp user create joe joe@joe.com --send-email --role=administrator --allow-root

I get this error

PHP Parse error:  syntax error, unexpected '.78' (T_DNUMBER) in phar:///wp/php/WP_CLI/Runner.php(792) : eval()'d code on line 46
Error: Error establishing a database connection

when i remove 
define(VHP_VARNISH_IP,124.140.78.130);

it works fine, but it does not send the new user and email

Using 
version 0.23.0
ubuntu 14.04

Thanks

**Comment by x2764tech** [comment]
What you've put isn't valid PHP

try:

`define( 'VHP_VARNISH_IP' , '124.140.78.130' );` 

(note the quote marks, which make the values into strings)

**Comment by gbcxjoe** [comment]
Perfect! that worked
