### ISSUE TITLE
Extended inserts

### ISSUE THREAD

**Issue by Benno007** [wp-cli/wp-cli#2634]
Is it possible to use WP-CLI and make it write the database with extended insert statements in the search-replace function? Our database is about 80mb and has about 70,000 records and extended inserts make it 10x quicker.

E.G.
INSERT INTO table (columns) VALUES (value), (value), (value) etc.

I can see where to do it in write_sql_row_fields and php_export_table in search-replace.php but not sure how to then get that being used by the wp command?

**Comment by danielbachhuber** [comment]
> Is it possible to use WP-CLI and make it write the database with extended insert statements in the search-replace function?

It could be possible.

> Our database is about 80mb and has about 70,000 records and extended inserts make it 10x quicker.

Can you share how you profiled the performance, and the specific benchmark numbers?

**Comment by danielbachhuber** [comment]
@Benno007 I'd still be interested to see your performance numbers on this, so we have it as a standard for comparison.

**Comment by Benno007** [comment]
Hi @danielbachhuber , sorry I didn't get back to you. I got pulled onto another project at work.
I'm not too sure how to get solid metrics from the database, but what I can do on Monday is export our DB manually with extended inserts and run import it via command line - it'll show the time taken, and then I can show the time taken to import the file outputted by WP-CLI.

Our DBA said that he thinks its a disk I/O issue between using extended inserts or single inserts, because the number of inserts (~45,000) in the wp-cli export, vs ~1500 extended insert statements has a time difference or approx 30 mins on our databases. 

I'll set aside some time Monday or even perhaps over the weekend if I get time to get those stats for you. It would be really beneficial for us to have it as extended inserts, because we have issues where the DB import dies because someone/thing loads wordpress up after a DROP TABLE, before it inserts all the wp_option rows and creates some default options (so we get a uniqueness error about 20mins into the import each time). I was going to try and also wrap the insert statements in a LOCK TABLE `tablename`; but not sure how to do that with bash/sed.

**Comment by Benno007** [comment]
Note: since I originally posted this issue we managed to reduce the DB size by about 30mb, so its faster than originally noted, but still quite slow.

Run 1 (extended inserts, exported from MySQL Workbench):
Export size 31,320KB
Insert statements: 41
Time Taken: 19 seconds

10:03:59 Restoring C:\Apps\xampp\htdocs\Dump20160516\out.sql
Running: mysql.exe < "C:\\Apps\\xampp\\htdocs\\Dump20160516\\out.sql"
10:04:18 Import of C:\Apps\xampp\htdocs\Dump20160516\out.sql has finished

Run 2: WP-CLI
Export size: 38724KB
Insert Statements: 109,158
Time Taken: 17mins 20 seconds
05-May-2016 16:02:09	Importing Database: mysql  dbName < /home/deploy/dbName.sql
05-May-2016 16:19:29	Import Successful

**Comment by danielbachhuber** [comment]
🚢
