### ISSUE TITLE
Add db size command

### ISSUE THREAD

**Issue by petenelson** [wp-cli/wp-cli#2636]
Was chatting with someone at WooConf that frequently does site migrations and they mentioned that it would be handy to have the ability to get the database size, as well as the table sizes, from the CLI.  

Something like this...
``
function size( $positional_args, $assoc_args = array() ) {

	global $wpdb;

	$size = $wpdb->get_var( $wpdb->prepare( "SELECT SUM(data_length + index_length) FROM information_schema.TABLES where table_schema = '%s' GROUP BY table_schema;", DB_NAME ) );

	\WP_CLI::Success( sprintf( "Database %s is %s", DB_NAME, size_format( $size ) ) );

}

vagrant@vvv:/srv/www/wordpress-default$ wp db-size
Success: Database wordpress-default is 344 MB
```

Tables would need to be handled different, maybe with a --sizes parameter since it defaults to just the table names.

If this sounds useful, I can start working on a pull request for them.

**Comment by danielbachhuber** [comment]
I think this is a great candidate for a community package :) Want to put one together? 

[Here's the full cookbook](http://wp-cli.org/docs/commands-cookbook/) on creating standalone commands, including [how to add one to the package index](http://wp-cli.org/docs/commands-cookbook/#add-to-the-package-index). Let me know if you end up with any questions after reviewing the documentation (and if there are improvements we could make to the documentation).
