### ISSUE TITLE
WP-CLI removes $_SERVER

### ISSUE THREAD

**Issue by JakeHenshall** [wp-cli/wp-cli#2637]
Hi,

I have seemed to some across an issue which remove $_SERVER from the extra php command.

        function configWP {
          cd $WPINSTALLDIR
          wp core config --dbhost=$DBHOSTNAME --dbname=$DBNAME --dbuser=$DBUSER --dbpass=$DBPASS --dbprefix=$DBPREFIX --extra-php <<PHP
        define( 'WP_CONTENT_DIR', ABSPATH . '/content' );
        define( 'WP_CONTENT_URL', 'http' . (!empty($_SERVER['HTTPS']) ? 's' : '') . '://' . $_SERVER["SERVER_NAME"] . '/content');
        define( 'WP_DEBUG', true );
        define( 'AUTOSAVE_INTERVAL', 160 );
        define( 'WP_POST_REVISIONS', 3 );
        define( 'FS_METHOD', 'direct' );
        define( 'WPMU_PLUGIN_DIR', __DIR__ . '/wp-content/mu-plugins' );
        define( 'WPCF7_LOAD_JS', false );
        define( 'WPCF7_LOAD_CSS', false );
        PHP
          wp db create $DBNAME

          if [ ! -f "wp-config.php" ]; then

            echo "Looks like something went wrong"
            exit

          fi
        }

The line in question is:

define( 'WP_CONTENT_URL', 'http' . (!empty($_SERVER['HTTPS']) ? 's' : '') . '://' . $_SERVER["SERVER_NAME"] . '/content');

wp-cli makes the link like this ->

define( 'WP_CONTENT_URL', 'http' . (!empty(['HTTPS']) ? 's' : '') . '://' . ["SERVER_NAME"] . '/content');

is there any workaround for this.

Jake.

**Comment by voldemortensen** [comment]
Even though $_SERVER is in an PHP block, bash is trying to interpret $_SERVER as a bash variable. You need to escape the dollar signs with a backslash.
