### ISSUE TITLE
IDs passed via $() being treated as a string instead of an array

### ISSUE THREAD

**Issue by petenelson** [wp-cli/wp-cli#2643]
While working on one of my plugins, I needed to cleanup some data, so I used: 

```wp post delete $(wp post list --post_type='wp-rest-ap-log' --format=ids)``` 

to delete all the posts, but I found it was only deleting the first post.  After putting some var_dumps() inside my local install of wp-cli, it looks like IDs passed in via this method were getting treated as a string rather than array.  Typing all the IDs out worked correctly though.

Did some more digging and it's only doing this on my vagrant box.  Tried it on my hosted Digital Ocean box and it works correctly, so I'm not exactly sure if it's something in bash or what.  Both are Ubuntu, same versions of bash, so it was kind of puzzling.  

Not sure if this is fixable, or even worth fixing, but wanted to pass as it might be handy to make a note of this in the docs.  Here's a screenshot replicating the issue I saw:

![image](https://cloud.githubusercontent.com/assets/1757075/14412819/9f20ca18-ff30-11e5-94f7-e5d144a7d44f.png)

**Comment by danielbachhuber** [comment]
@szepeviktor Know what this might be? I recall another thread reporting a similar problem, but my search foo is failing me.

**Comment by szepeviktor** [comment]
@petenelson Could you share `echo $BASH $BASH_VERSION` ?
I noticed two wp-cli-s: ./bin/wp and wp
You may find wp-cli by `which -a wp`

In Bash `$(...)` output could give *one* string only when it is enclosed in quotes `"$(echo one string)"`

Please run the first wp-cli command by this shell script called dump-my-args.sh

```bash
#!/bin/bash

echo "1:'$1' 2:'$2' 3:'$3' 4:'$4' 5:'$5' 6:'$6' 7:'$7' 8:'$8' 9:'$9'"
```

`dump-my-args.sh ./bin/wp post ... ...`
Please also share its output.
Thank you.

**Comment by petenelson** [comment]
I had contributed some code to this repo recently, so I was using my local 0.24.0-alpha install with some var_dump() statements to debug it, hence the ./bin/wp calls, but I had first encountered it with the 0.23.0 version in /usr/local/bin/wp

Tonight though, I can't recreate the issue and I wonder if it's simply a case of "have you tried turning it off and back on again?"  I had been on this vagrant box a couple days working on some plugins, shut it down this morning, then fired it back up this evening and it's working correctly.  Might be that either logging out or restarting it cleared whatever issue was happening in bash.

Here's 0.24.0-alpha working correctly.  I think the only other bash command-line work I had been doing was unit tests via some grunt tasks, so I think you can close this issue.  If I can consistently recreate the scenario, then I'll make sure it's repeatable before opening a new ticket.

```
vagrant@vvv:/srv/www/wp-baconipsum/wp-content/plugins/wp-rest-api-log$ echo $BASH $BASH_VERSION
/bin/bash 4.3.11(1)-release
vagrant@vvv:/srv/www/wp-baconipsum/wp-content/plugins/wp-cli$ ./bin/wp --info
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.14
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	/srv/www/wp-baconipsum/wp-content/plugins/wp-cli
WP-CLI packages dir:	/home/vagrant/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.24.0-alpha
vagrant@vvv:/srv/www/wp-baconipsum/wp-content/plugins/wp-cli$ ./bin/wp post list --post_status=draft
+----+------------+-----------+-----------+-------------+
| ID | post_title | post_name | post_date | post_status |
+----+------------+-----------+-----------+-------------+
+----+------------+-----------+-----------+-------------+
vagrant@vvv:/srv/www/wp-baconipsum/wp-content/plugins/wp-cli$ ./bin/wp post generate --count=3 --post_status=draft
Generating posts  100% [================================================================================================================================================] 0:00 / 0:00
vagrant@vvv:/srv/www/wp-baconipsum/wp-content/plugins/wp-cli$ ./bin/wp post list --post_status=draft --format=ids
5621 5620 5619vagrant@vvv:/srv/www/wp-baconipsum/wp-content/plugins/wp-cli$ ./bin/wp post delete $(./bin/wp post list --post_status=draft --format=ids)
Success: Trashed post 5621.
Success: Trashed post 5620.
Success: Trashed post 5619.
```

**Comment by danielbachhuber** [comment]
> If I can consistently recreate the scenario, then I'll make sure it's repeatable before opening a new ticket.

Sounds good. I'm pretty sure this has come up in the past, so it would be good to have documentation around it at the very least.
