### ISSUE TITLE
Auto-install plugins when activating a theme

### ISSUE THREAD

**Issue by fred974** [wp-cli/wp-cli#2646]
I have created a shell script that automatically install wordpress for me. Part of the script, I install all the core plugin that I use on all my site and finally my flatsome theme.
The theme required some pluggin to be installed in order to function correctly. 
Is there a command in wp-cli that I can use to automatically install all the theme required pluggin when the theme is actiavted?
`wp theme install ./data/flatsome.zip --activate`

Thank you
Fred

**Comment by danielbachhuber** [comment]
> Is there a command in wp-cli that I can use to automatically install all the theme required pluggin when the theme is actiavted?

There isn't, per se, but you can hook into an existing WordPress action, `switch_theme`. Here's an example of how you might install the Jetpack plugin after activating the P2 theme: https://gist.github.com/danielbachhuber/cc8be5468d4a28a477f6d59620aeb405
