### ISSUE TITLE
wp-cli doesn't use alternate database classes for 'db cli'

### ISSUE THREAD

**Issue by dsXLII** [wp-cli/wp-cli#2649]
Most of my production sites use the HyperDB plugin, to connect to multiple replicated database backends. For most features, this works just fine. Pretty much everything I want to do works as expected, with commands hitting one of my multiple database back-ends in accord with the db-config.php I created for HyperDB.

Unfortunately, the 'wp db cli' command does not work. I assume that, internally, it just prepares a shell exec to the mysql command-line utility, pulling the DB_HOST from wp-config.php, or something like that. Since DB_HOST is either not defined, or is set to an intentionally bogus value, this means I cannot use the 'db cli' command.

    [davsmi@wuis7827 site.name.here]$ wp db cli
    ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory")

It may not be possible to make this work, but it might be useful to at least show a more informative error message if the WordPress database class has been overridden.

**Comment by danielbachhuber** [comment]
> Since DB_HOST is either not defined, or is set to an intentionally bogus value, this means I cannot use the 'db cli' command.

You can set `DB_HOST` to the primary master if you want `wp db cli` to work. If the constant is undefined, then you'll see a PHP notice. I'm not sure what you gain by setting it to an intentionally bogus value.

**Comment by dsXLII** [comment]
In the event that the site gets moved/copied to an environment that doesn't have my HyperDB configuration, it would fall back to the configuration in wp-config.php. My goal is to minimize the chance that such a fallback causes problems (by, say, having a test site pointing to the production database). But I freely admit my use case is probably very limited.
