### ISSUE TITLE
Suppress Warnings or Change Message for "wp plugin deactivate --all"

### ISSUE THREAD

**Issue by mrwweb** [wp-cli/wp-cli#2652]
When I run into a bug and want to see if it's plugin-specific, I often run `wp plugin deactivate --all`.

The resulting listing includes a mix of `Warning: Plugin 'plugin-slug' isn't active.` and `Success: Plugin 'another-plugin' deactivated.`

The word "Warning" feels wrong here and I'd suggest either supressing the message entire or change it to "Notice:" or "Info:".

I don't know if there's a underlying status message philosophy that dictates this wording (if so, so be it), but in the case of the `--all` flag + `deactivate`, I'm perfectly aware that some plugins won't get deactivated since they already are inactive. (I guess it's a question of whether `wp plugin deactivate --all` is primarily a command (it is) or the desired result (also that).)

**Comment by danielbachhuber** [comment]
I think this is a bug, actually. We shouldn't be trying to deactivate plugins that aren't active in the first place.
