### ISSUE TITLE
Fatal error when working with menus in WP 4.5

### ISSUE THREAD

**Issue by eriktorsner** [wp-cli/wp-cli#2653]
Working with menus in WordPress 4.5 ends with a PHP fatal error. I've got a lot of wp-cli automation with fairly solid unit test and I'm as certain as can be that this issue surfaced with WP 4.5.

Steps to reproduce:
`$ wp --path=www/wordpress-test core version
4.5

$ wp --path=www/wordpress-test core verify-checksums
Success: WordPress install verifies against checksums.

$ wp --path=www/wordpress-test menu create foobar
Success: Created menu 3.

$ wp --path=www/wordpress-test menu item add-post foobar 1
Success: Menu item added.

$ wp --path=www/wordpress-test menu item list foobar
PHP Fatal error:  Class 'WP_Metadata_Lazyloader' not found in /vagrant/www/wordpress-test/wp-includes/meta.php on line 865
`

**Comment by eriktorsner** [comment]
Adding a line to load class-wp-metadata-lazyloader.php at the top of add_or_update_item() in wp-cli/php/commands/menu.php seem to fix the issue, at line 503:

	/**
	 * Worker method to create new items or update existing ones
	 */
	private function add_or_update_item( $method, $type, $args, $assoc_args ) {

		require_once( ABSPATH . WPINC . '/class-wp-metadata-lazyloader.php' );


I'm getting started with a pull-request, just need to read up on the contribution guidelines.

**Comment by danielbachhuber** [comment]
Can you share `wp --info`?

**Comment by eriktorsner** [comment]
In the environment where I found the issue:

vagrant@bootstrap:/vagrant$ wp --info
PHP binary: /usr/bin/php5
PHP version: 5.5.9-1ubuntu4.14
php.ini used: /etc/php5/cli/php.ini
WP-CLI root dir: /vagrant/vendor/wp-cli/wp-cli
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.22.0

(installed via composer)

/Erik



On Wed, Apr 13, 2016 at 12:22 PM, Daniel Bachhuber <notifications@github.com
> wrote:

> Can you share wp --info?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/wp-cli/wp-cli/issues/2653#issuecomment-209356362>
>



-- 
/Erik Torsner
Tel: 0733-118503
Skype: eriktorsner

**Comment by eriktorsner** [comment]
Hi Daniel.

I should probably redo that pull request because wpcli needs to work on
previous WP versions as well. Terribly sorry.

Obviously I'm not very experienced or comfortable working in the wp-cli
code base. Please advice if you prefer I rewrite the patch or if you prefer
to go ahead fixing this without my help.

/Erik


On Wed, Apr 13, 2016 at 12:24 PM, Erik Torsner <erik@torgesta.com> wrote:

> In the environment where I found the issue:
>
> vagrant@bootstrap:/vagrant$ wp --info
> PHP binary: /usr/bin/php5
> PHP version: 5.5.9-1ubuntu4.14
> php.ini used: /etc/php5/cli/php.ini
> WP-CLI root dir: /vagrant/vendor/wp-cli/wp-cli
> WP-CLI global config:
> WP-CLI project config:
> WP-CLI version: 0.22.0
>
> (installed via composer)
>
> /Erik
>
>
>
> On Wed, Apr 13, 2016 at 12:22 PM, Daniel Bachhuber <
> notifications@github.com> wrote:
>
>> Can you share wp --info?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wp-cli/wp-cli/issues/2653#issuecomment-209356362>
>>
>
>
>
> --
> /Erik Torsner
> Tel: 0733-118503
> Skype: eriktorsner
>
>


-- 
/Erik Torsner
Tel: 0733-118503
Skype: eriktorsner

**Comment by danielbachhuber** [comment]
You'll need to update to [WP-CLI v0.23.0](http://wp-cli.org/blog/version-0.23.0.html), which includes compatibility with WordPress 4.5. Prior versions of WP-CLI are incompatible with WordPress 4.5.
