### ISSUE TITLE
Multisite command support for archived sites

### ISSUE THREAD

**Issue by corradomatt** [wp-cli/wp-cli#2661]
Not sure if this has already been discussed or not...I've not been able to find a mention of it here or in the documentation.

I'd like to be able to run commands against sites on a multisite network which are archived. Maybe with a flag? Thoughts?

**Comment by danielbachhuber** [comment]
> I'd like to be able to run commands against sites on a multisite network which are archived.

I'm not sure I follow. Why can't you do this right now?

**Comment by QWp6t** [comment]
I run commands against archive sites all the time. Just set `--url` parameter and it works fine.

Or maybe he's wanting to target all archived sites with some sort of parameter? idk.
