### ISSUE TITLE
Composer 1.0.0

### ISSUE THREAD

**Issue by bfolliot** [wp-cli/wp-cli#2664]
Composer is now stable, if i try to update wp-cli to ~0.23 i have this message :

> Your requirements could not be resolved to an installable set of packages.

>   Problem 1
>     - Installation request for wp-cli/wp-cli ~0.23 -> satisfiable by wp-cli/wp-cli[v0.23.0].
>     - wp-cli/wp-cli v0.23.0 requires composer/composer 1.0.0-alpha11 -> satisfiable by composer/composer[1.0.0-alpha11] but these conflict with your requirements or minimum-stability

We need to update the require for composer to 1.0.0, i can make a pull request but i do not know enough about the project to make sure that this will not lead to problem.

Composer changelog : https://github.com/composer/composer/blob/1.0/CHANGELOG.md

**Comment by danielbachhuber** [comment]
See https://github.com/wp-cli/wp-cli/issues/2613#issuecomment-204196858 for how you can address this problem

**Comment by bfolliot** [comment]
Yes i know, that's what I did, but i do not find it logical to have to lower the level of stability

**Comment by danielbachhuber** [comment]
> i do not find it logical to have to lower the level of stability

WP-CLI v0.23.0 was released before Composer v1.0.0 was released. Given there's a workaround, and Composer is a secondary installation method to the Phar file, I don't see it necessary to release v0.23.1.

**Comment by bfolliot** [comment]
Yes i agree, it can wait for the v0.24 release.

Thanks

**Comment by dzuelke** [comment]
Could you please tag a 0.23.1 with this fix @danielbachhuber? I use Composer as the install method for e.g. https://github.com/dzuelke/wordpress-12factor and pull in WP-CLI as a dependency. That's currently not deployable without dropping minimum-stability.

**Comment by dzuelke** [comment]
It might also be a good idea to use `^1.0.0` and not `~1.0.0` as the version selector. The API will now remain stable until 2.0 at least.

**Comment by danielbachhuber** [comment]
> Could you please tag a 0.23.1 with this fix

Sure, I will try to do so this week.

**Comment by bfolliot** [comment]
> It might also be a good idea to use ^1.0.0 and not ~1.0.0 as the version selector. The API will now remain stable until 2.0 at least.

Yes or "~1.0"

**Comment by danielbachhuber** [comment]
v0.23.1 is released http://wp-cli.org/blog/version-0.23.1.html

**Comment by bfolliot** [comment]
Thanks

**Comment by dzuelke** [comment]
Thanks!
