### ISSUE TITLE
Symfony 2.7 breaks PHP 5.3.3 support

### ISSUE THREAD

**Issue by mackensen** [wp-cli/wp-cli#2669]
The Symfony 2.7 components (introduced in a249578ae2053b88c3174b15378266c9c65a9dfe) depend on PHP 5.3.9 or higher which isn't available on RHEL6/CentOS6 (and others).

**Comment by danielbachhuber** [comment]
Dang. Given this changeset has already been out for a couple of releases, and Travis uses PHP 5.3.29, I think we may need to just bump the minimum supported PHP version. How would you feel about that?

**Comment by mackensen** [comment]
I'm on RHEL6 for a little while longer, but I have options. In the short term is there a reason why I shouldn't locally downgrade the symfony components to `~2.3`?

**Comment by danielbachhuber** [comment]
> In the short term is there a reason why I shouldn't locally downgrade the symfony components to ~2.3?

There shouldn't be, no.

**Comment by mackensen** [comment]
Thanks. That gets me over the 4.5 upgrade hump and hopefully I'll be off RHEL6 before 4.6 rolls around. I can't imagine too many other people are in this position.
