### ISSUE TITLE
PHP Fatal error:  Cannot use object of type WP_Error as array in phar:///usr/bin/wp/php/WP_CLI/CommandWithTranslation.php on line 345

### ISSUE THREAD

**Issue by mahnunchik** [wp-cli/wp-cli#2670]
```
PHP Fatal error:  Cannot use object of type WP_Error as array in phar:///usr/bin/wp/php/WP_CLI/CommandWithTranslation.php on line 345
```
```bash
$ php -v
PHP 5.6.19-0+deb8u1 (cli) (built: Mar 14 2016 10:22:33) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

$ wp --version
WP-CLI 0.23.0
```

wordpress 4.5

**Comment by danielbachhuber** [comment]
Thanks for the bug report. Can you provide the command you were running when the error occurred?

**Comment by mahnunchik** [comment]
Hi @danielbachhuber

```
$ wp --allow-root core language install ru_RU
```

**Comment by danielbachhuber** [comment]
🔨

**Comment by diggy** [comment]
@danielbachhuber the patch in #2671 fails for me:

`Fatal error:  Class 'WP_CLI\WP_CLI' not found in /usr/local/Cellar/wp-cli/0.23.1/php/WP_CLI/CommandWithTranslation.php on line 346`

Looks like the global namespace separator is missing?

`\WP_CLI::error( $response );`

**Comment by kristn** [comment]
i have these error on my website 

Fatal error: Cannot use object of type WP_Error as array in /home/ericgelman1ab25/public_html/wp-content/themes/gelman/single-houselist.php on line 18

here is the link: http://www.ericgelman.com/houselist/blocks-downtown-san-anselmo/
can you please advise on what to do? 

wordpress version .4.7.5

**Comment by danielbachhuber** [comment]
Hi @kristn,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
