### ISSUE TITLE
Rewrite Structure doesn't deal with leading slashes

### ISSUE THREAD

**Issue by Stephen-Cronin** [wp-cli/wp-cli#2677]
When I run `wp rewrite structure '%category%/%postname%/'`, then check the Permalinks page in the admin interface, the Custom Structure field contains `/%category%/%postname%/` which is perfect.

However when I add a leading slash to the structure I'm setting, ie `wp rewrite structure '/%category%/%postname%/'`, then the Custom Structure field contains `/C:/Program%20Files/Git/%category%/%postname%/`. 

This happens in both 0.23.0 and 0.24.0-alpha. Some more details about my environment:
- WP-CLI version: 0.23.0
- WordPress 4.5
- PHP version: 5.6.15
- Apache version: Apache/2.4.17 (Win32) OpenSSL/1.0.2d
- Using XAMPP locally on Windows 8.1

**Comment by danielbachhuber** [comment]
I hate to say this to you, but this is a Windows-specific issue. Your use case works as expected on Ubuntu:

```
wp rewrite structure '%category%/%postname%/'
Success: Rewrite structure set.
$ wp option get permalink_structure
/%category%/%postname%/
$ wp option get permalink_structure
$ wp rewrite structure '/%category%/%postname%/'
Success: Rewrite structure set.
$ wp option get permalink_structure
/%category%/%postname%/
```

Windows isn't fully supported by WP-CLI for a couple of reasons:

* I personally have no way of debugging Windows-specific issues, and no one has stepped to maintain Windows compatibility.
* Travis CI (and other CI providers) don't support running tests on Windows, so we have no way of running the entire test suite on Windows.

**Comment by Stephen-Cronin** [comment]
@danielbachhuber - Thanks. That prompted me to do some further testing and I found that it's not even a Windows problem (Powershell works fine). It's something specific to Git for Windows (or maybe the way I've got it set up) and it happens for any php script using $GLOBALS['argv'] with a slash as the first character in a parameter. 

Sorry for wasting your time.

**Comment by danielbachhuber** [comment]
No worries — glad you've figured it out!
