### ISSUE TITLE
Is it possible to run certain command without database connection?

### ISSUE THREAD

**Issue by mahnunchik** [wp-cli/wp-cli#2678]
Is it possible to run certain command without database connection?

For example:
```bash
$ wp core language install ru_RU
```

I'd like to install languages before initial launch or `wp core install` command.

Of course, the following command should use database:
```
$ wp core language activate ru_RU
```

**Comment by danielbachhuber** [comment]
> Is it possible to run certain command without database connection?

Some commands do run without needing a functioning WordPress install. `wp core language *` requires a functioning WordPress install, though.

**Comment by mahnunchik** [comment]
@danielbachhuber Thanks!

It is my workaround:
```bash
curl https://downloads.wordpress.org/translation/core/$(wp core version)/ru_RU.zip -o ru_RU.zip
unzip -o ru_RU.zip -d languages/
```
