### ISSUE TITLE
`wp cron event run` missing DOING_CRON constant

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#2679]
The  `wp cron event run` does not execute all cron scripts.
Usually the constant DOING_CRON indicates that the cron jobs are running.
Scripts use to have such header:

```
if ( ! defined( 'DOING_CRON' ) || ! DOING_CRON ) {
	return;
}
```

As wp-cli is not setting DOING_CRON, such files won't be parsed / used in the cron.
So please define DOING_CRON when running `cron event run`.

```
define('DOING_CRON', true);
```

(as in wp-cron.php)

**Comment by danielbachhuber** [comment]
I'm curious why this hasn't been a problem yet. Can you share how you came across it?

**Comment by danielbachhuber** [comment]
As it turns out, we do already define `DOING_CRON`: https://github.com/wp-cli/wp-cli/blob/master/php/commands/cron.php#L227-L229

**Comment by sourcerer-mike** [comment]
Okay. I investigated further.

This is the call stack until I check for DOING_CRON:

- vendor/wp-cli/wp-cli/php/boot-fs.php:17
- vendor/wp-cli/wp-cli/php/wp-cli.php:21
- vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:755
- vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:807
- vendor/wp-cli/wp-cli/php/wp-settings-cli.php:287
- after here come my plugin, loading cron jobs and looking for DOING_CRON

DOING_CRON is not defined there. The wp-cli part https://github.com/wp-cli/wp-cli/blob/master/php/commands/cron.php#L227-L229
comes later.

It should be moved to an earlier position before loading the plugins. Common files look like that:


```php
<?php

if ( ! defined( 'DOING_CRON' ) || ! DOING_CRON ) {
	// no need for this part, when cron is not running
	return;
}

function my_plugin_cron_foo() {
// ...
```

**Comment by danielbachhuber** [comment]
> It should be moved to an earlier position before loading the plugins.

Ok. I'd be amenable to this change.
