### ISSUE TITLE
Cannot add/update user(s) using wp user import-csv

### ISSUE THREAD

**Issue by tersmitten** [wp-cli/wp-cli#2680]
```
PHP Fatal error:  Call to undefined function add_user_to_blog() in phar:///usr/local/bin/wp-cli/php/commands/user.php on line 700
```

**Comment by danielbachhuber** [comment]
Can you please [share more details](http://wp-cli.org/docs/bug-reports/)? In particular, it'd be useful to know which version of WordPress you're running, whether it's a multisite install, whether other commands work as expected, etc.

**Comment by tersmitten** [comment]
Sorry.

* wordpress 4.5
* no multisite install

The problem seems to occur when I omit the `--skip-update` setting of `wp user import-csv`.

All other commands that [we use](https://github.com/Oefenweb/ansible-wordpress) work just fine.

**Comment by danielbachhuber** [comment]
Ok. Thanks for the details. I suspect `add_user_to_blog()` isn't available on non-multisite, so we'll need to revisit that logic.

**Comment by danielbachhuber** [comment]
@tersmitten I'm not able to reproduce the issue with these test steps :(

```
Scenario: Update role of an existing WordPress user
  Given a WP install
  And a users.csv file:
    """
    user_login,user_email,display_name,role
    bobjones,bobjones@example.com,Bob Jones,contributor
    """

  When I run `wp user create bobjones bobjones@example.com --display_name="Robert Jones" --role=administrator`
  Then STDOUT should not be empty

  When I run `wp user import-csv users.csv`
  Then STDOUT should not be empty

  When I run `wp user list --format=count`
  Then STDOUT should be:
    """
    2
    """

  When I run `wp user get bobjones --fields=user_login,display_name,user_email,roles --format=json`
  Then STDOUT should be JSON containing:
    """
    {
      "user_login":"bobjones",
      "display_name":"Robert Jones",
      "user_email":"bobjones@example.com",
      "roles":"contributor"
    }
    """
```

`add_user_to_blog()` isn't available on multisite, so that truly is the problem, but I don't know why the existing user isn't included in `$blog_users`

**Comment by tersmitten** [comment]
Thanks! I'll see if this resolves the error.
