### ISSUE TITLE
Multiline @synopsis is not parsed correctly

### ISSUE THREAD

**Issue by octopuss** [wp-cli/wp-cli#2684]
In our project we have custom command implemented with synopsis longer than 120 characters. This violates [PSR-2 line length rule](http://www.php-fig.org/psr/psr-2/#2-3-lines), so we've changed it and added a few linebreaks. After that calling `wp` command failed, because attributes which are on 2nd and 3rd line of `@synopsis` are unknown to it.

**Example**
this works:
``` 
* @synopsis --name=<name> [--siteurl=<url>] [--dbname=<dbname>] [--dbuser=<dbuser>] [--dbpass=<dbpass>] [--dbhost=<dbhost>] [--dbprefix=<dbprefix>] [--dbcharset=<dbcharset>] [--dbcollate=<dbcollate>] [--force] [--yes]
```
this is not working and throws error:

```
     * @synopsis --name=<name> [--siteurl=<url>] [--dbname=<dbname>] [--dbuser=<dbuser>] [--dbpass=<dbpass>]
     *           [--dbhost=<dbhost>] [--dbprefix=<dbprefix>] [--dbcharset=<dbcharset>] [--dbcollate=<dbcollate>]
     *           [--force] [--yes]
```
```
Error: Parameter errors:
 unknown --dbprefix parameter
 unknown --yes parameter
```
Tested on WP-CLI version 0.22.0 and 0.23.0

I know that `@synopsis` is not part of official documentation, and we removed it from our commands. I've created this issue is just to let you know.

**Comment by danielbachhuber** [comment]
Thanks for the heads up.

Using `@synopsis` is no longer recommended (#1969), so I think we'll just leave things as they are.
