### ISSUE TITLE
Offer "no-content" and "new-bundled" downloads / source files

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#2685]
As of https://api.wordpress.org/core/version-check/1.7/
There is more than one kind of WordPress to install.

WP no-content does not have the wp-content folder.
WP new-bundled does not have the wp-content/plugins folder.

Interesting for `core download` and `core verify-checksum`.

**Comment by danielbachhuber** [comment]
Duplicate of #1978
