### ISSUE TITLE
Packages listed on the package index website can not be installed

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#2687]
I see several packages on the package index website that can not be installed, e.g.
```
user@computer:~/wordpress/wp-test$ wp package install post-gen
Error: Invalid package.
user@computer:~/wordpress/wp-test$ wp package install image-gen
Error: Invalid package.
```

**Comment by danielbachhuber** [comment]
> I see several packages on the package index website that can not be installed

Where do you see these listed? They aren't valid package names...

**Comment by COLABORATI** [comment]
ah, this was from the _tools_ page... ok, then these seem to be no packages. However, the code looks like in fact these are packages, well, ok.
