### ISSUE TITLE
Feature Request: add ability to install packages from github repo

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#2688]
Somehow I totally assumed that it was _of course_ possible to install packages from a guthub:
```
$> wp package install https://github.com/trepmal/post-gen
Error: Invalid package.
```
Obviously this is not yet possible - I feel this is an expected functionality in 2016, please catch up, thanks!

**Comment by danielbachhuber** [comment]
Packages need to be listed in the [package index](http://wp-cli.org/package-index/) in order to be installed with `wp package install`.
