### ISSUE TITLE
wp option update permalink_structure '/%postname%' Apache

### ISSUE THREAD

**Issue by blindpet** [wp-cli/wp-cli#2709]
A few days ago I was able to update the permalink structure for both nginx and apache. Now it only sticks for nginx. For Apache I have to login and click Save before the permalinks actually update.

I do get the success message when running the wp option update command in the WordPress directory behind Apache

**Comment by blindpet** [comment]
I investigated a bit more and it is probably because of a missing .htaccess, when I log in and save the permalinks the .htaccess is created with the rewrite rules

**Comment by blindpet** [comment]
Added a touch .htaccess to the installer and no change so it seems the wp option update doesn't make the changes to .htaccess even if it exists

**Comment by danielbachhuber** [comment]
I think this may be fixed with #1981.

Can you `wp cli update --nightly` and see if the issue still persists? And, just to confirm, you've added the `apache_mods` declaration to your `wp-cli.yml`?

**Comment by blindpet** [comment]
Will give this a whirl, I was trying to avoid using a yml if possible but will test later today.

I can see there is no flag for apache mods according to http://wp-cli.org/config/ is there a reason for that?

**Comment by danielbachhuber** [comment]
> Will give this a whirl, I was trying to avoid using a yml if possible but will test later today.

Ok, this is your problem then. [Per the docs](http://wp-cli.org/commands/rewrite/flush/), you'll need to create a `wp-cli.yml` file and include:

```
apache_modules:
  - mod_rewrite
```

> I can see there is no flag for apache mods according to http://wp-cli.org/config/ is there a reason for that? 

It's not necessary, because we have the configuration file declaration.
