### ISSUE TITLE
Affected wrong comment for ID > 9

### ISSUE THREAD

**Issue by JanVoracek** [wp-cli/wp-cli#2710]
Hi, I probably found a bug in the comment command. When I want to unapprove comment with ID 35, it affects comment with ID 3.

``` c
$ wp comment unapprove 35
Success: Unapproved comment 3
```

The problem is probably here:
The unapprove subcommand [calls](https://github.com/wp-cli/wp-cli/blob/18e12f4a18f841e4527c6b896024fb2cf8e9e7f1/php/commands/comment.php#L420) `set_status` for every ID and the `set_status` method [takes only the first character](https://github.com/wp-cli/wp-cli/blob/18e12f4a18f841e4527c6b896024fb2cf8e9e7f1/php/commands/comment.php#L305) from the ID.

**Comment by danielbachhuber** [comment]
Yep, that's a bug :(
