### ISSUE TITLE
wp update post post_content breaks down string on linelines

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#2712]
Hi,

I've noticed that when passing content using --post_content argument and the content contains new lines, the text after the new lines is ignored.

It would be nicer to get this working without using a temp file.
I've tried passing \ before the new line but still didn't work.
Could it be a Windows 8 thing?

other possible fixes is to have a prefix: e.g. wp-cli:base64:THE_CONTENT_ENCODED and have wp-cli decode this

Slavi

**Comment by danielbachhuber** [comment]
> I've noticed that when passing content using --post_content argument and the content contains new lines, the text after the new lines is ignored.

Can you share an example so I can see if I reproduce? And, just to confirm, you're aware that `wp post content -` (where the first argument is a dash) will read `post_content` from `STDIN`?

**Comment by lordspace** [comment]
Hi Daniel,

Ok. Will check about an example.

yes, I am aware of the dash parameter but it's not clean approach in my case.
I have a wrapper method that prepares parameters to be run by exec.
It captures the exec time and many other cool things.

Github doesn't allow me to attach php files so here's how to reproduce it.
Slavi

```
<?php

/**
 * This code shows how when post content has new lines only the first line gets used and the rest is ignored.
 * Slavi Marinov | http://orbisius.com & http://qSandbox.com
*/

/*
PHP binary:     c:\php5\php.exe
PHP version:    5.4.17
php.ini used:   C:\php5\php.ini
WP-CLI root dir:        C:\Copy\Dropbox\cloud\dos\wp-cli
WP-CLI packages dir:    /.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.0-alpha
*/


$content = file_get_contents( __FILE__ );

// nl2br breaks it totally i.e. the post doesn't have any content for some reason ?!?
//$content = nl2br( $content );
//echo $content;

// Solution: remove new lines
//$content = preg_replace( '#[\r\n]+#si', ' ', $content );

$content_esc = escapeshellarg( $content );

$cmd = "wp post update 1 --post_content=$content_esc";
 
echo `$cmd 2>&1`;

```

**Comment by danielbachhuber** [comment]
The problem with your script is that the newlines are passed to `$cmd` literally, meaning the shell interprets them as new commands. You'll need to quote `$content_esc` and escape newlines in order to use it with the command.

**Comment by lordspace** [comment]
escapeshellarg was supposed to do that, right?

**Comment by lordspace** [comment]
I decided to do this:

```
$arg = str_replace( array( "\r\n", "\n\r", "\r", "\n" ), ( $flags & self::NL2BR ) ? '<br/>' : ' ', $arg );
            $arg = str_replace( array( "\t", "\0", "\x0B" ), ' ', $arg ); // \x0B vertical tab?

```

**Comment by danielbachhuber** [comment]
> escapeshellarg was supposed to do that, right?

The [docs](http://php.net/manual/en/function.escapeshellarg.php) don't say anything about handling newlines.

**Comment by mikeschinkel** [comment]
> > I've noticed that when passing content using --post_content argument and the content contains new lines, the text after the new lines is ignored.
> 
> Can you share an example so I can see if I reproduce? And, just to confirm, you're aware that `wp post content -` (where the first argument is a dash) will read `post_content` from `STDIN`?

Turns out, [as per @danielbachhuber in Slack](https://wordpress.slack.com/archives/C02RP4T41/p1538570512000100) that `wp post content -` was incorrect.  The following syntax will work instead _(it assumes you have multiline post content in `post-content.html`:

```
cat post-content.html | wp post create --post_type='post'  --post_title="My Test Post" -
```
Be sure to include the trailing dash _(`-`)_.

**Comment by schlessera** [comment]
Yes, that is the correct syntax, it is documented under `<file>` in the [docs](https://developer.wordpress.org/cli/commands/post/create/):

<img width="474" alt="image 2018-10-03 at 3 44 50 pm" src="https://user-images.githubusercontent.com/83631/46414422-5ba31f80-c723-11e8-9f37-5f763ced267f.png">

Do note that this differs from [how `post generate` works](https://developer.wordpress.org/cli/commands/post/generate/) for achieving the same thing, though:

<img width="496" alt="image 2018-10-03 at 3 46 34 pm" src="https://user-images.githubusercontent.com/83631/46414500-868d7380-c723-11e8-89c7-6e2ed28d79c1.png">

**Comment by mikeschinkel** [comment]
@schlessera Thanks. Yes, I didn't happen to find the `<file>` doc, I had just googled and this link was what I found, and then got stuck trying `wp post content -`. So after asking on Slack I thought I would help the next person who finds this while looking for the same thing.

**Comment by drzraf** [comment]
Is there any possibility for reading `post_content` from STDIN for `wp post update <id> --post_content=-` or similar ?

**Comment by martisj** [comment]
@drzraf Yes you can update the content by removing `--post_content` like this: 
`wp post update <id> -` and STDIN your content 🙌
