### ISSUE TITLE
`wp option get users_can_register` fails

### ISSUE THREAD

**Issue by warrenseine** [wp-cli/wp-cli#2719]
While exporting options, I noticed an unexpected behavior with certain option values.

`wp option get users_can_register` returns 1 as error code and nothing in the standard output. On the other hand, `wp option list` correctly lists the option, with a value of `"0"`.

I suppose the error comes from the interpretation of the actual value of the option. Sounds like a bug to me.

**Comment by warrenseine** [comment]
`tag_base`, which has a value of `""`, is correctly retrieved, so this must be specific to `"0"` value.

**Comment by danielbachhuber** [comment]
I think `users_can_register` must've been unset when you ran `wp option get` the first time. The commands work as expected for me:

```
salty-wordpress ➜  wordpress-develop.dev  wp option get users_can_register
0
salty-wordpress ➜  wordpress-develop.dev  echo $?
0
salty-wordpress ➜  wordpress-develop.dev  wp option get invalid_option
salty-wordpress ➜  wordpress-develop.dev  echo $?
1
```

**Comment by warrenseine** [comment]
Why would `wp option get` unset a value?

**Comment by danielbachhuber** [comment]
> Why would `wp option get` unset a value?

It wouldn't, but something else in your codebase may.

**Comment by warrenseine** [comment]
I'm doing both commands in a row. If I do `list` again after `get`, the value is right there:

```bash
$ wp core version
4.4.2
$ wp --version
WP-CLI 0.23.0
$ wp option list | grep users_can_register
users_can_register	0
$ wp option get users_can_register
$ wp option list | grep users_can_register
users_can_register	0
```

**Comment by danielbachhuber** [comment]
> I should test with a clean WordPress install.

Yes, please do.

**Comment by warrenseine** [comment]
Other options with the same value get retrieved properly:

```bash
$ wp option get use_trackback
0
```

There must be something interfering indeed.

**Comment by danielbachhuber** [comment]
@warrenseine Were you able to work this out?
