### ISSUE TITLE
multisite-convert seems to doesn't do anything in .htaccess

### ISSUE THREAD

**Issue by Clemzd** [wp-cli/wp-cli#2721]
I run the following command : 
`wp core multisite-convert --allow-root --title="site multisite" --base="/multisite/21/"`

The wp-config is correctly changed but I can't see any changes in the .htaccess file.

**Comment by danielbachhuber** [comment]
> The wp-config is correctly changed but I can't see any changes in the .htaccess file.

You'll need to modify the `.htaccess` file manually. WordPress doesn't generate a `.htaccess` file for multisite.

**Comment by Clemzd** [comment]
No, it doesn't. But it suggests the lines that needs to be changed when a network is enabled. Exactly like the wp-config.php file. So in my opinion, this plugin should also do that.
