### ISSUE TITLE
Global --url flag not working with a custom command

### ISSUE THREAD

**Issue by DrewAPicture** [wp-cli/wp-cli#2723]
Howdy,

**Environment:**
WP-CLI: v0.24.0-alpha
Server: Ubuntu 14.04.3 LTS (trusty|VVV)
PHP: 7.0.5-3
WP: 4.5.1
Packages: None

**Description**
Was testing a custom command I'm writing today and discovered that I couldn't use the global `--url` flag in a multisite to target a specific site.

Note: I don't have historical perspective on whether this works in earlier PHP or an earlier wp-cli version, though I can say this is the first time I've seen the global `--url` flag fail in this way.

**Command Source:***
```
class My_Command extends WP_CLI_Command {
	/**
	 * Prints information about My Plugin.
	 */
	public function __invoke() {
		// Posts.
		$total_posts = count( get_posts( array(
			'posts_per_page' => -1,
			'fields'         => 'ids'
		) ) );

		WP_CLI::line( sprintf( __( 'Total Posts: %d', 'my-plugin' ), $total_posts ) );
	}
}
WP_CLI::add_command( 'myplugin', 'My_Command' );
```
**Steps to Reproduce:**
Command:
`$ wp myplugin --url=http://subsite.local.dev`

Output:
`Error: 'myplugin' is not a registered wp command. See 'wp help'.

Command (without flag, thus primary site):
`$ wp myplugin`

Output:
`Total Posts: 1`

**Debug Log:**
Passing the `--debug` flag gives the following output:
```
$ wp myplugin --debug --url=http://subsite.local.dev
Debug (bootstrap): No readable global config found (0.073s)
Debug (bootstrap): No project config found (0.079s)
Debug (bootstrap): No package autoload found to load. (0.266s)
Debug (bootstrap): ABSPATH defined: /srv/www/my/plugin/ (0.275s)
Debug (bootstrap): Set URL: http://subsite.local.dev (0.276s)
Debug (bootstrap): Begin WordPress load (0.282s)
Debug (bootstrap): wp-config.php path: /srv/www/my/plugin/wp-config.php (0.284s)
Debug (bootstrap): Loaded WordPress (1.905s)
Error: 'myplugin' is not a registered wp command. See 'wp help'.
```

**Comment by danielbachhuber** [comment]
Is the plugin active on the subsite?

**Comment by DrewAPicture** [comment]
> Is the plugin active on the subsite?

Wow. Thanks buddy :)

**Comment by danielbachhuber** [comment]
> Wow. Thanks buddy :)

No problem :) Sometimes all you need is a sanity check.
