### ISSUE TITLE
On a server with multiple WP databases, which one does wp search-replace affect?

### ISSUE THREAD

**Issue by thinkhuman** [wp-cli/wp-cli#2724]
I'm using wp-cli on a remote server, and that server has a staging db and a live db. When using wp search-replace, how do I specify the db I want to operate on?

**Comment by danielbachhuber** [comment]
> When using wp search-replace, how do I specify the db I want to operate on?

`wp search-replace` uses the value of `DB_NAME` defined in your wp-config.php

**Comment by thinkhuman** [comment]
Does this mean on a server with multiple WP installs in multiple directories, I run the command in the directory containing the wp-config I want it to reference? I often work on hosting servers where I've installed a dev and live site, so this is a common scenario.

**Comment by danielbachhuber** [comment]
> Do you mean I need to run the command in the directory containing the wp-config I want to reference?

Correct.

**Comment by thinkhuman** [comment]
@danielbachhuber Thanks! That's clear. I propose this detail as a future addition to the docs.

**Comment by danielbachhuber** [comment]
> I propose this detail as a future addition to the docs.

I'm not quite sure how it makes sense for the `wp search-replace` docs, given this is applicable to every WP-CLI command. See [config](http://wp-cli.org/config/) docs for more details on global parameters.

**Comment by thinkhuman** [comment]
I'm a regular user of wp-cli (and WP since there was a WP), and it wasn't clear to me (or my co-workers). The docs don't make it clear that you can use a global (e.g., --path) to accomplish it, and the docs don't say you must do that (or run it in the wp-config dir). You can do with that what you will.
