### ISSUE TITLE
Scaffold a fork of underscores

### ISSUE THREAD

**Issue by benoitchantre** [wp-cli/wp-cli#2725]
It would be very useful if we could use `wp scaffold _s` to create a new theme based on a fork of underscores.

Maybe it could be done by adding a new parameter to define the account from where to get underscores on Github.

**Comment by danielbachhuber** [comment]
I don't think this makes sense as an addition to WP-CLI, but you're [welcome to write your own command](http://wp-cli.org/docs/commands-cookbook/) for this need.

**Comment by benoitchantre** [comment]
After having looked at the source, I see that the `wp scaffold _s` relies on underscores.me and I understand better your answer. I thought wp-cli was doing the process directly.
