### ISSUE TITLE
How to get (custom) post url via wp-cli?

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#2727]
Hi,

Is there a way to get the url of a query post?
I noticed that in this file /wp-cli/php/commands/post.php there's a call to: get_permalink

why not put it in this method as well? maybe don't return it by default but only if a flag is listed in the fields?
public function get( $args, $assoc_args ) 

```
// fetch
        if ( isset( $assoc_args['url'] ) ) {
            $post_arr['url'] = get_permalink( $post_arr['ID'] );
            unset( $assoc_args['url'] );
        }
```

Slavi

**Comment by danielbachhuber** [comment]
You can use `wp post list --post__in=1 --field=url` to get the URL of a specific post.

See also #2070

**Comment by lordspace** [comment]
Thanks Daniel. That would work in many post types.
What about attachment / image thumbnail url?

**Comment by danielbachhuber** [comment]
> What about attachment / image thumbnail url?

This is more difficult to fetch, because the data is stored in post meta and then constructed on the fly.

If you `wp package install danielbachhuber/wp-rest-cli && wp plugin install rest-api --activate`, then you can use the REST API implementation:

```
salty-wordpress ➜  wordpress-develop.dev  wp rest attachment get 111 --field=source_url
http://wordpress-develop.dev/wp-content/uploads/2016/05/codeispoetry-1.png
```

**Comment by lordspace** [comment]
Thanks Daniel. The thing is I have 1-2 apps that are calling wp-cli and -cannot use the wp-cli rest api

**Comment by wojsmol** [comment]
@lordspace REST API is available as a command in the WP-CLI so there should not be a problem.
