### ISSUE TITLE
PHP notice when installing theme or plugin

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2728]
I am using `0.23.0`. I am getting notice when installing theme or plugin.
`
PHP Notice:  Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124
Notice: Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124
`
No package installed. WP version 4.5.2.
I see this error when `wp theme install simple-life`. Notice displays but theme is installed anyway.

**Comment by danielbachhuber** [comment]
Duplicate of #2627
