### ISSUE TITLE
wp cron test for spawning cron

### ISSUE THREAD

**Issue by phh** [wp-cli/wp-cli#2729]
I want to replace the WP cronjob with an alternative cronjob that triggers from wp-cli. My server cronjob runs my Make target every 15 minute:
```
wp-cron:
	wp cron test`
```

To make sure that cron is not triggered in the background when a user visits the site I use the disable cron like this:
```
if ( ! defined( 'WP_CLI' ) || ! WP_CLI ) {
	define( 'DISABLE_WP_CRON', true );
}
```

So my question is: Does it make sense to use `wp cron test` for triggering wp cron? As the description is saying: "_Test the WP Cron spawning system and report back its status._"?

**Comment by danielbachhuber** [comment]
You should use `wp cron event run`: http://wp-cli.org/commands/cron/event/run/

There will be a `--due-now` flag in the next release which means it will only run due events (instead of all with the `--all` flag).
