### ISSUE TITLE
Improvement in child theme scaffold

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2730]
Re: `wp scaffold child-theme`. 
In `functions.php` of child theme, function name is prefixed with parent theme. Eg. `wp scaffold child-theme hello --parent_theme=stargazer`. Then function name is `stargazer_parent_theme_enqueue_styles`. May be it could be `hello_enqueue_styles`. To be more safe, `hello_stargazer_enqueue_styles`?

Also, when `hello-world` is passed as slug of child theme `Theme Name:` could be `Hello World`, Currently it is `Hello-world`. 
Also I noticed that only two features tests scenarios are there. It would be nice if we add few more.

**Comment by danielbachhuber** [comment]
> Then function name is `stargazer_parent_theme_enqueue_styles`. May be it could be `hello_enqueue_styles`. To be more safe, `hello_stargazer_enqueue_styles`?

Have you actually run into a problem with this?

> Also, when hello-world is passed as slug of child theme `Theme Name`: could be `Hello World`, Currently it is `Hello-world`.

Don't we already have a `--theme_name` argument? 

> Also I noticed that only two features tests scenarios are there. It would be nice if we add few more.

Sure, more tests are always welcome :)

**Comment by ernilambar** [comment]
> Have you actually run into a problem with this?

Technically its not a problem. May be its just my bug bite from Theme Review. :D When I see function in a theme not prefixed with theme slug, it hurts. Just a standard, not critical issue.

> Don't we already have a --theme_name argument?

Yes, but when that parameter is not passed, theme name is generated automatically. Its just issue of making our command more intelligent I guess.

> Sure, more tests are always welcome :)

I will try my hand in more testing. :)

**Comment by danielbachhuber** [comment]
> Yes, but when that parameter is not passed, theme name is generated automatically. Its just issue of making our command more intelligent I guess.

I think there are a number of cases where the automatically-generated name would be non-sensical. I think it's better to keep the current behavior — the slug is easy enough to change.

> I will try my hand in more testing. :)

Sounds good.
