### ISSUE TITLE
`object-type` parameter in `post-type` command?

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2733]
Re: `wp post-type list`

What does `--object-type` do in this command? I tried example from the doc. `wp post-type list --object-type=post --fields=name,public` but result is empty. Is it `capability_type` we are trying to pass here?

**Comment by ernilambar** [comment]
See PR https://github.com/wp-cli/wp-cli/pull/2734

**Comment by danielbachhuber** [comment]
It must've been copy-pasta from `wp taxonomy` or similar.
