### ISSUE TITLE
How to test a wp-cli package from the terminal?

### ISSUE THREAD

**Issue by sciamannikoo** [wp-cli/wp-cli#2736]
I'm trying to create my first package, following the directions in http://wp-cli.org/docs/commands-cookbook

Everything looks quite clear, except how to run the package from the command line.

I don't mean testing (this will come later): I just want to test the package from the terminal, while I'm developing it.

How I'm supposed to tell wp-cli to register the package I'm writing, so I can call it from the terminal?

I'm sure this is one of these cases where the solution is just in front of me, but I don't see it :)

**Comment by danielbachhuber** [comment]
> How I'm supposed to tell wp-cli to register the package I'm writing, so I can call it from the terminal?

You can use a `wp-cli.yml` or `config.yml` file to `--require=<path-to-file>`, see http://wp-cli.org/config/

For instance, if you're developing your command as a standalone project, you could include a `wp-cli.yml` file in the project root:

```
require:
  - command.php
```

Alternatively, to be able to use your command from anywhere, you'd want to configure a global `config.yml` with a similar require statement, but using the full path to your command loader.

If you have suggestions on how to improve the Commands Cookbook, [pull requests are more than welcome](https://github.com/wp-cli/wp-cli.github.com/edit/master/docs/commands-cookbook/index.md)

**Comment by sciamannikoo** [comment]
Thank you @danielbachhuber.

The package already has the `wp-cli.yml` (it was automatically built by the scaffold command and files were created in the `~/.wp-cli/packages/vendor` directory).

But it looks like this is not enough.  
It seems the only way to make it run is to use `--require=<path-to-file>`, as you suggested, and which definitely works.

So, what I have is enough for me to keep developing, but I wonder why I can't make it work using the first of your suggestions.

Thanks again.

**Comment by danielbachhuber** [comment]
Is this code in a public repo where I can look at it?

Or, can you share more details on how you've changed the scaffolding, so I can better understand your project structure?

**Comment by sciamannikoo** [comment]
I'm in a very early stage (just playing with it, for now), but you can see it here: https://github.com/sciamannikoo/otgs-wp-cli

To recap:
- `wp wpml --require=/my-home-dir/.wp-cli/packages/vendor/otgs/wpml/command.php` works just fine
- `wp wpml` outputs `Error: 'wpml' is not a registered wp command. See 'wp help'.`

**Comment by danielbachhuber** [comment]
> wp wpml outputs Error: 'wpml' is not a registered wp command. See 'wp help'.

It appears you're only registering `wpml list`: https://github.com/sciamannikoo/otgs-wp-cli/blob/master/wpml/command.php#L28

**Comment by sciamannikoo** [comment]
Either I change the command registration to `WP_CLI::add_command( 'wpml', ...` or I call `wp wpml list` from the terminal, I keep getting the same result.

Also, I take for granted (but I might be wrong) that if I can make it work with the `--require` argument, it should work the same without it.

**Comment by danielbachhuber** [comment]
> Also, I take for granted (but I might be wrong) that if I can make it work with the --require argument, it should work the same without it.

Oh, I think there's a bit of confusion here. If you don't include `--require`, then the code isn't loaded (and the command isn't run).

**Comment by sciamannikoo** [comment]
Ah, I now realize I misread your initial suggestion, sorry!

> You can use a wp-cli.yml or config.yml file to --require=<path-to-file>, see http://wp-cli.org/config/

At this point, does it matter if I have or not the yml file, when using `--require=<path-to-file>`?

I know I must have it anyway for releasing the package, in fact it's there already: I'm just trying to get a full picture now :)

**Comment by danielbachhuber** [comment]
> At this point, does it matter if I have or not the yml file, when using --require=<path-to-file>?

No, `--require` will be used to load a file any time you supply the argument.
