### ISSUE TITLE
wp post list with non-public taxonomy

### ISSUE THREAD

**Issue by petenelson** [wp-cli/wp-cli#2742]
We have a non-public taxonomy for one of our custom post types.  Passing the taxonomy and slug to `post list` does not filter by the taxonomy and slug.

```
vagrant@vvv:~/msr$ wp post list --post_type=msr-research-item --format=count --msr-content-type=video
14096
```

If I temporarily set the taxonomy to public, filtering by it works as-expected.
```
vagrant@vvv:~/msr$ wp post list --post_type=msr-research-item --format=count --msr-content-type=video
5236
```

This is likely by design, but it would be handy to be able to query via CLI for non-public taxonomies.

**Comment by danielbachhuber** [comment]
In your project, can you try adding:

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    add_filter( 'query_vars', function( $vars ) {
        $vars[] = 'msr-content-type';
        return $vars;
    });
}
```

If it works, I think it would be a more appropriate appropriate approach. I don't think WP-CLI magically supporting querying by a private taxonomy is expected behavior.

**Comment by petenelson** [comment]
That didn't work, but adding a conditional to the register_taxonomy args took care of it.

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
	$args['public'] = true;
}
```

Thanks!
