### ISSUE TITLE
Deal with Requests being committed to WordPress core

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2744]
Because it's loaded by wp-settings.php, it doesn't incur an immediate incompatibility problem. We'll need to figure out how our copy can live alongside core's though.

https://core.trac.wordpress.org/changeset/37428

**Comment by danielbachhuber** [comment]
> Because it's loaded by wp-settings.php, it doesn't incur an immediate incompatibility problem.

As it turns out, the introduction of Requests does break WP-CLI: https://travis-ci.org/wp-cli/wp-cli/jobs/130013158

cc @rmccue @dd32 for thoughts on how we should address this, given WP-CLI can load Requests before WordPress, and thus would fatal in certain situations.

**Comment by rmccue** [comment]
Core should probably only load `Requests` and register the autoloader if `Requests` isn't already loaded. I'll patch core to that effect if we're 👍 on it.

**Comment by rmccue** [comment]
(Forget my earlier comment.)

WP [already checks](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-http.php#L10) if Requests is loaded before trying to load it; looks like the fatals there are for `WP_HTTP_Requests_Response` missing, which a new file loaded in `wp-settings.php`?

**Comment by danielbachhuber** [comment]
> WP already checks if Requests is loaded before trying to load it;

Ah, I had assumed it wasn't my bad.

> looks like the fatals there are for WP_HTTP_Requests_Response missing, which a new file loaded in wp-settings.php?

Yep, easier to fix :)
