### ISSUE TITLE
Missing gems and errors running wp-cli docs locally

### ISSUE THREAD

**Issue by NateWr** [wp-cli/wp-cli#2747]
Here are some errors I get following [setup instructions](https://github.com/wp-cli/wp-cli.github.com#setup) on the docs site:

```
           Source: /media/Storage/projects/wp-cli.github.com
       Destination: /media/Storage/projects/wp-cli.github.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Error reading file /media/Storage/projects/wp-cli.github.com/docs/internal-api/wp-cli-debug/index.md: (<unknown>): mapping values are not allowed in this context at line 4 column 61 
Error reading file /media/Storage/projects/wp-cli.github.com/docs/internal-api/wp-cli-error/index.md: (<unknown>): mapping values are not allowed in this context at line 4 column 61 
Error reading file /media/Storage/projects/wp-cli.github.com/docs/internal-api/wp-cli-success/index.md: (<unknown>): mapping values are not allowed in this context at line 4 column 65 
Error reading file /media/Storage/projects/wp-cli.github.com/docs/internal-api/wp-cli-warning/index.md: (<unknown>): mapping values are not allowed in this context at line 4 column 65 
     Build Warning: Layout 'nil' requested in atom.xml does not exist.
                    done in 4.606 seconds.
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```

`/blog` and `/package-index` don't work for me locally, but everything else seems fine.

Not a roadblock for me. Just a heads-up.

**Comment by danielbachhuber** [comment]
> Here are some errors I get following setup instructions on the docs site:

Thanks for flagging them. Having someone else notice them motivated me to finally fix them up :)

> /blog and /package-index don't work for me locally, but everything else seems fine.

`/blog` is built with the `./vendor/bin/phake` command. Did you try running that?

`/package-index` is built separately and served by https://github.com/wp-cli/package-index https://github.com/wp-cli/wp-cli.github.com/commit/deaee41cbcee9a06e9bb38e19af4c4a27472299f

**Comment by NateWr** [comment]
When I run `./vendor/bin/phake` I get a PHP notice:

```
PHP Notice:  Undefined variable: param in /media/Storage/projects/wp-cli.github.com/command.php on line 137
```

And the `/blog` page does appear. There are just no posts there.

**Comment by danielbachhuber** [comment]
Huh. I can't reproduce that issue locally.

I'll take another look as a part of #2768
