### ISSUE TITLE
Support running commands on remote servers over SSH

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2754]
As a WP-CLI user, it would be convenient if I could use a global `--ssh=<host>` argument to run a command against a WordPress install on a remote server:

```
$ wp --ssh=v:/srv/www/wordpress-develop.dev/src option get home
http://wordpress-develop.dev
```

To modify the behavior of the command at runtime, it should be possible to hook in a custom command:

```
WP_CLI::add_hook( 'before_ssh', function() {
	if ( $ssh = WP_CLI::get_runner()->config['ssh'] ) {
		list( $host, $path ) = explode( ':', $ssh );
		switch( $host ) {
			case 'runcommand.io':
				putenv( 'WP_CLI_SSH_PRE_CMD=export PATH=$HOME/bin:$PATH' );
				break;
		}
	}
});
```

https://github.com/xwp/wp-cli-ssh is good prior art from @westonruter and @jonathanbardo that we can crib from.

**Comment by danielbachhuber** [comment]
@westonruter @jonathanbardo Do you recall why you originally used `passthru()` instead of `ssh2_connect()` and its corresponding library?

**Comment by westonruter** [comment]
@danielbachhuber not exactly, but two reasons come to mind:

1. I wasn't aware of `ssh2_connect()`.
2. And `ssh2_connect()` isn't a core PHP function but part of a PECL extension.

**Comment by jonathanbardo** [comment]
I think at the time we also needed to be able to ssh into a jump server before reaching the final web server. This was going to be easier to do using `passthru()`.

**Comment by danielbachhuber** [comment]
Thanks guys. I think I'll end up going with `passthru()` because it will be easier to reuse the user's SSH config details.

**Comment by danielbachhuber** [comment]
Debating whether we need to support `port` in some fashion. I'm inclined to have users define the port in their SSH config if it's non-standard.

**Comment by danielbachhuber** [comment]
@westonruter @jonathanbardo Would you mind testing out the current implementation when you have a moment, and let me know what you think? Specifically, I'm looking for feedback on the implementation, and any additional features you think it needs.

**Comment by jonathanbardo** [comment]
@danielbachhuber I agree, SSH config makes sense.

**Comment by westonruter** [comment]
> Would you mind testing out the current implementation when you have a moment, and let me know what you think? Specifically, I'm looking for feedback on the implementation, and any additional features you think it needs.

@timneutkens actually, since you've been using WP-CLI SSH most frequently of late (AFAIK), would you give this PR a try and provide feedback?

**Comment by danielbachhuber** [comment]
> would you give this PR a try and provide feedback?

Just to clarify, the code has already landed on master. If you're using the Phar install, you can `wp cli update --nightly` to try it out.

**Comment by timneutkens** [comment]
@westonruter @danielbachhuber Will do. Bet I will have time to review this tomorrow.

**Comment by timneutkens** [comment]
Hey @danielbachhuber, looks good :)

Only thing I noticed is that `wp` is hardcoded here: https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L356.

Few weeks ago I created a pull request on wp-cli-ssh (https://github.com/xwp/wp-cli-ssh/pull/27) to add support for a custom command to be ran. So you could do something like: `wpcli_command: php ./vendor/bin/wp` (https://github.com/xwp/wp-cli-ssh/blob/master/wp-cli.sample.yml#L22) when you install wp-cli using composer.

The hook you implemented probably solves the issue I had wanting to use a different php command for wp-cli. Just not the part where you would want to use a different path to the command.

**Comment by danielbachhuber** [comment]
> Only thing I noticed is that `wp` is hardcoded here

That was intentional, although I could be convinced otherwise.

> The hook you implemented probably solves the issue I had wanting to use a different php command for wp-cli. Just not the part where you would want to use a different path to the command.

Well, my thinking is that you could create a just-in-time alias to a different path, if WP-CLI wasn't available as `wp`. Even though there is a workaround, it's somewhat intentional not to permit an arbitrary executable (e.g. it's a design decision that `--ssh` should only be used to execute WP-CLI).

What do you think about my explanation?

**Comment by timneutkens** [comment]
That's a fair point. You could alias `wp` using the hook. So that will do.

**Comment by timneutkens** [comment]
I also noticed that you can provide `WP_CLI_PHP` to use another version php. So that is an even better solution to the issue I was having 😄

**Comment by danielbachhuber** [comment]
> Debating whether we need to support port in some fashion. I'm inclined to have users define the port in their SSH config if it's non-standard.

I figured out a syntax for us to support port:

```
192.168.50.10:2222:/srv/www/wordpress-develop.dev/src
```

If the port isn't specified, then 22 is assumed:

```
192.168.50.10:/srv/www/wordpress-develop.dev/src
```

**Comment by timneutkens** [comment]
I agree, that's the best syntax for supporting ports 👍

**Comment by scribu** [comment]
Git uses a syntax without a colon between port and path:

```ssh://[user@]host.xz[:port]/path/to/repo.git/```

https://git-scm.com/docs/git-clone

**Comment by scribu** [comment]
Since it's a standard URL format, it should be parseable with PHP's `parse_url()`.

**Comment by danielbachhuber** [comment]
> Since it's a standard URL format, it should be parseable with PHP's parse_url().

I agree, I'll update.

**Comment by danielbachhuber** [comment]
Actually, `parse_url()` isn't quite compatible with using a SSH config like `v`. If we use regex instead, we could support a similar syntax to standard URL format:

```
@prod:
  ssh: rc~/webapps/production
@dev:
  ssh: v/srv/www/runcommand.dev
@wpdev:
  ssh: v:2222/srv/www/wordpress-develop.dev/src
```

**Comment by danielbachhuber** [comment]
Feeling pretty good with this now as a v1. I'll handle website documentation as a part of #2767

**Comment by timneutkens** [comment]
Thanks Daniel, will have to make so changes to our internal setup 👍

**Comment by toleabivol** [comment]
How would I do it if I usually login with :
`ssh -i ~/.ssh/pemfiles/yyyy.pem ec2-user@yyy.com`

**Comment by danielbachhuber** [comment]
@toleabivol You'll need to set a SSH config with the identity file reference.
