### ISSUE TITLE
Your PHP installation appears to be missing the MySQL extension which is required by WordPress

### ISSUE THREAD

**Issue by joelstransky** [wp-cli/wp-cli#2758]
After I install wp-cli, navigate to my site root and do `wp core download` then `wp core config --dbname=development --dbuser=admin --dbpass=vagrant`
then
`wp core install --url=http://192.168.10.12 --title=wordpress --admin_user=admin --admin_password=vagrant --admin_email=test@email.com`
I get the error
`Your PHP installation appears to be missing the MySQL extension which is required by WordPress`
which doesn't make sense because I can just go to `http://192.168.10.12` and run the normal wordpress install successfully.
Please help.

**Comment by Danw33** [comment]
Shot in the dark here - Could it be that you have multiple PHP environments and the PHP on your `$PATH` is different from the one being used by your web server?

**Comment by joelstransky** [comment]
Could be. Not sure.
Our vagrant boxes start with Ubuntu 12.04 and PHP 5.3. Following a suggestion [here](http://askubuntu.com/questions/565784/how-do-i-upgrade-php-version-to-the-latest-stable-released-version), I upgraded to PHP 5.5 before I installed wp-cli which is when I got this error.
I then destroyed the box and this time upgraded to PHP 5.4 which worked. Perhaps that can shed some light as I'm not a dev-ops guru.

**Comment by Danw33** [comment]
My guess would be the upgrade - If it was a third-party build it may have installed the newer version along side the old one (so `php` would be the 5.3, and for example `php55` might be the newer install)

On the dev-ops front - Me neither, it's like the blind leading the blind 😆

**Comment by tddamith** [comment]
please help me...
how to fix this issue 

Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

**Comment by danielbachhuber** [comment]
Hi @tddamith,

Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support
