### ISSUE TITLE
Retool README.md in the project repo

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2760]
Our README.md hasn't been edited in a while, and could use a refresh.

More specifically:

* [x] Restructure README.md to use the following sections: Using, Installing, Support, Extending, Contributing (similar to https://github.com/wp-cli/scaffold-package-command#wp-cliscaffold-package-command)
* [x] Using section should be a summary of the [Quick Start guide](http://wp-cli.org/docs/quick-start/), and then link to the full Quick Start guide.
* [x] Installing section should also specify requirements, and link to the [full installation guide](http://wp-cli.org/docs/installing/)
* [x] Make sure each link is still valid, and is the appropriate link for the topic.
* [x] Add RESTful WP-CLI mention
* [ ] Deploy README to website's index.

For whomever picks this up, it might be easier to collaborate in Dropbox Paper before creating a PR. Ideally, we can then automatically turn this into the WP-CLI homepage, thus reducing the need to maintain two equivalent documents.

**Comment by NateWr** [comment]
What are the installation requirements? WP version? PHP version?

**Comment by NateWr** [comment]
For the Support section, did you have in mind the content on the [Bug Reports](http://wp-cli.org/docs/bug-reports/) page from the docs site?

**Comment by danielbachhuber** [comment]
> What are the installation requirements? WP version? PHP version?

Left a comment on the PR with the reqs.

> For the Support section, did you have in mind the content on the Bug Reports page from the docs site?

I don't have a strong preference at this point. #2766 might provide some inspiration
