### ISSUE TITLE
Add "Updating" section to the Installation guide

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2761]
Our [Installation guide](http://wp-cli.org/docs/installing/) should mention how to update WP-CLI.

**Comment by kkoppenhaver** [comment]
There is now a brief sentence on updating on the homepage

`You can update WP-CLI with wp cli update (doc), or by repeating the installation steps.`

What about a section for the installation guide just after `Wondering what to do next?` that goes something like this:

# Updating WP-CLI
Once WP-CLI is installed you can update it at any time by running `wp cli update`.  

You will be prompted to confirm that you wish to update with a message similar to the following: 
`You have version 0.21.1. Would you like to update to 0.23.1? [y/n]`

After you accept, you should see a success message:
`Success: Updated WP-CLI to 0.23.1`

For more information, including flags and options that can be used, read the full [docs page on the update command](https://wp-cli.org/commands/cli/update/).

**Comment by kkoppenhaver** [comment]
Also, am I correct in assuming that the eventual change to incorporate this would have to be made on the [wp-cli.github.com](https://github.com/wp-cli/wp-cli.github.com) repo?

**Comment by danielbachhuber** [comment]
> What about a section for the installation guide just after Wondering what to do next? that goes something like this:

Looks good to me! Want to submit a pull request with the change?

> Also, am I correct in assuming that the eventual change to incorporate this would have to be made on the wp-cli.github.com repo?

Yes, although the homepage is automatically generated from the README.md, so updating is just a matter of running a script.

**Comment by danielbachhuber** [comment]
🚢
