### ISSUE TITLE
Add a 2-3 minute video quick start

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2762]
For those who are more inclined to watch a video over reading a piece of documentation, it would be nice if we had a well-edited 2-3 minute video quick start on the [Quick Start](http://wp-cli.org/docs/quick-start/) page.

**Comment by kkoppenhaver** [comment]
@danielbachhuber Still something you want to do? I could start putting together an outline.

**Comment by danielbachhuber** [comment]
Yep, I think it'd be useful.

**Comment by kkoppenhaver** [comment]
I'm thinking:

~45 seconds: Installing WP-CLI (phar method) 
~90 seconds: Setting up a WordPress site (wp core download && wp core install)
~30 seconds: Installing a Plugin from the repo (wp plugin install jetpack)

Total: ~2m45s

**Comment by danielbachhuber** [comment]
@kkoppenhaver Make any progress with this?

**Comment by kkoppenhaver** [comment]
Yup, been working on it off and on. Hope to have a rough cut uploaded somewhere shortly.

**Comment by kkoppenhaver** [comment]
@danielbachhuber First cut here: https://www.youtube.com/watch?v=GyhK_sJAqtY (unlisted for now, open to wherever you eventually want to host it)

My thoughts:
  - Want to smooth out an audio glitch in the middle
  - Maybe want to re-record the installation section (condense, tighten up wording a bit)

Other than that, I'm open to any and all feedback from you or others.

**Comment by danielbachhuber** [comment]
Looks pretty good, @kkoppenhaver. Thanks!

If you're thinking about re-recording parts, here are a few bits of feedback:

* In the installation process, it would be helpful to explain what each step is (what a Phar file is, what it means to mark a file as executable, or move it on your path).
* Might be helpful to have an introduction at the beginning of the video with an outline of the steps to be covered in the video.
* When showing a command being executed, it might be helpful to include a 10 second slide with an overview of the command.
* Generally, it's a bit difficult to read the text on the screen. The text would be more legible if you could zoom in on the relevant part of the screen.

**Comment by danielbachhuber** [comment]
Punting on this because it hasn't seen enough momentum to get over the finish line.
