### ISSUE TITLE
Refresh Quick Start page

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2763]
Generally, the [Quick Start](http://wp-cli.org/docs/quick-start/) page could use a bit of an edit, particularly the example usage section.

It would be nice of each instance of example usage was closer to what the user actually sees in their terminal, rather than just the command itself.

**Comment by iamnotjason** [comment]
I'm going to draft up an updated page with some good examples and output shortly. How do you feel about animated .gif files for the images on that page? It makes the page more flashy but it would allow for two - five second clips that can illustrate it in action.

**Comment by danielbachhuber** [comment]
> How do you feel about animated .gif files for the images on that page?

I was actually thinking of short animated GIFs for depicting WP-CLI commands the other day. I really like the idea, and think it would work well as long as they're a consistent style and not too large.
