### ISSUE TITLE
Write a general purpose CONTRIBUTING.md 

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2766]
Our current CONTRIBUTING.md is quite sparse:

> ### Contribute
> 
> 
> Thanks in advance for helping to improve WP-CLI.
> 
> To get started, please review our documentation on [creating an issue](http://wp-cli.org/docs/bug-reports/) or [submitting a pull request](http://wp-cli.org/docs/pull-requests/).

While I'd like to continue to have comprehensive dedicated docs for [bug reports](http://wp-cli.org/docs/bug-reports/) and submitting [pull requests](http://wp-cli.org/docs/pull-requests/), I think we need at least a few paragraphs as a general welcome mat.

Inspiration:

* http://hood.ie/contribute/
* https://github.com/nayafia/contributing-template

We can then also have CONTRIBUTING.md deploy to wp-cli.org/contributing

**Comment by danielbachhuber** [comment]
This issue could pair nicely with https://github.com/wp-cli/scaffold-package-command/issues/6

Meaning, we should reuse some of the language in the CONTRIBUTING.md we create here for `wp scaffold package-readme`

**Comment by kkoppenhaver** [comment]
First draft. Any feedback more than welcome.

## Welcome and thanks!

First off, thank you for considering contributing to WP-CLI. It's people like you that make continue to make it such a great tool.

Following these guidelines helps to communicate that you respect the time of the developers managing and developing this open source project. In return, they should reciprocate that respect in addressing your issue, assessing changes, and helping you finalize your pull requests.

## What kinds of contributions are we looking for?

WP-CLI is an open source project and we love to receive contributions from our community — you! There are many ways to contribute, from writing tutorials or blog posts to help spread the word about WP-CLI, improving the documentation, submitting bug reports and feature requests or writing code which can be incorporated into WP-CLI itself. To get started, take a look at any of the currently [open issues](https://github.com/wp-cli/wp-cli/issues/).

## Your First Contribution
If you're looking to make your first contribution, take a look at issues that have been [tagged as good for beginners](https://github.com/wp-cli/wp-cli/labels/good-first-issue).

Never made an open source contribution before? You can learn how from this *free* series, [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

Once you've found an issue you want to tackle, check out our process for [making a pull request](http://wp-cli.org/docs/pull-requests/). Please make sure any code you submit follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).

More detailed information on submitting your contribution can be found on our [Pull Requests page](http://wp-cli.org/docs/pull-requests/).

## Reporting a Bug
For more information on how to report a bug, please see the [detailed docs on bug reports](http://wp-cli.org/docs/bug-reports/).

## Community
Additional discussion around WP-CLI can be found in the #cli channel of the Make WordPress Slack.  For more information on joining the Make WordPress Slack Team, see their [information page](https://make.wordpress.org/chat/).

**Comment by danielbachhuber** [comment]
> First draft. Any feedback more than welcome.

Mind putting this into a Google Doc so we can more easily have a conversation around the text?

**Comment by kkoppenhaver** [comment]
Sure thing.

https://docs.google.com/document/d/1eRfCEoO2B1SbMgWERv2sCsiIGVgrvFZdPikuqZ66V2M/edit

**Comment by kkoppenhaver** [comment]
Good thoughts on the opening paragraph. Accepted the suggestions.

**Comment by danielbachhuber** [comment]
> Good thoughts on the opening paragraph. Accepted the suggestions.

Cool. I'll do another more thorough pass when I have the time in the near future.

**Comment by danielbachhuber** [comment]
@kkoppenhaver As it turns out, I have opinions about how this was written :) My edits ended up being quite extensive, so I just went ahead and published them: http://wp-cli.org/docs/contributing/

I appreciate your time on this though. I think we could still use a section on "Improving our documentation", written in a similar format. Up for taking care of that?

**Comment by kkoppenhaver** [comment]
@danielbachhuber No worries. Since you're looking for more contributions, it seems only fitting that you craft the document that shapes how those contributions come in.  Just glad I could get the ball rolling on this one.

I can definitely take on 'Improving our documentation'. Is there a separate issue for discussion of that or are we just keeping that here?

**Comment by danielbachhuber** [comment]
> Is there a separate issue for discussion of that or are we just keeping that here?

Here works fine for me.

**Comment by kkoppenhaver** [comment]
First version: 
https://docs.google.com/document/d/1k74bG1ZvAG-ItHNyDIssrT21P-whbfrUZnJnyxlrOlU/edit?usp=sharing

Possibly related issues (may want to include information from these tickets in the description):
https://github.com/wp-cli/wp-cli/issues/3037
https://github.com/wp-cli/wp-cli/issues/2769

**Comment by kkoppenhaver** [comment]
Condensed some sections based on @danielbachhuber 's feedback and made some additional edits.

**Comment by danielbachhuber** [comment]
@kkoppenhaver Looks pretty good! Want to submit a PR?

**Comment by kkoppenhaver** [comment]
@danielbachhuber Can do. I'm assuming you want it on the contributing page? https://wp-cli.org/docs/contributing/

**Comment by kkoppenhaver** [comment]
Nevermind, that's the page we were already discussing. PR incoming.

**Comment by danielbachhuber** [comment]
> I'm assuming you want it on the contributing page? https://wp-cli.org/docs/contributing/

Not quite. `docs/contributing/` is built from `CONTRIBUTING.md`

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢
