### ISSUE TITLE
Generate dynamic website pages using WP-CLI commands instead of Phake

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2768]
The website uses a Phakefile.php to "build" some of its pages. At a high-level, what's happening is that Phake is pulling some data from WP-CLI and generating mustache templates for Jekyll to render.

A set of WP-CLI commands can do essentially the same, while removing our need for Phake (and the added complexity of Phake for those who are unfamiliar with it). We should port our Phake tasks to WP-CLI commands.

This can be done in conjunction with #2760 and #2766, as they'll need to be transformed in order to end up on the website.

**Comment by bordoni** [comment]
I intend to start working on a Pull Request for the issue this weekend.
Will go based on what you did on wp-cli/wp-cli.github.com#159

**Comment by danielbachhuber** [comment]
> I intend to start working on a Pull Request for the issue this weekend.

Great! Feel free to clean up `command.php` as you see fit (creating a dedicated class, etc.). We could have a `wp website-generate` command with accepts 'homepage', 'contributing', 'commands', 'internal-apis', etc. or `--all`

**Comment by danielbachhuber** [comment]
@bordoni Still planning to work on this? It would be nice to have done in the next couple of days.

**Comment by bordoni** [comment]
Yes I do, got to wrap what I've started and Pull Request it.

**Comment by danielbachhuber** [comment]
@bordoni Where'd you end up with this? Can you push the code you have if it's usable? I'd like to wrap this up in the next couple of weeks.
