### ISSUE TITLE
Add tests for `--ssh` parameter

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2772]
We'll need a box we can connect to from Travis, though.

From #2754

**Comment by miya0001** [comment]
I came up with an idea.
Run ssh server and connect itself on travis like following.
Sorry I haven't tried yet... 😄 

### ci/setup_ssh_server.sh

```
#!/bin/sh 

sudo apt-get update -qq
sudo apt-get install -qq libssh2-1-dev openssh-client openssh-server

sudo start ssh

ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
cat ~/.ssh/id_rsa.pub >>~/.ssh/authorized_keys
ssh-keyscan -t rsa localhost >>~/.ssh/known_hosts

export SSH_PRIVATE_KEY="$HOME/.ssh/id_rsa"
export SSH_PUBLIC_KEY="$HOME/.ssh/id_rsa.pub"
```

### .travis.yaml

```
language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh ./ci/setup_ssh_server.sh
  - ./ci/prepare.sh

script: ./ci/test.sh
```

**Comment by danielbachhuber** [comment]
@miya0001 Or we could just set up a remote server used for CI, and encrypt the connection details.

**Comment by danielbachhuber** [comment]
Adding this to the wish list for now http://wp-cli.org/docs/wish-list/
