### ISSUE TITLE
Import: Class 'WP_HTTP_Requests_Response' not found

### ISSUE THREAD

**Issue by jacobischwartz** [wp-cli/wp-cli#2778]
I'm getting the following fatal error when wp import encounters a line that involves fetching a remote file:

PHP Fatal error:  Class 'WP_HTTP_Requests_Response' not found in /srv/www/wp/wp-includes/class-http.php on line 354
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->_run_command() phar:///usr/bin/wp/php/WP_CLI/Runner.php:757
PHP   6. WP_CLI\Runner->run_command() phar:///usr/bin/wp/php/WP_CLI/Runner.php:334
PHP   7. WP_CLI\Dispatcher\Subcommand->invoke() phar:///usr/bin/wp/php/WP_CLI/Runner.php:327
PHP   8. call_user_func:{phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:351}() phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:351
PHP   9. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:351
PHP  10. call_user_func:{phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:67}() phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:67
PHP  11. Import_Command->__invoke() phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:67
PHP  12. Import_Command->import_wxr() phar:///usr/bin/wp/php/commands/import.php:57
PHP  13. WP_Import->import() phar:///usr/bin/wp/php/commands/import.php:143
PHP  14. WP_Import->process_posts() /srv/www/wp-content/plugins/wordpress-importer/wordpress-importer.php:116
PHP  15. WP_Import->process_attachment() /srv/www/wp-content/plugins/wordpress-importer/wordpress-importer.php:611
PHP  16. WP_Import->fetch_remote_file() /srv/www/wp-content/plugins/wordpress-importer/wordpress-importer.php:859
PHP  17. wp_get_http() /srv/www/wp-content/plugins/wordpress-importer/wordpress-importer.php:905
PHP  18. wp_safe_remote_request() /srv/www/wp/wp-includes/deprecated.php:3644
PHP  19. WP_Http->request() /srv/www/wp/wp-includes/http.php:49

The class in question seems to get included by Wordpress via wp-settings.php. wp-cli loads it in php/wp-settings-cli.php, on line 211:
Utils\maybe_require( '4.6-alpha-37438', ABSPATH . WPINC . '/class-wp-http-requests-response.php' );

I'm using WP v4.6-alpha-37459, so that file _should_ be loaded... In theory.

**Comment by danielbachhuber** [comment]
@jacobischwartz Can you share `wp --info` ?

**Comment by jacobischwartz** [comment]
PHP binary:	/usr/bin/php5
PHP version:	5.6.18-1+deb.sury.org~precise+1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/vagrant/.wp-cli/packages/
WP-CLI global config:	/srv/www/wp-cli.yml
WP-CLI project config:	
WP-CLI version:	0.23.0

**Comment by danielbachhuber** [comment]
You'll need to `wp cli update --nightly` if you want to use WP-CLI against trunk.

The compatibility fix for WP 4.6 (#2753) hasn't been included in a major release yet.

**Comment by jacobischwartz** [comment]
Thanks! That fixed it. To be honest, I've been using VIP Quickstart without connecting the dots to using the nightly updates on the CLI.
