### ISSUE TITLE
Erroneous behavior of "theme" command

### ISSUE THREAD

**Issue by ivandotv** [wp-cli/wp-cli#2790]
Scenario:
If for some reason i have a **empty** directory inside the `themes` folder in wordpress installation with the name of the theme ( e.q. 'myth').
If I query if the theme is installed, I will get a **positive** answer. 
If I query the status of the theme, i will get this:
````
    Name: myth
    Status: Inactive
    Version: 
    Author: 
````
If I query the listing of the themes. Theme won't be in the list.

So basically `wp-cli` thinks just becase there is a folder with the name of the theme present, the theme is installed. 
So if I try to install the theme via `wp-cli` I get `Warning: myth: Theme already installed.`

You might ask why do I have a empty directory with the name of the theme.
It's because I'm using docker for development , and I need to "mount" that folder before launching the container.
I'm mounting an empty folder, and then the container (via wp-cli) installs all the plugins and themes I need.

**Comment by danielbachhuber** [comment]
What do you think the expected behavior is?

**Comment by ivandotv** [comment]
It should detect that that it's just an empty directory. 
It should detect that it's not a valid theme if there are no mandatory theme files inside.

**Comment by ivandotv** [comment]
Tried if with `--force`

````
Installing Myth (1.0.3)
Downloading install package from https://downloads.wordpress.org/theme/myth.1.0.3.zip...
Unpacking the package...
Installing the theme...
Removing the old version of the theme...
Warning: Could not remove the old theme.
Theme update failed.
````
It also fails as user `root` so it's not a permission issue.

**Comment by danielbachhuber** [comment]
> It should detect that that it's just an empty directory. 
> It should detect that it's not a valid theme if there are no mandatory theme files inside.

What does WordPress core do with an empty theme directory?

**Comment by ivandotv** [comment]
I mean that the `myth` directory is empty.

**Comment by danielbachhuber** [comment]
> I mean that the myth directory is empty.

Right. What does the WordPress admin do? WP-CLI should exhibit the same behavior as the admin.

**Comment by ivandotv** [comment]
Admin correctly detects that the theme doesn't exist, i.e there is no `myth` theme in backend.

**Comment by ivandotv** [comment]
`wp-cli` even allows me to activate the theme, but as soon as a reload wordpress in browser, it reverts to default theme. 
And them if I check on the command line if the `myth` is activated, it correctly says it's not.

Alos `myth` is just an example theme (first one I grabbed from wordpress theme repository)

**Comment by danielbachhuber** [comment]
Ok. We can add some logic to verify the theme is valid before listing it or permitting it to be activated.

**Comment by ivandotv** [comment]
I've looked at the code, it seems that you use wordpress function `wp_get_theme()`
It must correctly return `false` (1) if we query if the theme is installed.

> We can add some logic to verify the theme is valid before listing it or permitting it to be activated.

Theme is never listed, when calling `wp theme list`

**Comment by ivandotv** [comment]
This will land in 0.24.0? 
If so, when is the release date? 
Can I try it now?

**Comment by danielbachhuber** [comment]
> This will land in 0.24.0?

Yes

> If so, when is the release date? 

I haven't picked a release date yet.

> Can I try it now?

Sure, `wp cli update --nightly`

**Comment by ivandotv** [comment]
Just updated.
Same scenario:
Directory `myth` exists inside theme folder, but is **empty**.
Now when I run `wp theme is-installed myth` it correctly returns `0` (theme not installed)
However, in next step when I try to install the theme I get back:
`Warning: myth: Theme already installed.`

Using `--force`
````
Installing Myth (1.0.3)
Downloading install package from https://downloads.wordpress.org/theme/myth.1.0.3.zip...
Unpacking the package...
Installing the theme...
Removing the old version of the theme...
Warning: Could not remove the old theme.
Theme update failed.
````

`wp theme list` and
 `wp theme status myth`
Return the same results as in previous discussion.

**Comment by danielbachhuber** [comment]
In #2821, I'm changing the behavior of `wp theme status` to error if the theme is erred.

In the WordPress admin, if there's an empty directory where a complete theme is expected, the admin indicates the theme is installed:

![image](https://cloud.githubusercontent.com/assets/36432/15474587/4ff15d94-20ba-11e6-8d49-3c00e704db4e.png)

As such, the behavior of `wp theme is-installed` and `wp theme install` is consistent with the WordPress admin.

Beyond #2821, I don't believe any further changes are necessary. Can you confirm?

**Comment by ivandotv** [comment]
If there is a directory for the theme, but it's empty or it doesn't have required files for a valid theme,
you get "Broken themes" list at the end of all installed themes.
![screenshot from 2016-05-23 16-57-01](https://cloud.githubusercontent.com/assets/390700/15474977/c0619a74-2107-11e6-9064-64fa32dcfbc8.png)

So wp admin knows that something is broken with that theme.

1. Forcing the install of the theme should be successful. So I could override **broken** theme as Wordpress admin says. This currently doesn't work.

2. Optionally, `wp theme status` should detect broken theme.

**Comment by danielbachhuber** [comment]
> Forcing the install of the theme should be successful. So I could override broken theme as Wordpress admin says. This currently doesn't work.

It seems to work for me (6c44f2703a09e9507634ac8b020f715fe56855ba):

```
salty-wordpress ➜  wordpress-develop.dev  wp theme delete myth
Success: Deleted 'myth' theme.
salty-wordpress ➜  wordpress-develop.dev  mkdir src/wp-content/themes/myth
salty-wordpress ➜  wordpress-develop.dev  wp theme install myth --force
Installing Myth (1.0.3)
Downloading install package from https://downloads.wordpress.org/theme/myth.1.0.3.zip...
Using cached file '/home/vagrant/.wp-cli/cache/theme/myth-1.0.3.zip'...
Unpacking the package...
Installing the theme...
Removing the old version of the theme...
Theme updated successfully.
```

Are you sure you included the `--force` flag? And, are you sure your shell user can actually delete the directory?

**Comment by ivandotv** [comment]
It appears that there is a problem with mounted directories in docker, which has nothing to do with `wp-cli` 
The `wp-cli` code works correctly, I can delete, and `--force` install the theme.
