### ISSUE TITLE
login link just like drush user-login

### ISSUE THREAD

**Issue by guaka** [wp-cli/wp-cli#2803]
[`drush uli`](http://drushcommands.com/drush-9x/user/user-login/) gives me a convenient way to log in to a Drupal site as an administrator. It would be nice to have the same with `wp-cli`.

**Comment by danielbachhuber** [comment]
See https://github.com/runcommand/one-time-login

Because WP-CLI isn't executed in web requests, the feature needs to be a plugin that's activated by WordPress.
