### ISSUE TITLE
Using WP-CLI for configurating a plugin?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [wp-cli/wp-cli#2804]
Hi! I want to know if there is some way to configure a plugin using wp-cli.

I mean something like: `wp configure-plugin my-plugin-name set plugin-option-name true`

I'm developing a plugin and could be nice to set some values from CLI.

Thanks in advance!

**Comment by danielbachhuber** [comment]
@IAmJulianAcosta Take a look at the [Commands Cookbook](http://wp-cli.org/docs/commands-cookbook/) for details on how to write your own command.

If you wanted to write WP REST API endpoints for your plugin instead, [RESTful WP-CLI](https://github.com/danielbachhuber/wp-rest-cli) will dynamically make them available at the command line, and will eventually be a feature of WP-CLI.
