### ISSUE TITLE
Question/request "Reset files" command

### ISSUE THREAD

**Issue by crissoca** [wp-cli/wp-cli#2807]
Is it possible/viable to create a "reset plugin" or "reset core" command?

Not sure if you've seen this option that sucuri has to reset or re-install a plugin in case you think the plugin was compromised.

I'm aware of the commands delete and install but it will be faster to have a command that bundles the functions in one, maybe even to compare the installed version and get the same version, in case it's needed.

**Comment by danielbachhuber** [comment]
How would this be different than `wp plugin install <slug> --force`, or `wp core download --force` ?

**Comment by crissoca** [comment]
It will keep the same version as it's installed and not get the latest version.

This is useful for people that somehow got issues with the latest versions and break their sites with latest updates.

**Comment by danielbachhuber** [comment]
Ok.

For both `wp core download` and `wp plugin install`, you can specify `--version` to forcefully install a specific version.

To produce exactly the behavior you're describing in one command, I'd recommend [writing a custom command](http://wp-cli.org/docs/commands-cookbook/).
