### ISSUE TITLE
Adding success/error message in wp db query command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2814]
When I tried this following command, there was no any information whether task was completed successfully or there was some error. Adding some feedback message would be great I believe.

`wp db query < myfile.sql`

**Comment by danielbachhuber** [comment]
> When I tried this following command, there was no any information whether task was completed successfully or there was some error.

Don't you get an error from MySQL when there's an error?

```
salty-wordpress ➜  wordpress-develop.dev  wp db query 'FOO BAR;'
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FOO BAR' at line 1
```

**Comment by ernilambar** [comment]
Ah. I checked with incorrect SQL command and it displayed error. Should we assume success if no message displayed in the command run? Or adding success message would be any beneficial?

**Comment by danielbachhuber** [comment]
> Should we assume success if no message displayed in the command run?

Yes.
