### ISSUE TITLE
Method for clearing object caches which are not available on the command line

### ISSUE THREAD

**Issue by markjaquith** [wp-cli/wp-cli#283]
I use my [APC Object Cache](http://wordpress.org/extend/plugins/apc/) plugin on a lot of single-server installs, and on my locally hosted dev versions thereof. But APC isn't available when PHP runs on the command line. So if I activate a plugin with WP-CLI, then check it through a web server, it won't be activated until I restart PHP or otherwise flush the APC cache.

I'd like to think up a way that this could be done from the command line, so I can run WP-CLI commands, flush out the cache, and then go on my way. As we don't have access to APC, it'll have to involve some sort of command-line-to-WordPress-running-on-a-web-server communication.

Ideas:

1. Trigger an HTTP request that the WordPress install will respond to.
2. Update a flag somewhere in the database, the checking of which on the web server version will somehow skip the cache, and then trigger the flush. Perhaps a direct query on an option.

Any other ideas?

**Comment by danielbachhuber** [comment]
Going with a warning like this:

```
salty-wordpress ➜  wordpress-test.dev  wp --require=cache.php option get home
Warning: Running WP-CLI while the APC object cache is activated can result in cache corruption.
Given the consequences, do you wish to continue? [y/n]
```
