### ISSUE TITLE
`--post__in` is not taking space separated IDs in `export` command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2831]
Re: `wp export`

According to the doc, for `--post__in` parameter, both comma-separated and space-separated IDs are allowed.
`Export all posts specified as a comma- or space-separated list of IDs.`

But `wp export --post__in=1 2` gives error `Error: Too many positional arguments: 2`

Another case:
`wp export --post__in=$(wp post list --post_type=post --orderby=rand --posts_per_page=8 --format=ids)`
This also gives similar error.

**Comment by danielbachhuber** [comment]
You need to quote the values passed to the `--post__in` argument:

```
wp export --post__in="$(wp post list --post_type=post --orderby=rand --posts_per_page=8 --format=ids)"
```
