### ISSUE TITLE
Import progress indicator is inaccurate when WXR is split into multiple files

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#2834]
Given a WXR export that consists of multiple files (for example, one generated by `wp cli export --max_file_size=10`), the current post and total number of posts shown during `wp import` only represents the current file being imported, not the complete export.

**Example:**

Given an `export` directory containing a split WXR export:

```
mysite.wordpress.2000-01-01.000.xml
mysite.wordpress.2000-01-01.001.xml
mysite.wordpress.2000-01-01.002.xml
```

During `wp import /path/to/export`, each post that's processed will display something like the following:

```
-- 1,234 of 5,678
```

However, `5,678` refers to the number of posts in the current file, not the number of posts in all files in the directory. This is very misleading, especially when you're expecting a substantially higher number of posts.

**Comment by danielbachhuber** [comment]
> However, 5,678 refers to the number of posts in the current file, not the number of posts in all files in the directory. This is very misleading, especially when you're expecting a substantially higher number of posts.

What would be your proposed fix?

And, should we just commit @rmccue's new importer to WP-CLI instead?

**Comment by johnbillion** [comment]
> What would be your proposed fix?

I don't have one just yet. An interim solution could be to display the current/total file, eg `1 of 3 files` in addition to the current/total posts. Not ideal though. A complete solution would be to be able to read the total number of posts in all files at the start of the import process, but that would require loading each file into `WP_Import`.

> And, should we just commit @rmccue's new importer to WP-CLI instead?

Need to give it a look :)

**Comment by rmccue** [comment]
> And, should we just commit @rmccue's new importer to WP-CLI instead?

I'm treating the CLI as a first-class interface (alongside the web UI), so should be no need for anything special from your end. I wouldn't use it in production until it's ready though :)

**Comment by danielbachhuber** [comment]
@rmccue How would you feel about bundling it by default in a month or so, similar to how WP-CLI already bundles Nikolay's exporter code?

**Comment by danielbachhuber** [comment]
To fix this issue, going with:

```
-- 1,234 of 5,678 (in file wordpress.1.xml)
```

**Comment by johnbillion** [comment]
That's pretty clear I think. An indication of the total number of files would be a bonus.
