### ISSUE TITLE
Standardise on documentation syntax for default values

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#2837]
The default value for various flags are documented with two different syntaxes. Example:

```
Defaults to 10.
```

```
Default: json.
```

One syntax should be decided upon. My preference is for `Default: <value>.`

**Comment by danielbachhuber** [comment]
You should use the functional / declarative format introduced in the most recent release:

```
 * ## OPTIONS
 *
 * <path>
 * : Path to the project that includes a .distignore file.
 *
 * [--format=<format>]
 * : Choose the format for the archive.
 * ---
 * default: zip
 * options:
 *   - zip
 *   - targz
 * ---
```

We could update existing commands to use this as well.

**Comment by johnbillion** [comment]
Awesome, hadn't seen that.

**Comment by ernilambar** [comment]
I have few queries regarding new syntax of default.

* How could I change `Set the database collation. Default: ''` to new syntax?
* For date field like this?
`    
[--post_date=<yyyy-mm-dd>]
: The date of the generated posts. Default: current date
`
* For this type of parameter?
`
[--post_author=<login>]
: The author of the generated posts. Default: none
`

`none` is not the exact value going to pass here. NULL or empty string will be used I believe.

**Comment by danielbachhuber** [comment]
> How could I change Set the database collation. Default: '' to new syntax?

```
---
default:
---
```

> For date field like this

We can ignore that one for now.

> For this type of parameter?

```
---
default:
---
```

**Comment by danielbachhuber** [comment]
@ernilambar Are we getting close to completed on this?

**Comment by ernilambar** [comment]
Apart from few instances which we ignored after discussion, I would say this ticket can be closed. When we are at new decision for those undecided format, we can create new ticket fot those.

**Comment by danielbachhuber** [comment]
👍
