### ISSUE TITLE
Audit command messages for sentence ending character

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2848]
While I am fixing examples in command docs, I noticed that generally success/error message ends with `.` (full stop). But few are not. 
Example: 
`wp widget move` - `Widget moved.`
`wp widget deactivate` - `Widget(s) deactivated`

I found few other places with missing sentence ending sign.
* CLI - `update`
* CLI - `get_updates`
* Comment - `set_status`
* Comment - `recount`
* Widget - `deactivate`

Will it be worth fixing those? Or we would want to keep it like now as this is not critical issue?

**Comment by danielbachhuber** [comment]
> Will it be worth fixing those? Or we would want to keep it like now as this is not critical issue?

Sure, I'd be open to making sure we always include a trailing period.

**Comment by ernilambar** [comment]
First pass completed. Closing ticket now. If any new issue found then we can deal in new tickets.
