### ISSUE TITLE
Timeouts ?

### ISSUE THREAD

**Issue by chrisschaub** [wp-cli/wp-cli#2873]
Are there any timeouts that would come into play for a wp eval job running other than the php.ini settings? We have a job that runs to completion when logged in via shell, running by hand. But via cron, the job dies 3/4 of the way through. There seems to be a hard coded 10 minutes in the cli code -- anyway to override? Thanks for any help.

**Comment by danielbachhuber** [comment]
> Are there any timeouts that would come into play for a wp eval job running other than the php.ini settings?

Not that I'm aware of, no. To verify, you've been inspecting the php.ini for PHP-CLI, not whatever your web worker is? PHP-CLI uses a separate php.ini

> We have a job that runs to completion when logged in via shell, running by hand. But via cron, the job dies 3/4 of the way through. There seems to be a hard coded 10 minutes in the cli code -- anyway to override?

There aren't any hardcoded timeout values in WP-CLI. Can you share more details about your script, where you've added error logging, and what that error logging indicates?
