### ISSUE TITLE
Write a guide to "Shell friends of WP-CLI"

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#2876]
For those new to the command line, there are a number of shell-isms that make working with WP-CLI all the more powerful. Our existing [shell tips](http://wp-cli.org/docs/shell-tips/) is too unfocused; it would be nice to have a guide that documented our shell friends in a super newbie-friendly way.

Specifically, I'm referring to:
- CTRL + R for searching through bash history
- Chaining commands with `$()`
- Use of `xargs`
- Defining aliases in your `.bashrc`
- Piping both STDOUT and STDERR to a log file

"Shell friends" -> super user-friendly introduction to a half-dozen of the most common shell usage patterns.

**Comment by christ0ph3r** [comment]
"CTRL + C for searching through bash history"

I think you meant to say Control + R for searching?  Control + C usually cancels programs.

**Comment by ernilambar** [comment]
Few examples are collected. It will be helpful may be. https://gist.github.com/ernilambar/7ffddef287004ee16f224685253625b6

**Comment by danielbachhuber** [comment]
> I think you meant to say Control + R for searching? Control + C usually cancels programs.

Yes, you are correct. Updated.

> Few examples are collected. It will be helpful may be.

Thanks!

**Comment by andreiglingeanu** [comment]
Some helpful ones I use every day (tested only on OS X):

[kill-all-php-servers](https://gist.github.com/andreiglingeanu/7ffa8ada8adbcee3467ca54017c676ad)

[start unyson testing](https://gist.github.com/andreiglingeanu/311f1857050271b39a5034d17d287a7c)

The last one will download wp, and Unyson framework for it. Basically it will create a full featured working environment in a couple of seconds.

**Comment by myselfhimself** [comment]
The use of `--yes`

**Comment by danielbachhuber** [comment]
Actually, I think this would go well in our existing Quick Start doc.
