### ISSUE TITLE
PHP notice in comment untrash command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2917]
I get this notice in 0.23 and latest nightly version also.

$ wp comment trash 1
Success: Trashed comment 1.
$ wp comment untrash 1
PHP Notice:  Undefined index: SERVER_NAME in /var/www/staging.dev/public_html/wp-includes/pluggable.php on line 1466
Notice: Undefined index: SERVER_NAME in /var/www/staging.dev/public_html/wp-includes/pluggable.php on line 1466
Success: Untrashed comment 1.

**WP CLI info**
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.16
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/nilambar/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.23.0

**Comment by danielbachhuber** [comment]
> I get this notice in 0.23 and latest nightly version also.

WordPress is attempting to send an email notification about the comment status change: https://core.trac.wordpress.org/browser/tags/4.5.2/src/wp-includes/pluggable.php#L1466

`$_SERVER['SERVER_NAME']` isn't populated on CLI though, so there's an error notice. See https://github.com/wp-cli/wp-cli/issues/785#issuecomment-138040347
