### ISSUE TITLE
Add gpg, sha512 and md5 to releases page

### ISSUE THREAD

**Issue by michaellopez** [wp-cli/wp-cli#2919]
Using Docker and other automated tools it would be a nice thing to have all the signatures and hashes from https://github.com/wp-cli/builds/tree/gh-pages/phar available for each release on https://github.com/wp-cli/wp-cli/releases.

We'd like to pin down to version and upgrade explicitly, but right now we can only automate stable release from https://github.com/wp-cli/builds/tree/gh-pages/phar with GPG signing. If I'm missing something please enlighten me.

**Comment by danielbachhuber** [comment]
> Using Docker and other automated tools it would be a nice thing to have all the signatures and hashes from https://github.com/wp-cli/builds/tree/gh-pages/phar available for each release on https://github.com/wp-cli/wp-cli/releases.

In any particular format, or is simply uploading the signature sufficient?

**Comment by michaellopez** [comment]
@danielbachhuber For our case it is sufficient to upload the hashes and signatures that are available at https://github.com/wp-cli/builds/tree/gh-pages/phar for each release on https://github.com/wp-cli/wp-cli/releases.

This feature request is aimed at having a URL like (for each released version)
- https://github.com/wp-cli/wp-cli/releases/download/v0.23.1/wp-cli-0.23.1.gpg
- https://github.com/wp-cli/wp-cli/releases/download/v0.23.1/wp-cli-0.23.1.md5
- https://github.com/wp-cli/wp-cli/releases/download/v0.23.1/wp-cli-0.23.1.sha512

where we can be sure to get the signatures and hashes for a specific version, not only latest stable from https://github.com/wp-cli/builds/tree/gh-pages/phar

I hope I'm making myself clear :)

**Comment by michaellopez** [comment]
Also, I can't seem to find your public key anywhere...any info on that?

**Comment by danielbachhuber** [comment]
> For our case it is sufficient to upload the hashes and signatures that are available at https://github.com/wp-cli/builds/tree/gh-pages/phar for each release on https://github.com/wp-cli/wp-cli/releases.

Sounds good. I'll begin with the next release.

> Also, I can't seem to find your public key anywhere...any info on that?

Hadn't posted it anywhere, because no one asked for it :)

Here it is: https://github.com/wp-cli/builds/blob/gh-pages/README.md#wp-cli-builds

**Comment by michaellopez** [comment]
@danielbachhuber Great! Thanks.

Can you post that key to a public key server or publish it as a file for download? It helps with automation tools. Thanks.

**Comment by danielbachhuber** [comment]
> Can you post that key to a public key server or publish it as a file for download? It helps with automation tools. Thanks.

Sure: https://github.com/wp-cli/builds/blob/gh-pages/wp-cli.pgp

**Comment by michaellopez** [comment]
@danielbachhuber Great support, thanks. Will test this out when 0.24.0 lands. Leaving it open until then.

**Comment by danielbachhuber** [comment]
This is now complete https://github.com/wp-cli/wp-cli/releases/tag/v0.24.0

**Comment by michaellopez** [comment]
@danielbachhuber Awesome, thanks. I'll try it out when I get a window in my schedule :)
