### ISSUE TITLE
Updating post_content_filtered

### ISSUE THREAD

**Issue by warrenseine** [wp-cli/wp-cli#2921]
I'm using a WordPress Markdown [plugin](https://github.com/hoducha/wp-markdown-editor) that uses `post_content_filtered` to store the Markdown version of the post.

I'd like to update that field from a local Markdown file, but everytime I call:
```bash
wp post update $ID page.html --post_content_filtered="$(<page.md)"
```
the value of `post_content_filtered` is just the HTML content of the post, not the Markdown content, so the content in the editor is also the HTML content, not the Markdown version.

If I manually update the field with a SQL query, the editor shows the Markdown version, but `wp-cli` would be much better. I suppose that `wp_insert_post` triggers a `post_updated` action which must somehow replace the content of the `post_content_filtered` field.

Looking at the [source](https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L101), I don't think `wp-cli` is doing anything wrong. Do you have any idea how I can update that field with `wp-cli`?

**Comment by warrenseine** [comment]
Well, it turns out that I just need to update the `post_content` with the Markdown content, which will be copied to `post_content_filtered` as is, and then converted to the HTML version.

In the end, everything just works magically if I just send Markdown instead of HTML.

**Comment by danielbachhuber** [comment]
👍
