### ISSUE TITLE
`wp cli update` doesn't allow to update from nightly to latest stable

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#2942]
```
$ wp cli update --nightly
You have version 0.23.1. Would you like to update to the latest nightly? [y/n] y
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release

$ wp cli update
Success: WP-CLI is at the latest version.

$ wp cli update --major
Success: WP-CLI is at the latest major version.

$ wp cli update --minor
Success: WP-CLI is at the latest minor version.

$ wp cli check-update
Success: WP-CLI is at the latest version.

$ wp cli update --nightly
You have version 0.24.0-alpha-8a47d33. Would you like to update to the latest nightly? [y/n] n
```

I'm not sure if WP-CLI should support this, but one use case could be that the nightly version doesn't work as expected and so I want to _update_ to the latest stable version. Thoughts?

**Comment by danielbachhuber** [comment]
I'm on the fence too.

One thing we could do to keep the current behavior and support downgrading to a specific version is introduce a `--version=<version>` argument. But, you can also just re-install using cURL, so I'm not sure it's worth adding a new feature.

**Comment by ernilambar** [comment]
I believe adding --version would good enhancement. Say I am at `0.23.0`. Currently it is not possible to go to version `0.22.0`. Or is it possible? I have no detail idea :)

**Comment by ocean90** [comment]
> But, you can also just re-install using cURL, so I'm not sure it's worth adding a new feature.

True, but the same applies for an update. ;)

**Comment by danielbachhuber** [comment]
> True, but the same applies for an update. ;)

Sure, but updating is the majority use case compared to downgrading.

Is there other prior art we could look to that might influence the decision one way or another?

**Comment by voldemortensen** [comment]
Currently you can just do `wp core download --version=<version>` to get down to the right version, this now even deletes unused files between versions.

**Comment by ocean90** [comment]
@voldemortensen For WordPress yes, but this is about wp-cli. :)

**Comment by voldemortensen** [comment]
LOL! 😂   ..._*wanders away*_

**Comment by danielbachhuber** [comment]
I've come to a conclusion on this. Because we have `wp cli update --nightly`, we should also have `wp cli update --stable`, which would take you to the latest stable.
