### ISSUE TITLE
Fatal error "Call to undefined function apply_filters()" with 4.6 trunk

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#2953]
```
PHP Fatal error:  Call to undefined function apply_filters() in /wp-includes/load.php on line 315
PHP Stack trace:
PHP   1. {main}() /bin/wp:0
PHP   2. include() /bin/wp:4
PHP   3. include() phar:///bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///bin/wp/php/WP_CLI/Runner.php:806
PHP   6. require() phar:///bin/wp/php/WP_CLI/Runner.php:858
PHP   7. WP_CLI\Utils\wp_debug_mode() phar:///bin/wp/php/wp-settings-cli.php:59
PHP   8. wp_debug_mode() phar:///bin/wp/php/utils-wp.php:22
```
Caused by https://core.trac.wordpress.org/changeset/37626 and https://core.trac.wordpress.org/changeset/37588

**Comment by deltamualpha** [comment]
Not to be a pest, but when is the release of 0.24.0? This issue renders fresh installs of vip-quickstart impossible: https://github.com/Automattic/vip-quickstart/issues/500

**Comment by danielbachhuber** [comment]
> Not to be a pest, but when is the release of 0.24.0?

[July 27th](https://twitter.com/wpcli/status/739787784144048128)

> This issue renders fresh installs of vip-quickstart impossible:

You can use `wp cli update --nightly` to get a compatible nightly build.

**Comment by infn8** [comment]
For those who get here via google now you can now just run ```wp cli update``` without the ```--nightly``` to fix this.

**Comment by arobbins** [comment]
@infn8 That worked for me, thanks.

**Comment by ioannup** [comment]
I'm sorry, what am I doing wrong? http://i.imgur.com/rBfvQu9.png
