### ISSUE TITLE
How do I: Output errors from core verify-checksums to a file?

### ISSUE THREAD

**Issue by Deaton64** [wp-cli/wp-cli#2955]
Hello,
I have a bash script that runs a core verify checksum against a few sites. I can pipe the output to a file and see the success message if all is well. However, if there are any errors, they are not sent to the file.
Is there something I can do to get the errors in the file so it can be emailed?
Thanks,
David

**Comment by danielbachhuber** [comment]
> I can pipe the output to a file and see the success message if all is well. However, if there are any errors, they are not sent to the file.

Can you share how you're piping output?

**Comment by Deaton64** [comment]
Wow, thanks for the quick reply.
All I'm doing is "wp-cli core verify-checksums --path=$sitename > /tmp/wpcore.txt"

**Comment by wojsmol** [comment]
@Deaton64 use `wp-cli core verify-checksums --path=$sitename &> /tmp/wpcore.txt` see http://tldp.org/LDP/abs/html/io-redirection.html

**Comment by Deaton64** [comment]
Great, that works fine.
Thanks both 👍
