### ISSUE TITLE
Can't access archived/deleted/spam sites

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#2970]
Because of `ms_site_check()` you can't use CLI with a URL for a site which is marked as archived/deleted/spam.

```
wp plugin list --url=https://example.org
Error: This site has been archived or suspended.
```

[`ms_site_check()`](https://github.com/WordPress/WordPress/blob/460f4740a24e8a27fe3f744c36d8921915e6d2b9/wp-includes/ms-load.php#L84-L86) is skipped if the current user is a super admin, but that doesn't work either:

```
wp plugin list --url=https://example.org --user=superadmin
Error: This site has been archived or suspended.
```

`ms_site_check()` is used [here](https://github.com/wp-cli/wp-cli/blob/c1fdcb0ea17138fbe89a7a8062e4b13b1d98f242/php/wp-settings-cli.php#L373) which happens [before the user is set](https://github.com/wp-cli/wp-cli/blob/a9828f8ce90f2a2faf31d0d0e0c6742253a433a0/php/WP_CLI/Runner.php#L867-L870).

But `ms_site_check()` provides a[ `ms_site_check`](https://github.com/WordPress/WordPress/blob/460f4740a24e8a27fe3f744c36d8921915e6d2b9/wp-includes/ms-load.php#L73-L82) filter: Should WP-CLI set it always to a non-null value?

**Comment by danielbachhuber** [comment]
> But `ms_site_check()` provides a `ms_site_check` filter: Should WP-CLI set it always to a non-null value?

This seems like a reasonable assumption to me. When using WP-CLI without the `--user=<user>` argument, the expectation is that you can perform any operation, and those operations aren't run as any user.

> `ms_site_check()` is skipped if the current user is a super admin, but that doesn't work either:
>
> `ms_site_check()` is used here which happens before the user is set.

WP-CLI should be calling `wp_set_current_user()` at roughly the same time WordPress normally does. That it doesn't is a bug.

**Comment by ocean90** [comment]
> WP-CLI should be calling `wp_set_current_user()` at roughly the same time WordPress normally does. That it doesn't is a bug.

Hmm...

1) WP-CLI loads wp-settings-cli.php here: https://github.com/wp-cli/wp-cli/blob/a9828f8ce90f2a2faf31d0d0e0c6742253a433a0/php/WP_CLI/Runner.php#L856-L857
2) WP sets the user here: https://github.com/wp-cli/wp-cli/blob/c1fdcb0ea17138fbe89a7a8062e4b13b1d98f242/php/wp-settings-cli.php#L360
3) WP checks for `ms_site_check()` here: https://github.com/wp-cli/wp-cli/blob/c1fdcb0ea17138fbe89a7a8062e4b13b1d98f242/php/wp-settings-cli.php#L373
4) WP-CLI sets the user based on the `--user` arg here: https://github.com/wp-cli/wp-cli/blob/a9828f8ce90f2a2faf31d0d0e0c6742253a433a0/php/WP_CLI/Runner.php#L867-L870

What am I missing?

**Comment by danielbachhuber** [comment]
> What am I missing?

Sorry? I don't think you're missing anything. WP-CLI should be setting `--user=<user>` earlier, probably early on `init`. WP-CLI is setting the current user too late right now.

**Comment by ocean90** [comment]
My bad, I misread "That it doesn't is a bug." as "This isn't a bug.".
