### ISSUE TITLE
PHP notice when installing child theme

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#2971]
wp theme install https://wordpress.org/themes/download/encrypted-lite-green.0.1.1.zip?nostats=1
Downloading install package from https://wordpress.org/themes/download/encrypted-lite-green.0.1.1.zip?nostats=1...
Unpacking the package...
Installing the theme...
This theme requires a parent theme. Checking if it is installed...
**PHP Notice:  Undefined property: WP_CLI\UpgraderSkin::$api in /var/www/review.dev/public_html/wp-admin/includes/class-wp-upgrader.php on line 1399
Notice: Undefined property: WP_CLI\UpgraderSkin::$api in /var/www/review.dev/public_html/wp-admin/includes/class-wp-upgrader.php on line 1399**
Preparing to install Encrypted Lite 1.3.1...
Downloading install package from https://downloads.wordpress.org/theme/encrypted-lite.1.3.1.zip...
Unpacking the package...
Installing the theme...
Theme installed successfully.
Theme installed successfully.

**Info:**

PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.17
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	/home/nilambar/personal/gitarea/wp-cli
WP-CLI packages dir:	/home/nilambar/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.0-alpha

**Comment by ernilambar** [comment]
Seems to be core issue, rather than CLI issue. https://core.trac.wordpress.org/ticket/36615

**Comment by ocean90** [comment]
@ernilambar That ticket isn't related to your notice. It comes from https://github.com/WordPress/WordPress/blob/4.5.2/wp-admin/includes/class-wp-upgrader.php#L1399.
