### ISSUE TITLE
Impossible to get a user by a numerical user_login

### ISSUE THREAD

**Issue by john-bonachon** [wp-cli/wp-cli#2982]
I was wondering why I couldn't fetch a user by user_login doing `wp user get <user>`. 

My users' user_login values in my system are just numbers, and looking at [this part](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Fetchers/User.php) I realized that you test if the input is numerical then it's the ID.

**Comment by ernilambar** [comment]
Interesting and it is valid use case. But this is not limited to `user get` only. Example `wp post get` only accepts numeric ID. And similar to other several commands.
May be we can introduce new `--type` parameter where it will be like `ID` or `email` or `user_login` or `term` based on command type. If there is no `--type` parameter it will work as it is currently working.

**Comment by danielbachhuber** [comment]
> My users' user_login values in my system are just numbers, and looking at this part I realized that you test if the input is numerical then it's the ID.

This is correct. 

> May be we can introduce new --type parameter where it will be like ID or email or user_login or term based on command type. If there is no --type parameter it will work as it is currently working.

I'm not keen to introduce a parameter for this, to be honest. Given this is the only time the issue has come up in the long time that the feature has existed, I don't think we need to solve for it.

@john-bonachon If you want a workaround for fetching user data, try checking out https://github.com/danielbachhuber/wp-rest-cli which will, hopefully, eventually be the second generation of internals for WP-CLI https://github.com/wp-cli/wp-cli/issues/1784

**Comment by john-bonachon** [comment]
I actually need to update user fields. Their user login is their employee ID, which is why is turned out to be numerical...

Ok. Seems like I'm the only one on this.

**Comment by danielbachhuber** [comment]
The [Commands Cookbook](http://wp-cli.org/docs/commands-cookbook/) should be what you need if you wanted to write a custom command for your project.

**Comment by john-bonachon** [comment]
oh- great!, thanks

**Comment by sclark3-godaddy** [comment]
Following up on this -- there's an interesting workaround that was added by #5738 in WP-CLI 2.8.0 which lets you use `WP_CLI_FORCE_USER_LOGIN=1 wp user update 123456 ...` and other commands that rely on the User fetcher in a way that does not look up the ID when the value is numeric.
