### ISSUE TITLE
Serialized objects break when db server is compiled without pcre utf-8 support

### ISSUE THREAD

**Issue by vdwijngaert** [wp-cli/wp-cli#2985]
In [search-replace.php on line 214](https://github.com/wp-cli/wp-cli/blob/master/php/commands/search-replace.php#L214) there's this code:

    $serialRow = $wpdb->get_row( "SELECT * FROM `$table` WHERE `$col` REGEXP '^[aiO]:[1-9]' LIMIT 1" );

Its value is used to determine whether or not to use PHP for replacing values. This allows to intelligently replace in serialized objects. However, in some cases this mysql error occurs: 

> this version of PCRE is compiled without UTF support at offset 0

This happens when the PCRE version the database is using, is compiled without using UTF support. Currently, a version like this comes bundled with software like XAMPP. 

As a result of this error, the logic assumes that there are no serialized objects and the column is being replaced using the SQL method instead of PHP, in its turn breaking serialized objects (because of length differences).

I agree, it's strange that this error even occurs, but maybe WP-CLI can handle it with a little more grace?

Workaround is adding the `--precise` flag and force using PHP for every replacement, slowing everything way down.

Thanks,

Koen

**Comment by danielbachhuber** [comment]
> I agree, it's strange that this error even occurs, but maybe WP-CLI can handle it with a little more grace?

What change would you suggest?

**Comment by vdwijngaert** [comment]
I also think using a regular expression is the way to go to check for serialized objects. I believe it would hurt overall performance and cleanness to replace this check with something else. Maybe it is enough to just check whether or not the query returned an error (using wpdb's $last_error property?) and fall back to PHP replacement. 

I currently don't have a test environment set up, so I can't supply a pull request right now, but maybe later today or tomorrow.

**Comment by danielbachhuber** [comment]
> Maybe it is enough to just check whether or not the query returned an error (using wpdb's $last_error property?) and fall back to PHP replacement.

Hm. I'm not sure this is precise enough, or that its safe to make this assumption.

Is it possible to check whether MySQL PCRE has been compiled with UTF-8 support?

**Comment by vdwijngaert** [comment]
As far as I can see, this could be accomplished by running pcretest -C and checking for the "No UTF-8 support" string. 

Granted, this could give inconclusive results if a user has multiple AMP stacks installed on his computer, so to make it airtight, one would have to check for the existence of "pcretest", check the right binary is used and finally check for the "No UTF-8 support" string when running the command. Sounds like a lot of work just to check that. 

Does wpdb save the error code? In that case, one can match the code against 1139, that narrows things down to "issues with the regular expression in your query". In which case, I think, WP-CLI should always be prudent and fall back to PHP replacements.

**Comment by danielbachhuber** [comment]
> Does wpdb save the error code?

Yes:

```
salty-wordpress ➜  wordpress-develop.dev  wp shell
wp> $GLOBALS['wpdb']->query( "FOO BAR;" );
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FOO BAR' at line 1 for query FOO BAR; made by include('/home/vagrant/.wp-cli/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Shell_Command->__invoke, WP_CLI\REPL->start, eval
=> bool(false)
wp> $GLOBALS['wpdb']->last_error;
=> string(153) "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FOO BAR' at line 1"
```

> In that case, one can match the code against 1139, that narrows things down to "issues with the regular expression in your query". In which case, I think, WP-CLI should always be prudent and fall back to PHP replacements.

This seems like a safer assumption.

**Comment by danielbachhuber** [comment]
@vdwijngaert Coming back to this, can you sanity check this conditional?

```
if ( ! $php_only && ! $this->regex ) {
	$serialRow = $wpdb->get_row( "SELECT * FROM `$table` WHERE `$col` REGEXP '^[aiO]:[1-9]' LIMIT 1" );
	// MySQL doesn't have PCRE support, so we should fall back to PHP
	if ( false !== strpos( $wpdb->last_error, 'ERROR 1139' ) ) {
		$serialRow = true;
	}
}
```
