### ISSUE TITLE
Site Deactivate does not work?

### ISSUE THREAD

**Issue by srguglielmo** [wp-cli/wp-cli#2986]
Hello,

If I deactivate a site via the netadmin sites list of a WordPress multisite, browsing to the site URL gives the error "This site is no longer available." The site also is listed with a red background in the netadmin sites list. This is all expected.

However, if I use wp-cli to deactivate it (`wp site deactivate $id`), browsing to the site URL still shows the site (not the "no longer available" error). The site, however, does turn to a red background in the netadmin sites list, but browsing to the site still works.

EDIT: WP-CLI 0.23.0 running on RHEL w/ WP 4.5.2

**Comment by danielbachhuber** [comment]
> The site, however, does turn to a red background in the netadmin sites list, but browsing to the site still works.

Are you sure you're not logged in as a super admin in this case?

**Comment by danielbachhuber** [comment]
And, just to follow up, I've tried reproducing the issue but the site is deactivated as expected:

![image](https://cloud.githubusercontent.com/assets/36432/15877512/2c1b44fa-2cc9-11e6-9242-6dfeab0d7440.png)

However, I can still visit the site when logged in as a super admin:

![image](https://cloud.githubusercontent.com/assets/36432/15877536/496c275e-2cc9-11e6-8681-72a10eae5f85.png)

**Comment by srguglielmo** [comment]
Hm, I originally thought this was the issue (I had been using a private browsing window, but I think it still uses cookies from the non-private browsing).

However, I just tried it again and logged out completely, then tried to navigate to the site. I'm getting the same result. Here's what I did:

1. Log in as netadmin.
2. Find a site to test on and determine site ID.
3. Log out.
4. Browse to site. It works.
5. `wp site deactivate $id`
6. Browse to site. It works. Refresh, clear browser cache, still works.
7. Log in as netadmin.
8. Find site (it is marked as deleted now with a red background).
9. Activate site then immediately deactivate site.
10. Log out.
11. Browse to site. It says "This site is no longer available."

**Comment by danielbachhuber** [comment]
Is this on a vanilla install of WordPress, or could there be object caching issues or plugin conflicts at play?

**Comment by srguglielmo** [comment]
It's not vanilla. It's a pretty active site with various plugins and theme modifications. Since you can't reproduce it, I'm going to assume it's an issue specific to my site.

Thanks!
