### ISSUE TITLE
wp plugin list (ant other commands) show content of functions.php from active theme

### ISSUE THREAD

**Issue by flurinduerst** [wp-cli/wp-cli#2989]
`WP-CLI 0.23.1`

When Entering some commands (for example `wp plugin list` or `wp delete theme loremipsum`), right before the command is executed i see the content of the `functions.php` from the currently active theme. It happens using this theme: https://github.com/flurinduerst/WPSeed. It does not occur with a a "twentyfifteen" theme. Although as far as i know, there are no bugs in WPSeed and i have no clue why functions.php gets echoed with the WPSeed theme.

What could be the reason for this?

**Comment by danielbachhuber** [comment]
Sorry, but it's hard to say without knowing how your theme works in depth.
