### ISSUE TITLE
`wp plugin install` when using GitHub URLs, remove -master

### ISSUE THREAD

**Issue by billerickson** [wp-cli/wp-cli#2994]
To install a plugin that is hosted on GitHub but not WordPress.org, I copy the URL for the zip and run `wp plugin install [url] --activate`

GitHub provides a zip of the master branch and the folder name is [plugin name]-master. So when installed, the plugin is named [plugin name]-master.

I think adding a --name parameter for renaming the unzipped directory would work well, but maybe there's a better solution.

Example using [BE Static Subpages Widget](https://github.com/billerickson/BE-Static-Subpages-Widget)

`wp plugin install https://github.com/billerickson/BE-Static-Subpages-Widget/archive/master.zip --activate`

> Success: Plugin 'BE-Static-Subpages-Widget-master' activated.

**Comment by wojsmol** [comment]
The same parameter would be needed for `wp theme install`.

**Comment by szepeviktor** [comment]
See https://github.com/wp-cli/wp-cli/issues/2489

**Comment by pothi** [comment]
At times, having "master" helps to identify if the plugin is installed from w.org repo or from Github.

**Comment by danielbachhuber** [comment]
I'm not sure I want to adopt a special behavior just for Github. Why not create a community package for this?

**Comment by danielbachhuber** [comment]
Couple more considerations I thought of:

* Github actually produces a ZIP file for every branch (e.g. `https://github.com/billerickson/BE-Static-Subpages-Widget/archive/develop.zip`), so you'd need a reliable of identifying the branch name to remove.
* If you've already downloaded the ZIP file, you can install it with `wp plugin install` and I think you'd expect the same behavior of removing `-master`.

Of course, you could produce a community command that only worked for the master branch. I feel reasonably confident installing the master branch is the 80% use case.

**Comment by ernilambar** [comment]
@danielbachhuber Like in Git clone command `git clone <repository> [<directory>]`, we have option of `directory` to which folder we want to clone. Can we add some similar parameter in the command? Then it wont be Github specific and works for any Git URLs.

**Comment by danielbachhuber** [comment]
I've been thinking about this a bit, and would be amenable to adding the feature.

**Comment by nickbreen** [comment]
+1 for @ernilambar's suggestion... specification of the directory is ideal, as it also identifies the plugin in subsequent commands (like activate).

I wrote my own (primitive) equivalents of this for GitHub and for Bitbucket, but only included them in my docker image: https://github.com/nickbreen/docker-wp-setup / php. In this case I renamed the ZIP folder to the name of the repository. This also supports specification of a tag/branch, and for GitHub by default fetches the _releases_ list and chooses the most recent release (rather then master).

Worth considering is that for GitHub we'll also want the option to specify an OAuth token (for private repos, and for rate limiting), and for Bitbucket a key and a secret (for private repos).

**Comment by danielbachhuber** [comment]
> In this case I renamed the ZIP folder to the name of the repository. This also supports specification of a tag/branch, and for GitHub by default fetches the releases list and chooses the most recent release (rather then master).
> 
> Worth considering is that for GitHub we'll also want the option to specify an OAuth token (for private repos, and for rate limiting), and for Bitbucket a key and a secret (for private repos).

These features in particular make most sense as a community package.
