### ISSUE TITLE
Error establishing a database connection in Easy Engine server

### ISSUE THREAD

**Issue by santiazpi** [wp-cli/wp-cli#2995]
When I run a wp user delete command, I am getting an html output error 
...
`<h1>Error establishing a database connection</h1>`
...

When I run wp db query 'SHOW TABLES'; I get the proper output.

Any ideas on how to troubleshoot?

**Comment by szepeviktor** [comment]
Could you run the commands down here?
http://wp-cli.org/docs/bug-reports/
