### ISSUE TITLE
New badges

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#2996]
[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/wp-cli/wp-cli.svg)](http://isitmaintained.com/project/wp-cli/wp-cli "Average time to resolve an issue")

[![Percentage of issues still open](http://isitmaintained.com/badge/open/wp-cli/wp-cli.svg)](http://isitmaintained.com/project/wp-cli/wp-cli "Percentage of issues still open")

Could we have them in the README?

**Comment by danielbachhuber** [comment]
> Could we have them in the README?

What value do you think they provide? I'm not sure how I feel about _quantifying_ whether or not WP-CLI is maintained.

**Comment by danielbachhuber** [comment]
https://gemnasium.com/ could be another useful one

**Comment by szepeviktor** [comment]
Same functionality for free: https://security.sensiolabs.org/check

**Comment by szepeviktor** [comment]
> What value do you think they provide?

Show how fast a user will get help.

**Comment by danielbachhuber** [comment]
Gemnasium is also free.

**Comment by szepeviktor** [comment]
Thank you.
