### ISSUE TITLE
PSR-3 logging

### ISSUE THREAD

**Issue by JPry** [wp-cli/wp-cli#3005]
Has there been any thought given to converting the WP CLI logging classes into PSR-3 compatible loggers? 

One specific use case would be in using WP CLI with 3rd-party libraries, the WP CLI logger could be passed as a logger instance to those other libraries, and seamlessly used alongside another library, such as [Monolog](https://github.com/Seldaek/monolog).

**Comment by danielbachhuber** [comment]
> Has there been any thought given to converting the WP CLI logging classes into PSR-3 compatible loggers?

I had thought this was mentioned once before, but I can't find it. I'd be open to this if we could do so in a backwards-compatible way.

**Comment by danielbachhuber** [comment]
@JPry Is this still worth pursuing? If so, can you provide a suggested implementation?

**Comment by JPry** [comment]
@danielbachhuber Let me see if I can put something together within the next week or so.

**Comment by danielbachhuber** [comment]
Punting on this for now. Would be good to see an example before we commit to implementing the feature.
