### ISSUE TITLE
Add an config option/env var to disable root warning

### ISSUE THREAD

**Issue by c33s** [wp-cli/wp-cli#3018]
currently it is not possible to use bash completion if logged in as root.

```
root@vagrant:~# sudo -u wordpress -i -- wp --infoError: YIKES!
```

```
root@vagrant:~# wp --allow-root Error: YIKES!
```

would be helpful to tell `wp` to permanently allow root (i know that i have to chmod later)

**Comment by danielbachhuber** [comment]
You shouldn't use WP-CLI as root.

**Comment by c33s** [comment]
for example `puppet` will and also handle the chmod/chown stuff.

also if you have only a root user and the rest are very restricted users, it would really help to allow an admin to disable this warning. some of them are knowing what they are doing.

think just closing this and saying "shouldn't do that" is not really a good thing, there are circumstances where it helps and the person who is using your tool knows what he/she is doing. 

its like windows asking me "are you sure?" all the time. thought linux would safe me from forced indoctrinations which i can't disable. :smile: (`rm -rf *` is also dangerous but it works)

**Comment by danielbachhuber** [comment]
> for example puppet will and also handle the chmod/chown stuff.

Sure, I know. 

> also if you have only a root user and the rest are very restricted users, it would really help to allow an admin to disable this warning. some of them are knowing what they are doing.

You could also create a user with sudo privileges, and use that with WP-CLI.

> think just closing this and saying "shouldn't do that" is not really a good thing

Right, but you don't appear to know the historical context for why we've intentionally made it difficult to use `--allow-root`. Given there are alternatives, you should use those alternatives and not use WP-CLI as root.

**Comment by c33s** [comment]
> Right, but you don't appear to know the historical context for why we've intentionally made it difficult to use --allow-root
now you are making me 	curious. bother to tell why?

currently it is possible to use it as root just calling it with `--allow-root` (which i prefer when i work in dev env in vagrant, don't like to care for working with another user), so it is possible. i can create workarounds like making me a wrapper script, compile it myself... and so on. why not making the user choose what he prefers?
there are many webservers out there not using firewalls, wordpress installations without updates, outdated php versions, ... so just adding this warning and prevent user to set an env var to disable that feels, as i wrote before, indoctrinating. 

this often leads to much worse situations than before. for example browsers warn from self signed certs, so users prefer http over https because of the huuuuge warning (thanks letsencrpyt for making that better). anotherone is email encryption, enigmail prevents the user to completely decrypt their emails in the mail browser, because of security, making the user simply not using encryption because the mails are not searchable anymore. 
of course `--allow-root` doesn't really fit in my examples but i think you get what i want to tell you :smiley:

**Comment by samrueby** [comment]
I would like to bump this. When you run WordPress on Azure, using their Alpine/Debian container images, your only option is to be root.
