### ISSUE TITLE
Is it possible to use wp-cli locally to connect to and manager a remote WP install?

### ISSUE THREAD

**Issue by monkeypunch3** [wp-cli/wp-cli#3023]
I have a few WP installs on remote servers hosted at different companies. If I install wp-cli locally, can I connect to and use wp-cli with those remote instances?

**Comment by danielbachhuber** [comment]
Do you have SSH access to those remote servers, and do they have WP-CLI installed?

**Comment by monkeypunch3** [comment]
It looks like a few of them have WP-CLI installed already. So it looks they need to have it installed and then I would need to login to the remote server to use WP-CLI.
