### ISSUE TITLE
Add --porcelain flag for wp db export

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3028]
When using `--porcelain`, `wp db export` should just render the filename for the exported database.

**Comment by ernilambar** [comment]
@danielbachhuber I will try to create patch. But want to ask one question. What should we do if `-` is passed as `file` and also there is `--porcelain`? Which will have higher priority?

**Comment by danielbachhuber** [comment]
> Which will have higher priority?

I'd suggest returning an error if both are provided, with the error explaining why you can't use both.
