### ISSUE TITLE
First pass at a documentation standards page for the website

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3037]
Now that we're making some assertions about documentation format (#2769 #2848), we should start a page on the website to collect details about our documentation standards.

**Comment by ernilambar** [comment]
I have jotted down some points regarding examples.  It could be helpful. https://gist.github.com/ernilambar/7543adac4a50dcc84080cb340bbf1875

**Comment by ernilambar** [comment]
I have added few points regarding command messages. https://gist.github.com/ernilambar/7543adac4a50dcc84080cb340bbf1875#successerror-messages

**Comment by danielbachhuber** [comment]
@ernilambar Up for turning these notes into a website page?

**Comment by danielbachhuber** [comment]
@ernilambar Still want to see this issue through?
