### ISSUE TITLE
WP_CLI\Formatter, mixed LTR and RTL display

### ISSUE THREAD

**Issue by diggy** [wp-cli/wp-cli#3038]
I'm printing out a list of language properties using the WP_CLI Formatter. When a row contains RTL text like Arabic, the terminal picks up the text direction and displays the row accordingly. Looks weird on tables, but renders csv dumps completely useless (I assume).

I'm currently "fixing" the display by prepending a UTF-8 left-to-right mark to the value.

```
foreach ( $languages as $language ) {
    $language->name = "\xe2\x80\x8e" . $language->name;
}
```

I'm wondering however if something (has been or) could be implemented in the core WP CLI package to handle this out of the box.

**Comment by danielbachhuber** [comment]
> When a row contains RTL text like Arabic, the terminal picks up the text direction and displays the row accordingly. Looks weird on tables, but renders csv dumps completely useless (I assume).

Can you share some visual examples, and complete steps to reproduce?

**Comment by diggy** [comment]
Test command here: https://gist.github.com/diggy/163c2672f5a422c32fafc1888de311a9

**Screenshots**

`wp test test --format=table`

![test-table-1](https://cloud.githubusercontent.com/assets/1071337/16177646/015daca2-3634-11e6-8192-2f09668a980f.png)

`wp test test --format=table --ltr=1`

![test-table-2](https://cloud.githubusercontent.com/assets/1071337/16177647/04c106fa-3634-11e6-85cf-0e3968004c04.png)

`wp test test --format=csv`

![test-csv-1](https://cloud.githubusercontent.com/assets/1071337/16177649/0efc55ca-3634-11e6-9b05-1b4cbb800fb3.png)

`wp test test --format=csv --ltr=1`

![test-csv-2](https://cloud.githubusercontent.com/assets/1071337/16177651/143dee90-3634-11e6-8981-63f2c0cfd647.png)

**Comment by danielbachhuber** [comment]
Thanks @diggy 

Just wanted to weigh in that I haven't had a chance to reproduce this, but believe it's probably a problem with php-cli-tools, our upstream library for rendering tables.

**Comment by ernilambar** [comment]
May or may not be related. If post title has Unicode characters, then table format is distorted.
![term](https://cloud.githubusercontent.com/assets/2098823/16546177/07fbabca-4162-11e6-8bd1-51c356b1aa2a.png)

**Comment by danielbachhuber** [comment]
@diggy I wrote a test case for the RTL issue in #3508, which passes locally, so I think PHP parses RTL data in a CSV correctly. Did you find that the CSV wasn't parsed correctly, or just that it looked oddly?

@ernilambar I think https://github.com/wp-cli/php-cli-tools/pull/101 may be the fix. Up for verifying it?

**Comment by ernilambar** [comment]
I checked Unicode with last master branch. Its similar as before.
![workspace 1_001](https://cloud.githubusercontent.com/assets/2098823/20222412/53f4380a-a85d-11e6-8286-07ac04a83ace.png)

**Comment by danielbachhuber** [comment]
@ernilambar Could https://github.com/wp-cli/php-cli-tools/pull/101 be the fix? Any idea why the width is being miscalculated?

**Comment by ernilambar** [comment]
That PR fixed the Chinese. But Nepali unicode is same. It seems good for Arabic letters also. I have no idea how that calculation is done in Devnagari(Nepali, Hindi and similar) letters.
![img2](https://cloud.githubusercontent.com/assets/2098823/20222953/60fcd956-a85f-11e6-8c4c-20529ef6a6b1.png)

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/php-cli-tools/issues/103
