### ISSUE TITLE
wp post list --date_query before array

### ISSUE THREAD

**Issue by grappler** [wp-cli/wp-cli#3039]
I would like to query all post before 2015. I was able to query all posts from 2015 using `wp post list --post_type=post --format=ids --date_query=2015`

How can I make this query using wp-cli?
```
'date_query' => array(
	'before' => array(
		'year' => '2015'
	),
),
```

https://codex.wordpress.org/Class_Reference/WP_Query#Date_Parameters

**Comment by ernilambar** [comment]
To fetch all posts from 2015, command should be similar to
`wp post list --post_type=post --format=ids --year=2015`

Currently query parameters are directly merged with default and passed to the WP_Query call. https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L351 I doubt such type of query is currently possible. May be we can introduce some kind of mechanism where list command accepts multi level query parameters.

`wp post list --post_type=post --format=ids --date_query='{"before":{"year":"2015"}}'`
Just one noob idea :D 

Then we can support `meta_query` and `tax_query` in similar way.

**Comment by danielbachhuber** [comment]
> I doubt such type of query is currently possible. May be we can introduce some kind of mechanism where list command accepts multi level query parameters.

I've considered this in the past, but never identified a syntax I thought worked well.

> Or will this be too much for a single command?

The future of `wp post list` is `wp rest post list`, so I don't think we need to solve the problem here https://github.com/danielbachhuber/wp-rest-cli

**Comment by grappler** [comment]
@danielbachhuber So what I would like to do is not possible with `wp-cli` but is possible with `wp-rest-cli`?

**Comment by danielbachhuber** [comment]
> So what I would like to do is not possible with wp-cli but is possible with wp-rest-cli?

Yes:

```
wp rest post list --after="2014-12-31T23:59:59" --before="2016-01-01T00:00:00"
```

**Comment by tmuka** [comment]
> > So what I would like to do is not possible with wp-cli but is possible with wp-rest-cli?
> 
> Yes:
> 
> ```
> wp rest post list --after="2014-12-31T23:59:59" --before="2016-01-01T00:00:00"
> ```

just to save other people seeing this solution time,  `wp rest post list` is only capable of returning 100 post results at a time... it was more efficient for me to run --year queries for each year's worth of posts i needed to modify.

**Comment by formido** [comment]
> > > So what I would like to do is not possible with wp-cli but is possible with wp-rest-cli?
> > 
> > 
> > Yes:
> > ```
> > wp rest post list --after="2014-12-31T23:59:59" --before="2016-01-01T00:00:00"
> > ```
> 
> just to save other people seeing this solution time, `wp rest post list` is only capable of returning 100 post results at a time... it was more efficient for me to run `wp post list --year` queries for each year's worth of posts i needed to modify.

Pagination makes sense for a network api but for a cli that passes off a ton of complexity onto the user.

**Comment by skorasaurus** [comment]
Since it's been 6 years and there hasn't been active development of wp-rest-cli in the last couple years, so is wp-cli still the more appropriate place for this to be solved? 

If so, looks like this is blocked by https://github.com/wp-cli/wp-cli/issues/4616

**Comment by skorasaurus** [comment]
appears that this is now implemented!  https://github.com/wp-cli/entity-command/pull/520
