### ISSUE TITLE
wp core download with a locale with a fallback

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#3050]
Hi,

It seems there's a delay when the localized version of WP are packaged.
For example en_EN WP is 4.5.3 but bg_BG is 4.5.2 so when I try to download it I get an error.
Is it possible to have another parameter that in case the latest version is not there to go down 1 micro version to 4.5.2 instead ?

```
wp core download --locale=bg_BG
Error: The requested locale (bg_BG) was not found.
```

**Comment by danielbachhuber** [comment]
> It seems there's a delay when the localized version of WP are packaged.

Yes, I believe the localized version isn't packaged until the localization maintainer deems the strings to be ready.

> Is it possible to have another parameter that in case the latest version is not there to go down 1 micro version to 4.5.2 instead ?

Can't you just do `wp core download --locale=bg_BG --version=4.5.2`?

**Comment by wojsmol** [comment]
@lordspace see https://github.com/wp-cli/wp-cli/issues/2435#issuecomment-178812787
