### ISSUE TITLE
Add --porcelain flag for wp export

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3055]
When using `--porcelain`, `wp export` should just render the filename for the exported WXR file. What do you say?

**Comment by danielbachhuber** [comment]
What happens when it generates multiple filenames?

**Comment by ernilambar** [comment]
Ohh, my bad. I got this crazy idea from `And save STDOUT 'Writing to file %s' as {EXPORT_FILE}` in test. I wrapped filename like this `"Writing to file '%s'."` in the command message. I was looking for a way to get exact file name. When wrapped, value of `EXPORT_FILE` came like this `'/tmp/filename.xml'`, expected `/tmp/filename.xml`. I will try out if other method is possible.
