### ISSUE TITLE
unexpected T_STRING failure

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#3059]
All sites work. This is only a wp-cli problem. Updated to nightly to test also. Still fails.

wp-cli works on some sites + fails on a few sites with the error shown below.

My guess is some theme or plugin is slightly broken. Unsure how to debug this, as wp-cli produces insufficient info for debugging.

My question is about how to debug this + fix the offending code.
_______

net4-dev# uname -a
Linux net4.bizcooker.com 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

net4-dev# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

net4-dev# php -v
PHP 5.6.11-1ubuntu3.4 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

net4-dev# wp core version
4.5.3

net4-dev# wp-cli.phar --allow-root --info
PHP binary:	/usr/bin/php5
PHP version:	5.6.11-1ubuntu3.4
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.0-alpha-96a9866

et4-dev# wp-cli.phar --allow-root plugin list
PHP Parse error:  syntax error, unexpected '_' (T_STRING) in phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php(871) : eval()'d code on line 95
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:834
PHP Warning:  mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /sites/.../wordpress/wp-includes/wp-db.php on line 1492
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:834
PHP   6. require() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:892
PHP   7. apply_filters() phar:///david-favor/tools/wp-cli.phar/php/wp-settings-cli.php:91
PHP   8. call_user_func_array:{/sites/.../wordpress/wp-includes/plugin.php:235}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP   9. WP_CLI\Runner->WP_CLI\{closure}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP  10. require_wp_db() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:1008
PHP  11. wpdb->__construct() /sites/.../wordpress/wp-includes/load.php:371
PHP  12. wpdb->db_connect() /sites/.../wordpress/wp-includes/wp-db.php:658
PHP  13. mysqli_real_connect() /sites/.../wordpress/wp-includes/wp-db.php:1492
PHP Warning:  mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /sites/.../wordpress/wp-includes/wp-db.php on line 1492
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:834
PHP   6. require() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:892
PHP   7. apply_filters() phar:///david-favor/tools/wp-cli.phar/php/wp-settings-cli.php:91
PHP   8. call_user_func_array:{/sites/.../wordpress/wp-includes/plugin.php:235}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP   9. WP_CLI\Runner->WP_CLI\{closure}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP  10. require_wp_db() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:1008
PHP  11. wpdb->__construct() /sites/.../wordpress/wp-includes/load.php:371
PHP  12. wpdb->db_connect() /sites/.../wordpress/wp-includes/wp-db.php:658
PHP  13. mysqli_real_connect() /sites/.../wordpress/wp-includes/wp-db.php:1492
PHP Warning:  mysql_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /sites/.../wordpress/wp-includes/wp-db.php on line 1522
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:834
PHP   6. require() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:892
PHP   7. apply_filters() phar:///david-favor/tools/wp-cli.phar/php/wp-settings-cli.php:91
PHP   8. call_user_func_array:{/sites/.../wordpress/wp-includes/plugin.php:235}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP   9. WP_CLI\Runner->WP_CLI\{closure}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP  10. require_wp_db() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:1008
PHP  11. wpdb->__construct() /sites/.../wordpress/wp-includes/load.php:371
PHP  12. wpdb->db_connect() /sites/.../wordpress/wp-includes/wp-db.php:658
PHP  13. wpdb->db_connect() /sites/.../wordpress/wp-includes/wp-db.php:1515
PHP  14. mysql_connect() /sites/.../wordpress/wp-includes/wp-db.php:1522
PHP Warning:  mysql_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /sites/.../wordpress/wp-includes/wp-db.php on line 1522
PHP Stack trace:
PHP   1. {main}() /david-favor/tools/wp-cli.phar:0
PHP   2. include() /david-favor/tools/wp-cli.phar:4
PHP   3. include() phar:///david-favor/tools/wp-cli.phar/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///david-favor/tools/wp-cli.phar/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:834
PHP   6. require() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:892
PHP   7. apply_filters() phar:///david-favor/tools/wp-cli.phar/php/wp-settings-cli.php:91
PHP   8. call_user_func_array:{/sites/.../wordpress/wp-includes/plugin.php:235}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP   9. WP_CLI\Runner->WP_CLI\{closure}() /sites/.../wordpress/wp-includes/plugin.php:235
PHP  10. require_wp_db() phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php:1008
PHP  11. wpdb->__construct() /sites/.../wordpress/wp-includes/load.php:371
PHP  12. wpdb->db_connect() /sites/.../wordpress/wp-includes/wp-db.php:658
PHP  13. wpdb->db_connect() /sites/.../wordpress/wp-includes/wp-db.php:1515
PHP  14. mysql_connect() /sites/.../wordpress/wp-includes/wp-db.php:1522
Error: Error establishing a database connection

**Comment by ernilambar** [comment]
> PHP Parse error: syntax error, unexpected '_' (T_STRING) in phar:///david-favor/tools/wp-cli.phar/php/WP_CLI/Runner.php(871) : eval()'d code on line 95
There seems to be some PHP error in wp-config.php file. Can you please post content of `wp-config.php`. Please remove your password before posting.

**Comment by davidfavor** [comment]
Identified problem.

Debug file was set as...

ini_set( 'error_log', dirname(ABSPATH) . '../logs/wp-debug.log' );

Rather than this...

ini_set( 'error_log', dirname(ABSPATH) . '/logs/wp-debug.log' );

The first path is missing, so an error must have been generated which was quietly suppressed.

Unsure of best message approach. Maybe including the entire error message generated, rather than just "eval()'d code on line 95" might speed up debugging.
