### ISSUE TITLE
Regenerating thumbs might change size/URL despite same settings

### ISSUE THREAD

**Issue by kraftner** [wp-cli/wp-cli#3061]
While looking at an issue with the importer (see https://github.com/humanmade/WordPress-Importer/issues/64) I realized that this also affects WP-CLI. Let me explain:

When regenerating thumbs for attachments created pre WP 4.1 and the change in [#30660](https://core.trac.wordpress.org/changeset/30660) they might end up being one pixel off despite using exactly the same settings for thumb creation. This can break e.g. posts that have used those image sizes.

I think that the only way to fix this is replacing the URLs in `post_content` which I am not sure would be a thing WP-CLI should really do here. If not maybe there should at least be a warning concerning this issue in the docs. So basically I am asking for direction if this is something WP-CLI should be caring about or if it is just to be accepted and might just be warned about in the docs.

**Comment by danielbachhuber** [comment]
This is a pretty nasty bug :(

> If not maybe there should at least be a warning concerning this issue in the docs.

Including a warning in the documentation is a great idea. Could we also potentially perform the calculation ourselves, and indicate a warning to the end user if we detect the image filename will end up differently?

**Comment by kraftner** [comment]
Okay so concerning the docs - is there any example/format how warnings are meant to look/be written for WP-CLI? I couldn't find any examples. And the docs are [generated from the source](https://github.com/wp-cli/wp-cli/blob/4d92a9637599db50c3e0560276d95df9afaeb140/php/commands/media.php#L24-L59), right?

Concerning doing the calculation - yes we could actually. So what we would need to do is for each image calculate the thumb sizes using the current resizing and the legacy version from pre [#30660](https://core.trac.wordpress.org/changeset/30660). Then we can detect mismatches. Probably has some performance impact.
Anyway this only detects *potential* problems. We could of course also scan `post_content` but I think that is more fragile. Also references to the URLs might be in post meta or whatnot. So I think the first approach of potential issues is better.

Maybe if we do this before actually doing any regenerating we can abort with a warning and require a flag to still do the regeneration. What do you think?

**Comment by danielbachhuber** [comment]
> is there any example/format how warnings are meant to look/be written for WP-CLI? I couldn't find any examples.

Nothing specific, no.

> And the docs are generated from the source, right?

Correct.

> Maybe if we do this before actually doing any regenerating we can abort with a warning and require a flag to still do the regeneration. What do you think?

I'm concerned about introducing a confirmation prompt, because this could break any existing use of `wp media regenerate` in a script.

If programmatically checking the existing files looks like it's going to be too complex, then maybe we should just include the warning in the documentation and be done with it. Given this has been a problem since 4.1, it doesn't appear to have been hugely widespread, so maybe we don't need to spend a ton of time on it.

**Comment by kraftner** [comment]
Docs is definitely a good idea. But for that reason totally abandoning the idea of caring in the command - I'm not sure. But your argument not to break existing scripts is of course a strong one.
What if we at least have an option to be defensive about this? If you opt in any performance impact is also less of an issue. I'd have a look into how complex this is unless you can already say you definitely wouldn't merge it.

**Comment by danielbachhuber** [comment]
> What if we at least have an option to be defensive about this? If you opt in any performance impact is also less of an issue. I'd have a look into how complex this is unless you can already say you definitely wouldn't merge it.

"Decisions, not options" :) If we can create some intuitive behavior that doesn't have too much of a performance impact, then I'd be amenable to the improvement. I'm not keen to put it on to the end user, though.

I'm not sure if it's possible, but if we could somehow filter the size values when WordPress is generating the new image size, we could ensure an image retains its original proportions.

**Comment by kraftner** [comment]
Ah, how I love "Decisions, not options" :wink: 

But I get your point and I'll give it some more thought if we can handle it the way you just said. I'll report back when I have more information on that approach.

**Comment by danielbachhuber** [comment]
> But I get your point and I'll give it some more thought if we can handle it the way you just said. I'll report back when I have more information on that approach.

@kraftner Anything to report on how we can address this?

**Comment by kraftner** [comment]
Sorry, not yet. But I have it on my list of issues I want to look into - time permitting.

**Comment by danielbachhuber** [comment]
Ok. Closing as wontfix for now, but can reconsider later if someone wants to submit a PR for it.
