### ISSUE TITLE
Introduce reset subcommand for sidebar

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3063]
Proposal:

`wp sidebar reset <sidebar-id>`

- Cleans up all widgets in the the given sidebar.
- If sidebar ID is not passed, all registered sidebars will be reset.

Technically, reset means moving widgets from sidebar to `Inactive Widgets`.

**Comment by ernilambar** [comment]
This idea comes from my helper tool which I frequently use in the development process.
1. One is reset all sidebars at once.
2. Add widget ( say Text widget ) to every registered sidebars. Widget title be like `Test widget: %d`. %d replaced by sidebar ID. This helps a lot in theme development.

**Comment by danielbachhuber** [comment]
👍
