### ISSUE TITLE
More specifics on what I'm looking for from documentation / support contributors

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3064]
A good number of people replied to my [blog post from Thursday](http://wp-cli.org/blog/future-wp-cli.html), so I thought it might be easier to start a new thread in Github rather than have a dozen 1 on 1 email discussions.

At a high level, I'd like to make the WP-CLI project more sustainable by leveling-up the involvement of existing and new contributors. I could use the most help with documentation, marketing / website branding, and support (in that order), so I'm focusing on these areas first. In considering candidates for the role of maintainer (or some other title TBD), I expect to see consistent, reliable, and earnest involvement over time (e.g. a few hours per week over a period of months).

Becoming a maintainer is a long-term commitment and, honestly, a pretty thankless task. It's mostly the work no one else wants to do. You'll need a significant degree of self-motivation. For more background, [check out my WCEU presentation](https://runcommand.io/2016/06/26/my-condolences-youre-now-the-maintainer-of-a-popular-open-source-project/).

More specifically, there are a [number of documentation issues in the backlog](https://github.com/wp-cli/wp-cli/issues?q=is%3Aopen+is%3Aissue+label%3Ascope%3Adocumentation) that you could start with. I'm happy to provide additional information on them as needed. But, my expectation is that you'll provide leadership in a particular area, identifying a particular focus for a time period and iterating on the work you're doing until the focus is well met. Writing the documentation is one way to go about it, but you could also do some surveying to see what users might be interested in learning more about, or user testing the documentation to make sure it answers the questions it sets out to answer. And so on.

There's also a new [guide to contributing](http://wp-cli.org/docs/contributing/) that you can refer to.

Hit me up with any questions, comments, feedback or violent dissent you might have.

**Comment by jmichaelward** [comment]
Thanks for the link to your WCEU presentation, and specifically for the links to the open documentation issues, Daniel. I think these are great starting points and help clear up a lot of questions I'd had. Hopefully it has helped others, as well.
