### ISSUE TITLE
Provide localized versions of the homepage

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3065]
Now that we have a refreshed homepage (#2760), it would be great if we provided a few localized versions of it for non-English speakers. Let's focus on the homepage now as a more easily obtainable goal.

@ixkaito started an i18n implementation for WP-API (https://github.com/WP-API/docs-v2/pull/156) that we can crib from.

**Comment by miya0001** [comment]
Will localized homepages have their own repository?

For example:
* URL: ja.wp-cli.org
* Repo: https://github.com/wp-cli/ja-wp-cli.org

I feel it will be easy for people who isn't a programmer, so they can translate just clicking the edit button on the GitHub. :)
I can say to everybody "hey Japanese people! I want to translate it! Help me!". 😄 

But tracking changes of the original documentation will seem to be difficult.

**Comment by miya0001** [comment]
I found the translation guide of the ghost.
http://docs.ghost.org/translations/

**Comment by danielbachhuber** [comment]
> Will localized homepages have their own repository?

In the interest of keeping things simple, I'd prefer to just keep to one repository for now. Additional complexity is complexity I have to maintain long-term.

> I feel it will be easy for people who isn't a programmer, so they can translate just clicking the edit button on the GitHub. :)

Sure, we can do the same. For now though, let's just focus on making the homepage available in a few different languages.

**Comment by miya0001** [comment]
> let's just focus on making the homepage available in a few different languages.

Thanks, I felt that the way of the Ghost project is simple.
I will try to translate using their approach after a couple of days. 😄

**Comment by shulard** [comment]
I think I can help with french, how can I start the translation ?

**Comment by mustafauysal** [comment]
Here is Turkish homepage – https://gist.github.com/mustafauysal/1a8340711b3886ac81775a40740dd7c8

**Comment by danielbachhuber** [comment]
Any volunteers for setting up the Jekyll functionality to provide translations?

**Comment by miya0001** [comment]
I'll send a PR to provide translations today.
That will include,
* Menu for translations
* Translation example
* Readme of the workflow to translate

**Comment by miya0001** [comment]
I've sent PR.
How does everybody feel about it?
https://github.com/wp-cli/wp-cli.github.com/pull/162

**Comment by danielbachhuber** [comment]
@miya0001 Looks good to me! How about the others that will be providing translations? Are you happy with this implementation?

**Comment by shulard** [comment]
It seems nice to me.

(only the jQuery thing that hurt me a little :smile:, I don't think we need it)

**Comment by danielbachhuber** [comment]
@shulard @mustafauysal Want to have a go at translating? If you want to refactor the JS to not use jQuery, I'd be open to that too.

**Comment by shulard** [comment]
Ok I'll take a look very soon !

**Comment by shulard** [comment]
I've submited the PR :

* wp-cli/wp-cli.github.com#165
* wp-cli/wp-cli.github.com#166

**Comment by danielbachhuber** [comment]
Thanks everyone for your work on this so far! Couple of follow-up things from me:

Does someone want to style the language selector so it doesn't stand out so much in the header?

Also, here's our top 15 languages, according to Google Analytics:

![image](https://cloud.githubusercontent.com/assets/36432/16535710/798ea03c-3f9e-11e6-85ca-e74c2ead66cd.png)

It would be cool if we could get translations for:

* German
* Spanish
* Portuguese
* Russian
* Dutch
* Italian

**Comment by taianunes** [comment]
Hi @danielbachhuber, me and @bordoni will take care of pt-br translation!

**Comment by mustafauysal** [comment]
I've submitted PR for Turkish language pack: https://github.com/wp-cli/wp-cli.github.com/pull/169
(sorry for delay)

**Comment by andreascreten** [comment]
Will try to do the Dutch this week.

**Comment by shulard** [comment]
Hello !

I think it's an interesting approach but why using JavaScript in the browser to translate that strings ? I think that adding a dictionary in YML and using it will be more effective (the compiled version of Jekyll pages will be directly translated)...

**Comment by bordoni** [comment]
The problem is that we could end up with huge `_config.yml` files, where with this method we can place the strings on the Folder, as well as having a Original File (`.dist`) to allow new languages to follow.

**Comment by shulard** [comment]
You can do exactly the same thing in Jekyll, with data files : https://jekyllrb.com/docs/datafiles/
We can create a _data/{lang} which will contains all localizations.

With a JS translation system, we don't help Google and others search engines viewing the right labels (maybe they can interpret JS, maybe only some JS, maybe no JS...) and I think it can became an issue...

**Comment by bordoni** [comment]
Actually, you are are right, so what would be the best way to store these strings?
Folders as `_data/l10n/{lang}` and contents:
```
- {string}: {translations}
```

**Comment by shulard** [comment]
It seems a nice pattern. For me the `lang` must be the "ISO alpha2" to avoid collision on user defined keys : https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

Then we can access with something like `{{site.data.l10n[isoCode].stringToBeTranslated}}`

I already submitted a PR (wp-cli/wp-cli.github.com#193) which retrieve the iso based on current path. You can check that here: https://github.com/wp-cli/wp-cli.github.com/pull/176/commits/bc819d5ec4eb755993b507ca8e0c45a1a3e65488#diff-822e9cf54ee310f9a7ebd0d16c9ae066R1

I don't know if it's the cleaner way to do that but it works :smile:

**Comment by chantalcoolsma** [comment]
I can help with Dutch.

**Comment by danielbachhuber** [comment]
Can we get Spanish, Russian, Dutch, and Italian by next week?

Also, for those providing homepage translations, what's the best way to alert you when there are changes to be made (which hopefully won't be too often)?

**Comment by shulard** [comment]
Hello !

Maybe you can make a group of "translators" and ping them in an issue when there are some changes to be made, I think it's the simplest way to get notified...

**Comment by alessandrotesoro** [comment]
I'd be happy to help with the Italian translation, there's just a problem, I'm going on holiday next week and I'll be back end of August. If by then you haven't found anybody, just let me know 👍

**Comment by taianunes** [comment]
Hi @danielbachhuber, we already have a "translators" group for notifications?

**Comment by danielbachhuber** [comment]
> we already have a "translators" group for notifications?

I started one last week. I've gone ahead and invited everyone on this thread to it.

**Comment by taianunes** [comment]
Sorry, found mail now. Thanks! 👍

**Comment by danielbachhuber** [comment]
I've created new issues for the remaining languages.
