### ISSUE TITLE
Can I provide a path for installed packages?

### ISSUE THREAD

**Issue by dsXLII** [wp-cli/wp-cli#3072]
I'd like to install a few packages, and (more important) put them somewhere that others can use them, without requiring all my fellow admins to do a number of 'package install' commands.

I already have a "shared" wp-cli.yml file (in my case, it's in /var/www/html). I'd like to be able to add to that file a hypothetical "packages_location: /var/www/html/wp-cli-packages" line, and have packages loaded from this alternate location instead of/in addition to from ~/.wp-cli/packages/ .

**Comment by danielbachhuber** [comment]
@dsXLII Going forward, I'm using the new [Excerpts feature on the runcommand website](https://runcommand.io/excerpts/) to provide point by point documentation on questions such as this one.

Here's the answer I put together for you: https://runcommand.io/to/shared-wp-cli-packages/

Let me know what you think, and whether there's any follow-up clarification I can provide.
