### ISSUE TITLE
Error in menu list command when format is ids

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3074]
`wp menu list --format=ids`
Output:
`
PHP Catchable fatal error:  Object of class WP_Term could not be converted to string in /home/nilambar/personal/gitarea/wp-cli/php/WP_CLI/Formatter.php on line 129
Catchable fatal error: Object of class WP_Term could not be converted to string in /home/nilambar/personal/gitarea/wp-cli/php/WP_CLI/Formatter.php on line 129
`

CLI Info:

PHP binary: /usr/bin/php5
PHP version:    5.5.9-1ubuntu4.17
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:    /home/nilambar/personal/gitarea/wp-cli
WP-CLI packages dir:    /home/nilambar/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.0-alpha

**Comment by apertureless** [comment]
Seems to be a bug in the formatter not in the menu list command. 
Because it appears also on other list commdands 

    f.e. wp post-type list --format=ids
