### ISSUE TITLE
Language case sensitive

### ISSUE THREAD

**Issue by phh** [wp-cli/wp-cli#3078]
I'm not sure if this is really a "bug" but.

nb_no cannot be found
```
vagrant@vvv:/vagrant/www/bp-product-search$ wp core language install nb_no
Error: Language 'nb_no' not found.
```

It has to be named exactly nb_NO
```
vagrant@vvv:/vagrant/www/bp-product-search$ wp core language install nb_NO
Success: Language installed.
```

Is there a reason why these has to specified exactly like that or does it have more to due how WP fetches the languages?

**Comment by danielbachhuber** [comment]
> Is there a reason why these has to specified exactly like that or does it have more to due how WP fetches the languages?

It has to be specified as `nb_NO` because that's [what the locale string is](https://make.wordpress.org/polyglots/teams/), and it's case sensitive.
