### ISSUE TITLE
wp user import-csv with user metadata

### ISSUE THREAD

**Issue by cclass** [wp-cli/wp-cli#3079]
Are there any plans to allow importing of user metadata from a CSV using `wp user import-csv` or perhaps a new command such as `wp user meta import-csv`?

We're migrating to a new membership system and are in the process of moving all of the user accounts on our old system to the new one – nearly 10,000 users with additional metadata that also needs to be imported (billing details, settings, etc). Using wp-cli would make this process far easier and more reliable than a normal WordPress plugin.

I see there is `wp user meta set` and `wp user meta update` but as far as I can gather this doesn't allow for a bulk set or update of user meta data.

**Comment by danielbachhuber** [comment]
> Are there any plans to allow importing of user metadata from a CSV using wp user import-csv or perhaps a new command such as wp user meta import-csv?

No plans, see https://github.com/wp-cli/wp-cli/pull/1855#issuecomment-106920207

> I see there is wp user meta set and wp user meta update but as far as I can gather this doesn't allow for a bulk set or update of user meta data.

Correct. 

You can [write a custom command](http://wp-cli.org/docs/commands-cookbook/) to do what you need with the migration task.

**Comment by cclass** [comment]
cheers @danielbachhuber
