### ISSUE TITLE
Error in menu location list command when format is ids

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3083]
Error similar to https://github.com/wp-cli/wp-cli/issues/3074

`wp menu location list --format=ids`

PHP Catchable fatal error:  Object of class stdClass could not be converted to string in /home/nilambar/personal/gitarea/wp-cli/php/WP_CLI/Formatter.php on line 129
Catchable fatal error: Object of class stdClass could not be converted to string in /home/nilambar/personal/gitarea/wp-cli/php/WP_CLI/Formatter.php on line 129

**Comment by apertureless** [comment]
Well isn't ids just an unsupported format? Because... does menu locations have ids ?

**Comment by ernilambar** [comment]
Personally, `ids` should not be necessarily numeric ID. It could be unique key for the object which could be used to manipulate data.

Example: in `sidebar list`, output will be like `sidebar-1 footer-1 footer-2`.
Another example:
`wp widget list sidebar-1 --format=ids`
Sample output:
`search-2 recent-posts-2 recent-comments-2`

So, may be we need to fix error by adding support rather than removing support. :smile:

**Comment by danielbachhuber** [comment]
> It could be unique key for the object which could be used to manipulate data.

So the `location`?

**Comment by ernilambar** [comment]
> So the `location`?

In this case, yes.

**Comment by ernilambar** [comment]
@apertureless Will you be available to create new PR for this? 

Command:
`wp menu location list --format=ids`.

Output would be similar to `primary footer social`. 
`location` values separated by a space.

**Comment by apertureless** [comment]
@ernilambar oh now I see what you mean. 

Yeah sure, will change it.

**Comment by apertureless** [comment]
@danielbachhuber can be closed I guess.
