### ISSUE TITLE
Introduce `-ids` value for `format` parameter in site list command

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3085]
Command:

`wp site list --format=ids`

Sample output:

`1 2 3`

Blog IDs will be displayed separated by space.

**Comment by voldemortensen** [comment]
I don't do anything with multisite, but wouldn't
`wp site list --field=id`
do the same thing?

**Comment by ernilambar** [comment]
Yes, we can get similar with this command.
`wp site list --field=blog_id`
Output:
1
2
3

We can live with that as output is similar. And it can be fed to `xargs` with `\n` separator. But for parity also we could add it.
Adding this will make this type of command more breeze. 
`wp site archive $(wp site list --format=ids)`

Just my 2 cents :smile:

**Comment by danielbachhuber** [comment]
> But for parity also we could add it.

I'm amenable to this.
