### ISSUE TITLE
Test whether "Tested up to" is up to date

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3086]
*Please keep this 'good-first-issue' for a first time contributor if possible. Thanks!*

When scaffolding plugin tests, it would be cool to include a PHPUnit test to determine whether the "Tested up to" value in the `readme.txt` is up to date.

This value getting out of date is a common problem for many WordPress plugins, so we could help alter plugin authors to when their readme is out of date.

**Comment by ernilambar** [comment]
Tested upto parameter is going to be deprecated after new release of Plugins Directory. After that, it can be managed from the admin panel.

http://prnt.sc/bnbw06

**Comment by johnbillion** [comment]
I actually removed these tests from my own plugins because they cause otherwise passing builds to fail after every minor and major WP version is released.

Refs:
 * https://github.com/johnbillion/user-switching/commit/f7963b8841e679c1a22737e971af02ad5211d31e
 * https://github.com/johnbillion/query-monitor/commit/26defd396d73b9ee355aa60f82c50e40b81881fa

**Comment by danielbachhuber** [comment]
> Tested upto parameter is going to be deprecated after new release of Plugins Directory.

@ernilambar Should we just go ahead and remove it from the default `readme.txt` ?

**Comment by ernilambar** [comment]
May be we should wait until new Plugins directory is live. Lets keep as it is for now.

**Comment by danielbachhuber** [comment]
> When scaffolding plugin tests, it would be cool to include a PHPUnit test to determine whether the "Tested up to" value in the `readme.txt` is up to date.

Closing the issue because this original premise is now invalid. We can remove the "Tested up to" when it's deprecated by the Plugin Directory.
