### ISSUE TITLE
Command message according to the output number

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3103]
Command:
`wp cron event run --due-now`

Output:
`Success: Executed a total of 2 cron event(s).`

Since we already know the exact value of events in the command, it would be better UX if we could display message according to the number.

`Success: Executed a total of 1 cron event.`

`Success: Executed a total of 2 cron events.`

Since we are using such messages in several commands, we would have to audit all commands.

**Comment by ernilambar** [comment]
@danielbachhuber  https://github.com/wp-cli/wp-cli/pull/3111 is not related to this issue, I believe.

**Comment by danielbachhuber** [comment]
> is not related to this issue, I believe.

You are correct.

**Comment by ernilambar** [comment]
ToDos

[ ] `search-replace` in dry run mode
[ ] `widget delete`
[ ] `widget deactivate`
[ ] `widget delete`
[ ] `theme mod remove`
[ ] `menu item delete`

**Comment by ernilambar** [comment]
Closing ticket. :smile:
