### ISSUE TITLE
ALTERNATE_WP_CRON can trigger a redirect on the CLI

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#3104]
If the `ALTERNATE_WP_CRON` constant is defined on a site, any CLI command can potentially fail due to the cron spawner attempting a redirect (which gets caught by `WP_CLI\Utils\wp_redirect_handler()`).

WP-CLI can avoid this with the following:

```
if ( defined( 'ALTERNATE_WP_CRON' ) && ALTERNATE_WP_CRON ) {
    remove_action( 'init', 'wp_cron' );
}
```

Not sure where best to place this, and also I'm wondering whether WordPress core should add some extra logic to [this condition](https://github.com/WordPress/WordPress/blob/1d13c64927a0efa557be4e7df9446ace185f313e/wp-includes/cron.php#L274-L276) so it doesn't attempt a redirect on the CLI.

Thoughts?

**Comment by danielbachhuber** [comment]
Huh, this isn't very fun.

I'd like for us to continue to spawn cron as much as possible, although I suppose in the case of `ALTERNATE_WP_CRON` there's not a ton we can do.

> Not sure where best to place this

The end of `WP_CLI\Runner->load_wordpress()` is a fine place for it.

> also I'm wondering whether WordPress core should add some extra logic to this condition so it doesn't attempt a redirect on the CLI.

Nah, I think we can accommodate in WP-CLI just fine. We haven't placed any `defined( 'WP_CLI' )` checks in WordPress core yet, and I don't think we should until we absolutely have to.
