### ISSUE TITLE
WP-CLI not working after changing VPS

### ISSUE THREAD

**Issue by timeassistant** [wp-cli/wp-cli#3109]
Hi there,

we changed VPS server and during the change our account name was updated I now have the following issues: 

1)

```
[{NEW username}@server ~]$ wp cli
bash: /home/{OLD username}/wp-cli.phar: No such file or directory
```

How do I update this to the correct path?

2) Also on another domain its just not working at all. How do you fully uninstall wp cli in order to do a completely fresh install from scratch? 

3) Another domain only gives the following output 

[{username}@server root]$ wp --info
PHP binary:     /usr/local/bin/php
PHP version:    5.6.22
php.ini used:   /usr/local/lib/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /home/{username}/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0

but yet I only seem to have a wp-cli.phar file I do not have any other files or locations

How do I correct these issues ?

**Comment by danielbachhuber** [comment]
> How do I update this to the correct path?

If WP-CLI isn't installed somewhere on your `$PATH`, then you'll need to create a symlink on your PATH to the executable, or create an alias.

>  Also on another domain its just not working at all. How do you fully uninstall wp cli in order to do a completely fresh install from scratch?

See https://runcommand.io/to/delete-wp-cli/

> but yet I only seem to have a wp-cli.phar file I do not have any other files or locations

I'm not sure I follow. Can you clarify?

**Comment by timeassistant** [comment]
Thank you for the response, the runcommand.io link was perfect ! I would strongly advise you to add this into the WP-CLI docs as I was struggling for a while to remove the script.

I think I have fixed the problem now but I have fully removed it just to be safe and plan to reinstall. 

The alias for the site that had the wrong path was the issue. WP-CLI never seemed to have been installed to $PATH so it must have been alias only. (i removed the alias for now)

My last comment you quoted now makes sense, I had the wp-cli.phar file in the root dir of the users, and the `/usr/local/bin/wp` was created by root as the sub users cannot move the file to that location. 

The reason one of the sites was working is because it had the correct alias brought over from the old VPS. 

I believe now I can get this corrected but I still have one extra question / issue

When I go to reinstall WP-CLI this command `sudo mv wp-cli.phar /usr/local/bin/wp` does not work as the user as Sudo is not available, So I am wondering will performing `mv wp-cli.phar /usr/local/bin/wp` as root still have the same desired effect if I go and add an alias to each user such as `alias wp='php /home/{USERNAME}/wp-cli.phar'`

Thanks

**Comment by danielbachhuber** [comment]
> So I am wondering will performing mv wp-cli.phar /usr/local/bin/wp as root still have the same desired effect if I go and add an alias to each user such as alias wp='php /home/{USERNAME}/wp-cli.phar'

You should just need to `mv wp-cli.phar /usr/local/bin/wp` as root. Once you've moved the file, `/usr/local/bin` is typically on your PATH, so the `wp` command will become accessible.

**Comment by timeassistant** [comment]
Fantastic thank you !
