### ISSUE TITLE
Support --version=nightly for wp core download

### ISSUE THREAD

**Issue by stephenharris** [wp-cli/wp-cli#3113]
The nightly WordPress version can be downloaded from https://wordpress.org/nightly-builds/wordpress-latest.zip (I'm not aware if there are locale-specific nightly builds).

So in theory `get_download_url()` ([source](https://github.com/wp-cli/wp-cli/blob/3cc0fc180894d4f45ff55433cbc1a705416ffc9b/php/commands/core.php#L1347)) need only be adapted to accept a 'nightly' version argument. 

Assuming there is no locale-specific copies of the nightly builds, should we display an error/warning if the locale is not 'en_US'?

**Comment by danielbachhuber** [comment]
> So in theory get_download_url() need only be adapted to accept a 'nightly' version argument.

The last time I looked into this, it was more challenging than a one-line change. Specifically, `wp core download` is designed around handling `.tar.gz`, which the nightly isn't. If you work on this, be aware it's going to be more involved than you think.

> Assuming there is no locale-specific copies of the nightly builds, should we display an error/warning if the locale is not 'en_US'?

I'm not sure of the expected behavior. What's the actual difference between a locale copy and a normal copy?

**Comment by stephenharris** [comment]
Thanks for the heads up - I seem to remember you raising that point elsewhere, but I couldn't find it. I had thought it might be easier than it probably will be as `get_download_url()` defaults to 'zip', but I see now that wp-cli uses .tar.gz and leverages WordPress to install updates/plugins/themes which use zip.

Digging into Core's upgrader, it boils down to [this function](https://github.com/WordPress/WordPress/blob/c959b63539ce95f1ccc98269958102a013af99de/wp-admin/includes/file.php#L566) which either uses `ZipArchive` or this the `PclZip` class [bundled in core](https://github.com/WordPress/WordPress/blob/c3055cc190a4b09131e12a88c7f904f9f1079066/wp-admin/includes/class-pclzip.php), depending on availability.

I'll first work on the assumption that `ZipArchive` is available, and supporting infrastructures without it can be considered later.

> What's the actual difference between a locale copy and a normal copy?

A locale copy includes the translation files in `wp-content/languages`.
