### ISSUE TITLE
Consolidate wp transient delete-all and wp transient delete-expired to flags

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3116]
*Please keep this 'good-first-issue' for a first time contributor if possible. Thanks!*

Instead of `wp transient delete-all` and `wp transient delete-expired`, we should have `wp transient delete --all` and `wp transient delete --expired`. This is more in line with our other commands.

In making this change, we should make sure to add a backwards compat shim to `WP_CLI\Runner` so prior usage still works.

**Comment by ernilambar** [comment]
It would be great if we target this for 0.24.0.

**Comment by danielbachhuber** [comment]
> It would be great if we target this for 0.24.0.

It's not a critical bug, just a nice to have feature.

**Comment by danielbachhuber** [comment]
@ernilambar Want to pick this one up?

**Comment by ernilambar** [comment]
I will try to prepare PR this weekend.
