### ISSUE TITLE
Media regenerate creates thumbnails larger than original image

### ISSUE THREAD

**Issue by hansgv** [wp-cli/wp-cli#3129]
Hello,

it seems that media regenerate also creates thumbnails larger (in pixel dimensions) than the original image. For example, a '500x500.jpg' image gets a '1024x1024.jpg' thumbnail created (pending a thumbnail that size is established). This doesn't appear logical and AFAIK, Wordpress only creates thumbnail sizes smaller than the original when importing media.

**Comment by danielbachhuber** [comment]
Just to confirm, this issue reproduces on a fresh install of WordPress, with no plugins installed and the Twenty Sixteen theme active? Can you share specific steps to reproduce, including the image you've experienced the error with?

**Comment by hansgv** [comment]
Unfortunately I don't have the means to test on any other setup than the one I currently have and it's not a fresh install or Twenty Sixteen theme. Sorry.

As a matter of fact, I believe there aren't any additional theme or plugin defined thumbnail sizes on a fresh setup. So testing would be kinda pointless, I guess.

**Comment by danielbachhuber** [comment]
Ok. I can't reproduce this issue locally against WordPress trunk. If there's no way for you to track down more details on how to reproduce this, then there's not much we can do to help.
