### ISSUE TITLE
Unable to install the cli

### ISSUE THREAD

**Issue by eracadmin** [wp-cli/wp-cli#3131]
Hello 

Here's the error I've been getting upon installing it. I'm running a cloudlinux machine with CageFS. 
The user itself is in the wheel group and not in the cage.

[root@ip-172-31-5-228 www]# wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
--2016-07-08 19:44:37--  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
Resolving raw.githubusercontent.com... 151.101.24.133
Connecting to raw.githubusercontent.com|151.101.24.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4521939 (4.3M) [application/octet-stream]
Saving to: `wp-cli.phar.1'

100%[============================================================================================>] 4,521,939   9.80M/s   in 0.4s    

2016-07-08 19:44:38 (9.80 MB/s) - `wp-cli.phar.1' saved [4521939/4521939]

[root@ip-172-31-5-228 www]# php wp-cli.phar --info
X-Powered-By: PHP/5.6.23
Content-type: text/html; charset=utf-8

<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, string given in <b>phar:///home/ljcc/public_html/wp-cli.phar/php/WP_CLI/Loggers/Base.php</b> on line <b>47</b><br />
[root@ip-172-31-5-228 www]#

**Comment by eracadmin** [comment]
Also, I'm trying to install globally on my cpanel server. Thanks! Email me at maoz@techtone.ca so I can provide you with SSH access if you need it.

**Comment by danielbachhuber** [comment]
> Here's the error I've been getting upon installing it. I'm running a cloudlinux machine with CageFS. 
The user itself is in the wheel group and not in the cage.

Is this a managed machine? Have you shown the error to your host to see if they might know the cause? It appears to be a PHP misconfiguration issue, but it's hard to know what the issue is without access to the server.

> Email me at maoz@techtone.ca so I can provide you with SSH access if you need it.

Sorry, we don't provide this level of support for the project.

**Comment by moses-moore-spafax** [comment]
Had this problem on a cPanel machine, because /usr/bin/php that cpanel / EasyApache installs is weird.
I had to explicitly call `php-cli wp-cli.phar --info` to get it working properly.

**Comment by DavidAnderson684** [comment]
I had this problem on cPanel too. /opt/cpanel/ea-php56/root/usr/bin/php works but /opt/cpanel/ea-php70/root/usr/bin/php does not (but gives the same output as in this issue).

**Comment by heron-brito** [comment]
> I had this problem on cPanel too. /opt/cpanel/ea-php56/root/usr/bin/php works but /opt/cpanel/ea-php70/root/usr/bin/php does not (but gives the same output as in this issue).

I had this same behavior with cPanel.

**Comment by negrusti** [comment]
for me it was caused by some weird script in place of /usr/local/bin/php from CPanel, removed that and WP-cli started to work

**Comment by presswizards** [comment]
Just dropping by to comment that this worked for me on a custom locked down server when nothing else would:
php-cli wp-cli.phar --info

Thanks for adding that! :-)

Rob

> Had this problem on a cPanel machine, because /usr/bin/php that cpanel / EasyApache installs is weird.
> I had to explicitly call `php-cli wp-cli.phar --info` to get it working properly.

**Comment by Qadisha** [comment]
> 

I know it is an old thread, however still relevant for Cloudlinux + CPanel users. I found @negrusti solution applicable in our environment,
