### ISSUE TITLE
On multisite --url will fallback to the main site if the provided URL does not exist

### ISSUE THREAD

**Issue by stephenharris** [wp-cli/wp-cli#3137]
For a multisite `wp <command> --url=<url>` will run the command in the context of the specified blog with the given URL. However, if that URL does not exist that command is ran in the context of the main site.

Should it instead give an error?

This is obviously a significant breaking change, so should/could we instead provide a 'strict' flag or be able to pass a blog ID which over-rides the selection of the blog?

**Comment by stephenharris** [comment]
For those wanting to check if an blog exists with that URL I have written this rather clunky script:

    # Get the url from the database
    dburl="$(wp --url=${url} option get siteurl)";

    # Check the database URL matches the url we gave it (strip protocol and trailing slash).
    dburl=${dburl#'https://'}
    dburl=${dburl#'http://'}
    dburl=${dburl%'/'}

    cleanurl=${url#'https://'}
    cleanurl=${cleanurl#'http://'}
    cleanurl=${cleanurl%'/'}

    if [ "$dburl" = "$cleanurl" ]; then
        # They match
    else
        # They do not
    fi;

**Comment by danielbachhuber** [comment]
> For a multisite wp <command> --url=<url> will run the command in the context of the specified blog with the given URL. However, if that URL does not exist that command is ran in the context of the main site.
> 
> Should it instead give an error?

Are you sure you're working on a multisite install? There's an explicit [check](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L1076-L1080) and [test](https://github.com/wp-cli/wp-cli/blob/a7ee4ce276fe62b93656deb8dc3af2b05b731844/features/flags.feature#L33) for this scenario.

**Comment by stephenharris** [comment]
I'm not quite sure what the logic is, but that check doesn't fail if the passed url is has the correct domain.

E.g. multisite and example.dev and `--url=example.dev/this-site-doesnt-exist`. I guess this is probably because it's interpreted as page on example.dev.

**Comment by danielbachhuber** [comment]
> E.g. multisite and example.dev and --url=example.dev/this-site-doesnt-exist. I guess this is probably because it's interpreted as page on example.dev.

Oh. And doesn't WordPress core just return a 404 in this case, not a "Site not found" message?

**Comment by stephenharris** [comment]
It does, but the 'current blog' is populated as the main site and it still runs the command. 

So `wp --url=example.dev/this-site-doesnt-exist option get home` returns `example.dev`.

Perhaps this isn't an issue for wp-cli to solve. I had a script to be run across specific sites of a network (to change the theme) and wanted to see what would happen if there was a typo in the url, and it changed the theme of the main site.

**Comment by danielbachhuber** [comment]
> Perhaps this isn't an issue for wp-cli to solve. I had a script to be run across specific sites of a network (to change the theme) and wanted to see what would happen if there was a typo in the url, and it changed the theme of the main site.

I think we need to file this under "be aware of the WP-CLI commands you're running, and how they'll be interpreted." Given `--url=` doesn't explicitly mean "this particular site", but rather "mock a request to this URL", WP-CLI can't make the judgement call that you've entered the value incorrectly.
