### ISSUE TITLE
`wp site list --path=<path>` does not work

### ISSUE THREAD

**Issue by stephenharris** [wp-cli/wp-cli#3138]
When filtering the site lists `--path` is ignored (or throws an error because a WordPress install doesn't exist there). This is because it is used for the path to the WordPress install rather than 'path', the column in the `wp_blogs` table.

**Comment by danielbachhuber** [comment]
Try #3128, which will be introduced in v0.24.0

**Comment by stephenharris** [comment]
That works thanks
