### ISSUE TITLE
Add a --include-columns flag to search-replace

### ISSUE THREAD

**Issue by andyexeter** [wp-cli/wp-cli#3140]
When using the `search-replace` command, it'd be awesome if there was a `--include-columns=<columns>` flag which worked similarly to `--skip-columns=<columns>` except that the search/replace would only be performed on the specified columns.

Currently it appears the only way to do a search and replace on just the `post_content` column of `wp_posts` is to list and exclude every other column in the table with `--skip-columns`.

I'd happily submit a PR for this, but the contributing guide states that an issue should be opened up first.

**Comment by danielbachhuber** [comment]
The idea generally seems reasonable. However, `--include-columns=<columns>` is a bit ambiguous, given two tables can share the same columns.

Is there a syntax we could use to specify the columns of a given table as you're listing tables? e.g. something like `wp search-replace foo bar wp_posts:post_content`

**Comment by andyexeter** [comment]
Is it any more ambiguous than `--skip-columns=<columns>`? If I add a column to the `--skip-columns` flag I would expect it to skip that column in any table the search/replace is being performed in. If I added a column to an `--include-columns` flag I'd expect the opposite of that i.e include that column in any table the search/replace is being performed in (therefore excluding all other columns in that table)

The only issue I can see with your idea about the `wp_posts:post_content` syntax is that table names can contain colons and possibly other characters, so if someone (rather stupidly) added a table to their database  called `wp_posts:post_content`, how would the parser know if the user is referring to that table or the `post_content` column in the `wp_posts` table? The delimiter would need to be something that's not a valid character in a MySQL table or column name I guess.

**Comment by danielbachhuber** [comment]
> Is it any more ambiguous than --skip-columns=<columns>?

No. My question was more from the perspective of "given where we're at now, making a new decision".

> The only issue I can see with your idea about the wp_posts:post_content syntax is that table names can contain colons and possibly other characters, so if someone (rather stupidly) added a table to their database called wp_posts:post_content, how would the parser know if the user is referring to that table or the post_content column in the wp_posts table? The delimiter would need to be something that's not a valid character in a MySQL table or column name I guess.

Right. The colon was included for the sake of the example. I don't have a better suggestion for a character.

At this point, I'd be fine with introducing an `--include-columns=<columns>` argument.

**Comment by danielbachhuber** [comment]
🚢
