### ISSUE TITLE
Is there way to filter comments by date range

### ISSUE THREAD

**Issue by anantshri** [wp-cli/wp-cli#3143]
I am looking for a way to filter out comments via date range for example from 1-jan-2016 to 30-june-2016 or something like till 30th june 2016.

Specific use case in mind. Auto delete spam comments on monday evening but keep comments in trash or spam which were created after sunday. i.e. run cron on monday to auto delete spam comments but keep comments from monday safe so that those can be reviewed and bundled in next week execution.

any thoughts.

**Comment by danielbachhuber** [comment]
I don't believe there's a way to do this without writing some code, given `WP_Comment_Query` doesn't support any form of date filtering.

See the [commands cookbook](https://wp-cli.org/docs/commands-cookbook/) for more details on writing a custom command.
