### ISSUE TITLE
Hook for creating a new user

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3149]
Could we trigger `edit_user_created_user` on `wp user create`?

**Comment by ernilambar** [comment]
You can use custom hook to commands. See docs https://wp-cli.org/docs/internal-api/wp-cli-add-hook/
 You can check this example for reference. https://runcommand.io/to/wp-site-empty-custom-database-tables/

**Comment by szepeviktor** [comment]
Thank you.
I am waiting for the decision.

**Comment by danielbachhuber** [comment]
> Could we trigger edit_user_created_user on wp user create?

What are you trying to do, and why can't you use an existing action?

One concern with beginning to trigger this action now is that it could cause unexpected behaviors for users, given we haven't been triggering it until now.

**Comment by szepeviktor** [comment]
I've developed a TOTP login solution and I need to set the secret code at each `edit_user_created_user`.

**Comment by szepeviktor** [comment]
Then should I use `wp eval ...`?

**Comment by danielbachhuber** [comment]
Why not use the `wp_insert_user` action?

**Comment by szepeviktor** [comment]
I couldn't find that action.

Do you mean `user_register`?

**Comment by danielbachhuber** [comment]
Oh, I suppose it's `user_register` and `profile_edit`: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/user.php#L1691

**Comment by szepeviktor** [comment]
Thank you!
