### ISSUE TITLE
Backslashes are eaten 

### ISSUE THREAD

**Issue by TimothyBJacobs** [wp-cli/wp-cli#3152]
Backslashes are eaten by the post command.

`wp post create --post_title="My\Post" --post_content="My\Best\Post"`

```
+--------------+------------+
| Field        | Value      |
+--------------+------------+
| post_content | MyBestPost |
| post_title   | MyPost     |
+--------------+------------+
```

Backslashes are valid post content and should remain. 

`wp_insert_post()` expects slashed data, so the post command should probably `addslashes` the `$params` before inserting the post. This probably applies to other commands, but I didn't take a deeper look.

**Comment by danielbachhuber** [comment]
Previously #1923

**Comment by TimothyBJacobs** [comment]
I don't think this is ready to close yet, from looking at the code, it looks like this also needs addressing in the other three object commands.

**Comment by danielbachhuber** [comment]
> it looks like this also needs addressing in the other three object commands.

Do they expect slashed data?

**Comment by TimothyBJacobs** [comment]
Yep.

**Comment by danielbachhuber** [comment]
🔨
