### ISSUE TITLE
Import Media To CPT with CLI & Filter Custom Taxonomy

### ISSUE THREAD

**Issue by thatryan** [wp-cli/wp-cli#3153]
I have a lot of Custom Posts that I need to set featured images for, based on a custom taxonomy. I am trying to see if there is a way to do this via wp-cli, I see an example offered there which would let me import and set an image to all posts of the CPT. However I cannot figure out if it is possible to further filter that by a custom taxonomy.

`ATTACHMENT_ID="$(wp media import ~/Downloads/image.png --porcelain)"
wp post list --post_type=post --format=ids | xargs -0 -d ' ' -I % wp post meta add % _thumbnail_id $ATTACHMENT_ID`

Ideally something to the effect of, import `image.png` to all posts of `custom_post_type` that have a custom taxonomy `custom_tax`

Possible? Thank you.

**Comment by danielbachhuber** [comment]
You could filter `wp post list` to a particular custom taxonomy if the custom taxonomy adds a public query var.

For instance, a `location` taxonomy would be:

```
wp post list --location=<location>
```

`wp post list` accepts any arguments that `WP_Query` supports.

> I have a lot of Custom Posts that I need to set featured images for, based on a custom taxonomy.

Is each post meant to be assigned the same featured image, or does each post need a different featured image?

**Comment by thatryan** [comment]
Each post with the same custom tax will have the same featured image, yes.

**Comment by thatryan** [comment]
So this is the args and register part of the function,

`$args = array(
	'labels'                     => $labels,
	'hierarchical'               => true,
	'public'                     => true,
	'show_ui'                    => true,
	'show_admin_column'          => true,
	'show_in_nav_menus'          => true,
	'show_tagcloud'              => false,
);
register_taxonomy( 'system_type', array( 'sqms_prod_select' ), $args );$args = array(
	'labels'                     => $labels,
	'hierarchical'               => true,
	'public'                     => true,
	'show_ui'                    => true,
	'show_admin_column'          => true,
	'show_in_nav_menus'          => true,
	'show_tagcloud'              => false,
);
register_taxonomy( 'system_type', array( 'sqms_prod_select' ), $args );`

and I have a term named "Ductless" slug of "ductless"

I ran this command, 

`wp post list --system_type=ductless`

And return is an empty table. Am I misunderstanding something?

Thank you!

**Comment by danielbachhuber** [comment]
> Am I misunderstanding something?

`wp post list` defaults to `--post_type=post` (as does WP_Query). Try:

```
wp post list --system_type=ductless --post_type= sqms_prod_select --post_status=any
```

**Comment by thatryan** [comment]
Ah gotcha! Makes sense, returns this error, is this WP CLI related?

`Fatal error: Class 'WP_Metadata_Lazyloader' not found in /srv/www/plugin-dev/htdocs/wp-includes/meta.php on line 865`

**Comment by danielbachhuber** [comment]
> Makes sense, returns this error, is this WP CLI related?

Make sure you're [running the latest version of WP-CLI](http://wp-cli.org/#updating).

**Comment by thatryan** [comment]
Sweet, my bad.

Got that going, curious what this line does,

`ATTACHMENT_ID="$(wp media import ~/Downloads/image.png --porcelain)"`
Does that create a local variable to store the image for the next command?

**Comment by danielbachhuber** [comment]
> Does that create a local variable to store the image for the next command?

Yes.
