### ISSUE TITLE
Unable to find PHPUnit code coverage stats

### ISSUE THREAD

**Issue by mariadanieldeepak** [wp-cli/wp-cli#3154]
_Where should I check for the **code coverage** stats when using PHPUnit for WordPress?_

When I execute `phpunit` command to test a WordPress plugin, I'm able to see, if the test cases passed or failed. In my case there were no failures. 

To find the code coverage, I executed `phpunit --coverage-text=./coverage.txt`, the test cases passed but I'm unable to find the `coverage.txt` file to check the actual code coverage stats. A quick search for `coverage.txt` file in plugin's folder using the Windows explorer returned no results. Am I missing something?

**Comment by ernilambar** [comment]
Is this related to WP-CLI? It seems you are asking in general.

**Comment by johnbillion** [comment]
The coverage file will be placed in the root of the plugin directory. However, as ernilambar points out, this is unrelated to WP-CLI.
