### ISSUE TITLE
Support for using the local filesystem with `wp --ssh=<host>`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3162]
When you run a command with `wp --ssh=<host>`, any filesystem operations will happen on the remote file system.

It would be more intuitive to have `--ssh=<host>` proxy the local file system to the remote file system.

For instance, `wp --ssh=<host> db export database.sql` would copy the file into the local file system, instead of leaving it on the remote file system. Similarly, `wp --ssh=<host> db import database.sql` would copy `database.sql` from my local filesystem to my remote file system before running the import.

**Comment by jgraup** [comment]
Similarly, it would be nice to use the alias as a location for rapid deployment.

`wp @local db import @remote`
 
`wp @remote db export @local:/folder/for/my.sql`

I was [playing around with pipes](http://wordpress.stackexchange.com/questions/235879/whats-the-fastest-way-to-locally-import-a-remote-database-using-wp-cli) to do something similar without the filesystem requirement but I only tested locally with a new database;

`echo "$(wp @remote db export -)" | wp @local db import -`

and compression seems like a must for a large DB;

`DB_EXPORT=$(echo "$(wp @remote db export -)" | gzip | base64 -w0); echo "$DB_EXPORT" | base64 -d | gunzip | wp @local db import -`

**Comment by tnorthcutt** [comment]
> Similarly, `wp --ssh=<host> db import database.sql` would copy `database.sql` from my local filesystem to my remote file system before running the import.

What would you then do if you wanted to import an existing `database.sql` file already on the remote filesystem instead of copying from local first? In other words, how would you avoid the proxy? Perhaps you'd need a `--proxy=false` flag?

**Comment by danielbachhuber** [comment]
> What would you then do if you wanted to import an existing `database.sql` file already on the remote filesystem instead of copying from local first?

I'm not sure of the exact semantics of this yet. Implementation suggestions welcome.

**Comment by danielbachhuber** [comment]
I'm going to tackle this as a community package when I'm feeling inspired. I don't think we should make it the default behavior of WP-CLI at this point, if ever.
