### ISSUE TITLE
"cron event list" does not show events with same name

### ISSUE THREAD

**Issue by alessandrotesoro** [wp-cli/wp-cli#3170]
Hi there,

I was building a small plugin and did a bug in my code which triggered at least 10 duplicates of the same WP Cron Event with the same name.

When using the "cron event list" command, it would not show all the duplicated events with the same name, it would just display 1 single event. I realized there were multiple events with the same name when I tried to delete them via wp-cli and it would still be there, I've then installed the WP Crontrol plugin and it would show all the duplicated events.

Not sure if this is the intend behavior, just thought your might wanted to know 👍 

Regards,
Alessandro.

**Comment by ernilambar** [comment]
I can reproduce this. But I am also not sure this is expected behavior or not.

**Comment by danielbachhuber** [comment]
The expected behavior is to list all events, so this is a bug.
