### ISSUE TITLE
Unexpected Result: cli Exits without error

### ISSUE THREAD

**Issue by n8xja** [wp-cli/wp-cli#3176]
I'm new to wp-cli.  I have a test instance on a server that's hosting two wp sites. One site cli works perfectly, the second cli exits without error.

On the site that works, the debug looks like:

> Debug: No readable global config found (0.015s)
> Debug: No project config found (0.016s)
> Debug: No package autoload found to load. (0.023s)
> Debug: ABSPATH defined: /var/spool/ssd/<redacted>/ (0.023s)
> Debug: Begin WordPress load (0.023s)
> Debug: wp-config.php path: /var/spool/ssd/<redacted>/wp-config.php (0.023s)
> Debug: Loaded WordPress (1.182s)
> Debug: Running command: cron event list (1.183s)

On the site that does not, the same command returns this debug:

> Debug: No readable global config found (0.015s)
> Debug: No project config found (0.016s)
> Debug: No package autoload found to load. (0.023s)
> Debug: ABSPATH defined: /var/spool/ssd/<redacted>/ (0.023s)
> Debug: Begin WordPress load (0.025s)
> Debug: wp-config.php path: /var/spool/ssd/<redacted>/wp-config.php (0.025s)

I'm at a loss on what to try next. I had hoped debug would have reported an error to help further. Any suggestions on how to troubleshoot this further?

**Comment by n8xja** [comment]
Looking further, on the site that exists without error or any output, the follow command "wp --debug help" produces the same six lines of debug output., without displaying any help.

**Comment by danielbachhuber** [comment]
> I'm at a loss on what to try next. I had hoped debug would have reported an error to help further.

It appears WordPress is loading in one case, and not loading in another.

> Any suggestions on how to troubleshoot this further?

Try using `--skip-plugins` and `--skip-themes` to diagnose whether the problem is coming from a given plugin or theme:

https://runcommand.io/to/identify-plugin-theme-conflict-wp-cli/

**Comment by n8xja** [comment]
Used:  wp --skip-plugins plugin list --field=name | awk '{print "wp --skip-plugins="$1" plugin list "}' 

To cycle through each plugin, and found that:
wp --skip-plugins=redirect plugin list

which maps to a plugin that appearently hasn't been updated in 8 years.

Deactivating that plugin allows wp-cli to work on this site. Thank you for the troubleshooting "baby-sitting".

**Comment by danielbachhuber** [comment]
> Used: wp --skip-plugins plugin list --field=name | awk '{print "wp --skip-plugins="$1" plugin list "}'
> 
> To cycle through each plugin, and found that:
> wp --skip-plugins=redirect plugin list
> 
> which maps to a plugin that appearently hasn't been updated in 8 years.

Good suggestions. I've updated the Excerpt accordingly.

> Thank you for the troubleshooting "baby-sitting".

Yep, happy to help.
