### ISSUE TITLE
Different database users

### ISSUE THREAD

**Issue by morfikov** [wp-cli/wp-cli#3178]
Is there a way to use a different database users for `wp-config.php` file and `wp-cli`?

I just wanted to create two different users that would operate on the same database, but with different privileges. So for instance, my blog would only read the database, whereas `wp-cli` would do updates and other stuff like this, everything that needs to write to the database.

**Comment by danielbachhuber** [comment]
> Is there a way to use a different database users for wp-config.php file and wp-cli?

Sure, you could just do something like this:

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    define( 'DB_USER', 'privilegeduser' );
} else {
    define( 'DB_USER', 'limiteduser' );
}
```

More detail here: https://runcommand.io/to/detect-wp-cli/
