### ISSUE TITLE
User Create Sends Password Change Email

### ISSUE THREAD

**Issue by srguglielmo** [wp-cli/wp-cli#3182]
Hi,

Creating a new user by running:
`wp user create testuser "email@example.com" --display_name="First Last" --first_name="First" --last_name="Last"`

Sends an email to `email@example.com` which notifies the user of a password change:

> Hi testuser,
> 
> This notice confirms that your password was changed on Second Site.
> 
> If you did not change your password, please contact the Site Administrator at xxxx
> 
> This email has been sent to email@example.com
> 
> Regards,
> All at Second Site
> http://debian.vm/second"

The [wp-cli docs](http://wp-cli.org/commands/user/create/) state that --send-email can be supplied to send an email. I didn't include that switch as I didn't want to send any email at all. I imagine this is a side affect of wp-cli setting the password.

Is there a way to prevent sending any email at all when creating a user? Is this a WP thing that is out of wp-cli's control?

Thanks,
Steve

**Comment by danielbachhuber** [comment]
> Sends an email to email@example.com which notifies the user of a password change:

It looks like this happens on multisite because WP-CLI calls `wp_update_user()` to set the user details, which then thinks the password is being changed.

> Is there a way to prevent sending any email at all when creating a user? Is this a WP thing that is out of wp-cli's control?

It's a WordPress behavior, but I'd consider it a bug in WP-CLI given we have a `--send-email` flag.

There are `send_password_change_email` and `send_email_change_email` filters we can set to change the behavior for WP-CLI.

**Comment by srguglielmo** [comment]
@danielbachhuber Any estimate when the bug will be fixed? Not to rush you; I'm trying to plan for a project and will need to handle things a different way if it will be a few weeks before a fix. If you can point me to the proper location in the code, I'd be happy to try to fix it and send a pull request.

**Comment by danielbachhuber** [comment]
> Any estimate when the bug will be fixed?

No estimates at this time. It will get done when there's a pull request for it.

> If you can point me to the proper location in the code, I'd be happy to try to fix it and send a pull request.

Sure, you'll want to check out `User_Command` for the relevant code: https://github.com/wp-cli/wp-cli/blob/master/php/commands/user.php

We should probably introduce [functional tests](http://wp-cli.org/docs/pull-requests/#functional-tests) at this point for email sending, which will make the fix a bit more involved.

**Comment by srguglielmo** [comment]
@danielbachhuber How do I build the phar to test my changes? I see `utils/make-phar.php` exists, but it depends on `vendor/autoload.php` which isn't in the repo.

**Comment by pwkip** [comment]
This issue still seems to occur. Should it be reopened?
