### ISSUE TITLE
Indicate actual error for "Error establishing database connection"

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3188]
*Please keep this 'good-first-issue' for a first time contributor if possible. Thanks!*

When there's an error establishing the database connection, we should include the actual database error in the error message.

**Comment by danielbachhuber** [comment]
As it turns out, `$wpdb->last_error` is empty in these cases. We can display more of the error text, however.

**Comment by mbtamuli** [comment]
I would like to work on this. This will be my first time. Can I be assigned this issue?

**Comment by ernilambar** [comment]
@mbtamuli no need to assign ticket. You can simply submit PR. It will be merged after review.
