### ISSUE TITLE
Missing call to wp_unslash

### ISSUE THREAD

**Issue by promethe42** [wp-cli/wp-cli#3190]
Hello,

`wp post meta update` can fail if the value contains slashes, such as the `\n` special character.

```
$ echo -n '{
  "additional_headers": "Reply-To: [your-email]",
  "attachments": "",
  "body": "From: [your-name] <[your-email]>\nSubject: [your-subject]\n\nMessage Body:\n[your-message]\n\n--\nThis e-mail was sent from a contact form on 3DLab (http://mydomain.test)",
  "exclude_blank": false,
  "recipient": "hello@mydomain.test",
  "sender": "[your-name] <[your-email]>",
  "subject": "[your-subject]",
  "use_html": false
}' | ./bin/wp --allow-root --path=/var/www/home-web post meta update 26 _mail --debug
Error: Failed to update custom field '_mail'.
```

The `CommandWithMeta::update()` function will call the `update_metadata` WordPress function. This function will return false if:

1. there is an error
2. or the old and the new value are the same.

To make the distinction, `CommandWithMeta::update()` handles this second case before calling `CommandWithMeta::update()`. But the equality check performed by `CommandWithMeta::update()` in not the same as the one in `update_metadata`:
* `update_metadata` calls `wp_unslash()` and then `sanitize_meta()` on `$meta_value`
* `CommandWithMeta::update` calls only `sanitize_meta()`

Therefore, some old/new value equality cases will be considered as errors.
To fix this, we just have to make sure the checks are the same and call `wp_unslash` in `CommandWithMeta::update()`:

```php
public function update( $args, $assoc_args ) {
		list( $object_id, $meta_key ) = $args;

		$meta_value = WP_CLI::get_value_from_arg_or_stdin( $args, 2 );
		$meta_value = WP_CLI::read_value( $meta_value, $assoc_args );

		$object_id = $this->check_object_id( $object_id );

		$meta_value = wp_unslash($meta_value); // FIX: missing call to wp_unslash added here
		$meta_value = sanitize_meta( $meta_key, $meta_value, $this->meta_type );
		$old_value = sanitize_meta( $meta_key, get_metadata( $this->meta_type, $object_id, $meta_key, true ), $this->meta_type );

		if ( $meta_value === $old_value ) {
			WP_CLI::success( "Value passed for custom field '$meta_key' is unchanged." );
		} else {
			$success = update_metadata( $this->meta_type, $object_id, $meta_key, $meta_value );
			if ( $success ) {
				WP_CLI::success( "Updated custom field '$meta_key'." );
			} else {
				WP_CLI::error( "Failed to update custom field '$meta_key'." );
			}
		}
	}
```

Should I do a PR for this?

**Comment by danielbachhuber** [comment]
> Should I do a PR for this?

Yes please, [with tests](https://wp-cli.org/docs/pull-requests/#functional-tests).

**Comment by promethe42** [comment]
I don't see any unit tests for `wp post meta`. Should I create a new file?

**Comment by danielbachhuber** [comment]
> I don't see any unit tests for wp post meta. Should I create a new file?

They'll need to be functional tests. [Here's features/post-meta.feature](https://github.com/wp-cli/wp-cli/blob/master/features/post-meta.feature)

**Comment by danielbachhuber** [comment]
@promethe42 Are you still wanting to fix this yourself?

**Comment by promethe42** [comment]
@danielbachhuber I honnestly don't think I'll have the time :(

**Comment by ernilambar** [comment]
I will try to prepare PR.
