### ISSUE TITLE
Download parent theme while installing and activating child theme

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3196]
`wp theme install buntu --activate`

Output:

Installing Buntu (1.4.0)
Downloading install package from https://downloads.wordpress.org/theme/buntu.1.4.0.zip...
Unpacking the package...
Installing the theme...
Theme installed successfully.
Activating 'buntu'...
Error: The parent theme is missing. Please install the "stargazer" parent theme.

In admin panel when we install child theme, it downloads parent theme if applicable. What if we implement similar in CLI also?

**Comment by danielbachhuber** [comment]
> In admin panel when we install child theme, it downloads parent theme if applicable. What if we implement similar in CLI also?

Yep, this seems reasonable.

**Comment by danielbachhuber** [comment]
As it turns out, this was a bug, and a pretty nasty one at that c0d8618b72215f8ddad4ea457460816fd1bb5b51
