### ISSUE TITLE
Should we change WP-CLI's release cycle?

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3198]
WP-CLI's last five major releases have been roughly three months apart:

* [v0.24.0](http://wp-cli.org/blog/version-0.24.0.html) - July 26th, 2016
* [v0.23.0](http://wp-cli.org/blog/version-0.23.0.html) - March 23rd, 2016
* [v0.22.0](http://wp-cli.org/blog/version-0.22.0.html) - January 7th, 2016
* [v0.21.0](http://wp-cli.org/blog/version-0.21.0.html) - November 4th, 2015
* [v0.20.0](http://wp-cli.org/blog/version-0.20.0.html) - August 26th, 2015

My goal for WP-CLI is for users to never have to think about which version they're running — they should always be on the latest and greatest.

In the past, we've been fortunate that users are forced to update for compatibility with the latest WordPress version. Now that wp-settings.php is no longer forked (#2278), we don't have that excuse to depend on. Updating is easy for individual users — `wp cli update`. For organizational users, updating can include scheduling engineering time, a more rigorous QA process, and so on.

For the completion of this issue, I'd like to have documented:

* [x] How often new major versions are released, and when minor releases are produced.
* [x] Which versions of WP-CLI are officially supported.
* [x] How we handle breaking changes.
* [ ] How we handle dependency updates (because WP-CLI is built into a Phar file that includes Symphony components, etc.)

Consider this to be an open thread; I'm curious to hear different perspectives on this issue.

**Comment by voldemortensen** [comment]
My first thoughts are that I'd like the release cycle to fall inline with WordPress Core releases, but ~1 month beforehand. That would give larger organizations that use it in apps time to do regression testing, breaking change fixes, and deployments prior to a Core release.

I have to mull the rest over.

**Comment by szepeviktor** [comment]
AFAIK forcing a release cycle will result in more bugs. A natural "roughly three months" works well.

**Comment by voldemortensen** [comment]
I think it would only result in more bugs if devs tried forcing as many issues as possible into a release.

**Comment by danielbachhuber** [comment]
> My first thoughts are that I'd like the release cycle to fall inline with WordPress Core releases, but ~1 month beforehand. That would give larger organizations that use it in apps time to do regression testing, breaking change fixes, and deployments prior to a Core release.

I hadn't thought about it this way, but I suppose we're already on a pretty nice rhythm. Is this how it works for Bluehost right now?

**Comment by voldemortensen** [comment]
> I hadn't thought about it this way, but I suppose we're already on a pretty nice rhythm. Is this how it works for Bluehost right now?

Essentially. The current rhythm has worked out pretty well (minus those two unexpected point releases, but that shouldn't happen anymore). We have a fairly large app that uses WP-CLI very heavily.

**Comment by PowerKiKi** [comment]
I'd suggest to release a 1.0.0 to represent the maturity achieved in the last five years and the fact that it's widely used in production environments.

Other than that stick to semver, release patches "often", and release minor "from time to time". So basically what you did so far. I believe wp-cli tool is easy to update often, so as long as it's non breaking stuff (that would warrant a major version), then there is no problem to release whenever there is something to be released.

**Comment by danielbachhuber** [comment]
For 2016, [we're going to](http://wp-cli.org/blog/remaining-releases-2016.html) release a v0.25.0, and then tag v1.0.0.

I have some ideas on how to mix things up a bit post v1.0.0

**Comment by Ipstenu** [comment]
Belated followup - I think @voldemortensen's suggestion is a good one. While I'd love a longer release cycle (and I think WP should have only two majors a year), in order to keep parity _with_ WordPress, this is necessary.

**Comment by mamchenkov** [comment]
Whatever you were doing so far, worked great for us! :+1: Thanks for all the hard work. :smile: 

P.S.: WP-CLI is part of [project-template-wordpress](https://github.com/QoboLtd/project-template-wordpress) which we use to manage dozens, if not hundreds, of WordPress projects.
