### ISSUE TITLE
Provide a Dutch version of the homepage

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3201]
From https://github.com/wp-cli/wp-cli/issues/3065#issuecomment-234114727

**Comment by chantalcoolsma** [comment]
How do we translate? Do we have a tool for that?

**Comment by danielbachhuber** [comment]
> How do we translate?

See https://github.com/wp-cli/wp-cli.github.com/pull/162 for an example. It's essentially:

1. Add a new entry for the locale in `_config.yml`
1. Create a directory for the locale, copy the existing `index.md` to the directory, and perform the necessary edits.

> Do we have a tool for that?

No tool at this point. We've opted for the simplest possible solution.

**Comment by chantalcoolsma** [comment]
Thanks. Started working on Dutch. Will do a PR when ready.

**Comment by danielbachhuber** [comment]
No need to keep an issue open for this — the translation can come when it's ready.
