### ISSUE TITLE
Can't use debian package on Ubuntu Xenial

### ISSUE THREAD

**Issue by carlalexander** [wp-cli/wp-cli#3206]
The new Ubuntu LTS (Xenial) doesn't support PHP5 anymore. This makes it impossible to use the wp-cli Debian packages. You always get an error: 

```
Dependency is not satisfiable: php5-cli
```

wp-cli works fine if I install it by hand. So it's just a question of allowing for `php7.0-cli` as a dependency. Would changing the `Depends` line in `wp-cli-updatedeb.sh` do the trick?

**Comment by danielbachhuber** [comment]
cc @szepeviktor

**Comment by szepeviktor** [comment]
The Debian way is to release packages for every OS release.
In the next Debian release there will be a `php-cli` virtual package: https://packages.debian.org/sid/php-cli
But that is not available in the current stable release.

We could depend on php5-cli OR php7.0-cli.
https://github.com/wp-cli/wp-cli/blob/master/utils/wp-cli-updatedeb.sh#L34

@danielbachhuber ?

**Comment by danielbachhuber** [comment]
> We could depend on php5-cli OR php7.0-cli.

This seems fine to me, given we support both.

**Comment by szepeviktor** [comment]
@carlalexander Meanwhile your could `dpkg --ignore-depends php-wpcli_latest_all.deb`

**Comment by carlalexander** [comment]
Sounds good! You'll probably need to add `php5-mysql | php5-mysqlnd | php7.0-mysql | php7.0-mysqlnd` as well.

**Comment by carlalexander** [comment]
Sorry just spotted that just now.

**Comment by szepeviktor** [comment]
There is only `php7.0-mysql`
https://packages.debian.org/source/sid/php7.0

**Comment by carlalexander** [comment]
Ah sorry, I thought I saw it. But it's just a [virtual package](http://packages.ubuntu.com/xenial/php7.0-mysqlnd).

**Comment by szepeviktor** [comment]
Here it is https://github.com/wp-cli/wp-cli/pull/3208/commits/8cba590cf01ef6abdfd153893e68a1e16d790e8a

**Comment by carlalexander** [comment]
@danielbachhuber Does this mean that the packages work now or do we need to wait until the release of 0.25.0?

**Comment by danielbachhuber** [comment]
> Does this mean that the packages work now or do we need to wait until the release of 0.25.0?

@szepeviktor Can you create a new build?
