### ISSUE TITLE
Composer conflict with lucatume/wp-browser

### ISSUE THREAD

**Issue by LehaMotovilov** [wp-cli/wp-cli#3207]
Hi guys!

I want to install both "wp-cli/wp-cli" and "lucatume/wp-browser" via composer.

I have a problem, wp-cli require symfony/process: ~2.1 but wp-browser require symfony/process: ~3.1.

You can check: [packagist wp-browser](https://packagist.org/packages/lucatume/wp-browser#1.15.1) and [packagist wp-cli](https://packagist.org/packages/wp-cli/wp-cli#v0.24.0)

Maybe we can up symfony/process version to 3.1 in next wp-cli release?

**Comment by danielbachhuber** [comment]
> Maybe we can up symfony/process version to 3.1 in next wp-cli release?

I've posted a call for input on when it makes sense to change dependencies: https://github.com/wp-cli/wp-cli/issues/3198

**Comment by danielbachhuber** [comment]
For your particular situation, you can install the Phar version instead http://wp-cli.org/docs/installing/#recommended-installation
