### ISSUE TITLE
Warning: --autoload parameter needs a value

### ISSUE THREAD

**Issue by Noxalus** [wp-cli/wp-cli#3209]
Hello everyone,

Since this week (so, with the v0.24.0), I see this warning from the stderr output each time I try to update an option. This was not needed before and I would like to know why we this option should be specify now.

From the [Wordpress documentation](https://codex.wordpress.org/Function_Reference/update_option), the `autoload` parameter is optional for the function `upgrade_option()`, and its default value is `yes`.

So to avoid this warning I just add `--autoload='yes'` to my `wp option update` command. The problem is that I can't update the same option twice if I do that. (I have no explicit error even using the `--debug` flag => I just have `Error: Could not update option {optionName}`). 

Thanks in advance for your answer :smile:

**Comment by danielbachhuber** [comment]
This is a bug from 5349e8c660e6456787151deee0762d50e062c927

Specifically, YAML interprets `yes` and `no` into boolean values, when they should be strings.

We should take this as an opportunity to add a full set of tests around the autoload parameter.
