### ISSUE TITLE
wp core verify-checksums incorrectly reports extra files when a lower sub-dir is named wp-admin or wp-includes

### ISSUE THREAD

**Issue by rklrkl** [wp-cli/wp-cli#3214]
The (now obsolete - you won't find it in the WP plugin directory) Social plugin from Mailchimp contains a directory structure like this:

wp-content/plugins/social/views/wp-admin

WP-CLI 0.24.0's "wp core verify-checksums" command now incorrectly reports all files under that tree thus:

Warning: File should not exist: wp-content/plugins/social/views/wp-admin/options.php
Warning: File should not exist: wp-content/plugins/social/views/wp-admin/parts/accounts.php
[and so on for about 15 files]

I suspect that WP-CLI isn't anchoring the check to the top of the Web tree (i.e. /wp-admin) and is incorrectly reporting files under a lower sub-dir. The same probably applies to lower wp-includes sub-dirs too, though this plugin didn't have those.

**Comment by danielbachhuber** [comment]
> I suspect that WP-CLI isn't anchoring the check to the top of the Web tree (i.e. /wp-admin) and is incorrectly reporting files under a lower sub-dir. The same probably applies to lower wp-includes sub-dirs too, though this plugin didn't have those.

Good call. This is something we'll be able to more easily write tests for, too.
