### ISSUE TITLE
--export flag on search-replace causes data loss during migration

### ISSUE THREAD

**Issue by cfxd** [wp-cli/wp-cli#3215]
### Expected behavior
Running `$ wp search-replace '//example.dev' '//example.localhost' --export=db.sql` should replace all URLs and serialized data in the resulting dump, which should be immediately suitable for site migration without any lost data.

### Actual behavior
Certain records are excluded or not replaced/serialized correctly causing data loss between migration URLs. My most recent instance occurred with Gravity Forms being lost between URLs.

# Steps to reproduce

1. Create new site at http://example.dev and install/activate Gravity Forms
2. Create a Gravity Form
3. Run `$ wp search-replace '//example.dev' '//example.localhost' --export=db.sql`
4. Create new site at http://example.localhost and install/activate Gravity Forms
5. Import the dump from step 3 above using Sequel Pro
6. Visit Gravity Forms admin pages; the form created in step 2 above will not be present

## Notes:

1. There appears to be no data loss if I omit the `--export` flag in step 3 above and perform the `search-replace` on my live db then run a `mysqldump` of the searched-replaced database and use that for my migration.
2. There appears to be not data loss if I run a `mysqldump` of my live db and then run the dump through [Peach](http://petesaia.github.io/Peach/) to migrate the URLs.

**Comment by danielbachhuber** [comment]
Are you sure `--export=db.sql` is including the Gravity Forms table?

`wp search-replace` only operates on tables registered to `$wpdb` by default. If Gravity Forms doesn't register its tables to `$wpdb`, then they won't be present in the export file.

**Comment by cfxd** [comment]
Indeed that appears to be the issue, @danielbachhuber. The Gravity Forms db tables all begin with `<$table_prefix>_rg_` and are not present in the export.

Why is this behavior different from a standard `$ wp db export` command (which actually _does_ export the entire db)?

**Comment by danielbachhuber** [comment]
> Why is this behavior different from a standard `$ wp db export` command (which I confirmed actually does export the entire db including the Gravity Forms tables)?

They were implemented differently, and we haven't yet decided to make them behave consistently.

> The different behavior between `$ wb db export` and a search-replace with the `--export` flag is disconcerting but adding the `--all-tables` flag to the search-replace command appears to successfully export the entire database. 

Correct.
