### ISSUE TITLE
CLI subcommand `api-dump`

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3217]
http://wp-cli.org/commands/cli/api-dump/
This page shows `api-dump` as subcommand of `cli` but I could not find it in `CLI_Command` class. From where is it coming in the site?

**Comment by danielbachhuber** [comment]
> From where is it coming in the site?

This is a bug. It's defined in the website repo: https://github.com/wp-cli/wp-cli.github.com/blob/master/command.php#L94
