### ISSUE TITLE
Display default core language

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3219]
*Please keep this 'good-first-issue' for a first time contributor if possible. Thanks!*

Could we add `$wp_local_package` to `core version --extra`?
If it is not available then display `en_US`.

**Comment by ernilambar** [comment]
Current locale info would be nice. But I believe `wp core version --extra` is not best place to put that information because we are displaying only version info there. 
I would not mind if we could introduce `wp core info` for basic information of the current WP system.

**Comment by danielbachhuber** [comment]
> But I believe wp core version --extra is not best place to put that information because we are displaying only version info there.

Given `$wp_local_package` is a variable from `version.php`, I'm amenable to adding it to `wp core version --extra`.

**Comment by szepeviktor** [comment]
> Given $wp_local_package is a variable from version.php, I'm amenable to adding it to wp core version --extra.

Meanin that *someone* may send a PR?

**Comment by szepeviktor** [comment]
Should it be called *`Installation language` or `Package language`?
