### ISSUE TITLE
Respect WP_DEBUG instead of overriding

### ISSUE THREAD

**Issue by iandunn** [wp-cli/wp-cli#3220]
Currently the value of `display_errors` is overridden by `\Utils\wp_debug_mode()`, but I would expect WP_CLI to respect the value set by `WP_DEBUG`  and `\wp_debug_mode()` instead.

It sounds like [there may have once been a reason for overriding it](https://github.com/wp-cli/wp-cli/issues/706#issuecomment-236629262), but it's not known anymore.

In my experience, having it overridden is a hassle, because when I'm writing commands I don't have notice/warning/error messages easily available. In many cases, it might not even be obvious that an error occurred at all. So I have to manually check log files or [use a fragile workaround](https://github.com/iandunn/wp-cli-plugin-active-on-sites/blob/7b0d2e6/wp-cli-plugin-active-on-sites.php#L57) to restore the original settings.

I'd be happy to work on a PR if it's decided that this behavior should be removed.

Background information:

[php/utils-wp.php#L26](https://github.com/wp-cli/wp-cli/blob/7845a67b97c162573212b6bcf6aff62bfad2957c/php/utils-wp.php#L26)
cb57cc0
#786

**Comment by danielbachhuber** [comment]
> Currently the value of display_errors is overridden by `\Utils\wp_debug_mode()`, but I would expect WP_CLI to respect the value set by `WP_DEBUG` and `\wp_debug_mode()` instead.

Sorry if I'm being a bit dense, but I'm still not sure what the problem is. Can you provide a more detailed example of how this is a problem, what the current behavior is, and what you'd expect the behavior to be?

**Comment by iandunn** [comment]
Sorry, I probably just didn't describe that clearly. 

### Steps to reproduce:

1. `define( 'WP_DEBUG', true);` in your dev environment's `wp-config.php`
1. Create `test.php` with these contents:
	```php
	<?php
	
	echo "hello";
	calling_function_that_doesnt_exist();
	```
1. Run `wp eval-file test.php`

### Expected output:

```
> wp eval-file foo.php
hello
Fatal error: Call to undefined function calling_function_that_doesnt_exist() in test.php on line 3
```

### Actual output:

```
> wp eval-file foo.php
hello
```

`display_errors` has been disabled by `\Utils\wp_debug_mode()`, so any notices/warnings/errors thrown by PHP are not directed to `STDOUT`.

**Comment by iandunn** [comment]
Running `php test.php` behaves as expected since `display_errors` is on by default in my dev environment:

```shell
> php foo.php 
helloPHP Fatal error:  Call to undefined function calling_function_that_doesnt_exist() in test.php on line 3
```

**Comment by danielbachhuber** [comment]
What would you think about this?

1. If `WP_DEBUG=true`, then WP-CLI defaults to displaying errors when `--debug` is and isn't included. If `--no-debug` is passed, then WP-CLI silences errors.
2. If `WP_DEBUG=false` or isn't set, the WP-CLI defaults to not displaying errors. `--debug` would enable displaying errors.

It does seem somewhat erroneous for WP-CLI to quietly silence errors when `WP_DEBUG` is defined in `wp-config.php`.

**Comment by iandunn** [comment]
Yeah, that makes sense to me. I'll work on a PR :)

**Comment by danielbachhuber** [comment]
> Yeah, that makes sense to me. I'll work on a PR :)

👍 

It'd be good to have explicit test coverage for each of the scenarios, where we don't already.

**Comment by myselfhimself** [comment]
Hello, it would be nice to document how to get the current debug verbosity.. For now I have found by myself:
`if(\WP_CLI::get_config('debug')) {`
Thanks for the very good WP_CLI!!

**Comment by danielbachhuber** [comment]
> Yeah, that makes sense to me. I'll work on a PR :)

@iandunn Do you have a timeframe you're willing to commit to for this? Otherwise, I think this issue should be free for the first person to submit a PR.

**Comment by iandunn** [comment]
Sorry about that, my schedule got more packed than I expected. 

I think it's totally fine to consider it open, I didn't mean to call dibs or anything. I'm still planning to get to this, but if someone else wants to submit a PR first that's totally fine with me.

**Comment by danielbachhuber** [comment]
@iandunn I added a testcase in #3372 for the behavior you described in https://github.com/wp-cli/wp-cli/issues/3220#issuecomment-236649813. The testcase passes, which isn't what I'd expect if the behavior was broken like you initially described.

Can you re-verify the original issue, and confirm there isn't additional code in your environment that might be affecting error reporting?

**Comment by iandunn** [comment]
Huh, that test passes for me too, and now I can't reproduce the problem in any of my environments. That's odd, since I've been experiencing it for years.

I've updated WP and WP-CLI since opening this issue, but can't think of any other changes that'd be relevant. IIRC, I tested with a fresh WP install before opening the issue, too, to rule out external causes.

Oh well, I guess I'll just consider this resolved unless I run into it again in the future. Sorry for the trouble.

**Comment by danielbachhuber** [comment]
> Oh well, I guess I'll just consider this resolved unless I run into it again in the future. Sorry for the trouble.

No worries! Happy to look into it again if you can track down more steps to reproduce.

**Comment by iandunn** [comment]
I'm re-opening this because I can reproduce it again, using the steps in https://github.com/wp-cli/wp-cli/issues/3220#issuecomment-236649813

I think there may be a few extra conditions necessary:
* Xdebug must be enabled.
* `xdebug.force_display_errors` must be disabled.

I'll send a PR that shows the test failing.

**Comment by bitwombat** [comment]
Is --no-debug still a part of this PR?  Because I don't want to get all the notices and warnings from the CLI just because I've set WP_DEBUG true for the site itself.

**Comment by ahberg** [comment]
Hello I spent some hours on this issue and found that the issue is about the [log_errors](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-log) ini variable. If log_errors is On you can't disable errors reporting with `ini_set( 'display_errors', 0); `
log_errors is set to Off by default in php. In Ubuntu is On for PHP CLI php.ini file /etc/php/7.2/cli/php.ini. WP CLI using Ubuntu for testing (Github actions). I forked and updated @iandunn branch #4740. Added ini_set( 'log_errors', 0 ); and now the scenario didn't pass https://github.com/ahberg/wp-cli/pull/2.

**Comment by roborourke** [comment]
Kinda related but there's an issue with Xdebug 3 - this line:

https://github.com/wp-cli/wp-cli/blob/master/php/utils-wp.php#L69

Forces the value of `display_errors` if that function exists but Xdebug can now have it's mode set to `off` via the `xdebug.mode` ini setting, in which case the function exists but Xdebug won't do anything.

https://xdebug.org/docs/all_settings#mode

We should check if Xdebug is active too.

**Comment by ahberg** [comment]
@roborourke I think we don't need to check if xdebug is active. My solution is simple check my PR #5501.
Any feedback is welcome.

**Comment by ahberg** [comment]
Yes is still an issue. 
Can we label it as a confirmed **bug**?

**Comment by drzraf** [comment]
I concur with soulseekah that the behavior when xdebug is installed is wrong.
cb57cc0a (written 2013 and reference by OP) assumed that `display_errors` must be set to false if `xdebug_debug_zval` (xdebug enabled), but I'm pretty sure that xdebug changed overtime to actually respect `display_errors`.

With WP_DEBUG set and xdebug enabled, the following should trigger a visible `E_DEPRECATED` warning in the console.
`$ php8.3 wp eval  'ZipArchive::FL_RECOMPRESS ;'`

It actually doesn't **except if xdebug.force_display_errors=1**. I don't think it's right since xdebug output is legit (and expected) even with `force_display_errors`.

By the way, there is no way to inhibit `E_DEPRECATED` while still using WP_DEBUG.
