### ISSUE TITLE
WP DB Drop Options for DB Prefix

### ISSUE THREAD

**Issue by lukecav** [wp-cli/wp-cli#3223]
Currently the only option is --yes

Would there be a way to add an option to be able to drop a db by prefix?

https://wp-cli.org/commands/db/drop/

**Comment by danielbachhuber** [comment]
Just to clarify, your use case is deleting specific tables, not the entire database?

**Comment by lukecav** [comment]
@danielbachhuber 

Yes correct that use case would be for removing specific tables and not the entire database.

**Comment by blindpet** [comment]
Maybe the command should be wp table drop instead to avoid confusion?

**Comment by danielbachhuber** [comment]
> Maybe the command should be wp table drop instead to avoid confusion?

The command is `wp db drop` because it drops the entire database. There isn't a command for deleting individual tables.

**Comment by blindpet** [comment]
I understand that @danielbachhuber but @lukecav was asking if the same or a similar command to drop specific prefixes (i.e. tables) exists. I was just suggesting if you were going to add this feature then it may be appropriate to add a separate command specifically for tables.

It sounds like @lukecav wants to drop specific tables with specific prefixes, this wouldn't be dropping the database just a table or two.

**Comment by lukecav** [comment]
@blindpet 

Yep correct.

Seems like an option that would be of use. Again it might be an edge case, but I see it as being of use.
