### ISSUE TITLE
Reset cron jobs

### ISSUE THREAD

**Issue by andrewbanchich** [wp-cli/wp-cli#3224]
I would love a way for WP-CLI to be able to clear all existing cron jobs at once. There are a lot of people who have tons of backed up cron jobs they need to remove, and don't want to have to learn SQL just to remove them. I'd love to use WP-CLI to just say 'wp cron reset --all' or something of the sort, and have it totally clear the cron jobs.

**Comment by danielbachhuber** [comment]
How would this be different than `wp option delete cron` ?

**Comment by andrewbanchich** [comment]
Oh that's awesome! I was looking for that on the website documentation under 'wp cront event delete'. Thanks!
