### ISSUE TITLE
How to run a command later in the WordPress loading process.

### ISSUE THREAD

**Issue by grappler** [wp-cli/wp-cli#3225]
I am working a command that is duplicating attachment post types for a multilingual plugin "Polylang".

How do I get the command to run only at `wp_loaded`? I need to wait till this time point so that the Polylang is fully loaded. I am currently running it as a plugin.

I looked the documentation and other command but did see a possible solution.
I found `WP_CLI::add_wp_hook()` but the following code did not work.

```php
public function media() {
WP_CLI::add_wp_hook( 'wp_loaded', function() {
$thi->_duplicate_posts();
});
}
```
http://wp-cli.org/docs/internal-api/wp-cli-add-wp-hook/

**Comment by danielbachhuber** [comment]
> I am working a command that is duplicating attachment post types for a multilingual plugin "Polylang".

Can you share or point me to a copy of the full command?

> I found `WP_CLI::add_wp_hook()` but the following code did not work.

Just to verify, you've added `@when before_wp_load` to the command's synopsis to ensure the command itself is running before WordPress loads?

```
/**
 * My awesome command
 *
 * @when before_wp_load
 */
function my_function( $args, $assoc_args )
```

Without the `@when before_wp_load` flag, the command will run after WordPress has loaded, which means the hook won't fire.

However, with all of this being said, I'm not sure why you need to run the code on `wp_loaded` — simply running the code within the command method should be sufficient.

**Comment by grappler** [comment]
> Can you share or point me to a copy of the full command?

https://gist.github.com/grappler/1f214baf5329497cb0fe7e42990aa8e5

> Just to verify, you've added @when before_wp_load to the command's synopsis to ensure the command itself is running before WordPress loads?

Yes, but I don't think it will work as I am loading the command from a plugin. How do you develop commands before they are added to the package index.

> I'm not sure why you need to run the code on `wp_loaded`

Because the command id dependant on other code that is only run later.
https://github.com/polylang/polylang/blob/243bcf1af1df3bc37f65bf20cfd9b65b7bb03042/admin/admin.php#L59

Thank you for your help.

**Comment by danielbachhuber** [comment]
> Yes, but I don't think it will work as I am loading the command from a plugin.

This is correct.

> How do you develop commands before they are added to the package index.

You can load the file directly with `--require=command.php`, which means the code will be loaded before WordPress is loaded.

> Because the command id dependant on other code that is only run later.

It's still not clear to me why the code needs to hook exactly on to `wp_loaded`. `wp_loaded` is the last action in the bootstrap process. Why can't you just remove the `@when before_wp_load` and run the command in the scope of a fully-loaded WordPress?

**Comment by grappler** [comment]
> It's still not clear to me why the code needs to hook exactly on to wp_loaded.
A object gets added to a global which the command needs in `wp_loaded` at priority 5. If my command runs before the object gets added to the global then the code fails with a PHP error.

> Why can't you just remove the @when before_wp_load and run the command in the scope of a fully-loaded WordPress?
I could, the code just needs to run after `wp_loaded`.

**Comment by danielbachhuber** [comment]
> I could, the code just needs to run after wp_loaded.

Ok, that should work fine then.

**Comment by diggy** [comment]
@grappler not sure if you're developing for private or public use, just wanted to let you know there's a discussion going on about an "official" polylang cli component [here](https://github.com/dereckson/wp-cli-polylang/issues/5).

**Comment by grappler** [comment]
@danielbachhuber Ah, I think I know why my code was failing. The command need to run as if it were in the admin area and not on the front end.

@diggy I am developing it for private use but am to contribute it publically once it is ready and there is a home for it.

**Comment by grappler** [comment]
But I am not sure how to do that.

**Comment by grappler** [comment]
Ok, I got it to work. I needed to define the URL and USER parameter as the Polylang code required to be run in the admin context and the user needed to have the correct capabilities.

I misunderstood the problem. Thank you for your help.
