### ISSUE TITLE
wp site list --site_id=<id> returns sites of all networks

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#3226]
`site_id` is [documented](https://github.com/wp-cli/wp-cli/blob/e6dd8dffd3ccce15ceb87ab0a9c843d5a5644bdd/php/commands/site.php#L448
) as a valid field but the field is ignored when filtering the sites for a specific network.

By looking [at the code](https://github.com/wp-cli/wp-cli/blob/e6dd8dffd3ccce15ceb87ab0a9c843d5a5644bdd/php/commands/site.php#L499) I found `network` as another (undocumented) field. `wp site list --network=<id>` works as expected.

```
$ wp cli version
WP-CLI 0.24.0
$ wp core version
4.6-RC1-38175
```

**Comment by danielbachhuber** [comment]
> site_id is documented as a valid field but the field is ignored when filtering the sites for a specific network.

This is being caught by an overzealous backwards compat shim 639d9d97f488d85598e216d7b882a9e7b8e11560
