### ISSUE TITLE
Conflicting args for xargs in examples

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3228]
[Many examples](https://github.com/wp-cli/wp-cli/search?utf8=%E2%9C%93&q=xargs) have `xargs -0 -d '\n'` which means "Input items are terminated by a null character" AND "Input items are terminated by the specified character."

https://github.com/wp-cli/wp-cli/commit/9cbbb8d6a3e61264dcfae6d5d7f46c6139b9827c

**Comment by szepeviktor** [comment]
process one line at a time `| xargs -I %` ...
process each token (e.g. post ID) `| xargs -d " " -I %` ...

**Comment by ernilambar** [comment]
After 4 new PR are merged, I believe we are good.

**Comment by danielbachhuber** [comment]
🚢

**Comment by szepeviktor** [comment]
:ocean:
