### ISSUE TITLE
Piping when a progress bar is in use

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#3230]
When a command uses a progress bar (eg. with `\cli\progress\Bar`) and you pipe its output elsewhere, the output of the progress bar gets included and everything gets messy.

Is there a way for a command to provide a visual progress bar, and for its output to be piped elsewhere at the same time?

**Comment by johnbillion** [comment]
Actually, I don't mean piping, I mean sending output to a file, for example with `wp my command > file.csv`.

**Comment by danielbachhuber** [comment]
> Is there a way for a command to provide a visual progress bar, and for its output to be piped elsewhere at the same time?

You'd need to write the progress bar to STDERR and pipe STDOUT to the file, or vice versa.

Alternatively, you could write to the file from the command.
