### ISSUE TITLE
WP-CLI digest command

### ISSUE THREAD

**Issue by lukecav** [wp-cli/wp-cli#3235]
![wp cli digest command](https://cloud.githubusercontent.com/assets/5797332/17374433/d3b326ac-5969-11e6-9518-7c5396cddd8d.png)

Would a digest command be of use, to be added as a core command in WP-CLI?

**Comment by danielbachhuber** [comment]
> Would a digest command be of use, to be added as a core command in WP-CLI?

Like I mentioned in Slack, we're not typically adding new commands to WP-CLI core at this point. You're welcome to [publish the package as a community command](http://wp-cli.org/package-index/).
