### ISSUE TITLE
add --force option to wp cron run

### ISSUE THREAD

**Issue by mike503** [wp-cli/wp-cli#3239]
I would like to force run a cron hook, regardless of whether it's due or not.

**Comment by szepeviktor** [comment]
Try `wp cron event run -all`

**Comment by danielbachhuber** [comment]
> I would like to force run a cron hook, regardless of whether it's due or not.

This is the default behavior of `wp cron event run`.

**Comment by mike503** [comment]
Very odd. I wonder if it's due to the fact the cron hook might be hitting a `die()` because it's too easy for people to write poor plugins. I tested it with another hook and it did show the `next_run_relative` changed. My apologies. The documentation didn't make this clear either, which is why I was thinking it wasn't done by default.
