### ISSUE TITLE
Defining path not working

### ISSUE THREAD

**Issue by kasperrt** [wp-cli/wp-cli#3251]
I've installed WordPress to /app/wordpress/, but can't get wp-cli to recognize this as the install-directory.

Running ```$ wp --allow-root core is-installed --path=`/app/wordpress/` ``` returns:

```
bash: /app/wordpress/: Is a directory
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```
The same happens when I add ``` path: `/app/wordpress/` ``` to ~/.wp-cli/config.yml.

While ```$ wp --allow-root core is-installed --path="/app/wordpress/" ``` doesn't return anything. The same thing happens when I add ``` path: "/app/wordpress/" ``` to ~/.wp-cli/config.yml.

Any way of getting this to work correctly..=

**Comment by ernilambar** [comment]
Can you please try `wp --allow-root core is-installed --path=/app/wordpress/` without wrapping `path` value?

**Comment by danielbachhuber** [comment]
```--path=`/app/wordpress/` ``` is invalid syntax because a backtick is a [special operator in Bash](http://unix.stackexchange.com/a/27432). I'm not sure where you came across that example.

Keep in mind `--path=/app/wordpress/` means your app is installed off the system's root directory. If you're specifying a path relative to your current directory, the syntax is `--path=app/wordpress/` (note no preceding forward slash)

**Comment by luuring** [comment]
Nothing is returned when not wrapping the path.

It's installed in the system's root directory, so error isnt with the given path.

**Comment by kasperrt** [comment]
Nothing is returned when not wrapping the path.

It's installed in the system's root directory, so error isnt with the given path.

**Comment by ernilambar** [comment]
`wp core is-installed` does not display value. It return exit status. Try `wp --allow-root core version --path=/app/wordpress/` to check if its working.

**Comment by kasperrt** [comment]
My bad, it's working now.
