### ISSUE TITLE
How do I access the global parameters within a custom command?

### ISSUE THREAD

**Issue by grappler** [wp-cli/wp-cli#3253]
For a command I am writing I need the global parameters `url` and `user` to be defined.

I would like to return an error if they are not defined. How do I access the global parameters within a custom command?

I tried looking in `$args` and `$assoc_args` but they both returned an empty array. I could not find a helper function to fetch the global parameters.

**Comment by danielbachhuber** [comment]
Hi @grappler,

Our [support policies have changed](http://wp-cli.org/#support) (#3252), and Github issues are no longer the place for general support questions.

**Comment by grappler** [comment]
Ok, thanks.

I found a partial solution. I checked for the PHP error caused in my code when the global parameter is not defined and the set a warning.
