### ISSUE TITLE
Warning: Could not create directory.

### ISSUE THREAD

**Issue by helgatheviking** [wp-cli/wp-cli#3255]
Here's the full error I get when I install wp-cli and then try to use it to install a plugin

>wp plugin install akismet
Installing Akismet (3.1.11)
Downloading install package from https://downloads.wordpress.org/plugin/akismet.3.1.11.zip...
Using cached file '/home/leftback/.wp-cli/cache/plugin/akismet-3.1.11.zip'...
Unpacking the package...
Warning: Could not create directory.

**Comment by danielbachhuber** [comment]
Hi @helgatheviking,

Our [support policies have changed](http://wp-cli.org/#support) (#3252), and Github issues are no longer the place for general support questions.

**Comment by helgatheviking** [comment]
Well, at the very least I would suggest that the instructions or [common issues](https://wp-cli.org/docs/common-issues/) include information on required permissions settings.

**Comment by danielbachhuber** [comment]
> Well, at the very least I would suggest that the instructions or common issues include information on required permissions settings.

Happy to consider any suggested changes. Here's how you can contribute to the docs: http://wp-cli.org/docs/contributing/#improving-our-documentation

**Comment by helgatheviking** [comment]
Ideally someone who knows about permissions should write that and if I knew what the correct permissions were (that were also reasonably secure) I wouldn't have opened this thread in the first place.

**Comment by JamesTheHacker** [comment]
Same problem here too.

**Comment by harry-wood** [comment]
It's a documentation issue, and also the warning/error message itself should give a tiny bit more info, stating _where_ it's trying to create a directory. I've spun that out as a new issue: https://github.com/wp-cli/wp-cli/issues/4446  ...which has just been very rapidly closed. *sigh*

Anyway...  the answer is, it's trying to create something under `wp-content/upgrade/` I found it was enough to temporarily change ownership on that one directory, run the updates, and then change it back again:
```
sudo chown harry:harry wp-content/upgrade/
wp core update
wp plugin update --all
sudo chown root:root wp-content/upgrade/
```

**Comment by danielbachhuber** [comment]
@harry-wood Like I mentioned in the other ticket, this particular error message comes directly from WordPress core, not WP-CLI. The appropriate place to suggest improvements is [WordPress Core Trac](https://core.trac.wordpress.org/).

**Comment by noomz** [comment]
@harry-wood agreed, The error message is misleading. For `Warning: Could not create directory.`, the directory is not plugin directory, its `wp-content/upgrade` directory.

**Comment by Gribbs** [comment]
This did the trick for me on bitnami wordpress ec2 instance:

```
sudo /opt/bitnami/use_wordpress
wp plugin install gravityformscli --activate --allow-root
```
