### ISSUE TITLE
What is the best way to handle system cron messages?

### ISSUE THREAD

**Issue by morfikov** [wp-cli/wp-cli#3261]
I have some commands that are periodically run by my system cron. For instance:

`wp --no-color plugin update --all`

This unfortunately produces output similar to the following:

```
PHP Notice:  Undefined variable: siteurl in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(792) : eval()'d code on line 97
Success: Updated 0/0 plugins.
```
I know I could redirect the output to `/dev/null`, but I want to receive the system cron mail only when some action is preformed. So in this case, when there was a plugin that needed an update. Is there a way to achieve that?

BTW: how to get rid of the `PHP Notice: ` message?

**Comment by danielbachhuber** [comment]
Hi @morfikov,

Our [support policies have changed](http://wp-cli.org/blog/support-policy.html). This question falls outside of a bug report, enhancement request, or documentation suggestion.
