### ISSUE TITLE
MAMP Pro error establishing database connection

### ISSUE THREAD

**Issue by grahamlutz** [wp-cli/wp-cli#3262]
I followed the install instructions at wp-cli.org and am unable to connect to database.  I am using a newly installed (this morning) version of MAMP PRO.

    which php
    /usr/bin/php

    echo $WP_CLI_PHP
    <this returns an empty line>

    wp --info
    PHP binary:	    /usr/bin/php
    PHP version:	5.5.14
    php.ini used:	
    WP-CLI root dir:	phar://wp-cli.phar
    WP-CLI packages dir:	
    WP-CLI global config:	
    WP-CLI project config:	
    WP-CLI version:	0.24.1

**Comment by danielbachhuber** [comment]
Hi @grahamlutz,

Our [support policies have changed](http://wp-cli.org/blog/support-policy.html). This question falls outside of a bug report, enhancement request, or documentation suggestion.

**Comment by grahamlutz** [comment]
Ok, thanks @danielbachhuber.

For anyone who got here with the same problem, this is what ended up working for me - I put the following in my ~/.bash-profile:

```
#MAMP Madness
export PATH=/Applications/MAMP/Library/bin:$PATH
PHP_VERSION=`ls /Applications/MAMP/bin/php/ | sort -n | tail -1`
export PATH=/Applications/MAMP/bin/php/${PHP_VERSION}bin:$PATH
```
