### ISSUE TITLE
Permission denied causes PHP Fatal error

### ISSUE THREAD

**Issue by ryandaniels** [wp-cli/wp-cli#3263]
Using latest version of wp-cli.
Running command: wp core verify-checksums --path=/var/www/wp/mysite.com --debug

Output:
Debug (bootstrap): No readable global config found (0.009s)
Debug (bootstrap): No package autoload found to load. (0.047s)
Debug (bootstrap): ABSPATH defined: /var/www/wp/mysite.com/ (0.048s)
Debug (bootstrap): Running command: core verify-checksums (0.048s)
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/var/www/wp/mysite.com/wp-content/plugins/folder_owned_by_root): failed to open dir: Permission denied in phar:///usr/local/bin/wp/php/commands/core.php:1070
Stack trace:
`#`0 [internal function]: RecursiveDirectoryIterator->__construct('/var/www/wp/mysi...', 4096)
`#`1 phar:///usr/local/bin/wp/php/commands/core.php(1070): RecursiveDirectoryIterator->getChildren()
`#`2 phar:///usr/local/bin/wp/php/commands/core.php(1047): Core_Command->get_wp_core_files()
`#`3 [internal function]: Core_Command->verify_checksums(Array, Array)
`#`4 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
`#`5 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
`#`6 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(372): call_user_func(Object(Closure), Array, Array)
`#`7 phar:///usr/local/bin/wp/php/WP_C in phar:///usr/local/bin/wp/php/commands/core.php on line 1070

ls -ld /var/www/wp/mysite.com/wp-content/plugins/folder_owned_by_root
drwx------ 7 root root 4096 2015-05-31 13:41 /var/www/wp/mysite.com/wp-content/plugins/folder_owned_by_root

Can error handling be added to display a warning, instead of wp-cli halting with a PHP Fatal error?
I realize this is an edge case, but users may want to keep a plugin folder around for reference, but with no public/webserver access.

**Comment by danielbachhuber** [comment]
> Can error handling be added to display a warning, instead of wp-cli halting with a PHP Fatal error?

We can handle the exception. It will need to be a hard error though, instead of a warning and continuing.
