### ISSUE TITLE
Skipping cache on WordPress update

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3264]
WP was at `4.6-RC1-38210`.

I tried to update with `wp core update`.

```
Updating to version 4.6-RC1-38238 (en_US)...
Using cached file '/home/ubuntu/.wp-cli/cache/core/wordpress-4.6-latest-en_US.zip'...
Unpacking the update...
```

I was expecting it will fetch new `4.6-RC1-38238` from dot org. It seems we are ignoring later part of the version string.

Is it possible to skip cache for the command? Like `--skip-cache` or similar?

**Comment by danielbachhuber** [comment]
> I tried to update with wp core update.

Shouldn't that be `wp core update --nightly`, to update to the latest nightly?

> Is it possible to skip cache for the command? Like `--skip-cache` or similar?

No. You shouldn't have to think about skipping the cache. If you need to reset things, you can delete the cache directory.

**Comment by ernilambar** [comment]
```
$ wp core version
4.6-RC1-38238
```

```
$ wp core update --version=nightly
Success: WordPress is up to date.
```

Then I downloaded zip from https://wordpress.org/nightly-builds/wordpress-latest.zip and checked `version.php`. It is `$wp_version = '4.7-alpha-38242';`

**Comment by danielbachhuber** [comment]
> Shouldn't that be `wp core update --nightly`, to update to the latest nightly?

Sorry, I was incorrect. It should be `wp core download --version=nightly`. `wp core update` doesn't support `--version=nightly`

> I was expecting it will fetch new 4.6-RC1-38238 from dot org. It seems we are ignoring later part of the version string.

Why do you expect that `wp core update` handles nightly versions?

**Comment by ernilambar** [comment]
I believe `wp core update` should take WP install to valid available version, whether it is stable release or nightly release.

**Comment by danielbachhuber** [comment]
`wp core update` doesn't support `--version=nightly`, because it calls the WordPress updater under the hood, and the WordPress updater doesn't understand `nightly` as a version.

If you want to install the nightly build, you can use `wp core download --version=nightly`
