### ISSUE TITLE
add_command passing a object with constructor not working

### ISSUE THREAD

**Issue by romulodl** [wp-cli/wp-cli#3265]
I am trying to create a command which contains a `__construct` method is not working.

```php
class Command extends WP_Cli_Command
{
    public function __construct($my_param) {
         echo "hello" . $my_param;
    }

    // subcommands
}

$my_command = new Command("testing parameter");
WP_CLI::add_command('my_command', $my_command);
```

Is returning an error on https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Dispatcher/CommandFactory.php#L64-L71 expecting a parameter for my constructor method.

Is there any way to fix this? Or a way to send an object which is not instantiated within `add_command`?

Thanks
Romulo

**Comment by danielbachhuber** [comment]
Can you share `wp --info` ?

**Comment by danielbachhuber** [comment]
Nevermind. I just confirmed the bug.

**Comment by romulodl** [comment]
Hello @danielbachhuber.

Thank you for fixing this! 👍
