### ISSUE TITLE
Wp cli update tries to overrite /usr/bin/wp

### ISSUE THREAD

**Issue by merhawifissehaye** [wp-cli/wp-cli#3281]
I don't have access to /usr/bin/wp. I am running wp from ~/bin. There has to be an option on `wp cli update /path/to/binary`.

**Comment by danielbachhuber** [comment]
> I don't have access to /usr/bin/wp. I am running wp from ~/bin.

Can you share `wp --info`, and the full output when you run `wp cli update`?

> There has to be an option on wp cli update /path/to/binary.

We're not going to add an opinion.

**Comment by merhawifissehaye** [comment]
The output of `wp --info`
`PHP binary:     /ramdisk/php/54/bin/php54-cli
PHP version:    5.4.43
php.ini used:   /root/wp-cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.19.2`

The output of `wp cli update`
`Error: /root/php/54/usr/bin/wp is not writable by current user`

**Comment by danielbachhuber** [comment]
What makes you think that you're running `wp` from `~/bin`? Can you share `which wp` ?

**Comment by merhawifissehaye** [comment]
I followed the installation instruction and instead of moving wp-phar.cli to /usr/bin/wp I moved it to my ~/bin/wp directory.
`which wp` gives me nothing
`which ~/bin/wp` gives me /home1/username/bin/wp

**Comment by danielbachhuber** [comment]
Ok. It's hard to say what the problem might be without access to your environment, and further debugging.
