### ISSUE TITLE
Can't download WP RC using --version due to lowercasing of the version

### ISSUE THREAD

**Issue by jorgeatorres** [wp-cli/wp-cli#3282]
Hi guys,

Something like the following doesn't seem to work:

```
wp-cli core download --version=4.6-RC2
```

It seems it is because in https://github.com/wp-cli/wp-cli/blob/50640dd93e668534c3df36c43abb9448181f1e9b/php/commands/core.php#L137, the version number is lowercased, but, in this case, case is important 😅.

For instance, https://wordpress.org/wordpress-4.6-RC2.tar.gz exists, while https://wordpress.org/wordpress-4.6-rc2.tar.gz doesn't.

Thanks!

**Comment by danielbachhuber** [comment]
> the version number is lowercased, but, in this case, case is important

Seems like a bug :)

**Comment by jorgeatorres** [comment]
@danielbachhuber: thanks for your answer. I know this is a minor thing, but I've submitted a PR for this (#3283), just in case.
