### ISSUE TITLE
Missing command: wp plugin check-update

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3285]
Ha! Writing some update automation I expected to find ```wp plugin check-update``` like there is
```wp core check-update``` - but this command does not exist! 

It would be great if you could add this update status check also for the plugin subcommand. 

Anyway: I would like to do something (in a script), but only when updates are available (core, plugins, maybe also themes) - is there any way to do this with or without wp-cli? If there is any way to reliably check plugin update status, please give me a hint, I am stuck, THANKS!!!

**Comment by danielbachhuber** [comment]
> Ha! Writing some update automation I expected to find `wp plugin check-update` like there is
> `wp core check-update` - but this command does not exist!

You can check for plugins with updates with `wp plugin list`: http://wp-cli.org/commands/plugin/list/

> If there is any way to reliably check plugin update status, please give me a hint, I am stuck, THANKS!!!

Please see http://wp-cli.org/#support

**Comment by hirasso** [comment]
Alternatively, use `wp plugin status` for all plugins or `wp plugin status your-plugin-name` for a specific plugin.
