### ISSUE TITLE
How to get the ssh alias configuration in a custom command?

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3287]
How can I access the @aliases defined in a `wp-cli.yml` from within a custom script? 

I looked at Runner.php, but there is too much happening. 
I just want to access the project specific defined ssh aliases and their values, how to do this?

BTW this would be a nice topic for a tutorial about how to create wp-cli commands. 
The scaffolding for custom commands is great, but it should also contain at least some real life useful snippets, e.g. how to access configuration data.

The documentation about [get_config](https://wp-cli.org/docs/internal-api/wp-cli-get-config/) unfortunately is not extremely exhaustive and the code e.g. of Runner.php has not too many helpful comments. 

Before digging deeper, I hope for a hint, thank you very much for your attention!

**Comment by danielbachhuber** [comment]
> I just want to access the project specific defined ssh aliases and their values, how to do this?

See http://wp-cli.org/#support
