### ISSUE TITLE
Fatal error in packages should not breal wp-cli

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3288]
Hmm, I am a bit surprised to see that a fatal error in a package will break wp-cli execution, at least it did here just now. Wouldn't it be good if fatal errors in vendor code would be reported, but not break anything? Possible with PHP error handing?

**Comment by danielbachhuber** [comment]
> Wouldn't it be good if fatal errors in vendor code would be reported, but not break anything? Possible with PHP error handing?

A fatal error is exactly that: fatal.
