### ISSUE TITLE
plugin: docs not clear about how to define --fields

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3289]
It is not obvious how to format the `--fields` paramter for the plugin command. 
It took me a few minutes to long to understand that this is the accepted syntax:
```
wp plugin list --fields="name, update_version, update_package, update_id"
```

May seem trivial, but why not just put that example into the docs to make it super understandable for everybody and avoid that micro-distraction? 

Thanks again for your attention!

**Comment by danielbachhuber** [comment]
> May seem trivial, but why not just put that example into the docs to make it super understandable for everybody and avoid that micro-distraction?

`--fields=<fields>` is actually a relatively common argument across WP-CLI commands: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Awp-cli.org%20fields

It's not really viable to include an example of every argument with every command. wp user list ([doc](http://wp-cli.org/commands/user/list/)) contains an example of the `--fields=<fields>` parameter though:

```
# List users with only given fields
$ wp user list --fields=display_name,user_email --format=json
[{"display_name":"supervisor","user_email":"supervisor@gmail.com"}]
```
