### ISSUE TITLE
plugin: not possible to list github source of plugin

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3290]
It seems not to be possible to list the source of plugins that where installed from gihub. While it is possible to install plugins from github repos e.g. with
```
wp plugin install https://github.com/norcross/airplane-mode/zipball/master
```
what is great and very comfortable, it seems like that important source information is not saved anywhere, so it is not possible to list it. 

Here is a use case when this gets a problem: you want to save a list of all the activated plugins and install them on a different server. The names of plugins in that list that have been installed from github will lead to an error when trying to install:
```
$ wp plugin install norcross-airplane-mode-5f717c9
$ Warning: Couldn't find 'norcross-airplane-mode-5f717c9' in the WordPress.org plugin directory.
```

**Comment by danielbachhuber** [comment]
> it seems like that important source information is not saved anywhere, so it is not possible to list it.

Right, this is correct.
