### ISSUE TITLE
plugin: add npm-style --save and --save-dev feature and make wp plugin install use it

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3291]
Please add npm-style `--save` and `--save-dev` options to the `wp plugin install` command. 

These options will generate by default a `plugins.json` or `plugins.yml` file, which by default should be saved to the project base directory, but of course the save path **must** be configurable, e.g. via a `--save-path` option and via a  `save-output-path` key in the project specific `wp-cli.yml`. 

This option defines a directory, not the filename, so it will be possible to save multiple files, e.g. saving only activated plugins, saving only favorite plugins, etc. 

A `--save-home` option will save to the users wp-cli config directory in $HOME.

To let users define the name of the generated files an option named `--save-filename` should exist. 

Also it should be implemented an option for saving plugin configuration data named `--save-options`. 
Details about this additional feature should be discussed in a separate issue. 

Regarding the format of the generated files I see no problem with just dumping all the plugin meta information that is available (not help text content of course) and allow for local / private / package / plugin generated additions to these files. Please also see #3290 for a current problem that should be solved with this feature. It is important to avoid any limitations, e.g. in what an implementation that reads from these files will expect (ignore unknown stuff that could be handled by plugins or packages).

Actually this should provide a generalized infrastructure for building lists of plugin metadata that could be used for any plugin related data collection. Taking it one step further an implementation should not prevent the optional saving to a database as a datastore, however for now it would be ok to just keep that possibility in mind.

Now, to make sense of that, the `wp plugin install` command should be able to read these files and install all the plugins defined in there (from anywhere, please see #3290). Luckily there is currently no default action defined for `wp plugin install` (besides printing help) - what makes this a wonderful candidate for implementation of a npm-like install behaviour and would be a great step forward to a "tool parity webdev universe", if such a thing might ever exist.

Also the `wp plugin list` command should be adjusted to be able to save to the same file format when the `--save` or `--save-dev` options are given, so that lists of plugins generated with this command can be used by `wp plugin install`. Details about this feature should be discussed in a separate issue.

I am aware that there currently exists an option to save the result of the list subcommand to a json or yaml file via the generic output handling of wp-cli (good thing, btw!). Also several 3rd party solutions (better said, attempts) exist to provide similar functionality. However, this issue is not only about enhancing the current output options, it is about defining one 'canonical' way to export / import / install collections of plugins (and optionally their configuration) with wp-cli, what is currently missing if I am not wrong. 

BTW I do not think composer is the right way to handle that. It might be a good idea to use some features of composer, like e.g. dependency handling, but it would be wrong to force people to use composer. This should be an explicit wp-cli feature with its own config files.

Finally a good default use for `wp plugin install` - what do you think?

**Comment by danielbachhuber** [comment]
Thanks for taking the time to write this out, @COLABORATI 

Because WP-CLI is a mature project, new features are expected to be developed as [community packages first](http://wp-cli.org/package-index/).

**Comment by COLABORATI** [comment]
Thanks for taking the time to react in a way that helps me to learn how a mature project works.
However, how would you implement the default behaviour for `wp plugin install` with a package?

**Comment by danielbachhuber** [comment]
> However, how would you implement the default behaviour for wp plugin install with a package?

@COLABORATI Github issues aren't the appropriate place for support questions. See http://wp-cli.org/#support

**Comment by COLABORATI** [comment]
This is not a support question - I have to assume that you understand that very well.

**Comment by danielbachhuber** [comment]
> This is not a support question - I have to assume that you understand that very well.

If it's not a bug report or an enhancement to an existing command, then it's a support question.

If it's framed as "how do you do X?", "how would you do X?", or some variation of asking how to do something, then it's a support question.

Github issues aren't the appropriate venue for support questions, nor does using WP-CLI grant you commitments of other peoples' times for answering support questions.

If you disagree with this answer, that's fine — you're welcome to your opinions. However, I expect you to abide by the established policies for this issue tracker.
