### ISSUE TITLE
Are there methods for get_current_blog_id, get_blog_details or $wpdb->prefix?

### ISSUE THREAD

**Issue by jgraup** [wp-cli/wp-cli#3292]
I'm looking for some extra information about an mu site (`--url`) when attempt to export from a remote server to my local testing environment. 

One requirement for migration is the existing `blog_id` and database prefix. Using those I can do a search/replace on the `exported.sql` for `<wp-prefix>_<blog_id>_` to slot it into the correct db table on import.

Is there a better way to get the `blog_id` here? And can I get more information like the table prefix without running `eval`?

`blog_id=$(wp eval --url=http://domain.com/site-name/ 'echo get_current_blog_id();');`

`prefix=$(wp eval --url=http://domain.com/site-name/ 'global $wpdb; echo $wpdb->prefix;')`

Thanks.

**Comment by danielbachhuber** [comment]
Hi @jgraup,

Our [support policies have changed](http://wp-cli.org/blog/support-policy.html). This question falls outside of a bug report, enhancement request, or documentation suggestion.

**Comment by jgraup** [comment]
Thanks @danielbachhuber - I figured it was a stretch. I'll stick to the other locations for questions like these in the future. Thanks for your time.
