### ISSUE TITLE
Force reinstall all plugins or themes

### ISSUE THREAD

**Issue by jb510** [wp-cli/wp-cli#3293]
I feel like this has been suggested before, but the past issues I found were actually different (either about core, or about an individual plugin/theme)

I would really like it if there were a way to:
`wp plugin update --all --force`
and
`wp theme update --all --force`

Which would reinstall all plugins/themes with the latest version from the repo.

There is a regular plugin I've used for this in the past: https://wordpress.org/plugins/baw-force-plugin-updates/ but it seems a natural fit to wp cli.

This is common step when dealing with a hacked site and frankly I'd like to run it periodically on non-hacked sites just in case anything got out of sync between repos and servers.

**Comment by danielbachhuber** [comment]
You can achieve the same by [composing](http://wp-cli.org/docs/philosophy/#composability-is-always-a-good-idea) two commands:

```
$ wp plugin install $(wp plugin list --field=name) --force
Warning: Couldn't find 'airplane-mode' in the WordPress.org plugin directory.
Installing Akismet (3.1.11)
Downloading install package from https://downloads.wordpress.org/plugin/akismet.3.1.11.zip...
Unpacking the package...
Installing the plugin...
Removing the old version of the plugin...
Plugin updated successfully.
```

I'll include this as an example in the docs

**Comment by jb510** [comment]
Oh fancy! Thanks!

Question (obviously I'm not that versed in bash scripting): Is the first $ your bash prompt?  I use zsh and have a custom prompt, but I it didn't work when I included the first $.

`wp plugin install $(wp plugin list --field=name) --force`

Obviously I'm not that versed in bash syntax....   I found this https://www.gnu.org/software/bash/manual/bash.html#Command-Substitution which I assume is that function, just want to make sure I'm not missing something.

**Comment by danielbachhuber** [comment]
> Is the first $ your bash prompt? I use zsh and have a custom prompt, but I it didn't work when I included the first $.

No, `$` is just an indicator for a command being entered into the bash prompt (compared to output from the command).

**Comment by khromov** [comment]
Great snippet @danielbachhuber 

If anyone is looking to reinstall themes in the same manner, the command is:

```
wp theme install $(wp theme list --field=name) --force
```

**Comment by jb510** [comment]
So this normally works, but I'm getting fatals from plugins and the theme calling a member function on null (old code using globals).  Normally --skip-plugins and --skip-themes would bypass that, but here I get

```
root@f19514d19c46:/# wp plugin install $(wp plugin list --field=name) --force --skip-plugins --skip-themes

usage: wp plugin install <plugin|zip|url>... [--version=<version>] [--force] [--activate] [--activate-network]
root@f19514d19c46:/#
```
I guess you can't skip when installing?  Seems odd tough I thought those were global https://developer.wordpress.org/cli/commands/plugin/install/

**Comment by danielbachhuber** [comment]
@jb510 You're using bash substitution, which means you're running two separate commands. You'll need to also run `wp plugin list --skip-plugins --skip-themes`

**Comment by jb510** [comment]
damn it... that thought occurred to me briefly and then I forgot to try it. You bash skilled are legendary...

**Comment by sharmashivanand** [comment]
Try this if you don't want to attempt drop-ins, mu-plugins, waste files left inside plugins folders etc.

This carefully looks for directories only inside wp-content/plugins and forces a reinstall.

`wp plugin install $(ls -1p wp-content/plugins | grep '/$' | sed 's/\/$//') --force`

**Comment by tygalive** [comment]
You can also use [Force Reinstall](https://wordpress.org/plugins/force-reinstall/) to force plugin and theme reinstallation
