### ISSUE TITLE
wp export does fail, export frfom gui works

### ISSUE THREAD

**Issue by COLABORATI** [wp-cli/wp-cli#3300]
`wp export` does produce an incomplete xml dump, it just stops after the last term. 

The export from admin gui does work without any problems and contains everything.

**Comment by danielbachhuber** [comment]
> wp export does produce an incomplete xml dump, it just stops after the last term.

Does this reproduce on a new WordPress install with all themes and plugins deactivated?

Can you share specific steps to reproduce?

**Comment by COLABORATI** [comment]
Forget it, I will take another route.

I just occasionally have to dive into this dark php and wordpress underworld, fortunately for this use case at hand it is not too late to switch.

Have fun!
