### ISSUE TITLE
Consider removing symfony/finder as a dependency

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3305]
If we can remove our current use of symfony/finder, we can greatly reduce the number of included dependencies.

Related #3304

**Comment by danielbachhuber** [comment]
> we can greatly reduce the number of included dependencies.

As it turns out, Composer is dependent on `symfony/process`

**Comment by danielbachhuber** [comment]
... and Composer is dependent on `symfony/finder`:

```
"symfony/console": "^2.5 || ^3.0",
"symfony/finder": "^2.2 || ^3.0",
"symfony/process": "^2.1 || ^3.0",
"symfony/filesystem": "^2.5 || ^3.0",
```

So, we won't ever be able to remove Symfony from the dependencies.

We could potentially change the version constraint to `"^2.2 || ^3.0"`, but we'd need to make sure the Phar is always built with `^2.2` for PHP 5.3/4 support.

**Comment by thefrosty** [comment]
> As it turns out, Composer is dependent on `symfony/process`
> ... and Composer is dependent on `symfony/finder`

So it's reliant on both of these? 

I'll gladly test out the version updates. Hoping it could work out since we're running PHP 7.x.

**Comment by danielbachhuber** [comment]
> We could potentially change the version constraint to `"^2.2 || ^3.0"`, but we'd need to make sure the Phar is always built with `^2.2` for PHP 5.3/4 support.

I think this is more complexity than it's worth. Plus, if it breaks, it breaks a lot of things for a lot of people. Punting on this for now.
