### ISSUE TITLE
Fatal error: Call to undefined function apply_filters() in /home/public/wp-includes/load.php on line 317

### ISSUE THREAD

**Issue by gothmog123** [wp-cli/wp-cli#3308]
Hi,

after upgrading to wp 4.6, I get the error message in the title for all wp cli commands.

I apologize if this is not a bug, more like a support request.

Thank you.

**Comment by ernilambar** [comment]
@gothmog123 Can you please post output of `wp --info`?

**Comment by gothmog123** [comment]
Hi ernilambar,

Here it is:

PHP binary:	/usr/local/php/5.6.24-nfsn1/bin/php
PHP version:	5.6.24-nfsn1
php.ini used:	/usr/local/php/5.6.24-nfsn1/etc/php-cli.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/private//.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.23.1


Some command actually work, but most don't.

**Comment by ernilambar** [comment]
You are using `0.23.1` version. To make compatible with WP 4.6, please update WP-CLI to `0.24.1`.

**Comment by gothmog123** [comment]
Thanks for the replies. I think I'm not allowed to access wp cli files. It's a shared server at NFSN...

**Comment by jb510** [comment]
@gothmog123 have you tried `wp cli update` ? You may be correct that you need to wait for someone with privileges to update it for you.

**Comment by diggy** [comment]
@danielbachhuber has this issue been resolved? Running into the exact same error with `0.24.1` (doing `search-replace` on remote server)

**Comment by danielbachhuber** [comment]
> has this issue been resolved? Running into the exact same error with WP 4.6 and WP-CLI 0.24.1 (doing search-replace on remote server)

Yes. You're likely running into a different issue.

**Comment by JonathanDoughty** [comment]
Same problem; only when I back out the changes that led to the "PHP Fatal error:  Call to undefined function apply_filters()" and try to `wp cli update` I get "Error: The downloaded PHAR is broken, try running wp cli update again" - repeatedly. I can curl -O https://github.com/wp-cli/wp-cli/releases/download/v0.24.1/wp-cli-0.24.1.pharand the result has an sha256 of ba1ba7a66f6a2a983910d4497771a255dfa8212ab7787fb4fbd21cd9102f2dbc

wp --info
PHP binary:	/usr/bin/php5
PHP version:	5.6.24-0+deb8u1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/admin/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.23.1

**Comment by danielbachhuber** [comment]
@JonathanDoughty Github issues are no longer the appropriate place for general support. Please see http://wp-cli.org/#support
