### ISSUE TITLE
Update the config template to match the one generated by WP

### ISSUE THREAD

**Issue by veganista** [wp-cli/wp-cli#3311]
I think it might be handy for future developers ( who inherit our projects ) for the config file to have all the comments in that the wizard generated one has.

These are pretty handy especially for newer developers.

Happy to make a PR if you think it's useful.

**Comment by danielbachhuber** [comment]
> I think it might be handy for future developers ( who inherit our projects ) for the config file to have all the comments in that the wizard generated one has.

Sure, I'm amenable to this. Note that our `wp-config.php` doesn't include some constants intentionally, so the comments should just reflect the constants defined in WP-CLI's template.
