### ISSUE TITLE
ability to exclude wp_posts revisions from search-replace

### ISSUE THREAD

**Issue by drzraf** [wp-cli/wp-cli#3313]
search-replace is a great tool and it's exclude functionality is neat.
Anyway it lacks some granularity in table column choice.
One use-case is the following: I want to change the URL/hostname inside contents, but only the last published version (not the old/unpublished revisions).
Currently there is no way to act as such, but that would be appreciable.
That would imply a way to pass SQL-conditions to the command line tool in _some way_

**Comment by danielbachhuber** [comment]
> That would imply a way to pass SQL-conditions to the command line tool in some way

Why can't you just use a SQL statement in this case? post content shouldn't have serialized data

**Comment by drzraf** [comment]
> > That would imply a way to pass SQL-conditions to the command line tool in some way
> Why can't you just use a SQL statement in this case? post content shouldn't have serialized data

indeed, I could and you're may be right.

The best way would then be:
1* SQL UPDATE on wp_post
2* wp-cli --excluding' the whole wp_post table
and that wouldn't needs modification to wp-cli.

feel free to close

**Comment by david-treblig** [comment]
Hi, I'd like to revisit this issue. I indeed needed to switch around some markup included in serialized Gutenberg data just now and I wanted to avoid affecting revisions. 🤔  If they could be ignored, it would be the best case scenario here. Unless there is already a way that I don't know of to input our own custom "where" statements? Or would it be too close to writing SQL in the cli, which I think we should avoid... Just pitching ideas: what about a syntax to supplement the "--ignore-columns" flag? Like ```--ignore-columns="post_type=revision"```? Too much of a hassle to parse and pass to the required sql?

**Comment by drzraf** [comment]
You could test https://github.com/wp-cli/wp-cli/issues/3313 and report it worked for you.

**Comment by david-treblig** [comment]
Ooh that looks promising. Thank you so much! I didn't find that when I was researching the issue. Apologies for the useless ping 🤘

**Comment by davidwebca** [comment]
Found this issue back now almost 2 years later needing to achieve the same thing and that pull request hasn't been merge. Rip.
