### ISSUE TITLE
Intersection classes in new wordpress 4.6

### ISSUE THREAD

**Issue by evilebottnawi** [wp-cli/wp-cli#3315]
`wp-cli` use `rmccue/requests` package which have `Requests_Response` class and new wordpress have `Requests_Response` class. We have error after install `wp-cli` on `http://domain/wp-admin` page:
```
Fatal error: Uncaught Error: Call to undefined method Requests_Response::is_redirect() in /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-includes/class-requests.php:687
Stack trace: #0 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-includes/class-requests.php(383): Requests::parse_response(Array, 'http://api.word...', Array, Array, Array) 
#1 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-includes/class-http.php(366): Requests::request('http://api.word...', Array, Array, 'POST', Array) 
#2 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-includes/class-http.php(573): WP_Http->request('http://api.word...', Array) 
#3 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-includes/http.php(187): WP_Http->post('http://api.word...', Array) 
#4 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-admin/includes/dashboard.php(1414): wp_remote_post('http://api.word...', Array) 
#5 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-admin/includes/dashboard.php(27): wp_check_browser_version() 
#6 /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-admin/index.php(15): wp_dashboard_setup() 
#7 {main} thrown in /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-includes/class-requests.php on line 687
```

**Comment by danielbachhuber** [comment]
Can you share `wp --info`?

**Comment by danielbachhuber** [comment]
Actually, it looks like Requests v1.7 needs to be tagged, and then WP-CLI can use that.

**Comment by evilebottnawi** [comment]
@danielbachhuber be good if we fast fix this and release, if we need i can help :smile:

**Comment by danielbachhuber** [comment]
> be good if we fast fix this and release

We're waiting on @rmccue to tag the new version of Requests.

**Comment by swissspidy** [comment]
I already mentioned the tagging issue to Ryan a few days ago, seems like he's quite busy at the moment. This would solve issues like ServerPress/ds-cli#3 that have been brought up after the 4.6 release.

**Comment by schrapel** [comment]
This is blocking us upgrading to 4.6.

@rmccue when are you able to tag this?

**Comment by schrapel** [comment]
@evilebottnawi in the meantime we are using this in our made composer.json

` "rmccue/Requests"                                               : "dev-master#c887fdbbee5e012ae642eb2e0560b5a42fb4782e as 1.6.1",`

**Comment by evilebottnawi** [comment]
@schrapel Thanks!

**Comment by schrapel** [comment]
@danielbachhuber really though if this is now included in core surely we don't need to require it in wp-cli since it will load when we load wordpress?

**Comment by swissspidy** [comment]
@schrapel Backward compatibility would be a concern I guess.

**Comment by danielbachhuber** [comment]
> really though if this is now included in core surely we don't need to require it in wp-cli since it will load when we load wordpress?

WP-CLI works independently of WordPress.

**Comment by manuelRod** [comment]
do you know guys if is there any progress on that?

**Comment by evilebottnawi** [comment]
@manuelRod use https://github.com/wp-cli/wp-cli/issues/3315#issuecomment-242084985, we should wait when new version was released.
