### ISSUE TITLE
Can proceed with plugin upgrades after upgrade of core WP to 4.6

### ISSUE THREAD

**Issue by pmirek** [wp-cli/wp-cli#3324]
Versions:
 ./wp-cli.phar plugin search "test" --path=/apps/knowledge_base/wordpress/
WordPress version: 4.6
Database revision: 37965
TinyMCE version:   4.401 (4401-20160726)

wp-cli : latest version
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

Errors:
 ./wp-cli.phar plugin search "test" --path=/apps/knowledge_base/wordpress/
PHP Notice:  Undefined index: SERVER_PORT in /apps/knowledge_base/wordpress/wp-content/plugins/ajax-search-lite/includes/functions/functions.php on line 514
Notice: Undefined index: SERVER_PORT in /apps/knowledge_base/wordpress/wp-content/plugins/ajax-search-lite/includes/functions/functions.php on line 514
PHP Notice:  Undefined index: SERVER_NAME in /apps/knowledge_base/wordpress/wp-content/plugins/ajax-search-lite/includes/functions/functions.php on line 515
Notice: Undefined index: SERVER_NAME in /apps/knowledge_base/wordpress/wp-content/plugins/ajax-search-lite/includes/functions/functions.php on line 515
PHP Notice:  Undefined index: SERVER_PORT in /apps/knowledge_base/wordpress/wp-content/plugins/ajax-search-lite/includes/functions/functions.php on line 515
Notice: Undefined index: SERVER_PORT in /apps/knowledge_base/wordpress/wp-content/plugins/ajax-search-lite/includes/functions/functions.php on line 515
PHP Warning:  An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /apps/knowledge_base/wordpress/wp-admin/includes/plugin-install.php on line 158
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /apps/knowledge_base/wordpress/wp-admin/includes/plugin-install.php on line 158
Error: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/">support forums</a>. Try again

This one is because of some connectivity issue. I'm not sure if this is WP problem or wp-cli, as there was change for http api for wp connections over the proxy (which is my case). If this is wp core issue, please ignore.

http_proxy sys env works fine, as I can access wordpress plugins zip files manually with curl or wget.

https://core.trac.wordpress.org/ticket/37494

**Comment by danielbachhuber** [comment]
> I'm not sure if this is WP problem or wp-cli, as there was change for http api for wp connections over the proxy (which is my case). If this is wp core issue, please ignore.

WP-CLI calls WordPress under the hood, so this is likely a problem with WP itself.

**Comment by pmirek** [comment]
Thanks!

**Comment by pmirek** [comment]
The thing is that searches from WP itself works fine. Results show up in the web interface. But I can't get them via proxy & wp-cli.

**Comment by danielbachhuber** [comment]
> The thing is that searches from WP itself works fine. Results show up in the web interface. But I can't get them via proxy & wp-cli.

I think this is because WP-CLI is using an older version of Requests. See https://github.com/wp-cli/wp-cli/issues/3315
