### ISSUE TITLE
wp cache type - call to undefined function

### ISSUE THREAD

**Issue by blindpet** [wp-cli/wp-cli#3325]
I am on Debian Wheezy running memcached object cache enabled through the memcached is your friend plugin. I am trying to check the cache type

`wp cache type --allow-root`

I get this error

`PHP Fatal error:  Call to undefined function apply_filters() in /var/www/htpcguides.com/wp-includes/load.php on line 317
`
I updated wp-cli to the latest version and now checking the cache type returns Unknown

**Comment by ernilambar** [comment]
Are you using `0.24.1` version of WP-CLI? If not, please upgrade.

**Comment by blindpet** [comment]
@ernilambar at the end it says I updated to the latest version and now I just get Unknown when running `wp cache type`

**Comment by ernilambar** [comment]
Can you please post output of `wp --info `?

**Comment by blindpet** [comment]
Sure

```
PHP binary:     /usr/bin/php5
PHP version:    5.6.25-1~dotdeb.7.1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1
```

**Comment by danielbachhuber** [comment]
> now I just get Unknown when running `wp cache type`

"MemcacheD Is Your Friend" isn't one of the plugins we're checking for.

**Comment by blindpet** [comment]
That explains it @danielbachhuber where can I request plugins that are checked by wp-cli for object cache?

**Comment by danielbachhuber** [comment]
> where can I request plugins that are checked by wp-cli for object cache?

I took a look at checking for MemcachedD Is Your Friend, but decided against it because it doesn't seem to be actively supported and hasn't been updated for a year. I'm not sure it's viable for WP-CLI to identify every possible object cache drop-in.
