### ISSUE TITLE
custom php.ini for wp server?

### ISSUE THREAD

**Issue by harryfinn** [wp-cli/wp-cli#3328]
I've been looking to see if there is an option for passing a path to a custom `php.ini` file when using the `wp server` command but can't seem to find anything relating to this?

The built-in php server allows for this when using `-c` option, i.e. `php -S localhost:8080 -c php.ini` - is this something that wp-cli currently allows for or supports somehow?

**Comment by danielbachhuber** [comment]
> is this something that wp-cli currently allows for or supports somehow?

Not at the moment, but we could add support.

**Comment by harryfinn** [comment]
Thanks for the speedy response @danielbachhuber! It's definitely something myself and colleagues
would benefit from, primarily when we've got different WP projects with alternating php config options required and wanting to test locally etc.
