### ISSUE TITLE
0.24.1: Fatal error:  Cannot access private property WP_Object_Cache::$cache

### ISSUE THREAD

**Issue by lkraav** [wp-cli/wp-cli#3329]
```shell
$ wp cli info
PHP binary:     /opt/cpanel/ea-php56/root/usr/bin/php
PHP version:    5.6.24
php.ini used:   /opt/cpanel/ea-php56/root/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /home/convers/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.1
$ wp export --post_type=research-study
Starting export process...
Writing to file /home/convers/public_html/institute/wordpress.2016-08-22.000.xml
$ ls -l wordpress.2016-08-22.000.xml 
-rw-rw-r-- 1 convers convers 0 Aug 22 12:25 wordpress.2016-08-22.000.xml
```

0-byte file gets written, because the export actually crashes `[22-Aug-2016 16:25:08 UTC] PHP Fatal error:  Cannot access private property WP_Object_Cache::$cache in phar:///home/convers/.local/bin/wp/php/utils-wp.php on line 220`

EDIT object cache in use is Redis, with https://wordpress.org/plugins/redis-cache/

**Comment by lkraav** [comment]
Looks like the same thing as

https://wordpress.org/support/topic/make-function-public-instead-of-private

which points us to

https://github.com/10up/ElasticPress/issues/522

Not sure what the way forward here. Is it OK for the object cache implementations to have those class members as `public`, or are the users accessing them incorrectly?

**Comment by danielbachhuber** [comment]
> EDIT object cache in use is Redis

This is a problem with Redis Cache, not WP-CLI.

**Comment by jdanarola** [comment]
I am facing same problem. We are using Redis cache only. We tried to change private to public but still it gives error. 

Have you find any solution for it?

**Comment by blindpet** [comment]
Shame it doesn't work @jdanarola as lkraav says it [should work ](https://wordpress.org/support/topic/make-function-public-instead-of-private/)

I have everything working with this forked and fixed [memcached](https://github.com/wpbullet/memcached-is-your-friend) 

I recommend using [unix sockets](https://guides.wp-bullet.com/configure-memcached-to-use-unix-socket-speed-boost/) too for extra speed
