### ISSUE TITLE
Could we have documentation on how to setup an environment so that using --allow-root can be avoided?

### ISSUE THREAD

**Issue by blue928** [wp-cli/wp-cli#3333]
I've searched through all the recommended support channels and cannot find documentation on how to best get this setup.

I have an Ubuntu 16 server setup with typical LAMP stack with www-data:www-data for Apache.

When I run the command that the "no --allow-root" error suggests (sudo -u www-data -i -- wp <command>) I get an error that "This account is currently not available."

I'm at a loss of how to move forward correctly, avoiding issues in #973. If this is already documented somewhere, please point me in the right direction?

Related:
http://wordpress.stackexchange.com/questions/236725/whats-the-proper-way-to-setup-wp-cli-on-ubuntu-so-that-i-dont-have-to-use-the

**Comment by danielbachhuber** [comment]
> Could we have documentation on how to setup an environment so that using --allow-root can be avoided?

We discourage use of WP-CLI as root. You should switch to another user.

**Comment by blue928** [comment]
Thank you for the quick response. Yes, I understand that using root is discouraged, and I'm trying to setup the environment correctly so that I don't have to.

Trying to run  wp-cli as WWW-DATA throws an error that the account does not exist.

What do I need to do so this works correctly? Which user do I run it as?

**Comment by danielbachhuber** [comment]
> Trying to run wp-cli as WWW-DATA throws an error that the account does not exist.
> 
> What do I need to do so this works correctly? Which user do I run it as?

I'm sorry, but debugging this particular issue is outside the scope of WP-CLI's issue tracker.

**Comment by blue928** [comment]
The issue is not about debugging it but having documentation that explains its correct usage for different environments, even, if that's necessary. Is this documented somewhere?

**Comment by danielbachhuber** [comment]
> having documentation that explains its correct usage for different environments, even, if that's necessary. Is this documented somewhere?

There is lots of reference documentation on the internet about how to run a command in different environmental contexts. Given this particular question isn't specific to WP-CLI, it's not necessary to provide documentation about it.

... I don't really want to debate this endlessly. Please respect the fact there are certain things we take responsibility for documenting, and other things we don't. Furthermore, Github issues are an issue tracker for the project, not a general discussion forum. For discussion, you can join the `#cli` channel on the WordPress.org Slack organization.

**Comment by mkormendy** [comment]
If you are logged in as root, just become another user with the following command:

`su [username]`

Replace `[username]` with something like `admin`, or a user you know has privileges to run wp cli commands. (`admin` should be there in many cases).

When done, exit out of that user operation.

**Comment by RomkaLTU** [comment]
I done this woth alias

nano ~/.bashrc

add

alias wp='wp --allow-root'

Logout and login again after that.

**Comment by richardkentgates** [comment]
> The issue is not about debugging it but having documentation that explains its correct usage for different environments, even if that's necessary. Is this documented somewhere?

I am in the same spot. I'm trying to figure out the proper way to do this. I see the suggestion to find your own way to fix the permissions, but I see what is missing is that all of the other ways we can fix the permissions lead us to methods that are discouraged, which leads us back here looking for an answer. 

There are too many people looking for this exact answer for it to continue being ignored. Please stop telling us to look elsewhere. We need a definitive way to set permissions. This seems pretty elementary to any software, how to make it start working to begin with. Please, someone, stop avoiding this question and provide some guidance.

Is there some reason we just refuse to answer this? I've looked on IRC, Facebook, Google and StackOverflow, there is this question all over and no answers. I've been at this for 12 hours str8 now. Just this one topic. Please, for the love of God.
