### ISSUE TITLE
Online doc error

### ISSUE THREAD

**Issue by jonathanlaf** [wp-cli/wp-cli#3341]
On documentation on how to use post delete
- http://wp-cli.org/commands/post/delete/

There's an error on how to delete post in trash :
`# Delete all posts in the trash`
`$ wp post delete $(wp post list --post_status=trash --format=ids)`
`Success: Trashed post 1268.`
`Success: Trashed post 1294.`

But it's not working, you have to specify a post_type:

`wp post delete $(wp post list --post_type=page --post_status=trash --format=ids)`

It could be really helpful to add that it's possible to trigger multiple post_type at once! 

`wp post delete $(wp post list --post_type=page,post --post_status=trash --format=ids)`

**Comment by danielbachhuber** [comment]
> But it's not working, you have to specify a post_type:

Do you have normal posts in your WordPress install?

**Comment by jonathanlaf** [comment]
Yes I have normal post, let me a couple of minute I will share a video link of my console with you.

**Comment by jonathanlaf** [comment]
Oh WP-CLI god, can you forgive me ? I can't reproduce my "bug" so I assumed that I was typing it wrong all that time. I'm so sorry! 

Sorry for wasting your time I just tested it again and again to show it to you and I can't reproduce the problem, I don't type post_type and it default to post like it should. 

Have a good day! 

P.S. Still a good idea to tell that we can select multiple status / post_type with comma.

**Comment by danielbachhuber** [comment]
> P.S. Still a good idea to tell that we can select multiple status / post_type with comma.

This example is already under `wp post list`, actually.
