### ISSUE TITLE
Documentation for "--authors=" wp import command

### ISSUE THREAD

**Issue by mikaelengstrom** [wp-cli/wp-cli#3344]
The section about the --authors command does not say what will happen if 'skip' is entered:

`--authors=<authors>
    How the author mapping should be handled. Options are 'create',
    'mapping.csv', or
    'skip'. The first will create any non-existent users from the WXR file. The
    second will
    read author mapping associations from a CSV, or create a CSV for editing if
    the file path
    doesn't exist. The CSV requires two columns, and a header row like
    "old_user_login,new_user_login". The last option will skip any author
    mapping.`

**Comment by danielbachhuber** [comment]
I see:

> The last option will skip any author mapping.

Did you miss that?
