### ISSUE TITLE
wp theme install error when use google drive link or dropbox link

### ISSUE THREAD

**Issue by tienloc1** [wp-cli/wp-cli#3346]
Hi,

I tried install my private theme from dropbox and google drive, but when I tried, it's always get back this problem:

PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature.

I had think my theme is error, but it isn't, I tried using cloudup storage and it's work good. Maybe you can check it and if it's error, maybe I can have solution so I can use my dropbox link?

My command line:

wp theme install url

Demo link:
Dropbox: https://www.dropbox.com/s/j1rffjcg3wkg59p/katori.1.02.zip?dl=0
Cloudup driect link: https://cldup.com/dvJqI6v2bP.zip?download=katori.1.02.zip

Thank you.

**Comment by danielbachhuber** [comment]
> Maybe you can check it and if it's error, maybe I can have solution so I can use my dropbox link?

If one ZIP file works, but the other does not, then the problem is with the ZIP file, not WP-CLI.

**Comment by tienloc1** [comment]
I still don't know how to use dropbox direct link, the problem here: when get dropbox direct link and using it, it will get back 403 forbidden. Maybe you can investigate it?
