### ISSUE TITLE
Display plugin version of zip file

### ISSUE THREAD

**Issue by rklrkl** [wp-cli/wp-cli#3349]
Updates to commercial plugins (i.e. ones outside the standard WordPress Plugin Directory) often don't appear as "available" in the "wp plugin list" output, despite a license key being entered and there actually being updates available compared to the ones that are installed.

This forces you to either manually log into their commercial site and manually download the updates or screen-scrape the whole process (which is what I do). Annoyingly, even then the download page will have a link to the latest zip *without* any version number visible (either in the link text or in the .zip filename). An example of this is Advanced Custom Fields Pro, but there are others.

What I'd like WP-CLI to do is to parse the contents of the .zip file and tell me what the version number of the plugin is. I don't know if there's an "official" location for the version string (e.g. the comment at the top of plugin_name/plugin_name.php perhaps?). The WP-CLI command would be something like "wp plugin version plugin_filename.zip" and would output just the version number.

**Comment by danielbachhuber** [comment]
> What I'd like WP-CLI to do is to parse the contents of the .zip file and tell me what the version number of the plugin is. I don't know if there's an "official" location for the version string (e.g. the comment at the top of plugin_name/plugin_name.php perhaps?). The WP-CLI command would be something like "wp plugin version plugin_filename.zip" and would output just the version number.

New feature development is happening as [community commands first](http://wp-cli.org/package-index/). This sounds like a good candidate for a community command.
