### ISSUE TITLE
Empty responses?

### ISSUE THREAD

**Issue by MarioKnight** [wp-cli/wp-cli#3350]
I set up WP-CLI on a new server this past Monday, which worked as expected and scripts I've made worked following with no issue.  Yesterday, running the same script gave errors:

```
PHP Warning:  array_slice() expects parameter 1 to be array, null given in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php on line 610
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/wp/php/WP_CLI/Configurator.php on line 132
PHP Warning:  proc_open(): Descriptor item must be either an array or a File-Handle in phar:///usr/local/bin/wp/php/commands/help.php on line 111
PHP Warning:  proc_close() expects parameter 1 to be resource, boolean given in phar:///usr/local/bin/wp/php/commands/help.php on line 111
Content-type: text/html; charset=UTF-8
```

Even when running `--info` I get nothing:

```
# wp --info --allow-root
Content-type: text/html; charset=UTF-8
```

I'm at a loss, as 0.24.1 was working fine earlier in the week.  It does look like PHP was updated from 7.0.9 to 7.0.10 in-between when it worked and when it stopped.  However all of the permissions and location of the phar within `/usr/local/bin/` remained the same.  I know that you can't really give server support, but I was wondering if you could point me in a direction where I can further troubleshoot this.  Thank you in advance for any support you can provide.

**Comment by danielbachhuber** [comment]
> I know that you can't really give server support, but I was wondering if you could point me in a direction where I can further troubleshoot this. Thank you in advance for any support you can provide.

Github issues are [no longer an appropriate venue for support](http://wp-cli.org/blog/support-policy.html)

**Comment by Ipstenu** [comment]
In my case it was becuase the 7.0.10 package for CentOS was buggy and didn’t install CLI properly. If you ran php -v, you got (cgi-fcgi) instead of (cli). It auto-reinstalled itself last night and works now. I can’t even… So! “WP-CLI and _most other_ command like PHP apps won’t behave as expected if your PHP isn’t cli on the cli." 😵

**Comment by MarioKnight** [comment]
This seems to have been exactly it, mine also seems to have reinstalled itself on that server last night, now shows (cli), and my scripts are working again.  Very good to know to keep an eye out for, thank you!  =D

**Comment by ccarrascom** [comment]
i have the same problem but my server looks fine. When i run php -v this is what i see
`# php -v
PHP 5.6.26 (cli) (built: Sep 27 2016 03:23:51)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.1.1, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
    with Suhosin v0.9.38, Copyright (c) 2007-2015, by SektionEins GmbH`

**Comment by ccarrascom** [comment]
i found a solution, just add this into your php.ini 
`suhosin.executor.include.whitelist = phar`
This will whitelist phar packages execution
