### ISSUE TITLE
@alias ignored by `user` commands

### ISSUE THREAD

**Issue by marcusatbang** [wp-cli/wp-cli#3351]
We have an alias defined in local `wp-cli.yml`:

```yaml
@xfer:
  dbname: example_xfer
```

Note that only `dbname` is set; username, password, etc all stay the same as the primary config.

We have a script that (among other things) creates an administrator:

```bash
#!/bin/bash
...
sudo -u www-data wp @xfer user create localdev localdev@bang-on.net
sudo -u www-data wp @xfer user update localdev --role=administrator --user_pass=localdev
```

This creates the user in the primary database, not in the database named by `@xfer`.

We've confirmed that the alias is correctly used by other commands, such as `wp @xfer search-replace`. Running the commands with `--debug` shows:

```
sudo -u www-data wp @xfer user create localdev localdev@bang-on.net --debug
Debug (bootstrap): No readable global config found (0.013s)
Debug (bootstrap): Using project config: /data/example/htdocs/wp-cli.yml (0.014s)
Debug (bootstrap): No package autoload found to load. (0.136s)
Debug (bootstrap): ABSPATH defined: /data/example/htdocs/ (0.137s)
Debug (bootstrap): Begin WordPress load (0.139s)
Debug (bootstrap): wp-config.php path: /data/example/htdocs/wp-config.php (0.14s)
Debug (bootstrap): Loaded WordPress (1.382s)
Debug (bootstrap): Running command: user create (1.382s)
Success: Created user 16.
Password: Ft6mu9UhFCiD
```

This creates the user in the primary database, not in the `example_xfer` database referred to by the alias. The debug output shows that it's aware of the config file. The root folder hasn't changed.

`wp user list` also lists the users from the primary database.

**Comment by danielbachhuber** [comment]
WP-CLI doesn't natively support defining the `dbname` at runtime, nor will the alias feature persist a `dbname` variable. An alias can include 'user', 'url', 'path', 'ssh', or 'http'.

**Comment by marcusatbang** [comment]
So I'd need a whole second WordPress installation in order to reference an alternative database?

**Comment by danielbachhuber** [comment]
> So I'd need a whole second WordPress installation in order to reference an alternative database?

No. It's possible to do with a little bit of code.
