### ISSUE TITLE
List subcommand aliases on man page

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#3353]
When you run `wp help some command` it would be nice if the man page that is displayed would include any aliases for that command as well.

Eg: `wp help plugin update` would also show its alias `upgrade`.  
Perhaps something like this?

```
NAME

  wp plugin update

ALIASES

  wp plugin upgrade

DESCRIPTION
  ...
```

**Comment by danielbachhuber** [comment]
Sure, although lets put it further down the doc.
