### ISSUE TITLE
Allow class-based commands to accept arguments using setters as alternative to parameters

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#3354]
This is a desire I've had for a while.  I'm curious what everyone else might think about it.

I would love to be able to reference command arguments as properties on my command class rather than the arguments passed to the methods.

As it is now, this can still be done, but as far as I know you're left to do the setup within your command method yourself, which gets repetitive and yucky.

Here's how I'm thinking it could work:
- Create an interface, something like `WP_CLI\Receives_Args_As_Props`
```php
namespace WP_CLI;

interface Receives_Args_As_Props
{
    public function receive_positional_args($positional);

    public function receive_associative_args($associative);
}
```
- Create a base class that implements the interface.
- When bootstrapping the command to be run, just check if it implements the interface, and if it does, call those methods with the appropriate arguments.

So, the interface lets WP_CLI not really care about the implementation, but there would also be a base class to satisfy it "out of the box".  That class would be useful for devs who don't need to write their own implementation and just want to extend and go.  The interface would allow the freedom for not requiring inheritance to use it, nor any detail of the implementation.

Of course, this would be entirely opt-in, and I don't see it being hard to implement on the WP-CLI side either.  Methods within the class could still make use of the parameters passed to them if they wanted to, and it would have no effect on non-class-based commands.

I would be willing to propose some code if you're open to it?  I think it would be a great addition before 1.0!

**Comment by danielbachhuber** [comment]
What problem does this solve?

**Comment by aaemnnosttv** [comment]
I would say that this is a feature request on the internal API level.

A simple example would be a `get_flag($flag, $default = null)` method on said class.

Then within the class, within any of the methods you can simply `$this->get_flag('foo')` rather than passing the `$assoc` parameter around and calling the big namespaced function.

Or we could even make use of the synopsis to access parameters using names

Something like 
```php
/**
 * Follow a user
 * <user> <network> [--send-happy-face]
 *
```
We might be able to access the parameters like so:

```php
// pseudo code
{
    $this->param('user')
    $this->param('network')

    if ($this->get_flag('send-happy-face')) {
        // deploy happy face
    }
}
```

By making parameters available on the class at call-time, other cool things become possible, while still remaining compatible with the current way of doing things.

**Comment by danielbachhuber** [comment]
> By making parameters available on the class at call-time, other cool things become possible, while still remaining compatible with the current way of doing things.

Related #2495

Given it's possible to do so, I think it makes most sense to first develop this independently as a standalone package. If it proves to truly be useful, it's something we can eventually consider including in WP-CLI proper.

**Comment by aaemnnosttv** [comment]
Thanks for the link there, the Request class is an interesting idea.  I've been playing with it a bit, but I don't feel like it is a good fit in this case.

I agree with you in regards to making something available as a package first before including in core, but I think we might need a few minor additions in core first (I'll open a new issue).

Using the Request class to solve this is a bit awkward because its re-parsing and processing all the arguments from the `$argv` global rather than accessing what is already done and should be available.  I get that there may be use cases where this makes sense, but in my case, I really just want access to the arguments for the command before the method is invoked.

Consider this simple command:

```php
use WP_CLI\Request;

class TestCommand
{
	/**
	 * Say something
	 *
	 * <what>
	 * : What to say?
	 *
	 * @when before_wp_load
	 */
	public function say()
	{
		WP_CLI::line(Request::get_from_argv()->get_positional_args()[0]);
	}
}

WP_CLI::add_command('test', TestCommand::class);
```

This produces undesired results because it lacks the context of the command being invoked.
```
$ wp test say hi
test
```

The command outputs "test" instead of "hi".

After digging into this more, it seems like a better alternative to achieve the result I'm looking for would be to hook into the `before_invoke:{$cmd}` wp-cli hook, and get the arguments there, but of course that isn't possible right now.  

The other part that I mentioned as a nice enhancement would be the ability to access positional arguments with names is not possible with the Request class as it is now.  In the above example the use would look something like:
```php
$this->argument('what') // returns "hi"
```
I'm not sure that could be done as a package either as it would require access to the invoked command's spec including positional arguments.
