### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by scriptaimago** [wp-cli/wp-cli#3362]
Hi I get this error:
_PHP Fatal error:  include(): Cannot redeclare class requests_cookie in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 414
Fatal error: include(): Cannot redeclare class requests_cookie in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 414
Segmentation fault_

This is the configuration of wp cli (wp --info)
_PHP binary:	php
PHP version:	5.3.3
php.ini used:	/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.25.0-alpha-229ae6c_

Any idea on how I can fix this? Thank you

**Comment by danielbachhuber** [comment]
Hi @scriptaimago,

Github issues aren't the appropriate venue for support questions. Please review: http://wp-cli.org/#support
