### ISSUE TITLE
wp core config - Update config

### ISSUE THREAD

**Issue by sourcerer-mike** [wp-cli/wp-cli#3365]
The command `wp core config` creates the wp-config.php file
and uses a wp-cli.yml if present.
Unfortunately the wp-config.php is generated completely new.
It would be great to just updater or override some parts.

---

Imagine something like this:

```
wp core config-update --dbname="foo"
```

The feature shall be that "everything" in the wp-config.php will stay as it is and only the given parts will be updated. This can be done by reusing the given constants, filling the template with the data of the constants and generate the wp-config again. It is still a new wp-config but by reusing the given parts it will look like an update.

The other way would be to really parse and replace parts of it.

Things from the "wp-cli.yml" should be taken too. So if the wp-config has no extra-php part but now it is defined in the wp-cli.yml, then wp cli updates the wp-config and adds the extra-php part.

Please add this feature.

**Comment by danielbachhuber** [comment]
Previously #2501

New feature development is happening as [community commands first](http://wp-cli.org/package-index/). This sounds like a good candidate for a community command.
