### ISSUE TITLE
Syntax error in "Common issues and their fixes" example

### ISSUE THREAD

**Issue by guillaumemolter** [wp-cli/wp-cli#3366]
The [example on how to fix](http://wp-cli.org/docs/common-issues/#php-notice-undefined-index-on-server-superglobal) the "PHP notice: Undefined index on $_SERVER superglobal" contains a syntax error.

```php
if ( defined( 'WP_CLI' ) && WP_CLI ) && ! isset( $_SERVER['HTTP_HOST'] ) {
    $_SERVER['HTTP_HOST'] = 'wp-cli.org';
}
```
There is an extra parenthesis after the second WP_CLI.

**Comment by ernilambar** [comment]
This should be fixed in other repo. https://github.com/wp-cli/wp-cli.github.com/blob/master/docs/common-issues/index.md
Wanna submit PR?

**Comment by guillaumemolter** [comment]
@ernilambar was working on it :-)
