### ISSUE TITLE
Running eval-file via cron

### ISSUE THREAD

**Issue by wujekbogdan** [wp-cli/wp-cli#3367]
Hi,

I've been trying to execute a PHP file using the `eval-file` command via Cron, but no matter I do the PHP file is not executed. 

This is the PHP file:
``` php
<?php
echo 'test';
```

At First I've simply added the following crontab entry:
``` bash
* * * * * cd /Users/my_username/htdocs/my_site/ && wp eval-file wp-content/plugins/my_plugin/cron-jobs/import.php >> /Users/my_username/log.txt
```

Then I've replaced `wp` with `/usr/local/bin/wp`:
``` bash
* * * * * cd /Users/my_username/htdocs/my_site/ && /usr/local/bin/wp eval-file wp-content/plugins/my_plugin/cron-jobs/import.php >> /Users/my_username/log.txt
```

Then I've added the `path` parameter:
``` bash
* * * * * cd /Users/my_username/htdocs/my_site/ && /usr/local/bin/wp --path=`/Users/my_username/htdocs/my_site/` eval-file wp-content/plugins/my_plugin/cron-jobs/import.php >> /Users/my_username/log.txt
```

I've even tired to save the script as a separate `.sh` file and execute this file from cron. The `script.sh` file is executable. I've run `chmod +x script.sh`

The cron entry:
``` bash
* * * * * cd /Users/my_username && ./script.sh
```

The `*.sh` file:
``` bash
#!/usr/bin/env bash
cd /Users/my_username/htdocs/my_site/ && /usr/local/bin/wp --path=`/Users/my_username/htdocs/my_site/` eval-file wp-content/plugins/my_plugin/cron-jobs/import.php >> /Users/my_username/log.txt
```

When I execute the same command from a command line it works fine. When I replace `/usr/local/bin/wp` with `/usr/local/bin/php` then the PHP file is executed properly as well. In both cases I can see entries being added to the ` /Users/my_username/log.txt` file. So it's definitely something related to the wp-cli.

Is there any way I can debug the issue? It would be great if wp-cli has an option to save logs.

PHP 7.0.9
WP-CLI 0.24.1
OSX 10.11.6

**Comment by danielbachhuber** [comment]
Hi @wujekbogdan,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support
