### ISSUE TITLE
wp scaffold post-type (and taxonomy) should not allow dashes

### ISSUE THREAD

**Issue by benoitchantre** [wp-cli/wp-cli#3368]
I have noticed that we can generate invalid code if the post-type or taxonomy name contains a dash.

It would be great to check for dashes and to replace them by underscores or to throw an error.

**Comment by danielbachhuber** [comment]
> I have noticed that we can generate invalid code if the post-type or taxonomy name contains a dash.

Can you share an example, please, with specific steps to reproduce?

We're already producing a `$machine_name` variable for function names, so I'm not sure what exactly you're referring to.

**Comment by benoitchantre** [comment]
You can run a command like `wp scaffold post-type my-post-type` and it will return

```
function my_post_type_init() {
	register_post_type( 'my-post-type', array(
		'labels'            => array(
			'name'                => __( 'My post types', 'YOUR-TEXTDOMAIN' ),
			'singular_name'       => __( 'My post type', 'YOUR-TEXTDOMAIN' ),
			'all_items'           => __( 'All My post types', 'YOUR-TEXTDOMAIN' ),
			'new_item'            => __( 'New my post type', 'YOUR-TEXTDOMAIN' ),
			'add_new'             => __( 'Add New', 'YOUR-TEXTDOMAIN' ),
...
```

I read again the Codex and Code Reference: dashes are allowed but there are some drawbacks :

> if the post type contains dashes you will not be able to add columns to the custom post type's admin page

I have noticed another drawbacks when using a filter of Polylang to set that the posts are translatable: it doesn't work when the post name has dashes.

I think it is better to avoid to register a post type with dashes, because you loose a lot of time to understand why some things don't work. Then you loose time again to make an upgrade process to update the entries in the database.

**Comment by danielbachhuber** [comment]
> I think it is better to avoid to register a post type with dashes, because you loose a lot of time to understand why some things don't work. Then you loose time again to make an upgrade process to update the entries in the database.

Ok. Given this isn't technically a problem with WP-CLI, we're not going to change the behavior.
