### ISSUE TITLE
Wordpress 4.6 Fatal error: Class 'WP_Post_Type' not found in ~/projects/my-project/wp-includes/post.php on line 1031

### ISSUE THREAD

**Issue by dylanfisher** [wp-cli/wp-cli#3370]
I just downloaded a fresh install of Wordpress 4.6 with `wp core download`.

Inside this directory, if I run `wp --help --debug` I get the error `Fatal error: Class 'WP_Post_Type' not found in ~/projects/my-project/wp-includes/post.php on line 1031`.

Perhaps related to the new WP_Term_Query and WP_Post_Type in Wordpress 4.6? https://wordpress.org/news/2016/08/pepper/

I can still run `wp --info` inside the WP directory. This looks like:

```
PHP binary:	/Applications/MAMP/bin/php/php5.6.10/bin/php
PHP version:	5.6.10
php.ini used:	/Applications/MAMP/bin/php/php5.6.10/conf/php.ini
WP-CLI root dir:	/usr/local/Cellar/wp-cli/0.19.2
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.19.2
```

and my .bash_profile has this line in it: 

`export WP_CLI_PHP=/Applications/MAMP/bin/php/php5.6.10/bin/php`

**Comment by danielbachhuber** [comment]
Please update to the latest version of WP-CLI: http://wp-cli.org/#updating
