### ISSUE TITLE
Cache WP.org checksums

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3375]
AFAIK WP.org core checksums do not change.

Could we cache it by `FileCache`?

**Comment by danielbachhuber** [comment]
> AFAIK WP.org core checksums do not change.

Right, but if they're on the filesystem, then they could be manipulated by nefarious code. It's better to leave them uncached, to ensure we're getting legit checksums each time.

**Comment by szepeviktor** [comment]
OK-OK.

As far I see, there is no hook to hijack the WP.org API HTTP requests :cry:
