### ISSUE TITLE
RFE: Negating parms like `wp --allow-root plugin list --status<>must-use`

### ISSUE THREAD

**Issue by cap5** [wp-cli/wp-cli#3376]
Hiya,

The main reason for this request is that I handle the output of the command `wp --allow-root plugin list --status<>must-use` automatically (as json with `--format=json`). To avoid issues further down the line (deriving from the must-use entries) I would like to filter out the `must-use`.

Testing this with our hosting management software avoids duplicates 'closest to the fire', therewith keeping our code down the line a lot cleaner :)

Some pointers:

- A syntax with the excamation mark`--status!=must-use` might look readable, however the `!` can conflict on the CLI because it has a function related to executing old commands.
- Pythonesque is very readable `is not` but I think very hard in terms of implementing 
along the regular parm handling
- the `<>` seems the easiest to inplement: `--status<>must-use`, allthough I must admit not to have looked the wp-cli internal code.

nb: I found a negation thingy on wp-cli-.org which was a `--no-*-` parm which pertains to the wrong kind of parm,`true/false` rather then a `where`.

If there's anything I can help you with let me know.

Regards,

Gerard.

**Comment by danielbachhuber** [comment]
Good suggestion, @cap5. I do like the `<>` syntax for this use case. However, I'm not sure how cleanly the concept will apply to the underlying code.

How do you think a negated argument should be passed through to PHP, and then handled by the command?
