### ISSUE TITLE
Linux | PHP 7.0 | WP CLI unable to find MySQL extension

### ISSUE THREAD

**Issue by cec** [wp-cli/wp-cli#3381]
Hi,

I'm trying to start using WP CLI on an existing WP installation.

I tried two installation methods: first the .phar package, then the .deb package, but in both cases, if I run

`wp search-replace 'old_domain' 'new_domain' --all-tables --debug`

the output I get is

````
Debug (bootstrap): No readable global config found (0.004s)
Debug (bootstrap): No project config found (0.004s)
Debug (bootstrap): No package autoload found to load. (0.023s)
Debug (bootstrap): ABSPATH defined: /home/cec/core/work/projects/ll/ (0.023s)
Debug (bootstrap): Begin WordPress load (0.023s)
Debug (bootstrap): wp-config.php path: /home/cec/core/work/projects/ll/wp-config.php (0.023s)
L'installazione PHP  non ha l'estensione MySQL che è necessaria per utilizzare WordPress
````

The last line, in italian, states that the PHP installation has no MySQL extension, which **is definitely not the case**.

The output of `wp --info --debug` is:

````
Debug (bootstrap): No readable global config found (0.008s)
Debug (bootstrap): No project config found (0.008s)
Debug (bootstrap): Running command: cli info (0.011s)
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.10-1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.24.0
````

PHP 7.0.10 is the only PHP installation on my system.
Apache on my system properly serves other php based websites that access the database

I'm also attaching the [php.ini](https://github.com/wp-cli/wp-cli/files/461903/php.ini.zip) used by WP CLI.

**Comment by danielbachhuber** [comment]
Hi @cec,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support
