### ISSUE TITLE
Latest build calls apply_filters before plugin.php is loaded

### ISSUE THREAD

**Issue by insprintorob** [wp-cli/wp-cli#3388]
Simple bug, plugin.php defines `apply_filters()` but `wp_debug_mode()` which is called by `Utils\wp_debug_mode()` calls `apply_filters()` before plugin.php is included. This happens when running any command e.g. `wp help` and subsequently crashes without output (output suppressed maybe?).

This affects the latest build: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar and seems to be fixed in the latest master branch.

php/wp-settings-cli.php
```
// Check if we're in WP_DEBUG mode.
Utils\wp_debug_mode(); //apply_filters called further down the stack see below

// Define WP_LANG_DIR if not set.
wp_set_lang_dir();

// Load early WordPress files.
require( ABSPATH . WPINC . '/compat.php' );
require( ABSPATH . WPINC . '/functions.php' );
require( ABSPATH . WPINC . '/class-wp.php' );
require( ABSPATH . WPINC . '/class-wp-error.php' );
require( ABSPATH . WPINC . '/plugin.php' );
require( ABSPATH . WPINC . '/pomo/mo.php' );`
```
php/utils-wp.php
```
function wp_debug_mode() {
	if ( \WP_CLI::get_config( 'debug' ) ) {
		.....
	} else {
		\wp_debug_mode(); //will call apply_filters
	}
.....
}
```

(wordpress core wp-includes/load.php)
```
function wp_debug_mode() {
	/**
	 * Filters whether to allow the debug mode check to occur.
	 *
	 * This filter runs before it can be used by plugins. It is designed for
	 * non-web run-times. Returning false causes the `WP_DEBUG` and related
	 * constants to not be checked and the default php values for errors
	 * will be used unless you take care to update them yourself.
	 *
	 * @since 4.6.0
	 *
	 * @param bool $enable_debug_mode Whether to enable debug mode checks to occur. Default true.
	 */
	if ( ! apply_filters( 'enable_wp_debug_mode_checks', true ) ){ //Crashes here silently, no output. Running function_exists('apply_filters') returns false because plugin.php is not included at this point
		return;
	}
```

**Comment by danielbachhuber** [comment]
Can you share `wp --info`, and the version of WordPress you're running against?

WP-CLI v0.24.1 calls `wp-settings.php`, not `wp-settings-cli.php` for WordPress 4.6 and higher. For older versions of WordPress, `wp-includes/plugin.php` is required early: https://github.com/wp-cli/wp-cli/blob/master/php/wp-settings-cli.php#L18

I'm not sure where you copied your example from.

**Comment by markparolisi** [comment]
I had this issue as well running WP v4.6 and WP-CLI v0.23.1
Updating CLI to v0.24.1 fixed it.

**Comment by insprintorob** [comment]
The example came from the v0.24 code, which came from the latest.phar download. I also updated to v0.24.1 through cloning this repo and setting it up, fixed the issue for me.

I'm running WordPress 4.6
