### ISSUE TITLE
wp-cli over ssh

### ISSUE THREAD

**Issue by isvaljek** [wp-cli/wp-cli#3391]
When I try to ssh to remotely manage an wordpress install, I get:
bash: wp: command not found
It seems to accept the ssh credentials, but this is the error I get.

Does wp-cli have to be installed on both ends, or is it enough to have it on my laptop/controller device?

**Comment by danielbachhuber** [comment]
> Does wp-cli have to be installed on both ends, or is it enough to have it on my laptop/controller device?

It needs to be installed on both ends.

**Comment by almai** [comment]
I installed wp-cli on client and server, but when I try following command...

`wp rest attachment list --ssh=xxxx --path=~/path/to/wp/installation`

...I get the afore mentioned error message:

`bash: wp: command not found`

**Comment by danielbachhuber** [comment]
Hi @almai,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by gitowiec** [comment]
I have the same problem.
I just installed wp-cli on my webfaction account (CentOS Linux release 7.3.1611 Core) and I have another wp-cli installation on my vbox vm(Ubuntu 16.0.4.2). I entered alias of webfaction account into `wp-cli.yml` configuration file. I know that ssh connection from vbox -> webfaction is ok, I did setup it with `ssh-copy-id` so there is no need to use password, public key does the authentication.
```
@staging:
  ssh: login@webXXX.webfaction.com/home/login/webapps/project_staging
```
Now I want to run `wp @staging core version` but I got error `bash: wp: command not found`.
If I do: `wp @staging core version --debug` I get
```
Debug (bootstrap): No readable global config found (0.018s)
Debug (bootstrap): Using project config: /workspace/strefatradera_proj/public_html/wp-cli.yml (0.019s)
Debug (bootstrap): No package autoload found to load. (0.108s)
Debug (bootstrap): Required file from config: /workspace/strefatradera_proj/public_html/config/wp-cli/quiet.php (0.108s)
Debug (bootstrap): SSH host: totumfacky@web566.webfaction.com (0.109s)
Debug (bootstrap): SSH port:  (0.109s)
Debug (bootstrap): SSH path: /home/totumfacky/webapps/strefatradera_staging (0.109s)
Debug (bootstrap): Running SSH command: ssh -q totumfacky@web566.webfaction.com -t cd /home/totumfacky/webapps/strefatradera_staging; wp 'core' 'version' '--debug' (0.109s)
**bash: wp: command not found**
```

Then I run by hand same command as in debug log's last but one line:
```
ssh -q totumfacky@web566.webfaction.com -t cd /home/totumfacky/webapps/strefatradera_staging; wp 'core' 'version' '--debug'
```
And my output is
```
Debug (bootstrap): No readable global config found (0.019s)
Debug (bootstrap): Using project config: /workspace/strefatradera_proj/public_html/wp-cli.yml (0.02s)
Debug (bootstrap): No package autoload found to load. (0.109s)
Debug (bootstrap): Required file from config: /workspace/strefatradera_proj/public_html/config/wp-cli/quiet.php (0.109s)
Debug (bootstrap): ABSPATH defined: /workspace/strefatradera_proj/public_html/ (0.11s)
Debug (bootstrap): Running command: core version (0.11s)
**4.7.3**
```
What am I doing wrong?
Sorry for reporting it here but I didn't find any help looking here http://wp-cli.org/#support

**Comment by gitowiec** [comment]
Ok, I found error, got to report is as new
