### ISSUE TITLE
Invalid json on option update

### ISSUE THREAD

**Issue by info2000** [wp-cli/wp-cli#3393]
I'm trying to update options from linux shell.
So this command 
`wp option update _cbc_yt_api_key '{"key":"keyvalue","valid":true}' --format=json --debug`
return this error:

> Error: Invalid JSON: {key:keyvalue,valid:true} 

I pass the json by a validator, and is ok
This is my info values
```
PHP binary:     /usr/bin/php7                                                                                                                 
PHP version:    7.0.10                                                                                                                        
php.ini used:   /etc/php7/php.ini                                                                                                             
WP-CLI root dir:        phar://wp-cli.phar                                                                                                    
WP-CLI packages dir:                                                                                                                          
WP-CLI global config:                                                                                                                         
WP-CLI project config:                                                                                                                        
WP-CLI version: 0.24.1  

```

How can solve it?
Thanks

**Comment by ernilambar** [comment]
`wp option update _cbc_yt_api_key '{"key":"keyvalue","valid":true}' --format=json --debug`

Output:
`Success: Updated '_cbc_yt_api_key' option.`

Its working as expected in my side.

**Comment by info2000** [comment]
but in my install, isn't working, and in other installs works

**Comment by danielbachhuber** [comment]
Hi @info2000,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support
