### ISSUE TITLE
wp-cli has issues when W3 Total Cache is enabled

### ISSUE THREAD

**Issue by tersmitten** [wp-cli/wp-cli#3395]
We have trouble pinpointing the exact problem but the Object Cache of W3TC seems to be problematic (when it is `enabled`).

Some commands the we have trouble with are `options` / `users`, but we suspect that there are more.

Is there any way to change `W3TC` settings before and after running `wp-cli` commands. [This] looks promising, but we don't know exactly how to get it to work. We also don't know if this should be part of `wp-cli` or not.

**Comment by tersmitten** [comment]
Some related issues:
* https://github.com/wp-cli/wp-cli/issues/2680
* https://github.com/wp-cli/wp-cli/issues?q=is%3Aissue+W3+Total+Cache+is%3Aclosed

**Comment by danielbachhuber** [comment]
Hi @tersmitten,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support
