### ISSUE TITLE
Wordfence caching may be capturing wp-cli command line output. 

### ISSUE THREAD

**Issue by rgoodie** [wp-cli/wp-cli#3396]
I turned on Wordfence Basic caching and immediately after ran a `wp pluign list` on the command line When I went to my site, I saw the text based web page just listing of output that matched the command I just executed. 

From `/var/www/html` I did a `grep -RIn ` which pointed me to `/var/www/html/wp-content/wfcache/~~~~_wfcache.html `. 

I did a cat and saw the output of my previous command:

```
$ cat \~~~~_wfcache.html 
+---------------------------------+----------------+--------+-----------+
| name                            | status         | update | version   |
+---------------------------------+----------------+--------+-----------+
| add-from-server                 | inactive       | none   | 3.3.2     |
| akismet                         | active-network | none   | 3.2       |
.
.
.
| wp-add-custom-css               | inactive       | none   | 1.0.0     |
| wp-google-analytics             | inactive       | none   | 1.4.1     |
+---------------------------------+----------------+--------+-----------+
```

I've since turned off caching since becoming aware of this. I've never run across this before because these files are saved under my user and not under `apache`.  An error log deatiled that apache could not access `/var/www/html/wp-content/wfcache/~~~~_wfcache.html `. Upon chancing that owner of that file to `apache`. The site then stopped working, only printout the contents of this file.

**Comment by danielbachhuber** [comment]
Hi @rgoodie,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support
