### ISSUE TITLE
Segmentation fault 4.6 and wp-cli 0.24.1

### ISSUE THREAD

**Issue by mantismamita** [wp-cli/wp-cli#3403]
Getting a Segmentation fault  with `wp core update-db --network` 
WP version 4.6.1 
wp-cli 0.24.1 

PHP 5.6.24-0+deb8u1

This is on a multisite using Multi- network https://wordpress.org/plugins/wp-multi-network/ 1.8.1

**Comment by danielbachhuber** [comment]
Is this a bug with WP-CLI, or the environment?

**Comment by mantismamita** [comment]
Works with former versions of wp-cli and WordPress on the same machine.

**Comment by danielbachhuber** [comment]
Can you provide steps to reproduce, please?

**Comment by mantismamita** [comment]
Sure,
In the root folder in a debian/jessie environment. 
typing `wp core update-db --network`
same problem with several other commands including `wp user list`

There don't seem to be any problems with other commands and no problems with debian/wheezy

```
PHP binary:     /usr/bin/php5
PHP version:    5.6.24-0+deb8u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    
WP-CLI global config:   
WP-CLI project config:  /var/www/dev.example.com/data/releases/20160914091523/www/wp-cli.yml
WP-CLI version: 0.24.1
```

I'm not sure what else would be useful but happy to provide any additional information.

**Comment by danielbachhuber** [comment]
Ok. I think this is a problem specific to your WordPress install, and not WP-CLI.

If you can identify the problem within WP-CLI, that's something we can get fixed. Otherwise, Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by mantismamita** [comment]
Ok thanks. Turned out to be a problem with space characters at the bottom of the wp-cli.yml file  in case anyone runs into this.
