### ISSUE TITLE
PHP Parse Error

### ISSUE THREAD

**Issue by janvanriswyck** [wp-cli/wp-cli#3409]
Hey Guys i have following issue,
When i Try to use a Code from a Plugin i use (superlist) where is a Plugin implemented that allows to import Data from Google places into an XML file i get this Error Message:

PHP Parse error:  syntax error, unexpected '?' in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 1

Anyone knows how to fix that? The Theme Author says its an Error insite the WP Cli syntax. What do you think?

That was what i am trying to achieve: http://inventorwp.com/documentation/developer-guide/google-places.html

**Comment by ernilambar** [comment]
Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
