### ISSUE TITLE
Notice: Undefined offset: 2 when running wp core check-update from major version

### ISSUE THREAD

**Issue by samlangdon** [wp-cli/wp-cli#3410]
When I run 'wp core check-update' on a major version of Wordpress (for example, version: 4.6), I receive the following:

Notice: Undefined offset: 2 in phar:///usr/local/bin/wp/php/utils.php on line 659

I don't get the same error if I run this on a minor version (for example, version 4.5.4)

Thanks,
Sam

**Comment by ernilambar** [comment]
Can you please post output of `wp --info`?

**Comment by danielbachhuber** [comment]
This is fixed by #3404
