### ISSUE TITLE
wp core multisite-install doesn't add --admin_user to site_admin

### ISSUE THREAD

**Issue by onnimonni** [wp-cli/wp-cli#3411]
I found out that when I created new site with `wp core multisite-install` it somehow sets empty string into `get_option('site_admins);'.

Because It saves empty string into that option also:
```
wp super-admin add admin
```
is broken.

`super-admin` subcommand should check if that's not array and add array over there.

*Versions:*
```
$ wp core version
4.6
$ wp cli version
WP-CLI 0.24.1
```

**Comment by Ipstenu** [comment]
I ran this:

`wp core multisite-install --url=http://local.wp-cli.dev --title="Just Another WP Site" --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email`

And while `$ wp option get site-admins` is empty, I got this:

```
$ wp super-admin add admin
Warning: User 'admin' already has super-admin capabilities.
No changes.
```

I added a second user (bobby) and ran this:

```
$ wp super-admin add bobby
Success: Granted super-admin capabilities.
```

Again, no output with `wp option get site_admins` but it totally worked.

And this would be because the site_admins is stored in wp_sitemeta and not wp_options :smh

**Comment by mmaton** [comment]
I've run into the same issue (I think!)

```[vagrant@localhost wordpress]$ wp core multisite-install --url='local.example.com' --title='Example Site' --admin_email='wp@example.com' --admin_name='admin' --admin_password='administrator123'
Warning: Unable to create directory wp-content/uploads/2017/09. Is its parent directory writable by the server?
Created single site database tables.
Set up multisite database tables.
Success: Network installed. Don't forget to set up rewrite rules.
[vagrant@localhost wordpress]$ wp core version
4.8
[vagrant@localhost wordpress]$ wp cli version
WP-CLI 1.3.0
[vagrant@localhost wordpress]$ ```

And we check the database:
```
[vagrant@localhost wordpress]$ mysql -uroot -e "select * from wordpress.wcp_sitemeta where meta_key = 'site_admins'"
+---------+---------+-------------+------------------------+
| meta_id | site_id | meta_key    | meta_value             |
+---------+---------+-------------+------------------------+
|       9 |       1 | site_admins |                        |
|      25 |       1 | site_admins | a:1:{i:0;s:5:"admin";} |
+---------+---------+-------------+------------------------+
[vagrant@localhost wordpress]$ 
```

![screen shot 2017-09-19 at 17 24 38](https://user-images.githubusercontent.com/982832/30603458-701681c6-9d5f-11e7-864b-272bd72d72b5.png)
