### ISSUE TITLE
Success message of `wp site create` can contain a wrong site URL

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#3415]
`wp site create` uses `wpmu_create_blog()` which has a `wpmu_new_blog` action. The action can be used to customize site details including the site URL.

I suggest to call `get_blog_details( $id )` before https://github.com/wp-cli/wp-cli/blob/v0.24.1/php/commands/site.php#L382 and use `$details->site_url` instead.

Any objections?

**Comment by danielbachhuber** [comment]
👍
