### ISSUE TITLE
It's not an issue, but idea for small addition - wp plugins update plugin1, plugin2, plugin3

### ISSUE THREAD

**Issue by rtofvnt** [wp-cli/wp-cli#3419]
Hi,
This wp-cli is one of the best things ever - fire, wheel, monotheism, pol dancing and WP-Cli - milestones for me in human evolution. 
I have a few wp run websites and quite a few plugins to update, however I can't update them all per site. Would that be possible to add an option as per subject:
wp plugin**s** update plugin1, plugin2, plugin3

Thanks

**Comment by ernilambar** [comment]
Multiple plugins can be updated like this `wp plugin update plugin1 plugin2`

**Comment by rtofvnt** [comment]
ok - I'll promise to read FULL manual next time.
Thanks

**Comment by ernilambar** [comment]
You can also try `wp plugin update --all`. This will update all plugins.

**Comment by rtofvnt** [comment]
Cheers -  as I was mentioned - I can't update all, that's why solution with comma separated is the best solution for me. 
Thanks
