### ISSUE TITLE
How I can create own private package

### ISSUE THREAD

**Issue by anhskohbo** [wp-cli/wp-cli#3423]
Hi everyone,

I don't want public my packages in to http://wp-cli.org/package-index/, any correct ways to do this?
I found the one way by now is going to: ~/.wp-cli/packages, run install package as Composer do.

**Comment by danielbachhuber** [comment]
Hi @anhskohbo,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

Here's one way you can share packages on a server: https://runcommand.io/to/shared-wp-cli-packages/

The installation process may be improved upon in the future, see #2565 and #2532
