### ISSUE TITLE
Ideas to mitigate slowness of URL replacement on import

### ISSUE THREAD

**Issue by realgeek** [wp-cli/wp-cli#3431]
I'm still in the process of importing 100,000+ posts via multiple WXRs in a directory. I've fixed one post type import slowdown with the addition of a new index created on the wp_posts table. There is one more significant DB slowdown which I'm trying to address when there are thousands of posts present.

After each batch of WXR items is imported, the import attempts to replace all occurrences of OldURL with NewURL. I would rather do this separately from the import in a search-replace operation (if the importer could save all the source->dest strings is a CSV, perhaps) or when the importer is finished with the entire directory of imports. This could actually be classified as a bug rather than a feature request, since the after-each-wxr-replacement will only replace strings on posts it's already imported, not on the posts which haven't been imported yet.

The other problem is that post_content is not indexable, so performing the search-replace is extremely time-consuming. In addition, in my particular import, I have a high degree of confidence that the only URLs which need to be replaced are contained within the posts which were just imported in that batch. In this case, if the MIN and MAX post IDs are stored on a per-WXR basis, then we can add a WHERE clause to the replacement query. This has the potential to turn this:

    mysql> update wp_posts set post_content = REPLACE(post_content,
    'http://sunj.nebuCHOLO0zezzar', 'foop');
    Query OK, 0 rows affected (13.10 sec)
    Rows matched: 314298  Changed: 0  Warnings: 0```

into this (note the difference in time):

    mysql> update wp_posts set post_content = REPLACE(post_content,
    'http://sunj.nebuCHOLO0zezzar', 'foop') where id > 50000 and id < 100000;
    Query OK, 0 rows affected (3.37 sec)
    Rows matched: 22941  Changed: 0  Warnings: 0

So my proposal is to have two options ( --opt_1 | --opt_2 ) for `import` (one of the options is required and negates the other). Opt_1 is the case where the MIN and MAX IDs are stored per-WXR and those are the only posts which get replacement, via the WHERE clause.

Opt_2 takes a file argument that stores the source->dest replacement strings for later processing. Or perhaps it could just store the mapping as a transient? Some form of storage is needed, in case the import is interrupted. The processing might use some kind of batch mechanism, so that it could be handled by cron tasks. Or it could be a separate `import` subcommand that takes the saved CSV file as an argument. 

Sorry for writing such a thick book of a post, but I genuinely would like to improve on wp-cli. Thanks.

**Comment by danielbachhuber** [comment]
> After each batch of WXR items is imported, the import attempts to replace all occurrences of OldURL with NewURL. I would rather do this separately from the import in a search-replace operation (if the importer could save all the source->dest strings is a CSV, perhaps) or when the importer is finished with the entire directory of imports.

Is this code within WP-CLI, or the WordPress Importer?

**Comment by realgeek** [comment]
Damnit. It's in backfill_attachment_urls() in wordpress-importer.php.

**Comment by danielbachhuber** [comment]
Ok. A better place for this enhancement is going to be https://github.com/humanmade/WordPress-Importer

The existing WordPress Importer is basically in LTS mode right now. It doesn't make sense to continue to monkey patch new things into it.
