### ISSUE TITLE
nginx SSL proxy -  HTTP_X_FORWARDED_PROTO error

### ISSUE THREAD

**Issue by gbcxjoe** [wp-cli/wp-cli#3432]
HI

we need at add this code to wp-config.php to handle nginx reverse proxy with ssl. 

if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
$_SERVER['HTTPS']='on';
if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
$_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}

error:
PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in phar:///wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 88

we are getting the following error.... is there any work around to have this code and have wp-cli work?

thanks

**Comment by danielbachhuber** [comment]
Hi @gbcxjoe,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
