### ISSUE TITLE
Some plugins are not activated as of `is_admin() == false`

### ISSUE THREAD

**Issue by garex** [wp-cli/wp-cli#3434]
Solution for all actions like plugin activateion/upgrade is to define `WP_ADMIN` during this.

This is ancient issue, that is not solved for a long time. And I'm dont' understand why. Currently there is ugly workaround like:

    echo "<?php define( 'WP_ADMIN', true );" > /tmp/enable-admin.php
    wp --require=/tmp/enable-admin.php plugin activate some-plugin

Previous issue #984 is locked. Ok.

So I'm asking once again: what prevents us from doing this? Does this against some "policy" in this tool?

**Comment by danielbachhuber** [comment]
> So I'm asking once again: what prevents us from doing this? Does this against some "policy" in this tool?

Did you read through #674 ? Defining `WP_ADMIN` generally for WP-CLI causes more problems than it solves.

**Comment by garex** [comment]
> Defining WP_ADMIN generally for WP-CLI causes more problems than it solves.

Nobody talks to define it globally.

It could be defined only for plugin activation/upgrade.

See original comment by @scribu  https://github.com/wp-cli/wp-cli/issues/984#issuecomment-33698510

Do you know any issues when defined `WP_ADMIN ` breaks something in WP CLI during plugin activation?
In WordPress it's defined because those operations are processed by admin and through wp-admin area.

**Comment by danielbachhuber** [comment]
> Do you know any issues when defined `WP_ADMIN` breaks something in WP CLI during plugin activation?

I don't, but it would bleed through to the remainder of the process.

Given the history of unexpected consequences with `WP_ADMIN=true`, I don't think it's worth the effort to conditionally define it in the case of `wp plugin activate`.

**Comment by garex** [comment]
>  I don't think it's worth the effort to conditionally define it in the case of wp plugin activate.

Then this tool becomes incompatible with it's purpose:

> You can update plugins, configure multisite installs and much more, without using a web browser.

You can't actually install/update plugins that depends on `is_admin()` internally. You to state that in README then and also provide ugly workaround with `--require=/tmp/enable-admin.php`  in docs for those who want to have trully compatible tool.
