### ISSUE TITLE
 --skip-themes and --skip-plugins are not working in the "db query" command.

### ISSUE THREAD

**Issue by wolfkang** [wp-cli/wp-cli#3435]
Hi,
I don't think  --skip-themes and --skip-plugins options work in the "db query" command.
My wp-cli version is 0.24.1.
Look at this file. [wp_cli.txt](https://github.com/wp-cli/wp-cli/files/502325/wp_cli.txt)
Thanks.

**Comment by ernilambar** [comment]
This seems to be a bug. I also can reproduce this.

**Comment by danielbachhuber** [comment]
Thanks for the report, @wolfkang 

> This seems to be a bug. I also can reproduce this.

I'm unable to reproduce this with the testcase in #3441.

`wp db query` runs before WP loads, so I'm not quite sure how WordFence would be loading. Can you share reproduction steps?

**Comment by ernilambar** [comment]
* Make some PHP fatal error in activated theme
* Try this command `wp db query "CHECK TABLE $(wp db tables | paste -s -d',');" --skip-themes`

**Comment by danielbachhuber** [comment]
Oh, it's user error.

Your use of `wp db tables` needs `--skip-themes` as well. It should be `wp db query "CHECK TABLE $(wp db tables --skip-themes | paste -s -d',');" --skip-themes`

`$()` is a native bash feature, not something that WP-CLI implements.
