### ISSUE TITLE
wp user list on multiple WP sites

### ISSUE THREAD

**Issue by alicengiz** [wp-cli/wp-cli#3437]
I have multiple WP sites (on vhosts) (various versions 4.4.x, 4.2.x, 3.7.x) on my server and I'm using wp-cli (0.24.1) like this:

/var/www/foo.com
/var/www/bar.com
/var/www/test.com

I want to take user list with wp-cli commands using script on my all WP sites.

$ cd /var/www/foo.com
$ wp user list >> userlist.xml
$ cd /var/www/bar.com
$ wp user list >> userlist.xml
$ cd /var/www/test.com
$ wp user list >> userlist.xml

But it returns wrong user list on other sites if ID's are the same with foo.com, foo.com users ok, but others same like foo.com users.

$ cd /var/www/foo.com
$ wp user list

+----+------------+--------------+----------------------------+---------------------+---------------+
| ID | user_login | display_name | user_email                 | user_registered     | roles         |
+----+------------+--------------+----------------------------+---------------------+---------------+
| 1  | admin      | admin        | admin@test.com             | 2007-12-19 16:26:09 | administrator |
| 2  | test       | testy        | testy@test.com             | 2007-12-19 16:27:31 | administrator |
+----+------------+--------------+----------------------------+---------------------+---------------+

$ cd /var/www/bar.com
$ wp user list

+----+------------+--------------+----------------------------+---------------------+---------------+
| ID | user_login | display_name | user_email                 | user_registered     | roles         |
+----+------------+--------------+----------------------------+---------------------+---------------+
| 1  | admin      | admin        | admin@test.com             | 2007-12-19 16:26:09 | administrator |
| 2  | test       | testy        | testy@test.com             | 2007-12-19 16:27:31 | administrator |
| 3  | another    | another      | another@test.com           | 2015-01-20 11:54:41 | administrator |
+----+------------+--------------+----------------------------+---------------------+---------------+

I inserted garbage collection commands and wp cache flush commands after wp user list command on my script, but it didn't work.

# garbage collection
echo "<?php unset($instance_var); ?>" | php

# wp cache flush
wp cache flush

How can I fix this issue?

**Comment by danielbachhuber** [comment]
Hi @alicengiz,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
