### ISSUE TITLE
Language Updates - How to Specify more Locales?

### ISSUE THREAD

**Issue by hakre** [wp-cli/wp-cli#3446]
I'm seeing a small discrepancy between running lanugage updates on the command-line with *wp-cli* and using the updater in the *wordpress admin*.

I think this is related b/c wp-cli only sees one language (english) while in-fact I have some more activated in the backend (via the *Polylang* plugin), so these are not taken into account.

Would be great to provide a list of languages for which language updates are done.

**Comment by hakre** [comment]
The discrepancy in detail:

The wp-cli interface reports:

	$ wp core language update 
	Success: Translations updates are not needed for the 'English (US)' locale.

While in the *wordpress admin* there is

> Translations \n  New translations are available.

reported, and updates are actually available and then done:

> Updating translations for Twenty Fifteen (&lt;ISO-LANG-CODE>)…

> Updating translations for Twenty Ten (&lt;ISO-LANG-CODE>)…

So just technically a

    $ wp core language update -- [ISO-LANG-CODE...]

would be working in my case.

Alternatively if it would work out of the box with *Polylang* would be extremely comfortable but I'm more for a general  solution than specific to a plugin and I can't say the exact cause of the flaw, so *Polylong* is just what I assume.

**Comment by danielbachhuber** [comment]
Is this a bug? If so, what are the steps to reproduce?

**Comment by hakre** [comment]
Sorry, I thought it was clear from my report. It could qualify as a bug, however, more clarity for me would be if I can specificy the ISO-code with the `core language update` command sequence.

It can be reproduced by installing more than the default language.
