### ISSUE TITLE
New `wp option list` parameter to exclude transients

### ISSUE THREAD

**Issue by borekb** [wp-cli/wp-cli#3448]
Including transients in the output of `wp option list` can be problematic, see https://github.com/wp-cli/wp-cli/issues/3447. The could be a parameter to exclude them (that I would personally use as a default), like:

```
wp option list --no-transients
```

**Comment by ernilambar** [comment]
Transients are just a small part of options table. There is currently `--search` where it add `LIKE` in the query. May be we could add other parameter which would use `NOT LIKE`. It would be good enhancement to the command I believe.  Just my 0.02 dollar :)

**Comment by borekb** [comment]
Given that there is a command for transients, `wp vp transient`, one could even argue that transients should not be outputted by the `option` command at all. But I understand that it would be controversial and also a breaking change.

**Comment by danielbachhuber** [comment]
I'd be amenable to adding a `--transients` flag which filters to all transients and supports the inverse, `--no-transients`, for excluding transients.

**Comment by ernilambar** [comment]
Personally I am opposite to adding such specific filter parameter. I believe, in core, we should be adding base achieve such feature. So that user can easily achieve other filter parameters like `--widgets/--no-widgets` or `--theme-mods/--no-theme-mods` or similar.

**Comment by danielbachhuber** [comment]
> Personally I am opposite to adding such specific filter parameter. I believe, in core, we should be adding base achieve such feature.

We can add a negate search too if you'd like. That transients (a caching mechanism) are stored in the options table is a bit of a WordPress-ism. I think wanting to filter them out is a totally valid use case.
