### ISSUE TITLE
PHP Notice:  Constant WP_DEBUG already defined in

### ISSUE THREAD

**Issue by highacid** [wp-cli/wp-cli#3454]
```
[root@www html]# wp user list --field=ID --role=customer | xargs wp user delete --yes
PHP Notice:  Constant WP_DEBUG already defined in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 139
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
PHP Notice:  Constant WP_DEBUG already defined in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 139
<!DOCTYPE html>
<!--[if lte IE 9 ]><html class="ie lt-ie9" lang="en-US"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en-US"> <!--<![endif]-->
```

**Comment by danielbachhuber** [comment]
Hi @highacid,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by rilwis** [comment]
Hi @danielbachhuber ,

I think it's a bug rather than a support question. After 4 years, I still get the same PHP notice in the console.

**Comment by schlessera** [comment]
@rilwis, This is not a bug in WP-CLI, this is code in your environment that tries to redefine a constant that is already defined. You should check your site to verify where it is setting the `WP_DEBUG` constant and adapt the code to not break.

**Comment by rilwis** [comment]
@schlessera That's weird, because I have only `WP_DEBUG` defined in `wp-config.php`. Is that the problem?

**Comment by schlessera** [comment]
No, that's fine, WP-CLI will account for that. However, that could mean that you have a non-standard bootstrapping sequence for your WordPress site that happens to trigger the `wp-config.php` file twice.

As initially stated, GitHub is not the right place for support. Join the #cli channel on the Make WordPress Slack if you want to discuss this further.

**Comment by lowv-developer** [comment]
@schlessera Yep! that is the case.. thnx
