### ISSUE TITLE
Segmentation Fault PHP 7.0

### ISSUE THREAD

**Issue by danielpataki** [wp-cli/wp-cli#3462]
I'm testing some of our products locally using Rasmus Lerforf's [php7dev](https://github.com/rlerdorf/php7dev) Vagrant box. If I switch it to PHP5.6 (`newphp 56`) everything works as expected. If I use the default 7.1.0-dev or 7.1.0-dev I get segmentation faults for many commands.

`wp core install` will give me segmentation error, but more interestingly: `wp core is-installed` gives me nothing but the segmentation error. 

Let me know if you need any more information to reproduce this issue.

**Comment by danielbachhuber** [comment]
> Let me know if you need any more information to reproduce this issue.

Does WordPress itself work as expected in PHP 7.1.0-dev?

Can you share the output of `/var/logs/syslog` when one of these segmentation error occurs?

**Comment by danielpataki** [comment]
Hi @danielbachhuber,

Yes, it seems to work fine. I haven't done any proper testing on 7.1.0 but I did click around the admin, add some posts and whatnot - no issues so far. 

Some more info: when I use `sudo wp core is-installed --allow-root` I do not get the segmentation fault, but I also don't get any output at all. 

I checked a bunch of logs:
* `/var/log/syslog/`
* '/var/log/nginx/default-error.log'
* '/var/log/nginx/error.log'
* '/var/log/nginx/php-fpm_error.log'

My Nginx error log is set to the `error.log` file in there and I modified the reporting level to debug, still nothing. I know a little bit about error logs and I find my way around the terminal and servers but I'm no sysadmin, sorry if I'm not of huge help here.

**Comment by danielpataki** [comment]
Also, I thought I'd mention that I **have** used WP-CLI heavily on PHP Version 7.0.11-1 before without issues so this might be a problem with the Vagrant box. I suspect that if this was a widespread issue on 7.x there would be a lot more issues about this :)

**Comment by danielbachhuber** [comment]
> Some more info: when I use `sudo wp core is-installed --allow-root` I do not get the segmentation fault, but I also don't get any output at all.

This is the expected behavior of `wp core is-installed`. It uses exit codes to inform you whether or not core is installed.

> Also, I thought I'd mention that I have used WP-CLI heavily on PHP Version 7.0.11-1 before without issues so this might be a problem with the Vagrant box.

Yes, it does seem like it's environmental at this point.
