### ISSUE TITLE
Better error reporting for user update

### ISSUE THREAD

**Issue by gmcinnes** [wp-cli/wp-cli#3464]
It's easy to screw up the field names when doing `wp user update`.  For example, I just got caught by doing `wp user update --user_pass=password` instead of `wp user update --user-pass=password`  (Underscore vs hyphen).

The thing is, if you screw up the field name, there's no useful output from wp-cli.  Instead, you get the misleading `Success: Updated user 30` when nothing has actually been updated.

Perhaps you'd consider outputing some diagnostics if there's a field name passed that doesn't have a match as a column in the db table.

**Comment by danielbachhuber** [comment]
We can't really change the behavior now without causing a breaking change.

`wp user update` passes its arguments through to `wp_update_user()`, which technically could accept an argument of `user-pass`.

If you use RESTful WP-CLI, this process will exhibit more strict behavior https://github.com/wp-cli/restful
