### ISSUE TITLE
Trying to update from 0.20 to 0.24 self-destructed wp-cli

### ISSUE THREAD

**Issue by slikts** [wp-cli/wp-cli#3465]
This should say it all:

    $ wp cli update
    Warning: The `wp cli update` command has an invalid synopsis part: [--patch]
    Warning: The `wp cli update` command has an invalid synopsis part: [--minor]
    Warning: The `wp cli update` command has an invalid synopsis part: [--nightly]
    Warning: The `wp cli update` command has an invalid synopsis part: [--yes]
    You have version 0.20.0. Would you like to update to 0.24.1? [y/n] y
    Downloading from https://github.com/wp-cli/wp-cli/releases/download/v0.24.1/wp-cli-0.24.1.phar...
    New version works. Proceeding to replace.
    Success: Updated WP-CLI to 0.24.1
    $ wp core update
    /home/slikts/.local/bin/wp: line 1: syntax error near unexpected token `newline'
    /home/slikts/.local/bin/wp: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
    $ cat ~/.local/bin/wp
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message> ...

**Comment by danielbachhuber** [comment]
This issue was fixed in v0.23.0: #2483
