### ISSUE TITLE
core download --version=latest can install an old version

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#3466]
![image](https://cloud.githubusercontent.com/assets/1621608/19322201/2b3e11f2-90c9-11e6-9dcf-9ae3191dab21.png)

Obviously this is because the cache is using a key which is not tied to a specific version.

Omitting the `--version=` works as expected.  Using `--version=latest` should be the same behavior as omitting it, no?

I would assume using `nightly` would probably not produce the same result as I'm guessing that probably isn't even cached, or the lifetime is much less.

**Comment by danielbachhuber** [comment]
> Using `--version=latest` should be the same behavior as omitting it, no?

Yes, I think we should make sure the cache key always represents the version.
