### ISSUE TITLE
media regenerate Command - Website Documentation Improvements

### ISSUE THREAD

**Issue by richardbuff** [wp-cli/wp-cli#3469]
1) On this page http://wp-cli.org/commands/media/regenerate/ you might want to include an example of passing multiple IDs.  Like:

` $ wp media regenerate 1 2 3 4 5 `

I'll bet there's a lot of people that try separating them with a comma or otherwise trying to group the IDs. 

2) Also, maybe include an example of using 'wp media regenerate' without the --yes flag so that it shows the confirmation message?  I remember the first time I used the regenerate command, I gave it an ID, and there is no confirmation message when you give it arguments, so I was looking at the docs and thinking 'what confirmation message? Did I do something wrong?  What was I supposed to be confirming?'   Maybe the answer to that would be putting in the --yes flag explanation that the confirmation message only shows if you pass no args?

**Comment by danielbachhuber** [comment]
👍
