### ISSUE TITLE
Media regeneration doesn't work with multisites

### ISSUE THREAD

**Issue by yratof** [wp-cli/wp-cli#3473]
Working with a multisite, the structure of the uploads folder in wp-content is 

`wp-content/uploads/sites/*site_number*/*date* like this:

![image](https://cloud.githubusercontent.com/assets/1001935/19434295/e0b20752-9464-11e6-8745-d9ac47f2f562.png)

However, when using media regen, it only finds the images in `2016` in `upload` and ignores the other 5000 images in the multisite install.

Can we define where this should be point at to regen?

**Comment by danielbachhuber** [comment]
> Can we define where this should be point at to regen?

`wp media regenerate` only applies to an individual site on the WordPress multisite instance.

To designate which site you'd like to run `wp media regenerate` against, you can use the `--url=<url>` param.

**Comment by yratof** [comment]
Fantastic, running `wp media regenerate -url='http://demo.dev/deepthought` worked exactly how it should. Only 5000 images remaining!

**Comment by stillatmylinux** [comment]
Actually it's --url= 

`wp media regenerate --url='http://demo.dev/deepthought`
