### ISSUE TITLE
Examples needs to be updated for media regenerate

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/wp-cli#3475]
After https://github.com/wp-cli/wp-cli/pull/3407 examples needs to be updated for `wp media regenerate`.

**Comment by danielbachhuber** [comment]
> Examples needs to be updated for media regenerate

Examples are regenerated on every release. We haven't released v0.25.0 yet

**Comment by ernilambar** [comment]
I meant here. https://github.com/wp-cli/wp-cli/blob/master/php/commands/media.php#L11
We have added progress indicator before each message.

**Comment by danielbachhuber** [comment]
> We have added progress indicator before each message.

Ah, sorry, I misunderstood.

**Comment by ernilambar** [comment]
Its missing in some places. I will prepare PR by next few days.
