### ISSUE TITLE
term create and no record in wp_term_taxonomy

### ISSUE THREAD

**Issue by GitHub-Mike** [wp-cli/wp-cli#3476]
I use XAMPP with Windows 7 and have a problem with wp term create.

`wp term create category "Cat One" --slug=cat_one --description="Description for cat one"`

Create a new record in wp_terms but not in wp_term_taxonomy.

Is it a problem with windows and wp-cli?

**Comment by danielbachhuber** [comment]
Does the problem reproduce in a fresh WordPress install?

**Comment by GitHub-Mike** [comment]
Yes, with:

- wp core download --locale=de_DE
- wp core config ...
- wp core install ...
- wp plugin install woocommerce --activate

2016-10-17 18:21 GMT+02:00 Daniel Bachhuber <notifications@github.com>:

**Comment by danielbachhuber** [comment]
Does it reproduce without WooCommerce activated?

**Comment by GitHub-Mike** [comment]
No problem with new wordpress installation and new database, without
plugins.

WordPress version: 4.6.1
Database revision: 37965
TinyMCE version:   4.401 (4401-20160726)

2016-10-17 18:49 GMT+02:00 Daniel Bachhuber <notifications@github.com>:

**Comment by danielbachhuber** [comment]
> No problem with new wordpress installation and new database, without
> plugins.

Ok. The problem lies with one of your plugins then, not WP-CLI.

**Comment by GitHub-Mike** [comment]
No,

I installed woocommerce plugin only. No other plugins!

WP CLI supports woocommerce commands.

2016-10-17 19:33 GMT+02:00 Daniel Bachhuber <notifications@github.com>:
