### ISSUE TITLE
site list hangs on deleted/redirected site. 

### ISSUE THREAD

**Issue by tommcgee57** [wp-cli/wp-cli#3478]
I'm attempting to get a list of sites that have a specific plugin activated: 

`wp site list --field=url | xargs -t -n1 -I % wp plugin list --status=active --name=shutter-reloaded --url=% --skip-themes --user=some_admin
`

It hums along as expected, throwing a few warnings on sites that are domain-mapped. The '-t' flag shows the command and the warning:

`wp plugin list --status=active --name=shutter-reloaded --url=http://epirate.shu.edu/ --skip-themes --user=some_admin
Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(http://blogs.shu.edu/technology/category/epirate-3/)
`

Nevertheless it goes right on to the next. 

But I have one site using an external domain was moved off of our multisite installation altogether and then deleted.   Again the '-t' flag so we can see what the command is: 

`wp plugin list --status=active --name=shutter-reloaded --url=http://www.stillmanexchange.com/ --skip-themes --user=some_admin
`
At this point, it freezes.  Adding --debug gives these messages:

(output)
Debug (bootstrap): No readable global config found (0.008s)
Debug (bootstrap): Using project config: /var/www/html/wp-cli.yml (0.009s)
Debug (bootstrap): No package autoload found to load. (0.131s)
Debug (bootstrap): ABSPATH defined: /var/www/html/ (0.131s)
Debug (bootstrap): Set URL: http://www.stillmanexchange.com/ (0.131s)
Debug (bootstrap): Begin WordPress load (0.131s)
Debug (bootstrap): wp-config.php path: /var/www/wp-config.php (0.132s)
PHP Notice:  Use of undefined constant widget_recent_global_comments - assumed 'widget_recent_global_comments' in /var/www/html/wp-content/plugins/recent-global-comments-widget/recent-global-comments-widget.php on line 145
Notice: Use of undefined constant widget_recent_global_comments - assumed 'widget_recent_global_comments' in /var/www/html/wp-content/plugins/recent-global-comments-widget/recent-global-comments-widget.php on line 145

But they're identical to the messages for all the commands that actually did work, and it again freezes at this point. 

A way to skip over archived/deleted sites would be helpful here.

**Comment by danielbachhuber** [comment]
> A way to skip over archived/deleted sites would be helpful here.

Why not just list sites that are active?

**Comment by tommcgee57** [comment]
Ah, thanks. Adding --archived=0 to the site list command worked.
