### ISSUE TITLE
Error message when using specific user account - works fine w/ root

### ISSUE THREAD

**Issue by bph** [wp-cli/wp-cli#3480]
User aauw-ca generates error message 
Error: This does not seem to be a WordPress install 

The wp cli command is executed just fine when using it at root. 

What's wrong with my set-up? 

here is the full session: 
> root@joyweed:/home/aauw-ca/public_html# sudo -u aauw-ca -i -- wp cli check-update
> Success: WP-CLI is at the latest version.
> root@joyweed:/home/aauw-ca/public_html# sudo -u aauw-ca -i -- wp plugin update --all
> Error: This does not seem to be a WordPress install.
> Pass --path=`path/to/wordpress` or run `wp core download`.
> root@joyweed:/home/aauw-ca/public_html# sudo -u aauw-ca -i -- wp plugin update --all --debug
> Debug (bootstrap): No readable global config found (0.012s)
> Debug (bootstrap): No project config found (0.013s)
> Debug (bootstrap): No package autoload found to load. (0.074s)
> Debug (bootstrap): ABSPATH defined: / (0.074s)
> Error: This does not seem to be a WordPress install.
> Pass --path=`path/to/wordpress` or run `wp core download`.
> root@joyweed:/home/aauw-ca/public_html# wp plugin update --all --debug --allow-root
> Debug (bootstrap): No readable global config found (0.013s)
> Debug (bootstrap): No project config found (0.014s)
> Debug (bootstrap): No package autoload found to load. (0.074s)
> Debug (bootstrap): ABSPATH defined: /home/aauw-ca/public_html/ (0.074s)
> Debug (bootstrap): Begin WordPress load (0.074s)
> Debug (bootstrap): wp-config.php path: /home/aauw-ca/public_html/wp-config.php (0.075s)
> Debug (bootstrap): Loaded WordPress (0.725s)
> Debug (bootstrap): Running command: plugin update (0.725s)
> Success: Updated 0/0 plugins.
> root@joyweed:/home/aauw-ca/public_html#

**Comment by danielbachhuber** [comment]
Hi @bph,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
