### ISSUE TITLE
Update localized versions of wp-cli.org for v0.25.0

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3486]
Each localized version of the wp-cli.org homepage should be updated based on the current English version:

* [x] Japanese
* [x] Français
* [x] Português (Brasil)
* [x] Türkçe
* [x] Deutsch
* [x] नेपाली
* [x] ελληνικά
* [x] Italiano

**Comment by danielbachhuber** [comment]
@wp-cli/translators Could you take on ^ sometime before midday Tuesday Pacific time please?

**Comment by kouratoras** [comment]
I created [pull request](https://github.com/wp-cli/wp-cli.github.com/pull/228) for Greek translation.

**Comment by mustafauysal** [comment]
[PR](https://github.com/wp-cli/wp-cli.github.com/pull/229) ready for Turkish

**Comment by shulard** [comment]
I'll make the french update on monday...

**Comment by ernilambar** [comment]
नेपाली translation -  https://github.com/wp-cli/wp-cli.github.com/pull/231

**Comment by swissspidy** [comment]
[Pull Request](https://github.com/wp-cli/wp-cli.github.com/pull/232) for the German translation created. I found it difficult to know what changed without going through the whole file again.

**Comment by taianunes** [comment]
[PR](https://github.com/wp-cli/wp-cli.github.com/pull/235) is ready for Brazilian portuguese translation!

**Comment by shulard** [comment]
PR for french made too: wp-cli/wp-cli.github.com#237

Just a question, we are talking about 0.25.0 version but in the `index.md` it's still 0.24.1 which is mentioned. Is there an automatic process to update version in files ?

**Comment by danielbachhuber** [comment]
> Just a question, we are talking about 0.25.0 version but in the `index.md` it's still 0.24.1 which is mentioned. Is there an automatic process to update version in files ?

There isn't at the moment. I'll make sure to handle that in https://github.com/wp-cli/wp-cli/issues/3487

We could maybe make it scriptable as a part of https://github.com/wp-cli/wp-cli/issues/2768

**Comment by miya0001** [comment]
I finished Japanese translation.

Anyway, can you tag like `v0.24.1` on `wp-cli.github.com` repository too when new version is released.
We can know the diff with like following url.

https://github.com/wp-cli/wp-cli.github.com/compare/v0.24.1...master

I am thinking that I write the tag into commit message when I translate it, so I can track where should I translate.

Thanks!

**Comment by danielbachhuber** [comment]
> Anyway, can you tag like v0.24.1 on wp-cli.github.com repository too when new version is released.

Yes, I will do that going forward.
