### ISSUE TITLE
v0.25.0 release checklist

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3487]
In addition to the [standard release checklist](http://wp-cli.org/docs/release-checklist/), these are the additional steps we need to perform for releasing v0.25.0, shortly prior to the release:

* [x] Prepare a list of WP-CLI packages that have been published or updated since the last release, to be included in the release notes.
* [x] Change `0.24.1` to `0.25.0` on the homepages. See https://github.com/wp-cli/wp-cli/issues/3486#issuecomment-255713052

**Comment by ernilambar** [comment]
Ok sure. I will list those down.

**Comment by ernilambar** [comment]
This is the list of new packages added since July 27. https://gist.github.com/ernilambar/e2abfa37eef2e732e171c20fdebd977b

**Comment by danielbachhuber** [comment]
Thanks @ernilambar

**Comment by danielbachhuber** [comment]
🚢
