### ISSUE TITLE
CLI tool very slow on all commands

### ISSUE THREAD

**Issue by afail** [wp-cli/wp-cli#3495]
We are using the CLI tool with Bedrock and the tool seems to be very slow loading Wordpress. Any advice on what we can do to troubleshoot this?

./wp-cli.phar plugin activate wordfence --allow-root --debug

Debug (bootstrap): No readable global config found (0.11s)
Debug (bootstrap): Using project config: /data/sites/wp_cpamobility/wp-cli.yml (0.115s)
Debug (bootstrap): No package autoload found to load. (0.508s)
Debug (bootstrap): ABSPATH defined: /data/sites/wp_cpamobility/web/wp/ (0.512s)
Debug (bootstrap): Begin WordPress load (0.534s)
Debug (bootstrap): wp-config.php path: /data/sites/wp_cpamobility/web/wp-config.php (0.539s)
Debug (bootstrap): Loaded WordPress (129.59s)
Debug (bootstrap): Running command: plugin activate (129.595s)
Warning: Plugin 'wordfence' is already active.

**Comment by danielbachhuber** [comment]
Hi @afail,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
