### ISSUE TITLE
core check-update: Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by moses-moore-spafax** [wp-cli/wp-cli#3502]
I don't remember seeing this warning message before updating wp-cli to v0.25.0

    # sudo -u mach -- php-cli /usr/local/bin/wp-cli core check-update
    Warning: Invalid argument supplied for foreach() in phar:///usr/local/bin/wp-cli/php/commands/core.php on line 1389
    Success: WordPress is at the latest version.

Steps to reproduce: see above.
Expected: no "Warning:" message.
Witnessed: warning about invalid arguments
Environment:

    # sudo -u mach -- php-cli /usr/local/bin/wp-cli --info
    PHP binary:	/usr/local/bin/php
    PHP version:	5.6.27
    php.ini used:	/usr/local/lib/php.ini
    WP-CLI root dir:	phar://wp-cli.phar
    WP-CLI packages dir:	
    WP-CLI global config:	
    WP-CLI project config:	
    WP-CLI version:	0.25.0
    # sudo -u mach php-cli /usr/local/bin/wp-cli core version
    4.6.1

More info: looking in commands/core.php:1389 I can see `foreach ( $from_api->updates as $offer )` and before that `$from_api = get_site_transient( 'update_core' );`

    # sudo -u mach php-cli /usr/local/bin/wp-cli transient type
    Transients are saved to the wp_options table.
    # sudo -u mach php-cli /usr/local/bin/wp-cli transient get update_core
    Warning: Transient with key "update_core" is not set.

**Comment by danielbachhuber** [comment]
The existing logic is:

```
wp_version_check();
$from_api = get_site_transient( 'update_core' );
if ( ! $from_api ) {
	return array();
}

$compare_version = str_replace( '-src', '', $GLOBALS['wp_version'] );

$updates = array(
	'major'      => false,
	'minor'      => false,
	);
foreach ( $from_api->updates as $offer ) {
```

I suppose we could check for `if ( empty( $from_api->updates ) )` instead.

Any ideas how you ended up with a truthy but non-object value in the `update_core` transient?

**Comment by danielbachhuber** [comment]
> I don't remember seeing this warning message before updating wp-cli to v0.25.0

Which WP-CLI version were you running previously?

**Comment by moses-moore-spafax** [comment]
v0.24.1
I just downgraded, re-ran the command and got the same warning.  I must be misremembering.

**Comment by moses-moore-spafax** [comment]
Edited the last comment for markdown typos and a dumb update_core/core_update mistake.

**Comment by moses-moore-spafax** [comment]
I just copied the site & db over to another staging machine where I have four other wordpress sites, and php 5.5.9.  Updated wp-cli and I still get the "foreach()" warning with the mach site, but not the other four sites.  The mach site functions well, nothing broken as a website. and `wp core update` reports "Success: WordPress is up to date." with no warnings.  This is bizarre, and I'm thinking the mach site is a fluke.  Is there a way to reset transients, or force wordpress to wipe and remake the update_core transient?

**Comment by danielbachhuber** [comment]
> Is there a way to reset transients, or force wordpress to wipe and remake the update_core transient?

`wp transient delete --all`.

> force wordpress to wipe and remake the update_core transient?

`wp core check-update` does this when it runs actually.

**Comment by moses-moore-spafax** [comment]
weird.

    # sudo -u mach php-cli /usr/local/bin/wp-cli transient delete --all
    Success: 25 transients deleted from the database.
    # sudo -u mach php-cli /usr/local/bin/wp-cli core check-update
    Warning: Invalid argument supplied for foreach() in phar:///usr/local/bin/wp-cli/php/commands/core.php on line 1389
    Success: WordPress is at the latest version.

same on the staging server clone, 'cept I can use `php` directly instead of `php-cli` first.

**Comment by danielbachhuber** [comment]
Ok. I think this problem is specific to your environment — something (plugin or similar) must be clobbering the data somehow.
