### ISSUE TITLE
PHP Notice:  Undefined variable: table_prefix in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(952) : eval()'d code on line 29

### ISSUE THREAD

**Issue by keerthankoundinya** [wp-cli/wp-cli#3506]
I am having an issue opening my wordpress admin dashboard. Not sure where the issue is, but my wordpress login page just does not load.

I tried the following commands.

balgam@nginx1:~/alltop9.com/public$ wp plugin list
PHP Notice:  Undefined variable: table_prefix in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(952) : eval()'d code on line 29
+----------------------------+----------+--------+----------+

balgam@nginx1:~/alltop9.com/public$ wp --debug

Debug (bootstrap): No readable global config found (0.019s)
Debug (bootstrap): No project config found (0.02s)
Debug (bootstrap): No package autoload found to load. (0.374s)
Debug (bootstrap): ABSPATH defined: /home/balgam/alltop9.com/public/ (0.374s)
Debug (bootstrap): Begin WordPress load (0.375s)
Debug (bootstrap): wp-config.php path: /home/balgam/alltop9.com/public/wp-config.php (0.375s)
PHP Notice:  Undefined variable: table_prefix in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(952) : eval()'d code on line 29
Debug (bootstrap): Loaded WordPress (0.637s)
Debug (bootstrap): Running command: help (0.637s)

Kindly help me identify where the error is.

**Comment by danielbachhuber** [comment]
Hi @keerthankoundinya,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
