### ISSUE TITLE
Running WP-CLI Commands From Composer

### ISSUE THREAD

**Issue by JakeHenshall** [wp-cli/wp-cli#3511]
Hi,

Is there any way that I can do this.

I'm trying to run either any WP-CLI command from within the "post-install-cmd" inside composer and/or create a script.sh with the commands in and run them aswell, to allow the user to have a clean fresh version of WordPress installed.

Thanks Jake.

**Comment by danielbachhuber** [comment]
Hi @JakeHenshall,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
