### ISSUE TITLE
HTML output on import of xml file

### ISSUE THREAD

**Issue by chrismccoy** [wp-cli/wp-cli#3516]
I noticed the CLI import command spits out HTML which is not needed via cmd line.

    <p>All done. <a href="http://domain.como/wp-admin/">Have fun!</a></p><p>Remember to update the passwords and roles of imported users.</p>

**Comment by danielbachhuber** [comment]
This is unfortunate, but expected, behavior. `wp import` wraps the WordPress importer, which renders its messages in HTML. If you look closely, you'll notice other output includes HTML too.
