### ISSUE TITLE
Magic Method Names -- Not recommended by PHP

### ISSUE THREAD

**Issue by amiga-500** [wp-cli/wp-cli#3521]
PHP says:

> _PHP reserves all function names starting with __ as magical. It is recommended that you do not use function names with __ in PHP unless you want some documented magic functionality._ 

WP-CLI allows for magic method naming convention to hide methods you dont want to appear as commands.  The problem is for PHP validation tester tools this will fail all the tests.  Sure, keep the feature in but is it possible you guys could hadd another way to also provide this hide function feature? e.g. prefixing **_wpcli__** ?

Thanks
Kimberly

**Comment by danielbachhuber** [comment]
Hi @amiga-500,

Our use of `__invoke()` is deliberate; we do want the documented magic functionality.

There are a [variety of ways](https://wp-cli.org/docs/internal-api/wp-cli-add-command/) you can register WP-CLI commands, so you don't necessarily need to use `__invoke()`.

**Comment by amiga-500** [comment]
Ahh thank you very much!
