### ISSUE TITLE
`wp comment list` unable to display `--type=sensei_lesson_status` comments, why?

### ISSUE THREAD

**Issue by lkraav** [wp-cli/wp-cli#3523]
WP-CLI 0.25.0

Things clearly exist:

    $ [-] wp comment get 15225                                  
    +----------------------+----------------------+
    | Field                | Value                |
    +----------------------+----------------------+
    | comment_ID           | 15225                |
    | comment_post_ID      | 3671                 |
    | comment_author       |                      |
    | comment_author_email |                      |
    | comment_author_url   |                      |
    | comment_author_IP    |                      |
    | comment_date         | 2016-11-02 04:06:20  |
    | comment_date_gmt     | 2016-11-01 21:06:20  |
    | comment_content      |                      |
    | comment_karma        | 0                    |
    | comment_approved     | in-progress          |
    | comment_agent        |                      |
    | comment_type         | sensei_lesson_status |
    | comment_parent       | 0                    |
    | user_id              | 293                  |
    +----------------------+----------------------+

But `wp comment list` remains empty. I'm guessing it's because `comment_content` is empty in these records.

    $ [-] wp comment list --fields=comment_ID,comment_type,comment_author --type=sensei_lesson_status
    +------------+--------------+----------------+
    | comment_ID | comment_type | comment_author |
    +------------+--------------+----------------+
    +------------+--------------+----------------+

What's the remedy? Documentation has no help for this case.

**Comment by lkraav** [comment]
Solution seems to be using `--status=any`. This is confusing, because https://developer.wordpress.org/reference/classes/wp_comment_query/__construct/ says default `status => 'all'`, which would imply the default query to return everything without further arguments needed. Why this naming difference? PS using `--status=all` doesn't work.

**Comment by danielbachhuber** [comment]
> Why this naming difference? PS using --status=all doesn't work.

See https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-comment-query.php#L496-L522

**Comment by lkraav** [comment]
Ty. I'm not sure how I missed spotting that (or hitting Ctrl+F there). Feels like a small documentation patch here with an additional example here about this would be incrementally useful for world sanity.
