### ISSUE TITLE
Allow for random password generation on install

### ISSUE THREAD

**Issue by pkarjala** [wp-cli/wp-cli#3534]
As discussed in #129, the `wp install` method does not currently allow for the system to generate a random password for the admin user.  It would be ideal if this could be done so that the user does not have to worry about creating a sufficiently random password.  Instead, let Wordpress handle the task, and present that password to the user at the end of the install process.

This takes care of having to input a password on the command line for the `install` command as well.

**Comment by danielbachhuber** [comment]
👍  Dig it
