### ISSUE TITLE
wp-cli doesn't update wordfence plugin (but returns success)

### ISSUE THREAD

**Issue by th3penguinwhisperer** [wp-cli/wp-cli#3549]
First things first :) Thanks for your efforts on this library. It's keeping my site up to date with a minimal of effort.

I update wp-cli daily pulling from the git repository (cronjob): https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

All works great. Except for 1 plugin. It's called wordfence. I'm pretty sure this is not a problem in wp-cli but rather how wordfence does what it does (having crappy code to annoy users so they will uninstall or buy. No wait, just uninstall).

I just want to mention this so you might be able to shed a look at it to ensure this isn't with other major plugins. If you need extra info, just ask and I'll supply.
For me the choice is easy: updating my wordpress install daily automatically or having failures everyday and having to login and still install wordfence update manually. (and they do this really often, I'd almost think they just do a version bump every few days). The only useful thing it does for me is telling me when people are logging in, but I'm sure there are plenty of other plugins doing the same stuff.

**Comment by danielbachhuber** [comment]
Hi @th3penguinwhisperer,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
