### ISSUE TITLE
[Documentation] current wp-cli install directions do not allow use of wp cli update

### ISSUE THREAD

**Issue by pkarjala** [wp-cli/wp-cli#3572]
As part of the install directions at https://wp-cli.org/ the user is suggested to do the following steps to install:

> To use WP-CLI from the command line by typing wp, make the file executable and move it to somewhere in your PATH. For example:
```
$ chmod +x wp-cli.phar
$ sudo mv wp-cli.phar /usr/local/bin/wp
```

However, if the user follows these steps, they will be unable to easily update wp-cli as suggested at https://wp-cli.org/commands/cli/update/; running the command results in the following:

```
$ wp cli update
Error: /usr/local/bin is not writable by current user.
```

The user can opt to run this as `sudo` but receives a warning against doing so; however, since we moved the script to a location that requires `sudo` to be updated, it seems to be that allowing this for updating the script itself is OK.

The installation instructions do briefly mention updating by installing over the existing version, but this seems clunky, especially for testing features that are not yet in the mainline release version.

I'm not sure what a good solution for this one is.

**Comment by danielbachhuber** [comment]
@szepeviktor Suggestions?

**Comment by szepeviktor** [comment]
Of course. Don't you remember the --allow-root issue?

Please issue `wp --allow-root cli update`

**Comment by danielbachhuber** [comment]
@szepeviktor Meaning, suggest using `sudo su; wp --allow-root cli update` ?

**Comment by szepeviktor** [comment]
Yes, a system files update is the chore of root.

**Comment by szepeviktor** [comment]
Actually
```bash
sudo su -
# Enter your pwd
wp --allow-root cli update
```

**Comment by pkarjala** [comment]
OK; if the expectation is to use `sudo` to perform the update in this case, that's fine by me!

**Comment by szepeviktor** [comment]
maybe you've missed --allow-root from the two docs commits


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
