### ISSUE TITLE
Call to undefined function add_filter()

### ISSUE THREAD

**Issue by mopquill** [wp-cli/wp-cli#3574]
Hey! I'm attempting to automate updates of my WordPress sites/plugins/themes, and I'm getting an error just trying to run a simple `wp core check-update` command. I read the [documentation](https://wp-cli.org/docs/) and the [best practices](http://wp-cli.org/docs/bug-reports/), and I'm reporting what may well be a support issue in case there's some kind of bug. This is my first time attempting to use wp-cli, but I've also been working with WordPress for 8 or so years now, so I'm hopefully not wasting anyone's time. Apologies if I'm way off-base.

I installed following the [installation instructions](https://wp-cli.org/docs/installing/), and made sure the executable is in the recommended location, `/usr/local/bin/wp`. Its permissions are `755`. My first attempt at running a command was immediately greeted with a fatal error. I went over the [common issues](https://wp-cli.org/docs/common-issues/), and I have not made any of the mistakes in there. And to be extra clear, I have not removed `require_once(ABSPATH . 'wp-settings.php');` from `wp-config.php`. My wp-config.php *is* one directory above my public directory (where WordPress lives), though I tried temporarily moving it into pub to see if the command would run. No dice, however. I also tried running the nightly, but got the same error. I reinstalled the stable version of wp-cli after that and tested again.

I'm running on Debian Jessie 8.6, totally stable, no Sid packages or anything weird. The box is a simple web server, and its packages are pretty standard (LAMP stack), and up to date as of this writing.

Here's the `--info`:
```Shell
$ wp --info
PHP binary:     /usr/bin/php5
PHP version:    5.6.27-0+deb8u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.25.0
```

And it reports being on the latest version:
```Shell
#wp cli update --allow-root
Success: WP-CLI is at the latest version.
```

Here's the command I was attempting to run with the `--debug` flag attached.
```Shell
$ wp core check-update --debug
Debug (bootstrap): No readable global config found (0.009s)
Debug (bootstrap): No project config found (0.01s)
Debug (bootstrap): No package autoload found to load. (0.151s)
Debug (bootstrap): ABSPATH defined: <domain-lives-here>/pub/ (0.151s)
Debug (bootstrap): Begin WordPress load (0.152s)
Debug (bootstrap): wp-config.php path: <domain-lives-here>/wp-config.php (0.152s)
PHP Fatal error:  Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(952) : eval()'d code on line 96
```

And here's the request debug info:
```Shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie
$ uname -a
Linux nocturne 4.6.5-x86_64-linode71 #2 SMP Fri Jul 29 16:16:25 EDT 2016 x86_64 GNU/Linux
$ which -a php
/usr/bin/php
$ php -v
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
$ php -m | grep -i suhosin
$ grep '^$wp_version\s' wp-includes/version.php
$wp_version = '4.6.1';
$ which -a wp
/usr/local/bin/wp
$ stat $(which wp)
  File: ‘/usr/local/bin/wp’
  Size: 5123908         Blocks: 10032      IO Block: 4096   regular file
Device: 800h/2048d      Inode: 14289       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (   50/   staff)
Access: 2016-11-16 04:12:15.000000000 -0700
Modify: 2016-11-16 04:12:15.000000000 -0700
Change: 2016-11-16 04:12:40.000000000 -0700
 Birth: -
$ wp package list
Error: Composer directory for packages couldn't be created.
```

Again, I tried to verify that this is not a support issue, but apologies if I've made a mistake. Thanks for any light you guys can shed on this.

**Comment by danielbachhuber** [comment]
Hi @mopquill,

Thanks for the detail. This type of request would be considered support though.

**Comment by mopquill** [comment]
It doesn't work out of the box... would you care to point me in the right direction?

**Comment by danielbachhuber** [comment]
> would you care to point me in the right direction?

See http://wp-cli.org/#support

**Comment by mopquill** [comment]
Yes, I read that, which is how I found many of the links I mentioned. As I stated in my original post, my thoughts were that it not working out of the box on a cookie-cutter system might indicate an issue, which I wanted to confirm, especially as the error isn't actually telling me the problem it's running into. Thanks.

**Comment by mopquill** [comment]
If anyone else ends up seeing this and needing it, this error is related to the parsing of config.php in such a way that you cannot use WordPress functions. The error failing out is cryptic, and this has been reported by the same guy that closed my thread. It was marked as a bug that will not be fixed: https://github.com/wp-cli/wp-cli/issues/1631

The solution is to move anything causing errors to mu-plugins as a workaround.

**Comment by danielbachhuber** [comment]
> The error failing out is cryptic, and this has been reported by the same guy that closed my thread.

It's also the second error listed on common issues and their fixes: http://wp-cli.org/docs/common-issues/#php-fatal-error-cannot-redeclare-wpunregisterglobals

I'm the maintainer of WP-CLI, btw.

**Comment by mopquill** [comment]
That's not the same issue. It's also a fatal error, but that's about it. If that is intended to be the same error, something more along the lines of "wp-cli attempts to parse your wp-config.php and removes the code that starts WordPress. Attempting to call a WordPress function will result in a failure. Any modifications that cause this can be moved to an mu-plugin as a workaround."

From my perspective, I was reporting a bug that had already been reported, which would not fall under support. It would have been reasonable to link me to that specific report, as earlier, I was *not* looking at things that were classified as bugs, as I would have thought they would be dealt with or detailed on the issues page -- which was perhaps an oversight on my part. Closing the thread as support and linking me to the page I already read doesn't seem to be in good faith, especially considering the time and effort I put into my original post for what turned out to be a bug after all.

As a fellow developer, I understand that burnout can set in from overwhelming amounts of support requests for a free product (and that's not to say I don't appreciate all the work! -- and believe me, I really empathize), but I'd rethink the philosophy behind this behavior -- clearly I wasn't being lazy, I just wasn't familiar with the idiosyncrasies of this hitch.

In any case, thanks for creating this in the first place. It seems like it will be really useful to keep everything running well, so I look forward to that. Have a good day. :)

**Comment by danielbachhuber** [comment]
> That's not the same issue. It's also a fatal error, but that's about it.

To help the next person that comes along, could you submit a PR to the "Common Issues" doc with your suggested changes?

> From my perspective, I was reporting a bug that had already been reported, which would not fall under support.

Ok. I think part of the problem may be that we have two different working definitions of "support".

> Closing the thread as support and linking me to the page I already read doesn't seem to be in good faith, especially considering the time and effort I put into my original post for what turned out to be a bug after all.

Sure, but please appreciate the implicit demand of time you're making on someone else. Even though it was helpful for you to put together a comprehensive report, it's ultimately self-serving — to solve your own issue. 

> As a fellow developer, I understand that burnout can set in from overwhelming amounts of support requests for a free product (and that's not to say I don't appreciate all the work! -- and believe me, I really empathize), but I'd rethink the philosophy behind this behavior -- clearly I wasn't being lazy, I just wasn't familiar with the idiosyncrasies of this hitch.

What would you suggest doing instead, that doesn't increase the maintenance burden?

**Comment by mopquill** [comment]
> To help the next person that comes along, could you submit a PR to the "Common Issues" doc with your suggested changes?
Sure, I can do that.

> Ok. I think part of the problem may be that we have two different working definitions of "support".
That is possible. To me, support is "fix my problem for me" as opposed to "this is a bug that is not practical to fix, see: https://github.com/wp-cli/wp-cli/issues/1631" which takes about as much effort as closing the thread and linking me to the support section on the main site.

> Sure, but please appreciate the implicit demand of time you're making on someone else. Even though it was helpful for you to put together a comprehensive report, it's ultimately self-serving — to solve your own issue.
I absolutely do. I took the time to write this report because it didn't work out of the box, after following all instructions perfectly. I could have taken the time to just try fixing my issue alone (which I did after it looked like I wasn't going to hear anything, and it only took like 10 minutes of searching -- stack exchange was less helpful and I thought it would be more helpful). I figured rather than just trying to fix it for myself, I'd spend a while compiling all of that information, and pouring over everything because this seems like a good project, and it would help to hammer something like that out if possible for future users. Yes, I would benefit from it, but not as much as I would not dedicating time to writing up an issue for something I thought might be an *unknown* bug and just fixing my own stuff. It seems like something that should be made very apparent if a wordpress CLI can't run built-in wordpress commands from the config. I absolutely understand why that is so, but it's not at all apparent to a newcomer to wp-cli, you know?

I personally usually do extensive FAQs. Make sure they cover all of the stuff people run into, so you really can just link them the page and close the thread. Then anyone coming in is lazy, or reporting an actual bug.

**Comment by danielbachhuber** [comment]
> To me, support is "fix my problem for me" as opposed to "this is a bug that is not practical to fix, see: #1631" which takes about as much effort as closing the thread and linking me to the support section on the main site.

Just for the record, while it may not seem to take a lot of effort, it does take more effort for me to work with you to track down the bug. I didn't know it was that issue at the time; if so, I would've linked to it.

> I took the time to write this report because it didn't work out of the box, after following all instructions perfectly.

Oh, you indirectly gave me an idea. I should clarify that bugs need to be reproducible in a fresh WP install: https://github.com/wp-cli/wp-cli.github.com/pull/253

> I personally usually do extensive FAQs. Make sure they cover all of the stuff people run into, so you really can just link them the page and close the thread.

As you learn how to use WP-CLI, and want to share your findings, pull requests to improve the documentation are more than welcome.

**Comment by mopquill** [comment]
> Just for the record, while it may not seem to take a lot of effort, it does take more effort for me to work with you to track down the bug. I didn't know it was that issue at the time; if so, I would've linked to it.

Well, knowing the issue now, I would say that `Call to undefined function add_filter()` makes the issue obvious, but I can certainly understand not having the time to read through all the details of a post like this.

> Oh, you indirectly gave me an idea. I should clarify that bugs need to be reproducible in a fresh WP install: wp-cli/wp-cli.github.com#253

That's a good idea.

> As you learn how to use WP-CLI, and want to share your findings, pull requests to improve the documentation are more than welcome.

Okay, cool, will do. I just finished the changes to the .md for common issues, going to fork and file a pull request in a moment. I do most things via command line and an IDE, and I know git, but not github, so bear with me for a few minutes while I figure out the GUI equivalents to the commands. Github keeps showing me a unicorn, so that is only further complicating matters. :P

**Comment by GabLeRoux** [comment]
Found this issue from a google search with following error message:

> PHP Fatal error:  Uncaught Error: Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1070) : eval()'d code:110

Useful things from above comments:

> wp-cli attempts to parse your wp-config.php and removes the code that starts WordPress. Attempting to call a WordPress function will result in a failure. Any modifications that cause this can be moved to an mu-plugin as a workaround.

Related documentation: [wp-cli common issues: PHP Fatal error: Call to undefined function \ #](https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-call-to-undefined-function)

I installed fresh install of a [wordpress bitnami installation](https://bitnami.com/stack/wordpress) on aws as [their suggested installation method](https://aws.amazon.com/getting-started/tutorials/launch-a-wordpress-website/) and the `undefined function add_filter()` error occurs because bitnami has a custom `wp-config.php` file where it adds the following lines at the end of the file:

```php
//  Disable pingback.ping xmlrpc method to prevent Wordpress from participating in DDoS attacks
//  More info at: https://docs.bitnami.com/?page=apps&name=wordpress&section=how-to-re-enable-the-xml-rpc-pingback-feature

// remove x-pingback HTTP header
add_filter('wp_headers', function($headers) {
    unset($headers['X-Pingback']);
    return $headers;
});
// disable pingbacks
add_filter( 'xmlrpc_methods', function( $methods ) {
        unset( $methods['pingback.ping'] );
        return $methods;
});
add_filter( 'auto_update_translation', '__return_false' );
```

Error message is indeed obvious, we need to get rid of the `add_filter` functions from `wp-config.php`.

A simple workaround for this is to move these lines from `wp-config.php` to your theme's `functions.php` instead.

## Suggestion for a `wp-cli` fix

Instead of failing with the error, the script could also parse the document with a regex to find calls to `add_filter` since this seems quite common, strip them in a similar way to what it does with `require_once(ABSPATH . 'wp-settings.php');`, and write a warning with links to the  [wp-cli common issues: PHP Fatal error: Call to undefined function \ #](https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-call-to-undefined-function).

Not a big deal anyway. Thanks the awsome wp-cli, :v:

**Comment by jotamartos** [comment]
Hi @GabLeRoux , Bitnami Engineer here. 

As a workaround in the Bitnami stack, you can simply include the pingback's configuration lines in the wp-config.php file inside a if block like this one:

```
if ( !defined( 'WP_CLI' ) ) {
// remove x-pingback HTTP header
}
```

We also noticed that we need to set the HTTP_HOST variable when using WP CLI and that can be fixed using this:

```
if ( defined( 'WP_CLI' ) ) {
     $_SERVER['HTTP_HOST'] = 'localhost';
}
```

I hope this information helps.
Jota

**Comment by GabLeRoux** [comment]
Checking for WP_CLI is indeed a much better solution, thanks for passing by :)

**Comment by carlosbensant** [comment]
As Gabriel indicated, I just got rid of all the add_filter functions from WP-Config.php.

Thank you @GabLeRoux!
