### ISSUE TITLE
Send structured output to stderr

### ISSUE THREAD

**Issue by greg-1-anderson** [wp-cli/wp-cli#3580]
Breaking out the [suggestion from gmcmillan](https://github.com/wp-cli/wp-cli/issues/3577#issuecomment-261317786) into a separate issue.

Drush has a "backend invoke" mode that sends back structured data (currently json) for use by scripts. This code could use a little modernization. If wp-cli were interested in sending structured results back via stderr, I'd be interested in collaborating [*] on a common library to do this.

[*] By 'collaborating' I mean listening to your requirements from scripts that call wp-cli, and what sort of data they expect to get back. Not actually expecting you to rewrite backend invoke for me. ;)

**Comment by danielbachhuber** [comment]
Could you provide an example of how Drush uses this, how WP-CLI might use it, and why the current behavior isn't sufficient?

**Comment by greg-1-anderson** [comment]
Drush itself primarily uses this facility when running `drush @remote command`. This uses backend invoke, which is a wrapper around proc_open that manages I/O in such a way as to allow the user to see incremental output, and still return structured data that includes the different log messages, the rendered output, the original php object or array that produced the output, and so on. This is useful for scripts that might want to call Drush and act on the results.

The current behavior is sufficient for most uses. Folks can use `ob_start()` with a callback function when they call `exec` or `passthru` to call wp-cli. They can ask for results in json format or what-have-you, as supported. Backend invoke is more convenient, and using a library could add consistency; however, it's also possible to just insert `write(stderr, json_encode(...))` where needed in wp-cli. That would likely be messier / harder to maintain / potentially less consistent, but certainly would be sufficient.

**Comment by danielbachhuber** [comment]
Ok. It seems like there's not much that's actionable at this point. This seems like a good idea, but it's not clear what the immediate use cases are.

How would you suggest proceeding forward?

**Comment by greg-1-anderson** [comment]
I'll update this issue when I start factoring out backend invoke.

**Comment by danielbachhuber** [comment]
Sounds good. Going to close it for now.

**Comment by greg-1-anderson** [comment]
Drush backend invoke has now been replaced by [consolidation/site-process](https://github.com/consolidation/site-process). This library is independent of Drush, and can be re-used by other projects. Doing so also requires the use of [consolidation/site-alias](https://github.com/consolidation/site-alias), though.

**Comment by schlessera** [comment]
Thanks for the update, @greg-1-anderson ! As soon as I find a minute I will take a closer look and see whether this is something that can be reused by WP-CLI as well.
