### ISSUE TITLE
Every command should support `--format=json`

### ISSUE THREAD

**Issue by voldemortensen** [wp-cli/wp-cli#3581]
In developing apps around wp-cli, I've found it would be incredibly useful to have every command support `--format=json`. Currently, there are cases where I've had to resort to parsing output to get the information that I need. For example, `wp core verify-checksums`.

I'm currently taking output i.e.:
```
Warning: File doesn't verify against checksum: wp-includes/version.php
Warning: File doesn't verify against checksum: readme.html
Warning: File doesn't verify against checksum: wp-config-sample.php
Error: WordPress install doesn't verify against checksums.
```
And using regex to parse out which files don't match so I can display them with a custom error message and steps to take to investigate/fix the issue.

This output would be far easier to consume:
```{"error":1,"mismatches":["wp-includes\/version.php","readme.html","wp-config-sample.php"],"message":"WordPress install doesn't verify against checksums."}```

Even if a command would only produce `{"success":1}` it would be much easier to consume in app development.

Thoughts?

**Comment by danielbachhuber** [comment]
Seems interesting. I'd encourage you to develop this out as a community package first. We can consider it for inclusion in WP-CLI when it's getting close to feature complete.

**Comment by danielbachhuber** [comment]
Also, I'll be working on something similar with [wp doctor](https://runcommand.io/wp/doctor/) and will share my learnings when I have them.

**Comment by mikeschinkel** [comment]
Just curious what the status is for this?
