### ISSUE TITLE
`wp server` "Cannot modify header information" error

### ISSUE THREAD

**Issue by doup** [wp-cli/wp-cli#3587]
When using the `wp-cli` builtin server (`wp server --port=1340 --host=0.0.0.0`) it gives me the following error in `/wp-admin` URL:

```
Warning: Cannot modify header information - headers already sent by (output started at /Users/doup/Code/celobert-web/wp-content/plugins/js_composer/js_composer.php:1) in /Users/doup/Code/celobert-web/wp-includes/pluggable.php on line 1174
```

**But**, when running from the php server (`php -S 0.0.0.0:1340 -t .`) it just works. I've checked `js_composer.php`, `pluggable.php` and the previous callers but could not find any error. Well, indeed _it just works_ when using `php -S` instead of `wp server`… so, whatever.

Not sure if this is a `wp-cli` error or if it's another component in my system. 😓 

My `wp --info`:
```
PHP binary:	/usr/local/Cellar/php54/5.4.45_6/bin/php
PHP version:	5.4.45
php.ini used:	/usr/local/etc/php/5.4/php.ini
WP-CLI root dir:	/usr/local/Cellar/wp-cli/0.25.0
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.25.0
```

**Comment by danielbachhuber** [comment]
@doup Does the problem reproduce in a fresh install of WordPress with no plugins activated?
