### ISSUE TITLE
Custom wp-includes & Error: This does not seem to be a WordPress install.

### ISSUE THREAD

**Issue by DuckDagobert** [wp-cli/wp-cli#3590]
When redefining WPINC to a custom value (e.g. source instead of wp-includes), which is fully supported by WP except for the update functionality, it will throw this error.

When just copying the new directory (e.g /source) and renaming it to wp-includes it works fine.

**Comment by danielbachhuber** [comment]
> When redefining WPINC to a custom value (e.g. source instead of wp-includes), which is fully supported by WP except for the update functionality

Where does WordPress say this is supported?

`wp-settings.php` has `WPINC` hardcoded at the top: https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L16 If you set `WPINC` earlier, you'll get a PHP notice.

**Comment by danielbachhuber** [comment]
Also, can you share `wp --info` and `wp core version`?

**Comment by DuckDagobert** [comment]
wp --info
PHP binary:     /usr/bin/php
PHP version:    7.0.9
php.ini used:   /etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /home/USERNAME/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.1


wp core version
4.5.1

**Comment by danielbachhuber** [comment]
Hi @DuckDagobert, 

This isn't something WP-CLI is going to support.
