### ISSUE TITLE
update scaffold blog post

### ISSUE THREAD

**Issue by squarecandy** [wp-cli/wp-cli#3597]
The actual documentation pages for scaffold are all good, but I find myself referring to this blog post frequently - it's such a great clear overview with great useful examples:
http://wp-cli.org/blog/scaffolding-custom-post-types-and-taxonomies.html

Might be worth updating `--post-type=zombie` to `--post_types=zombie`.

P.S. - WP CLI is awesome! I use it all the time.

**Comment by danielbachhuber** [comment]
@squarecandy I'm not sure I follow. Could you edit https://github.com/wp-cli/wp-cli.github.com/blob/master/_posts/2013-03-29-scaffolding-custom-post-types-and-taxonomies.md with your suggested changes, and submit a PR?

**Comment by squarecandy** [comment]
Ok, submitted.

**Comment by danielbachhuber** [comment]
@squarecandy Where'd you submit it?

**Comment by squarecandy** [comment]
https://github.com/wp-cli/wp-cli.github.com/compare/master...squarecandy:patch-1?expand=1#diff-9d9b5c8cae9fcf9f6ec2aee8d25b6167

https://github.com/squarecandy/wp-cli.github.com/tree/patch-1
