### ISSUE TITLE
`wp mu-plugin`

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#36]
I think we should separate mu-plugin handling from the `plugin` command.

Most subcommands simply don't make sense for them: status, activate, deactivate, toggle, install, update.

The only subcommands that would work would be `list`, `path` and `delete`.

**Comment by joeguilmette** [comment]
Care to share your solution?

**Comment by oviliz** [comment]
+1 to @joeguilmette request...

**Comment by pabloselin** [comment]
+1 to @joeguilmette and @oviliz

**Comment by sc0ttkclark** [comment]
Being able to at least update mu-plugins (assuming slugs match wordpress.org slugs) would be handy here
