### ISSUE TITLE
Delete given number of posts

### ISSUE THREAD

**Issue by twentyfortysix** [wp-cli/wp-cli#3607]
Hello,

how can I delete posts in batch, for example 1000 posts at once.
I know I can do 
`wp post delete $(wp post list --format=ids)`
Which is fine if you have certain amount of posts, but I have 45 000 (I'm working on a project where I use custom posts for "other" kind of data).
 
when I run just 
`wp post list --format=ids`

it lists all the post ids, but when I run 
`wp post delete $(wp post list --format=ids)`

it gets stuck
`-bash: /usr/local/bin/wp: Argument list too long`

and so my question is how to list number of posts to shorten the list down and make it doable?

**Comment by trepmal** [comment]
I'm going to sneak some help in, but Github issues aren't for general support questions anymore. There are other venues you can try: http://wp-cli.org/#support

You can pass `posts_per_page` to `wp post list` 

`wp post list --format=ids --posts_per_page=30`

I do not know off-hand what the maximum number of arguments is.

**Comment by twentyfortysix** [comment]
elegant :)

**Comment by austinginder** [comment]
I ran into the same argument error while attempting to use `wp post meta update` with a very large piece of data. I overcame the argument limitation using [here documents](https://en.wikipedia.org/wiki/Here_document) which will instead stream it to the command. This same approach can be applied for this use case. Here are some examples.

Deletes massive list of posts IDs 
```
wp post delete --prompt << heredoc
$(wp post list --format=ids)
heredoc
```

Updates post meta with contents of a massive json file.
```
wp post meta update 123 custom_field << heredoc
$(cat massive.json)
heredoc
```

Or similar, updates post meta with contents of a massive bash variable.
```
wp post meta update 123 custom_field << heredoc
$json
heredoc
```

**Comment by ethanclevenger91** [comment]
@austinginder Reviving this a bit here since your post doesn't allow comments - how would one turn this into a proper one-liner? heredoc used this way seems to require interaction.

**Comment by austinginder** [comment]
Not sure there is a proper one liner with heredocs. I would put the above multiple lines into a bash script like `delete-posts.sh` then just run that, `./delete -posts.sh`. That would be one line 😀.
