### ISSUE TITLE
wp_cli WPML compatibility

### ISSUE THREAD

**Issue by twentyfortysix** [wp-cli/wp-cli#3608]
Hello,

the wp_cli command doesn't see posts/pages/anything in second language made via WPML plugin (licensed).

I tried it on 2 websites, both has same problem.

Say a have a 42 posts in "cz" (default language) and 1 post in english, second language, in other  words 43 posts.
when I run 
wp post list --post_type='post' --format=count
it returns 42
![prispevky zachran jidlo wordpress](https://cloud.githubusercontent.com/assets/747153/20620227/f2d4b49a-b2f8-11e6-9bdc-164ed74b9ada.jpeg)

I have moved the english post to trash and run 
wp post list --post_type='post' --post_status=trash --format=count
returns 0
.. although the administration clearly shows that the post in second language is in the trash.
![2](https://cloud.githubusercontent.com/assets/747153/20620312/67083b48-b2f9-11e6-8b62-90cbf5848896.jpeg)

**Comment by danielbachhuber** [comment]
Hi @twentyfortysix,

This is an issue specific to WPML, not WP-CLI. Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by twentyfortysix** [comment]
It is hard to say where is the problem, I've submitted ticket on WPML.

**Comment by ClodClod** [comment]
For use WP-CLI the only solution for now is disable WPML plugin and reactive after use WP-CLI.

**Comment by wojsmol** [comment]
@ClodClod Please describe the problem.

**Comment by twentyfortysix** [comment]
Hi, I guess it's over.
I can't remember now on what website I've been doing this ..it's two years old issue.

**Comment by wojsmol** [comment]
@twentyfortysix Your issue description is clear. I ask @ClodClod :smile:

**Comment by zhickson** [comment]
In case anyone comes across this, one option is to add the argument `--suppress_filters=false` to the WP CLI command.

E.g. `wp post list --post_type=post --suppress_filters=false --posts_per_page=50 --format=ids`

This will suppress the filters that WPML are applying to the query. Description in this thread: [https://wpml.org/forums/topic/how-to-get-all-posts-for-a-single-language-code-in-php/](https://wpml.org/forums/topic/how-to-get-all-posts-for-a-single-language-code-in-php/)

**Comment by karlozadro** [comment]
Ran into a similar issue today while needing to update tags on a translated post using WP CLI. I realized you can use the `--url` parameter to target your actions to a specific language by passing in the base URL for that specific language.

So for example `wp post list --tag__in=1,2,3 --ids` will query posts that are tagged with term IDs 1, 2, and 3 in the site's default language, but `wp post list --tag__in=1,2,3 --ids --url="https://www.example.com/fr/"` will run that same query for French posts. Just make sure to update the `--url` parameter to your correct domain & language URL format and the rest should work as expected

**Comment by twentyfortysix** [comment]
> Ran into a similar issue today while needing to update tags on a translated post using WP CLI. I realized you can use the `--url` parameter to target your actions to a specific language by passing in the base URL for that specific language.

nice hack :)

what I do now is the action.. you need to make a custom function with altered query 

```
do_action('wpml_switch_language', 'all');
        $args = array(
            'post_type' => $type,
            'posts_per_page' => 1,
            'fields' => 'ids',
            'post_status' => 'any',
            'meta_query' => [
                [
                    'key' => 'uid',
                    'value' => $id,
                ]
            ]
        );
        $posts = get_posts($args);
        do_action('wpml_switch_language', null);
```
        
and run that for whatever language or all you need.
`wp eval "your_function();"`
