### ISSUE TITLE
PHP warning are displaying when using WP CLI

### ISSUE THREAD

**Issue by SpartakusMd** [wp-cli/wp-cli#3613]
Hello,

I'm running WP CLI 0.25.0 on Debian, PHP 7.0. I keep getting the PHP warnings displayed. In php.ini I have set `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_WARNING`, but no difference. Ran WP CLI with `--debug=false`, still no effect.

How to suppress the warning display, as it breaks the JSON output ?

**Comment by danielbachhuber** [comment]
Hi @spartakusmd,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
