### ISSUE TITLE
Shell integration with Boris (to suppress exit on fatal exception)?

### ISSUE THREAD

**Issue by damien-roche** [wp-cli/wp-cli#3614]
I cannot find documentation about this anywhere, but have found a mention here:

http://wp-cli.org/commands/shell/

I have checked the common problems, joined the slack channel. 

The problem is every time I experience a fatal exception the shell exits and I lose the session. Any ideas? I know this isn't technically a ticket, but I've been looking for support in a few places.

**Comment by danielbachhuber** [comment]
> The problem is every time I experience a fatal exception the shell exits and I lose the session. Any ideas? I know this isn't technically a ticket, but I've been looking for support in a few places.

Github issues aren't an appropriate support venue.
