### ISSUE TITLE
wordfence conflict

### ISSUE THREAD

**Issue by jjcampbell** [wp-cli/wp-cli#3616]
I am getting apache error log messages and cli errors whenever I use wp-cli or the wordpress website has activity.
The apache error logs are:
[Mon Nov 28 17:36:19 2016] [error] [client 23.239.108.83] Unable to open /var/www/network11/wp-content/wflogs/config.php for reading and writing., referer: http://classicrock.network11.sc11.shoutcaststreaming.us/wp-cron.php?doing_wp_cron=1480383379.7646911144256591796875
[Mon Nov 28 17:36:20 2016] [error] [client 47.140.128.149] Unable to open /var/www/network11/wp-content/wflogs/config.php for reading and writing., referer: http://classicrock.network11.sc11.shoutcaststreaming.us/wp-admin/upload.php
and the cli messages are:
Unable to open /var/www/network11/wp-content/wflogs/ips.php for reading and writing.
PHP binary:     php
PHP version:    5.3.3
php.ini used:   /etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /home/jjcampbell/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.25.0

I created a directory with ips.php and config.php at /var/www/network11/wflogs
I have wordfence installed and using the directory /var/www/network11/wp-content/wflogs/
with these same file names.

This is a wordpress multi-site configuration.

What is wrong? How can I make wp-cli to use its own directory separate from wordfence?

**Comment by jjcampbell** [comment]
OK I found a problem with wordfence ownership issues of its log files.
Don't know why this happened - nothing I did. Nor do I understand why this
started happening right after wp-cli was installed.

**Comment by tmuka** [comment]
this permissions issue happens to me whenever i run a wp-cli command as root.  eg `wp-cli --allow-root option get blogname`.  For whatever reason, even after i fix the wflogs/config.php file permissions they get overwritten every time i use wp-cli as root.  It'd be nice if that config wasn't overwritten every time.   Perhaps Wordfence should create the wflogs directory with g+s permissions or something?

**Comment by Guardian101** [comment]
I am getting this same issue, how was this bug closed??

**Comment by PauloBoaventura** [comment]
I am getting this same issue, how was this bug closed??

**Comment by Retro64XYZ** [comment]
I have this error.
