### ISSUE TITLE
Deprecation policy

### ISSUE THREAD

**Issue by diggy** [wp-cli/wp-cli#3620]
The `wp (term|comment) url` subcommands were not deprecated but removed (#3596), causing breakage in custom commands relying on them.

**Comment by danielbachhuber** [comment]
> causing breakage in custom commands relying on them.

Custom commands shouldn't call WP-CLI command class methods directly.

**Comment by diggy** [comment]
OK, but not really my point. Deprecation does not equal removal. A random definition plucked from the interwebs: "should not be used because there is (or there will be) a better alternative in that software that should be used instead". It would be nice to have at least a little time to transition.

>Custom commands shouldn't call WP-CLI command class methods directly

Actually, I'm not following. Looks like this is encouraged in the `WP_CLI::run_command()` [docs](https://wp-cli.org/docs/internal-api/wp-cli-run-command/), no? Why should I write my own `list` subcommand if can just pass the data to a core command w/ `run_command`?

**Comment by danielbachhuber** [comment]
> OK, but not really my point. Deprecation does not equal removal. A random definition plucked from the interwebs: "should not be used because there is (or there will be) a better alternative in that software that should be used instead". It would be nice to have at least a little time to transition.

Noted for the future.

> Actually, I'm not following. Looks like this is encouraged in the `WP_CLI::run_command()` docs, no? Why should I write my own list subcommand if can just pass the data to a core command w/ `run_command`?

Sorry, I thought you were calling `Term_Command->url()` directly.

Calling a command through `WP_CLI::run_command()` (and shortly, `WP_CLI::runcommand()` #3605) is supported, although WP-CLI only applies the backwards compat conversions if you launch a new process.

**Comment by danielbachhuber** [comment]
> although WP-CLI only applies the backwards compat conversions if you launch a new process.

I'll make sure `WP_CLI::runcommand()` applies the backwards compat conversion too
