### ISSUE TITLE
W3 Total cache object cache detection

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3628]
It would be nice to detect cache type `wp cache type` based on this code
https://github.com/szepeviktor/fix-w3tc/issues/184
There's a misunderstanding around $message, it could be `W3TC` plus one of the
possible values: `file, apc (apcu uses the same name), eaccelerator, xcache, wincache, memcached, redis`

**Comment by danielbachhuber** [comment]
+1
