### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted 

### ISSUE THREAD

**Issue by mikejakobsen** [wp-cli/wp-cli#3629]
I just updated to version 1.0.0. But now i can't seem to install any 3 party modules?

How do i fix it? I tried updating every file/folder permission possible. Tried installing it trough Homebrew and the regular Curl method, nothing works.

![Error gif](https://media.giphy.com/media/l2JhqFFBusY2vvvMI/giphy.gif)

```
Installing package runcommand/user-reset-password (dev-master)
Updating /Users/Mike/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /usr/local/Cellar/wp-cli/1.0.0/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 266
```

**Comment by danielbachhuber** [comment]
Hi @mikejakobsen,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by noplanman** [comment]
@mikejakobsen and all others having this issue.

An easy workaround is to manually call composer to complete the installation:
1. `wp package install <package>` (which fails, ok)
2. `composer -d="$(wp package path)" update`
3. Happy! Go and use `wp <whatever-you-just-installed>`

**Comment by danielbachhuber** [comment]
See aso https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes

**Comment by noplanman** [comment]
@danielbachhuber I saw and tried that already, but unfortunately some hostings have their fixed limits, so there doesn't seem to be any workaround 😕 

Hopefully in the future, composer can become lighter and more resource-friendly, let's see.

**Comment by grappler** [comment]
I was able to get it work by changing the PHP version that I used to install the package e.g. `php71 wp package install wp-cli/profile-command`

The alias for the different PHP version may be different on other hosts.

**Comment by noplanman** [comment]
@grappler That's a good tip!
Tried that as well back then, with the different versions available, but sometimes the memory error popped up, sometimes not.

Composer is like the cookie monster, but for memory 😄

**Comment by rlaan** [comment]
@noplanman thanks for your tip, it brought me onto the right track. 
I did need a slight variation and some further digging =>

the composer command I needed was:
`composer --working-dir="$(wp package path)" update`

however wp-cli (1.5.1) had reverted the composer.json file allready after the failed install...

So I manually checked (using cat) the shortly changed composer.json file before it got reverted (but after the package install command), then manually change the file afterwards and it worked :)

**Comment by yashodhank** [comment]
```
php -d memory_limit=512M "$(which wp)" package install <package-name>
```
Example: `php -d memory_limit=512M "$(which wp)" package install wp-cli/admin-command`
