### ISSUE TITLE
Fix PHP 7.1 build failure

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3632]
P2 is causing the [build to fail on PHP 7.1](https://travis-ci.org/wp-cli/wp-cli/jobs/180595582):

```
PHP Warning:  Parameter 1 to wp_default_scripts() expected to be a reference, value given in /tmp/wp-cli-test-run-5840ed2288e4e1.42416671/wp-includes/plugin.php on line 600
```

We either need to:

1. Get P2 to fix this issue.
2. Remove P2 from the test suite in favor of a different theme.

From #3625

**Comment by ernilambar** [comment]
What if we build a theme ourself rather than depending upon other. Doing this will get us full control over it.

**Comment by danielbachhuber** [comment]
We could transition to using a different theme from WordPress.org. If we did, I think I'd prefer to use one from Automattic, as that gives us the greatest likelihood of being around for the long term

**Comment by ocean90** [comment]
Only WP 4.7+ will be fully compatible with PHP 7.1, see https://core.trac.wordpress.org/ticket/37772 and https://core.trac.wordpress.org/ticket/37295.

**Comment by danielbachhuber** [comment]
> Only WP 4.7+ will be fully compatible with PHP 7.1

👍
