### ISSUE TITLE
Ability to specify flags in search-replace regex

### ISSUE THREAD

**Issue by david-treblig** [wp-cli/wp-cli#3634]
Hi! 

I was searching for a way to replace all the content before a certain tag on my WP site to no avail. It's mainly because preg_replace's flag in the SearchReplacer.php file doesn't specify the multiline flag. There could maybe be an option in the cli for that? like --regex-flags=is and still leave them off by default?

Thanks for the great work!

**Comment by danielbachhuber** [comment]
> There could maybe be an option in the cli for that? like --regex-flags=is and still leave them off by default?

I'd be amenable to this.

**Comment by david-treblig** [comment]
Are you for real? I'm so used to be ignored with my silly requests on open source projets and 24h hours later it's done? Thanks! 👍 ❤️
