### ISSUE TITLE
Allow populating network with constants set

### ISSUE THREAD

**Issue by rmccue** [wp-cli/wp-cli#3641]
Right now, `wp core multisite-convert` is a no-op if the multisite constants are set, as it checks `is_multisite()` before running. This is tough to work with in a provisioned environment, as the config may have the constants set, but the database hasn't been "converted" (populated) from single-site yet.

I'd like to propose adding a `--force` that overrides the `is_multisite()` check. This allows other software to do the check instead:

```
if $(wp core is-installed) && ! $(wp core is-installed --network); then
    echo 'define( 'MULTISITE', true ); ...' >> wp-config-local.php
    wp core multisite-convert --force
fi
```

**Comment by danielbachhuber** [comment]
> I'd like to propose adding a `--force` that overrides the `is_multisite()` check. This allows other software to do the check instead:

And, just to clarify, it would only run the database conversion, not attempt to include the constants again?

**Comment by rmccue** [comment]
Yeah, ideally it wouldn't try and write the constants out either

**Comment by danielbachhuber** [comment]
When `MULTISITE=>true` and the database tables don't yet exist, WordPress will error before WP-CLI can execute:

```
  Scenario: Use the `--force` flag when `MULTISITE` constant is already defined # features/core-multisite-convert.feature:4
    Given a WP install                                                          # features/steps/given.php:47
    And a multisite.php file:                                                   # features/steps/given.php:20
      """
      <?php
      define( 'MULTISITE', true );
      """
    And a wp-cli.yml file:                                                      # features/steps/given.php:20
      """
      require:
        - multisite.php
      """
    When I try `wp core multisite-convert`                                      # features/steps/when.php:29
    Then STDERR should be:                                                      # features/steps/then.php:15
      """

      """
      $ wp core multisite-convert

      WordPress database error Table 'wp_cli_test.wp_site' doesn't exist for query SELECT * FROM wp_site LIMIT 2 made by include('php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), require('wp-includes/ms-settings.php'), ms_load_current_site_and_network
      Error: One or more database tables are unavailable. The database may need to be repaired.
      cwd: /tmp/wp-cli-test-run-5846d253dd3393.29184616/
      exit status: 1
```

However, you can make `wp-config.php` unwritable, run`wp core multisite-convert`, and then append the constants after `wp core multisite-convert` runs to achieve the same effect.
