### ISSUE TITLE
Cannot install package from ftp:// address

### ISSUE THREAD

**Issue by Kubitomakita** [wp-cli/wp-cli#3642]
I was trying to install a plugin zip from my private FTP account like this:

`wp plugin install 'ftp://user:pass@host.com/plugin.zip' --activate`

But it returned:

`Warning: Download failed. "A valid URL was not provided."`

Is this possible to use such URLs?

**Comment by danielbachhuber** [comment]
> Is this possible to use such URLs?

I suppose not. `wp plugin install` uses the WordPress upgrader under the hood, which must not support the `ftp://` protocol.
