### ISSUE TITLE
Update version in docs `wp --info` example

### ISSUE THREAD

**Issue by jgraup** [wp-cli/wp-cli#3647]
http://wp-cli.org/#installing has  a reference to `WP-CLI version: 0.25.0` in the `wp --info` example but only [`1.0.0`](http://wp-cli.org/docs/roadmap/) and above are [currently supported](http://wp-cli.org/#support). This is minor but might make sense to update.

I would expect if I was new to the project to see examples with no less than the least supported version.

Cheers.

**Comment by danielbachhuber** [comment]
> This is minor but might make sense to update.

It does, thanks for flagging. There are a bunch of version references we need to make sure are update at release time.
