### ISSUE TITLE
Import command downloads all my media instead of keeping the old URLs.

### ISSUE THREAD

**Issue by ultimagriever** [wp-cli/wp-cli#3650]
The blog I'm trying to migrate to a more recent WordPress version currently offloads the media to an AWS S3 bucket, and, that being, I need to import the media while retaining the S3 URL. It's unfeasible to download the media all over again, seeing as that I have over 2 GB of media and Amazon will bill me for the spent bandwidth. Is there a way to extend the import command so that I can create the media the standard way, but retaining the S3 link?

**Comment by danielbachhuber** [comment]
Hi @ultimagriever,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
