### ISSUE TITLE
Notice: Undefined variable: key in phar:...class-wp-cli.php on line 1003

### ISSUE THREAD

**Issue by mwithheld** [wp-cli/wp-cli#3653]
wp-cli.phar --url=/ core update-db --network

shows one notice for every blog in the network:

> Notice: Undefined variable: key in phar:///path/to-wp-cli/wp-cli.phar/php/class-wp-cli.php on line 1003
> WordPress database already at latest db version 38590 on blah.bloo.com/

**Comment by danielbachhuber** [comment]
Fixed by #3633
