### ISSUE TITLE
wp command not found

### ISSUE THREAD

**Issue by premier-web-design** [wp-cli/wp-cli#3654]
I have installed wp-cli on ubuntu 16.04 with nginx and PHP 7.0
It has successfully being moved to where my WordPress installation is /var/www/html
However whenever I use wp I get a command not found error.
I cannot find anything in the documentation.
Any pointers will help?

**Comment by danielbachhuber** [comment]
Hi @premier-web-design,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
