### ISSUE TITLE
WP CORE UPDATE IN PUBLIC_HTML AND SUB DIRECTORY FOLDER?

### ISSUE THREAD

**Issue by tienloc1** [wp-cli/wp-cli#3658]
Hi,

I have many sites install in sub folder, the structure look like below:

/public_html/
/public_html/site1-directory
/public_html/site2-directory

How I can run single cli to update core for /public_html/ and /public_html/subfolder without repeat it many times?

Thank so much for any helps.

**Comment by danielbachhuber** [comment]
Hi @tienloc1,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
