### ISSUE TITLE
wp db export fails when using --tables via PHP

### ISSUE THREAD

**Issue by ablears** [wp-cli/wp-cli#3660]
I have a PHP script that runs WP-CLI commands via shell_exec.

Running  `shell_exec("wp db export")` works as expected.

Running `shell_exec("wp db export --tables=$(wp db tables 'wpintbnet_5*') export.sql")` appears to work - it returns a success message - but the .sql file only contains the first matching table (example attached). This should return the sql for an entire network sub site. Running the same command directly via cli works as expected.

[export.txt](https://github.com/wp-cli/wp-cli/files/647874/export.txt)

My system:
PHP 7.1.0 
WP-CLI 1.0.0
OSX 10.11.2

**Comment by danielbachhuber** [comment]
Thanks for the detail, @ablears. 

> Running the same command directly via cli works as expected.

This isn't a bug with WP-CLI then. It appears the `$()` operator doesn't work as expected with `shell_exec()`
