### ISSUE TITLE
Stuck on "Error: Another update is currently in progress"

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#3661]
On a site of mine, the `wp core update` command mysteriously failed after downloading the update ZIP file (possibly a network error).

Upon re-running `wp core update`, the message `Error: Another update is currently in progress.` is now blocking the command. Visiting the site in the browser doesn't present the database upgrade screen, and the site has not been updated.

There doesn't appear to be any means of skipping this error, and it's not clear what's causing it to appear. Is there a way of bypassing this error, or flushing its state?

**Comment by danielbachhuber** [comment]
Funny enough, I actually ran into this the other day.

> it's not clear what's causing it to appear.

Here's the source: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-core-upgrader.php#L117

It's not clear why `WP_Upgrader::release_lock( 'core_updater' );` wouldn't have happened if the first update failed though. Any ideas?

**Comment by miya0001** [comment]
We had the same problem today.
We could solve the problem after running the following command.
```
$ wp option delete core_updater.lock
```
However, I do not know it was a safety or not...

**Comment by danielbachhuber** [comment]
@johnbillion Suggestions on how you think we should move forward with this?

**Comment by johnbillion** [comment]
I attempted to get around the problem with the `--force` flag, which is logical but may not be desired as it actually serves another purpose (to force an upgrade to an equal or lower version).

Maybe a different flag and/or a confirmation message. I've not looked into the locking code though so I don't know what would explode if a method of ignoring the lock is introduced.

**Comment by danielbachhuber** [comment]
Fixing this with documentation for now.
