### ISSUE TITLE
Rewrite Structure not working

### ISSUE THREAD

**Issue by harrissAvalon** [wp-cli/wp-cli#3662]
## Command:
 `wp rewrite structure '/%postname%/'`

## Actual Results:

Terminal:
`Success: Rewrite rules flushed.
Success: Rewrite structure set.`

Browser:
When hitting a page I get
![image](https://cloud.githubusercontent.com/assets/22985861/21145649/027d5cda-c11d-11e6-9744-db26e7ebd0a4.png)

## Expected Results:

Browser renders page appropriately.

## Note:

When I go to the permalinks setting page the postname is filled in but not executed. It works when I manually click on the Save Changes button.

![image](https://cloud.githubusercontent.com/assets/22985861/21145747/555d13f0-c11d-11e6-9212-b6facacd5fb3.png)

**Comment by danielbachhuber** [comment]
@harrissAvalon This issue seems incomplete?

**Comment by harrissAvalon** [comment]
@danielbachhuber Sorry I hit enter by accident before finishing typing

**Comment by danielbachhuber** [comment]
@harrissAvalon It looks like you're missing a `.htaccess` file. Did you [follow the setup instructions](http://wp-cli.org/commands/rewrite/structure/), including adding the mod rewrite declaration to your `wp-cli.yml`?

**Comment by harrissAvalon** [comment]
@danielbachhuber I missed the wp-cli.yml step. Thank you for the clarification.
