### ISSUE TITLE
Visible backslashes in path when folder already exists

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#3668]
When attempting to install a plugin into a directory that already exists, the error message contains visible backslashes in the path.

Steps to reproduce:

1. Run `wp plugin install backupwordpress`.
2. Delete at least `wp-content/plugins/backupwordpress/backupwordpress.php`, but not all of the files in the directory.
2. Run `wp plugin install backupwordpress` a second time.
3. Note that the path in the `Destination folder already exists` error message contains backslashes.

**Comment by danielbachhuber** [comment]
Just to confirm, you're suggesting we trim the slashes?

**Comment by johnbillion** [comment]
That's correct. The backslashes are unnecessary escaping.

**Comment by danielbachhuber** [comment]
@johnbillion This is what I see:

```
$ wp plugin install backupwordpress --version=3.6.2
Installing BackUpWordPress (3.6.2)
Downloading install package from https://downloads.wordpress.org/plugin/backupwordpress.3.6.2.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
$ wp plugin install backupwordpress --version=3.6.3
Warning: backupwordpress: Plugin already installed.
Success: Plugin already installed.
```

Do I need to do something different to replicate?

**Comment by johnbillion** [comment]
My steps to reproduce were incorrect. I've updated the ticket description.

**Comment by danielbachhuber** [comment]
> My steps to reproduce were incorrect. I've updated the ticket description.

Thanks, I've reproduced.

The source of the issue is `WP_CLI::error_to_string()`:

```
/**
 * Convert a wp_error into a string
 *
 * @param mixed $errors
 * @return string
 */
public static function error_to_string( $errors ) {
	if ( is_string( $errors ) ) {
		return $errors;
	}

	if ( is_object( $errors ) && is_a( $errors, 'WP_Error' ) ) {
		foreach ( $errors->get_error_messages() as $message ) {
			if ( $errors->get_error_data() ) {
				return $message . ' ' . json_encode( $errors->get_error_data() );
			} else {
				return $message;
			}
		}
	}
}
```

Specifically, we're `json_encode()`'ing the data on the `WP_Error` object. In this case, the destination path gets extra slashes.

Given the data is informational, I think we can solve the problem by only JSON encoding the data when it's an array or object, and simply quoting it otherwise.
