### ISSUE TITLE
Incorrect example in `wp post update` documentation

### ISSUE THREAD

**Issue by timparenti** [wp-cli/wp-cli#3669]
The example in both [the `wp post update` documentation](https://wp-cli.org/commands/post/update/) and the output of `wp post update --help` refers to updating a field called `post_name`, while no such field is mentioned on the [function reference for `wp_update_post`](https://codex.wordpress.org/Function_Reference/wp_update_post).  The proper field is `post_title`.

**Comment by danielbachhuber** [comment]
`post_name` is a valid field for `wp_update_post()` too. It's the post slug.
