### ISSUE TITLE
Adding subcommands to existing commands

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3671]
Could we enhance the cookbook to mention this?

I think it is only possible by `__invoke()`

**Comment by danielbachhuber** [comment]
I'm not sure I follow. Can you explain in further detail?

**Comment by szepeviktor** [comment]
I was adding `wp core git-update` but it was only possible through __invoke()

**Comment by szepeviktor** [comment]
`\WP_CLI::add_command( 'core', '\\WP_CLI_Git\\Core_Command' );` overwrote the whole core command.

**Comment by danielbachhuber** [comment]
`\WP_CLI::add_command( 'core git-update', '\\WP_CLI_Git\\Core_Command' );`

**Comment by szepeviktor** [comment]
OK for me but missing in the cookbook.

**Comment by szepeviktor** [comment]
I was opening this issue to spare time for other by adding it to the command cookbook.
