### ISSUE TITLE
wp site create --slug creates sites at the wrong URL

### ISSUE THREAD

**Issue by vmasto** [wp-cli/wp-cli#3673]
Hello, first, thank you for this amazing piece of software.

I believe there's a slight issue with the `wp site create` command when the Multisite installation is under a subdirectory.

For example when the URL is `http://localhost/dev/`, doing `wp site create --slug=newsite` adds the site to the (erroneous) URL of `http://localhost/newsite` (instead of `http://localhost/dev/newsite`).

Here's the wp-config:

```php
define('WP_ALLOW_MULTISITE', true);

define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', false );
$base = '/dev/';
define( 'DOMAIN_CURRENT_SITE', 'localhost' );
define( 'PATH_CURRENT_SITE', '/dev/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
```

**Comment by danielbachhuber** [comment]
> For example when the URL is `http://localhost/dev/`, doing `wp site create --slug=newsite` adds the site to the (erroneous) URL of `http://localhost/newsite` (instead of `http://localhost/dev/newsite`).

@vmasto When you perform the equivalent steps through the WordPress admin, do you see the same behavior or different behavior?

**Comment by vmasto** [comment]
WordPress admin works correctly. It identifies the base and only requires the slug.
