### ISSUE TITLE
Update themes/plugins from GitHub zip

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3675]
`wp plugin install https://github.com/envato/wp-envato-market/archive/master.zip` works quite well, strips off `-master` from the folder name.

Could we have zip-based plugin updates?

**Comment by szepeviktor** [comment]
Untill then

```bash
#!/bin/bash

WP_CONTENT_DIR="$(wp eval 'echo WP_CONTENT_DIR;')"

if [ -n "$WP_CONTENT_DIR" ] && [ -d "$WP_CONTENT_DIR" ]; then
    rm -rf "${WP_CONTENT_DIR}/plugins/wp-envato-market"
    wp plugin install "https://github.com/envato/wp-envato-market/archive/master.zip"
fi
```

**Comment by danielbachhuber** [comment]
Duplicate of #2394

 You can run `wp plugin install --force <plugin|zip|url>` to achieve the same effect.

**Comment by szepeviktor** [comment]
Thank you.
