### ISSUE TITLE
Possible bug with wp core update

### ISSUE THREAD

**Issue by consc198** [wp-cli/wp-cli#3680]
Hello all,

I believe i've located a bug with wp core update, this is occuring with WP CLI 1.0.0 however it was occurring on previous versions aswell.

The process is getting stuck at this step here:

root@server [/home/chris57/public_html]# wp core update --allow-root
  adding: -

We've investigated it and there is what seems to be a stuck zip process:

root@server [/home/chris57]# ps aux | grep zip
root      4716  0.0  0.0 101436   952 pts/0    S+   13:23   0:00 zip
root      4827  0.0  0.0 103308   876 pts/1    S+   13:23   0:00 grep zip
root@server [/home/chris57]# lsof +p 4716
COMMAND  PID USER   FD   TYPE             DEVICE SIZE/OFF      NODE NAME
zip     4716 root  cwd    DIR              253,0     4096   5901587 /home/chris57/public_html
zip     4716 root  rtd    DIR              253,0     4096         2 /
zip     4716 root  txt    REG              253,0   212048  17828128 /usr/bin/zip
zip     4716 root  mem    REG              253,0 99160384  17835529 /usr/lib/locale/locale-archive
zip     4716 root  mem    REG              253,0  1923352  11141134 /lib64/libc-2.12.so
zip     4716 root  mem    REG              253,0   154664  11141123 /lib64/ld-2.12.so
zip     4716 root  mem    REG              253,0    26060  17826603 /usr/lib64/gconv/gconv-modules.cache
zip     4716 root    0u   CHR              136,0      0t0         3 /dev/pts/0
zip     4716 root    1w  FIFO                0,8      0t0 650223037 pipe
zip     4716 root    2u   CHR              136,0      0t0         3 /dev/pts/0
zip     4716 root    3u  unix 0xffff8803e3ac5080      0t0 650223004 socket

This occurs on around 30 sites on this server, the server has around 300 sites - the rest update fine but some display this error.

I believe there must be some bug, it just gets stuck there forever really until we terminate the command.

OS is CentOS 6.8 x86_64 running with cPanel as the control panel.

Please let me know what other details you require from me.

Thank you.

**Comment by danielbachhuber** [comment]
@consc198 It sounds like this is an environmental issue (e.g. specific to your server configuration), not a bug with WP-CLI. Per the [bug report guidelines](http://wp-cli.org/docs/bug-reports/), bugs need to be reproducible with a stock WordPress install.

If the [current fundraising](http://wp-cli.org/blog/the-big-question.html) effort proves successful, there will be a forum for general support in early 2017.
