### ISSUE TITLE
Purge opcode cache on updates

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#3682]
Drush uses a special URL to purge opcode cache on the webserver.

Could we use a wpnonce-protected URL to purge OPcache after updates?
...so you don't have to reload php-fpm (or Apache using mod_php)

**Comment by danielbachhuber** [comment]
This will need to be implemented as a plugin. WP-CLI could call a URL to flush opcache after updates, but the plugin would need to be active on the site to receive it.

**Comment by szepeviktor** [comment]
Could we implement that *plugin*?
It must be no more than registering a hook with OPcache purge function.

**Comment by danielbachhuber** [comment]
You're more than welcome to.

**Comment by szepeviktor** [comment]
@danielbachhuber Is it Ok to hook `upgrader_process_complete` for OPcache purge?

**Comment by szepeviktor** [comment]
There are my thoughts.
```php
if ( function_exists( 'opcache_get_status' ) {

    // After an upgrade Tell PHP behind the webserver to purge its opcode cache
    add_action( 'upgrader_process_complete', function () {
        // HTTP/POST to '/wp-admin/admin-post.php?action=opcache_invalidate&wp_nonce=$NONCE'
    } );

    // Receive the request to purge
    // admin_post_nopriv_ ???
    add_action( 'admin_post_opcache_invalidate', function () {
        // nonce check
        // __FILE__ is in ini_get( 'opcache.restrict_api' );
        $status = opcache_get_status();
        foreach( $status['scripts'] as $script ) {
            opcache_invalidate( $script['full_path'] );
        }
    } );
}
```
