### ISSUE TITLE
Cannot use: wp core download

### ISSUE THREAD

**Issue by vietzon** [wp-cli/wp-cli#3686]
Hello

I have WHM and just installed the WP-CLI. As far as i can see, the install was OK, no errors. 

_PHP binary:	/opt/cpanel/ea-php56/root/usr/bin/php
PHP version:	5.6.29
php.ini used:	/opt/cpanel/ea-php56/root/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.0.0_

But i cannot install wordpress with cmd:  **wp core download** 
It went through but there are not wp files in public_html ...

_Debug (bootstrap): No readable global config found (0.009s)
Debug (bootstrap): No project config found (0.01s)
Debug (bootstrap): No package autoload found to load. (0.156s)
Debug (bootstrap): ABSPATH defined: /home/dpdzv953/public_html/ (0.156s)
Debug (bootstrap): Running command: core download (0.156s)
Downloading WordPress 4.7 (en_US)...
md5 hash verified: 474c022ef8e5371a8fc756dbfeb96d1b_

Just to be clear. I can run cmd such as:
wp core config
wp core install

So instead run cmd: wp core download; i download directly:
wget http://wordpress.org/latest.tar.gz

and unpack the zip. So, clearly cmd  wp core download is not working...

Cheers

**Comment by danielbachhuber** [comment]
Hi @vietzon,

It sounds like this is an environmental issue (e.g. specific to your server configuration), not a bug with WP-CLI. Per the [bug report guidelines](http://wp-cli.org/docs/bug-reports/), bugs need to be reproducible with a stock WordPress install.

**Comment by vietzon** [comment]
Weird. The server is WHM and a new one. Also i can do other cmds except '
wp core download'

We do use default installation.


cheers



Den 22 dec. 2016 15:52 skrev "Daniel Bachhuber" <notifications@github.com>:

**Comment by 4ernovm** [comment]
+1 for this. recently issuing same problem on several WHM servers.

**Comment by 4ernovm** [comment]
@vietzon in my case it's caused by low memory_limit. make sure you have it in at least 64M or better 128M. If you're using WHM you must have error_log file inside the directory where you're trying to download WP to. It also may help

**Comment by vietzon** [comment]
Hello

thanks for tip. Will write down a checklist in case we install new WHM next
time

cheers

Den 16 jan. 2017 7:14 PM skrev "Michael" <notifications@github.com>:
