### ISSUE TITLE
wp-cli phar file has garbage in it

### ISSUE THREAD

**Issue by mrme44** [wp-cli/wp-cli#3692]
When I try to download wp-cli from [](https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar)

I get the following file

> #!/usr/bin/env php
> <?php
> Phar::mapPhar();
> include 'phar://wp-cli.phar/php/boot-phar.php';
> __HALT_COMPILER(); ?>^M
> k6^A^@▒^C^@^@^Q^@^@^@^A^@^K^@^@^@wp-cli.phar^@^@^@^@"^@^@^@php/WP_CLI/CommandWithDBObject.php▒^Q^@^@Q▒=X▒^Q^@^@~S_^Fr▒^A^@^@^@^@^@^@^^^@^@^@php/WP_CLI/CommandWithMeta.php~Q^X^@^@Q▒=X~Q^X^@^@b▒▒Ƕ^A^@^@^@^@^@^@^_^@^@^@php/WP_CLI/CommandWithTerms.phpS^S^@^@Q▒=XS
> ^S^@^@▒"▒^[▒^A^@^@^@^@^@^@%^@^@^@php/WP_CLI/CommandWithTranslation.php▒0^@^@Q▒=X▒0^@^@r~BJ▒▒^A^@^@^@^@^@^@!^@^@^@php/WP_CLI/CommandWithUpgrade.phpx:^@^@Q▒=Xx:^@^@~^▒~W~J▒^A^@^@^@^@^@^@^Z^@^@^@php/WP_CLI/Completions.phpw^K^@^@Q▒=Xw^K^@^@W8^]^C▒^A^@^@^@^@^@^@^Y^@^@^@php/WP_CLI/ComposerIO.php  ^C^@^@Q▒=X 
> ...

The striked out lines must be from something triggering the markdown for striked out lines, but the main thing here is the compiler is running into some issue, and corrupts the file. There is some valid PHP in the phar file after a bunch of garbage is dumped out.

**Comment by danielbachhuber** [comment]
Hi @mrme44,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support

**Comment by mrme44** [comment]
I'm not looking for support with using the wp-cli tool. I'm reporting that the phar file is broken. If this isn't the place to report bugs, where do I report them?

**Comment by danielbachhuber** [comment]
The Phar file isn't broken. You need to fix Phar execution on your system.

See #1758 for a prior thread.

**Comment by mrme44** [comment]
Sorry for not being clear about how I got that output. I'm not executing the phar file. All I'm doing is going to the URL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar in Chrome. Once the phar file is downloaded, I open it up with vi, and I see the message about the compiler halting followed by a bunch of garbage. That is why I say that the phar file is broken. The same thing happens if I download the phar file using curl.

**Comment by danielbachhuber** [comment]
> Once the phar file is downloaded, I open it up with vi, and I see the message about the compiler halting followed by a bunch of garbage. That is why I say that the phar file is broken.

Oh.

Why are you opening the file in your editor? What you're seeing is expected output. Phar is a compiled PHP format.

**Comment by mrme44** [comment]
![phar](https://cloud.githubusercontent.com/assets/2624199/21509230/4e886ee4-cc44-11e6-9486-50bed8c51c3a.png)

**Comment by mrme44** [comment]
Oh. I didn't know what phar was, and so I opened it, and I saw the message about the compiler having halted, and I figured that was the cause of the problems I've been having with installing wp-cli, but if that's the way it's suppose to be than I guess it's fine. Sorry to have bothered you about this.
