### ISSUE TITLE
Update symfony/console dependency

### ISSUE THREAD

**Issue by raramente** [wp-cli/wp-cli#3693]
Hi,

I've had wp-cli installed via composer. However had to remove it because of a conflict with another global requirement (laravel/envoy).

The problems resides on the symfony/console dependency which is still at 2.7 for wp-cli and 3 for larave/envoy.
I see you've updated the dependencies a few weeks ago. Maybe this is a bigger conflict than I image.

**Comment by danielbachhuber** [comment]
See https://github.com/wp-cli/wp-cli/pull/3635#issuecomment-264854948
