### ISSUE TITLE
With a multi-site WP install, $table_prefix is not set correctly when using --url

### ISSUE THREAD

**Issue by toolstack** [wp-cli/wp-cli#3694]
The global `$table_prefix` (aka `$GLOBALS['table_prefix']`) is set in WordPress to identify the database prefix to use for the current site (which is also available via `$wpdb->prefix`), however when using a WP-CLI command with the global `--url` parameter to select which site of a multi-site install to work on, `$table_prefix` remains unchanged.

Any plugin or code that uses `$table_prefix` to identify the WP tables to use will only act on the original site, effectively ignoring the `--url` parameter.

**Comment by danielbachhuber** [comment]
@toolstack I wasn't aware `$table_prefix` adapts based off the loaded blog.

Can you provide more detail on how you discovered the issue, where this logic is in WordPress core, and steps to reproduce?

**Comment by toolstack** [comment]
I discovered the issue as part of GlotPress, we use the global to get the table prefix to define our tables.

We extend WP-CLI with several commands that then act on GP, in multi-site the `--url` parameter is used but has no effect due to the global not being updated.

When WP normally runs, it is updated without any issue and GP support multi-site.  It's only when WP-CLI is used that it fails.

**Comment by toolstack** [comment]
FYI, [this is the GitHub issue](https://github.com/GlotPress/GlotPress-WP/issues/578) from GlotPress.

**Comment by toolstack** [comment]
You can see `$GLOABLS['table_prefix']` being updated as part of the core `switch_to_blog()` logic in ms-blogs.php, around line 789.

**Comment by danielbachhuber** [comment]
I've reproduced the issue. Debugging why this is happening now.

**Comment by danielbachhuber** [comment]
> Debugging why this is happening now.

Identified the fix in #3695
