### ISSUE TITLE
Some plugins not updating

### ISSUE THREAD

**Issue by Android63** [wp-cli/wp-cli#370]
If I do
  wp plugin update-all
I get
  Success: Updated 0/0 plugins.
But in my WordPress site's dashboard, I see 2 plugins are out of date.
I tried updating them specifically with
  wp plugin update jigoshop
  wp plugin update table-of-contents-plus
and in both cases got
  Warning: The plugin is at the latest version.
Any ideas? I'm using wp-cli 0.9.0

**Comment by kzap** [comment]
i've seen this happen also to me, it seems cache related, like wp-cli is caching a list of plugin versions and you have to get that cache to update somehow

```
$ wp plugin list --skip-plugins=adaptive-images --debug
Debug: No readable global config found (0.005s)
Debug: No project config found (0.005s)
Debug: ABSPATH defined: /PATH/ (0.014s)
Debug: Begin WordPress load (0.014s)
Debug: wp-config.php path: /PATH/wp-config.php (0.014s)
Debug: Loaded WordPress (0.363s)
Debug: Running command: plugin list (0.364s)
+----------------------------------------------+----------+--------+----------+
| name                                         | status   | update | version  |
+----------------------------------------------+----------+--------+----------+
| adaptive-images                              | inactive | none   | 0.6.42   |
| Gravity-Forms-ACF-Field                      | active   | none   | 1.1.0    |
| advanced-custom-fields-pro                   | active   | none   | 5.3.2.2  |
```

then after:
```
$ wp plugin list --debug
Debug: No readable global config found (0.005s)
Debug: No project config found (0.005s)
Debug: ABSPATH defined: /PATH/ (0.014s)
Debug: Begin WordPress load (0.014s)
Debug: wp-config.php path: /PATH/wp-config.php (0.014s)
Debug: Loaded WordPress (0.36s)
Debug: Running command: plugin list (0.36s)
+----------------------------------------------+----------+-----------+----------+
| name                                         | status   | update    | version  |
+----------------------------------------------+----------+-----------+----------+
| adaptive-images                              | inactive | none      | 0.6.42   |
| Gravity-Forms-ACF-Field                      | active   | none      | 1.1.0    |
| advanced-custom-fields-pro                   | active   | available | 5.3.2.2  |
| aftership-woocommerce-tracking               | active   | available | 1.4.6    |
```

I think some how --skip-plugins is making this cache update

**Comment by joeydi** [comment]
@kzap I just wanted to confirm that the optimizepress seems to be causing this issue. If I temporarily disable it, the run `wp plugin update --all` all plugins get updated.

**Comment by kzap** [comment]
Yep its annoying and you have to ignoring each plugin one by one

On Jan 5, 2017 3:21 AM, "Joe di Stefano" <notifications@github.com> wrote:

@kzap <https://github.com/kzap> I just wanted to confirm that the
optimizepress seems to be causing this issue. If I temporarily disable it,
the run wp plugin update --all all plugins get updated.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wp-cli/wp-cli/issues/370#issuecomment-270461201>, or mute
the thread

**Comment by collinkrawll** [comment]
For me, it was my wp-content/object-cache.php file. I removed the file and then was able to update my plugins.  I ended up replacing it with a different implementation of the object cache. The different implementation doesn't have any issues with wp-cli.

**Comment by minac** [comment]
--skip-plugins should skip loading all of them and thus showing the correct update status for each one of them right? Because there are a couple that I can see have updates on the dashboard but wp-cli shows that there is no update for them. :(

**Comment by amandafrench** [comment]
Just a note that I use a plugin called Exclude Plugins on my multisite install that lets me exclude plugins for subsite users. Exclude Plugins causes the same error, and deactivating it allows me to update plugins that otherwise are erroneously shown as not installed.
