### ISSUE TITLE
Package Index: Listing only actual 'Releases' not branches?

### ISSUE THREAD

**Issue by JayWood** [wp-cli/wp-cli#3701]
I noticed with my update today to the random post generator that all my branches were showing under the available versions for the package.

Is there some composer magic I have to do to ensure only actual releases are listed - ie. tags? I ask this purely out of my ignorance of composer 😄

**Comment by danielbachhuber** [comment]
I've noticed this before too. It might be a configuration option with Satis, the package index generator. I'll look into it at some point.

**Comment by JayWood** [comment]
Thanks @danielbachhuber - it's not a huge issue with me, but figured it wouldn't hurt to ask 😄

**Comment by schlessera** [comment]
Composer makes a difference between downloading packaged releases and downloading from a source repository.

When downloading packaged releases, these are served from a server that already has the metadata about the package (i.e. the version number). This metadata was stored from the `composer.json` that was found inside the release package. So, as a simplified example, it requests the package `xyz/awesome` at version 1.0.0, and the server can immediately fetch the exact version that is needed.

When downloading from a source repository, the server (in this case usually a git server) does not provide such metadata. The actual metadata is found in the `composer.json` file as part of one of the source files. Unfortunately, this file exists in all branches, across all tags, and can be different between these. As there's no guarantee that a given tag or branch actually reflects the exact content of the `composer.json` file (i.e. the source code in tag `v1.0.5` has the `"version"` set to `1.0.4` within its `composer.json` file)., Composer is forced to look through all branches, fetch the `composer.json` from each, and look through its contents, to be sure it finds the best possible version.

**Comment by schlessera** [comment]
Ah, it seems the downloads are indeed packaged releases, so this should be configurable on the server that serves these releases.

**Comment by danielbachhuber** [comment]
I think this is something we can eventually solve with Satis (or a future Packagist implementation if we choose one). I'm part of the way there with: https://github.com/composer/satis/issues/393#issuecomment-278339750

I'm not sure of the future state for the package index at this point though, so I refrained from investing more time in it.

**Comment by danielbachhuber** [comment]
Passing on this for now, as the package index is in a permanent state of limbo #3977
