### ISSUE TITLE
Coding standard fixes

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#3703]
Hi!

I started to fix coding standards.
https://github.com/wp-cli/wp-cli/pull/3702

There are so many errors, I want to fix them.

Pros:

* It makes the code clean.
* We can get more contributors.
* It may find potential bugs.

Cons:

* It may introduce a new bug, we have to do it very carefully.
* We need hard work.

Actually, I did it for some files.
https://github.com/miya0001/wp-cli/commits/coding-standard

How do everybody think about it?

**Comment by miya0001** [comment]
My ruleset is following.

```
<?xml version="1.0"?>
<ruleset name="WordPress Coding Standards via https://github.com/Automattic/_s/blob/master/codesniffer.ruleset.xml">
	<!-- See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml -->
	<!-- See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml -->

	<!-- Set a description for this ruleset. -->
	<description>A custom set of code standard rules to check for WP-CLI</description>

	<exclude-pattern>vendor/*</exclude-pattern>
	<exclude-pattern>codesniffer/*</exclude-pattern>
	<exclude-pattern>PHP_Codesniffer-VariableAnalysis/*</exclude-pattern>

	<!-- Include the WordPress ruleset, with exclusions. -->
	<rule ref="WordPress">
		<exclude name="Squiz.Commenting.FunctionComment.Missing" />
		<exclude name="Squiz.Commenting.ClassComment.Missing" />
		<exclude name="Squiz.Commenting.FileComment.Missing" />
		<exclude name="Generic.WhiteSpace.ScopeIndent.IncorrectExact" />
		<exclude name="Generic.WhiteSpace.ScopeIndent.Incorrect" />
		<exclude name="PEAR.Functions.FunctionCallSignature.Indent" />
		<exclude name="WordPress.XSS.EscapeOutput.OutputNotEscaped" />
		<exclude name="WordPress.VIP.FileSystemWritesDisallow.FileWriteDetected" />
	</rule>
</ruleset>
```

**Comment by danielbachhuber** [comment]
At this point, I'm 👎 on making coding standards changes to the entire codebase.

My biggest concern is the cons significantly outweigh the pros. Cleaning up the entire codebase is a huge amount of work for the subjective upsides of making the code more clean and getting more contributors. Making significant stylistic changes across the codebase also makes it more difficult to `git blame`, which is critical for a project as old as this one is.

Do you know of another comparable project that's successfully completed this type of initiative?

**Comment by miya0001** [comment]
> Do you know of another comparable project that's successfully completed this type of initiative?

I don't know. 😓 

> makes it more difficult to `git blame`

Ah, You have a point.
I tried it for a few days and it was actually very hard.

I close this issue, thanks!
