### ISSUE TITLE
docs: `wp core help` doesn't mention --version optional parameter

### ISSUE THREAD

**Issue by vfonic** [wp-cli/wp-cli#3709]
I wanted to download WP v4.6.1 and ran `wp help core` but didn't see any reference to optional `--version` parameter that solved my issue. I found it mentioned on the wp-cli website under `wp plugin` command.

EXPECTED:
`wp help core` docs mention optional `--version` parameter and its usage.

ACTUAL:
No mention of optional `--version` parameter

**Comment by ernilambar** [comment]
I believe this is expected behaviour. `--version` is not global parameter. It is only available in few sub-commands of `core` command.
Try `wp help core download`

**Comment by vfonic** [comment]
That's it! Didn't know I can have more parameters to help command. Thanks!
