### ISSUE TITLE
Is there a way to exclude a single table from a db export?

### ISSUE THREAD

**Issue by emeraldjava** [wp-cli/wp-cli#3715]
Hi Guys,

Thanks for a great tool. In my scenario for DB exports, i'd like to ignore the 'wp_options' content when I'm synching my production and test env's. Is the an existing recommended method to achieve this?

Regards,
Paul

**Comment by danielbachhuber** [comment]
Hi @emeraldjava,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
