### ISSUE TITLE
Look into Consolidation GitHub organization

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3717]
The GitHub organization `Consolidation` (https://github.com/consolidation) provides common PHP projects that can be reused by command-line tools.

It offers such functionality like shared output formatters that are reused by `robo`, `drush` and `terminus`: https://github.com/consolidation

I think it would be overall beneficial for WP-CLI to participate in this effort.

**Comment by danielbachhuber** [comment]
cc @greg-1-anderson 

Are there any aspects in particular you think WP-CLI would benefit from?

**Comment by greg-1-anderson** [comment]
@danielbachhuber The history of Consolidation commands is:

WP-CLI annotated commands -> Robo (submitted by third party via PR) -> Annotation format standardized to match phpdoc -> Refactored into consolidation/annotated-command -> Use of library in Drush and Terminus.  Terminus 0.x, as you may know, was a fork of wp-cli 0.x, and Terminus 1.x was then ported to use the annotated command library. This effort was very successful; you could ask @TeslaDethray and @ronan about their impressions.

The main addition that Consolidation added along the way is the output formatters project, which makes it very convenient for commands to produce structured output (e.g. tables) that can be rendered in human-readable format, with selected / reordered columns, converted to yml or json, etc. etc.

The main cost to WP-CLI would be that all of the command annotations would need to be reformatted to match the new syntax. Also, there are command hooks offered that are annotation based; these could optionally be adopted in place of the hook system WP-CLI is using now. I'm not sure if there is any immediate benefit to this; however, the annotated command hook system is extremely flexible and easy to use.

If you didn't want to take the leap to WP-CLI 2.0, you could also immediately benefit from the output formatters by using them directly. Output formatter support is automatic with no additional code when using the annotated command project, but you can also add them in to any Symfony Console per the [API overview in the README](https://github.com/consolidation/output-formatters#api-usage). This would not be hard.

It would be great to have wp-cli join consolidation as a full user of annotated commands, though, as then, any future improvements to the parser / processor / outputter would benefit all of the associated tools using it.

**Comment by danielbachhuber** [comment]
Thanks @greg-1-anderson 

> The main cost to WP-CLI would be that all of the command annotations would need to be reformatted to match the new syntax.

Given the ecosystem of community commands around WP-CLI, I think this would be a huge, potentially insurmountable cost.

To provide a bit of context, here's how I begin to evaluate questions like this:

* What's the benefit to making the change? (More specific, the better)
* What are the costs to making the change? (Effort, backwards compatibility, etc.)
* Is there a way of achieving the same result with less cost?

Also, I'm not of the mindset that more dependencies == better. WP-CLI has few dependencies as it is, and it's already a pain point: https://github.com/wp-cli/wp-cli/pull/3304#issuecomment-240271105

Going forward into a future where feature development happens as separate WP-CLI packages, I think it becomes important to evaluate changes to WP-CLI from the perspective of: what does this add to the WP-CLI packages dependent on it?

Lastly, in cases where we can't add libraries as dependencies directly, we can always steal ideas from them :)

**Comment by schlessera** [comment]
There are three packages that would make immediate sense: the annotated commands, the standardized output formatter and the bootstrapper.

I personally would love to have a generalized bootstrapper that can deal with all sorts of environments/frameworks, where the individual frameworks just provide the information that is needed.

However, if WP-CLI really does keep the PHP 5.3 requirement, all of this is moot anyway. PHP versions progress faster now, and everyone should pretty much just drop PHP 5 support by now. This is done by some of the major libraries, so depending on external libraries is not an option anymore in this case.

**Comment by greg-1-anderson** [comment]
Consolidation works back to php 5.4 -- but 5.3 is a non-starter. I'd like to see WP-CLI use the output formatter, but it would have to accept php 5.4 as a minimum php version in order to do so.

The bootstrap component is conceptual; it is not in use in any project. There is less use for a generalized bootstrapper when every CLI works with just one framework, as WP-CLI and Drupal Console have always done. With Drush 9 moving in the same direction, I don't know if that component will ever be finished.

**Comment by danielbachhuber** [comment]
Ok.

WP-CLI's minimum PHP version will be increased with v2.0.0, which is looking like the end of 2017. We can re-evaluate the output formatter at that point. I'm not terribly interested in adopting Consolidation's annotated commands because it seems like they're functionally equivalent.

@greg-1-anderson Feel free to loop us in if Consolidation starts on any new projects that might be relevant.
