### ISSUE TITLE
Allow imports from REST endpoints

### ISSUE THREAD

**Issue by andrewbanchich** [wp-cli/wp-cli#3718]
For easy site migrations it would be great to just plug in the URL of a site we are moving and have WP-CLI import the data into the database of a new WordPress install.

Is this something that we can currently do? I couldn't find the option anywhere.

**Comment by ernilambar** [comment]
I dont think this is currently available, but this would be a great CLI package. It would be very handy for site migration.

**Comment by danielbachhuber** [comment]
> Is this something that we can currently do? I couldn't find the option anywhere.

It's not currently possible, no.

> I dont think this is currently available, but this would be a great CLI package.

Somewhat of a work in progress as https://github.com/wp-cli/restful. There are a variety of technical problems to solve, however.
