### ISSUE TITLE
The example of user delete command is wrong and it's not working

### ISSUE THREAD

**Issue by metodiew** [wp-cli/wp-cli#3719]
I've been working on a project where I have to delete almost all users and I've tried to run the example from, https://wp-cli.org/commands/user/delete/. In my case:
`$ wp user delete $(wp user list --role=contributor --format=ids) --reassign=2`
which should delete all contributors and assign them to user with ID 2. 
However, when I try with this command I got this error:
`Warning: Invalid user ID, email or login: 'the list of IDs here'`

I've replaced `format-ids` with `--field=ID` and the command is running successfully, without any issues. In the next few minutes Ill apply a patch with the fix.

**Comment by danielbachhuber** [comment]
@metodiew Planning to submit a pull request with your change?

**Comment by metodiew** [comment]
Ah, I thought I did submit the pull request, but I looks like I haven't sent it. Here is the PR https://github.com/wp-cli/wp-cli/pull/3722 :)
