### ISSUE TITLE
wp scaffold _s should validate the slug

### ISSUE THREAD

**Issue by rosswintle** [wp-cli/wp-cli#3723]
I just tried `wp scaffold _s` for the first time on a project that will be called 100 Stories.

My theme slug was `100stories` - this seemed reasonable at the time, but I repeatedly received:

```
Error: Couldn't create theme (received 500 response).
```

I checked out the code and saw that it was making a POST to underscores.me and I realised there's a simple API with an interface on the Underscores website. So I tried putting my options into the form there and got back:

```
Theme slug could not be used to generate valid function names. Please go back and try again.
```

From which I worked out that the slug should not start with a number.

Can we add a simple validation check to the `_s` function in `php/commands/scaffold.php` to check for this condition?

I might try and create a patch later on if I have time.

Thanks.

**Comment by danielbachhuber** [comment]
> Can we add a simple validation check to the `_s` function in `php/commands/scaffold.php` to check for this condition?

Sure! Let's use the exact regex that the `_s` website uses: https://github.com/Automattic/underscores.me/blob/c506caba271a287f719d5f7824e3e23272aeccdd/plugins/underscoresme-generator/underscoresme-generator.php#L99-L100

**Comment by rosswintle** [comment]
Added a simple check in pull request: https://github.com/wp-cli/wp-cli/pull/3724

Not sure if I can link the issue to the pull request - or is that something you can do?

Thanks
