### ISSUE TITLE
WP-CLI fails to connect when wp-config.php has database environment variables

### ISSUE THREAD

**Issue by bgeihsgt** [wp-cli/wp-cli#3729]
This is similar to https://github.com/wp-cli/wp-cli/issues/2365 which I don't think got properly resolved. 

I want my wp-config.php to be stateless so can deploy it to any environment (in this case, I'm deploying it to Docker and  AWS Elastic Beanstalk). So I define my DB config settings like this:

```
define('DB_NAME',     getenv("RDS_DB_NAME"));
define('DB_USER',     getenv("RDS_USERNAME"));
define('DB_PASSWORD', getenv("RDS_PASSWORD"));
define('DB_HOST',     getenv("RDS_HOSTNAME"));
```

This works great in multiple environments, but WP CLI doesn't pick up the settings properly. It looks like the culprit is these lines:

https://github.com/wp-cli/wp-cli/blob/v1.0.0/php/class-wp-cli.php#L1011-L1026

Passing in the new environment into `proc_open` will replace the parent environment, thus replacing any environment variables that exist when invoking the CLI. I'm curious, why does this need to pass a new environment? Couldn't we just pass NULL there to inherit the parent environment?

**Comment by bgeihsgt** [comment]
Forgot to mention I'm using `wp rewrite structure` to update permalink rules. It looks like https://github.com/wp-cli/wp-cli/issues/3640 is the exact issue I'm hitting.

I think the right solution here is to just pass NULL for the env parameter. That way it will inherit the environment of the parent PHP process. @danielbachhuber what do you think?

**Comment by danielbachhuber** [comment]
> I think the right solution here is to just pass NULL for the env parameter. That way it will inherit the environment of the parent PHP process. @danielbachhuber what do you think?

Oh, huh. Have you tested to verify the environment variables are actually passed through?

**Comment by bgeihsgt** [comment]
I haven't tested it yet, was going off of the docs here: http://php.net/manual/en/function.proc-open.php

Will test shortly.

**Comment by bgeihsgt** [comment]
What's the easiest way to make a change and test it locally? (sorry, I'm a PHP n00b)

**Comment by bgeihsgt** [comment]
For now going with installing it as a project and testing it that way

**Comment by bgeihsgt** [comment]
@danielbachhuber I tested it locally and verified it works. Please see PR #3730 above.

**Comment by danielbachhuber** [comment]
Interesting. Learn something new every day!
