### ISSUE TITLE
Improve `wp core language activate`

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#3731]
We need to set default timezone and date format.

There is a time lag from en_US version to localized version, so we can't run `wp core install --locale=ja` today.

Following works fine, but timezone and date format won't be set.

```
$ wp core install
$ wp core language install ja --activate
```

Default timezone and format is in `po/mo` files.

* https://translate.wordpress.org/projects/wp/dev/admin/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=40444&filters%5Btranslation_id%5D=1653450
* https://translate.wordpress.org/projects/wp/dev/admin/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=216367&filters%5Btranslation_id%5D=10294358

I will write a patch.

**Comment by miya0001** [comment]
Ah, `wp core install` was not right.
Try following today. 

```
$ wp core download --version=latest --locale=ja
```

Other languages have the same problem too.

```
wp core download --version=latest --locale=tr_TR
```

**Comment by danielbachhuber** [comment]
@miya0001 Could you describe the problems you ran into with your implementation?

**Comment by miya0001** [comment]
Ah, sorry for lack of explanation.

I found a problem that some countries have two or more time zone.
My solution doesn't work for those languages.
However almost all users will use `wp core download` and my solution doesn't solve this command.

So I am trying to solve this problem on `wp core download` and I am thinking we shouldn't add options that make use case difficult to understand.

Thanks!

**Comment by danielbachhuber** [comment]
Ok, sounds good.
