### ISSUE TITLE
search-replace does not skip guid by default, as documented

### ISSUE THREAD

**Issue by rosswintle** [wp-cli/wp-cli#3732]
I'm on a roll after raising and patching an issue. Sorry to bug you with more trivial stuff. Happy to fix this, but not sure where the error is.

This MAY be a documentation issue, or it may be a bug/error.

The documentation and code comments (is one generated from the other?) say that for `search-replace`: 

> ‘guid’ is skipped by default. 

But this does not seem to be the case.

Steps to reproduce:

Run: `wp search-replace --dry-run donotfindthis donotreplacewiththis`

Expected output:

List of tables and columns EXCLUDING `guid`

Actual output:

List of tables and columns INCLUDING `guid`

In `php/commands/search-replace.php` the setup only seems to do the following involving `--skip-columns`:

```
		$this->skip_columns = explode( ',', \WP_CLI\Utils\get_flag_value( $assoc_args, 'skip-columns' ) );
```

and

```
		// never mess with hashed passwords
		$this->skip_columns[] = 'user_pass';
```

So I can't see the code attempting to exclude `guid`

Interestingly, I note that the functional tests in `search-replace.feature` support the CODE, not the DOCS:

```
    When I run `wp search-replace foo bar`
    Then STDOUT should contain:
      """
      guid
      """

    When I run `wp search-replace foo bar --skip-columns=guid`
    Then STDOUT should not contain:
      """
      guid
      """
```

Do you think `guid` should be excluded by default? Or should we leave it and fix the docs?

**Comment by danielbachhuber** [comment]
> Sorry to bug you with more trivial stuff.

Not at all! Even trivial bugs are bugs :)

> This MAY be a documentation issue, or it may be a bug/error.

Let's call this a documentation issue. It looks like I mistakenly added the mention in 5f7cd8793c567c3339014ae9d7a2005746c76700

To fix the documentation issue, let's simply remove the statement that the command skips `guid` by default.

**Comment by mrwweb** [comment]
Unless the website is behind the repo, this is still an issue. I just came here to report the same thing.

**Comment by danielbachhuber** [comment]
> Unless the website is behind the repo, this is still an issue.

It is. The website is typically updated on every major release. It's currently in the process of being migrated to WordPress.org.
