### ISSUE TITLE
Missing pages when installing Wordpress + BuddyPress using WP CLI

### ISSUE THREAD

**Issue by fbnlsr** [wp-cli/wp-cli#3736]
For a project I'm currently working on, I need to install Wordpress and BuddyPress using WP CLI inside a bash script.

When the installation and activation of the plugin is done, BuddyPress sometimes lacks pages such as "register", "members", "activity" and so on.

I've noticed that if the pages are not created (I can't see them in the database) and log into the admin, they seem to be automatically generated. The error seems to be random though, as sometimes everything goes well and the pages are created and BuddyPress works fine.

It might be a problem on the BuddyPress side, but since this error is random and I sometimes get the pages BuddyPress needs, I'm wondering if WP CLI has something to do with this issue.

Steps to reproduce:

- Install Wordpress using WP CLI
- Install and activate BuddyPress using WP CLI
- Check to see if pages are missing

**Comment by danielbachhuber** [comment]
Hi @fbnlsr,

This issue tracker is for bugs specific to WP-CLI. This issue sounds like it's specific to BuddyPress or your environment.
