### ISSUE TITLE
conflict with plugin code

### ISSUE THREAD

**Issue by pmirek** [wp-cli/wp-cli#3737]
I'm not sure if this is a general bug, or just conflict for a single plugin. This occurs when calling options like:
* core check-update
* plugin status

> PHP Fatal error:  Call to a member function javascriptVariables() on null in /apps/wordpress/wp-content/plugins/search-in-place/codepeople_search_in_place.php on line 35

Conflicting code from plugin:
**search-in-place/php/searchinplace.clss.php**
```
        public function javascriptVariables(){
                return $this->javascriptVariables;
        } // End javascritpVariables
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @pmirek.

This is a bug with the plugin. Specifically, the `$codepeople_search_in_place_obj` variable needs to be explicitly globalized before instantiation:

```
$ svn diff
Index: codepeople_search_in_place.php
===================================================================
--- codepeople_search_in_place.php	(revision 1575978)
+++ codepeople_search_in_place.php	(working copy)
@@ -36,6 +36,7 @@
 		}
 	}

+global $codepeople_search_in_place_obj;
 $codepeople_search_in_place_obj = new CodePeopleSearchInPlace();
 $codepeople_search_in_place_obj->init();

@@ -53,4 +54,4 @@
 add_action('wp_ajax_search_in_place', array(&$codepeople_search_in_place_obj, 'populate'));
 add_action('pre_get_posts', array(&$codepeople_search_in_place_obj, 'modifySearch'));
 add_filter('posts_request', array(&$codepeople_search_in_place_obj, 'modifySearchQuery'), 99);
```

See #2089 for some of the history.

In the interim, you can use `wp --skip-plugins` to skip the loading of plugins with WP-CLI.

**Comment by danielbachhuber** [comment]
This will be fixed in the next version of the plugin https://wordpress.org/support/topic/explicitly-globalize-codepeople_search_in_place_obj-variable/
