### ISSUE TITLE
Db export to be smart about what it exports

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#3738]
I've noticed that wp db export file.sql exports all the tables in the db.
I was expecting it to export on current site's tables. It just makes more sense to me.
It has read the wp-config why not check the db table prefix come up with the list by itself?

In context of multisite to export tables that belong to that network.

Yes, I know I can list tables to export but that will require extra code to figure out the tables and if I have that info I probably won't need wpcli for the db export.

**Comment by danielbachhuber** [comment]
> I've noticed that wp db export file.sql exports all the tables in the db.
> I was expecting it to export on current site's tables. It just makes more sense to me.
> It has read the wp-config why not check the db table prefix come up with the list by itself?

I appreciate the input. At this point, we're not going to change the behavior because it would be a breaking change.

> Yes, I know I can list tables to export but that will require extra code to figure out the tables and if I have that info I probably won't need wpcli for the db export.

It doesn't take any code, actually. [From the docs](http://wp-cli.org/commands/db/export/):

```
# Export all tables matching prefix
$ wp db export --tables=$(wp db tables --all-tables-with-prefix --format=csv)
Success: Exported to 'wordpress_dbase.sql'.
```
