### ISSUE TITLE
Support field filters for `wp site option list`

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#3741]
Examples:

* `wp site option list --site_id=1`
* `wp site option list --meta_key=foo`
* `wp site option list --meta_value=bar`

~Just like `wp option list` does.~ Misread the docs, it's more like `wp site list`.

Happy to work on this if it's a good idea.

**Comment by danielbachhuber** [comment]
I'm not opposed, but I don't see the need either. Could you describe the use case in more detail?

If we add them to `wp site option list`, we should add them to `wp option list` too.

**Comment by ocean90** [comment]
I had to compare the options of one network between stage and prod. My idea was to filter the options by site_id, sort them and use `diff`. Similar to http://wpkrauts.com/2015/compare-user-roles-in-a-multisite-with-wp-cli/.

**Comment by danielbachhuber** [comment]
Makes sense. Let's go with adding `wp site option list --site_id=<id>` for now.
