### ISSUE TITLE
Uncaught Error: Class 'WP_CLI' not found

### ISSUE THREAD

**Issue by j-baconator** [wp-cli/wp-cli#3746]
I am having issues when adding a custom cli command into an existing wordpress theme. My `wp --info` is the following:
`PHP binary:	/usr/local/Cellar/php70/7.0.13_6/bin/php
PHP version:	7.0.13
php.ini used:	/usr/local/etc/php/7.0/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	/Users/julie/my-site/my-site/wp-cli.yml
WP-CLI version:	1.0.0
`

When I register the example command from the commands cookbook using  `WP_CLI::add_command( 'example', 'Example_Command' );` within my theme, I get the error:
`Uncaught Error: Class 'WP_CLI' not found in /Users/julie/my-site/public/wp-content/themes/plugin-name/lib/theme-wp-cli-commands.php:39`

Any insight on why it is not finding WP_CLI despite the results from `wp --info` ?

**Comment by danielbachhuber** [comment]
Hi @j-baconator,

Github issues are no longer an appropriate venue for support. Please review http://wp-cli.org/#support
