### ISSUE TITLE
--blog_id instead of --url

### ISSUE THREAD

**Issue by rumoru** [wp-cli/wp-cli#3749]
Hi, 
I would like to suggest a simple change or additional feature:

use --blog_id=N as a global argument to specify which blog run command against.
Using --url= takes time to find out, type or copy/paste that url. 

By the way, really really nice tool. 
Thank you

rumo

**Comment by danielbachhuber** [comment]
Hi @rumoru,

Thanks for the suggestion. This idea was explored originally in #854, and closed for reasons described in the thread.

As an alternative, you can use a nested bash command to achieve the same result:

```
wp --url=$(wp site url 2) option get blogname
```

**Comment by rumoru** [comment]
Thanks for reply.  Sorry I haven't seen this issue.
