### ISSUE TITLE
[Feature Request ] List subcommand

### ISSUE THREAD

**Issue by jareis** [wp-cli/wp-cli#3750]
Is not always useful to use the help subcommand to get information from a specific subcommand. Sometimes we just need to check a command list. The "list" command could be used to list all the commands and arguments from a parent command.

usage example
```
$wp cron list
Usage:
  wp cron [COMMAND]
Subcommands:
  event            Manage WP-Cron events.
  schedule      Manage WP-Cron schedules.
  test              Test the WP Cron spawning system and report back its status.
$
```

**Comment by danielbachhuber** [comment]
> Is not always useful to use the help subcommand to get information from a specific subcommand.

Why? Could you explain further?

> The "list" command could be used to list all the commands and arguments from a parent command.

You can already achieve the same by running the parent command:

```
local ➜  wordpress-develop git:(master) wp cron
usage: wp cron event <command>
   or: wp cron schedule <command>
   or: wp cron test

See 'wp help cron <command>' for more information on a specific command.
```

Can you describe how this would be different?

**Comment by jareis** [comment]
The main idea behind the request is the same as the difference between the man pages and the -h argument for a *nix terminal application. If you do `man wget` on a terminal you will get the full manual page for wget, but you can also do `wget -h` just to get commands help. 

When you issue the help command it opens up a manual page, this is helpful if you want more information about a command. But sometimes you just need to take a quick view on the subcommand list and the help command is not very friendly for that.

**Comment by jareis** [comment]
ps: i notice now that the proposed list subcommand may be in conflict with some commands, like:
```
$ wp plugin list
```
maybe add "-h" for consistence with terminal commands?
```
$ wp plugin -h
```

**Comment by jareis** [comment]
just ignore only know i have noticed what you said above... i wasn't really easy to perceive a 1st.

**Comment by danielbachhuber** [comment]
No worries! I think you've brought up a general observation that the design of the man pages could use some love, which I agree with.
