### ISSUE TITLE
is-installed ignores --quiet

### ISSUE THREAD

**Issue by niladam** [wp-cli/wp-cli#3752]
Hello,

I'm working on a script that tries to make sure that WordPress is installed in the current directory and i was thinking about using the *is-installed* command. I know the command should return an exit code and i can use that. However, i'd like the check to be quiet. Here's what happens.

I go into an empty directory (no WordPress installed in it, this is however a *subfolder* of a WordPress install.

```
[root@zeus geoip]# ll
total 876K
drwxr-xr-x  2 madalin madalin   22 Jan 20 00:09 ./
drwxr-xr-x 11 madalin madalin 4.0K Jan 19 23:51 ../
-rw-r--r--  1 madalin madalin 870K Jun 19  2016 GeoIP.dat
```
`[root@zeus geoip]# wp core is-installed --path=$PWD`
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

I expected to see some sort of message, and turned to the `--quiet` option hoping to actually just get an exit code, as stated in the docs.

`[root@zeus geoip]# wp core is-installed --path=$PWD --quiet`
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

Here, i thought that `$PWD` wasn't returning it's correct value, and moved on, testing for that and manually providing the path.

```
[root@zeus geoip]# echo $PWD
/home/madalin/www/geoip
```
`[root@zeus geoip]# wp core is-installed --path=/home/madalin/www/geoip`
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

Good, so the path works, and yes -- it's not a WordPress install. Let's try the `--quiet` option.

`[root@zeus geoip]# wp core is-installed --path=/home/madalin/www/geoip --quiet`
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

I was expecting to see nothing here, just have a return code. The return code does exist and apparently it's the correct one. According to the [docs](http://wp-cli.org/commands/core/is-installed/): 

`# Check whether WordPress is installed; exit status 0 if installed, otherwise 1`

```
[root@zeus geoip]# echo $?
1
[root@zeus geoip]#
```

**Comment by danielbachhuber** [comment]
Good question.

`wp core is-installed` is meant more specifically for whether WordPress' database tables are installed, not for testing the presence of WordPress files. The latter task is a bit more fraught with challenges, because WP-CLI will look upward if it doesn't find the `wp-config.php` in the current directory.

As far `--quiet` goes, the flag has historically only meant suppressing `STDOUT`, not `STDERR`.

> I'm working on a script that tries to make sure that WordPress is installed in the current directory and i was thinking about using the _is-installed_ command. I know the command should return an exit code and i can use that. However, i'd like the check to be quiet.

Could you share more detail on the script, and why you want `STDERR` to be quiet too?

**Comment by niladam** [comment]
Hi @danielbachhuber,

First of all sorry for my ignorance. I forgot to provide you with the details about WP-CLI (even though now i'm seeing they were of no help, i am using 1.0.0);

Second of all, the script i'm trying to build is a personal script that tries to automatically generate a backup of the current WordPress dir. The way it works is it does some checks first like the existence of *wp-cli*, and the fact that WordPress is actually installed.

Right now, because of this issue -- i'm using a sort of prone to error solution:

```
	if [ ! -f "$WPEB_CWD/wp-includes/version.php" ]; then
	    # nope, not WordPress, let's abort..
	    echo "This script needs to be executed in the main WordPress folder that you're trying to backup. Aborting..."
	    exit 1
	fi
```

Which obviously cannot be relied upon. So, that's why i wanted to use the is installed check. I was thinking the checks are more thorough and i can actually rely upon that..

**Comment by danielbachhuber** [comment]
> So, that's why i wanted to use the is installed check. I was thinking the checks are more thorough and i can actually rely upon that..

But why does it matter whether `wp core is-installed` writes anything to `STDERR`? Why not just check the exit code?

> Second of all, the script i'm trying to build is a personal script that tries to automatically generate a backup of the current WordPress dir. The way it works is it does some checks first like the existence of wp-cli, and the fact that WordPress is actually installed.

As a heads up, you may be interested in https://github.com/wp-cli/ideas/issues/5

**Comment by niladam** [comment]
Yeah, i could use use `&>/dev/null` -- but i thought that the `--quiet` flag should do it. My bad.

That's a really good idea, however for this particular case i've decided to build my own shell script as i couldn't find anything really simple and effective. For now it's just a pretty simple bash script called [wpeb](https://github.com/niladam/wpeb) that i intend to further maintain.

Thanks for your time.

**Comment by danielbachhuber** [comment]
> Yeah, i could use use `&>/dev/null` -- but i thought that the `--quiet` flag should do it. My bad.

Oh, no worries. Just wanted to make sure you were aware you could check the exit code explicitly: https://github.com/niladam/wpeb/pull/1

> That's a really good idea, however for this particular case i've decided to build my own shell script as i couldn't find anything really simple and effective. For now it's just a pretty simple bash script called wpeb that i intend to further maintain.

Makes sense. Would you be interested in working on the WP-CLI version when the time comes?

**Comment by niladam** [comment]
Of course i'd be interested. But i'm not really sure about my code quality (PSR, tests and so on), so i might not be the best for this. But i'd love to give a helping hand! Anytime!:)

**Comment by danielbachhuber** [comment]
> As far `--quiet` goes, the flag has historically only meant suppressing `STDOUT`, not `STDERR`

Closing this issue as wontfix for now:

* It doesn't make sense to change the behavior of `--quiet` to also suppress errors at this point.
* It's not worth the effort to suppress `STDERR` messages exclusively for `wp core is-installed`.

**Comment by JollyWizard** [comment]
I feel like the list of assumptions for this command's usage, as discussed in this thread, should be clearly indicated on the wiki page for the command.

https://developer.wordpress.org/cli/commands/core/is-installed/

Nothing on that page would indicate that only the database is tested, or that "no output" is a highly qualified statement. With more and more CLI casuals thanks to docker, subtleties on the stdout and stderr system are going to be less common knowledge. Even with some background, it was not clear to me that was what was happening here.  Since Wordpress will be a gateway for many casual developers into these topics, I think that it is reasonable to extend the benefit of the doubt on this issue.
