### ISSUE TITLE
Commands for media wp-contents/uploads folder cleanup

### ISSUE THREAD

**Issue by virtuman** [wp-cli/wp-cli#3756]
We run a pretty large woocommerce store that integrates with our backend listing automation and order management tool. Daily - our system will re-evaluate listed products and prices and adjust them according to the business rules. This results in very many listings being re-created on a daily basis and with a few thousands of listings - this continuously creates more and more of the media images for each newly re-listed products.

Is there, or should there be a command that analyzes any uploaded media image (in wp-contents/uploads folder) to identify such images and log information about unused images into some sort of actionable table or log file?
I purchased pretty much every plugin out there that claims to do something similar, but all of these plugins are web based and with tens and hundreds of thousands of images hosted on NFS (where NFS is known to be a super slow storage mechanism) - all of those plugins are useless because they simply timeout and don't ever complete a single operation.

I would suggest commands that would identify some of the basic plugins and standard functionalities of wordpress and consider all of them during the scan. 
First few things that many of us may have an immediate need for are:
- scan
- PLUGIN: woocommerce

Latest plugins that I tried to no avail are:
https://wordpress.org/plugins/media-cleaner/ - Media Cleaner - both Free and PRO version
https://wordpress.org/plugins/dnui-delete-not-used-image-wordpress/ - DNUI - both Free and PRO version

I'm not a very avid wp-cli user and not very familiar with command naming standards in wp-cli, but If commands for this do not yet exist, then I would suggest something similar to this:

```
- wp media cleanup [options] - this would identify and do a dry-run command only - or possibly log to DB table or 
options:
   --prune (or delete)  - follow the execution of delete of files based on previously identified files 
   --list                         - dump list of all media to be deleted
   --ignore=[(glob*)]   - list of locations to ignore
   --out=/path/to/file   - save output of activity to file (default behavior to APPEND to file)
   --skip-excerpt         - do not check post excerpt for included media 
   --skip-content         - do not check post content for included media 
   --skip-shortcodes   - do not check included media with shortcodes
   --yes                         - without "yes" and "--prune" enabled - it should trigger a disclaimer with prompt that - "images are going to be deleted from disk and that this operation is irreversable"
```

**Comment by danielbachhuber** [comment]
Hi @virtuman,

Thanks for the suggestions! We have a new repository for ideas, https://github.com/wp-cli/ideas. Can you post your issue there?

**Comment by stefanomonteiro** [comment]
Hi. Has this idea gone forward? Thanks
