### ISSUE TITLE
`wp db export` exports to insecure location by default

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#3759]
If I run `wp db export` without any parameters, it exports to `{dbname}.sql` inside the current directory, which is usually accessible to the outside world via the server.

So, if I leave that file around, anyone can download it by accessing http://example.com/dbname.sql

This has always bothered me, but I never got around to opening an issue for it.

Possible solutions:

a) make `<file>` a required parameter
b) add a random string to the dump file, so that it looks something like  `{dbname}-{random}.sql`

**Comment by danielbachhuber** [comment]
I like option b
