### ISSUE TITLE
Command line result for `option update` different than `WP_CLI::runcommand('option update...')`

### ISSUE THREAD

**Issue by Squybee** [wp-cli/wp-cli#3760]
Hello,

It seems that running the same command both in the console and using `WP_CLI::runcommand()` doesn't yield the same results.

If I run  
`wp option update my_custom_option  --autoload='no' <path/to/option/value.json`
I get 

> Success: Updated 'my_custom_option' option.

But if I define my own command, and inside it launch the former command as follows:  

```php
$options = [
    'return'     => 'all',
    'launch'     => false,
    'exit_error' => false,
];
var_dump(WP_CLI::runcommand("option update my_custom_option  --autoload='no' < path/to/option/value.json", $options);
```
I get the following result: 

> object(stdClass)#7060 (3) {
>   ["stdout"]=>
>   string(0) ""
>   ["stderr"]=>
>   string(154) "Error: Too many positional arguments: path/to/option/value.json"
>   ["return_code"]=>
>   int(1)
> }

I thought this had something to do with `--autoload` but apparently not as it yields the same output without the option. 
However running the same command with a hardcoded value yields the expected result on both sides.

Running on WP 4.7, got the wp-cli.phar last Friday by CURL.

**Comment by danielbachhuber** [comment]
I see one immediate issue: `< path/to/option/value.json` is a bash-ism to transform a file's contents to `STDIN`. It definitely won't work if you're running `option update my_custom_option  --autoload='no'` within the same process, and I don't believe it will work when launching a child process.

**Comment by Squybee** [comment]
So what should I do? `file_get_content()` my file and force feed it directly in the value, giving it a `--format=json` option?

**Comment by danielbachhuber** [comment]
Sure — whatever approach you work out.

**Comment by Squybee** [comment]
I ended up using `update_option` in the end, because `WP_CLI::runcommand()` isn't versatile enough to allow for complex JSON values. I believe it is because it uses `Utils\parse_str_to_argv()` to parse its arguments into an array, thus over-analyzing the value. I think it shouldn't do that in case `--format=json` is passed.
