### ISSUE TITLE
Incorrect success message when a plugin cannot be installed due to write permissions

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#3761]
Steps to reproduce:

1. Remove write access to the plugins directory for the current CLI user.
2. Run `wp plugin install [plugin]` with a plugin that's not yet installed.

Observe that WP-CLI outputs `Warning: Could not create directory. [directory]`, immediately followed by an success message stating `Installed 1 of 1 plugins`, yet the plugin was not installed.

**Comment by danielbachhuber** [comment]
Thar be a bug: bd957e8e
