### ISSUE TITLE
"Installed 1 of 1 plugins" is not an optimal message

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#3762]
The `Installed x of x plugins` terminology works well when x > 1, but it's overly verbose when installing just one plugin.

Is there a reason the old `Plugin installed` message shouldn't/couldn't be used when installing one plugin?

**Comment by danielbachhuber** [comment]
Because `wp plugin install` can accept one or more plugins, I prefer the verbosity as explicit confirmation of the action you've performed.

Also, consistent messaging simplifies parsing for third-party systems.

**Comment by andreiglingeanu** [comment]
> Also, consistent messaging simplifies parsing for third-party systems.

This.

I stumped so many times upon that thing -- when the software tries to be way smarter than it needs to be.
