### ISSUE TITLE
cs_CZ translation is outdated

### ISSUE THREAD

**Issue by grumpa** [wp-cli/wp-cli#3766]
`wp core language install cs_CZ` downloads translation almost one year old.
I'd like to help with updating or translating but I don't know how.
Thank you
Viktor

**Comment by ernilambar** [comment]
Yes. Latest version should have been downloaded.
Currently it is downloading,
```
Downloading translation from https://downloads.wordpress.org/translation/core/4.4.2/cs_CZ.zip...
```

**Comment by grumpa** [comment]
So I will contact Wordpress Czech translation team. Thanks.
