### ISSUE TITLE
Quick Question - WP_CLI::Error()

### ISSUE THREAD

**Issue by amiga-500** [wp-cli/wp-cli#3767]
I am adding into W3 Total Cache a prime feature for WP-CLI.  However, in the w3tc code i see these strange WP_CLI::error lines:

```php
catch ( Exceptions $e ) 
{
    WP_CLI::error( __( 'Error Occurred ', 'w3-total-cache' ), $e->getCombinedMessage() );
    WP_CLI::error( __( 'Error %s', 'w3-total-cache' ), $e );
}
```
What is confusing to me is on your site the syntax for WP_CLI::error is:

WP_CLI::error( $message= **<string|WP_ERROR>**, $exit = **<boolean|integer>** )

So if that is the official syntax then wouldnt the two WP_CLI::error lines above in w3tc be incorrect and will not display correctly?  I just want to get the official word to ensure i am not going insane.

Thanks for the clarification.

**Comment by danielbachhuber** [comment]
Correct, this syntax is incorrect. It looks like each line is missing a call to `sprintf()`

```
WP_CLI::error( sprintf( __( 'Error Occurred ', 'w3-total-cache' ), $e->getCombinedMessage() ) );
WP_CLI::error( sprintf( __( 'Error %s', 'w3-total-cache' ), $e ) );
```

Also, `WP_CLI::error()` doesn't natively handle Exception objects, so you'll need to make sure you're passing the correct data.

**Comment by amiga-500** [comment]
Much appreciated...now i know i am not crazy.
