### ISSUE TITLE
Bug in --help display?

### ISSUE THREAD

**Issue by amiga-500** [wp-cli/wp-cli#3773]
I think i found a visual bug.  When providing a function's comment description, which is used for the _**--help**_ feature i noticed that the first parameter will not show the ":" that precedes its description, and the following parameters will then be indented to the right, below the 1st parameter, but will show the ":" that precede their descriptions.  For example, compare the  `[<stop>]` and `[--batch=<size>]` in the comment code and the CLI result.

Here is the comment code:
```php
    /**
     * Prime the page cache (cache preloader)
     *
     * ## OPTIONS
     *
     * [<stop>]
     * : Stop the active page cache priming session.
     *
     * [--batch=<size>]
     * : Max number of pages to create per batch. If not set, the value given in
     *   W3TC's Page Cache > Pages per Interval field is used. If size is 0 then
     *   all pages within the sitemap will be created/cached without the use of a
     *   batch and without waiting.
```
And here is the result in CLI

![prim](https://cloud.githubusercontent.com/assets/5191497/22265607/bff485a6-e24a-11e6-98b5-60282af40386.gif)

**Comment by trepmal** [comment]
Can I ask what version of wp-cli you're using? Help info looks okay on my end (WP-CLI 1.1.0-alpha)

![screen shot 2017-01-24 at 1 03 25 pm](https://cloud.githubusercontent.com/assets/251183/22266658/bb8d3c3e-e235-11e6-8cac-7f1d3cc1b717.png)

**Comment by amiga-500** [comment]
Seems i am using **WP-CLI 1.0.0**

The **`wp cli update`** says i have the latest.

So i have to assume your **WP-CLI 1.1.0-alpha** is not out yet but figure a `wp cli update --nightly` will bump my version up to that, fixing my problem.  I'll give it a try.

Thanks

**Comment by amiga-500** [comment]
Sadly...after updating mine to the alpha version:   **WP-CLI 1.1.0-alpha-80ddf39** i am still seeing the same problem:

![newprim](https://cloud.githubusercontent.com/assets/5191497/22267173/c85d8e6c-e250-11e6-8880-581d542d6935.png)


Once again, take note of the indentation AND also take note how there is no ":" before the description: "_Stop the active page cache priming session._"

**Comment by danielbachhuber** [comment]
@amiga-500 This seems to be specific to your PHP configuration. GitHub issues aren't meant for general support, see http://wp-cli.org/#support

**Comment by amiga-500** [comment]
Hi @danielbachhuber  i figured it out finally...it seems when a  php file saves in PC-style Line Ending instead of UNIX then WP-CLI collapses and is unable to parse the help text correctly (as seen in the pix above).  When i re-saved the text file in UNIX style WP-CLI then was able to work correctly

Do you think that including files saved as PC style could be supported too?  I figure you'd simply be looking for \r\n and not just \n ?

**Comment by danielbachhuber** [comment]
> Do you think that including files saved as PC style could be supported too? I figure you'd simply be looking for \r\n and not just \n ?

Oh. I'd guess this to be the culprit: https://github.com/wp-cli/wp-cli/blob/master/php/commands/help.php#L66-L67

As a rule of thumb, we typically key off the `PHP_EOL` constant for cross-platform compatibility. Can you see if there's some improved regex that would work for your use case?

**Comment by danielbachhuber** [comment]
> As a rule of thumb, we typically key off the `PHP_EOL` constant for cross-platform compatibility.

`PHP_EOL` wouldn't help us in this case, because it would be the "correct" end of line character, not the incorrect one we need to replace.

Closing as wontfix. Not worth spending the effort for the number of users impacted.
