### ISSUE TITLE
PHPDoc Annotation Question -- ## EXAMPLES Section

### ISSUE THREAD

**Issue by amiga-500** [wp-cli/wp-cli#3774]
The WP-CLI Documentation standards say the following:

> _Each example should have 3 parts._
> 
> * _Description_
>         - _Must start with # and a space._
>         - _Sentence should start with capital letter_
>         - _Comment must end in full-stops, exclamation marks, or question marks._
>         _`Eg: # Create database.`_
> * _Command_
>         - _Must start with $ and a space. Eg: `$ wp db create`_

But what if one's description is longer than 1 sentence and spans multiple lines because the example provided does something that requires an extensive explanation?  Is it ok to use multiple "#" for the example or must we adhere to the single "#" per example description?

**Comment by danielbachhuber** [comment]
It's fine to use multiple `#`.
