### ISSUE TITLE
Search Replace report feature request

### ISSUE THREAD

**Issue by inderpreet99** [wp-cli/wp-cli#3777]
I wanted to share my some thoughts on a feature request about Search Replace:

There should be a way to see the changes that a search-replace would make. This would be especially valuable to use with `--regex` flag, where your changes can get out of control if you don't see what's going on.

The current export feature is a bit underpowered because it generates a huge SQL file for the site. There's no easy way to see what exactly is changing.

I think we need a report feature that generates a from/to report for each table (that's changing). I would suggest using something like WP's built-in [Text Diff](http://pear.php.net/manual/en/package.text.text-diff.usage-examples.shell.php) or [PHP-diff](https://github.com/chrisboulton/php-diff) for a diff column.

There are lots of false-positives. For example, plugins that have had their PHP classes change (new properties). The unserialize will add with the newer properties from the PHP class. It will be "incorrectly" reported as a replacement. This is probably unavoidable since this has to happen at some point. However, number 1 (above) could alleviate the confusion from this.

**Comment by danielbachhuber** [comment]
> There should be a way to see the changes that a search-replace would make.

Interesting idea. We have a `--dry-run` flag right now but that will only show you a summary of the changes, not the full set.

> I think we need a report feature that generates a from/to report for each table (that's changing). I would suggest using something like WP's built-in Text Diff or PHP-diff for a diff column.

I'm amenable to this suggestion, although the user experience would be a challenging problem to solve (e.g. when there are 1000+ potential changes to display).

Out of curiosity, have you seen https://github.com/runcommand/db-ack ?

**Comment by inderpreet99** [comment]
The summary is not sufficient. It raises eyebrows for falsepositives (rare case though). I'm always wary of what it is going to replace before I execute the replace.

The idea is coming from in-house BU search-replace script that does diffs using php-diff and outputs them into CSV files. It lacks regex searching. We're in the mode to adopt wp-cli more in the future, hence the feature request.

I hadn't seen db-ack before. That's pretty cool. I'll add it to my toolbox. db ack's output of found search results is pretty neat. That's what I would expect from search-replace:
* the relevant rows that are about to be changed (like db ack)
* what they will end up being after the replacement

If the output is too much to handle, it could be a verbosity option.

**Comment by danielbachhuber** [comment]
Makes sense. We can let this idea soak for a bit to see if anyone comes up with a proposed implementation.

**Comment by jonathanbossenger** [comment]
I'm just spitballing here, but would a combination of --dry-run and --export work here? --dry-export=file or something? That way you could expand the details of the dry run and export that to a file, for the user to review before running search-replace properly.

**Comment by danielbachhuber** [comment]
Hey @inderpreet99,

Just wanted to let you know I've moved your issue to the new repo for `wp search-replace`: https://github.com/wp-cli/search-replace-command/issues/1

We're in the process of splitting out each command to its own project repo: https://github.com/wp-cli/wp-cli/issues/3728
