### ISSUE TITLE
Search Replace regex docs

### ISSUE THREAD

**Issue by inderpreet99** [wp-cli/wp-cli#3778]
The `--regex` parameter needs an example. Or, some documentation to let users know the regex parameter does not expect delimiters (`/`) to be wrapped around. Due to the false-positives, it gets tricky knowing what's going on.

To further add to the confusion about regex flags, `--regex-flags` is not appearing [in the commands docs](http://wp-cli.org/commands/search-replace/).

**Comment by danielbachhuber** [comment]
> The `--regex` parameter needs an example. Or, some documentation to let users know the regex parameter does not expect delimiters (`/`) to be wrapped around.

Good suggestion. Want to submit a pull request?

> To further add to the confusion about regex flags, `--regex-flags` is not appearing in the commands docs.

Command docs are rebuilt on every release. `--regex-flags` was introduced in v1.1.0 (#3634), which is scheduled to be released next week.
