### ISSUE TITLE
List installed languages for Themes and Plugins

### ISSUE THREAD

**Issue by grappler** [wp-cli/wp-cli#3782]
> We're skipping support for plugins / themes this time around. When core supports plugins / themes in a more substantial way, we'll likely move wp core language * to a top-level wp language command.

By @danielbachhuber in https://github.com/wp-cli/wp-cli/pull/1382#issuecomment-54776469

We use WP-CLI to install and update translations which works great. The command also installs the theme and plugin translations.

I wanted to see which translations were installed for which plugins. This would be a great extension of the feature.

**Comment by danielbachhuber** [comment]
> I wanted to see which translations were installed for which plugins. This would be a great extension of the feature.

I'm onboard with exploring how this would be done.

**Comment by ocean90** [comment]
Isn't that what `wp core language list` does? 🤔

**Comment by ocean90** [comment]
Ah, there's only `Core_Language_Command` which sets [$obj_type]( https://github.com/wp-cli/wp-cli/blob/cd4d6e27005db5415a4ac3da68f883e3d65ccc95/php/commands/core-language.php#L28). [`CommandWithTranslation::get_installed_languages()`](https://github.com/wp-cli/wp-cli/blob/071454fb1dcbe2a779707b2c5f5a5b2d273991fe/php/WP_CLI/CommandWithTranslation.php#L350) would support plugins and themes too.

**Comment by danielbachhuber** [comment]
After `wp core language` is split out to `wp language core` in #3728, we should add `wp language (plugin|theme)` for plugin and theme language management.

**Comment by schlessera** [comment]
Apparently, when you run `wp language core`, WP takes care of updating plugins and themes language files automatically now.

We'd probably need to set this filter: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-language-pack-upgrader.php#L74-L82

I just think that WP-CLI should be very explicit about what it does, and what it doesn't. It is okay for WP to hook into an admin backend button click and do some magic. But I don't think that WP-CLI should do that sort of magic as well.

**Comment by danielbachhuber** [comment]
> I just think that WP-CLI should be very explicit about what it does, and what it doesn't. It is okay for WP to hook into an admin backend button click and do some magic. But I don't think that WP-CLI should do that sort of magic as well.

I agree with this sentiment. Updating language packs for themes and plugins should be distinct from updating core's language packs.

**Comment by gitlost** [comment]
Was thinking of giving this a bash. I'll close the issue here soon and re-open it in `language-command`...

**Comment by gitlost** [comment]
Okay I kept getting distracted on this and didn't follow through. It'd be nice to have for 1.5.0 if someone wants to give it a go and if I do get a run at it I'll bags it again...

**Comment by swissspidy** [comment]
@gitlost I just created a branch for this to work on: https://github.com/wp-cli/language-command/tree/plugin-theme-command

`wp language plugin list <plugin...>` already works. I'll try to continue with the rest as well.

**Comment by gitlost** [comment]
Closing this in favour of https://github.com/wp-cli/language-command/issues/24
