### ISSUE TITLE
Error `wp core verify-checksums` on minor update

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#3783]
I got an error like following on `wp core verify-checksums` on my some sites.
Some Japanese people have the same problem too.
Is this a specification on minor upgrade?

```
$ wp core update
$ wp core verify-checksums 
Warning: File doesn't verify against checksum: wp-config-sample.php
Error: WordPress install doesn't verify against checksums.
```

**Comment by ShinichiNishikawa** [comment]
I get the same warning.

Japanese WordPress package has a different wp-config-sample.php, which is a translated version of the original one. After overwriting the file to the original one, I don't get the error.

**Comment by danielbachhuber** [comment]
> Japanese WordPress package has a different wp-config-sample.php, which is a translated version of the original one.

This explanation of the issue makes sense. We'll have to consider our options on what we can do.

**Comment by miya0001** [comment]
The cause of the problem of `wp core download --locale=xxx` is probably same.

**Comment by miya0001** [comment]
Do we add an option `--skip=wp-config-sample.php` to `wp core verify-checksums` for now?

**Comment by danielbachhuber** [comment]
> **Decisions, not Options**
> When making decisions these are the users we consider first. A great example of this consideration is software options. Every time you give a user an option, you are asking them to make a decision. When a user doesn’t care or understand the option this ultimately leads to frustration. As developers we sometimes feel that providing options for everything is a good thing, you can never have too many choices, right? Ultimately these choices end up being technical ones, choices that the average end user has no interest in. It’s our duty as developers to make smart design decisions and avoid putting the weight of technical choices on our end users.

**Comment by danielbachhuber** [comment]
I'd suggest WP-CLI should still display the warning for localized packages, but not consider it a fatal warning.

**Comment by ocean90** [comment]
Localized packages have their own checksums. Example: https://api.wordpress.org/core/checksums/1.0/?version=4.7.2&locale=ja

This sounds like either `wp core update` had loaded the en_US version and checked against the checksum of the localized packages or the other way around. (Or something else. 🙂)

**Comment by miya0001** [comment]
@ocean90 

There is a time lag before the localized package is released, and the API doesn't work.
And `wp core download --locale=xxx` doesn't work for same reason.

I am trying to fix it, but I can't find the solution. Do you have any idea?

**Comment by danielbachhuber** [comment]
> There is a time lag before the localized package is released, and the API doesn't work.

@miya0001 If the API doesn't work, shouldn't you see this error?

```
$checksums = self::get_core_checksums( $wp_version,
			! empty( $wp_local_package ) ? $wp_local_package : 'en_US' );

if ( ! is_array( $checksums ) ) {
	WP_CLI::error( "Couldn't get checksums from WordPress.org." );
}
```

Can you write a Behat test case for the bug? We have a test case for non-US locale (https://github.com/wp-cli/wp-cli/blob/69c978b38e5264eaf3824e7fc4bb2c3ece95b7fe/features/core-verify-checksums.feature#L58-L66), which I modified locally to run against `ja`, and it works as expected.

**Comment by miya0001** [comment]
OK! Thanks!

I'll write tests for `wp core download` and `wp core check-update` too.
They also have a similar problem.

**Comment by miya0001** [comment]
@danielbachhuber 

Ugh, I couldn't reproduce those problems.
Japanese package was already released.
I want to reproduce the same situation, but I have no idea... 😢 

But I found the solution for temporary use.
Maybe, following will be same with the localized package.

```
$ wp core download
$ wp core language install ja --activate
$ wp option update timezone_string $(wp eval "echo _x( '0', 'default GMT offset or timezone string' );")
$ wp option update date_format $(wp eval "echo __( 'M jS Y' );")
```

I will implement them and update our Vagrant solution and I would like to wait for feedback from our users. 😎 

Thanks!

**Comment by miya0001** [comment]
Ah, I will continue to investigate to solve this.

**Comment by danielbachhuber** [comment]
> Ah, I will continue to investigate to solve this.

Ok. We can re-open it if you can put together reproduction steps.
