### ISSUE TITLE
Fatal error: Call to undefined method WP_CLI::runcommand()

### ISSUE THREAD

**Issue by cpxi-admin** [wp-cli/wp-cli#3787]
Hi,

I'm running a command to get all post based on a category, once I have the id's I want to run the export command but keep getting the fatal error on `WP_CLI::runcommand()`

`if ( $args_assoc['export'] !== null && $args_assoc['export'] == true ) {
			
			WP_CLI::line( '----------' );
			
			$exportPath = CPXI_WP_CLI_DIR . '/export/';
			$exportUrl = WP_PLUGIN_URL . '/wp-cli/export/';
			
			$file = $sitename . '_export_posts_'.date( 'Y-m-d_H-i', time() ).'.xml';
			
			$export = 'export --dir='.$exportPath.' --skip_comments --filename_format='.$file.' --post__in='.implode( ',', $postIds );
			
			$options = array(
				'launch'     => false,
				'exit_error' => true,
			);
			
			WP_CLI::runcommand( $export, $options );
			WP_CLI::line( WP_CLI::colorize( 'Exporting posts to WXR file locate at %B' . $exportUrl . $file .'%n' ) );
		}`

Thanks

**Comment by danielbachhuber** [comment]
Can you share `wp --info` please?

**Comment by cpxi-admin** [comment]
`PHP binary:	/usr/local/Cellar/php55/5.5.36/bin/php
PHP version:	5.5.36
php.ini used:	/usr/local/etc/php/5.5/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.24.1`

**Comment by danielbachhuber** [comment]
You need to update to WP-CLI v1.0.0

**Comment by cpxi-admin** [comment]
Great! no more error thank you!
