### ISSUE TITLE
Create RPM distribution for each release

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3793]
For those that use RPMs to install software, it would be helpful to create an official WP-CLI build for each release.

Previously #1155, #2229

**Comment by szepeviktor** [comment]
Is there a linter for RPM-s?

**Comment by danielbachhuber** [comment]
Not sure I follow. Could you explain further?

**Comment by szepeviktor** [comment]
A package may be functional without any kind of inspection. I test my Debian packages with lintian and act accordingly.

**Comment by szepeviktor** [comment]
So my question is: What kind of linter does Redhat use?

**Comment by schlessera** [comment]
The Fedora project (community branch of Red Hat Enterprise Linux) uses a tool called `rpmlint`:
https://fedoraproject.org/wiki/Packaging:Guidelines#Use_rpmlint

**Comment by szepeviktor** [comment]
Thank you.

That is what I was afraid of. It has [34 messages](https://fedoraproject.org/wiki/Common_Rpmlint_issues).
Debian lintian has 1 zillion messages.

**Comment by danielbachhuber** [comment]
From an email thread:

> We make use of a Open Build Service, though we host our own instance in-house. Its pretty easy to use.
> 
> http://openbuildservice.org/
> 
> I was able to get an RPM built from your source in about 10 mins on an existing OBS project we have. 
>
> The OBS group hosts a reference instance that can be used to build Open Source projects:
> 
> https://build.opensuse.org/
> 
> You could give that a try if it will work with your build infrastructure.

@szepeviktor Do you have any experience creating RPMs?

**Comment by szepeviktor** [comment]
Nope. I am Debian user.
See my above comment. I am not willing to get closer to a loose system. I like very restrictive systems.

**Comment by SosyalAlkolik** [comment]
Hi everyone, I built a wp-cli RPM for version 1.1.0. Please can you check it? RPM and spec files are attached in my repository.

[https://github.com/SosyalAlkolik/wp-cli](url)

**Comment by SosyalAlkolik** [comment]
Hi everyone, I built a wp-cli RPM for version 1.1.0. Please can you check it? RPM and spec files are attached in my repository.

[https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0-1.el7.centos.noarch.rpm](url)
[https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0.spec](url)

**Comment by szepeviktor** [comment]
Actually:
https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0-1.el7.centos.noarch.rpm
https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0.spec

**Comment by SosyalAlkolik** [comment]
Thanks for correction the links.

**Comment by szepeviktor** [comment]
You're welcome.

Would you run an up-to-date rpmlint on it?

**Comment by danielbachhuber** [comment]
Thanks @SosyalAlkolik !

> Please can you check it?

I'm a total RPM newbie. What's the best way to check it?

Are you open to committing your `wp-cli.1.1.0.spec` to this repo as `wp-cli.spec`, and producing new builds when we have a release?

Happy to chat in the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you prefer realtime.

**Comment by SosyalAlkolik** [comment]
@szepeviktor 
I used rpmlint on CentOS7. This result in a attached file
![screenshot_20170329_000547](https://cloud.githubusercontent.com/assets/21251727/24427640/641a0804-1414-11e7-8e5b-8ea67eee50a0.png)

@danielbachhuber 
I tried this package with some wp commands using and also I checked installed files list. 
Secondly, yes, I will happy for commiting my spec file to wp-cli.spec repo and I am glad to try to produce new releases when you have.

**Comment by szepeviktor** [comment]
@SosyalAlkolik Please try checking your rpmlint version. I've used the latest in Debian.

```
$ rpmlint --version
rpmlint version 1.9 Copyright (C) 1999-2007 Frederic Lepied, Mandriva
```

Then please consider checking the package:
```bash
rpmlint -iv  wp-cli-1.1.0-1.el7.centos.noarch.rpm
```

**Comment by SosyalAlkolik** [comment]
@szepeviktor 
Thanks for comment. I used v1.9 and I will fix its errors soon.

**Comment by SosyalAlkolik** [comment]
I updated my rpm and spec files. I did not fix 
`wp-cli.noarch: W: no-documentation`
`wp-cli.noarch: W: no-manual-page-for-binary wp`
`wp-cli.noarch: E: no-signature`
Because wp-cli already use help inline
https://github.com/wp-cli/wp-cli/pull/548

**Comment by szepeviktor** [comment]
A script from the Debian package to generate a small man page:
https://github.com/wp-cli/wp-cli/blob/master/utils/wp-cli-updatedeb.sh#L69-L79

**Comment by SosyalAlkolik** [comment]
Why we have to create a man page? This program already has it in in-line help.

**Comment by szepeviktor** [comment]
> Why we have to create a man page?

Actually don't have to. I usually follow linters.
Anyone may issue `man wp` and - I think - it takes minimal efforts to generate a manual page.

**Comment by SosyalAlkolik** [comment]
Hi back, I changed RPM package for v1.1.0. I added man pages in the package.
https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0-1.el7.centos.noarch.rpm

**Comment by szepeviktor** [comment]
Thank you.
Could you provide the output of `rpmlint -vi wp-cli-1.1.0-1.el7.centos.noarch.rpm` ?

And please consider fixing the summary: https://github.com/SosyalAlkolik/wp-cli/pull/2

**Comment by SosyalAlkolik** [comment]
![screenshot_20170404_162429](https://cloud.githubusercontent.com/assets/21251727/24658737/40e776e8-1953-11e7-873e-dafe5f988880.png)
rpmlint -vi wp-cli-1.1.0-1.el7.centos.noarch.rpm command output

**Comment by SosyalAlkolik** [comment]
![screenshot_20170404_165205](https://cloud.githubusercontent.com/assets/21251727/24660040/1d520190-1957-11e7-835a-3fbdde05ce90.png)
Summary and description are fixed.

**Comment by SosyalAlkolik** [comment]
I think, my files are correct now.

https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0-1.el7.centos.noarch.rpm
https://github.com/SosyalAlkolik/wp-cli/blob/master/wp-cli-1.1.0.spec

Could you check the package and spec file?

**Comment by szepeviktor** [comment]
@SosyalAlkolik Are you prepared for building a new RPM at release time?

**Comment by szepeviktor** [comment]
Creating a new Debian package is scripted.

**Comment by SosyalAlkolik** [comment]
Yes, I'm ready to create a new RPM package when it release.

**Comment by danielbachhuber** [comment]
@SosyalAlkolik Can you:

* Submit your spec file in a pull request to this repository? It should go in this directory: https://github.com/wp-cli/wp-cli/tree/master/utils
* Submit your RPM build in a pull request to the builds repository? https://github.com/wp-cli/builds We should create a new `/rpm/` directory, I think.

@szepeviktor Any other steps you'd recommend?

**Comment by szepeviktor** [comment]
I don't dare to *recommend* a build script as https://github.com/wp-cli/wp-cli/blob/master/utils/wp-cli-updatedeb.sh

**Comment by SosyalAlkolik** [comment]
If you open a /rpm/ directory, I can pull a new request to submit rpm file.

**Comment by danielbachhuber** [comment]
> If you open a /rpm/ directory, I can pull a new request to submit rpm file.

@SosyalAlkolik You should be able to easily create the directory when you submit the file.

**Comment by SosyalAlkolik** [comment]
@danielbachhuber  Uploads are disabled in this branch.

**Comment by szepeviktor** [comment]
See the <kbd>Fork</kbd> button up there!

**Comment by SosyalAlkolik** [comment]
@szepeviktor Thanks

**Comment by SosyalAlkolik** [comment]
Hi, do I have to build RPM packages for older versions of wp-cli? Is this okay for only latest version? In addition to el7 rpm, I am going to prepare a package for el6.

**Comment by szepeviktor** [comment]
> Is this okay for only latest version?

Yes.

**Comment by SosyalAlkolik** [comment]
Thank you @szepeviktor! Today, I will prepare it for el6.

**Comment by SosyalAlkolik** [comment]
I cannot prepare for el6 because centos 6 doesn't support php 5.3.29 or higher. What do you want me to do?

**Comment by szepeviktor** [comment]
The popular remi repo may be the solution: http://rpms.famillecollet.com/

**Comment by SosyalAlkolik** [comment]
I builded RPM package for el6. There are latest rRPM packages in these links.
https://github.com/SosyalAlkolik/builds/blob/gh-pages/rpm/wp-cli-1.1.0-1.el7.centos.noarch.rpm
https://github.com/SosyalAlkolik/builds/blob/gh-pages/rpm/wp-cli-1.1.0-1.el6.noarch.rpm

**Comment by behzod** [comment]
@SosyalAlkolik I found and fixed a minor typo in your spec file. You may want to re-create your rpm files. See this merge request: #4014

**Comment by schlessera** [comment]
Might be interesting/relevent/a use case:

https://github.com/pantheon-systems/rpmbuild-wp-cli

**Comment by anantshri** [comment]
I would suggest looking at https://github.com/jordansissel/fpm rpm, deb, osx pkg multiple output options available. I am using it to build deb packages (not wp-cli but others) but rpm and others should not be a problem too:  https://github.com/AndroidTamer/Packaging_Tools/blob/master/bin/build_package#L8

**Comment by SosyalAlkolik** [comment]
Hi, I created RPM packages for v1.2.0 and v1.2.1. I added spec files and rpm packages.
https://github.com/SosyalAlkolik/wp-cli-1/tree/master/utils
https://github.com/SosyalAlkolik/builds/tree/gh-pages/rpm

**Comment by szepeviktor** [comment]
Could you provide the `rpmlint -vi wp.rpm` output?

**Comment by SosyalAlkolik** [comment]
```
$ rpmlint -vi Downloads/wp-cli-1.2.0-1.el7.centos.noarch.rpm 
wp-cli.noarch: I: checking
wp-cli.noarch: W: manpage-not-compressed bz2 /usr/share/man/man1/wp.1.gz
This manual page is not compressed with the bz2 compression method (does not
have the bz2 extension). If the compression does not happen automatically when
the package is rebuilt, make sure that you have the appropriate rpm helper
and/or config packages for your target distribution installed and try
rebuilding again; if it still does not happen automatically, you can compress
this file in the %install section of the spec file.

wp-cli.noarch: I: network-checks-disabled http://wp-cli.org/
Checks requiring network access have not been enabled in configuration, see
the NetworkEnabled option.

Error checking signature of Downloads/wp-cli-1.2.0-1.el7.centos.noarch.rpm: env: ‘rpm’: No such file or directory
wp-cli.noarch: E: no-dependency-on locales-cli
1 packages and 0 specfiles checked; 1 errors, 1 warnings.
```
```
$ rpmlint -vi Downloads/wp-cli-1.2.1-1.el7.centos.noarch.rpm 
wp-cli.noarch: I: checking
wp-cli.noarch: W: manpage-not-compressed bz2 /usr/share/man/man1/wp.1.gz
This manual page is not compressed with the bz2 compression method (does not
have the bz2 extension). If the compression does not happen automatically when
the package is rebuilt, make sure that you have the appropriate rpm helper
and/or config packages for your target distribution installed and try
rebuilding again; if it still does not happen automatically, you can compress
this file in the %install section of the spec file.

wp-cli.noarch: I: network-checks-disabled http://wp-cli.org/
Checks requiring network access have not been enabled in configuration, see
the NetworkEnabled option.

Error checking signature of Downloads/wp-cli-1.2.1-1.el7.centos.noarch.rpm: env: ‘rpm’: No such file or directory
wp-cli.noarch: E: no-dependency-on locales-cli
1 packages and 0 specfiles checked; 1 errors, 1 warnings.
```

**Comment by szepeviktor** [comment]
Is it possible to resolve Warning and  Errors?

**Comment by SosyalAlkolik** [comment]
For first warning, I will use bz2 manpage and solve that warning. Secondly, actually, we don't have to sign these packages because they aren't in an RPM repository. The reason for using signatures is to ensure that the correct packages are installed from the correct repositories. If you want, my company tells me, they can give an RPM repository service for you.

**Comment by szepeviktor** [comment]
> Secondly, actually, we don't have to sign these packages because they aren't in an RPM repository.

I think the error is `wp-cli.noarch: E: no-dependency-on locales-cli`

**Comment by SosyalAlkolik** [comment]
This error appears when I run rpmlint on Mint or another deb based distros. When I run on the rpm based distros, the output is (on openSUSE) 
```
rpmlint --version
rpmlint version 1.8 Copyright (C) 1999-2007 Frederic Lepied, Mandriva

rpmlint -vi wp-cli-1.2.0-1.el7.centos.noarch.rpm 
wp-cli.noarch: I: network-checks-disabled http://wp-cli.org/
Checks requiring network access have not been enabled in configuration, see
the NetworkEnabled option.

wp-cli.noarch: I: checking
1 packages and 0 specfiles checked; 0 errors, 0 warnings.
```

**Comment by szepeviktor** [comment]
Seems like those Debian-based ones have modern rpmlint.
https://github.com/rpm-software-management/rpmlint/releases

**Comment by szepeviktor** [comment]
> rpmlint has detected that the package uses some capabilities not provided by its dependencies. E.g., the package installs Perl modules but does not require Perl itself.

http://fba.rosalinux.ru/rpmlint/descriptions/no-dependency-on/

I think by adding `locales-cli` the error will go away.

**Comment by SosyalAlkolik** [comment]
Latest version of rpmlint is available on Fedora 25.
https://pkgs.org/download/rpmlint
Outputs with latest version (1.9.9) of rpmlint:
```
# rpmlint -V
rpmlint version 1.9 Copyright (C) 1999-2007 Frederic Lepied, Mandriva
```
1.2.0
```
# rpmlint -vi wp-cli-1.2.0-1.el7.centos.noarch.rpm 
wp-cli.noarch: I: checking
wp-cli.noarch: W: spelling-error %description -l en_US multi -> mulch, mufti
The value of this tag appears to be misspelled. Please double-check.

wp-cli.noarch: I: checking-url http://wp-cli.org/ (timeout 10 seconds)
1 packages and 0 specfiles checked; 0 errors, 1 warnings.
```
1.2.1
```
# rpmlint -vi wp-cli-1.2.1-1.el7.centos.noarch.rpm 
wp-cli.noarch: I: checking
wp-cli.noarch: W: spelling-error %description -l en_US multi -> mulch, mufti
The value of this tag appears to be misspelled. Please double-check.

wp-cli.noarch: I: checking-url http://wp-cli.org/ (timeout 10 seconds)
1 packages and 0 specfiles checked; 0 errors, 1 warnings.
```

**Comment by SosyalAlkolik** [comment]
Everything is OK?

**Comment by szepeviktor** [comment]
Yes.

**Comment by murtzsarialtun** [comment]
Do you intend to publish these packages to a repo?

**Comment by danielbachhuber** [comment]
> Do you intend to publish these packages to a repo?

You're welcome to submit these as a PR to https://github.com/wp-cli/builds

Eventually, I'd like to create these builds in an automated manner.

**Comment by szepeviktor** [comment]
It is not possible to match for example [Red Hat](https://access.redhat.com/sites/default/files/attachments/rpm_building_howto.pdf) and [Fedora Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Tags_and_Sections)

See the PR #4203

**Comment by danielbachhuber** [comment]
The automation is now live: https://github.com/wp-cli/rpm-build

The builds are pushed here: https://github.com/wp-cli/builds/tree/gh-pages/rpm

Thanks again @szepeviktor @murtzsarialtun for your work on this
