### ISSUE TITLE
WPDB-Prefix not escaped in wp_get_table_names

### ISSUE THREAD

**Issue by jaysn** [wp-cli/wp-cli#3794]
In `wp_get_table_names` the `$wpdb->prefix` is used to query/show all Tables with the site-specific prefix (eg. in Multisite  environments). Unfortunately this query is not properly escaped which results in a show tables like wp_10_posts and wp_100_posts because of the unescaped single-char-whildcard "\_".

The Query builds to `"SHOW TABLES LIKE "$prefix%"` which results in a prepared `SHOW TABLES LIKE "wp_10_%"`. since the "\_" Char is a Single-Character-Wildcard in LIKE Patterns this Query also matches eg. wp\_100\_ prefixed tables.

A Solution could be an special escapement of the prefix to prepend either the standard mysql escape-character as mentioned in http://stackoverflow.com/a/3683868

i found this issue while copying some sites from one multisite environment to another and it exported the wp\_7\_tables but also the wp\_7x\_tables.

i've then tailored the problem down to `\WP-CLI\Utils\wp_get_table_names()`.

**Comment by danielbachhuber** [comment]
Thanks for the great bug report, @jaysn !
