### ISSUE TITLE
search-replace doesn't work if Scandic letters (ä, ö ,å) in url

### ISSUE THREAD

**Issue by jisaksson** [wp-cli/wp-cli#3796]
I have a url with scandic letter ä. When I try to replace it to anything it fails.

`c:\xampp\htdocs\virtualhosts\wordpress>wp search-replace http://äåö.fi http://aoa.fi --dry-run --all-tables --debug

Debug (bootstrap): No readable global config found (0.012s)
Debug (bootstrap): No project config found (0.012s)
Debug (bootstrap): No package autoload found to load. (0.061s)
Debug (bootstrap): ABSPATH defined: C:\xampp\htdocs\virtualhosts\wordpress/ (0.062s)
Debug (bootstrap): Begin WordPress load (0.062s)
Debug (bootstrap): wp-config.php path: C:\xampp\htdocs\virtualhosts\wordpress\wp-config.php (0.063s)
PHP Notice:  Undefined index: HTTP_HOST in C:\xampp\htdocs\virtualhosts\wordpress\wp-content\plugins\wp-super-cache\wp-cache-base.php on line 4
Notice: Undefined index: HTTP_HOST in C:\xampp\htdocs\virtualhosts\wordpress\wp-content\plugins\wp-super-cache\wp-cache-base.php on line 4
Debug (bootstrap): Loaded WordPress (0.436s)
Debug (bootstrap): Running command: search-replace (0.436s)
WordPress database error Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation 'like' for query`

Windows 10
Apache
PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS )
10.1.19-MariaDB mariadb.org binary distribution

**Comment by danielbachhuber** [comment]
It looks like the source of the error is this:

> WordPress database error Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,COERCIBLE) for operation 'like' for query

Have you verified the collations on your database? I'm not sure this is something WP-CLI should attempt to fix for you.

**Comment by viktorbijlenga** [comment]
Looks like the issues is related to different collations in the database, so I would guess that it doesn't have anything to do with WP Cli.

@jisaksson This [thread on Stackoverflow](http://stackoverflow.com/questions/11770074/illegal-mix-of-collations-utf8-unicode-ci-implicit-and-utf8-general-ci-implic) might be a good starting point to solve the error.

**Comment by jisaksson** [comment]
@danielbachhuber You are correct. It's indeed problem with my database, thanks.

@viktorbijlenga Yup, my bad.
