### ISSUE TITLE
Store the private deploy key in Travis settings, not in the repo

### ISSUE THREAD

**Issue by simonwheatley** [wp-cli/wp-cli#3798]
I recently discovered that it's possible to store encrypted variables in the [Travis repo settings](https://docs.travis-ci.com/user/environment-variables#sts=Defining Variables in Repository Settings), this has the benefit that the encrypted variable (in this case the private deploy key) is not distributed with the Git repository. The implementation is fairly simple, something like:

``` bash
# Turn off command traces while dealing with 
# the private key
set +x

# Get the encrypted private key from the repo settings
# This is the private pair to the "Travis GH Pages Deploy Key"
# The public key portion can be deleted here:
# https://github.com/wp-cli/builds/settings/keys
# The private key is in Travis settings here:
# https://travis-ci.org/wp-cli/builds/settings
echo -e $WPCLI_GITHUB_DEPLOY_KEY > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

set -x
```

I suggest WP CLI switches to this implementation to reduce the risk of distributing even an encrypted copy of the private key.

**Comment by danielbachhuber** [comment]
👍  This is something I just haven't gotten around to doing.

**Comment by danielbachhuber** [comment]
I had to `cat .ssh/id_rsa | base64` the SSH private key, because no amount of escaping it as a string would get to echo properly as a file.

**Comment by simonwheatley** [comment]
> I had to `cat .ssh/id_rsa | base64` the SSH private key, because no amount of escaping it as a string would get to echo properly as a file.


How frustrating. 

I have it working [over here](https://github.com/Automattic/vip-go-mu-plugins/blob/258-generate-docs/ci/generate-docs.sh#L20-L30). Prior to pasting into the repo settings, I replaced all newlines with `\n` and then when pasting into repo settings in Travis I surrounded it with quotes, e.g. `"KEY\nHERE\n"`.

**Comment by danielbachhuber** [comment]
> Prior to pasting the private key into the repo settings, I replaced all newlines

Ah, that'd make sense. `base64` encoding works well enough.

**Comment by dhimmel** [comment]
> I have it working over here.

The "over link" was not versioned and now doesn't work. But I think the [correct link now is this](https://github.com/Automattic/vip-go-mu-plugins/blob/5f985910c849b1eb104c3b4b19776e9be0fb5b87/ci/deploy.sh#L19-L34)?

> I replaced all newlines with `\n` and then when pasting into repo settings in Travis I surrounded it with quotes

I wonder if replacing the newlines is necessary. When I copy in text into the Travis settings environment variable value, newlines are converted to spaces. Not sure whether spaces are acceptable for ssh-add / private ssh keys.

Will update this comment with a link to a PR to switch from Travis encrypted files to Travis environment variables for storing the private SSH key.
