### ISSUE TITLE
search-replace serialization fails with podcast data from PowerPress (and other plugins)

### ISSUE THREAD

**Issue by theDanielJLewis** [wp-cli/wp-cli#3804]
PowerPress is the #1 podcasting plugin for WordPress. It, and a couple other WordPress plugins, save media enclosure data in a mixed-format row under …_postmeta.

Here's a sample "meta_data" from "meta_key" = "enclosure" :

```
https://traffic.libsyn.com/noodlemx/tap291.mp3
20540288
audio/mpeg
a:3:{s:8:"duration";s:8:"00:42:30";s:7:"summary";s:2073:"TRUNCATED";s:12:"itunes_image";s:133:"TRUNCATED";}
```
(Where "TRUNCATED" is content or data from the post.)

Note that the first few lines are regular strings, and then there's serialized data for additional fields.

When using `wp search-replace`, it _will_ change the values in this row, but it _does not_ reserialize the data.

For example, the "itunes_image" string is a URL. When I switched my site from HTTP to HTTPS and ran an appropriate `wp search-replace`, it _did_ change the URL in this row. However, it did not properly increment the character count.

So it seems that `wp search-replace` doesn't properly handle and reserialize mixed-format data like this.

Consequently, the data is not properly serialized and it disappears from PowerPress and the places where it's supposed to appear.

Thus, I recommend that `wp search-replace` recognize serialization in fields, even when it's deeper in the field, or combined with regular strings.

**Comment by danielbachhuber** [comment]
Oh, wow. I thought storing PHP serialized data in the database was the worst, and now I've been proven wrong.

> Thus, I recommend that `wp search-replace` recognize serialization in fields, even when it's deeper in the field, or combined with regular strings.

I'm not sure this is a problem WP-CLI can provide a solution for. It would be impossible to correctly handle _every_ data format when you open the playing field to literally everything. Should WP-CLI decode a base64-encoded string, perform search replace, and then re-encode it? Etc.

Do you have a suggested algorithm for identifying PHP serialized strings inside of arbitrary blobs?

**Comment by theDanielJLewis** [comment]
From my limited dev knowledge, I would suggest WP-CLI simply recognize serialized data regardless of where it appears in the field. It does, after all, follow the same pattern.

Practically, this seems as simply as adding wildcards before and after the serialization. Effectively saying, "regardless of what's before this or after this, reserialize this data that's clearly serialized in the middle."

**Comment by javorszky** [comment]
Hi @theDanielJLewis! Would storing those 4 lines of data in 4 different rows be a viable option? That would eliminate having to create something that is non-trivial to revognise serialised arrays within other things.

Other edge cases that would bring about is: how do you know whether the thing in the middle of other things that _look like_ a serialised array is actually a serialised array, and is meant to be search-replaced, or just a string, and changing that would break something else?

**Comment by danielbachhuber** [comment]
> From my limited dev knowledge, I would suggest WP-CLI simply recognize serialized data regardless of where it appears in the field. It does, after all, follow the same pattern.

I'm not confident it's as easy as this. I *think* trying to identify serialized data within an arbitrary string (either one instance or many) is significantly more challenging than identifying when an entire string is serialized data. What if the serialized data contained a string that also represented serialized data.

And, because it's more challenging, changing the current algorithm runs the risk of nasty unexpected consequences.

**Comment by rmccue** [comment]
Recognising serialized data anywhere in the post could break actual post content that talks about serialization, so it's a bit crazy to do that IMO.

**Comment by theDanielJLewis** [comment]
> Would storing those 4 lines of data in 4 different rows be a viable option? 

I understand that's ultimately more desirable. But this is the way PowerPress and a couple other plugins work.

> Recognising serialized data anywhere in the post could break actual post content that talks about serialization, so it's a bit crazy to do that IMO.

But if you want to find-and-replace the data in that post's serialization example, wouldn't you _want_ the serialization to be updated, too?

I did, in the meantime, discover https://github.com/tokmak/Fix-Serialization, which works to fix the inaccurate serialization that WP-CLI leaves behind.

**Comment by javorszky** [comment]
> I understand that's ultimately more desirable. But this is the way PowerPress and a couple other plugins work.

I would argue that in this case PowerPress and the other plugins that work this way should be ones migrating over to this way. I can't see a benefit of storing these things in one row, but there are numerous drawbacks.

**Comment by theDanielJLewis** [comment]
I've sent this thread to the PowerPress developer.

**Comment by danielbachhuber** [comment]
This isn't something WP-CLI is going to fix at this point. My recommendation is that PowerPress updates its storage mechanism.
