### ISSUE TITLE
wordpress-tests-lib : factory->post->create_object not working on mysql Ver 14.14 Distrib 5.7.16

### ISSUE THREAD

**Issue by imatat** [wp-cli/wp-cli#3805]
Hello, 

The function factory->post->create_object is not worlking on mysql Ver 14.14 Distrib 5.7.16.
When I try to insert a new post, it return 0 as the Id and doesn't insert the post.
I suspected that it has to do with mysql version, and when I forced mysql version to 5.6.24 on my docker image, it just worked fine.

Thanks

**Comment by danielbachhuber** [comment]
Hi @imatat,

This sounds like it's a bug with the WordPress core test suite. The appropriate bug tracker is https://core.trac.wordpress.org/
