### ISSUE TITLE
Core Update Failing  4.7.1 to 4.7.2

### ISSUE THREAD

**Issue by designextreme** [wp-cli/wp-cli#3806]
I am trying to update from 4.7.1 to 4.7.2 and nothing happens...
`
wp core update --allow-root`

(currently in an active WordPress website, or I can use --path). I have the latest WP-Cli installed. I have around 50 WordPress installations to update and I need WP-Cli to do its job.

Here is the debug result:

```
root@server [~]# cd /home/user/public_html
root@server [/home/user/public_html]# wp --allow-root core version
4.7.1
root@server [/home/user/public_html]# wp --allow-root core update
root@server [/home/user/public_html]# wp --allow-root core update --debug
Debug (bootstrap): No readable global config found (0.006s)
Debug (bootstrap): No project config found (0.006s)
Debug (bootstrap): No package autoload found to load. (0.094s)
Debug (bootstrap): ABSPATH defined: /home/user/public_html/ (0.094s)
Debug (bootstrap): Begin WordPress load (0.094s)
Debug (bootstrap): wp-config.php path: /home/user/public_html/wp-config.php (0.094s)
```

That's it.

I've edited it a little for privacy.

- Noah

**Comment by danielbachhuber** [comment]
Hi @designextreme,

Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support
