### ISSUE TITLE
Run some commands without requiring an active Database

### ISSUE THREAD

**Issue by mathieuhays** [wp-cli/wp-cli#3808]
Hi !

I've been trying to run the `wp help` and `wp scaffold plugin-tests` commands but it fails because I haven't configured wp-cli to reach for my remote database (I'm using Vagrant for my dev environment). I understand this is fixable by using `wp-cli.yml` but do these commands really need to load WordPress in order to work?

It would be nice to have commands that can bypass WordPress altogether when relevant (A bit ironic for a WordPress-CLI I know 👍).

In the idea it could also be useful to expose a parameter or hook enabling people creating community packages to prevent an unnecessary WordPress load when all they're doing is I/O manipulation for example.

What do you think?

PS: Thanks for maintaining this awesome tool !

**Comment by danielbachhuber** [comment]
Hi @mathieuhays:

>  I understand this is fixable by using `wp-cli.yml` but do these commands really need to load WordPress in order to work?

Yes, those do.

> It would be nice to have commands that can bypass WordPress altogether when relevant (A bit ironic for a WordPress-CLI I know

This is already possible. See `wp dist-archive` as an example: https://github.com/runcommand/dist-archive/blob/master/command.php#L45

> In the idea it could also be useful to expose a parameter or hook enabling people creating community packages to prevent an unnecessary WordPress load when all they're doing is I/O manipulation for example.

This is already possible. Simply add the following to your command's doc block:

```
@when before_wp_load
```

See https://make.wordpress.org/cli/handbook/commands-cookbook/#docblock-tags

**Comment by mathieuhays** [comment]
Sorry I missed that. Thanks for the answer
