### ISSUE TITLE
Warn for low memory scenarios and provide guidance.

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3811]
For memory-heavy commands like `wp package install <package>`, it would be helpful to check the amount of memory available and provide some guidance on how to overcome that in case an error might come up.

Two potential solutions (which can just as well be combined):

1. Check memory limit with [`ini_get( 'memory_limit' )`](http://php.net/manual/en/function.ini-get.php) before executing memory-heavy operations and echo a warning in console before executing the operation.

2. Add a shutdown handler with [`register_shutdown_function()`](http://php.net/manual/en/function.register-shutdown-function.php) and then check whether the last error was indeed an "Allowed memory size of ... exhausted" issue using [`error_get_last()`](http://php.net/manual/en/function.error-get-last.php).

**Comment by danielbachhuber** [comment]
💯 

I was also thinking the other day that it would be helpful to know where all of the memory was going. The `composer` standalone doesn't have the same problem as far as I know.

**Comment by schlessera** [comment]
Here's a profile run for `wp package install binarygary/db-checkpoint`:
https://blackfire.io/profiles/4852c68c-d545-4c07-998b-39d4a763bd0f/graph

**Comment by schlessera** [comment]
So, at first glance, 76 packages are being considered, resulting in 180k rule nodes.
The operation needs 242 MB (on PHP 7.0.15), of which roughly one third goes into `json_decode()`.
There's no immediate general issue that I can identify, with the main culprit just being the fact that there's a lot of dependency rules to take care of.

**Comment by schlessera** [comment]
Related: https://github.com/composer/composer/pull/6168

**Comment by danielbachhuber** [comment]
> Related: composer/composer#6168

Nice.

> Add a shutdown handler with `register_shutdown_function()` and then check whether the last error was indeed an "Allowed memory size of ... exhausted" issue using `error_get_last()`.

We might consider doing this for [other common issues](https://make.wordpress.org/cli/handbook/common-issues/) as well.

**Comment by schlessera** [comment]
Yes, I agree. Ideally, there should never be fatal errors, and users should be offered meaningful next steps to resolve any issues they might encounter.

**Comment by danielbachhuber** [comment]
Composer's memory improvements landed in v1.4.0: https://github.com/composer/composer/releases/tag/1.4.0

We should re-profile to see what memory consumption is like now, and determine a course of action from there.

In any case, we should also include some mention of this problem in the release notes.

**Comment by schlessera** [comment]
This was solved via https://github.com/wp-cli/package-command/pull/95
