### ISSUE TITLE
Return keyword is missing?

### ISSUE THREAD

**Issue by AppChecker** [wp-cli/wp-cli#3815]
Hi!

Please look this [fragment of the source code](https://github.com/wp-cli/wp-cli/blob/f900a4b04139d03125b78cef27f1e27d83e30285/php/commands/widget.php#L625):

```
		if ( empty( $widget ) ) {
			false;
		}
```

Is the 'return' keyword missing?

This possible defect found with [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by danielbachhuber** [comment]
Looks like it!
