### ISSUE TITLE
Existing PDF previews not deleted on media regenerate.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#3817]
`$metadata['file']`isn't set for PDFs so `Media_Command::remove_old_images()` won't delete existing previews. A corresponding issue arises in `Media_Command::needs_regeneration()`.

Passing down the `$fullsizepath` from `process_regeneration()` (and adjusting the `$dir_path` calc) would be a simple fix.

Also the use of `basename()` has UTF-8 issues (see eg core trac [#33227](https://core.trac.wordpress.org/ticket/33227#comment:12)) - I'll open a separate ticket for that.

**Comment by danielbachhuber** [comment]
👍 Thanks for the report

**Comment by danielbachhuber** [comment]
🔨
