### ISSUE TITLE
basename() doesn't deal well with UTF-8.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#3818]
As mentioned in core trac [#33227](https://core.trac.wordpress.org/ticket/33227#comment:12)) `basename()` and `PATHINFO_BASENAME` are PHP locale dependent and fail with UTF-8 file names unless the locale is UTF-8.

A simple fix is just to replace `basename()` with the locale-independent `wp_basename()`.

**Comment by szepeviktor** [comment]
I think in the third millennium you should use UTF-8 everywhere.

**Comment by danielbachhuber** [comment]
> A simple fix is just to replace `basename()` with the locale-independent `wp_basename()`.

At a first glance, it looks like this won't be too difficult to do.

There are some places we're calling `basename()` before WordPress is loaded, so we may need to shim `wp_basename()`.

> I think in the third millennium you should use UTF-8 everywhere.

@szepeviktor Please be kind.

**Comment by szepeviktor** [comment]
Excuse me.

**Comment by schlessera** [comment]
`wp_basename` is just a one-liner: https://core.trac.wordpress.org/browser/tags/4.5.3/src//wp-includes/formatting.php#L4311
As the WP version does not have an include guard, we should probably just provide a WP-CLI specific version to not run into conflicts.

**Comment by danielbachhuber** [comment]
> As the WP version does not have an include guard

What's an include guard?

**Comment by schlessera** [comment]
A mechanism to avoid double inclusion/definition/declaration. In this case, it would be wrapping it in:
```if ( ! function_exists( 'wp_basename' ) { ... }```

**Comment by gitlost** [comment]
I should add that `PATHINFO_FILENAME` also suffers from the same malaise, and I suppose should be dealt with too, though the 2 places it's used aren't that likely to encounter UTF-8 as of now. Also, there's no WP core equivalent for it (there should be!), but then it's only a two-liner.
