### ISSUE TITLE
Speed up wp db import

### ISSUE THREAD

**Issue by tfrommen** [wp-cli/wp-cli#3820]
Hi there,

I was doing several imports of rather large SQL dumps, and they took quite a while. So I had a look at what WP-CLI is actually doing.

Is there a reason to not apply some _common optimization_ that is safe to do for imports?

I am talking about something like setting `AUTOCOMMIT`, `FOREIGN_KEY_CHECKS` and `UNIQUE_CHECKS` to `0` (and reverting after the import has been done, or failed). The reason for this is: if there were violations, they should have been detected in the database the dump originated from. And if not, you wouldn't end up with the same data - because the original database is corrupted somehow, and yours is not.

Does that make sense?

Happy to provide more information as necessary.

Cheers,
Thorsten

**Comment by danielbachhuber** [comment]
> Is there a reason to not apply some _common optimization_ that is safe to do for imports?

No reason not to, unless there are backwards compatibility issues.

**Comment by schlessera** [comment]
I'd suggest adding these in to accelerate the most common use case and add an option to disable these optimizations for the few cases where they might still cause an issue.

**Comment by danielbachhuber** [comment]
> I'd suggest adding these in to accelerate the most common use case and add an option to disable these optimizations for the few cases where they might still cause an issue.

👍  Works for me.

**Comment by danielbachhuber** [comment]
🚢
