### ISSUE TITLE
Wrong DB prefix in `wp-config.php` produces misleading error messages

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3825]
When a WordPress site is correctly installed within the DB, but the `wp-config.php` that WP-CLI parses provides the wrong DB prefix, WP-CLI aborts any actions with the following message:
```
Error: The site you have requested is not installed.
Run `wp core install`.
```
In the particular case I encountered, this was due to the `wp-config.php` incorrectly parsing the prefix from a `.env` file. See [related issue](https://github.com/wecodemore/wpstarter/issues/61).

Although this should normally not happen, it would be preferable for WP-CLI to check the existing tables when the DB connection was successful, any maybe point the user to the fact that there is already an install under a different prefix, hinting at a configuration issue.

**Comment by danielbachhuber** [comment]
> Although this should normally not happen, it would be preferable for WP-CLI to check the existing tables when the DB connection was successful, any maybe point the user to the fact that there is already an install under a different prefix, hinting at a configuration issue.

One thing worth noting: this is a valid use case. One feature of the `$table_prefix` global is that you can run multiple WordPress installs out of the same database.

Do you have a suggested fix?

**Comment by danielbachhuber** [comment]
@schlessera Can you provide a suggested implementation?

**Comment by schlessera** [comment]
A basic algorithm could be to look for tables in the DB that match a known suffix, so that you can then extract the corresponding prefix and match that against the other tables.

So:

Check for list of tables to find a string that ends on `options`. Let's say you find a string `random_options`. Peeling `options` off of `random_options` leaves you with `random_` as a possible prefix. If you then find a `{$possible_prefix}posts` and a `{$possible_prefix}postmeta`, you probably found the correct prefix. Compare whether it is a different one than the one in `wp-config.php` and let the user know about the findings.

**Comment by Lewiscowles1986** [comment]
What would be the situation for a WordPress install if the prefix was unknown though?

`SHOW TABLES LIKE '%posts'` could return a post (if there are more than one logic would have to be that it's multi-site or multiple installs). You can dig deeper from that point I suppose.

https://dev.mysql.com/doc/refman/5.7/en/show-tables.html

**Comment by schlessera** [comment]
@Lewiscowles1986 No, WP-CLI has a mechanism to load the variables from `wp-config.php` without triggering `wp-settings.php`.

**Comment by Lewiscowles1986** [comment]
Then the details to connect are present and the command should yield results in a database with a posts table. The problem would be if there were multiple installs of wp (more than two rows), you'd essentially have to short-circuit out or guess (I'd lean more toward short-circuiting out). Also if `wp-config.php` can be loaded without executing, the site it's loaded from shouldn't work without a prefix (or should be in perpetual setup mode), right?

Is this more for people that are DB switching inside of wp-config.php based upon URL? I'd like to know more about the problem and the situations that can lead to not being able to read a prefix.
