### ISSUE TITLE
Warn when managing rewrites with `--skip-plugins` or `--skip-themes`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3827]
WordPress' rewrites API requires the rewrite rules to be registered in order to be saved to the database.

If you run `wp rewrite flush` with `--skip-plugins` or `--skip-themes`, you can inadvertently miss saving rewrites registered in plugins or themes.

To help the user realize their mistake, we should provide a warning when they use `wp rewrite *` with `--skip-plugins` or `--skip-themes` to alert them to the fact that some rewrite rules may be missing.

**Comment by leepeterson** [comment]
@danielbachhuber I think perhaps the language should reflect exactly _what_ did not load themes, or perhaps _why_ themes were not loaded.

> Warning: Some rewrite rules may be missing because themes weren't loaded.

...might change to...

> Warning: Some rewrite rules may be missing because themes weren't loaded by WP-CLI.

...or...

> Warning: Some rewrite rules may be missing because `skip-themes` is set.

In the case of WordPress living in its own subdirectory, if `WP_DEFAULT_THEME` is not set, or if `register_theme_directory()` is not called, a wp-cli user may think a step was missed during setup when "themes weren't loaded" is encountered.

**Comment by danielbachhuber** [comment]
@leepeterson Sure, can you open a new issue for it?

**Comment by leepeterson** [comment]
Yes, sir. Thank you.
