### ISSUE TITLE
Users created by `wp user create` flagged by Wordfence

### ISSUE THREAD

**Issue by gd-jroberts** [wp-cli/wp-cli#3828]
It would be nice to have an option to force `wp user create` to use "wp_insert_user()" instead of "wpmu_create_user()" as the latter seems to be missing some metadata that Wordfence looks for. The result is a whole lot of hand waving and people running around when Wordfence notifies them that "The user `admin` was created outside of WordPress."

**Comment by danielbachhuber** [comment]
Previously #1499

Can you explain why you think `wp_insert_user()` is more correct? It seems like Wordfence is actually the issue here, and should be hooking into `wpmu_create_user()` as well.

**Comment by gd-jroberts** [comment]
Sorry, I'm not sure my depth of knowledge is deep enough to answer that question. Just grasping for a way to be able to automate user account creation through wpcli and not have Wordfence complain each time. Can you help me understand why `wpmu_create_user()` is preferred? From what I'm reading (https://developer.wordpress.org/reference/functions/wpmu_create_user/) it seems specific to multisite installs. I don't have any multisites or rules to apply to each new user account.

**Comment by danielbachhuber** [comment]
> Can you help me understand why `wpmu_create_user()` is preferred?

Per #1499, `wpmu_create_user()` is used on multisite to run the data through `wpmu_validate_user_signup`, which some plugins use to apply additional registration rules (e.g. a `user_login` can't conflict with an existing site slug).

**Comment by gd-jroberts** [comment]
Thanks. I'll open a support ticket with Wordfence and see what happens.
