### ISSUE TITLE
Cannot use "self" when no class scope is active 

### ISSUE THREAD

**Issue by juekbr** [wp-cli/wp-cli#3830]
Hi

I am using wp search-replace in a script which moves a site to test cause it needs some updates. The script fails at the wp search-replace step with
"Fatal error: Cannot use "self" when no class scope is active in .." and points to a php file in the theme.

I am clueless if this is a bug or if some more config is needed. Any idea or workaround?
Thx. Kr, JK

------------------------
System:
PHP 7.0.16 (cli)
OS: Debian GNU/Linux 8.7 (jessie)
WP: 4.2.2
WP-CLI 1.1.0

**Comment by danielbachhuber** [comment]
> "Fatal error: Cannot use "self" when no class scope is active in .." and points to a php file in the theme.

This sounds like a bug in your theme, not WP-CLI.

You can use the `--skip-themes` flag to skip the loading of themes when running WP-CLI.
