### ISSUE TITLE
Feature request: wp db info command

### ISSUE THREAD

**Issue by javorszky** [wp-cli/wp-cli#3831]
It would print out the current database connection details:

* host
* username
* database name
* database prefix

This would be useful in cases when there are multiple config files present and the `wp-config.php` pulls one of them in based on environment or ENV vars set. See how pantheon does local development. If there is a `wp-config-local.php`, use that, otherwise use default pantheon details.

The intended purpose of the `db info` command would be to double check WHICH database details we're using before issuing a potentially destructive command like `wp db import <file>`.

**Comment by schlessera** [comment]
I could indeed have used that command myself recently, as I was dealing with a DB prefix that was not correctly being set, so I agree about the usefulness.

However, given your use case, wouldn't you actually want to have a command to get the path to the config that is currently being used? So, that would return either `<some/path>/wp-config.php` or `<some-path>/wp-config-local.php`.

**Comment by javorszky** [comment]
In case of the dev site I'm working on currently, the config file used is `wp-config.php`, but the contents of the file are (abridged) as follows:

```
if (file_exists(dirname(__FILE__) . '/wp-config-local.php') && !isset($_ENV['PANTHEON_ENVIRONMENT'])):
    # IMPORTANT: ensure your local config does not include wp-settings.php
    require_once(dirname(__FILE__) . '/wp-config-local.php');

/**
 * Pantheon platform settings. Everything you need should already be set.
 */
else:
    // their local settings here
endif;
```
If I expand that with other forks, like `wp-config-dev.php` or `wp-config-dave.php`, etc, then the file parsed is STILL going to be the `wp-config.php` from what I understand.

**Comment by schlessera** [comment]
Yes, right. As I said, I had a related issue lately where seeing the prefix being used would have helped me save some time with troubleshooting.

I wonder whether having access to the password would make sense as well. Someone being able to run WP-CLI would also be able to directly look into the `wp-config.php` or `.env` file (or access the DB directly anyway), so I don't think that would cause a security issue. Combined with RESTful access, it would potentially allow for more simple cloning of sites.

**Comment by danielbachhuber** [comment]
Interesting idea.

If `wp db info` was more generally about `wp-config.php` data, would it make more sense as `wp config info` ?

Related https://github.com/wp-cli/ideas/issues/34 and https://github.com/wp-cli/ideas/issues/4, which generally seem to be leading to `wp config (create|edit|update)`

**Comment by javorszky** [comment]
Hm, `wp config info` would make sense, except there's no `wp config` command yet. There's a `wp core config`, but that writes things.

There is a `wp db` command already, so adding `info` to it is fairly easy. Or maybe `wp core info`?

**Comment by danielbachhuber** [comment]
> Hm, `wp config info` would make sense, except there's no `wp config` command yet.

Not a blocker. Creating `wp-cli/config-command` could be a follow-up to https://github.com/wp-cli/wp-cli/issues/3728

**Comment by javorszky** [comment]
`wp config info` is more sensible then. :shipit: 

I'll help out over the weekend.

**Comment by danielbachhuber** [comment]
After https://github.com/wp-cli/wp-cli/pull/3978 lands, we can make this happen in https://github.com/wp-cli/config-command

Closing in favor of https://github.com/wp-cli/config-command/issues/2
