### ISSUE TITLE
Simple dependency resolution

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3835]
There are several scenarios where commands fail because some of their dependencies are not met. The error that results in this can appear in several spots:

* when the actual command is run
* when another command is run that depends on that command
* when WP-CLI is run

While the two first error cases are not very elegant when working with WP-CLI, the third one is a hurdle a lot of people don't seem to be able to overcome. When something is wrong with their DB, they might not even be able to display the help screen.

To provide a generalized solution to overcome this, I'd like to look into providing a simple and flexible dependency resolution mechanism, with the ability to let commands that are currently installed remain inactive until all its dependencies are met.

Here's a mockup of what the user would see (in this example, with an invalid DB configuration):
![commands-dependency-mockup](https://cloud.githubusercontent.com/assets/83631/23267537/51acdcc0-f9eb-11e6-9fce-17af70f64653.jpg)

This would keep WP-CLI working even when some dependencies are not met, and it would give clear indications to the user about what is currently missing for the command they need.

**Comment by danielbachhuber** [comment]
> There are several scenarios where commands fail because some of their dependencies are not met.

It'd be helpful to identify the specific types of dependencies, and at what point we can know whether they're met.

Some dependencies (e.g. a valid database connection) require performing part or all of the WordPress load process.

> it would give clear indications to the user about what is currently missing for the command they need.

I do like the mockup you've provided, in the sense that it would be worthwhile to redesign the help screens at some point.

**Comment by schlessera** [comment]
[From Slack:](https://wordpress.slack.com/archives/C02RP4T41/p1491929061685119)
> danielbachhuber [6:44 PM] 
> ok. the issue seems too abstract at this point. it'd be good to identify one or two actionable aspects, solve those, and address the rest of it later
> 
> schlessera [6:45 PM] 
> Ok. I've had trouble in the past coming up with "evolutionary steps" when dealing with architectural issues like these.
> Sometimes, there's no small steps to cross a given distance, it only works with a leap. I think this might be something along these lines. (edited)
> But that's just a feeling. I'll think some more about this and try to find more concrete issues and solutions related to this.
> 
> danielbachhuber [6:46 PM] 
> it's important to aways ask too: is this a solution in search of a problem?
> 
> schlessera [6:46 PM] 
> Yes, which might be the case here.
> 
> danielbachhuber [6:47 PM] 
> I think the use case "can I use this command right now?" is a valid one
> e.g. `wp export` requires a working WordPress install
> might be a good place to start

**Comment by schlessera** [comment]
I have currently two specific use cases for the above issue. They are both from the Bootstrap refactor, as this makes the loading of commands more flexible, and thus is more dependent on specifying loading order.

1. The test `Removing a subcommand should remove it from the index` from `features/command.feature`.
This test tries to remove the `comment` subcommand and asserts that it has gone from the list of available commands in the help screen

2. The test `Installed packages work as expected` from `features/runcommand.feature`.
This test tries to install the `scaffold package` subcommand through the package manager and asserts that the command appears on the list of available commands in the help screen.

Both of these currently fail with the bootstrap refactor due to loading order. The subcommands get removed/added when the main command they depend on has not yet been loaded and added.

While thinking about these, I devised very basic mechanism that should solve the above cases and that satisfies the following conditions:

- It fits within the current architecture without introducing a new concept.
- It is backwards-compatible.
- It is optional, and code can still keep using the current approach (as long as it is working as expected).
- It allows for both the loading of commands/subcommands in the correct order as well as deactivating commands that don't make sense in the given context.

The mechanism would just be an extension of the hooks system, adding before and after hooks to each `add_command()` call, with the name of the command as a suffix: `before_add_command:<command>` and `after_add_command:<command>`.

The `after_add_command:<command>` hook can be used to define loading order. So, for the use case 1. above, we would solve it by attaching the `remove_command()` call to `after_add_command:comment`.

Th `before_add_command:<command>` hook can be used to check requirements. The hook should get a reference to a value that defines whether WP-CLI should proceed with the loading or not. For example, we could have the callback return a `WP_Error` for the `db` command if the database configuration cannot be read. The error string would then be shown as the reason within the help screen, as illustrated in the above mock screenshot.

The only change we would need is to allow the `do_hook()` to pass arguments to the hooks. If these are passed by reference, they can be used as a kind of return value as well. This can easily be done in a way that won't break existing code.

**Comment by danielbachhuber** [comment]
> The `before_add_command:<command>` hook can be used to check requirements. The hook should get a reference to a value that defines whether WP-CLI should proceed with the loading or not.

👍 Sounds neat.

> The only change we would need is to allow the `do_hook()` to pass arguments to the hooks. 

I think @aaemnnosttv would like this too.

**Comment by aaemnnosttv** [comment]
This looks like a great idea! `do_hook()` can already pass arguments to its callbacks as of #3470 ;)

**Comment by danielbachhuber** [comment]
> `do_hook()` can already pass arguments to its callbacks as of #3470

How quickly my brain cells die.

**Comment by schlessera** [comment]
In defense of your brain, the corresponding documentation is missing => https://github.com/wp-cli/wp-cli/issues/4028

**Comment by schlessera** [comment]
For the hook name, we need to decide on a way to encode command/subcommand relationships.

So, for example, for the hook that adds the subcommand `scaffold package`, these would be straight-forward options:

1. `before_add_command:scaffold:package` - keeps the colon as the separator
2. `before_add_command:scaffold/package` - has the slash as the command relationship separator, keeping it separate from the hook separator
3. `before_add_command:scaffold.package` - has the dot as the command relationship separator, keeping it separate from the hook separator

Any preference? Any additional options that make sense?

**Comment by aaemnnosttv** [comment]
Does it need to be encoded? Other hooks currently preserve the space such as `before_invoke:{$cmd}`

**Comment by schlessera** [comment]
Hmm, if that works in all cases. Given the command-line environment, I'm very paranoid about spaces... :)

**Comment by aaemnnosttv** [comment]
I like the dot syntax, and agree with the paranoia but I am using this hook in it's current form so be careful to change it :)

**Comment by danielbachhuber** [comment]
`before_invoke:` uses `before_invoke: scaffold package`, so we should continue with spaces.

**Comment by schlessera** [comment]
Yes, I already made the change.

The system is basically done, I just need to wait for https://github.com/wp-cli/wp-cli/issues/4030 to be merged.

**Comment by schlessera** [comment]
The hooks are now in, and this type of simple dependency resolution should work.

However, I'd like to look further into providing feedback like in the mockup above about why a command might not be available. The `before_add_command:<command>` hook passes a `WP_CLI\Dispatcher\CommandAddition` object to the callback, which has an `abort( $reason )` method.

I'm thinking about adding a new command object for this, something like `WP_CLI\Dispatcher\DisabledCommand`. When preparing the help screen, we can then still cycle over all commands, but provide different output for the disabled ones. They should also not be available to be actually run.

What do you think?

**Comment by schlessera** [comment]
Created new issue: #4035
