### ISSUE TITLE
Can't run help commands in docker/alpine because imcompatible less options

### ISSUE THREAD

**Issue by sir-gon** [wp-cli/wp-cli#3840]
I'm getting this output trying to see wp-cli help.

```
/var/www/html # wp --allow-root help
less: unrecognized option: r
BusyBox v1.24.2 (2016-11-01 12:56:05 GMT) multi-call binary.

Usage: less [-EIMmNSh~] [FILE]...

View FILE (or stdin) one screenful at a time

	-E	Quit once the end of a file is reached
	-I	Ignore case in all searches
	-M,-m	Display status line with line numbers
		and percentage through the file
	-N	Prefix line number to each line
	-S	Truncate long lines
	-~	Suppress ~s displayed past EOF
```

I'm running in a custom images based on php:7-fpm-alpine.
Googling, I found the same issue in this (another) project: https://github.com/pry/pry/issues/1494#issuecomment-162336567

They has a workaround, but is possible to make wp-cli more compatible?

**Comment by danielbachhuber** [comment]
Have you tried setting the `PAGER` environment variable?

See https://github.com/wp-cli/wp-cli/blob/cd4d6e27005db5415a4ac3da68f883e3d65ccc95/php/commands/help.php#L96

**Comment by sir-gon** [comment]
Yes, i'm using the following to run a shell of my docker:

`docker exec -it www_php_1 /bin/sh -c "export TERM=xterm; export PAGER='busybox less'; exec sh"`

Works, but... is just a workaround.

**Comment by danielbachhuber** [comment]
Ok. That's what the `PAGER` environment variable is there for.

**Comment by vovimayhem** [comment]
For those of you suffering from a scrambled output when using `busybox less` as a value for the `PAGER` env variable, use `more` instead. Works beautifully!

(Thanks to @jeffyjefflabs for the tip used in nbgallery/jupyter-docker@e471c470f4bc906c6763cf9a9232386c6c741f9f)
