### ISSUE TITLE
Activate flag ignored when trying to install a language that already exists

### ISSUE THREAD

**Issue by fjarrett** [wp-cli/wp-cli#3843]
If a language already happens to be installed and you run:

```
$ wp core language install de_DE --activate
Warning: Language already installed.
```

The command exits at the warning, and the language is never activated.

This is contrary behavior to how other `install` commands operate in similar scenarios:

```
$ wp plugin install akismet --activate
Warning: akismet: Plugin already installed.
Activating 'akismet'...
Plugin 'akismet' activated.
Success: Plugin already installed.
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @fjarrett.

I *think* this is actually a bug in `wp plugin install`. `wp plugin install <slug> --activate` is meant to be functionally equivalent to `wp plugin install <slug> && wp plugin activate <slug>`, which will halt if the first command fails.

But, it appears this incorrect behavior for `wp plugin install` has been around for a while, so I don't think we can change it at this point.

It's also worth noting `wp plugin install` accepts one or more plugin slugs, while `wp core language install` only accepts one language. Fundamentally, this is why the difference in behavior exists.

I don't have a strong opinion on which direction to take. @schlessera Second opinion?

**Comment by fjarrett** [comment]
Thanks @danielbachhuber,

> ... which will halt if the first command fails.

That makes a lot of sense for actual installation failures. And not to broaden the scope here too much, but I'd argue that if the goal is to install something, and that thing already installed, then it's not really a blocking failure.

And if you really did need to treat it as one, you would just do:

```
wp plugin is-installed <slug> || { wp plugin install <slug> && wp plugin activate <slug> }
```

Of course `wp core language is-installed` doesn't exist yet. So maybe that's a spin-off issue.

**Comment by danielbachhuber** [comment]
> And not to broaden the scope here too much, but I'd argue that if the goal is to install something, and that thing is already installed, then it's not really a blocking failure.

That's a fair assessment. Let's consider the current behavior a bug then, and get it fixed.
