### ISSUE TITLE
Automatically run `composer update` on a regular interval

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3847]
To date, I've been running `composer update` manually (e.g. #3809)

After our commands are split out into discrete packages (#3728), it would be nice to have a bot that runs `composer update` on a regular interval (nightly?) and generates a PR when there are changes.

Ideally, the commit message and PR would be in the same format as I've been following, so it's easy to track what's changed.

**Comment by schlessera** [comment]
The package I suggested to add in #3877 includes an auto-commit feature that commits any changes on `composer update` whenever package versions changed: https://github.com/pyrech/composer-changelogs/blob/master/doc/autocommit.md

**Comment by schlessera** [comment]
As noted in Slack, you might want to take a look at https://github.com/pyrech/composer-changelogs/blob/master/doc/autocommit.md for this ticket.

**Comment by danielbachhuber** [comment]
@schlessera One thing I ran into: Because `composer-changelogs` is `require-dev`, it's not available when I run `composer update --no-dev`. Any ideas how to address this?
