### ISSUE TITLE
wp core multisite-install creates site and blogs table id mismatch

### ISSUE THREAD

**Issue by mmarcotte** [wp-cli/wp-cli#3849]
Using wp-cli 1.1.0 

Having problems all of a sudden with the `wp core multisite-install` command. After running it, the resultant DBs do not get created properly. The keys are off, and subseuent wp cli calls fail with this message: Error: One or more database tables are unavailable. The database may need to be repaired.

Now, I know it's one of your common problems, but you offer no solution. This had been working prior to the 4.7.2 upgrade and the wp cli upgrade.

Here's the step-by-step after the DB was created:

```
$ /usr/bin/wp core multisite-install --url=mm11.staging.example.com --title="Management Site" --admin_user=admin --admin_email=admin@example.com --admin_password='password' --path=/wpdata/clients/example/
Created single site database tables.
Set up multisite database tables.
Success: Network installed. Don't forget to set up rewrite rules.
$ mysql -uxxxx -pxxxx -hxxxx mm11 -A
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 290240
Server version: 10.1.17-MariaDB MariaDB Server

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [mm11]> select blog_id, site_id, domain, path from WBPNblogs;
+---------+---------+-----------------------------------+------+
| blog_id | site_id | domain                            | path |
+---------+---------+-----------------------------------+------+
|       3 |       1 | mm11.staging.example.com | /    |
+---------+---------+-----------------------------------+------+
1 row in set (0.00 sec)

MariaDB [mm11]> select * from WBPNsite;
+----+-----------------------------------+------+
| id | domain                            | path |
+----+-----------------------------------+------+
|  3 | mm11.staging.example.com | /    |
+----+-----------------------------------+------+
```

Shouldn't site_id `3` in the WBPNblogs table? That's the association with the rest of my functional blogs. I think it's just defaulting to 1 because it's the first one. For now I can write a workaround that cleans this up post install, but it seems like a straightforward fix.

**Comment by schlessera** [comment]
Your database schema seems off. The `site_id` is the ID of the "network" within a "multi-network" (a network of multiple multisites) install of WordPress (which is not supported out of the box yet). For a normal multisite install (a network of multiple single sites), you should only have 1 single `site_id` (=1), and it should point to the root domain of the multisite install.

So, what you would want to see is this (note the ID _and_ the domain):
```
MariaDB [mm11]> select * from WBPNsite;
+----+-----------------------------------+------+
| id | domain                            | path |
+----+-----------------------------------+------+
|  1 | staging.example.com               | /    |
+----+-----------------------------------+------+
```

**Comment by danielbachhuber** [comment]
@mmarcotte Can you reproduce this issue on a brand new WordPress install, and share the reproduction steps?
