### ISSUE TITLE
Test suite for abstracted command package runs against wrong code

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3850]
Houston, we have a problem.

When a command is abstracted out to a separate package (#3728), its test suite is **incorrectly run against the version of the command included in the current WP-CLI nightly build**, _not_ the version of the command in the package repository.

To illustrate, here's a PR that should fail its tests, but doesn't: https://github.com/wp-cli/cron-command/pull/3

In this example:

* `bin/install-wp-tests.sh` downloads `wp-cli-nightly.php` from GitHub, for use in the test suite: https://github.com/wp-cli/cron-command/blob/master/bin/install-package-tests.sh#L21
* `wp-cli-nightly.php` includes a copy of `class Cron_Command` from the point at which the Phar package was built.
* Because the nightly's copy of `class Cron_Command` is autoloaded before the package repository's copy, the test suite is run against `wp cron *` present in the nightly build, not that represented by the code in the repository.

The expectation is that the repository's copy of `class Cron_Command` is registered over the nightly's copy.

Open to all sorts of creative ideas for how we should address this issue.

**Comment by danielbachhuber** [comment]
Couple of bad ideas I've had already:

**1. Monkey with spl autoload priority**

If we could somehow monkey with spl autoload's priority, we could autoload the package repository copy of `class Cron_Command` before the WP-CLI nightly version. But, we can't, because:

1. There isn't a way to modify the spl autoload priority. The callbacks are run in the order they're registered, and WP-CLI's is registered first.
1. The autoloader for the WP-CLI nightly build is called much earlier than packages are loaded.

**2. Dynamically create a second class**

If the copy of the class remained as `class Cron_Command` within the WP-CLI nightly build, then the package could run `WP_CLI::add_command( 'cron', 'WP_CLI\Commands\Cron' );` to override it.

We'd need WP-CLI's autoloader for packages to `eval( str_replace( file_get_contents() ) )` (or some other such amazingly hackery) in order to dynamically create this second class without having two actual classes.

**Comment by schlessera** [comment]
How about this:

**3. Use both as dependencies to determine order**

Create a separate `composer.json` for testing, that includes both the package to test as well as WP-CLI nightly as dependencies, in that order. This will create one common autoloader where the package to test is in front of WP-CLI nightly. Then we can create a kind of bootstrap file that first loads that common autoloader and then kicks off the tests.

**Comment by danielbachhuber** [comment]
> Create a separate `composer.json` for testing, that includes both the package to test as well as WP-CLI nightly as dependencies, in that order.

Could work, but it would only solve the problem for testing. Ideally, you could `wp package install wp-cli/cron-command` and have the installed package overload the bundled version.

**Comment by schlessera** [comment]
Well, as far as I understood, the functionality will be removed from the main package within the source code, and would only be provided by the bundled PHAR version. The bundled PHAR would already contain the external Composer package, so a `wp package install wp-cli/cron-command` would not do anything. However, the bundled PHAR would at that point already come with the previously tested Composer version.

So, if I understood correctly, the problem is limited to finding a way to test commits to the external package against a WP-CLI nightly that already comes bundled with that same package in a pre-commit version.

**Comment by danielbachhuber** [comment]
> The bundled PHAR would already contain the external Composer package, so a `wp package install wp-cli/cron-command` would not do anything.

Incorrect. There are two `composer.json` files, one for WP-CLI and one for installed packages. The packages autoloader is loaded much later: https://github.com/wp-cli/wp-cli/blob/90332c4399f99b6a52a6fbcfd2662df880891808/php/WP_CLI/Runner.php#L811

> So, if I understood correctly, the problem is limited to finding a way to test commits to the external package against a WP-CLI nightly that already comes bundled with that same package in a pre-commit version.

The scope of the problem is both testing and general usage.

**Comment by schlessera** [comment]
> Incorrect. There are two composer.json files, one for WP-CLI and one for installed packages. The packages autoloader is loaded much later: https://github.com/wp-cli/wp-cli/blob/90332c4399f99b6a52a6fbcfd2662df880891808/php/WP_CLI/Runner.php#L811

Not sure we are talking about the same thing here.

What is the expected behaviour when you run `wp package install wp-cli/cron.command` when the cron command is already installed as a package. I would say that the expected behaviour should be that you get a message that the package is already installed, and no change is made.

The more interesting question would be whether you can run a `wp package update wp-cli/cron.command` to update an external more recent version of the cron package over an outdated bundled version.

In that case I would say that the expected behavior should be that the outdated cron package is replaced by the up-to-date cron package, and that later calls to `wp cron` would make use of the updated package.

Conceptually, I would like to see WP-CLI as the framework only come with the `wp package` command built in. All of the other commands should be external packages, but some of them could be bundled with the PHAR release. So, WP-CLI-the-framework is a package manager for WordPress command-line commands. Within this concept, there should be no direct technical difference between a command that was already installed (or bundled in PHAR) and a command that is added later on via the `wp package install` command.

Assuming the above assumptions would be true, tests for external commands would need to be either done against a Composerized version of WP-CLI, or add the WP-CLI PHAR nightly as I suggested above as a second autoloader after the actual command to test.

**Comment by schlessera** [comment]
Just a note about an implementation detail:
We can provide a "meta" Composer package that defines the commands to be bundled. This would then be used by the PHAR build process, and it could also be used by people wanting to quickly install WP-CLI through Composer with a basic set of commands.

**Comment by danielbachhuber** [comment]
WP-CLI has two composer.json files: one for the project, and one for installed packages.

The project's `composer.json` is tracked in the `wp-cli/wp-cli` repo. The installed packages `composer.json` is created in `~/.wp-cli/packages/` the first time you run `wp package install`.

When `wp-cli/cron-command` is added as a dependency for the former, it can still be used for the latter, because there's no reconciliation process between the two.

> What is the expected behaviour when you run `wp package install wp-cli/cron.command` when the cron command is already installed as a package?

The expected behavior is that `wp-cli/cron-command` installs as a package, and supersedes the bundled version.

The actual behavior is that `wp-cli/cron-command` installs as a package, but does not supersede the bundled version.

> The more interesting question would be whether you can run a `wp package update wp-cli/cron.command` to update an external more recent version of the cron package over an outdated bundled version.

I'm not sure how this would be possible, given the files for the bundled version are injected into the Phar file.

> Conceptually, I would like to see WP-CLI as the framework only come with the wp package command built in. All of the other commands should be external packages, but some of them could be bundled with the PHAR release.

I agree.

> Within this concept, there should be no direct technical difference between a command that was already installed (or bundled in PHAR) and a command that is added later on via the wp package install command.

But there is a technical difference. You should inspect how the Phar is currently built:

* https://github.com/wp-cli/wp-cli/blob/master/utils/make-phar.php#L62

When the Phar is built, all of the projects files (dependencies included) are rolled in to a single `wp-cli.phar`.

Later, when you run `wp package install <package-name>`, a new Composer project is created in `~/.wp-cli/packages/`, and the Phar file loads the autoloader midway through the bootstrap process.

**Comment by schlessera** [comment]
The current code contains this in [`WP_CLI\Runner::start()` line 807-809](https://github.com/wp-cli/wp-cli/blob/v1.1.0/php/WP_CLI/Runner.php#L807-L809):
```
		// Load bundled commands early, so that they're forced to use the same
		// APIs as non-bundled commands.
		Utils\load_all_commands();
```

Of course, forcing to loading bundled versions is a major problem in the context of this ticket.

@danielbachhuber, can you elaborate on the comment in that snippet? What was the problem that this force-loading was meant to solve?

**Comment by schlessera** [comment]
I probably still ignore why you wanted to force load bundled commands early. Provided that whatever reason there is can be dealt with in a different manner, it would probably be fairly simple to turn the loading around so that the package commands are loaded first, and then the bundled commands are loaded wherever they have not been replaced by a packaged command yet. In this way, package-installed commands would take precedence, with a fall back to the bundled versions.

**Comment by schlessera** [comment]
When we swap around the loading of the commands in this way, we can avoid loading the autoloader for the bundled commands up until the point where the autoloader for the packaged commands has already been loaded, and all the packaged commands have already been registered.

**Comment by danielbachhuber** [comment]
> can you elaborate on the comment in that snippet? What was the problem that this force-loading was meant to solve?

What history have you dug up by using blame? (Not to dodge the question, but I think it's generally a good step to look through the history first)

> Provided that whatever reason there is can be dealt with in a different manner, it would probably be fairly simple to turn the loading around so that the package commands are loaded first, and then the bundled commands are loaded wherever they have not been replaced by a packaged command yet. In this way, package-installed commands would take precedence, with a fall back to the bundled versions.

Right, although bundled commands that are Composer packages are autoloaded right now with autoload file. This happens earlier in the bootstrap process: https://github.com/wp-cli/wp-cli/blob/v1.1.0/php/wp-cli.php#L19

**Comment by schlessera** [comment]
I found the initial addition of the loading code, but it didn't come with an issue number: https://github.com/wp-cli/wp-cli/commit/782a6b71f2382ebb29614bfb8f441bd8e0f3ff5a

In the `WP_CLI\Utils\load_dependencies()` function, we could probably already check whether there's a home folder autoloader, and load this one first. I'll try to summarize the bootstrap process:

1. Set up environment, and where main WP files are
2. Load package autoloader
3. Load WP_CLI autoloader
4. Load PHAR hardcoded autoloader
5. Register package management
6. Register packaged commands
7. Register PHAR hardcoded commands that haven't been registered through packaged commands yet

**Comment by schlessera** [comment]
Found a bit of information for the commit that changed the `load_command()` to `load_all_commands()`:
```
Also modifies the bootstrap process to always register commands, instead
of lazyloading them based on command name. Packages and required
commands are always loaded, so we should follow similar behavior with
core commands.
```

**Comment by danielbachhuber** [comment]
> I found the initial addition of the loading code, but it didn't come with an issue number: 782a6b7

At the top of every changeset, you can see which pull request it came from:

![Image](https://dl.dropboxusercontent.com/s/p0ebnez3iqxjx7v/2017-02-28%20at%2011.15%20AM.png)

Some more load history #468

> In the `WP_CLI\Utils\load_dependencies()` function, we could probably already check whether there's a home folder autoloader, and load this one first. 

This is the direction I'm headed too.

_However_, commands can also be loaded via the `--require=<file>` global argument. This is, in part, how the test suite loads the code in the package repository: https://github.com/wp-cli/cron-command/blob/v1.0.0/features/bootstrap/FeatureContext.php#L12-L31

So, another annoying thing to accommodate, but it seems doable.

**Comment by schlessera** [comment]
Yes, indeed. I would assume that we need to have the autoloaded be active before loading the `--require` file, as it will probably make use of previously defined classes.

So, updated summary:

1. Set up environment, and find out where main WP files are
2. Load package autoloader
3. Load WP_CLI autoloader
4. Load PHAR hardcoded autoloader
5. Register package management
6. Load `--require` file (in case this is an autoloader, it will not be able to override the autoloaders under 2., 3. & 4.)
7. Register packaged commands that have not been registered through `--require` yet
8. Register PHAR hardcoded commands that haven't been registered through either `--require` or the packaged commands yet

**Comment by danielbachhuber** [comment]
I think your updated summary is more or less correct.

Another potential challenge is that packages can implicitly depend on classes present in WP-CLI. We may need to register the two class autoloaders (packages, and WP-CLI), and then run each instances autoload file.

Might be time to start exploring through code.

**Comment by schlessera** [comment]
Do you want me to have a go at this in a pushed branch? Seems like a good way to get more intimate with the code... ;)

**Comment by danielbachhuber** [comment]
> Do you want me to have a go at this in a pushed branch? Seems like a good way to get more intimate with the code... ;)

Go for it!

**Comment by schlessera** [comment]
The following scenarios should be covered by the tests to reliably make changes to the bootstrap process:

_To test normal code changes:_
- [x] Git WP-CLI -> override command with `--require`
- [x] Git WP-CLI -> override command with `package install`

_To test for regressions:_
- [x] Downloaded PHAR WP-CLI -> override command with `--require`
- [x] Downloaded PHAR WP-CLI -> override command with `package install`

_To test new bundled builds:_
- [ ] PHAR from Git WP-CLI -> override command with `--require`
- [ ] PHAR from Git WP-CLI -> override command with `package install`

**Comment by schlessera** [comment]
I have completed the test suite that should cover the possible bootstrap interactions for overriding commands.

At this time, one single test scenario fails: `Composer stack with override requirement before WP-CLI`

This is the scenario that should cover what we want to achieve for the tests of the external commands, as discussed above.

I will now proceed to make changes to the bootstrap process, all the while running the changes through all the tests that are tagged with `@bootstrap`.

@danielbachhuber Can you confirm that the above makes sense?

**Comment by danielbachhuber** [comment]
> Can you confirm that the above makes sense?

I *think* so, although I don't see any class definition as a part of the tests...

**Comment by schlessera** [comment]
I do think that the `"files"`already checks for Composer autoloader order, but I agree that it would probably be safer to also add classes with a PSR-4 autoloader as well.

**Comment by schlessera** [comment]
One bigger issue I am facing is the early need for `cli\Shell` class located in a Composer package, as I want to load the actual WP_CLI autoloader only after having loaded the package autoloaders.

Dependencies involved:
package autoloaders -> logging
logging -> colorization
colorization -> `cli\Shell::isPiped()`

To get around this issue for now, I will add `cli\Shell::isPiped()` to `WP_CLI\Utils\isPiped()` (it is currently being used in 2 places).

Once I've gone through a working refactor, we'll need to rediscuss some of the code layout either way.

**Comment by danielbachhuber** [comment]
> The main issue is that the Composer-required packages will need to have the framework autoloader be available already, to make use of the framework API. However, this framework autoloader is the exact same one that has the bundled commands and hence their autoloader.

Yep, this is about the core of the issue.

> One idea would be to have a Composer plugin hook into the autoloader generation and filter out the commands from the normal `vendor/autoload.php` and put them into a separate `vendor/autoload-commands.php`.

This seems like a viable direction to explore. 

Can you turn your branch into a WIP pull request, so it's easier to review the scope of the changes?

**Comment by schlessera** [comment]
I think the splitting of the autoloader works pretty much as expected. I could iron out most of the issues now, except for a rather annoying YAML issue. The YAML library that is being used in the `WP_CLI\Configurator` is procedural code, not class-based. As the splitting of the autoloader can only be done per class, this is not loaded with the framework code.

We already have the Symfony YAML library included as a dependency as well, and I wonder why that one is not being used. It would solve this issue, as Symfony is strictly OOP.

**Comment by danielbachhuber** [comment]
@schlessera I made a really happy (re)discovery in the last 24 hours.

When WP-CLI is installed as a dependency to a WP-CLI package (e.g. https://github.com/wp-cli/package-command/pull/2), Composer treats the WP-CLI package as the resolution for WP-CLI's declared dependency for it.

I originally discovered this in #2546, but had forgotten about it / didn't realize it applied to this use case.

As such, by switching all of the bundled commands to https://github.com/wp-cli/scaffold-package-command/pull/89, we'll also solve the original stated problem:

> Test suite for abstracted command package runs against wrong code

If #3872 doesn't have any significant blockers, I think it'd still be worthwhile to land.

**Comment by schlessera** [comment]
Yes, but I thought the problem came from using a PHAR while testing? Won't we ever have the need to make this work with PHARs?

**Comment by danielbachhuber** [comment]
> Yes, but I thought the problem came from using a PHAR while testing?

It did, yes.

> Won't we ever have the need to make this work with PHARs?

Probably yes, but it's no longer the `omgwtfbbq` blocker for proceeding with #3728 (and actually improving upon the packages).

**Comment by danielbachhuber** [comment]
This is 🔨 for the problem originally defined in the issue. Landing the new bootstrap PR will enable this for Phar builds too.
