### ISSUE TITLE
Error: Failed to get latest version (HTTP code 403).

### ISSUE THREAD

**Issue by strarsis** [wp-cli/wp-cli#3853]
When trying to update wp cli by running `wp cli update` as root (using sudo), update fails with error:
````
Error: Failed to get latest version (HTTP code 403).
````
wp is located at '/usr/local/bin/wp', is executable (chmod +x as in the installation instructions).

**Comment by danielbachhuber** [comment]
@strarsis Do you have another system on the machine making calls to the GitHub API?

**Comment by dws122** [comment]
what was the resolution to this error message? 
receiving the same error message on one of our servers when attempting to update WP-CLI from 1.4.0 to 1.5.0

all other servers updated properly
![3__root_tmwsp01____ssh_](https://user-images.githubusercontent.com/12969150/35627575-49769cd8-0667-11e8-98d4-5552ebedddf7.png)

**Comment by danielbachhuber** [comment]
@dws122 I think this is because @schlessera forgot to upload the executable to the release. Can you test again?

**Comment by dws122** [comment]
@danielbachhuber worked now. thanks!

**Comment by p810** [comment]
I'm getting this issue when running `wp cli check-update` and `wp cli update` with 2.0.1 and 2.4.0.

I have 2.0.1 installed in my local bin directory and installed 2.4.0 with Composer in a test directory. I just checked and it looks like the Phar wasn't uploaded with 2.4.1.

**Comment by evantill** [comment]
Same problem here. The problem seems due to API rate limit exceeded.

I need to update around 40 installations. 

```shell
xxx@xxx:~$ wp cli info
OS:	Linux 4.9.0-0.bpo.9-amd64 #1 SMP Debian 4.9.168-1+deb9u3~deb8u1 (2019-06-17) x86_64
Shell:	/bin/bash
PHP binary:	/xxx/xxx/php/7.2/bin/php
PHP version:	7.2.31
php.ini used:	/xxx/xxx/php/7.2/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/vhosts/xxx
WP-CLI packages dir:	/var/www/vhosts/xxx/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:	/var/www/vhosts/xxx/wp-cli.yml
WP-CLI version:	2.4.0
xxx:~$
```

```shell
wp cli check-update
Error: Failed to get latest version (HTTP code 403).
```

**Testing with wget give more informations**
```shell
xxx@xxx:~$ wget -S -O - https://api.github.com/repos/wp-cli/wp-cli/releases?per_page=100
--2020-06-08 18:07:12--  https://api.github.com/repos/wp-cli/wp-cli/releases?per_page=100
Resolving api.github.com (api.github.com)... 140.82.118.6
Connecting to api.github.com (api.github.com)|140.82.118.6|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 403 rate limit exceeded
  Date: Mon, 08 Jun 2020 18:07:12 GMT
  Server: Varnish
  Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
  Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
  Content-Type: application/json
  X-Ratelimit-Limit: 60
  X-Ratelimit-Remaining: 0
  X-Ratelimit-Reset: 1591640660
  Content-Length: 249
  X-GitHub-Request-Id: DAD8:E719:4B3C1D1:59C8957:5EDE7E50
2020-06-08 18:07:12 ERROR 403: rate limit exceeded.

**Comment by stevus** [comment]
Why was this closed? I'm still experiencing this issue when trying to update to 2.5.0.

**Comment by stevus** [comment]
@danielbachhuber please reopen this as it is not resolved

![image](https://user-images.githubusercontent.com/1261603/118846173-7279ee80-b89a-11eb-9e83-fd6278fbcd50.png)
