### ISSUE TITLE
Apply standard repository settings across all WP-CLI repos

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3857]
Now that we're abstracting internal commands to separate repos (#3728), we should:

1. [x] Identify which repo settings need to be common across all projects (e.g. `master` as a protected branch).
2. [x] Automate the application of the repo settings.

Common repo settings:

* [x] Description: Composer description + top-level commands

https://github.com/bkeepers/github-configurer looks like a neat option for the latter.

**Comment by danielbachhuber** [comment]
Oh, https://github.com/probot/probot looks even cooler

**Comment by schlessera** [comment]
Although the labels might differ between the packages (as they also include the scope), the coloring for the shared labels should be made consistent.

Note the `good-first-issue` label in the screenshot below:

<img width="758" alt="screenshot 2017-04-28 09 58 55" src="https://cloud.githubusercontent.com/assets/83631/25519803/9b6a1d10-2bf9-11e7-927a-81b3f1f0c183.png">

**Comment by danielbachhuber** [comment]
> Although the labels might differ between the packages (as they also include the scope), the coloring for the shared labels should be made consistent.

I agree. I've been waiting to have the bot hooked up to make this change, because I've gotten tired of making it a hundred times manually.

**Comment by danielbachhuber** [comment]
Managing protected branches is blocked by https://github.com/probot/settings/issues/3

**Comment by danielbachhuber** [comment]
Label setting doesn't seem to work :(

**Comment by danielbachhuber** [comment]
🔨

**Comment by danielbachhuber** [comment]
Following up later with https://github.com/wp-cli/scaffold-package-command/issues/163
