### ISSUE TITLE
Media regeneration issue

### ISSUE THREAD

**Issue by ivankruchkoff** [wp-cli/wp-cli#3859]
It seems that the following fails when you regenerate thumbs for an image which has a dimension smaller than a registered image size:
wp media regenerate --yes --only-missing

We have two test images, a) 1000x1000 b) 627x362.

we register a size of 400x400
We fetch via media_sideload_image 

When we call:
wp media regenerate --yes --only-missing

It will always regenerate the thumbnails for b) due to:

wp eval 'print_r(array_diff( get_intermediate_image_sizes(), array_keys( wp_get_attachment_metadata(111)['sizes'] ) ));'
Array
(
    [1] => medium
    [2] => medium_large
    [3] => large
)

1 = 400x400, 2=512x512, 3=768x768
This arises in https://github.com/wp-cli/wp-cli/blob/master/php/commands/media.php#L375

**Comment by szepeviktor** [comment]
> when you regenerate thumbs for an image which has a dimension smaller than a registered image size

Do you mean the 627x362 image is smaller than 400x400?

**Comment by ivankruchkoff** [comment]
Correct :)

**Comment by ivankruchkoff** [comment]
Put out a PR for the issue: https://github.com/wp-cli/wp-cli/pull/3879

**Comment by danielbachhuber** [comment]
I think this is actually because thumbnail isn't included as an image size in `get_intermediate_image_sizes()`

I've ported this issue over to the new repository for `wp media *`: https://github.com/wp-cli/media-command/issues/2
