### ISSUE TITLE
wp-cli missed few rows while doing search and replace url

### ISSUE THREAD

**Issue by spkrn87** [wp-cli/wp-cli#3860]
We have  migrated  a standalone wp site to wp multisite , after importing the db in multisite we did search and replace the url for the site .

Initially i executed the command with "--dry-run option"  and the output shows  sucess: 1450 rows needs to be updated , But whem i executed without  "--dry-run option"  the out shows sucess: 1444 rows updated 6 rows not updated.

here what will be the issue with those 6 rows  and how can i identify those 6 rows and update those again.

**Comment by danielbachhuber** [comment]
Hi @spkrn87,

Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support
