### ISSUE TITLE
Provide suggestions for invalid parameters

### ISSUE THREAD

**Issue by khromov** [wp-cli/wp-cli#3861]
The `--dbpass` is the only flag in the `wp core config` command that is truncated. Furthermore, it is not truncated in a way users would exect (for example, my initial attempt after trying `--dbpassword` was `--dbpasswd` which also doesn't work).

I would highly recommend to add `--dbpassword` as an alias for `--dbpass` to remove this frustrating inconsistency.

**Comment by danielbachhuber** [comment]
I'm not a huge fan of adding an alias for the argument. It seems like a one-off solution to your specific problem.

What if, instead, WP-CLI guessed at which parameter you were trying to use, and offered that as a suggestion in the error message?

**Comment by szepeviktor** [comment]
```
$ git stati
git: 'stati' is not a git command. See 'git --help'.

Did you mean this?
        status
```

**Comment by khromov** [comment]
@danielbachhuber Sounds like a great idea!

**Comment by schlessera** [comment]
This is now implemented for commands, but parameters are not yet affected by this implementation.

**Comment by schlessera** [comment]
Types of user entry to implement suggestions for:
- [x] (sub)commands
- [ ] parameters
- [ ] aliases

**Comment by schlessera** [comment]
Resolved with #4004, #4008 and #4109.

**Comment by khromov** [comment]
@schlessera I'm not sure the original issue is resolved. Here is an example using WP-CLI 1.3.0:

```
#wp config create --allow-root --dbname=foo --dbuser=bar --dbpassword=baz

Error: Parameter errors:
 unknown --dbpassword parameter
```

My suggestion was to include a hint when there is a typo like this. No such hint has been implemented?

**Comment by schlessera** [comment]
@khromov You are right. While implementing the suggestion feature, we had discussed the more distant changes like these, and decided that we want to keep the threshold low, but add a pre-built dictionary of suggestion mappings instead.

Here's the issue for that: https://github.com/wp-cli/wp-cli/issues/4379

**Comment by szepeviktor** [comment]
How do git and drush do it?
Something like http://php.net/manual/en/function.levenshtein.php ?
