### ISSUE TITLE
Strange output on wp core install

### ISSUE THREAD

**Issue by khromov** [wp-cli/wp-cli#3862]
```
➜  wptest wp core install --url=http://localhost:8000 --title=WPTest --admin_user=admin --admin_email="test@test.com"
unknown: warning: valid_hostname: numeric hostname: 57434
unknown: fatal: unable to use my own hostname
Admin password: HH38w3tlTR2P
```

OS: OSX Sierra 10.12.3
Uname: Darwin 57434 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
php -v: PHP 7.0.15 (cli) (built: Jan 22 2017 08:51:45) ( NTS )
WP: 4.7.2
which -a wp: /usr/local/bin/wp
mysql --version: mysql  Ver 14.14 Distrib 5.7.17, for osx10.12 (x86_64) using  EditLine wrapper

**Comment by schlessera** [comment]
@khromov This is an issue with your local Mac setup, namely the hostname.

As you can see in the error message, your hostname seems to be set to `57434`, which is not valid. As `localhost` is resolved to this hostname you'll get the above error.

You need to properly configure a valid hostname for your Mac.
