### ISSUE TITLE
Add new sumcommand `favicon`

### ISSUE THREAD

**Issue by evilebottnawi** [wp-cli/wp-cli#3863]
It is be great to add ability to get, add, update and delete favicon for site.

**Comment by danielbachhuber** [comment]
Why not update the option?

**Comment by evilebottnawi** [comment]
@danielbachhuber option contain only ID. I need:
1. Create attachment, but if i create attachment i can't use `site_icon_image_sizes` filter there containt sizes for favicon :sob: .
2. Update option.

**Comment by danielbachhuber** [comment]
Ah, makes sense.

Can you file this in the ideas repo please? https://github.com/wp-cli/ideas/issues
