### ISSUE TITLE
Default .editorconfig for scaffold

### ISSUE THREAD

**Issue by bhubbard** [wp-cli/wp-cli#3865]
For the following commands:

https://wp-cli.org/commands/scaffold/theme-tests/
https://wp-cli.org/commands/scaffold/plugin-tests/

I would like to see it add the default .editorconfig that is used by wordpress. It may be useful to have it added when a new plugin or theme is generated as well.

**Comment by danielbachhuber** [comment]
> It may be useful to have it added when a new plugin or theme is generated as well.

👍  I think it would be generally useful to add `.editorconfig` to every theme and plugin.

**Comment by danielbachhuber** [comment]
`.editorconfig` is already added as a part of `wp scaffold plugin`, so it doesn't make sense to also include it in `wp scaffold plugin-tests`.

We can add `.editorconfig` to child themes and Underscores though.
