### ISSUE TITLE
Unable to override PHP_BINARY with WP_CLI_PHP

### ISSUE THREAD

**Issue by Steveorevo** [wp-cli/wp-cli#3867]
It appears that WP_CLI_PHP was intended to allow one to override the php binary used with wp-cli; via an environment variable. This allows one to ensure the that correct PHP interpreter is used in spawned processes (such as the "wp server" command). However, this is not possible because of the precedence given to PHP_BINARY (PHP's built-in define for the binary path) in the public static function get_php_binary() starting at line 908:

wp-cli/php/class-wp-cli.php
```
public static function get_php_binary() {
		if ( defined( 'PHP_BINARY' ) )
			return PHP_BINARY;

		if ( getenv( 'WP_CLI_PHP_USED' ) )
			return getenv( 'WP_CLI_PHP_USED' );

		if ( getenv( 'WP_CLI_PHP' ) )
			return getenv( 'WP_CLI_PHP' );

		return 'php';
	}
```

Shouldn't WP_CLI_PHP check occur before PHP_BINARY? As it is, it's impossible to override the native PHP_BINARY value, which **always exists** because we're in the PHP interpreter already. If we want to override the PHP interpreter for spawned processes or we've done something custom to our system (i.e. have multiple PHP versions installed on our system and have tweaked our PHP default binary with a bash script, or how about we simply wish to define a specific interpreter path), shouldn't WP_CLI_PHP the environment variable enable this? I do have a use case where this WP_CLI_PHP would have been helpful, but as is, it's nullified because PHP_BINARY always exists before WP_CLI_PHP.

**Comment by Steveorevo** [comment]
Submitted pull request https://github.com/wp-cli/wp-cli/pull/3868

**Comment by danielbachhuber** [comment]
> However, this is not possible because of the precedence given to PHP_BINARY (PHP's built-in define for the binary path) in the public static function get_php_binary() starting at line 908:

I did some blaming to get to the original use of this logic: 32bcd448cba0859a68118e1c2492da22b2070d08 (from #219)

> Shouldn't WP_CLI_PHP check occur before PHP_BINARY?

Yes, I think this was the original intent.

> As it is, it's impossible to override the native PHP_BINARY value, which **always exists** because we're in the PHP interpreter already.

Only as of PHP 5.4:

![image](https://cloud.githubusercontent.com/assets/36432/23511056/c6069ffa-ff10-11e6-866f-1b90a987f679.png)
