### ISSUE TITLE
May be more infos

### ISSUE THREAD

**Issue by geekoun** [wp-cli/wp-cli#3869]
Hello,

I suggest that it is necessary to explain what is a .phar via a link and to say that wp-cli uses of the php to make more curious the greenhorns.

Thx

**Comment by szepeviktor** [comment]
Hello!
You may learn what a *Phar* file is by googling: https://www.google.com/search?q=PHP+Phar+file

You will and on this page: http://php.net/manual/en/intro.phar.php

**Comment by geekoun** [comment]
Yes and no. When you make a tutoriel you give your sources.
You do not let people without a minimum guide them. And Google does not justify everything!
When you possess a lot of knowledge, I think that it is essential to share at best and to be most possible teacher, it is a responsibility.

**Comment by danielbachhuber** [comment]
Hi @geekoun,

Thanks for opening the issue. Feel free to submit a pull request with your suggested changes:

* https://github.com/wp-cli/wp-cli/blob/master/README.md
* https://github.com/wp-cli/handbook/blob/master/installing.md
