### ISSUE TITLE
wp user delete --network 898 --reassign=911  ERROR MESSAGE

### ISSUE THREAD

**Issue by wonderWomantotheResue** [wp-cli/wp-cli#3870]
Are you aware of this error? How do I get past it?
(I don't at the moment write PHP code, so I can't use/call any PHP functions --where do I get a list of them anyway?)

I get an error message that reads:
reassigning content to a different user is not supported on multisite.

**Comment by danielbachhuber** [comment]
Hi @wonderWomantotheResue,

Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support
