### ISSUE TITLE
database export name

### ISSUE THREAD

**Issue by gbcxjoe** [wp-cli/wp-cli#3873]
HI

after upgrading to version 1.1.0, when we run the database backup script, it no longer names the exported sql dump by the database name. instead, it names the file the database name plus random characters? how do I get the exported sql file named with the just the database name?

define( 'DB_NAME', 'adnas' );

example 
it the exported file was named 
adnas.sql
now its named
adnas-941e1ab.sql

for all our scripts to work, we need the exported sql file with name of the database

PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.17
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0

**Comment by gbcxjoe** [comment]
ok, i see now

sudo -u adnas/wp db export ./adnas.sql

**Comment by szepeviktor** [comment]
I've looked it up for you.
If you go to a file here on GitHub and press the <kbd>Blame</kbd> button you see:
https://github.com/wp-cli/wp-cli/commit/6302579a8b34a1a87fbc86cf3c618d4f77c48284

**Comment by szepeviktor** [comment]
To restore the old naming:
```bash
wp db dump $(wp eval 'echo DB_NAME;').sql
```

**Comment by gbcxjoe** [comment]
thanks. also found this

sudo -u annas /wp db export ./annas.sql

**Comment by schlessera** [comment]
This change was introduced to decrease the chance of SQL dumps being accessible from the web at predictable URLs, as you can see here: https://github.com/wp-cli/wp-cli/pull/3765#issue-202674584

If your scripts rely on the name to be fixed, you should change them to export to a fixed name, as @szepeviktor has already shown above.
