### ISSUE TITLE
Replace library `mustangostang/spyc` with `symfony/yaml`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3875]
The YAML config files are currently parsed by the `WP_CLI\Configurator` class using the `mustangostang/spyc`. This library is procedural code, which does not work for our current autoloading requirements.

We already have the `symfony/yaml` library included as a dependency, so we should switch all YAML parsing to be done through that library. It is OOP code, which fits in nicely with the new autoloading requirements.

**Comment by schlessera** [comment]
#3876 needs to taken care of first before switching the library.

**Comment by schlessera** [comment]
Given that #3876 can not be easily resolved without introducing major breaking change, the preferable course of action might be to either submit a patch to `mustangostang/spyc` or fork it (it is only a single file) so that we can load the `Spyc` class through the class map.

**Comment by danielbachhuber** [comment]
> the preferable course of action might be to either submit a patch to `mustangostang/spyc`

👍

**Comment by schlessera** [comment]
Closed in favor of https://github.com/wp-cli/wp-cli/issues/3882
