### ISSUE TITLE
Invalid YAML in Behat test

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3876]
The test file `features/config.feature` contains a scenario that uses invalid YAML content:

```gherkin
  Scenario: Persist positional parameters when defined in a config
    Given a WP install
    And a wp-cli.yml file:
      """
      user create:
        - examplejoe
        - joe@example.com
        user_pass: joe
        role: administrator
      """
```

The YAML is not valid according to spec version 1.2, because you can only use **either** a sequence (` - sequence_item`) **or** a mapping (`key: value`) when in a list, not both at the same time.

The library that is currently being used only supports the outdated YAML spec 1.0 and does not care about this issue.

However, in light of #3875 , we should support proper YAML 1.2 syntax only.

**Comment by schlessera** [comment]
If I understand the specs correctly, this is even a bug in the Spyc library with the YAML 1.0 spec, so the proper resolution would be to get rid of such notations.

However, the way WP-CLI parses the YAML into command line arguments seems to heavily rely on this bug, so a change would very probably break lots of real-world usage.

**Comment by danielbachhuber** [comment]
@schlessera I'd suggest `wontfix` at this point. I don't think it's worth the effort getting into the weeds of unwinding this problem.

**Comment by schlessera** [comment]
Yes, agree.
