### ISSUE TITLE
Improve Composer update change logs

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3877]
As we directly use the output of the Composer Update command in the commit messages, we should consider adding the package [pyrech/composer-changelogs](https://github.com/pyrech/composer-changelogs) to the development requirements, to make them more useful.

![Demo](https://github.com/pyrech/composer-changelogs/raw/master/doc/demo.gif)

**Comment by danielbachhuber** [comment]
👍 

Related #3847

**Comment by schlessera** [comment]
Related pull request: https://github.com/pyrech/composer-changelogs/pull/44
