### ISSUE TITLE
Fatal error, Class already declared in the bedrock

### ISSUE THREAD

**Issue by mostafasoufi** [wp-cli/wp-cli#3878]
Hi @danielbachhuber,

I used `wp media regenerate 278359`  command and i get bellow error:

`Fatal error: Class already declared: Comment_Command in phar://wp-cli.phar/php/commands/comment.php on line 27`

It's seems All everything is good. Even I've checked some parameter like `--force` & `--skip-plugins` But it did not anything change.

Note. I used bedrock structure for handling the wordpress 

Regards

**Comment by danielbachhuber** [comment]
Hi @mostafasoufi,

Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support
