### ISSUE TITLE
Make `Spyc` class in `mustangostang\spyc` package autoloadable.

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3882]
Part of the solution for #3850 is to make the code properly autoloadable and register the different autoloaders in a controlled order.

For this to work properly, the `Spyc` class needs to be modified so that it can be autoloaded through Composer without side effects.

See https://github.com/mustangostang/spyc/issues/65

**Comment by danielbachhuber** [comment]
I don't think the upstream repo is actively maintained. I'm amenable to handling this with a temporary downstream fork for the time being.

**Comment by danielbachhuber** [comment]
> I'm amenable to handling this with a temporary downstream fork for the time being.

Created a fork: https://github.com/wp-cli/spyc

**Comment by danielbachhuber** [comment]
This landed in #3872
