### ISSUE TITLE
Capture and report anonymized usage statistics

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3886]
To help us better understand how WP-CLI is used, it would be helpful to capture and report anonymized usage statistics. This data would be captured into Google Analytics.

These metrics could include:

* WP-CLI version.
* WP-CLI installation type (Phar vs. Composer)
* PHP version.
* WordPress version (for the commands interacting with WordPress directly).
* Frequency of internal command usage (e.g. we don't care about custom commands).
* Execution time for internal commands.
* Whether a command is being run by an end user or a machine (e.g. system cron or provisioning system).

To gain sufficient data, reporting would be opt-out (e.g. on by default, disable with a `WP_CLI_DISABLE_USAGE_ANALYTICS` environment variable).

Some prior art:

* https://github.com/Homebrew/brew/blob/master/docs/Analytics.md
  * https://github.com/Homebrew/brew/blob/e116ba196e2834025c713a2a566e0e150907d6d0/Library/Homebrew/utils/analytics.sh#L70-L123
* https://github.com/atom/metrics#collected-data
  * https://github.com/atom/metrics/issues/16

Your feedback is welcome! Specifically:

* In addition to the data points listed, what others might be worthwhile to capture?
* Are there other aspects to the project we should consider?

**Comment by joshkoenig** [comment]
+1 seems legit.

**Comment by mwithheld** [comment]
Suggestions for security -- don't capture data hackers could use, e.g. :

- IP, hostname, url, username running the processes
- Some parameter values, config values

The more info is released, the more likely admins are to opt out.

You might want to re-assure why admins should trust releasing data rather than opting out.

**Comment by danielbachhuber** [comment]
> Suggestions for security -- don't capture data hackers could use, e.g. :

I agree. Definitely not planning to capture any data that could be personally identifiable.

**Comment by fjarrett** [comment]
Hey @danielbachhuber, a few questions:

1. Will this result in outbound HTTP requests for every command executed?
2. Will the values passed to `$args` and `$assoc_args` always be ignored?

> wp user update ~1 --user_pass=mysecret --user_email=myprivate@email.com~
> wp option update ~my_social_security_number 123-45-6789~

**Comment by aaronjorbin** [comment]
Some events and what I would hope to discover

1. wp help calls ( what commands generate the most documentation views? Could those commands be made better?)
1. skip-plugins / skip-themes (in order to discover if there are any plugins/themes commonly skipped and thus there is a need to work with the team/people behind them)
1. `not a registered subcommand` and `not a registered wp command` triggers.  (Could help find common misspellings/mistypes that the system should handle with grace or potentially inspire new commands)

**Comment by danielbachhuber** [comment]
Good questions.

> 1. Will this result in outbound HTTP requests for every command executed?

Implementation is still TBD, but it will be done with performance in mind. Could happen on shutdown, or written to a log file that's periodically pushed in batch.

> 2. Will the values passed to `$args` and `$assoc_args` always be ignored?

Yes. We may capture which arguments you use, but not the values you pass to them.

**Comment by danielbachhuber** [comment]
Great suggestions, @aaronjorbin 

> 3. not a registered subcommand and not a registered wp command triggers. (Could help find common misspellings/mistypes that the system should handle with grace or potentially inspire new commands)

Related https://github.com/wp-cli/wp-cli/issues/3861

**Comment by danielbachhuber** [comment]
@schlessera I'd actually like to try to land this in 1.2.0 so we have the data sooner rather than later.

We should only capture use of public commands from the WP-CLI organization. Thoughts on how we can easily whitelist these in a maintainable way?

**Comment by schlessera** [comment]
@danielbachhuber If we want to have an automated way, we can make use of Composer, as that is the component that pulls in the bundled commands. Also, we're forced to keep this up-to-date, as the failure to do so will break the full Phar test-suite we're working on.

As an example, here's the data that Composer currently generates in `vendor/composer/autoload_commands_classmap.php`:

<details>
<pre>
    'CLI_Command' => $baseDir . '/php/commands/src/CLI_Command.php', 
    'Cache_Command' => $vendorDir . '/wp-cli/cache-command/src/Cache_Command.php', 
    'Capabilities_Command' => $vendorDir . '/wp-cli/role-command/src/Capabilities_Command.php', 
    'Checksum_Command' => $vendorDir . '/wp-cli/checksum-command/src/Checksum_Command.php', 
    'Comment_Command' => $vendorDir . '/wp-cli/entity-command/src/Comment_Command.php', 
    'Comment_Meta_Command' => $vendorDir . '/wp-cli/entity-command/src/Comment_Meta_Command.php', 
    'Config_Command' => $vendorDir . '/wp-cli/config-command/src/Config_Command.php', 
    'Core_Command' => $vendorDir . '/wp-cli/core-command/src/Core_Command.php', 
    'Core_Language_Command' => $vendorDir . '/wp-cli/language-command/src/Core_Language_Command.php', 
    'Cron_Command' => $vendorDir . '/wp-cli/cron-command/src/Cron_Command.php', 
    'Cron_Event_Command' => $vendorDir . '/wp-cli/cron-command/src/Cron_Event_Command.php', 
    'Cron_Schedule_Command' => $vendorDir . '/wp-cli/cron-command/src/Cron_Schedule_Command.php', 
    'DB_Command' => $vendorDir . '/wp-cli/db-command/src/DB_Command.php', 
    'EvalFile_Command' => $vendorDir . '/wp-cli/eval-command/src/EvalFile_Command.php', 
    'Eval_Command' => $vendorDir . '/wp-cli/eval-command/src/Eval_Command.php', 
    'Export_Command' => $vendorDir . '/wp-cli/export-command/src/Export_Command.php', 
    'Import_Command' => $vendorDir . '/wp-cli/import-command/src/Import_Command.php', 
    'Media_Command' => $vendorDir . '/wp-cli/media-command/src/Media_Command.php', 
    'Menu_Command' => $vendorDir . '/wp-cli/entity-command/src/Menu_Command.php', 
    'Menu_Item_Command' => $vendorDir . '/wp-cli/entity-command/src/Menu_Item_Command.php', 
    'Menu_Location_Command' => $vendorDir . '/wp-cli/entity-command/src/Menu_Location_Command.php', 
    'Network_Meta_Command' => $vendorDir . '/wp-cli/entity-command/src/Network_Meta_Command.php', 
    'Option_Command' => $vendorDir . '/wp-cli/entity-command/src/Option_Command.php', 
    'Package_Command' => $vendorDir . '/wp-cli/package-command/src/Package_Command.php', 
    'Plugin_Command' => $vendorDir . '/wp-cli/extension-command/src/Plugin_Command.php', 
    'Post_Command' => $vendorDir . '/wp-cli/entity-command/src/Post_Command.php', 
    'Post_Meta_Command' => $vendorDir . '/wp-cli/entity-command/src/Post_Meta_Command.php', 
    'Post_Term_Command' => $vendorDir . '/wp-cli/entity-command/src/Post_Term_Command.php', 
    'Post_Type_Command' => $vendorDir . '/wp-cli/entity-command/src/Post_Type_Command.php', 
    'Rewrite_Command' => $vendorDir . '/wp-cli/rewrite-command/src/Rewrite_Command.php', 
    'Role_Command' => $vendorDir . '/wp-cli/role-command/src/Role_Command.php', 
    'Scaffold_Command' => $vendorDir . '/wp-cli/scaffold-command/src/Scaffold_Command.php', 
    'Search_Replace_Command' => $vendorDir . '/wp-cli/search-replace-command/src/Search_Replace_Command.php', 
    'Server_Command' => $vendorDir . '/wp-cli/server-command/src/Server_Command.php', 
    'Shell_Command' => $vendorDir . '/wp-cli/shell-command/src/Shell_Command.php', 
    'Sidebar_Command' => $vendorDir . '/wp-cli/widget-command/src/Sidebar_Command.php', 
    'Site_Command' => $vendorDir . '/wp-cli/entity-command/src/Site_Command.php', 
    'Site_Option_Command' => $vendorDir . '/wp-cli/entity-command/src/Site_Option_Command.php', 
    'Super_Admin_Command' => $vendorDir . '/wp-cli/super-admin-command/src/Super_Admin_Command.php', 
    'Taxonomy_Command' => $vendorDir . '/wp-cli/entity-command/src/Taxonomy_Command.php', 
    'Term_Command' => $vendorDir . '/wp-cli/entity-command/src/Term_Command.php', 
    'Term_Meta_Command' => $vendorDir . '/wp-cli/entity-command/src/Term_Meta_Command.php', 
    'Theme_Command' => $vendorDir . '/wp-cli/extension-command/src/Theme_Command.php', 
    'Theme_Mod_command' => $vendorDir . '/wp-cli/extension-command/src/Theme_Mod_Command.php', 
    'Transient_Command' => $vendorDir . '/wp-cli/cache-command/src/Transient_Command.php', 
    'User_Command' => $vendorDir . '/wp-cli/entity-command/src/User_Command.php', 
    'User_Meta_Command' => $vendorDir . '/wp-cli/entity-command/src/User_Meta_Command.php', 
    'User_Session_Command' => $vendorDir . '/wp-cli/entity-command/src/User_Session_Command.php', 
    'User_Term_Command' => $vendorDir . '/wp-cli/entity-command/src/User_Term_Command.php', 
    'WP_CLI\\CommandWithDBObject' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/CommandWithDBObject.php', 
    'WP_CLI\\CommandWithMeta' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/CommandWithMeta.php', 
    'WP_CLI\\CommandWithTerms' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/CommandWithTerms.php', 
    'WP_CLI\\CommandWithTranslation' => $vendorDir . '/wp-cli/language-command/src/WP_CLI/CommandWithTranslation.php', 
    'WP_CLI\\CommandWithUpgrade' => $vendorDir . '/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php', 
    'WP_CLI\\CoreUpgrader' => $vendorDir . '/wp-cli/core-command/src/WP_CLI/CoreUpgrader.php', 
    'WP_CLI\\DestructivePluginUpgrader' => $vendorDir . '/wp-cli/extension-command/src/WP_CLI/DestructivePluginUpgrader.php', 
    'WP_CLI\\DestructiveThemeUpgrader' => $vendorDir . '/wp-cli/extension-command/src/WP_CLI/DestructiveThemeUpgrader.php', 
    'WP_CLI\\Fetchers\\Comment' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/Fetchers/Comment.php', 
    'WP_CLI\\Fetchers\\Plugin' => $vendorDir . '/wp-cli/extension-command/src/WP_CLI/Fetchers/Plugin.php', 
    'WP_CLI\\Fetchers\\Post' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/Fetchers/Post.php', 
    'WP_CLI\\Fetchers\\Site' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/Fetchers/Site.php', 
    'WP_CLI\\Fetchers\\Theme' => $vendorDir . '/wp-cli/extension-command/src/WP_CLI/Fetchers/Theme.php', 
    'WP_CLI\\Fetchers\\User' => $vendorDir . '/wp-cli/entity-command/src/WP_CLI/Fetchers/User.php', 
    'WP_CLI\\LanguagePackUpgrader' => $vendorDir . '/wp-cli/language-command/src/WP_CLI/LanguagePackUpgrader.php', 
    'WP_CLI\\NonDestructiveCoreUpgrader' => $vendorDir . '/wp-cli/core-command/src/WP_CLI/NonDestructiveCoreUpgrader.php', 
    'WP_CLI\\REPL' => $vendorDir . '/wp-cli/shell-command/src/WP_CLI/REPL.php', 
    'WP_CLI\\SearchReplacer' => $vendorDir . '/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php', 
    'WP_Export_Base_Writer' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Base_Writer.php', 
    'WP_Export_Exception' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Exception.php', 
    'WP_Export_File_Writer' => $vendorDir . '/wp-cli/export-command/src/WP_Export_File_Writer.php', 
    'WP_Export_Oxymel' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Oxymel.php', 
    'WP_Export_Query' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Query.php', 
    'WP_Export_Returner' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Returner.php', 
    'WP_Export_Split_Files_Writer' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Split_Files_Writer.php', 
    'WP_Export_Term_Exception' => $vendorDir . '/wp-cli/export-command/src/WP_Export_Term_Exception.php', 
    'WP_Export_WXR_Formatter' => $vendorDir . '/wp-cli/export-command/src/WP_Export_WXR_Formatter.php', 
    'WP_Export_XML_Over_HTTP' => $vendorDir . '/wp-cli/export-command/src/WP_Export_XML_Over_HTTP.php', 
    'WP_Iterator_Exception' => $vendorDir . '/wp-cli/export-command/src/WP_Iterator_Exception.php', 
    'WP_Map_Iterator' => $vendorDir . '/wp-cli/export-command/src/WP_Map_Iterator.php', 
    'WP_Post_IDs_Iterator' => $vendorDir . '/wp-cli/export-command/src/WP_Post_IDs_Iterator.php', 
    'Widget_Command' => $vendorDir . '/wp-cli/widget-command/src/Widget_Command.php', 
</pre>
</details>

&nbsp;

So, it might be as simple as checking the `get_class()` of the current command being executed against this list.

Composer can also generate this list in a more convenient way for the tracking functionality, if that should be needed.

**Comment by schlessera** [comment]
Want me to do a PR for a `WP_CLI::is_bundled_command( $command ): bool`?

**Comment by danielbachhuber** [comment]
> Want me to do a PR for a WP_CLI::is_bundled_command( $command ): bool?

👍 Go for it

**Comment by schlessera** [comment]
I added it to the `WP_CLI\Utils` file, because it doesn't need WP to run, and thus can be better tested that way.

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢  This is now in `master`

**Comment by getsource** [comment]
I'm catching this after the fact, but am not comfortable at all with this being opt-out rather than opt-in, both for reasons of predictable performance and privacy-by-proxy (users at hosts, for instance).

If it's going to get released this way, please do so very loudly. Most folks that use WP-CLI probably don't follow these tickets.

**Comment by Ipstenu** [comment]
I (personally) would advocate for opt-in, given the general view of tracking in the WordPress community. That said, _IF_ it stays, this is something that should be as loudly and publicly announced as WordPress' auto-updates. It's a massive shift and not something that should be swept under the radar. That said I know Daniel's traveling atm so I'm not saying OMG NOW! Just that this should be done before the code drops.

**Comment by danielbachhuber** [comment]
From Pressable:

```
barry [3:55 PM] it does seem sketchy
barry [3:55 PM] I dont endorse the idea
```

**Comment by danielbachhuber** [comment]
I'm reverting.

For posterity, this did produce pretty cool data:

![image](https://cloud.githubusercontent.com/assets/36432/25924952/79b78572-359a-11e7-8019-60b9e35b3ce1.png)

![image](https://cloud.githubusercontent.com/assets/36432/25924941/6a37a3b6-359a-11e7-814a-d2010660b067.png)

![image](https://cloud.githubusercontent.com/assets/36432/25924945/701cbc12-359a-11e7-872c-924009c3e0e7.png)

**Comment by aaronjorbin** [comment]
What about a hybrid opt it/out.  Essentially this:

1) No data is collected until there has been an affirmative consent.
2) Upon upgrading, when a command is entered in interactive mode, a user is
prompted asking if they consent to data collection.  This question defaults
to yes (i.e. they have to type no or N in order to opt out).
2a) If a command is run in noninteractive mode, the return value is
appended with a notice to please make a selection with the dream that these
are being logged somewhere and someone looks at the log files.
3) Once a user enters a choice on data collection, it's stored on a system
level in  the `WP_CLI_CONFIG_PATH` file. This also allows people to
preemptively opt-out before running any commands. (i.e. after we scream
from the rooftops)

http://aaron.jorb.in
twitter: twitter.com/aaronjorbin

**Comment by danielbachhuber** [comment]
> What about a hybrid opt it/out.  Essentially this:

This is similar to what Homebrew ended up doing, actually. 

Personally, I don't want to fight the battle to get to some compromise solution. WP-CLI the project has existed just fine without the data up to this point, so I guess we can continue on without.

I've reverted the tracking mechanism.

**Comment by aaronjorbin** [comment]
Homebrew was my inspiration :)

I don't think that it's a compromise solution. It's a solution that satisfies the needs of everyone.  

As there is no close status, by closing do you mean to signify this that the project is no longer interested in this functionality or something else?

**Comment by danielbachhuber** [comment]
> As there is no close status, by closing do you mean to signify this that the project is no longer interested in this functionality or something else?

Yes, I'm no longer going to pursue anonymized usage statistics (at least for the foreseeable future)

**Comment by jgraup** [comment]
When the issue is revisited 🤞 I could see this as an opt-in setting in the [config.yml](https://make.wordpress.org/cli/handbook/config/#config-files). Much in the same way you can `disabled_commands`  and set configurations per [`@alias`](https://developer.wordpress.org/cli/commands/cli/alias/) to keep this process transparent and granular. 

On a multisite with 85+ sites, I personally do not want to incur a performance hit running crons per site every 5 minutes or during ANY data migration tasks. I also don't want to have to remember to ask my ops team to make production config changes to maintain company privacy.

However, I would happily contribute analytics to THIS project for any site I am working on that is not under some sort of NDA.
