### ISSUE TITLE
Restore "Make sure files are cleaned up" test for PHP 7

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3888]
It was disabled in https://github.com/wp-cli/wp-cli/pull/3887/commits/c91c53dc01fda0ef2f8e4da93f9f950bfc4b5c02

See https://github.com/wp-cli/wp-cli/pull/3887#issuecomment-285363975

Need to figure out why the test fails on PHP 7.1.2, and not 7.1.0, and then restore the test.

**Comment by danielbachhuber** [comment]
This core ticket is probably related https://core.trac.wordpress.org/ticket/40084

**Comment by gitlost** [comment]
This was fixed by https://github.com/wp-cli/core-command/pull/13
