### ISSUE TITLE
Argument arrays vs code robustness

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3890]
The framework contains portions of code that have functions and methods do multiple different things based on some random combinations of argument arrays. One instance that popped into my eye was when going over this PR: https://github.com/wp-cli/scaffold-package-command/pull/87/commits/d3eacbef438496e94dcabde78cc793eee277b9ca

The problem with these argument arrays is that they can fail in a multitude of ways, and often still not produce a hard error, but rather just do something else than was intended:

* If you have a typo in an argument key, that key is probably ignored, falling back to the default value instead of the override that was provided.
* If you have a typo in a value, error handling depends on the internal validation of the arguments and can produce erratic results.
* If you misremember the default values, you might omit an argument that was crucial for the kind of behaviour you were looking for.
* The implementation within the actual function or method is very convoluted, as it needs to implement a very complex behaviour that can result in dozens or hundreds of actual code paths.

While a complete refactor of most of these is not an option, I recommend keeping them better in checks through the following means:

1. Provide class/interface constants for the argument keys. This avoids typos in the key, helps discovery, allows for code completion in IDEs, makes the code more future-safe and reduces the memory footprint. So, instead of `Class::do_something( array( 'some_parameter' => 5 ) );`, we'll have something like `Class::do_something( array( Class::SOME_PARAMETER => 5 ) );`.

2. Provide class/interface constants for the argument values where a distinct set of flags/options are available. Same as with 1., this avoids typos in the value, helps discovery, allows for code completion in IDEs, makes the code more future-safe and reduces the memory footprint. So, instead of `Class::do_something( array( 'format' => 'json' ) );`, we'll have something like `Class::do_something( array( 'format' => Format::JSON ) );`.

3. Provide separate (convenience) functions/methods where behavior significantly changes based on arguments. This helps communicate intents and reduces potential misunderstandings about what the arguments do. It also avoids errors where the default values are not as expected/remembered. So, instead of `Class::method( array( 'behavior' = 'variant_a' ) );` we'll have both `Class::method_with_a();` and `Class::method_with_b()`. These can still use the main shared method behind the scenes, of course. The purpose is to make the API clearer and better communicate intent.

**Comment by danielbachhuber** [comment]
> The framework contains portions of code that have functions and methods do multiple different things based on some random combinations of argument arrays.

This is correct. It's a common WordPress pattern.

> The problem with these argument arrays is that they can fail in a multitude of ways, and often still not produce a hard error, but rather just do something else than was intended:

How often does this happen?

> While a complete refactor of most of these is not an option, I recommend keeping them better in checks through the following means:

Do the benefits of these means outweigh the costs? Some costs include: deviation from standard patterns, additional code complexity, time spent on this vs. other focuses.

**Comment by schlessera** [comment]
> This is correct. It's a common WordPress pattern.

Yes, unfortunately. ;)

> How often does this happen?

I have no hard numbers here, but, in the context of WordPress, I suspect that a large number of bugs or newbie coding requests are caused by this ("my query does not work..."), and it is one of the reasons why developers need to constantly look up stuff in the documentation or source code when working with WordPress, instead of just being assisted by their IDE like in any other environment.

> Do the benefits of these means outweigh the costs? Some costs include: deviation from standard patterns, additional code complexity, time spent on this vs. other focuses.

- "deviation from standard patterns" -> the more wide-spread pattern is to make code DRY and only use one single source of truth to avoid the possibility of typos;
- "additional code complexity" -> Only if you consider adding a section with all known constants at the top of a class additional complexity. I would argue that it does the contrary. You have one place where you see at a glance what the possible options are, and you get immediate feedback in your IDE if you use something else;
- "time spent on this vs. other focuses" -> I'm not saying we should rewrite the entire code base. But whenever we touch related code, we might introduce such constants and slowly improve usage of them. Making the transition complete can be evaluated at a later time as opportunity arises. Starting with it would however build more robust conventions for future commands.

**Comment by danielbachhuber** [comment]
Ok. I'm not strongly opposed to this, but I'd suggest we hold on this for a while.

>  in the context of WordPress, I suspect that a large number of bugs or newbie coding requests are caused by this ("my query does not work..."), and it is one of the reasons why developers need to constantly look up stuff in the documentation or source code when working with WordPress, instead of just being assisted by their IDE like in any other environment.

I don't think most WordPress developers use an IDE. I personally don't. I'm not sure it's something we need to optimize for.

> the more wide-spread pattern is to make code DRY and only use one single source of truth to avoid the possibility of typos;

It's not a wide-spread pattern in WordPress, which is the community / developer pool we're working with.

> Only if you consider adding a section with all known constants at the top of a class additional complexity. I would argue that it does the contrary. You have one place where you see at a glance what the possible options are

What about a class with multiple methods that each accept multiple arguments?

**Comment by schlessera** [comment]
> What about a class with multiple methods that each accept multiple arguments?
Yes, still preferable to the arguments array.

Basically, the arguments array takes all of the improvements PHP has made to its typing system, to its OOP mechanisms, etc... and throws it out the window to replace everything with dumb strings. All of the assistance that both the language and the tools provide are gone, you can only validate by hand to make sure your strings are the exact strings that you were looking for...

**Comment by schlessera** [comment]
Quick preview of how these class constants look from within an IDE...

You define the class constants where they make the most semantic sense. In PHP, class constants can also be defined in interfaces, not only in classes.
Defining them like this makes the list of choices very explicit and self-documenting.
<img width="633" alt="screenshot 2017-03-10 18 03 14" src="https://cloud.githubusercontent.com/assets/83631/23804865/f646fa78-05bb-11e7-8f2c-31346c0ba02c.png">

Then, from within the consuming code, you get a list of available options and can easily choose one. As auto-completion is active, although the references contain more characters, they are faster to type then the raw strings. And you can't introduce typos.
<img width="753" alt="screenshot 2017-03-10 18 03 52" src="https://cloud.githubusercontent.com/assets/83631/23804921/2685fa72-05bc-11e7-8dbe-95f6d81b69e3.png">

**Comment by GaryJones** [comment]
> I don't think most WordPress developers use an IDE. I personally don't. I'm not sure it's something we need to optimize for.

> It's not a wide-spread pattern in WordPress, which is the community / developer pool we're working with.

Most WordPress developers aren't going to be making changes or even necessarily reading the source code for wp-cli. wp-cli is a tool that does not have to stick with anti-patterns that WP source uses.

**Comment by schlessera** [comment]
This might not be that relevant here, but here's another argument against arrays, for completeness' sake:
https://twitter.com/nikita_ppv/status/847855830821109760

In case the tweet is not expanded:
```
Some graphs comparing memory usage of arrays and objects (with declared properties) in PHP 7. Arrays need between 2x and 6x more memory.
```

**Comment by danielbachhuber** [comment]
At this point, I'm leaning towards wontfix on this issue for a few reasons:

1. This will be a substantial amount of effort over the long term, and there are higher impact projects we can focus our energy on.
2. The majority of WP-CLI contributors and users don't use IDEs. This change is primarily for the benefit of those who use IDEs.
3. This isn't a common code pattern in the WordPress world, which introduces complexity to onboarding new contributors from our primary contributor pool.

I'm willing to be convinced otherwise if it can be proven:

* This will be a high impact project.
* The majority of WP-CLI contributors and users use IDEs with autocompletion.
* This is a common code pattern in the WordPress world.

**Comment by schlessera** [comment]
> This is a common code pattern in the WordPress world.
Ha, now you're taking the easy way out.

Of course it isn't. WordPress code in general is of very low quality, and most of the common code patterns are for procedural legacy PHP.

But I agree this is not a high impact. I'm not suggesting we go ahead and rewrite major parts of WP-CLI.

However, I would really like stuff like this to be considered when we are creating new code. There's no need to repeat issues like these when creating code from scratch.

As a sidenote: I don't really understand the argument about IDEs. Yes, there's more advantages to be had when using an IDE. That doesn't mean that it removes anything for people not using an IDE. In fact, I would even go so far as to say that code patterns like the "$args" pattern are what make people believe that there's no inherent difference between a text editor and an IDE, as both just force you to type everything out in the same manner.

**Comment by danielbachhuber** [comment]
> However, I would really like stuff like this to be considered when we are creating new code. There's no need to repeat issues like these when creating code from scratch.

Happy to consider it when creating new code. Not sure why it's worth bringing up when taking about old code.

> As a sidenote: I don't really understand the argument about IDEs. Yes, there's more advantages to be had when using an IDE. That doesn't mean that it removes anything for people not using an IDE.

The `$args` pattern makes everything readable in a few short lines. Introducing a half dozen class variables is harder to read and understand when you're not using an IDE that interprets it.

**Comment by schlessera** [comment]
> Happy to consider it when creating new code. Not sure why it's worth bringing up when taking about old code.

To give examples of what we should try to avoid in the future. The cross-referenced issue just now happended to be a case that demonstrated a type of mistake that is avoidable through code patterns.

> The $args pattern makes everything readable in a few short lines. Introducing a half dozen class variables is harder to read and understand when you're not using an IDE that interprets it.

Class constant definitions can be just as short. But they do provide semantic meaning, which the random strings are lacking.

I'm happy that this has at least been discussed and can be considered for future code.
