### ISSUE TITLE
wp user import-csv --send-email sends password change email in multisite

### ISSUE THREAD

**Issue by WTurunen** [wp-cli/wp-cli#3903]
Hi,

On a multisite install (WP 4.7.3, WP-CLI 1.1.0), I need to create users from csv with the command 
```
wp user import-csv users.csv --send-email --skip-update --url="http://example.dev/test/"
```
The csv:
```
user_login,user_email,display_name,role
import01,import01@example.dev,Import 01,editor
```

The users receive an email that asks them to change their password, which is great. But they also receive an email notice confirming that their password was changed. This is not what I wanted because the users are in fact new and have never been to the site so the notice is just confusing them.

I suspect that this happens because in multisite when adding new users from csv, `wp-cli/user.php:875` first creates a new user with `wpmu_create_user` and then updates the rest of the information using `wp_update_user`. The problem is that the password is also given and checked to see if it matches the hashed one in the db! Of course, it doesn't match the hashed one, so a notice is sent out.

If this is the case, then maybe the password information should be omitted from the `wp_update_user` function?

**Comment by danielbachhuber** [comment]
Thanks for the report, @WTurunen !

> If this is the case, then maybe the password information should be omitted from the `wp_update_user` function?

We can go ahead and bypass core's email notifications altogether.
