### ISSUE TITLE
Verify checksums for files under wp-content that should never change

### ISSUE THREAD

**Issue by tmugford** [wp-cli/wp-cli#3913]
I was recently investigating a successful hack, and used `verify-checksums` in an attempt to locate files that were modified as part of that hack. It returned a clean bill of health, but on further inspection, it transpired that a number of files under `wp-content` had actually been modified. I understand why `verify-checksums` [specifically excludes `wp-content`](https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php#L978-L981), but I’m wondering if it might make sense to check those files that should never change—`wp-content/index.php` for example.

Failing that, it might be worth adding a note to the documentation.

I’m happy to investigate further and submit a PR either way if this is something of interest.

**Comment by danielbachhuber** [comment]
> but I’m wondering if it might make sense to check those files that should never change—`wp-content/index.php` for example.

If there are checksums published for the file, we can check for it. Otherwise, it's outside the scope of `wp core verify-checksums`. It may be a good fit for `wp doctor` though: https://github.com/wp-cli/doctor-command/

> Failing that, it might be worth adding a note to the documentation.

Happy to look at a PR with documentation improvements.

**Comment by tmugford** [comment]
Wow, that was a quick response!

There are checksums published for `wp-content/index.php`, but I realise there are otherwise very few files under `wp-content` that will never change as part of the normal upgrade process. As you say, this might be better suited to `wp doctor` (which is a fantastic addition by the way).

I think it might be better to go the documentation root on this one. I’ll take a look and submit a PR.

Keep up the great work.

**Comment by danielbachhuber** [comment]
> I think it might be better to go the documentation root on this one. I’ll take a look and submit a PR.

👍  Sounds good.
