### ISSUE TITLE
Feature request: temporarily enable a theme

### ISSUE THREAD

**Issue by tedmasterweb** [wp-cli/wp-cli#3914]
We sometimes have (parent) themes with bad code in them, code that causes fatal (or other) errors that don't allow us to work on the site using wp-cli (because it just quits). This is a request to allow us to tell wp to load a specific theme for the current wp command, something like: --use-theme=twentyseventeen.

This would allow us to work on the site without interrupting the service the site provides on the front end.

I know it seems odd that we would allow a theme to be used in production when it's throwing fatal errors but the error only seems to happen when using wp-cli (probably an environment variable that doesn't exist on the command line).

Does this make sense? Is the use case clear enough?

Thanks in advance.

Ted Stresen-Reuter

**Comment by danielbachhuber** [comment]
> We sometimes have (parent) themes with bad code in them, code that causes fatal (or other) errors that don't allow us to work on the site using wp-cli (because it just quits). This is a request to allow us to tell wp to load a specific theme for the current wp command, something like: --use-theme=twentyseventeen.

Are you familiar with the `--skip-themes` [global parameter](https://make.wordpress.org/cli/handbook/config/)?

I'm not sure `--use-theme=<theme>` makes sense to add as a global parameter (global parameters are expensive to add, because they have the possibility of colliding with local parameters), but you could achieve the use-case with this `theme-env.php` file:

```
WP_CLI::add_wp_hook( 'muplugins_loaded', function(){
	$theme = getenv( 'WP_CLI_USE_THEME' );
	if ( ! $theme ) {
		return;
	}
	$use_theme = function() use ( $theme ) {
		return $theme;
	};
	add_filter( 'pre_option_template', $use_theme );
	add_filter( 'pre_option_stylesheet', $use_theme );
});
```

```
$ wp --require=theme-env.php option get stylesheet
twentyseventeen
$ WP_CLI_USE_THEME=twentysixteen wp --require=theme-env.php option get stylesheet
twentysixteen
```

**Comment by tedmasterweb** [comment]
--skip-themes was exactly what I was looking for, actually, so for me, problem solved!

Thank you!

**Comment by danielbachhuber** [comment]
👍
