### ISSUE TITLE
wp core config shell_exec

### ISSUE THREAD

**Issue by Amstramgram** [wp-cli/wp-cli#3916]
Hello,
wp-cli returns NULL when we php-launched like that :

`shell_exec('/usr/local/bin/wp core config  --dbname=MyDB --dbuser=root --dbpass=root --dbhost=127.0.0.1');`

in fact all shell executed wp-cli commands works, except for 'core config'. 
Is there any tricks ?
Thanks

**Comment by danielbachhuber** [comment]
Hi @Amstramgram,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
