### ISSUE TITLE
search-replace corrupting serialized data

### ISSUE THREAD

**Issue by newtoid** [wp-cli/wp-cli#3920]
Customer reports that search-replace corrupts serialized data is being corrupted when migrating a site to the Pantheon platform. He reports that after.txt is completely corrupted and cannot be parsed with http://www.unserialize.com/

No problems noted when just cloning, please see attached. 

[before.txt](https://github.com/wp-cli/wp-cli/files/859106/before.txt)
[after.txt](https://github.com/wp-cli/wp-cli/files/859107/after.txt)

**Comment by danielbachhuber** [comment]
Hi @newtoid,

As a heads up, this is the public issue tracker for the WP-CLI project.

Can you share steps to reproduce the issue on a stock WP install?

**Comment by danielbachhuber** [comment]
@newtoid Based on our conversation, it sounds like this was an issue with Blogvault. Feel free to open a new issue for anything else WP-CLI related.
