### ISSUE TITLE
Silly Question - WP Cli user create with user meta

### ISSUE THREAD

**Issue by cAstraea** [wp-cli/wp-cli#3922]
Is it possible to create a user with custom user_url and custom user meta in wp_usermeta? 
The most important point was creating the usermeta. Couldn't do it from the wp rest interface with a post like  to /wp-json/wp/v2/users
```
{
	"username" : "test2",
	"email": "test2@gmail.com",
	"password": "123456",
	"meta": {
		"messengerId": "11223344"
	}
	
}  
```          
So I'm putting all my hope on the WP Cli 

Last solution would be to insert the stuff from the node app with mysql-node in wp_user and wp_usermeta

**Comment by cAstraea** [comment]
Noticed can use wp user meta add 123 bio but would still need t know the user id beforehand. Is there a command that merges the 2 commands to do everything in one command ? Was planning to use a wrapper like https://github.com/gtg092x/node-wp-cli in the express app.

**Comment by danielbachhuber** [comment]
Hi @cAstraea,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
