### ISSUE TITLE
Feature request: wp user list w/ meta filter + orderby

### ISSUE THREAD

**Issue by mwithheld** [wp-cli/wp-cli#3927]
I recognize this can be done with a CLI loop, but it's be really handy to be able to:

- get a list of users (wp user list)
- with optional meta_field=val filter
- with optional sorting by meta_field

The use case I've got in mind is:
- Find users whose last_activity is > 2 years ago, orderby last_activity; display userid, username, last_activity

**Comment by danielbachhuber** [comment]
Because these arguments are passed directly through to `get_users()`, I think you can already do this with:

```
wp user list --meta_key=last_activity --orderby=meta_value_num --order=desc --fields=ID,user_login
```

Have you tried this?

**Comment by mwithheld** [comment]
OK you're one level of awesome up!  Close to what I was looking for.  Maybe you could update
http://wp-cli.org/commands/user/list/
to indicate you can use --meta_key= --orderby=meta_value_num and --order=desc
or add a link to where is says that in the docs.

Too bad --fields can't also return last_activity or meta_value or meta_value_num
And I can't see how to do the WHERE clause filtering, but that could get a bit nasty.

This sql gets close:
db query "SELECT ID, user_login, um.* FROM uvwp_users u JOIN uvwp_usermeta um ON u.ID=um.user_id Where um.meta_key='last_activity' AND UNIX_TIMESTAMP(meta_value)<UNIX_TIMESTAMP('2017-1-1 00:00:01') ORDER BY um.meta_value"

**Comment by mwithheld** [comment]
IMO might not be worth implementing anything here more than what you've got.

**Comment by danielbachhuber** [comment]
> Maybe you could update
> http://wp-cli.org/commands/user/list/
> to indicate you can use --meta_key= --orderby=meta_value_num and --order=desc
> or add a link to where is says that in the docs.

Sounds good 👍
