### ISSUE TITLE
Run PHPCS before Behat

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3929]
As both PHPCS and Behat will block a merge on failure, we should run the much faster PHPCS first, and only run the complete Behat test suite only if PHPCS succeeded.

This avoids scenarios where you let the entire test suite to run for an hour, only to then be blocked by a missing space.

**Comment by danielbachhuber** [comment]
> This avoids scenarios where you let the entire test suite to run for an hour, only to then be blocked by a missing space.

This should be much less of a problem once we're done with #3728

**Comment by schlessera** [comment]
Agree, but it's also a very easy fix that might save time and processing power.
