### ISSUE TITLE
Doesn't work in since 1.1 on php7.1

### ISSUE THREAD

**Issue by davidsword** [wp-cli/wp-cli#3932]
Ubuntu 16.04.2. PHP 7.1.3.

Long time user. Was running 0.x alpha fine for over a year, was working fine, upgraded to 1.1, `wp` commands run but every action receives **Errors.**

`wp --info:`
```
PHP binary:	/usr/bin/php7.1
PHP version:	7.1.3-2+deb.sury.org~xenial+1
php.ini used:	/etc/php/7.1/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0
```

`wp theme install twentyfifteen --debug:`
```
Debug (bootstrap): No readable global config found (0.015s)
Debug (bootstrap): No project config found (0.015s)
Debug (bootstrap): No package autoload found to load. (0.058s)
Debug (bootstrap): ABSPATH defined: /var/www/httpdocs/ (0.058s)
Debug (bootstrap): Begin WordPress load (0.058s)
Debug (bootstrap): wp-config.php path: /var/www/httpdocs/wp-config.php (0.058s)
Debug (bootstrap): Set URL: example.com/ (0.058s)
Debug (bootstrap): Loaded WordPress (0.47s)
Debug (bootstrap): Running command: theme install (0.47s)
Installing Twenty Fifteen (1.7)
Error: No themes installed.
```

and

`wp plugin update --all` gives:
```
PHP Warning:  array_filter() expects parameter 1 to be array, boolean given in phar:///usr/local/bin/wp/php/WP_CLI/CommandWithUpgrade.php on line 319
Warning: array_filter() expects parameter 1 to be array, boolean given in phar:///usr/local/bin/wp/php/WP_CLI/CommandWithUpgrade.php on line 319
+--------------------------------+-------------+-------------+--------+
| name                           | old_version | new_version | status |
+--------------------------------+-------------+-------------+--------+
| google-analytics-for-wordpress | 6.0.16      | 6.1.5       | Error  |
| the-events-calendar            | 4.4.4       | 4.4.5       | Error  |
| wordpress-seo                  | 4.4         | 4.5         | Error  |
+--------------------------------+-------------+-------------+--------+
Error: No plugins updated.

```

I deleted `/usr/local/bin/wp/` and did a clean install twice, same issue. I ran `php wp-cli.phar theme install twentyfifteen --debug` on fresh download of .phar and got some **Error: No themes installed.** message.

**Comment by lilmike** [comment]
Hi there,
Just FYI, it works on my arch linux vps, php 7.1.3. Tested with wp theme install twentyseventeen.
-Michael.

**Comment by schlessera** [comment]
This looks like an issue specific to your environment. The PHP error you see probably means that the WordPress upgrade action returned `false`, which means that there were connection/permission issues with your filesystem. Verify the filesystem and FTP settings of your installation.

**Comment by davidsword** [comment]
Thanks for your replies.

Anyway I can pinpoint the connection/permission issues with my filesystem?

I followed the instructions to a tee on reinstallation and it didn't work out. I've been trying to resolve this for more hours than I'd like to admit.

**Comment by davidfavor** [comment]
davidsword wrote:
> Thanks for your replies.
> 
> Anyway I can pinpoint the connection/permission issues with my filesystem?
> 
> I followed the instructions to a tee on reinstallation and it didn't 
> work out. I've been trying to resolve this for more hours than I'd like 
> to admit.

I host many sites in many LXD containers.

Here's my setup approach to keep debugging simple.

1) Install XDebug - On Ubuntu, apt-get install php-xdebug

2) In xdebug.ini, ensure xdebug.scream = 1

3) Do an Apache reload or restart (depends on your distro)

4) Verify xdebug.scream == 1 for Apache, via phpinfo.php
    file to dump your PHP environment

Enabling scream short circuits the PHP '@' (shutup) operator, which
suppresses all manner of meaningful debug info.

Enable WP_DEBUG.

Now execute your failing wp-cli command(s) + refer to your WP debug log.

Likely wp-cli will spew diagnostics or your WP debug log will contain
what you're looking for.

**Comment by davidsword** [comment]
Thats a really great tip, thank you so much @davidfavor
