### ISSUE TITLE
Travis fails on `wp package install` due to Composer conflict

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3933]
There's two test failures right now due to Composer conflicts:

<img width="912" alt="screenshot 2017-03-25 08 34 37" src="https://cloud.githubusercontent.com/assets/83631/24320456/0ca9c054-1136-11e7-9048-2452d161dad8.png">

I suspect these are due to the fact that we used a too strict branch alias of `1.0.x-dev`. I think this will resolve if we use `1.x-dev` as branch alias, which should include `1.2.0-alpha` as well.

**Comment by schlessera** [comment]
I just noticed that we haven't yet merged the branch alias stuff (in branch `wp-cli/package.command@1-phar-access`. So the currently pulled-in version of `wp-cli/package-command` has no branch alias at all.

**Comment by schlessera** [comment]
As the current PR that includes the branch alias has other changes and currently fails to build, I added another PR to just deal with this issue to resolve it quickly.

**Comment by schlessera** [comment]
Urgh. The "quick-fix" PR to just include the branch alias in `wp-cli/package-command` of course fails on all the make-phar issues.

**Comment by danielbachhuber** [comment]
> There's two test failures right now due to Composer conflicts:

@schlessera Those test failures come from `wp-cli/scaffold-package-command`, not `wp-cli/package-command`

**Comment by danielbachhuber** [comment]
Testing locally produces the same issue:

```
local ➜  wp-cli git:(master) wp package install wp-cli/scaffold-package-command
Installing package wp-cli/scaffold-package-command (dev-master)
Updating /Users/danielbachhuber/wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Installation request for wp-cli/wp-cli 1.2.0-alpha -> satisfiable by wp-cli/wp-cli[1.2.0-alpha].
    - wp-cli/scaffold-package-command dev-master requires wp-cli/wp-cli dev-master -> satisfiable by wp-cli/wp-cli[dev-master].
    - Can only install one of: wp-cli/wp-cli[dev-master, 1.2.0-alpha].
    - Installation request for wp-cli/scaffold-package-command dev-master -> satisfiable by wp-cli/scaffold-package-command[dev-master].
---
Error: Package installation failed (Composer return code 2). Reverted composer.json
```

I suspect it's related to the `"version": "1.2.0-alpha"` included in `~/.wp-cli/packages/` (from #3603):
```
local ➜  wp-cli git:(master) cat packages/composer.json
{
    "name": "wp-cli/wp-cli",
    "description": "Installed community packages used by WP-CLI",
    "version": "1.2.0-alpha",
    "authors": [
        {
            "name": "WP-CLI",
            "email": "noreply@wpcli.org"
        }
    ],
    "homepage": "https://wp-cli.org/package-index/",
    "require": {
        "runcommand/dist-archive": "dev-master"
    },
    "require-dev": {},
    "minimum-stability": "dev",
    "license": "MIT",
    "repositories": {
        "wp-cli": {
            "type": "composer",
            "url": "https://wp-cli.org/package-index/"
        }
    },
    "config": {
        "secure-http": true
    }
}
```

**Comment by danielbachhuber** [comment]
> I suspect it's related to the `"version": "1.2.0-alpha"` included in `~/.wp-cli/packages/composer.json`

I tested and this is the case. If I permit `"version": "dev-master"`, then the package can install.

I guess this is a logical incompatibility with #2675. We'll need to specify the minimum supported version in the package's `composer.json`, then run `composer require wp-cli/wp-cli:dev-master` to run the tests against trunk.

**Comment by danielbachhuber** [comment]
This is [fixed](https://travis-ci.org/wp-cli/wp-cli/jobs/214665837) by https://github.com/wp-cli/scaffold-package-command/pull/95
