### ISSUE TITLE
feature request: update a specific field of an option

### ISSUE THREAD

**Issue by lilmike** [wp-cli/wp-cli#3934]
Hi,
It would be nice if you could update a specific index or field of an encoded option, for example x[y=a,z=b] and you only wanted to update x[z] to c. This may be more useful as a search-replace enhancement, so I'll mention it in the issue I'm about to update. Currently, the only real way (that I've found) to update a specific key in an option is to:
1. wp option get <x> --format=json > file.json
2. edit file.json with your data (very risky and error-prone) -- better to back it up first.
3. wp option update <x> < file.json (hope you kept that backup, as if you forked something up in the formatting that wp cli can't detect, your option is irrecoverable).
-Michael.

**Comment by danielbachhuber** [comment]
> It would be nice if you could update a specific index or field of an encoded option, for example x[y=a,z=b] and you only wanted to update x[z] to c.

What would this syntax look like?

**Comment by lilmike** [comment]
Maybe wp option update a[z] c Though more complex use-cases would probably require more thought. I just had an issue where I needed to update an option that literally was a 500kb option or so, and it was not easy :-).
-Michael.

**Comment by danielbachhuber** [comment]
I think this is better solved with `wp shell` at the moment:

```
$ wp shell
wp> update_option( 'test_option', array( 'foo' => 'bar' ) );
=> bool(true)
wp> $value = get_option( 'test_option' );
=> array(1) {
  ["foo"]=>
  string(3) "bar"
}
wp> $value['foo'] = 'burrito';
=> string(7) "burrito"
wp> update_option( 'test_option', $value );
=> bool(true)
wp> $value = get_option( 'test_option' );
=> array(1) {
  ["foo"]=>
  string(7) "burrito"
}
```
