### ISSUE TITLE
feature request: more "filtering" option for search-replace

### ISSUE THREAD

**Issue by lilmike** [wp-cli/wp-cli#3935]
Hi,
I just opened an issue about possibly enhancement of the option command, and this may cover both, depending what you think, but yeah.
Anyway, it would be nice if you could set not only the columns to exclude/include, but also what (regex, etc) those columns need to match to be excluded or included. This could allow you to only replace your site url in a specific value of a column on a table, if you didn't want all of them updated -- especially if that same column had it in multiple values.
-Michael.

**Comment by danielbachhuber** [comment]
> Anyway, it would be nice if you could set not only the columns to exclude/include, but also what (regex, etc) those columns need to match to be excluded or included.

Can you do this by running `wp search-replace` multiple times?

**Comment by lilmike** [comment]
I don't think so. Basically what I meant is if I wanted to replace all occurrances of "test" with "test2", but skip any row that had the user column set to 2, for example.
-Michael.

**Comment by danielbachhuber** [comment]
I think this is better suited for a custom command.
