### ISSUE TITLE
feature request: db full search

### ISSUE THREAD

**Issue by lilmike** [wp-cli/wp-cli#3936]
Hi,
This is a rather hard thing to do in pure mysql shell, so it would help those of us who don't want to have and maintain php-myadmin.
-Michael.

**Comment by danielbachhuber** [comment]
@lilmike I'm not sure I follow. Could you explain in greater detail how this feature would work?

Also, as a heads up, https://github.com/wp-cli/ideas/issues is the best place for new _features_. This issue tracker is best for enhancements to or bugs for existing commands.

**Comment by lilmike** [comment]
Basically I would want to see any column/value pair in the database, or possibly limited by table, that contains a certain phrase. Does this make any more sense?

**Comment by szepeviktor** [comment]
> Does this make any more sense?

Yes.
Up to now I use search-replace in dry-run mode.

**Comment by danielbachhuber** [comment]
@lilmike Have you tried `wp db ack` ? https://github.com/runcommand/db-ack

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/db-command/issues/7 and https://github.com/wp-cli/search-replace-command/issues/1
