### ISSUE TITLE
Attempting to use the dist-archive command throws incorrect error

### ISSUE THREAD

**Issue by jonathanbossenger** [wp-cli/wp-cli#3937]
If the dist-archive package is not installed, attempting to run wp dist-archive shows the following error

Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.

Ideally this should rather be something like

Error: This does not seem to be a valid WP-CLI command, have you installed the dist-archive package.

**Comment by schlessera** [comment]
Which version are you running?

The current stable version seems to work as expected:
<img width="508" alt="screenshot 2017-03-25 14 59 02" src="https://cloud.githubusercontent.com/assets/83631/24322828/c11e27a2-116b-11e7-8c19-de3a74e3b320.png">

**Comment by jonathanbossenger** [comment]
WP-CLI version:	1.1.0

It's probably because the command is being run outside of a WP install, as I keep my 'in-development' plugins in a separate folder and symlink them to a WP install. However as I understand it the dist-archive package can be run independently from a WP install.

**Comment by danielbachhuber** [comment]
> If the dist-archive package is not installed, attempting to run wp dist-archive shows the following error
>
> Ideally this should rather be something like

This is expected behavior, because WP-CLI commands can be registered by plugins or themes. I agree with how it can be confusing.

> However as I understand it the dist-archive package can be run independently from a WP install.

It can, but it needs to be installed in the first place.
