### ISSUE TITLE
wp-profile callback drilldown fails

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#3938]
Likely I'm misunderstanding the documentation.

Let me know the correct way to drill down into a callback.

Here's what I've tried, based on my interpretation of documentation.
_______

Runtime environment...
lxd: net12-clients # wp-cli.phar --allow-root --info
PHP binary:	/usr/bin/php7.1
PHP version:	7.1.3-3+deb.sury.org~yakkety+1
php.ini used:	/etc/php/7.1/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/root/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0

Apache - 2.4.25

lxd: net12-clients # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

Attempting to drill down into a callback.

```
lxd: net12-clients # wp-cli.phar --allow-root profile hook wp_head --spotlight 2>/dev/null
+-------------------------+-----------------------------------------------+----------+------------+-------------+-------------+------------+--------------+--------------+---------------+
| callback                | location                                      | time     | query_time | query_count | cache_ratio | cache_hits | cache_misses | request_time | request_count |
+-------------------------+-----------------------------------------------+----------+------------+-------------+-------------+------------+--------------+--------------+---------------+
| WPSEO_Frontend->head()  | wordpress-seo/frontend/class-frontend.php:657 | 0.0148s  | 0.0011s    | 2           | 98.4%       | 185        | 3            | 0s           | 0             |
| wp_print_head_scripts() | wp-includes/script-loader.php:1169            | 0.0027s  | 0.0003s    | 1           | 62.5%       | 5          | 3            | 0s           | 0             |
| mvp_theme_options()     | devoe/functions.php:93                        | 0.0015s  | 0.0002s    | 1           | 96.77%      | 30         | 1            | 0s           | 0             |
| mvp_site_layout()       | devoe/functions.php:1154                      | 12.5633s | 0s         | 0           | 100%        | 54         | 0            | 12.5524s     | 3             |
+-------------------------+-----------------------------------------------+----------+------------+-------------+-------------+------------+--------------+--------------+---------------+
| total (4)               |                                               | 12.5823s | 0.0016s    | 4           | 89.42%      | 274        | 7            | 12.5524s     | 3             |
+-------------------------+-----------------------------------------------+----------+------------+-------------+-------------+------------+--------------+--------------+---------------+
```

This profile analysis sometimes returns low numbers + sometimes 10-20 seconds for mvp_site_layout() so my guess is there's some sort of callout to an external site.

Trying to figure out how to drill down into mvp_site_layout + docs seem to indicate only way to do this is using eval-file.

Trying to drill down into functions.php as a standalone file, outside the normal WordPress stages, seem like it will never work, as the runtime environment never gets built... so... doing this returns PHP Fatal errors for redefined functions... which also seems broken...

```
cd .../wordpress/wp-content/themes/devoe
lxd: net12-clients # wp-cli.phar --allow-root profile eval-file ./functions.php 2>&1 | egrep '^PHP Fatal'
PHP Fatal error:  Cannot redeclare pif_disable_redirect_canonical() (previously declared in /sites/casey-curtis/wildlifeinsider.com/wordpress/wp-content/themes/devoe/functions.php:1458) in /sites/casey-curtis/wildlifeinsider.com/wordpress/wp-content/themes/devoe/functions.php on line 1458
```
The Fatal error seems odd too. First off the error is incorrect, unless somehow the entire site runtime environment gets build up from index.php which would certainly create a redeclaration for each function in functions.php because the file is already loaded + all functions already declared.

This turns about to be true, as inotifywait reports functions.php being eval'ed twice...

```
lxd: net12-clients # dirwatch | grep functions.php
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
./functions.php 2017-03-25-19:37:36 OPEN
./admin/admin-functions.php 2017-03-25-19:37:36 OPEN
./functions.php 2017-03-25-19:37:37 OPEN
```

**Comment by danielbachhuber** [comment]
Hi @davidfavor:

> Let me know the correct way to drill down into a callback.

It's possible to profile a specific hook (action or filter) in the way you've specified. For instance, this is how you profile the `wp_head` hook:

```
$ wp-cli.phar --allow-root profile hook wp_head --spotlight 2>/dev/null
```

Once you've profiled a hook, it's not currently possible to use `wp profile` to profile the callback itself.

> This profile analysis sometimes returns low numbers + sometimes 10-20 seconds for mvp_site_layout() so my guess is there's some sort of callout to an external site.

This issue will probably help in the future: https://github.com/wp-cli/profile-command/issues/129

> Trying to drill down into functions.php as a standalone file, outside the normal WordPress stages, seem like it will never work, as the runtime environment never gets built... so... doing this returns PHP Fatal errors for redefined functions... which also seems broken...

Right. You'd need to put the code you want to execute in a custom PHP file, and then `wp profile eval-file` on that file. Calling other files that require the WordPress bootstrap process probably won't work.
