### ISSUE TITLE
Invalid plugin slug specified with wp scaffold plugin-tests

### ISSUE THREAD

**Issue by Robin-Andrews** [wp-cli/wp-cli#3939]
On my Windows 10 machine

`wp plugin list` gives

```
+------------------------------------+----------+-----------+---------+
| name                               | status   | update    | version |
+------------------------------------+----------+-----------+---------+
| akismet                            | active   | available | 3.1.10  |
| backupwordpress                    | active   | available | 3.6.1   |
| crafty-social-buttons              | active   | available | 1.5.5   |
| hello                              | inactive | none      | 1.6     |
| one-click-child-theme              | active   | none      | 1.6     |
```
etc...

yet `wp scaffold plugin-tests hello` gives Error: Invalid plugin slug specified.

Same for all listed plugins.

Previous to updating from v0.25 this was working.
I also updated psy/psysh

Any suggestions why/how to make work?

**Comment by Robin-Andrews** [comment]
Also gives same error on creating new plugin scaffolding:

`wp scaffold plugin new-plugin`

`Success: Created plugin files.
Error: Invalid plugin slug specified.`

**Comment by danielbachhuber** [comment]
I suspect this is related to #3666 

Windows isn't formally supported, but I'm amenable to including a fix if we can figure out what the cause is.

**Comment by Robin-Andrews** [comment]
That would be great. Like I said, it seems the issue was introduced post v0.25.0

**Comment by Rarst** [comment]
Also getting a notice in between:

```
/wp.bat scaffold plugin new-plugin
Success: Created plugin files.
Notice: Undefined index: ci in C:\server\wp-cli\php\commands\scaffold.php on line 568
Error: Invalid plugin slug specified.
```

Weirdly I only see two instances of this error in source and I _can't_ dump that either of them is responsible for this output. That's weird. Is there anything else that might generate this message indirectly?

**Comment by Rarst** [comment]
Ok, it seems this is down to `check_target_directory()` method not normalizing paths:

```
string(36) "C:/server/www/dev/wp-content/plugins" // WP_PLUGIN_DIR
string(36) "C:\server\www\dev\wp-content\plugins" // $parent_dir
```

**Comment by miya0001** [comment]
Ah I wrote the `check_target_directory()` and I'm sorry for this bug. 😓 

I think the problem will be solved if we modify as follows.
But I haven't use WP-CLI on Windows. 
Can anyone try it?

https://github.com/wp-cli/scaffold-command/blob/master/src/Scaffold_Command.php#L790-L808

After line 795:
```
$parent_dir = str_replace( DIRECTORY_SEPARATOR, '/', $parent_dir );
```

**Comment by Rarst** [comment]
I promised to do a proper PR, as a resident WordPress Windows person, will get to it... :)

**Comment by danielbachhuber** [comment]
@Rarst Still up for submitting the PR, or should someone else take care of it?

**Comment by Rarst** [comment]
Got a little busy, but still intend to this week, :)

**Comment by FarizF** [comment]
Hi guys!

I have a Wordpress project set up locally using XAMPP. I'm trying to use the scaffold command to add plugin-tests to my plugin using the XAMPP command line on Windows.

When I use `wp plugin list`, it lists my plugins correctly: 

![image](https://cloud.githubusercontent.com/assets/6086354/26154785/263c2dcc-3b11-11e7-89d9-5c0dc253aa7a.png)

When I try running the command `wp scaffold plugin-tests tjs-autoradam --ci=circle`, it returns `Error: Invalid theme slug specified.`.

I squinted hard and long enough to be able to confirm that the inserted plugin name in the last command I've executed matches the name in the plugin list. Could this mean that the issue hasn't yet been resolved? Or is it just "'cause Windows"?

**Comment by danielbachhuber** [comment]
@FarizF You can `wp cli update --nightly` to update to the nightly build. This issue hasn't made it into a stable release yet.

**Comment by FarizF** [comment]
I see! I'll do that now. Thanks!

**Comment by zahardoc** [comment]
Hello, still have this issue on Ubuntu 16.04, php 7.0. Updated to the latest wp-cli version with `wp cli update --nightly`. Did I miss something?

`wp scaffold plugin-tests test`
Error: Invalid plugin slug specified

`wp scaffold theme-tests test`
Error: Invalid theme slug specified.

`wp scaffold plugin test`
Success: Created plugin files.
Success: Created test files.

**Comment by zahardoc** [comment]
Tried on the absolutely different environment - Gentoo 2.2 with php 5.4 - result is the same.

**Comment by zahardoc** [comment]
My fault - I should create directory first. After creating theme dirrectory files have been created flawlessly. Thanks for your work.

**Comment by gitlost** [comment]
@zahardoc thanks for reporting back - maybe you could raise a documentation issue (or better yet - a PR!) on `scaffold-package`?
