### ISSUE TITLE
Consider supporting Symfony 3.x without causing breaking changes

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3941]
It may be possible, but we need to make sure the committed `composer.lock` represents Symfony 2.x, and the Phar is built from 2.x

Related #3909

Previously https://github.com/wp-cli/wp-cli/issues/3305#issuecomment-240888816

**Comment by schlessera** [comment]
My current reasoning is the following:

`wp-cli/wp-cli` framework package should work with both Symfony 2.x and 3.x. It should be able to adapt the current environment and the additional dependencies that come with the rest of the given project.

For a build that needs Symfony 2.x, we would need to run `composer update` in such a way that the platform is perceived as being PHP 5.3.29 (the current required minimum for WP-CLI). As Symfony 3.x doesn't work with this requirement, Composer would automatically choose Symfony 2.x for that build step.

For building a Phar, this can be easily done with a separate package for the Phar build pipeline as discussed in https://github.com/wp-cli/wp-cli/issues/3950. This package can then have a platform requirement of `"php": "~5.3.29"`, and all should work as expected.

For the `composer.lock` file, things are a bit more complicated, but the question is in what ways we even need the `composer.lock` file (given that the lock file is only even considered as a root package, not a dependency):

1. Using WP-CLI as a Phar - Phar meta-package is used, `composer.lock` is irrelevant.
2. Using WP-CLI through a ZIP - not supported.
3. Using WP-CLI as a global Composer install - `composer.lock` is irrelevant.
4. Using WP-CLI as a Composer dependency within a project - `composer.lock` is irrelevant.
5. Running tests in Travis - PHP matrix is used and pulls in WP-CLI via Composer - `composer.lock` is irrelevant.

Did I miss a use case where we do indeed directly depend on the `composer.lock` file now for the `wp-cli/wp-cli` package?

**Comment by danielbachhuber** [comment]
> Did I miss a use case where we do indeed directly depend on the `composer.lock` file now for the `wp-cli/wp-cli` package?

See #2280

I think the Phar should be built off the lock file too. Our Phar build process can `git clone; composer install` to respect the lock file.

> Running tests in Travis - PHP matrix is used and pulls in WP-CLI via Composer - composer.lock is irrelevant.

It is relevant for the main project test suite, however.

**Comment by schlessera** [comment]
Having the same `composer.json` file for the Phar as well as for the rest makes it difficult to force the platform requirement for the Phar while not forcing it for the rest of the use cases.

The normal `composer.json` file can only dictate a *minimum* PHP version, and `composer update` will then use whatever PHP version is currently running as long as it meets that minimum.

For the Phar building, we would want to dictate an *exact* major PHP version of `5.3.x`, to make sure that nothing is being used that doesn't match that requirement, even if we're building the Phar on a PHP 7 machine.

If you don't want to go down that route, then other options would be to either build the Phar within a container (like it is done inside of Travis), or make a run-time change of the `composer.json` file before building the Phar (creating a copy and injecting the PHP 5.3.x platform requirement into that copy). I think a Phar meta-package would be cleaner, though.

**Comment by danielbachhuber** [comment]
```
schlessera [9:11 AM] I just wanted to quickly discuss https://github.com/wp-cli/wp-cli/issues/3941 , because I think that fix misses the actual problem. (edited)
[9:12] `platform` is being used, to force Composer to only consider PHP 5.3 dependencies.
[9:12] I specifically did not propose to use that, because it will (afaik) render all Travis platform tests useless.
[9:12] So, for the root package, all Travis environments will now build against PHP 5.3 dependencies, which makes the tests unreliable.
danielbachhuber [9:13 AM] oh
[9:13] is this a theoretical problem or a real problem?
schlessera [9:13 AM] Outside of the root package, this `platform` config will be ignored, so there, the real dependencies will be used.
danielbachhuber [9:14 AM] because we have a `composer.lock` file, dependencies shouldn't be changing between Travis environments
schlessera [9:14 AM] Difficult to say, really. I think it might perhaps be safe, but the safety that the platform tests provide is a bit illusionary now.
[9:15] That's why I wanted to split the Phar-building into a separate repo, so that we can force only the Phar to be 5.3, and the rest to adapt as needed.
[9:16] So, I cannot really say in a definite way, whether this is yay or nay. I just know that it is potentially an issue.
[9:16] It might cause tests to succeed and real installs to fail in specific circumstances.
danielbachhuber [9:16 AM] ok. I feel comfortable with things as they stand. I suspect it's most likely a theoretical problem because of the `composer.lock` file (edited)
[9:17] the `composer.lock` file mandates dependencies be installed according to a specific hash
schlessera [9:17 AM] Okay, I'm fine with that. I just wanted to make sure the behavior is clear.
[9:18] There's several layers to a full install, so it is difficult to really know what the different edge cases will produce. I suppose we'll soon find out if it is indeed an issue.
```
