### ISSUE TITLE
Feature request: Please add a "wp update --all" command

### ISSUE THREAD

**Issue by Benosika** [wp-cli/wp-cli#3942]
As for now we have `wp plugin update --all` which as I understand works only for plugins.

Please add a `wp update --all` command to work both for plugins and core theme updates.

**Comment by danielbachhuber** [comment]
Hi @Benosika,

Thanks for the feature request. This is already tracked in https://github.com/wp-cli/ideas/issues/16 (`wp-cli/ideas` is the appropriate place for feature requests).
