### ISSUE TITLE
IP address being cut short

### ISSUE THREAD

**Issue by L337LUKE** [wp-cli/wp-cli#3945]
Hey Guys,

I've come to setup a WP installation using a mix of (vagrant / homestead box / wp-cli / bedrock / bedrock-capistrano) but i'm hitting a bit of a wall when trying to install an existing site on my other machine, i'm using all the same configurable's that are on my other machine but no joy.

What seems to be happening is that when i run any command needing to interact with the database and that is tied to wp-cli, it clips the last digit from the IP set in the .env file.  In this case it's the IP of the vagrant box i'm running.

What's really strange however is that at the very bottom of the error it prints out the correct ip address?

Has anyone had this issue before?

`stderr`
```
wp
PHP Warning:  mysqli_real_connect(): (HY000/1045): Access denied for user 'vagrant'@'192.168.10.1' (using password: YES) in /Users/luke/Sites/client/test/public/web/wp/wp-includes/wp-db.php on line 1538
Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'vagrant'@'192.168.10.1' (using password: YES) in /Users/luke/Sites/client/test/public/web/wp/wp-includes/wp-db.php on line 1538
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `192.168.10.10`. This could mean your host’s database server is down.
```

other files that might help

`.env`
```
DB_HOST=192.168.10.10
DB_NAME=homestead
DB_USER=vagrant
DB_PASSWORD=secret

WP_ENV=development
WP_HOME=http://somesite.app
WP_SITEURL=${WP_HOME}/wp

# Generate your keys here: https://roots.io/salts.html
...
```

`Gemfile`
```
source 'https://rubygems.org'

gem 'capistrano', '~> 3.4.0'
gem 'capistrano-composer'
gem 'capistrano-wpcli'
```

**Comment by danielbachhuber** [comment]
Hi @L337LUKE,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
