### ISSUE TITLE
Allow `user create --user-pass` to accept encrypted or obfuscated password

### ISSUE THREAD

**Issue by romanrev** [wp-cli/wp-cli#3948]
The `wp user create` command already has a `--user-pass` option to supply password in the command line, which greatly facilitates automation of creating users and replicating them across different environments. 
It would be even better if that option would also allow one to supply password in an encrypted - or at least obfuscated form.

**Comment by danielbachhuber** [comment]
> It would be even better if that option would also allow one to supply password in an encrypted - or at least obfuscated form.

Why? Could you share more detail about what you're trying to do?

**Comment by romanrev** [comment]
We are trying to centralise the user creation across the WP environments and going to maintain a central registry with the user:password details for each of them. We do not want to store the passwords in clear form there as the registry will be open for all users, so we do not want them to be able to use credentials they are not entitled to.

**Comment by danielbachhuber** [comment]
Makes sense.

This sounds like it would be better suited for a [custom command](https://make.wordpress.org/cli/handbook/commands-cookbook/); it doesn't seem like a feature 80% of WP-CLI users need.

Also, I'd suggest you look at a true identity provider solution like SAML. I think you'll find that syncing user passwords isn't the most robust long-term approach.

**Comment by romanrev** [comment]
@danielbachhuber: with the *dynamic* teams of 5 to 15 people working on WP instances running in autoscaling groups on AWS, having to maintain a central server providing SAML authentication seems like an overkill, at least to my taste.
I wonder how you defined that 80% of WP users don't need the feature, but that's not really relevant to this discussion.
I'll have a look at the custom commands at the link you provided, thank you.

**Comment by romanrev** [comment]
I had a look at the [wpmu_create_user](https://codex.wordpress.org/WPMU_Functions/wpmu_create_user) function source and realised that the issue is not with the WP-CLI but the Wordpress PHP code itself. There is just no provision for supplying an encrypted password whatsoever.
Ironically it will be easier to implement using any other scripting language (say Python or even plain Bash) and plain SQL - in accordance with the guidelines on [Resetting your password](https://codex.wordpress.org/Resetting_Your_Password). 
Seems like a blast-from-the-past bad design decision on behalf of the WP devs.

**Comment by danielbachhuber** [comment]
> Seems like a blast-from-the-past bad design decision on behalf of the WP devs.

@romanrev Please be respectful.

**Comment by romanrev** [comment]
I think you conjecture too much @danielbachhuder, I have not had an intention to express any sort of disrespect. All of us make decisions: good and bad, myself included.
