### ISSUE TITLE
Export & Import — Swaps Emojis with '?' Marks!

### ISSUE THREAD

**Issue by ahmadawais** [wp-cli/wp-cli#3949]
I am running the latest version of WP-CLI.

![](https://i.imgur.com/KSzjpe7.png)
I have had been building a custom Backup and Restore script that works out of the box for my personal use on a self-hosted VPS.

It backups a site DB via 

```bash
wp db export $BACKUPPATH/$SITE/$DATE-$SITE.sql --allow-root --path=$SITESTORE/$SITE/
tar -czf $BACKUPPATH/$SITE/$DATE-$SITE.sql.gz $BACKUPPATH/$SITE/$DATE-$SITE.sql
rm $BACKUPPATH/$SITE/$DATE-$SITE.sql
```
Then I upload it to Dropbox, when I restore the backup, this happens 

```bash
# Un tar the backup,
# -C To extract an archive to a directory different from the current.
# --strip-components=1 to remove the root(first level) directory inside the zip.
tar -xvzf $BACKUPPATH/$SITE_NAME/$DATE-$SITE_NAME.sql.gz -C $BACKUPPATH/$SITE_NAME/db/ --strip-components=3

echo "Db extracted"

# Remove the backup file.
rm -f $BACKUPPATH/$SITE/$DATE-$SITE.sql.gz

echo "⏲  Restoring the database..."
# Reset the database.
wp db reset --yes --path=$SITESTORE/$SITE_NAME/htdocs/ --allow-root

# Import the DB of old site to new site.
wp db import $BACKUPPATH/$SITE_NAME/db/$DATE-$SITE_NAME.sql --path=$SITE_PATH/htdocs/ --allow-root
wp db repair --path=$SITE_PATH/htdocs/ --allow-root
wp db optimize --path=$SITE_PATH/htdocs/ --allow-root
```

This is how I backup a website, and restore it in case anything goes bad.
This works pretty great, the only issue is that it doesn't take care of emojis. All the emojis on my blog get replaced with '?' signs.

**BEFORE**
![](https://i.imgur.com/q4sUIW7.png)
**AFTER**
![](https://i.imgur.com/Jp3eFZR.png)
Can anyone help me figure out what am I doing wrong here?

**Comment by danielbachhuber** [comment]
Hi @ahmadawais,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

**Comment by ahmadawais** [comment]
@danielbachhuber Let me know what you need to reproduce this issue. It is not specific to my system. 
Here's the bash script for [backup and restore](https://github.com/ahmadawais/BR-CLI/blob/master/brcli.sh) setup an instance of Ubuntu 16.04 on DO or Vultr and you'll be able to reproduce this issue. 

Any suggestions or pointers? What could be the cause?

**Comment by danielbachhuber** [comment]
Which MySQL version are you creating the backup from, and which MySQL version are you running the import into?

**Comment by ahmadawais** [comment]
Thanks for responding. 

My bad I forgot to mention. It's EasyEngine 3.7.4. MySQL (10.1.22-MariaDB).

**Comment by ahmadawais** [comment]
Thanks for responding.

My bad I forgot to mention. It's EasyEngine 3.7.4. MySQL (10.1.22-MariaDB).

**Comment by danielbachhuber** [comment]
@ahmadawais I'm not sure what the issue is, but I suspect it's related to your database charset. Happy to chat about it in `#cli`.

**Comment by ahmadawais** [comment]
OK, let's move this chat there.
