### ISSUE TITLE
Add new PHP extension requirement behat tag.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#3953]
Add processing to "utils/behat-tags.php" for "@require-extension" tags, as mentioned in [https://github.com/wp-cli/media-command/pull/4#issuecomment-290542501](https://github.com/wp-cli/media-command/pull/4#issuecomment-290542501), to allow behat tests to be skipped if a required PHP extension isn't installed.

Pull request will follow shortly.

**Comment by szepeviktor** [comment]
> if a required PHP extension isn't installed.

BTW if you want to check your PHP extension and directives see this small class
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/php-env-check.php
