### ISSUE TITLE
Make some scaffold methods more accessible

### ISSUE THREAD

**Issue by CodeProKid** [wp-cli/wp-cli#3957]
I was recently working on a command to scaffold a custom plugin, but noticed that a lot of the underlying methods to do things like write files to the filesystem were locked down under private methods within the `Scaffold_Command ` class. I ended up copying the `create_files`, `prompt_if_files_will_be_overwritten`, `log_whether_files_written`, and `init_wp_filesystem` methods into my command.

I think it would be good to either make these methods protected, so someone could just extend the `Scaffold_Command` class, or abstract them as `Utils`. Let me know what you think of this, and if you have a good direction you think it should go in, I'd be happy to work on it!

**Comment by danielbachhuber** [comment]
👍  I'm amenable to making them protected, if you'd like to submit a PR for this.
