### ISSUE TITLE
'assoc_args_to_str' and provided '--require' arguments

### ISSUE THREAD

**Issue by seanosh** [wp-cli/wp-cli#3958]
From line `1017` of `class-wp-cli.php`:

```
$runtime_config = Utils\assoc_args_to_str( $runtime_config );
```

If `wp` was invoked with one or more `--require` arguments then dumping the contents of `$runtime_config` may, for example, result in:

```
(
    [debug] => 1
    [require] => Array
        (
            [0] => extra-vars.php
        )
    [path] => wordpress/4.7.3
)
```

`assoc_args_to_str` then generates warnings since `escapeshellarg` only takes 1 parameter which is expected to be a string, not an array. The resulting `$runcommand` (based on above example) passed to `proc_open` ends up as:

```
/usr/local/bin/php /usr/local/bin/wp --debug --require= --path='wordpress/4.7.3' rewrite flush --hard
```

**Steps to reproduce:**

1. (install WP, WP-CLI, run `wp core install` - the basics, etc.)
2. Create a file `extra-vars.php` - can be empty, or have several `define`s or just a `return;`
3. Run `wp --require=extra-vars.php rewrite structure '/%year%/%monthnum%/%postname%/' --hard`

**Expected results/output:**

```
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
Success: Rewrite rules flushed.
Success: Rewrite structure set.
```

**Actual results/output:**

```
Warning: Regenerating a .htaccess file requires special configuration. See usage docs.
PHP Warning:  escapeshellarg() expects parameter 1 to be string, array given in phar:///usr/local/bin/wp/php/utils.php on line 199
Warning: escapeshellarg() expects parameter 1 to be string, array given in phar:///usr/local/bin/wp/php/utils.php on line 199
Error: Required file '' doesn't exist (from runtime argument).
```

**Environment:**

* OS: Linux, Debian Jessie 8.6
* PHP Version: 7.0.17
* WP Version: 4.7.3
* WP-CLI Version: 1.1.0
* WP-CLI Packages: none

**Comment by danielbachhuber** [comment]
Thanks for the report @seanosh — appreciated.
