### ISSUE TITLE
Performance & combining multiple commands and executing them in a sequence?

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#3961]
I use wp-cli in a lot of my products for automated set ups. Thanks Daniel and others for improving this product.
I was wondering if there is a way to pass a JSON or base64 encoded JSON/php serialized data to wp-cli and have it execute each command sequentially. That would save the boot time.
Most commands take at least 1 second and above (the staging server is not an SSD powered though) see 'exec_time' field.

```
  'cmd' => 'wp post create --porcelain --path=\'/var/www/vhosts/system.staging.go359.com/users/3/5/gou35/sites/slavi-2017-04-01.staging.go359.com/htdocs/\' --post_title=\'Контакт\' --post_content=\'Можете да се свържете с нас на тел. 0888 111 222\' --post_name=\'contact\' --post_type=\'page\' --post_status=\'publish\'',
  'exec_time' => '2.3051',
  'cmd_params' => '',
  'full_cmd' => 'wp post create --porcelain --path=\'/var/www/vhosts/system.staging.go359.com/users/3/5/gou35/sites/slavi-2017-04-01.staging.go359.com/htdocs/\' --post_title=\'Контакт\' --post_content=\'Можете да се свържете с нас на тел. 0888 111 222\' --post_name=\'contact\' --post_type=\'page\' --post_status=\'publish\'',
  'status' => true,
  'output' => '4',

  'cmd' => 'wp option update admin_email \'slavi-2017-03-12+local+stg@slavi.ca\' --path=\'/var/www/vhosts/system.staging.go359.com/users/3/5/gou35/sites/slavi-2017-04-01.staging.go359.com/htdocs/\'',
  'exec_time' => '1.0603',
  'cmd_params' => '',
  'full_cmd' => 'wp option update admin_email \'slavi-2017-03-12+local+stg@slavi.ca\' --path=\'/var/www/vhosts/system.staging.go359.com/users/3/5/gou35/sites/slavi-2017-04-01.staging.go359.com/htdocs/\'',
  'status' => true,
  'output' => 'Success: Updated \'admin_email\' option.',
)

[Sat, 01 Apr 2017 10:43:36 +0300] [Command #10] [INFO] array (
  'cmd' => 'wp option update timezone_string \'Europe/Sofia\' --path=\'/var/www/vhosts/system.staging.go359.com/users/3/5/gou35/sites/slavi-2017-04-01.staging.go359.com/htdocs/\'',
  'exec_time' => '1.7270',
  'cmd_params' => '',
  'full_cmd' => 'wp option update timezone_string \'Europe/Sofia\' --path=\'/var/www/vhosts/system.staging.go359.com/users/3/5/gou35/sites/slavi-2017-04-01.staging.go359.com/htdocs/\'',
  'status' => true,
  'output' => 'Success: Value passed for \'timezone_string\' option is unchanged.',
)
```

**Comment by danielbachhuber** [comment]
Hi @lordspace:

> I was wondering if there is a way to pass a JSON or base64 encoded JSON/php serialized data to wp-cli and have it execute each command sequentially. That would save the boot time.

It's not currently possible, but something you could [put together with a custom command](https://make.wordpress.org/cli/handbook/commands-cookbook/). I don't know if it would ever make sense to include in WP-CLI proper because there are a number of qualifiers about performing multiple operations in the same request.

> Most commands take at least 1 second and above (the staging server is not an SSD powered though) see 'exec_time' field.

Yes, loading WordPress can take some time. If you don't need your plugins or theme, including `--skip-plugins --skip-themes` may provide some speed improvements.
