### ISSUE TITLE
Support "Examples" in the third argument for WP_CLI::add_command()

### ISSUE THREAD

**Issue by nerrad** [wp-cli/wp-cli#3962]
Currently there are two methods for describing new commands.  

- specifically formatted phpdocs for the command.
- including `short_desc` and specifically structured `synopsis` array items in the third argument when registering the command

However, if one chooses to use the second option above (which has good use case when dynamically registering commands), there's no current way to provide "Examples" of usage.

The current structure of this third argument is [found here](https://github.com/wp-cli/wp-cli/blob/v1.1.0/php/class-wp-cli.php#L376-L383):

```
* @param array $args {
	 *      Optional An associative array with additional registration parameters.
	 *      'before_invoke' => callback to execute before invoking the command,
	 *      'after_invoke' => callback to execute after invoking the command,
	 *      'shortdesc' => short description (80 char or less) for the command,
	 *      'synopsis' => the synopsis for the command (string or array),
	 *      'when' => execute callback on a named WP-CLI hook (e.g. before_wp_load),
	 * }
```

I'm proposing adding an additional key to that index `examples`.

The format for this additional argument would be structured array of arrays where each array represents an example.

```php
array(
    'examples' => array(
        array(
            'short_description' => 'Command example description',
            'command' => 'wp command example',
            'result' => 'Success: The example subcommand has successfully executed for command.'
        )
    )
);

//Results in this in the output
// # Command example description
// $ wp command example
// Success: The example subcommand has successfully executed for command.
```

Structured array's allow for ensuring output follows the current documentation standards [outlined here](https://make.wordpress.org/cli/handbook/documentation-standards/).

**Comment by nerrad** [comment]
I'm willing to work on this as a pull request - might be able to get something by the end of this week.

**Comment by danielbachhuber** [comment]
👍 

On a related note, our test coverage for help doc generation is somewhat lacking (as I'm sure you'll discover). I'd love to see some PHPUnit tests for this that lay the foundation for more comprehensive coverage.

**Comment by nerrad** [comment]
What specific coverage are you looking for?  I see there is current coverage of the [doc parser](https://github.com/wp-cli/wp-cli/blob/master/tests/test-doc-parser.php) and the [synopsis parser](https://github.com/wp-cli/wp-cli/blob/master/tests/test-synopsis.php).  Are you wanting to have some test coverage on `WP_CLI::run_command` handling of that third argument array?  Are you okay with more integration type tests for that or should I break out the third argument parsing there into smaller methods that can be more traditionally unit tested using PHPUnit?

**Comment by danielbachhuber** [comment]
> What specific coverage are you looking for?

Output rendering (e.g. these arguments render to X string).

> Are you okay with more integration type tests for that or should I break out the third argument parsing there into smaller methods that can be more traditionally unit tested using PHPUnit?

PHPUnit would be more precise, and faster.

**Comment by danielbachhuber** [comment]
@nerrad Did you have any code you want to submit for this?

**Comment by nerrad** [comment]
Not yet.  I was fully intending on doing stuff that week but then I got swamped again with other jobs.  I _do_ still want to contribute to this but understand if either someone else picks it up or it gets closed because you decide you don't want it in the project.

**Comment by danielbachhuber** [comment]
> The format for this additional argument would be structured array of arrays where each array represents an example.

I'm going with a simpler implementation of a `longdesc` argument. I don't think it's worth the effort to invent a data schema for the longdesc at this point.

**Comment by nerrad** [comment]
ya that should do fine.  Sorry for not picking this up :(
