### ISSUE TITLE
Applying a WPCLI command to all websites under /var/www/html?

### ISSUE THREAD

**Issue by Benosika** [wp-cli/wp-cli#3964]
What will you say is the best way to use a command like `wp plugin update --all --allow-root` for all WP installations under /var/www/html?

Thanks,

**Comment by danielbachhuber** [comment]
Hi @Benosika,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
