### ISSUE TITLE
Test taxonomy.feature will fail if run against WP 4.4+ due to data change.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#3971]
The second part of the "features/taxonomy.feature:7" test will fail if run against WordPress 4.4+ due to this change https://core.trac.wordpress.org/changeset/35153 where for taxonomy `link_category` the `show_ui` setting (mapped to `show_tagcloud`) changed from false to true.

A simple fix would be to by-pass the issue by using a different `object_type`, eg `nav_menu_item`, see https://github.com/gitlost/wp-cli/pull/1/commits/b9f15f905c09b14e41d2726dc8d8bfd5a87546f8.

**Comment by danielbachhuber** [comment]
Care to submit a pull request against the new location for `features/taxonomy.feature` ? https://github.com/wp-cli/entity-command/blob/master/features/taxonomy.feature

**Comment by gitlost** [comment]
My! Components come and go so quickly here! Will do...

**Comment by schlessera** [comment]
Resolved with https://github.com/wp-cli/entity-command/commit/1a34b38a29250698d63abaf370b5d2d09ca86353
