### ISSUE TITLE
Package install error

### ISSUE THREAD

**Issue by andygagnon** [wp-cli/wp-cli#3972]
Version wp-cli V 1.1.0

Getting an error trying to install dist-archive; and also wp-cli/profile and wp-cli/doctor (same error)

$ wp package install runcommand/dist-archive
Installing package runcommand/dist-archive (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.182 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package wp-cli/profile could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package wp-cli/doctor could not be found in any version, there may be a typo in the package name.

Thanks in advance

**Comment by schlessera** [comment]
This looks like an usage error on your part (wrong package names). I've noted some details in the Slack channel, please continue the discussion there.
