### ISSUE TITLE
Overwritten argument in `iterator_map()`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3973]
Something is off with the function [`iterator_map($it, $fn)` in the `php/utils.php` file](https://github.com/wp-cli/wp-cli/blob/v1.1.0/php/utils.php#L99-L132).

The signature takes a second argument `$fn`, which the docblock states as being `@param callback The function to apply to an element`.

However, that argument is never used and is being overwritten instead in the `foreach` loop: https://github.com/wp-cli/wp-cli/blob/v1.1.0/php/utils.php#L127

Either the argument is not used and should be removed (or maybe, a warning thrown), or the code is buggy and needs rewriting.

**Comment by danielbachhuber** [comment]
@schlessera Doesn't this block mean `iterator_map` takes the second and any subsequent arguments as `$fn`?

```
foreach ( array_slice( func_get_args(), 1 ) as $fn ) {
    $it->add_transform( $fn );
}
```

Note `array_slice( func_get_args(), 1 )`

Introduced in 262245904b21fcec6962eb2728ca520a7011e146

**Comment by schlessera** [comment]
Ah, yes, nevermind then.

My PHPStorm showed me an error, and I failed to notice the `func_get_args()`.
