### ISSUE TITLE
Add minor to plugins

### ISSUE THREAD

**Issue by mkdizajn** [wp-cli/wp-cli#3974]
Hi, 

it would be nice to have a `--minor` flag added to the `plugins` same as we have it for the `core`

`wp plugin update --minor --all`

That would not crash our sites like recent WooCommerce v3 update but would keep the old good v2.x after autoupdating..

Thx, Kres

**Comment by danielbachhuber** [comment]
👍 

Coincidentally, @jeichorn mentioned this last night.

Closing in favor of https://github.com/wp-cli/extension-command/issues/3
