### ISSUE TITLE
Communicate package index status

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#3977]
The WP-CLI package index is currently on hold. However, this is not really communicated, apart from a comment in one of the pull requests: https://github.com/wp-cli/package-index/pull/90#issuecomment-264880112

To better communicate the state of the package index, and what that means for users we should do one or more of the following:

- [ ] Describe the current state and its consequences in the package index's [`README.md`](https://github.com/wp-cli/package-index/blob/master/README.md) file
- [ ] Put up a notice pointing to the README.md section on the package index's [frontpage](http://wp-cli.org/package-index/)
- [ ] Put up a notice pointing to the README.md section on the ["Add to the package index" section](https://make.wordpress.org/cli/handbook/commands-cookbook/#add-to-the-package-index) of the handbook
- [ ] Put a warning pointing to the README.md section into a [`.github/PULL_REQUEST_TEMPLATE.md` file](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by danielbachhuber** [comment]
Closing in favor of #4236
