### ISSUE TITLE
Cache Cleanup Mechanism

### ISSUE THREAD

**Issue by loyukfai** [wp-cli/wp-cli#3979]
On some hosting platforms, keeping a large cache could be detrimental as it incurs additional storage charge. Is it possible to designate wp-cli to clean up more often, or simply does not keep the cache at all?

Thanks in advance.

```
        /** 
         * @return FileCache 
         */ 
        public static function get_cache() { 
                static $cache; 

                if ( !$cache ) { 
                        $home = getenv( 'HOME' ); 
                        if ( !$home ) { 
                                // sometime in windows $HOME is not defined 
                                $home = getenv( 'HOMEDRIVE' ) . getenv( 'HOMEPATH' ); 
                        } 
                        $dir = getenv( 'WP_CLI_CACHE_DIR' ) ? : "$home/.wp-cli/cache"; 

                        // 6 months, 300mb 
                        $cache = new FileCache( $dir, 15552000, 314572800 ); 

                        // clean older files on shutdown with 1/50 probability 
                        if ( 0 === mt_rand( 0, 50 ) ) { 
                                register_shutdown_function( function () use ( $cache ) { 
                                        $cache->clean(); 
                                } ); 
                        } 
                } 

                return $cache; 
        }
```

**Comment by danielbachhuber** [comment]
> Is it possible to designate wp-cli to clean up more often, or simply does not keep the cache at all?

It's not possible currently.

As a workaround, you could specify an alternate cache directory with the `WP_CLI_CACHE_DIR` environment variable, and then use system cron to delete the directory more regularly. Or, you can use system cron to delete the `~/.wp-cli/cache/` dir.

**Comment by loyukfai** [comment]
Would you consider adding this as a feature in future releases?

Cheers.

**Comment by danielbachhuber** [comment]
Probably not. It seems like this is best handled outside of WP-CLI at the moment.

**Comment by loyukfai** [comment]
How about a command within WP-CLI to clean up the cache folder?

Cheers.

**Comment by danielbachhuber** [comment]
Why do you need a command for it when you can run `rm` yourself?

**Comment by loyukfai** [comment]
Like, being convenient to some unknown number of end users (could be just one) who may possibly appreciate not having to set up a cron job or environment variable (which doesn't work for me because /tmp is still counted towards the usage) or make his/her own bash script to clean up the cache files left behind by WP-CLI...

But anyway, you've made your point, I think.

Cheers.
