### ISSUE TITLE
Create helper utility for getting file path inside of Phar

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#3987]
Instead of having to implement https://github.com/wp-cli/scaffold-command/commit/88a21778d5daf7c7eba5214824bb425eaf2afb1c and https://github.com/wp-cli/server-command/pull/15 on a case by case basis, it would be helpful if WP-CLI provided a generic helper utility.

**Comment by schlessera** [comment]
How about some kind of "PathFinder" object that we can just query for relative paths? We can then add both a `FilesystemPathFinder` and a `PharPathFinder` version, and it is easily extensible for future needs.

**Comment by danielbachhuber** [comment]
Util function might be simple enough. I care most that it's reliable and has test coverage.
