### ISSUE TITLE
syntax error, unexpected 'dirname' (T_STRING)

### ISSUE THREAD

**Issue by aerogus** [wp-cli/wp-cli#3989]
I've got a difficult to understand message on one of my WordPress instance (for any wp-cli command that I type in the project root) :

versions : wp-cli 1.1.0, wp 4.7.3

```
$ wp cli version --debug
Debug (bootstrap): No readable global config found (0.01s)
Debug (bootstrap): No project config found (0.01s)
Debug (bootstrap): No package autoload found to load. (0.056s)
PHP Parse error:  syntax error, unexpected 'dirname' (T_STRING), expecting ';' in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(151) : eval()'d code on line 1

Parse error: syntax error, unexpected 'dirname' (T_STRING), expecting ';' in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(151) : eval()'d code on line 1
```

I precise that this instance has wp installed via composer in a /wp subdirectory.

I finally managed to find the bug !

here is my index.php bootstrap :
```
<?php
define('WP_USE_THEMES', true);
require_once dirname(__FILE__) . '/wp/wp-blog-header.php';
exit;
```

Replacing require_once by require solved the bug.

```
$ wp cli version --debug
Debug (bootstrap): No readable global config found (0.011s)
Debug (bootstrap): No project config found (0.011s)
Debug (bootstrap): No package autoload found to load. (0.061s)
Debug (bootstrap): ABSPATH defined: /Users/aerogus/wordpress/ (0.061s)
Debug (bootstrap): Running command: cli version (0.061s)
WP-CLI 1.1.0
```

Maybe you should be more permissive in the regexp in Runner.php ? (accept require and require_once which make sens in this bootstrap file ?)

**Comment by danielbachhuber** [comment]
Hi @aerogus,

I suspect this issue is actually related to #1631. Can you confirm?

**Comment by aerogus** [comment]
Kind of. But it's more linked to the parsing of root index.php that the wp-config.php one ?
Nevertheless I read #1631 with attention 👍

**Comment by danielbachhuber** [comment]
> Kind of. But it's more linked to the parsing of root index.php that the wp-config.php one ?

WP-CLI doesn't parse `index.php` any more than your web server does. Are you sure you didn't change `wp-config.php` when you were debugging?

**Comment by aerogus** [comment]
All I know is changing "require_once" by "require" solved (or seem to) the parsing error.
My only diff (in /index.php) :

```
< require_once dirname(__FILE__) . '/wp/wp-blog-header.php';
---
> require dirname(__FILE__) . '/wp/wp-blog-header.php';
```
don't know if it helps ...

**Comment by danielbachhuber** [comment]
Ok. We can look at it further if it comes up again.
