### ISSUE TITLE
Improve Tagging of Behat Scenarios

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#3996]
It would be nice if the Behat scenarios were tagged a bit more generously with the relevant components they touch.  This would improve the development workflow overall I think but also for contributing by letting you run a subset of feature tests more easily.

I realize this is already possible in a way by specifying the specific feature file, but I'm suggesting something a bit more granular, so you don't have to run a whole feature file if only a handful of scenarios meet your criteria.

For example, if I want to work on a feature related to a specific aspect of the configuration, it would be nice if all the related scenarios followed a particular tagging convention like:

`@config:path` or `@config:require` for these specific configuration values.

Flags could use a similar convention: `@flag:path` `@flag:url` etc.

I think it would be quite useful, and I would be willing to contribute some PRs for this too.

Thoughts?

**Comment by danielbachhuber** [comment]
> It would be nice if the Behat scenarios were tagged a bit more generously with the relevant components they touch. This would improve the development workflow overall I think but also for contributing by letting you run a subset of feature tests more easily.

`wp scaffold` has had some of these in the past, but I don't know if they've been used other than the first time they were added https://github.com/wp-cli/scaffold-command/blob/master/features/scaffold.feature#L3

Personally, when I'm working on a specific scenario, I tag it with `@daniel` and then run `behat --tags="@daniel"`

> I realize this is already possible in a way by specifying the specific feature file, but I'm suggesting something a bit more granular, so you don't have to run a whole feature file if only a handful of scenarios meet your criteria.

Yes, this is deliberate. I've found it more effective to break component tests into logical files.

> For example, if I want to work on a feature related to a specific aspect of the configuration, it would be nice if all the related scenarios followed a particular tagging convention like:
>
> `@config:path` or `@config:require` for these specific configuration values.
>
> Flags could use a similar convention: `@flag:path @flag:url` etc.

One challenge I can see with adopting this is the associated maintenance burden.

For this to be a useful part of the development experience, _all scenarios would need to be accurately flagged_. With https://github.com/wp-cli/wp-cli/issues/3728, everything is getting split into separate subpackages, which increases the difficulty of keeping things tagged properly.

I'm not strongly opposed to this, but I see the costs as outweighing the benefits at this point.

**Comment by aaemnnosttv** [comment]
I hear you. I guess I don't see it being too much of a burden as it could be added over time and I feel like the examples I gave would be loose enough that they shouldn't need to be changed in big swaths across the codebase. It should only need to be changed when you're working on a new feature or updating an old one.

> Personally, when I'm working on a specific scenario, I tag it with @daniel and then run behat --tags="@daniel"

This is kind of what I've been doing too.  Is this documented anywhere?  If this is the recommended way right now, it would be useful to others as well.

**Comment by danielbachhuber** [comment]
> Is this documented anywhere? If this is the recommended way right now, it would be useful to others as well.

It's not, but it could be. Here are the two places you can submit pull requests:

* https://github.com/wp-cli/handbook/blob/master/pull-requests.md
* https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests

If you want to spend a bit more time writing docs, it'd be great if you worked on a consolidated document: https://github.com/wp-cli/handbook/issues/3

**Comment by aaemnnosttv** [comment]
> If you want to spend a bit more time writing docs, it'd be great if you worked on a consolidated document: wp-cli/handbook#3

I may do that.

**Comment by danielbachhuber** [comment]
> I may do that.

Sounds good, thanks @aaemnnosttv 

Closing this issue as wontfix. We can always re-evaluate later if some additional information comes to light.
