### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by OussamaElgoumri** [wp-cli/wp-cli#3997]
i created a small script to automate some tasks on wordpress, the script uses `shell_exec` to run wp, when i toke the code to the host, the script run with no problem from the command line, but when i send a post request to run the same script i get 403 forbidden.

```php
// $HOME/public_html/app.php

$output = shell_exec("php wp plugin list --field=name");
echo $output;
// return 403 forbidden
```

the post request that return 403 forbidden
`curl http://example.com/app.php --data "key=value"`

no problem when i run it from the command line
`php app.php` return the list of plugins names

**Comment by danielbachhuber** [comment]
Hi @OussamaElgoumri,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
