### ISSUE TITLE
Longer password length 

### ISSUE THREAD

**Issue by tillkruss** [wp-cli/wp-cli#3998]
When running `wp create user` I get a 12 character password assigned. It would be nice if the password would be 24 characters, just like WordPress uses for generated passwords.

Probably the same for `wp core install`.

**Comment by danielbachhuber** [comment]
👍 

This change would now be made to https://github.com/wp-cli/entity-command Up for submitting a pull request?

**Comment by tillkruss** [comment]
Yes, thanks!
