### ISSUE TITLE
Proposal: site generate

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#4003]
I would like to contribute a `site generate` command, similar to `post generate` for quickly creating a number of sub sites on a multisite network.

It would mostly be a wrapper for `site create` but would also allow for a `script` option to run as a kind of provisioning script for each site after it's created. This could be a php script for running in the context of the current blog, or a shell script to run other wp-cli commands, etc.

Is this something you guys would be interested or open to having in core or you would rather see it as a package first?

**Comment by danielbachhuber** [comment]
I'm amenable to it.

Btw, new command ideas go here: https://github.com/wp-cli/ideas/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

`wp site generate` would best fit in https://github.com/wp-cli/entity-command
