### ISSUE TITLE
WP DB export and cron

### ISSUE THREAD

**Issue by aelsharawi** [wp-cli/wp-cli#4013]
Hello

I have a script that backups a wp-cli DB daily

the script runs fine manually (recived the backup sql) and  when in cron it dosent backup the db (size always 20b)

this is the part tht belongs to WP-CLI
` wp db export $BACKUPPATH/$s/$DATEFORM-$s.sql --allow-root --skip-themes --skip-plugins
    cat $BACKUPPATH/$s/$DATEFORM-$s.sql | gzip > $BACKUPPATH/$s/$DATEFORM-$s.sql.gz
    rm $BACKUPPATH/$s/$DATEFORM-$s.sql
    `

I,m on centminmod with php 7 and nginx 10.12 with latest version of wp-cli and wordpress

any ideas?

**Comment by danielbachhuber** [comment]
Hi @aelsharawi,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

**Comment by aelsharawi** [comment]
I think it is PHP 7 incompatibility.

**Comment by davidfavor** [comment]
aelsharawi wrote:
> Hello
> 
> I have a script that backups a wp-cli DB daily
> 
> the script runs fine manually (recived the backup sql) and when in cron 
> it dosent backup the db (size always 20b)
> 
> this is the part tht belongs to WP-CLI
> |wp db export $BACKUPPATH/$s/$DATEFORM-$s.sql --allow-root --skip-themes 
> --skip-plugins cat $BACKUPPATH/$s/$DATEFORM-$s.sql | gzip > 
> $BACKUPPATH/$s/$DATEFORM-$s.sql.gz rm $BACKUPPATH/$s/$DATEFORM-$s.sql|
> 
> I,m on centminmod with php 7 and nginx 10.12 with latest version of 
> wp-cli and wordpress
> 
> any ideas?

grep CRON /var/log/syslog or whatever file logs CRON events on your system.

Likely this will turn up some good debug information.

Also, your command uses "wp" rather than something like "wp-cli.phar --allow-root",
so... if "wp" is an alias + your root shell startup file only creates aliases if
there's a TTY (default behavior on most systems), then wp will never exist in cron.

Simple test workaround, change "wp" to "wp-cli.phar --allow-root" + check syslog.

**Comment by aelsharawi** [comment]
no errors shown from wp-cli step

I couldn't use wp-cli.phar, not working

I used this

`/usr/bin/wp db export $BACKUPPATH/$s/$DATEFORM-$s.sql --allow-root`


and still have the same results.

this is my log for the cron

I used @echo to know the steps running

backup domain.com: /home/nginx/domain.com/public
^[[0;34m check remote backup folder exists on gdrive
^[[0;31m deleting old backup
 craeting local backup folder
 getting the full wordpress path
backup wordpress folder
 starting the wp-cli sql export
 get google drive folder list
 create google drive folder if not present
 upload to google drive wordpress folder
Uploading /tmp/backups/domain.com/2017-04-23-domain.com.tar.gz
