### ISSUE TITLE
Clarify error message for incorrect 'DOMAIN_CURRENT_SITE'

### ISSUE THREAD

**Issue by oneumyvakin** [wp-cli/wp-cli#4015]
- wp-cli 1.1.0
- WordPress 4.7.3

*STEPS*
1. Setup site network in WordPress, create new site and create new blog post to new site.
2. Change 'DOMAIN_CURRENT_SITE' in wp-config.php to some non-existent site
3. Try to get info from this WordPress instance

*RESULT*
```
# wp --path=/var/www/vhosts/site.tld/httpdocs/
{"err_code":0,"err_message":"Site not-exists.site.tld\/ not found."}
```

*EXPECTED RESULT*
- Improve error message to something like:
'DOMAIN_CURRENT_SITE' from wp-config.php not found in prefix_blogs table

**Comment by danielbachhuber** [comment]
Thanks for the report, @oneumyvakin.

This improvement to the error message seems like a reasonable suggestion.

Want to submit a pull request for it? The corresponding code is in `WP_CLI\Runner`: https://github.com/wp-cli/wp-cli/blob/2169810bc456391f642b67a48549b12d3d16f571/php/WP_CLI/Runner.php#L1164-L1168

Pull requests are expected to have corresponding functional tests. You can find an overview here: https://make.wordpress.org/cli/handbook/pull-requests/#running-and-writing-tests

**Comment by danielbachhuber** [comment]
Here's how I was able to reproduce the issue, assuming `--dbuser=root` and an empty db password:

### Setup

```
$ wp core config --dbname=mstest --dbuser=root
Success: Generated 'wp-config.php' file.
$ wp db create
Success: Database created.
$ wp core multisite-install --url=mstest.dev --title=mstest --admin_user=wpcli --admin_email=wpcli@example.org
Admin password: y@dyUUg6JBQRf!j6Pd
Created single site database tables.
Set up multisite database tables.
Added multisite constants to 'wp-config.php'.
Success: Network installed. Don't forget to set up rewrite rules.
```
### Edit `wp-config.php` to replace `mstest.dev` with `mstest.org`

```
$ vim wp-config.php
define( 'WP_ALLOW_MULTISITE', true );
define( 'MULTISITE', true );
define( 'SUBDOMAIN_INSTALL', false );
$base = '/';
define( 'DOMAIN_CURRENT_SITE', 'mstest.dev' );
define( 'PATH_CURRENT_SITE', '/' );
define( 'SITE_ID_CURRENT_SITE', 1 );
define( 'BLOG_ID_CURRENT_SITE', 1 );
```

### Using WP-CLI produces the error

```
$ wp option get home
Error: Site mstest.org/ not found.
```

**Comment by danielbachhuber** [comment]
In order to conditionally adapt the error message, we'll need to determine the ways in which `ms_site_not_found` can be triggered (whether it's only this condition where the domain can't be found in the blogs table, or others), and make sure the error message handles all potential conditions.

**Comment by BhargavBhandari90** [comment]
@danielbachhuber 
Can you look into this: https://github.com/BhargavBhandari90/wp-cli/commit/0f857c4c7b04a486ec864e2ed6d65c8369e05b91
I tried something for this. Need some info from you.

**Comment by danielbachhuber** [comment]
@BhargavBhandari90 Can you start a pull request so we can continue the conversation on the pull request?

**Comment by BhargavBhandari90** [comment]
Requested it.
https://github.com/wp-cli/wp-cli/pull/4022
