### ISSUE TITLE
`wp core language install` should support passing multiple languages

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4018]
Commands such as `wp theme install` allow passing multiple names in order to install themes at once. `wp core language install` doesn't support this, which means installing multiple languages requires using multiple commands.

**Comment by danielbachhuber** [comment]
As a point of clarification, this change will now need to be made in https://github.com/wp-cli/language-command

**Comment by 1naveengiri** [comment]
https://github.com/wp-cli/language-command/pull/4

**Comment by 1naveengiri** [comment]
@danielbachhuber  @schlessera @johnbillion 
I think `wp core language uninstall` should also have support to uninstall multiple languages at once.

**Comment by danielbachhuber** [comment]
@1naveengiri Want to submit a PR for `wp core language uninstall` too?

**Comment by 1naveengiri** [comment]
Yes, :)

**Comment by 1naveengiri** [comment]
should I create an issue for it or just send PR?

**Comment by danielbachhuber** [comment]
> should I create an issue for it or just send PR?

PR is fine. We can keep this issue open until it's done.

**Comment by 1naveengiri** [comment]
@danielbachhuber https://github.com/wp-cli/language-command/pull/5

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢
