### ISSUE TITLE
cron --due-now runs all jobs that are due now

### ISSUE THREAD

**Issue by KwadroNaut** [wp-cli/wp-cli#4020]
`:~# wp-cli cron event run --quiet publish_future_post --due-now` will go through all cron jobs that are due now and run them. Expected result: limited to those cron jobs that are actually specified, it's written as an option and not an argument after all.

**Comment by danielbachhuber** [comment]
> Expected result: limited to those cron jobs that are actually specified, it's written as an option and not an argument after all.

👍 I think this is reasonable. Closing in favor of https://github.com/wp-cli/cron-command/issues/10
