### ISSUE TITLE
Don't error out when a cron job to be run doesn't exist

### ISSUE THREAD

**Issue by KwadroNaut** [wp-cli/wp-cli#4021]
Sometimes you want to run a cron job if it exists and is due now. If it doesn't exist, then all is fine, if it shouldn't be run now, then it shouldn't be run.
```
:~# wp-cli cron event run --quiet publish_future_post 
Error: Invalid cron event 'publish_future_post'
:~# echo $?
1
```
This is probably an OK example, using unix cron to check if an article is scheduled for publishing, if there isn't one, don't error out, rather give a warning which gets suppressed with --quiet.

**Comment by danielbachhuber** [comment]
> Sometimes you want to run a cron job if it exists and is due now. If it doesn't exist, then all is fine, if it shouldn't be run now, then it shouldn't be run.

Have you seen the `--due-now` [flag](http://wp-cli.org/commands/cron/event/run/)?

```
# Run all cron events due right now
$ wp cron event run --due-now
Success: Executed a total of 2 cron events.
```

> This is probably an OK example, using unix cron to check if an article is scheduled for publishing, if there isn't one, don't error out, rather give a warning which gets suppressed with --quiet.

I think implementing this specific feature might be better suited for a bash script, so you can ignore the return code if you want. I'm not sure why WP-CLI needs to include an option controlling the return code.

**Comment by KwadroNaut** [comment]
> Have you seen the --due-now flag?

The --due-now flag is treated like a regular argument, not a flag, and executes all cron events that are due now, see #4020 

> I think implementing this specific feature might be better suited for a bash script, so you can ignore the return code if you want. I'm not sure why WP-CLI needs to include an option controlling the return code.

WP-CLI doesn't need an option to control the return code, it should give a correct return code. Compare with an empty unix cron file: you won't get a warning or an error, there's nothing to execute. The absence of a cron job must not give an error message. An argument can be made for using a suppressible warning (--quiet).

**Comment by danielbachhuber** [comment]
> Compare with an empty unix cron file: you won't get a warning or an error, there's nothing to execute. The absence of a cron job must not give an error message.

But, in the example you provided, you included a cron job that didn't exist?

```
:~# wp-cli cron event run --quiet publish_future_post 
Error: Invalid cron event 'publish_future_post'
```

If a unix cron file has a path to a non-existent executable, it will error when it tries to execute it.

**Comment by KwadroNaut** [comment]
> But, in the example you provided, you included a cron job that didn't exist?

Point is: sometimes there's an article to be published -in the near or far future- sometimes not. And this changes irregularly. When it exists, there's nothing to be done most of the time, since publishing at a specific time happens only once for each article.

> If a unix cron file has a path to a non-existent executable, it will error when it tries to execute it.

It's a WP core job, it might be apples and oranges. 

At the moment, I'll dump all errors to /dev/null, unless you've got a better idea.

**Comment by marcocarnazzo** [comment]
I have a similar need: I have to run a cron every 5 minutes but I don't want to execute so often other jobs.

For other like us, I resolved with a taste of bash:

```
CRON_JOB="my_cron_job_name"
if $(wp cron event list | grep -q "${CRON_JOB}"); then
  wp cron event run ${CRON_JOB} --due-now
fi
```
