### ISSUE TITLE
Create make.wordpress.org/cli/dash dashboard for project maintainers

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4045]
It would be helpful to have a common dashboard that:

* [ ] <del>List pull requests labeled `review-merge`</del>
* [x] Listed all command packages with open milestones (and potentially the lasted updated issue / PR), so it was easy to identify which need release tagging.

todo: list anything else that might be useful.

**Comment by danielbachhuber** [comment]
Looking like this locally:

![image](https://cloud.githubusercontent.com/assets/36432/26604402/1ed6cbb8-453f-11e7-8a3f-77b8ffd213ad.png)

**Comment by danielbachhuber** [comment]
review-merge issues look like this:

![image](https://cloud.githubusercontent.com/assets/36432/26608342/f71c2cc4-454f-11e7-9715-551bd83f250a.png)

**Comment by gitlost** [comment]
Very nice! (I probably messed up your tests by review-merging that!)

**Comment by danielbachhuber** [comment]
Here's a neat dashboard use by Jekyll https://dashboard.jekyllrb.com/

**Comment by danielbachhuber** [comment]
Dash is live. 'review-merge' list was yanked because of #4191

**Comment by gitlost** [comment]
Where?!

**Comment by danielbachhuber** [comment]
> Where?!

Oh, https://make.wordpress.org/cli/dash/
