### ISSUE TITLE
`(Framework|Bundled)Autoloader` in Composerized stack

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4051]
The current bootstrap has the following bootstrap steps that deal with autoloading:
```
1. 'WP_CLI\Bootstrap\IncludeFrameworkAutoloader',
2. 'WP_CLI\Bootstrap\IncludePackageAutoloader',
3. 'WP_CLI\Bootstrap\IncludeBundledAutoloader',
4. 'WP_CLI\Bootstrap\IncludePHARAutoloader',
5. 'WP_CLI\Bootstrap\IncludeFallbackAutoloader',
```

This was done to be able control the order in which the different layers are loaded.

It currently includes kind of a "hack", in that 1. & 3. & 5. are all created out of the root `composer.json` file, where 1. is "everything that is not a command", 3. is "everything that is a command" and 5. is "standard Composer autoloader, to make sure we didn't miss anything. This then allows us to interject 2. and 5. into what would normally be one single autoloader.

The separation into 1. and 3. is done through a couple of regexes.

The issue that currently remains is that these regexes are not smart enough to only include classes that are required from `wp-cli/wp-cli`, so in the (more rare) case that you pull in WP-CLI as well as external commands in through a common `composer.json` file (where both WP-CLI and the external commands are dependencies), you'll end up having the classes of the external commands appear in 1. and 3. depending on how they were named.

This will almost never result in a bug, but as we now rely on 3. to know which commands to track the usage of, some of the external commands would then be tracked as well.

**Comment by schlessera** [comment]
Punted to 1.3.0. As discussed in Slack:

Right now, the classes are split based on a regex on the package name. As I didn't want to have a manually maintained list of packages, this regex was a good compromise.

The solution would be to read the `composer.json` of the framework package and collect the list of packages in there.

The point where the regex is currently applied is a merged list of all Composer packages (all dependencies).

As we have several somewhat hacky instances of reasoning about bundled packages, it might be good to abstract this info into one central location.

This could then be used for other stuff like building the handbook, etc...

**Comment by schlessera** [comment]
Punted to 1.4.0.

**Comment by danielbachhuber** [comment]
Punting on this indefinitely. We can address in the future if it ever comes up.
