### ISSUE TITLE
Allow defining `ABSPATH` manually before bootstrap

### ISSUE THREAD

**Issue by rask** [wp-cli/wp-cli#4054]
When using the `require` configuration value in project specific `wp-cli.yml` config file containing the following

```php
<?php

if (!defined('ABSPATH'))
    define('ABSPATH', __DIR__ . '/path/to/abspath/');
```

Running any command complains about ABSPATH being already defined.

Could it be possible to add a check in `Runner::set_wp_root()` to not attempt overriding the defined `ABSPATH` if it is available?

Some WordPress installations do not follow the generic method of having everything clumped inside a single directory which breaks some use-cases of WP-CLI.

The predefined `ABSPATH` works but the notices and warnings are ticking me off. :P

My problem is that setting `path` in `wp-cli.yml` forces `ABSPATH` to the same directory, which in turn breaks some configurations:

```
# `path` === '/path/to/public_html` which has subdir installation of WP core
# without predefined ABSPATH
$ wp plugin path
> This is not a WP installation <snip> ...

# with predefined ABSPATH, to make use of `WP_CONTENT_DIR`
$ wp plugin path
> /path/to/public_html/wp-content/plugins
```

**Comment by rask** [comment]
To clarify:

1. Core and plugins are installed using Composer
2. Core sits at `app/public_html/wp` and `wp-content` is at `app/public_html/wp-content` and is defined with `WP_CONTENT_DIR` which is defined inside `app/wp-config.php`
2. There is a `app/public_html/wp-config.php` which just includes the `app/wp-config.php` file.

**Comment by danielbachhuber** [comment]
> Could it be possible to add a check in `Runner::set_wp_root()` to not attempt overriding the defined `ABSPATH` if it is available?
> 
> Some WordPress installations do not follow the generic method of having everything clumped inside a single directory which breaks some use-cases of WP-CLI.

While it seems easy enough to make this change, WP-CLI has historically only officially supported WordPress install configurations that you can also achieve through the web interface. Introducing this check implies we support every potential installation configuration, which is a rabbit hole I'm not keen to enter.

> My problem is that setting path in wp-cli.yml forces ABSPATH to the same directory, which in turn breaks some configurations:
> ```
> # `path` === '/path/to/public_html` which has subdir installation of WP core
> # without predefined ABSPATH
> ```

It seems you're using `--path=<path>` incorrectly. It's meant to be used to set `ABSPATH`.

If WP is installed to a `wp/` subdirectory, then you should use `--path=/path/to/public_html/wp`.

**Comment by rask** [comment]
I found that a 3rd party package was somehow overriding my `wp-config.php` (i.e. creating one where one should not be). I need to verify this was not the cause of my issues here and get back to you.

**Comment by rask** [comment]
Hello and sorry for the delay, forgot to get back to you. It was indeed an issue with a Behat extension messing with paths and now things are in working order as far as I know.
