### ISSUE TITLE
Error 1044:  Access denied for user

### ISSUE THREAD

**Issue by cagross** [wp-cli/wp-cli#4056]
I'm trying to install WordPress using WP-CLI, but getting an 'access denied' error when running _wp db create_. Specifically, my steps were:

```
cag8f [~/www]$ wp core config --dbname=my-db-name --dbuser=my-db-user --dbpass=my-db-password
*Success: Generated wp-config.php file.*
cag8f [~/www]$ chmod 644 wp-config.php
cag8f [~/www]$ wp db create
*ERROR 1044 (42000) at line 1: Access denied for user 'my-db-user'@'localhost' to database 'my-db-name'*
```
I found some other issues in this repo that seemed to relate, but none seemed to have a resolution.  One indicated it was a "MySQL config error."

[Post 1](https://github.com/wp-cli/wp-cli/issues/1408)
[Post 2](https://github.com/wp-cli/wp-cli/issues/2589)
[Post 3](https://github.com/wp-cli/wp-cli/issues/1300)

I double checked wp-config and all information seemed correct.

Any ideas on how I can troubleshoot this further?

**Comment by danielbachhuber** [comment]
Can you verify `my-db-user` has permission to create new databases?

**Comment by cagross** [comment]
>> Can you verify my-db-user has permission to create new databases?

I can try, but I'd need some assistance doing that.  I've tried a couple
things to determine privileges, but with no luck:

I tried opening phpmyadmin, and as I understand, there should be a 'Users'
option, but there is none.  But now, after some cursory research, I see
that perhaps this feature was removed for cpanel users of phpmyadmin.

I tried opening cpanel-->MySQL Databases, but that just seems to list the
users, their names, and allow me to add, remove, or change password.  I can
also add users to databases here.  But I don't see an option to check user
privileges.

I have SSH access to my server, although to date I have not used it to
connect to MySQL.  Perhaps I should try, then use SHOW GRANTS
<https://dev.mysql.com/doc/refman/5.7/en/show-grants.html>?

FYI my web hosting is done by Go Daddy, and I'm on a shared server.

On Wed, May 10, 2017 at 12:24 AM, Daniel Bachhuber <notifications@github.com

**Comment by danielbachhuber** [comment]
> I can try, but I'd need some assistance doing that.  I've tried a couple
> things to determine privileges, but with no luck:

Ok. GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
