### ISSUE TITLE
Clean up disabled WPCS sniffs

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4058]
Many sniffs were disabled in a57b9fb22789566167758ba0fecafa3fe043f1f9 (#4057).

We should eventually restore them, and then clean up affected files. When we restore them, it would be helpful to only restore one sniff per pull request to make the file churn easily understandable.

* [x] Generic.ControlStructures.InlineControlStructure.NotAllowed
* [x] Generic.Formatting.DisallowMultipleStatements.SameLine
* [x] Generic.Formatting.SpaceAfterCast.NoSpace
* [x] Generic.Functions.OpeningFunctionBraceKernighanRitchie.ContentAfterBrace
* [x] Generic.Functions.OpeningFunctionBraceKernighanRitchie.SpaceBeforeBrace
* [x] Generic.PHP.LowerCaseKeyword.Found
* [x] Generic.PHP.LowerCaseConstant.Found
* [x] Generic.PHP.NoSilencedErrors.Discouraged
* [x] Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed
* [x] Generic.WhiteSpace.ScopeIndent.Incorrect
* [x] Generic.WhiteSpace.ScopeIndent.IncorrectExact
* [x] PEAR.Functions.FunctionCallSignature.Indent
* [x] PEAR.Functions.FunctionCallSignature.EmptyLine
* [x] PEAR.Functions.FunctionCallSignature.SpaceAfterOpenBracket
* [x] PEAR.Functions.FunctionCallSignature.SpaceBeforeCloseBracket
* [x] PEAR.Functions.FunctionCallSignature.SpaceBeforeOpenBracket
* [x] PSR2.ControlStructures.ElseIfDeclaration.NotAllowed
* [x] Squiz.Strings.ConcatenationSpacing.PaddingFound
* [x] Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword
* [x] Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis
* [x] Squiz.Commenting.LongConditionClosingComment.Missing
* [x] Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingAfterOpen
* [ ] Squiz.PHP.DisallowMultipleAssignments.Found
* [x] Squiz.Strings.DoubleQuoteUsage.NotRequired
* [x] Squiz.WhiteSpace.SuperfluousWhitespace.EndLine
* [x] WordPress.Arrays.ArrayDeclaration.NotLowerCase
* [x] WordPress.Arrays.ArrayDeclaration.NoComma
* [x] WordPress.Arrays.ArrayDeclaration.NoCommaAfterLast
* [x] WordPress.Arrays.ArrayDeclaration.SpaceAfterKeyword
* [x] WordPress.Arrays.ArrayDeclarationSpacing.AssociativeKeyFound
* [x] WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener
* [x] WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser
* [x] WordPress.Arrays.ArrayKeySpacingRestrictions.SpacesAroundArrayKeys
* [x] WordPress.Arrays.ArrayKeySpacingRestrictions.NoSpacesAroundArrayKeys
* [x] WordPress.DB.RestrictedFunctions.mysql_mysql_host_to_cli_args
* [ ] WordPress.Files.FileName.InvalidClassFileName
* [ ] WordPress.Files.FileName.NotHyphenatedLowercase
* [ ] WordPress.NamingConventions.ValidFunctionName.FunctionNameInvalid
* [ ] WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid
* [ ] WordPress.NamingConventions.ValidVariableName.NotSnakeCaseMemberVar
* [ ] WordPress.NamingConventions.ValidVariableName.MemberNotSnakeCase
* [ ] WordPress.NamingConventions.ValidVariableName.NotSnakeCase
* [x] WordPress.PHP.YodaConditions.NotYoda
* [x] WordPress.WhiteSpace.CastStructureSpacing.NoSpaceBeforeOpenParenthesis
* [x] WordPress.WhiteSpace.CastStructureSpacing.NoSpaceAfterCloseParenthesis
* [x] WordPress.WhiteSpace.ControlStructureSpacing.BlankLineAfterEnd
* [x] WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceAfterStructureOpen
* [x] WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceAfterOpenParenthesis
* [x] WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceBeforeOpenParenthesis
* [x] WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceAfterCloseParenthesis
* [x] WordPress.WhiteSpace.ControlStructureSpacing.NoSpaceBeforeCloseParenthesis
* [x] WordPress.WhiteSpace.ControlStructureSpacing.ExtraSpaceAfterOpenParenthesis
* [x] WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter
* [x] WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore

**Comment by GaryJones** [comment]
Noting that PRs for the commit references above are not yet created, until a [blocker](https://github.com/DealerDirect/phpcodesniffer-composer-installer/pull/39) has been fixed.

**Comment by Potherca** [comment]
FYI: The related merge-request(s) in `dealerdirect/phpcodesniffer-composer-installer` have just been released as `v0.4.3`.

**Comment by GaryJones** [comment]
@danielbachhuber [said](https://github.com/wp-cli/wp-cli/pull/4335#issuecomment-329688181) that pull requests that contained small groups of files that addressed multiple standards was acceptable, so that's what I've done, referenced in the 11 PRs above.

**Comment by gitlost** [comment]
Unfortunately as you can see it's not possible to do it that way as the tests will fail, so I think the originally suggested approach of only enabling one or two sniffs globally at a time is the way to go.

**Comment by GaryJones** [comment]
Hmmm. That will make visual reviewing trickier since the sniffs work together to produce the end result.

There's no easy way that I know of (ping @jrfnl) to limit exclusions to just one group of files.

The other option is just to do all sniffs for all files in one go, which is what I wanted originally. Yes, it's a lot to review in one go, but the tests will pass, and it's the technical debt repayment for letting it get this far. The tests passing should show that no functionality has been changed and that it's safe to merge.

**Comment by gitlost** [comment]
> the sniffs work together to produce the end result.

From my experimenting, many are independent.

> The tests passing should show that no functionality has been changed

Alas the tests are far from comprehensive.

Anyway I got `phpcbf` (2.9.1) working locally and noticed that (without changing the current `phpcs.xml.dist`, which passes `phpcs`) running `phpcbf` applied `PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket` and `PEAR.Functions.FunctionCallSignature.CloseBracketLine` which messed up the source. After adding these to the exclusion list `phpcbf` ran without changing anything.

Then commenting out the first excluded rule (one of the scariest but also probably the most useful) `Generic.ControlStructures.InlineControlStructure.NotAllowed` produced what looked like a good result with only one indentation error that would need to be fixed manually.

So I'd recommend going with this:
```
@@ -20,7 +20,7 @@
     <exclude-pattern>*/vendor/*</exclude-pattern>
 
     <rule ref="WordPress-Core">
-        <exclude name="Generic.ControlStructures.InlineControlStructure.NotAllowed" />
+        <!--exclude name="Generic.ControlStructures.InlineControlStructure.NotAllowed" /-->
         <exclude name="Generic.Formatting.DisallowMultipleStatements.SameLine" />
         <exclude name="Generic.Formatting.SpaceAfterCast.NoSpace" />
         <exclude name="Generic.Functions.OpeningFunctionBraceKernighanRitchie.ContentAfterBrace" />
@@ -31,6 +31,8 @@
         <exclude name="Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed" />
         <exclude name="Generic.WhiteSpace.ScopeIndent.Incorrect" />
         <exclude name="Generic.WhiteSpace.ScopeIndent.IncorrectExact" />
+        <exclude name="PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket" /> <!--Unreported by phpcs but applied by phpcbf -->
+        <exclude name="PEAR.Functions.FunctionCallSignature.CloseBracketLine" /> <!--Unreported by phpcs but applied by phpcbf -->
         <exclude name="PEAR.Functions.FunctionCallSignature.Indent" />
         <exclude name="PEAR.Functions.FunctionCallSignature.EmptyLine" />
         <exclude name="PEAR.Functions.FunctionCallSignature.SpaceAfterOpenBracket" />
```
as the basis for the first PR, to be reviewed by everyone before merging.

**Comment by jrfnl** [comment]
> There's no easy way that I know of (ping @jrfnl) to limit exclusions to just one group of files.

PHPCS 3.x contains a [`gitmodified` filter](https://github.com/squizlabs/PHP_CodeSniffer/commit/4315292970fb1e48cf14b4a9012c6cf78f22df68) which may be useful here to limit the report to only those files which were modified. I haven't played with it yet, but I suspect this filter may only work in a pre-commit state, so not sure whether it would actually be useful here.

Looking at the discussion here, I would like to offer an alternative approach to the PR(s) for consideration:
Have only one PR, but have a series of commits in that PR each addressing a different thing. The final commit should then be a passing build, but having the individual commits in the PR will make it easier to review the PR.
The commits could either be the way @GaryJones has set things up already:
- removing all the exclusions
- addressing parts of the codebase in separate commits folder by folder

An alternative would be to:
- remove one exclusion, run phpcbf over all code, review & commit
- remove the next exclusion... etc

The first approach make reviewing commits easier as you see the final result for each file.
The second approach makes reviewing commits easier in that the reviewer only has to focus on one particular type of change for each commit.

> Anyway I got phpcbf (2.9.1) working locally and noticed that (without changing the current phpcs.xml.dist, which passes phpcs) running phpcbf applied PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket and PEAR.Functions.FunctionCallSignature.CloseBracketLine which messed up the source. After adding these to the exclusion list phpcbf ran without changing anything.

There is a reason for those two being enabled for the fixer while being disabled for the sniffer, see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/968 and https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1020

As a side-note, I would say that the PEAR sniff used for this may need to be replaced by a more WP specific sniff, but that's going to be quite a lot of work, so might still take a while before that change is made in WPCS.

Side-note for @gitlost: I would strongly suggest using PHPCS `master` or at least `3.0.2` for big codebase fixing projects at the moment, as the WP Core CS project has led to improvement upstream which will be in the 3.x branch, but mostly won't be in the 2.x branch of PHPCS.

Anyway, hope this input helps.

**Comment by danielbachhuber** [comment]
Just to weigh in here.

To land the pull requests that have already been submitted, I've been reverting the "PHPCS: Remove exclusions that can be fixed" changeset so Travis passes.

Once all of the pull requests are merged, I'll create a new pull request restoring "PHPCS: Remove exclusions that can be fixed".

**Comment by gitlost** [comment]
> Have only one PR, but have a series of commits in that PR each addressing a different thing

Apart from a time lag issue with this, per-commit reviewing would be difficult to follow I think, and just doesn't sit well with github.

> There is a reason for those two being enabled for the fixer while being disabled for the sniffer

I'm sorry but I consider this a bug. `phpcbf` should never apply anything not reported by `phpcs`.

>  I would strongly suggest using PHPCS master or at least 3.0.2 

Ta, will do.

**Comment by GaryJones** [comment]
> To land the pull requests that have already been submitted, I've been reverting the "PHPCS: Remove exclusions that can be fixed" changeset so Travis passes.
> 
> Once all of the pull requests are merged, I'll create a new pull request restoring "PHPCS: Remove exclusions that can be fixed".

That's a great approach - nice one.

**Comment by danielbachhuber** [comment]
We can leave the remaining sniffs ignored:

```
<rule ref="WordPress-Core">
	<exclude name="WordPress.Files.FileName.InvalidClassFileName" />
	<exclude name="WordPress.Files.FileName.NotHyphenatedLowercase" />
	<exclude name="WordPress.NamingConventions.ValidFunctionName.FunctionNameInvalid" />
	<exclude name="WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid" />
	<exclude name="WordPress.NamingConventions.ValidVariableName.NotSnakeCaseMemberVar" />
	<exclude name="WordPress.NamingConventions.ValidVariableName.MemberNotSnakeCase" />
	<exclude name="WordPress.NamingConventions.ValidVariableName.NotSnakeCase" />
</rule>
```

**Comment by jrfnl** [comment]
@danielbachhuber If you like, you can simplify that block to exclude the complete sniffs as you're now excluding (nearly all) the individual error messages.

The difference is that if WPCS would add new errors to one of these existing sniff, you would with the above block still get the new errors, while with the below block, you wouldn't see them. Up to you what you prefer.

```xml
<rule ref="WordPress-Core">
	<exclude name="WordPress.Files.FileName" />
	<exclude name="WordPress.NamingConventions.ValidFunctionName" />
	<exclude name="WordPress.NamingConventions.ValidVariableName" />
</rule>
```

**Comment by danielbachhuber** [comment]
@jrfnl Ah. Want to submit a pull request to that effect?

**Comment by jrfnl** [comment]
@danielbachhuber I'm working on other things atm, so will happily leave it for someone else to pick up.

**Comment by GaryJones** [comment]
A couple of the excludes are handled in open PRs.

**Comment by jrfnl** [comment]
For whomever will be working on sorting out the ruleset - you may find the [WPCS custom properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) wiki page useful as well.
