### ISSUE TITLE
Use slug as identifier where possible

### ISSUE THREAD

**Issue by mimecine** [wp-cli/wp-cli#4060]
Something that is bugging me when I work with wp-cli is that I often wish I could specify a slug instead of an id when I do actions on individual items. It would be convenient when using pipes or when you are working on two different installs:
$ wp terms update category miscellaneous --description="Misc Stuff"
Having to look up the id before an edit seems counterproductive when slugs are unique per taxonomy or post_type (or are they not? parent/slug vs slug in Pages?) 
I'd love to have a crack at it! I'm a slow, rusty programmer though so any pointers at where to start would be welcome..

**Comment by danielbachhuber** [comment]
> Something that is bugging me when I work with wp-cli is that I often wish I could specify a slug instead of an id when I do actions on individual items.

Related https://github.com/wp-cli/wp-cli/pull/3896

> Having to look up the id before an edit seems counterproductive when slugs are unique per taxonomy or post_type (or are they not? parent/slug vs slug in Pages?)

They're unique per taxonomy and post type. I think it makes more sense to start with terms, as it's more common to refer to a term by its slug than it is a post.

> I'd love to have a crack at it! I'm a slow, rusty programmer though so any pointers at where to start would be welcome..

Sure! I've created a new issue for it in the repo for that specific codebase: https://github.com/wp-cli/entity-command/issues/13

For a primer on writing commands, check out the commands cookbook: https://make.wordpress.org/cli/handbook/commands-cookbook/

**Comment by mimecine** [comment]
...and this explains why I couldn't skim my way to where it would be implemented. It's in a different repo:) Thanks!
