### ISSUE TITLE
core verify checksum and .gz files

### ISSUE THREAD

**Issue by anantshri** [wp-cli/wp-cli#4065]
Let me explain the situation:
1. I use wp-cli for running some daily checks on my server. `wp core verify-checksums` being one of the commands.
2. I have nginx with gzip-static installed (https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html) which means i pre-create the .gz files for quicker turnaround on requests.

with above two in place verify-checksums keep giving me error that .gz file should not be present. and as its gzip of every css and every js i endup with 100's of warning. Any specific suggestion what could be going wrong.

**Comment by danielbachhuber** [comment]
Hi @anantshri,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
