### ISSUE TITLE
Report error when broken records are encountered in user meta get

### ISSUE THREAD

**Issue by KwadroNaut** [wp-cli/wp-cli#4068]
Used a badly written plugin in the past (that's a common thing to do, I've been told ;-)), so we ended up with some broken records.

Broken example:
```
$ user meta get 123 ym_custom_fields  --format=yaml --debug
[…]
Debug (bootstrap): Loaded WordPress (0.647s)
Debug (bootstrap): Running command: user meta get (0.647s)
---
- 'a:9:{i:7;s:3:"Jan";i:8;s:5:"Klaas";i:9;s:0:"";i:10;s:13:"Streetname 7";i:11;s:4:"1111";i:12;s:4:"Genk";i:13;s:6:"Belgi'
~# echo $?
0
```

Non-broken record:
```
$ user meta get 321 ym_custom_fields  --format=yaml --debug
[…]
Debug (bootstrap): Loaded WordPress (0.587s)
Debug (bootstrap): Running command: user meta get (0.587s)
---
7: Bridget
8: Name1234
9: ""
10: Streetname 7
11: "1111"
12: Genk
13: België
14: ""
15: vrouwelijk
```

Especially when using the debug flag, I expected it to be more verbose when encountering broken records.

**Comment by danielbachhuber** [comment]
Hi @KwadroNaut,

Thanks for the report.

> Especially when using the debug flag, I expected it to be more verbose when encountering broken records.

I'm not sure I understand what you expect WP-CLI to do. If you have broken serialized data, how would WP-CLI know what's broken in the serialization?

Can you clarify further?

**Comment by danielbachhuber** [comment]
Also, it's worth noting WP-CLI uses `get_user_meta()` under the hood, so it doesn't really have visibility into whether or not the source is broken — only the value returned by `get_user_meta()`.

**Comment by KwadroNaut** [comment]
Seems you're right about get_user_meta() not actually checking the data it has, thus not emitting any warnings nor errors. However, the --format stuff, seems to be from wp-cli? I expected a notice, warning or error when such serialized entries are obviously incorrect and I try to show them in a (re-)formatted way. Is the is_serialized() from wp doing any meaningful checks?

The most basic checks for WP-CLI, could be: check if it's a string, check the length. I think that 98% of the broken data would be noticed that way.

**Comment by danielbachhuber** [comment]
> However, the --format stuff, seems to be from wp-cli?

Correct.

> I expected a notice, warning or error when such serialized entries are obviously incorrect and I try to show them in a (re-)formatted way.

How would WP-CLI know the entry is expected to be serialized, if it only renders the return value from `get_user_meta()` ?

**Comment by KwadroNaut** [comment]
I get your point, and I'll revert to sanitizing/dealing with the content and strings with tools that are designed for parsing the data wp-cli agnostically spits out.
