### ISSUE TITLE
Maxgalleria Incompatibility

### ISSUE THREAD

**Issue by PositiveLions** [wp-cli/wp-cli#4069]
Steps to reproduce.
1.) Disable all plugins
2.) Enable Maxgalleria plugin
3.) Enable Maxgalleria Facebook plugin (or almost any other Maxgalleria plugin)
4.) Run: `wp eval "echo 'hi';"`  (or any wp command)
5.) See fatal error

Unfortunately this means that I can't control any sites with WP-CLI if Maxgalleria and any of its other plugins are active.

**Comment by danielbachhuber** [comment]
Hi @PositiveLions 

You can use the `--skip-plugins=<plugins>` argument to skip the loading of specific plugins when using WP-CLI. See https://make.wordpress.org/cli/handbook/config/
