### ISSUE TITLE
wp site list fails if DOMAIN_CURRENT_SITE not set

### ISSUE THREAD

**Issue by slarti-b** [wp-cli/wp-cli#4071]
The `wp site list` command is very useful in multi-site.  If you want to write scripts which are site-agnostic you need to be able to run this without specifying a --rul - either to loop all sites returned or just use the first (usually loop).

This works if DOMAIN_CURRENT_SITE is defined in wp-config.php  However, if that is not defined it fails with _Error: Site  not found._  The error comes from https://github.com/wp-cli/wp-cli/blob/d9d405a4ca01ba23e80277b8cb9000857e84e0cd/php/WP_CLI/Runner.php#L1123 but the question is why it's needed?  Can `wp site list` run earlier, before WordPress needs to load the sites, since it just needs to return a list and shouldn't care which site it is on.

Example to repeat:
```
[root@adamc-centos test]# wp core download
Downloading WordPress 4.7.4 (en_US)...
Using cached file '/root/.wp-cli/cache/core/wordpress-4.7.4-en_US.tar.gz'...
Success: WordPress downloaded.
[root@adamc-centos test]# wp core config --dbhost=$DB_HOST --dbname=$DB_SCHEMA --dbuser=$DB_USER --dbpass=$DB_PASS --dbcollate=$DB_COLLATE
Success: Generated 'wp-config.php' file.
[root@adamc-centos test]# wp db create
Success: Database created.
[root@adamc-centos test]# wp core multisite-install --url=https://eweb-local-test.carus.com --title="Dummy test Site" --admin_user=adam --admin_email=adam@example.com --skip-email --admin_password=test
Created single site database tables.
Set up multisite database tables.
Added multisite constants to 'wp-config.php'.
Success: Network installed. Don't forget to set up rewrite rules.
[root@adamc-centos test]# # Check status of DOMAIN_CURRENT_SITE
[root@adamc-centos test]# grep DOMAIN_CURRENT_SITE wp-config.php
define( 'DOMAIN_CURRENT_SITE', 'eweb-local-test.carus.com' );
[root@adamc-centos test]# wp site list
+---------+-----------------------------------+---------------------+---------------------+
| blog_id | url                               | last_updated        | registered          |
+---------+-----------------------------------+---------------------+---------------------+
| 1       | http://eweb-local-test.carus.com/ | 0000-00-00 00:00:00 | 2017-05-16 11:30:06 |
+---------+-----------------------------------+---------------------+---------------------+
[root@adamc-centos test]# # Comment out DOMAIN_CURRENT_SITE
[root@adamc-centos test]# sed -ie "s/define( 'DOMAIN_CURRENT_SITE'/#define( 'DOMAIN_CURRENT_SITE'/" wp-config.php
[root@adamc-centos test]# # Verify it is commented out
[root@adamc-centos test]# grep DOMAIN_CURRENT_SITE wp-config.php
#define( 'DOMAIN_CURRENT_SITE', 'eweb-local-test.carus.com' );
[root@adamc-centos test]# wp site list
Error: Site  not found.
```

**Comment by danielbachhuber** [comment]
> the question is why it's needed?

The code in WP-CLI is an interpretation of an error returned by WordPress.

WordPress uses the supplied request URL to determine which site to load. If there isn't a valid site to load, then WordPress halts the load process.

> Can `wp site list` run earlier, before WordPress needs to load the sites, since it just needs to return a list and shouldn't care which site it is on.

Unfortunately, no. Plugins and themes can modify the site list (however unlikely), so WordPress needs to fully load the current site before producing the list.

You're welcome to write your own WP-CLI command to do what you need, though. See Commands Cookbook for more: https://make.wordpress.org/cli/handbook/commands-cookbook/
