### ISSUE TITLE
Double quotes are not appearing correctly 

### ISSUE THREAD

**Issue by Sher-Chowdhury** [wp-cli/wp-cli#4082]
Hi, I noticed that additional doube qoutes are appearing. for example:

```
$ wp post list --path=/var/www/html --fields=ID,post_title --format=csv | grep '""'
526,"Ansible - A ""hello world"" Playbook"
```

However it should be:

```
$ wp post list --path=/var/www/html --fields=ID,post_title --format=csv | grep '""'
526,"Ansible - A "hello world" Playbook"
```

**Comment by danielbachhuber** [comment]
Sorry, I'm not sure I follow. Your second example isn't valid CSV.

Can you clarify?

**Comment by Sher-Chowdhury** [comment]
Hi Daniel,
Sorry my mistake. I didn't realise that double quotes are used as an escape character in csv files!

I'll close this ticket. 

Thanks for the fast response!

Kind regards,
Sher Chowdhury
