### ISSUE TITLE
Advising `sudo USER -i` might not be correct?

### ISSUE THREAD

**Issue by gregharvey** [wp-cli/wp-cli#4092]
If you try to run wp-cli as root you get this:

> If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
> 
> If you'd like to continue as root, please run this again, adding this flag:  --allow-root
> 
> If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
> 
>     sudo -u USER -i -- wp <command>

This is clearly a *good* thing. However, the sudo manual says:

>     -i, --login
>                 Run the shell specified by the target user's password database entry as a login shell.  This means that login-specific resource files such as .profile or .login will be read by the shell.  If a command is specified, it is passed to the shell for execution via the shell's -c option.  If no command is specified, an interactive shell is executed.  sudo attempts to change to that user's home directory before running the shell.  The command is run with an environment similar to the one a user would receive at log in.  The Command Environment section in the sudoers(5) manual documents how the -i option affects the environment in which a command is run when the sudoers policy is in use.

Key passage being "sudo attempts to change to that user's home directory before running the shell".

So if I do this:

`sudo -u jenkins -i -- wp cache flush`

It jumps to /home/jenkins and then tries to execute `wp cache flush` - which ain't gonna work. :-)

Result:

```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

This doesn't work when you explicitly pass the path as suggested either. Whereas if you `cd` to the application directory and ditch the `-i` then no more problems:

```
sudo -u jenkins  -- wp cache flush
Success: The cache was flushed.
```

w00t!

So suggest a documentation update to drop the `-i` from the sudo command?

**Comment by danielbachhuber** [comment]
> So suggest a documentation update to drop the `-i` from the sudo command?

But then what would happen to the loading of `.profile`?

>  This means that login-specific resource files such as `.profile` or `.login` will be read by the shell.

**Comment by robrecord** [comment]
How do we get around the problem highlighted by @gregharvey ?

```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
````

**Comment by gitlost** [comment]
Does 
> Whereas if you `cd` to the application directory and ditch the `-i` then no more problems:

```
sudo -u jenkins  -- wp cache flush
Success: The cache was flushed.
```
not work for you?

**Comment by robrecord** [comment]
Yes it does, but it seemed that @danielbachhuber was suggesting it wasn't wise (and hence wouldn't change the docs) because the .profile wouldn't be loaded - although I can't see how this affects me.

(Currently finding the whole situation a bit inelegant, wondering how to simplify.)

**Comment by gitlost** [comment]
What's the situation where you're running as root in the first place, is it to do with Jenkins (about which I know nothing btw!)?
