### ISSUE TITLE
The script `make_phar.php` needs to be tightly coupled to the framework version

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4095]
While I was advocating for putting the script `utils/make-phar.php` into a separate repository independent of the framework, I now think this cannot possibly be done, as that script needs to have inherent knowledge about the exact setup of the framework version it is being used against.

As an example, an issue like https://github.com/wp-cli/package-command/issues/12 crops up because there's a disconnect between the framework version and the script version. The script decides what files & folders will be put into the Phar, and that needs to exactly match the file & folder structure of the framework it is run against. Otherwise, the framework version might make use of files that the script will leave out of the Phar.

Therefore, I recommend putting that script into the `wp-cli/wp-cli` package, and removing it from any other package. A package that needs it for its tests should dev-require `wp-cli/wp-cli` and use the script from there.

**Comment by danielbachhuber** [comment]
> Therefore, I recommend putting that script into the `wp-cli/wp-cli` package, and removing it from any other package.

@schlessera Isn't this currently the case? What needs to be done with this issue?

**Comment by schlessera** [comment]
It is currently the case for all released packages, yes. I had other plans at one point, but I don't think the architecture allows for these.

Closing this for now, it has been recorded for reference anyway.
