### ISSUE TITLE
Make Good First Issues more discoverable

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4099]
The issues labeled with "Good First Issue" should be made more easily discoverable.

1. Create a page with a shortcode at `make.wordpress.org/cli/good-first-issues/` that shows a summary list of all issues labeled as such.

2. Put a link to the page created under 1. in the big grey box under the site header, with a small introductory text.

<img width="1027" alt="screenshot_2017-05-25_18_04_04" src="https://cloud.githubusercontent.com/assets/83631/26458915/014a4912-4175-11e7-92a5-be4697f75c12.png">

**Comment by danielbachhuber** [comment]
💯 Neat idea

**Comment by danielbachhuber** [comment]
![image](https://cloud.githubusercontent.com/assets/36432/26650446/4ff0494e-45fe-11e7-89e8-a243fda85c62.png)

https://make.wordpress.org/cli/good-first-issues/
