### ISSUE TITLE
wp-cli breaks when there is a plugin error

### ISSUE THREAD

**Issue by gizemcan** [wp-cli/wp-cli#4100]
Hello All,
I am running WP-CLI version: 1.1.0 and love it so far... but it often breaks when there is a problem with plugin or theme

For example; my wp-seo plugin is broken right now (error can be seen below) and I want to use wp-cli to disable that plugin but I cannot do it because any theme / plugin related things breaks wp-cli

**Would you guys be able to explain why theme/plugin related things breaks wp-cli?**

`mywebsite@ip-172-30-1-4:~/web$ wp plugin list
PHP Fatal error:  Uncaught Error: Class 'ComposerAutoloaderInita41f77dc6b6a8296b963efc9f27f398a' not found in /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/vendor/autoload_52.php:7
Stack trace:
#0 /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/wp-seo-main.php(54): require()
#1 /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/wp-seo.php(47): require_once('/var/www/global...')
#2 /var/www/mywebsite.net/web/wp-settings.php(304): include_once('/var/www/global...')
#3 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1008): require('/var/www/global...')
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(945): WP_CLI\Runner->load_wordpress()
#5 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#6 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
#7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/vendor/autoload_52.php on line 7
Fatal error: Uncaught Error: Class 'ComposerAutoloaderInita41f77dc6b6a8296b963efc9f27f398a' not found in /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/vendor/autoload_52.php:7
Stack trace:
#0 /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/wp-seo-main.php(54): require()
#1 /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/wp-seo.php(47): require_once('/var/www/global...')
#2 /var/www/mywebsite.net/web/wp-settings.php(304): include_once('/var/www/global...')
#3 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1008): require('/var/www/global...')
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(945): WP_CLI\Runner->load_wordpress()
#5 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#6 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
#7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in /var/www/mywebsite.net/web/wp-content/plugins/wordpress-seo/vendor/autoload_52.php on line 7
`

**Comment by gitlost** [comment]
You can skip loading plugins with the `--skip-plugins` global parameter. Try
```
wp --skip-plugins plugin deactivate wordpress-seo
```
(PS support questions are best asked elsewhere [http://wp-cli.org/#support](http://wp-cli.org/#support)).

**Comment by schlessera** [comment]
Just as a quick explanation on why these types of error cannot be avoided, for future reference:

WP-CLI needs to provide the same behavior than your WordPress install, so that the same resources are available (like custom post types created through plugins) and the same results are generated (like updating a post running through filters added through a plugin).
