### ISSUE TITLE
error: Could not decompress your theme files when when we hit wp scaffold _s ..

### ISSUE THREAD

**Issue by madebyaris** [wp-cli/wp-cli#4102]
Hi, thanks for great tools, currently I'm facing problem when I try to run
`wp scaffold _s testingtheme --theme_name="testing theme" --author="aris setiawan" --sassify` it give me error like this 
`Error: Could not decompress your theme files ('/tmp/underscores-S6yaf2.tmp') at '/var/www/html/testing/wp-content/themes': Incompatible Archive.`

I tried to change folder permission, but unfortunately, it didn't help,
`I use Linux gnome 16.04.2 , php 7 latest, wp-cli latest` 

thank for your help :)

**Comment by gitlost** [comment]
This could be any number of issues relating to your server setup I think. You could try
```
curl --data 'underscoresme_name=testing theme&underscoresme_slug=testingtheme&underscoresme_author=aris setiawan&underscoresme_generate_submit=Generate&underscoresme_generate=1&underscoresme_sass=1' http://underscores.me -o /tmp/testingtheme.zip
```
and see if that works, and if so unzip "/tmp/testingtheme.zip" into your "wp-content/themes" directory. (You'll need `sudo apt-get install curl` and `sudo apt-get install unzip` if you haven't them already.)

(PS support questions are best asked elsewhere http://wp-cli.org/#support).

**Comment by madebyaris** [comment]
hi @gitlost , when I tried to run that command, it's working great and I can unzip it via command,
yeah maybe there some issue with mine :/
