### ISSUE TITLE
core is-installed - ready to install / files in place

### ISSUE THREAD

**Issue by strarsis** [wp-cli/wp-cli#4106]
Sometimes it can be very helpful to know when a WordPress installation is ready for installation 
(files in place), like with the official WordPress Docker images from Docker Hub which copies 
the WordPress files after starting it up.

`wp core is-installed` only exits successfully if not only the WordPress files are in place - 
but also the setup procedure has been completed (either by running `wp core install` command or 
by filling out the installation form manually).

Edit: Currently I check for WordPress installation being ready using `wp db check` - 
it will fail when WordPress files aren't in place and/or the database not available.

**Comment by danielbachhuber** [comment]
> Sometimes it can be very helpful to know when a WordPress installation is ready for installation
> (files in place), like with the official WordPress Docker images from Docker Hub which copies
> the WordPress files after starting it up.

Could you describe this use case in a bit more detail?

> `wp core is-installed` only exits successfully if not only the WordPress files are in place -
but also the setup procedure has been completed (either by running `wp core install` command or by filling out the installation form manually).

Right. In WordPress vernacular, "installed" means "correct database tables present", in addition to the core files being in place.

What you're describing sounds more like `wp core is-download`, although I'm curious why you need WP-CLI to handle that for you.

**Comment by strarsis** [comment]
For a demo a WordPress container is started - the official one installs itself after container startup.
Before the setup.sh script can begin setting up the WordPress installation, it has to wait until WordPress (and database) became ready, see in this script: https://github.com/strarsis/twentyseventeen-onepage/blob/master/live-demo/setup.sh#L9

**Comment by danielbachhuber** [comment]
@strarsis Could you provide some direction on how you'd suggest moving forward with this improvement?

**Comment by strarsis** [comment]
`wp db check` is sufficient for me because it checks for core files in place and for database ready.

**Comment by danielbachhuber** [comment]
👌 Thanks @strarsis
