### ISSUE TITLE
Hook up build process to complete test suite.

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4108]
In https://github.com/wp-cli/wp-cli/issues/3950 , we've built a mechanism for running the combined set of tests for the framework as well as all commands, which now resides in https://github.com/wp-cli/phar-build .

* [x] Have test system download built nightly Phar: `wget -O ...`
* [x] Rename repository to reflect sole purpose as running the full test suite.
* [x] Configure Travis to run on a nightly basis.
* [x] Set up Slack notifications for build failures.

**Comment by danielbachhuber** [comment]
@schlessera I've updated the issue description with a task list of what I think's remaining here. Can you verify?

**Comment by schlessera** [comment]
@danielbachhuber I'm not sure about the first item on the check list. Maybe we're not talking about the same thing here...

The current repository was originally built to run checks _before_ building the Phar, as a result of a pull request. So, it pulls everything in via the source packages, and then runs the test suites of all these packages.

For the first item, I suppose you want to have the tests run against the final nightly build of the Phar instead, not the source that would be used for that build.

So the question is: do you want me to change the tests to download the Phar nightly and run the tests against this? Or maybe just have both mechanisms, to detect problems in either source or Phar use cases?

**Comment by danielbachhuber** [comment]
> The current repository was originally built to run checks before building the Phar, as a result of a pull request. So, it pulls everything in via the source packages, and then runs the test suites of all these packages.

Correct, this is my understanding.

> For the first item, I suppose you want to have the tests run against the final nightly build of the Phar instead, not the source that would be used for that build.

Yes. My thinking is that, given #4095, it'd be simpler (and more correct) to run the test suite against an existing distributed build.

At this point, I'm fine with catching any regressions on a nightly basis. If they start happening more frequently, we can run the test suite more often.

**Comment by danielbachhuber** [comment]
@schlessera Do you have an opinion on the new repository name? One idea (that I don't really love): `wp-cli/full-test-suite`

**Comment by schlessera** [comment]
Options:
* `wp-cli/test-runner`
* `wp-cli/nightly-tests`
* `wp-cli/automated-tests`

I think I like that last one best, as it makes it clear there's no human action required, and it is general enough to be able to take on additional related roles if it makes sense.

**Comment by schlessera** [comment]
Related: https://meta.trac.wordpress.org/ticket/3025

**Comment by danielbachhuber** [comment]
`wp-cli/automated-tests` works for me.

**Comment by danielbachhuber** [comment]
@schlessera Any sense as to when you'll be able to wrap this up?

**Comment by schlessera** [comment]
@danielbachhuber Let's discuss this tonight. There's something off that I just can't put my finger on right now (and the tests take an eternity to run). Maybe you have an idea what is happening there.

Just to give you a quick overview of the problem I have:

The tests have failures where the actual testing code that is being run seems to not match the version of the code that is executed. So, for the nightly Phar, there might be very small discrepancies, but as the Phar is the latest `master` of `wp-cli/wp-cli`, it should actually be a match for a 24h window.

However, I have tests failing like this:
```
01. $ wp --require=custom-cmd.php command invalid

    Error: 'invalid' is not a registered subcommand of 'command'. See 'wp help command' for available subcommands.
    Did you mean 'valid'?
    cwd: /var/folders/ct/673d2dy510s3dlwb_2bfwdnw0000gn/T/wp-cli-test-run-5992908b79ad11.00160541/
    exit status: 1
    In step `Then STDERR should contain:'.               # vendor/wp-cli/wp-cli/features/steps/then.php:15
    From scenario `Invalid subcommand of valid command'. # vendor/wp-cli/wp-cli/features/command.feature:84
    Of feature `WP-CLI Commands'.                        # vendor/wp-cli/wp-cli/features/command.feature
```
This failed just now, and the code to test this as well as the implementation were comitted 6 days ago...

**Comment by danielbachhuber** [comment]
@schlessera Nightly automated build just broke a second time in a week (first was https://github.com/wp-cli/package-command/pull/28):

![image](https://user-images.githubusercontent.com/36432/29579748-97dfbe0e-8728-11e7-9e80-f91295b7c5f0.png)

Could we get both successes and failures piped into `#cli` on Slack so we can close out this issue?

**Comment by schlessera** [comment]
I asked @pento for assistance regarding the broken Slack notifications. Maybe there's something off with the webhook we're using.

**Comment by danielbachhuber** [comment]
@schlessera Can you own this through to completion please?

**Comment by danielbachhuber** [comment]
Looks like we've been failing for a week:

![image](https://user-images.githubusercontent.com/36432/31585460-c885d00c-b176-11e7-9918-c01ae0cdcf8b.png)

**Comment by schlessera** [comment]
Related: https://meta.trac.wordpress.org/ticket/3025

**Comment by schlessera** [comment]
There's hope...

![image 2017-10-18 at 11 27 09 am](https://user-images.githubusercontent.com/83631/31711100-5d6eca34-b3f7-11e7-8b9d-f84dcea1a171.png)

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢
