### ISSUE TITLE
Provide an option to turn off spelling suggestions

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4114]
WP-CLI now provides spelling suggestions if you enter wrong commands, parameters or aliases.

This might potentially throw off some scripts that parse the output of an erroneous command, so it might be useful to provide an option to turn these suggestions off.

**Comment by danielbachhuber** [comment]
I'm not super keen on making this an option unless we have to, so I'd suggest we wait until this is presented as a real world problem before we fix it.
