### ISSUE TITLE
Documentation for running the development version of WP-CLI

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4119]
Prior to the great decoupling of 2017, I ran WP-CLI locally with just a clone of the git repo so I could run the development version and contribute ~~patches~~ pull requests.

It appears that in order to do this now, `composer install --prefer-source` is a required step.

This should be documented so that new contributors have clear instructions on how to run a development version of WP-CLI. Some instructions on how to stay updated (is `composer update` enough?) would help too.

**Comment by johnbillion** [comment]
Also, `composer install --prefer-source` takes _ages_ because it installs from source for every dependency. I doubt there's anything that can be done about that, though.

**Comment by danielbachhuber** [comment]
> Prior to the great decoupling of 2017, I ran WP-CLI locally with just a clone of the git repo so I could run the development version and contribute patches pull requests.

Just to clarify, you did need to run `composer install` to install the project's other dependencies.

> This should be documented so that new contributors have clear instructions on how to run a development version of WP-CLI.

Is this already covered by https://github.com/wp-cli/handbook/issues/57 ?

**Comment by johnbillion** [comment]
> Just to clarify, you did need to run composer install to install the project's other dependencies.

Ah yes

> Is this already covered by wp-cli/handbook#57 ?

The reason I opened the issue here is I thought this should be documented in the readme. I think if a developer finds a bug in WP-CLI and wants to find out how to install the development version, they're likely to read the readme on GitHub first. Having this in place in both the readme and the handbook might be a good idea.

**Comment by danielbachhuber** [comment]
> The reason I opened the issue here is I thought this should be documented in the readme. I think if a developer finds a bug in WP-CLI and wants to find out how to install the development version, they're likely to read the readme on GitHub first. Having this in place in both the readme and the handbook might be a good idea.

Makes sense.

Generally, I think we want to point people to the handbook as much as possible, because it's easier to maintain one central documentation source than it is duplicate documentation in dozens of repos.

We can keep this issue open until we revisit the contribution workflow though, and make sure `composer install --prefer-source` is noted.

**Comment by danielbachhuber** [comment]
> We can keep this issue open until we revisit the contribution workflow though, and make sure `composer install --prefer-source` is noted.

This is now documented: https://make.wordpress.org/cli/handbook/pull-requests/#setting-up
