### ISSUE TITLE
/usr/bin/env The system cannot find the path specified. (Windows)

### ISSUE THREAD

**Issue by webspecnick** [wp-cli/wp-cli#4120]
I would file this issue to a specific command, but it deals with all commands that switched from using `foo` to `/usr/bin/env foo`.

I'm running wp-cli v1.3.0-alpha on Windows 10 using git bash. wp-cli is installed using a git clone, composer install, and the bin folder is in my path. I noticed that after updating from <1.2.0 a lot of commands are now failing with the message `The system cannot find the path specified`, such as `wp config create` when it tries to run a subcommand such as `/usr/bin/env mysql`. I can run `/usr/bin/env mysql` in my bash and it'll execute without that error, but running `wp config create` the command fails and produces the error. Checking out v1.1.0 and composer installing will fix the issue (using `wp core config` instead of `wp config create`)

I think that this could be solved with some extra docs for Windows users, instead of having to switch back the commands to the previous `foo` calls, if the fix involves adding some extra lines to `.bashrc` or adjusting paths.

**Comment by danielbachhuber** [comment]
It's interesting that `mysql` worked before, `/usr/bin/env mysql` works if you call it directly, but `/usr/bin/env mysql` doesn't work when called with `proc_open()`.

Did you do anything previously to get `mysql` to work? Can you share any relevant contents of your `.bashrc` that might shed more light?

**Comment by gitlost** [comment]
I think either way there should be a check before prefixing `/usr/bin/env` that it's not on Windows (and perhaps that `/usr/bin/env`is executable). The prefixing is only done here:
```
config-command/src/Config_Command.php:			Utils\run_mysql_command( '/usr/bin/env mysql --no-defaults', array(
db-command/src/DB_Command.php:		$command = '/usr/bin/env mysqldump --no-defaults %s';
db-command/src/DB_Command.php:		self::run( '/usr/bin/env mysql --no-defaults --no-auto-rehash', array( 'execute' => $query ) );
db-command/src/DB_Command.php:		self::run( '/usr/bin/env mysql --no-defaults --no-auto-rehash', $assoc_args );
db-command/src/DB_Command.php:		self::run( '/usr/bin/env mysql --no-defaults --no-auto-rehash', $assoc_args );
db-command/src/DB_Command.php:		self::run( '/usr/bin/env mysql --no-defaults --no-auto-rehash', $mysql_args );
db-command/src/DB_Command.php:		self::run( Utils\esc_cmd( '/usr/bin/env mysqlcheck --no-defaults %s', DB_NAME ), array(
db-command/src/DB_Command.php:		self::run( Utils\esc_cmd( '/usr/bin/env mysqlcheck --no-defaults %s', DB_NAME ), array(
db-command/src/DB_Command.php:		self::run( Utils\esc_cmd( '/usr/bin/env mysqlcheck --no-defaults %s', DB_NAME ), array(
dist-archive-command/features/bootstrap/FeatureContext.php:		Utils\run_mysql_command( '/usr/bin/env mysql --no-defaults', array(
doctor-command/features/bootstrap/FeatureContext.php:		Utils\run_mysql_command( '/usr/bin/env mysql --no-defaults', array(
package-command/features/bootstrap/FeatureContext.php:		Utils\run_mysql_command( '/usr/bin/env mysql --no-defaults', array(
php-cli-tools/lib/cli/Shell.php:				$columns = (int) exec('/usr/bin/env tput cols');
scaffold-package-command/features/bootstrap/FeatureContext.php:		Utils\run_mysql_command( '/usr/bin/env mysql --no-defaults', array(
wp-cli/features/bootstrap/FeatureContext.php:		Utils\run_mysql_command( '/usr/bin/env mysql --no-defaults', array(
```
Excluding the `FeatureContext` cases, it's only done in `Config_Command`, `DB_Command` and `Shell` and in the `Shell` case it's only done when not on Windows. Perhaps add a `WP_CLI\Utlls\maybe_prefx_env()` helper.

**Comment by webspecnick** [comment]
@danielbachhuber All I had to do to get `mysql` to run was having the bin folder on my path. I am using XAMPP's mysql executable. I tested with a blank `.bashrc` and still got the same error.

I also tested on a co-worker's Windows machine. 1.2.0 causes the error, downgrading to 1.1.x fixes the error. I used a blank `.bashrc`, their `mysql` is from wamp added to their path.

**Comment by danielbachhuber** [comment]
> All I had to do to get `mysql` to run was having the bin folder on my path. I am using XAMPP's mysql executable.

Ah, make sense.

Is there an equivalent to `/usr/bin/env` on Windows that you could symlink `/usr/bin/env` to?

**Comment by gitlost** [comment]
See https://github.com/gitlost/wp-cli/pull/10 for adding a simple `WP_CLI\Utils\maybe_prefix_env()` function. I think this is a candidate for 1.2.1.

For not using `/usr/bin/env` on Windows, see for instance https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Installer/PearInstaller.php#L62

**Comment by danielbachhuber** [comment]
> See gitlost#10 for adding a simple WP_CLI\Utils\maybe_prefix_env() function. I think this is a candidate for 1.2.1.

Rather than having a dozen instances of `WP_CLI\Utlls\maybe_prefx_env()`, it'd be better to have `Utils\run_mysql_command()` dynamically adapt `/usr/bin/env` on Windows. This way, we only need to fix it once.

**Comment by gitlost** [comment]
Updated https://github.com/gitlost/wp-cli/pull/10 to do that.

**Comment by danielbachhuber** [comment]
@gitlost Can you open the PR against this repo so I can comment on it?

Also, generally speaking, can you open PRs against this repo first, so we can ensure the history remains searchable within the project?
