### ISSUE TITLE
WP Cli does not show update for plugins and themes

### ISSUE THREAD

**Issue by gulaholic** [wp-cli/wp-cli#4121]
Hi,

I’m using WordPress Multisite for a hobby website which uses WP Cli to create the initial install configuration.

After some time, the update check feature in my site seems broken thus it does not show any update available for plugins and themes.
Fortunately, update notification for WordPress core is doing good and works as expected.

Today, I checked the update using WP Cli and it does not show any update available either but actually there are updates for my plugins and themes.

I’m wondering what happened with my WP Cli installation.

Can you share your thought on this?

**I'm using the latest WP Cli version.**
PHP binary:     /usr/bin/php
PHP version:    5.6.24
php.ini used:   /etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/user
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.2.0

Thanks
NC

**Comment by danielbachhuber** [comment]
Hi @gulaholic,

It's hard to say what the problem might be without having access to debug.

Can you share the debugging you've tried? Does the problem reproduce in a stock WordPress install (no plugins active, and using a default WordPress theme) in the same environment?

**Comment by gulaholic** [comment]
Hi,

I think I found the issue. It was caused by a plugin, caching plugin to be exact.

The question is, how can a plugin interferes WP CLI function.
I thought WP CLI is a standalone software or does it use Wordpress core function to check updates?

Thank you Daniel,

**Comment by corradomatt** [comment]
@gulaholic from my understanding wp-cli runs most (if not all) of the WordPress core runtime behind the scenes. This includes plugin and theme code. This is why there are `--skip-plugins` and `--skip-themes` flags to skip some or all of these addons when running commands. If there is a php warning or fatal error caused by a plugin you'll see that output to the console when running wp-cli commands.

**Comment by danielbachhuber** [comment]
> The question is, how can a plugin interferes WP CLI function.
> I thought WP CLI is a standalone software or does it use Wordpress core function to check updates?

WP-CLI uses WordPress functions under the hood.

**Comment by reidelliott** [comment]
What are the WordPress functions used under the hood to produce `wp plugin list --format=json` ?

**Comment by schlessera** [comment]
@reidelliott It uses `get_plugins()` to retrieve a list of all plugins, and then fetches the `'update_plugins'` site transient through `get_site_transient()` to get information about available updates.

**Comment by schlessera** [comment]
Note: The `--format=json` is not specific to this particular command, but a generally way of formatting lists as a JSON array.
