### ISSUE TITLE
What Happened? Docs are getting worse on wp.org

### ISSUE THREAD

**Issue by corradomatt** [wp-cli/wp-cli#4128]
Sorry to post this here....it's obviously not the right place for it but I don't know where would be better. Documentation on wp-cli.org/commands/ was close to perfect....now on wp.org it's subpar at best. I can't find the global flags/options list which was in the sidebar with each command page.

Who's in charge of the documentation? I can help if that will make a difference.

**Comment by danielbachhuber** [comment]
> Documentation on wp-cli.org/commands/ was close to perfect....now on wp.org it's subpar at best. I can't find the global flags/options list which was in the sidebar with each command page.

Can you constructively clarify what you mean by "subpar at best"? Are you solely referring to the global parameters, or other aspects too?

**Comment by corradomatt** [comment]
Well, now it seems like I'm offending people which was not my intention. I just thought the documentation on wp-cli.org was some of the best documentation for a tool like this I've seen. I don't feel good about the new documentation on wp.org

Besides the global parameters....
* When on https://developer.wordpress.org/cli/commands/ (I get there because I bookmarked wp-cli.org/commands and I'm redirected) I see breadcrumbs. The breadcrumbs show /home/commands but when I click on home I would expect to be directed to a main wp-cli page ... not the developer resources page.
* There's no clear organization between wp-cli docs - I would expect to be able to navigate between pages of cli docs with links or some context. For example, https://developer.wordpress.org/cli/ doesn't exist.
* There should be a link to a main wp-cli.org page here - https://developer.wordpress.org/

I get it, it takes time to build these pages out and move content over from the current site. But until it's setup to have all the content and relevant info from wp-cli.org there's no reason to forward people to the wp.org site. Let's build it out in tandem and then we can turn off the wp-cli.org site when the content on wp.org is great! Not sure if I'm able to help with the wp.org site, but I can volunteer a few hours a week to help make it happen (that the least I can do....wp-cli has been such a huge help to me on a daily basis).

**Comment by danielbachhuber** [comment]
> The breadcrumbs show /home/commands but when I click on home I would expect to be directed to a main wp-cli page ... not the developer resources page.

This is an information architecture change, so I don't know that we'll be changing it, but I understand your point.

> There's no clear organization between wp-cli docs - I would expect to be able to navigate between pages of cli docs with links or some context. For example, https://developer.wordpress.org/cli/ doesn't exist.

Good point. We should either create a page there, or redirect it to wp-cli.org.

> There should be a link to a main wp-cli documentation page here - https://developer.wordpress.org/

I agree.

> The link to "github issues" on single command pages on wp.org doesn't work

It seems to work for me:

![image](https://cloud.githubusercontent.com/assets/36432/26830278/274bed12-4a7d-11e7-87ad-4e861f6813f7.png)

> The leave a comment link on single command pages doesn't work

Good point, we can get that fixed.

>  But until it's setup to have all the content and relevant info from wp-cli.org there's no reason to forward people to the wp.org site. Let's build it out in tandem and then we can turn off the wp-cli.org site when the content on wp.org is great!

For a variety of reasons, we decided to do it the way we did. But, we can continue to iterate on the new site until it's as good as the old one.

**Comment by corradomatt** [comment]
Thanks for the reply Daniel.

For the github issues, I failed to realize that it's filtering for those particular commands....very cool. And thanks for being receptive to my gripes. In spite of what it may sound like I really appreciate and respect the work you've done for wp-cli and the rest api.

**Comment by danielbachhuber** [comment]
> And thanks for being receptive to my gripes.

No worries. Just wanted to get to the source of the issue.

> In spite of what it may sound like I really appreciate and respect the work you've done for wp-cli and the rest api.

Thanks!

**Comment by danielbachhuber** [comment]
> The leave a comment link on single command pages doesn't work

For now, I've removed it in favor of this comment:
![image](https://user-images.githubusercontent.com/36432/27795005-4cb4da90-5fb9-11e7-921f-612b14bc8aac.png)

https://meta.trac.wordpress.org/changeset/5614

> The link to "github issues" on single command pages on wp.org doesn't work

I've updated it so it links to both open and closed issues about the command.

https://meta.trac.wordpress.org/changeset/5615

**Comment by corradomatt** [comment]
@danielbachhuber awesome! The docs are much improved on wp.org now. I especially like the new chapters menu sidebar on https://make.wordpress.org/cli/handbook/ - that's a great homepage for the project.

Personally I think that the commands page should have the same navigation sidebar as the handbook pages.

**Comment by danielbachhuber** [comment]
> Personally I think that the commands page should have the same navigation sidebar as the handbook pages.

Could work, although it'd need to fit within the design.

**Comment by danielbachhuber** [comment]
Adding WP-CLI to developer.wordpress.org homepage in https://meta.trac.wordpress.org/attachment/ticket/2937

**Comment by danielbachhuber** [comment]
Continuing this in other issues. For the latest, see https://github.com/wp-cli/wp-cli/issues/4244#issuecomment-320807561

**Comment by corradomatt** [comment]
Thanks @danielbachhuber -- the docs are getting WAY better!
