### ISSUE TITLE
Speed up page creation?

### ISSUE THREAD

**Issue by fbnlsr** [wp-cli/wp-cli#4129]
I'm working on a project which makes good use of WP CLI. We're using it inside a bash script which prepares a custom version of Wordpress as a build system.

In this bash script, we're creating about 150 wordpress pages, which takes a LONG time, I'd say more than ten minutes on an i7 macbook air.

Each page has its own line of WP CLI doing its thing. I was wondering if there was a way to chain the page creation commands, or any other way we could use to speed up the process?

**Comment by danielbachhuber** [comment]
Hi @fbnlsr,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
