### ISSUE TITLE
Add Composerized WP stack test

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4137]
We need a test that builds a Composerized WordPress install with both WordPress Core and WP-CLI as a dependency and then tries to run the Composer-provided WP-CLI in this way.

We'd build a `composer.json` file that includes the WordPress core from here: https://github.com/johnpbloch/wordpress-core as well as WP-CLI, both as normal dependencies

Then we run a `composer install` and test running `vendor/bin/wp` commands through it.

**Comment by pierre-dargham** [comment]
Regarding previous issue https://github.com/wp-cli/wp-cli/issues/4124, should we also think about checking that WP frontend bootstrap runs without error ? Could be useful if we go further on the autoloader refactoring, as discussed in https://github.com/wp-cli/wp-cli/issues/3928

**Comment by schlessera** [comment]
Yes, that would probably make sense, although I'm not sure we already have a custom step to check the frontend.

**Comment by danielbachhuber** [comment]
> I'm not sure we already have a custom step to check the frontend.

Could use `wp server` to start a development server, then run some ping check against the WordPress install.

**Comment by pierre-dargham** [comment]
I have made some progress on the 2 tests (command-line & web), I will clean my code and submit a PR within the week

**Comment by schlessera** [comment]
Thanks @pierre-dargham for the great work on the test!
