### ISSUE TITLE
Error in composer if WP-CLI install GLOBAL like composer package

### ISSUE THREAD

**Issue by VaLeXaR** [wp-cli/wp-cli#4138]
If WP-CLI install like composer package in global, i have error when composer generate autoload files during installing or removing another packages. 
```
[ErrorException]
  include_once(C:\Users\VaLeXaR\Code\itua/vendor/wp-cli/wp-cli/php/WP_CLI/AutoloadSplitter.php): failed to open stream: No such file or directory
```
Composer search local path either include files from global path.
```
C:\Users\VaLeXaR\AppData\Roaming\Composer\vendor\wp-cli\wp-cli\php\WP_CLI\AutoloadSplitter.php
```
In global path file exist.
If remove WP-CLI from global or use phar package error disappear.

OS: Windows 10

**Comment by schlessera** [comment]
@VaLeXaR This is a known issue: https://github.com/wp-cli/autoload-splitter/issues/5

To get around this for now, you can manually add an additional configuration key to your global `composer.json` file, like described here: https://github.com/wp-cli/autoload-splitter/pull/6#issue-233269100 (under "I was able to resolve the error with the following config setting:")

**Comment by VaLeXaR** [comment]
@schlessera Thanks.
In global `composer.json` not working. I added to project's `composer.json`.

**Comment by schlessera** [comment]
Resolved by https://github.com/wp-cli/autoload-splitter/pull/9
