### ISSUE TITLE
Problems with 1.2.0-1.2.1 using composer installation

### ISSUE THREAD

**Issue by evilebottnawi** [wp-cli/wp-cli#4141]
Command:
```
vendor/bin/wp
```

Output:
```shell
Error: Callable "Theme_Mod_Command" does not exist, and cannot be registered as `wp theme mod`.
```

**Comment by danielbachhuber** [comment]
@evilebottnawi To verify, you've recently run `composer install`?

Can you share full steps to reproduce?

**Comment by evilebottnawi** [comment]
@danielbachhuber just run `composer install`. Simple steps:
1. `cd /home/user/web/mysite`
2. `composer install`
3. `vendor/bin/wp` or `vendor/bin/wp --help` and etc, always error

**Comment by evilebottnawi** [comment]
Start debugging

**Comment by danielbachhuber** [comment]
> Start debugging

Sorry?

**Comment by evilebottnawi** [comment]
@danielbachhuber found problem.
Setting `config.classmap-authoritative` to `true` in `composer.json` throw this error.

**Comment by danielbachhuber** [comment]
> Setting `config.classmap-authoritative` to true in `composer.json` throw this error.

Ah. Any ideas how we can fix this on our end?

**Comment by evilebottnawi** [comment]
@danielbachhuber seems some classes don't put into the classmap composer (https://getcomposer.org/doc/articles/autoloader-optimization.md#how-to-run-it--2). 
I am not familiar with wp-cli on deep level :disappointed:

**Comment by gitlost** [comment]
This case typo https://github.com/wp-cli/extension-command/blob/master/src/Theme_Mod_Command.php#L20 looks very suspicious - if it's fixed and I understand composer (which I don't), then the error seems to go away.

**Comment by schlessera** [comment]
Good catch, @gitlost, that typo is very probably the culprit.

Class names for autoloading are not case-sensitive, but array keys in the optimized Composer autoloader are.

**Comment by danielbachhuber** [comment]
@evilebottnawi Just wanted to let you know that https://github.com/wp-cli/extension-command/issues/19 will land in WP-CLI proper early next week.

**Comment by danielbachhuber** [comment]
This landed in https://github.com/wp-cli/wp-cli/pull/4149
