### ISSUE TITLE
Unable to run WP-cli with sudo

### ISSUE THREAD

**Issue by dtolj** [wp-cli/wp-cli#4152]
Trying to run a simple WP command as non root `sudo wp core version` but it gives me 
`/usr/bin/env: php: No such file or directory`

php -v
PHP 7.0.19 (cli) (built: May 11 2017 10:37:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

wp --version
WP-CLI 1.2.1

uname -a
Linux xxxx 2.6.32-696.3.1.el6.x86_64 #1 SMP Thu Apr 20 11:30:02 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

which -a php
/usr/bin/php

php -m | grep -i suhosin
no output.

grep '^\$wp_version\s' wp-includes/version.php
$wp_version = '4.7.4';

which -a wp
/usr/local/bin/wp

stat $(which wp)
  File: `/usr/local/bin/wp'
  Size: 6804077         Blocks: 13296      IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 1443456     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-06-12 15:46:46.694055793 -0400
Modify: 2017-06-12 15:46:16.271752005 -0400
Change: 2017-06-12 15:46:16.271752005 -0400

wp package list
none.

Could this be a Path issue?

echo $PATH
/usr/lib64/qt-3.3/bin:/opt/rh/rh-mysql57/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

sudo -l
Matching Defaults entries for dejant on this host:
    !visiblepw, always_set_home, env_reset, env_keep="COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS", env_keep+="MAIL PS1 PS2 QTDIR USERNAME LANG
    LC_ADDRESS LC_CTYPE", env_keep+="LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES", env_keep+="LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER
    LC_TELEPHONE", env_keep+="LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY", secure_path=/sbin\:/bin\:/usr/sbin\:/usr/bin\:/usr/local/bin

User dejant may run the following commands on this host:
    (ALL) ALL

**Comment by gitlost** [comment]
What do you get when you run
```
sudo /usr/bin/env php --version
sudo which php
sudo echo $PATH
```
?

**Comment by dtolj** [comment]
`/usr/bin/env: php: No such file or directory`

why is it looking in there, my php is located in /usr/bin, both paths are in my sudo secure_path variable.
`which: no php in (/usr/local/bin)`

`/usr/lib64/qt-3.3/bin:/opt/rh/rh-mysql57/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/dejant/bin`

**Comment by danielbachhuber** [comment]
Hi @dtolj,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
