### ISSUE TITLE
Enhancement Request - Create login context for user/pass + allow context to be specified in all other commands

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#4153]
In many cases, accessing a page as a logged in user is required.

Examples...

1) Show restricted membership page, as a specific user.

2) Produce Query Monitor statistics accessing various pages.

Possible syntax...

wp login context $user $pass - where a unique context identifier is returned

wp --login-context=$context_id $command

So context would effect site view of all other commands. Wildly ambitious + would in essence emulate using curl to create this work flow.

Maybe this facility already exists + I'm just missing it in the docs.

Thanks for considering this enhancement request.

**Comment by danielbachhuber** [comment]
Hi @davidfavor,

This plugin will do the trick for you: https://wordpress.org/plugins/one-time-login/

**Comment by davidfavor** [comment]
Ah... Let's make sure I understand... If this is returned...

Success: Your one-time login URL is: http://wp.dev/wp-login.php?user_id=1&one_time_login_token=eb6f4de94323e589addb9ad3391883e1d6233bc3

Then I'd use this one time login to reference a page by crafting a URL like...

 http://wp.dev/post-slug-name?user_id=1&one_time_login_token=eb6f4de94323e589addb9ad3391883e1d6233bc3

Let me know if I have this correct.

Thanks.

**Comment by danielbachhuber** [comment]
Sorry, to clarify, the One Time Login plugin can be used to generate a login link for any existing user on the site. The login link permits global login access; it's not specific to a particular page.
