### ISSUE TITLE
Difficulty finding correct repo for commands

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4154]
I wanted to file a bug for the `wp user` command, but searching for "user" from the https://github.com/wp-cli screen does not return any results. I had to scroll through the command repos and make an educated guess about which one was correct and then look through the documentation.

**Comment by danielbachhuber** [comment]
> Difficulty finding correct repo for commands

Good observation. In your ideal world, how would you address this?

**Comment by johnbillion** [comment]
Does GitHub search the repo description when searching for repos? If so, adding something like the following would help: `This repo provides the following commands: wp user, wp this, wp that`.

**Comment by danielbachhuber** [comment]
> Does GitHub search the repo description when searching for repos?

It appears so. We could dynamically generate this description when we take on #3857

**Comment by danielbachhuber** [comment]
> We could dynamically generate this description

I don't think it's going to be realistic to try and fit all commands into the description.

Instead, we'll link to the correct repo from the docs in #4244

**Comment by johnbillion** [comment]
I don't think you need to add all the commands to the description, just the top level commands. eg. `user`, `post`, `term`, etc.

**Comment by danielbachhuber** [comment]
> I don't think you need to add all the commands to the description, just the top level commands.

Oh, good point. This seems reasonable. I'll do when I pick up #3857
