### ISSUE TITLE
DB installation script is missing

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4155]
The individual commands contain a script to prepare the DB for running tests.

The framework package seems to be missing this script.

**Comment by danielbachhuber** [comment]
> The framework package seems to be missing this script.

This is currently in https://github.com/wp-cli/wp-cli/blob/master/ci/prepare.sh#L35-L36

We can abstract to a separate script though.

**Comment by danielbachhuber** [comment]
Closing in favor of #4167

I don't see the value in moving stuff around until we have a clear direction of where we're moving it.
