### ISSUE TITLE
Means of suggesting community commands

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4157]
I'd like to have a command which works like `git blame` for WordPress post content in order to deduce who was responsible for introducing or last editing a given line of content. It could use the revisions API in order to calculate this.

This isn't something that would be a good fit for WP-CLI core. Therefore it would be great to have a place where users could suggest community commands.

Thoughts?

**Comment by schlessera** [comment]
@johnbillion The best place to suggest such commands so far is https://github.com/wp-cli/ideas/issues .

**Comment by johnbillion** [comment]
Perfect!
