### ISSUE TITLE
Publish notes from the WCEU community summit

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4166]
We had two sessions we need to publish notes for (once we receive direction on how to publish the notes):

* [x] Future of the package index @schlessera 
* [x] Contributing workflow @danielbachhuber

**Comment by danielbachhuber** [comment]
@schlessera The email I received yesterday seemed to imply someone else will take care of publishing the notes. I submitted mine through the form. Did you read the email the same?

**Comment by schlessera** [comment]
@danielbachhuber Yes, I read the same thing. This is probably also to have a final review on their part to make sure the safe space is respected.

**Comment by danielbachhuber** [comment]
I haven't seen these come through yet, so I replied to the email they sent out requesting more details.

**Comment by danielbachhuber** [comment]
Published: https://make.wordpress.org/summit/2017/07/25/wp-cli-conversations-at-the-community-summit/
