### ISSUE TITLE
Reduce size of wp-cli.phar.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4170]
`wp-cli.phar` is huge. Most of that hugeness comes from containing behat, phpunit, composer, and the Symfony components used by them.

I see composer is used by `package-command`. But was wondering if behat and phpunit are necessary? I experimented with removing them and their Symfony components, plus the "features" directory of commands, and the phar size was reduced by 30%.

**Comment by danielbachhuber** [comment]
> But was wondering if behat and phpunit are necessary?

No, they're included mistakenly.
