### ISSUE TITLE
wp-cli should check that `proc_open` and `proc_close` are enabled.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4178]
As raised by @jimlongo56 in slack and https://github.com/wp-cli/handbook/issues/73#issuecomment-310488940 wp-cli should check whether `proc_open()` and `proc_close()` are disabled and throw an error if so.

**Comment by danielbachhuber** [comment]
@gitlost So that it's easier for a new contributor to pick up, can you provide a suggested implementation for this? Where should the error happen, and what should display?

**Comment by gitlost** [comment]
Well thinking about it just issuing a warning in `WP_CLI\Runner::start()` after `check_root()` in a `check_proc_open()` function would probably be enough. It could also do a check in `Runner::run_alias_group()` (the original incident) to return an explicit error perhaps  - it was really that it was so mysteriously failing to process aliases with no indication and yet seeming to go through them that appeared so puzzling and unfriendly.

**Comment by danielbachhuber** [comment]
> Well thinking about it just issuing a warning in `WP_CLI\Runner::start()` after `check_root()` in a `check_proc_open()` function would probably be enough.

This seems like it might run too frequently, and break existing usage. We probably only should check right before `proc_open()` is set to run.

**Comment by gitlost** [comment]
Yes. Looking through there seem to be 4 cases that should error:

1. `Runner:run_alias_group()`
2. `Utils::run_mysql_command()`
3. `WP_CLI::launch()` (via `Process`)
4. `WP_CLI::runcommand()`

and 2 cases which could error or just pass through their input:

1. `Help_Command::pass_through_pager()`
2. `Utils::launch_editor_for_input()`

**Comment by gitlost** [comment]
I'll do this - probably not a good first issue anyway.
