### ISSUE TITLE
--ssh=<ssh> global parameter doesn't work when port isn't specified

### ISSUE THREAD

**Issue by freegenie** [wp-cli/wp-cli#4180]
Documentation says (https://make.wordpress.org/cli/handbook/config/#global-parameters) I can pass global parameters as arguments on the command line. For instance it's stated that I can do something like: 

```
wp --ssh=username@hostname:/my/path/to/wordpress plugin list 
```

But it looks like it's not working on current master branch, neither in latest stable release. 

Running the command with --debug I see that it's entering the SSH code but it looks like it's not taking the param from the command line:

```
Debug (bootstrap): SSH host:  (0.173s)
Debug (bootstrap): SSH port:  (0.173s)
Debug (bootstrap): SSH path:  (0.173s)
Debug (bootstrap): Running SSH command: ssh -q  -t wp 'plugin' 'list' '--debug' (0.173s)
```

**Comment by gitlost** [comment]
The format is `--ssh=[<user>@]<host>[:<port>][<path>]` - if you're not specifying a port then there's no colon.

**Comment by freegenie** [comment]
It looks like the parser function is not allowing for a null port number. PR soon.

**Comment by freegenie** [comment]
I've found debugging SSH url parser function that port must be provided, surprisingly. I took for granted it was falling back to a default like other tools like  `scp` and `git` do.

**Comment by danielbachhuber** [comment]
> I've found debugging SSH url parser function that port must be provided, surprisingly. I took for granted it was falling back to a default like other tools like `scp` and `git` do.

It's supposed to work similarly to `scp` and `git`, so this is a bug.

**Comment by danielbachhuber** [comment]
🔨
