### ISSUE TITLE
PHP Notice:Use of undefined constant bpgmZ

### ISSUE THREAD

**Issue by googlebe** [wp-cli/wp-cli#4183]
PHP 7.1.5 error
use the wp command ,notice the error bellow:
PHP Notice:  Use of undefined constant bpgmZ_ - assumed 'bpgmZ_' in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(964) : eval()'d code on line 65
Failed to find the cause of the problem？

**Comment by googlebe** [comment]
Find the problem，i custom defined the table_prefix "bpgmZ" in the wp-config.php,how can i fix it?

**Comment by schlessera** [comment]
Hi @googlebe,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
