### ISSUE TITLE
Getting releases doesn't take into account github's paging.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4186]
`CLI_Command::get_updates()` doesn't handle github's paging.

The issue is demonstrated by `features/cli.feature:68` "Patch update from 0.14.0 to 0.14.1" which will fail if run locally (without setting the `github-api` tag), because the release 0.14.1 is currently on the second page returned by github so `wp-cli` thinks it's at the latest patch release.

I actually noticed this last week but it took a while to come up with a scheme (in lieu of a proxy server https://github.com/wp-cli/wp-cli/issues/3426) to get around github's rate limiting so the tests could run on Travis.

Full disclosure in the PR to follow.

**Comment by schlessera** [comment]
Solved by #4189, but still discussing #4187 .

**Comment by danielbachhuber** [comment]
#4189 is sufficient for our needs now.
