### ISSUE TITLE
Deprecate "review-merge" label in favor of assigning wp-cli/committers for review

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4191]
GitHub introduced the ability to assign a team for review on a pull request, effectively making our "review-merge" label moot.

We should deprecate "review-merge" label in favor of assigning wp-cli/committers for review. Two things need to be done:

* [x] Update the dashboard to pull in list of pull requests based on assigned wp-cli/committers.
* [x] Update our documentation correspondingly.

Previously #4075

**Comment by danielbachhuber** [comment]
@wp-cli/committers I'm not sure I can filter pull requests through the API based on the 'wp-cli/committers' team yet.

Is assigning the team for review sufficient?

![image](https://user-images.githubusercontent.com/36432/27831478-c0d08ade-607f-11e7-9eaf-56f6d949ade9.png)

**Comment by gitlost** [comment]
> Is assigning the team for review sufficient?

I think so...

**Comment by schlessera** [comment]
No, the search does not seem to work.

Actually, I do think it should already show these PRs if you just search for your own assigned pull requests, not only for those assigned to the group. If I'm part of a group, and you assign something to that group, I want to see it if I search for the stuff that's assigned to me. Otherwise, there's no real point in having these groups...

Looks like an unfinished feature to me so far.

**Comment by danielbachhuber** [comment]
I emailed GitHub support about this too:

> Is it possible to query the issues API for pull requests assigned a specific review team?
> 
> https://developer.github.com/v3/issues/
> 
> Or, similarly, can I use the global search dashboard to search for pull requests of a review team?
> 
> https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+review-requested%3Adanielbachhuber+sort%3Aupdated-desc+
> 
> Our WP-CLI organization has a 'wp-cli/committers' team. I'm trying to figure out a way team members can see all pull requests awaiting review.
> 
> [...]
> 
> Hey Daniel,
> 
> This isn't currently possible, but it is definitely on our radar for the future. I'll add your +1 to that internally.
> 
> Best,
> Shawna

@schlessera Are the email notifications sufficient for you? Adding a `review-merge` label to PRs seems like a bit of mental overhead given we now have an alternative.

**Comment by danielbachhuber** [comment]
I've removed the 'review-merge' list from the dashboard.
