### ISSUE TITLE
Warn when version on server differs from local version

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4195]
Using `wp --ssh=<ssh>` across two different versions can produce inconsistent behavior.

```
grapplerulrich [8:26 AM] I am a bit confused the by the `language`  subcommand documentation. https://developer.wordpress.org/cli/commands/language/core/
The title and URL say `wp language core` but in the examples there is `wp core language install`. Which order is correct?
schlessera [8:47 AM] @grapplerulrich The examples are outdated. The command has been changed into `wp language core` to make room for other elements like `wp language plugin`.
[8:50] @grapplerulrich https://github.com/wp-cli/language-command/issues/8 (edited)
grapplerulrich [8:54 AM] Thanks, I found an interesting bug if locally I had version `1.2` and on the server `1.1` both versions of the command don't work when using San ssh alias.
```

From https://wordpress.slack.com/archives/C02RP4T41/p1499095618481690

When WP-CLI is used across two different versions, we should emit a warning when the versions differ.

The implementation of this might be a bit tricky. Ideally, we'd avoid a separate SSH connection when checking the version. But, it probably should be the local version checking the remote version.

**Comment by schlessera** [comment]
What if the local version sends its own version string in a transparent way? The remote can then emit a warning, and still try to complete the command. No additional connection needed.

**Comment by danielbachhuber** [comment]
> What if the local version sends its own version string in a transparent way? The remote can then emit a warning, and still try to complete the command.

This would work, but only for `>=1.3.0` (or whenever this was packaged into a stable release).

I suppose this is the easier implementation, however.

**Comment by grappler** [comment]
What if as of `1.3.0` there was a success code and if that did not exist then there would be a warning. Though any improvements that we make now will only help if version `>=1.3.0` is being used remotely or locally.

What we should also think about is when the remote version is higher than the local version.

If the remote does not receive the version then it would emit a warning too.

**Comment by danielbachhuber** [comment]
Closing as `wontfix`. I think the problem caused by this discrepancy is infrequent enough that it's not worth creating a solution for. We can always re-open in the future if there's a compelling case otherwise.
