### ISSUE TITLE
please change checksum files

### ISSUE THREAD

**Issue by computersalat** [wp-cli/wp-cli#4202]
Hi,
is it possible to change the way `checksum` files are created like:

```
$> md5sum wp-cli-1.2.1.phar > wp-cli-1.2.1.phar.md5
$> cat wp-cli-1.2.1.phar.md5
a21a6c7b4553b8e788f3a17a6eb84959  wp-cli-1.2.1.phar
```

then it would be more easy to check the `checksum` via:

```
$> md5sum -c wp-cli-1.2.1.phar.md5
wp-cli-1.2.1.phar: OK
```

same for sha512sum.
Thank you

**Comment by danielbachhuber** [comment]
> is it possible to change the way `checksum` files are created like:

Technically it's possible, but it would be a breaking change to the distribution system, so I don't think it's worth the potential repercussions.

**Comment by computersalat** [comment]
Sorry, wasn't aware that `github` is producing such a bullshit :(

**Comment by danielbachhuber** [comment]
Please watch your language and tone.

**Comment by computersalat** [comment]
I do when it is worth to do :-P
