### ISSUE TITLE
Automate RPM building

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#4204]
See #4203 

- [x] Move getting source from `%prep` to `/utils/wp-cli-updaterpm.sh`
- [x] Where to put them? `${HOME}/rpmbuild/SOURCES/`
- [x] Replace version `0.0.0`
- [x] Run `rpmbuild -bb wp-cli-rpm.spec`
- [x] Commit to wp-cli/rpm-builds, needs `apt-get install rpm rpmlint`

@murtzsarialtun

**Comment by danielbachhuber** [comment]
@szepeviktor I was planning to take https://github.com/wp-cli/wp-cli/pull/3959 and put it in https://github.com/wp-cli/rpm-build.

Want to help out with that? Once we get RPMs building, I can take care of getting them uploaded to wp-cli/builds

**Comment by szepeviktor** [comment]
Almost done in #4216 
I am not familiar with secret GitHub uploads.

**Comment by danielbachhuber** [comment]
> Commit to wp-cli/rpm-builds, needs apt-get install rpm rpmlint

@szepeviktor I'm [getting an error](https://travis-ci.org/wp-cli/rpm-build/builds/253660642):

```
$ sudo apt-get install -qq rpm rpmlint php-cli
E: Unable to locate package rpmlint
E: Unable to locate package php-cli
The command "sudo apt-get install -qq rpm rpmlint php-cli" failed and exited with 100 during .
```

Ideas on how to resolve?

**Comment by danielbachhuber** [comment]
@szepeviktor Or, do you want to run the build script locally and submit a build to the builds repo?

**Comment by szepeviktor** [comment]
Only Ubuntu Trusty has the *dependencies* of rpmlint.
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=rpmlint
rpmlint is only available in xenial.

**Comment by szepeviktor** [comment]
Trying in https://github.com/wp-cli/rpm-build/pull/1

**Comment by szepeviktor** [comment]
Could you proceed with auto-committing to wp-cli/rpm-builds?

**Comment by danielbachhuber** [comment]
> Could you proceed with auto-committing to wp-cli/rpm-builds?

What do you mean by auto-committing?

**Comment by szepeviktor** [comment]
Committing the RPM package to wp-cli/rpm-builds when there is a new release.
With the same mechanism as the phar goes to wp-cli/builds.

**Comment by szepeviktor** [comment]
> when there is a new release

When https://github.com/wp-cli/wp-cli/blob/master/VERSION is different from the version in the hook.

**Comment by danielbachhuber** [comment]
> Committing the RPM package to wp-cli/rpm-builds when there is a new release.
> With the same mechanism as the phar goes to wp-cli/builds.

Oh, right. I'm actually thinking the RPM should be built in `wp-cli/wp-cli` now and we can use the existing deployment pipeline.

**Comment by szepeviktor** [comment]
OK.

**Comment by danielbachhuber** [comment]
We can keep this open until it's done.

**Comment by danielbachhuber** [comment]
🚢
