### ISSUE TITLE
Travis testing of PHP 5.3 code

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4218]
It seems that, starting september 2017, we will not be able to test the PHP 5.3 matrix in Travis anymore.

They will switch the default Ubuntu distro from `precise` to `trusty`.

Related issue: https://github.com/travis-ci/travis-ci/issues/8072

We need to plan our next steps for dealing with this. This basically leaves us with three options:

A. Switch to docker-based testing to allow us to use our own images.
B. Test from PHP 5.4+ and hope for the best.
C. Drop official PHP 5.3 support.

**Comment by schlessera** [comment]
From what I've been able to read in the change logs and the documentation, fthe `sudo: required` container might still come with PHP 5.3.29.

So, the combination of `sudo: required` and `dist: precise` might still do the trick _after_ September 1st, 2017. We'll have to run tests, though, as I've read about conflicting results with this approach.

**Comment by danielbachhuber** [comment]
> C. Drop official PHP 5.3 support.

I'd be amenable to this.

**Comment by danielbachhuber** [comment]
> It seems that, starting september 2017, we will not be able to test the PHP 5.3 matrix in Travis anymore.

According to [this blog post](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status), we have until April 1st, 2018.

**Comment by danielbachhuber** [comment]
We'll bump minimum to PHP 5.4 at the beginning of February #4554
