### ISSUE TITLE
WP_CLI::runcommand() fails when cli PHP binary < 5.5.

### ISSUE THREAD

**Issue by madebycaliper** [wp-cli/wp-cli#4223]
Hey I'm writing a hefty migration script that is executed via a WP CLI command, which in turn calls other commands from within the "main" class file. I've been successfully using wp-cli v1.0.0 for a while, but when I just updated to v1.2.1, the script started exiting at the first use of `WP_CLI::runcommand()`.

After a lot of poking around **I found the problem was my PHP binary version**...it was set to MAMP's included `5.4.42` but when I targeted `5.5` or higher the script was able to run again.

I checked the docs here and it says the PHP req's are 5.3.29 or later, but this seems to contradict that. Am I doing something wrong or is it possible that runcommand requires a PHP binary of >5.5?

thanks!

**Comment by schlessera** [comment]
All the code is being automatically tested against PHP version from 5.3 to 7.1.

Maybe there is a problem with your 5.5 installation, or it has been compiled in an unusual way?

**Comment by madebycaliper** [comment]
It's very possible there's a problem with my setup, sure. My guess is it has to do with the nested calls to `wp` commands. Can you think of anything that would cause an unexpected failure when using `runcommand` from within another command?

**Comment by schlessera** [comment]
A possible problem could be that the environment variables necessary for running your PHP install are not brought over from one process to the next.

**Comment by schlessera** [comment]
I suspect this has more to do with the peculiarities of MAMP, rather than being a bug in WP-CLI, so this falls under support, which is out of the scope of this issue tracker.

Please head over to the #cli channel in the make.wordpress.org Slack if you want to get help with this issue.

**Comment by madebycaliper** [comment]
Thanks for response, though it feels dismissive to me. Maybe it's my lack of understanding of how your automatic testing works, but how can you be so sure that this is because of my setup?

I tried MANY different internal command in the script (`launch()`,`launch_self()`,`run_command()`, etc) ALL of which failed to run with wp cli v1.2.1 and PHP 5.4, whereas they worked perfectly for 6 months at least with wp cli v1.0.0 and PHP 5.4.  The only thing that was changed on my setup was an update to wp-cli...

**Comment by schlessera** [comment]
It was not meant to be dismissive, we're just trying to redirect communication to where it gets the best results.

If you still feel this could be a problem with WP-CLI and have specific steps for us to reproduce, please feel free to just add these steps to this ticket, and I'll reopen if I can confirm.

**Comment by madebycaliper** [comment]
Totally understand, thanks for your reply! I'll try to find some time to post a set of reproducable steps.

**Comment by danielbachhuber** [comment]
> we're just trying to redirect communication to where it gets the best results.

It's worth emphasizing this — helping someone debug is about 10x easier on Slack, which is why it's our preferred channel.
