### ISSUE TITLE
Feature Request: wp site list -- add status

### ISSUE THREAD

**Issue by corradomatt** [wp-cli/wp-cli#4229]
When listing sites on a multisite network it would be great if the status of the site was listed in the default `wp site list` command. By status I mean it would be either `active`, `archived`, `deleted` or `spam`.

In this way we could filter the list output by the status of the site(s). I'd like to try my hand with a PR for this and just wanted to start the conversation before I write any code. Comments, pros-cons and suggestions are welcomed.

**Comment by schlessera** [comment]
@corradomatt Thanks for your feature request.

Would you mind moving this over to https://github.com/wp-cli/ideas/issues ?

That's the central location where we want to discuss potential features, and besides, the `wp-cli/wp-cli` does not contain the `site` command anymore.

Thanks!

**Comment by corradomatt** [comment]
sure @schlessera - thanks!
