### ISSUE TITLE
Warn about discrepancy between repository name and package name

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4232]
When using the `package install` command with a git repository, WP-CLI will automatically add the git repository as a new entry in the `"repositories"` section of the `~/.wp-cli/packages/composer.json` and then `require` the package.

In cases where the repository identifier does not match the package identifier, this does not work correctly.

**Example:**

Assume I have a package `wp-cli/my-command` that is stored in the repo `schlessera/my-wp-cli-command`.

Running `wp package install https://github.com/schlessera/my-wp-cli-command.git` will add the following entry to the `"repositories"` section:

```
"schlessera/my-wp-cli-command": {
    "type": "vcs",
    "url": "https://github.com/schlessera/my-wp-cli-command.git"
}
```

At this point, Composer does not know what package we want to install, it only knows the repository, and assumes the package to have the same name.

When it then downloads the actual package, it is looking for `schlessera/my-wp-cli-command` in the `composer.json` file, but only finds `wp-cli/my-command`, which it rejects.

We should investigate ways to either get around this (which is probably not easily possible) or at least warn the user about what the problem is.

**Comment by Sidsector9** [comment]
@schlessera what if we could compare the names before running composer?
We have the path = 'github.com/user/package';
we could compare `user/package` with the name in `https://raw.githubusercontent.com/user/package/master/composer.json`, if it doesn't matches then throw an error?

**Comment by danielbachhuber** [comment]
@schlessera @Sidsector9 This is handled fully by https://github.com/wp-cli/package-command/pull/31, right?

**Comment by schlessera** [comment]
Yes, closing.
