### ISSUE TITLE
Update command works manually but not from Nix cron

### ISSUE THREAD

**Issue by Benqzq** [wp-cli/wp-cli#4237]
I have the following WP-CLI command to update all plugins and core. It seems to fail when being executed from cron for about a month and a half now, even though it works manually.

This is wired, given that other cron commands work just fine (I had this tested for a period).

    0 0 * * 0 for dir in /var/www/html/*/; do cd "$dir" && wp plugin update --all --allow-root; wp core update --allow-root; done

When I ran it manually (after a manual update from GUI after a period without updates), I got the following for all sites:

> Success: Plugin already updated.
> Success: WordPress is up to date.

Why would the command fail on cron? Maybe another phrasing is needed?

**Comment by danielbachhuber** [comment]
Hi @Benqzq,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by Benqzq** [comment]
Hi, I am still not sure if this is a bug. Either way, one can reproduce this by trying the same command.

**Comment by danielbachhuber** [comment]
@Benqzq If you jump into the `#cli` room in Slack, documented in the support guidelines, happy to help you debug. I'm pretty sure this is an issue with your environment.

**Comment by Benqzq** [comment]
Explanation on the problem, including solution, [is available here](https://wordpress.stackexchange.com/questions/273884/wp-cli-command-to-update-all-plugins-and-core-fails-when-executed-from-cron/275204#275204).

I explained the nature of the problem in way accessed to all levels of usage.
