### ISSUE TITLE
camelCase associated arguments returns Parameter Error.

### ISSUE THREAD

**Issue by emilushi** [wp-cli/wp-cli#4238]
I have created a custom command for setting Algolia search settings but facing a wired problem with associated arguments.
When I set the argument as camelCase as they are on Algolia, wp cli command doesn't work.

Example:

`wp comand_name indexes set_settings --name=algolia_index_name --searchableAttributes=title`
the above command returns:
`Error: Parameter errors: unknown --searchableAttributes parameter`

But the below command works perfectly:
`wp comand_name indexes set_settings --name=algolia_index_name --searchable_attributes=title`

Any help will be appreciated.

**Comment by gitlost** [comment]
WP-CLI only accepts lower-case in option names - see https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/SynopsisParser.php#L96. It's fairly standard to convert camelCase to `camel-case` or `camel_case` in these situations...

**Comment by danielbachhuber** [comment]
You can also use this type of option definition to pass any arguments through:

```
[--<field>=<value>]
: Pass arguments through to Algolia
```

@gitlost Should we get this documented in the Commands Cookbook?

**Comment by gitlost** [comment]
Oh very good, didn't think of that - yes, might be good to highlight it in the Commands Cookbook.

**Comment by emilushi** [comment]
@danielbachhuber Thanks for the help.

I will give a try with that as for the moment I resolved that by creating a function to convert snake_case to camelCase.

**Comment by danielbachhuber** [comment]
> yes, might be good to highlight it in the Commands Cookbook.

As it turns out, it's already in there:

![image](https://user-images.githubusercontent.com/36432/28573024-ff703e72-70fd-11e7-96b3-ac0bab771760.png)
