### ISSUE TITLE
Issue with wp post delete and unknown parameters on Windows

### ISSUE THREAD

**Issue by FlorianBrinkmann** [wp-cli/wp-cli#4243]
Hi!

I am trying to run the following command (running WP-CLI 1.2.1 with PHP 7.1.4 on Windows 10):

```
wp post delete $(wp post list --post_type='wp-parser-function' --format=ids)
```

And get the following error:

```
Error: Parameter errors:
 unknown --post_type parameter
 unknown --format parameter
```

Running this command works – I get a list of IDs:

```
wp post list --post_type='wp-parser-function' --format=ids
```

The whole command (with `wp post delete`) works on a web server, but it would be cool to get it working on my local machine for testing.

Thanks in advance for any help!

**Comment by danielbachhuber** [comment]
Hi @FlorianBrinkmann,

As a heads up, Windows isn't an officially supported platform.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by FlorianBrinkmann** [comment]
Didn’t notice that Windows is not officially supported, sorry :) Will take a look at the links, thanks!
