### ISSUE TITLE
UX improvements to WP-CLI command docs

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4244]
*Consolidating a few different issues into one for clarity.*

These are some near future improvements we'd like to make to the existing command docs (e.g. https://developer.wordpress.org/cli/commands/cache/add/)

### 1. Add global parameters to each command page

Global parameters currently exist here: https://make.wordpress.org/cli/handbook/config/#global-parameters

To make them more accessible when reviewing a command doc, we should summarize them somewhere on the page — possibly a sidebar or maybe even in the main content well under command options.

### 2. Add a command navigation sidebar to each command page 

> awesome! The docs are much improved on wp.org now. I especially like the new chapters menu sidebar on https://make.wordpress.org/cli/handbook/ - that's a great homepage for the project.
> 
> Personally I think that the commands page should have the same navigation sidebar as the handbook pages.

From https://github.com/wp-cli/wp-cli/issues/4128#issuecomment-313566509

### 3. Add some form of navigation bar for open issues, closed issues, and command repo

Our entry point into a command's GitHub presence currently looks like this:

![image](https://user-images.githubusercontent.com/36432/28584500-d29ac43e-7121-11e7-96a0-3d6039ad3ebd.png)

Totally meh.

It'd be great if we had some more helpful navigation UI that had links for open issues (with count), closed issues (with count), "Create a new issue" that opened in the correct repository, and a link to the package's repository generally.

Related #4043

**Comment by danielbachhuber** [comment]
@mapk When you have a moment, I'd love your design sensibilities on ^.

It would rock my world if you provided HTML/CSS that I could just plug logic into. Timing-wise, I'm hoping to complete this in the next week and a half or so.

**Comment by mapk** [comment]
1. Seems like the correct placement for this would be in the main content. A reference at the bottom? I can help design this.

2. In order to get the https://developer.wordpress.org/cli/ site to mimic the current make/cli handbook, we need to move over the O2 Plugin I think. @pento or @ocean90 might have a stronger idea how to make this happen. It will give us the new look and feel with the sidebar navigation.

3. Would this be a page by itself? A section that exists across all pages? Seems like the simplest would be a stand alone page that could highlight these? I can help design this as well.

**Comment by danielbachhuber** [comment]
> 1. Seems like the correct placement for this would be in the main content. A reference at the bottom? I can help design this.

That'd be great, thanks.

> 2. In order to get the https://developer.wordpress.org/cli/ site to mimic the current make/cli handbook, we need to move over the O2 Plugin I think.

I'm not sure I want to go that far (enabling O2 and getting everything to work there). Is there a simpler design we could go with that I can implement on my own?

> 3. Would this be a page by itself? A section that exists across all pages? Seems like the simplest would be a stand alone page that could highlight these? I can help design this as well.

It'd be a section of each command page, because the links would be different for each command.

**Comment by mapk** [comment]
1. If we're adding global parameters to each page, it might be a good idea to include them in an accordion-type of table so they aren't visually overwhelming. I've cleaned up some table styling here: https://codepen.io/mapk/pen/brwPOL?editors=0110 

Take a look and let me know if that works for no. 1.

**Comment by danielbachhuber** [comment]
> Take a look and let me know if that works for no. 1.

@mapk Looks great! Do I need to commit that to the dev hub theme or will you take care of it?

@wp-cli/committers Locally, the global params mention on command docs looks like this:

![image](https://user-images.githubusercontent.com/36432/28973656-e5634c70-7901-11e7-8cbb-39314a16b999.png)

Feel free to weigh in on https://github.com/wp-cli/handbook/pull/115 if you have feedback on the implementation.

**Comment by mapk** [comment]
@danielbachhuber If you don't mind committing it yourself, please do. I'll work on the issue notifications (no. 3) today.

**Comment by danielbachhuber** [comment]
> If you don't mind committing it yourself, please do.

Cool, I'll pick it up on Monday.

> I'll work on the issue notifications (no. 3) today.

Great!

**Comment by mapk** [comment]
I've got No.3 ready to go as well. Take a look at this: https://codepen.io/mapk/pen/YxpJqL

![screen shot 2017-08-04 at 1 49 12 pm](https://user-images.githubusercontent.com/617986/28986411-b9d9d4ce-791b-11e7-8c62-ab3eaa9200cf.png)

**Comment by danielbachhuber** [comment]
@mapk Love it! Where would you place it on the page?

**Comment by mapk** [comment]
Excellent. I guess that depends how important it is for the user to see. 

If the user is there because they want to research information (which is most likely the case), then contributing through Github would probably be secondary for them. So maybe at the bottom?

**Comment by danielbachhuber** [comment]
> If the user is there because they want to research information (which is most likely the case), then contributing through Github would probably be secondary for them. So maybe at the bottom?

Yes, this makes sense.

We also want to discourage use of GitHub as a support venue, so maybe we need some light support CTA at the top.

I'll give it some thought.

**Comment by danielbachhuber** [comment]
Looking like this locally:

![image](https://user-images.githubusercontent.com/36432/29049730-9cb85d34-7b8c-11e7-80ea-2ede40fa979c.png)

@mapk The button styles didn't translate very well directly.

@schlessera For the GitHub icon and "Create New Issue" elements to appear, we have to get the `repo_url` into post meta for the page. I'm thinking this could be included in `wp cli cmd-dump` and then stored in the `commands-manifest.json` file for importing. However, I don't have any good ideas on how to programmatically generate the correct `repo_url` for each command. Ideas?

**Comment by mapk** [comment]
@danielbachhuber It's probably missing the regular button styles. Try pulling them in from the Plugin Directory theme. Can you do that?

**Comment by schlessera** [comment]
@danielbachhuber For the repo url, it is currently safe to assume that the Composer package name matches the repo slug on Github. So, fetching the Composer package name lets us build a default GitHub URL for the repo.

**Comment by schlessera** [comment]
For the global parameters, would it make sense to include an accordion (or a similar UI element that only displays the lot on demand) with a short reference of all of them, instead of showing an arbitrary subset?

**Comment by danielbachhuber** [comment]
@mapk Closer, but I think there's still some conflict with the existing button styles:

![image](https://user-images.githubusercontent.com/36432/29070792-993061c0-7bf5-11e7-8ccb-6df6c7838bf7.png)

**Comment by mapk** [comment]
@danielbachhuber Looks like the buttons are a lot closer now.

![screen shot 2017-08-08 at 5 22 37 pm](https://user-images.githubusercontent.com/617986/29100080-31d5dafa-7c5e-11e7-805c-b4c4919a1e31.png)

Did you want to add the .btn-group css as well?

**Comment by danielbachhuber** [comment]
> Looks like the buttons are a lot closer now.

Weird. I'm not sure why I see the shading but you don't. I still see:

![image](https://user-images.githubusercontent.com/36432/29121921-602457d0-7cc5-11e7-868e-3b78b0b16aed.png)

> Did you want to add the .btn-group css as well?

Good catch. Thar be a bug in my CSS: https://meta.trac.wordpress.org/changeset/5785

**Comment by mapk** [comment]
I was viewing them in FF, you were viewing them in Chrome maybe? We need to fix the styling so it applies to all browsers. I can take a look.

**Comment by danielbachhuber** [comment]
> you were viewing them in Chrome maybe?

Yes.

> We need to fix the styling so it applies to all browsers. I can take a look.

Maybe a vendor prefix then. Let me know what I should add.

**Comment by mapk** [comment]
Looks like this change in the CSS should work.

FROM
```
-webkit-appearance: button;
```
TO
```
-webkit-appearance: none;
```

**Comment by danielbachhuber** [comment]
> Looks like this change in the CSS on the anchor tag should work.

Perfect — 🚢 

I'll handle the issue count in #4043

**Comment by danielbachhuber** [comment]
Thanks for your help with this, @mapk !
