### ISSUE TITLE
Can’t connect to local MySQL server through socket ‘/var/lib/mysql/mysql.sock’ (2)

### ISSUE THREAD

**Issue by pablito07** [wp-cli/wp-cli#4248]
Why is the mysql socket path not downloaded from php.ini?

```
$ wp db reset
error: ERROR 2002 (HY000): Can’t connect to local MySQL server through socket ‘/var/lib/mysql/mysql.sock’ (2)

wp-config.php
define('DB_HOST', 'localhost');

php.ini:
mysqli.default_socket: /var/run/mysql/mysql.sock
```

**Comment by danielbachhuber** [comment]
Hi @pablito07,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
