### ISSUE TITLE
env: mysql: No such file or directory

### ISSUE THREAD

**Issue by Nann** [wp-cli/wp-cli#4251]
wp core config --dbname=db_wp-cli --dbuser=root --dbpass=root

Mac, MAMP PRO

**wp-cli.phar --info**

PHP binary:	/usr/bin/php
PHP version:	5.5.38
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/nan
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.2.1

**wp --info**
PHP binary:	/usr/bin/php
PHP version:	5.5.38
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/nan
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.2.1

**Comment by miya0001** [comment]
@Nann 

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The PHP path isn't same with MAMP's PHP. You have to add path to the MAMP's PHP to $PATH environment variables.
