### ISSUE TITLE
Some command doesn't have `.github` directory.

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#4252]
Some command doesn't have `.github` directory.
They should have [ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE](https://github.com/wp-cli/wp-cli/tree/master/.github).

* [x] `wp (cache|transient) *` https://github.com/wp-cli/cache-command
* [x] `wp checksum` https://github.com/wp-cli/checksum-command
* [x] `wp config *` https://github.com/wp-cli/config-command
* [x] `wp core *` https://github.com/wp-cli/core-command
* [x] `wp cron *` https://github.com/wp-cli/cron-command
* [x] `wp db *` https://github.com/wp-cli/db-command
* [x] `wp (eval|eval-file)` https://github.com/wp-cli/eval-command
* [x] `wp export` https://github.com/wp-cli/export-command
* [x] `wp (option|post|comment|user|term|site) *` https://github.com/wp-cli/entity-command
* [x] `wp import` https://github.com/wp-cli/import-command
* [x] `wp language` https://github.com/wp-cli/language-command
* [x] `wp media *` https://github.com/wp-cli/media-command
* [x] `wp package *` https://github.com/wp-cli/package-command
* [x] `wp (plugin|theme) *` https://github.com/wp-cli/extension-command
* [x] `wp rewrite` https://github.com/wp-cli/rewrite-command
* [x] `wp (role|cap) *` https://github.com/wp-cli/role-command
* [x] `wp scaffold *` https://github.com/wp-cli/scaffold-command
* [x] `wp search-replace` https://github.com/wp-cli/search-replace-command
* [x] `wp server` https://github.com/wp-cli/server-command
* [x] `wp shell` https://github.com/wp-cli/shell-command
* [x] `wp super-admin *` https://github.com/wp-cli/super-admin-command
* [x] `wp (widget|sidebar) *` https://github.com/wp-cli/widget-command

**Comment by miya0001** [comment]
* [ ] `wp doctor` https://github.com/wp-cli/doctor-command
* [ ] `wp rest` https://github.com/wp-cli/restful
* [x] `wp scaffold package*` https://github.com/wp-cli/scaffold-package-command

**Comment by danielbachhuber** [comment]
@miya0001 Good catch. I was planning to do this after `wp-cli/scaffold-package-command` v0.4.0 was released (https://github.com/wp-cli/scaffold-package-command/milestone/4), so we only have to run it once per project.

**Comment by danielbachhuber** [comment]
🔨
