### ISSUE TITLE
Is it possible to run custom wp-cli command before site is installed?

### ISSUE THREAD

**Issue by onnimonni** [wp-cli/wp-cli#4258]
I would want to register my own seed command to install seed data even before WordPress is installed. I saw that `enable_maintenance_mode` is quite early in the init system and I tried to hook to that in my custom wp-cli package:
```
WP_CLI::add_hook( 'enable_maintenance_mode', function() {
	die('TESTING');
});
```

But I still ended into the site not installed error:
```
$ wp seed install
Error: The site you have requested is not installed.
Run `wp core install`.
```

I know that my package loads before that error but doesn't do anything.

How can I register a command which runs before `wp_not_installed()` function is used? I would like to achieve something like the `$ wp db` commands as they don't fail when WP is not yet installed.

**Comment by danielbachhuber** [comment]
Hi @onnimonni,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
