### ISSUE TITLE
wp db create seems like it will never work

### ISSUE THREAD

**Issue by davidfavor** [wp-cli/wp-cli#426]
To create a database requires a user with sufficient privileges to create the database.

For example, on Debian + Ubuntu a root user cnf file is used to automate scripts, so it seems like the 'wp db create' must do two things...

1) pass the root user + pass (different from wp-config user + pass)

2) no user + pass specified, see if a file like /etc/mysql/debian.cnf exists, then use it

3) else die with error

**Comment by danielmerriott** [comment]
bump :-)

So from my point of view `db create` will work 'as is' in most dev or hosted environments.
i.e. if the dbuser specified in wp-config.php is root (hopefully dev environments only!) or if the *dbuser specified already exists and already has permissions to create a database* (e.g. for example I have used various hosts that allow new databases to be created with a specific prefix - as mentioned above by @khromov). In other hosted environments, the database will likely have to be created via whatever control-panel (or will be created for the user) so `db create` isn't needed anyway.

However for those who are using their own vhost in non-dev environments, automating the creation of the database *and the database user* would still be useful. Having the option via command-line switch or config file to either load the current user's own `~/.my.cnf` or another defaults file (ala `--defaults-file /etc/mysql/debian.cnf`) and then go ahead with the database and user creation would pretty much plug the need for automating this part of the wordpress install I think?

**Comment by danielbachhuber** [comment]
Happy to include smarter behavior if someone wants to put together a pull request

**Comment by danielbachhuber** [comment]
> However for those who are using their own vhost in non-dev environments, automating the creation of the database and the database user would still be useful.

On second thought, I'm not sure why WP-CLI would need to be involved with process.

It _does_ make sense for `wp db create` to be used when the command uses database details from `wp-config.php`. WP-CLI knows how to locate the `wp-config.php`, and read the constants stored in it.

It _doesn't_ make sense for `wp db create` to be used when the command doesn't use database details stored in `wp-config.php`. In this context, `wp db create` is nothing more than a wrapper for the `mysql` binary.
