### ISSUE TITLE
The --prompt=<assoc> flag does not work for --<field> flags

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4260]
The following command fails with a usage error:

```
$ wp user update admin --prompt=user_pass
usage: wp user update <user>... --<field>=<value>
```

Presumably this is because flags such as `--user_pass` aren't real flags, rather they are values for `--<field>` used as a means of delivering values to `wp_update_user()`.

The `--user_pass` flag is a particularly good use case for a prompt. It would be great if it could work.

Here is a failing test:

```gherkin
Scenario: Update a user by prompting for the user password
  Given a WP install
  And a user file:
    """
    testuser@example.com
    newpass
    ""
  When I run `wp user create testuser testuser@example.com`
  Then I run `wp user update --prompt=user_email,user_password < user`
  Then STDOUT should not be empty

  When I run `wp user list --field=user_email`
  Then STDOUT should be:
    """
    testuser@example.com
    """
```

**Comment by johnbillion** [comment]
If we could solve https://github.com/wp-cli/entity-command/issues/19 programatically, then it could lead to this being possible.

**Comment by danielbachhuber** [comment]
> If we could solve wp-cli/entity-command#19 programatically, then it could lead to this being possible.

@johnbillion What do you mean by "programmatically"? I think defining the arguments in the command docs may actually solve both this and https://github.com/wp-cli/entity-command/issues/36

**Comment by danielbachhuber** [comment]
I think this is reasonably fixed by https://github.com/wp-cli/entity-command/pull/39

Although, I've since run into #4272
