### ISSUE TITLE
Use wp-cli features/bootstrap for bundled commands.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4261]
It's probably in the air but changing the bundled commands to use the `features/bootstrap` in their `vendor/wp-cli/wp-cli` rather than having their own copies would be good, eg by adding to each a `behat.yml`
```
default:
  paths:
    bootstrap: 'vendor/wp-cli/wp-cli/features/bootstrap'
```

**Comment by danielbachhuber** [comment]
It was a deliberate decision to avoid `behat.yml` actually. Plus, the current approach offers two distinct advantages:

* Phar users (e.g. the majority) can run the test suite against their existing executable without needing to install WP-CLI as a dependency (and make sure `wp` points to the correct path, etc.)
* The end user of the test suite can easily modify the test suite if they choose to.

Just want to provide context around why the decision was made.

**Comment by gitlost** [comment]
Ah I see, ta.

**Comment by danielbachhuber** [comment]
@gitlost Although, also related https://github.com/wp-cli/wp-cli/issues/3826
