### ISSUE TITLE
Inconsistency in help and suggestions for specially treated commands.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4265]
There's consistency issues with invoking help. For instance doing:
```bash
wp help db chec
```
(or `wp help db asdf`) in an install (or pathed to an install) will just exit, printing nothing. Whereas:
```bash
wp help db chec --path=/nowhere
```
will come up with the "not a WordPress install" error, which isn't very helpful either, while both
```bash
wp help db --path=/nowhere
wp help db check --path=/nowhere
````
will come up with the help screen, but
```bash
wp help asdf --path=/nowhere
```
won't but prints the "not a WordPres install" message.

Suggestions on typos in commands in help don't appear either, eg
```bash
wp help confi
wp help packag
wp help core instal
```
just say they're not commands.

Another issue is with the `auto_check_update()` which if forced to trigger by:
```bash
wget https://github.com/wp-cli/wp-cli/releases/download/v1.2.0/wp-cli-1.2.0.phar
echo 0 > ~/.wp-cli/cache/wp-cli-update-check
php wp-cli-1.2.0.phar help config
```
just presents you with the update question and if you say no it just exits.

I'll post a PR.

**Comment by danielbachhuber** [comment]
> won't but prints the "not a WordPres install" message.

Right. In cases where the command isn't already registered (e.g. bundled with WP-CLI itself), the command _could_ be registered in a theme or plugin. WP-CLI attempts to load WordPress to see if additional commands are registered.

**Comment by gitlost** [comment]
Yes I see that but you've asked for help. You should be able to browse the help freely without having to set options or have a WP install.

**Comment by danielbachhuber** [comment]
> You should be able to browse the help freely without having to set options or have a WP install.

What if you've asked for help from a command in a plugin?

**Comment by gitlost** [comment]
Well maybe append (or prepend) that info to the command error?

**Comment by danielbachhuber** [comment]
@gitlost Let's chat about this in Slack when you have a moment. I think there's some disconnect.

**Comment by danielbachhuber** [comment]
@gitlost Anything else we need to address here, or is this 🚢 ?

**Comment by gitlost** [comment]
I think it's :ship: for now anyway, so I'll close...

**Comment by gitlost** [comment]
I'm going to upload a new PR for this, which is basically the same as the old ones plus https://github.com/wp-cli/wp-cli/pull/4291/commits/571de94fc8ba3cc2dd0cede69835666c175381ea, ie defining `WP_DEBUG` (instead of `WP_ADMIN`) to get around the `die()` in `dead_db()`, and which I'll justify in the PR.

Just to clarify here that the failure in https://travis-ci.org/wp-cli/wp-cli/builds/264638663 (which has nothing to do with `WP_DEBUG`) mentioned in https://github.com/wp-cli/wp-cli/pull/4291#issuecomment-322402505 is current broken behaviour, and the reason the test was introduced in https://github.com/wp-cli/wp-cli/pull/4285.

The current behaviour can be reproduced by a variant of the script given in https://github.com/wp-cli/wp-cli/pull/4266#issuecomment-321643179:

```bash
set -v
wget https://github.com/wp-cli/wp-cli/releases/download/v1.3.0/wp-cli-1.3.0.phar -nc -q && chmod +x wp-cli-1.3.0.phar
rm -rf /tmp/issue_4265_wp_install
mkdir /tmp/issue_4265_wp_install
mysql --user=wp_cli_test --password=password1 --execute='DROP DATABASE IF EXISTS wp_cli_test;'
./wp-cli-1.3.0.phar core download --path=/tmp/issue_4265_wp_install
./wp-cli-1.3.0.phar config create --dbname=wp_cli_test --dbuser=wp_cli_test --dbpass=password1 --path=/tmp/issue_4265_wp_install
./wp-cli-1.3.0.phar help core --path=/tmp/issue_4265_wp_install
```
which produces:
![screenshot from 2017-08-16 15-33-02](https://user-images.githubusercontent.com/481982/29369060-63721538-8299-11e7-8c41-17f711239c67.png)

(In passing note that the check for DB connection in `wp config create` might be expanded to include checking the database exists as at the moment it only checks that the user/password/host is good.)
