### ISSUE TITLE
Fix presentation of arg arguments in command docs

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4270]
`---` is being transformed to `-—` (dash emdash):

![image](https://user-images.githubusercontent.com/36432/28973957-c255c7a2-7902-11e7-88dc-d0c1fe4ac58b.png)

**Comment by emgk** [comment]
@danielbachhuber Is these issue is inside https://github.com/wp-cli/handbook ?

**Comment by danielbachhuber** [comment]
> Is these issue inside https://github.com/wp-cli/handbook ?

The data in the handbook is correct. The problem lies in how WordPress renders the page: https://developer.wordpress.org/cli/commands/cache/add/

Specifically, there's some filter on `the_content` that automatically transforms a double-dash to an em-dash. We need to disable that in some manner, but I think we could format the arguments better too.

**Comment by danielbachhuber** [comment]
Fixed in https://meta.trac.wordpress.org/changeset/5761/
