### ISSUE TITLE
Create the Debian build in an automated manner

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#4276]
It would be nice to run the [existing Debian packaging script](https://github.com/wp-cli/wp-cli/blob/master/utils/wp-cli-updatedeb.sh) on Travis and upload the result to wp-cli/builds.

**Comment by danielbachhuber** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/3793

> run the existing Debian packaging script on Travis

Is it possible to run the script on Travis or does it need to be run inside a Docker container?

**Comment by szepeviktor** [comment]
> Is it possible to run the script on Travis or does it need to be run inside a Docker container?

Yes it is. As creating the package is just copying two-ish files into a .deb archive.

**Comment by danielbachhuber** [comment]
@szepeviktor Cool. Can you prepare a `.travis.yml` [similar to this one](https://github.com/wp-cli/rpm-build/blob/master/.travis.yml) and I'll hook it up?

**Comment by szepeviktor** [comment]
https://github.com/szepeviktor/wp-cli-debbuild/blob/master/.travis.yml

**Comment by szepeviktor** [comment]
The output will be `./php-wpcli_1.3.0_all.deb`

**Comment by szepeviktor** [comment]
Done.

**Comment by danielbachhuber** [comment]
Thanks @szepeviktor. We'll get this set up in the near future.

**Comment by szepeviktor** [comment]
You're welcome.

https://travis-ci.org/szepeviktor/wp-cli-debbuild/builds/262697297

**Comment by danielbachhuber** [comment]
@szepeviktor Setting this up now.

**Comment by danielbachhuber** [comment]
@szepeviktor Thanks again for the `.travis.yml`. Can you verify this [bot-built release](https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_1.4.0_all.deb), and then I'll set up the symlink behavior? Or is the symlink necessary?

**Comment by szepeviktor** [comment]
This is the symlink
https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_latest_all.deb
and it is outdated now.

**Comment by szepeviktor** [comment]
The deb is as good as it can be:
```
I: php-wpcli: extended-description-is-probably-too-short
E: php-wpcli: depends-on-obsolete-package depends: mysql-client => default-mysql-client
E: php-wpcli: php-script-but-no-php-cli-dep usr/bin/wp
```

**Comment by szepeviktor** [comment]
BTW the analysis appears at the end of each build log:
https://travis-ci.org/wp-cli/deb-build#L753-L754

**Comment by danielbachhuber** [comment]
Fixed the symlink 🔨
