### ISSUE TITLE
undefined method cli\Table::setAsciiPreColorized()

### ISSUE THREAD

**Issue by andreiglingeanu** [wp-cli/wp-cli#4278]
I just pulled latest code from `master` and I am on fce44997 revision.

When I try to list posts I get a raised error in response.

Reproduce:

1. Use latest master version 
2. Run `wp post list`

You'll see that error being raised:

```php
Fatal error: Call to undefined method cli\Table::setAsciiPreColorized() in ~/Projects/open_source/wp-cli/php/WP_CLI/Formatter.php on line 285
```

<hr>

By manually bisecting the code, I found out that it worked fine on cf2f753c revision and I tend to think that 5b0aa648 was the one introducing the error, can't say too much though.

**Comment by gitlost** [comment]
You need to make sure you have `wp-cli/php-cli-tools` 0.11.4 at least - try doing a `composer update`.

**Comment by andreiglingeanu** [comment]
Yup, that helped. Thanks!
