### ISSUE TITLE
New command to detect a command

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#4283]
This is very ugly: `wp help | grep '^\s*find\s'`

And also

```
$ wp help nonexistent
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

**Comment by danielbachhuber** [comment]
> New command to detect a command

Could you describe your use-case in greater detail? What are you trying to do?

**Comment by szepeviktor** [comment]
I am trying to detect whether a custom command is installed.

In Bash `wp --allow-root cli cmd-dump | jq -r '.subcommands[].name | select(. == "find")'`

**Comment by danielbachhuber** [comment]
> I am trying to detect whether a (custom) command is installed.

Why?

**Comment by szepeviktor** [comment]
The new tool `wp-choose.sh` checks its dependencies.
https://github.com/szepeviktor/debian-server-tools/blob/master/tools/wp-choose.sh#L21-L22

![image](https://user-images.githubusercontent.com/952007/29176338-daa13038-7deb-11e7-858e-261d1c957615.png)

**Comment by danielbachhuber** [comment]
@szepeviktor This seems like a reasonable request.

@wp-cli/committers Suggestions on naming? Something in the `wp cli *` namespace would make most sense, I think.

**Comment by szepeviktor** [comment]
> in the wp cli * namespace

I agree.

**Comment by schlessera** [comment]
Depdens on whether you want to:
1. Find a list of commands that match a specific pattern - `wp cli find-command` or `wp cli cmd-find`
2. Check whether a specific command is known - `wp cli has-command` or `wp cli cmd-exists`
3. List the known commands - `wp cli command list` or `wp cli cmd-list`

These three approaches could solve the above problem.

**Comment by miya0001** [comment]
I like `wp cli has-command`. :)

**Comment by szepeviktor** [comment]
> List the known commands

...could be `wp cli cmd-dump --format=table`

**Comment by danielbachhuber** [comment]
Cool, let's go with `wp cli has-command`.

@szepeviktor Want the honors of submitting a pull request?

**Comment by szepeviktor** [comment]
> honors

🤣

**Comment by Sidsector9** [comment]
@szepeviktor @danielbachhuber , what will has-command return if the command is found?
Boolean?

**Comment by danielbachhuber** [comment]
We should follow the current behavior of `wp core is-installed`:

* Exit `0` when core is installed.
* Exit `1` when core is not installed.

**Comment by Sidsector9** [comment]
Cool.
I have 2 implementations, just needed some clarity over this before I submit a pull request
1. Using recursive algorithm, it will detect if a command as `wp term` `wp term delete` exists or not. However, this will return false if you don't provide input in the correct sequence. For example, `wp has-command "delete"` will return false whereas `wp term delete` will return true.

2. The other implementation will detect any command/subcommand and return true. For example `wp has-command "delete"` or `wp has-command "list"` will return true.

Which of the above 2 is more suitable for this feature request?

**Comment by schlessera** [comment]
@Sidsector9 I think we need to go with 1. here. The name of a command is basically the entire series of words, like `term delete`. Just looking for `delete` does not make much sense in my eyes.

Also, the command should work like the help command, in the sense that you can just add multiple words and it will accept these as one command.

So, both of these should work:
```
wp cli has-command "term delete"
wp cli has-command term delete
```

**Comment by schlessera** [comment]
Fixed by https://github.com/wp-cli/wp-cli/pull/4349
