### ISSUE TITLE
Cannot install packages

### ISSUE THREAD

**Issue by YewTreeWeb** [wp-cli/wp-cli#4289]
Hi, when I try to install a package for WP-CLI my terminal get to 'updating dependancies' and stops. When I try `wp package list` it shows an empty table. For example:
```
wp package install iandunn/wp-cli-rename-db-prefix
Installing package iandunn/wp-cli-rename-db-prefix (dev-master)
Updating /Users/Mat/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
```
```
+------+---------+---------+--------+----------------+
| name | authors | version | update | update_version |
+------+---------+---------+--------+----------------+
+------+---------+---------+--------+----------------+
```

I am using WP-CLI with MAMP and my `--info` log is:

```
PHP binary:	/Applications/MAMP/bin/php/php7.0.20/bin/php
PHP version:	7.0.20
php.ini used:	/Applications/MAMP/bin/php/php7.0.20/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/Users/Mat/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0
```
When I go into the package folder with wp the Composer JSON file shows:

```
"homepage": "https://wp-cli.org/package-index/",
    "require": {
        "iandunn/wp-cli-rename-db-prefix": "dev-master"
    },
```
 But the packages never work or display in package list. If you can provide any help it would be really appreciated.

Thanks for taking the time to read my issue.

**Comment by miya0001** [comment]
Please try WP-CLI 1.3.0.
It looks working fine for me with the newest version.
The current version of WP-CLI is the only officially supported version.

```
$ wp --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.8-0ubuntu0.16.04.3
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/html
WP-CLI packages dir:	/home/vagrant/.wp-cli/packages/
WP-CLI global config:	/home/vagrant/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	1.3.0
$ wp package install iandunn/wp-cli-rename-db-prefix 
Installing package iandunn/wp-cli-rename-db-prefix (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.492 seconds
Analyzed 4456 packages to resolve dependencies
Analyzed 177659 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: iandunn/wp-cli-rename-db-prefix:dev-master 95ce5b2
 - Installing iandunn/wp-cli-rename-db-prefix (dev-master 95ce5b2)
Writing lock file
Generating autoload files
---
Success: Package installed.
$ wp package list 
+---------------------------------+----------+------------+--------+----------------+
| name                            | authors  | version    | update | update_version |
+---------------------------------+----------+------------+--------+----------------+
| iandunn/wp-cli-rename-db-prefix | Ian Dunn | dev-master | none   |                |
+---------------------------------+----------+------------+--------+----------------+
```

Anyway, GitHub issues aren't for general support questions, but there are other venues you can try: https://wp-cli.org/#support.

Thanks.

**Comment by YewTreeWeb** [comment]
Hi @miya0001 thank you for your reply. I'm still having the same issue with 1.3.0 but I will try support 🙂

**Comment by BenBrostoff** [comment]
I'm actually having the same issue as @miya0001 and using `WP-CLI 1.3`. @YewTreeWeb - did you find anything helpful in support?

**Comment by colorful-tones** [comment]
@YewTreeWeb @BenBrostoff 

I'm curious if you have any further insight to report back, because I'm currently running up against this same issue and I'm running WP-CLI 1.4.1 with `php.ini` memory limit 512M.

**Comment by gitlost** [comment]
@colorful-tones the problem might be that your `~/.wp-cli/packages/composer.json` is corrupted (see https://github.com/wp-cli/package-command/issues/27, fixed for upcoming release 1.5.0 https://github.com/wp-cli/package-command/pull/64).

If your symptoms are the same as https://github.com/wp-cli/package-command/issues/27 you could try editing your `~/.wp-cli/packages/composer.json` to remove references to the package that failed to install and then try to install again...

**Comment by colorful-tones** [comment]
I was able to `cd /Users/my_cool_user/.wp-cli/packages/` and `composer install`, which then allows me to get a list with `wp pacakage list`. I'm not sure what is blocking Composer.

The only oddity is if I run `php -r "echo ini_get('memory_limit').PHP_EOL;"` I get back `128M`, which makes no sense, because: 

* `which php` gives me: `/Applications/MAMP/bin/php/php7.1.8/bin/php`, and
* `wp --info` gives me: `php.ini used:	/Applications/MAMP/bin/php/php7.1.8/conf/php.ini`

And the `php.ini` for MAMP's PHP 7.1.8 is currently now at 2G. ¯\_(ツ)_/¯

**Comment by colorful-tones** [comment]
@gitlost thanks for the help. I deleted `/Users/my_cool_user/.wp-cli/packages/composer.json` and then installed a package and I seem to be back in working order.

**Comment by danfsd** [comment]
Increasing memory also did the trick here. Using `512M` now. Thanks!

**Comment by strarsis** [comment]
Workaround that could help (also if increasing the `memory_limit` doesn't fix the issue):
https://github.com/alwaysblank/blade-generate/issues/5#issuecomment-824985552
