### ISSUE TITLE
"Given a PHP built-in web server" step has dependency on "wordpress/" folder

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4292]
"Given a PHP built-in web server" requires the WordPress install to be installed to "wordpress/".

I'd expect it to use the `RUN_DIR` unless the directory is specified.

**Comment by ryotsun** [comment]
Hello, I just would like to know more details what do you want to do, to clarify this issue.

I guess installing path is depending on the composer library... is it right? :cold_sweat:
https://github.com/wp-cli/server-command/blob/master/features/bootstrap/FeatureContext.php#L649-L651

It will be generated `composer.json` and will be made `wordpress` folder after `composer install`...
Therefore, I'm a bit confused...

**Comment by ryotsun** [comment]
ooops, sorry I've overlooked the following:
https://github.com/wp-cli/server-command/blob/master/features/bootstrap/FeatureContext.php#L702-L711

So, I'll read codes again and will be working on this.
Thank you.

**Comment by ryotsun** [comment]
reading around here.
will keep investigation... 🙇 
https://github.com/wp-cli/server-command/blob/master/features/bootstrap/FeatureContext.php#L647

**Comment by danielbachhuber** [comment]
@ryotsun #4372 is what I was thinking of. I decided to create a pull request for it because I didn't think it'd be able to better explain the issue to you in a comment.

If you're looking for issues to work on, I'll be posting another "Good First Issues" blog post in the next few days: https://make.wordpress.org/cli/

**Comment by ryotsun** [comment]
@danielbachhuber Noted on this.
Thank you. 🙇
