### ISSUE TITLE
Indicate in page title when a command implements subcommands

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4297]
It should look something like this:

![image](https://user-images.githubusercontent.com/36432/29326798-c84ee77c-81a1-11e7-8def-934bde9174e3.png)

**Comment by schlessera** [comment]
As already discussed, I would make this grey, to visually distinguish it from the stuff that you "just type as is":
![29326798-c84ee77c-81a1-11e7-8def-934bde9174e3 copy](https://user-images.githubusercontent.com/83631/29397133-88340664-831c-11e7-9463-ca844aa7631f.png)

**Comment by danielbachhuber** [comment]
Landed in https://meta.trac.wordpress.org/changeset/5817/
