### ISSUE TITLE
Homepage should show latest stable release

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4298]
The current homepage has no mention of the latest stable version.

I think this should be added directly after the description of the project:
<img width="835" alt="screenshot 2017-08-15 19 07 28" src="https://user-images.githubusercontent.com/83631/29326792-31462d9e-81ed-11e7-80f6-e2fcd7001098.png">

**Comment by danielbachhuber** [comment]
What about something like this?

![image](https://user-images.githubusercontent.com/36432/29331722-4a0ced12-81b2-11e7-9a98-3e32c2df1c08.png)
