### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#4299]
Following page is not seen by anonymous user.
https://github.com/orgs/wp-cli/teams/committers/members

![](https://www.evernote.com/l/ABWQ7ESjHlZNMazXd5LGtV44mtw5HwzU4gMB/image.png)

**Comment by danielbachhuber** [comment]
Dang. How about we link to the [Committer's Credo](https://make.wordpress.org/cli/handbook/committers-credo/) instead?
