### ISSUE TITLE
Installing wp-cli in a docker container 

### ISSUE THREAD

**Issue by ilibilibom** [wp-cli/wp-cli#4304]
Hi 
I'm try to use WP-CLI within a phpfrm container. 
It seems that some commands are working fine for me, and some do not. 

For example, when I run wp --info I get 

PHP binary:	/usr/local/bin/php
PHP version:	7.1.8
php.ini used:	/usr/local/etc/php/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/html
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.3.0 

Also wp core download work fine. 

But when I try running wp config create, I get this error
/usr/bin/env: mysql: No such file or directory
Form where is this error coming from ? 
Any clue how to fix this one ? 

This is the repo i'm working on: 
https://github.com/ilibilibom/Docker-wordpress-ngnix-php-mysql-wpcli-mailcaher

If someone wishes to contribute this fix - it would be great. 
This project is TOTALLY open-source - for the benefit of WP + Docker users.

**Comment by danielbachhuber** [comment]
> But when I try running wp config create, I get this error
> /usr/bin/env: mysql: No such file or directory
> Form where is this error coming from ?
> Any clue how to fix this one ?

You'll need to install the MySQL executable. See https://github.com/wp-cli/wp-cli/issues/1324#issuecomment-241722285

For future reference, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/ideas/issues/52
