### ISSUE TITLE
Suggestion: Check for options when unzipping core package

### ISSUE THREAD

**Issue by b4dnewz** [wp-cli/wp-cli#4308]
## __Edit:__ 
Maybe I misunderstood the use of --skip-things during wp core download, I tried with this command: `wp core --skip-themes --skip-plugins download` or this: `wp core download --skip-themes --skip-plugins` which should be identical and the default themes and plugins (like askimet, ..) are still loaded, is supposed to work like this, am I missing something? I would like to skip the installation/extraction of themes and plugins.

---

__Original:__
Hi, first of all thanks for the great tool, i'm using it a lot and I love it.
I would like to suggest an improvement or a bug fix (depends on the point of view) I ran this command:

```bash
wp download
```
which downloaded for me the latest wordpress zip and put it in cache in my `~/.wp-cli/cache/core/wordpress-*` folder, that's ok and is usefull so when I run again `wp download` it will take that cached zip file and use it if matching my request.

The problem came when I ran: `wp download --skip-themes --skip-plugins` and it still used the cached version which has both themes and plugins (as default) and seems I can't find a way to avoid to using the cache, I mean a [global option](https://make.wordpress.org/cli/handbook/config/#global-parameters) like `--no-cache` or something.

So I manually removed the cache and ran the command again to ~obtain what I needed, wordpress installation without themes and/or plugins~ have the same thing.

So my suggestion is, during the unzip process where wordpress is extracted, check for command line options and optionally exclude themes or plugins, or introduce an option to avoid using cached files.

Many thanks in advance.

**Comment by gitlost** [comment]
Hi @b4dnewz 

> Maybe I misunderstood the use of --skip-things during wp core download,

Yes, the `--skip-things` options only affect WP-CLI itself, telling it not to load plugins/themes/packages when it loads. It does not affect commands as such.

>  I would like to skip the installation/extraction of themes and plugins.

`wp core download` just extracts whatever is in the official WordPress release. I don't think it would be good for it to do anything else. So use `wp plugin delete` and `wp theme delete` to customize your install.

> I can't find a way to avoid to using the cache, I mean a global option like --no-cache or something

I think a `--no-cache` (or similar) option to `wp core download` might be a good idea. Could you open an issue at `wp-cli/core-command` https://github.com/wp-cli/core-command/issues/new to suggest this enhancement?

In general, see also http://wp-cli.org/#support if you haven't already. Thanks!

**Comment by b4dnewz** [comment]
@gitlost thanks for your help, anyway I would like to have another clarification after looking at [wp plugin](https://developer.wordpress.org/cli/commands/plugin/delete/#examples) command I noticed there isn't a  "easy" way to remove all plugins, I assume is the same for themes, it could be possible archived by doing this:

`wp plugin delete $(wp plugin list --field=name)` 

I think it could be useful to have an aliased option to this like `--all` for both __theme__ and __plugin__ commands.

What do you think?

**Comment by gitlost** [comment]
@b4dnewz A key principle of WP-CLI is [composability](https://make.wordpress.org/cli/handbook/philosophy/#composability-is-always-a-good-idea) but I can see that such an easy `--all` option would be convenient so certainly go ahead and suggest such an option at `wp-cli/extension-command` https://github.com/wp-cli/extension-command/issues/new (warning: all suggestions may be rejected!).
