### ISSUE TITLE
WP-CLI not using the correct MySQL user

### ISSUE THREAD

**Issue by jlambe** [wp-cli/wp-cli#4318]
**Summary:**

I've installed the `wp-cli.phar` into a project. I can't install the file into a `bin` directory of our production server so I have to run commands like so `php wp-cli.phar`.

We do the same locally, each project as its own WP-CLI. Running commands locally works perfectly.

We run into issues when using it on production. Somehow, WP-CLI can't find the correct MySQL user (the one defined into the `wp-config.php`) when running commands. This triggers errors on the Terminal like `Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'server-db'@'localhost'` where `server-db` is nowhere to be found.

**Steps to reproduce:**
1. Install wp-cli.phar into your project
2. Push it live
3. Try to run commands on a virtual private server using `php wp-cli.phar`

**Environment:**

#### What is your system?
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 8.8 (jessie)
Release: 8.8
Codename: jessie

#### Which version of PHP are you using?
/usr/bin/php
php 7.0.1

#### Which version of WordPress are you using?
4.8.1

#### Can you share the results of which wp ?
1.3.0

#### Are you running any packages? If one is causing a problem, you can use `--skip-packages` to skip
No.

**Results and impacts:**

#### Severity
High

#### Expected results
Being able to run any commands

#### Actuel results
MySQL error message `Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'server-db'@'localhost'`

I've also posted the error to our provider. They perhaps might give us a hint but would like to know if anyone has ever had this issue.

Or is it possible to define a database user to use when running commands?

**Comment by miya0001** [comment]
Hi @jlambe 

Please try `wp --info` and `which php` and please check the path of those PHPs.

Anyway, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by jlambe** [comment]
@miya0001 Paths are correct and like explained, we don't have full control over the server. So if we had to change anything on the filesystem, it's not possible.

The WordPress site is working correctly. When using the `wp-cli`, it reads the `wp-config.php` but looks like it ignores the defined SQL user from the project.

2 things that I would like you to perhaps consider:
1. Is there any other check that wp-cli could do when detecting the SQL user?
2. What about to provide global parameters when running commands where we can define the `dbuser` and other related informations ?

Thanks

**Comment by miya0001** [comment]
wp-cli is requiring the `wp-config.php`, so db account should be loaded from it.
Please ask us on the slack, if you have questions more.
http://wp-cli.org/#support
