### ISSUE TITLE
Parent Themes with spaces in directory are not escaped

### ISSUE THREAD

**Issue by eliseferguson** [wp-cli/wp-cli#4319]
When attempting to scaffold a child theme from a parent theme that contains spaces, the resulting child theme function is not escaped properly and renders the child theme inaccessible via the browser.

Using the following command-
$ wp scaffold child-theme notio-child-theme --parent_theme='notio-wp 2'

Example-
Parent theme directory: 'notio-wp 2'
Enqueue styles function name in child theme: 'notio_wp 2_parent_theme_enqueue_styles()'

![screenshot 2017-08-21 14 01 27](https://user-images.githubusercontent.com/1854885/29534294-116dbbee-867b-11e7-9768-2025749ec168.png)

**Comment by danielbachhuber** [comment]
Thanks for the report @eliseferguson.

Want to submit a pull request with the fix? I think we'd need to add spaces to [this str_replace() call](https://github.com/wp-cli/scaffold-command/blob/master/src/Scaffold_Command.php#L375).

[Here's an overview to submitting a pull request](https://make.wordpress.org/cli/handbook/pull-requests/).

**Comment by danielbachhuber** [comment]
Fixed in https://github.com/wp-cli/scaffold-command/pull/40
