### ISSUE TITLE
Add .github/SUPPORT.md to the repo

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4324]
If we add a `.github/SUPPORT.md` file, it will show up in the header like this:

![image](https://user-images.githubusercontent.com/36432/29745699-0ffd4608-8a77-11e7-9a17-eccd01e508c8.png)

Spotted via Ghost's repo, which has some [very concise human-readable language](https://github.com/TryGhost/Ghost/blob/master/.github/SUPPORT.md). I am too verbose :(

**Comment by schlessera** [comment]
Ha, I have the same problem with verbosity. Maybe we should hire _Ghost_writers... ;)
