### ISSUE TITLE
There are some problems on `--prompt`

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#4325]
I found some problems on `--prompt`.

## 1. PHP notice with the `--<field>=<value>`

If the command has a option like `--<field>=<value>`, prompt displays PHP notices like following.

```
$ wp plugin list --prompt
1/4 [--<field>: 
string(0) ""
PHP Notice:  Undefined variable: required in /Users/miyauchi/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php on line 204
Notice: Undefined variable: required in /Users/miyauchi/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php on line 204
```

## 2. Input should not be displayed for password field, but it is displayed.

```
$ ./bin/wp user update --prompt
1/15 <user>...: admin
2/15 [--user_pass=<password>]: 1234
```

## 3. `cli\prompt()` is  not used.

https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Dispatcher/Subcommand.php#L107-L123

There is a comment `Wrapper for CLI Tools' prompt() method.`, but it is not used.
Are there any reason?

`cli\prompt()` is supporting hidden option and it looks woking fine, so I guess it should be used.
https://github.com/wp-cli/php-cli-tools/blob/e02568e72a460713c2e696c7edaca988735ffdef/lib/cli/Streams.php#L147-L173

**Comment by danielbachhuber** [comment]
> If the command has a option like `--<field>=<value>`, prompt displays PHP notices like following.

We should fix this.

> Input should not be displayed for password field, but it is displayed.

Why is this a problem?

> There is a comment Wrapper for CLI Tools' prompt() method., but it is not used.
> Are there any reason?

See https://github.com/wp-cli/wp-cli/commit/7f695c548b1b90c33a47e3a76f293cbdde3e52f2

**Comment by miya0001** [comment]
@danielbachhuber 

> Why is this a problem?

Ah, I read following. It is OK.

* https://github.com/wp-cli/wp-cli/issues/996
* https://github.com/wp-cli/wp-cli/issues/129
