### ISSUE TITLE
Not working on debian 8.9 Jessie with clean install

### ISSUE THREAD

**Issue by fmonera** [wp-cli/wp-cli#4330]
(Probably a similar error was previously raised [here](https://github.com/wp-cli/doctor-command/issues/113) but the answer is not valid for normal users)

With a clean install of WP-CLI on a debian server, I get the following error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method cli\Table::setAsciiPreColorized() in phar:///usr/bin/wp/php/WP_CLI/Formatter.php:285
... (full error traceback pasted later)
```

Steps to reproduce:

(as root)
```
# curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
# chmod 755 wp-cli.phar
# mv wp-cli.phar /usr/bin/wp
```

(as nginx user)
```
# cd path/to/wordpress
 # wp plugin list
```

About the machine:

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.9 (jessie)
Release:        8.9
Codename:       jessie

# php -v
PHP 7.0.23-dev (cli) (built: Aug  8 2017 14:47:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

The complete error dump:

PHP Fatal error:  Uncaught Error: Call to undefined method cli\Table::setAsciiPreColorized() in phar:///usr/bin/wp/php/WP_CLI/Formatter.php:285
Stack trace:
#0 phar:///usr/bin/wp/php/WP_CLI/Formatter.php(138): WP_CLI\Formatter::show_table(Array, Array, false)
#1 phar:///usr/bin/wp/php/WP_CLI/Formatter.php(89): WP_CLI\Formatter->format(Array, false)
#2 phar:///usr/bin/wp/vendor/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php(441): WP_CLI\Formatter->display_items(Array)
#3 phar:///usr/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(951): WP_CLI\CommandWithUpgrade->_list(Array, Array)
#4 [internal function]: Plugin_Command->list_(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Runner.php(323): WP_ in phar:///usr/bin/wp/php/WP_CLI/Formatter.php on line 285
Fatal error: Uncaught Error: Call to undefined method cli\Table::setAsciiPreColorized() in phar:///usr/bin/wp/php/WP_CLI/Formatter.php:285
Stack trace:
#0 phar:///usr/bin/wp/php/WP_CLI/Formatter.php(138): WP_CLI\Formatter::show_table(Array, Array, false)
#1 phar:///usr/bin/wp/php/WP_CLI/Formatter.php(89): WP_CLI\Formatter->format(Array, false)
#2 phar:///usr/bin/wp/vendor/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php(441): WP_CLI\Formatter->display_items(Array)
#3 phar:///usr/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php(951): WP_CLI\CommandWithUpgrade->_list(Array, Array)
#4 [internal function]: Plugin_Command->list_(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#7 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(401): call_user_func(Object(Closure), Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Runner.php(323): WP_ in phar:///usr/bin/wp/php/WP_CLI/Formatter.php on line 285

Can you tell me what I am doing wrong?

Thanks a lot

**Comment by schlessera** [comment]
@fmonera I suspect you may have outdated dependencies in the installation of your external commands.

Could you please try to run the following commands:
```
cd ~/.wp-cli/packages/
composer update
```

That should hopefully update your internal version of `wp-cli/php-cli-tools`.

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/4332

**Comment by fmonera** [comment]
@schlessera There is no such folder for people that installs WP-CLI the official way (downloading the PHAR file).

```
$ cd ~/.wp-cli/packages
-su: cd: /home/nginx/.wp-cli/packages: No such file or directory
```

What would be the "wp-cli/packages" folder to run "composer update" for people who downloads the PHAR?

(sorry if I am not understanding something)

**Comment by schlessera** [comment]
@fmonera If you type `wp cli info`, it will show which folders it is using. There's a `WP-CLI packages dir` in there as well.

**Comment by fmonera** [comment]
@schlessera The packages dir is empty. I suppose it is always empty if you download the PHAR instead of building from source but I don't really know.

```
$ wp cli info
PHP binary:     /opt/php/bin/php
PHP version:    7.0.23-dev
php.ini used:   /etc/php/7.0/fpm/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/nginx
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.3.0
```

**Comment by danielbachhuber** [comment]
@fmonera Can you join us in the `#cli` room on WordPress.org Slack for further assistance debugging? This seems like it's problem specific to your environment, and chat makes it easier to provide suggestions.
