### ISSUE TITLE
Help word wrapping should deal better with long non-spaced runs (links in particular).

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4336]
Related https://github.com/wp-cli/wp-cli/issues/4302

The word wrapping in help should deal better with long runs of non-spaced characters. This is especially true in the case of links such as
```
[Roles and Capabilities](https://codex.wordpress.org/Roles_and_Capabilities)
```
as in https://github.com/wp-cli/role-command/pull/7 which display poorly with a low `COLUMNS` setting (see https://github.com/wp-cli/wp-cli/issues/4302#issuecomment-327819046).

**Comment by miya0001** [comment]
Thanks @gitlost :)

I am thinking following options.

* Hide long description on command line help.
* Hide only url in long description on command line help.

It should be displayed on the handbook, either way.

**Comment by gitlost** [comment]
I'd be more inclined to hide the square brackets and their content and the opening/closing round brackets around the url, so eg
```
[Roles and Capabilities](https://codex.wordpress.org/Roles_and_Capabilities)
```
becomes just
```
https://codex.wordpress.org/Roles_and_Capabilities
```
as the url is useful and the link description isn't so much (especially given well named links such as in the codex).

Another option is not to hide the link description or the url but (programmatically) insert a space between the `](` (and maybe lose the opening/closing round brackets around the url).

**Comment by miya0001** [comment]
I tried:

![](https://www.evernote.com/l/ABUzExTDsLFHEpKd6Wh4D625towTmG80tlsB/image.png)

It looks better than before.
Actually if we remove the url as I said, it is not useful. 😄

**Comment by miya0001** [comment]
I came up with another idea.
It changes long description to be list of the reference URLs.

![](https://www.evernote.com/l/ABUufdG-_IpM-prrZ_viO-KEwluFW6SEY0sB/image.png)

**Comment by gitlost** [comment]
Both of them are excellent! The first might be more robust and apply to more cases?

**Comment by miya0001** [comment]
> The first might be more robust and apply to more cases?

I thinks so too.
But I just wrote the second example as follows, so it looks easy to solve the problem. :)

```
/**
 * Manages user roles, including creating new roles and resetting to defaults.
 *
 * References:
 * * https://codex.wordpress.org/Roles_and_Capabilities
 * * https://codex.wordpress.org/Class_Reference/WP_User.
```

**Comment by gitlost** [comment]
Just to be clear, for the second are you suggesting a documentation change or doing it programmatically?

**Comment by miya0001** [comment]
I am not sure for now. I want to see whole list of the long description.

**Comment by schlessera** [comment]
How about adding the links as footnotes? Something like this maybe (or any other type of syntax that we can just automate):

```
See references for [Roles and Capabilities:1] and [WP User class:2].

---
[1] https://codex.wordpress.org/Roles_and_Capabilities
[2] https://codex.wordpress.org/Class_Reference/WP_User
```

It would keep both the proper, descriptive sentence and provide real links in an easy to copy way.

**Comment by miya0001** [comment]
Oh, I like it. 👍

**Comment by danielbachhuber** [comment]
> How about adding the links as footnotes? Something like this maybe (or any other type of syntax that we can just automate):

💯  I actually came to this idea independently.

**Comment by schlessera** [comment]
@danielbachhuber Any feedback on the actual format to use? I provided one possible example, but not entirely sure about the `[<anchor>:<number>]` format...

**Comment by danielbachhuber** [comment]
I don't have a strong preference.

**Comment by gitlost** [comment]
stackoverflow uses `[title][1]` (where `1` can be anything) for what it's worth https://stackoverflow.com/help/formatting.

**Comment by miya0001** [comment]
Following are examples:

Example 1:
![](https://www.evernote.com/l/ABWf3Liqvc9IOoTlNzvbN0peIvAsR2s-rYsB/image.png)

Example 2:
![](https://www.evernote.com/l/ABX1pMyuc8ZK4Y4o9GCHPQkRPiKqFiecqugB/image.png)


I like Example 2. 😊

**Comment by danielbachhuber** [comment]
@miya0001 Found a case where this breaks:

![image](https://user-images.githubusercontent.com/36432/31946793-a6d6550e-b887-11e7-8efe-cc6b108b8682.png)

The source is: https://github.com/danielbachhuber/php-compat-command/blob/8455f84729b71ac4700d166d6dca57829254dde5/src/PHP_Compat_Command.php#L8-L11

Also, it'd be nice to have one more line break between the description and the footnote.

**Comment by danielbachhuber** [comment]
It's even more problematic when there are multiple lines of description:

![image](https://user-images.githubusercontent.com/36432/31947150-7e365346-b888-11e7-8c4e-8068903354d8.png)

**Comment by danielbachhuber** [comment]
Lastly, I think reference links should only be parsed out on _display_ in the terminal, not when piping (e.g. generating docs).

**Comment by miya0001** [comment]
> Lastly, I think reference links should only be parsed out on display in the terminal, not when piping (e.g. generating docs).

Yes, you are right. 
Do you have an idea how should it detect terminal or piping?
Will we add global parameters?

**Comment by danielbachhuber** [comment]
I think `WP_CLI\Utils\isPiped()` should do the trick.

**Comment by miya0001** [comment]
Great! Thanks 😊

**Comment by danielbachhuber** [comment]
Also, I'm not sure `DocParser` is the best place for this anymore. `Help_Command` may be more appropriate, because it's only used in display help context.

**Comment by danielbachhuber** [comment]
🔨 looks pretty good now
