### ISSUE TITLE
Batch results grammar for "spam"

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4338]
The `WP_CLI\Utils\report_batch_operation_results` function returns bad grammar for the `$verb` `'spam'`: `spamed` instead of `spammed`.

See this PR for an example. https://github.com/wp-cli/entity-command/pull/74/files#diff-20d228cbdcf363412c22760ffc0dcc4dR363

**Comment by miya0001** [comment]
@schlessera 

There is the function `pluralize()` in [wp-cli/scaffold-command](https://github.com/wp-cli/scaffold-command).
It looks similar problem as follows.
https://github.com/wp-cli/scaffold-command/issues/48

Should `pluralize()` be moved into `wp-cli/wp-cli` and solve #48?

**Comment by gitlost** [comment]
> Should pluralize() be moved into wp-cli/wp-cli

I think that would be overkill here given the limited vocab involved - I've written a function to do the past tense anyway (probably overkill as well), PR to follow.

**Comment by danielbachhuber** [comment]
🚢
