### ISSUE TITLE
Dashboard crash with replace form 'blog' on Japanese version.

### ISSUE THREAD

**Issue by kmikage** [wp-cli/wp-cli#4342]
[Issue]
Run 'wp search-replace blog foo', crash dashboard(MOJIABKE), but toppage is available.
if re-replace 'wp search-replace blog foo', replace dashboard.
---
[Operating Environment]
Version : WP-CLI 1.3.0
OS : KUSANAGI Version 8.0.8-1(CentOS 7 Base for WordPress Distribution Linux - https://kusanagi.tokyo/ )
WordPress Version : 4.7.3-ja
not customize (Installed default).
---
[Screenshots and Console logs]
![replace-befour](https://user-images.githubusercontent.com/2312119/30233378-3f357814-9530-11e7-960d-c988615de4cf.png)
```
$ wp search-replace blog foo
+------------------+-----------------------+--------------+------+
| Table            | Column                | Replacements | Type |
+------------------+-----------------------+--------------+------+
| wp_options       | option_name           | 4            | SQL  |
| wp_options       | option_value          | 2            | PHP  |
+------------------+-----------------------+--------------+------+
Success: Made 6 replacements.
(snip zero replacements lines.)
```
![replace-after](https://user-images.githubusercontent.com/2312119/30233377-3f3378d4-9530-11e7-96d3-1673afbcd85e.png)
---
may be...
a word 'blog' in wp-options, for use japanese dashboard lang.
but replace 'blog' to 'foo' , not working.

**Comment by gitlost** [comment]
There's `blog_charset` (and also `blog_public`, `blogdescription` and `blogname`) in `wp_options.option_name` so that is probably causing the issue. You could try
```bash
wp search-replace blog foo --skip-columns=option_name
```
to get around this, or use a regex to replace only the word `blog`
```bash
wp search-replace '\bblog\b' foo --regex
```

**Comment by schlessera** [comment]
As @gitlost has said, this is the expected behavior of WP-CLI. Unless told otherwise, it will replace _all_ occurrences in the database of `blog` with `foo`.

In case you were trying to replace the site name, you should always work with actual domains (like `blog.dev`), and hopefully unambiguous ones.
