### ISSUE TITLE
Create separate cache directory for behat for each version of WordPress

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#4343]
I haven't looked into details for now yet. 
But I guess following function is not working as expected.
https://github.com/wp-cli/wp-cli/blob/master/features/bootstrap/FeatureContext.php#L147-L159

If there is `/tmp/wp-cli-test-core-download-cache/`, behat is using `4.8.1`, even though `WP_VERSION=trunk` is defined.

```
$ export WP_VERSION=trunk
$ vendor/bin/behat 

PHP binary:	/usr/bin/php
PHP version:	7.0.22-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	/vagrant/extension-command/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	/vagrant/extension-command/vendor
WP_CLI phar path:	
WP-CLI packages dir:	
WP-CLI global config:	/tmp/wp-cli-package-test/config.yml
WP-CLI project config:	/vagrant/extension-command/wp-cli.yml
WP-CLI version:	1.3.0

WordPress 4.8.1
```

But I remove `/tmp/wp-cli-test-core-download-cache/`, behat downloads `trunk` as expected.

```
$ rm -fr /tmp/wp-cli-test-core-download-cache/
$ vendor/bin/behat 

PHP binary:	/usr/bin/php
PHP version:	7.0.22-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	/vagrant/extension-command/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	/vagrant/extension-command/vendor
WP_CLI phar path:	
WP-CLI packages dir:	
WP-CLI global config:	/tmp/wp-cli-package-test/config.yml
WP-CLI project config:	/vagrant/extension-command/wp-cli.yml
WP-CLI version:	1.3.0

WordPress 4.9-alpha-41352
```

I found this problem when I was trying to solve https://github.com/wp-cli/extension-command/pull/41.
So, we have to fix this problem for all repositories if we need to solve this. 😓

**Comment by miya0001** [comment]
Ah, we will have contributor day at WordCamp Tokyo at 9/16. :)

**Comment by gitlost** [comment]
> But I guess following function is not working as expected.

Note that the `FeatureContext` in `extension-command` is old https://github.com/wp-cli/extension-command/blob/master/features/bootstrap/FeatureContext.php#L126-L137 and doesn't have the `WP_VERSION`-specific download cache added in https://github.com/wp-cli/wp-cli/pull/4287.

**Comment by miya0001** [comment]
Oh, I see!
OK, I will ask new contributors to update this file in Tokyo. :)

**Comment by miya0001** [comment]
Note:
https://github.com/wp-cli/scaffold-package-command/blob/master/features/bootstrap/FeatureContext.php#L77-L88

**Comment by schlessera** [comment]
Updating the test suites should always be done through the automated scaffolding:
```
wp scaffold package-tests . --force
```
( See https://github.com/wp-cli/scaffold-package-command/#wp-scaffold-package-tests )

Just make sure you run this with the latest WP-CLI version.

**Comment by danielbachhuber** [comment]
> Updating the test suites should always be done through the automated scaffolding:

Related https://github.com/wp-cli/wp-cli/issues/4344

We should run `wp scaffold package-tests . --force` for all packages to make sure they're up to date.

**Comment by schlessera** [comment]
I would do a run over all packages this week.

**Comment by miya0001** [comment]
@schlessera 

> I would do a run over all packages this week.

I want to do them with Japanese people at contributor day in this weekend in Tokyo. :)

**Comment by schlessera** [comment]
@miya0001 Ah, okay, that is a good idea.

Will you cover both the tests and the README files?

**Comment by miya0001** [comment]
> Will you cover both the tests and the README files?

Yes . :)

**Comment by miya0001** [comment]
Ah, but we have some commands that isn't updated description.
https://github.com/wp-cli/wp-cli/issues/4302#issuecomment-326804539

We will need to update readme again for some commands.
I'll create a check sheet on #4344 which is a list of the updated.

**Comment by miya0001** [comment]
Thankfully, we will have 10 or more attendees at CLI team at contributor day.
I want to keep their tasks. :)

**Comment by miya0001** [comment]
* [ ] admin
* [ ] cache
* [ ] cap
* [ ] checksum
* [ ] cli
* [ ] comment
* [ ] config
* [ ] core
* [ ] cron
* [ ] db
* [ ] eval
* [ ] eval-file
* [ ] export
* [ ] help
* [ ] import
* [ ] language
* [ ] media
* [ ] menu
* [ ] network
* [ ] option
* [ ] package
* [ ] plugin
* [ ] post
* [ ] post-type
* [ ] rewrite
* [ ] role
* [ ] scaffold
* [ ] search-replace
* [ ] server
* [ ] shell
* [ ] sidebar
* [ ] site
* [ ] super-admin
* [ ] taxonomy
* [ ] term
* [ ] theme
* [ ] transient
* [ ] user 
* [ ] widget

**Comment by miya0001** [comment]
㊗️
