### ISSUE TITLE
Refresh README.md

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#4344]
We have to refresh REDAME.md of each repositories, after #4302 closed.

e.g,  https://github.com/wp-cli/extension-command/pull/39#issuecomment-328048608

**Comment by schlessera** [comment]
This is done with:
```
wp scaffold package-readme . --force
```

( See https://github.com/wp-cli/scaffold-package-command/#wp-scaffold-package-readme )

**Comment by danielbachhuber** [comment]
🔨
