### ISSUE TITLE
Error: Could not insert post into the database

### ISSUE THREAD

**Issue by mightytravels** [wp-cli/wp-cli#4345]
I have been running the same version of PHP and WP CLI for some time. 

I can still insert sample posts:

wp post create --post_type=post --post_title='A sample post' --path=myinstall

Created post 75389.

But I usually pull the post from file as text like this one:

http://filetemp.s3.amazonaws.com/post_deals.txt

This worked just fine for many months but now I get Error: Could not insert post into the database

My WP post limit is 64M and I can copy and paste the text just fine through the Web Interface.

Ideas?

**Comment by danielbachhuber** [comment]
Hi @mightytravels,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
