### ISSUE TITLE
A class `@when` overrides individual method `@when`s.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4350]
Related https://github.com/wp-cli/wp-cli/pull/4349

If a command class has an `@when`, then any individual method `@when`'s are ignored. In particular if the class has `@when before_wp_load`, then a method with `@when after_wp_load` will be called before WP loads.

**Comment by danielbachhuber** [comment]
I think we can consider this a bug. The expected behavior should be:

> If a class has a `@when before_wp_load` but a method has a `@when after_wp_load`, then the method's definition should take priority (e.g. hierarchical inheritance).
