### ISSUE TITLE
PHP NOTICE on undefined constant GLOB_BRACE in docker alpine php 7.1.9

### ISSUE THREAD

**Issue by gd-jroberts** [wp-cli/wp-cli#4353]
When running Alpine 3.6 with PHP 7.1.9 and the WP-CLI 1.3.0 I receive the following PHP NOTICE:

PHP Notice:  Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' in phar:///bin/wp/php/utils.php on line 915

It is only a notice, but is also extra unexpected output on the cli. Google-fu returned this which might be related: https://github.com/zendframework/zend-stdlib/issues/58

**Comment by gitlost** [comment]
Thanks for the report @gd-jroberts. Apart from the notice, if braces were used (not sure if they are) then it would fail.

I see from the link you've given that the Zend framework has a polyfill https://github.com/zendframework/zend-stdlib/blob/master/src/Glob.php, so it'd probably make sense to copy this class into WP-CLI and use it in `Utils\expand_globs()` if `GLOB_BRACE` isn't defined.

(For reference, `GLOB_BRACE` is also used in `import-command`, https://github.com/wp-cli/import-command/blob/master/src/Import_Command.php#L58.)

**Comment by schlessera** [comment]
As we cannot know what other commands might use `Utils\exapnd_globs()`, the safe approach is probably to provide a polyfill indeed (and not try to get rid of brace usage).

As `Utils\expand_globs()` works in a namespace, we could also provide an external compatibility package that provides `Utils\glob` as a polyfill, instead of copying a class into the framework package. This way, you can only install this if needed. However, I wonder whether that wouldn't create more hassle than it is worth.

**Comment by gitlost** [comment]
I did a test implementation of this using the simple copy/require method:
```php
function expand_globs( $paths, $flags = null ) {
	// Compatibility with systems without GLOB_BRACE.
	$glob_user_func = null;
	if ( ! defined( 'GLOB_BRACE' ) || getenv( 'WP_CLI_TEST_EXPAND_GLOBS_NO_GLOB_BRACE' ) ) {
		if ( ! class_exists( 'WP_CLI\Utils\Zend_Glob', false ) ) {
			require __DIR__ . '/foreign/class-zend-glob.php';
		}
		$glob_user_func = array( 'WP_CLI\Utils\Zend_Glob', 'glob' );
		if ( null === $flags ) {
			$flags = Zend_Glob::GLOB_BRACE;
		}
	} elseif ( null === $flags ) {
		$flags = GLOB_BRACE;
	}

	$expanded = array();

	foreach ( (array) $paths as $path ) {
		$matching = array( $path );

		if ( preg_match( '/[' . preg_quote( '*?[]{}!', '/' ) . ']/', $path ) ) {
			$matching = ( $glob_user_func ? call_user_func( $glob_user_func, $path, $flags, true ) : glob( $path, $flags ) ) ?: array();
		}

		$expanded = array_merge( $expanded, $matching );
	}

	return array_unique( $expanded );
}
```
with very light edits to Zend's `Glob.php` (here copied as `foreign/class-zend-glob.php`) to make it WP-CLI and PHP 5.3 compat.
 
> we could also provide an external compatibility package

That would be nicer.

> This way, you can only install this if needed.

Wondering how to make that work.

**Comment by schlessera** [comment]
> Wondering how to make that work.

Something like: `wp package install wp-cli/glob-polyfill`.

**Comment by gitlost** [comment]
And then plug it in with something like:
```php
function expand_globs( $paths, $flags = null ) {
	if ( ! defined( 'GLOB_BRACE' ) ) {
		WP_CLI::warning( "No GLOB_BRACE. Do wp package install wp-cli/glob-polyfill." );
	} elseif ( null === $flags ) {
		$flags = GLOB_BRACE;
	}
```
I suppose? May or may not be worth it as you say.

**Comment by schlessera** [comment]
No, I thought to define a `WP_CLI\Utils\glob()` function instead. As `glob()` is being used relatively, if a `WP_CLI\Utils\glob()` exists, it will be preferred over the global `\glob()`.

**Comment by gitlost** [comment]
Yes I understood that, just wondering about the user experience. Actually in the above code, would probably still need to use `Zend_Glob::GLOB_BRACE`, as defining `GLOB_BRACE` in the polyfill could be messy and confusing and have other issues.

**Comment by schlessera** [comment]
Ah, yes, sorry.

Maybe something like this:

```php
function expand_globs( $paths, $flags = null ) {

   static $brace_warning_issued = false;

   if ( ! defined( 'GLOB_BRACE' )
        && ! class_exists( 'Zend_Glob' )
        && ! $brace_warning_issued ) {
      WP_CLI::warning( "No GLOB_BRACE support, this operation might return the wrong results. We recommend installing a compatibility package using the following command: 'wp package install wp-cli/glob-polyfill'" );
      $brace_warning_issued = true;
   } elseif ( null === $flags ) {
      $flags = GLOB_BRACE;
   }
```

**Comment by danielbachhuber** [comment]
In what cases is `GLOB_BRACE` not available?

Could we instead point the user to update their system configuration to include `GLOB_BRACE`?

**Comment by gitlost** [comment]
It's when a Linux (such as [Alpine](https://alpinelinux.org/)) has been built with a libc (such as [musl](https://www.musl-libc.org/)) that doesn't implement it, so there's no system configuring that can get around it.

I went ahead with this anyway by just copying and adapting the relevant code (around 70 lines) from the Zend Framework into a new utils function - it avoids the confusing `GLOB_X` flags issue of the Zend stuff, which expects you to use its class `Glob::GLOB_X` flags. PR to follow.
