### ISSUE TITLE
Help command should work when database credentials are incorrect

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4367]
Given a `wp-config.php` file which contains incorrect database credentials, it's not possible to see any of WP-CLI's help docs, either with `wp help` or `wp [command] --help`.

It would be good if requests for help didn't require a valid database connection.

The `wp help` or `wp [command] --help` commands do work when there is no WordPress installation present, or one hasn't yet been installed.

**Comment by danielbachhuber** [comment]
> Given a `wp-config.php` file which contains incorrect database credentials, it's not possible to see any of WP-CLI's help docs, either with `wp help` or `wp [command] --help`.

Can you share which command you were trying to see help for?

> It would be good if requests for help didn't require a valid database connection.

How would WP-CLI access a command provided by an active plugin without a valid database connection?

**Comment by johnbillion** [comment]
> Can you share which command you were trying to see help for?

Specifically, I was looking for help for `wp config` so I could un-break my installation :-)

> How would WP-CLI access a command provided by an active plugin without a valid database connection?

Good point. I wonder if it could check the database connection and fall back to displaying help only for built-in commands if the database connection isn't valid.

**Comment by danielbachhuber** [comment]
> I wonder if it could check the database connection and fall back to displaying help only for built-in commands if the database connection isn't valid.

This is the current behavior. When I run `wp help config` with invalid database credentials, I see the help docs.
