### ISSUE TITLE
need disable auto update/upgrade feature 

### ISSUE THREAD

**Issue by mekbuk** [wp-cli/wp-cli#4373]
hello,

can you provide the feature for disable auto update/upgrade wordress with **ee** command
because some plugin/theme is corrupted if auto update/upgrade is active

**Comment by danielbachhuber** [comment]
Hi @mekbuk,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
