### ISSUE TITLE
Behat is failing on WordPress 3.7.11

### ISSUE THREAD

**Issue by miya0001** [wp-cli/wp-cli#4376]
See: 

* https://travis-ci.org/wp-cli/export-command/builds/277404081?utm_source=github_status&utm_medium=notification
* https://travis-ci.org/wp-cli/extension-command/builds/277782245?utm_source=github_status&utm_medium=notification

**Comment by miya0001** [comment]
I tried `wp plugin list` with WordPress 3.7 + PHP 5.3.

```
$ wp plugin list
+---------+----------+--------+---------+
| name    | status   | update | version |
+---------+----------+--------+---------+
| akismet | inactive | none   | 2.5.6   |
| hello   | inactive | none   | 1.6     |
| no-mail | must-use | none   |         |
+---------+----------+--------+---------+
```

The version number of akismet is `2.5.6`, but version `4.0` is available.
I tried `wp cron event run --all ` and run `wp plugin list` again.
But it couldn't find update as expected.

```
ubuntu@82f7db666203:/tmp/wp-cli-test-run-plugin-update.feature.3-59c4a89329e7b5.66075305$ 
/shared/vendor/bin/wp cron event run --all 
Executed the cron event 'wp_version_check' in 2.928s.
Executed the cron event 'wp_update_plugins' in 0.626s.
Executed the cron event 'wp_update_themes' in 0.506s.
Success: Executed a total of 3 cron events.
ubuntu@82f7db666203:/tmp/wp-cli-test-run-plugin-update.feature.3-59c4a89329e7b5.66075305$ 
/shared/vendor/bin/wp plugin list
+---------+----------+--------+---------+
| name    | status   | update | version |
+---------+----------+--------+---------+
| akismet | inactive | none   | 2.5.6   |
| hello   | inactive | none   | 1.6     |
| no-mail | must-use | none   |         |
+---------+----------+--------+---------+
```

**Comment by miya0001** [comment]
Related:
* https://github.com/wp-cli/export-command/pull/12
* https://github.com/wp-cli/extension-command/pull/45

**Comment by miya0001** [comment]
I tried to run following tests with older version of WordPress.
https://github.com/wp-cli/extension-command/blob/master/features/plugin-update.feature

Then WordPress 3.7 - 3.9 have a same problem. 😓

**Comment by gitlost** [comment]
Note the export-command issue isn't related, it's just buggy code.

**Comment by miya0001** [comment]
@gitlost Oh, I didn't see log. :)

**Comment by danielbachhuber** [comment]
> Note the export-command issue isn't related, it's just buggy code.

@gitlost Could you clarify or open a new issue?

**Comment by danielbachhuber** [comment]
@miya0001 Is this fixed?

**Comment by miya0001** [comment]
@danielbachhuber 
The problem for extension-command had been solved.
But the problem for the export-command is not, I guess @gitlost is working for it at https://github.com/wp-cli/export-command/pull/12#issuecomment-333160356.

**Comment by danielbachhuber** [comment]
🔨
