### ISSUE TITLE
be able to run wp from any path

### ISSUE THREAD

**Issue by Dan33l** [wp-cli/wp-cli#4377]
wp cli needs to be executed with current working directory on root of wp.

For instance, listing plugins needs two steps : 

1. set your current working directory to the root of your wp : `cd /pathroot/of/your/wordpress/`
2. list plugins `wp  plugin list`

It should be interesting to be possible to run, from everywhere, a one step command : `wp  --wproot=/pathroot/of/your/wordpress/ plugin list`

I used the sub command plugin, but it should be interesting for all sub commands.

**Comment by miya0001** [comment]
Hi @Dan33l 

You can use `--path` parameter, also you can set default path by `~/.wp-cli/config.yml`.
There are other options in documentation.
https://make.wordpress.org/cli/handbook/config/

Thanks :)

**Comment by Dan33l** [comment]
Thank you for the link. It is written :

> WP-CLI has a series of global parameters (e.g. --path=<path> and --user=<user>) which work with all commands. They are called global parameters because they affect how WP-CLI interacts with WordPress, and have the same behavior across all commands.

This sentence should be added also at the top of page https://developer.wordpress.org/cli/commands/
