### ISSUE TITLE
Call one wordpress WP_CLI::run_command to get plugin list antoher site path

### ISSUE THREAD

**Issue by VikashSaharan1** [wp-cli/wp-cli#4378]
@Daniel Bachhuber 
please any body tell  me how to achieve this 
 WP_CLI::run_command(array("plugin", "list"), array('--path' => '/Applications/XAMPP/htdocs/bwtemplates/' )
my current wordpress in '/Applications/XAMPP/htdocs/wpms/ '

**Comment by danielbachhuber** [comment]
Hi @VikashSaharan1,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
