### ISSUE TITLE
Handle all cases for Utils\wp_version_compare()

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4380]
WordPress uses a few more versions than we currently accommodate in `Utils\wp_version_compare()`:

> While this works, it will have the unintended side effect of not prompting for updates when they are available. For example, if I have deployed `4.9-alpha-40870-src` but then a nightly build of `4.9-beta1-45000` is available, then I should still get prompted to update. But it should not update using the nightly build because then that will blow away the `-src`. So in that case, a different notification should be displayed.

We should:

* [x] Identify all of these potential version strings.
* [x] Update `Utils\wp_version_compare()` to handle the potential version strings.
* [x] Write unit tests around each case.

From https://github.com/pantheon-systems/WordPress/pull/136#issuecomment-331984995

**Comment by westonruter** [comment]
I think the comparison logic should be something like this:

```php
/**
 * Compare two WordPress version numbers which look like '4.9-alpha-40870-src'.
 *
 * @param string $ver_a Version A.
 * @param string $ver_b Version B.
 * @return int Comparison.
 */
$compare = function( $ver_a, $ver_b ) {
	$ver_a_parts = explode( '-', $ver_a );
	$ver_b_parts = explode( '-', $ver_b );

	// Compare semantic versions.
	$semver_a = array_shift( $ver_a_parts );
	$semver_b = array_shift( $ver_b_parts );
	$comparison = version_compare( $semver_a, $semver_b );
	if ( 0 !== $comparison ) {
		return $comparison;
	}

	// Compare pre-release identifiers 'alpha', 'beta', 'rc'.
	$prerelease_a = array_shift( $ver_a_parts );
	$prerelease_b = array_shift( $ver_b_parts );
	$comparison = strcmp( $prerelease_a, $prerelease_b );
	if ( 0 !== $comparison ) {
		return $comparison;
	}

	// If either version is a src (but not both) then consider them equal.
	$src_a = 'src' === array_shift( $ver_a_parts );
	$src_b = 'src' === array_shift( $ver_b_parts );
	if ( $src_a xor $src_b ) {
		return 0;
	}

	// Compare revision numers.
	$rev_a = intval( array_shift( $ver_a_parts ) );
	$rev_b = intval( array_shift( $ver_b_parts ) );
	return $rev_b - $rev_a;
};
```
