### ISSUE TITLE
is_cli() conditional

### ISSUE THREAD

**Issue by lkraav** [wp-cli/wp-cli#4381]
https://danielbachhuber.com/tip/detect-wp-cli/ talks about `defined( 'WP_CLI' ) && WP_CLI` being the best available check.

Looks and feels noisy. Is it possible to get `is_cli()` or something going for us, too?

**Comment by danielbachhuber** [comment]
> Is it possible to get `is_cli()` or something going for us, too?

Probably not. Checking the constant is a well-defined standard. You're welcome to write your own helper function though.

**Comment by schlessera** [comment]
Also, that would just break if WP-CLI would not be available, because it would have been declared in WP-CLI.

**Comment by lkraav** [comment]
> Also, that would just break if WP-CLI would not be available, because it would have been declared in WP-CLI.

@schlessera yes exactly, which is why I'm thinking maybe something core level.
