### ISSUE TITLE
Add descriptions for top-level `wp language` and `wp network` commands

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4385]
Descriptions are conspicuously absent:

![image](https://user-images.githubusercontent.com/36432/31016817-18b1a6f8-a4db-11e7-8fbb-8692c8518925.png)

This is a conceptual problem with our underlying framework. When `wp network meta` is registered, WP-CLI transparently creates the `wp network` namespace:

![image](https://user-images.githubusercontent.com/36432/31016851-4af357e2-a4db-11e7-8734-6ab14f54e63b.png)

However, there's no PHPDoc to parse, so no description is included.

Open to suggestions on how to fix.

**Comment by danielbachhuber** [comment]
@schlessera I'm seeing this error locally:

```
[RuntimeException]
  Exception has been thrown in "beforeSuite" hook, defined in FeatureContext::prepare()

  $ wp cli info

  Warning: Could not add command /Users/danielbachhuber/wp-cli/php/commands/cli.php. Reason: Class \WP_CLI\Dispatcher\CommandNamespace does not exist
  Warning: Could not add command /Users/danielbachhuber/wp-cli/php/commands/help.php. Reason: Class \WP_CLI\Dispatcher\CommandNamespace does not exist
  Error: 'cli' is not a registered wp command. See 'wp help' for available commands.
  Did you mean 'cap'?
```

**Comment by danielbachhuber** [comment]
Oh. `composer dump-autoload` seems to have done the trick.

**Comment by schlessera** [comment]
If the autoloader was dumped as "optimized" (`-o`), it is actually a classmap, and won't notice additions until you regenerate it.

**Comment by danielbachhuber** [comment]
🔨
