### ISSUE TITLE
 danielbachhuber 

### ISSUE THREAD

**Issue by VikashSaharan1** [wp-cli/wp-cli#4430]
@danielbachhuber  i have create a many command that is executed success after that remove and create a new server after that show for all custom commands Error: 'xyz' is not a registered wp command. please Reply ASAP

**Comment by danielbachhuber** [comment]
Hi @VikashSaharan1,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
