### ISSUE TITLE
Console output buffered

### ISSUE THREAD

**Issue by MoreKoo** [wp-cli/wp-cli#4437]
Create test.php, with content:

`<?php

WP_CLI::line( "1ST" );
sleep(3);
WP_CLI::line( "2ND" );`

From command line: >wp eval-file test.php

It takes three seconds, then both lines are echoed on the screen and script exists.

A bug? Is this a known issue, I didn't find anything (or used wrong keywords in searches).

**Comment by danielbachhuber** [comment]
Hi @MoreKoo,

I can't reproduce the issue. WP-CLI doesn't perform any sort of output buffering, so I suspect it's specific to your environment (possibly a caching plugin or similar). [Here's some detail](https://danielbachhuber.com/tip/identify-plugin-theme-conflict-wp-cli/) on how to identify a plugin or theme conflicting with WP-CLI.

**Comment by MoreKoo** [comment]
Thanks for the link, Daniel. Actually skipping plugins fixed the issue, so there's a conflict somewhere....
