### ISSUE TITLE
Warning: Could not create directory

### ISSUE THREAD

**Issue by harry-wood** [wp-cli/wp-cli#4446]
It would be useful if the message "Warning: Could not create directory" also stated which directory it is trying to create.  Likewise when updating core I saw "Error: Could not create directory."

(For those who may be wondering, by default it seems to be trying to create something under `wp-content/upgrade/`. Changing ownership on this directory temporarily is enough to run updates)

**Comment by danielbachhuber** [comment]
Hi @harry-wood,

Thanks for the report. This particular error message is straight from WordPress core. I'd suggest [filing a core Trac ticket](https://core.trac.wordpress.org/) instead.

**Comment by treehousetim** [comment]
I too need the directory name so I can check permissions.  this error is worthless.
