### ISSUE TITLE
Support system wide / user wide settings file

### ISSUE THREAD

**Issue by kalabro** [wp-cli/wp-cli#445]
Thanks for great tool!

It will be cool if I could set settings like `--admin_email`, `--locale` and etc somewhere in `~/wp-cli.yml`, so the order will be:
1. Command-line flags
2. wp-cli.local.yml file in site folder
3. wp-cli.yml file  in site folder
4. **wp-cli.yml in $HOME folder**
5. Defaults

**Comment by Luke-SF** [comment]
> wp --config=$HOME/wp-cli-defaults.yml core install

On WP-CLI 2.7.1 this --config parameter seems to always give 
Error: Parameter errors:
 unknown --config parameter

**Comment by danielbachhuber** [comment]
@Luke-SF WP-CLI changed a bit in the past decade. Here are the docs on how global parameters work: https://make.wordpress.org/cli/handbook/references/config/
