### ISSUE TITLE
wp media regenerate shouldn't regenerate clones

### ISSUE THREAD

**Issue by DuckDagobert** [wp-cli/wp-cli#4457]
Hi,

a couple plugins like WPML will clone attachments so they are available in all languages but not duplicate the files (which makes sense, don't want to clutter my SSD space)

when I regenerate the thumbnails (e.g. seq 1000 2000 | xargs wp media regenerate) it will iterate over the clones and regenerate it in each language even though it is the same file every time, thus wasting server ressources & taking much longer than necessary.

It will then look something like this:
54/97 Regenerated thumbnails for "my-picture" (ID 915).
55/97 Regenerated thumbnails for "my-picture" (ID 905).
56/97 Regenerated thumbnails for "my-picture" (ID 906).
57/97 Regenerated thumbnails for "my-picture" (ID 907).
58/97 Regenerated thumbnails for "my-picture" (ID 908).
59/97 Regenerated thumbnails for "my-picture" (ID 909).
60/97 Regenerated thumbnails for "my-picture" (ID 910).
61/97 Regenerated thumbnails for "my-picture" (ID 911).
62/97 Regenerated thumbnails for "my-picture" (ID 916).
63/97 Regenerated thumbnails for "my-picture" (ID 917).
64/97 Regenerated thumbnails for "my-picture" (ID 782).
65/97 Regenerated thumbnails for "my-picture" (ID 914).
66/97 Regenerated thumbnails for "my-picture" (ID 912).
67/97 Regenerated thumbnails for "my-picture" (ID 920).
68/97 Regenerated thumbnails for "my-picture" (ID 919).
69/97 Regenerated thumbnails for "my-picture" (ID 918).
70/97 Regenerated thumbnails for "my-picture" (ID 913).

I suggest to add something like this, to improve this:
if ( current_file_name == previous_file_name ) { skip this pic; }

**Comment by danielbachhuber** [comment]
Hi @DuckDagobert,

Thanks for the report. We don't generally add plugin-specific workarounds to WP-CLI. I'd recommend reaching out to the plugin author to see if they can help you accommodate this issue.
