### ISSUE TITLE
is_ssl() returning false can lead to misleading results

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4459]
On the command line, `is_ssl()` returns false because the corresponding `$_SERVER['https']` variable isn't.

While technically this is correct, it can lead to misleading behavior within WP-CLI. For instance:

```
$ wp option get siteurl
https://example.com
$ wp site list --field=url
http://example.com
```

I don't have an opinion for an immediate solution on this; more so, flagging behavior for visibility.

From https://wordpress.slack.com/archives/C02RP4T41/p1508444879000316

**Comment by schlessera** [comment]
We could try to provide some semi-smart guesses and adapt the URL accordingly. For example, if `FORCE_SSL` is set to true, the expected URL should generally be HTTPS.

**Comment by DODEK1986** [comment]
csvdfnmb

**Comment by danielbachhuber** [comment]
A more graceful approach would be to disable `set_url_scheme()` in CLI context. Or, solely for the `http -> https` and `https -> http` conversions.

**Comment by schlessera** [comment]
Yes, that might work as well and be less of a hack. There's a filter that provides both the original and the changed URL.
