### ISSUE TITLE
synopsis to pass comma-separated argument

### ISSUE THREAD

**Issue by drzraf** [wp-cli/wp-cli#4463]
For more than 1 hour I'm digging documentation, github issues/commits/sourcecode in order to create the synopsis for a command allowing it to take a comma-separated list of string as a value.

Documentation needs to state explicitly whether its possible **or not** (and if yes, how)
Ideally, this page https://make.wordpress.org/cli/handbook/commands-cookbook/ should contains the pattern `comma-sep*`

**Comment by danielbachhuber** [comment]
> For more than 1 hour I'm digging documentation, github issues/commits/sourcecode in order to create the synopsis for a command allowing it to take a comma-separated list of string as a value.

You'll need to quote the argument:

```
wp my-command 'option1,option2,option3'
```

**Comment by drzraf** [comment]
It's not about quotes, it's about `wp-cli` synopsis syntax.
In a shell, "," (comma) is not a special character.
`wp XXX YYY,ZZZ` is the same as `wp "XXX" "YYY,ZZZ"`

**Comment by drzraf** [comment]
Once again today :

* `command has an invalid synopsis part: <url,...>`
* `command has an invalid synopsis part: <url...>`
* `command has an invalid synopsis part: [url,...]`
* `command has an invalid synopsis part: <url>[,...]`
* `command has an invalid synopsis part: <url>,...`
* `command has an invalid synopsis part: [url],...`
* `command has an invalid synopsis part: [url]`  
  `command has an invalid synopsis part: ...`    (for `[url] ...`)

@danielbachhuber
