### ISSUE TITLE
Trouble doing a base build with Circle CI and empty scaffolded plugin.

### ISSUE THREAD

**Issue by devanonyme** [wp-cli/wp-cli#4472]
Hello,

I used a vvv vagrant installation and it's seems like it's using a developpement version of WP-CLI:
vagrant@vvv:~$  wp --info
...
WP-CLI version: 1.5.0-alpha-32f2247

What would be the best version or starting point to have a working sample generated with WP-CLI?

Actually, as I type this I got my first working build!

There was a error in php file, which was fine to validate phpcs execution but I had to change the machine definition, there where errors regarding the version of php used and the version required by phpunit.

I didn't want to jump throught all the hoops so as suggested in a similar thread, I used a tag instead of the php:  5.xx generated by the scaffold.

machine:
  image: circleci/php:7.1.4-apache-browsers (not sure if it's a adaquate machine).

It's was just to get a base working state, we plan to support from php 5.6 for our project so I guess I will have to look further into this.

ps: Thanks for the great tools!

**Comment by danielbachhuber** [comment]
Hi @devanonyme,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by devanonyme** [comment]
Sorry, it was not appropriately filed but I think it is a bug because the constructed plugin generated a file that was not working as expected (failed build in CircleCI). This is reproductible. But I do realise now that it should have been reported here : https://github.com/wp-cli/scaffold-package-command.
