### ISSUE TITLE
Add `phpcs` as a Git pre-commit hook

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4474]
To avoid unnecessary build failures, it would be helpful to have `phpcs` as a required pre-commit hook for the repository. It's fast-enough (5s) that it shouldn't be a hinderance to development.

**Comment by danielbachhuber** [comment]
Looks like we'd need symlink a short executable script to `.git/hooks/pre-commit` on `composer install` or similar, because `.git/hooks` isn't tracked in VCS

**Comment by schlessera** [comment]
@danielbachhuber:
The way this is now done will overwrite an existing git hook in the developer's local codebase.

For a safer approach, maybe consider using https://github.com/php-composter/php-composter

**Comment by gitlost** [comment]
Removed this from the 1.5.0 milestone per office hours slack https://wordpress.slack.com/archives/C02RP4T41/p1516726954000467

**Comment by danielbachhuber** [comment]
This was shipped with #4622 and #4696
