### ISSUE TITLE
Question: list inactive plugins across network

### ISSUE THREAD

**Issue by raptor235** [wp-cli/wp-cli#4484]
Can't seem to find this anywhere but is there a way to list plugins that are inactive across the entire network?

**Comment by danielbachhuber** [comment]
Sorry for the late reply here, @raptor235 

You could probably adapt https://github.com/runcommand/find-unused-themes for this purpose.

Also, more generally, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
