### ISSUE TITLE
Error: Could not update option 'home'.

### ISSUE THREAD

**Issue by apb1963** [wp-cli/wp-cli#4491]
Please note http vs httpS.  

$ wp option update home http**s**://myhost.mydomain.com --path=/usr/local/src/template --url=http**s**://myhost.mydomain.com
Error: Could not update option 'home'.

$ wp option update home http://myhost.mydomain.com --path=/usr/local/src/template --url=http://myhost.mydomain.com
Success: Updated 'home' option.

$ wp option update home http**s**://myhost.mydomain.com --path=/usr/local/src/template --url=http**s**://myhost.mydomain.com
Success: Updated 'home' option.

$ wp --info --path=/usr/local/src/myhost --url=https://myhost.mydomain.com
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.22-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/data/local/src/myscripts
WP-CLI packages dir:	/home/apb/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.4.0

**Comment by danielbachhuber** [comment]
Hi @apb1963,

Have you been able to reproduce the issue with a fresh WordPress install and no plugins active?

**Comment by apb1963** [comment]
Yes.  I wrote a bash script to do exactly that, and so I reinstall over and over for testing purposes.  I do an apt-get purge prior to reinstalling each time, and I don't add any plugins except woocommerce & storefront.

However, based on your question I did it differently this time (i.e. w/out my script) on the command line and so get a different error than originally stated.  Although I see what's wrong, I don't know how or the best way to fix it.

It wants /etc/wordpress/config-.php which of course doesn't exist, instead of /etc/wordpress/config-localhost.php - as that file actually exists.  Presumably it needs HTTP_HOST to have a value which is why it's looking for the wrong file I guess.  I don't know why it doesn't have a value.... other than the fact I'm not calling it through a browser; which is kind of the point of wp-cli, yes?  So it's possible there are actually two potentially related bugs - the original one I first reported and now this second one.


sudo apt install wordpress
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  wordpress-l10n
Suggested packages:
  php-ssh2
The following NEW packages will be installed:
  wordpress wordpress-l10n
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/7,871 kB of archives.
After this operation, 48.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package wordpress.
(Reading database ... 241392 files and directories currently installed.)
Preparing to unpack .../wordpress_4.4.2+dfsg-1ubuntu1_all.deb ...
Unpacking wordpress (4.4.2+dfsg-1ubuntu1) ...
Selecting previously unselected package wordpress-l10n.
Preparing to unpack .../wordpress-l10n_4.4.2+dfsg-1ubuntu1_all.deb ...
Unpacking wordpress-l10n (4.4.2+dfsg-1ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up wordpress (4.4.2+dfsg-1ubuntu1) ...
Added to /var/lib/wordpress/wp-content/themes: index.php twentyfifteen twentyseventeen twentysixteen 
Added to /var/lib/wordpress/wp-content/plugins: akismet hello.php index.php 
Added to /var/lib/wordpress/wp-content/languages: admin-ar.mo admin-bs_BA.mo admin-ca.mo admin-cy.mo admin-da_DK.mo admin-de_DE.mo admin-el.mo admin-es_ES.mo admin-es_PE.mo admin-et.mo admin-eu.mo admin-fa_IR.mo admin-fi.mo admin-fr_FR.mo admin-gl_ES.mo admin-he_IL.mo admin-hr.mo admin-it_IT.mo admin-ja.mo admin-ko_KR.mo admin-my_MM.mo admin-network-ar.mo admin-network-bs_BA.mo admin-network-ca.mo admin-network-cy.mo admin-network-da_DK.mo admin-network-de_DE.mo admin-network-el.mo admin-network-es_ES.mo admin-network-es_PE.mo admin-network-et.mo admin-network-fa_IR.mo admin-network-fi.mo admin-network-fr_FR.mo admin-network-gl_ES.mo admin-network-he_IL.mo admin-network-hr.mo admin-network-it_IT.mo admin-network-ja.mo admin-network-ko_KR.mo admin-network-my_MM.mo admin-network-ru_RU.mo admin-network-sk_SK.mo admin-network-sl_SI.mo admin-network-sq.mo admin-network-sr_RS.mo admin-network-sv_SE.mo admin-network-ug_CN.mo admin-network-zh_CN.mo admin-network-zh_TW.mo admin-ru_RU.mo admin-sk_SK.mo admin-sl_SI.mo admin-sq.mo admin-sr_RS.mo admin-sv_SE.mo admin-ug_CN.mo admin-zh_CN.mo admin-zh_TW.mo ar.mo bg_BG.mo bn_BD.mo bs_BA.mo ca.mo ckb.mo continents-cities-bg_BG.mo continents-cities-bs_BA.mo continents-cities-cs_CZ.mo continents-cities-cy.mo continents-cities-da_DK.mo continents-cities-de_DE.mo continents-cities-el.mo continents-cities-en_CA.mo continents-cities-es_PE.mo continents-cities-et.mo continents-cities-eu.mo continents-cities-fa_IR.mo continents-cities-fi.mo continents-cities-fr_FR.mo continents-cities-gd.mo continents-cities-he_IL.mo continents-cities-hr.mo continents-cities-hu_HU.mo continents-cities-it_IT.mo continents-cities-ja.mo continents-cities-ka_GE.mo continents-cities-ko_KR.mo continents-cities-lv.mo continents-cities-mk_MK.mo continents-cities-my_MM.mo continents-cities-nb_NO.mo continents-cities-nn_NO.mo continents-cities-pl_PL.mo continents-cities-pt_BR.mo continents-cities-pt_PT.mo continents-cities-ro_RO.mo continents-cities-ru_RU.mo continents-cities-sk_SK.mo continents-cities-sl_SI.mo continents-cities-sq.mo continents-cities-sr_RS.mo continents-cities-su_ID.mo continents-cities-sv_SE.mo continents-cities-ta_LK.mo continents-cities-tr_TR.mo continents-cities-ug_CN.mo continents-cities-vi.mo continents-cities-zh_CN.mo continents-cities-zh_TW.mo cs_CZ.mo cy.mo da_DK.mo de_DE.mo el.mo en_CA.mo eo.mo es_CL.mo es_ES.mo es_PE.mo et.mo eu.mo fa_IR.mo fi.mo fr_FR.mo gd.mo gl_ES.mo he_IL.mo hr.mo hu_HU.mo id_ID.mo it_IT.mo ja.mo jv_ID.mo ka_GE.mo ko_KR.mo lv.mo mk_MK.mo ms_MY.mo my_MM.mo nb_NO.mo nl.mo nl_NL.mo pl_PL.mo pt_BR.mo pt_PT.mo ro_RO.mo ru_RU.mo ru_UA.mo si_LK.mo sk_SK.mo sl_SI.mo sq.mo sr_RS.mo su_ID.mo sv_SE.mo sw.mo ta_LK.mo th.mo tr_TR.mo ug_CN.mo uk.mo ur.mo vi.mo zh_CN.mo zh_HK.mo zh_TW.mo 
Setting up wordpress-l10n (4.4.2+dfsg-1ubuntu1) ...

apb@yellow:~$ sudo wp option update home http://localhost --path=/usr/share/wordpress --allow-root
PHP Notice:  Undefined index: HTTP_HOST in phar:///data/local/bin/wp/php/WP_CLI/Runner.php(1070) : eval()'d code on line 10
Neither <b>/etc/wordpress/config-.php</b> nor <b>/etc/wordpress/config-.php</b> could be found. <br/> Ensure one of them exists, is readable by the webserver and contains the right password/username.

apb@yellow:/usr/share/wordpress$  sudo cat wp-config.php
wp-config.php pasted below (because oddly, .php uploads are not supported by github and changing the extension to .txt doesn't fool it.)

```

<?php
/***
 * WordPress's Debianised default master config file
 * Please do NOT edit and learn how the configuration works in
 * /usr/share/doc/wordpress/README.Debian
 ***/

/* Look up a host-specific config file in
 * /etc/wordpress/config-<host>.php or /etc/wordpress/config-<domain>.php
 */
$debian_server = preg_replace('/:.*/', "", $_SERVER['HTTP_HOST']);
$debian_server = preg_replace("/[^a-zA-Z0-9.\-]/", "", $debian_server);
$debian_file = '/etc/wordpress/config-'.strtolower($debian_server).'.php';
/* Main site in case of multisite with subdomains */
$debian_main_server = preg_replace("/^[^.]*\./", "", $debian_server);
$debian_main_file = '/etc/wordpress/config-'.strtolower($debian_main_server).'.php';

if (file_exists($debian_file)) {
    require_once($debian_file);
    define('DEBIAN_FILE', $debian_file);
} elseif (file_exists($debian_main_file)) {
    require_once($debian_main_file);
    define('DEBIAN_FILE', $debian_main_file);
} elseif (file_exists("/etc/wordpress/config-default.php")) {
    require_once("/etc/wordpress/config-default.php");
    define('DEBIAN_FILE', "/etc/wordpress/config-default.php");
} else {
    header("HTTP/1.0 404 Not Found");
    echo "Neither <b>$debian_file</b> nor <b>$debian_main_file</b> could be found. <br/> Ensure one 
of them exists, is readable by the webserver and contains the right password/username.";
    exit(1);
}

/* Default value for some constants if they have not yet been set
   by the host-specific config files */
if (!defined('ABSPATH'))
    define('ABSPATH', '/usr/share/wordpress/');
if (!defined('WP_CORE_UPDATE'))
    define('WP_CORE_UPDATE', false);
if (!defined('WP_ALLOW_MULTISITE'))
    define('WP_ALLOW_MULTISITE', true);
if (!defined('DB_NAME'))
    define('DB_NAME', 'wordpress');
if (!defined('DB_USER'))
    define('DB_USER', 'wordpress');
if (!defined('DB_HOST'))
    define('DB_HOST', 'localhost');
if (!defined('WP_CONTENT_DIR') && !defined('DONT_SET_WP_CONTENT_DIR'))
    define('WP_CONTENT_DIR', '/var/lib/wordpress/wp-content');

/* Default value for the table_prefix variable so that it doesn't need to
   be put in every host-specific config file */
if (!isset($table_prefix)) {
    $table_prefix = 'wp_';
}

if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
    $_SERVER['HTTPS'] = 'on';

require_once(ABSPATH . 'wp-settings.php');
?>

```

**Comment by danielbachhuber** [comment]
Please see: https://make.wordpress.org/cli/handbook/common-issues/#php-notice-undefined-index-on-_server-superglobal

Also, for support options, please review http://wp-cli.org/#support

**Comment by apb1963** [comment]
Your comment here: https://github.com/wp-cli/wp-cli/issues/4073 is likely applicable.  I just filed a bug with launchpad, and in the meantime I'll give your suggestion a try and add it to the config file and see what happens.

**Comment by danielbachhuber** [comment]
Yes, empty `HTTP_HOST` is a common issue.
