### ISSUE TITLE
Travis CI keeps failing

### ISSUE THREAD

**Issue by dingo-d** [wp-cli/wp-cli#4494]
I don't know if this is a bug or what but I added the `.travis.yml` file that was created when I scaffolded the plugin for unit testing (`wp scaffold plugin-tests json-wp-post-parser`
) and created a PR, but every time I push to the repo the Travis CI fails.

```sh
PHP Warning:  require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream: No such file or directory in /home/travis/build/infinum/json-wp-post-parser/tests/bootstrap.php on line 14
```

The failing test is here: https://travis-ci.org/infinum/json-wp-post-parser/jobs/298067249

When I run the unit tests locally they pass.
Any idea what should be changed?

**Comment by danielbachhuber** [comment]
Hi @dingo-d,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

**Comment by dingo-d** [comment]
Woops, sorry, will ask in the correct place :)
