### ISSUE TITLE
Create new 'build' stage to build a Phar, use it during the test stages, and ultimately deploy

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4500]
From https://github.com/wp-cli/wp-cli/pull/4499#issuecomment-342929130

> What we actually need to do is have a build stage to produce a build artifact, use it through each test stage, and then upload it in the deploy stage.

Related #3931

**Comment by danielbachhuber** [comment]
Travis [doesn't offer persistence between jobs](https://docs.travis-ci.com/user/build-stages/#Data-persistence-between-stages-and-jobs), so we'd need to use some system of our own. Options include:

1. S3 bucket.
2. `scp` to a random web server.
3. Put the Phar file into a Docker container and push to Docker cloud.
4. ???

One gotcha though: secrets. In order to make this system available to non-org pull requests, we'd need to expose the auth secret to the pull request — which means it could theoretically be abused for other purposes.

Maybe we could abuse Travis' caching system by writing a Phar file to it with the commit hash in the filename.

**Comment by schlessera** [comment]
I think you should be able to configure the credentials so that they are secure.

Here's a comment from the S3 example's `travis.yml` file:
```
# It assums S3 credentials to be set up in the repository settings
# or to be configured as encrypted env vars here.
```

**Comment by danielbachhuber** [comment]
> I think you should be able to configure the credentials so that they are secure.

How? If they're decrypted at any point in the build process, they could be exposed by the person submitting the PR.

**Comment by schlessera** [comment]
A possible solution seems to be https://docs.travis-ci.com/user/jwt .

However, I don't think it's supported by S3...

**Comment by danielbachhuber** [comment]
The current system is imperfect but the perfect system is a significant level of effort. Let's stick with the current system until there's reason otherwise.
