### ISSUE TITLE
Should we run another survey?

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4502]
I've run a couple of surveys in the past ([2014](https://make.wordpress.org/cli/2014/04/29/survey-results/), [2015](https://make.wordpress.org/cli/2015/12/01/survey-results-2015/)). Think we should do another?

If yes... here are the questions from the last survey:

* How often do you use WP-CLI? (Multiple times per day, Couple or few times per week, etc.)
* Which version of WP-CLI do you use?
* What do you use WP-CLI for? (open ended)
* How do you use WP-CLI? (Interactively (at the command line), In bash scripts, etc.)
* "If WP-CLI could do one new thing, I'd want it to..." (open ended)

I don't love this question set. What questions do you think we should ask? Or, phrased another way: what questions do you have that could be answered through some aggregate data?

cc @wp-cli/committers

**Comment by javorszky** [comment]
What is it that you want to achieve with the survey?

**Comment by danielbachhuber** [comment]
> What is it that you want to achieve with the survey?

Good question. A point in time understanding of how people are using WP-CLI, I suppose.

For 2018, it seems like our priority needs to be _discovery_, or helping users level-up their usage of WP-CLI. My suspicion is that the majority of users only know some smaller subset of what WP-CLI is capable of. If we can increase their awareness of what's possible, we can increase usage more broadly.

**Comment by trepmal** [comment]
> majority of users only know some smaller subset of what WP-CLI is capable of

Absolutely. For as much as I love and use WP-CLI, I know there's stuff that I don't even realize is there, let alone newer and more casual users. But I don't know that these are the users that are going to take a survey though (just a feeling, I have no evidence to back this up). 

> If we can increase their awareness of what's possible

I'd love to see this. On my own, I've made some attempts to get more people interested (occasional blog post, WordCamp talk... been meaning to do more/better). Are there specific ways you saw this happening?

**Comment by danielbachhuber** [comment]
> But I don't know that these are the users that are going to take a survey though (just a feeling, I have no evidence to back this up).

I think there are some promotion channels we can use to get better distribution.

> On my own, I've made some attempts to get more people interested (occasional blog post, WordCamp talk... been meaning to do more/better). Are there specific ways you saw this happening?

I appreciate the effort :) I have some ideas, but nothing specific yet.

**Comment by schlessera** [comment]
I think WP-CLI usage goes hand in hand with how comfortable users are with the shell in general. For a lot of people trying to start with WP-CLI, the shell is the hurdle, not WP-CLI itself.

So, maybe add a question to the survey about how comfortable/capable they feel with the shell.

Also, at one point, I'd like to work on a more linear part of the handbook that takes users through the initial hurdles of the shell and slowly builds on that knowledge. I have already started on this indirectly through talks ([see these slides as an example](https://schlessera.github.io/wcber-2017/)), and I think that would be a major opportunity to increase usage.

**Comment by danielbachhuber** [comment]
@schlessera Do you think we should run a survey, or no? I'm on the fence at this point.

**Comment by schlessera** [comment]
@danielbachhuber Personally, I think that the data we'll get with the above questions will not do much except generate some work for all involved. It does not really serve a purpose and won't have any meaningful impact.

I'd prefer surveys to be used as a tool to serve a specific goal. So, for example, if we have a big decision to make, a survey could help find out what the community's best interest is. Surveys should be goal-driven and result in an actionable data set.

Just knowing who uses WP-CLI how much will not answer any meaningful question, as long as we're not in the business of selling demographics data.

**Comment by danielbachhuber** [comment]
> I'd prefer surveys to be used as a tool to serve a specific goal. So, for example, if we have a big decision to make, a survey could help find out what the community's best interest is. Surveys should be goal-driven and result in an actionable data set.

👌 Sounds good.

**Comment by davidfavor** [comment]
You might consider adding the question...

How many total sites do you administer with wp-cli?

In my case I'd have to could all sites for all clients, many 100s.

This data might give you a clue about people using wp-cli all day, every day.

Having a list of these people might provide you a way to reach out + gather more specific data from them, as I'm guessing data from these people might lead to more pervasive deployment into mass hosting companies.

Just a guess.
