### ISSUE TITLE
Consider enabling PHP errors by default in Behat tests

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4504]
From https://github.com/wp-cli/extension-command/pull/62#pullrequestreview-75899079:

> Have a PR to expose PHP notices/warnings when running behat which I'll post one day rather than having to do ad-hoc debug file requires and tags etc...

One caveat when doing so: we may expose a good number of issues we're not currently aware of. Before we commit to this, it'd be good to run a complete test suite with this enabled to see what sort of existing problems we have.

**Comment by gitlost** [comment]
Yes maybe do it immediately after 1.4.1 is released...

**Comment by gitlost** [comment]
Hmm looking at the patch I had it would break backward compatibility not just for bundled commands (which is dealable with, if tedious) but for any external code that uses the behat test suite - is that acceptable?

**Comment by danielbachhuber** [comment]
> it would break backward compatibility

In what way? Can you submit the PR so we can look at it?

**Comment by gitlost** [comment]
> In what way?

As it stands it changes `WP_CLI\Process` to throw an error if `stderr` (as opposed to `STDERR`) is non-empty, so some `And I run` steps need changing to `And I try` steps and the expectation that the return code will be non-zero (or not) needs to be explicitly specified...will do PR anyway...
