### ISSUE TITLE
Version incorrect in 1.4.1 tag

### ISSUE THREAD

**Issue by 0x6d617474** [wp-cli/wp-cli#4514]
The release tagged `1.4.1` has `1.5.0-alpha` in the `VERSION` file, and `wp --version` displays `1.5.0-alpha` instead of the expected `1.4.1`

**Comment by danielbachhuber** [comment]
Oh boy, I really messed this one up. I'll re-tag in a moment.

**Comment by danielbachhuber** [comment]
Ok, v1.4.1 points to the correct hash now.
