### ISSUE TITLE
Fix failing wp-cli/automated-tests build

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4519]
wp-cli/automated-tests build is currently failing https://travis-ci.org/wp-cli/automated-tests/builds/303641930

This is because our test suite now exposes PHP errors as test failures #4515

We'll need to update all package tests, tag releases, and then (hopefully) the full test suite will pass again.

Simply creating an issue for visibility.

**Comment by danielbachhuber** [comment]
@gitlost I think this is our last failure:

![image](https://user-images.githubusercontent.com/36432/33099653-6dcc72f2-cec6-11e7-9635-6b3956696414.png)

From https://travis-ci.org/wp-cli/automated-tests/jobs/305390045

Any ideas on how to address?

**Comment by danielbachhuber** [comment]
Something got really slow too :(

![image](https://user-images.githubusercontent.com/36432/33099742-c0f7ed08-cec6-11e7-8d96-869ef3b80757.png)

**Comment by gitlost** [comment]
Yeah it's missing the `@github-api` tag, and `GITHUB_TOKEN` isn't defined for automated tests by the look.

**Comment by gitlost** [comment]
> **Something got really slow too :(

I think a lot depends on Travis load but yeah, various of the suites made some major work to speed them up - a obvious target is the repetitive downloading which could be cached in a lot of cases...

**Comment by danielbachhuber** [comment]
> `GITHUB_TOKEN` isn't defined for automated tests by the look.

I've added one.

> a obvious target is the repetitive downloading which could be cached in a lot of cases...

Where? WordPress core, plugin, and theme downloads are cached, unless the cached is purged.

**Comment by danielbachhuber** [comment]
All fixed and much faster:

![image](https://user-images.githubusercontent.com/36432/33133330-422e82bc-cf51-11e7-96d5-b196b2097b70.png)

https://travis-ci.org/wp-cli/automated-tests/builds/305390044

**Comment by gitlost** [comment]
Cool (surprised to be honest!).

> Where? WordPress core, plugin, and theme downloads are cached, unless the cached is purged.

I'll respond to this soon, after some fact-checking!
