### ISSUE TITLE
wp db size --tables or --all-tables don´t show all tables in the DB

### ISSUE THREAD

**Issue by ibertrix** [wp-cli/wp-cli#4529]
It doesn´t show the plugin tables

**Comment by prajapatisagar** [comment]
Hi @ibertrix 

`wp db size --tables` only displays WordPress core tables. For list all the tables you will need to run `wp db size --tables --all-tables` command.

Thanks

**Comment by ibertrix** [comment]
Thanks! Ok, I was using only wp db size --all-tables.

The help is confusing:

 wp db size [--size_format] [--tables] [--format] [--scope=<scope>] [--network] [--all-tables-with-prefix] [--all-tables]

it seems that --all-tables is an alternative to --tables option. Doesn´t make sense to change --tables option to --core-tables? Doesn´t make sense to use either --tables or --all-tables? Just a question of economy. What´s the difference between --all-tables-with-prefix and --all-tables? I don´t see any difference in the output...

**Comment by prajapatisagar** [comment]
Hi @ibertrix 

Difference:
`--all-tables-with-prefix`: List all tables that match the table prefix even if not registered on $wpdb.

`--all-tables`: List all tables in the database, regardless of the prefix, and even if not registered on $wpdb. Overrides --all-tables-with-prefix.

Please check [https://developer.wordpress.org/cli/commands/db/size/](url) for more detail.

Thanks
