### ISSUE TITLE
Broken Link in Docs to Package Index

### ISSUE THREAD

**Issue by richardbuff** [wp-cli/wp-cli#4532]
Occurs on [this page](https://make.wordpress.org/cli/handbook/tools/)

[Screenshot with broken link highlighted](https://cl.ly/2l420N1E0X2y )

Believe its supposed to be [linking to this](http://wp-cli.org/package-index/)

**Comment by gitlost** [comment]
Thanks @richardbuff ! Will do PR on https://github.com/wp-cli/handbook

**Comment by richardbuff** [comment]
Ah, I will know next time to do that myself, sorry I had overlooked that the docs were available in their own repo
