### ISSUE TITLE
Force terminal language to be in specific language

### ISSUE THREAD

**Issue by rabin-io** [wp-cli/wp-cli#4533]
I looked in several places but I was not able to find any information about it. I have several Wordpress installation  on a server, some in a different languages, when working from the command line with wp-cli I like to force the output to be in English only, how can I do that ?

**Comment by danielbachhuber** [comment]
Hi @rabin-io,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
