### ISSUE TITLE
Add 'proxy' setting as the command

### ISSUE THREAD

**Issue by kimipooh** [wp-cli/wp-cli#4538]
This is a command additional suggestion.
In case of the following situation, the proxy setting (WP_PROXY_HOST, WP_PROXY_PORT, WP_USERPROXY) in wp-config.php is needed. If an administrator manages many WordPress, it's too hard to change the proxy setting. Therefore, I suggest to add the 'proxy' setting as the command. 

For Visitors 
[Internet]--> IP address (A) --> WordPress 
For Web server (WordPress)
WordPress --> IP address (B) --> [LAN only]

This situation has also been applied by my University.

**Comment by danielbachhuber** [comment]
Hi @kimipooh,

Thanks for the issue. I'm not sure I fully understand the request.

Would you like to include `WP_PROXY_HOST` when generating the `wp-config.php` file? If so, you might consider the `--extra-php` parameter:

```
wp config create --dbname=testing --dbuser=wp --dbpass=securepswd --extra-php <<PHP
define( 'WP_PROXY', 'host.net' );
PHP
```

Alternatively, you could add `define( 'WP_PROXY', 'host.net' );` to a `proxy-settings.php` file. Then, you can use it in the WP-CLI runtime with:

```
wp --require=proxy-settings.php option get home
```

See [Config](https://make.wordpress.org/cli/handbook/config/) for more.

**Comment by kimipooh** [comment]
Thank you for your reply.
I understood how to create wp-config.php with the proxy setting by your comment.
This is great information!

Could you change, delete, or add the wp-config.php setting as the command?

It seems that "wp config create" command cannot use in case of existing wp-config.php.

**Comment by danielbachhuber** [comment]
> Could you change, delete, or add the wp-config.php setting as the command?

Not quite yet but this is on our radar. See https://github.com/wp-cli/ideas/issues/4

**Comment by kimipooh** [comment]
Sound good!
Thank you for the comment!

At least, I will use --extra-php command when generating new WordPress using WP-CLI :-)
