### ISSUE TITLE
Switch all help docs to third person singular form

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4542]
The help docs for WP-CLI commands includes a mixture of first person and third person verbiage.

For example, the description for `wp help cache` is `Manipulate the WP Object Cache object`, but the description for `wp help cap` is `Adds, removes, and lists capabilities of a user role`.

The latter is the correct grammatical person to use, as per the core documentation standards.

Ref: https://core.trac.wordpress.org/ticket/36913

**Comment by DrewAPicture** [comment]
I believe I've covered all of the commands at this point with the above linked PRs. Please let me know if I've missed anything.

**Comment by schlessera** [comment]
Wow, thanks for all that work, @DrewAPicture !

**Comment by gitlost** [comment]
Ok a lot of instances have been changed thanks to @DrewAPicture and others, but probably not all, so am thinking of removing this from the 1.5.0 milestone @schlessera ?

**Comment by schlessera** [comment]
Yes, we should remove it. This will probably remain an on-going process for a while until we've detected every single offender.

**Comment by bethannon** [comment]
Hi Alain! You added the Hacktoberfest label recently, but the trac ticket looks closed. I'm not much for coding, but I'm happy to help with documentation editing. Still need help on this?

**Comment by schlessera** [comment]
Hi Beth,
I think we haven't yet changed _all_ of the single-person entries to third-person yet. If you can detect singular use in the documentation for the commands, PRs are of course always welcome.
It might make sense to first create a checklist with the different packages first, though, so we can check them off once they were controlled. Otherwise, it is difficult to know what has been verified already and what hasn't.

**Comment by miya0001** [comment]
Following is the list that should be updated. :)

* [ ] https://github.com/wp-cli/wp-cli/blob/master/php/commands/src/CLI_Command.php
* [ ] https://github.com/wp-cli/wp-cli/blob/master/php/commands/src/CLI_Alias_Command.php
* [ ] https://github.com/wp-cli/wp-cli/blob/master/php/commands/src/CLI_Cache_Command.php
* [ ] https://github.com/wp-cli/wp-cli/blob/master/php/commands/src/Help_Command.php

**Comment by JacobMC** [comment]
Hey there! Just added a PR to take care of those last 4 commands mentioned. Please let me know if there are any other doc changes needed with respect to this issue.

**Comment by schlessera** [comment]
I think we've covered everything by now, so I'm closing this issue.

Thanks all for helping on this one.
