### ISSUE TITLE
composer install breaks inside a submodule

### ISSUE THREAD

**Issue by yardenac** [wp-cli/wp-cli#4544]
your post-install-cmd is "cp -f ./utils/git-pre-commit-hook ./.git/hooks/pre-commit" but that won't work if the wp-cli repo is inside a git submodule. Rather than a dir or symlink, .git will be a file starting with "gitdir:"

This needs to be replaced by a script which uses something like `git rev-parse --git-dir`

**Comment by danielbachhuber** [comment]
Thanks for the heads up. I'll go ahead and revert for now, per https://github.com/wp-cli/wp-cli/issues/4474#issuecomment-343651402
