### ISSUE TITLE
Set --allow-root  in an Environment Variable

### ISSUE THREAD

**Issue by davidbarratt** [wp-cli/wp-cli#4548]
To use WP-CLI within a docker container (which typically runs as root) it would be helpful to be able to set the `--allow-root` config option from an environment variable.

**Comment by danielbachhuber** [comment]
Hi @davidbaratt,

Use of `--allow-root` is strongly discouraged. Should you absolutely need to use it, you can alias `wp` to include `--allow-root`. Generally though, you should try to find some alternative.

**Comment by davidbarratt** [comment]
@danielbachhuber why would it be discouraged within a docker container? The entire thing is sandboxed anyways.

Every other CLI has to run as root anyways (composer, npm, etc.)

**Comment by danielbachhuber** [comment]
> why would it be discouraged within a docker container? The entire thing is sandboxed anyways.

It's still a vector for privilege escalation.

**Comment by davidbarratt** [comment]
@danielbachhuber well the only alternative would be to run as the Apache user (`www-data`), which would be _less_ secure.

**Comment by zmoazeni** [comment]
Seconding @davidbarratt here.

> It's still a vector for privilege escalation.

Can you explain this more? I'm running into this _when I'm already root_. Why would wp-cli try to protect me from a privilege _I already have_?

**Comment by danielbachhuber** [comment]
> Can you explain this more? I'm running into this _when I'm already root_. Why would wp-cli try to protect me from a privilege _I already have_?

If you have any themes or plugins installed, then you're executing probably unknown third-party code as root too.

**Comment by zmoazeni** [comment]
@danielbachhuber Sure, and I appreciate the default set as it is. I wouldn't want to change that.

But shouldn't I, the person with root access, be able to make that choice to change that default without making each invocation of wp-cli more cumbersome?

I'm in the same boat as @davidbarratt using docker. I don't care if unknown third-party code is running as root in this case. That is already a risk I'm willing to accept.

**Comment by danielbachhuber** [comment]
Feel free to `alias wp='wp --allow-root'` then.

**Comment by Charl13** [comment]
+1 for adding a environment variable for this. I would add it to my default docker template.

**Comment by infn8** [comment]
+1 for @danielbachhuber shutting down everybody who wants this across [multiple threads(https://github.com/wp-cli/wp-cli/issues/1838)  I came here looking for this too and now I have a better idea as to why I should totally not want this.  It's easy to make the argument of 

> But I'm super smart and I'm an edge case and I won't break my stuff.

but the team isn't building for edge cases and if you're super smart you can totally add an alias to your profile.

**Comment by wstoettinger** [comment]
@danielbachhuber i don't understand your objections to adding a config option when it is anyways already possible to run it with the '--allow-root' option. Anyone can add this option to his commands as should anyone be able to add this to a config file. Of course the user should be made aware of the implications but it should in the end be the user's choice to add it to the config file or not.

In times of Docker and CI your default response that it's discouraged, shutting down all further discussions seems a bit ignorant to the whole concept of docker.

**Comment by michaelzangl** [comment]
If you are using wp-cli in scripts. I always add --allow-root. This won't do any harm (I assume the people starting the scripts know what they are doing) and allows them to be run in docker containers without problems.

**Comment by Luc45** [comment]
Howdy @danielbachhuber. It's the era of Containerized environments. At least give us an option to disable this warning. The community clearly wants this feature, and there are those of us who know what we are doing.

**Comment by Sirfrummel** [comment]
Any tips here how to add the alias into a Dockerfile?  Feels like it might be relevant to others landing here from Google like I have.

**Comment by Clean-Cole** [comment]
For anyone else googling this. I looks like  [WP_CLI_ALLOW_ROOT](https://github.com/wp-cli/wp-cli/blob/7914bc4fdd5461da83da10358e36dcecd4444cc2/php/WP_CLI/Runner.php#L981) is available.  Prob not worth bothering Daniel considering he is no longer the maintainer.  Obviously a useful feature.

**Comment by g0053** [comment]
`alias wp='wp --allow-root --path=/var/www/wordpress'`
:)

**Comment by soulteary** [comment]
> For anyone else googling this. I looks like [WP_CLI_ALLOW_ROOT](https://github.com/wp-cli/wp-cli/blob/7914bc4fdd5461da83da10358e36dcecd4444cc2/php/WP_CLI/Runner.php#L981) is available. Prob not worth bothering Daniel considering he is no longer the maintainer. Obviously a useful feature.

It was introduced into the project in 2020. Simply setting environment variables can avoid setting unnecessary parameters.

- https://github.com/wp-cli/wp-cli/commit/281f6b21ee208c758006125432476a3233b0fc15


```bash
export WP_CLI_ALLOW_ROOT=1
```

or Dockerfile:

```dockerfile
ENV WP_CLI_ALLOW_ROOT=1
```
