### ISSUE TITLE
Synopsys passed to WP_CLI::add_command not parsed correctly.

### ISSUE THREAD

**Issue by gmazzap** [wp-cli/wp-cli#4561]
I have a couple issues by adding arguments to a command via `WP_CLI::add_command` and the `'synopsis'` argument.

I have issues with both positional and associative arguments.

## Positional arguments issue

Regarding positional arguments, it seems it is **not possible to add "multiple" positional arguments**.

For example if I do:

```php
WP_CLI::add_command(
    'foo bar',
    'my_callback',
    [
        'synopsis' => [
            [
                'type'     => 'positional',
                'name'     => 'test',
                'optional' => true,
                'multiple' => TRUE,
            ],
        ],
    ]
);
```

I obtain:

```shell
$ wp foo bar a b c
Error: Too many positional arguments: b c
```

Changing `'multiple' => TRUE` to `'multiple' => FALSE` changes nothing.

## Associative arguments issue

Regarding **associative** arguments the issue is that is **not possible to add an associative argument to be used as a flag**.

For example if I do:

```php
WP_CLI::add_command(
    'foo bar',
    'my_callback',
    [
        'synopsis' => [
            [
                'type'     => 'assoc',
                'name'     => 'test',
                'optional' => true,
            ],
        ],
    ]
);
```

I obtain:

```shell
$ wp foo bar --test
Warning: --test parameter needs a value
```

Note that if I do:

```shell
$ wp foo bar --no-test
```

Everything works, and the value `false` is correctly assigned to `test` argument.

Adding a _default_ does not help. In fact with:

```php
'synopsis' => [
    [
        'type'     => 'assoc',
        'name'     => 'test',
        'optional' => true,
        'default'  => 1,
    ],
],
```

I still get _"Warning: --test parameter needs a value"_.

Setting _options_ does not help either. With:

```php
'synopsis' => [
     [
          'type'     => 'assoc',
          'name'     => 'test',
          'optional' => true,
          'options'  => [ 1, 0 ],
          'default'  => 1,
     ],
],
```

_"Warning: --test parameter needs a value"_ is still there.

----

This has been tested with latest version at the moment of writing (`v1.4.1`), but I can say things were not different in `v1.3.1`, not tested in earlier versions.

Tested in PHP 7.0 and 7.1.

**Comment by danielbachhuber** [comment]
Thanks for the report, @gmazzap.

> Regarding positional arguments, it seems it is not possible to add "multiple" positional arguments.

The correct registration argument is `'multiple' => true`, not `'repeating' => true`. I've submitted a PR to fix the documentation.

> Regarding associative arguments the issue is that is not possible to add an associative argument to be used as a flag.

The correct registration argument is `'type' => 'flag'` instead of `'type' => 'assoc'`.

**Comment by gmazzap** [comment]
@danielbachhuber  I spend an hour reading docs before opening the issue... With last changes everything is clear. Thanks!

**Comment by gmazzap** [comment]
PS: Might I suggest to use:

```php
$flag = false !== filter_var( $flag, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE );
```

 to validate a flag?

This way `--aflag=false`, `--aflag=no`, `--aflag=off`, and  `--aflag=0`  would be considered `false`, and anything else would be `true`.

**Comment by danielbachhuber** [comment]
> I spend an hour reading docs before opening the issue... With last changes everything is clear. Thanks!

You're welcome :) Apologies you had to spend an hour in the first place.

> This way `--aflag=false`, `--aflag=no`, `--aflag=off`, and `--aflag=0` would be considered false, and anything else would be true.

This would be a breaking change, so we won't be changing it at the framework level. You're welcome to implement the equivalent in your command though.
