### ISSUE TITLE
Displaying boolean false values in output

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4567]
The format that a boolean value is presented in as part of an array of data varies depending on the output format. In some formats it's not optimal.

Example code for a command's output:

```php
$results = [
	[
		'name'  => 'true_foo',
		'value' => true,
	],
	[
		'name'  => 'false_bar',
		'value' => false,
	],
];
$formatter = new \WP_CLI\Formatter( $assoc_args, array_keys( $results[0] ) );
$formatter->display_items( $results );
```

When output as JSON or YAML, the output is fine:

```json
[{"name":"true_foo","value":true},{"name":"false_bar","value":false}]
```

```yaml
---
-
  name: true_foo
  value: true
-
  name: false_bar
  value: false
```

When output as a CSV or a table, false values get "lost":

```
name,value
true_foo,1
false_bar,
```

```
+-----------+-------+
| name      | value |
+-----------+-------+
| true_foo  | 1     |
| false_bar |       |
+-----------+-------+
```

Is there a way that `false` values can be displayed as `0` in this situation? Would it be preferable to display them as `true` and `false` instead of numerically?

**Comment by danielbachhuber** [comment]
> When output as a CSV or a table, false values get "lost":

Why do you consider empty to be lost?

> Is there a way that `false` values can be displayed as `0` in this situation?

You'd need to preprocess the data before output.

> Would it be preferable to display them as `true` and `false` instead of numerically?

This would be a breaking change. We can't trust that systems parsing CSV would magically know to interpret these values as boolean.

**Comment by johnbillion** [comment]
> Could you provide more context as to how you ran into this issue?

I've written [a package](https://github.com/johnbillion/ext) that lists the installed status of PHP extensions as a boolean. The displayed value for boolean false in tabular output appears suboptimal to me.

Would you consider a change that switches tabular output to display `true` and `false` for boolean values? I understand it would be a breaking change. For CSVs, I'm not really sure on the best output, but I was expecting a `0` to appear for false values.

**Comment by danielbachhuber** [comment]
> Would you consider a change that switches tabular output to display `true` and `false` for boolean values? I understand it would be a breaking change.

Probably not :/ I think there are systems parsing tabular output, and I don't think the risk of breaking those systems outweighs the benefit of making this change.

For the purposes of your command, it should be possible to preprocess the data based on `--format`
