### ISSUE TITLE
RPM Package PHP Requirement Problem.

### ISSUE THREAD

**Issue by murtzsarialtun** [wp-cli/wp-cli#4570]
Hi, in the spec file of the package, we put the Requires: php >= 5.3.29. Hovever, tis requirements doesn't work on the EL based distros like Centos7 with php 7.0 or 7.1 because there are no packages that include 7.0 or 7.1 on the base repo of Centos7. We install php from additional repos and in additional repos, packages names are different from php-5.4.x. So, it conflicts with other versions of php like php70u or php71u. It is decreasing to using RPM packages from customers and they are complaining about this conflicts. In my opinion, we should remove the requirement in the spec file. But we can also add a output sentence like "Php 5.3.29 or above must be installed."

**Comment by danielbachhuber** [comment]
Sure, we can change this in the next build for v1.5.0 (due out end of January)

**Comment by murtzsarialtun** [comment]
Ok, I changed spec file my forked repo. https://github.com/murtzsarialtun/wp-cli/blob/master/utils/wp-cli-rpm.spec

**Comment by danielbachhuber** [comment]
@murtzsarialtun Do you want to submit a pull request with your change?

**Comment by murtzsarialtun** [comment]
@danielbachhuber Ok, I submitted. Waiting for the checks

**Comment by danielbachhuber** [comment]
Fixed in #4570
