### ISSUE TITLE
Dictionary-based suggestion should only be shown if they are a valid option

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4578]
Right now, when mistyping a command, a dictionary-based suggestion is automatically shown as soon as it is present. However, as there's partial overlap across commands, the dictionary will contain false positives as well.

The dictionary-based suggestion should only be shown if the suggestion it would produce is actually part of the available options.

**Comment by danielbachhuber** [comment]
What do you mean by "directory-based"?

**Comment by schlessera** [comment]
Huh? I meant "dictionary-based", of course...
