### ISSUE TITLE
WP-CLI displays error when index.php substituted

### ISSUE THREAD

**Issue by smazur** [wp-cli/wp-cli#4583]
Hi! I've encountered with following problem:
We use index.php file substitution while deploy stage of our CD process to show our users a nice lookign message that site is under maintenance. And in this case wp-cli stops working with folowing error:

```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

The reason is that wp-cli runner can't find line in substituted index.php (as it is plain html file) matching following pattern:

`'|^\s*require\s*\(?\s*(.+?)/wp-blog-header\.php([\'"])|m'`

Please, fix or suggest how to solve the problem. Thank you!

**Comment by danielbachhuber** [comment]
Hi @smazur,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
