### ISSUE TITLE
Ability to expose the fact that a plugin includes a WP-CLI command

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4585]
If I'm searching for a plugin to provide a particular piece of functionality, I might be more inclined to choose one over another if it includes a WP-CLI command.

Within the context of w.org, there's no means of exposing the fact that a plugin includes a WP-CLI command.

I wonder if we should look into a standard machine readable means of exposing this. At its most basic, a `wp-cli: true` header could be added to the plugin and then exposed via the w.org plugin API, but maybe extending this to expose the command name or introduce some direct connection to the command declaration or documentation would also be desirable.

Thoughts welcome!

**Comment by johnbillion** [comment]
Oh, this was prompted by the fact I recently discovered over 150 plugins include a WP-CLI command (more specifically, they include the string `extends WP_CLI_Command`).

Results: https://gist.github.com/johnbillion/0e8fb24ad4b1cbf3671cbfe4b4c3fb6f

**Comment by danielbachhuber** [comment]
> Within the context of w.org, there's no means of exposing the fact that a plugin includes a WP-CLI command.

We've discussed this briefly in the past but I guess it never was documented anywhere. I think this would be cool too.

> I wonder if we should look into a standard machine readable means of exposing this. At its most basic, a `wp-cli: true` header could be added to the plugin

Scanning with Tide might be another option.

> (more specifically, they include the string extends `WP_CLI_Command`).

Searching for `WP_CLI::add_command()` is probably the most reliable, because commands don't need to extend the `WP_CLI_Command` class.

**Comment by danielbachhuber** [comment]
This might make more sense for the ideas repo if you'd like to re-open there https://github.com/wp-cli/ideas

**Comment by schlessera** [comment]
@johnbillion I had already created a related meta trac issue: https://meta.trac.wordpress.org/ticket/3126

**Comment by danielbachhuber** [comment]
Meta Trac ticket is the better place to discuss this going forward.
