### ISSUE TITLE
wp-cli ends with nothing after the "Loaded WordPress" message (SOLVED)

### ISSUE THREAD

**Issue by lucidheart** [wp-cli/wp-cli#4587]
My apologies if this is an inappropriate place to post this. I really didn't see any better place for it that might come up in a google search for others to find.

I am running wp-cli on a cPanel server, version 68.0.21 on CentOS 7.4.  I was getting good results with "wp --info" and "wp core version" commands.  Also, passing "--debug" was not reporting any errors at all.  However, once I got to doing anything significant, like a "wp plugin status", it was returning no results, and ending after the "Loaded WordPress" message was displayed.

After comparing my cPanel EasyApache extensions to that of a working system, I discovered the only difference was that mbstring was not configured on the non-working system.  Once I added mbstring to the EasyApache 4 configuration, everything began working just fine.

Perhaps mbstring ought to be listed as one of the "minimum requirements" to work?  I don't know.  Maybe it's just assumed that mbstring would be included by default for most installations.  :-)

Thought I'd post in the case that this information might be helpful to others.

**Comment by gitlost** [comment]
WP-CLI itself should work without `mbstring` (or `intl`) being enabled (although you'll get degraded UTF-8 results), so maybe one of your plugins or themes is using `mbstring` functions without checking first?

**Comment by lucidheart** [comment]
Thanks for the suggestion about possible mbstring issues/requirements in the plugins.  If the plugins required mbstring, wouldn't that mean that the WordPress website would be broken on the front-end as well?   Because, from what I can tell, all of the plugins were functioning just fine from the front facing website, as well as from the wp-admin interface.

For the record.  Here are the plugins I have installed.
  I akismet  4.0.2
  A jetpack  5.6.1
  A woocommerce  3.2.6
  A woocommerce-gateway-paypal-powered-by-braintree  2.0.4
  A woocommerce-services  1.9.1

And the themes, for completeness.
2 installed themes:
  A galleria 2.2.12
  P storefront 2.2.5

**Comment by gitlost** [comment]
> If the plugins required mbstring, wouldn't that mean that the WordPress website would be broken on the front-end

Php on the command line usually uses different `php.ini` and `conf.d` ini files than the server does, so an extension could be enabled on the server and not on the command line.

Did anything appear in your `error_log`?

**Comment by schlessera** [comment]
Try running `wp plugin status --skip-plugins` to see whether that changes the output. If it does, it is indeed a plugin issue.

Either way, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. I'm closing this now, feel free to hit us up on Slack in the #cli team for further discussion & support.
