### ISSUE TITLE
wp scaffold and WPCS

### ISSUE THREAD

**Issue by sandrodz** [wp-cli/wp-cli#4589]
Files generated by wp scaffold command are not WordPress coding standard compliant!

For example cpt generated:

<img width="1280" alt="screen shot 2017-12-22 at 3 39 29 pm" src="https://user-images.githubusercontent.com/8479569/34301798-5635d66c-e72e-11e7-9062-378b07b4a648.png">

**Comment by schlessera** [comment]
@sandrodz Thanks for reporting.

I can confirm, some of the templates will produce code that does not pass WPCS.

Could you please open this issue in the correct repository under https://github.com/wp-cli/scaffold-command ?

**Comment by sandrodz** [comment]
ah, got it, opening in correct repo.
