### ISSUE TITLE
Add OS & shell information to `--info` output

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4599]
For debugging purposes, we should add basic information about the operating system & the shell that WP-CLI is currently running in to the output of `wp cli info`.

This would help to pinpoint platform-specific issues faster.

**Comment by thrijith** [comment]
sorry about the first commit message

**Comment by gitlost** [comment]
Closed via https://github.com/wp-cli/wp-cli/pull/4604.
