### ISSUE TITLE
Is `wp core update` deprecated?

### ISSUE THREAD

**Issue by benqzq** [wp-cli/wp-cli#4611]
Is `wp core update` deprecated?

Given that since 2017 core is updated automatically, I'm afraid that there could be some **conflict** between default automatic core updates, and manual core updates as in upgrade all behavior:

	0 2 * * * for dir in /var/www/html/*/; do cd "$dir" && /usr/local/bin/wp plugin update --all --allow-root; done
	0 3 * * * for dir in /var/www/html/*/; do cd "$dir" && /usr/local/bin/wp core update --allow-root; done
	0 4 * * * for dir in /var/www/html/*/; do cd "$dir" && /usr/local/bin/wp theme update --all --allow-root; done
	0 5 * * * chown www-data:www-data /var/www/html/* -R
	0 6 * * * find /var/www/html/* -type d -exec chmod 755 {} \; && 0 0 * * * find /var/www/html/* -type f -exec chmod 644 {} \;

**Comment by schlessera** [comment]
No, `wp core update` is not deprecated.

A lot of site owners actually disable the automatic updates, to have full control over the state of their state. They still want to be able to run manual updates.

Also, a conflict is unlikely, as an update starts with a check to see if updates are available. If they have already been done, no new ones are available, so nothing happens really.
