### ISSUE TITLE
wp cli update cron issue

### ISSUE THREAD

**Issue by nandulal8272** [wp-cli/wp-cli#4614]
Hi,

I have added cron for wp cli update
---
30 18 * * * yes |  /usr/local/bin/wp cli update --allow-root
---
cronjob for wp cli update it results in error
---
PHP Notice:  Undefined index: argv in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Runner.php on line 772
PHP Warning:  array_slice() expects parameter 1 to be array, null given in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Runner.php on line 772
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Configurator.php on line 134
PHP Notice:  Use of undefined constant STDOUT - assumed 'STDOUT' in phar:///usr/share/wp-cli/wp-cli.phar/php/utils.php on line 950
PHP Notice:  Undefined index: argv in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Runner.php on line 886
PHP Warning:  implode(): Invalid arguments passed in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Runner.php on line 886
PHP Notice:  Use of undefined constant STDERR - assumed 'STDERR' in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Loggers/Regular.php on line 50
PHP Warning:  fwrite() expects parameter 1 to be resource, string given in phar:///usr/share/wp-cli/wp-cli.phar/php/WP_CLI/Loggers/Base.php on line 61
X-Powered-By: PHP/7.0.26
Content-type: text/html; charset=UTF-8
---

**Comment by gitlost** [comment]
You don't seem to be running `WP-CLI` via the command line php CLI, see https://github.com/wp-cli/wp-cli/issues/1346.

**Comment by nandulal8272** [comment]
How can I remove those error, and add that cron?
What steps I need to follow to add that cronjob for "wp cli update"?

**Comment by nandulal8272** [comment]
# php -v
ea-php-cli Copyright 2017 cPanel, Inc.
PHP 7.0.26 (cli) (built: Nov 30 2017 12:31:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.26, Copyright (c) 1999-2017, by Zend Technologies

**Comment by danielbachhuber** [comment]
Hi @nandulal8272,

For support, please review: https://wp-cli.org/#support
