### ISSUE TITLE
Alias for a Vagrant machine in a subdirectory

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4618]
Scenario: I have a project that contains a Vagrant environment as a submodule in a subdirectory. As a result, every time I want to run a Vagrant command I have to change into the correct directory.

    cd vm
    vagrant ssh
    (run commands)
    cd ../

I was hoping to use a WP-CLI alias to avoid the need to do this. Unfortunately the alias suffers from the same problem, in that the `vagrant ssh` command needs to be run from a subdirectory. I can get around this problem by using the VM's IP address in the alias, but this means it's not a portable configuration.

Might it make sense to allow a Vagrant alias to specify a local directory from which the command gets run? (Relative to the root of the installation I guess?) I'm not sure on the best format for the syntax. Maybe:

    @local:
      ssh: vagrant:<subdirectory>/<machine>

**Comment by grappler** [comment]
You can use the hostname from`vagrant ssh-config` and use that instead.

**Comment by miya0001** [comment]
You can write `wp-cli.yml` like following.

```
@local:
  ssh: vagrant:<machine-name>:<path>
```

And you can define `<machine-name>` in Vagrantfile.

```
config.vm.define "<machine-name>" do |v|
  # Nothing to do. :)
end
```

Then you can run command `wp @local plugin list`.

See example:
* https://github.com/vccw-team/vccw/blob/master/Vagrantfile#L42-L43
* https://github.com/vccw-team/vccw/blob/master/provision/playbooks/templates/wp-cli.yml

**Comment by johnbillion** [comment]
Thanks for the tips, @grappler and @miya0001. Unfortunately it seems that the command still needs to be run from inside the subdirectory that contains the VM. Even running the Vagrant command `vagrant ssh <machine>` doesn't work if you're not in the directory and you use the machine name, only if you use the machine id from the `id` column of `vagrant global-status` (which I don't believe is portable).

**Comment by grappler** [comment]
> Unfortunately it seems that the command still needs to be run from inside the subdirectory that contains the VM.

You only need to run `vagrant ssh-config` once and copy the output to `~/.ssh/config`.  A quick shortcut would be `vagrant ssh-config > ~/.ssh/config`. Sorry for not being clearer before.

This is the output of one of our vagrant boxes where vagrant config is in a subfolder.
```
Host wearerequired
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/grappler/Documents/webdev/wearerequired.local/_vagrant/puphpet/files/dot/ssh/id_rsa
  IdentityFile /Users/grappler/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
```

**Comment by schlessera** [comment]
I think this is better handled with the tools that vagrant or the environment provide.

What you give to the `vagrant:` prefix is a host name. Having something like `<subdirectory>/<hostname>` does not make conceptual sense.

Also, the main purpose of adding the `vagrant:` prefix in the first place was to be able to conveniently use `@alias` notation to refer to your machines. This is meant to work no matter where you are located, so a relative subdirectory does again not make sense.

Closing this for now. Feel free to reopen in case I have missed a blocking technical limitation.
