### ISSUE TITLE
wp core check-update reporting wrong result

### ISSUE THREAD

**Issue by raptor235** [wp-cli/wp-cli#4619]
Hey guys, I'm seeing WordPress is at the latest version when I check for update... 

when I cat 

cat wp-includes/version.php

I get $wp_version = '4.7.8';

I'm running wp core check-update --minor  so I would be expecting 4.7.9 as per https://codex.wordpress.org/WordPress_Versions but wp cli is showing WP is up to date...

How is the version actually checked in the DB or in the file system?

**Comment by gitlost** [comment]
Can't reproduce this using a WP 4.9.1 site, `wp core check-update --minor` returns 4.9.2. If I artificially edit `wp-includes/version.php` to be 4.7.8 I get 4.7.9 returned.

> How is the version actually checked in the DB or in the file system?

It uses core functions `wp_version_check()` and `get_site_transient( 'update_core' )`.

**Comment by raptor235** [comment]
Very strange... so I've added a bunch of test dumps into wp_version_check() 

When I dump out all the $offers back from the server I get 4.7.9 included as one of the offers yet WP CLI is reporting that the install is up to date... 

You can see that 4.7.8 is picked up from versions.php and the server responds as it should

http://www.flowpress.com/screenshots/screenshot_2018-01-22_at_1.41.40PM.png

When I run the wp cli command with the debug dumps I can see 4.7.9 included as well but the message results in update not being required

http://www.flowpress.com/screenshots/screenshot_2018-01-22_at_1.42.29PM.png

Going to keep digging.

**Comment by raptor235** [comment]
Just to give some background here...the DB is running 4.7.9 but the files aren't. We run the production site on WP Engine who automatically upgraded the build. But our git repo is behind... so we're trying to run an automatic update but cli is saying it's up to date when in reality the file system isn't.

**Comment by raptor235** [comment]
@gitlost is it possible for you to run a test where you run the update... then revert the entire file structure and leave db in tact... see what WP CLI responds with at that point?

**Comment by raptor235** [comment]
By the way when I log into the install WP is reporting the correct number

http://www.flowpress.com/screenshots/screenshot_2018-01-22_at_1.49.22PM.png

**Comment by schlessera** [comment]
I cannot reproduce either:

![image 2018-01-22 at 7 54 42 pm](https://user-images.githubusercontent.com/83631/35238651-6d4448aa-ffae-11e7-936f-1abd0a772bb1.png)

Feel free to investigate further if you still think this might be a bug, and reopen this issue if you discover something.

In case you just want to get ahead with your site, you can use this command to force an update to `4.7.9`:
```
wp core update --version=4.7.9 --force
```
