### ISSUE TITLE
Cannot add multiple meta at once

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4621]
I would like to know if there is a way to add multiple meta at once like wp post meta add 2271 meta1 value1 meta2 value2 and so on ?

**Comment by killown** [comment]
The issue is that I have to set meta in hundred of posts and every post has 10 meta values and for every post I need to execute one line from wp cli and every line takes almost 2 seconds to finish, so the issue here is performance, if possible, could you implement this feature?

**Comment by gitlost** [comment]
Ah I see, very good. Will open the issue on the `wp-cli/entity-command` repo as an enhancement request and close this issue...

**Comment by gitlost** [comment]
I should add that if https://github.com/wp-cli/wp-cli/issues/4616 were implemented then that would be an alternative method of updating lots of meta at once...

**Comment by killown** [comment]
Thank you!

**Comment by gitlost** [comment]
Closing in favor of https://github.com/wp-cli/entity-command/issues/132
