### ISSUE TITLE
Make bundled composer.jsons consistent.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4625]
As mentioned in https://github.com/wp-cli/embed-command/issues/18#issuecomment-358173238, the `composer.json`s for bundled commands aren't consistent in requiring `wp-cli/wp-cli`.

These:

db-command
eval-command
export-command
import-command
media-command
package-command
search-replace-command
server-command
shell-command

have:
```
    "require": {
        "wp-cli/wp-cli": "*"
    }
```

while these:

cache-command
checksum-command
config-command
core-command
cron-command
entity-command
extension-command
language-command
rewrite-command
role-command
scaffold-command
super-admin-command
widget-command

have
```
    "require-dev": {
        "wp-cli/wp-cli": "*"
    }
```

I suppose using `require-dev` makes the most sense since that's when the `composer.json` is used??

Some extra motivation here is that it would make sense to me that the version of `wp-cli/wp-cli` required would match the latest version it's been tested and released against, so on releasing `embed-command` for instance would have:
```
    "require-dev": {
        "wp-cli/wp-cli": "^1.5.0"
    }

```

Edit: This ~~might necessitate~~ necessiates having a branch alias in the `composer.json` for `wp-cli/wp-cli`:
```
        "branch-alias": {
            "dev-master": "1.5.x-dev"
        },
```
~~but I don't understand Composer so not sure~~ as mentioned by @schlessera https://github.com/wp-cli/db-command/pull/79#issuecomment-357967577.

Another motivation is that currently to get the latest framework in a bundled command I do this:
```
composer require wp-cli/wp-cli:dev-master
composer update
git checkout composer.json # Undo change.
```
which shouldn't be necessary.

Also having a consistent template overall would be nice. Suggestion:
```
{
    "name": "wp-cli/<xxx-command>",
    "description": "<xxx-command-description>.",
    "type": "wp-cli-package",
    "homepage": "https://github.com/wp-cli/<xxx-command>",
    "support": {
        "issues": "https://github.com/wp-cli/<xxx-command>/issues"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "<xxx-command-author-name>",
            "email": <xxx-command-author-email>",
            "homepage": "<xxx-command-author-homepage>"
        }
         <etc if other authors>
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "autoload": {
        "psr-4": {
            <other stuff as needed eg "WP_CLI\\": "src/WP_CLI",>
           "": "src/"
        },
        "files": [ "<xxx-command.php>" ]
    },
    "require": {},
    "require-dev": {
        "behat/behat": "~2.5",
        <other stuff as need eg "phpunit/phpunit": ">=4", "composer/composer": "^1.2.0",>
        "wp-cli/wp-cli": "<caret latest version released against>"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.x-dev"
        },
        "bundled": true,
        "commands": [
            <xxx-command list>
        ]
    }
}
```

**Comment by schlessera** [comment]
While you're absolutely right that this should be consistent, this is just a huge effort without any immediate gain. Let's remove this from the 1.5.0 milestone for now.

**Comment by gitlost** [comment]
Cool, I'll do some though if the opportunity arises.

**Comment by schlessera** [comment]
This was made consistent and should currently work as intended.
