### ISSUE TITLE
mmap() failed: [12] Cannot allocate memory in post list

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4627]
wp  post list --format=csv --allow-root --path=/var/www/html

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

This is happening in a DB with 22075 posts

1GB memory wasn't enough

Suggestion, implement a way to chunk post list and append to a file

**Comment by miya0001** [comment]
I guess it will be solved by `php://temp`.
But I can't reproduce this problem with the 100,000 posts.

```
$ wp post generate --count=100000
$ php -d memory_limit=64M /usr/local/bin/wp post list --format=csv
```

**Comment by danielbachhuber** [comment]
> Suggestion, implement a way to chunk post list and append to a file

You can use `WP_Query`'s [existing pagination arguments](https://codex.wordpress.org/Class_Reference/WP_Query#Pagination_Parameters) to iterate the data, and append to a file with `>>`.

I'm not convinced this is worth solving in WP-CLI.
