### ISSUE TITLE
wp core download throws error 'mkdir(): Permission denied in FileCache.php'

### ISSUE THREAD

**Issue by flurinduerst** [wp-cli/wp-cli#4633]
When downloading WordPress using `wp core download` i get this error:

`==> default: PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/wp/php/WP_CLI/FileCache.php on line 265`

It does not interrupt the download though. Everything works fine, but it just seems odd. I can't figure out why this is happening and what it actually tries to do. 

Note: Im using a bash script to execute this and many other commands via ssh on a vagrant machine. Everything else (`wp core config`, `wp core install` etc.) works totally fine.

user permissions for `wp*` on `/usr/local/bin`
```
-rwxr-xr-x  1 root root  4409743 Jan 23 16:11 wp*
```

**Comment by chriscroome** [comment]
Could it be an issue with not having write permissions for the TMPDIR?

**Comment by schlessera** [comment]
@flurinduerst Yes, @chriscroome is probably right. WP-CLI downloads the zipped core to a temporary location, and then extracts it into the target location. Your login probably doesn't have the correct permissions to write into whatever the system claims to be the temporary folder.

**Comment by flurinduerst** [comment]
Thanks for your answers, appreciate it! 
The error occurs within the installation process of [WPDistillery](https://wpdistillery.org) which is using [scotchbox](https://box.scotch.io) and uses ssh to login to the vagrant-box as root. Not sure why there is a permission problem.

`usr/local/bin/*wp* permissions are: -rwxr-xr-x so there shouldn't be a problem being logged in as root.
