### ISSUE TITLE
wp media features [feature-request]

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4657]
Hi there! I am wondering if would be possible to implement:
    wp media search filename:  search for files
    wp media list: list all files in media
    wp media import filename --return_url: return https://mydomain/filename after importing

**Comment by gitlost** [comment]
Could you open separate issues for each of these on https://github.com/wp-cli/media-command/issues instead @killown  (or one issue on https://github.com/wp-cli/ideas/issues)?

**Comment by killown** [comment]
I will do that, thank you for reply
