### ISSUE TITLE
Use alternate pager when `less -R` is not available (ie Busybox)

### ISSUE THREAD

**Issue by goldenapples** [wp-cli/wp-cli#4662]
I'm using wp-cli in a Docker container running Busybox, and keep being frustrated that the `wp help` command tries to use `less` with the `-R` flag, which isn't available in the stripped down version of `less` that is bundled with Busybox. 

<img width="394" alt="screen shot 2018-02-01 at 5 44 39 pm" src="https://user-images.githubusercontent.com/665992/35712600-a3b7e83a-0777-11e8-93aa-49a435c3fc2c.png">

It would be good to test for this environment in the same way that we test for Windows, and use "more" for the pager on Busybox rather than `less -R`. 

Unfortunately, this isn't as simple as checking the PHP_OS superglobal, since Busybox just advertises itself as "Linux". The only sure way I've found is checking if running in Busybox is along the lines of `if ( system( 'busybox --list | grep more' ) === 'more' )`. 

But the problem is more general than just Busybox, as I think the same thing would hold true in terminals without color support. I'm wondering if doing some terminal feature detection would be appropriate here. 

```
if ( shell_exec( 'tput colors' ) === '' ) {
  /* ... */ $pager = 'more';
}
```

...so that `wp help ` doesn't output all of its color escape codes in terminals that don't support color.

**Comment by gitlost** [comment]
The standard solution re `less -r` is to set the `PAGER` environment variable to what you want. This needs to be documented explicitly I think, as it's a common issue https://github.com/wp-cli/wp-cli/search?q=busybox&type=Issues&utf8=✓. It might also make sense to have a `ENVIRONMENT VARIABLES` section after the `GLOBAL PARAMETERS` section in the help.

Also I'm wondering if the `-r` option shouldn't just be removed, as I don't think any help docblocks use (or should use) color escape sequences.

Re detecting if on Busybox, as it can be installed standalone on any repo (it is on my Ubuntu 17.04 for instance), your example wouldn't work unfortunately. Googling shows a number of other possible methods, but I'm wondering if the `SHELL` variable could be used? It's set to `/bin/ash` on a VirtualBox Alpine I half-installed, which although just a symlink to `/bin/busybox` seems a good bet as being distinctive enough (mind you `PAGER` is also set to `less` so not sure why that isn't working for other instances such as yours).

**Comment by gitlost** [comment]
> Also I'm wondering if the `-r` option shouldn't just be removed, as I don't think any help docblocks use (or should use) color escape sequences.

Ah just occurred to me that escape sequences are used to bold the section headers [commands/help.php#L91](https://github.com/wp-cli/wp-cli/blob/v1.5.0/php/commands/help.php#L91) so that's why it's used. However a better option would probably be to use the `LESS` environment variable to set options, which is recognized by GNU and macOS `less`.

**Comment by goldenapples** [comment]
> I'm wondering if the SHELL variable could be used?

On my install, SHELL is just `/bin/sh`, but that is a symlink to `/bin/busybox`, so a realpath check would work. Environment detection is a blunt tool though: it's totally possible to install GNU less and a shell that supports color on busybox.

Locally I'm setting `PAGER=more` and that works for me, and I'm happy to close this if that's the best solution that can be done. It just strikes me that it would be good to default to `more` in terminals without color support.

**Comment by schlessera** [comment]
How about detecting whether the pager command worked, and if not put the safest option (`more`) into the config files, with a short warning about what is happening?
```
Warning: The default pager couldn't be used on your system, saving the use of the
compatibility fallback pager 'more' into your ~/.wp-cli/config.yml file.
```

This would then automatically adapt to any environment, while still giving users several options to override.

**Comment by goldenapples** [comment]
I like that approach. I'll try and come up with a PR to address it in the next few days.

**Comment by danielbachhuber** [comment]
Closing this as `maybelater`. It seems like the existing solution is sufficient-enough.
