### ISSUE TITLE
Issue Updating CLI

### ISSUE THREAD

**Issue by ajitbohra** [wp-cli/wp-cli#4664]
Trying to update WP-CLI 1.5.x nightly build to latest stable release.

Getting CURL timeout & SSL error.

**Last Error:**
Error: Failed to get url 'https://github.com/wp-cli/wp-cli/releases/download/v1.5.0/wp-cli-1.5.0.phar': cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104.****

**Comment by gitlost** [comment]
Can't reproduce this. Might be something wrong with your local setup. Does
```
curl -LO https://github.com/wp-cli/wp-cli/releases/download/v1.5.0/wp-cli-1.5.0.phar
```
work for you?

**Comment by ajitbohra** [comment]
Was trying to update it on the server (DigitalOcean) ended up manually updating/reinstalling latest copy. Will try on few other servers and confirm if same persist.

**Comment by ajitbohra** [comment]
works perfect on other servers seems like an issue specific server config.

**Comment by gitlost** [comment]
Thanks for reporting anyway @ajitbohra (and for closing!).
