### ISSUE TITLE
wp media search files [Request]

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4665]
hi there, could you implement a way to search files?

example:
> wp media search file1
http://mywordpress.com/file1.txt
http://mywordpress.com/somewhere/file.png
http://mywordpress.com/wp-content/uploads/file12.jpg

> wp media search file1.tar.gz
http://mywordpress.com/hidden/file1.tar.gz
http://mywordpress.com/file1.tar.gz

> wp media search --search_path='hidden' file1.tar.gz
http://mywordpress.com/hidden/file1.tar.gz

> wp media search all --search_date=today
No files found

> wp media search all --search_date="2018/01/01"
http://mywordpress.com/file1.txt
http://mywordpress.com/somewhere/file.png
http://mywordpress.com/wp-content/uploads/file12.jpg

**Comment by danielbachhuber** [comment]
Hi @killown,

Thanks for the suggestion. How would this be different than `grep` or similar?

**Comment by kirtangajjar** [comment]
@danielbachhuber `grep` uses filesystem to search for files. This command would search in database if that particular file exists. Yes we can use `wp db search` but this can be a nice wrapper around it.

**Comment by schlessera** [comment]
I agree with @danielbachhuber 's sentiment, there's no real difference to simply using `grep` or `find`. I'm not sure what the benefit is of having this as a WP-CLI command.
