### ISSUE TITLE
Individual command documentation has disappeared from wordpress.org

### ISSUE THREAD

**Issue by aj-adl** [wp-cli/wp-cli#4668]
**Summary:**

All auto-generated command documentation is no longer present on https://developer.wordpress.org/cli/commands/

**Steps to reproduce**

1. visit https://developer.wordpress.org/cli/commands/ or any command sub-page
2. command description (list pages) or documentation (individual command pages) will be completely blank

Non-core commands display their installation instructions but no further details - ie: https://developer.wordpress.org/cli/commands/dist-archive/ or https://developer.wordpress.org/cli/commands/admin/

**Results and Impacts**

All detailed command documentation is missing. 

Handbook is still accessible, but all the auto-generated command docs are gone.

Example screenshots - 
https://www.dropbox.com/s/ih88i1t6ca90z04/Screenshot%202018-02-06%2015.30.40.png?dl=0
https://www.dropbox.com/s/etdc8scee2iin0q/Screenshot%202018-02-06%2015.31.05.png?dl=0

**Comment by schlessera** [comment]
Thanks, @aj-adl !
We're aware of the issue and working on a fix.

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/handbook/issues/202

**Comment by schlessera** [comment]
Commands are back online again.
