### ISSUE TITLE
Tests should not depend on external commands

### ISSUE THREAD

**Issue by kirtangajjar** [wp-cli/wp-cli#4673]
`testRunMysqlCommandProcDisabled`, `testLaunchEditorForInputProcDisabled` and `testGetTempDir` in `test-utils.php` and `testLaunchProcDisabled` in `test-ee.php` depends on `eval-command`. 

This shouldn't be the case. If they *have* to, It's better to move such tests in a separate file(as it's done with `test-bundled-commands.php`)

**Comment by gitlost** [comment]
Thanks @kirtangajjar . Not 100% sold on the philosophical argument but these are poor tests as they're never run on the phar so should have been fixed with https://github.com/wp-cli/wp-cli/pull/4597. Will refactor as behat tests.

**Comment by schlessera** [comment]
The main issue here is that you cannot run the "unit tests that are supposed to test the framework" without including the hidden dependency of the bundled command. So not only are they not "unit" tests (which, I know, is something WordPress does not really care about at all), but they also break when you just want to test your "package" in isolation.

**Comment by gitlost** [comment]
Well I find the whole bundled versus framework division artificial. But that should be part of the Great Package Debate following on from the last office hours...

**Comment by schlessera** [comment]
That division is not so artificial. I had to build a Composer plugin that splits 1 autoloader setup into two, just to make it work...

**Comment by kirtangajjar** [comment]
@gitlost The thing is `wp-cli` is an excellent shell rather than being just a wp specific utility. So if we manage the code in such a way that it does not depend on wp specific commands, it will be very easy to fork the code and use it as a base to build another cli utility on top of it.
