### ISSUE TITLE
Check if post_name already exist [Request]

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4677]
Could you implement an efficient way to check if a post_name already exist?

Example:

    wp post list --post_name='Testing'
    Post name: Testing found

    wp post list --post_name='Testing2'
    Post name: Testing2 Not found 

    wp post list --post_name='Testing' --boolean
    True

**Comment by killown** [comment]
well sorry, wp post list --field=post_name is enough

**Comment by schlessera** [comment]
How about:
```
wp150 post list --name='Testing' --format=count
```

**Comment by killown** [comment]
worked!! thank you
