### ISSUE TITLE
Support v4 symfony packages

### ISSUE THREAD

**Issue by evilebottnawi** [wp-cli/wp-cli#4678]
I can help with this, if you accept :+1:

**Comment by schlessera** [comment]
We'll discuss the roadmap for v2.0.0 during the upcoming office hours. We'll then decide how we want to handle dependencies.

**Comment by danielbachhuber** [comment]
@schlessera How'd this turn out?

**Comment by tapetersen** [comment]
Is there any progress on this or anyone found a reasonable workaround to be able to  require and use wp cli commands in a project using symfony 4.

**Comment by schlessera** [comment]
WP-CLI v2 is planned for end of July.

Up until then, a possible workaround is to use Phive or Tooly to use the Phar-version of WP-CLI with Composer.

**Comment by tapetersen** [comment]
Ok thanks for that. My problem is not that  I want to use wp-cli *the tool* in a project using symfony bot rather use some of the classes/functions from it in a couple of symfony commands and I can't install those in the same project it seems. 

Even if the individual commands can be installed they lacked some class from the main project (missing dependency).

It's not breaking for me and I solved it by replicating the commands I needed but thanks for the timeline update.

**Comment by schlessera** [comment]
This should now work correctly as of v2.0.0.
