### ISSUE TITLE
Count of Uncategorized category show 1 instead of 0 after wp site empty

### ISSUE THREAD

**Issue by benoitchantre** [wp-cli/wp-cli#4679]
`wp site empty` command removes all contents, but when you look at the Uncategorized category (not removable), the count value show `1`instead of `0` although all posts have been removed.

**Comment by gitlost** [comment]
Thanks @benoitchantre , yes looks like a bug, am going to move this to `entity-command` where `Site_Command` lives...

**Comment by gitlost** [comment]
Closing in favor of https://github.com/wp-cli/entity-command/issues/143
