### ISSUE TITLE
Allow to overwrite arguments in `before_invoke` hook

### ISSUE THREAD

**Issue by kierzniak** [wp-cli/wp-cli#4680]
Hi,
thank you for your work on wp-cli. This is awesome project.

I have in mind one idea which require to add command arguments to `before_invoke` hook in such a way that they can be overwritten by my wp-cli plugin.

I just want to make possible to add or change command arguments based on my dotenv file. My workflow is heavily based on dotenv file and environment variables from my local environment to ci build process.

If you think it is good idea please let me know and I can start working on pull request.

**Comment by danielbachhuber** [comment]
Hi @kierzniak,

Thanks for the suggestion. I'm not sure this is a great idea because:

1. It could lead to inconsistent usage behavior.
2. It becomes yet another use-case / feature we need to support in the long term.

> I just want to make possible to add or change command arguments based on my dotenv file. My workflow is heavily based on dotenv file and environment variables from my local environment to ci build process.

Could you share more details on what you're trying to do, so we can see if there's an existing alternative?

**Comment by kierzniak** [comment]
Hi @danielbachhuber,
thank you to your response.

> Could you share more details on what you're trying to do, so we can see if there's an existing alternative?

I'm trying to automate my work everywhere I can. wp-cli is helping me to download, configure and install WordPress. Depending on the current environment I need to pass different arguments to wp-cli. 

Now I'm passing dotenv variables in my phing [build.xml file](https://github.com/motivast/wp-site-boilerplate/blob/master/build.xml#L37). Which is basically creating the same wp-cli commands with own arguments from dotenv file. Everytime I want to execute wp-cli command with dotenv variables I have to add build task.

I feel like I am doing work which was already done. I came up with idea to write a plugin to replace wp-cli arguments with dotenv variables.

I seen some suggestions to create seperate wp-cli files like `wp-cli.development.yml`, `wp-cli.production.yml` and load them by changing `WP_CLI_CONFIG_PATH` but I don't want to keep my development and production configuration in VCS.

Enviromental variables are widely supported e.g. in [travis](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) and [gitlab](https://docs.gitlab.com/ce/ci/variables/README.html#secret-variables) where they are kept in secret and can be different depending on the deploy target. Also my solution is based on phing task system which is no very popular. When I want to introduce my workflow to my teammates and community they are confused about many tools. I would like to keep it simple.

**Comment by danielbachhuber** [comment]
Makes sense, thanks for clarifying.

At this point, it doesn't seem like a compelling reason to add runtime modification of passed arguments. Based on your needs, I think it'd make most sense to create a standalone bash file that calls all of the WP-CLI setup commands you need to run. This bash file could easily read execution arguments from the environment variables, and pass them through to WP-CLI.
