### ISSUE TITLE
wp user create fails silently

### ISSUE THREAD

**Issue by roscom** [wp-cli/wp-cli#4682]
wp user create ... fails to create the user and provides no indication of why.
The following demonstrates the error:
```
wp user create bob bob@gmail.com --user_pass=C2n6qfZMDSP --debug

Debug (bootstrap): No readable global config found (0.181s)
Debug (bootstrap): No project config found (0.181s)
Debug (bootstrap): argv: /usr/local/bin/wp user create bob bob@gmail.com --user_pass=C2n6qfZMDSP --debug (0.181s)
Debug (bootstrap): ABSPATH defined: /home/arabisla/public_html/ (0.181s)
Debug (bootstrap): Begin WordPress load (0.182s)
Debug (bootstrap): wp-config.php path: /home/arabisla/public_html/wp-config.php (0.182s)
Debug (bootstrap): Loaded WordPress (0.364s)
Debug (bootstrap): Running command: user create (0.364s)
[arabisla@server2 public_html]
[arabisla@server2 public_html]$ wp user list
[arabisla@server2 public_html]$ 
```
No success msg or any error msg of any kind.
wp --info output:
```
[arabisla@server2 public_html]$ wp --info
OS:     Linux 2.6.32-696.16.1.el6.x86_64 #1 SMP Wed Nov 15 16:51:15 UTC 2017 x86_64
Shell:  /bin/bash
PHP binary:     /opt/cpanel/ea-php56/root/usr/bin/php
PHP version:    5.6.33
php.ini used:   /opt/cpanel/ea-php56/root/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/arabisla/public_html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.0
[arabisla@server2 public_html]$
```
WordPress version is:
```
[arabisla@server2 public_html]$ wp core version
4.9.4
[arabisla@server2 public_html]$
``` 
Would appreciate your assistance.
Ross

**Comment by danielbachhuber** [comment]
Hi @roscom,

Does this issue reproduce on a stock WordPress install, with no plugins active? If not, it may be a problem from an existing theme or plugin. [Please see this documentation](https://make.wordpress.org/cli/handbook/identify-plugin-theme-conflict/) for further debugging information.

**Comment by roscom** [comment]
Hi Daniel

Output of the offending command with plugins & themes skipped:

```
    [civilcel@server2 public_html]$ wp core verify-checksums
    Success: WordPress installation verifies against checksums.
```

```
 [civilcel@server2 public_html]$ wp --skip-plugins --skip-themes user list --debug
    Debug (bootstrap): No readable global config found (0.183s)
    Debug (bootstrap): No project config found (0.184s)
    Debug (bootstrap): argv: /usr/local/bin/wp --skip-plugins --skip-themes user list --debug (0.184s)
    Debug (bootstrap): ABSPATH defined: /home/civilcel/public_html/ (0.184s)
    Debug (bootstrap): Begin WordPress load (0.184s)
    Debug (bootstrap): wp-config.php path: /home/civilcel/public_html/wp-config.php (0.184s)
    Debug (bootstrap): Loaded WordPress (0.313s)
    Debug (bootstrap): Running command: user list (0.314s)
    Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///usr/local/bin/wp/vendor/symfony/polyfill-mbstring/Mbstring.php on line 534
    [civilcel@server2 public_html]$
```
Error would not seem to be plugin or theme related.
Hope this helps.

**Comment by danielbachhuber** [comment]
Based on the fatal error, it seems the `iconv()` PHP function isn't available. Any ideas why that might not be the case?

**Comment by roscom** [comment]
Thanks.
Nope. I have no idea.

**Comment by danielbachhuber** [comment]
Ok. I'd recommend reaching out to whomever manages your server and ask them to compile PHP with iconv enabled.

**Comment by roscom** [comment]
Thank you. That's done & I'll post the results.

**Comment by gitlost** [comment]
It's unusual for `iconv()` not to be enabled but it seems like a bug in `vendor/symfony/console` and `vendor/symfony/translation` in that they require `symfony/polyfill-mbstring` and call `mb_encoding_convert()` which uses `iconv()` but don't require `symfony/polyfill-iconv`.

@roscom you should also get them to install the PHP extension `mbstring` (and preferably `intl`) if possible for performance and reliability reasons anyway.

**Comment by roscom** [comment]
iconv compiled in and both wp user list and wp user create now function correctly.
Thank you all for your help

**Comment by schlessera** [comment]
Related: https://github.com/symfony/polyfill/issues/66
