### ISSUE TITLE
Cannot delete plugin

### ISSUE THREAD

**Issue by paulcanning** [wp-cli/wp-cli#4683]
I have a fresh install of WAMP, WP and WP-CLI.

I can run `wp plugin install plugin_name` but the delete command doesn't work. No output is showing in the console when i run the delete command.

I tried to remove the read-only settings on the whole WP folder, but for some reason it doesn't remove it? I'm on Window 10 64bit.

**Comment by danielbachhuber** [comment]
Hi @paulcanning,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
