### ISSUE TITLE
Global config and missing dbuser parametr

### ISSUE THREAD

**Issue by sebastianpisula** [wp-cli/wp-cli#4685]
Hi!

In location ~/.wp-cli/ I have config.yml with content:

core config:
    dbuser: root 
    dbpass: root
    extra-php: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_ENVIRONMENT', 'local' );
        #define( 'WP_REMOTE_URL', '' );

and in my project directory I have wp-cli.yml with content:

core config:
  dbprefix: arl_
  dbname: test
  extra-php: |
    define( 'WP_REMOTE_URL', '' );

when I run "wp core config" then I have error: `Error: Parameter errors:
 missing --dbuser parameter (Set the database user.)`

WP-CLI 1.4.1

**Comment by danielbachhuber** [comment]
Hi @sebastianpisula,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
