### ISSUE TITLE
Return, SSH or Path

### ISSUE THREAD

**Issue by jigsawsoul** [wp-cli/wp-cli#4686]
Hi,

I have searched high and low, but is there away to return the ssh or path from the config.yml file.
ie. `wp @site.prod --show-path`

I am trying to create a bash script to rsync the uploads folders, I would be ideal if I could get wp cli to return the path and ssh defined, into a variable which I can then access and use as needed.

Thanks

**Comment by schlessera** [comment]
Hey @jigsawsoul,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

Easiest is to hit us up in the #cli channel on the official make.wordpress.org Slack team.
