### ISSUE TITLE
WP-CLI hangs when running from user on password update

### ISSUE THREAD

**Issue by robertmylne** [wp-cli/wp-cli#4687]
When I run this as the user: `mylinuxuser` it returns the response instantly then exits.
`wp user update mywpuser --user_pass=123123`

When I run this as the user: `root` it returns the response instantly then hangs for up to 30 seconds and then exits "gives me back my #prompt".
`su mylinuxuser -c 'cd ~/public_html && wp user update mywpuser --user_pass=123123'`

The curious thing is this only happens for that one command. It does not happen for any other wp commands like wp user meta update ... etc that I have found and I have used a lot of them.

In order to avoid the 30 seconds lag I run this instead but that doesn't give me some warnings but the command is executed ok, maybe needs some tweaking

sudo -u mylinuxuser -- /usr/local/bin/wp user update mywpuser --user_pass=123123 --path=/home/mylinuxuser/public_html

PHP Warning:  fwrite() expects parameter 1 to be resource, string given in phar:///usr/local/bin/wp/php/WP_CLI/Loggers/Base.php on line 57
Content-type: text/html; charset=UTF-8

<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, string given in <b>phar:///usr/local/bin/wp/php/WP_CLI/Loggers/Base.php</b> on line <b>57</b><br />

Thank you

**Comment by schlessera** [comment]
Could you try running these commands with `--debug` to see what specific step is taking so long?

**Comment by robertmylne** [comment]
```
[root@whm ~]# su mylinuxuser -c 'cd ~/public_html && wp user update mywpuser --user_pass=123123 --debug'
Debug (bootstrap): No readable global config found (0.088s)
Debug (bootstrap): No project config found (0.088s)
Debug (bootstrap): argv: /usr/local/bin/wp user update mywpuser --user_pass=123123 --debug (0.088s)
Debug (bootstrap): ABSPATH defined: /home/mylinuxuser/public_html/ (0.088s)
Debug (bootstrap): Begin WordPress load (0.089s)
Debug (bootstrap): wp-config.php path: /home/mylinuxuser/public_html/wp-config.php (0.089s)
Debug (bootstrap): Loaded WordPress (0.265s)
Debug (bootstrap): Running command: user update (0.266s)
Notice: Undefined index: SERVER_NAME in /home/mylinuxuser/public_html/wp-includes/pluggable.php on line 330
Success: Updated user 1.
```

Then it just hangs after `Success: Updated user 1.` for around 25-30seconds

**Comment by schlessera** [comment]
@robertmylne I tried to investigate what could cause such an issue, and I don't think this has something to do with WP-CLI code. My best bet right now is that either something triggers a network request or similar in your `su`, which times out because the environment is misonfigured, or working through the credentials is somehow locking.

What you can do is to use `strace` to find out what the exact thing is that takes such a long time to complete.

**Comment by bportman** [comment]
Hello, I am seeing this same error on a CentOS linux server with cPanel running in which I have just installed the WP-CLI according to the installation instructions.  It seems to have installed correctly but when I run pretty much any command I get 

```
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, string given in <b>phar:///usr/local/bin/wp/php/WP_CLI/Loggers/Base.php</b> on line <b>61</b><br />
```

For example i am trying to run 'wp rewrite flush' to flush permalinks on a site and this error is produced and the permalinks are not flushed.

Here is my wp --info:

# wp --info
X-Powered-By: PHP/5.6.36
Content-type: text/html; charset=UTF-8

OS:	Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/opt/cpanel/ea-php56/root/usr/bin/php-cgi
PHP version:	5.6.36
php.ini used:	/opt/cpanel/ea-php56/root/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/usr/local/bin
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	1.5.1

and here is my php --version output:

# php --version
PHP 5.6.36 (cgi-fcgi) (built: May 29 2018 01:54:51)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd.

Any help would be appreciated!
