### ISSUE TITLE
Error during Compose Install: .../vendor/wp-cli/wp-cli/php/WP_CLI/AutoloadSplitter.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by jbcoder** [wp-cli/wp-cli#4690]
I have been trying to set up a new WordPress theme using [Tonik](https://labs.tonik.pl/theme/) and [Sage](https://roots.io/sage/). During both of the `create-project` commands, I run into the following error during theme creation right after `Generating autoload files`.

```sh
  [ErrorException]
  include_once(C:\www\wp-test\www\wp-content\themes\sage-test/vendor/wp-cli/wp-cli/
  php/WP_CLI/AutoloadSplitter.php): failed to open stream: No such file or director
  y
```

I have updated Composer. I have updated wp-cli. I have cleared the Composer cache. I'm not sure what to do. I know that there was a similar issue but was supposed to have been resolved last August. 

Here is my info:

```sh
λ wp --info
OS:     Windows NT 10.0 build 17074 (Windows 10) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\tools\php72\php.exe
PHP version:    7.2.2
php.ini used:   C:\tools\php72\php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       C:\www\wp-test\www\wp-content\themes
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.0
```

```sh
λ composer -V
Composer version 1.6.3 2018-01-31 16:28:17
```

Anyone have the same issue or some guidance with this? Is this a Composer issue or wp-cli issue?

**Comment by schlessera** [comment]
@jbcoder I cannot fully make sense of what you are exactly doing and need more information.

You say that the error happens during `create-project` of a theme, but at that point, you couldn't yet include the `wp-cli/wp-cli` dependency. Are you using a custom fork that you `create-project` ? If so, can you post the `composer.json` file of that fork?
