### ISSUE TITLE
Update license copyright date to 2018

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4693]
Across all repositories, the copyright date should say 2018 instead of 2017.

**Comment by kirtangajjar** [comment]
@danielbachhuber I have manually verified in all wp-cli repos. Most of them already had 2018 in license. Some had 2017, there I've sent a PR. Some did not have LICENCE. There i've opened issue in repo.

I think it's safe to close this issue now.

**Comment by danielbachhuber** [comment]
👍 Thanks @kirtangajjar
