### ISSUE TITLE
WordPress trunk is causing framework test to fail

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4694]
See screenshot:

![image](https://user-images.githubusercontent.com/36432/36389786-483451ec-1555-11e8-89df-b4cb9ef929a0.png)

Affecting #4692

**Comment by danielbachhuber** [comment]
Might be caused by https://core.trac.wordpress.org/changeset/42716/

**Comment by gitlost** [comment]
Yes! just tracked this down to this recent change https://core.trac.wordpress.org/ticket/42299 in trunk which gets around a bug in `WP_Site_Query::query()` that doesn't ignore `domain__in` when given empty arg and which will probably be properly addressed by https://core.trac.wordpress.org/ticket/42252

Have PR ready!...
