### ISSUE TITLE
Fatal error: Call to undefined function ...iconv()

### ISSUE THREAD

**Issue by holisticnetworking** [wp-cli/wp-cli#4700]
_Summary_
When attempting to search and replace in the database, issue the following command and receive the following response:
```$ php -d memory_limit=512M ~/wp-cli.phar search-replace etcohomes.holisticnetworking.net monroeathazeltine.com --dry-run
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'ReactiveChild\ReactiveChildFunctions' does not have a method 'meta_boxes' in /home/monroeathazeltin/public_html/wp-includes/class-wp-hook.php on line 286
Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///home/monroeathazeltin/wp-cli.phar/vendor/symfony/polyfill-mbstring/Mbstring.php on line 534 
```

PHP version: PHP 7.0.27

```
$ php --ri iconv

iconv

iconv support => enabled
iconv implementation => glibc
iconv library version => 2.12

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value
```

**Comment by danielbachhuber** [comment]
See https://github.com/wp-cli/wp-cli/issues/4682#issuecomment-365442507

**Comment by gitlost** [comment]
Weird though in this case if `iconv()` is enabled, hard to make sense of it...

**Comment by schlessera** [comment]
Related: https://github.com/symfony/polyfill/issues/66

**Comment by holisticnetworking** [comment]
Right. Iconv is enabled per the data I provided. Both links shared here presuppose that it isn't installed?

**Comment by gitlost** [comment]
@holisticnetworking would it be possible for you to install the PHP extension `xdebug` so that a stack backtrace is generated on the error in order to debug further what's happening here?

**Comment by holisticnetworking** [comment]
@gitlost I've got xdebug installed. But can you give me a little insight as to what you want to see?

Sorry, but I've only ever used xdebug with PHPStorm locally, and even that, not terribly successfully...

**Comment by gitlost** [comment]
Just wanted to see what was calling `mb_strwidth()` to cause the error you're getting at [Mbstring.php#L534](https://github.com/symfony/polyfill/blob/v1.6.0/src/Mbstring/Mbstring.php#L534). With `xdebug` installed, should get a `Stack trace` which will show what's calling it. Only need to run WP-CLI with it enabled on the command line...

(May not give much more info, to be honest, but may build a PHP with `iconv` disabled if have further clues...)

**Comment by gitlost** [comment]
@holisticnetworking if you could post the output of `wp cli info` it'd be useful as well ta...

**Comment by gitlost** [comment]
Hmm, just noticed you said you've got xdebug already installed! Could you do `php --info | grep xdebug` to be sure?!

**Comment by gitlost** [comment]
Okay reproduced the error message with a PHP with `iconv()` disabled (and xdebug installed):
```
Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///home/mburke/bin/wp/vendor/symfony/polyfill-mbstring/Mbstring.php:534
Stack trace:
#0 phar:///home/mburke/bin/wp/vendor/symfony/polyfill-mbstring/bootstrap.php(46): Symfony\Polyfill\Mbstring\Mbstring::mb_strwidth('Table', 'ASCII')
#1 phar:///home/mburke/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/cli.php(345): mb_strwidth('Table', 'ASCII')
#2 phar:///home/mburke/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/Colors.php(200): cli\strwidth('Table', 'ASCII')
#3 phar:///home/mburke/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/table/Ascii.php(138): cli\Colors::width('Table', false, 'ASCII')
#4 phar:///home/mburke/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/Table.php(146): cli\table\Ascii->row(Array)
#5 phar:///home/mburke/bin/wp/vendor/wp-cli/php-cli-tools/lib/cli/Table.php(125): cli\Table->getDisplayLines()
#6 phar:///home/mburke/bin/wp/vendor/wp-cli/search-replace-command/src/Search_Replace_Command.php(376): cli\Table->display()
#7 [i in phar:///home/mburke/bin/wp/vendor/symfony/polyfill-mbstring/Mbstring.php on line 534
```
so I think the PHP you're using must have `iconv()` disabled, despite the results of `php --ri iconv` posted.

Given that according to

> Related: symfony/polyfill#66

not including the iconv polyfill is deliberate Symfony policy, maybe adding a check to WP-CLI to warn if both `iconv` and the `mbstring` aren't available is something to be considered, to avoid this user experience...

(May also gird myself up to raise an issue/PR about this at Symfony as it's poor behavior really...)

**Comment by holisticnetworking** [comment]
I'm not sure what the problem is or was: I've had mbstring installed
forever and certainly installed all the dependencies. However, after
installing xdebug and reloading the server, now everything's fine.

Call it gremlins. But I guess I'm ok.

Thanks for the help, everybody!

Thomas J Belknap
Senior Web Developer
585.305.1619
http://holisticnetworking.net
<https://mailtrack.io/trace/link/abb5508045d177a63c5d69231d66fd940472a506?url=http%3A%2F%2Fholisticnetworking.net&userId=1948639&signature=d36b12d5ffc25b6b>
