### ISSUE TITLE
missing cacert.pem

### ISSUE THREAD

**Issue by swiffer** [wp-cli/wp-cli#4703]
Running WP-CLI 1.5.0 I cannot install new commands via

wp package list / install because of:

```bash
failed to open stream: phar error: "vendor/composer/ca-bundle/res/cacert.pem" is not a file in phar
```

(Running on PHP 7.2.2 / Win 10 64bit / Cygwin Bash)

**Comment by gitlost** [comment]
Thanks @swiffer. Could you try doing
```
export SSL_CERT_FILE=phar://wp-cli.phar/vendor/rmccue/requests/library/Requests/Transport/cacert.pem
```
and see if it fixes it? If so will reopen in `package-command` as that might be the easiest workaround.

The list of things that Composer tries can be seen here [CaBundle.php#L64](https://github.com/composer/ca-bundle/blob/master/src/CaBundle.php#L64).

**Comment by swiffer** [comment]
Yes, this fixed the issue!

**Comment by gitlost** [comment]
Thanks for the feedback @swiffer , will close this in favor of https://github.com/wp-cli/package-command/issues/72

**Comment by florianbrinkmann** [comment]
I had the same problem on Windows. Using `set` instead of `export` fixed it there (just for reference, if some Windows user has the same problem and finds this issue before the new WP-CLI version with the fix gets published :)):

```
set SSL_CERT_FILE=phar://wp-cli.phar/vendor/rmccue/requests/library/Requests/Transport/cacert.pem
```
