### ISSUE TITLE
wp media regenerate --yes --only-missing stops running

### ISSUE THREAD

**Issue by mister-cairns** [wp-cli/wp-cli#4705]
I have a WordPress media library of 80k images. A number of older images need to be resized so I'm running wp media regenerate --yes --only-missing which seems to run fine. When it reaches a file that needs regenerating, it does it, and then immediately stops and returns to the command line:

<img width="571" alt="screenshot 2018-02-27 12 57 38" src="https://user-images.githubusercontent.com/1581854/36708435-1ea19d1c-1bc7-11e8-953f-1e2934768f07.png">

No errors are shown. It's running on a Linux/Serverpilot setup.

Any advice would be greatly appreciated.

**Comment by mister-cairns** [comment]
Looks like it was a memory issue. I increased the memory limit in wp-config.php and it's running.

**Comment by gitlost** [comment]
Thanks for the report anyway @mister-cairns , we're very interested in improving memory usage in WP-CLI  so if you have the time to post some more info it would be appreciated:

- What did you have to set the memory limit to?
- There should have been a PHP error message in your `error_log`. If so, could you post this please?

**Comment by mister-cairns** [comment]
No error message.
I upped the memory limit to 1024MB as I was churning through 88k media files.

On Fri, Mar 2, 2018 at 3:58 AM, gitlost <notifications@github.com> wrote:
Thanks for the report anyway @mister-cairns [https://github.com/mister-cairns] , we're very interested in improving memory usage in WP-CLI so if you have the time to post some more info it would be appreciated:

 * What did you have to set the memory limit to?
 * There should have been a PHP error message in your error_log . If so, could you post this please?
