### ISSUE TITLE
Changing admin_email option sends an email

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#4713]
Is there a way to stop WP from sending an email when admin_email option is updated?

`wp option update admin_email 'email@example.com'`

it would be good to be able to pass --skip-email option.
`wp option update admin_email 'email@example.com' --skip-email`

Error: Parameter errors:
 unknown --skip-email parameter

```
OS:     Linux 4.14.12-x86_64-linode92 #1 SMP Fri Jan 5 15:34:44 UTC 2018 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.25-0ubuntu0.16.04.1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/vhosts/example/users/6/6/gou66/sites/slavi-2018-02-28-11.example.com/htdocs
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.0

```

**Comment by lordspace** [comment]
I've also tried the hooks that the codex suggested for replacing the callbacks for updating the update but that still didn't stop the notification

**Comment by gitlost** [comment]
Overriding `send_site_admin_email_change_email` works for me, eg with `no_admin_email.php`:
```php
<?php

WP_CLI::add_hook( 'after_wp_load', function () {
	add_filter( 'send_site_admin_email_change_email', '__return_false' );
} );
```

`wp option update admin_email 'email@example.com --require=no_admin_email.php`

> it would be good to be able to pass --skip-email option

Might be something to consider, though it's very specific to `admin_email`.

**Comment by danielbachhuber** [comment]
Using a filter to disable the behavior seems most appropriate to me. I don't think this is a common-enough use-case to merit a flag.

**Comment by lordspace** [comment]
Thanks @gitlost for the workaround. It worked.
I will use that idea for other similar cases.
I've named the file: wp_cli_init.php

@danielbachhuber , I have an installer that does multiple things and some of them are done in background. Requiring a separate is not ideal. It's just 3-4 lines of code.

**Comment by schlessera** [comment]
Adding a `--skip-email` parameter to this command does not make much sense, as `wp option` is meant to manage all options. For all but one, the `--skip-email` flag would be useless. I don't want to start building contextual parameters like this, as that path quickly leads to a wild mixture of random, conflicted flags.

This is part of the filterable default WordPress behavior, and can thus be easily changed through the normal means that WordPress provides.

**Comment by lordspace** [comment]
FYI: @schlessera only @gitlost's suggestion worked in the context of wp-cli.
