### ISSUE TITLE
Cannot create post with latin characters in title

### ISSUE THREAD

**Issue by diegomagikal** [wp-cli/wp-cli#4714]
**Environment:**  
Windows7, Wamp, WP-CLI, 1.5

**Summary:**
Cannot create post with latin characters in post title

**Command to reproduce the bug:**
`wp post create --post_type=page --post_status=publish --post_title="Perícias Contábeis"`
or
`wp post create --post_type=page --post_status=publish --post_title="Atuação"`

**Actual Results:**
`Error: N├úo foi poss├¡vel inserir o post no banco de dados`

If I remove the characters "í", "á", "ç" and "ã" (Portuguese), the post is saved.
`wp post create --post_type=page --post_status=publish --post_title="Pericias Contabeis"`
Result:
`Success: Created post 56`

**Comment by gitlost** [comment]
Thanks for the report @diegomagikal . Using UTF-8 in PHP arguments doesn't work on Windows for PHP <= 7.0, however it will work for PHP >= 7.1, as it was fixed as part of [Support for long and UTF-8 path](http://php.net/manual/en/migration71.windows-support.php). A workaround for PHP <= 7.0 is to use the `--prompt` option:
```bash
echo "Perícias Contábeis" | wp post create --post_type=page --post_status=publish --prompt=post_title
```

This issue should probably be added to https://make.wordpress.org/cli/handbook/common-issues/

**Comment by diegomagikal** [comment]
Thanks, I updated my environment to php 7.2.30 and it works fine.
