### ISSUE TITLE
Remove composer.lock from git.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/wp-cli#4717]
For discussion.

Having `composer.lock` in git doesn't suit our development setup and should be removed. I can't see what value it adds, and removing it would for instance avoid the need to update Composer dependencies via the make-coffee bot, and also be one less thing to worry about generally.

**Comment by danielbachhuber** [comment]
Previously https://github.com/wp-cli/wp-cli/pull/2280

> Applications should commit composer.lock to the repository. The ensures that future builds of old tags produce predictable results.  See the [Composer documentation on the composer.lock files](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file).

**Comment by schlessera** [comment]
The `make-coffee` bot basically ensures that our tests are run with every single new version of our dependencies.

Removing the `composer.lock` file is tempting, as it often causes frustration, but you'll only replace immediate errors and some manual fiddling with hard-to-debug random errors that get introduced without our knowledge.

**Comment by danielbachhuber** [comment]
Also worth noting `wp-make-coffee` was broken for a while (#4711). This is why our dependencies weren't auto-updated.
