### ISSUE TITLE
Please make wp config create never-dependant on existing datase

### ISSUE THREAD

**Issue by benqzq** [wp-cli/wp-cli#4720]
From Unix and Linux stackexhcange:

I use Ubuntu 16.04 with Bash and I tried to run the following command set to automatically create a WordPress `wp-config.php` file with the WordPress Bash extension [WP-CLI][1]. Yet I'm having some problem I miss (Bash related?).

    loh="127.0.0.1"
    drt="/var/www/html"
    domain="example-xyz.com"
    dbuserp_1="example-xyz.password"
    
    rm -rf "$drt/$domain"/ 2>/dev/null
    wp core download --path="$drt/$domain" --allow-root

    wpConfig() {
    	rm -rf "$drt/$domain"/ 2>/dev/null
    	wp core download --path="$drt/$domain" --allow-root
    	wp config create \
    	--path=${drt}/${domain} \
    	--dbname=${domain} \
    	--dbuser=${domain} \
    	--dbpass=${dbuserp_1} \
    	--dbhost=${loh} \
    	--allow-root
    }
    wpConfig

I double checked that the DB user password I use is correct.

And yet, I get this error:

> ERROR 1045 (28000): Access denied for user 'example-xyz.com'@'localhost' (using password: YES)

Changing all ${x} to "$x" changed nothing.

I fail to understand why I get the above error (what does it have to do with MySQL itself, as this error seem MySQL related).

  [1]: https://wp-cli.org/

---

## Please make wp config create never-dependant on existing datase

The above problem is cuased due to lack of these data in the (MySQL) database.

I think that WP-CLI **SHOULD NOT** necess the user to have the data to create the conf file.It should be a matter of choice for the user to choose if to create the `wp-config.php` file before or after creating a DB stack.

I humbly suggest the WP-CLI developers (I'm not a PHP developer) to change it so that `wp config create` will become totally independent in the database; the current dependence is redundant for creating a `wp-config.php` from the sample, as one could do it with a non WP-CLI Bash script.

**Comment by danielbachhuber** [comment]
Hi @benqzq,

You can include `--skip-check` to avoid checking the database when creating a `wp-config.php` file.
