### ISSUE TITLE
Add support for comma delimited output

### ISSUE THREAD

**Issue by grappler** [wp-cli/wp-cli#4721]
I was trying to get a list of post ids for a certain group of post types.

The problem was that that I was getting an error `Error: Too many positional arguments:` for the following command: `wp post list --format=ids --post_type=$(wp post-type list --capability_type=post --field=name)`

The reason is that the output of `wp post-type list --capability_type=post --field=name` is as follows:
```
post
attachment
revision
```

The format needed for `--post_type=` is `post,attachment,revision`.

I expect the patch would be added to `WP_CLI::print_value()`.

Would a comma delimited format make sense?

**Comment by danielbachhuber** [comment]
Hey @grappler,

Thanks for the suggestion. `tr "\n" ","` is a reasonable alternative for your case:

```
$ wp post-type list --capability_type=post --field=name | tr "\n" ","
post,attachment,revision,nav_menu_item,custom_css,oembed_cache,wp_block,
```

All together, this would be:

```
wp post list --format=ids --post_type=$(wp post-type list --capability_type=post --field=name | tr "\n" ",")
```

Given there's a reasonable alternative, I think it'd be best to use `tr` instead of introducing new behavior for WP-CLI.

**Comment by theMikeD** [comment]
```
[mike@macster: /glwc/] $ wp term update countrytax $(wp term list countrytax --format=ids) --description="test"
Error: Too many positional arguments: 61 11 69 80 67 12 42 6 4 68 9 8 13 58 60 7 14 63 5
```

This is the same issue is it not? I think adding a CSV option would be quite helpful unless I'm missing something. The tr thing is fine but a csv option would def. add value.
