### ISSUE TITLE
trying to use .phar file

### ISSUE THREAD

**Issue by nya1998** [wp-cli/wp-cli#4725]
hello, i want try the php cli. but when i test .phar file i got this error
PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in phar:///usr/local/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php:637
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php(729): Mustache_Engine->getTemplateClassName('{{#is_subcomman...')
#1 phar:///usr/local/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php(657): Mustache_Engine->loadSource('{{#is_subcomman...')
#2 phar:///usr/local/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php(236): Mustache_Engine->loadTemplate('{{#is_subcomman...')
#3 phar:///usr/local/bin/wp/php/utils.php(485): Mustache_Engine->render('{{#is_subcomman...', Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CompositeCommand.php(304): WP_CLI\Utils\mustache_render('phar://wp-cli.p...', Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CompositeCommand.php(130): WP_CLI\Dispatcher\CompositeCommand->get_global_params()
#6 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(302): WP_CLI\Dispatcher\Comp in phar:///usr/local/bin/wp/vendor/mustache/mustache/src/Mustache/Engine.php on line 637

**Comment by danielbachhuber** [comment]
Hi @nya1998,

It appears the PHP JSON extension is missing in your system. You, or your system administrator, will need to re-compile PHP with the JSON extension included.
