### ISSUE TITLE
Connection issue with Local by Flywheel

### ISSUE THREAD

**Issue by alzearafat** [wp-cli/wp-cli#4728]
Hi there,

I have an issue with local by flywheel. The issue is this one : https://make.wordpress.org/cli/handbook/common-issues/#error-cant-connect-to-the-database

I'm trying the suggested steps (I also using MAMP by the way), but still no luck. This is the output of `wp --info` : 

```
Zea-MacBook-Pro:~ zea$ wp --info
OS:     Darwin 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    7.1.7
php.ini used:
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/zea
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.0
```

This is my flywheel setup : 

![local by flywheel](http://i68.tinypic.com/91cndj.png "flywheel")

Any help would be greatly appreciated!
Thanks!

**Comment by schlessera** [comment]
@alzearafat :
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

I'm closing this now, as it is very likely only a misconfiguration of your local development setup.
