### ISSUE TITLE
Alternate way to install packages

### ISSUE THREAD

**Issue by rahilwazir** [wp-cli/wp-cli#4729]
So the server I'm trying to install a wp package has `allow_url_fopen=0` thus I get the following error

```bash
Error: The "https://wp-cli.org/package-index/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0
failed to open stream: no suitable wrapper could be found)
```

I don't have access to the primary `php.ini` file so I've created a user specific `php.ini` also enabling the option `allow_url_fopen=1`

```bash
> export WP_CLI_PHP="/usr/local/bin/php -c /path/to/php.ini"
> echo $WP_CLI_PHP
/usr/local/bin/php -c /path/to/php.ini
```

Re-login to the server and tried installing the package again, shows the same initial error. Is there any workaround or I am doing something wrong?

**WP-CLI:** `1.5.0`

**Comment by danielbachhuber** [comment]
Hi @rahilwazir,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
