### ISSUE TITLE
WP_CLI::confirm to STDERR

### ISSUE THREAD

**Issue by joshbetz** [wp-cli/wp-cli#4732]
For scripts that write to `STDOUT`, it would be useful for `WP_CLI::confirm` to optionally write to `STDERR` instead of `STDOUT`. I often redirect output to a file in which case, the confirmation prompt is also redirected to the file. Writing to stderr would fix this.

**Comment by danielbachhuber** [comment]
Closing because of https://github.com/wp-cli/wp-cli/pull/4733#issuecomment-381363178
