### ISSUE TITLE
wp-cli only shows available theme update after looking at update page in /wp-admin 

### ISSUE THREAD

**Issue by gerardjp** [wp-cli/wp-cli#4744]
**Issue**
After some research chasing a bug related to theme updates in our WP management platform I discovered the above issue.

In short: the update only shows up on the commandline after I watched it via the `/wp-admin/update-core.php` page first.

I know there's an update for enfold. The correct license/api key is in place to detect and access the update (information) from vendor.

**Steps**
- The update does *not* show on CLI
- Login and go to wp-admin page with updates
- Run command again and the update magically appears on CLI

I gather there's something triggered related to the updates page and/or some transient data refreshed, but not sure where to look for this. All help welcome, any input can be provided.

**Context**

Before:
```
$ wp --allow-root theme list
+-----------------+----------+--------+---------+
| name            | status   | update | version |
+-----------------+----------+--------+---------+
| enfold          | active   | none   | 4.2.2   |
| twentyfifteen   | inactive | none   | 1.9     |
| twentyseventeen | inactive | none   | 1.4     |
| twentysixteen   | inactive | none   | 1.4     |
+-----------------+----------+--------+---------+
```

Immediately after:
```
$ wp --allow-root theme list
+-----------------+----------+-----------+---------+
| name            | status   | update    | version |
+-----------------+----------+-----------+---------+
| enfold          | active   | available | 4.2.2   |
| twentyfifteen   | inactive | none      | 1.9     |
| twentyseventeen | inactive | none      | 1.4     |
| twentysixteen   | inactive | none      | 1.4     |
+-----------------+----------+-----------+---------+
```

Details
```
$ php /usr/bin/wp --info
OS:	Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.24
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/www.blueblox.nl
WP-CLI packages dir:
WP-CLI global config:	/root/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	1.5.0
```

WP version: 4.9.4

From WP update page:
```
Enfold
You have version 4.2.2 installed. Update to 4.2.6.
```

**Comment by danielbachhuber** [comment]
Hi @gerardjp,

Sorry for the delay. GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. This issue seems specific to your theme update mechanism. For support options, please review http://wp-cli.org/#support
