### ISSUE TITLE
wp post list pagination

### ISSUE THREAD

**Issue by romanvbabenko** [wp-cli/wp-cli#4746]
```wp post list``` is being killed by OOM when a site got lots of posts.
It'd be great to add pagination to reduce the number of posts fetched at once.

**Comment by danielbachhuber** [comment]
Hi @romanvbabenko,

`wp post list` supports `WP_Query`'s pagination arguments: `posts_per_page` and `paged. You're welcome to use those as you wish.

WP-CLI may handle large queries automatically in the future. For more information, see https://github.com/wp-cli/ideas/issues/91
