### ISSUE TITLE
Improve display of "Good First Issues" list

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4747]
The list of issues labeled "good-first-issue" that we show at https://make.wordpress.org/cli/good-first-issues/ could be improved:

* As the shortcode filters on a specific label, that specific label should not be displayed in the label tags. Every single issue in that list is bound to have it.
* Instead of having the repository slug after every issue title, we should group by repository instead. The labels could then be displayed after the title, instead of the repository slug.

Regarding the grouping, this would turn this:
```
This is an issue title (wp-cli/wp-cli)
[label1] [label2]

This is another issue title (wp-cli/example-command)
[label3] [label4]

Yet another issue title (wp-cli/wp-cli)
[label5] [label6]
```
into this:
```
wp-cli/wp-cli:
- This is an issue title [label1] [label2]
- Yet another issue title [label5] [label6]

wp-cli/example-command:
- This is another issue title [label3] [label4]
```

**Comment by schlessera** [comment]
Another small detail: the `wp-cli/wp-cli` group should come first, with the rest sorted alphabetically.

**Comment by danielbachhuber** [comment]
This is now live:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/36432/40841023-d723c8c6-655d-11e8-8a89-29865ecc3094.png">

https://make.wordpress.org/cli/good-first-issues/

**Comment by schlessera** [comment]
Thanks, @danielbachhuber, it's looking great!
