### ISSUE TITLE
wp post meta missing options

### ISSUE THREAD

**Issue by apb1963** [wp-cli/wp-cli#4760]
The following command needs an option that eliminates the ASCII graphics, such as a --porcelain option, and/or --field option (singular). Only --fields (plural) is valid and brings the graphics with it. --format=ids is also missing/broken.

In short, in the following example, I need the output of the wp post meta list to be "168", without quotes - nothing more, nothing less.
```

wp post meta list 203 --keys=_thumbnail_id --field=meta_value
Error: Parameter errors:
 unknown --field parameter
Did you mean '--fields'?

wp post meta list 203 --keys=_thumbnail_id --fields=meta_value
+------------+
| meta_value |
+------------+
| 168        |
+------------+

wp post meta list 203 --keys=_thumbnail_id --fields=meta_value --format=ids
PHP Catchable fatal error:  Object of class stdClass could not be converted to string in phar:///data/local/bin/wp/php/WP_CLI/Formatter.php on line 139
Catchable fatal error: Object of class stdClass could not be converted to string in phar:///data/local/bin/wp/php/WP_CLI/Formatter.php on line 139


```

**Comment by schlessera** [comment]
@apb1963 `wp post meta list` is for extracting tables of information.

To get the single value output you want above, you can use the following command:
```
wp post meta get 203 _thumbnail_id
```
