### ISSUE TITLE
`--prompt` should skip flags that have been included in the command

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#4762]
When running a command with the `--prompt` flag, any other flags that are passed to the command (either positional or associative) should be skipped in the prompt.

Example:

`wp core install --admin_email=email@example.com --prompt`

This command should skip the `admin_email` field when prompting the user for input.

**Comment by schlessera** [comment]
Oh yes, absolutely. I wonder though whether that was not the original behavior and we had a regression at some point...?

Either way, the expected behavior would be to only prompt for values that were not yet provided.

**Comment by szepeviktor** [comment]
> Either way, the expected behavior would be to only prompt for values that were not yet provided.

👍
