### ISSUE TITLE
wp-cli hangs on Resolving dependencies through SAT

### ISSUE THREAD

**Issue by 3pepe3** [wp-cli/wp-cli#4763]
I'm trying to install a package from github but wp package install hangs on Resolving dependencies through SAT... This happens with all packages that I tried to install.
Example:
```
$ wp package install git@github.com:sebastiaandegeus/wp-cli-salts-command.git
Installing package sebastiaandegeus/wp-cli-salts-command (dev-master)
Updating /home/webid4/.wp-cli/packages/composer.json to require the package...
Registering git@github.com:sebastiaandegeus/wp-cli-salts-command.git as a VCS repository...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
```
wp --info
```
OS:     Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.29-1~dotdeb+8.1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/projects/dev/pms.example.pro/htdocs
WP-CLI packages dir:    /home/webid4/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.0
```
Composer version : Composer version 1.2.2 2016-11-03 17:43:15

**Comment by danielbachhuber** [comment]
Hi @3pepe3:

> I'm trying to install a package from github but wp package install hangs on Resolving dependencies through SAT... This happens with all packages that I tried to install.

Can you try deleting your `/home/webid4/.wp-cli/packages/` directory and installing fresh? What debugging have you done to track down where it's a specific package causing the problem?
