### ISSUE TITLE
Tab completions for tcsh

### ISSUE THREAD

**Issue by catchmyfame** [wp-cli/wp-cli#4767]
Can someone convert the tab completions script for use with tcsh?

**Comment by schlessera** [comment]
@catchmyfame This issue tracker is for bug reports and for working on the WP-CLI framework, not for making feature requests.

If you want to introduce a feature request and think other people might be interested in this as well, please open an issue (with more details) in https://github.com/wp-cli/ideas/issues.

If you need this functionality now, your best bet is to work on a pull-request yourself. Please see https://make.wordpress.org/cli/handbook/contributing/#creating-a-pull-request for more information about how to do this.

**Comment by catchmyfame** [comment]
Thanks. I'll add it as a feature request as I know zip about tcsh scripting and how it differs from bash scripting.
