### ISSUE TITLE
provide assoc_args via the WP_CLI::Runner

### ISSUE THREAD

**Issue by drzraf** [wp-cli/wp-cli#4769]
wp-cli commands may use the filter/action hook system.
These filter and action may exist well below and after the initial `WP_CLI_Command` class' method and would not be provided the wp-cli command lines arguments.
We could say that each command would provide this information as filter/action additional arguments.
But that'd be even better if wp-cli provided this information itself a bit like [drush_get_option](http://api.drush.org/api/drush/includes%21context.inc/function/drush_get_option/8.0.x) does.
Currently it's accessible via the (private) property `assoc_args`. So basically calling  `WP_CLI::get_runner()->assoc_args` but it's not in the public API.

**Comment by danielbachhuber** [comment]
Hi @drzraf,

Even though `WP_CLI::get_runner()->assoc_args` is marked private, its values are exposed through a magic getter function. You can access the arguments directly as `WP_CLI::get_runner()->assoc_args`.
