### ISSUE TITLE
Permission Issue (wp-admin redirect)

### ISSUE THREAD

**Issue by tareq1988** [wp-cli/wp-cli#477]
I have a plugin which does admin area blocking based on user roles. The code is as follows (runs on `admin_init`):

``` php
function block_admin_access() {
    global $pagenow;

    $access_level = wpuf_get_option( 'admin_access', 'wpuf_general', 'read' );
    $valid_pages = array('admin-ajax.php', 'async-upload.php', 'media-upload.php');

    if ( !current_user_can( $access_level ) && !in_array( $pagenow, $valid_pages ) ) {
        wp_die( __( 'Access Denied. Your site administrator has blocked your access to the WordPress back-office.', 'wpuf' ) );
    }
}
```

It was working fine when I was using WordPress 3.5.1. Recently upgraded to 3.6-beta3 and wp-cli gave some error. So I thought to upgrade to the latest dev(github) version. Now when I run `wp` command, I get **Access Denied. Your site administrator has blocked your access to the WordPress back-office.** message which is coming from my plugin, which I think it shouldn't. So I can't run any command while the code is active.

**Comment by quinncomendant** [comment]
I notice that *Warning: Some code is trying to do a URL redirect* will also occur if `WP_HOME` or `WP_SITEURL` is empty (e.g., because it's trying to get it from `HTTP_HOST` which isn't available on the CLI).
