### ISSUE TITLE
mysql 8?

### ISSUE THREAD

**Issue by Onyx808** [wp-cli/wp-cli#4777]
anyone having issues with mysql 8?

Im getting `Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.`

however wp-config.php is correct and mysql is running with the correct db in it...

**Comment by schlessera** [comment]
WP-CLI lets WordPress itself handle the database connection. If your WordPress site is correctly set up (and doesn't require webserver-specific details to deduce the database server) then WP-CLI will work as well.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by Onyx808** [comment]
it was actually a new feature on mysql 8 "Caching SHA-2 Pluggable Authentication"
