### ISSUE TITLE
Specify user type when logging in?

### ISSUE THREAD

**Issue by robertmylne** [wp-cli/wp-cli#4780]
If I make the username=9 and then I run the update command how do I specify I am referring to the login and not the id of the user?

At the moment it assumes it is the ID which is not always true.

**Comment by schlessera** [comment]
I don't think it is that hard to solve, actually.

Assuming that we want to avoid adding further global parameters like `--user-id`, `--user-email`, ... the best approach I can think of is to allow for JSON-encoded values that make the type unambiguous:

```
--user={"id":9}
```
vs
```
--user={"login":"9"}
```
This will not change anything for regular uses but allows for more unambiguous usage in advanced cases.

**Comment by danielbachhuber** [comment]
> I don't think it is that hard to solve, actually.

I meant more from the perspective of: even though it technically _can_ be solved, _should_ it be solved?

**Comment by schlessera** [comment]
There's many places around the codebase where the arguments are not as expressive as some users might need them to be. This is one of these cases.

I don't see this as a priority or something I will work on myself in the near future.

But I'd like to keep the issue open for now and maybe at a later point do a push for improving the consistency of how arguments are handled. Another ticket in the same vein is https://github.com/wp-cli/wp-cli/issues/4616.

Every time WP-CLI is less expressive than regular WordPress usage, I feel we're failing with our UNIX philosophy.

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/wp-cli/issues/5706
