### ISSUE TITLE
WP CLI not populating Database on install

### ISSUE THREAD

**Issue by Stefan-Adam** [wp-cli/wp-cli#4782]
Summary:
After running wp core install on a fresh WP install (Downloaded with wp core download, config file generated with wp core config), then browsing the database in phpMyAdmin, I find that the new WP installs database contains blank tables for everything except the wp_options table. The server is CLOUDLINUX 7.4 standard. The wp_options table is correctly populated with the details from the command.

Steps to reproduce:

1. Run wp core download
2. Run wp core config
3. Run wp core install
4. Observe database via phpMyAdmin

Environment:

# What is your system?

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CloudLinux
Description:	CloudLinux release 7.4 (Georgy Grechko) 
Release:	7.4
Codename:	GeorgyGrechko

uname -a
Linux longevitygraphics.localdomain 3.10.0-714.10.2.lve1.5.12.el7.x86_64 #1 SMP Fri Feb 2 00:27:48 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

# Which version of PHP are you using?
which -a php

PHP 5.6.35 (cli) (built: Apr  7 2018 08:55:55) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

# Are you running suhosin? If so, make sure you've added `suhosin.executor.include.whitelist = phar` to your php.ini
php -m | grep -i suhosin
Not running suhosin (blank response)

# Can you share the results of which wp ?
which -a wp

/usr/local/bin/wp

stat $(which wp)

  File: ‘/usr/local/bin/wp’
  Size: 4561899   	Blocks: 8912       IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 4299510286  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-04-26 17:00:40.379523669 -0400
Modify: 2018-04-18 14:32:14.301413059 -0400
Change: 2018-04-18 14:32:53.085297558 -0400
 Birth: -

# Are you running any packages? If one is causing a problem, you can use `--skip-packages` to skip loading them
wp package list

No Packages (Blank Response)

Severity – High

Expected Results: WP Core install should populate the database properly for use.

Actual Results: Database has blank tables for everything except wp_options

Workaround: Manually insert tables afterwards.

**Comment by schlessera** [comment]
Hi @Stefan-Adam and thanks for the detailed bug report.

WP-CLI uses the WordPress function `[wp_install](https://developer.wordpress.org/reference/functions/wp_install/)` to do the actual installation process.

My first assumption is that this has to do either with your current environment or with an upstream bug in WordPress Core. WP-CLI basically just passes on arguments to the WordPress function, and if the arguments would be off, we'd see issues everywhere.

I'm marking this as unconfirmed for now, but I keep the issue open for a while in case you can find additional insights into this particular problem or other people can confirm the problem.

**Comment by daniel-banciulea** [comment]
I have the exact same issue as described above. Nothing has changed in my environment which used to work just fine a couple of months ago when I last tested.

**Comment by schlessera** [comment]
@Stefan-Adam : Thanks for the update.

I'm closing this issue now, but please post any further updates in here if you gather more data or actually solve the problem, so that people with the same issue in the future will find help.
