### ISSUE TITLE
Executing --info argument as root results in inconsistent messaging

### ISSUE THREAD

**Issue by cpanelchip** [wp-cli/wp-cli#4788]
**Summary:**

When executing wp-cli --info as root, results are inconsistent with other commands run as root, not producing the appropriate warning.

**Steps to Reproduce:**

1. Execute --info argument as root user:  ` wp --info`
2. Observe the following result:
```
# wp --info
--
Content-type: text/html; charset=UTF-8 
#
```

3. Execute --info argument as root user with --allow-root argument: `wp --info --allow-root`
```
# wp --info --allow-root
--
Content-type: text/html; charset=UTF-8
 
PHP binary:	/opt/cpanel/ea-php56/root/usr/bin/php-cgi
PHP version:	5.6.35
php.ini used:	/opt/cpanel/ea-php56/root/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0

#
```

**Workaround:**
None known

**Comment by danielbachhuber** [comment]
Hi @cpanelchip,

WP-CLI blocks script execution as root unless `--allow-root` is provided. Normally, you'd see a big scary error message:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36432/39761954-44a0729c-528e-11e8-845a-325d968c0843.png">

In your case, it appears your `STDERR` isn't being piped to display.
