### ISSUE TITLE
Travis builds fail with a missing `scaffold package` command

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4791]
Inside of the Travis builds, the tests that touch the `package` command currently fail, because that command does somehow fail to register.

I couldn't get this to reproduce on my local system so far.

Here are the observations I could make:
- Failure in the `wp-cli/wp-cli` package: https://travis-ci.org/wp-cli/wp-cli/jobs/376280873#L631
- Tests in `wp-cli/package-command` all pass: https://travis-ci.org/wp-cli/package-command
- Fresh clone and setup on local (Mac OS X with PHP 7.1) has all tests passing

I'll record any additional details as I find out more, which has proven to be  surprisingly difficult in this instance.

**Comment by schlessera** [comment]
* The problem seems to be limited to the 5.3 branch: https://travis-ci.org/wp-cli/wp-cli/builds/377594092

This might indicate that it is caused by either dependency versions that are pulled in for 5.3, or by the custom Travis setup that we need to use for 5.3, as the default Travis image does not support 5.3 anymore.

It might just be one more hint that it is time to get rid of PHP 5.3 support...

**Comment by szepeviktor** [comment]
Could it be the cause?

```
# wp --allow-root package install wp-cli/scaffold-package-command
Error: The "https://wp-cli.org/package-index/packages.json" file could not be downloaded: Peer certificate CN=`ssl391970.cloudflaressl.com' did not match expected CN=`wp-cli.org'
Failed to enable crypto
failed to open stream: operation failed
```

**Comment by szepeviktor** [comment]
But SNi is enabled

```
$ php -r 'echo OPENSSL_TLSEXT_SERVER_NAME;'
1
```

http://php.net/manual/en/openssl.constsni.php

**Comment by schlessera** [comment]
Unfortunately, dropping PHP 5.3 did not solve the issue. This has at least produced new data, though:

- It breaks on PHP 5.4 too.
- It is unrelated to the special, legacy PHP-5.3-enabled distro that Travis uses.

**Comment by schlessera** [comment]
Finally figured out the reason. WP-CLI uses the `cacert.pem` for its SSL verification, but for Composer in the `package-command` code, it does not extract that file from the Phar first and directly points to the file from within the Phar filetree. Composer fails to properly read the file from inside the Phar.

Resolved in https://github.com/wp-cli/package-command/issues/82
