### ISSUE TITLE
Can't change editor

### ISSUE THREAD

**Issue by mountwebs** [wp-cli/wp-cli#4809]
Hi,

I want to change editor for editing posts in terminal, but I can't seem to do this. I have set "export EDITOR="/usr/bin/nano" in .zshrc (and in .bashrc/.bash_profile), but I end up with vim no matter what I do. I don't know if this is an wp-cli issue, but I can't find a solution anywhere else.

Ps. I'm on a mac.

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

TL,DR; Head over to Slack #cli channel, and we can discuss this.

**Comment by guaka** [comment]
I have a very similar issue. My EDITOR is set to `emacs` yet `wp post edit 1` and `EDITOR=emacs wp post edit 1` open my post in nano. There is no `nano` anywhere in my `env`.
