### ISSUE TITLE
SHA256 mismatch on Brew Install

### ISSUE THREAD

**Issue by papakay** [wp-cli/wp-cli#4816]
I was trying to install through brew and i got this error

```
Error: SHA256 mismatch
Expected: c1114450e647ca0c72afcbb6d02b577a55ec9915a510399579626c960d5dd2d2
Actual: 0cc7a95e68a2ef02fc423614806c29a8e76e4ac8c9b3e67d6673635d6eaea871
Archive: /Users/PAPAKAY/Library/Caches/Homebrew/wp-cli-1.5.1.phar
To retry an incomplete download, remove the file above.
```

Please can you kindly help look into this. Thank you.

**Comment by mistydemeo** [comment]
There's some more discussion on the Homebrew tracker: https://github.com/Homebrew/homebrew-core/pull/28579#issuecomment-394058348

It looks like the file changed yesterday. 1.5.1 was released April 21, but the current tag now says it was released 1 day ago and is tagged at 3aac73bc4d629372531f3e15bbb67945d19b5d5a, which is only 2 days old.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/780485/40870946-678d3ecc-65e7-11e8-8a14-3872a0647832.png">

@ilovezfs has a copy of the original 1.5.1 .phar, and was able to diff the contents. They're very different. https://gist.github.com/ilovezfs/2095a51cd8a552840aaed34bd0a074e3

**Comment by schlessera** [comment]
Thanks for the report, @papakay, and thanks for the link to Homebrew, @mistydemeo !

I commented on the Homebrew ticket. As soon as the hash is adapted on their side, the above issue should be fixed.

**Comment by schlessera** [comment]
Looking at the diff from the two Phars, I'm surprised to see these changes, though. The release was made by pulling the branch from which the original 1.5.1 was made and only changing one file.

If that process introduces so many changes to the final release, I think we need to re-check how our releases are being processed.

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/4817

**Comment by schlessera** [comment]
Homebrew sticks with the old release of v1.5.1 for now, which they provide through a backup location.
