### ISSUE TITLE
Search-replace for JSON stored objects...

### ISSUE THREAD

**Issue by raptor235** [wp-cli/wp-cli#4819]
Hey guys, could use some help with this... seems that search and replace doesn't work with JSON stored objects... urls don't get replaced... 

I've been banging my head againts trying to use regex but I've tried 20+ variations and not getting anywhere...

Any suggestions on how to replace urls stored as JSON strings in the db would be very helpful... here is an example

Wonder Plugin Carousel  stores data this way

Sequel Pro
http://www.flowpress.com/screenshots/screenshot_2018-06-07_at_2.07.26PM.png

DB Dump
http://www.flowpress.com/screenshots/screenshot_2018-06-07_at_2.10.36PM.png

I've gotten regex working with a regex tester ( http://www.flowpress.com/screenshots/screenshot_2018-06-07_at_2.13.20PM.png )  but doesn't seem like WP CLI is working with the same rules that I got to work with a regex tester... 

Any suggestions would be welcome.

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/search-replace-command/issues/45

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
