### ISSUE TITLE
Trouble upgrading from v1.2.0

### ISSUE THREAD

**Issue by schrapel** [wp-cli/wp-cli#4822]
We have a site that currently requires wp-cli via Composer v1.6.5

`"wp-cli/wp-cli"                                                 : "^1.0",`

When we try to upgrade to any version above 1.2 we get the following error.

```
Problem 1
    - Conclusion: don't install wp-cli/wp-cli v1.5.1
    - Conclusion: don't install wp-cli/wp-cli v1.5.0
    - Conclusion: don't install wp-cli/wp-cli v1.5.1
    - Installation request for wp-cli/wp-cli ^1.5 -> satisfiable by wp-cli/wp-cli[v1.5.0, v1.5.1].
    - Conclusion: don't install justinrainbow/json-schema 4.1.0
    - wp-cli/wp-cli v1.5.0 requires justinrainbow/json-schema ~5.2.5 -> satisfiable by justinrainbow/json-schema[5.2.5, 5.2.6, 5.2.7].
    - Can only install one of: justinrainbow/json-schema[5.2.5, 4.1.0].
    - Can only install one of: justinrainbow/json-schema[5.2.6, 4.1.0].
    - Can only install one of: justinrainbow/json-schema[5.2.7, 4.1.0].
    - Installation request for justinrainbow/json-schema (locked at 4.1.0) -> satisfiable by justinrainbow/json-schema[4.1.0].
```

When I traceback why the only thing locking this is wp-cli itself

```
➜  composer why justinrainbow/json-schema
composer/composer  1.3.2  requires  justinrainbow/json-schema (^1.6 || ^2.0 || ^3.0 || ^4.0)
```

```
➜  composer why composer/composer
wp-cli/wp-cli  v1.1.0  requires  composer/composer (^1.2.0)
```

```
➜  composer why wp-cli/wp-cli
schrapel/project        master  requires  wp-cli/wp-cli (^1.0)
```

**Comment by schlessera** [comment]
Hey @schrapel,

Can you post the `composer.json` file you're using (minus any sensitive data)?

**Comment by schlessera** [comment]
Note: I'm asking this because I suspect there might be some other code that pulls in either an old version of `justinrainbow/json-schema` or an old version of `wp-cli/wp-cli` (like a custom command you've built, for example).

**Comment by schrapel** [comment]
No code brings in a older version of `justinrainbow/json-schema` that is what the `composer why` command shows. 

However, found the issue. Another one of our repos had `"wp-cli/php-cli-tools": "0.11.1"` and that locked the version of `wp-cli/wp-cli` we could use. Since later version of wp-cli need `0.11.2` or higher

https://github.com/wp-cli/wp-cli/blob/master/composer.json#L58

Thanks for helping though.

**Comment by schlessera** [comment]
I'm working on heavily improving Composer support by changing how packages are structured: #4752 

Hopefully, this will resolve some of the issues people face when pulling in WP-CLI through Composer.
