### ISSUE TITLE
Readme.txt file of theme has been giving wrong date and version in the changelog.

### ISSUE THREAD

**Issue by girishpanchal0007** [wp-cli/wp-cli#4825]
I have installed the new theme using this command `wp scaffold _s test-theme --theme_name="Test Theme" --author="Me"` after installing the theme I found wrong changelog detail in the readme.txt also found the wrong versioning as compared to stable tag on the file.

The changelog date should the same date when theme installed and they changelog tag should same as the stable tag.

Check the below sceenshot.

![screenshot-jun-26-18](https://user-images.githubusercontent.com/18365991/41900541-9a311d8a-794c-11e8-8cf1-3525bfbad8a1.png)

**Comment by schlessera** [comment]
@girishpanchal0007 Thanks for the bug report!
However, for generating this file, we just post all of our available data to the Underscores API (which powers https://underscores.me/) and get a generated ZIP file in return.

You should post a bug report in the upstream Underscores.me repository instead, which you can find here: https://github.com/Automattic/underscores.me
