### ISSUE TITLE
Can set env var for custom PHP binary, but not matching php.ini

### ISSUE THREAD

**Issue by Justin-TheMitchells** [wp-cli/wp-cli#4827]
Environment:
- Windows 10 x64
- WAMPserver 3.1.3 + separate install of PHP 7.2.7 in system root
- WP-CLI v1.5.1
```λ wp --info
OS:     Windows NT 10.0 build 17134 (Windows 10) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\wamp\bin\php\php7.2.4
PHP version:    7.2.7
php.ini used:   C:\PHP7\php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       C:\wamp\www\project_dir
WP-CLI packages dir:    C:\Users\MyUser/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.1
```

Issue:
As mentioned above, I've got WAMP running but I also have a separate install of PHP 7.2.7 in my system root (C:\PHP7) and I was having issues with wp-cli using the one at system root instead of WAMP's install, so I set WP_CLI_PHP to the WAMP install's PHP and that's taking fine, but wp-cli is still using the other php.ini.
I've dug through all the SO threads and other sites I can find about customizing wp-cli's php binary to use, but I don't see anything about also setting the appropriate php.ini. Should wp-cli automatically be using the php.ini within the directory of it's set php binary? It's not happening for me and if it doesn't do this automatically, can it in a future release or at least offer an environment variable like WP_CLI_PHP_INI to be able to have it use the right ini?

At the moment, I don't _really_ need the extra PHP install so I've deleted it and just added WAMP's to my environment instead.

If I've missed the memo and it's somewhere very obvious, sorry!

**Comment by schlessera** [comment]
WP-CLI is not responsible for deciding what PHP ini file to use, that's done through the way PHP is set up in your environment. I think you should be able to override what your system does with the `PHP_INI_SCAN_DIR` environment variable.

Tools like WAMP do all sorts of magic with PHP and often make PHP work for their purposes while breaking them for the rest of the system, unfortunately.

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get further support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
