### ISSUE TITLE
Shell script `bin/wp` should avoid legacy backticks operator

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4833]
The `bin/wp` shell script uses the legacy backtick operator ( `command` ).

https://github.com/wp-cli/wp-cli/blob/3aac73bc4d629372531f3e15bbb67945d19b5d5a/bin/wp#L31

It should use the preferable `$()` notation.

See https://github.com/koalaman/shellcheck/wiki/SC2006

**Comment by wojsmol** [comment]
@schlessera I can prepare PR in few minutes if you wont.

**Comment by schlessera** [comment]
Fixed via #4841
