### ISSUE TITLE
`$WP_CLI_PHP_ARGS` should be quoted

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4835]
The `$WP_CLI_PHP_ARGS` should be put in double quotes, to avoid issues with globbing and word splitting.

https://github.com/wp-cli/wp-cli/blob/3aac73bc4d629372531f3e15bbb67945d19b5d5a/bin/wp#L45

See https://github.com/koalaman/shellcheck/wiki/SC2086

**Comment by wojsmol** [comment]
See https://github.com/wp-cli/wp-cli/issues/631 for discussion when `WP_CLI_PHP_ARGS` was added.

**Comment by CodeProKid** [comment]
fwiw, when I added this change locally, I was getting the following error: `Could not open input file:` don't know nearly enough about this to know what that means though.

**Comment by schlessera** [comment]
Looked through this again, and I think this issue was not valid. Adding quoting actually breaks here. Let's close this for now.
