### ISSUE TITLE
wp cli with custom wp-config, core and content folder

### ISSUE THREAD

**Issue by xwulfus** [wp-cli/wp-cli#4844]
I try with VCCW get wp works with custom pathes.

current files simmiliar this:

```
index.php: .. require( 'wpcore/wp-blog-header.php' );
wp load.php: <?php  require_once('wpcore/wp-load.php');
conf.php - custom config, actually moved wp-config
wpcore - original wp folder
.htaccess
```
Here is wp debug

```
vagrant@customconf:/www/customconf/public_html$ wp config get --debug
Debug (bootstrap): Using default global config: /home/vagrant/.wp-cli/config.yml (0.22s)
Debug (bootstrap): No project config found (0.225s)
Debug (bootstrap): argv: /usr/local/bin/wp config get --debug (0.225s)
Debug (bootstrap): ABSPATH defined: /www/customconf/public_html/ (0.226s)
Debug (bootstrap): Running command: config list (0.228s)
Error: Strange wp-config.php file: wp-settings.php is not loaded directly.
```
wpcore/wp-config.php:

require_once( path/to/conf.php);

All works perfectly, except wp cli

How I can enable it?

Thank you

**Comment by schlessera** [comment]
Hi @xwulfus,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by xwulfus** [comment]
Sorry, thanks for link!
