### ISSUE TITLE
WPCI get_option  [Feature Request]

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4846]
Is there any way to get meta global values when using something like:

    add_option( 'option_name', 'option_value', 'deprecated', 'yes' );
    $your_data = get_option('option_name', 'option_default_value');
    echo $your_data;

if not, could it be implemented to store and get values?

something like: 
     wp global meta add option_name value
     wp global meta get option_name

**Comment by schlessera** [comment]
@killown This functionality already exists under `wp option`: https://developer.wordpress.org/cli/commands/option/
