### ISSUE TITLE
Segmentation fault on FreeBSD 11.1 with PHP 7.2.5

### ISSUE THREAD

**Issue by hdilaver** [wp-cli/wp-cli#4847]
Hello, 

I am getting a SegFault with the following versions ;

**OS**: FreeBSD 11.1-RELEASE #0 r321309
**PHP**: PHP 7.2.5 (cli) (built: Jun  6 2018 10:02:46) ( NTS )
**WP CLI:** WP-CLI 1.5.1

**SegFault backtrace:** 
(gdb) run /usr/local/bin/wp theme install /appdata/xxxx_data/branches/v2.0.5_6.zip
Starting program: /usr/local/bin/php /usr/local/bin/wp theme install /appdata/xxxx_data/branches/v2.0.5_6.zip
warning: Lowest section in /usr/local/lib/libicudata.so.61 is .hash at 0000000000000120

Installing the theme...
Theme installed successfully.
Success: Installed 1 of 1 themes.

Program received signal SIGSEGV, Segmentation fault.
0x00000008044e9874 in ?? ()

(gdb) bt
#0  0x00000008044e9874 in ?? ()
#1  0x00007fffdfffdf40 in ?? ()
#2  0x000000080216d130 in _pthread_mutex_init_calloc_cb () from /lib/libc.so.7
#3  0x00000008044f2fe6 in ?? ()
#4  0x0000000000000000 in ?? ()

Please let me know, if you need further information to identify the issue.

Cheers

**Comment by schlessera** [comment]
At first glance I have to assume that this is caused by a bug in PHP itself (in version 7.2.5 more specifically), or a problematic build of that PHP version on your current distribution.

Are you able to test this on the same system with a different version of PHP?
