### ISSUE TITLE
Error deleting comments when only 1 exists

### ISSUE THREAD

**Issue by echodreamz** [wp-cli/wp-cli#4849]
Hello,

Having an issue automatically deleting spam comments. When there is more than 1 spam comment, the command below completes without issues. If there is only a single spam comment, the command fails stating it failed to delete comment xxxxxx.

`wp comment delete $(wp comment list --status=spam --format=ids)`

**OS:** CentOS 7.5
**PHP:** PHP 7.0.31 (cli) (built: Jul 17 2018 15:30:29) ( NTS )
**WP CLI:** WP-CLI 1.5.1

**Comment by danielbachhuber** [comment]
Hi @echodreamz,

Were you able to sort this out?

**Comment by echodreamz** [comment]
No this is still an issue.

**Comment by echodreamz** [comment]
Confirmed it still happens with build 2.0.1.

`wp comment delete $(wp-cron comment list --status=spam --format=ids)

Warning: Failed deleting comment 18921.`

**Comment by schlessera** [comment]
@echodreamz I just tested this now and cannot replicate. When I have a single spam comment, I can delete it just fine with the above command.

Can you give us more details about your environment?
- `wp cli info --debug`
- `echo "$IFS" | cat -ETv`
