### ISSUE TITLE
Review .gitignore contents

### ISSUE THREAD

**Issue by GaryJones** [wp-cli/wp-cli#4855]
Here are the current contents of [.gitignore](https://github.com/wp-cli/wp-cli/blob/56e2b61abf3cc9d5da85c953935a439df4f10fc9/.gitignore):

```
.DS_Store
config.yml
PHAR_BUILD_VERSION
/cache
/packages
/vendor
/*.phar
/phpunit.xml.dist
/codesniffer
/PHP_Codesniffer-VariableAnalysis
.*.swp
```

A Git ignore file should contain references to files and folders generated as part of this project.

- `.DS_Store` is operating-system specific and should be ignored via [global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c).
- `config.yml` - no idea what this relates to - add a comment if known and still valid (an artefact that anyone can generate when contributing to this project)
- `cache/` - for what? Add a comment
- `packages/` - still valid?
- `phpunit.xml.dist` - why is this excluded, especially when it's already in the repo? Possibly meant to exclude the local version `phpunit.xml`.
- `codesniffer/` - possibly related to any reports being generated to file by PHPCS? Add a comment if so, and note it somewhere so others know to use it.
- `/PHP_Codesniffer-VariableAnalysis` - not sure why this would be needed - the [VariableAnalysis](https://github.com/sirbrillig/phpcs-variable-analysis) is not even in use.
- `.*.swp` - possibly related to swap file, which would be an operating system file, not a project artefact.

Also missing is `.phpcs.xml` and `phpcs.xml` to allow local overrides for PHPCS.

Here's what it _could_ look like, depending on a best guess:

```
# Composer directory.
/vendor

# Phar file generation - see {URL explaining to how to generate a .phar}.
PHAR_BUILD_VERSION
/*.phar

# PHPUnit local file.
/phpunit.xml

# PHPCS local files and generated report directory.
/.phpcs.xml
/phpcs.xml
/codesniffer

# Other stuff I have no idea are even valid.
config.yml
/cache
/packages
```

**Comment by schlessera** [comment]
Yes, I agree, this could use cleanup, and I love the addition of comments.

Some observations:
* `.DS_Store` should indeed be part of the global gitignore file. However, many developers are unaware of how this works, and if we remove this, we'll have half of the PRs in the future messed up with this file. We might add this to `precommit` checks first.
* `config.yml` is the local WP-CLI configuration file you can put in a folder. This can for example be used for pointing WP-CLI to a specific site when running tests.

I'll need to examine what the `/cache` and `/packages` folders are about. This might be historical, or it might be the fallback for when the user's home folder is not writeable.
