### ISSUE TITLE
WP-CLI does not use the same way as wordpress to locate the `wp-config.php`

### ISSUE THREAD

**Issue by michaelzangl** [wp-cli/wp-cli#4856]
You won't notice the difference except if you are using symbolic links for your wordpress path.

Wordpress works when using a symbolic link to the wordpress installation and putting the wp-config.php in the parent directory. WP-CLI won't find the config then, even if ABSPATH is set to the correct directory (not the real one, but the symbolic path)

This is how Wordpress checks:
```php
if ( file_exists( ABSPATH . 'wp-config.php' ) ) {
	// => ABSPATH . 'wp-config.php' 
} elseif ( @file_exists( dirname( ABSPATH ) . '/wp-config.php' ) && ! @file_exists( dirname( ABSPATH ) . '/wp-settings.php' ) ) {
	// => dirname( ABSPATH ) . '/wp-config.php' ;
} else {
```

This is how wp-cli currently checks
```php
function locate_wp_config() {
    //...
		if ( file_exists( ABSPATH . 'wp-config.php' ) ) {
			// =>  ABSPATH . 'wp-config.php';
		} elseif ( file_exists( ABSPATH . '../wp-config.php' ) && ! file_exists( ABSPATH . '/../wp-settings.php' ) ) {
			// => ABSPATH . '../wp-config.php';
		}
// ...
$path = realpath( $path );
    //...
}
```

**Comment by schlessera** [comment]
Yes, I agree, we should use `dirname` as well to make behavior match WordPress.
