### ISSUE TITLE
cavalcade compatibility issues ?

### ISSUE THREAD

**Issue by mirzazeyrek** [wp-cli/wp-cli#4865]
When I try to run `wp cavalcade log` on with wp-cli 1.5.1 and wp-cli 1.5.0, I'm getting this error:

https://5e8b25de-f7a8-4b18-934e-9f3b0d54042e.htmlpasta.com/

It works fine with wp cli 1.4.1 without any errors. 

We are using PHP 7.2.6-1+ubuntu16.04.1+deb.sury.org+1 with latest wordpress release.

Any ideas ?

[Cavalcade](https://github.com/humanmade/Cavalcade)

**Comment by swissspidy** [comment]
I mostly see WooCommerce in the call stack. Have you tried disabling or skipping WooCommerce for that command?

Also, it‘s probably more of a bug in Cavalcade than WP-CLI itself. So if it persists even without WooCommerce I‘d rather report it to Cavalcade.

**Comment by schlessera** [comment]
@mirzazeyrek From what I can see in the trace, my first guess would be that either Cavalcade, WooCommerce or a WooCommerce plugin messes up the `'site_url'`, which requires 4 arguments but seems to be passed in with 1 argument only.

I'd grep the code of the site to see what happens with that `'site_url'` filter first.

**Comment by mirzazeyrek** [comment]
Thanks for the insights @schlessera and @swissspidy, I can confirm that deactivating `WooCommerce Subscriptions By Prospress Inc.` solves the issue.
