### ISSUE TITLE
Get a specific meta from all posts [Need Help]

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4869]
Hi there, I am wondering if there is a way to get a specific meta from all posts? and if not, would it be possible to implement in wp cli?
Eg.  I have meta: test
I want to get the value from test on each post and return all at once

like this: wp post list --post_type=post --post_status=publish --field=post_name --allow-root --path=/var/www/wordpress

which is to get all titles

**Comment by danielbachhuber** [comment]
Hi @killown,

You can do this with `xargs`:

```
wp post list --post_type=post --format=ids | xargs -0 -d ' ' -I % wp post meta get % _thumbnail_id
```

Change `_thumbnail_id` to whichever meta you'd like to retrieve.

See Shell Friends for more details: https://make.wordpress.org/cli/handbook/shell-friends/#combine-wp-cli-commands

If you have other questions, please visit the `#cli` channel in Slack. We don't typically use GitHub issues for support questions. See https://wp-cli.org/#support

**Comment by killown** [comment]
thank you @danielbachhuber but this method is too slow
