### ISSUE TITLE
Remove `WP_CLI\Utils\is_bundled_command( $command )` again

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#4874]
The `WP_CLI\Utils\is_bundled_command( $command )` method was introduced for making it easy to only track usage of bundled commands, not third-party commands.

As we don't do the tracking anymore, we don't need the above method either.

**Comment by schlessera** [comment]
Related:
* Add `WP_CLI\Utils\is_bundled_command( $command )` function - https://github.com/wp-cli/wp-cli/pull/4049
* Capture and report anonymized usage statistics - https://github.com/wp-cli/wp-cli/issues/3886

**Comment by swissspidy** [comment]
Any chance we could first discuss revisiting #3886 again as a fully opt-in solution?
