### ISSUE TITLE
Help for static analysis

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#4878]
Hello!

Could you help me to load WordPress without actually outputting something like WP-CLI does?
I'd like to run [static analysis](https://github.com/phpstan/phpstan) on WordPress.

**Comment by schlessera** [comment]
@szepeviktor GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions.

But just join me in #cli channel and we can discuss what you are trying to do.
