### ISSUE TITLE
core update fails inside latest wordpress Docker image

### ISSUE THREAD

**Issue by tofumatt** [wp-cli/wp-cli#4879]
Gutenberg's tests are failing because when we run `wp-cli core update` inside the official WordPress docker image (https://github.com/WordPress/gutenberg/blob/master/bin/install-wordpress.sh#L52) we get an error:

```
Warning: Unable to create directory wp-content/uploads/2018/08. Is its parent directory writable by the server?
Updating to version 4.9.8 (en_US)...
Downloading update from https://downloads.wordpress.org/release/wordpress-4.9.8-no-content.zip...
Unpacking the update...
Error: Could not create directory.
```

Removing the update command things work fine, regardless of WordPress image version.

I have no idea how WP CLI works but it seems an issue with it. 🤷‍♂️

**Comment by schlessera** [comment]
@tofumatt The docker container seems to have permission problems, at least when creating directories (as the first warning already shows). Without the possibility to create a temporary folder, the update's zip file cannot be extracted.

You should ensure that the user that executes these commands within your Docker container has the needed permissions.

**Comment by tofumatt** [comment]
Yeah, I'm actually trying that out now, realising that https://github.com/WordPress/gutenberg/commit/0b368452b84a309e416f3a312d969ed8156e4e88 might've been in our code to cover the permissions issue.

**Comment by schlessera** [comment]
I'll close this issue because it seems that it is a problem with your environment. Just hit me up in the #cli channel in case you need further assistance.

**Comment by tofumatt** [comment]
Yup, you're totally right. Thanks and sorry for the noise! 👍
