### ISSUE TITLE
Global settings partly ignored?

### ISSUE THREAD

**Issue by noplanman** [wp-cli/wp-cli#4884]
I have a plugin that is interfering with redirections.

Thanks to the `skip-plugins` parameter via CLI it can easily be skipped and everything works as expected.

What doesn't work though, is using `skip-plugins` in the global config.
It doesn't get loaded and the redirect error pops up again.

Am I missing something obvious?

What I've tried (both as `string` and `array`):
```yaml
skip-plugins: my-plugin
```
```yaml
@host {skip-plugins: my-plugin}
```

**Comment by wojsmol** [comment]
paste config minus any secrets.

**Comment by noplanman** [comment]
@wojsmol The above code blocks are each the `~/.wp-cli/config.yml` I've tried.

More complete, would be like this, using it for a subsite on a multisite install:
```yaml
@example-com: {ssh: example, url: example.com, path: public_html, skip-plugins: my-plugin}
```

(As mentioned above, I've also tried to move the `skip-plugins` into the global context)

**Comment by wojsmol** [comment]
https://make.wordpress.org/cli/handbook/config/#config-files - se how example file is formatted

**Comment by swissspidy** [comment]
Formatting should be fine I think. Have never really seen YAML files with brackets but apparently it's a thing: http://symfony.com/doc/current/components/yaml/yaml_format.html

I just tried to set the `skip-pkugins` option locally and I am able to reproduce the issue.

**Comment by noplanman** [comment]
I haven't dug into the code, but assume it's some forgotten snippet when `skip-plugins` was introduced, as the functionality is there when using CLI.

**Comment by schlessera** [comment]
That the Yaml standard accepts some notation does not mean that our interpreter library understands it as well. Yaml is a hugely complex format with more than one broken implementation.

The syntax I usually use is this:
```
skip-plugins:
  - my-plugin
```

**Comment by swissspidy** [comment]
> The syntax I usually use is this:

That's the format I tried locally and didn't seem to work.

**Comment by danielbachhuber** [comment]
@noplanman Did you get this sorted out?

One thing to note: if you have a project `wp-cli.yml`, it will override all settings in `~/.wp-cli/config.yml`, unless you explicitly specify inheritance.

**Comment by noplanman** [comment]
@danielbachhuber Thanks for your reply and explanation.

Aaah, just noticed now that by having a remote configuration (using `@host`), the local configuration gets skipped entirely and instead only the remote config(s) get used.

By adding the settings to the `~/.wp-cli/config.yml` on the remote server, it works as it should.

Is this intended? To me, the local config should apply too, but maybe my thinking is off a bit or there is a hidden flag for this.

Regarding inheritance, could you elaborate a bit more or point me in the right direction where I can learn how that works, please?

**Comment by danielbachhuber** [comment]
> Is this intended? To me, the local config should apply too, but maybe my thinking is off a bit or there is a hidden flag for this.

I think https://github.com/wp-cli/wp-cli/issues/4708 is related. I don't recall the specifics off the top of my head.



> Regarding inheritance, could you elaborate a bit more or point me in the right direction where I can learn how that works, please?

See https://make.wordpress.org/cli/handbook/config/#config-files, specifically the annotated config file.

**Comment by noplanman** [comment]
As far as I can tell, the problem stated in #4708 is fixed and wp-cli works like this now.
Executing `wp @remote --info` shows that the remote config file(s) are being used.

What I'm looking for, is that the local config gets used for remote calls.

e.g. If I have a handful of different sites and want them all to share the same config, instead of having to set the config files on all the remotes, it would be great to have the configs read from a local config file.

I've tried with `inherit` or defining the necessary parameters in each remote alias, but none of that works.

Am I missing something fundamental?

@swissspidy As you mentioned above, setting the config directly in the aliases should work, right? Even if it's the "local" config file that defines the aliases. (Which is kind of the whole point here...)
