### ISSUE TITLE
Error: 'package' is not a registered wp command. See 'wp help' for available commands.

### ISSUE THREAD

**Issue by bondansebastian** [wp-cli/wp-cli#4900]
Hi, i just tried `wp-cli` and curently experiencing problem trying to use this cool tool.

I installed `wp-cli` via composer using `composer global require wp-cli/wp-cli` command.
Currently only 3 commands available for me:

    SUBCOMMANDS

      cli       Review current WP-CLI info, check for updates, or see defined aliases.
      help      Get help on WP-CLI, or on a specific command.
      ocdi
When i tried to install a package, the command line says

    Error: 'package' is not a registered wp command. See 'wp help' for available commands.

I am on windows machine, using `MINGW64` as terminal.
Strange thing is, calling `wp` on window's `cmd` or `powershell` results in

    'sh' is not recognized as an internal or external command, operable program or batch file.
I have enabled linux subsystem for windows though.

Here's the output of `wp --info`

    OS:     Windows NT 10.0 build 17134 (Windows 10) i586
    Shell:  C:\WINDOWS\system32\cmd.exe
    PHP binary:     C:/xampp/php/php
    PHP version:    7.1.15
    php.ini used:   C:\xampp\php\php.ini
    WP-CLI root dir:        C:\Users\Bondan\AppData\Roaming\Composer\vendor\wp-cli\wp-cli
    WP-CLI vendor dir:      C:\Users\Bondan\AppData\Roaming\Composer\vendor
    WP_CLI phar path:
    WP-CLI packages dir:
    WP-CLI global config:
    WP-CLI project config:
    WP-CLI version: 2.0.0
As can be seen above, my `WP-CLI packages dir` is always empy, even though i called `wp` command from my local wordpress installation folder.

And here's the complete output of `wp help`, which always the same no matter from which folder i run the command.

    NAME

      wp

    DESCRIPTION

      Manage WordPress through the command-line.

    SYNOPSIS

      wp <command>

    SUBCOMMANDS

      cli       Review current WP-CLI info, check for updates, or see defined aliases.
      help      Get help on WP-CLI, or on a specific command.
      ocdi

    GLOBAL PARAMETERS

      --path=<path>
          Path to the WordPress files.

      --url=<url>
          Pretend request came from given URL. In multisite, this argument is how the target site is specified.

      --ssh=[<scheme>:][<user>@]<host|container>[:<port>][<path>]
          Perform operation against a remote server over SSH (or a container using scheme of "docker", "docker-compose", "vagrant").

      --http=<http>
          Perform operation against a remote WordPress install over HTTP.

      --user=<id|login|email>
          Set the WordPress user.

      --skip-plugins[=<plugins>]
          Skip loading all plugins, or a comma-separated list of plugins. Note: mu-plugins are still loaded.

      --skip-themes[=<themes>]
          Skip loading all themes, or a comma-separated list of themes.

      --skip-packages
          Skip loading all installed packages.

      --require=<path>
          Load PHP file before running the command (may be used more than once).

      --[no-]color
          Whether to colorize the output.

      --debug[=<group>]
          Show all PHP errors and add verbosity to WP-CLI output. Built-in groups include: bootstrap, commandfactory, and help.

      --prompt[=<assoc>]
          Prompt the user to enter values for all command arguments, or a subset specified as comma-separated values.

      --quiet
          Suppress informational messages.

      Run 'wp help <command>' to get more information on a specific command.

**Comment by wojsmol** [comment]
Hi
Please see [WP-CLI r2.0 release blog post](https://make.wordpress.org/cli/2018/08/08/wp-cli-v2-0-0-release-notes/), for normal use with all commands remove wp-cli/wp-cli and require wp-cli/wp-cli-bundle

**Comment by bondansebastian** [comment]
Thanks for pointing out @wojsmol !

**Comment by schlessera** [comment]
Yes, requiring `wp-cli/wp-cli-bundle` will pull in all the bundled command. `wp-cli/wp-cli` is the pure framework only now.

**Comment by coreyworrell** [comment]
This should be updated in the docs right? https://make.wordpress.org/cli/handbook/installing/#installing-via-composer

**Comment by truongwp** [comment]
Thanks @wojsmol,

It solves my problem as well. The WordPress handbook should be updated.
