### ISSUE TITLE
Some commands listed twice in the commands list on website

### ISSUE THREAD

**Issue by skorasaurus** [wp-cli/wp-cli#4902]
First, congratulations on the 2.0 release! 

After some searching, I wasn't sure where to best log this and was suggested #cli slack that this may be the most appropriate place to post this issue. 

Several (not all) commands are listed twice on https://developer.wordpress.org/cli/commands/ (e.g. https://developer.wordpress.org/cli/commands/eval-2/) and the duplicate listings are missing description as shown below. 

The duplicate listings are listed first and have urls with the suffix -2 appended to them. 

![selection_140](https://user-images.githubusercontent.com/955351/43916871-c842e610-9bdc-11e8-9939-1c6aa21d7be6.png)

**Comment by swissspidy** [comment]
Thanks for posting this. We're aware of the issue with the documentation import script. I hope we can fix it soon.

**Comment by danielbachhuber** [comment]
I've fixed the underlying problem with https://meta.trac.wordpress.org/changeset/7611/ and https://meta.trac.wordpress.org/changeset/7612/

I've also cleaned up the duplicate data.
