### ISSUE TITLE
PHP Notice:  Undefined index: SERVER_ADDR .. WP_CLI/Runner.php(1150) : eval()'d code on line 24

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#4904]
Hey,

I am getting the an error when I tried to export the db $wp_version = '4.9.8'; multisite.
wp db export db.sql

> PHP Notice:  Undefined index: SERVER_ADDR in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1150) : eval()'d code on line 24
> PHP Notice:  Undefined index: REQUEST_URI in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1150) : eval()'d code on line 25

> PHP Notice:  Undefined index: SERVER_ADDR in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1150) : eval()'d code on line 24
> PHP Notice:  Undefined index: REQUEST_URI in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1150) : eval()'d code on line 25

> wp --info
> OS:     Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
> Shell:  /bin/bash
> PHP binary:     /usr/bin/php7.0
> PHP version:    7.0.30-0ubuntu0.16.04.1
> php.ini used:   /etc/php/7.0/cli/php.ini
> WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
> WP-CLI vendor dir:      phar://wp-cli.phar/vendor
> WP_CLI phar path:       /var/www/vhosts/qsandbox.com/htdocs
> WP-CLI packages dir:
> WP-CLI global config:
> WP-CLI project config:
> WP-CLI version: 2.0.0
>

**Comment by wojsmol** [comment]
@lordspace Do you use in wp-config.php values of `$_SERVER['SERVER_ADDR']` and `$_SERVER['REQUEST_URI']`? Whole `$_SERVER` is not set in cli environment.

**Comment by schlessera** [comment]
Closing, as this is almost certainly an issue of how the `wp-config.php` file of the site is set up.

**Comment by schlessera** [comment]
@lordspace GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
