### ISSUE TITLE
--post_content escape single and/or double quotes

### ISSUE THREAD

**Issue by BKirev** [wp-cli/wp-cli#4905]
Hey! First of all, thanks for the awesome work!

I'm a bit stuck in a situation here. I have a post in HTML format, which contains things as:
```HTML
<div id="(double quotes)something">Notice the don't(single quote) word here</div>
```

If I just put this in --post_content it messes up, which is expected, because of the single and double quotes(and probably more other characters which are messing up).
I've tried to add ```addslashes``` and it does adds the posts successfully BUT all the `\` characters used for escaping are visible in the wordpress post afterwards.

So I was wondering is there any way to publish a post with wp-cli and don't mess the shell somehow with special characters?

**Comment by schlessera** [comment]
@BKirev If you can put this HTML into a file, you can send it through STDIN:
```
cat myhtml.txt | wp post create --post-title="My Title" -
```
Note the dash at the end to denote receiving the content through STDIN.

Hope this helps!
