### ISSUE TITLE
v.2.0.0 needs an active database ?

### ISSUE THREAD

**Issue by jukefr** [wp-cli/wp-cli#4908]
Hello,

I have been installing wp-cli on my docker container at build time up until now.
Since it is installed in a container at build time no other services are running, that never was an issue until v2.0.0 because the CLI never required an active DB.

However with wp-cli 2.0.0 when I install I get the following error
```
Warning: mysqli_real_connect(): (HY000/2002): No such file or directory in /var/www/html/wp-includes/wp-db.php on line 1531
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at ``. This could mean your host’s database server is down.
```
Which tells me it is trying to access my db for some reason.

Is this a bug or a feature ? Is this documented anywhere ?
The way this works right now makes it impossible to dockerize at build time.

Installing 1.5.1 works perfectly fine, I can also add cli packages at build time in docker with 1.5.1 and no db active...

**Comment by wojsmol** [comment]
@jukefr Please provide commands you are executing immediately before error.

**Comment by jukefr** [comment]
```
curl --silent --show-error https://getcomposer.org/installer | php &&\
    php composer.phar config --global github-oauth.github.com $GITHUB_OAUTH &&\
    php composer.phar global require wp-cli/wp-cli:1.5.1 &&\
    /var/www/.composer/vendor/bin/wp package install jukefr/wp-cli-media-cleanup &&\
    /var/www/.composer/vendor/bin/wp package install typisttech/image-optimize-command:0.1.2 &&\
    /var/www/.composer/vendor/bin/wp package install wp-cli/profile-command:0.3.0
```
with 1.5.1 no problem

```
curl --silent --show-error https://getcomposer.org/installer | php &&\
    php composer.phar config --global github-oauth.github.com $GITHUB_OAUTH &&\
    php composer.phar global require wp-cli/wp-cli:2.0.0 &&\
    /var/www/.composer/vendor/bin/wp package install jukefr/wp-cli-media-cleanup &&\
    /var/www/.composer/vendor/bin/wp package install typisttech/image-optimize-command:0.1.2 &&\
    /var/www/.composer/vendor/bin/wp package install wp-cli/profile-command:0.3.0
```
all hell breaks loose and get error in 1st post

**Comment by wojsmol** [comment]
Packages require update for WP-CLI v2.00.

**Comment by swissspidy** [comment]
Yeah `wp-cli/wp-cli-bundle` now contains the actual bundled comamnd, `wp-cli/wp-cli` is just the framework.

Glad you were able to resolve it.

For future questions, please note that GitHub issues are meant for tracking enhancements to and bugs of existing commands, not general support. For that we have a Slack channel and the support forums, see https://github.com/wp-cli/wp-cli#support.
