### ISSUE TITLE
pick_fields util function can't deal with numerical headings

### ISSUE THREAD

**Issue by javorszky** [wp-cli/wp-cli#4910]
This issue is valid as of latest commit on master at present time: https://github.com/wp-cli/wp-cli/commit/45f1dec1b8f11f857425f51dd739e5fb6110b795.

I have the following data I want to display the following way:

```
$counts = [
    '1' => 34,
    '2' => 12,
    '3' => 22,
    '4' => 99,
    '5' => 422,
    'total' => 589,
];

WP_CLI\Utils\format_items( 'table', [ $counts ], [ '1', '2', '3', '4', '5', 'total' ] );
```
The data relates to star ratings.

It however comes out as this:

```
+---+---+---+---+---+-------+
| 1 | 2 | 3 | 4 | 5 | total |
+---+---+---+---+---+-------+
|   |   |   |   |   | 589   |
+---+---+---+---+---+-------+
```

## Reason

[This part of pick_fields](https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L342) is responsible for setting either the value, or `null`, if the item doesn't have value with key `$field`.

Because $item is an object, accessing a numerical property on the object is just not a thing php does, no matter how I coerce the character `5`, ie it doesn't matter if it's a number, or a string.

Reason for that is how properties work in PHP (http://php.net/manual/en/language.oop5.properties.php), ie they need to be declared in the class using one of the visibility keywords, followed by a normal variable declaration.

A [variable follows the rules of all other labels in php](http://php.net/manual/en/language.variables.basics.php), namely:

> A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'

Which means that having table headings as numbers only won't work.

Interestingly if I set the key to `1one` instead of `1` only, then the value appears, so in this case the property can be accessed even when it starts with a number, which as per php variable declaration, should not be possible.

## Expectation

I do expect to be able to have a table with numbers as its headers and data to correctly show up.

**Comment by danielbachhuber** [comment]
> I do expect to be able to have a table with numbers as its headers and data to correctly show up.

Do you have a suggested implementation?

**Comment by javorszky** [comment]
I was wondering if `$item` needs to be an object, or can that be an array instead.

**Comment by danielbachhuber** [comment]
It looks like there's some history to why we've cast as objects ae1d08bf2b4a3536f2f259444a9d0fbaf32290fe

Instead, we could avoid casting `$item` at all, and handle both cases (one where `$item` is an array and other where `$item` is an object).

Want to submit a pull request for it? Unit tests would be good too.

**Comment by javorszky** [comment]
Yup, can do, probably over the weekend though, as WordCamp Brighton time for the next few days. I'll do my best with unit tests, but I might need some help with that, but will reach out if that's the case! :)

Feel free to assign me to this issue.

Thanks for digging up https://github.com/wp-cli/wp-cli/commit/ae1d08bf2b4a3536f2f259444a9d0fbaf32290fe, will have a look at why that happened.

**Comment by schlessera** [comment]
A quick test revealed that using curly brace syntax is not enough here and still fails.

Not casting, but using either an object or an array, as @danielbachhuber suggested, does work for this specific case.

@javorszky Recovered from Brighton and up for a PR?

**Comment by javorszky** [comment]
No, sorry! Work and life got in the way of this, but thank you for doing this! <3
