### ISSUE TITLE
WP_CLI::colorize breaks table layout

### ISSUE THREAD

**Issue by kshaner** [wp-cli/wp-cli#4912]
Follow up from ticket #1736. Using WP CLI 2.0 (not sure how far back it goes) and WP_CLI::colorize on table data contents before being output breaks the ascii output of the table.

Here is a simplified sample command that breaks the table with color output:

```php
WP_CLI::add_command( 'color_test', function( $args, $ssoc_args ) {
	$rows = [
		[
			'capability' => 'manage_options',
			'administrator' => '+',
			'editor' => '-',
			'author' => '-',
			'contributor' => '-',
		],
		[
			'capability' => 'read',
			'administrator' => '+',
			'editor' => '+',
			'author' => '+',
			'contributor' => '+',
		],
	];

	foreach( $rows as &$row ) {
		foreach( $row as $key => &$val ) {
			switch( $val ) {
				case '+':
					$val = WP_CLI::colorize( '%g+%n' );
				break;
				case '-':
					$val = WP_CLI::colorize( '%r-%n' );
				break;
			}
		}
	}

	$formatter = new \WP_CLI\Formatter( $assoc_args, array_keys( $rows[0] ) );
	$formatter->display_items( $rows );
});
```

Here is the output of the code above:

![image](https://user-images.githubusercontent.com/1686106/44167039-e3ed3880-a081-11e8-9827-87bf651d4fc2.png)

The issue may lie within php-cli-tools, but this issue is to find out.

**Comment by schlessera** [comment]
@kshaner Please see https://github.com/wp-cli/php-cli-tools/issues/134#issuecomment-414751843 for a resolution to the above issue.

**Comment by kshaner** [comment]
Thanks @schlessera, is this documented somewhere I can point colleagues to?

**Comment by schlessera** [comment]
@kshaner No, not really, as the docblocks that mention this are currently not being pulled in as internal API pages. I've created an issue here to correct this: https://github.com/wp-cli/wp-cli/issues/4915
