### ISSUE TITLE
WPCLI stuck on every command

### ISSUE THREAD

**Issue by mpawlak96** [wp-cli/wp-cli#4932]
Hello,

I have a problem with wpcli. It doesn't matter what i want to do:
wp plugin list
wp plugin install
etc. it get stucked. I can see it also on strace (this PID): 

strace: Process 599848 attached
read(3, 

I have this problem only on 2 wordpress. Website (front + backend) is working fine.

WP version - 4.9.8

wpcli version:

wp --info
OS:	Linux XXXXXXXX 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Shell:	/bin/bash
PHP binary:	/opt/alt/php56/usr/bin/php
PHP version:	5.6.37
php.ini used:	/opt/alt/php56/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.0.0

**Comment by swissspidy** [comment]
Have you tried running WP-CLI with the `--skip-plugins` and `--debug` arguments?

Note that's easier for us to help you with support in the #cli Slack channel instead of GitHub. GitHub is for keeping track of enhancements and bugs.
