### ISSUE TITLE
Nightly Phar build missing '-alpha' in version string

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#4940]
On a Phar installation, if I update to the latest nightly:

```
$ wp cli update --nightly
You have version 2.0.1. Would you like to update to the latest nightly? [y/n] y
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
md5 hash verified: 2459cc6ff5823e47fd1b95eefdf3b1dd
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.
```

I'd expect to see the `-alpha` included in the version string. However, when I currently see this:

```
$ wp cli version
WP-CLI 2.0.1
```

Historically, https://github.com/wp-cli/wp-cli/blob/master/VERSION was bumped after each release to include `-alpha` in the version string: 

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/36432/45326380-5bd74300-b508-11e8-9ca4-d48c24d50c5e.png">

https://github.com/wp-cli/wp-cli/commits/master/VERSION

The `ci/prepare.sh` script would then append the Git short hash to the version as a part of the build process:

https://github.com/wp-cli/wp-cli/blob/3aac73bc4d629372531f3e15bbb67945d19b5d5a/ci/prepare.sh#L18-L24

This would then give us a nightly build version like this:

```
$ wp cli version
WP-CLI 2.1.0-alpha-2459cc6
```

So, something broke about this system but I'm not sure where.

As a user, my expectation is that I can:

1. Run `wp cli update --nightly` to end up the latest nightly build.
2. Run `wp cli update` to then update to the next nightly build.
3. Run `wp cli update --stable` to revert back to the latest stable build.

Step 2 is broken right now because nightly builds have an incorrect version string.

Previously #2942 #1536

**Comment by schlessera** [comment]
I think I know what the problem is. The Composer lock file in `wp-cli/wp-cli-bundle` locks to a tagged release of `wp-cli/wp-cli` (`2.0.1` in this case).

I think I need to pull in `dev-master` of `wp-cli/wp-cli` for `wp-cli/wp-cli-bundle`, instead of `^2`.

**Comment by schlessera** [comment]
> Run `wp cli update --nightly` to end up the latest nightly build.
> Run `wp cli update --stable` to revert back to the latest stable build.

Tested this just now and it works as expected again.
