### ISSUE TITLE
Installation failed: The package could not be installed.

### ISSUE THREAD

**Issue by Salman7870** [wp-cli/wp-cli#4949]
Hello Everyone,
My WordPress site was perfect, but when I Updated all my plugins then my website behave was not good. The main issue occurred was that I can't install any plugins by WP Plugin installer or any theme by theme installer. 
I have tried each and every method to solve this problem but not worked yet. Now I have erase each and everything , like Wordpress, Database and Database Users. I have installed each and everything Fresh but the problem is still there. 
I am tired to configured the wp-config.php file but the result is not too good.
Please help.   I have attached the screenshots of the error. 
**Error: Installation failed: The package could not be installed.**

![22](https://user-images.githubusercontent.com/43409679/45769703-41caee00-bbf5-11e8-9546-74ab51d3d9a4.PNG)
![1111](https://user-images.githubusercontent.com/43409679/45769704-41caee00-bbf5-11e8-8c69-fa8f2ed92a28.PNG)

**Comment by schlessera** [comment]
@Salman7870 This is probably something you should contact your hosting provider's support about, or the general WordPress Support forum: https://wordpress.org/support/

This place here is for contributing to the development of WP-CLI, the WordPress command line interface.
