### ISSUE TITLE
Use of undefined constant STDOUT ... wp-cli/php/utils.php on line 995

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#4952]
sudo -H -u inx10 bash -c '/usr/local/bin/wp --info'

`PHP Warning:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 995`

OS that has cPanel installed.
` Linux version 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 (mockbuild@buildfarm02.cloudlinux.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue May 22 10:39:25 EDT 2018`

some header is also output.
Content-type: text/html; charset=UTF-8

```
OS:     Linux 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64
Shell:  /bin/bash
PHP binary:     /opt/cpanel/ea-php72/root/usr/bin/php-cgi
PHP version:    7.2.9
php.ini used:   /opt/cpanel/ea-php72/root/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /usr/local/bin
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.0.1
```

**Comment by lordspace** [comment]
Here's the same call on a different server. It's running ea-php71.
The STDOUT warning is not showing up but Content-type does.

```
root@qsandbox.com-vps1300 [/home]# sudo -H -u qs9 bash -c '/usr/local/bin/wp --info'
Content-type: text/html; charset=UTF-8

OS:     Linux 3.10.0-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64
Shell:  /bin/bash
PHP binary:     /opt/cpanel/ea-php71/root/usr/bin/php-cgi
PHP version:    7.1.21
php.ini used:   /opt/cpanel/ea-php71/root/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /usr/local/bin
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.0.1

```

**Comment by danielbachhuber** [comment]
Hi @lordspace:

> Here's the same call on a different server. It's running ea-php71.
> The STDOUT warning is not showing up but Content-type is.

You don't seem to be running WP-CLI via PHP CLI. You'll want to make sure your server is configured to do so.

**Comment by pothi** [comment]
@lordspace I have the same issue. Have you found a solution?

**Comment by pothi** [comment]
While I don't have a solution, here's a workaround... cPanel seems to have php-cgi and php-cli with php-cgi as default (at least in mine). So, running wp using php-cli would be the workaround. Specifically, running `/usr/local/bin/php /path/to/wp wp_command` is the actual workaround. We can put it as alias such as `alias wp_cli=/usr/local/bin/php /path/to/wp`. I hope that helps someone.

**Comment by danielbachhuber** [comment]
Worth noting: this will error more explicitly with https://github.com/wp-cli/wp-cli-bundle/pull/465
