### ISSUE TITLE
No output on some WP installs

### ISSUE THREAD

**Issue by fredbradley** [wp-cli/wp-cli#4966]
Hello, bit of an odd one. 

I'm new at using WP-CLI. I've installed it on my linux production server, and on my mac. 90% of the time its working as expected. 

However there is one site installation that when I run any `wp` command there is an empty response returned (nothing is output). 

It's the same WP instance both remotely and locally which suggests to me that there must be something within that particular config/instance that it doesn't like? 

Is there a way of debugging this? Are there any common things that people could suggest that it might be conflicting against?

**Comment by swissspidy** [comment]
Please have a look at https://make.wordpress.org/cli/handbook/troubleshooting/ and also https://make.wordpress.org/cli/handbook/common-issues/.

GitHub issues are meant for tracking enhancements and bugs, not general support.  So if your problem persists I suggest joining our [Slack channel](https://make.wordpress.org/chat/) or [posting in the support forums](https://wordpress.org/support/forum/wp-advanced/#new-post) with the tag `WP-CLI`
