### ISSUE TITLE
Testing wp-cli.phar throws error

### ISSUE THREAD

**Issue by SeijiSensei** [wp-cli/wp-cli#4967]
I downloaded the phar file with

curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

to /usr/local/bin on my server, then ran the prescribed test

php wp-cli.phar --info

and got this error

PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/i18n-command/src/MakePotCommand.php on line 29

Platform:   CentOS 6.7 (Final)
PHP version: PHP 5.3.3 (cli) (built: Feb  9 2016 10:36:17)

**Comment by SeijiSensei** [comment]
Updating to the most recent PHP release for this platform, 5.3.3-49, did not resolve the problem.

**Comment by wojsmol** [comment]
@SeijiSensei Minimum php version required for wp-cli 2.x is 5.4.x.

**Comment by SeijiSensei** [comment]
I'll see what I can do about upgrading.  I haven't built PHP from source in some time now.  CentOS 6 and RedHat 6 are still a very popular and well-supported platforms.

Still an "unexpected [" error doesn't seem likely to be a versioning problem, but I'll see what I can find.

**Comment by SeijiSensei** [comment]
Works with php client 5.6 from http://repo1.dal.innoscale.net/remi/enterprise/6/php56/x86_64/repoview/

Thanks for the help!

**Comment by wojsmol** [comment]
`unexpected [` is caused by use of short array syntax `[]` instead of `array()`. Short array syntax was introduced in php 5.4.x.
