### ISSUE TITLE
"YIKES" root user warning on tab completion, etc.

### ISSUE THREAD

**Issue by Roy-Orbison** [wp-cli/wp-cli#4968]
The CLI root warning is great, but aren't all the `wp cli …` sub-commands informational/server-level administrative, therefore relatively safe to run as root? If I'm typing a command as below (per the CLI's own recommendations), hitting tab invokes `wp cli completions` in the background and produces the **YIKES** error rather than showing completion options.

```
root public_html # sudo -u A_NON_LOGON_USER -i -- wp se
```

Only 2 are whitelisted:  
https://github.com/wp-cli/wp-cli/blob/34ba8d41b4bf8dcd23b8f3f01136eb3f52a3d932/php/WP_CLI/Runner.php#L909

I can't even tab-complete `wp --allow-root`.

**Comment by swissspidy** [comment]
Running WP-CLI as root is extremely dangerous. When you execute WP-CLI as root, any code within your WordPress instance (including third-party plugins and themes you’ve installed) will have full privileges to the entire server. This can enable malicious code within the WordPress instance to compromise the entire server. _That's_ why we as a project strongly discourage running WP-CLI as root. See also #973 for some background

Since the same issue with tab completion as root came up in #1829 I'm closing this one as a duplicate.

**Comment by Roy-Orbison** [comment]
@swissspidy I'm not entirely convinced you actually read the issue. I completely understand why executing such 3rd party code as root is dangerous, hence the compliment above. I tried to make it clear, even giving an example, that I am referring to the literal `wp cli ...` sub-commands, not wp-cli commands in general. Two have already been whitelisted. I find it hard to believe that it's okay to run `wp cli update` as root, but not `wp cli check-update`.

**Comment by lightningspirit** [comment]
Running `wp` cli inside a Docker container should not pose any issue, as the container per si is isolated from the rest of the host. Is there any way to switch off this warning message?

**Comment by schlessera** [comment]
@lightningspirit There is a flag `--allow-root` that you can add to any WP-CLI command to allow it to be run as the `root` user.

There is also a new `WP_CLI_ALLOW_ROOT` environment variable that allows you to run all WP-CLI in your environment as root without needing to add the `--allow-root` flag. This is available in current `nightly` build and will be shipped with WP-CLI v2.5.0.

**Comment by schlessera** [comment]
@Roy-Orbison I'll keep this in mind and recheck the completion code to see if that can be improved. in the mean-time, you can set the `WP_CLI_ALLOW_ROOT` environment variable on latest nightly as a (unsafe!) workaround.

**Comment by lightningspirit** [comment]
@schlessera thank you for the clarification. That's awesome!
