### ISSUE TITLE
Generating thumbnails fails with maximum execution time exceeded

### ISSUE THREAD

**Issue by cooperdk** [wp-cli/wp-cli#4974]
Using wp media generate with this command:

`runuser -l (***) -c 'wp media regenerate --path=/(***)/public_html/'`

I have many images on my site and around image 140 out of 2000, WP-CLI breaks with this error:

`Fatal error: Maximum execution time of 300 seconds exceeded in /(***)/public_html/wp-includes/class-wp-image-editor-imagick.php on line 362`

I checked how WP-CLI runs:

```
OS:     Linux m5132.contaboserver.net 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php5
PHP version:    5.6.38-0+deb8u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /(***)/public_html/wp-content
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.0.1
```

Since the CLI build of PHP has no execution limit, this seems odd.
Any idea why this happens?

**Comment by schlessera** [comment]
This probably means you're running WP-CLI through your webserver SAPI instead of cli SAPI.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by cooperdk** [comment]
Well, as you can see from my output, I am NOT running thru the webserver SAPI, but CLI and using path, not URL for the Wordpress root.

Also, the stated execution time of 300 seconds is not what I have actually set in either PHP-CLI or the webserver's PHP-settings.

**Comment by henriquebs12** [comment]
Any updates? I have the same issue. And tried to overwrite in several places the execution time and it just ignores, and keeps the 300 seconds.

**Comment by andreasanta** [comment]
+1

**Comment by kelvinkuiper** [comment]
+1

/opt/plesk/php/7.3/bin/php -d max_execution_time=0 -d time_limit=0 wp-cli.phar media regenerate --yes --only-missing --skip-delete

PHP Fatal error:  Maximum execution time of 300 seconds exceeded

**Comment by danielmccosker** [comment]
For anyone running into this problem without finding a solution: You might have a php_value set in `.htaccess` such as `php_value max_execution_time 300`.

You might try increasing that value, or removing the override in `.htaccess`.

**Comment by cooperdk** [comment]
> For anyone running into this problem without finding a solution: You might have a php_value set in `.htaccess` such as `php_value max_execution_time 300`.
> 
> You might try increasing that value, or removing the override in `.htaccess`.

No, I do not have that php_value set in .htaccess or anywhere else.

Why can't the devs simply insert the php_value command in the script? I don't seem to be able to edit it.

**Comment by drzraf** [comment]
@schlessera : Please reopen

`php -d max_execution_time=42 $(which wp) eval "echo ini_get('max_execution_time');"`
// outputs 42

`time php -d max_execution_time=42 $(which wp) media regenerate --only-missing --yes`
```
php7.4: time limit exceeded `Operation canceled' @ fatal/cache.c/GetImagePixelCache/1868.

real	0m30,995s
user	0m27,111s
sys	0m3,571s
```


Something in the media-regenerate WordPress (or wp-cli) logic is clearly resetting `max_execution_time` (or at least killing the process after 30 seconds)

**Comment by schlessera** [comment]
@drzraf :
The above `time limit exceeded` error message comes from an ImageMagick `TimeResource` limitation. As you've already found out, this can be configured via the ImageMagick configuration files. There might be ways of getting around that limit in WP-CLI, but this is unrelated to what the original poster has been experiencing.

Can you please open a separate issue for this in the https://github.com/wp-cli/media-command repo?
