### ISSUE TITLE
theme activate: not working when upper-case letters are included in theme's zip file

### ISSUE THREAD

**Issue by dimitrismitsis** [wp-cli/wp-cli#4976]
This issue is introduced in wp-cli > 2.0.0, it's not reproducible with 1.5.1.

Steps:
* Try installing and activating the attached theme:
`wp theme install twentysixteen_child_with_LS_template.zip --force --activate` 

This fails (during the activation) with an error that the theme wasn't found.  

If instead though, you split the installation with the activation:
`wp theme install twentysixteen_child_with_LS_template.zip --force --activate` 
`wp theme activate twentysixteen_child_with_ls_template`  

The last command only works if you turn all uppercase characters to lowercase.  

We actually first noticed this with Divi in our automatic tests.

[twentysixteen_child_with_LS_template.zip](https://github.com/wp-cli/wp-cli/files/2491309/twentysixteen_child_with_LS_template.zip)

**Comment by schlessera** [comment]
Fixed in (not yet released) https://github.com/wp-cli/extension-command/pull/137
