### ISSUE TITLE
Strange Permalink Settings Set on Fresh Install

### ISSUE THREAD

**Issue by mipon** [wp-cli/wp-cli#4991]
Hi there,

Using the command `db` and `core` to install WordPress, the `Permalink Settings` option seems to have unusual values. The select option defaults to `Custom Structure` and the input field is `/index.php/%year%/%monthnum%/%day%/%postname%/`.

![image](https://user-images.githubusercontent.com/11385613/47949227-b332e600-df82-11e8-8765-4baad02ab65d.png)

If WordPress is manually installed, `Day and name` is selected and the input field is set  `/%year%/%monthnum%/%day%/%postname%/` by default. This is the normal behavior.

![image](https://user-images.githubusercontent.com/11385613/47949181-e45ee680-df81-11e8-8c51-2173e11191c3.png)

**Comment by mipon** [comment]
XAMPP locally on Windows 7. PHP 7.2.5 Apache 2.4.33.0 WP-CLI 2.0.1.

Running the below script from browser, it says Enabled as expected.
```php
echo in_array( 'mod_rewrite', apache_get_modules() ) 
    ? 'Enabled' 
    : 'Not enabled';
```
But if I run the script from console, it gives `PHP Fatal error:  Uncaught Error: Call to undefined function apache_get_modules() `

**Comment by johnbillion** [comment]
Ah then your CLI has a separate configuration from CGI/FPM. Run `php --info` on the CLI and take a look at the output for `.ini` and it should show you where the configuration file is being read from. Compare it with what you see in `php_info()` in the browser.

**Comment by mipon** [comment]
```
$ php.exe -i > info.txt
```
`info.txt`
```
...
Configuration File (php.ini) Path => C:\Windows
Loaded Configuration File => C:\xampp7.2\php\php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
...
```

In browser,
![image](https://user-images.githubusercontent.com/11385613/48414546-69ba7600-e78e-11e8-832a-b3ca53a7566c.png)
![image](https://user-images.githubusercontent.com/11385613/48414565-7343de00-e78e-11e8-9755-84cde67badd2.png)

So the same configuration file seems to be loaded.

**Comment by schlessera** [comment]
Right now I assume that there might be a difference between WP-CLI behavior and Core behavior here.

The core behavior is not directly used from Core, but has been (at least partially) copied to a separate WP-CLI method: https://github.com/wp-cli/core-command/commit/02ce185f7d3e92b30e60adbcdc68e9649d72db54

This copying has happened in 2013, and the method has probably never been checked to make sure it is still in sync with current Core behavior. I'll go through this in more detail when I find the time to see whether there are deviations.
