### ISSUE TITLE
How can I get all terms(tags) from a given post ID? [HELP]

### ISSUE THREAD

**Issue by killown** [wp-cli/wp-cli#4993]
is there someway to get all terms(tags) from a given post ID?

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
