### ISSUE TITLE
Error: Extracting a zip file requires ZipArchive.

### ISSUE THREAD

**Issue by pnikolaev31** [wp-cli/wp-cli#4997]
Hello,
[root@whm test]# wp core download --skip-content --allow-root
Downloading WordPress 4.9.8 (en_US)...
Error: Extracting a zip file requires ZipArchive.
[root@whm test]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
[root@whm test]#

I got the following error. Doing strace doesn't give me a lot of information. Kindly provide me with some reasons why this can fail in a such way. Further on this I didn't saw any requirements related to ZIP...
Thanks.

**Comment by the-sides** [comment]
If anyone else is having this problem on MacOS, as dumb as it sounds, my case was that I didn't install php.
`brew install php` did the trick.

**Comment by fearoffish** [comment]
> If anyone else is having this problem on MacOS, as dumb as it sounds, my case was that I didn't install php.
> `brew install php` did the trick.

In your defense, I wouldn't call it dumb...homebrew packages that don't specify a dependency they require are ;)
