### ISSUE TITLE
Warning: Failed to create directory \'/dev/null/\': mkdir(): File exists

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#5011]
hey,

I have have an app that calls wp-cli. I didn't want it to cache the packages because of some security reasons. WP-CLI attempts to write to dev null

```
putenv("WP_CLI_CACHE_DIR=/dev/null");
putenv("WP_CLI_DISABLE_AUTO_CHECK_UPDATE=1"); // no need to have ext requests.
```

`wp core download --path=/tmp/wp5/users/t1/6/6/4/qs3_1543300866_0664/site/htdocs`;

Error: 

> Downloading WordPress 4.9.8 (en_US)...Warning: Failed to create directory \'\\/dev\\/null\\/\': mkdir(): File exists.md5 hash verified: c4e7d68b5c382fbbaf547f2b2d42c198Success: WordPress downloaded.

```
qs@ubuntu:~$ wp --info
OS:	Linux 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.32-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/qs
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.0.1

```

**Comment by schlessera** [comment]
Indeed, we should do a similar check than Composer does here: https://github.com/composer/composer/blob/master/src/Composer/Cache.php#L47-L51
