### ISSUE TITLE
WP CLI can no longer be installed on Windows

### ISSUE THREAD

**Issue by jrfnl** [wp-cli/wp-cli#5018]
Since #5001, `wp-cli` can no longer be installed on Windows.

The Posix extension which has been added as a requirement is [not available on Windows](http://php.net/manual/en/intro.posix.php), so a `composer install` will always fail.

_(unless you resort to horrible hacks like compiling an empty `php_posix.dll` for the particular PHP version you want to run wp-cli on, but that isn't really a solution at all)_

**Comment by schlessera** [comment]
Oh, that was not intentional. Let's remove that particular requirement again, then, and just make sure we're safeguarding the affected calls accordingly.

**Comment by jrfnl** [comment]
@Rarst I'm aware, but I don't think those kind of measures should need to be taken to install a tool like `wp-cli`.

**Comment by Rarst** [comment]
That was for general information, not everyone looking at the issue might. :) I concur this should be reverted, but before then ignore argument is the only way.
