### ISSUE TITLE
Make search-replace work on tables without primary keys

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#502]
Current MO (pseudo-code):

```
for $table in $tables {
  for $column in $table {
    for $row in `SELECT * FROM $table` {
      $new_value := convert($row->$column)
      `UPDATE $table SET $column=$new_value WHERE $primary_key=$row->$primary_key`
    }
  }
}
```

Proposed MO:

```
for $table in $tables {
  for $column in $table {
    for $old_value in `SELECT DISTINCT $column FROM $table` {
      $new_value := convert($old_value)
      `UPDATE $table SET $column=$new_value WHERE $column=$old_value`
    }
  }
}
```

* Pro: If there are multiple rows with the same value, we only need to do a single UPDATE query.
* Con: Probably need special handling for longtext columns like `post_content`

**Comment by danielbachhuber** [comment]
Punting on this issue as I haven't seen any support issues in the last couple of years regarding not being able to search / replace on tables without primary keys.
