### ISSUE TITLE
phar build does not pick correct pager on Windows

### ISSUE THREAD

**Issue by Rarst** [wp-cli/wp-cli#5034]
phar distribution on Windows fails on help command that calls system’s pager utility:

```
>wp --version
WP-CLI 2.0.1

>wp
'less' is not recognized as an internal or external command,
operable program or batch file.
```

It should [default to `more` on Windows platform](https://github.com/wp-cli/wp-cli/blob/a0c973927761ea84f79ac49c976931808f129e03/php/commands/src/Help_Command.php#L118-L120) but it doesn’t happen.

I've tried source checkout and it doesn't seem to have the issue.

**Comment by schlessera** [comment]
@Rarst Did you check whether your `PAGER` environment variable might have been set?

**Comment by schlessera** [comment]
Nvm, that would break on both Phar and source then.

Not sure why there would be a difference in the first place, though...

**Comment by schlessera** [comment]
Can you please try the following with both versions to see if Windows is properly detected?

```
wp eval "var_dump( WP_CLI\Utils\is_windows() );"
```

**Comment by Rarst** [comment]
Ok, that’s weird. It's not a difference between phar and source, it's a difference between directories in my system with _some_ of them having PAGER set to less. This isn't in system variables so it's probably git messing with environment or something... Ugh.

<rant>Honestly I wish WP CLI just defaulted to no pager. It's blind external dependency, there is always something wrong with it, and that breaks _help_ which is the entry point to everything.</rant> :)
