### ISSUE TITLE
Gutenberg wp rewrite issue on fresh install

### ISSUE THREAD

**Issue by sjaakbanaan** [wp-cli/wp-cli#5054]
I created a bash script to install a fresh WP on our dev server.  The last line of the script is:
`wp rewrite structure '/%postname%/' --hard`

But when I log in to this fresh WP install I can't create pages, on publish I get the following error:
`Publishing failed`
same goes for updating.

When I check the permalink structure on options-permalink.php everything seems fine. 
The only way I can fix this is by pressing the 'Save changes' button on this page. After that everything works. 

I do not have this issue with Gutenberg disabled. More info on this issue can be found here: https://github.com/WordPress/gutenberg/issues/2565

edit: I updated to the lastest version of both WP and WP CLI before testing this.

**Comment by swissspidy** [comment]
> The only way I can fix this is by pressing the 'Save changes' button on this page.

The WP-CLI equivalent for that action is `wp rewrite flush`. Have you tried that as well?

The error message `Publishing failed` can have many causes. Please debug using the Network tab in your browser's developer tools, disable all plugins, etc.

Also note that we don't provide support via GitHub. You're welcome to join our Slack channel though, see https://wp-cli.org/#support.

**Comment by schlessera** [comment]
@sjaakbanaan I cannot reproduce this, so I suppose this is due to your server environment.

If you want to get to the bottom of this, feel free to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
