### ISSUE TITLE
ramsey/array_column is abandoned

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#5061]
Do we support <5.5 ?

https://packagist.org/packages/ramsey/array_column

**Comment by szepeviktor** [comment]
Yes

https://github.com/wp-cli/wp-cli/blob/master/composer.json#L11

Why??? :)

**Comment by schlessera** [comment]
Regarding WP-CLI PHP minimum requirement: https://make.wordpress.org/cli/2019/01/15/wp-cli-php-requirements-strategy/

**Comment by schlessera** [comment]
I'd suggest just copying that single function over and then dropping it once we raise the PHP minimum past 5.5.

**Comment by schlessera** [comment]
Another option is to switch over to the `symfony/polyfill-php55` package: https://github.com/symfony/polyfill/tree/master/src/Php55

**Comment by danielbachhuber** [comment]
I think we should copy the function over.

**Comment by szepeviktor** [comment]
Yes.

**Comment by javorszky** [comment]
Is this something that we can skip requiring if the required php version is 5.5+ in composer?

**Comment by szepeviktor** [comment]
WordPress core stopped supporting <5.6
https://wordpress.org/news/2019/04/minimum-php-version-update/
