### ISSUE TITLE
Broken link on wiki homepage

### ISSUE THREAD

**Issue by thecliguy** [wp-cli/wp-cli#5065]
The link to the docs on the wiki homepage is broken: http://wp-cli.org/docs

I'm not sure what is considered to be the most appropriate link to the docs now?

**Comment by danielbachhuber** [comment]
Sorry about that! I've add a redirect for it

https://github.com/wp-cli/wp-cli.github.com/commit/6a60a6d07497243c88b60a3158458b2ac7a64b30#diff-1a523bd9fa0dbf998008b37579210e12
https://github.com/wp-cli/wp-cli.github.com/commit/8a519bbb1d3f52a21677f05336ae9553e28bceb1#diff-1a523bd9fa0dbf998008b37579210e12
