### ISSUE TITLE
"wp config create" and "wp db create" do not work if the MySQL binary is not in PATH on Windows

### ISSUE THREAD

**Issue by Hlsgs** [wp-cli/wp-cli#5076]
Obviously, I'm talking about `wp config create` without `--skip-check`.

`wp search-replace`, for example,  can work through PHP and therefore not require access to the mysql binary. Is this not the case with the above commands aswell? After all, a vanilla WP install is done purely through PHP...

**Comment by schlessera** [comment]
The thing is that `wp config create` will create or replace your WordPress installation's config file... which includes the credentials for WordPress to connect to the database. So without a configuration file, we cannot use WordPress to connect to the DB.

**Comment by schlessera** [comment]
Note. That is the reason why the `--skip-check` flag was added. We don't need a DB connection to create a configuration file, we only need it to verify that the credentials we stored in there actually work.

**Comment by Hlsgs** [comment]
@schlessera Yes, but the main issue is that `wp db create` cannot do it's work through PHP and relies on access to `mysql.exe`
