### ISSUE TITLE
Look into replacing Travis CI

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5083]
Here's where we are currently at:

- Travis CI is slow to run and hard to debug;
- Travis CI is currently broken for our automated tests and their support was not helpful in resolving the issue;
- Travis CI [has been bought](https://blog.travis-ci.com/2019-01-23-travis-ci-joins-idera-inc) by a company with somewhat questionable practices;
- Travis CI key engineers [have been laid off a few weeks after the acquisition](https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/);

I think it might be time to look into moving away from Travis CI and using a different CI for our automated testing and release deployment.

**Comment by schlessera** [comment]
@felicianotech I remember you helped us move our CircleCI scaffolding to v2.0.

- Do you think the CircleCI Open Source plan is a good fit for the WP-CLI project's requirements?
- Is the migration from Travis CI to CircleCI something you would be willing to help with?

**Comment by felicianotech** [comment]
1) I'm not sure, what are your requirements?
2) Yes

**Comment by danielbachhuber** [comment]
It should be relatively straightforward to switch from Travis to Circle. I did so on some internal projects this past month.

One gotcha though: it's more difficult to run against different PHP versions. I opted for using the [PHP compatibility sniffs](https://github.com/PHPCompatibility/PHPCompatibility) instead.

**Comment by schlessera** [comment]
> it's more difficult to run against different PHP versions

Why is that?

**Comment by danielbachhuber** [comment]
> Why is that?

I think Travis has been better about maintaining images for each PHP version. I didn't spend a ton of time on it though.

**Comment by felicianotech** [comment]
I can provide a PR for a CircleCI if if you all are still interested. Unless someone tells me no, I'll provide one sometime today (Tuesday).

**Comment by schlessera** [comment]
@felicianotech Yes, please, that would be highly appreciated. I think we should start with one of the command packages, as these should all reuse the exact same config. The framework and bundle will require special handling.

**Comment by felicianotech** [comment]
What's needed for this to run other that PHP, Composer, and MySQL? I'm running into an issue where only 20 of the 73 pass.

```
WordPress 5.1

...F----F------F---F---...F-------F----------F---F-----F----...F--F--- 70
---F------...F--F------F--F--F-----F----F-----F-------...F-------F---- 140
-----F-------------F--------F---------F-----------...F--F-----...F---- 210
--------------F---------F---------F----------F-----F---...F---F-----.. 280
.F----F---F----F---F---------------F---...F---F---...F--F---F--------- 350
-F---F----------F--F----........................................F----- 420
--F---

(::) failed steps (::)

01. $ wp core install --url='http://example.com' --title='WP CLI Site' --admin_user='admin' --admin_email='admin@example.com' --admin_password='password1' --skip-email
    
    cwd: /tmp/wp-cli-test-run-check-autoload-options-size.feature.11-5c7f1d949e22e1.01251757/
    run time: 0.10646200180054
    exit status: 255
    In step `Given a WP install'.                            # vendor/wp-cli/wp-cli-tests/features/steps/given.php:93
    From scenario `Autoloaded options are less than 900 kb'. # features/check-autoload-options-size.feature:11
    Of feature `Check the size of autoloaded options'.       # features/check-autoload-options-size.feature
```

```
73 scenarios (20 passed, 53 failed)
426 steps (73 passed, 300 skipped, 53 failed)
0m27.907s
```

**Comment by schlessera** [comment]
That looks like the `doctor-command`, so total requirements would be:
- PHP 5.4+
- MySQL (+ `mysql` binary)
- `ext-curl`
- `ext-readline`
- `ext-json`

Do you have a complete log of the test failures so I can try to see a pattern?

**Comment by felicianotech** [comment]
I was missing `mysqli`.

I'll open a PR in the doctor command repo in the next day or so.

**Comment by felicianotech** [comment]
Initial example config for the `doctor` command: https://github.com/wp-cli/doctor-command/pull/144

**Comment by danielbachhuber** [comment]
GitHub actions for the future!
