### ISSUE TITLE
Edge case of missing table `wp_blogmeta`

### ISSUE THREAD

**Issue by tristanleboss** [wp-cli/wp-cli#5085]
Hello,

We suffered an issue with our WordPress Multi-site install using WP-CLI v2.1.0

The command we use:

`php '/var/www/community/wp-installer/wp-cli.phar' --path='/var/www/community' --allow-root site list --fields=blog_id,url --format=csv 2>&1`

The result we get:

```
Erreur de la base de données WordPress Table 'community.wp_blogmeta' doesn't exist pour la requête SELECT blog_id, meta_key, meta_value FROM wp_blogmeta WHERE blog_id IN (1) ORDER BY meta_id ASC faite par include('phar://wp-installer/wp-cli.phar/php/boot-phar.php'), include('phar://wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), require('wp-includes/ms-settings.php'), ms_load_current_site_and_network, get_site_by_path, get_sites, WP_Site_Query->query, WP_Site_Query->get_sites, _prime_site_caches, update_site_cache, update_sitemeta_cache, update_meta_cache
blog_id,url
1,http://community.valeur-et-capital.intra/
2,http://community.valeur-et-capital.intra/valofi-extranet/
```

As you can see the result contains an error related to a missing table `wp_blogmeta`. This table didn't exists on our WordPress install.

The problem occured because of our deployment system: we had a version 5.0 deployed last week. When we deploy a site, we just send `wp-config.php` along with some themes and plugins and we use WP Cli `core download` function to get the latest WP files.

I don't know if the problem comes from WP-Cli or WordPress but between the 2 commands (`core download` and the one below `site list`), WordPress didn't launch its update database system (dbDelta).
WordPress files were 5.1 but the database stayed 5.0 (the blogmeta table was not created).

Is WP-Cli preventing database upgrade? In the past, I remember seeing a WordPress message in my browser when accessing a site where a database update has to be done... but what happens if no browser is used?

**Comment by swissspidy** [comment]
> but what happens if no browser is used?

Then you'd need to run `wp core update-db` after deployment.

**Comment by tristanleboss** [comment]
Okay, it does solve the problem. Maybe WP Cli should give an error ("You need to execute `wp core update-db`") when the database is not at the expected/correct version instead of trying to complete the request?

**Comment by swissspidy** [comment]
I don‘t think it‘s a good idea to show errors/warnings for every command when the DB is not up to date, especially since DB updates are usually rather rare and minor.

But perhaps we could add a command to check whether the DB version is current?

**Comment by mackensen** [comment]
Just to chime in, you see this error even when running the core database upgrade to resolve the error. If you have the upgrades scripted then the error output may lead to unexpected failures.

**Comment by mackensen** [comment]
I think the root issue is the call to `ms_load_current_site_and_network`, which ultimately triggers `_prime_site_caches`. `$update_meta_cache` is true by default, and it will fail if you haven't run the upgrade yet. Note that if I apply the patch from https://core.trac.wordpress.org/ticket/46357 I get a new error: `PHP Fatal error:  Uncaught Error: Call to undefined function __() in ../wp-includes/ms-site.php:1314`

**Comment by mackensen** [comment]
Please disregard part of my previous comment: with the core patches in place this works as expected.

**Comment by schlessera** [comment]
> But perhaps we could add a command to check whether the DB version is current?

I created a new issue for this: https://github.com/wp-cli/ideas/issues/133

I'm closing this one, as the initial problem seems to be resolved.
