### ISSUE TITLE
wp-cli shouldn't require ext-readline

### ISSUE THREAD

**Issue by ju1ius** [wp-cli/wp-cli#5092]
Hi,

I use wp-cli quite often in production environments to run custom commands that don't require user interaction, i.e. for automated deployment tasks, cron tasks etc...

Before version 2.1, I could `composer require wp-cli/wp-cli` in my project, and my commands would run fine, because they don't use the `--prompt` flag. But since 2.1 adds `ext-readline` to composer requirements, wp-cli can't be installed anymore on environments without the readline extension.

Would you consider making `ext-readline` a _soft_ dependency, so that we can continue to use non-interactive commands on environments that don't provide the readline extension ?

Thanks.

**Comment by schlessera** [comment]
Yes, I think these hard requirements cause more issues than they help. I'm open to removing them again, and add both a check in the `--prompt` and a Composer `suggest` clause instead.

Are you up for providing a PR for the above?

**Comment by danielbachhuber** [comment]
> add both a check in the `--prompt`

This already exists? https://github.com/wp-cli/wp-cli/blob/cbc8a34a7eecb2c14b921757a4a8b9c6fe7c5a22/php/WP_CLI/Dispatcher/Subcommand.php#L115-L128

**Comment by schlessera** [comment]
Ah, great, then we can just add a `suggest` section in the Composer file and that's it.
