### ISSUE TITLE
Wrong Namespace In Type Doc

### ISSUE THREAD

**Issue by XedinUnknown** [wp-cli/wp-cli#5110]
## The Problem
[`WP_CLI\Utils\make_progress_bar()`][] documents that it returns `WP_CLI\Utils\cli\progress\Bar`. This class does not exist, which causes confusion, and breaks IDE features.

## Possible Cause
The return type of `make_progress_bar()` is documented literally as `cli\progress\Bar`, which is a relative FQN. [Being inside `WP_CLI\Utils`][1], this translates into `WP_CLI\Utils\cli\progress\Bar`.

## Suggested Solution
Make the return type absolute, i.e. [`\cli\progress\Bar`][`cli\progress\Bar`].

## Remarks
Looks like the documentation of types is not very careful. Maybe it's worth running the code through a tool like [Phan][] to see if there are other mismatches in the project.

[Phan]: https://github.com/phan/phan
[`WP_CLI\Utils\make_progress_bar()`]: https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L529
[`cli\progress\Bar`]: https://github.com/wp-cli/php-cli-tools/blob/master/lib/cli/progress/Bar.php
[1]: https://github.com/wp-cli/wp-cli/blob/master/php/utils.php#L5

**Comment by schlessera** [comment]
Good catch, @XedinUnknown . Care to open a PR for this?

**Comment by XedinUnknown** [comment]
Absolutely!

**Comment by XedinUnknown** [comment]
So, [here's a report][phan_report] generated by Phan. The config used was based on [this][phan-relaxed-config], but with severity lowered to 5 (normal), quick mode disabled, and including the WP codebase in the parse (avoids false positives for "non-existing" WP entities). The bug I found is on lines 96 and 97.


[phan_report]: https://github.com/wp-cli/wp-cli/files/2999440/phan_report.txt
[phan-relaxed-config]: https://github.com/phan/phan/wiki/Tutorial-for-Analyzing-a-Large-Sloppy-Code-Base

**Comment by XedinUnknown** [comment]
@schlessera, please take a look at the new PRs. The first one addresses just the single reported issue. The second one goes through the list of problems reported by phan, and fixes those of the type-related problems which can be fixed without functional modifications.

That said, there are still multiple issues, which should be addressed in code. Some of the problems are architectural. For example, the command, sub-command, and command namespace classes should be implementing a single interfaces, and then the functions that deal with common methods would depend on that. Currently, those functions break interface segregation.

Some other reported problems can be converted by simply casting or converting used type, such as when `-1` is being passed as a value to `ini_set()`, but that expects string.

Some other problems can be ignored, such as constants not being found (they are being generated or assumed. Alternatively and preferably, they are polyfilled.

**Comment by XedinUnknown** [comment]
@schlessera, thanks for the quick review and merge.

So, now that the most surface type issues are taken care of, what of the other issues I described above? Would you consider a PR with a command interface?

**Comment by schlessera** [comment]
A command interface could be added, but we can't make it required for backward compatibility reasons. That makes the entire thing rather useless.
In general, such refactoring work should be planned for the big picture and fleshed out for a major release, I think.

**Comment by schlessera** [comment]
I'm closing this issue for now as the immediate problem was solved.
If you are interested in more high-level discussions about how the general framework could be refactored, I think the best way is to create a fresh high-level issue in the `wp-cli/ideas` repository.

**Comment by XedinUnknown** [comment]
> such refactoring work should be planned for the big picture and fleshed out for a major release

Totally. Sp, how about a `3.x` branch?
