### ISSUE TITLE
Question: Is there any user:group permissions flag?

### ISSUE THREAD

**Issue by stefanos82** [wp-cli/wp-cli#5116]
I have looked but couldn't find anything, unless it's hidden somewhere and cannot find it.

Is there any flag that lets me set or change user:group permissions during installation?

I want to avoid using chmod all the time for files and folders.

Yes, I know I can add my user in www-data group, but I wanted to have this flag as I have seen wp-cli installing a plugin or a theme as my current user for both user:group and gave me a headache until figuring it out and change permissions accordingly.

**Comment by danielbachhuber** [comment]
> I have looked but couldn't find anything, unless it's hidden somewhere and cannot find it.

It's in WordPress core, in fact.

> Is there any flag that lets me set or change user:group permissions during installation?

I think you can set the `FS_CHMOD_DIR` and `FS_CHMOD_FILE` constants: https://codex.wordpress.org/Editing_wp-config.php#Override_of_default_file_permissions

I did a skim through `WP_Upgrader`, `unzip_file()`, and `_unzip_file_ziparchive()`. It seems these constants are respected when archives are being extracted.
