### ISSUE TITLE
Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5127]
WP-CLI tests on PHP 5.4 now fail because WordPress `latest` now requires PHP 5.6+.

We need to adapt the `WP_VERSION` for the PHP 5.4 tests in Travis to `5.1` as being the last one to support PHP 5.4.

**Comment by wojsmol** [comment]
IMHO this issue can be closed.
