### ISSUE TITLE
Add command for updating wp-cli.yml files

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#515]
Similar to `git config`, it would be handy to have a command that shows and updates config settings.

For instance:

```
# Show 'require' key from some wp-cli.yml file
wp cli-config get require --config=$HOME/wp-cli.yml

# Add a path to the 'require' key
wp cli-config add require /path/to/commands-bundle/vendor/autoload.php
```

Related: #445, #514

**Comment by danielbachhuber** [comment]
At this point, I'm going to call this wontfix. Editing a YML file is pretty easy.

**Comment by XedinUnknown** [comment]
Editing is pretty easy. However, retrieving configuration that is used by WP CLI itself is not easy. I need to find out what are the values that WP CLI is going to use when run - from inside a bash script. I don't want to have to parse the YML file, and also, even if I do parse it, I have no guarantee that I will get the same result as what WP CLI will actually use. Please re-open, this is a very valuable feature - even more so now that WP CLI is becoming increasingly popular.
