### ISSUE TITLE
Adopt `WP_CLI_CS` across the `wp-cli` organization

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5179]
All `wp-cli` repos should be adapted to use and enfore the new `WP_CLI_CS` PHPCS code standard.

### Completed
- [x] https://github.com/wp-cli/export-command/issues/56
- [x] https://github.com/wp-cli/core-command/issues/110
- [x] https://github.com/wp-cli/i18n-command/issues/158
- [x] https://github.com/wp-cli/wp-cli/issues/5166
- [x] https://github.com/wp-cli/package-command/issues/106
- [x] https://github.com/wp-cli/widget-command/issues/28
- [x] https://github.com/wp-cli/rewrite-command/issues/31
- [x] https://github.com/wp-cli/wp-cli-bundle/issues/100
- [x] https://github.com/wp-cli/language-command/issues/73
- [x] https://github.com/wp-cli/entity-command/issues/248
- [x] https://github.com/wp-cli/shell-command/issues/38
- [x] https://github.com/wp-cli/checksum-command/issues/60
- [x] https://github.com/wp-cli/config-command/issues/86
- [x] https://github.com/wp-cli/role-command/issues/31
- [x] https://github.com/wp-cli/embed-command/issues/45
- [x] https://github.com/wp-cli/server-command/issues/53
- [x] https://github.com/wp-cli/db-command/issues/139
- [x] https://github.com/wp-cli/super-admin-command/issues/34
- [x] https://github.com/wp-cli/extension-command/issues/168
- [x] https://github.com/wp-cli/eval-command/issues/39
- [x] https://github.com/wp-cli/cache-command/issues/55
- [x] https://github.com/wp-cli/cron-command/issues/44
- [x] https://github.com/wp-cli/import-command/issues/51
- [x] https://github.com/wp-cli/media-command/issues/104
- [x] https://github.com/wp-cli/scaffold-command/issues/219
- [x] https://github.com/wp-cli/search-replace-command/issues/114
- [x] https://github.com/wp-cli/maintenance-mode-command/issues/4

Related #5192

**Comment by jrfnl** [comment]
I have a suspicion that there are still some repos missing from the above list. Is there a specific reason why these were excluded from this ticket ?

- [ ] [dist-archive-command](https://github.com/wp-cli/dist-archive-command)
- [ ] [doctor-command](https://github.com/wp-cli/doctor-command)
- [ ] [find-command](https://github.com/wp-cli/find-command)
- [ ] [profile-command](https://github.com/wp-cli/profile-command)
- [ ] [scaffold-package-command](https://github.com/wp-cli/scaffold-package-command)

**Comment by thrijith** [comment]
@jrfnl I think the list only contains repos, that are [part](https://github.com/wp-cli/wp-cli-bundle/blob/5e93dcdeb043e1d8eeac99942fe70264baf0c8e3/composer.json#L12-L36) of `wp-cli-bundle`.

**Comment by jrfnl** [comment]
@thrijith ... which then begs the question why the above listed commands are no part of the bundle ? :smiley:

**Comment by thrijith** [comment]
>The WP-CLI GitHub organization contains all project code repositories. Some commands are bundled with WP-CLI, while others are independently installable. Commands are bundled with WP-CLI when they’re stable, closely aligned with the project philosophy, and useful to a majority of users.

Ref: https://make.wordpress.org/cli/handbook/governance/#how-does-all-of-this-work

I think this should answer your question. 😄

**Comment by schlessera** [comment]
There are multiple possible reasons why they might not be bundled:
- abandoned, but then moved over to WP-CLI for long-term maintenance
- not mature enough
- only contextually useful

We will hoist everything we can to the new CS, but only the bundled commands are relevant for the release deadline, hence the prioritisation.

**Comment by schlessera** [comment]
This is fixed for all bundled commands and completes the requirements for the v2.2.0 release.

Work on non-bundled packages will be tracked in https://github.com/wp-cli/wp-cli/issues/5201
