### ISSUE TITLE
Make completions available in zsh

### ISSUE THREAD

**Issue by Martin1982** [wp-cli/wp-cli#518]
I'm using oh-my-zsh as my default command line tool, when adding the completion to my .zshrc the command is not recognized.

```
/Users/myusername/.composer/vendor/wp-cli/wp-cli/utils/wp-completion.bash:21: command not found: complete
```

It would be a nice feature if zsh is supported as well.

**Comment by fjarrett** [comment]
Thanks, it worked for me!

For anyone else using [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) this is what I did:

```bash
$ vagrant ssh
$ echo "autoload -U +X bashcompinit && bashcompinit" >> ~/.zshrc
$ echo "source /srv/www/wp-cli/utils/wp-completion.bash" >> ~/.zshrc
$ source ~/.zshrc
```

**Comment by jorgeorpinel** [comment]
For anyone who needs this now (that composer installation is kind of obscured in the wp-cli docs) you can still set it up by copying the contents of [master/utils/wp-completion.bash](https://github.com/wp-cli/wp-cli/blob/master/utils/wp-completion.bash) to a local ~/wp-completion.bash file, and adding these lines to .zshrc (or .zshprofile I assume, not sure, I use oh-my-shell):

```sh
# WP-CLI Bash completions
autoload bashcompinit
bashcompinit
source $HOME/wp-completition.bash
```

**Comment by aaronsmulktis** [comment]
you da man @rezzafr33

**Comment by mlopezcoria** [comment]
Thank you very much for your help @jorgeorpinel ! I made a script to install the completion into zsh (OhMyZsh!). Maybe it can be useful for anyone:

```
#! /bin/bash

printf "Downloading WP-CLI...\n"
wget -O ~/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

printf "\nInstalling \'wp\' command...\n"
chmod +x ~/wp-cli.phar
sudo mv ~/wp-cli.phar /usr/local/bin/wp

printf "\nDownloading WP-Cli zsh completion...\n"
wget -O ~/wp-completion.bash https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-completion.bash
printf '\n# WP-CLI Bash completions\nautoload bashcompinit\nbashcompinit\nsource ~/wp-completion.bash' >> ~/.zshrc
source ~/.zshrc

printf "\nWP-CLI installation done!\n"
```
Regards!
