### ISSUE TITLE
Adopt new `WP_CLI_CS` PHPCS standard in non-bundle packages 

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5201]
# In progress

- [x] [doctor-command](https://github.com/wp-cli/doctor-command) - https://github.com/wp-cli/doctor-command/issues/148 (@jrfnl)
- [x] [scaffold-package-command](https://github.com/wp-cli/scaffold-package-command) (@pattonwebz)
- [x] [find-command](https://github.com/wp-cli/find-command)  (@thrijith)
- [x] [dist-archive-command](https://github.com/wp-cli/dist-archive-command) (@sagarnasit)
- [x] [profile-command](https://github.com/wp-cli/profile-command) (@BhargavBhandari90)

# Completed

**Comment by ernilambar** [comment]
Completed. Closing ticket.
