### ISSUE TITLE
Product last modified option

### ISSUE THREAD

**Issue by mojitocup** [wp-cli/wp-cli#5224]
Hey everyone, what i am doing wrong? I want to delete all products that hasnt been updated for a while, so first im trying to list products that has not been updated for few days. So i run this:

`wp post list --post_status=published --post_type='product' --last_modified='2019-05-11' --format=ids --posts_per_page=10000`

But it seems to work only with posts, not products, how do I choose last_modified for products?

Thanks.

**Comment by schlessera** [comment]
@mojitocup I assume you mean WooCommerce products? You should contact WooCommerce support regarding this, as they are the ones providing and supporting the WooCommerce WP-CLI integration.

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
