### ISSUE TITLE
Add option to allow wp-cli to trigger wp_admin

### ISSUE THREAD

**Issue by joeldeteves** [wp-cli/wp-cli#5225]
## Feature Request

 

- ✅ Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Reference issue: #984

Given that we host a large number of Wordpress sites, I have run into certain plugins / themes that require wp_admin in order for updates to be detected, or in the case of the original issue, to activate plugins. One such theme is Divi, which is a very popular theme used across a [large percentage](https://trends.builtwith.com/framework/Divi) of Wordpress sites.

Currently, the workaround per the originally closed issue is to create a php file containing `define( 'WP_ADMIN', true );` and use `--require=file.php` however this presents a clear security risk. A somewhat hacky workaround is to create and delete the file when executing wp-cli via a  script, but this is unreliable at best and the implications of failure could lead to unwanted privilege escalation.

**Describe the solution you'd like**

wp-cli should have a switch / option that allows triggering WP_ADMIN on run, e.g: `wp theme list --admin=true`

Thank you in advance for your consideration,

**Comment by swissspidy** [comment]
Previously: #984, #674.

**Comment by danielbachhuber** [comment]
This is now implemented with the `--context=` global argument https://github.com/wp-cli/wp-cli/pull/5581
