### ISSUE TITLE
Configure Dependabot for managing dependencies

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5232]
GitHub [acquired Dependabot](https://dependabot.com/blog/hello-github/) and all of its features are free. I've removed Dependencies.io — we should switch over to Dependabot.

**Comment by schlessera** [comment]
I configured Dependabot to run over all repositories.

It works a bit differently then Dependencies.io, so we'll have to wait and see whether this needs additional tweaking down the line...

**Comment by danielbachhuber** [comment]
Great, thanks!
