### ISSUE TITLE
Undefined constant STDERR & fwrite() 

### ISSUE THREAD

**Issue by chetansatasiya** [wp-cli/wp-cli#5237]
Hey I am running a site on a subdirectory called `resources` and I am trying to run the CLI command via the PHP.

`shell_exec("/usr/local/bin/wp --path='/home/test/public_html/resources/' plugin list --status=active >> /home/test/public_html/resources/wp-content/test.log 2>&1");`

But, I am not sure I am getting below errors.

- [11-Jun-2019 17:41:30 UTC] PHP Notice:  Use of undefined constant STDERR - assumed 'STDERR' in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Loggers/Regular.php on line 41
- [11-Jun-2019 17:41:30 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Loggers/Base.php on line 64
- [11-Jun-2019 17:41:30 UTC] PHP Notice:  Use of undefined constant STDERR - assumed 'STDERR' in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils-wp.php on line 122
- [11-Jun-2019 17:41:30 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, string given in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils-wp.php on line 122
- [11-Jun-2019 17:41:30 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Loggers/Regular.php:41) in /home/test/public_html/resources/wp-includes/pluggable.php on line 1251
- [11-Jun-2019 17:41:30 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Loggers/Regular.php:41) in /home/test/public_html/resources/wp-includes/pluggable.php on line 1254

Can someone help me here if I am doing anything wrong here?

Many Thanks

**Comment by ovidiul** [comment]
You should check if you have php CLI support enabled, so try and run this code

```
echo "STDERR DEFINED: ".shell_exec("php -r \"echo defined('STDERR');\"");
echo "<br />\n";
//print_r(getenv());
echo "PHP SAPI HANDLER: ".php_sapi_name();
echo "<br />\n";
echo "PHP Version: ".shell_exec('php -v');
echo "<br />\n";
```

here is my output:

STDERR DEFINED: 1
PHP SAPI HANDLER: apache2handler
PHP Version: PHP 7.2.1 (cli) (built: Jan 15 2018 12:20:50) ( NTS ) Copyright (c) 1997-2017 The PHP Group Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies 


STDERR, STDIN, STDOUT are only defined in CLI SAPI

You could use

`putenv("WP_CLI_PHP=/Applications/MAMP/bin/php/php7.2.1/bin/php");
`
before your shell_exec call to define where your php cli should point to

Hope it helps
