### ISSUE TITLE
Debian .deb package build process broken and latest version 2.1.0 is incompatible with php7.2-mysql

### ISSUE THREAD

**Issue by martingoldie** [wp-cli/wp-cli#5239]
Not related to a specific command. This issue is only about the deb package compatibility.

- [x] Yes, I reviewed the [contribution guidelines]
- [x] Yes, more specifically, I reviewed the guidelines on how to write clear bug reports

**Summary:**

The deb package build process appears to be broken as there is no `2.2.0` version and the package dependencies do not allow for `php7.2-mysql` or `php7.3-mysql` as it requires one of `php5-mysql | php5-mysqlnd | php7.0-mysql | php7.1-mysql`

I'm running Debian 9 Stretch but this would apply to any OS using .deb packages.
The latest build found here (https://github.com/wp-cli/builds/tree/gh-pages/deb) is `php-wpcli_2.1.0_all.deb` and the "latest" https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_latest_all.deb is a symbolic link to `php-wpcli_2.1.0_all.deb`

The checklist https://github.com/wp-cli/wp-cli/issues/5204#issue-436951487
shows that the deb build should have been triggered so this must be broken.

> ### Updating the Debian and RPM builds
> * [x]  Trigger Travis CI build on [wp-cli/deb-build](https://github.com/wp-cli/deb-build)

Since the build script `utils/wp-cli-updatedeb.sh` which is mentioned in some docs was removed we can no longer see what the dependencies are to offer a pull request. As far as I can tell it shows as the following:

`Depends: php5-cli (>= 5.4) | php-cli | php7-cli, php5-mysql | php5-mysqlnd | php7.0-mysql | php7.1-mysql, mysql-client | mariadb-client`

This was mentioned in [this comment](https://github.com/wp-cli/wp-cli/issues/5204#issuecomment-486562351) but because it referenced Debian buster and daily builds, I feel like the rest of the comment regarding dependency issues and not having any info on what has replaced the previous deb build scripts was ignored. Can we make this more visible so we can offer pull requests and have an easier time trouble shooting when there is an issue?

**Steps to reproduce:**

1. Use curl or wget to download https://raw.githubusercontent.com/wp-cli/builds/gh-pages/deb/php-wpcli_latest_all.deb

2. Try to install it on Debian.
```
sudo` dpkg -i /tmp/php-wpcli_2.1.0_all.deb
(Reading database ... 156161 files and directories currently installed.)
Preparing to unpack /tmp/php-wpcli_2.1.0_all.deb ...
Unpacking php-wpcli (2.1.0) over (2.1.0) ...
dpkg: dependency problems prevent configuration of php-wpcli:
 php-wpcli depends on php5-mysql | php5-mysqlnd | php7.0-mysql | php7.1-mysql; however:
  Package php5-mysql is not installed.
  Package php5-mysqlnd is not installed.
  Package php7.0-mysql is not installed.
  Package php7.1-mysql is not installed.

dpkg: error processing package php-wpcli (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 php-wpcli
```

What PHP environment does WP-CLI run in?

PHP7.2

**Describe what you expect as the correct outcome**

The latest deb package build should be able to be installed when running `php7.2-mysql` or `php7.3-mysql`.

**Let us know what environment you are running this on**

Debian 9 Stretch

**Provide a possible solution**

Support for `php7.2-mysql` and `php7.3-mysql` should be added to the deb build script `Depends:`.

**Results and impacts**

Severity – High (in relation to .deb package being not workable but using the phar workaround makes this severity low for those able to do that)

Expected Results: The latest deb package build is able to be installed when running` php7.2-mysql` or `php7.3-mysql`.

Actual Results: It is not possible to use the latest deb package with `php7.2-mysql` or `php7.3-mysql`.

Workaround: Use phar build instead until this has been fixed.

**Comment by schlessera** [comment]
There is a debian package for v2.2.0 now that should also allow for PHP 7.2 and PHP 7.3.

I'm closing this as I assume this works as expected now. Please reopen in case there's still an issue here.
