### ISSUE TITLE
Top level themes/functions.php file breaks `--skip-themes`

### ISSUE THREAD

**Issue by austinginder** [wp-cli/wp-cli#5240]
For compatibility I'm using  `--skip-themes` when fetching plugin details. The actual command I run looks like this `wp plugin list --format=json --skip-themes --skip-plugins --skip-packages --fields=name,title,status,version`. However this issue looks more generic. Here are steps to reproduce.

1. Create an empty WordPress 5.5.2 site running WP-CLI 2.2.0
2. Create a `functions.php` file with a syntax error or an undefined function like `<?php genesis_register_sidebar();` and place under /wp-content/themes/
3. Attempt to run `wp plugin list --skip-themes`

I'd expect this to work as it's skipping themes however it seems functions.php is special and gets triggered resulting in the following output.

```
PHP Fatal error:  Uncaught Error: Call to undefined function genesis_register_sidebar() in /Users/username/Sites/wordpress/wp-content/themes/functions.php:3
Stack trace:
#0 /Users/username/Sites/wordpress/wp-settings.php(499): include()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1209): require('/Users/austingi...')
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1130): WP_CLI\Runner->load_wordpress()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in /Users/username/Sites/wordpress/wp-content/themes/functions.php on line 3
Fatal error: Uncaught Error: Call to undefined function genesis_register_sidebar() in /Users/username/Sites/wordpress/wp-content/themes/functions.php:3
Stack trace:
#0 /Users/username/Sites/wordpress/wp-settings.php(499): include()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1209): require('/Users/austingi...')
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1130): WP_CLI\Runner->load_wordpress()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in /Users/username/Sites/wordpress/wp-content/themes/functions.php on line 3
Error: The site is experiencing technical difficulties.

```

**Comment by danielbachhuber** [comment]
@austinginder @brandonpayton Here's a Behat scenario that reproduces the issue:

```
  Scenario: Avoid loading index.php when --skip-themes is included
    Given a WP installation
    And a wp-content/themes/functions.php file:
      """
      <?php
      wp_cli_function_doesnt_exist_5240();
      """

    When I run `wp --skip-themes plugin list`
    Then STDOUT should be:
      """
      http://example.org/
      """
    And STDERR should be empty
```

When WP-CLI includes `--skip-themes`, it returns an empty string for the `template` and `stylesheet` options:

https://github.com/wp-cli/wp-cli/blob/a71167e1030462275a48c419854261efceba11e3/php/WP_CLI/Runner.php#L1751-L1755

However, it seems WordPress still defines `TEMPLATEPATH` and `STYLESHEETPATH` with these empty strings:

https://github.com/WordPress/wordpress-develop/blob/6222a118c9b87ca9f5703b5055831457469627b7/src/wp-includes/default-constants.php#L393-L405

And then the paths are loaded anyway:

https://github.com/WordPress/wordpress-develop/blob/6222a118c9b87ca9f5703b5055831457469627b7/src/wp-settings.php#L589-L593

This is how the `wp-content/themes/functions.php` file ends up loaded.

There doesn't seem to be a great way to null out `wp_get_active_and_valid_themes()`:

https://github.com/WordPress/wordpress-develop/blob/6222a118c9b87ca9f5703b5055831457469627b7/src/wp-includes/load.php#L925-L966

Let's continue the conversation on this core ticket: https://core.trac.wordpress.org/ticket/57928

**Comment by brandonpayton** [comment]
@danielbachhuber, we ran into a different case today with `--skip-themes` leading to a PHP fatal because WP was able to look up the current theme anyway and tried to auto-include it's block patterns here:
https://github.com/WordPress/wordpress-develop/blob/52f05444bab8659076a3cd6b5282ea44af44da86/src/wp-includes/block-patterns.php#L474

This led to a fatal because the pattern(s) depended on theme functions that did not exist.

Initially, I viewed this as a core bug and started thinking about what a good fix would look like. But the more I thought about it, the more it seemed like having _some_ theme is a reasonable expectation of WordPress. What if we pivoted here and had WP-CLI provide a bare-bones, do-nothing sort of theme that is used by WP when `--skip-themes` is enabled? Would that make sense and remove these tricky situations where we want WordPress to be OK with not having a stylesheet/template defined?

**Comment by danielbachhuber** [comment]
> But the more I thought about it, the more it seemed like having _some_ theme might be a reasonable expectation of WordPress.

@brandonpayton I'm not so sure. Core has `wp_using_themes()` (https://github.com/WordPress/wordpress-develop/blob/1825c75f886f2b1ab4d2bbb3cae74ce6eb18df3e/src/wp-includes/load.php#L1575-L1591), which I think is an argument in favor of https://github.com/WordPress/wordpress-develop/pull/4409

`wp_using_themes()` came with https://core.trac.wordpress.org/ticket/44458, which is in the related territory.

**Comment by brandonpayton** [comment]
Thanks for your feedback and the links, @danielbachhuber. Given the presence of `wp_using_themes()`, it seems reasonable for core to have to confirm that themes are in use before eagerly including theme PHP files. :)  I plan to file a core bug and hopefully a patch for the block pattern loading logic.

**Comment by danielbachhuber** [comment]
It seems like too much of a rabbit hole to fix upstream, so I'm going with the more helpful error message approach: https://github.com/wp-cli/wp-cli/pull/5817
