### ISSUE TITLE
1045: Access denied for user

### ISSUE THREAD

**Issue by alferx** [wp-cli/wp-cli#5253]
Hello,
  I found a strange situation.
Migrating my WP site 5.2 to a new server (Ubuntu 18.04.2):
1. the webserver Apache2 serves my WP website correctly
2. trying connection using mysql client `mysql -u wol -h localhost -ptest` I can connect to the database

Here is some more info about mysql:
```
$ mysql -V
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

# mysql -e 'SHOW VARIABLES LIKE "%version%"'
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.7.26                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| tls_version             | TLSv1,TLSv1.1           |
| version                 | 5.7.26-0ubuntu0.18.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | Linux                   |
+-------------------------+-------------------------+
```

But I want to use wp-cli, so I installed it on the new server

```
$ wp --info
OS:	Linux 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.2
PHP version:	7.2.19-0ubuntu0.18.04.1
php.ini used:	/etc/php/7.2/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/wol/
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.2.0
```

Issuing in example:
```
$ wp core version
5.2.2
```

NOW, the `wp-config.php` contains the right entries:
```
define('DB_NAME', 'my_wp');
define('DB_USER', 'wol');
define('DB_PASSWORD', 'test');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
```

**but issuing any db oriented command, got always this _access denied_ error**
```
$ wp db check
mysqlcheck: Got error: 1045: Access denied for user 'wol'@'localhost' (using password: YES) 
```

I really don't understand why...
Any suggestion?

**Comment by schlessera** [comment]
There's lots of suggestions on how to diagnose this problem here: https://stackoverflow.com/questions/10299148/mysql-error-1045-28000-access-denied-for-user-billlocalhost-using-passw

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
