### ISSUE TITLE
Undefined index: HTTPS

### ISSUE THREAD

**Issue by sebastienserre** [wp-cli/wp-cli#5254]
Hello

I have this message with wp-cli 2.2.2
`PHP Notice:  Undefined index: HTTPS in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1169) : eval()'d code on line 106

Notice: Undefined index: HTTPS in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1169) : eval()'d code on line 106
`
wp cache flush and also wp search-replace

**Comment by schlessera** [comment]
@sebastienserre You seem to be trying to read `$_SERVER['HTTPS']` from your `wp-config.php` file.

See https://make.wordpress.org/cli/handbook/common-issues/#php-notice-undefined-index-on-_server-superglobal for more information on why that doesn't work within WP-CLI context.
