### ISSUE TITLE
Clarify distinction between issues suited for `wp-cli/wp-cli` and `wp-cli/ideas`

### ISSUE THREAD

**Issue by iandunn** [wp-cli/wp-cli#5255]
The feature request template says that ["a more general idea"](https://github.com/wp-cli/wp-cli/blame/6ce3adb162ea013e12716b4c1be21e20956606ec/.github/ISSUE_TEMPLATE/2-FEATURE_REQUEST.md#L48) is better suited for `wp-cli/ideas`, but I'm not really sure what that means, specifically. It's vague enough that I can imagine lots of issues fitting in either repo.

It'd be helpful to explicitly state the specific criteria that determine which repo an issue should go in, and provide some examples.

**Comment by schlessera** [comment]
Yes, I agree, that could be better phrased, indeed.

I think the main distinction is whether it is something directly related to an existing package (adding a parameter to a command, changing the behavior of a command, adding a subcommand to an existing main command, ...) or whether it is something that would go into a separate, new package, or would need discussion about what package to go into first.
