### ISSUE TITLE
2.3.0 Undefined index: host in phar

### ISSUE THREAD

**Issue by janw-me** [wp-cli/wp-cli#5264]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Every wp command I run over `@vvv` will throw a notice (twice).
 > PHP Notice:  Undefined index: host in phar:///home/janw/.local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/[FileCache.php on line 363
](https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/FileCache.php#L363)

I run: `wp @vvv option get home`
```
PHP Notice:  Undefined index: host in phar:///home/janw/.local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/FileCache.php on line 363
PHP Notice:  Undefined index: host in phar:///home/janw/.local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/FileCache.php on line 363
http://cultuurbedrijfnop.test
```

`wp-cli.yml` of project:
```
@vvv:
   ssh:  vagrant
   path: /srv/www/cultuurbedrijfnop/public_html
   url: cultuurbedrijfnop.test
@live:
   ssh: ********@ ********.nl
   path: /var/www/vhosts/ ********/cultuurbedrijfnop.nl/public_html
   url: cultuurbedrijfnop.nl
```

`wp --info` ( on host machine)
```
OS:	Linux 5.0.0-23-generic #24-Ubuntu SMP Mon Jul 29 15:36:44 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.8-1+ubuntu19.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/janw/Webdev/vagrant-local/www/cultuurbedrijfnop
WP-CLI packages dir:	/home/janw/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	/home/janw/Webdev/vagrant-local/www/cultuurbedrijfnop/wp-cli.yml
WP-CLI version:	2.3.0
```

**Possible solution**

A simple `isset($url_parts['host'] )` check should solve the notice but I don't know is this also has other implications.

**Screenshots**
![wp notice](https://user-images.githubusercontent.com/1026882/63009464-d8933f80-be84-11e9-969c-9f22bf083385.png)

A small var_dump notice I added to the file to provide more info.

**Comment by johnbillion** [comment]
I'm also seeing this issue.
