### ISSUE TITLE
error_to_string() should support exceptions too

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#5267]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When calling `WP_CLI::error( $message )`, either a string or a `WP_Error` instance can be passed in as the message, and the `WP_CLI::error_to_string( $errors )` method handles the conversion to string, including its error data as necessary.

It would be great if `Exception` instances were supported too, so you could write code such as:

```php
try {
    ...
} catch ( Exception $e ) {
    WP_CLI::error( $e );
}
```

**Comment by schlessera** [comment]
Yes, that looks useful. I'll gladly accept PRs for the above.
