### ISSUE TITLE
Incorrect PHPDoc for Formatter::display_items()

### ISSUE THREAD

**Issue by mundschenk-at** [wp-cli/wp-cli#5269]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The PHPDoc annotation for the `$items` parameter states `array`, when from the code and usage in core commands it is clear that it also supports instances of `Iterator`.

**Provide a possible solution**

The annotation should be changed to `array|\Iterator`.

**Comment by schlessera** [comment]
Yes, indeed. Are you open to providing a pull request for this change, @mundschenk-at ?

**Comment by mundschenk-at** [comment]
Sure.
