### ISSUE TITLE
install-wp-tests.sh: Using GNU sed on macOS results in a syntax error

### ISSUE THREAD

**Issue by noriods** [wp-cli/wp-cli#5285]
## Bug Report

On macOS, if you've installed GNU sed using Homebrew (and have it in your path), running install-wp-tests.sh fails because of these lines:

```
        # portable in-place argument for both GNU sed and Mac OSX sed
        if [[ $(uname -s) == 'Darwin' ]]; then
                local ioption='-i .bak'
        else
                local ioption='-i'
        fi
```

## To replicate:

- Run macOS.
- Install GNU sed via Homebrew.
- Add it to your $PATH variable.
- Refresh $PATH by opening a new terminal.
- Run `bin/install-wp-tests.sh wordpress_test username 'password' localhost latest`
  - Replace "username" with MySQL username.
  - Replace "password" with MySQL password.

You'll get this error at the end of the command output:

```
+ sed -i .bak 's:dirname( __FILE__ ) . '\''/src/'\'':'\''/tmp/wordpress/'\'':' /tmp/wordpress-tests-lib/wp-tests-config.php
sed: -e expression #1, char 1: unknown command: `.'
```

## Proposed solution

There are probably smarter ways to do this but maybe this could work:

- Run `where sed`
- Check for `gnu-sed`
- If that's there AND the platform is Darwin, then use the GNU syntax. Otherwise use the macOS syntax.

**Comment by schlessera** [comment]
@noriods I'm not sure what you are referring to here, this repository does not have a `bin/install-wp-tests.sh` file.

Are you referring to the scaffolded tests that are created via [`wp-cli/scaffold-command`](https://github.com/wp-cli/scaffold-command)? Or are you referring to WordPress Core?

**Comment by noriods** [comment]
> Are you referring to the scaffolded tests that are created via wp-cli/scaffold-command? Or are you referring to WordPress Core?

Whoops, most likely. I don't remember though. Haven't worked on that project in a while.
