### ISSUE TITLE
Send `WP_CLI_SSH_PRE_CMD` warning to STDERR

### ISSUE THREAD

**Issue by ocean90** [wp-cli/wp-cli#5288]
The warning when `WP_CLI_SSH_PRE_CMD` is set is currently sent to STDOUT:

https://github.com/wp-cli/wp-cli/blob/f731dd5c34f2222c94350d672198f179a1b3b069/php/WP_CLI/Runner.php#L422-L430

This becomes an issue when you use `wp post create --porcelain` as the warning will be part of the output.

Example:
```sh
$ HOME_PAGE_ID=`wp $ALIAS post create --post_title=Home --post_status=publish --post_type=page --porcelain`
$ echo $HOME_PAGE_ID
WP_CLI_SSH_PRE_CMD found, executing the following command(s) on the remote machine:
export PATH=/opt/php72/bin/:$PATH
4
```

Maybe we can remove the colorizing and switch to `WP_CLI::warning()`?

**Comment by schlessera** [comment]
Yes, I agree, turning this into a `WP_CLI::warning()` instead is the easiest fix.
