### ISSUE TITLE
Can't save the output

### ISSUE THREAD

**Issue by NicolasKulka** [wp-cli/wp-cli#5292]
Hello,

Command : 'wp core verify-checksums'

It is impossible for me to recover the return of this order, it is directly displayed.

Output with choice of format for example, same as commande 'wp plugin verify-checksums'

Do you have an idea to solve this problem?

**Comment by chesio** [comment]
Hi @NicolasKulka,

the command `wp core verify-checksums` outputs any errors/warnings to stderr, so you have to capture them with `wp core verify-checksums 2> output.log` or redirect stderr to stdout if you want to capture both error and success messages: `wp core verify-checksums 1> output.log 2>&1`.

See also: https://make.wordpress.org/cli/handbook/shell-friends/#save-command-output
