### ISSUE TITLE
search-replace not working with Gutenberg blocks

### ISSUE THREAD

**Issue by despecial** [wp-cli/wp-cli#5293]
Currently we pull the database from a production page to develop environment.
After import we run this commmand to update to local urls
`wp search-replace production_url local_url`

The problem seems to be the way Gutenberg stores values.
URLs are escaped and become:
`https:\/\/www.domain.com`

So I ask myself: should wp cli run twice or use two wp search-replace commands?
`wp search-replace https://www.production_url https://local_url`
`wp search-replace https:\/\/www.production_url https:\/\/local_url`

**Comment by stuartcusackie** [comment]
Can confirm. These \/\/ strings are definitely causing problems for my sync script.

Perhaps --regex-flags=<regex-flags> could be utilised somehow?

**Comment by Jeppeskovsgaard** [comment]
I ran into the same issue. I can confirm that using double quotes around the urls are necessary for the command to work.

**Comment by planetahuevo** [comment]
Will simple quotes work here too or they need to be double ones?

**Comment by drzraf** [comment]
1. Should be opened against https://github.com/wp-cli/search-replace-command (dup' of https://github.com/wp-cli/search-replace-command/issues/126)
2. I think Gutenberg's block JSON could deserves a specific treatment from search-replace (parsing the json, replacing the attributes array recursively and regenerating the corresponding markup [if even possible])

**Comment by lukechinworth** [comment]
I usually search-replace the domain,`wp search-replace www.production.url local.url`

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/search-replace-command/issues/186
