### ISSUE TITLE
possible to trigger a button click of a plugins settings page or function?

### ISSUE THREAD

**Issue by kmob2** [wp-cli/wp-cli#5294]
Hello,

I’m installing and activating a plugin via WP CLI. The plugin then requires me to enter a license key. I’m able to add the license key via `wp option update` however when I log into WP admin panel, I see the license key is entered but not activated. The plugin requires me to click the button in the settings page “Activate License” so it runs a function that verifies the license key. Looking at the code of the plugin, the “Activate License” button triggers a function in a class that looks something like the below code.

Is it possible to trigger a button click of a plugins settings page or function containing $_POST information via WP CLI? Any hints, links or references to which WP CLI command could be used would be helpful.

I've read a few comments here where people asked similar questions and all official replies were something like "we don't believe in premium plugins", "everything should be GPL" and therefore ignores the question. Keep in mind there are many GPL plugins that need an API key for 3rd party services, such as Akismet and still require a one time activation in the settings page. Also many other plugins that don't require any keys also require WP admins to "click" a button after activating the plugin, to get the plugin going. (really simple SSL plugin for example).

I'm simply looking for a way on how WP-CLI can trigger a function of a plugin from a settings page.

```
// Stripped down version of the function that is called when clicking the “Activate License” button
function activate_license() {

if ( isset( $_POST[$this->plugin_name . '_license_activate'] ) ) {

    if ( !check_admin_referer( $this->plugin_name . '_license_nonce', $this->plugin_name . '_license_nonce' ) )
        return;

        $license = sanitize_text_field ($_POST[$this->plugin_name . '_license_key'] );
		
        // runs code to connect to 3rd party server to verify license key

        // $license_data->license will be either "valid" or "invalid"
update_option( $this->plugin_name . '_license_status', $license_data->license );

    }
}

```

**Comment by chesio** [comment]
Hi @kmob2,

you can try to execute the function via `wp eval` command:
```bash
wp eval 'activate_license();'
```

Note that this works only if the function is declared in global scope.

**Comment by schlessera** [comment]
Clicking the button would require building up the page in a browser, which is beyond the scope of WP-CLI.

You can indeed run the function through `wp eval`, but you'll need to set the `$_POST` variable to your key first:

```php
wp eval '$_POST['XYZ_license_activate'] = '<license>'; activate_license();'
```

Adapt `XYZ` with the proper plugin name (and don't it from your issue) and `<license>` with the actual license value.

**Comment by schlessera** [comment]
Also, I'm closing this issue now.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
