### ISSUE TITLE
Dependencies when not using Apache for WorpPress

### ISSUE THREAD

**Issue by kryltsov** [wp-cli/wp-cli#5299]
wp-cli requires php, which is, in turn, requires httpd.

https://src.fedoraproject.org/rpms/wp-cli/blob/master/f/wp-cli.spec#_13 
Requires:   php-cli, php-common, php, php-json

Do you really need php package?

If you run WordPress via Nginx + PHP-FPM you end up with Apache being installed.

Thank you

**Comment by blackfile** [comment]
Thanks @kryltsov it makes sense, I'm going to work on that issue

**Comment by schlessera** [comment]
I think the actual issue here is that `php` requires `httpd`. That does not make any sense. Why would a programming language only work when a specific web server is installed...?

**Comment by kryltsov** [comment]
This is beyond our reach :) If wp-cli only requires php-cli this should be the case.

**Comment by danielbachhuber** [comment]
Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
