### ISSUE TITLE
Fatal error: Declaration of WP_UnitTestCase::assertNotFalse

### ISSUE THREAD

**Issue by fpilee** [wp-cli/wp-cli#5315]
```bash
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Fatal error:  Declaration of WP_UnitTestCase::assertNotFalse($condition, $message = '') must be compatible with PHPUnit\Framework\Assert::assertNotFalse($condition, string $message = ''): void in /tmp/wordpress-tests-lib/includes/testcase.php on line 14

Fatal error: Declaration of WP_UnitTestCase::assertNotFalse($condition, $message = '') must be compatible with PHPUnit\Framework\Assert::assertNotFalse($condition, string $message = ''): void in /tmp/wordpress-tests-lib/includes/testcase.php on line 14
```
I used wpcli to scaffold theme tests and I have installed tests libs
`php wp-cli.phar scaffold theme-tests my-theme`
`bin/install-wp-tests.sh wp-tests homestead secret`

but when I run phpunit I have that error.

homestead release
php 7.3.9
phpunit 7.0.3 phpunit 7.3.* 7.4.* 7.5.*

```php
$ tail /tmp/wordpress-tests-lib/includes/testcase.php
        <?php

require_once dirname( __FILE__ ) . '/abstract-testcase.php';

/**
 * Defines a basic fixture to run multiple tests.
 *
 * Resets the state of the WordPress installation before and after every test.
 *
 * Includes utility functions and assertions useful for testing WordPress.
 *
 * All WordPress unit tests should inherit from this class.
 */
class WP_UnitTestCase extends WP_UnitTestCase_Base {

        /**
         * Asserts that a condition is not false.
         *
         * This method has been backported from a more recent PHPUnit version, as tests running on PHP 5.2 use
         * PHPUnit 3.6.x.
         *
         * @since 4.7.4
         *
         * @param bool   $condition Condition to check.
         * @param string $message   Optional. Message to display when the assertion fails.
         *
         * @throws PHPUnit_Framework_AssertionFailedError
         */
        public static function assertNotFalse( $condition, $message = '' ) {
                self::assertThat( $condition, self::logicalNot( self::isFalse() ), $message );
        }
}






```

**Comment by fpilee** [comment]
it only works with phpunit 5

**Comment by UVLabs** [comment]
Had to use PHP Unit 5.x though the wp develop library mentions it being compatible up to PHP Unit 7.x

**Comment by tylercollier** [comment]
I'm on WP 5.5.6.

I was seeing this error when I had run the `wp scaffold plugin-tests` in the wrong directory and didn't have a `phpunit.xml.dist` file where I was running `phpunit` from, and thus the code in my `tests/bootstrap.php` file was never run. After moving my files like `phpunit.xml.dist` and `bootstrap.php` to where they needed to go, the error disappeared.

---

Another clue: the first problem I ran into, before the one mentioned by the OP, was this:

```
PHP Fatal error:  Uncaught Error: Class 'WP_UnitTestCase' not found in /www/wp-content/plugins/ifound/tests/test-sample.php:11
```

To fix that, I added this line to the top of `test-sample.php`:

```php
require_once '/tmp/wordpress-tests/lib/includes/testcase.php';
```

I mention this because this probably should have been a sign that I was doing something wrong to begin with. After putting files in the right place as mentioned above, that line is not necessary.

**Comment by kavyaimversion** [comment]
Im also experiencing same issue
 ./vendor/bin/phpunit --version
**PHPUnit 7.5.20** by Sebastian Bergmann and contributors.


Any help is appreciated

**Comment by UVLabs** [comment]
> Im also experiencing same issue ./vendor/bin/phpunit --version **PHPUnit 7.5.20** by Sebastian Bergmann and contributors.
> 
> Any help is appreciated

@kavyaimversion see my comment above 

"Had to use PHP Unit 5.x though the wp develop library mentions it being compatible up to PHP Unit 7.x" I dont know if this still stands but thats what i had to do

**Comment by kavyaimversion** [comment]
yes i did see that lemme try the 5.x version thanks @UVLabs

**Comment by kavyaimversion** [comment]
I did try 5.7 version still facing same issue :(

**Comment by kavyaimversion** [comment]
> 

Can you please help me in understanding what is test-sample.php exactly

**Comment by kavyaimversion** [comment]
@tylercollier  
Can you please help me in understanding what is test-sample.php exactly like you mentioned in your comment
in that path i dont see this test
/tmp/wordpress-tests/lib/includes/testcase.php';
