### ISSUE TITLE
WP_CLI::launch hangs forever

### ISSUE THREAD

**Issue by tillkruss** [wp-cli/wp-cli#5323]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I'm trying to run `WP_CLI::launch()` with `redis-cli` as argument, but the process seems to hang and can't be cancelled with `<cmd>+c`.

There are no log entries and `--debug` doesn't show anything either.

When I run `redis-cli` by itself in the terminal it connects fine and acts similar to `wp shell`.

**Describe how other contributors can replicate this bug**

Make sure Redis and `redis-cli` is installed on the system and then just run:

```php
WP_CLI::launch('redis-cli');
WP_CLI::launch('redis-cli -h 127.0.0.1 -p 6379 -n 0');
```

**Describe what you expect as the correct outcome**

I expect the `redis-cli` process to take over I/O as described.

**Let us know what environment you are running this on**

```log
wp cli info
OS:	Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct 23 18:29:05 PDT 2019; root:xnu-6153.41.3~44/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/bin/php
PHP version:	7.3.12
php.ini used:	/usr/local/etc/php/7.3/php.ini
WP-CLI root dir:	/Users/<snip>/.composer/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	/Users/<snip>/.composer/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Provide additional context/screenshots**

I've tried various parameters `--raw`, `--no-raw` as well the 2nd and 3rd parameter of `WP_CLI::launch()` without any luck.

Is there maybe a PHP extension missing?

**Comment by danielbachhuber** [comment]
@tillkruss Were you ever able to figure this one out?

**Comment by tillkruss** [comment]
No we use `proc_open_compat` instead.

**Comment by danielbachhuber** [comment]
Sounds good 👍
