### ISSUE TITLE
Error when creating an alias.

### ISSUE THREAD

**Issue by PieterT2000** [wp-cli/wp-cli#5327]
When I try to create an alias, I get an error. (see printscreen) Any thoughts on how to solve this problem?
![image](https://user-images.githubusercontent.com/47913749/70805018-3f375400-1db8-11ea-8f73-cc69ba474600.png)

**Comment by johnbillion** [comment]
I'm seeing this issue too. Haven't done any debugging yet.

**Comment by johnbillion** [comment]
It looks like this error occurs when the `~/.wp-cli/config.yml` file doesn't yet exist. I `touch`ed the file and then the `wp cli alias add` command worked as expected.

**Comment by schlessera** [comment]
Yes, I noticed that, too. WP-CLI should create an empty default file as needed here.

**Comment by PieterT2000** [comment]
@johnbillion Thanks a lot! This did the trick for me too.
