### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'WP_CLI\Fetchers\User' not found in /WP_CLI/Runner.php

### ISSUE THREAD

**Issue by kemal-amsterdam** [wp-cli/wp-cli#5328]
Except the abstract Base class in Fetchers folder, all other files were removed since version 1.2.0,
but Runner.php still contain a line that try to instantiate a new object of type \WP_CLI\Fetchers\User.

The fatal error happens if the command line is invoked with --user='any-name' and the constant WP_INSTALLING has not been defined. 

Note: WP_INSTALLING is a constant which gets defined by Wordpress when it start installation for a fresh site.

**Comment by mikeschinkel** [comment]
Yes. I just experienced the same issue, except I was not using the `--user` switch.
