### ISSUE TITLE
Compatibility with LSPHP

### ISSUE THREAD

**Issue by tristanleboss** [wp-cli/wp-cli#5329]
Using LSPHP to execute wp-cli.phar leads to many warnings/errors:

```
#!/usr/bin/env php
PHP Warning:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///var/www/community/wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/utils.php on line 1057

Warning: Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///var/www/community/wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/utils.php on line 1057
PHP Notice:  Undefined index: HTTP_HOST in phar:///var/www/community/wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 75

Notice: Undefined index: HTTP_HOST in phar:///var/www/community/wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 75

Warning: Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///var/www/community/wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Loggers/Base.php on line 75

Warning: fwrite() expects parameter 1 to be resource, string given in phar:///var/www/community/wp-installer/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Loggers/Base.php on line 64
```

To reproduce, install:

```
wget -O - http://rpms.litespeedtech.com/debian/enable_lst_debian_repo.sh | bash
apt-get -y -q install openlitespeed lsphp72
ln -sf /usr/local/lsws/lsphp72/bin/lsphp /usr/local/lsws/fcgi-bin/lsphp5
ln -sf /usr/local/lsws/fcgi-bin/lsphp /usr/bin/php
php '/var/www/community/wp-installer/wp-cli.phar' --path='/var/www/community' --allow-root config get DB_HOST
```

**Comment by schlessera** [comment]
Litespeed is a web server, but WP-CLI only works in the console context (`cli` PHP SAPI), not in the web server context.

You need to a `cli` SAPI version of PHP to run WP-CLI.

You can find more information here: https://www.php.net/manual/en/features.commandline.introduction.php

**Comment by tristanleboss** [comment]
If one day someone wants to make it compatible, it's not really hard.

To detect this use case (WP-CLI used using LSPHP binary) : `php_sapi_name() === 'litespeed'`

If accessed from LiteSpeed (the server), $_SERVER contains the index "SERVER_SOFTWARE" (for example) so it's easy to detect if LSPHP is used from server or from command line.

STDIN and STDOUT constants doesn't exist but can probably be created with lines like `define('STDIN',fopen("php://stdin","r"));`...

For now, lot of stuffs work... the only dead features are WP-CLI logs and CSV format export... (they use STDIN and STDOUD constants)

**Comment by schlessera** [comment]
@tristanleboss This is not about making the PHP code work, PHP is always just PHP.

But running WP-CLI within a web server context will question all the security principles it is built on and will very likely cause major technical issues or the server being hacked down the road. Web servers and console tools serve different purposes and have different requirements on their environment. You cannot simply exchange them and assume everything will be just fine.

**Comment by tristanleboss** [comment]
Okay, thanks for being insistent as I was dumb and tired... when installing LSPHP, you get two binaries:
- /usr/local/lsws/lsphp72/bin/lsphp : the one used by the server ('litespeed' = sapi)
- /usr/local/lsws/lsphp72/bin/php : the 'cli' = sapi version meant for command line use

So, yes, you should not use the `lsphp` binary which is made for use by the litespeed webserver but, instead, use the `php` cli binary.

**Comment by raywjohnson** [comment]
Little help?

> Warning:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1057

CentOS Linux release 7.8.2003 (Core)

PHP 7.3.17 (cli) (built: Apr 22 2020 16:45:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies

Important: the commands are run from a cron, that runs a PHP script, that calls exec().

Info:

WP-CLI Commands

core update
core update-db
theme update --all
plugin update --all
      
exec()

```
sudo -u %s $(which php) $(which wp) {COMMAND HERE} --require=/opt/wp-cli-pre.php --path=/home/USERNAME/public_html
```
contents of /opt/wp-cli-pre.php

```
<?php
if(!defined('STDIN')) define('STDIN',  fopen('php://stdin',  'r'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));
if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w'));
```

What am I not doing correctly?

I need a way to ensure the many Wordpress sites I manage stay up to date. And I cannot depend on the Wordpress system for many sites. Is there a better way? Thanks for any guidance.

**Comment by brasofilo** [comment]
> So, yes, you should not use the `lsphp` binary which is made for use by the litespeed webserver but, instead, use the `php` cli binary.

Yes, that was about it! Thanks for pointing it out. 
I'll leave here my full installation code for future reference:

```bash
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
ln -s /usr/local/lsws/lsphp74/bin/php /usr/bin/php
php wp-cli.phar --info
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp
wp --info
```
