### ISSUE TITLE
Tab completion results in error: Too many positional arguments

### ISSUE THREAD

**Issue by LukasFritzeDev** [wp-cli/wp-cli#5341]
## Bug Report

Using the tab completion script as described [here](https://make.wordpress.org/cli/handbook/installing/#tab-completions) gives me the following error:
```
Error: Too many positional arguments: plugi
```

I tried to find the issue. In the completion script the command `wp cli completions` is called. But even the [sample from the sources](https://github.com/wp-cli/wp-cli/blob/c3e269b1e62b845e45334c76872d02a596eeb675/php/commands/src/CLI_Command.php#L546) produces the same error:
```
$ wp cli completions --line='wp eva' --point=100
  Error: Too many positional arguments: eva
```

Since I'm not so into the wp-cli development, I don't know how I can further debug it.

**steps to replicate**

- install wp-cli and tab completion script as described in the [handbook](https://make.wordpress.org/cli/handbook/installing/)
- type incomplete command
- press tab to expand -> error

**environment**

```
$ wp cli info
OS:	Linux 2.6.32-openvz-042stab138.1-amd64 #1 SMP Wed May 15 09:36:25 MSK 2019 i686
Shell:	/bin/bash
PHP binary:	/usr/local/php/bin/php
PHP version:	7.3.2
php.ini used:	/etc/php/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/
WP-CLI packages dir:	/files/swm2/wp-cli/.wp-cli/packages/
WP-CLI global config:	/files/swm2/wp-cli/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	2.4.0
```

**Comment by schlessera** [comment]
It looks like the quotes to send the flag `--line='wp eva'` as one argument are ignored and the flag is split at the space.

I suggest checking your `IFS` setting, this can be a likely cause for the above. See https://unix.stackexchange.com/questions/26784/understanding-ifs

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
