### ISSUE TITLE
how to show plugin list in root? 

### ISSUE THREAD

**Issue by waseemjani** [wp-cli/wp-cli#5349]
I want to show my plugin list but this error is coming, how can I allow the root to show plugin list? the error is below ,i already install wp cli.
![Capture1](https://user-images.githubusercontent.com/60694452/73836717-58dda080-4829-11ea-94bd-6a943cda9bb3.PNG)

**Comment by wojsmol** [comment]
Use `--allow-root` as mentioned in the message.

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the Make WordPress Slack Team.
