### ISSUE TITLE
Too many positional arguments:

### ISSUE THREAD

**Issue by ajmaurya99** [wp-cli/wp-cli#5352]
I am trying to run this command on CLI, it gives me an error saying "**Too many positional arguments:"** can someone guide what is wrong with this command.

`ssh mywebsitehost.com "cd /home/directorypath/ && wp db query 'UPDATE wp_options SET option_value = \"abcdefgh\" WHERE wp_options.option_name = \"options_api_key\"'"`

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/). I know you've already asked there, but this doesn't mean you should open an issue here.

Here's a more thorough guide about shell quoting, maybe that will help you diagnose the issue: http://rg1-teaching.mpi-inf.mpg.de/unixffb-ss98/quoting-guide.html
