### ISSUE TITLE
Fail to update post meta of 5-digit `post_id`

### ISSUE THREAD

**Issue by ixkaito** [wp-cli/wp-cli#5354]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When a `post_id` is 5-digit (10000 or higher), `wp post meta update` returns a wrong message and fails to update fields.

**Describe how other contributors can replicate this bug**

For example, post_id `10794` has an `old_value` in `key` field.

```bash
$ wp post meta update 10794 key new_value
Success: Updated custom field 'key'.
```
WP-CLI returns `Success: Updated`, but actually the value didn't change. 

```bash
$ wp post meta update 10794 key old_value
Success: Value passed for custom field 'key' is unchanged.
```

Trying to revert to the `old_value`, WP-CLI returns `field 'key' is unchanged` because `key` remains the `old_value`.

After this, WP-CLI fails to update values.

```bash
$ wp post meta update 10794 key new_value
Error: Failed to update custom field 'key'.
```

**Describe what you expect as the correct outcome**

To update post meta of 5-digit `post_id` posts and to return correct messages.

**Let us know what environment you are running this on**

```
OS:     Linux 4.4.0-169-generic #198-Ubuntu SMP Tue Nov 12 10:38:00 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary:     /opt/php-7.3.14/bin/php
PHP version:    7.3.14
php.ini used:   /opt/php-7.3.14/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/kiteretz
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.2.0
```

```
OS:     Linux 4.14.125-barge #1 SMP Wed Jun 12 00:10:12 UTC 2019 x86_64
Shell:
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.33-0+deb9u6
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/wordpress
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  /var/www/wp-cli.yml
WP-CLI version: 2.1.0
```

**Provide additional context/screenshots**

![20200218085122](https://user-images.githubusercontent.com/5457539/74695487-7fdb9f80-5237-11ea-9725-13631334e88d.png)

**Comment by danielbachhuber** [comment]
Hey @ixkaito,

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
