### ISSUE TITLE
`WP_CLI::error_to_string()` doesn't have a guaranteed return value

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5356]
The method `WP_CLI::error_to_string()` is supposed to accept an error object and return an error message that can be output.

However, if you pass a type into the method that it doesn't recognize, it doesn't return anything at all.

This should never happen. If it does nevertheless, it should throw an `InvalidArgumentException` to make sure a developer sees this and fix the problem.

The exception could use a message like the following:
`Unsupported argument type passed to WP_CLI::error_to_string(): {$type}`

**Comment by vsamoletov** [comment]
I'd like to take care of this one.

**Comment by schlessera** [comment]
@vsamoletov There's already a pull-request here: https://github.com/wp-cli/wp-cli/pull/5374

But it seems the author didn't continue work on it.

**Comment by kishanjasani** [comment]
> @vsamoletov There's already a pull-request here: #5374
> 
> But it seems the author didn't continue work on it.

So can we close that and create a new PR for this Issue?
