### ISSUE TITLE
WP CLI - wp theme delete --all flag not working

### ISSUE THREAD

**Issue by subtopic** [wp-cli/wp-cli#5357]
## Bug Report

I understand --allow-root is bad, but I am only running this command on a brand new install to clear out junk softaculous adds in.

Look at photo to see what I run, and what I get.

![image](https://user-images.githubusercontent.com/17188780/74774249-38a9da80-5248-11ea-9101-2a8fdd3fb15f.png)

Obviously nothing happens.

![image](https://user-images.githubusercontent.com/17188780/74774222-2f207280-5248-11ea-90a1-2272b2485ffd.png)

According to here https://developer.wordpress.org/cli/commands/theme/delete/ the --all flag should work fine, and remove all themes.

Thanks for all the work you guys do!

**Comment by subtopic** [comment]
Anyone able to replicate this issue?

**Comment by timothyjensen** [comment]
For me running `wp theme delete --all` deletes all themes, except the active theme, which is exactly what the documentation says should happen.

**Comment by glennforrest** [comment]
@subtopic I ran into the same thing recently, and it turns out I was running an out-dated version of the WP CLI which didn't support that argument.

Running `wp cli update` sorted that for me.
