### ISSUE TITLE
Updates themes or plugins with a local zip using wp theme install / wp plugin install 

### ISSUE THREAD

**Issue by niroma** [wp-cli/wp-cli#5363]
Hi :)  

First of all, thank you for developping wp-cli, that's a wonderful tool and congratulations for your work !!  

I need your help for a particular case as I build  themes and plugins (some are public others are private).  

By now I'm using this kind of loop to manage my sites :   

<code>
blah blah blah  

for SITE_URL in $SITE_URLS  

do  

	echo "checking CRON TASKS for ${SITE_URL}"  

	wp cron event run --due-now --url="$SITE_URL" --path="$WP_PATH"  

	echo "checking PLUGINS updates for ${SITE_URL}"  

	wp plugin update --all  

	echo "checking CORE update for ${SITE_URL}"  

        wp core update  

	echo "DONE !! All is fine for ${SITE_URL} in ${WP_PATH}"  

done

blah blah blah  
</code>

And it's working fine =)  

Concerning the private part I need to deploy themes or plugins locally using this kind of arguments in my loop :  
<code>
if (wp theme is-active my-theme) {  

wp theme install ../my-theme.zip --activate  

}  

if (wp plugin is-active my-plugin) {  

   wp plugin install my-plugins --activate  

}  
</code>

Fact is, this might work (I haven't tested this code in production yet but this is the idea), BUT as I'm running my shell script multiples times per day, I'd like to check if my theme or plugin need an update or not ...  

As my file are zipped I can't check plugin/theme version and I can't figure how to achieve this (I'd love to perform a plugin/theme update locally only if it is needed).  

I hope you'd reply to my request even if my english is so bad :/ Sorry, it's not my native language ...  

Have a nice day and may the force be with you !

**Comment by danielbachhuber** [comment]
Hey there,

GitHub issues are for bug reports, enhancements, etc., not support requests.

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
