### ISSUE TITLE
Updating to 5.4 wordpress doesn't update the database scheme

### ISSUE THREAD

**Issue by mirabellette** [wp-cli/wp-cli#5376]
Hello,
I recently updated my Wordpress website with wp-cli. The update was successfully done but unfortunately, only partially.

Indeed, when I go the website, I still have to do the database scheme. I thought it would have been done during the upgrade process.

Is it possible to include it in wp-cli in order to avoid any other action from the system administrator ?

**Comment by chesio** [comment]
Hi @mirabellette,

https://github.com/wp-cli/core-command/#wp-core-update-db is what you are asking for :-)

**Comment by mirabellette** [comment]
Thank you very much for your help, I didn't see this part in the tutorial !
