### ISSUE TITLE
Consider supporting a canonical wp-config filename that is specific to WP-CLI?

### ISSUE THREAD

**Issue by mikeschinkel** [wp-cli/wp-cli#5377]
## Feature Request

Have you considered supporting a canonical wp-config filename that is specific to WP-CLI, for example `wp-cli-config.php` and `wp-cli-config.local.php`?

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Getting WP-CLI to work with a project's `wp-config.php` file is often very difficult.

It seems WP-CLI frequently just hangs when there is an issue with `wp-config.php`, and it is hard to debug the reasons why. So rather than fight those I have just been using `WP_CONFIG_PATH` and a config file that is crafted specifically for use with WP-CLI.

However, the setting of `WP_CONFIG_PATH` is not easily committed to version control, and especially not for debugging commands from within PhpStorm. 

For debugging in PhpStorm we have to add the environment variable to the dialog, and this means other people on our team who might need to debug WP-CLI commands have to do the same. Or I might have to do it again in the future after I have forgotten exactly what I have to do it. Then they or I have to waste the time to figure out how to do it while getting frustrated we are wasting time while it is not working. 

_(We can certainly document how to set `WP_CONFIG_PATH` for our projects, but people don't often read documentation, especially if it does not occur to them that documentation for the specific issue exists.)_

**Describe the solution you'd like**

I would rather just be able to create a `wp-cli-config.php` / `wp-cli-config.local.php` with all the required configuration information — a file we can commit to version control — and have it all _"just work"_ in the future. 

I believe the coding solution would be simple; just insert four lines `\WP_CLI\Utils->locate_wp_config()` to check for the proposed two (2) files starting in front of [line 252](https://github.com/wp-cli/wp-cli/blob/6f5e81f10be31ea2b8d9edfc0bbbe539fd719340/php/utils.php#L252):

```
} elseif ( file_exists( ABSPATH . 'wp-cli-config.local.php' ) ) {
	$path = ABSPATH . 'wp-cli-config.local.php';
} elseif ( file_exists( ABSPATH . 'wp-cli-config.php' ) ) {
	$path = ABSPATH . 'wp-cli-config.php';
```

After insert, this is what the `locate_wp_config()` method would look like:

```
function locate_wp_config() {
	static $path;

	if ( null === $path ) {
		$path = false;

		if ( getenv( 'WP_CONFIG_PATH' ) && file_exists( getenv( 'WP_CONFIG_PATH' ) ) ) {
			$path = getenv( 'WP_CONFIG_PATH' );
		} elseif ( file_exists( ABSPATH . 'wp-cli-config.local.php' ) ) {
			$path = ABSPATH . 'wp-cli-config.local.php';
		} elseif ( file_exists( ABSPATH . 'wp-cli-config.php' ) ) {
			$path = ABSPATH . 'wp-cli-config.php';
		} elseif ( file_exists( ABSPATH . 'wp-config.php' ) ) {
			$path = ABSPATH . 'wp-config.php';
		} elseif ( file_exists( dirname( ABSPATH ) . '/wp-config.php' ) && ! file_exists( dirname( ABSPATH ) . '/wp-settings.php' ) ) {
			$path = dirname( ABSPATH ) . '/wp-config.php';
		}

		if ( $path ) {
			$path = realpath( $path );
		}
	}

	return $path;
}
```
Will you accept a PR?

**Comment by johnbillion** [comment]
> Getting WP-CLI to work with a project's `wp-config.php` file is often very difficult.

I'd be interested to know what sort of code you're often putting into `wp-config.php` that often causes WP-CLI to break (I realise you stated that debugging the problem is difficult, hence this ticket, but I assume there's a reasonably common pattern).

I can't recall the last time I had a problem with the config file when using WP-CLI, if ever, and I've worked with some pretty gnarly config files.

Is there a certain pattern to your config files @mikeschinkel ? Something that might be a common cause of problems?

I support the idea of making it easier to use a separate config file for WP-CLI, but it would also be good to try and identify what can cause WP-CLI to get tripped up and not provide useful debugging output.

**Comment by danielbachhuber** [comment]
Holding off on this for now. We can consider it in the future if there's an obvious and common use case for it.
