### ISSUE TITLE
Display full output when there's an SSH connection error

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#5378]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When the connection to a remote server (with the `--ssh` flag or an alias) results in an error being returned from the server, the error message from the remote server is not shown.

For example, connecting to a server with invalid credentials can return the following error but this is never shown to the user:

```
Received disconnect from UNKNOWN port 65535:2: Too many authentication failures
Disconnected from UNKNOWN port 65535
```

Instead, WP-CLI only shows this error:

```
Error: Cannot connect over SSH using provided configuration.
```

**Describe the solution you'd like**

If a server returns an error, WP-CLI should output it.

**Comment by strarsis** [comment]
+1, I had this issue once too often. Some PHP fatal error in WordPress (e.g. a plugin) causes the connection to fail. It would be great if the WP CLI can log/show the causing issue (in this case a PHP fatal error).

**Comment by swissspidy** [comment]
Relevant code section: https://github.com/wp-cli/wp-cli/blob/28803dffcb9e041764aed6dd712346ca243cf0e8/php/WP_CLI/Runner.php#L474-L680

We'd need to dump the output from the server

**Comment by thelovekesh** [comment]
@swissspidy Can you please assign it to me?
