### ISSUE TITLE
v2.4.1 phar file

### ISSUE THREAD

**Issue by noelspringer** [wp-cli/wp-cli#5379]
The current release version as a phar file is 2.4.0.
Version 2.4.1 fixes a bug with PHP 7.4.

Can the 2.4.1 version please be made available as a phar file?

Cheers,
Noel

**Comment by vincent-guesnard** [comment]
Bump

**Comment by schlessera** [comment]
Please use latest nightly instead. v2.4.1 only fixed a Composer-specific issue, not PHP 7.4 compatibility.
