### ISSUE TITLE
Call to undefined method WP_Site_Health::get_instance

### ISSUE THREAD

**Issue by funkytwig** [wp-cli/wp-cli#5382]
Hi, ime using Centos 7 and just installed wp-cli (https://www.sitepoint.com/wp-cli/).  php --version gives me PHP 7.3.16.  I have WordPress 5.4 installed.

When I run

su -c  "wp search-replace 'https://tvpp.tv/' 'https://tvpp.freeddns.org/'" new_tvpp

I get

PHP Fatal error:  Uncaught Error: Call to undefined method WP_Site_Health::get_instance() in /home/back/new_tvpp/1586830801_Tue_14Apr2020_0320/docker/new.tvpp.tv/html/wp-settings.php:372
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in /home/back/new_tvpp/1586830801_Tue_14Apr2020_0320/docker/new.tvpp.tv/html/wp-settings.php on line 372
Fatal error: Uncaught Error: Call to undefined method WP_Site_Health::get_instance() in /home/back/new_tvpp/1586830801_Tue_14Apr2020_0320/docker/new.tvpp.tv/html/wp-settings.php:372
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in /home/back/new_tvpp/1586830801_Tue_14Apr2020_0320/docker/new.tvpp.tv/html/wp-settings.php on line 372
Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.

**Comment by schlessera** [comment]
@funkytwig This method is not being called by WP-CLI, but by WordPress Core.

My guess would be that a plugin is badly coded and trying to integrate with Site Health too early. Try running the command with the `--skip-plugins` flag. For more information about troubleshooting issues like these, see https://make.wordpress.org/cli/handbook/troubleshooting/.

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
