### ISSUE TITLE
Allow selecting child sites by site id for multisite installs

### ISSUE THREAD

**Issue by binaryfire** [wp-cli/wp-cli#5388]
Hi guys

It'd be great if we could select child sites by id for multisite installs. There are some situations where this would be much easier than using the URL. For example I put always put stores on a subdomain when building sites for musicians. The id is always 2. It'd be easier to automate actions on all these stores if I didn't need to look up the URLs first.

Cheers

**Comment by mcaskill** [comment]
Absolutely. I'm currently working on a multisite/multidomain/multilingual client project and the `--url` parameter does not work.

**Comment by danielbachhuber** [comment]
This is now possible with a little bit of custom code https://github.com/wp-cli/wp-cli/issues/5649#issuecomment-1227814680
