### ISSUE TITLE
Incorrect success message when adding an alias without an @ symbol

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#5391]
## Bug Report

**Describe the current, buggy behavior**

Adding an alias but forgetting its leading `@` symbol results in an invalid alias being added, and a success message being shown to the user.

**Describe how other contributors can replicate this bug**

- Run `wp cli alias add hello --set-path=/` and observe a success message
- Run `wp @hello help` and observe the alias does not exist
- Run `wp cli alias list` and observe the alias is not listed
- Open your `~/wp-cli/config.yml` file and observe that the alias was added without a leading `@` symbol

**Describe what you expect as the correct outcome**

I would like the `wp cli alias` commands to work both with and without the leading `@` symbol, with one being added as necessary behind the scenes.

The `--grouping` flag appears to be the only place in WP-CLI where the leading `@` symbol is optional. Both of the following work:

* `wp cli alias add @foo --grouping=bar,baz`
* `wp cli alias add @foo --grouping=@bar,@baz`

**Comment by swissspidy** [comment]
That would indeed improve developer experience 👍  I can see that this would be helpful as you don't have to worry about adding the `@` every time.
