### ISSUE TITLE
search finds matches by search-replace doesn't

### ISSUE THREAD

**Issue by NizarBlond** [wp-cli/wp-cli#5393]
Hi,

I am running the command below wanting to replace the dev URL links "myawssite2.yijfs7.ap-southeast-2.superawshosting.com" with "myawssite2.com"

A few backgrounds
- WP-CLI 2.4.0
- Not multisite network

I tried to run various commands

> wp search-replace myawssite2.yijfs7.ap-southeast-2.superawshosting.com myawssite2.com --all-tables

> wp search-replace myawssite2.yijfs7.ap-southeast-2.superawshosting.com myawssite2.com elm_postmeta

> wp search-replace myawssite2.yijfs7.ap-southeast-2.superawshosting.com myawssite2.com elm_postmeta --precise --all-tables

> wp search-replace myawssite2.yijfs7.ap-southeast-2.superawshosting.com myawssite2.com elm_postmeta 

> wp search-replace 'myawssite2.yijfs7.ap-southeast-2.superawshosting.com' 'myawssite2.com'

But the result I keep getting is 0 replacements
+--------------+------------+--------------+------+
| Table        | Column     | Replacements | Type |
+--------------+------------+--------------+------+
| elm_postmeta | meta_key   | 0            | PHP  |
| elm_postmeta | meta_value | 0            | PHP  |
+--------------+------------+--------------+------+

However, when I run search, I find the matches.

`
> [root@ip-172-32-5-243 myawssite2]# wp db search 'myawssite2.yijfs7.ap-southeast-2.superawshosting.com' --one_line

> elm_postmeta:meta_value:1466:/05/illustration1.jpg";s:2:"54";s:99:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/illustration [...] 20/05/logo-amazon.png";s:2:"56";s:97:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-amazon. [...] o-dear-inventory.png";s:2:"63";s:105:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-dear-in [...] 2020/05/logo-ebay.png";s:2:"62";s:95:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-ebay.pn [...] 20/05/logo-paypal.png";s:2:"61";s:97:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-paypal. [...] -shopify-partner.png";s:2:"60";s:106:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-shopify [...] 20/05/logo-stripe.png";s:2:"59";s:97:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-stripe. [...] ogo-woo-commerce.png";s:2:"58";s:103:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-woo-com [...] 2020/05/logo-xero.png";s:2:"57";s:95:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/logo-xero.pn

> elm_postmeta:meta_value:5969:020/05/ecommerce2.jpg";s:2:"80";s:96:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/ecommerce2.j [...] media/2020/05/mug.jpg";s:2:"81";s:89:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/mug.jpg";s:2

> elm_postmeta:meta_value:11772:ook-white-36x36.png";s:3:"204";s:100:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/facebook-whi [...] /facebook-white.png";s:3:"204";s:106:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/facebook-whi [...] /instagram-36x36.png";s:3:"214";s:95:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/instagram.pn [...] 20/05/instagram.png";s:3:"214";s:101:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/instagram-36 [...] linkedin-1-36x36.png";s:3:"210";s:96:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/linkedin-1.p [...] 0/05/linkedin-1.png";s:3:"210";s:102:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/linkedin-1-3 [...] 05/twiiter-36x29.png";s:3:"213";s:93:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/twiiter.png" [...] /2020/05/twiiter.png";s:3:"213";s:99:"//myawssite2.yijfs7.ap-southeast-2.superawshosting.com/wp-content/uploads/2020/05/twiiter-36x2

> Warning: No text columns for table 'elm_yoast_seo_meta' - skipped.
`

What might be the issues?

**Comment by davidfavor** [comment]
I'm having what appears to be a similar problem, which seems to relate to complex serialized data.

wp db search - finds the strings

wp search-replace --precise --recurse-objects --all-tables - fails to change strings

**Comment by giantoctopus** [comment]
could this be related to https://github.com/wp-cli/wp-cli/issues/5293 ? with a possible solution so far being https://github.com/wp-cli/wp-cli/issues/5293#issuecomment-578736033

**Comment by momomesh** [comment]
why not do a --dry-run
to see if it works before executing it?

did it work?
in the latest version of wp-cli, the serialization problem seems to be fixed.

**Comment by danielbachhuber** [comment]
Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
