### ISSUE TITLE
o

### ISSUE THREAD

**Issue by bs0807** [wp-cli/wp-cli#5403]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

A clear and concise description of what you are actually trying to do, and in what way the current version of WP-CLI is not up to the task.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Add any considered drawbacks if you can think of any.

**Comment by schlessera** [comment]
@bs0807 You've created two bogus issues, so I closed them.

Do you need with something?
