### ISSUE TITLE
Add alias to existing grouping

### ISSUE THREAD

**Issue by cedriclajato** [wp-cli/wp-cli#5414]
Hi WP-CLI team,

Looks like we missed one of the important function which to add alias to existing alias grouping

For example with this scenario: 

@membership - alias key
 grouping
 @websiteone
 @websitetwo
 @websitethree
 @websitefour

How can you add another alias like @websitefive? There's no option as of this moment and what you can do only is to do update but not add at all.

Thank you.

Kind regards,
Cedric

**Comment by schlessera** [comment]
The `wp cli alias add` command accepts a `--grouping=<grouping>` flag that you can use to add an alias to an existing group.

Is that what you are looking for?

**Comment by cedriclajato** [comment]
**I have tried that already it does not work to add an alias to existing group**

![add-alias](https://user-images.githubusercontent.com/57404000/99351445-8dfc4080-28db-11eb-96f4-db47568ba196.PNG)

**Comment by schlessera** [comment]
As discussed on Slack, the syntax was wrong here and the group and alias wre switched.
