### ISSUE TITLE
More Developer friendly WordPress installation

### ISSUE THREAD

**Issue by AbmSourav** [wp-cli/wp-cli#5416]
## More Dynamic way of WordPress installation with WP-CLI

When we install WordPress with WP-CLI, we need to do it in a step by step process. We also need to write lots of arguments for `wp`. But what if we do it just like *npm init* style. Just one command, then follow the instructions.

I did it with bash script: [WP-CLI Automation](https://github.com/AbmSourav/wpcli-automation)

Something like this:
![wpi-automation-demo](https://user-images.githubusercontent.com/39233955/86516085-8f9efd80-be3f-11ea-8d93-9d9c88f76b57.gif)

**Comment by schlessera** [comment]
This will remain an area for custom scripts and automation tools, given the philosophy of the project: https://make.wordpress.org/cli/handbook/contributions/philosophy/
