### ISSUE TITLE
Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Extractor.php

### ISSUE THREAD

**Issue by cedriclajato** [wp-cli/wp-cli#5424]
Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Extractor.php on line 52
Error: Cannot connect over SSH using provided configuration.

Anyone who experienced this issue? Trying to automate everything but having problem with it.

**Comment by cedriclajato** [comment]
Basically I used wp core download but it hat plugins folder etc.. with size of 300 mb.

**Comment by danielbachhuber** [comment]
Hope you were able to figure this out! Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
