### ISSUE TITLE
LIttle Help

### ISSUE THREAD

**Issue by raywjohnson** [wp-cli/wp-cli#5425]
I get this warning notice when I run wp-cli (/usr/local/bin/wp) via the PHP exec() function, in a root cron...

> Warning:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1057

CentOS Linux release 7.8.2003 (Core)

PHP 7.3.17 (cli) (built: Apr 22 2020 16:45:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies

WP-CLI v2.4.0

Important: the commands are run from a cron, that runs a PHP script, that calls exec().

Info:

WP-CLI Commands

core update
core update-db
theme update --all
plugin update --all
      
exec()

```
sudo -u %s $(which php) $(which wp) {COMMAND HERE} --require=/opt/wp-cli-pre.php --path=/home/USERNAME/public_html
```
contents of /opt/wp-cli-pre.php

```
<?php
if(!defined('STDIN')) define('STDIN',  fopen('php://stdin',  'r'));
if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));
if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w'));
```

What am I not doing correctly?

I need a way to ensure the many Wordpress sites I manage stay up to date. And I cannot depend on the Wordpress system for many sites. Is there a better way? Thanks for any guidance.

Forgot to mention that the CRON is via the ROOT account.

**Comment by raywjohnson** [comment]
Update. Tried just added the WP command direct to a users CRON.

wp core update --path=/home/USERNAME/public_html/

But...

> PHP Warning:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1057

**Comment by raywjohnson** [comment]
If I use: wp core update **--require=/opt/wp-cli-pre.php** --path=/home/USERNAME/public_html/

Then only the original warning...



> PHP Warning: Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1057

**Comment by wojsmol** [comment]
@raywjohnson Most likly you are raningWP-CLI using wrong SAPI - web instead of cli.

**Comment by raywjohnson** [comment]
@wojsmol 

Thanks for that info. How do I fix that issue?

PHP version says **CLI**

PHP 7.3.17 **(cli)** (built: Apr 22 2020 16:45:50) ( NTS )

**Comment by raywjohnson** [comment]
Alrighty then!

The solution is discovered at last.

CRONs run PHP under SAPI: cgi-fcgi

This is the output of a simple PHP script running in a root cron: php /root/test.php

PHP SAPI == cgi-fcgi
PATH == /usr/bin:/bin

But... 

If I set I run it thus: **/usr/local/bin/ph**p /root/test.php

PHP SAPI: cli
PATH == /usr/bin:/bin

I get the proper SAPI.
