### ISSUE TITLE
Unable to upgrade some packages due to `dev-master` constraint for `wp-cli/wp-cli` dependency

### ISSUE THREAD

**Issue by rob006** [wp-cli/wp-cli#5426]
Multiple packages were released with `"wp-cli/wp-cli": "dev-master"` in require section of `composer.json`. It makes it impossible to upgrade if you use `"minimum-stability": "stable"` in your project (which actually protects you from installing unstable version of `wp-cli/wp-cli`).

```console
$ composer outdated
wp-cli/db-command                   v2.0.6             v2.0.9             Performs basic database operati...
wp-cli/entity-command               v2.0.7             v2.0.9             Manage WordPress comments, menu...
wp-cli/extension-command            v2.0.10            v2.0.11            Manages plugins and themes, inc...
wp-cli/scaffold-command             v2.0.8             v2.0.10            Generates code for post types, ...
$ composer why-not wp-cli/db-command:2.0.9
wp-cli/db-command    v2.0.9  requires  wp-cli/wp-cli (dev-master)  
my/project  trunk   requires  wp-cli/wp-cli (^2.4)        
$ composer why-not wp-cli/entity-command:2.0.9
wp-cli/entity-command  v2.0.9  requires  wp-cli/wp-cli (dev-master)  
my/project    trunk   requires  wp-cli/wp-cli (^2.4)        
$ composer why-not wp-cli/extension-command:2.0.11
wp-cli/extension-command  v2.0.11  requires  wp-cli/wp-cli (dev-master)  
my/project       trunk    requires  wp-cli/wp-cli (^2.4)        
$ composer why-not wp-cli/scaffold-command:2.0.10
wp-cli/scaffold-command  v2.0.10  requires  wp-cli/wp-cli (dev-master)  
my/project      trunk    requires  wp-cli/wp-cli (^2.4)
```

Releases with such requirement should be avoided, because in 5 years `dev-master` will point to completely different version than now - this is extremely unreliable constraint. Stable releases should not depend on unstable dependencies.

**Comment by rob006** [comment]
Why do your release stable release of `wp-cli/db-command` if it is not stable (since it relies on unstable dependency)?

**Comment by schlessera** [comment]
Because I'll otherwise be stuck in a chicken&egg scenario and no tests will ever pass. 😁 

There are ways of getting around that, but it is way more complex and much more work to maintain. The current way does not break anything for anyone and is quick to iterate upon and get test results.

**Comment by schlessera** [comment]
Note: This is the reason why I'm thinking of uncoupling the version of the `wp-cli/wp-cli` package from the actual WP-CLI binary version. However, that will be a major breaking change for third-party commands and require changes in the release process automation as well. Maybe for v3...

**Comment by rob006** [comment]
> Because I'll otherwise be stuck in a chicken&egg scenario and no tests will ever pass.

Sorry, I don't know wp-cli build process and I have no idea what tests you're talking about. `wp-cli/db-command` has its own tests, why do you need to release this package to pass test?

**Comment by schlessera** [comment]
> Sorry, I don't know wp-cli build process and I have no idea what tests you're talking about. wp-cli/db-command has its own tests, why do you need to release this package to pass test?

There is an overarching test suite that assembles the entire bundled WP-CLI phar executable in a development version to run the tests against it, because some problems cannot be detected when isolating a single command.

I'm working on shortening the release cycles and maybe even decoupling some things, so hopefully, issues like these will soon be a thing of the past.

Thanks for flagging it, @rob006 !
