### ISSUE TITLE
Just releasing WP-CLI stubs for static analysis

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/wp-cli#5428]
Hello!
https://github.com/php-stubs/wp-cli-stubs
We are working on this _right now_.

I plan to release WP-CLI versions from 2.1.0. What do you think?

If would be nice to declare minimum WP core version for the stubs.
Where can I find that for WP-CLI v2.1.0 and so on?

**Comment by szepeviktor** [comment]
Burried in Runner::check_wp_version?

https://github.com/wp-cli/wp-cli/blob/v2.1.0/php/WP_CLI/Runner.php#L848

**Comment by schlessera** [comment]
The closest is probably the Behat tests. Those that only work with certain WP versions will include a `@require-wp-x-x` tag. Sometimes this might overshoot, but it should be reliable enough to be used.

**Comment by szepeviktor** [comment]
Thank you for your response.
Meanwhile I've realized that core stubs releases start from 4.7 :)
