### ISSUE TITLE
Dynamic options?

### ISSUE THREAD

**Issue by kodie** [wp-cli/wp-cli#5437]
Is it not possible for options to be dynamic? For example:

```
$ wp my-command --field-name=Test1 --field-email=Test2 --field-blah=Test3
```

I've got the name of my option set to `field-<variable>` however I get the following error:

```
Warning: The `wp my-command` command has an invalid synopsis part: [--field-<variable>=<field-<variable>>...]
```

It's very possible that I'm going about this wrong however I've tried a few things and nothing seems to work so I'm lead to believe that wp-cli doesn't support this currently.

**Comment by schlessera** [comment]
You currently cannot define a prefix like you have here with `field-`. IF you want dynamic options, the entire option name needs to be dynamic. You could still do checks afterwards, of course.

See the `post list` command for an example:

https://github.com/wp-cli/entity-command/blob/d649690102735f586764dcd94e93c6945bffff2e/src/Post_Command.php#L512-L513
