### ISSUE TITLE
wp cli suggested command do not work

### ISSUE THREAD

**Issue by Nick-6** [wp-cli/wp-cli#5441]
I'm trying to use the following suggested command to run WP-CLI as www-data.

`sudo -u www-data -i -- wp <command>`

Which gives ...

`This account is currently not available.`

But the actual working command is ...

`sudo -u www-data wp <command>`

It works but I would like to know why the WP-CLI suggested method is not working.

[I'm on Debian 10 with LAMP stack installed.]

**Comment by schlessera** [comment]
Those are syntax details about the particular version of `sudo` you are running, and is not directly related to WP-CLI development.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review [https://wp-cli.org/#support](https://wp-cli.org/#support).

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
