### ISSUE TITLE
RPM - can't be found the release phar "wp-cli-2.4.1.phar"

### ISSUE THREAD

**Issue by blackfile** [wp-cli/wp-cli#5442]
Hey guys, can you please enable "Assets"  in the tag release 2.4.1?, I use the phar file to build the RPM.

![image](https://user-images.githubusercontent.com/1482214/93141957-bcc32400-f6aa-11ea-9f0f-8ea3aa220ee7.png)

@schlessera can you help me.

Thanks.

**Comment by schlessera** [comment]
There is no separate 2.4.1 release, it was a hotfix targeting Composer installations only. See https://github.com/wp-cli/wp-cli/issues/5359#issuecomment-593201128
