### ISSUE TITLE
Global parameters are always suppressed

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5453]
The code in https://github.com/wp-cli/wp-cli/pull/5423 does not seem to work correctly. Even though the Behat tests are passing, on my machine it always suppresses the global parameters, no matter the state of the environment variable.

**Comment by schlessera** [comment]
@thrijith Did this work for you in actual usage?

**Comment by austinginder** [comment]
I see the problem. Whether you set `WP_CLI_SUPPRESS_GLOBAL_PARAMS=true` or `WP_CLI_SUPPRESS_GLOBAL_PARAMS=false` in PHP `(bool) getenv( 'WP_CLI_SUPPRESS_GLOBAL_PARAMS' )` will always translate to true. That's because getenv always returns a string and a string will always be true unless empty when converted to a boolean. I believe it should be safe to run the PHP check as a string.

**Comment by thrijith** [comment]
> @thrijith Did this work for you in actual usage?

@schlessera Apologies, I believe I didn't test with a false value for the variable, checked right now and it seems only the absence of the variable makes the global params to show up. 

@austinginder Thanks for the PR, I think we can add a behat test to make sure the params show up If the value is set to `false`, @schlessera thoughts?

**Comment by schlessera** [comment]
In my case, even the absence of the variable suppressed the global parameters, it seems.

Yes, we need to have a test that can trigger both states successfully.

**Comment by austinginder** [comment]
I'm wondering if maybe the environment variable was still hanging around for some other reason relating to your setup. I wasn't able to replicate that behaviour on my end. Here are the steps I took with what I'm seeing as of the latest commit. I'm on Linux.

`wp` - I'm seeing global parameters as expected.

`export WP_CLI_SUPPRESS_GLOBAL_PARAMS=true` then `wp` and I'm no longer seeing them as expected.

`export WP_CLI_SUPPRESS_GLOBAL_PARAMS=anything_else` then `wp` and I'm not longer seeing them as not expected. This should be fixed as of the patch.

`unset WP_CLI_SUPPRESS_GLOBAL_PARAMS` then `wp` and I'm now seeing them as expected.

Just added a behat test to my pull request which will check for the reverse state. Hope that is helpful.

**Comment by thrijith** [comment]
@schlessera I've merged the PR, please test from your end if it fixes the issue, thanks!
