### ISSUE TITLE
WP Cli doesn't works, and does not produce any errors

### ISSUE THREAD

**Issue by Androlax2** [wp-cli/wp-cli#5456]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

No, all commands doesn't works (I can juste works with wp --debug and wp --info)

Here is what wp --info returning 

```shell
OS:	Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/Applications/MAMP/bin/php/php7.4.9/bin/php
PHP version:	7.4.9
php.ini used:	/Applications/MAMP/bin/php/php7.4.9/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/theobenoit
WP-CLI packages dir:	/Users/theobenoit/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Describe how other contributors can replicate this bug**

I don't know how you can do that, it was working well before I install PHP 7.4 with MAMP.
I tryed to reinstall it etc...

**Describe what you expect as the correct outcome**

I can't do any commands, and it does not product an output, so I can't even understand where the problem come.

**Let us know what environment you are running this on**

```shell
OS:	Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/Applications/MAMP/bin/php/php7.4.9/bin/php
PHP version:	7.4.9
php.ini used:	/Applications/MAMP/bin/php/php7.4.9/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/theobenoit
WP-CLI packages dir:	/Users/theobenoit/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Provide additional context/screenshots**

![Capture d’écran 2020-10-21 à 13 09 42](https://user-images.githubusercontent.com/39646949/96712012-bb1e0780-139e-11eb-85c0-993478ac3d18.png)

**Comment by wojsmol** [comment]
Hi
Please try update to nightly with `wp cli update --nightly`

**Comment by Androlax2** [comment]
> Hi
> Please try update to nightly with `wp cli update --nightly`

Hello,

I already tryed that. I did it again, but it doesn't work either :/

**Comment by wojsmol** [comment]
Any packages in /Users/theobenoit/.wp-cli/packages/

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the Make [WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by Androlax2** [comment]
Nothing in, I reinstalled everything. I don't understand where it could came.

Yes I know. I posted that here because, as you could see I have no error messages, nothing. I don't really know where it come, but it should be something to understand where the problem come from :/ 

So If we could find where it come, you could implement an Exception thrown when this kind of things happens. I don't know i'm the only one with this problem, maybe, I don't know. I didn't found any real answers on the internet.

**Comment by Androlax2** [comment]
Hello,

For every person that come there, I finally found how to restore my WP Cli : 

cd ~
cd .wp-cli/
rm -rf packages
rm -rf cache

It will remove caches and packages of wp cli. Maybe it came from packages or cache I don't know.
