### ISSUE TITLE
http_request utility ignores verify option

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/wp-cli#5463]
## Bug Report

The `\WP_CLI\Utils\http_request` utility accepts an array of `$options` which it passes to `Requests::request`. One of these options is [`verify`](https://github.com/rmccue/Requests/blob/9da347890787e08334ceef8ea28f76f15e139ad5/library/Requests.php#L339-L342) for specifying a custom SSL certificate to use or [`false` to disable certificate verification](https://github.com/rmccue/Requests/blob/9da347890787e08334ceef8ea28f76f15e139ad5/library/Requests/Transport/cURL.php#L149-L152).

The wp-cli utility however [sets this option with its own value](https://github.com/wp-cli/wp-cli/blob/b9e30a0299c94457e472e99f2f79422ce3bbcae7/php/utils.php#L747-L766) regardless of any passed value.

This makes debugging requests using an HTTP proxy nearly impossible because a custom certificate cannot be used, nor can certificate verification be disabled.

As a developer familiar with HTTP requests in WP and Requests, I would expect the `verify` option provided to the utility to take precedence over any other logic to determine or require an SSL certificate.

**Is your bug report directly related to a specific command?**

No

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

This is a pretty low-level detail in an internal utility function so it should be quite clear by the description above but I'm happy to elaborate if needed 😄 

**Describe what you expect as the correct outcome**

A clear and concise description of what you expected to happen (or code).

**Let us know what environment you are running this on**

```
OS:	Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php@7.2/7.2.33/bin/php
PHP version:	7.2.33
php.ini used:	/usr/local/etc/php/7.2/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.4.10-MariaDB, for osx10.14 (x86_64) using readline 5.1
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/aaemnnosttv
WP-CLI packages dir:	/Users/aaemnnosttv/.wp-cli/packages/
WP-CLI global config:	/Users/aaemnnosttv/.config/wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	2.5.0-alpha-102ef48
```

**Provide a possible solution**

If `verify` is set in the given `$options` to `\WP_CLI\Utils\http_request`, this value should be passed through rather than overwritten.

**Comment by schlessera** [comment]
Yes, I agree with the provided solution. Are you up for submitting a PR?

**Comment by aaemnnosttv** [comment]
Sure thing 👍

**Comment by aaemnnosttv** [comment]
@schlessera PR submitted 👍
