### ISSUE TITLE
WP CLI ignores current project' PHP version

### ISSUE THREAD

**Issue by zzap** [wp-cli/wp-cli#5464]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

In my local setup I use different PHP versions per project and can switch versions inside the project but default PHP version for my system is `8.0.0RC3`. 

However, when I'm inside the project, WP CLI ignores its specified PHP version and use the default one. 

Here is PHP info for one of projects:
![local-php](https://user-images.githubusercontent.com/1508963/97869797-52297e80-1d12-11eb-8775-67939f08ab58.png)

And here is WP CLI info in the root of that project.

```
$ wp cli info
OS:     Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.0
PHP version:    8.0.0RC3
php.ini used:   /etc/php/8.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/milana/www/developerka.loc
WP-CLI packages dir:    /home/milana/.wp-cli/packages/
WP-CLI global config:   /home/milana/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.4.0
```

Is this expected behavior for WP CLI or is it a bug?

**Comment by thefrosty** [comment]
PHP versions can differ from source to command line (CLI Interpreter).

**Comment by zzap** [comment]
Yes, I ended up removing PHP8.0 from my system. It's now on 7.4 .12 and WP-CLI works as expected.

**Comment by thefrosty** [comment]
If you manage PHP locally via brew like I do, check out [brew-php-switcher](https://formulae.brew.sh/formula/brew-php-switcher#default)

**Comment by schlessera** [comment]
Indeed, often times switching PHP version only switches the version used via the web server. The version used for WP-CLI is the `cli` SAPI that happens to be found first in the environment's `$PATH` variable. You can adapt this via different mechanisms, but they all involve doing a change the CLI environment level.

This is expected and just the way PHP CLI tools work, so closing this for now. Feel free to ping me in #cli on Slack if you need further assistance.
