### ISSUE TITLE
Composer v2.0

### ISSUE THREAD

**Issue by thefrosty** [wp-cli/wp-cli#5466]
Not sure whether this is a support request, bug or just a moot point around composer autoloaders in composer v2.0.

Got a deprecation notice:
```bash
Deprecation Notice: Class WP_CLI located in ./vendor/wp-cli/wp-cli/php/class-wp-cli.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class WP_CLI_Command located in ./vendor/wp-cli/wp-cli/php/class-wp-cli-command.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

Is this a valid issue? Should it just be ignored?

**Comment by schlessera** [comment]
This was already fixed in https://github.com/wp-cli/wp-cli/pull/5407, but not yet released. If you don't want to wait for the upcoming release, you can use `dev-master` branch for now to have this resolved.
