### ISSUE TITLE
More than 1 command at a time

### ISSUE THREAD

**Issue by plittlefield** [wp-cli/wp-cli#5468]
When used on a server or remotely, is it possible to run more than 1 command after each other?

e.g.

`wp core check-update update update-db`

Right now, I use the Linux && to run multiple wp commands one after the other as long as the previous command is successful.

Just a thought...

**Comment by schlessera** [comment]
It would be impossible to reliably detect where one command ends and the next begins, as most commands also accept positional arguments.

**Comment by plittlefield** [comment]
Ah, fair point.

Never mind, I'll string my commands together as before then :-)

You can close this ticket.

Thanks,

Paully
