### ISSUE TITLE
fatal error after PHP upgrade from 7.0-FPM to 8.0-FPM

### ISSUE THREAD

**Issue by DieselDriver** [wp-cli/wp-cli#5482]
Hello,

since I upgraded PHP 7.0 to PHP 8.0 on destination server I get following error when I try to execute wp-cli.

################################################################
#wp-cli.phar --allow-root --ssh=root@xxxxxxxxxxxxxxxxxxxxxxxx plugin update --all#
################################################################
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php:75
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php(75): implode()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(32): WP_CLI\DocParser->get_longdesc()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(117): WP_CLI\Dispatcher\CompositeCommand->__construct()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(49): WP_CLI\Dispatcher\CommandFactory::create_composite_command()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php(516): WP_CLI\Dispatcher\CommandFactory::create()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/cache-command/cache-command.php(12): WP_CLI::add_command()
#6 phar:///usr/local/bin/wp/vendor/composer/autoload_real.php(66): require('...')
#7 phar:///usr/local/bin/wp/vendor/composer/autoload_real.php(56): composerRequire755feccb8675069258c415b8c4b89bbf()
#8 phar:///usr/local/bin/wp/vendor/autoload.php(7): ComposerAutoloaderInit755feccb8675069258c415b8c4b89bbf::getLoader()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php(49): require('...')
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\AutoloaderStep->process()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(25): WP_CLI\bootstrap()
#12 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#13 /usr/local/bin/wp(4): include('...')
#14 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php on line 75
Error: Cannot connect over SSH using provided configuration.

Is there any workaround?

Thanks, a lot.

**Comment by mrme44** [comment]
I'm getting the same error after switching to 8.0-FPM

**Comment by johnbillion** [comment]
This was fixed in #5273 for WP-CLI version 2.4.0, but if you install wp-cli/wp-cli via Composer on PHP 8 you'll only get WP-CLI version 2.1.0 because all subsequent versions have a PHP version constraint of `^5.4 || ^7.0` or `^5.6 || ^7.0`.

#5477 fixes this but hasn't been included in a release version of WP-CLI yet.

**Comment by johnbillion** [comment]
You can get around this with `composer update --ignore-platform-reqs` but use it at your own risk.

**Comment by chrilleferna** [comment]
I have similar problem with PHP 8.0 although I do have WP-CLI version 2.4.0.
The error message I'm getting is:

PHP Fatal error:  Uncaught TypeError: unserialize(): Argument #1 ($data) must be of type string, array given in phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php:86

I downgraded to PHP 7.4 and the problem disappears.

**Comment by lesterchan** [comment]
Came to +1 to @chrilleferna issue, the same thing happens to me. Working fine on PHP 7.4 but not PHP 8.0.

```
11:14 root@vps4:~|⇒  /usr/local/bin/wp --info
OS:	Linux 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/bin/php8.0
PHP version:	8.0.1
php.ini used:	/etc/php/8.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Comment by Onyx808** [comment]
Same here

```
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(681): Requests::request()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(310): WP_CLI\Utils\http_request()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(319): Core_Command::read()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(183): Core_Command->get_download_offer()
#6 [internal function]: Core_Command->download()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->do_early_invoke()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp(4): include('...')
#19 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195
```

```
wp --info
OS:	Linux 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.0
PHP version:	8.0.2
php.ini used:	/etc/php/8.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/onyx808/temp
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```

**Comment by andrejcremoznik** [comment]
The nighlty build is 3 months old. Can we at least get an update on that?

I'm willing to test run it on PHP8 but I'm not going to set up a full dev environment for this.

**Comment by acki** [comment]
+1

**Comment by schlessera** [comment]
@andrejcremoznik The nightlies build properly again and are currently being tested against PHP 8. There might be a few minor notices with PHP 8 still hidden in places, but in general, the nightly should work fine with PHP 8.

**Comment by schlessera** [comment]
The error above in https://github.com/wp-cli/wp-cli/issues/5482#issuecomment-772995711 is from the Requests library, unfortunately, which is a third-party library that hasn't seen a release since 2016. We've migrated this over to be maintained under the WordPress umbrella now at https://github.com/WordPress/Requests and are currently working hard on pushing a release with PHP 8 fixes.

**Comment by joelmcdwebworks** [comment]
Running WP-CLI 2.4.0 on PHP 7.4.14 and MySQL 8.0.23. Getting the following error when running search-replace:

Uncaught TypeError: unserialize(): Argument #1 ($data) must be of type string, array given in phar:///opt/sp/bin/wp-cli.phar/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php:86

**Comment by mopquill** [comment]
Glad to hear that, @schlessera, thanks for the update!

For any folks newer to linux/wp-cli finding this from the web:

On my Debian install, `php7.4` is a usable command by default, despite updating to PHP 8. So if your environment also shares this trait, you can simply work around this bug in the interim with:

```
php7.4 /usr/local/bin/wp search-replace "find" "replace" [...]
```

The exact command will vary depending on the location of your callable `php`, and where you installed `wp-cli` to -- I used the default of `/usr/local/bin/wp`, though you can find out where yours are with `ls /usr/bin/php*` and `which wp`, respectively. Modify commands as needed for distro, and change the above work-around as necessary based on your results.

If you use `wp-cli search-replace` religiously, you can also alias the command like so:

```
alias wp="php7.4 /usr/local/bin/wp"
```

...again, modifying as needed. You can also add that line to your .bashrc (if you're using bash) to have that as part of your environment -- just don't forget to remove it once this bug is fixed. And, as always, don't run commands you find on the internet without understanding what they do!

**Comment by simonbuerger** [comment]
Yeah this one is blocking us from more broadly switching to php 8.0 at my company, appreciate the update @schlessera 

How soon after 1.8.0 of Wordpress/Requests is released will there be a new version of wp cli using it?

**Comment by andrejcremoznik** [comment]
@schlessera thank you very much for fixing nightly builds.

I've been running nightlies on php8 for a while now and didn't experience any issues. Commands I use regularly are

```
cli update [--nightly]
core download / update / install
transient delete
cache flush
db create / reset / export / import
plugin de-/activate
theme de-/activate
site empty
widget delete
```

**Comment by sangaman** [comment]
I ran into the issue described here with php 8.0 and `wp search-replace`. Upgrading the to the nightly with `wp cli update --nightly` made the problem go away using the same command that failed before. Thanks!

**Comment by p810** [comment]
I'm still having this issue with `wp core download` using the nightly build.

```
OS:     Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.0
PHP version:    8.0.3
php.ini used:   /etc/php/8.0/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/p810/dev/project
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0-alpha-1a19028
```

**Comment by MatthewHyatt** [comment]
core update fails for me also.
version: WP-CLI 2.5.0-alpha-1a19028
PHP 8.0.3 (cli) (built: Mar  5 2021 07:53:39) ( NTS )
wp core update
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195

**Comment by schlessera** [comment]
After lots of work, we finally pushed a new release for Requests yesterday (the first one since 2016): https://github.com/WordPress/Requests/releases/tag/v1.8.0.

So expect this to be fixed very soon now, and thanks for the patience.
