### ISSUE TITLE
Error when using wp eval-file

### ISSUE THREAD

**Issue by Aeyzaz** [wp-cli/wp-cli#5486]
PHP Parse error:  syntax error, unexpected end of file in phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/EvalFile_Command.php(76) : eval()'d code on line 409

OS Info:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)

PHP Version: 7.4.3

**Comment by schlessera** [comment]
This probably means the PHP file your `eval`ing is corrupt. You'd need to post the actual code for me to be able to help you further.

**Comment by anubisthejackle** [comment]
For what it's worth, anyone looking in the future, I've seen this error crop up when eval-ing code that included PHP opening and closing tags.

Example:

```php
eval("<?php echo 'test'; ?>");
```

This will throw an error. The solution is to close the hidden opening tag, like so:

```php
eval("?><?php echo 'test'; ?>");
```

Sandbox Example: https://3v4l.org/hZXPo

**Comment by Rococolab** [comment]
and I have this error
WP-CLI (2.50) was working fine 
 Parse error:  syntax error, unexpected token "if" in phar:///usr/local/bin/w p/
vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 77

eval("<?php echo 'test'; ?>");
-bash: syntax error near unexpected token `"<?php echo 'test'; ?>"'

Running on LEMP Ubuntu 20.04/PHP 8.08 on a development platform

After the initial install, i used the command as usual to install a few plugins (but never activated any), tested the site everything seem ok and then not sure if it is after running update/upgrade that it no longer worked.

Would removing and re-installing wp-cli be of any help?

**Comment by schlessera** [comment]
@anubisthejackle This is to be expected, as the `eval` command is specifically about executing PHP code. What you try to pass into it is templated HTML instead.

@Rococolab I'm unable to help you without knowing what you are trying to eval, but from the looks of the error message, I'm assuming that this has more to do with incorrect escaping of shell input, as `bash` is the one complaining.

In general, it is pretty complex to correctly escape code in the shell, and the OPs problems are very probably a result of that as well. As the command seems to work as expected from what I can tell, I'm closing this issue for now.

Please join me in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/) to discuss details about specific commands so we can figure out where the escaping went wrong.
