### ISSUE TITLE
wp post update slug-of-post

### ISSUE THREAD

**Issue by nextgenthemes** [wp-cli/wp-cli#5487]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I like to update content for posts that id I do not know. I have seen code snippets to get "post id by slug" things but I think it would be great if WP-CLI would make this easy possible. Probably something great for edit/update and a lot of other cases that require a specific id.

**Describe the solution you'd like**

`wp post update slug-of-post ...`

If could simply assume a slug if the argument is not numeric or 

`wp post update --slug="slug-of-post" ...`

**Comment by johnbillion** [comment]
[One of the philosophies of WP-CLI is that composability is always a good idea](https://make.wordpress.org/cli/handbook/contributions/philosophy/#composability-is-always-a-good-idea). As a result, what you want is already possible:

```
wp post update $(wp post list --name="slug-of-post" --field=ID) ...
```

This seems like quite a narrow use case, I don't think it's worth adding to WP-CLI.

**Comment by nextgenthemes** [comment]
Oh that's cool. But how is this a narrow use case? Do you know all your post IDs on the top of your head? I do not think the creation of posts even returns the ID in WP-CLI ... that would require scripting anyway.

**Comment by wojsmol** [comment]
When `--porcelain` flag is given then `wp post create` returns only created post id - see [documentation](https://developer.wordpress.org/cli/commands/post/create/).

**Comment by nextgenthemes** [comment]
OK that's also cool to know, even though the `wp list` solution is better and basically what I wanted in complicated. I still no not think this case is narrow. And as I already said this would require scripting to save the ID of a created post somehow to later use it to edit a post.

If I want to edit an existing post from CLI that exists I need the ID. How is that a narrow use case?
If I programmatically create some test posts I need each and every ID to later edit them. Why should I need to write a script or a complex subshell command to do that? That is pretty much one of THE use cases of WP-CLI.

There are many commands in WP-CLI that require ID and I think a simpler way like I suggest would be very useful and more importantly easy to remember instead of having this very long `wp post list` command on a subshell.

**Comment by nextgenthemes** [comment]
`wp post meta` would be another case I think is everything but narrow. Adding a custom data to a page/post that already exists and things like this would be easier and straight forward.
