### ISSUE TITLE
wp plugin update-all should check for updates rather than rely on the cache

### ISSUE THREAD

**Issue by wojsmol** [wp-cli/wp-cli#549]
Hallo
IMHO `wp plugin update-all` should make checking for updates, rather than relying on the last check performed by Wordpress. As last, knowing that there is a newer version of the plugin that I have installed on a fairly large number of Wordpress installation I used this command, but WP-CLI rather than inform obout the update returned information about their absence. Only this sequence of commands solved the problem:
```
wp plugin status
wp plugin update-all
```
Regards

**Comment by planetahuevo** [comment]
How can we force a check and not rely on cache?
