### ISSUE TITLE
Mass Search-Replace Different Text in Database

### ISSUE THREAD

**Issue by momomesh** [wp-cli/wp-cli#5491]
This is the first time asking a question in the holy grail of programming nest, so pardon my stupid questions,
I finally got wp-cli installed on my server and got SSH connection via Putty to it,

Hurray, and I did a "wp search-replace" to my serialized database and it went through successfully,
now the biggest concern I have right now is I have more than 20k different databases to find and replace,

it's already in an excel sheet column 1 find, column 2 replace,
just wanted to ask the gurus, how many lines of codes can I enter into the Putty SSH wp-cli?

I've tried 10 so far, and it went successfully,
just wanted to to ask is there a quicker way to do it?

just need some where to read about how to implement it?
what scripts I need to read up, and can I just paste 1,000 lines of codes at a time?

wp search-replace "find1" "change1" wp_postmeta meta_value   --skip-columns=meta_key
wp search-replace "find2"   "change2" wp_postmeta meta_value --skip-columns=meta_key
wp search-replace "find3"   "change3" wp_postmeta meta_value --skip-columns=meta_key
wp search-replace "find4"   "change4" wp_postmeta meta_value --skip-columns=meta_key
wp search-replace "find5"   "change5" wp_postmeta meta_value --skip-columns=meta_key
wp search-replace "find6"   "change6" wp_postmeta meta_value --skip-columns=meta_key
....till 1,000 lines?

can I just paste the whole thing in?
or do I need to split it up? will it do it one by one?

sorry this is the first time doing coding.

**Comment by wojsmol** [comment]
> now the biggest concern I have right now is I have more than 20k different databases to find and replace,

Different databases or different values in one database?

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the Make [WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by momomesh** [comment]
same database different values,
example, youtube.com/jfjrie88943 to vimeo.com/8jkf89d898fd,

but I have almost 20k links to change.
they're at hand, do I have to split them into batches or I can just paste the whole 20k lines of codes into the putty SSH?

Thanks for replying mate!

**Comment by wojsmol** [comment]
Yon can use simple bash loop for this and a csv file as a data source. Convert Excel sheet to csv with structure like this:
```
find1;change1;
find2;change2;
```
then create .sh file with content like this
```bash
#!/bin/bash
web="/PATH/TO/WORDPRESS/" #absolute bath to WordPress
while IFS=$(echo ';') read fimd replace
do
cd ${web} && wp search-replace "${fimd}" "${replace}" wp_postmeta meta_value --skip-columns=meta_key
done < ./in.csv
```
Using Notepad++ convert line endings to LF in both files. **Make current database backup.** After that place both files on the server next to each other. Then in putty execute `chmod +x ./filename.sh` to make this file executable and run  `./filename.sh`

**Comment by momomesh** [comment]
I know it's super easy for you guys to implement,
but I'm a total newbie,

can you point me in the right direction in what keywords to google to read up on how to implement the codes you stated above? like "notepad++ convert line endings to LF" what should I read up?

anyways I'll try to do as what you told step by step,
If I succeed or face any problems after trying to google them I'll report back!

and thank you from the bottom of my heart!

**Comment by wojsmol** [comment]
Please join WordPress slack - link in the secoubd part of my first message and the we can chat in #cli channel :)

**Comment by momomesh** [comment]
joined slack kinda tricky,
getting the hang of it, might as well download the slack. have to signup for wordpress account too.

hold on.

**Comment by momomesh** [comment]
Thanks to @wojsmol this issue has been resolved! 

Thanks a million!

**Comment by momomesh** [comment]
btw @wojsmol,
what if I want to find and replace <iframe src="https://youtube"></iframe> codes with another <iframe src="videmo.com"></iframe> codes?

in the .csv file how do I make it find and replace the whole code?
I tried <iframe src="https://youtube"></iframe>;<iframe src="videmo.com"></iframe>;

it didn't work, but changing the middle https worked,

Thanks
