### ISSUE TITLE
Debian packaged wp-cli does not seem to work with debian packaged wordpress

### ISSUE THREAD

**Issue by ianbmacdonald** [wp-cli/wp-cli#5493]
## Bug Report

Currently the Debian packaged wp-cli doesn't appear to work within the packaged wordpress environment.   Even after creating a separate user with required permissions, and excluding themes and plugins, it seems to fail. 

Background:
We run our enterprise wordpress environments in Debian, in part due to the strict policy around feature introduction mid-release cycle and FHS policies that inform security best-practices.

Debian wordpress packages run as an unpriviledged user (one that does not have login privledges by default) and has a file struture that adheres to best practices (per Debian policy), i.e. it follows the FHS standard for location and permissions related to configuratin, dynamic content, etc. 

ie. It is not a flat dump into /siteroot/ with wholesale access from the same user as the apache2 daemon which appears to be where a lot instances and examples with wp-cli are spawned from

Problem Scenarios: 
Firstly, you can't just sudo to the user running the web service, www-data without enabling that user to have shell access; So a user has to be created, seperate from the one serving the public via apache2, whith the proper file system access. 

```
sudo -u www-data -i -- wp plugin list --url=website.com --debug
This account is currently not available.

```

In our case we happen to have a user defined that has access wordpress folders for use with the ftpsockets FS_METHOD during theme and plugin upgrades.

Unfortunately, even after excluding themes and plugins per https://github.com/wp-cli/wp-cli/issues/2376 we still can't seem to make wp-cli enumerate configuration.  we have no includes in our config-website.com.php

`sudo -u ftpsecure -i -- wp config --skip-plugins --skip-themes --url=website.com --debug
`
resulting in the following console error 
 ...
```
Debug (bootstrap): Begin WordPress load (0.213s)
Debug (bootstrap): wp-config.php path: /usr/share/wordpress/wp-config.php (0.213s)
Debug (commands): Deferring command: redirection import (1.092s)
Debug (commands): Deferring command: redirection export (1.092s)
Debug (commands): Deferring command: redirection database (1.092s)
Debug (commands): Deferring command: redirection setting (1.092s)
Debug (commands): Deferring command: redirection plugin (1.092s)
Debug (commands): Adding command: action-scheduler (1.662s)
Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.

```

and the following php debug log

` PHP Fatal error:  Cannot redeclare wp_get_server_protocol() (previously declared in /usr/share/wordpress/wp-includes/load.php:16) in /usr/share/wordpress/wp-includes/load.php on line 21
`

The only thing we seem to be able to do is
`sudo -u ftpsecure -i -- wp cli info  --skip-plugins --skip-themes --url=website.com --debug
`
which reports some cli information 

Hopefully there is a simple workaroud for systems using packaged wordpress in production scenarios, as it is useful to be able orchestrate wordpress from command line for certain types of mainteance.

**Comment by danielbachhuber** [comment]
Sorry for your troubles, @ianbmacdonald.

Closing this issue because it's stale. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
