### ISSUE TITLE
make-pot tries to execute sh on windows

### ISSUE THREAD

**Issue by sephentos** [wp-cli/wp-cli#5496]
Hi guys,

coming from _s starter wordpress theme ( https://github.com/Automattic/_s ).
They provide running ```composer make-pot ``` 
which simply runs ```wp i18n make-pot . languages/test.pot``` in the command line of windows.

Result of that:

![grafik](https://user-images.githubusercontent.com/35430448/107169151-7eae0000-69bd-11eb-811a-b5e98cd66634.png)

Although the error is in german, its just windows telling that "sh" could not be found and executed (which is of course logic since i'm not running linux). 

Just wondering about the windows compatibility of wp-cli and why this utility tries to run a linux shell script on windows?
Any idea with that?

composer.json
```
    "require-dev": {
...
        "wp-cli/i18n-command": "^2.2.5"
    },
    "scripts": {
...
        "make-pot": "wp i18n make-pot . languages/test.pot"
    },
```

**Comment by swissspidy** [comment]
I moved this issue to the corect place now since it's not about the i18n command.

@schlessera any ideas regarding the above error?

**Comment by schlessera** [comment]
@sephentos You're environment is not POSIX compliant. The particular issue here is that the standard shell binary `sh` is not available. You can try executing WP-CLI via `wp.bat` instead. However, do note that there's no official support for running WP-CLI on Windows. I'd recommending setting up WSL (2) on a Windows machine to run server CLI tools, as that is POSIX compliant.

I'm closing off this issue as GitHub is not meant for support requests. Feel free to join us in the MakeWP Slack under the `#cli` channel to discuss this further, as I think there might be other folks running present that run WP-CLI directly under Windows.
