### ISSUE TITLE
where is htaccess

### ISSUE THREAD

**Issue by truesamurai** [wp-cli/wp-cli#5497]
Today I did my first WordPress install with wp_cli.
All went fine, except my htaccess is missing.

In my root I have a wp-cli.yml with:
apache_modules:
         - mod_rewrite

and I did wp rewrite flush --hard 
but no htaccess is generated.

Whats the best way to create htaccess with wp_cli ?
I can create it manually but I was thinking it should be in the install with wp_cli.

**Comment by marcinkrzeminski** [comment]
Hey @sh1va73,

Try setting up permalinks first, to something like this: `wp rewrite structure '%postname%'`. Adjust the structure to your liking if needed.
