### ISSUE TITLE
Add support for application passwords

### ISSUE THREAD

**Issue by binaryfire** [wp-cli/wp-cli#5512]
Hi guys,

Now that application passwords have been added to core, could we get some wp cli commands to manage them?

Cheers

**Comment by chesio** [comment]
Hi @binaryfire,

this idea has already been raised here: https://github.com/wp-cli/ideas/issues/160

**Comment by binaryfire** [comment]
Hey @chesio. Thanks, I searched but must have missed it. Closing this in favour of the other issue.
