### ISSUE TITLE
Site tagline is "Just another Fake Site site" after wp core multisite-install

### ISSUE THREAD

**Issue by binaryfire** [wp-cli/wp-cli#5515]
Hi guys,

If multisite settings are already defined in wp-config.php, then **wp core multisite-install** results in the site's tagline being "Just another Fake Site site" 

Is this a bug?

Cheers

**Comment by nickdaugherty** [comment]
The `Fake Site` is hardcoded here and set during `wp core multisite-install` - https://github.com/wp-cli/wp-cli/blob/b2818e0c515c040ce518a46e3d6ad8a24e82e6e0/php/WP_CLI/Runner.php#L1315
