### ISSUE TITLE
How to check the version of included extension-command

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#5531]
Is there a way to check in cli directly, which version of wp-cli/extension-command is included in the currently installed version of wp-cli? (stable, nightly)
I'm asking since the extension-command has an independent release cycle and I would like to know if I'm on the latest version of it or not.

**Comment by schlessera** [comment]
The Phar release of WP-CLI has a list of its bundled dependencies added at its end to verify what the actual versions are. You can check the version of the `wp-cli/extension-command` package with something like this:
```bash
tail -100 $(which wp) | grep -a extension-command
```
Latest nightly should use `v2.1.0` of the `wp-cli/extension-command` package.
