### ISSUE TITLE
Warning: Failed pre-update status code check (HTTP code 418).

### ISSUE THREAD

**Issue by danielbair** [wp-cli/wp-cli#5532]
When trying to update plugins or themes I am now getting this...
Fetching pre-update site response...                                                                                                                  
 -> HTTP status code: 418                                                                                                                             
 -> I'm a little teapot.                                                                                                                              
Warning: Failed pre-update status code check (HTTP code 418).

wp cli core us up-to-date on my server when I checked.

I have checked the error logs on my server, and I don't see any HTTP code 418 being thrown, so where is this coming from?

I have no problem updating plugins and themes via InfiniteWP though.

**Comment by danielbair** [comment]
I do have better-wp-security installed, but what ip is wp cli coming from? 127.0.0.1 or such or another ip?

**Comment by rkasselman** [comment]
Also experiencing this on some websites. Can update core and themes, but not plugins.

**Comment by danielbair** [comment]
@rachelbaker Do you have the wp-cli package update-verify installed? Are you running better-wp-security (iThemes Security)? What hosting server are you running on? I am experiencing this on DreamHost servers. And wp-cli was setup by DreamHost with alot of wp-cli packages installed including update-verify. When I installed wp-cli in my local user and used that one (without update-verify) then I was able to update/install themes and plugins again.

**Comment by danielbair** [comment]
Ok, I setup a test wp install and was able to discover that this problem only exists when the better-wp-security plugin is installed. I have filed a bug report with them for now and my local wp-cli workaround with update-verity disabled is what I am able to use for now.

**Comment by rkasselman** [comment]
Also on Dreamhost servers, mostly on shared hosting packages. One plugin blocks almost everything. That is the Bad Behavior plugin. Does not allow CLI to perform updates or almost anything else. Nobody has commented on the plugin for seven months or more. Disabled it and CLI works perfect.
