### ISSUE TITLE
MYSQL_PWD is deprecated in mysql client 8.0, wp db check fails

### ISSUE THREAD

**Issue by johnkawakami** [wp-cli/wp-cli#5534]
https://github.com/wp-cli/wp-cli/blob/c3bd5bd76abf024f9d492579539646e0d263a05a/php/utils.php#L528

Oracle says MYSQL_PWD is deprecated in version 8.0. I am running mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

"wp db" commands won't connect to the database.

I am able to log into the database via the client, directly, if I use a password on the console, or on the command line, or with a mysql configuration file.

I am able to connect to the database through the website, as well.

**Comment by danielbachhuber** [comment]
I'm not quite sure what the issue is here. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
