### ISSUE TITLE
Publishing a post on a wordpress installation using wp post create does not generate hooks such as publish_post

### ISSUE THREAD

**Issue by antoineyvon** [wp-cli/wp-cli#5538]
**Describe the current, buggy behavior**

Publishing a post on a wordpress installation using wp post create does not generate hooks such as "publish_post".

**Describe how other contributors can replicate this bug**

- Register callback function that shows that it has been called  for "publish_post" hook
- Publish a post with WP Cli 

**Describe what you expect as the correct outcome**

- The hook would be generated in the same way as it is when publishing from the back office

**Comment by danielbachhuber** [comment]
Thanks for the report, @antoineyvon.

`wp post create` simply calls `wp_insert_post()` under the hood, so all of Core's actions and filters will be used.

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
