### ISSUE TITLE
wp site create exits without success message (no id with `--porcelain`)

### ISSUE THREAD

**Issue by rastitkac** [wp-cli/wp-cli#5548]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When creating a subsite on multisite with `wp site create --slug=your-site-slug --porcelain` the stdout is empty if successful, instead of returning ID of the created site.
I can reproduce it with:
- wp-cli@2.5.0 on PHP@7.4.21
- wp-cli@2.4.0 on PHP@7.4.16
 
However it works as expected with:
- wp-cli@2.3.0 on PHP@7.4.20.

**Describe how other contributors can replicate this bug**

- Create and setup a multisite install (subfolder)
- Run `wp site create --slug=your-site-slug --porcelain`
- If the command is successful, it exits with empty STDOUT (which should be the id of the new site). 
Also when run without `--porcelain` flag, there is no success message (but the site is created correctly).
- If the site already exists, it exits (correctly) with the error "Error: This site already exists!" (also without `--porcelain`)

**Describe what you expect as the correct outcome**

I expect the command to return the id of the newly created site on exit

**Let us know what environment you are running this on**

```bash
# incorrect outcome (local installation)
OS:	Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64
Shell:	/usr/local/bin/fish
PHP binary:	/usr/local/Cellar/php@7.4/7.4.21_1/bin/php
PHP version:	7.4.21
php.ini used:	/usr/local/etc/php/7.4/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.5.9-MariaDB, for osx10.16 (x86_64) using readline 5.1
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/rastitkac/sites/fhnw
WP-CLI packages dir:	/Users/rastitkac/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.5.0
```

```bash
# incorrect outcome (staging installation)
OS:	Linux 3.10.0-962.3.2.lve1.5.42.el7.x86_64 #1 SMP Mon Nov 9 08:11:18 EST 2020 x86_64
Shell:	/bin/bash
PHP binary:	/opt/alt/php74/usr/bin/php
PHP version:	7.4.16
php.ini used:	/opt/alt/php74/etc/php-cli.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/fhnwwebk/public_html/plattformen
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

```bash
# correct outcome (live installation)
OS:	Linux 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.20
php.ini used:	/etc/php/7.4/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/html/plattformen/wp-admin
WP-CLI packages dir:	/home/webkinder/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.3.0
```

**Comment by schlessera** [comment]
I cannot recreate this, so I'm assuming for now that this is a problem with your environment. are you able to try the following combinations as well?
- WP-CLI v2.3.0 on your local installation
- WP-CLI v2.5.0 on your live installation

This would give a clearer picture of whether this is tied to the WP-CLI version number or the environment in which it is run.

**Comment by danielbachhuber** [comment]
Closing because no reply. Feel free to re-open with further details.
