### ISSUE TITLE
wp-cli to check for ENV first and then if it's writable to avoid disk hit

### ISSUE THREAD

**Issue by lordspace** [wp-cli/wp-cli#5557]
This line checks if the file is wriable. Why not move that check later. Right after the env and posix_isatty() checks?
This should save a file operation I think
https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L1740

**Comment by danielbachhuber** [comment]
@lordspace It looks like your code reference is out of date, unfortunately 😦 

Which code execution are you referring to?

In the future, it's better to link to a specific hash if possible.
