### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [wp-cli/wp-cli#5560]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by chesio** [comment]
Hi,

if the issue is related to WP-CLI itselft, I believe you can contact @schlessera directly, he's the sole maintainer in the moment. If the issue however is related to WordPress, then you should report it via their [HackerOne page](https://hackerone.com/wordpress).

**Comment by chesio** [comment]
Update: it seems WordPress HackerOne profile should be used to report issues with WP-CLI too.

**Comment by schlessera** [comment]
@JamieSlome Thanks for getting in touch!

Please submit a security report via the WordPress team on HackerOne: https://hackerone.com/wordpress?type=team

Also, good point about the `SECURITY.md` file, I'll have one added.
