### ISSUE TITLE
Setting `DOMAIN_CURRENT_SITE` with hostname and port gets interpreted incorrectly 

### ISSUE THREAD

**Issue by Netroxen** [wp-cli/wp-cli#5565]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

* I set `define('DOMAIN_CURRENT_SITE', 'wordpress:8080');` in `wp-config.php` with `<HOST>:<PORT>`
* I then run ` wp site create --slug="foobar" --title="Foobar" --email="$WP_ADMIN_EMAIL"` in a multi-site installation
* The site URL is incorrectly interpreted.
  * Result: http://foobar.wordpress8080/
  * Expected: http://foobar.wordpress:8080/

```
root@xyz:/opt/bitnami/scripts/wordpress# wp site list --allow-root
+---------+-------------------------------+---------------------+---------------------+
| blog_id | url                           | last_updated        | registered          |
+---------+-------------------------------+---------------------+---------------------+
| 1       | http://wordpress:8080/        | 0000-00-00 00:00:00 | 2021-10-01 07:32:07 |
| 4       | http://foobar.wordpress8080/  | 2021-10-01 07:32:27 | 2021-10-01 07:32:27 |
+---------+-------------------------------+---------------------+---------------------+
```

**Describe what you expect as the correct outcome**

* The colon between the hostname and port should not be removed from the evaluated domain.

**Let us know what environment you are running this on**

```
PHP binary:	/opt/bitnami/php/bin/php
PHP version:	7.4.23
php.ini used:	/opt/bitnami/php/lib/php.ini
MySQL binary:	/opt/bitnami/mysql/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for Linux (x86_64) using readline 5.1
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/
WP-CLI packages dir:	/opt/bitnami/wp-cli/.packages/
WP-CLI global config:	/opt/bitnami/wp-cli/conf/wp-cli.yml
WP-CLI project config:	
WP-CLI version:	2.5.0
```

**Comment by janw-me** [comment]
A candidate for _good-first-issue_ ?

**Comment by wavvves** [comment]
Hi, just took a look at this for my [WCEU](https://europe.wordcamp.org/2022/) contributor day, and by looking at the code nothing seemed wrong, as it ultimately resorted to `wpmu_create_blog()` which does not seem to have port definition in mind at all.

After digging a bit deeper, it seems that actually multisite was made to only run on `:80` and `:443`, and there seems to be some [WIP](https://core.trac.wordpress.org/ticket/21077) to add custom port support to it.

**Comment by abdullah-kasim** [comment]
So we'd need to see if this is supposed to work (was this part of the docs?). I'm not sure if a `DOMAIN` is supposed to include the colon and the port. Will find out.

**Comment by abdullah-kasim** [comment]
Generally it looks like this configuration is not expected to be supported by wp-core. See https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/src/wp-admin/includes/network.php#L141 - we're detecting if non-80 or non-443 ports are being used.

Either `wp-core` should support such a config, or we'd have to provide an error message in `wp-cli`.

**Comment by abdullah-kasim** [comment]
Filed as a core bug: https://core.trac.wordpress.org/ticket/57748#ticket

**Comment by danielbachhuber** [comment]
Nice debugging, folks! Closing in favor of https://core.trac.wordpress.org/ticket/57748#comment:2
