### ISSUE TITLE
Curl Error 60 when trying to install package

### ISSUE THREAD

**Issue by Androlax2** [wp-cli/wp-cli#5567]
Hello,

I got this error while installing package :

```
Error: curl error 60 while downloading https://wp-cli.org/package-index/packages.json: SSL certificate problem: certificate has expired
```

I tried to reset wp-cli etc.. But nothing :/

**Comment by wojsmol** [comment]
Hi
Please post output of `openssl version` this most probably is caused by recent Let's Encrypt root certificate expiration.
