### ISSUE TITLE
Specify optional positional argument to Long Description Docblock

### ISSUE THREAD

**Issue by UVLabs** [wp-cli/wp-cli#5572]
I'm registering a command like this to allow for various operations to do with modules available in the theme such as listing, activating and deactivating:

`\WP_CLI::add_command( 'neve module', '\\Neve_Pro\\CLI\\Module' );`

Inside that `Module` Class it has some public methods that allow for activating and deactivating modules offered by the theme:

`public function activate(){}`
`public function deactivate(){}`

Here is sample code for the `activate` method:

```
  /**
    * Orchestrate the activating of one, many, or all Neve modules.
     *
     * ## OPTIONS
     *
     * <module_name>...
     * : The module(s) name that you want to activate.
     *
     * [--all]
     * : Activate all main modules.
     *
     * ## EXAMPLES
     *
     * wp neve module activate woocommerce_booster                   Activates WooCommerce Booster module.      
     * wp neve module activate woocommerce_booster blog_pro          Activates WooCommerce Booster and Blog Booster module.
     * wp neve module activate --all                                 Activates all modules.
     *
     * 
     * @param array $modules 
     * @param array $assoc_args 
     * @return void 
     * /
     public function activate( $modules, $assoc_args ) {

	$activate_all = $assoc_args['all'] ?? false;

	if ( $activate_all ) {
		$this->activate_all_modules();
	} else {
		$this->activate_module( $modules );
	}

    }
```

From the examples you can see how this command is meant to work. The thing is `wp neve module activate --all` won't work like that when making use of the WP CLI `long desc` because `<module_name>` is a required positional argument. **How can I declare an optional positional argument from inside a docblock?** I tried `[module_name]` with square brackets instead but that doesn't work. It gives the message `usage: wp neve module activate <optional>... [--all]`

I can however set the positional argument to be optional if I register the command like this instead:

```
$synopsis = array(
	‘shortdesc’=> ‘Orchestrate the activating of one, many, or all Neve modules.’,
	‘synopsis’=>array(
		array(
            ‘type’        => ‘positional’,
            ‘name’        => ‘module_name’,
            ‘description’ => ‘test’,
            ‘optional’    => true, // I can make optional here
            ‘repeating’   => true,
        ),
        array(
            ‘type’     => ‘flag’,
            ‘name’     => ‘all’,
            ‘optional’ => true,
        ),
	)
);

\WP_CLI::add_command( 'neve module activate', '\\Neve_Pro\\CLI\\Module' , $synopsis);
```
Trying to figure out if there's a way to specific an optional positional argument inside the docblock like there is in the example above.

**Comment by swissspidy** [comment]
Have you tried `[<module_name>]`?

**Comment by UVLabs** [comment]
@swissspidy Thank you! That worked. I had to also add `...` to allow for repeating arguments. So in the end `[<module_name>...]` worked for me.

**Comment by UVLabs** [comment]
@swissspidy I proposed a small edit to the handbook to include this example here: https://github.com/wp-cli/handbook/pull/390
