### ISSUE TITLE
search-replace takes 2 passes to find all references

### ISSUE THREAD

**Issue by bradp-wordkeeper** [wp-cli/wp-cli#5573]
I use wpcli constantly and one of the main tasks I use it for is to replace the domain of a site for use in staging sites.  I ran across a site recently where it always takes 2 passes of search-replace to find all references.

The only other time I've seen this kind of issue was when there was a database trigger set up which ended up getting triggered during the search-replace operation and causing problems.  But that isn't the case this time and I can't find out why it always takes two search-replace passes on this 1 particular site.

Please note the following:
- All plugins have been disabled (including dropins and MU)
- Theme is the default 2021 theme
- Wordpress core files pass validation so there are no modifications

Here is a test:
```
$ wp search-replace '//test1.com' '//test2.com' --all-tables 2>/dev/null | grep Success
Success: Made 43773 replacements.

$ wp search-replace '//test1.com' '//test2.com' --all-tables 2>/dev/null | grep Success
Success: Made 761 replacements.

$ wp search-replace '//test1.com' '//test2.com' --all-tables 2>/dev/null | grep Success
Success: Made 0 replacements.
```

And another test run right after:
```
$ wp search-replace '//test2.com' '//test3.com' --all-tables 2>/dev/null | grep Success
Success: Made 43773 replacements.

$ wp search-replace '//test2.com' '//test3.com' --all-tables 2>/dev/null | grep Success
Success: Made 761 replacements.
```

For some reason, if I use the --regex option then it works all in 1 pass.  But it takes forever, of course.
```
$ wp search-replace '//test3.com' '//test4.com' --all-tables --regex 2>/dev/null | grep Success
Success: Made 44534 replacements.
```

I also tried the --precise option but that doesn't seem to work very well.
```
$ wp search-replace '//test4.com' '//test5.com' --all-tables --precise 2>/dev/null | grep Success
Success: Made 24432 replacements.

$ wp search-replace '//test4.com' '//test5.com' --all-tables --precise 2>/dev/null | grep Success
Success: Made 11102 replacements.

$ wp search-replace '//test4.com' '//test5.com' --all-tables --precise 2>/dev/null | grep Success
Success: Made 5000 replacements.
```

Any idea why it always takes 2 search-replace passes to fully replace the domain on this 1 site?  Is there anything else besides a database trigger that I should look into?

Let me know if you need any more info!

**Comment by schlessera** [comment]
Fixed with v2.6.0 release.
