### ISSUE TITLE
Cache: Change file cache size

### ISSUE THREAD

**Issue by mn7zDev** [wp-cli/wp-cli#5574]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**
The main problem is WP-CLI file cache size cannot be changed. Cache storage size should be changeable, we need to store more than 300MB in the cache.
**Describe the solution you'd like**
If file storage size is set in environment variables it should be taken from there.

**Comment by schlessera** [comment]
@mn7zDev Are you up for providing a pull request to add two environment variables:

* `WP_CLI_CACHE_MAX_SIZE` with a default of 300MB
* `WP_CLI_CACHE_EXPIRY` with a default of 6 months
