### ISSUE TITLE
Can't run WP-CLI: PHP Parse error:  syntax error, unexpected '?'

### ISSUE THREAD

**Issue by dddns** [wp-cli/wp-cli#5577]
Howdy,
I've been using wp-cli for some time, and now I have a instalation of wordpress that it doesn't run/work.

No matter what I try to do, a search-replace or other command, I always get this information.
What can I do to make it work?
I have a feeling that is due to some plugins on this instalation.

wp-cli config list --allow-root
PHP Parse error:  syntax error, unexpected '?' in phar:///sbin/wp-cli/vendor/wp-cli/config-command/src/Config_Command.php(365) : eval()'d code on line 1

**Comment by wojsmol** [comment]
@dddns This error is probably related to content of `wp-config.php`.

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the Make [WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by dddns** [comment]
Ok understand, but no about wp-config, i compared it with an instalation that works.

**Comment by dddns** [comment]
@wojsmol this was indeed a bug report, not a general user question :P I'm sysadm not user.
Thanks for the fix.
