### ISSUE TITLE
WP Cron Schedule to specific time interval is not working

### ISSUE THREAD

**Issue by krupal-panchal** [wp-cli/wp-cli#5592]
Hello,

I have one cron event (ex. my_cron_test), which runs every 12 hours. I want to reschedule it for every 14 hours.
So I tried with the below command.

> wp cron event schedule my_cron_test '+2 hour'

But it gives an error of  "Error: ''+2' is not a valid datetime." Is there any issue with that?

Thanks

**Comment by costdev** [comment]
Try changing the single quotes `'` to double quotes `"` - that works for me.
```
wp cron event schedule my_cron_test "+2 hour"
```

**Comment by krupal-panchal** [comment]
Hi @costdev 

Thanks for your help. I tried with your code and it's working, but I want something like that if I reschedule it for +2 hours then it runs every 14 hours. not +2 hours from the current time. Can I do that?

**Comment by chesio** [comment]
Hi @krupal-panchal,

you need to define a custom interval (custom schedule) with 14 hours and use it with your task - see: https://developer.wordpress.org/plugins/cron/understanding-wp-cron-scheduling/

As far as I know, there is no way how to do it with WP-CLI only, but I might be mistaken.

**Comment by krupal-panchal** [comment]
Okay @chesio

I'll check it out that.

**Comment by schlessera** [comment]
Custom intervals need custom PHP logic, which is not something WP-CLI can just add. You'll have to add that in a separate way (custom plugin).

If you need further support, the easiest way is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
