### ISSUE TITLE
Purge git history for irrelevant files from all repos

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5594]
WP-CLI started out as a singe repository in git and was split up into multiple packages many years later.

When splitting up the packages, we tried to make sure that no historical knowledge is lost, so each subsplit package started out as the original main package and then removed the files that were not needed.

However, it seems like the purging we did afterward to remove unused history was not thorough enough.

Right now, each package contains the history of all WP-CLI files across all commands up to the point of the split. This makes most statistics and contribution data useless and drastically increases the size of the individual VCS repos. When cloning a full environment, each command repo has about 10MB of historical data of which most is useless.

To solve this, a more thorough purge should be done:
```bash
git checkout master
git ls-files > keep-these.txt
git ls-files | while read -r line; do (git log --follow --raw --diff-filter=R --pretty=format:%H "$line" | while true; do if ! read hash; then break; fi; IFS=$'\t' read mode_etc oldname newname; read blankline; echo $oldname; done); done >> keep-these.txt
git filter-branch --force --index-filter  "git rm  --ignore-unmatch --cached -qr . ; cat $PWD/keep-these.txt | tr '\n' '\0' | xargs -d '\0' git reset -q \$GIT_COMMIT --" --prune-empty --tag-name-filter cat -- --all
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
```

Then, the `master` branch needs to be force-pushed to overwrite the current `master` branch history.

:warning: However, this will cause all open PRs to become invalid and immediately be closed! :warning:

Therefore, this should be worked upon for each repo separately, while first ensuring no PRs are open against the `master` branch anymore.

TODO:
- [x] [wp-cli/wp-cli-bundle](https://github.com/wp-cli/wp-cli-bundle)
- [x] [wp-cli/cache-command](https://github.com/wp-cli/cache-command)
- [x] [wp-cli/checksum-command](https://github.com/wp-cli/checksum-command)
- [x] [wp-cli/config-command](https://github.com/wp-cli/config-command)
- [x] [wp-cli/core-command](https://github.com/wp-cli/core-command)
- [x] [wp-cli/cron-command](https://github.com/wp-cli/cron-command)
- [x] [wp-cli/db-command](https://github.com/wp-cli/db-command)
- [x] [wp-cli/embed-command](https://github.com/wp-cli/embed-command)
- [x] [wp-cli/entity-command](https://github.com/wp-cli/entity-command)
- [x] [wp-cli/eval-command](https://github.com/wp-cli/eval-command)
- [x] [wp-cli/export-command](https://github.com/wp-cli/export-command)
- [x] [wp-cli/extension-command](https://github.com/wp-cli/extension-command)
- [x] [wp-cli/i18n-command](https://github.com/wp-cli/i18n-command)
- [x] [wp-cli/import-command](https://github.com/wp-cli/import-command)
- [x] [wp-cli/language-command](https://github.com/wp-cli/language-command)
- [x] [wp-cli/maintenance-mode-command](https://github.com/wp-cli/maintenance-mode-command)
- [x] [wp-cli/media-command](https://github.com/wp-cli/media-command)
- [x] [wp-cli/package-command](https://github.com/wp-cli/package-command)
- [x] [wp-cli/rewrite-command](https://github.com/wp-cli/rewrite-command)
- [x] [wp-cli/role-command](https://github.com/wp-cli/role-command)
- [x] [wp-cli/scaffold-command](https://github.com/wp-cli/scaffold-command)
- [x] [wp-cli/scaffold-package-command](https://github.com/wp-cli/scaffold-package-command)
- [x] [wp-cli/search-replace-command](https://github.com/wp-cli/search-replace-command)
- [x] [wp-cli/server-command](https://github.com/wp-cli/server-command)
- [x] [wp-cli/shell-command](https://github.com/wp-cli/shell-command)
- [x] [wp-cli/super-admin-command](https://github.com/wp-cli/super-admin-command)
- [x] [wp-cli/widget-command](https://github.com/wp-cli/widget-command)
- [x] [wp-cli/wp-cli](https://github.com/wp-cli/wp-cli)
- [x] [wp-cli/wp-cli-tests](https://github.com/wp-cli/wp-cli-tests)
- [x] [wp-cli/doctor-command](https://github.com/wp-cli/doctor-command)
- [x] [wp-cli/profile-command](https://github.com/wp-cli/profile-command)
- [x] [wp-cli/handbook](https://github.com/wp-cli/handbook)
- [x] [wp-cli/wp-cli.github.com](https://github.com/wp-cli/wp-cli.github.com)

**Comment by wojsmol** [comment]
@schlessera If  you are already doing task requiring 0 open PR's against `master` then maybe at the same time change `master` branch to `main` or `trunk`?

**Comment by schlessera** [comment]
@wojsmol Yes, agree, this should be done in tandem with #5598

**Comment by danielbachhuber** [comment]
Prior to purging the history, I'm capturing the code to each open pull request in this manner:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/36432/202736269-b2178869-1a16-40d0-914f-4aa9a08067ae.png">

If the pull request doesn't have an issue, I'll open that too.

**Comment by danielbachhuber** [comment]
On Mac, `xargs` doesn't have `-d`. The easy workaround is to `brew install findutils` for `gxargs`:

```
git checkout master
git ls-files > keep-these.txt
git ls-files | while read -r line; do (git log --follow --raw --diff-filter=R --pretty=format:%H "$line" | while true; do if ! read hash; then break; fi; IFS=$'\t' read mode_etc oldname newname; read blankline; echo $oldname; done); done >> keep-these.txt
git filter-branch --force --index-filter  "git rm  --ignore-unmatch --cached -qr . ; cat $PWD/keep-these.txt | tr '\n' '\0' | gxargs -d '\0' git reset -q \$GIT_COMMIT --" --prune-empty --tag-name-filter cat -- --all
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
```

**Comment by danielbachhuber** [comment]
🚢
