### ISSUE TITLE
I have the following questions ...

### ISSUE THREAD

**Issue by raghavan2004** [wp-cli/wp-cli#5595]
My idea is to create a one click installer for my project for wordpress installation...( eg : cpanel / softaculous installer for wordpress)

How do i run this command and install wordpress and mysql 

1 ... will i be able to install the wordpress in my aws ec2 instances...
2.. I like to know while installing Do i need need to manually add the database details or will it be created automatically and also the wp-config file is automatically created...
3 ... Can i run this wp-cli package by using a button click in a php file ..

will be of great help ...

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment.

For support options, please review https://wp-cli.org/#support .
