### ISSUE TITLE
PHP Fatal error:  Cannot declare class WP_CLI, because the name is already in use

### ISSUE THREAD

**Issue by markmaurerrr** [wp-cli/wp-cli#5596]
In a fresh installation on a new m1 mac i get the following error on **wp plugin list**

`PHP Fatal error:  Cannot declare class WP_CLI, because the name is already in use in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php on line 26`

i tried version 2.5.0 as well as the nightly version 2.5.1

```
$ wp --info 
OS:	Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
Shell:	/bin/zsh
PHP binary:	/opt/homebrew/Cellar/valet-php@8.0/8.0.3/bin/php
PHP version:	8.0.3
php.ini used:	/opt/homebrew/etc/valet-php/8.0/php.ini
MySQL binary:	/opt/homebrew/bin/mysql
MySQL version:	mysql  Ver 14.14 Distrib 5.7.36, for osx10.17 (x86_64) using  EditLine wrapper
SQL modes:	NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/REMOVED/Desktop
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.5.1-alpha-0947428
```

What's going on?

**Comment by schlessera** [comment]
It looks like something is off in your specific environment.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review https://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
