### ISSUE TITLE
Switch main branch from `master` to `main` in all bundled packages

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5598]
Switch all main branches for the bundled packages from `master` to `main`.

:warning: However, this will cause all open PRs to become invalid and immediately be closed! :warning:

Therefore, this should be worked upon for each repo separately, while first ensuring no PRs are open against the `master` branch anymore.

Note: The Composer `branch-alias` needs to be adapted to change from `dev-master` to `dev-main` as well. Additionally, `wp-cli-dev` will need its `composer.json` file updated.

After the changes, the following commands can adapt a local repository for the same change:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

TODO:
- [x] [wp-cli/admin-command](https://github.com/wp-cli/admin-command)
- [x] [wp-cli/wp-cli-bundle](https://github.com/wp-cli/wp-cli-bundle)
- [x] [wp-cli/cache-command](https://github.com/wp-cli/cache-command)
- [x] [wp-cli/checksum-command](https://github.com/wp-cli/checksum-command)
- [x] [wp-cli/config-command](https://github.com/wp-cli/config-command)
- [x] [wp-cli/core-command](https://github.com/wp-cli/core-command)
- [x] [wp-cli/cron-command](https://github.com/wp-cli/cron-command)
- [x] [wp-cli/db-command](https://github.com/wp-cli/db-command)
- [x] [wp-cli/embed-command](https://github.com/wp-cli/embed-command)
- [x] [wp-cli/entity-command](https://github.com/wp-cli/entity-command)
- [x] [wp-cli/eval-command](https://github.com/wp-cli/eval-command)
- [x] [wp-cli/export-command](https://github.com/wp-cli/export-command)
- [x] [wp-cli/extension-command](https://github.com/wp-cli/extension-command)
- [x] [wp-cli/i18n-command](https://github.com/wp-cli/i18n-command)
- [x] [wp-cli/import-command](https://github.com/wp-cli/import-command)
- [x] [wp-cli/language-command](https://github.com/wp-cli/language-command)
- [x] [wp-cli/maintenance-mode-command](https://github.com/wp-cli/maintenance-mode-command)
- [x] [wp-cli/media-command](https://github.com/wp-cli/media-command)
- [x] [wp-cli/package-command](https://github.com/wp-cli/package-command)
- [x] [wp-cli/rewrite-command](https://github.com/wp-cli/rewrite-command)
- [x] [wp-cli/restful](https://github.com/wp-cli/restful)
- [x] [wp-cli/role-command](https://github.com/wp-cli/role-command)
- [x] [wp-cli/scaffold-command](https://github.com/wp-cli/scaffold-command)
- [x] [wp-cli/scaffold-package-command](https://github.com/wp-cli/scaffold-package-command/)
- [x] [wp-cli/search-replace-command](https://github.com/wp-cli/search-replace-command)
- [x] [wp-cli/server-command](https://github.com/wp-cli/server-command)
- [x] [wp-cli/shell-command](https://github.com/wp-cli/shell-command)
- [x] [wp-cli/super-admin-command](https://github.com/wp-cli/super-admin-command)
- [x] [wp-cli/widget-command](https://github.com/wp-cli/widget-command)
- [x] [wp-cli/wp-cli](https://github.com/wp-cli/wp-cli)
- [x] [wp-cli/wp-cli-tests](https://github.com/wp-cli/wp-cli-tests)
- [x] [wp-cli/doctor-command](https://github.com/wp-cli/doctor-command)
- [x] [wp-cli/profile-command](https://github.com/wp-cli/profile-command)
- [x] [wp-cli/handbook](https://github.com/wp-cli/handbook)
- [x] [wp-cli/wp-cli.github.com](https://github.com/wp-cli/wp-cli.github.com)

**Comment by danielbachhuber** [comment]
> ⚠️ However, this will cause all open PRs to become invalid and immediately be closed! ⚠️

@schlessera I believe Jetpack was able to switch the default branch name without this outcome. What makes you think this is what happen?

**Comment by danielbachhuber** [comment]
> I believe Jetpack was able to switch the default branch name without this outcome. What makes you think this is what happen?

Following up on [this Slack conversation](https://wordpress.slack.com/archives/C02RP4T41/p1657645742088899), it appears the automatic branch renaming can unexpectedly break for some repos with very old PRs, etc.

**Comment by danielbachhuber** [comment]
🚢

**Comment by danielbachhuber** [comment]
Fixed up with:
* https://github.com/wp-cli/wp-cli-bundle/commit/a425d41c13a10e0999bb7a147d47ac39913ad4ad
* https://github.com/wp-cli/automated-tests/commit/9b58933acde137af079070db9938f420bc03210f
* https://github.com/wp-cli/wp-cli-dev/pull/41
