### ISSUE TITLE
[2.6.0] GPG key was changed without documentation. 

### ISSUE THREAD

**Issue by tuxmaster5000** [wp-cli/wp-cli#5608]
On
https://make.wordpress.org/cli/2018/05/31/gpg-signature-change/
is noted that the new key has no expire date.
But it don't fit to the asc file of the 2.6.0 version.
```
/gpgverify --keyring=/builddir/build/SOURCES/Keys --signature=/builddir/build/SOURCES/wp-cli-2.6.0.phar.asc --data=/builddir/build/SOURCES/wp-cli-2.6.0.phar
gpgv: Signature made Wed Jan 26 01:11:45 2022 CET
gpgv:                using RSA key 3DCA429248511076B4EF6582832A67716C7B07AD
gpgv: Can't check signature: No public key
gpgverify: Signature verification failed.
```

**Comment by schlessera** [comment]
Thanks for the report, @tuxmaster5000 !

Indeed, the machine I did the release with does not have the correct key. I had assumed this would then throw an error message, but apparently `gpg` just used a different ky without any feedback.

I'll have to check if I can retrieve the original key from here (I'm on a different continent right now than the rest of my setup), or if I might need to announce a new key change. I'll keep you updated here.

**Comment by schlessera** [comment]
@tuxmaster5000 The release was now re-signed with (hopefully) the correct key. The updated files was pushed to the `wp-cli/builds` repo and re-uploaded to the release notes in both `wp-cli/wp-cli` and `wp-cli/wp-cli-bundle`.

Can you confirm that this now works as expected?

**Comment by tuxmaster5000** [comment]
Yes, now it works. :)
