### ISSUE TITLE
site create not working in a loop in 5.9

### ISSUE THREAD

**Issue by CactusWren2020** [wp-cli/wp-cli#5614]
**Describe the current, buggy behavior**

I am running wp site create in a loop in an .sh file. It is now not making the site, but still reporting Success.

**Describe how other contributors can replicate this bug**

- Wordpress multisite in 5.9
- use the below script in Windows
- observe the below report in log.out
- check the database and see the sites are showing up in wp_blogs but not getting their own tables
- clicking on the sites after the first one created goes back to the main site

### script to make sites
```
# saves log to log.out
exec 1>log.out 2>&1

for i in {6..10}
do
    # creates subsites in a multisite
    wp site create --slug=new_site_$i --title=new_site_$i --email=mike@mike.com
done
```

### output in log.out
```
C:\xampp\htdocs\network_sub>type log.out
Success: Site 6 created: http://www.network_sub.loc/sub6/
Success: Site 7 created: /
Success: Site 8 created: /
Success: Site 9 created: /
Success: Site 10 created: /
```

**Describe what you expect as the correct outcome**

My expectations were for the attached script to result in new subsites.

**Let us know what environment you are running this on**

Windows, xampp

**Provide additional context/screenshots**

Note that this is working on Wordpress 5.8 and ***the bug only showed up in 5.9***

**wp cli info output**
C:\xampp\htdocs\network_sub2>wp cli info
OS:     Windows NT 10.0 build 19044 (Windows 10) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\xampp\php\php.exe
PHP version:    8.0.3
php.ini used:   C:\xampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       C:\xampp\htdocs\network_sub2
WP-CLI packages dir:    C:\Users\micha/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0

**Comment by danielbachhuber** [comment]
Thanks for the report, @CactusWren2020 !

Were you able to figure this one out?
