### ISSUE TITLE
Using wp db export throws a mysql error

### ISSUE THREAD

**Issue by markhowellsmead** [wp-cli/wp-cli#5626]
The following error is generated since MySQL 5.7.31 and 8.0.21:

`mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces`

The [suggested solution](https://anothercoffee.net/how-to-fix-the-mysqldump-access-denied-process-privilege-error/) from the hosting company suggests the use of `--no-tablespaces` in the `mysqldump` command, but using `--include-tablespaces` as a CLI command option throws the error `mysqldump: [ERROR] unknown option '--include-tablespaces'`.

(WP 5.9.2, CLI 2.6.0).

**Comment by chesio** [comment]
That's strange, calling `wp db export` should include the `--no-tablespaces` parameter for `mysqldump`. As per `wp help db export`:

```
[--include-tablespaces]
  Skips adding the default --no-tablespaces option to mysqldump.
```

So you don't want to call `wp db export --include-tablespaces` if your mysql user does not have `PROCESS` privilege.

**Comment by markhowellsmead** [comment]
I ran it both with and without the parameter and get the same error.

**Comment by schlessera** [comment]
Are you sure you're running on the latest WP-CLI version? You can verify with `wp cli info`, it should be v2.6.0.

Also, you can see the actual MySQL command that is being executed by appending `--debug=db` to your command.

**Comment by markhowellsmead** [comment]
Yes, 2.6.0. I'm in contact with the hosting company because even though I definitely haven't made any changes (and they say they haven't), it suddenly started working again.
