### ISSUE TITLE
Utility functions not autoloaded for per-project Composer installation

### ISSUE THREAD

**Issue by ethanclevenger91** [wp-cli/wp-cli#5635]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When WP-CLI is required as a Composer dependency in a WordPress project managed with Composer (like Bedrock, for example), the Utils functions are all in a namespace, but don't belong to a class, so Composer doesn't autoload them. This means my code can call the `\WP_CLI\add_hook` function, but `\WP_CLI\Utils\describe_callable` may not be available, which can result in a fatal error.

With a global WP-CLI install, a check for the `WP_CLI` constant/class in most plugins prevents their commands and other code from being registered on vanilla WordPress requests (like the admin), so they don't get far enough to be using function in the `Utils` namespace. But because the `WP_CLI` class is autoloaded by Composer as a local dependency, and Composer's autoloader is required by Bedrock, the commands are loaded on all WordPress requests.

**Describe how other contributors can replicate this bug**

- Create a Bedrock WordPress install
- `composer require wp-cli/wp-cli`
- Install and activate [this plugin](https://wordpress.org/plugins/atum-stock-manager-for-woocommerce/), which calls the `add_hook` function when WP-CLI is available. 
- See fatal error site-wide

**Describe what you expect as the correct outcome**

No fatal error.

**Let us know what environment you are running this on**

There are a few versions of WP-CLI at play here.

There is a global WP-CLI available in WSL:

```
OS:     Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.29
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/ethan/code/prov
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  /home/ethan/code/prov/wp-cli.yml
WP-CLI version: 2.6.0
```

There is WP-CLI available globally in the Docker container in which the site is being run:
```
OS:     Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64
Shell:
PHP binary:     /usr/bin/php8.0
PHP version:    8.0.18
php.ini used:   /etc/php/8.0/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 8.0.28-0ubuntu0.21.10.3 for Linux on x86_64 ((Ubuntu))
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  /var/www/html/wp-cli.yml
WP-CLI version: 2.6.0
```

And there's the WP-CLI executable in `vendor/bin`:

```
OS:     Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php
PHP version:    7.4.29
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        /home/ethan/code/prov/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      /home/ethan/code/prov/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  /home/ethan/code/prov/wp-cli.yml
WP-CLI version: 2.6.0
```

**Provide a possible solution**

Add `utils-wp.php` and `utils.php` to the classmap portion of the Composer autoloader, or wrap them into some kind of helper class.

**Comment by danielbachhuber** [comment]
Hey @ethanclevenger91,

Thanks for the report!

For this particular scenario, the plugin's commands shouldn't be loaded outside of the WP-CLI environment.

A more reliable approach than `method_exists( '\WP_CLI', 'add_hook' )` is `defined( 'WP_CLI' ) && WP_CLI`. The `WP_CLI` constant is only defined true when WP-CLI is loaded through its bootstrap process:

https://github.com/wp-cli/wp-cli/blob/f8207adcb7f800a91ba380e4411611f36373f143/php/wp-cli.php#L4

Calling `WP_CLI::add_hook()` on a web request isn't a supported use case, so autoloading `\WP_CLI\Utils` isn't an appropriate fix.

Hope this helps!
