### ISSUE TITLE
Error: Callable "WPSEO_CLI_Yoast_Command_Namespace" does not exist, and cannot be registered as `wp yoast`

### ISSUE THREAD

**Issue by DrLightman** [wp-cli/wp-cli#5636]
Sorry for the minimal info provided.
Any idea where to look for this wp-cli fatal error?
Can't update any plugin via wp-cli, it doesn't even boot without arguments.
But `wp --version` works.

```
[root@web001]# wp
PHP Warning:  include(/opt/www/wp-content/plugins/wordpress-seo/vendor/composer/../../cli/class-cli-yoast-command-namespace.php): failed to open stream: No such file or directory in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 478
PHP Warning:  include(): Failed opening '/opt/www/wp-content/plugins/wordpress-seo/vendor/composer/../../cli/class-cli-yoast-command-namespace.php' for inclusion (include_path='.:/opt/remi/php74/root/usr/share/pear:/opt/remi/php74/root/usr/share/php:/usr/share/pear:/usr/share/php') in phar:///usr/local/bin/wp/vendor/composer/ClassLoader.php on line 478
Error: Callable "WPSEO_CLI_Yoast_Command_Namespace" does not exist, and cannot be registered as `wp yoast`.
```

WP-CLI 2.5.0
WordPress 5.3.3
Yoast SEO 13.5

I know components are outdated but can't do otherwise for a while.

Thank you.

**Comment by lukecav** [comment]
The WP-CLI command for Yoast SEO was added in version 14.0.
https://developer.yoast.com/features/wp-cli/reindex-indexables
https://yoast.com/indexables/
https://github.com/Yoast/wordpress-seo/releases/tag/14.0

**Comment by DrLightman** [comment]
Isn't that strange that such an error pops out? Shouldn't wp-cli just ignore Yoast since it doesn't provide commands in 13.5?

**Comment by danielbachhuber** [comment]
@DrLightman Feel free to drop by the `#cli` channel in WordPress.org Slack if you'd like help tracking this down further.
