### ISSUE TITLE
Allow registration of custom global arguments

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5649]
On WordPress.com, we'd like to add `--blog_id=<id>` as a global argument. WordPress.com has all sorts domain transformation logic in a long `sunrise.php` so, in certain cases, it would be more reliable to pass a specific `--blog_id=<id>` argument.

The idea was originally discussed in https://github.com/wp-cli/wp-cli/issues/854#issuecomment-27436064

Because `--blog_id=<id>` still requires some blog id -> URL lookup, I'm still not convinced it's something WP-CLI should be responsible for. However, third-party code (via `sunrise.php` or similar) could easily perform this logic, so it would be nice if it was possible to register `--blog_id=<id>` as a global argument.

A couple of ideas:
1. Have some form of filtering mechanism for the return values of `WP_CLI::get_configurator()`: https://github.com/wp-cli/wp-cli/blob/0c427c5f68f6265678e3db109d0a8f0e6f7887af/php/class-wp-cli.php#L61-L69
2. Allow a custom path to be defined for `config-spec.php`: https://github.com/wp-cli/wp-cli/blob/0c427c5f68f6265678e3db109d0a8f0e6f7887af/php/class-wp-cli.php#L65

I kind of like the second option, which would give the environment control over which global arguments were available. I'm not sure what breaks when you remove one, though.

**Comment by schlessera** [comment]
In general, the extensibility is not quite where we want to have it. This is not only the case for global flags, but also for extending/changing the flags of an existing command.

I think it might be preferable to think about a generic mechanism for adapting flags, with the global ones just happening to be a special case that is taken care of as well. Maybe the implementation has to be split up into two anyway, but it would be good to see if we can find a sort of "API" that would work across both global and regular flags.

Also, regarding the `--blog_id` flag, I just want to note that we explored this particular case during WCEU contributor day, and the actual access to the database from within the WP-CLI context turned out to be way more complicated to achieve than expected. Maybe this is a non-issue if you hard-code it for a certain platform, but it might still be more involved than anticipated. Something to keep in mind.

**Comment by danielbachhuber** [comment]
> I think it might be preferable to think about a generic mechanism for adapting flags, with the global ones just happening to be a special case that is taken care of as well. Maybe the implementation has to be split up into two anyway, but it would be good to see if we can find a sort of "API" that would work across both global and regular flags.

@schlessera Could you share a bit more detail on what you're thinking about in this regard?

> Also, regarding the `--blog_id` flag, I just want to note that we explored this particular case during WCEU contributor day, and the actual access to the database from within the WP-CLI context turned out to be way more complicated to achieve than expected. Maybe this is a non-issue if you hard-code it for a certain platform, but it might still be more involved than anticipated. Something to keep in mind.

Correct. My expectation is that each platform would need a custom implementation, which is why it wouldn't make sense as a global flag in WP-CLI proper.

**Comment by schlessera** [comment]
> Could you share a bit more detail on what you're thinking about in this regard?

My initial thought would be something like:
```php
WP_CLI::add_parameter( $command, $parameter, $callback );
```
For global parameters, we could have something like `'global'` as a special notation. In your above use case, this would then be something like:
```php
$blog_id_parameter = [
	'name' => 'blog_id',
	'type' => 'assoc',
	'default' => 0,
];
WP_CLI::add_parameter( 'global', $blog_id_parameter , $blog_id_callback);
```

The tricky bit is the timing and all the hardcoding we already have in place.

|What are your immediate thoughts about the feasibility of such a syntax?

**Comment by danielbachhuber** [comment]
@schlessera Thanks for clarifying! Your explanation makes sense to me 😄 

Personally, I don't see the need to introduce custom registration of global arguments as a developer-facing API. I'd be curious to learn more about the specific use-cases.

However, on a platform operator level (WordPress.com, WP Engine), it would be helpful to have some level of control over global arguments because the global argument behavior may or may not be available on the platform.

@wp-cli/committers Any other thoughts to bring into the mix?

**Comment by schlessera** [comment]
Related issue: https://github.com/wp-cli/ideas/issues/126

**Comment by danielbachhuber** [comment]
One challenge worth noting: if Package A registers a `--foo=<foo>` global parameter, it could negative impact the Package B's `--foo=<foo>` command argument. This is why I think it should be an platform operator API, not a package developer API.

I'd be curious to hear the specific use cases for making it a package developer API.

**Comment by danielbachhuber** [comment]
@wp-cli/committers Did a first pass with #5656 that I'd enjoy getting some thoughts on when someone has a moment.

**Comment by danielbachhuber** [comment]
From [Slack](https://wordpress.slack.com/archives/C02RP4T41/p1660837304377179):

> For now, I would suggest adding a filter after the config-spec.php has been processed. This will still leave the option open to get rid of that file later on. For providing the filter, to keep this from being to public right now, I suggest having an environment variable that provides a comma-separated list of fully qualified callables, i.e. :
> `WP_CLI_FILTER_GLOBAL_PARAMETERS="My\Project\Cli\GlobalParametersFilter::process"`
> This can easily be used in Composer projects or at the platform/integrator level, but it cannot be provided via WP-CLI packages or WP plugins.

**Comment by danielbachhuber** [comment]
For posterity, here's how we're implementing `--blog=<id>` in WPCOM's `sunrise.php`:

```php
function wpcom_wp_cli_handle_blog_global_param() {
	if ( ! class_exists( 'WP_CLI' ) ) {
		return;
	}
	if ( empty( WP_CLI::get_runner()->config['blog'] ) ) {
		return;
	}
	if ( ! is_numeric( WP_CLI::get_runner()->config['blog'] ) ) {
		WP_CLI::error( 'The --blog parameter is expected to be numeric.' );
	}
	$blog = get_site( WP_CLI::get_runner()->config['blog'] );
	if ( ! $blog ) {
		WP_CLI::error( 'The --blog value is not a valid blog.' );
	}
	WP_CLI::set_url( $blog->domain );
}
if ( defined( 'WP_CLI' ) && WP_CLI ) {
	wpcom_wp_cli_handle_blog_global_param();
}
```
