### ISSUE TITLE
Not getting active plugins in multisite installation

### ISSUE THREAD

**Issue by davidperezgar** [wp-cli/wp-cli#5650]
## Bug Report
Hello! I’m using WP-CLI in multisite, and when I’m using in a subsite is not getting active plugins.
For example: I use this custom command: wp cronsync fundacio -—url=[url.com](http://url.com/)  and is in subsite 7, and needs WooCommerce to be actived.
I use in the command switch_to_blog(7)  but gets fatal error with functions not defined of Woo, because is like using the active plugins from main site.
How would you recommend to approach this problem?

**Describe the current, buggy behavior**
Not manage to get active plugins in focused site. Using --url but it does not get active plugins. For ex. in a WooCommerce installation in subsite, does not work.

**Describe how other contributors can replicate this bug**

- Create a multisite
- Install for example a WooCommerce in a subsite
- Use a custom command that uses WooCommerce functions.

**Describe what you expect as the correct outcome**

It should scope in the site that we are pointing and get active plugins

**Comment by danielbachhuber** [comment]
Let's continue the conversation in #5622

**Comment by davidperezgar** [comment]
Ok! perfect
