### ISSUE TITLE
New nightly and tagging

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#5657]
Hi,

would it be possible to release a new nightly as some WP CLI packages (e.g. https://github.com/wp-cli/i18n-command/releases) have great new features/bug-fixes added.

If it's not too much effort, tagging nightly releases in github would be great too for later reference.

**Comment by strarsis** [comment]
+1! I am delighted that `wp i18n` had a new release that fixes many issues and also introduces a command to update (merge) PO files with POT files. As `wp i18n` ships bundled together with `wp`, a new release of `wp` would be great!
Currently a separate install of the newer `wp i18n` has to be used, also the `wp i18n` related classes of older `wp i18n` in the `wp` phar have precedence over the separately installed, newer version of `wp i18n`, so the `wp i18n` executable has to be invoked by absolute path.

**Comment by kkmuffme** [comment]
For some reason I didn't get a new nightly with wp cli update on July 14th. It looks like everything's there now though, with the latest nightly.
