### ISSUE TITLE
wp --context=admin doesn't trigger admin_init action

### ISSUE THREAD

**Issue by d1sparity-plesk** [wp-cli/wp-cli#5661]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

WP-CLI has got a cool feature "execution context". I have found that "admin" context doesn't trigger **admin_init** action.

**Describe how other contributors can replicate this bug**

- add hook for admin_init action with debug code
- run any command with --context=admin

**Describe what you expect as the correct outcome**

**admin_init** action is triggered

**Let us know what environment you are running this on**

WP-CLI version: 2.6.0

**Provide additional context/screenshots**

`do_action( 'admin_init' );` performs in the wp-admin/admin.php file.

Looks like admin context of wp-cli, requires this file inside [admin_init action handler](https://github.com/wp-cli/wp-cli/blob/ea0739650e442d56b67ca4be68adc82edba220ea/php/WP_CLI/Context/Admin.php#L41-L59) [here](https://github.com/wp-cli/wp-cli/blob/ea0739650e442d56b67ca4be68adc82edba220ea/php/WP_CLI/Context/Admin.php#L58)

So, so there is no place to trigger this action.

From Slack conversation https://wordpress.slack.com/archives/C02RP4T41/p1658199286371689

**Comment by danielbachhuber** [comment]
Thanks for the report, @d1sparity-plesk 

> * add hook for admin_init action with debug code
> * run any command with --context=admin

Just to confirm, where is your hook registered? Can you provide a code sample that reproduces the issue?

**Comment by danielbachhuber** [comment]
> Just to confirm, where is your hook registered? Can you provide a code sample that reproduces the issue?

@d1sparity-plesk Nevermind, I understand what's going on now.

**Comment by schlessera** [comment]
Fixed via #5663
