### ISSUE TITLE
No "necessary rights to create a new version" when importing

### ISSUE THREAD

**Issue by tamasgal** [wp-cli/wp-cli#5662]
I am trying to migrate a Wordpress instance and used the export feature of Wordpress to generate the XML and the authors file. Everything went well while importing with `import --authors=authors.csv ecap.wordpress.xml --path=/var/www/html/` until entry 961 where I got a confusing message saying:

```
Processing post #9 ("Welcome to ECAP") (post_type: page)
-- 961 of 1,244 (in file ecap.wordpress.2022-07-18_all_woWidgets.xml)
-- Wed, 20 Jul 2022 13:52:03 +0000
Error: You do not have the necessary rights to create a new version.
```

I removed that entry manually and tried again but this error happened a few items later again.

The error message is a bit confusing, what kind of "rights" is `wp-cli` referring to? I grepped the source code of `wp-cli` for this message but could not find an, neither in the Wordpress source.

**Comment by danielbachhuber** [comment]
Hey @tamasgal, thanks for the report!

> The error message is a bit confusing, what kind of "rights" is `wp-cli` referring to? I grepped the source code of `wp-cli` for this message but could not find an, neither in the Wordpress source.

That is a confusing error message!

My guess is that it's coming from a plugin. Could you download the site's codebase and see if the message exists there?
