### ISSUE TITLE
Add `--load-wordpress` flag to include commands registered in plugins and themes

### ISSUE THREAD

**Issue by ssnepenthe** [wp-cli/wp-cli#5666]
Hopefully I am not missing anything obvious... Should the output from `wp cli cmd-dump` include commands registered from plugins and themes?

Currently it does not.

If this is not the intended behavior, changing the command to be executed on `after_wp_load` looks like a simple fix.

```
OS:	Linux 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.30
php.ini used:	/etc/php/7.4/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.5.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/srv/www/wordpress-one/public_html
WP-CLI packages dir:	/home/vagrant/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	/srv/www/wordpress-one/wp-cli.yml
WP-CLI version:	2.7.0-alpha-73364e5
```

**Comment by danielbachhuber** [comment]
Hey @ssnepenthe,

Thanks for the question!

`wp cli cmd-dump` is used for generating the [WP-CLI Handbook](https://make.wordpress.org/cli/handbook/) and other sources of documentation.

I don't think we want to change its current behavior. However, we could introduce a `--load-wordpress` flag that would load WordPress and have the theme/plugin docs included.

> Hopefully I am not missing anything obvious... Should the output from `wp cli cmd-dump` include commands registered from plugins and themes?

Out of curiosity, could you share a bit more detail about how you're planning to use `wp cli cmd-dump` ?

**Comment by ssnepenthe** [comment]
> I don't think we want to change its current behavior.

Good to know, thanks for the follow-up!

It isn't actually affecting me - I am using this command to generate a list of core commands (with --skip-packages --skip-plugins --skip-themes) which is used as a sort of filter against the currently running command.

I dropped the flags to verify the difference, noticed that package commands were present but not theme and plugin commands, and thought it might be a bug.

**Comment by danielbachhuber** [comment]
> It isn't actually affecting me - I am using this command to generate a list of core commands (with --skip-packages --skip-plugins --skip-themes) which is used as a sort of filter against the currently running command.
> 
> I dropped the flags to verify the difference, noticed that package commands were present but not theme and plugin commands, and thought it might be a bug.

Ah! In that case, we'll punt on implementing this until someone actually finds it necessary.

Thanks for clarifying!
