### ISSUE TITLE
Missing image sizes after a media regenerate (to add a new size)

### ISSUE THREAD

**Issue by loicparent** [wp-cli/wp-cli#5667]
Hello,

(This is an issue or a question)

I added new image size and so, I tried to generate the new size to all the existing images using this command:
`wp media regenerate --image_size=thumb_120x120 --skip-delete --only-missing`

So I expected to generate only the files for only the new size and also, I expected that the image size was added to the list of current sizes in the table `_postmeta` of the database.

After the command process was finished, I noticed that the image file was well created and the new size was added in the database BUT the other sizes was not present in the database (for a lot of media).

Is this normal behavior? How can I get back the other sizes present in the folder `uploads`? Should I regenerate all the media size?

_Thank you for your help,
Loïc_

**Comment by chesio** [comment]
Hi @loicparent,

unfortunately this is a known issue, please see: https://github.com/wp-cli/media-command/issues/130

**Comment by loicparent** [comment]
Hi @chesio,

Ok Thank you so I will close this issue discussion and use [this thread](https://github.com/wp-cli/media-command/issues/130).
