### ISSUE TITLE
There's no command to check a specific plugin version

### ISSUE THREAD

**Issue by rafiahmedd** [wp-cli/wp-cli#5676]
We can see all the plugin list using wp cli and it also contains the plugin version however we can't see a specific plugin version. I think there should be a command for this.

**Comment by danielbachhuber** [comment]
Thanks for the report, @rafiahmedd! 

> however we can't see a specific plugin version. I think there should be a command for this.

I'm not sure I understand your suggestion. Can you share a bit more detail?

**Comment by rafiahmedd** [comment]
@danielbachhuber sorry for my confusing report. Let me make it clear. At this moment if we command `wp plugin list` then it shows all the available plugins with the version numbers. However what if I have more than 100 plugins on my site and I want to know one specific plugin version for example I have a plugin name `XYZ` and I want to check if this plugin is up to date or not then I have to command `wp plugin list` and then I have to look for the plugin `XYZ` to check it's version number. Can't we add something like this `wp plugin <plugin-slug/foldername> --version` to check a specific plugin's version number? 

Thanks, @danielbachhuber for replying to this.

**Comment by wojsmol** [comment]
@rafiahmedd There is `wp plugin get` command to get info for bone plugin.

**Comment by rafiahmedd** [comment]
@wojsmol thanks, however I didn't see this command

**Comment by rafiahmedd** [comment]
I am clear about this now, thanks to both of you I will close this issue.

**Comment by danielbachhuber** [comment]
Thanks for clarifying, @rafiahmedd — and thanks for helping out, @wojsmol !
