### ISSUE TITLE
Behat execution configuration

### ISSUE THREAD

**Issue by timotheemoulin** [wp-cli/wp-cli#5680]
Dear all,

Is there a way to set the behat configuration before running tests?

From what I can see, the database user/password is hardcoded in some places and unfortunately, my dev environment don't share the same config :)

Is there a guide/procedure to run behat locally?

**Comment by danielbachhuber** [comment]
Hey @timotheemoulin !

Feel free to stop by the `#cli` channel on [WordPress.org](https://make.wordpress.org/chat/) Slack if you'd like help figuring this out.
