### ISSUE TITLE
Error: The downloaded PHAR is broken

### ISSUE THREAD

**Issue by RoundAboutWEB** [wp-cli/wp-cli#5688]
Since 12/10 at 12:00 I get the following error message when trying to update wp-cli:

```
> php wp-cli.phar cli update --yes
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v2.7.0/wp-cli-2.7.0.phar...
md5 hash verified: f5645a4981e0dee32c7400c6f7504e47
Error: The downloaded PHAR is broken, try running wp cli update again.
```

Has anything changed on the wp-cli server?

**Comment by danielbachhuber** [comment]
Thanks for the report, @RoundAboutWEB !

It's odd that the `md5` has verifies...

I'm able to successfully update:

```
$ wget -q https://github.com/wp-cli/wp-cli/releases/download/v2.6.0/wp-cli-2.6.0.phar
$ php wp-cli-2.6.0.phar cli version
WP-CLI 2.6.0
$ php wp-cli-2.6.0.phar cli update
You have version 2.6.0. Would you like to update to 2.7.0? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v2.7.0/wp-cli-2.7.0.phar...
md5 hash verified: f5645a4981e0dee32c7400c6f7504e47
New version works. Proceeding to replace.
Success: Updated WP-CLI to 2.7.0.
$ php wp-cli-2.6.0.phar cli version
WP-CLI 2.7.0
```

Here's what the upgrader runs against the downloaded file:

https://github.com/wp-cli/wp-cli/blob/58e145f65a86f987ffa736b67a3fd9908e3fe3a2/php/commands/src/CLI_Command.php#L358-L366

Can you check your PHP error log to see if there's anything insightful there?

**Comment by RoundAboutWEB** [comment]
Hello @danielbachhuber ,

the php-errorlog says:
`PHP Fatal error:  Uncaught Error: Class "Phar" not found in /tmp/wp_63494e5fc88d60.88689916.phar:3`

and this will be the first 4 lines in the file:
```
#!/usr/bin/env php
<?php
Phar::mapPhar();
include 'phar://wp-cli.phar/php/boot-phar.php';
```

**Comment by danielbachhuber** [comment]
@RoundAboutWEB Oh, interesting! `Phar` support isn't loaded for that PHP executable, then. Do you know why that might be the case?

You might be able to use `wp shell` to see which PHP binary is being called:

```
$ wp shell
wp> WP_CLI\Utils\get_php_binary();
=> string(21) "/opt/homebrew/bin/php"
```

**Comment by RoundAboutWEB** [comment]
if I download the current version (2.7.0) with wget it works:
```
wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
php wp-cli.phar cli update
Success: WP-CLI is at the latest version.
```

But a "cli update" for old version (2.6.0) causes an error:
```
php wp-cli.phar cli update
You have version 2.6.0. Would you like to update to 2.7.0? [y/n] y
Downloading from https://github.com/wp-cli/wp-cli/releases/download/v2.7.0/wp-cli-2.7.0.phar...
...
Error: The downloaded PHAR is broken, try running wp cli update again.
```

Downloading the direct path from update will work also:
```
wget https://github.com/wp-cli/wp-cli/releases/download/v2.7.0/wp-cli-2.7.0.phar
php wp-cli-2.7.0.phar cli update
Success: WP-CLI is at the latest version.
```
**So what can be the problem with "cli update"?**

**Comment by RoundAboutWEB** [comment]
PHP 8.0.23 (cli) (built: Sep  1 2022 08:35:05) ( NTS )

**Comment by danielbachhuber** [comment]
@RoundAboutWEB Interesting! It shouldn't be that... here's what it is for me:

```
$ php wp-cli-2.6.0.phar shell --path=/Users/danielbachhuber/projects/vanilla
wp> WP_CLI\Utils\get_php_binary();
=> string(43) "/opt/homebrew/Cellar/php@8.0/8.0.24/bin/php"
```

Maybe you're experiencing the same issue that was fixed with https://github.com/wp-cli/wp-cli/pull/5672

Using `wp shell` with WP-CLI v2.6.0 again, can you share the value for `getenv( 'WP_CLI_PHP_USED' )` and `getenv( 'WP_CLI_PHP' )` ?

**Comment by danielbachhuber** [comment]
Feel free to stop by the `#cli` channel on [WordPress.org](https://make.wordpress.org/chat/) Slack if you'd like help debugging further.
