### ISSUE TITLE
wp cli info retrieving wrong info on Windows

### ISSUE THREAD

**Issue by symisz** [wp-cli/wp-cli#5702]
It used to retrieve the right info when on build: 2.8.0-alpha-bd378d0
Which should be:
>WP_CLI phar path:       C:\wp-cli

On the latest nightly build (2.8.0-alpha-f63c8e6) I get the wrong path displayed:

>OS:     Windows NT 10.0 build 22623 (Windows 11) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\xampp\php\php.exe
PHP version:    8.1.10
php.ini used:   C:\xampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       C:\Users\USERNAME
WP-CLI packages dir:
WP-CLI cache dir:       C:\Users\USERNAME/.wp-cli/cache
WP-CLI global config:   C:\Users\USERNAME/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version: 2.8.0-alpha-f63c8e6

**Comment by danielbachhuber** [comment]
Thanks for the report, @symisz 

It doesn't seem like the `WP_CLI phar path: ` lookup code has changed recently:

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/36432/204528595-2bf69803-16b0-4cfc-8601-633bdbf7fa0f.png">

https://github.com/wp-cli/wp-cli/blame/main/php/commands/src/CLI_Command.php#L171

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/36432/204528752-7d98b7d5-be2e-4259-b134-8c231329c126.png">

https://github.com/wp-cli/wp-cli-bundle/blame/0bab399aba59a5040eca6e9bfc6b818c85e9b13c/php/boot-phar.php#L4

Maybe something changed on your system? Did a second copy of WP-CLI get installed on your path?

Feel free to stop by the `#cli` channel on [WordPress.org](https://make.wordpress.org/chat/) Slack if you'd like help debugging further.

**Comment by symisz** [comment]
very late reply, sorry!
there is no second copy on the other path `WP_CLI phar path: C:\Users\USERNAME` everything is still in `C:\wp-cli`
i don't think i had drastic changes to my system that could explain this.

latest version: WP-CLI 2.8.1
still points to the wrong path.
