### ISSUE TITLE
Provide a more helpful error message when php-cgi is detected

### ISSUE THREAD

**Issue by gjedeer** [wp-cli/wp-cli#5703]
I tried running wp-cli in a cpanel environment and the experience was as following:

```
[user@hwd-wp ~]$ wget https://github.com/wp-cli/wp-cli/releases/download/v2.7.1/wp-cli-2.7.1.phar
(....)
2022-11-18 09:55:09 (60,9 MB/s) - ‘wp-cli-2.7.1.phar’ saved [6729511/6729511]

[user@hwd-wp ~]$ chmod +x wp-cli-2.7.1.phar 
[user@hwd-wp ~]$ php wp-cli-2.7.1.phar 
Status: 500 Internal Server Error
Content-type: text/html; charset=UTF-8
```

I've then found in error log that the cause for this is `Undefined constant "WP_CLI\Utils\STDOUT"`, which in turn is caused by cPanel providing php-cgi instead of php-cli:

```
[user@hwd-wp public_html]$ php -v
PHP 8.1.12 (cgi-fcgi) (built: Nov  9 2022 17:32:43)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies
```

Since cPanel is a pretty popular environment, maybe it would be good if wp-cli detected when it's not ran using wp-cli and returned a more user friendly message? Two solutions come to my mind:

1. explicit [php_sapi_name](https://www.php.net/manual/en/function.php-sapi-name.php) check and die() with a friendly error message if it's not a supported SAPI
2. a catch-all exception handler printing the error (which is not needed in php-cli, so maybe php_sapi_name() needs to be used?)

It was not obvious to me that I should look for output of shell script in an error log - which is of course because of cPanel not wp-cli.

**Comment by danielbachhuber** [comment]
Showing a more helpful error message sounds great! Feel free to submit a pull request if you'd like.

**Comment by gjedeer** [comment]
It looks like the check is already present: https://github.com/wp-cli/wp-cli/blob/main/php/boot-fs.php but the phar version uses another entry point. 

I can't find any documentation on how to build the source code into phar, if I knew that I could work my way to finding the other entry point and testing the phar on a cpanel box.

**Comment by gjedeer** [comment]
I think I've found the entry point, it's in another repo https://github.com/wp-cli/wp-cli-bundle/blob/main/php/boot-phar.php

And there's the phar build script: https://github.com/wp-cli/wp-cli-bundle/blob/main/utils/make-phar.php

**Comment by danielbachhuber** [comment]
Great sleuthing, @gjedeer !

It's interesting that we don't do the `PHP_SAPI` or `PHP_VERSION` checks in `boot-phar.php`. I don't recall the history of that off the top of my head.

Here's where the `PHP_SAPI` check moved to `wp-cli-boot.php`: https://github.com/wp-cli/wp-cli/commit/c3b14f9b8e76ba2858c5ae036e6ebe325686dee0

`wp-cli-boot.php` moved to `boot-fs.php` in https://github.com/wp-cli/wp-cli/commit/28456b765a23f13c79f75e0e6f350823c721469d

`boot-phar.php` was added in https://github.com/wp-cli/wp-cli-bundle/commit/f5a585fb1aaa61d89450909f46f27b1805fc07b0

Here's its pull request: https://github.com/wp-cli/wp-cli/pull/658

As far as I can tell, it was an oversight not to include the checks in `boot-phar.php` and we should be able to simply add them. It might cause some unexpected breakage, but at least it will be obvious when the breakage occurs.

**Comment by gjedeer** [comment]
Okay, I've added a PR.

If someone stumbles upon this in the future, here's how to manually build the phar for testing:

```
git clone https://github.com/wp-cli/wp-cli-bundle/
docker run -it --rm -v `pwd`/wp-cli-bundle:/wp-cli-bundle composer:latest bash
cd /wp-cli-bundle/
composer install
php -dphar.readonly=0 utils/make-phar.php wp-cli.phar --version=$CLI_VERSION
exit
```

This will create wp-cli.phar in wp-cli-bundle/ directory.

**Comment by gjedeer** [comment]
And here's output from a cPanel server which has `php` aliased to `php-cgi` for reasons known only to cPanel developers:

```
$ php /tmp/wp-cli.phar cache flush
Content-type: text/html; charset=UTF-8

Only PHP-CLI access.
You're currently using the cgi-fcgi PHP SAPI.
If you're trying to run this file with a web browser, don't.
When running in command line, ensure that `php -v` has the
word "cli" in the first line of output.
```
