### ISSUE TITLE
wp cli info fatal error with PHP 8.1.13

### ISSUE THREAD

**Issue by IIM-Andreas** [wp-cli/wp-cli#5710]
## Bug Report

- [x ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
fatal error

PHP version:    8.1.13
PHP Fatal error:  Uncaught Error: Call to undefined function WP_CLI\Utils\proc_open() in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1535
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Process.php(73): WP_CLI\Utils\proc_open_compat()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(1728): WP_CLI\Process->run()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php(166): WP_CLI\Utils\get_mysql_binary_path()
#3 [internal function]: CLI_Command->info()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
#5 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(419): WP_CLI\Dispatcher\Subcommand->invoke()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(442): WP_CLI\Runner->run_command()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1157): WP_CLI\Runner->run_command_and_exit()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#13 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#14 /usr/local/bin/wp(4): include('...')
#15 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1535

**Describe how other contributors can replicate this bug**
call command: "wp cli info"

**Describe what you expect as the correct outcome**
no fatal!

**Let us know what environment you are running this on**
OS:     Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64

**Comment by danielbachhuber** [comment]
Thanks for the report, @IIM-Andreas !

It looks like we need a `check_proc_available()` in `Process::run()`: https://github.com/wp-cli/wp-cli/pull/5711
