### ISSUE TITLE
@when definition isn't respected when using @alias in DocBlock

### ISSUE THREAD

**Issue by mrsdizzie** [wp-cli/wp-cli#5724]
When using the `@alias` feature inside of a DocBlock, it doesn't seem to respect the `@when` definition when being called as the alias. Here is a test case where the command runs `before_wp_load` when using the standard name, but not when using the alias"

```php
<?php

class Test_Command {
	/**
	 * test
	 *
	 * @alias bar
	 *
	 * @when before_wp_load
	 *
	 */
	public function foo( $args, $assoc_args ) {
		echo "Hello\n";
	}
}

WP_CLI::add_command( 'test', Test_Command::class );
```

When run in a directory that doesn't have a WordPress installation, the results are different:

```bash
$ wp test foo
Hello
$ wp test bar
Error: This does not seem to be a WordPress installation.
The used path is: /Users/mrsdizzie/
Pass --path=`path/to/wordpress` or run `wp core download`.
```

I checked and it does register the alias so that part is working:

```bash
$ wp help test foo
NAME

  wp test foo

DESCRIPTION

  test

SYNOPSIS

  wp test foo

ALIAS

  bar
```

```
$  wp cli info
OS:	Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64
Shell:	/usr/local/bin/bash
PHP binary:	/usr/local/opt/php@7.4/bin/php
PHP version:	7.4.32
php.ini used:	/usr/local/etc/php/7.4/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.10.2-MariaDB, for osx10.18 (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:	/Users/mrsdizzie/source/wp-cli
WP-CLI vendor dir:	/Users/mrsdizzie/source/wp-cli/vendor
WP_CLI phar path:
WP-CLI packages dir:	/Users/mrsdizzie/.wp-cli/packages/
WP-CLI cache dir:	/Users/mrsdizzie/.wp-cli/cache
WP-CLI global config:	/Users/mrsdizzie/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	2.8.0-alpha
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @mrsdizzie !

The `@when` definition should definitely be respected, so this seems like a bug. Feel free to submit a pull request if you'd like.

**Comment by mrsdizzie** [comment]
I'd like to come up with a fix but I'm not super familiar with the structure of everything. After a bit of searching I think this happens because early invoke is checked in the `__construct` method of the parent `CompositeCommand` class here:

https://github.com/wp-cli/wp-cli/blob/0285d4ab23efa729d6dcdaeeed1bfdab2ee007c9/php/WP_CLI/Dispatcher/CompositeCommand.php#L33-L46

But a `CompositeCommand` can't have an alias, only a `Subcommand` can. The alias for a `Subcommand` is set in the `__construct` method of the child class: 

https://github.com/wp-cli/wp-cli/blob/0285d4ab23efa729d6dcdaeeed1bfdab2ee007c9/php/WP_CLI/Dispatcher/Subcommand.php#L16-L33

so by that time the check for `@when` and call to `register_early_invoke` has already happened in the `CompositeCommand` parent class.

I don't know the best place to make a change. Should `register_early_invoke` be able to check if the command has an alias and add that too? Or should there be another call to `register_early_invoke` somewhere for the alias?

**Comment by danielbachhuber** [comment]
@mrsdizzie Makes sense. It's not super obvious to me, either. I'll need to spend some time with the code.

Want to submit a pull request with a failing test and we can work from there?

**Comment by mrsdizzie** [comment]
> @mrsdizzie Makes sense. It's not super obvious to me, either. I'll need to spend some time with the code.
> 
> Want to submit a pull request with a failing test and we can work from there?

Sure!
