### ISSUE TITLE
Performance issue with composer autoloader caused by empty namespace prefix

### ISSUE THREAD

**Issue by mweimerskirch** [wp-cli/wp-cli#5731]
This bug report is not directly related to wp-cli core, but if affects all commands. That's why I decided on reporting it here, and if my suggestion is welcome, I can prepare pull requests for all the commands.

We have identified a performance issue in one of our projects related to the wp-cli commands and the way the composer autoloader handles them. Specifically, all wp-cli commands contain the following lines in the composer.json file:

```
    "autoload": {
        "psr-4": {
            "": "src/"
        }
    },
```

The bug only affects performance if you install it into your project using Composer. When using the .phar version, this issue does not make any difference.

Defining an autoloader with an empty namespace prefix is detrimental to performance, as the autoloader will try to find classes within all the folders that were defined without a namespace.

This issue became apparent when activating the Yoast SEO plugin, as this has its own autoloader that gets registered after ours and it autoloads many files. As a result, our autoloader makes many roundtrips to the filesystem, causing a slowdown of 8 seconds per page load in our dev environment with Docker and mounted folders. In production (where everything is on the same filesystem) the slowdown is less noticeable, but still worth improving.

A short-term solution that should not cause any backwards compatibility issues is to replace the above fragment with the following:

```
    "autoload": {
        "classmap":  [ "src/" ]
    },
```

With the [classmap](https://getcomposer.org/doc/04-schema.md#classmap) key, a list of all found classes and corresponding files are added to the autoloader. Given that the commands each all have only one or two files, there should be no downside to this.

As I mentioned, I can prepare pull requests for all the commands if this change is accepted.

In the long-term, it would be a good idea to add namespaces to everything, but this is more likely to cause compatibility issues.

**Comment by mweimerskirch** [comment]
As a more visual example, this gets generated inside vendor/composer/autoload_static.php with the current configuration:

```
    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/..' . '/wp-cli/cache-command/src',
        1 => __DIR__ . '/..' . '/wp-cli/checksum-command/src',
        ...
        20 => __DIR__ . '/..' . '/wp-cli/super-admin-command/src',
        21 => __DIR__ . '/..' . '/wp-cli/widget-command/src',
    );
```

And with the suggested classmap configuration, vendor/composer/autoload_static.php would contain this:

```
    public static $classMap = array (
        ...
        'Cache_Command' => __DIR__ . '/..' . '/wp-cli/cache-command/src/Cache_Command.php',
        'Checksum_Command' => __DIR__ . '/..' . '/wp-cli/cache-command/src/Checksum_Command.php',
        ...
    )
```

The autoloading would work exactly the same way, but with improved performance.

**Comment by danielbachhuber** [comment]
@mweimerskirch Do you want to prepare PRs against the remaining repositories, or would you like me to take care of that?

Also, if you're willing to, could you also include https://github.com/wp-cli/.github/issues/41 (either as a separate PR or in the PR)?

**Comment by mweimerskirch** [comment]
Sorry for spamming you with PRs ;-)
I changed the autoloader almost everywhere now.

The following packages are already properly namespaced, so no changes required here:

- `i18n-command`
- `scaffold-package-command`
- `maintenance-mode-command`
- `profile-command`
- `embed-command`

The `doctor-command` includes its own autoloader, but that is also namespaced, so not part of the scope of this performance fix, but at some point it could be refactored to use the composer autoloader.

I'll look into `entity-command` and `shell-command` now.
Those two use a mix of namespaced and non-namespaced autoloaders.

**Comment by mweimerskirch** [comment]
The PRs for `entity-command` and `shell-command` are slightly different compared to the PRs on the other commands, because part of the code is namespaced while another part is not. I still propose to replace the psr-4 autoloader with a classmap for now, until everything is namespaced.

**Comment by mweimerskirch** [comment]
> Also, if you're willing to, could you also include [wp-cli/.github#41](https://github.com/wp-cli/.github/issues/41) (either as a separate PR or in the PR)?

I think it might be best to do the code beautifier change in another PR. Unfortunately, I don't think I'll be able to do this though (at least not anytime soon). It potentially changes a lot of code requiring testing and it could lead to a bit of follow up work which I might not be able to do over the next weeks and months because my personal priorities will change soon: 👶

**Comment by danielbachhuber** [comment]
🚢 🚢 🚢 

Thanks for your help with this, @mweimerskirch ! Have a great time with your new journey, too 😊
