### ISSUE TITLE
Fatal Error attempting to run commands when Woocommerce Plugin is activated

### ISSUE THREAD

**Issue by pierrerocket** [wp-cli/wp-cli#5732]
Hello.  Our hosting seems to be causing some kind of issue with WP CLI and Woocommerce and I'm hoping you can help me track down the cause so I can get it resolved.  The reason I think this has something to do with my hosting environment is because when running websites locally the problem doesn't occur.  But once deployed it crops up, and it occurs across several of our client websites across several vps servers all utilizing the same environment and using Woocommerce. 

The problem is I get the following error when attempting to do almost anything with WP CLI:
`Fatal error: Declaration of Automattic\WooCommerce\Vendor\League\Container\Container::get($id, bool $new = false) must be compatible with Automattic\WooCommerce\Vendor\Psr\Container\ContainerInterface::get(string $id) in /storagehome/SITE/public_html/wp-content/plugins/woocommerce/lib/packages/League/Container/Container.php on line 15`

If I disable the Woocommerce plugin the error goes away and I can run commands again.

I read in another thread this may have something to do with composer, but frankly the discussion was a little over my head.  But in case it is related the The hosting is apache, on a WHM/cpanel VPS running centOS.
PHP version is 7.4.33 (set via Cpanels MultiPHP Manager).
I read in another thread this may have something to do with composer, but frankly that was over my head.  But in case it is related the server is running Composer version 2.2.12.  

My local version of composer is 2.1.5

**Comment by wojsmol** [comment]
Hi @pierrerocket 
Please check that your PHP and PHP CLI versions are in fact set to 7.4 - see [this wordpress.org forum reply](https://wordpress.org/support/topic/fatal-error-after-upgrading-wocommerce-to-6-9-2/#post-16059654) for related issue solution.

Moreover, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For WP-CLI support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the Make [WordPress Slack Team](https://make.wordpress.org/chat/).
