### ISSUE TITLE
Call to undefined function add_filter() causing a critical error

### ISSUE THREAD

**Issue by C0UNT3RP01NT** [wp-cli/wp-cli#5734]
Alright I'm just going to give a little background here: I'm a coding dumbass. I'm not a complete idiot, but I don't have any education in this stuff. I'm a broke college student working for a small business. Originally I had nothing to do with the website, but the owners asked me to add some new products once, and it was pretty straightforward, and then I became the website guy. I didn't make the website. 

I went to login to the admin page, and got a critical error. The website works outside of that. You can go onto it, you can still use the email buttons to place orders (we're a wholesaler that does our orders through there). So I went over to cpanel to see what the error is, and I got this:

> Fatal error: Uncaught Error: Call to undefined function add_filter() in /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code:85 Stack trace: #0 /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231): eval() #1 /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1192): WP_CLI\Runner->load_wordpress() #2 /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start() #3 /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/bootstrap.php(77): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState)) #4 /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap() #5 /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/boot-fs.php(17): require_once('/ in /usr/local/cpanel/3rdparty/wp-toolkit/plib/vendor/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 85

Normally I'm pretty decent at finding stuff in the backend, but it's kind of a mess. It's a custom theme, with a lot of plugins, and I haven't really changed much because I don't want to break the site since I don't really know what I'm doing. However, even when searching for files and folders through cpanel, I can't find a /usr/ or a /3rdparty/ or even a /wp-toolkit/ (I've found something that has wp-toolkit as part of the name). There's a few different Runners, but the only one that reads just Runner, doesn't have add_filter() as part of the code. I just can't find what this error is referencing. That's kind of where my ability is at. If I can find it, and there's a close enough solution, I can probably reverse engineer it.

I've been researching this for a few hours, I've read several GitHub threads and WP forum threads and it's not helping because I can't find it. I'm not even sure if I have found it, and understand what the error is. There's a labyrinth of files, folders, and code that I did not write or make. My company stopped using the people who made the website because they weren't really happy with the service (charged a lot and we're slow to respond and fix issues). 

Look I'm totally all for learning this stuff, I just need some help doing so. The only reason I'm coming here is because I've hit a deadend trying to figure out how to fix it. 

As it stands the front end works, but I can't login to the admin page.

**Comment by danielbachhuber** [comment]
Hey @C0UNT3RP01NT,

Sorry for the trouble you're running into!

Per [our documentation](https://wp-cli.org/#support), GitHub issues aren't meant for general support. If you'd like to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/), I'm sure someone would be happy to chat with you about your problem.

You might also consider [Codeable](https://www.codeable.io/) to find a freelancer to help you fix your problem.
