### ISSUE TITLE
Block theme pattern is still loaded even when --skip-themes is used

### ISSUE THREAD

**Issue by vikasprogrammer** [wp-cli/wp-cli#5736]
I am getting this error while executing this command. 

`wp option update admin_email bibepamupu23810 --skip-plugins --skip-themes --skip-content`

(happens with other commands as well). 

As you can see, I have skipped loading themes and even content to be loaded, still the command is trying to load the theme in runtime.

Interestingly, it works when I remove the flag `--skip-themes` . 

```
PHP Fatal error:  Uncaught Error: Undefined constant "BLOCKLINE_URL" in /home/bibepamupu2381/web/ing-planet-jize.wordpress.website-tutor.de/public_html/wp-content/themes/blockline/patterns/hero-1.php:46
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @vikasprogrammer

> As you can see, I have skipped loading themes and even content to be loaded, still the command is trying to load the theme in runtime.

It's hard to say what the issue might be without the ability to reproduce.

Does the problem exist on a fresh WordPress install? Can you do some debugging to track down the source of the problem?

**Comment by vikasprogrammer** [comment]
A WordPress installation with blockline theme will reproduce this issue.

**Comment by danielbachhuber** [comment]
Thanks @vikasprogrammer, I was able to reproduce:

```
$ wp core download --path=wpdebug
Creating directory '/Users/danielbachhuber/projects/wpdebug/'.
Downloading WordPress 6.1.1 (en_US)...
Using cached file '/Users/danielbachhuber/.wp-cli/cache/core/wordpress-6.1.1-en_US.tar.gz'...
Success: WordPress downloaded.
$ cd wpdebug
$ wp core config --dbname=wpdebug --dbuser=root
Success: Generated 'wp-config.php' file.
$ wp db create
Success: Database created.
$ wp theme install --activate blockline
Error: The site you have requested is not installed.
Run `wp core install` to create database tables.
$ wp core install --url=wpdebug.test --title=wpdebug
Success: WordPress installed successfully.
$ wp theme install --activate blockline
Installing Blockline (1.0.2)
Downloading installation package from https://downloads.wordpress.org/theme/blockline.1.0.2.zip...
Unpacking the package...
Installing the theme...
Theme installed successfully.
Activating 'blockline'...
Success: Switched to 'Blockline' theme.
Success: Installed 1 of 1 themes.
$ wp eval 'var_dump( function_exists( "blockline_support" ) );'
bool(true)
$ wp eval 'var_dump( function_exists( "blockline_support" ) );' --skip-themes
Fatal error: Uncaught Error: Undefined constant "BLOCKLINE_URL" in /Users/danielbachhuber/projects/wpdebug/wp-content/themes/blockline/patterns/hero-1.php:4
```

It seems like core is loading the pattern even though the theme isn't loaded. We'll need to fix this behavior in core, most likely.
