### ISSUE TITLE
When a new user is added, they are not sent a registration notification.

### ISSUE THREAD

**Issue by monsterbnd** [wp-cli/wp-cli#5746]
When a new user is added, they are not sent a registration notification.
<code>wp user create alice alice.vostrikova@gmail.com --role=consultant --send-email</code>
However, the notification is normally sent when the password is reset.
<code>wp user reset-password alice</code>
I don't know how important this is, but I use the WP Mail SPTM plugin: 'Other SMTP' setting.
```
$ wp cli info
OS:     Linux 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.33
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 14.14 Distrib 5.7.41, for Linux (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/ss-pt.com/public_html
WP-CLI packages dir:
WP-CLI cache dir:       /home/web-ss-pt.com/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.7.1

```

**Comment by danielbachhuber** [comment]
Hey @monsterbnd 

This worked as expected for me with WP-CLI v2.7.1:

```
wp user create danieltest daniel+test@redacted.com --send-email
```

Maybe some other plugin is disabling email notifications?

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.

**Comment by monsterbnd** [comment]
Yes, plugin reCaptcha by BestWebSoft blocked registration message.
