### ISSUE TITLE
There was an error overwriting existing files.

### ISSUE THREAD

**Issue by IonutAlexandruPanait** [wp-cli/wp-cli#5752]
While I am trying to reinstall WordPress core files, I got this error:

Warning: Unable to copy 'index.php' to current directory. Warning: Unable to copy 'wp-blog-header.php' to current directory. Error: Couldn't extract WordPress archive. There was an error overwriting existing files. Downloading WordPress 6.1.1 (en_US)... md5 hash verified: 381a9855e7e35b01bdc6b3e65a901c69

I wasn't able to find resources on the internet regarding a solution on this.

**Comment by danielbachhuber** [comment]
Hey @IonutAlexandruPanait,

This issue seems specific to your environment. GitHub issues are for bug reports with reproduction steps. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
