### ISSUE TITLE
WP CLI showing errors on CLI

### ISSUE THREAD

**Issue by JamesVanWaza** [wp-cli/wp-cli#5755]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
See screenshot attached 
<img width="1918" alt="Screenshot 2023-03-27 at 8 45 52 PM" src="https://user-images.githubusercontent.com/4000076/228098014-784d4995-6b65-4367-8d59-9980522cda32.png">

A clear and concise description of the behavior that produces an incorrect result or error.

Remember: more information is better. Please provide context on how you're running the command to make sure we're all on the same page when reasoning about this.

**Describe how other contributors can replicate this bug**

- a list of
- steps to replicate
- the error condition

```js
// You can also use code snippets if needed.
```

**Describe what you expect as the correct outcome**
I am unable to run wp cli `commands`

A clear and concise description of what you expected to happen (or code).

**Let us know what environment you are running this on**

```
(Paste the output of "wp cli info" into this box)
OS:     Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020 arm64
Shell:  /bin/zsh
PHP binary:     /opt/homebrew/Cellar/php/8.2.4/bin/php
PHP version:    8.2.4
php.ini used:   /opt/homebrew/etc/php/8.2/php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/dosbrandingcreative
WP-CLI packages dir:
WP-CLI cache dir:       /Users/dosbrandingcreative/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.7.1

```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/screenshots**

If applicable, add screenshots to help explain (you can just drag&drop images into the Github issue).

**Comment by danielbachhuber** [comment]
Thanks for the report, @JamesVanWaza !

This was fixed in https://github.com/wp-cli/wp-cli/pull/5707

You're welcome to run `wp cli update --nightly` to install the latest nightly build and resolve the error.

**Comment by JamesVanWaza** [comment]
@danielbachhuber , thank you so much
I had to run the following command first
`brew uninstall wp-cli` and then reinstalled it using `brew install wp-cli` and it updated to `2.8.0`
