### ISSUE TITLE
Fix failing automated-tests in preparation for 2.8.0 release

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5764]
We have a variety of tests failing across the project right now. We should fix those up in preparation for the release.

**Done is:**
* All of the test suites are passing (but we can ignore https://github.com/wp-cli/wp-cli-tests/issues/160 for now).

**Comment by wojsmol** [comment]
We only have issues in `wp-cli/wp-cli`, `wp-cli/language-commend` and `wp-cli/core-commend` according to https://github.com/wp-cli/automated-tests/actions/runs/4624049339 but php 8.2 are still have `continiu-on-error`.

**Comment by danielbachhuber** [comment]
> php 8.2 are still have `continue-on-error`.

@wojsmol Oh, now I remember what you're referring to. Want to submit a PR to disable that, and we can see what pops up?

**Comment by wojsmol** [comment]
@danielbachhuber I already submited PR to `wp-cli/.github` reposirory.

**Comment by danielbachhuber** [comment]
@schlessera @swissspidy Looks like they're passing much more reliably now:

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/36432/234005981-0af1f2a4-6f27-4ca4-a045-f086b288ae55.png">
