### ISSUE TITLE
¿How to use WP_CLI object?

### ISSUE THREAD

**Issue by AnxoBastos** [wp-cli/wp-cli#5767]
Hi, i have WP_CLI installed on a Siteground server and it only allows me to access it through console commands. How could I access the object WP_CLI to use it in my php files? In this case i would want to use it in a plugin.

**Comment by dixitalmedia** [comment]
Hi,
We also have sites hosted by Siteground and from our plugins we can use WP CLI calling `exec()` or `shel_exec()` but if we want to access WP_CLI class we get this error message: **PHP Fatal error: Uncaught Error: Class "WP_CLI" not found** 
We can even use WP CLI if we connect by ssh to the server.

Should we do any `require()` or something else in order to get access to WP_CLI class ?

Many thanks

**Comment by danielbachhuber** [comment]
Hey folks,

Unfortunately, I'm not familiar with SiteGround's implementation and am unable to support it. Feel free to reach out to SiteGround support with your question.

**Comment by dixitalmedia** [comment]
Hi @danielbachhuber 

Just a question:

_Is it supposed that Class "WP_CLI" should exist when WP CLI is running on the server or it is a third party library that is not included in WP CLI core, so in this case we should install it ?_

SiteGround support suggested me to install Class "WP_CLI", but if it is included in WP CLI it makes no sense to install it twice.

As I've said, WP CLI runs properly on a ssh window and also if it is called from PHP with exec() or shel_exec() 

Thanks a lot!

**Comment by danielbachhuber** [comment]
@dixitalmedia The `WP_CLI` class should exist when you're running a custom WP-CLI command. It won't exist in the web request context, however. If you'd like your plugin to call WP-CLI commands from API requests or similar, you'll need to use `exec()` to call the `wp` executable.

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.

**Comment by dixitalmedia** [comment]
@danielbachhuber we have already used `exec()` sucessfully to call _wp_ commands but I probably misunderstood and I thought that the right way to do it was calling Class "WP_CLI" as we do with WC_Cart, WC_Checkout or WC_Order.

So now it's clear :-)

Many thanks

**Comment by danielbachhuber** [comment]
@dixitalmedia Great! Glad we figured this out 😊
