### ISSUE TITLE
Call wp_cache_flush_runtime in wp_clear_object_cache 

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/wp-cli#5769]
## Feature Request

Call the function  `wp_cache_flush_runtime` in `wp_clear_object_cache `. This function has been in core since 6.0.0 ( https://github.com/WordPress/wordpress-develop/commit/c98f4c04db13a1c3db14345db4cff116dd01bf51) and is designed to perform the what currently `wp_clear_object_cache` does. 

**Describe the solution you'd like**

It might be worth calling `wp_cache_supports('flush_runtime')` before calling `wp_cache_flush_runtime`.

**Comment by danielbachhuber** [comment]
Seems fine 👍

Feel free to submit a PR if you'd like.

**Comment by spacedmonkey** [comment]
> Feel free to submit a PR if you'd like.

PR is created #5778
