### ISSUE TITLE
Requests default certificate fails to load from Phar

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5779]
## Bug Report

**Describe the current, buggy behavior**

The current integration with the Requests library surfaces an issue when the default certificate location provided by the Requests library has not been overridden and the library is found within the WP-CLI Phar file.

In that scenario, the location to the certificate file still points into the Phar file, and cURL cannot properly handle that file location, as it is unable to read archived files within Phar archives.

**Describe how other contributors can replicate this bug**

The behavior can be replicated by building a Phar archive an running tests using that Phar archive via `WP_CLI_BIN_DIR`:
1. Clone the `wp-cli/wp-cli-bundle` repository and `cd` into its folder.
2. Run `composer install`
3. Run `php -dphar.readonly=0 utils/make-phar.php wp-cli.phar --version=custom`
4. Run `mv wp-cli.phar wp && chmod +x wp`
5. Run `WP_CLI_BIN_DIR=/home/alain/wp-cli-bundle composer behat`

**Describe what you expect as the correct outcome**

The tests should succeed.

But instead, they produce an error:
```
PHP Fatal error:  Uncaught WpOrg\Requests\Exception: cURL error 77: error setting certificate verify locations:
          CAfile: phar://wp/vendor/rmccue/requests/src/../certificates/cacert.pem
          CApath: /etc/ssl/certs in phar://wp/vendor/rmccue/requests/src/Transport/Curl.php:490
```

**Provide additional context/screenshots**

![Merge pull request #534 from wp-cli_update-composer-lock-file-2023-05-03 ·   2023-05-04 at 11 30 58 AM](https://user-images.githubusercontent.com/83631/236170859-4083b277-5626-45b0-8aab-db18ffc99132.jpeg)

**Comment by schlessera** [comment]
I already tried to extract the certificate upfront: https://github.com/wp-cli/wp-cli/pull/5777

This does not yet work, and I currently ignore why.

**Comment by danielbachhuber** [comment]
I tried running the `features/requests.feature` test directly:

```
$ WP_CLI_BIN_DIR=/home/danielbachhuber/projects/wp-cli-bundle composer behat features/requests.feature
```

All scenarios pass as expected:

```
3 scenarios (3 passed)
45 steps (45 passed)
0m31.25s (9.37Mb)
```

I don't see this particular failure in [our automated tests](https://github.com/wp-cli/automated-tests/actions/runs/4877737348) (although it looks like there are a variety of new failures now).

**Comment by danielbachhuber** [comment]
@schlessera I don't think this test makes sense:

https://github.com/wp-cli/wp-cli-bundle/blob/862826a05e501037d1ad707b53a32167b307c254/features/requests.feature#L67-L76

In `\WP_CLI\Utils\http_request()`, we have a fallback mechanism to extract the certificate when the initial request fails:

https://github.com/wp-cli/wp-cli/blob/1bb6da1efc370edc06f9787571c3dd5fa3f52c9a/php/utils.php#L768-L773

We don't have such a mechanism (and never have) when `\WpOrg\Requests\Requests::get()` is called directly.

**Comment by pwtyler** [comment]
This exact issue surfaced recently for us at Pantheon with someone trying to use `wp eval '$url = "https://example.com"; Requests::get($url);'` and I held off investigating too deeply at first thinking a fix would come about among upgrading `Requests` in Core/WP-CLI— but sounds like there's also a workaround with `\WP_CLI\Utils\http_request()` for now.

**Comment by pwtyler** [comment]
@schlessera, can we re-open this (or I can open another)? I know this was implemented one way and then backed out and re-addressed, but I just tried again with 2.8.0 and still getting a fatal error trying to use `Requests::get()`

```
% wp eval '$url = "https://google.com"; Requests::get($url);'
PHP Fatal error:  Uncaught WpOrg\Requests\Exception: cURL error 77: error setting certificate verify locations:  CAfile: phar:///usr/local/bin/wp/vendor/rmccue/requests/src/../certificates/cacert.pem CApath: none in phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Transport/Curl.php:490
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Transport/Curl.php(219): WpOrg\Requests\Transport\Curl->process_response('', Array)
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Requests.php(469): WpOrg\Requests\Transport\Curl->request('https://google....', Array, '', Array)
#2 phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Requests.php(305): WpOrg\Requests\Requests::request('https://google....', Array, NULL, 'GET', Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/Eval_Command.php(39) : eval()'d code(1): WpOrg\Requests\Requests::get('https://google....')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/Eval_Command.php(39): eval()
#5 [internal function]: Eval_Command->__invoke(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(431): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(454): WP_CLI\Runner->run_command(Array, Array)
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(131): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1202): WP_CLI\Runner->do_early_invoke('before_wp_load')
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#17 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#18 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Transport/Curl.php on line 490
Fatal error: Uncaught WpOrg\Requests\Exception: cURL error 77: error setting certificate verify locations:  CAfile: phar:///usr/local/bin/wp/vendor/rmccue/requests/src/../certificates/cacert.pem CApath: none in phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Transport/Curl.php:490
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Transport/Curl.php(219): WpOrg\Requests\Transport\Curl->process_response('', Array)
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Requests.php(469): WpOrg\Requests\Transport\Curl->request('https://google....', Array, '', Array)
#2 phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Requests.php(305): WpOrg\Requests\Requests::request('https://google....', Array, NULL, 'GET', Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/Eval_Command.php(39) : eval()'d code(1): WpOrg\Requests\Requests::get('https://google....')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/eval-command/src/Eval_Command.php(39): eval()
#5 [internal function]: Eval_Command->__invoke(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(431): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(454): WP_CLI\Runner->run_command(Array, Array)
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(131): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1202): WP_CLI\Runner->do_early_invoke('before_wp_load')
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#17 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#18 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/src/Transport/Curl.php on line 490
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```

**Comment by danielbachhuber** [comment]
@pwtyler I can reproduce:

```
$ curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
$ php wp-cli.phar eval '$url = "https://google.com"; Requests::get($url);' --skip-wordpress

Deprecated: The PSR-0 `Requests_...` class names in the Requests library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience. in phar:///Users/danielbachhuber/Desktop/wp-cli.phar/vendor/rmccue/requests/library/Requests.php on line 24

Fatal error: Uncaught WpOrg\Requests\Exception: cURL error 77: error setting certificate verify locations:  CAfile: phar:///Users/danielbachhuber/Desktop/wp-cli.phar/vendor/rmccue/requests/src/../certificates/cacert.pem CApath: none in phar:///Users/danielbachhuber/Desktop/wp-cli.phar/vendor/rmccue/requests/src/Transport/Curl.php:490
Stack trace:
```

I removed the `bug` label, though. This isn't really a regression if it never worked in the first place 😁

It seems like the certificate path setting isn't working, or is getting reset:

```
$ php wp-cli.phar eval "echo Requests::get_certificate_path();" --skip-wordpress
phar:///Users/danielbachhuber/Desktop/wp-cli.phar/vendor/rmccue/requests/src/../certificates/cacert.pem
```

**Comment by pwtyler** [comment]
> This isn't really a regression if it never worked in the first place

makes sense. I thought I saw this fixed on one of the builds that was later reverted, so I figured it might still be on the radar for the future/continued work around `Requests`. I'm good with the `http_request` workaround til then.

**Comment by schlessera** [comment]
@pwtyler The correct way to do this would be something like this:

```bash
php wp-cli.phar eval '$url = "https://google.com"; \WP_CLI\Utils\http_request( "GET", $url );' --skip-wordpress
```

This way, you're making use of the Requests wrapper in WP-CLI that translates between different versions of Requests.

**Comment by schlessera** [comment]
Note that the "fix" t omake this work automatically created more issues than it solved, as it required WP-CLI to initialize Requests unconditionally before WordPress, so it couldn't take WordPress' version of Requests into account. The work that you saw me doing to try to automatically extract the certificate had to be reverted for that reason.

If you want to nevertheless use Requests directly in `wp eval`, you can also do something like this:
```bash
wp eval '$url = "https://google.com"; \Requests::set_certificate_path( \WP_CLI\Utils\get_default_cacert() ); \Requests::get($url);' --skip-wordpress
```

**Comment by schlessera** [comment]
I'm closing this again for now, as there is a viable work-around, and I don't think there is an easy fix to make this work automatically.

**Comment by pwtyler** [comment]
Thanks @schlessera, yes, we are recommending that anyone that has been asking for this to use `http_request( "GET", $url )` instead, but thanks for the alternative with `set_certificate_path` as well 👍🏻
