### ISSUE TITLE
Requests v2 conflicts with Requests v1 on older WP sites

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli#5782]
Running the latest WP-CLI nightly that includes Requests v2 on an older WP site with Requests v1 creates a conflict, as expected:

![_ 2023-05-05 at 10 30 46 AM tes_testsite2](https://user-images.githubusercontent.com/83631/236411926-7a5d1835-e452-4c26-9c13-d895329c267c.jpeg)

The plan is now to check early if a WP installation is found, and if yes, trigger the Requests autoloader of that WordPress installation, instead of the one that we bundle.

All of the code in WP-CLI directly touching the Requests library will need to be conditionally branched based on which version we're using.

**Comment by danielbachhuber** [comment]
@schlessera Was this resolved with https://github.com/wp-cli/wp-cli/pull/5783 ?

**Comment by schlessera** [comment]
Yes, it was. Closing.
