### ISSUE TITLE
[2.8.0] GPG key is missing

### ISSUE THREAD

**Issue by tuxmaster5000** [wp-cli/wp-cli#5793]
It looks like the gpg  key was changed:
LANG=C gpg --verify SOURCES/wp-cli-2.8.0.phar.asc SOURCES/wp-cli-2.8.0.phar
gpg: Signature made Wed May 31 19:15:43 2023 CEST
gpg:                using RSA key 012B5FF55FFADC1A52C04C03C2188A5B63449075
gpg: requesting key 0xC2188A5B63449075 from hkps://keys.openpgp.org
And the last gpg key:
ANG=C gpg SOURCES/Keys 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048/0xA3A2E8F226F0BC06 2018-05-31 [SC]
      63AF7AA15067C05616FDDD88A3A2E8F226F0BC06
uid                             WP-CLI Releases <releases@wp-cli.org>
sub   rsa2048/0xF6B7309F0E6A9622 2018-05-31 [E]

**Comment by wdoekes** [comment]
Indeed. The GPG key from https://make.wordpress.org/cli/2018/05/31/gpg-signature-change/ is not used:
```
pub   rsa2048 2018-05-31 [SC]
      63AF7AA15067C05616FDDD88A3A2E8F226F0BC06
uid           [ unknown] WP-CLI Releases <releases@wp-cli.org>
sub   rsa2048 2018-05-31 [E]
```
https://keyserver.ubuntu.com/pks/lookup?search=63AF7AA15067C05616FDDD88A3A2E8F226F0BC06&fingerprint=on&op=index

Instead, there is this:
```
$ gpg --batch --verify wp-cli-test.phar.asc wp-cli-test.phar
gpg: Signature made wo 31 mei 2023 19:15:43 CEST
gpg:                using RSA key 012B5FF55FFADC1A52C04C03C2188A5B63449075
gpg: Can't check signature: No public key
```
```
$ curl -sSfL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar.asc | gpg --list-packets 
# off=0 ctb=89 tag=2 hlen=3 plen=563
:signature packet: algo 1, keyid C2188A5B63449075
	version 4, created 1685553343, md5len 0, sigclass 0x00
	digest algo 10, begin of digest 4b eb
	hashed subpkt 33 len 21 (issuer fpr v4 012B5FF55FFADC1A52C04C03C2188A5B63449075)
	hashed subpkt 2 len 4 (sig created 2023-05-31)
	subpkt 16 len 8 (issuer key ID C2188A5B63449075)
	data: [4096 bits]
```
No idea where that key is from.

**Comment by schlessera** [comment]
@tuxmaster5000 , @wdoekes thanks for the report. The release was signed with the wrong key as I was using a different machine and I fell (again) into the trap of assuming that `gpg` would tell me when I'm trying to use a key that doesn't exist. Well, it doesn't.

I've resigned the release now, so the key should be the one that is expected. I'm closing this issue now, but please feel free to reopen or ping me if you still see an issue.
