### ISSUE TITLE
Notices/Warnings should only print to Stderr, but are sent to both Stderr and Stdout

### ISSUE THREAD

**Issue by pwtyler** [wp-cli/wp-cli#5809]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

PHP Notices and warnings are sent to both stderr and stdout, so they cannot be redirected or discarded when needed in scripts
```
$ wp config get table_prefix
PHP Notice:  Foo. in phar:///usr/local/bin/wp/vendor/wp-cli/config-command/src/Config_Command.php(444) : eval()'d code on line 75

Notice: Foo. in phar:///usr/local/bin/wp/vendor/wp-cli/config-command/src/Config_Command.php(444) : eval()'d code on line 75
PHP Warning:  Bar. in phar:///usr/local/bin/wp/vendor/wp-cli/config-command/src/Config_Command.php(444) : eval()'d code on line 76

Warning: Bar. in phar:///usr/local/bin/wp/vendor/wp-cli/config-command/src/Config_Command.php(444) : eval()'d code on line 76
wp_
```

**Describe how other contributors can replicate this bug**
I have a script to showcase/reproduce issues captured in [this gist](https://gist.github.com/pwtyler/0d037fd7a69e4cfe8e86df6dd5d7efe7), which makes use of `wp config` to avoid requiring a database, but the behavior can be reproduced with most other commands like `wp site list` as well.

**Describe what you expect as the correct outcome**

Errors/Warnings/Notices are only sent to stderr so that they can be captured, redirected, or discarded with shell redirections. Errors printing to stdout means capturing the output of a command is hard where you may not control all the code (i.e. running plugins with deprecated php syntax in PHP 8.2) and/or do not want to re-configure WP_DEBUG and its related constants.

**Let us know what environment you are running this on**

```
OS:	Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000 arm64
Shell:	/bin/zsh
PHP binary:	/opt/homebrew/Cellar/php/8.2.3/bin/php
PHP version:	8.2.3
php.ini used:	/opt/homebrew/etc/php/8.2/php.ini
MySQL binary:	/opt/homebrew/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.11.2-MariaDB, for osx10.17 (arm64) using  EditLine wrapper
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/philtyler/pantheon/projects/wpcli-repro
WP-CLI packages dir:
WP-CLI cache dir:	/Users/philtyler/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.8.1
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @pwtyler 

I'm not quite sure what the problem is. It's been a while since I dug deep into this part of things.

I see slightly different behavior than what you're describing.

Here's how I'm set up:

```
$ head -n 4 wp-config.php
<?php

trigger_error('Take Note.', E_USER_NOTICE);
trigger_error('You have been warned.', E_USER_WARNING)
```

No redirection shows the notice and the warning:

```
$ wp config get table_prefix

Notice: Take Note. in /Users/danielbachhuber/projects/wp-cli-dev/config-command/src/Config_Command.php(446) : eval()'d code on line 1

Warning: You have been warned. in /Users/danielbachhuber/projects/wp-cli-dev/config-command/src/Config_Command.php(446) : eval()'d code on line 2
wp_
```

Redirecting STDERR shows the notice and the warning:

```
$ wp config get table_prefix 2> /dev/null

Notice: Take Note. in /Users/danielbachhuber/projects/wp-cli-dev/config-command/src/Config_Command.php(446) : eval()'d code on line 1

Warning: You have been warned. in /Users/danielbachhuber/projects/wp-cli-dev/config-command/src/Config_Command.php(446) : eval()'d code on line 2
wp_
```

Redirecting STDOUT produces no output:

```
$ wp config get table_prefix > ./prefix.txt
```

https://github.com/wp-cli/wp-cli/issues/4944 could be related. I'm not sure that https://github.com/wp-cli/wp-cli/issues/3220 is implicated because `wp-config.php` isn't evaluated in this case.

Can you share the contents of your `php.ini` in a Gist?

**Comment by pwtyler** [comment]
Yep, this looks like this is related if not a dupe of #4944.

Here's [my php.ini](https://gist.github.com/pwtyler/30de552227bc1b8cdce615dd3530db08) I am almost positive it's all the defaults from homebrew here.
Shortcutting to what I expect we care most about, I have 
```
error_reporting = E_ALL
log_errors = On
display_errors = On
```

so in some capacity this may be _working as intended_ (insofar that errors go to stdout, not that errors are logged twice). I re-ran my test script from above after setting `display_errors = stderr`, and now I am able to redirect errors (🎊 ) but still seeing notices and warnings twice (but all to stderr).

re: your symptoms above, do _you_ have something discarding/obfuscating stderr? Seems we're only seeing the STDOUT side of what I got on your side.
