### ISSUE TITLE
Get tests passing again in all repositories

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5810]
We have a lot of automated test failures right now. Let's get them passing again!

**Done is:**
* Automated tests are passing in all repositories.

**Comment by swissspidy** [comment]
Now that https://github.com/wp-cli/.github/pull/61 has been merged, let's re-run some tests to see if they still fail now.

Some are now already passing again, so that's great 🎉 

Note: Some packages (e.g. widget-command, package-command, maintenance-mode-command, language-command, embed-command) haven't run tests in a while, so we need to push some changes to trigger a run

➡️  [#58673](https://core.trac.wordpress.org/ticket/58673) is a common issue across many packages. It will be resolved hopefully before RC. No action needed from our side!


**[wp-cli/scaffold-command](https://github.com/wp-cli/scaffold-command)**

Still some failures:

* `Scenario: Install WordPress from trunk` (in general)
	* Caused by [#58673](https://core.trac.wordpress.org/ticket/58673)
* `Scenario: Install WordPress from trunk` (on PHP 5.6 + WP latest)
	* Needs a `@require-php-7.0` tag

**[wp-cli/profile-command](https://github.com/wp-cli/profile-command)**

* `Scenario: Error when SAVEQUERIES is defined to false`
	* Caused by [#58673](https://core.trac.wordpress.org/ticket/58673)

**[wp-cli/db-command](https://github.com/wp-cli/db-command)**

* `Scenario: Clean up a WordPress install without dropping its database entirely but tables with prefix`
	* Caused by [#58673](https://core.trac.wordpress.org/ticket/58673)

**Comment by swissspidy** [comment]
> > Note: Some packages (e.g. widget-command, package-command, maintenance-mode-command, language-command, embed-command) haven't run tests in a while, so we need to push some changes to trigger a run
> 
> For this re-enabiling a testing workflow will be enough.

We tested it earlier and I was not able to re-run tests after re-enabling the workflows because the runs were too old (more than 90 days). See for example https://github.com/wp-cli/maintenance-mode-command/actions/workflows/testing.yml

**Comment by swissspidy** [comment]
@wojsmol That's not what I meant, I was referring to this button which is missing in those cases:

<img width="380" alt="Screenshot 2023-07-12 at 19 39 13" src="https://github.com/wp-cli/wp-cli/assets/841956/fac1d5cd-01b2-4636-905d-b6291ab3243c">

But yeah I'll just wait for the next test to be triggered.

**Comment by swissspidy** [comment]
[**`wp-cli/core-command`**](https://github.com/wp-cli/core-command) ([run](https://github.com/wp-cli/core-command/actions/runs/5526716848/jobs/10097270248))

* `001 Example: | trunk   | When I run wp core update --version=trunk`
* `Example: | nightly |   When I run wp core update --version=nightly`
* `003 Scenario: Installing latest nightly build should skip cache`

These should all get `@require-php-7.0`

[**`wp-cli/automated-tests`**](https://github.com/wp-cli/automated-tests)

* https://github.com/wp-cli/automated-tests/pull/36

----

I think that's it. We can go through all of them again once that bug in core is fixed.

**Comment by swissspidy** [comment]
[**`wp-cli/search-replace-command`**](https://github.com/wp-cli/search-replace-command) ([run](https://github.com/wp-cli/search-replace-command/actions/runs/5526716088/jobs/10097235537))

* `001 Scenario: Run on all tables matching string with wildcard`
	* This one seems to cause an exception on trunk. Needs further investigating.

**Comment by danielbachhuber** [comment]
Tagged some releases and submitted an update to the bundle https://github.com/wp-cli/wp-cli-bundle/pull/559

**Comment by swissspidy** [comment]
So far it's looking really good!

`search-replace-command` still needs looking into: https://github.com/wp-cli/search-replace-command/actions/runs/5538237598/jobs/10118012114

In the `automated-tests` repo `embed-command` is now failing when trying to do `wp embed provider match https://asciinema.org/a/140798`. Tests passed in the `embed-command` repo itself though yesterday. But I don't know why.

asciinema.org is not an allowlisted oEmbed provider in WordPress and does not oEmbed meta tags to its web pages. Maybe they just removed that recently? In that case we would need to update tests to use different URLs.

`media-command`: the tests were disabled, I just re-enabled the workflow.

This test appears to be failing as it tries to upgrade to trunk on PHP 5.6:

https://github.com/wp-cli/media-command/blob/0334b288f123861714029c843d1ea9410ebb7f27/features/media-regenerate.feature#L1214-L1226

Any ideas?

**Comment by danielbachhuber** [comment]
> `search-replace-command` still needs looking into: https://github.com/wp-cli/search-replace-command/actions/runs/5538237598/jobs/10118012114

Seems to be some collision with a new core option in trunk. I tweaked the test with https://github.com/wp-cli/search-replace-command/pull/185



> In the `automated-tests` repo `embed-command` is now failing when trying to do `wp embed provider match https://asciinema.org/a/140798`. Tests passed in the `embed-command` repo itself though yesterday. But I don't know why.

Yeah, let's swap with a different provider.

> This test appears to be failing as it tries to upgrade to trunk on PHP 5.6:
> 
> https://github.com/wp-cli/media-command/blob/0334b288f123861714029c843d1ea9410ebb7f27/features/media-regenerate.feature#L1214-L1226

We can skip the test because it's only applicable to PHP 5.6: https://github.com/wp-cli/media-command/pull/179

**Comment by swissspidy** [comment]
Fix for the embed command:

* https://github.com/wp-cli/embed-command/pull/71/

**Comment by danielbachhuber** [comment]
Thanks for your work on this, @swissspidy ! 🙌
