### ISSUE TITLE
Fatal error thrown on WP-CLI 2.8+ through SSH when using wp_remote_post from a plugin during a command.

### ISSUE THREAD

**Issue by jmtorres** [wp-cli/wp-cli#5816]
## Bug Report

--- ✅ If you are in the correct location now... --->

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When a plugin uses wp_remote_post during a wp-cli command, a fatal error is thrown related to the Request Response class. This appears to be related to the changes Request library changes wp-cli 2.8+. We are using the Decalog plugin with a Datadog logger. The plugin uses wp_remote_post to transmit logs after running a wp-cli command.

PHP Fatal error:  Uncaught TypeError: WP_HTTP_Requests_Response::__construct(): Argument #1 ($response) must be of type Requests_Response, WpOrg\Requests\Response given, called in /www/public/wp-includes/class-wp-http.php on line 397 and defined in /www/public/wp-includes/class-wp-http-requests-response.php:42
Stack trace:
#0 /www/public/wp-includes/class-wp-http.php(397): WP_HTTP_Requests_Response->__construct()
#1 /www/public/wp-includes/class-wp-http.php(614): WP_Http->request()
#2 /www/public/wp-includes/http.php(179): WP_Http->post()
#3 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(109): wp_remote_post()
#4 /www/public/wp-content/plugins/decalog/includes/handlers/class-datadoghandler.php(56): Decalog\Handler\AbstractBufferedHTTPHandler->write()
#5 /www/public/wp-content/plugins/decalog/includes/handlers/class-datadoghandler.php(80): Decalog\Handler\DatadogHandler->write()
#6 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(144): Decalog\Handler\DatadogHandler->handleBatch()
#7 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(161): Decalog\Handler\AbstractBufferedHTTPHandler->flush()
#8 /www/public/wp-includes/class-wp-hook.php(305): Decalog\Handler\AbstractBufferedHTTPHandler->close()
#9 /www/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#10 /www/public/wp-includes/plugin.php(474): WP_Hook->do_action()
#11 /www/public/wp-includes/load.php(1100): do_action()
#12 [internal function]: shutdown_action_hook()
#13 {main}
  thrown in /www/public/wp-includes/class-wp-http-requests-response.php on line 42

**Describe how other contributors can replicate this bug**

- Install Wordpress 5.9.5
- Install Decalog 3.8.0
- Configure a Datadog event logger
- Run a command that generates a log captured by the Decalog Datadog logger

**Describe what you expect as the correct outcome**

The command completes without throwing a fatal error.

**Let us know what environment you are running this on**

OS:	Linux 5.4.0-1108-gcp #117-Ubuntu SMP Tue Jun 20 23:26:26 UTC 2023 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.0
PHP version:	8.0.28
php.ini used:	/etc/php/8.0/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.5.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/www
WP-CLI packages dir:
WP-CLI cache dir:	/www/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.8.1

Wordpress version: 5.9.5

**Comment by jmtorres** [comment]
Here is the line that calls wp_remote_post [class-abstractbufferedhttphandler.php(109): wp_remote_post()](https://github.com/Pierre-Lannoy/wp-decalog/blob/6b36591703de18669112b41defb6ceb4fd4485ab/includes/handlers/class-abstractbufferedhttphandler.php#L109)

**Comment by jmtorres** [comment]
When running the commands directly on the server, it appears to work correctly. However, when running the command remotely with an alias, it seems that wp-cli isn't able to recognize which request class it should use.

Works properly:
~/public$ wp --debug=bootstrap
Debug: Processing bootstrap step: WP_CLI\Bootstrap\DeclareAbstractBaseCommand (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeFrameworkAutoloader (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\ConfigureRunner (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeRequestsAutoloader (0.008s)
Debug: Setting RequestsLibrary::$version to v1 (0.008s)
Debug: Setting RequestsLibrary::$source to wp-core (0.008s)
Debug: Setting RequestsLibrary::$class_name to \Requests (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeColorization (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeLogger (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\DefineProtectedCommands (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LoadExecCommand (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LoadRequiredCommand (0.008s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludePackageAutoloader (0.008s)
Debug: Loading packages from: /www/.wp-cli/packages/vendor/autoload.php (0.009s)
Debug: Loading detected autoloader: /www/.wp-cli/packages/vendor/autoload.php (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeFallbackAutoloader (0.009s)
Debug: Fallback autoloader paths: phar://wp-cli.phar/vendor/autoload.php (0.009s)
Debug: Loading detected autoloader: phar://wp-cli.phar/vendor/autoload.php (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\RegisterFrameworkCommands (0.045s)
Debug: Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/cli.php (0.045s)
Debug: Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/help.php (0.047s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\RegisterDeferredCommands (0.047s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeContexts (0.047s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LaunchRunner (0.048s)
Debug: No readable global config found (0.048s)
Debug: No project config found (0.048s)
Debug: argv: /usr/local/bin/wp --debug=bootstrap (0.048s)
Debug: ABSPATH defined: /www/public/ (0.048s)
Debug: Begin WordPress load (0.048s)
Debug: wp-config.php path: /www/public/wp-config.php (0.048s)
Debug: Looking for UTF-8 BOM (0.048s)
Debug: Looking for UTF-16 (BE) BOM (0.048s)
Debug: Looking for UTF-16 (LE) BOM (0.048s)
Debug: Loaded WordPress (0.793s)
Debug: Running command: help (0.794s)


Produces error:
➜  ~ wp @***** --debug=bootstrap
Debug: Processing bootstrap step: WP_CLI\Bootstrap\DeclareAbstractBaseCommand (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeFrameworkAutoloader (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\ConfigureRunner (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeRequestsAutoloader (0.012s)
Debug: Setting RequestsLibrary::$version to v2 (0.012s)
Debug: Setting RequestsLibrary::$source to wp-cli (0.012s)
Debug: Setting RequestsLibrary::$class_name to \WpOrg\Requests\Requests (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeColorization (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeLogger (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\DefineProtectedCommands (0.012s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LoadExecCommand (0.013s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LoadRequiredCommand (0.013s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludePackageAutoloader (0.013s)
Debug: Loading packages from: /Users/jose.torres/.wp-cli/packages/vendor/autoload.php (0.014s)
Debug: Loading detected autoloader: /Users/jose.torres/.wp-cli/packages/vendor/autoload.php (0.014s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeFallbackAutoloader (0.017s)
Debug: Fallback autoloader paths: phar:/wp-cli.phar/vendor/autoload.php (0.017s)
Debug: Loading detected autoloader: phar:/wp-cli.phar/vendor/autoload.php (0.017s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\RegisterFrameworkCommands (0.034s)
Debug: Adding framework command: phar:/wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/cli.php (0.034s)
Debug: Adding framework command: phar:/wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/help.php (0.035s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\RegisterDeferredCommands (0.036s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeContexts (0.036s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LaunchRunner (0.036s)
Debug: Using default global config: /Users/jose.torres/.wp-cli/config.yml (0.036s)
Debug: No project config found (0.036s)
Debug: argv: /opt/homebrew/bin/wp @***** --debug=bootstrap (0.036s)
Debug: SSH scheme:  (0.036s)
Debug: SSH user: ***** (0.036s)
Debug: SSH host: ***** (0.036s)
Debug: SSH port: ***** (0.036s)
Debug: SSH path:  (0.036s)
Debug: SSH key:  (0.036s)
Debug: Running SSH command: ssh -q -p *****  -t '*****@*****' 'WP_CLI_RUNTIME_ALIAS='\''{"@*****":{"path":"\/www\/public"}}'\'' wp @***** '\''--debug=bootstrap'\''' (0.036s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\DeclareAbstractBaseCommand (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeFrameworkAutoloader (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\ConfigureRunner (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeRequestsAutoloader (0.009s)
Debug: Setting RequestsLibrary::$version to v2 (0.009s)
Debug: Setting RequestsLibrary::$source to wp-cli (0.009s)
Debug: Setting RequestsLibrary::$class_name to \WpOrg\Requests\Requests (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeColorization (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeLogger (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\DefineProtectedCommands (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LoadExecCommand (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LoadRequiredCommand (0.009s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludePackageAutoloader (0.009s)
Debug: Loading packages from: /www/.wp-cli/packages/vendor/autoload.php (0.01s)
Debug: Loading detected autoloader: /www/.wp-cli/packages/vendor/autoload.php (0.01s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\IncludeFallbackAutoloader (0.01s)
Debug: Fallback autoloader paths: phar:/wp-cli.phar/vendor/autoload.php (0.01s)
Debug: Loading detected autoloader: phar:/wp-cli.phar/vendor/autoload.php (0.01s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\RegisterFrameworkCommands (0.05s)
Debug: Adding framework command: phar:/wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/cli.php (0.05s)
Debug: Adding framework command: phar:/wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/help.php (0.051s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\RegisterDeferredCommands (0.052s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\InitializeContexts (0.052s)
Debug: Processing bootstrap step: WP_CLI\Bootstrap\LaunchRunner (0.052s)
Debug: No readable global config found (0.052s)
Debug: No project config found (0.052s)
Debug: argv: /usr/local/bin/wp @***** --debug=bootstrap (0.052s)
Debug: ABSPATH defined: /www/public/ (0.052s)
Debug: Begin WordPress load (0.053s)
Debug: wp-config.php path: /www/public/wp-config.php (0.053s)
Debug: Looking for UTF-8 BOM (0.053s)
Debug: Looking for UTF-16 (BE) BOM (0.053s)
Debug: Looking for UTF-16 (LE) BOM (0.053s)
PHP Deprecated:  The PSR-0 `Requests_...` class names in the Requests library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience. in phar://usr/local/bin/wp/vendor/wp-cli/wp-cli/bundle/rmccue/requests/library/Requests.php on line 24
Deprecated: The PSR-0 `Requests_...` class names in the Requests library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience. in phar://usr/local/bin/wp/vendor/wp-cli/wp-cli/bundle/rmccue/requests/library/Requests.php on line 24
PHP Fatal error:  Uncaught TypeError: WP_HTTP_Requests_Response::__construct(): Argument #1 ($response) must be of type Requests_Response, WpOrg\Requests\Response given, called in /www/public/wp-includes/class-wp-http.php on line 397 and defined in /www/public/wp-includes/class-wp-http-requests-response.php:42
Stack trace:
#0 /www/public/wp-includes/class-wp-http.php(397): WP_HTTP_Requests_Response->__construct()
#1 /www/public/wp-includes/class-wp-http.php(614): WP_Http->request()
#2 /www/public/wp-includes/http.php(179): WP_Http->post()
#3 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(109): wp_remote_post()
#4 /www/public/wp-content/plugins/decalog/includes/handlers/class-datadoghandler.php(56): Decalog\Handler\AbstractBufferedHTTPHandler->write()
#5 /www/public/wp-content/plugins/decalog/includes/handlers/class-datadoghandler.php(80): Decalog\Handler\DatadogHandler->write()
#6 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(144): Decalog\Handler\DatadogHandler->handleBatch()
#7 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(161): Decalog\Handler\AbstractBufferedHTTPHandler->flush()
#8 /www/public/wp-includes/class-wp-hook.php(305): Decalog\Handler\AbstractBufferedHTTPHandler->close()
#9 /www/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#10 /www/public/wp-includes/plugin.php(474): WP_Hook->do_action()
#11 /www/public/wp-includes/load.php(1100): do_action()
#12 [internal function]: shutdown_action_hook()
#13 {main}
  thrown in /www/public/wp-includes/class-wp-http-requests-response.php on line 42
Fatal error: Uncaught TypeError: WP_HTTP_Requests_Response::__construct(): Argument #1 ($response) must be of type Requests_Response, WpOrg\Requests\Response given, called in /www/public/wp-includes/class-wp-http.php on line 397 and defined in /www/public/wp-includes/class-wp-http-requests-response.php:42
Stack trace:
#0 /www/public/wp-includes/class-wp-http.php(397): WP_HTTP_Requests_Response->__construct()
#1 /www/public/wp-includes/class-wp-http.php(614): WP_Http->request()
#2 /www/public/wp-includes/http.php(179): WP_Http->post()
#3 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(109): wp_remote_post()
#4 /www/public/wp-content/plugins/decalog/includes/handlers/class-datadoghandler.php(56): Decalog\Handler\AbstractBufferedHTTPHandler->write()
#5 /www/public/wp-content/plugins/decalog/includes/handlers/class-datadoghandler.php(80): Decalog\Handler\DatadogHandler->write()
#6 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(144): Decalog\Handler\DatadogHandler->handleBatch()
#7 /www/public/wp-content/plugins/decalog/includes/handlers/class-abstractbufferedhttphandler.php(161): Decalog\Handler\AbstractBufferedHTTPHandler->flush()
#8 /www/public/wp-includes/class-wp-hook.php(305): Decalog\Handler\AbstractBufferedHTTPHandler->close()
#9 /www/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#10 /www/public/wp-includes/plugin.php(474): WP_Hook->do_action()
#11 /www/public/wp-includes/load.php(1100): do_action()
#12 [internal function]: shutdown_action_hook()
#13 {main}
  thrown in /www/public/wp-includes/class-wp-http-requests-response.php on line 42
Error: Cannot connect over SSH using provided configuration.

**Comment by danielbachhuber** [comment]
We [debugged this a bit in Slack](https://wordpress.slack.com/archives/C02RP4T41/p1692627727795489).

The alias implementation is passing `--path` through an environment variable:

```
Debug: Running SSH command: ssh -q -p ***** -t '@' 'WP_CLI_RUNTIME_ALIAS='''{"@":{"path":"/www/public"}}''' wp @ '''--debug=bootstrap'''' (0.036s)
```

This is normally applied in the runner:

https://github.com/wp-cli/wp-cli/blob/89eb9918c37e22745657f76bc147a0eb0781a63e/php/WP_CLI/Runner.php#L1160

However, it's not applied in `IncludeRequestsAutoloader`:

https://github.com/wp-cli/wp-cli/blob/89eb9918c37e22745657f76bc147a0eb0781a63e/php/WP_CLI/Bootstrap/IncludeRequestsAutoloader.php#L49-L52

**Comment by danielbachhuber** [comment]
Also, I was able to reproduce this locally by installing WordPress 5.8 to `/Users/danielbachhuber/projects/vanilla`, adding a `wp_remote_get()` call to a mu-plugin, and running `WP_CLI_RUNTIME_ALIAS='{"@foo":{"path":"/Users/danielbachhuber/projects/vanilla"}}' wp @foo option get home --debug`
