### ISSUE TITLE
Identify a couple dozen 'contributor-day' and 'good-first-issue' issues for WCUS 2023

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5820]
> Good first issue: don’t require a lot of context; either straightforward, or the solution is in the issue
> Contributor day: solvable in a few hours, can involve some discussion with other contributors, fairly straightforward.
> We can also ask new contributors whether they have any issues they’d like to work on, or suggest.
> Ideas repository could be another source (and more exciting).

**Done is:**
* These issues are listed in our Contributor Day doc #5811

**Comment by swissspidy** [comment]
* [All contributor day issues](https://github.com/search?q=org%3Awp-cli%20label%3Acontributor-day+is%3Aopen&type=issues)
* [All good first issues](https://github.com/search?q=org%3Awp-cli+label%3Agood-first-issue+is%3Aopen&type=issues)

So far 44 results combined (there is some overlap)

**Comment by danielbachhuber** [comment]
@swissspidy Want to submit a PR against [my PR](https://github.com/wp-cli/handbook/pull/456) with the 10-15 issues you think are the best?

**Comment by danielbachhuber** [comment]
Added some issues in https://github.com/wp-cli/handbook/pull/460

**Comment by danielbachhuber** [comment]
@schlessera @swissspidy I think I’m finding it more effect to help folks find their first issue based on area of interest and skill level, instead of leaving them to figure it out for themselves.
