### ISSUE TITLE
List posts by a taxonomy producing unexpected results

### ISSUE THREAD

**Issue by Mr-Alexander** [wp-cli/wp-cli#5826]
for some reason, the results are the same whether I add the taxonomy param or omit it, regardless of which (public) taxonomy I use

these return the same results:

```
01. wp post list

02. wp post list --<taxonomy>=<term-slug>
```

as a safety measure, I even deactivated all the plugins, but still the same results.

Please advise what could be missing here or needs to be refined further.

The [documentation](https://developer.wordpress.org/cli/commands/post/list/) does not offer examples in this regard and simply mentioned to include any WP_Query params, yet `tax_query` is an array param.

Thanks for your help, I am able to elaborate further as needed.

**Comment by danielbachhuber** [comment]
Hey @Mr-Alexander,

GitHub is meant as an issue tracker, not a general support forum. 
Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
