### ISSUE TITLE
Run the test suite with SQLite

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5831]
For ease of contributing to WP-CLI, it would be cool if you could run the test suite against SQLite. This would remove the requirement of a working MySQL server.

Some WP-CLI commands use the MySQL executable directly. We can simply flag the tests with a `@requires-mysql` flag, and have the command bail when SQLite is detected.

**Done is:**
* It's possible to run the test suite against MySQL.
* The WP-CLI test suite has an additional run against SQLite.

**Comment by mrsdizzie** [comment]
This would be cool! Is the current state of WordPress and SQLite that it requires a plugin to use? Does that mean only running tests against a modified version of the latest WordPress release with that plugin pre-installed?

**Comment by danielbachhuber** [comment]
@mrsdizzie Yep, we'd need to inject https://github.com/WordPress/sqlite-database-integration into `Given a WP install`. WordPress core wouldn't need to be modified, though.

**Comment by swissspidy** [comment]
Here's where WP installation happens:

https://github.com/wp-cli/wp-cli-tests/blob/c2d228bbfe6eecc0cab3cfe71ea0d04c4ae1e095/src/Context/FeatureContext.php#L884-L970

There are also a bunch of places in that file where MySQL commands are run and tables being cached etc. So those need to be adapted as well.

Here's where tags like `@requires-mysql` or `@requires-sqlite` could be defined:

https://github.com/wp-cli/wp-cli-tests/blob/c2d228bbfe6eecc0cab3cfe71ea0d04c4ae1e095/utils/behat-tags.php

I suppose both could check for a `DB_TYPE` environment variable or something.

If `DB_TYPE=sqlite`, install WP with SQLite and skip all tests that require MySQL

**Comment by swissspidy** [comment]
I think we achieved this by now, marking as closed!
