### ISSUE TITLE
Make search-replace as a subcommand of 'db'

### ISSUE THREAD

**Issue by f2cmbeapi** [wp-cli/wp-cli#5835]
Error: 'search-replace' is not a registered subcommand of 'db'. See 'wp help db' for available subcommands.

This command is obviously a database-related one, why not apply the logic and move this command as a sub one for 'db' ?

**Comment by danielbachhuber** [comment]
Thanks for the question, @f2cmbeapi !

`wp search-replace` has always existed as a standalone command. The `wp db *` set of commands focus more on direct database interaction. We won't be moving `wp search-replace` at this time.
