### ISSUE TITLE
Resolve duplicate copies of `RecursiveDataStructureTraverser`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5837]
We have two copies of `RecursiveDataStructureTraverser`, one in https://github.com/wp-cli/entity-command/ and one in https://github.com/wp-cli/cache-command/.

Ideally, we'd just have one copy of the class. It could live in this repository, or it could live as a standalone package.

From https://github.com/wp-cli/cache-command/pull/89

**Done is:**
* We only have one copy of the class, and it's referenced by each repository.

**Comment by thelovekesh** [comment]
@danielbachhuber Since this will also need to be updated in `wp-cli/entity-command`, I have opened an issue for that https://github.com/wp-cli/entity-command/issues/435

**Comment by thelovekesh** [comment]
As discussed on WP CLI hack day, these changes will be part of a new package - https://github.com/wp-cli/wp-recursive-traverser

**Comment by schlessera** [comment]
After a follow-up discussion in https://github.com/wp-cli/wp-cli/pull/5866, we decided to include it in the WP-CLI framework instead as initially planned.

**Comment by thelovekesh** [comment]
@danielbachhuber @schlessera  Since this has landed in the WP CLI 2.10.0 release, I think we can close it as completed.

**Comment by danielbachhuber** [comment]
Sounds good, thanks!
