### ISSUE TITLE
Documentation: skip-plugins, skip-themes and mu-plugins

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#5838]
Could the docs for "wp db reset" be updated to clarify that/if:
1) if the command will not load any themes/plugins (= "--skip-plugins --skip-themes" are the default?)

2) if the command will not load any mu-plugins? 
If it does load mu-plugins, there should be a way to stop that from happening. As otherwise (malicious) mu-plugins could stop the DB reset by just calling exit; and abort the process.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @kkmuffme

I think we could do even better: for every command with `@when before_wp_load`, include some explanation of when the command executes.

I moved this to `wp-cli/wp-cli` because doing so would be a general framework change.

**Comment by danielbachhuber** [comment]
@mrsdizzie Could you apply the equivalent of https://github.com/wp-cli/handbook/pull/501 to `wp scaffold package-readme` too? https://github.com/wp-cli/scaffold-package-command
