### ISSUE TITLE
Unexpected tab completion behaviour with prefixes

### ISSUE THREAD

**Issue by Roy-Orbison** [wp-cli/wp-cli#5845]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When using tab completions, wp-cli's behaviour is inconsistent with all other tab completions I've used, in the case where the word being completed is both an option itself and a prefix of another option. It does not seem to be specific to a shell but, rather, is caused by the potential options wp-cli returns from a given input. I've encountered this using the options beginning with `--report` or `--regex` when using `wp search-replace` but I imagine there are other cases.

**Describe how other contributors can replicate this bug**

E.g. type this then press <kbd>Tab</kbd> a couple of times:
```sh
$ wp search-replace --rep
```

Actual behaviour "eats" the shorter option and completes the longer:
```sh
$ wp search-replace --report-changed-only
```

**Describe what you expect as the correct outcome**

The expected behaviour is to stop completing and display both options until the user disambiguates with <kbd>Space</kbd>, <kbd>-</kbd> or <kbd>Enter</kbd>:
```sh
$ wp search-replace --report
--report               --report-changed-only
```

To get a like-for-like comparison:
1. Run the following code in bash to set up a command named `wpx` for comparison (a safe no-op), and rudimentary completion for it:
    ```bash
    wpx () {
        :
    }
    _wpx () {
        if [ "$3" = "$1" ]; then
            COMPREPLY=( $( compgen -W search-replace -- "$2" ) )
        else
            COMPREPLY=( $( compgen -W '--report --report-changed-only' -- "$2" ) )
        fi
    }
    complete -F _wpx wpx
    ```
2. Enter `wpx` then press <kbd>Tab</kbd> until the output does not change.

**Let us know what environment you are running this on**

I've experienced this in multiple environments in many versions of wp-cli, but all were on Linux.

**Comment by swissspidy** [comment]
Hmm I already get this behavior in my shell:

```bash
# Press Tab shows both options
$ wp search-replace --rep
--report                --report-changed-only

# Press Tab once, completes to first option
$ wp search-replace --report

# Press Tab again, completes to second option
$ wp search-replace --report-changed-only 
```

Where/how did you install the bash completion on your system? What OS are you using?

Here's the current one for comparison:

https://github.com/wp-cli/wp-cli/blob/f4f783fc3db8996e01d35fae530bed14a0eaee5b/utils/wp-completion.bash

**Comment by Roy-Orbison** [comment]
> ```shell
> # Press Tab once, completes to first option
> $ wp search-replace --report
> 
> # Press Tab again, completes to second option
> $ wp search-replace --report-changed-only 
> ```

That's what I get, and is the issue I'm reporting; the completion of the second option is non-standard. It's assuming a selection based on number of Tab presses, but it should show both until the user disambiguates their choice.

Another example of standard completion behaviour:
```sh
roy@RoyBook:~$ rsync --delete
--delete           --delete-after     --delete-before    --delete-delay     --delete-during    --delete-excluded
roy@RoyBook:~$ rsync --delete
--delete           --delete-after     --delete-before    --delete-delay     --delete-during    --delete-excluded
roy@RoyBook:~$ rsync --delete
--delete           --delete-after     --delete-before    --delete-delay     --delete-during    --delete-excluded
roy@RoyBook:~$ rsync --delete
```
It doesn't matter how many times one presses Tab, the results continue to include both the original word being completed _and_ the other options the word is a prefix of. Wp-cli's current completion would change this to `--delete-` (with a trailing dash).

> Here's the current one for comparison:

That's identical to mine.

In concrete terms, this is what is happening:
```sh
roy@RoyBook:~$ (COMP_LINE='wp search-replace --report'; wp cli completions --line="$COMP_LINE" --point=${#COMP_LINE})
--report-changed-only
```
But it should be the same as if `COMP_LINE` were `wp search-replace --rep`, like so:
```sh
roy@RoyBook:~$ (COMP_LINE='wp search-replace --report'; wp cli completions --line="$COMP_LINE" --point=${#COMP_LINE})
--report
--report-changed-only
```

This would result in output consistent with other tools, exactly as the above `wpx` example demonstrates:
```sh
roy@RoyBook:~$ wp search-replace --report
--report               --report-changed-only
roy@RoyBook:~$ wp search-replace --report
--report               --report-changed-only
roy@RoyBook:~$ wp search-replace --report
--report               --report-changed-only
```

**Comment by swissspidy** [comment]
Ah, now I got it, thanks!
