### ISSUE TITLE
Simple "How to use Behat" video for WP-CLI Hack Day 2023

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5858]
This is for folks participating in the WP-CLI Hack Day: https://make.wordpress.org/cli/handbook/contributions/contributor-day/

First, watch the introductory video: https://www.youtube.com/watch?v=hMJDGmuXAoY

Once you've done so, feel free to ask any questions here!

**Comment by sejas** [comment]
Daniel, great video! 🙌

I'm dropping the testing instructions here in case other folks want to run the same example step by step.

## Testing Instructions

To ensure that your development environment is setup correctly, please follow these steps.

1. **Navigate to the test directory:**

    ```bash
    cd entity-command
    ```

2. **Create a new feature test:** Navigate to the `entity-command/features` directory and create a new file named `example.feature`.

    ```bash
    touch features/example.feature
    ```

2. **Add the test content:** Open the `example.feature` file you just created and insert the following content:

```gherkin
Feature: Manage WordPress options

  Scenario: Read an individual option
    Given a WP install

    When I run `wp option get home`
    Then STDOUT should be:
      """
      https://example.com
      """
```

You can do this using a text editor of your choice.

4. **Execute the test:** Use Composer to run the Behat test suite specifying the path to your new test file:

    ```bash
    composer behat -- features/example.feature
    ```

5. **Observe the expected output:** Upon successful completion of the test, you should see output similar to the following:

<img width="524" alt="Test result" src="https://github.com/wp-cli/wp-cli/assets/779993/f0ae518a-74fe-4e3c-a6c3-db4d7eee18e5">

**Comment by danielbachhuber** [comment]
🚢
