### ISSUE TITLE
WP-CLI November 2023 Hack Day pull requests

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5859]
This issue tracks the pull requests submitted during WP-CLI November 2023 Hack Day. Feel free to log any other contributions here too.

**Comment by danielbachhuber** [comment]
🚢

**Comment by 2ndkauboy** [comment]
Why stop at 22, when there are two more pending? 😉

But great job everyone! 🙌

**Comment by danielbachhuber** [comment]
@2ndkauboy If you're so motivated, you can figure out this MySQL socket thing 😉 https://github.com/wp-cli/config-command/pull/171#issuecomment-1806326832

Thanks for joining us today!

**Comment by 2ndkauboy** [comment]
I was motivated, but it was already 1am for me 😅
