### ISSUE TITLE
wp config create --dbhost="localhost:/run/mysqld/mysqld.sock" not working since 2.9.0 update

### ISSUE THREAD

**Issue by tobias992** [wp-cli/wp-cli#5878]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Before update 2.9.0 i created my wp-config.php files with this command:

wp config create --dbname=db_name --dbuser=dbu_name --dbpass=db_password --dbhost="localhost:/run/mysqld/mysqld.sock" --dbprefix=12345_ --allow-root

Since 2.9.0 i cannot use "localhost:/run/mysqld/mysqld.sock" anymore. I get a database connection error.

**Describe how other contributors can replicate this bug**

Just try my command with version 2.9.0. That's all.

**Let us know what environment you are running this on**

```
OS:     Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.1
PHP version:    8.1.25
php.ini used:   /etc/php/8.1/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.11.5-MariaDB, for debian-linux-gnu (x86_64) using readline EditLine wrapper
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI cache dir:       /root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.9.0
```

**Provide a possible solution**

First:
wp config create --dbname=db_name --dbuser=dbu_name --dbpass=db_password --dbprefix=12345_ --allow-root

Then:
wp config set DB_HOST "localhost:/run/mysqld/mysqld.sock" --type=constant --allow-root

I just want to let you know that there was a change in last release and i could not find anything about this in changelog.

**Comment by danielbachhuber** [comment]
Thanks for the report, @tobias992 !

This is a bug and is being tracked here: https://github.com/wp-cli/config-command/issues/169

You can include `--skip-check` for now to bypass the error.
