### ISSUE TITLE
PHP parse error 

### ISSUE THREAD

**Issue by retrofan2019** [wp-cli/wp-cli#5888]
## Bug Report

- [ x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

After downloading the phar file using wget ... I checked info using this command
`php wp-cli.phar --info `

and this is the error I got :

```
[root@www ~]# php wp-cli.phar --info                                           
 PHP Parse error:  syntax error, unexpected '[' in phar:///root/wp-cli.phar/vendor/wp-cli/wp-cli/php/compat.php on line 85
```

**Let us know what environment you are running this on**

Dedicated server running  ‪CentOS 6.7.
PHP 7.0.33 | Apache | MySQL 5.1.73

**Comment by danielbachhuber** [comment]
Thanks for the report, @retrofan2019.

It looks like the fatal is originating with this line:

https://github.com/wp-cli/wp-cli/blob/d9ba82bc90105e75ff1a2ca460d295a10a18b690/php/compat.php#L85

Short array syntax originated in PHP 5.4, so my guess is that `php` is somehow mapped to an earlier version.

Can you share what you see when you run `php --version`?

**Comment by retrofan2019** [comment]
yes, you are right .. it is mapped to an earlier version (5.3.3) ...not really sure how this happened ..
I rarely do anything server side and I used Plesk to set everything up.

**Comment by retrofan2019** [comment]
I used "Export" command to be able to use PHP 7.0.33 ...it only works during the open session but it does the trick and wp-cli works with no problems  .
