### ISSUE TITLE
Owners and Permissions scheme

### ISSUE THREAD

**Issue by richardkentgates** [wp-cli/wp-cli#5890]
I could not find enough documentation on the permission scheme to begin using the wp cli. I feel like I can figure it out but I will wait until... Thank you

**Comment by richardkentgates** [comment]
Group permissions are required. Should have been in the documentation. Why is nobody providing this information to anyone else asking this question? at least 5 years of this question floating around the internet, and I still couldn't find an answer today. I had to go to wordpress IRC.

**Comment by richardkentgates** [comment]
I tried the wordpress IRC and what I got was two answers. Create a group with apache and the current/desired user and give it permissions to the web root, along with changing the directory owner to the desired user. The other was to perform commands as apache/web server. Does anyone have the CORRECT answer for this? Following the documentation just does not work, period.

**Comment by danielbachhuber** [comment]
Looks like this conversation happened in Slack: https://wordpress.slack.com/archives/C02RP4T41/p1703954516192989

To summarize, providing direction on filesystem permissions is outside the scope of the WP-CLI project. Filesystem permissions are a complex topic and not directly tied to WP-CLI's operation.
