### ISSUE TITLE
phar version is out-of-date

### ISSUE THREAD

**Issue by baizmandesign** [wp-cli/wp-cli#5904]
Hi there,

When I follow the [official installation instructions](https://make.wordpress.org/cli/handbook/guides/installing/) to install the phar version of WP CLI, version 2.9.0 gets installed. Version 2.10.0 was released last week.

Steps to reproduce:

```
$ curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
$ php wp-cli.phar --info
OS:     Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 x86_64
Shell:  /bin/zsh
PHP binary:     /usr/local/Cellar/php/8.3.2/bin/php
PHP version:    8.3.2
php.ini used:   /usr/local/etc/php/8.3/php.ini
MySQL binary:   /Users/Shared/DBngin/mysql/8.0.27/bin/mysql
MySQL version:  mysql  Ver 8.0.27 for macos11 on x86_64 (MySQL Community Server - GPL)
SQL modes:      ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/saul/Desktop
WP-CLI packages dir:
WP-CLI cache dir:       /Users/saul/.wp-cli/cache
WP-CLI global config:   /Users/saul/.wp-cli/config.yml
WP-CLI project config:
--> WP-CLI version: 2.9.0 <--
```

Did something happen, or fail to happen, during the release process?

Thanks.

Saul

**Comment by danielbachhuber** [comment]
Thanks for the report, @baizmandesign 

> Did something happen, or fail to happen, during the release process?

Something failed to happen during the release process.

Specifically, it appears the stable build files didn't get updated during the release process:

![CleanShot 2024-02-11 at 06 54 09@2x](https://github.com/wp-cli/wp-cli/assets/36432/bec70902-8777-4095-a638-287c1b06dae0)

It looks like there's a new release build thing, but that doesn't quite map to the [documented release process steps](https://github.com/wp-cli/wp-cli/issues/5891):

![CleanShot 2024-02-11 at 06 55 44@2x](https://github.com/wp-cli/wp-cli/assets/36432/1df31b51-d34b-4a4a-b199-739e9a3cdc04)

@schlessera @swissspidy Has the release process been modified? If so, should we update the template accordingly? Also, for this particular issue, can I simply [download the files from the release](https://github.com/wp-cli/wp-cli/releases/tag/v2.10.0) and commit them directly to the builds repo?

**Comment by schlessera** [comment]
@danielbachhuber I just checked, it looks like I missed (or messed up) the final push for the required change. It was already committed in my local branch, but I somehow failed to push it to remote.
Should be fixed now.
Thanks fore reporting, @baizmandesign !

**Comment by danielbachhuber** [comment]
@schlessera Ah, cool. Thank you 😊

**Comment by baizmandesign** [comment]
Thanks for fixing this, @schlessera and @danielbachhuber! I appreciate it.
