### ISSUE TITLE
Author URI of the plugin translation string in generated POT file

### ISSUE THREAD

**Issue by henrywright** [wp-cli/wp-cli#5906]
When I generate a POT file using `wp i18n make-pot . languages/my-plugin.pot` there seems to be an entry for URI. For example:

```
#. Author URI of the plugin
msgid "https://example.com"
msgstr ""
```

Even though it isn't a "clickable" link, is it a good idea to make this string available for translation?

**Comment by swissspidy** [comment]
Why is it not "clickable"? The URL is used for linking to the author's website, for example on the plugins page in wp-admin.

Some people translate their website into other languages, so this might be translated to `https://example.com/de` or `https://example.com/es` for example.

So yes, it is a good idea to make this string available for translation and WordPress translates it.

In fact, 'Name', 'Plugin URI', 'Description', 'Author', 'Author URI', 'Version' are all fields that WordPress translates.

So we want to make sure people can translate it.

**Comment by henrywright** [comment]
My point is the translation may not be from https://example.com/de to https://example.com/es. Instead it may be from https://example.com/de to something like https://hack.me
