### ISSUE TITLE
Difficult to create posts with blocks

### ISSUE THREAD

**Issue by jcvignoli** [wp-cli/wp-cli#5923]
Latest wp-cli version (2.10), I can't create a new post with html tags.

I try the following command:
```
wp post create --post_title="Test" --post_type=post --post_content="<p>asfasdfasdf</p>"
```
but get no `<p>` tag created.
My true objective is to get something like: 
```
wp post create --post_title="Test" --post_type=post --post_content= "<!-- wp:paragraph -->\n<p><div class="wp-block-myplugin-main"><span data-myplugin_data="movie_id">0062622</span></div></p>\n<!-- /wp:paragraph -->"
```
which is, quite frankly, extermely complicated, due to the quotes escaping. I found sort a formula on two lines, with a line break before the --post_centent, which kinds of works, only if the wp:paragraphs tags are added:

```
wp post create --post_title="Test" --post_type=post --post_status="publish" \
--post_content="<!-- wp:paragraph --><span data-myplugin_data=""movie_id"">0062622</span><!-- /wp:paragraph -->"
```
but unfortunately, no post is inserted. If I take out the wp:paragraphs, I get `Error: Unable to read content from 'data-myplugin_data=movie_id>0062622</span>'.`

I've tried many combinations, escaping quotes, slashes, using single quotes instead of double quotes, but I'm most often get "Too many positional arguments".

I can't understand how to insert html tags with wp post create. Seems actually quite complicated.

**Comment by swissspidy** [comment]
> I try the following command:
> 
> ```
> wp post create --post_title="Test" --post_type=post --post_content="<p>asfasdfasdf</p>"
> ```
> 
> but get no `<p>` tag created. My true objective is to get something like:

This is probably just WordPress removing the `<p>` upon insertion into the database. That's how WordPress has always operated, as it then uses `wp_autop` on the frontend to add back the paragraph tags. So this is expected.

I just tried this and it works like a charm:

```bash
wp post create --post_title="Test" --post_type=post --post_content='<!-- wp:paragraph --><p><div class="wp-block-myplugin-main"><span data-myplugin_data="movie_id">0062622</span></div></p><!-- /wp:paragraph -->'
```

---

On that note, a kind reminder that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review [https://wp-cli.org/#support](https://wp-cli.org/#support).

The easiest way to get support is to join us in the [`#cli`](https://wordpress.slack.com/messages/C02RP4T41) channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by danielbachhuber** [comment]
> I wonder if there's some opportunity for a better abstraction around doing what you're trying to do. Driving `wp post create` might be too low-level. Maybe we need some CLI for manipulating blocks?

@adamziel @dmsnell I'd be curious to hear your thoughts on ^. This could be something worth discussing at [WP-CLI Hack Day](https://make.wordpress.org/cli/2024/04/02/save-the-date-wp-cli-hack-day-on-friday-april-26th/) or the WordCamp Europe Contributor Day.

**Comment by helgatheviking** [comment]
>Out of curiosity, could you share more detail about your use case for using WP-CLI to create posts?

For me, it was to attempt to create the post as a step in the `blueprint.json` for setting up a plugin preview for a .org hosted plugin. I was having a lot of issues with importing an XML file (as importing was behaving differently in the playground than outside the playground). I think the problem is likely escaping because `blueprint.json` is JSON.

**Comment by danielbachhuber** [comment]
@helgatheviking Thanks! We should definitely improve that.

**Comment by swissspidy** [comment]
> > I wonder if there's some opportunity for a better abstraction around doing what you're trying to do. Driving `wp post create` might be too low-level. Maybe we need some CLI for manipulating blocks?
> 
> @adamziel[<img alt="" width="12" height="12" src="chrome-extension://paaanofjmlfndlnjcccfefllegcpckfd/images/wp-logo.png">](https://profiles.wordpress.org/zieladam) @dmsnell[<img alt="" width="12" height="12" src="chrome-extension://paaanofjmlfndlnjcccfefllegcpckfd/images/wp-logo.png">](https://profiles.wordpress.org/dmsnell) I'd be curious to hear your thoughts on ^. This could be something worth discussing at [WP-CLI Hack Day](https://make.wordpress.org/cli/2024/04/02/save-the-date-wp-cli-hack-day-on-friday-april-26th/) or the WordCamp Europe Contributor Day.

@danielbachhuber Please see https://github.com/wp-cli/ideas/issues/119

**Comment by jcvignoli** [comment]
> This is probably just WordPress removing the `<p>` upon insertion into the database. That's how WordPress has always operated, as it then uses `wp_autop` on the frontend to add back the paragraph tags. So this is expected.
> 
> I just tried this and it works like a charm:
> 
> ```shell
> wp post create --post_title="Test" --post_type=post --post_content='<p><div class="wp-block-myplugin-main"><span data-myplugin_data="movie_id">0062622</span></div></p>'
> ```

Thanks very much, you gave me the hint I need to find the bug. Since you confirmed it would work on your side, I deduced there was an issue with my workflow. I investigated and figured out that my home-made bash script to launch wp cli wasn't properly including all the command-line arguments, reasons why I got 2Too many positional arguments". I just embeded into double quotes and now it works like a charm.

> On that note, a kind reminder that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review https://wp-cli.org/#support.

I thought it was a bug.

**Comment by jcvignoli** [comment]
> @jcvignoli Out of curiosity, could you share more detail about your use case for using WP-CLI to create posts?
> 
> I wonder if there's some opportunity for a better abstraction around doing what you're trying to do. Driving `wp post create` might be too low-level. Maybe we need some CLI for manipulating blocks?

@danielbachhuber The issue was actually an local home-made script misconfiguration, and fixing it fixed my issue. Still interested? The wp-cli command I use is not groundbreaking or complex, just creating a post with a block.

**Comment by danielbachhuber** [comment]
> The issue was actually an local home-made script misconfiguration, and fixing it fixed my issue.

@jcvignoli Makes sense!

> Still interested? The wp-cli command I use is not groundbreaking or complex, just creating a post with a block.

I think it's still worth exploring. We can do so as a part of this issue: https://github.com/wp-cli/ideas/issues/119
