### ISSUE TITLE
WP-CLI April 2024 Hack Day pull requests

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5935]
This issue tracks the pull requests submitted during WP-CLI April 2024 Hack Day. Feel free to log any other contributions here too.

**Comment by danielbachhuber** [comment]
🚢  https://make.wordpress.org/cli/2024/04/27/fifteen-merged-prs-for-wp-cli-hack-day-2024/

**Comment by nikhilpachange** [comment]
[Correct plugin main file in bootstrap in scaffolded test wp-cli/scaffold-command#335](https://github.com/wp-cli/scaffold-command)
