### ISSUE TITLE
WCEU 2024 Contributor Day pull requests

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli#5955]
This issue tracks the pull requests submitted during WCEU Contributor Day. Feel free to log any other contributions here too.

**Comment by danielbachhuber** [comment]
9 contributors at each table, plus Alain and I

**Comment by wojtekn** [comment]
Wrapped up a potential plan for [Add commands to export and import SQLite databases](https://github.com/wp-cli/ideas/issues/188#issuecomment-2165659016).
