### ISSUE TITLE
Follow link with ctrl + click appends a full stop to the url 

### ISSUE THREAD

**Issue by pongoe** [wp-cli/wp-cli#5959]
Having updated a plugin using wp-cli, opening the download link with ctrl + click adds a full stop to the url and thus prevents the download since the page becomes a 404.

Occurs with literally every download from the WP repo.

**Comment by ernilambar** [comment]
How links are rendered in the CLI output in the terminal depends upon the terminal emulator. Can you please try in other terminal app?

**Comment by priyanshuhaldar007** [comment]
I tried it in the default terminal on mac, it's appropriately redirecting to the zip download link and is not appending any full stops to the URL.
