### ISSUE TITLE
WCUS 2024 Contributor Day pull requests

### ISSUE THREAD

**Issue by BrianHenryIE** [wp-cli/wp-cli#5985]
This issue tracks the pull requests submitted during WCUS Contributor Day. Feel free to log any other contributions here too.

See #5955 and #5832 for past Contributor Day contributions.

**Comment by zunaid321** [comment]
Working on this for WCUS 2024 - Contributor Day!

**Comment by zunaid321** [comment]
SSH key needs to be added to your Github Account, otherwise the access right issues will come up when you run composer install - when you try to prepare the Dev Environment for WP-CLI:

Was following the instructions here:

https://github.com/wp-cli/wp-cli-dev?tab=readme-ov-file#installation

**Comment by aaln** [comment]
Submitted [https://github.com/wp-cli/wp-cli-tests/pull/220](https://github.com/wp-cli/wp-cli-tests/pull/220)

This fixes issue with `composer prepare-tests` on sql v8.0.4+ related to [this bug ticket.](https://github.com/wp-cli/ideas/issues/194)
