### ISSUE TITLE
wp core download --path=$dest --locale=de_DE not working

### ISSUE THREAD

**Issue by bernham** [wp-cli/wp-cli#6015]
## Bug Report

- [ ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

A clear and concise description of the behavior that produces an incorrect result or error.

Remember: more information is better. Please provide context on how you're running the command to make sure we're all on the same page when reasoning about this.

**Describe how other contributors can replicate this bug**

- a list of
- steps to replicate
- the error condition

```js
// You can also use code snippets if needed.
```

**Describe what you expect as the correct outcome**

A clear and concise description of what you expected to happen (or code).

**Let us know what environment you are running this on**

```
(Paste the output of "wp cli info" into this box)
```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/screenshots**

If applicable, add screenshots to help explain (you can just drag&drop images into the GitHub issue).

**Comment by bernham** [comment]
wp core download --path=$dest --locale=de_DE hangs 
Hangs, without error message. Tested on MacBook Pro M2 and in a VM with Ubuntu 24.04. Worked two days ago without any problems. No changes were made to my system.

**Comment by swissspidy** [comment]
Is this still happening for you? Maybe wp.org was just down for a moment or so.

**Comment by bernham** [comment]
It works again. The problem was there for two days and the cause was not obvious, as it was always possible to download WP via the website. I also have no knowledge of how and where wp-cli performs the download.  Thank you very much for your commitment!
