### ISSUE TITLE
[Doc] how to disable global parameters

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli#6024]
https://docs.wpvip.com/vip-cli/wp-cli-with-vip-cli/disallowed-commands/#h-disallowed-global-parameters disables certain global parameters like `--ssh` but I couldn't find any docs on how to disable these via wp-cli.yml

Are there any docs available?

**Comment by swissspidy** [comment]
I think they use the `WP_CLI_EARLY_REQUIRE` environment variable to load a custom PHP file early in the bootstrap process, where they can add all sorts of custom logic.

Added in https://github.com/wp-cli/wp-cli/pull/5664, which contains an example of how it works.

We still need to document it in the handbook though.
