### ISSUE TITLE
Make plugin and theme subcommands aware of version-controlled folders

### ISSUE THREAD

**Issue by scribu** [wp-cli/wp-cli#639]
I don't mean running git or svn commands, just alerting the user when needed.

Use-case: I have a site in which some plugins are git submodules, while others are just copied, because it's too much work to create git mirrors for them.

So, for example, when I run `wp plugin update --all`, it should show a prompt:

```
Detected `.git` folder inside posts-to-posts plugin folder. Skip update? [y/n]
```

Related: https://github.com/tolgap/wp-svn-cli

**Comment by danielbachhuber** [comment]
At this point, I think the current behavior is fine as it is.
