### ISSUE TITLE
`wp comment generate` command

### ISSUE THREAD

**Issue by ryanduff** [wp-cli/wp-cli#671]
I want to tackle a command to generate random comments but wanted to get some feedback first as to how and which flags it should offer. This should be similar to the generate posts command where we can just bulk generate something to have data available for testing. 

For simplicity's sake, something like --max=200 would generate 200 comments randomly across all published posts. I'd just use the current timestamp to start along with user-x and user-x@example.com to generate some variety. Down the road perhaps grab the post publish time and pull a random timestamp between the publish time and current time. 

I've had theme testing use cases where we needed to grab comment counts from past x days, as well as totals on posts, top posts by comment count, etc. 

Any feedback or suggestions welcome before I start working on a PR.

**Comment by johnbillion** [comment]
Any movement on this? If not, I'll tackle it.

**Comment by danielbachhuber** [comment]
I've added a very basic `wp comment generate` in #1819. Some of the enhancements in this thread seem like they'd be nice.

**Comment by danielbachhuber** [comment]
Basic command seems to be working well for now.
