### ISSUE TITLE
Provide a way to upgrade the network after `wp update`

### ISSUE THREAD

**Issue by joehoyle** [wp-cli/wp-cli#683]
Would be cool if there were  / is a fall to do the network upgrade after WordPress has been updated. WordPress has this silly mechanism of doing 5 sites at a time for the network, if you have a few thousands sites this is not so cool.

Could wp-cli assist here?

**Comment by mackensen** [comment]
It seems like this requires two commands to accomplish with the current version of wp-cli:

- `wp site list --field=url | xargs -n 1 -I % wp core update-db --url=%` (update the sites in the network)
- `wp network meta update 1 wpmu_upgrade_site <version>` (to dismiss the notice in the network admin)

Am I missing something?

**Comment by danielbachhuber** [comment]
I like the idea of `wp db update --network`. We can incorporate it into the next release.
