### ISSUE TITLE
Command for installing language files

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/wp-cli#714]
A command for installing language files would be great. The files can be grabbed from the [localisation repository](http://codex.wordpress.org/Translating_WordPress#WordPress_Localization_Repository).

Ideas for the command structure:

`wp language install ro_RO`

`wp language list`

`wp language uninstall fr_FR`

`wp language update --all`

Thoughts?

**Comment by danielbachhuber** [comment]
This has since shipped.

**Comment by guaka** [comment]
For the record:

```
wp core language  # can do what?
wp core language list
wp core language install fr_FR
wp core language activate fr_FR
```
