### ISSUE TITLE
command for changing site url

### ISSUE THREAD

**Issue by guaka** [wp-cli/wp-cli#759]
When looking at http://codex.wordpress.org/Changing_The_Site_URL again I thought there was a need for a wordpress shell script. I started my own before tumbling on wp-cli, really happy I found it!

Unfortunately I can't find a command for changing the site URL.
#249 (search-replace) was the only issue that showed up.

Let's implement it... how and where do I start?

**Comment by kokoye2007** [comment]
its work for multi site ?
```
wp site  list
| 5       | http://chitkoko.ubuntu-mm.net/        | 
wp site option update 5 siteurl="https://chitkoko.ubuntu-mm.net/" 
```

like that 
http to https for multisite
