### ISSUE TITLE
Failure to correctly find wp-content/plugins or themes

### ISSUE THREAD

**Issue by whimsy-github** [wp-cli/wp-cli#785]
I cannot get wp-cli to find my plugin or theme directories the way I've structured wordpress files (relative to webserver root)

index.php: (copied from WordPress install with path modified to send it to the subdirectory)

    <?php 
    /* Short and sweet */
    define('WP_USE_THEMES', true);
    require('./wordpress/wp-blog-header.php');
    ?>

wordpress/   -->> Wordpress install as downloaded, no edited files
wp-content/  -->> MY plugins and themes under this

wp-config.php: (relevant excerpt below)

    if ($_SERVER['DOCUMENT_ROOT'] == "")
       $_SERVER['DOCUMENT_ROOT'] = dirname(__FILE__);
    define( 'WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content' );

Note: I added the first two lines in an attempt to work around this problem. My blog behaves well on both my production web host and my local test install (MAMP) without it.

In my database, the blog location settings point to example.com and WordPress location settings point to example.com/wordpress

`wp plugin path` should output:

/path/to/public_html/wp-content/plugins

Instead it outputs:

/path/to/public_html/wordpress/wp-content/plugins

`wp plugin list` shows me Hello Dolly and Akismet from the default wordpress file structure, instead of all the plugins I've got installed on my blog

**Comment by Ipstenu** [comment]
Just FYI, this is because PHP is a but of an idiot.

> The SERVER_NAME is not available when you run PHP from the CLI for that very same reason.
> 
> When you run PHP from the CLI, you start your own PHP intepreter that runs whatever code you passed to it, without any kind of server. So from the CLI, PHP knows nothing about your web server that you do not explicitly tell it.

http://stackoverflow.com/questions/626416/php-server-name-from-command-line

You're not doing it wrong, PHP is doing it right and it's unexpected. WP-CLI doesn't fully populate the #_SERVER array because PHP can't via command line :( Not an answer, but hopefully an explanation that helps.

**Comment by danielbachhuber** [comment]
Related #730
