### ISSUE TITLE
Generate config without possible database connection

### ISSUE THREAD

**Issue by vvondra** [wp-cli/wp-cli#787]
Currently it is not possible to run wp core config without access to the database which is being configured.

This can come in handy when preparing and installation on a server, which does not have access to the database server and WordPress will be copied to it subsequently.

I'd suggest adding a option --skip-db-check to the command

**Comment by danielbachhuber** [comment]
`wp core config` supports `--skip-check` since #1068, which will skip the check on whether the database is available.
