### ISSUE TITLE
wp: command not found

### ISSUE THREAD

**Issue by paddelboot** [wp-cli/wp-cli#811]
Embarrassing, but I get the above error message. I followed the install method here: http://wp-cli.org/

System is Ubuntu 12.04 with PHP 5.3

The install runs through fine (after asking me to add a line to my php.ini). Trying to update composer using 

php composer.phar require 'wp-cli/wp-cli=@stable' --no-dev

, I get another error:

  [RuntimeException]  
  The "--no-dev" option does not exist.

Any suggestions?

**Comment by Benqzq** [comment]
Newcomers might also want to review this for further processing this information:

https://wordpress.stackexchange.com/questions/273884/wp-cli-command-to-update-all-plugins-and-core-fails-when-executed-from-cron/275204#275204
