### ISSUE TITLE
Add support for installing WordPress.org-favorited plugins

### ISSUE THREAD

**Issue by westonruter** [wp-cli/wp-cli#827]
When installing plugins inside of the WordPress admin, you can filter the plugins to install by a WordPress.org username to list only the plugins favorited by that user. It would be handy if WP-CLI included a way to batch-install all favorited plugins, for example:

```sh
wp plugin install-favorited <username> [--force] [--activate]
```

The list of user-favorited plugins can be obtained via the WordPress.org API, e.g. https://github.com/c3mdigital/Dot-Org-Favorite-Plugins/blob/master/favorite-plugins.php#L49

This would be a handy way to quickly install the plugins you always use.

**Comment by danielbachhuber** [comment]
Another option: we could rename `wp plugin search` to `wp plugin directory [--search=<query] [--favorites=<username>]`

**Comment by shawnhooper** [comment]
I like the `wp plugin directory` approach @danielbachhuber.

**Comment by danielbachhuber** [comment]
A community command now exists for listing favorite plugins https://github.com/mikedance/wp-cli-favorite-plugins
