### ISSUE TITLE
Support stdClass in `option update`

### ISSUE THREAD

**Issue by nikolay** [wp-cli/wp-cli#852]
There are some plugins such as Edit Flow (http://editflow.org/), which store options as stdClass objects. I have a workaround to use `wp eval` to set those options, but it would be nice if `--format` add support for `--format=json-object`, for example, which would do an `(object) value` conversion to void the atypica use of `wp eval`.

**Comment by danielbachhuber** [comment]
This hasn't come up again in quite a while. We can punt.
