### ISSUE TITLE
`export --category=Foo` only works for posts

### ISSUE THREAD

**Issue by mjangda** [wp-cli/wp-cli#871]
Because of the check here: https://github.com/wp-cli/wp-cli/blob/master/php/commands/export.php#L336

We should allow it to work for any post types that support category as a taxonomy.

**Comment by danielbachhuber** [comment]
Exporter still has this problem: https://github.com/wp-cli/wp-cli/blob/master/php/export/class-wp-export-query.php#L221

**Comment by danielbachhuber** [comment]
At this point, we're not making any changes to the exporter that would further fork it from what's in core. We need to see the core ticket to some form of resolution.
