### ISSUE TITLE
`export --category=123` fails due to an `is_int()` check in `term_exists()`

### ISSUE THREAD

**Issue by nickdaugherty** [wp-cli/wp-cli#894]
When exporting with a numeric category id, the id is passed to `category_exists()` as a string...it then fails an `is_int()` check in `term_exists()`, resulting in a failed export.

`$category` should be cast to an int before sending it to `category_exists()`, if it's numeric.

**Comment by danielbachhuber** [comment]
At this point, I'm not going to make any changes to the exporter that would further fork it from what's in core.

Eventually, when the REST API endpoints have landed in core, I can see the exporter supporting the same query arguments you might pass to REST API endpoints.
