### ISSUE TITLE
PharException

### ISSUE THREAD

**Issue by bellwood** [wp-cli/wp-cli#942]
When running:

wp --info

...I get no output... If I place ini_set('display_errors',1); under the opening PHP tag and then re-run the command I get:

```
Fatal error: Uncaught exception 'PharException' with message 'phar "/usr/bin/wp" has a broken signature' in /usr/bin/wp:4
Stack trace:
#0 /usr/bin/wp(4): Phar::mapPhar()
#1 {main}
  thrown in /usr/bin/wp on line 4
```

```
PHP 5.4.23 (cli) (built: Dec 13 2013 09:28:45)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
    with the ionCube PHP Loader v4.5.0, Copyright (c) 2002-2013, by ionCube Ltd., and
    with Zend Guard Loader v3.3, Copyright (c) 1998-2013, by Zend Technologies
    with Suhosin v0.9.34-dev, Copyright (c) 2007-2012, by SektionEins GmbH
```

CentOS 5.10

**Comment by bellwood** [comment]
This is still an issue:

I've added display errors:

```php
#!/usr/bin/env php
<?php
ini_set('display_errors',1);
Phar::mapPhar();
include 'phar://wp-cli.phar/php/boot-phar.php';
__HALT_COMPILER(); ?>
...
```

PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/usr/local/bin/wp" has a broken signature' in /usr/local/bin/wp:4
Stack trace:
#0 /usr/local/bin/wp(4): Phar::mapPhar()
#1 {main}
  thrown in /usr/local/bin/wp on line 4

Fatal error: Uncaught exception 'PharException' with message 'phar "/usr/local/bin/wp" has a broken signature' in /usr/local/bin/wp:4
Stack trace:
#0 /usr/local/bin/wp(4): Phar::mapPhar()
#1 {main}
  thrown in /usr/local/bin/wp on line 4

**Comment by steinhaug** [comment]
Make sure that PHAR files are uploaded as BINARY especially if you are renaming them from PHAR to PHP as many FTP software have PHP usualy default as ASCHII. I had exact same problem and was knocking my head against the wall here before I spotted the error in my setup (that being PHP files transferring as ASCHII).
