### ISSUE TITLE
Huge performance boost using MySQL transaction

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [wp-cli/wp-cli#952]
Hello, 

When using search-replace command I've noticed dramatically performance boost while using transaction (MySQL).

I've modified wp-cli/vendor/wp-cli/wp-cli/php/commands/search-replace.php , adding following lines to get_table_list(), handle_col(), get_columns() functions:

$wpdb->query( "START TRANSACTION;" );
// function body 
$wpdb->query( "COMMIT;" );

Before applying the hack my search-replace command was executing in more than 15 minutes on more than 3k rows. After the hack it executes within less then 1min.

Please take a look at the following articles: http://stackoverflow.com/questions/14675147/why-does-transaction-commit-improve-performance-so-much-with-php-mysql-innodb
and that: http://docs.oracle.com/cd/E17952_01/refman-5.5-en/optimizing-innodb-transaction-management.html

**Comment by santagada** [comment]
I've tried the @rodrigoprimo branch on a big database (2gb) and it took 10 min without the patch and 9:30 with the patch, and I think the difference was mostly a fluctuation as I only ran the test once. I still think that there is something wrong on the patch, on theory a more coarse transactions should speed things up.

**Comment by Melmoth-the-Wanderer** [comment]
Pity i cant reproduce the environment and the database is missing. I'll keep an eye on the problem and let you know if anything happens.

**Comment by danielbachhuber** [comment]
We can re-open this issue again if it becomes actionable in the future.

Since the issue was originally opened, we've had a couple algorithm optimizations (#1261, #2304) which have led to substantial performance improvements that I'm quite happy with.
