### ISSUE TITLE
Add --force flag to 'install', 'multisite-install' and 'config' subcommand

### ISSUE THREAD

**Issue by BjornW** [wp-cli/wp-cli#964]
Make it possible to force the following commands to overwrite a previous action as if the previous action never took place by adding a --force flag to the command. 
### Why?

I'm currently using [Vagrant](http://www.vagrantup.com/) with [Ansible](http://docs.ansible.com/index.html) to automatically provision the Vagrant box. When I'm running the `vagrant provision` command multiple times I'd like the results to be exactly the same no matter how many times I will provision the box (apparently this behaviour is know as [Idempotence](https://en.wikipedia.org/wiki/Idempotence)). 

At this moment if I run `vagrant provision` for a second time with the following commands (haven't tested the other commands yet): 
- wp core config
- wp core install 
- wp core multisite install

I will get errors from wp-cli complaining of existing database tables and an existing wp-config file, which I'd consider the expected behaviour. Nonetheless I'd like to have the possibility to 'force' these commands to overwrite the previous installed database tables and wp-config as if I wanted to start fresh again, which would ensure each time `vagrant provision` is run the same outcome will be achieved with regards to wp-cli

**Comment by borekb** [comment]
Force would be nice, I am executing the config command via https://github.com/xwp/wp-cli-ssh and having to run two separate commands just complicates things. Hopefully this could be reconsidered.
