### ISSUE TITLE
define is_admin() or WP_ADMIN at plugin install

### ISSUE THREAD

**Issue by mastef** [wp-cli/wp-cli#984]
I stumbled recently over a few plugins that only include their plugin update&installation&activation code when is_admin() returns true, or WP_ADMIN is set to true.

This is of course a hassle and instead of using the following :

``` sh
sudo -u www-data sed -i 's|<?php|<?php define("WP_ADMIN", true);|g' /var/www/wp-config.php
sudo -u www-data wp --path=/var/www/ plugin install plugin.zip --activate
sudo -u www-data sed -i 's|define("WP_ADMIN", true);||g' /var/www/wp-config.php
```

I was wondering if wp-cli is able to take care to adjust the wp-config.php file automatically ( e.g. like with the

``` sh
wp core  --extra-php <<PHP
define( 'WP_ADMIN', true );
PHP
```

functionality, but with an existing wp-config.php ) and/or set itself as admin during a plugin installation/activation?

Especially to properly get rid of the WP_ADMIN line afterwards, as some plugins alter the wp-config later on, and overall this not being a nice solution.

**Comment by garex** [comment]
> But defining it only on plugin activation is an interesting suggestion.

@scribu so what prevents us from doing this?

**Comment by danielbachhuber** [comment]
@garex This is an extremely old ticket, and @scribu is no longer involved with the project.

Please [review the support policy](http://wp-cli.org/#support).
