### ISSUE TITLE
W3 Total Cache command doesn't work

### ISSUE THREAD

**Issue by johnpbloch** [wp-cli/wp-cli#99]
`wp total-cache` returns this error:

```
Error: 'total-cache' is not a registered wp command. See 'wp help'.
```

This is because, in class-wp-cli.php, `WP_CLI::run_command` uses the command to look for a file. So running the command `wp total-cache` causes it to look for `'/commands/community/total-cache.php'`, which does not exist. Changing the command to `wp w3-total-cache` (to match the filename) results in the same error, since w3-total-cache.php adds the command `total-cache`, not `w3-total-cache`.

Either changing the file name to `total-cache.php` or the command name to `w3-total-cache` fixes the issue.

**Comment by mkormendy** [comment]
@scribu why was this closed?
