### ISSUE TITLE
PHP Fatal error:  Cannot redeclare wp_unregister_GLOBALS() 

### ISSUE THREAD

**Issue by tchwpkgorg** [wp-cli/wp-cli#992]
I'm not able to run wp-cli on *some* websites.

Running Wordpress 3.8.1 with wp-cli 0.13.0 and 0.14.0-beta.

I've checked the FAQ entry about a similar problem, and reported issue #288, but they don't seem to apply in this case.

Tried disabling the plugins, but it didn't help.

As far as I can see, it has something to do with the database.

Merely substituting these values with the ones from a website where wp-cli is working is enough to make wp-cli run:

define('DB_NAME', 'db_name');
define('DB_USER', 'db_user');
define('DB_PASSWORD', 'pass');

Any ideas how to debug this further?

**Comment by samtuke** [comment]
I also have this issue with Wordpress 4.1.

**Comment by danielbachhuber** [comment]
@samtuke Can you share the contents of your `wp-config.php`, minus any secrets?

**Comment by bgelfand** [comment]
I figured out it was a poorly made plugin, it was doing require_once($root.'/wp-settings.php'); and I suspect it may be the cause for other people out there. Look for if wp-settings.php is being required anywhere else but in the core, as it was at least the cause for my troubles.

**Comment by danielbachhuber** [comment]
I've created a new canonical issue to point people to: #1631
